### ISSUE TITLE
monkeyslockette ajtó védési hiba

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#1]
Ha egy ajtó le van védve [Lock] táblával, és a block alatta nincs levédve, a block kiütésével ki lehet szedni az ajtót is.

![2015-11-28_11 44 37](https://cloud.githubusercontent.com/assets/16057404/11451410/94a9cc30-95c5-11e5-9322-6d8138677df3.png)
![2015-11-28_11 44 46](https://cloud.githubusercontent.com/assets/16057404/11451411/94d373fa-95c5-11e5-8fc1-83be8c8fc771.png)

**Comment by andris155** [comment]
https://github.com/mcmonkey4eva/monkeyslockette/issues/3

**Comment by UDPSendToFailed** [comment]
Lol, ezt nem is láttam :D

**Comment by andris155** [comment]
Remélhetőleg a fejlesztő minél hamarabb javítja majd.

**Comment by andris155** [comment]
Ideiglenes megoldás: Védd le a területet zmoddal.

**Comment by andris155** [comment]
Lehet új védési plugin lesz majd, de még gondolkozok, hogyan oldjam meg.

**Comment by andris155** [comment]
Elvileg javítva:
- monkyslockette cserélve deadboltra.
