### ISSUE TITLE
Robbanó reaktor

### ISSUE THREAD

**Issue by Viktor1969TOC** [andris155/TheOld-Crafters#1000]
Már 2 reaktorom felrobbant mikor átváltotam mert nekem plutonium Kell (benne volt az uranium a coolant cell es mikor váltotam egybõl robbant) Remélem a 2 reaktorom visszakapom nem olcsó mulatság az a 2 reaktor Ami belerobbant a bugba!

**Comment by andris155** [comment]
Ez nem hiba és nem fejlesztés!
