### ISSUE TITLE
*új warp ötlet*

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#1001]
lehetne külön /warp újszabad-tájak warp, mind a rendes tájak warp

**Comment by poprundelHD** [comment]
Ez mondjuk jó ötlet is lenne,csak az újszabad warpnak nincs olyan beosztása,illetve biomeja mint egy sima világnak. Több olyan különbözőnek kinéző biome van,ami igazából ugyanaz,csak más generálás.  Van olyan biome,aminek nagyon rövid része van,és nem férne el példának... Példának mondjuk a "jégföld" tájspawnja(vagy mi :D) Szóval érted,ennek nincs értelme,de jó lenne ha az újszabad nem lenne olyan mint amilyen most.
