### ISSUE TITLE
MineMarket elírás (#2)

### ISSUE THREAD

**Issue by Mousking** [andris155/TheOld-Crafters#1006]
Üdv, találtam pár hibát a MineMarketben.

1.  PC Survival tiltás feloldásánál Survvial van írva Survival helyett.

![screenshot_20171017-172821](https://user-images.githubusercontent.com/25939300/31674375-f954c642-b361-11e7-85b0-bda6988d3931.png)

2.  PC Survival némítás feloldásnál Survvial van írva Survival helyett, és emellett "az némítás" van írva "a némítás" helyett
![screenshot_20171017-172842](https://user-images.githubusercontent.com/25939300/31674543-57021542-b362-11e7-8ec7-c240a17a9698.png)

3. A többi PC Survival büntetés feloldásnál is a Survival helyett Survvial van írva.

![screenshot_20171017-172917](https://user-images.githubusercontent.com/25939300/31674945-872b4ef4-b363-11e7-8767-9ddb3a047f51.png)
![screenshot_20171017-172943](https://user-images.githubusercontent.com/25939300/31674951-8fe89bbe-b363-11e7-859c-06278c580a3c.png)

4. PC Savsziget némítás feloldásnál "az némításod" van írva "a némításod" helyett.

![screenshot_20171017-173001](https://user-images.githubusercontent.com/25939300/31675173-1e51a7a6-b364-11e7-90b2-c1ffe637cd00.png)

5. PE Survival némítás feloldásnál "az némításod" van írva "a némításod" helyett.

![screenshot_20171017-173059](https://user-images.githubusercontent.com/25939300/31675319-84441a12-b364-11e7-86eb-56def1f21e76.png)

6. PE SkyPvP némítás feloldásnál "az némításod" van írva "a némításod" helyett.

![screenshot_20171017-173139](https://user-images.githubusercontent.com/25939300/31675355-aecc9a20-b364-11e7-812a-baf26a73b601.png)

Valamint a némítás feloldásoknál a második mondat elején is ott az elírás.

7. Minden büntetés feloldás menüpontban "eltarhat néhány percig" van írva "eltarthat néhány percig" helyett.

![screenshot_20171017-173334](https://user-images.githubusercontent.com/25939300/31675459-fc5a381a-b364-11e7-8adc-ffa3c035b021.png)
![screenshot_20171017-173351](https://user-images.githubusercontent.com/25939300/31675469-0436b2a2-b365-11e7-8b98-2b377188d0a9.png)
![screenshot_20171017-173401](https://user-images.githubusercontent.com/25939300/31675477-0dd58a4a-b365-11e7-98fd-54cc1245e1f9.png)
![screenshot_20171017-173413](https://user-images.githubusercontent.com/25939300/31675484-131e0f2c-b365-11e7-9f99-a29e23114e40.png)

**Comment by andris155** [comment]
javítva

**Comment by andris155** [comment]
330 OCD
