### ISSUE TITLE
Sf. Surv. Android PC

### ISSUE THREAD

**Issue by Viktor1969TOC** [andris155/TheOld-Crafters#1007]
Nálam nemtudom kinél még, de az Empowered Android (Fisherman) Mindig átbuggol egy fejj neve is az lesz, hogy: CSCoreLib feje..

**Comment by Kelvin172** [comment]
Már tudunk róla, folyamatos hiba szokott lenni, ilyenkor szólj egy adminnak, vagy a tulajnak, hogy cserélje ki neked, az elbugoltat odaadva neki.

**Comment by andris155** [comment]
Holnaptól elvileg jó lesz. De majd nyissatok újat ha mégsem!

**Comment by andris155** [comment]
330 OCD
