### ISSUE TITLE
Építész szerver WE grafikus hiba.

### ISSUE THREAD

**Issue by LambWolf** [andris155/TheOld-Crafters#1008]
Bármilyen parancsot használva a WE félig, vagy "semmit" nem csinál. A blockokat lerakja viszont azok nem frissülnek ( jelennek meg) ameddig a pályát be nem töltjük újra, ami egy elég idegesítő dolog. A //set-et duplán kell használni hogy jó legyen viszont ezt minden parancsnál nem lehet elkövetni. És ha nincs fent senki akkor még a TP-zés is nehéz.

**Comment by andris155** [comment]
Már jó lett?

**Comment by poma123** [comment]
Igen, jó.
