### ISSUE TITLE
Achivment Bug

### ISSUE THREAD

**Issue by Sherox** [andris155/TheOld-Crafters#1011]
Mindegyik Achivmentet 2x ír ki a chat-re:
![image](https://user-images.githubusercontent.com/30244296/31861164-6c88f0b0-b728-11e7-9404-541073090822.png)

-./Sherox/.-

**Comment by Mousking** [comment]
Nemcsak kétszer, végtelenszer is lehet, 10mp-t kell várni az egyik munkavégzéstől a másodikig.

**Comment by andris155** [comment]
most jó?

**Comment by poma123** [comment]
Elvileg igen

**Comment by andris155** [comment]
204 OCD

**Comment by poma123** [comment]
Igen, most már jó.
