### ISSUE TITLE
Privát üzenet

### ISSUE THREAD

**Issue by Mousking** [andris155/TheOld-Crafters#1013]
A PC Survival szerveren ugye a privát üzenetek megjelennek a Jobb felső sarokban, mint mikor célt teljesítünk. Viszont ha valaki nem szeretné látni a privátokat, sem a chatet, és ezért kikapcsolja a Chat megjelenítését, akkor is látja a jobb felső sarokban, amit írnak neki.

**Comment by andris155** [comment]
kikapcsolva
