### ISSUE TITLE
MurderMystery A "visszaszámlálás" nem fér ki a scoreboardon

### ISSUE THREAD

**Issue by poma123** [andris155/TheOld-Crafters#1015]
![image](https://user-images.githubusercontent.com/25465545/31897344-5f27bc96-b816-11e7-8151-b274e6e53b70.png)
A "visszaszámlálás" nem fér ki a scoreboardon

**Comment by andris155** [comment]
javítva, holnap betölt

**Comment by andris155** [comment]
204 OCD
