### ISSUE TITLE
PC SF. Input node

### ISSUE THREAD

**Issue by Viktor1969TOC** [andris155/TheOld-Crafters#1016]
Mai nap beléptem és a gyárakba bepakoltam Az anyagot (kö stb.) És néztem miert nem szedi ki Az alapanyagot mikor még akkartam nyitni a nodot nem engedte kiütöttem es CSCoreLib fejét kaptam meg.

**Comment by andris155** [comment]
Sajnos előfordul ilyenkor újra le kell rakni. :/ Megoldás nincs rá. De a fejlesztő oldalán jelentve van.
