### ISSUE TITLE
Murder Bugok.

### ISSUE THREAD

**Issue by Sherox** [andris155/TheOld-Crafters#1017]
Mikor valaki beírja azt hogy /murder leave akkor néha Ki kickel legközelebb meg tempban-t ad.

Tab,neve mellett is eltűnik a prefix:
![asdsa](https://user-images.githubusercontent.com/30244296/31946178-6d568fca-b8d1-11e7-82d9-4cbfc4bcbb8c.png)

Minden Felszerelés Elveszik játék után.
(Ki kéne táblázni/mint Survival Games-en nem enged be felszerelést tartalmazó inventoryval.)

-./Sherox/.-

**Comment by andris155** [comment]
javítva. Sajnos a tab-bot nem lehet.

**Comment by andris155** [comment]
330 OCD
