### ISSUE TITLE
Login szerverre kérés

### ISSUE THREAD

**Issue by rikmind** [andris155/TheOld-Crafters#1018]
Szia Andris!
Azt szeretném kérdezni, hogy Login szerveren belül van e olyan rang, hogy moderátor? És hogy kaphatnánk-e, ha van? Csak, hogy rombolni ne lehessen, hanem ha kell, akkor onnan is ki tudjunk tiltani játékosokat, ha komoly szerver szidást csinálnak. Mint amilyen tegnap is volt például. Mert tegyük fel, hogy S1-ről kitiltjuk, de Lobbyban, illetve Login szerveren meg folytatják, akkor legalább tudnánk intézkedni. 
Előre is köszi a választ!
Rikmind

**Comment by andris155** [comment]
Szia!
Ott nincs ilyen rang.
