### ISSUE TITLE
Carbonado Edged Furnace

### ISSUE THREAD

**Issue by baumannkitti** [andris155/TheOld-Crafters#1021]
Carbonado Edged Furnace bebugolt és elkezdett faszenet dobálni kifelé, de csak 2 db faszén volt benne összesen és 16x64 db-ot dobott ki. Hiába próbáltuk nem engedte megnyitni. Miután kiütöttük rendesen működött, de volt már vele máskor is hiba, de akkor csak annyi, hogy egy sima furnace sebességével sütött.

**Comment by andris155** [comment]
Videó kellene erről.
