### ISSUE TITLE
Murder Mystery lagg

### ISSUE THREAD

**Issue by AwesomeFM** [andris155/TheOld-Crafters#1023]
Nem tudom mennyire mondható bugnak, de az új minigame a Murder Mystery rettenetesen laggol, és sok esetben szinte játszhatatlan.

**Comment by andris155** [comment]
FPS?

**Comment by AwesomeFM** [comment]
Nem, FPS, net. De néha nagyon durva.

**Comment by andris155** [comment]
Több információ kellene erről, hogy mikor. Meg esetleg egy videó.
