### ISSUE TITLE
2 Ember Pc.

### ISSUE THREAD

**Issue by Viktor1969TOC** [andris155/TheOld-Crafters#1027]
MrDinamit88 on mutatva. Leraktam a játékot tálcára és ez történt:

![2017-10-26_14 06 09](https://user-images.githubusercontent.com/32791069/32051968-f6dbf812-ba56-11e7-8739-96f77ea1ff26.png)

**Comment by HELLCATGHOST** [comment]
Slimefun Fejlesztő úrfi : "Ilyen hiba nem létezik. "

2017. okt. 26. 14:07 ezt írta ("Viktor1969TOC" <notifications@github.com>):

**Comment by andris155** [comment]
Volt már jelentve. Sajnos nem tudok vele mit csinálni.
