### ISSUE TITLE
Telkek

### ISSUE THREAD

**Issue by poprundelHD** [andris155/TheOld-Crafters#1028]
Hali Andris!

Több visszajelzés érkezett,hogy az sf cuccok napról-napra tünnek el érthetetlen okokból. Teszteltem, ez azért van mert az sf nincsen eléggé levédve telek világon,így mondjuk a reactorokba,vagy ehhez hasonló sf-es tárgyakba bele lehet nyúlni, így cuccot is ki lehet lopni, és mivel a CoreProtect nem működik sf-en, így kideríteni sem lehet ki volt az. Ha megkérhetnélek rá(Persze csak ha képes vagy erre), meg tudnád egy picit bütykölni a telkeket,vagy utána járni ennek a dolognak? Választ előre köszi. 
*poprundelhd*

**Comment by andris155** [comment]
A Slimefun nem támogatja a PlotSquaredet.
