### ISSUE TITLE
Kreatív inventory bug

### ISSUE THREAD

**Issue by Mousking** [andris155/TheOld-Crafters#1029]
Üdv. Ha egy lépcsőn ülve gmsben kilépünk, miközben a fejünk felett kitörnek egy ládát, és a törés pillanatában lelépünk, majd visszalépünk és gmcbe váltunk, a tárgyak felvehetőek.

**Comment by poma123** [comment]
Videó a **[bugról](https://www.youtube.com/watch?v=IKv-yd0a8eY&feature=youtu.be/)**

**Comment by andris155** [comment]
Javítva!
Köszönjük a hibajelentést!

**Comment by andris155** [comment]
330 OCD
