### ISSUE TITLE
Szabályzat hozzáadás

### ISSUE THREAD

**Issue by MrZeroTOC** [andris155/TheOld-Crafters#103]
Új szabályzat bevezetése, mely írásban nincs -még- foglalva, viszont szóban már régóta használjuk.
A szabály: Levédetlet területért felelősséget nem vállal a szerver.
Erre a szabályra tudunk hivatkozni, ha azt mondják, hogy a levédett ládából kiszívták tölcsérrel a cuccokat.

MrZero

**Comment by andris155** [comment]
A kérés elutasítva.
Ez a szabály azért nem jó, mert ha tudják, hogy szabad lopni levédetlen területről, még rosszabb lesz a táj, és több panasz is lesz.
