### ISSUE TITLE
Murder bugok

### ISSUE THREAD

**Issue by Mousking** [andris155/TheOld-Crafters#1030]
-Murderezés közben a gyilkos meg tudja kapni áldozatainak a fejét, és fel tudja venni az inventoryjába.

-Ha valaki becsatlakozott a pálya Lobbyjába, azt a Murder warpon a pálya táblája nem jelzi ki.

-Murderben halál után ha az első slot gombját megnyomjuk, mivel gm 3ban vagyunk, a játékosok után tudunk nézni, vagy akár azt is, hogy egy-egy Staff mit csinál éppen.
![2017-10-26_21 40 25](https://user-images.githubusercontent.com/25939300/32073361-1434364c-ba96-11e7-83bf-432858f5152d.png)
(A képen épp gm3-ban teleportoltam)

-Amikor a játék kiírja hogy ,,A gyillkos megkapta a kardját" , ott a gyilkos kettő ,,l" betűvel van írva.

-Ha Detektív szerepet oszt a játékosnak a plugin, akkor a Rangja ugyanúgy Ártatlanként jelenik meg a képernyő közepén, és nem Detektívként. Viszont a képernyő oldalán Detektívet ír.

**Comment by andris155** [comment]
A fejes szerintem teljesen mindegy mivel ott más táska van. A többi javítva.

**Comment by andris155** [comment]
204 OCD
