### ISSUE TITLE
Murder Scoreboard

### ISSUE THREAD

**Issue by poma123** [andris155/TheOld-Crafters#1031]
Menet után ott marad a scoreboard a képernyő szélén
Észrevette: ***baumannkitti***

**Comment by poma123** [comment]
![image](https://user-images.githubusercontent.com/25465545/32122978-ce8066f2-bb62-11e7-9aee-d39a0c05eb12.png)

**Comment by TamasB14** [comment]
Nekem is ugyan úgy márt én is észre vettem

**Comment by andris155** [comment]
A plugin hibája. Írtam a fejlesztőnek.
