### ISSUE TITLE
Murder

### ISSUE THREAD

**Issue by poprundelHD** [andris155/TheOld-Crafters#1037]
A Murder kezdeténél a Detektív rangja el van írva Ártatlanná, így bele lehet kavarodni.

**Comment by Mousking** [comment]
#1030

**Comment by andris155** [comment]
Javítva

**Comment by andris155** [comment]
https://github.com/andris155/TheOld-Crafters/commit/6a3367c04cdaae32476356a180ce419caf5ffdf2
