### ISSUE TITLE
Telek bug

### ISSUE THREAD

**Issue by ImorePresents** [andris155/TheOld-Crafters#1039]
Üdv!

A survival szerveren találtam egy bugot, a telkeknél.
Mikor veszel egy telket, a tábla, mely a telek tulajdonosát írja, lebugol/leesik róla.
![2017-10-29_00 17 29](https://user-images.githubusercontent.com/33187072/32139020-ced49088-bc3e-11e7-9f3c-54a021270c77.png)

**Comment by andris155** [comment]
Elvileg nem minden teleknél van így.

**Comment by ImorePresents** [comment]
MrZero-val próbáltuk.
Valamelyik teleknél van tábla, valamelyiknél nincs.

**Comment by andris155** [comment]
Elvileg holnaptól jó lesz. Köszönjük a hibajelentést.
