### ISSUE TITLE
Grappling Hook Bug

### ISSUE THREAD

**Issue by TamasB14** [andris155/TheOld-Crafters#1040]
CSináltam 2 darabot és az eggyiket messzire eldobtam egy "ház" felett és nem adott semmi löketet és eltünt és a 2. grappling hookot nemtudtam eldobni aztán . kiléptem és visszaléptem akkor se működik ráadásul az 1. grappling hook  Lasszó lett és az "eredetit" az a másodikat nemtudom én használni de más tudja.

**Comment by andris155** [comment]
A hibáról tudunk, de sajnos inaktív a Slimefun fejlesztő így nem tudni lesz-e valaha javítva.

**Comment by andris155** [comment]
https://github.com/TheBusyBiscuit/Slimefun4/issues/253
