### ISSUE TITLE
kreatív silverfish bug

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#1041]
minden kőtéglaí/kő féléhez odavan írva hogy silverfishel pl.: kőtégla blokk silverfishel ezért nem lehet letenni kreatívban

**Comment by andris155** [comment]
Nem lehet, mivel lehetne silverfish-t kreálni vele.

**Comment by skrisz0101** [comment]
nem az a baj, az a baj hogy nincs kő/kőtégla blokk silverfish nélkül

**Comment by andris155** [comment]
Pedig van.
