### ISSUE TITLE
Andris félreértetted a silverfishest

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#1044]
nem az a baj hogy nem lehet letenni a pl silverfishes kőtéglát, hanem az, hogy nincs silverfissh nélküli kőégla. ugyan ez a kőnél,undás kőnél stb

**Comment by skrisz0101** [comment]
bocsánatot kérek, vaksi voltam ás nem láttam.... x ':D

**Comment by andris155** [comment]
Ott a kőtégla a menüben. A Java Edition-ben nem is lehet módosítani azt a menüt a szerver oldalról. Tehát benne kell lennie.
