### ISSUE TITLE
PaintBall Kilépés üzenet hiba

### ISSUE THREAD

**Issue by poma123** [andris155/TheOld-Crafters#1045]
Amikor valaki kilép a meccsből, így írja ki a PB:
![image](https://user-images.githubusercontent.com/25465545/32187395-3564835a-bda5-11e7-8629-a53de83ed6ed.png)

**Comment by andris155** [comment]
Javítva!
Köszönjük a hibajelentést!

**Comment by andris155** [comment]
204 OCD
