### ISSUE TITLE
Privát üzenet fordítási hiányosság

### ISSUE THREAD

**Issue by AwesomeFM** [andris155/TheOld-Crafters#1046]
Ha egy AFK emberre írunk rá privátban az üzenet amit kiad angol.

![2017-10-30_19 57 44](https://user-images.githubusercontent.com/18013708/32190054-d5ec00ee-bdac-11e7-8624-ab1b059f1cde.png)

**Comment by andris155** [comment]
Javítva!
Köszönjük a hibajelentést!

**Comment by andris155** [comment]
204 OCD
