### ISSUE TITLE
Pistonnal blokk áttolás end határánál

### ISSUE THREAD

**Issue by poma123** [andris155/TheOld-Crafters#1048]
Az end határánál pistonnal át lehet tolni blokkokat.

**Comment by poma123** [comment]
![image](https://user-images.githubusercontent.com/25465545/32195557-e1506126-bdbd-11e7-8a50-b623cf8da944.png)

**Comment by andris155** [comment]
A fő célja a határnak, hogy te ne juss át. Talán jobb is, hogy a piston-t nem nézi, mivel így kevesebb erőforrást használ. Az, hogy pár játékos meg át tol pár blokkot az meg nem baj szerintem.
