### ISSUE TITLE
Smeltery Pickaxe bug

### ISSUE THREAD

**Issue by Mousking** [andris155/TheOld-Crafters#1049]
Ha egy Shulkert Smeltery Pickaxe segítségével kiszedünk, és volt a Shulkerben cucc, az nem marad benne a kiszedés után.

**Comment by andris155** [comment]
Gondolom nem támogatja az NBT-jét. Sajnos ez hiányosság nem pedig hiba.

**Comment by andris155** [comment]
https://github.com/TheBusyBiscuit/Slimefun4/issues/481
