### ISSUE TITLE
Láthatatlanság

### ISSUE THREAD

**Issue by poprundelHD** [andris155/TheOld-Crafters#1050]
Akik láthatatlanság bájitalt innak,azoknak olyan,mintha vanishben lennének(Nincsenek tabon,nem lehet rájuk írni,stb...). Ebben az érdekes,hogy még eddig nem volt ilyen, lehetséges hogy az essentials túlságosan kompatibilitis az Essentials-al,vagy nem tudom.
*poprundelhd*

🗡 Bug megtalálója: wenix 🗡

**Comment by andris155** [comment]
Sajnos a Murder miatt van így. Nem teljesen hiba, igazából nem valami jól oldotta meg a fejlesztő. A hibát többen jelentették előbb is így sajnos nem tudok OCD-t adni.
