### ISSUE TITLE
Minemarket OCD utalási hiba. 

### ISSUE THREAD

**Issue by PreczPerec** [andris155/TheOld-Crafters#1051]
A minemarketben, amikor utalni szeretnék más játékosnak OCD-t, akkor "Belső rendszerhibát" észlel. Akárhányszor próbáltam ugyanazt írta ki. 
![github](https://user-images.githubusercontent.com/31320050/32223201-b5162666-be3c-11e7-8528-e0d29094abf9.png)

**Comment by andris155** [comment]
Ki kell lépnie akinek küldöd.

**Comment by PreczPerec** [comment]
Előbb megpróbáltuk wenixel, de akkor sem sikerült. :(

**Comment by Levytheking** [comment]
Rosz helyre írtad az OCD-t és a nevet. Cseréld meg és jó lesz. Nekem is ez volt
