### ISSUE TITLE
Cargo optimalizálása

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#1054]
ha kilenne alapból kapcsolva a cargo villogása és nem lehetne bekapcsolni, nem lenne jobb a szervernek?
lag ügyileg

**Comment by andris155** [comment]
fps-ben biztos, hogy tps-ben azt nem tudom.

**Comment by Mousking** [comment]
Szerintem is felesleges lagforrás, még hacsak fps-ben is, de 5 blockot le tud mindenki számolni, hogy a következő connectort hova tegye ahhoz, hogy kapcsolódva legyen.

**Comment by andris155** [comment]
Ráfogok nézni majd a kódra mindenképpen.

**Comment by andris155** [comment]
Megnéztem a kódot egyelőre inkább nem akarok beleírni, mert valószínűleg hibát is okoznék bele.
