### ISSUE TITLE
Börtön parancstiltás hiányosság

### ISSUE THREAD

**Issue by Mousking** [andris155/TheOld-Crafters#1055]
A PC Survival szerver börtönében nincs tiltva a /murder join <pálya> parancs. Ha így csatlakozunk egy arénába, ahol az induláshoz elegendő játékos van, akkor ugyanúgy a cellában maradunk, ezzel a Murderen "halhatatlanságot" szerezve. Nem volt időm tesztelni, de szerintem az sg join és a pb join is megy (a parancsot tesztelni volt időm, viszont flyom volt a börtönben, így nem tudtam megnézni, hogy csatlakozik-e az sghez/pbhez).

**Comment by Mousking** [comment]
![2017-10-31_18 04 39](https://user-images.githubusercontent.com/25939300/32291053-380231fa-bf3c-11e7-8982-d28996fae15a.png)
![2017-10-31_18 09 37](https://user-images.githubusercontent.com/25939300/32291057-384fa4a8-bf3c-11e7-8410-dbd3fbab1aa3.png)

**Comment by MrDinamit88** [comment]
xD

**Comment by Sheep04** [comment]
Noice

**Comment by andris155** [comment]
javítva
