### ISSUE TITLE
SlimeFun spawner - mob spawnolás plot-on

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#1056]
SlimeFun-os spawner működik telken, és ha a mob átmegy más telkére, nem lehet megölni.

![2017-11-01_14 58 55](https://user-images.githubusercontent.com/16057404/32278230-55e64a98-bf15-11e7-976a-53f973b567d3.png)

**Comment by andris155** [comment]
Persze, hogy nem lehet mivel a mobok védettek a telkeken.
