### ISSUE TITLE
Játékos ijesztgetés murderen

### ISSUE THREAD

**Issue by TamasB14** [andris155/TheOld-Crafters#1057]
murderen nézőként ha ütögetünk egy játékost hallani azt a suhintás hangot és a játékosokat ezzel meg lehet zavarni

**Comment by andris155** [comment]
XD. Hát erre nincs megoldásom sem.

**Comment by andris155** [comment]
A plugin fejlesztő szerint a gm 3 lenne, de az meg teljes gm 3 módot ad. xd
