### ISSUE TITLE
Murder-re ötlet

### ISSUE THREAD

**Issue by TamasB14** [andris155/TheOld-Crafters#1058]
Egy olyan ötletem van hogy egy olyan uj játék mód lenne hogy mindenki gyilkos lenne és mindenkinek lenne egy célpontja egy "térképen" a skine és felette a neve és lenne 2 detektiv aki csak akkor lőheti le a gyilkost ha a kard kezében van vagy ha elrakja a kardot 5 másodpercig még megölheti a gyilkost de gyilkos nem ölhet detektivet.

**Comment by andris155** [comment]
Nem tudom átírni a plugin-t, mivel zárt kódú. De köszönjük azért!
