### ISSUE TITLE
Belépés szöveg hiba

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#1060]
![image](https://user-images.githubusercontent.com/16057404/32312515-7ba54d18-bf9e-11e7-84dc-9e69829e30b3.png)

![image](https://user-images.githubusercontent.com/16057404/32312537-a12bb28e-bf9e-11e7-97cd-b2576f3691e4.png)

A kilépés se jó:

![image](https://user-images.githubusercontent.com/16057404/32313088-45bdeb80-bfa1-11e7-90c9-db2ffa0c1897.png)

**Comment by Sherox** [comment]
# Szia

### Tudunk a hibáról kb reggel 8óta.

Javítás alatt van.

-./Sherox/.-

**Comment by andris155** [comment]
javítva
