### ISSUE TITLE
Szerver Hiba

### ISSUE THREAD

**Issue by Paxelcfg** [andris155/TheOld-Crafters#1061]
Szia ime pár hiba:
-----------------------[Belépés]-----------------------
![hiba1](https://user-images.githubusercontent.com/24989931/32320136-7fc56488-bfc5-11e7-9cf5-bed8baea9f14.png) 
![hiba2](https://user-images.githubusercontent.com/24989931/32320166-9148d3ac-bfc5-11e7-86d6-a0ab3cda5da1.png)
Lobbyban is meg a szervereken is ezt írja.
-----------------------[tell/m]-----------------------
Mikor írni szeretnék /tell ben Ezt írja:
![hiba3](https://user-images.githubusercontent.com/24989931/32320295-ea3f5bd4-bfc5-11e7-836a-8aa532ac522a.png)
-----------------------[Smiley]-----------------------
![hiba4](https://user-images.githubusercontent.com/24989931/32320790-96d3cba4-bfc7-11e7-94c6-7e53245ea38d.png)
-----------------------[Csunya szó/Hirdetés]-----------------------
![hiba6](https://user-images.githubusercontent.com/24989931/32320855-cdacbd0c-bfc7-11e7-8fb6-fe561b29fef5.png)
![hiba7](https://user-images.githubusercontent.com/24989931/32320891-ff7e1a56-bfc7-11e7-937b-c5fd9eac62e7.png)
(Persze az IP Egy semleges.)
-----------------------[Caps/flood]-----------------------
![hiba7](https://user-images.githubusercontent.com/24989931/32321073-947114d8-bfc8-11e7-99f9-d77073c6ab29.png)
![hiba10](https://user-images.githubusercontent.com/24989931/32321097-aab584e0-bfc8-11e7-9be8-316885657f61.png)
-----------------------[Sav sziget]-----------------------
Nem lehet Szigetet létre hozni :(
![hiba8](https://user-images.githubusercontent.com/24989931/32321315-693f7c68-bfc9-11e7-83b3-b82659f40353.png)

**Comment by Sherox** [comment]
# Szia
### Tudunk a hibáról reggel 8óta.
Javítás alatt van.


-./Sherox/.-

**Comment by andris155** [comment]
Elméletileg most jól írja nem?

**Comment by andris155** [comment]
javítva
