### ISSUE TITLE
Murder Hiba!

### ISSUE THREAD

**Issue by poma123** [andris155/TheOld-Crafters#1062]
Ha valaki beírja a /warp Murder warpon, hogy /lc c, majd utána kreatívba tárgyakat kivesz magának, utána belép egy arénába a táblával, ott túlélőbe teszi őt a plugin, de utána kilép, és átteszi magát túlélőbe, akkor azok a dolgok amik kreatívba nála voltak, átkerülnek a túlélő inventoryba

**Comment by GhostTriggerGT** [comment]
Elvileg javítva. Tesztelés szükséges!

**Comment by poma123** [comment]
Ghosti letiltotta az összes lehetséges krea commandot a helyszínen, és mikor odawarpol valaki, túlélőbe teszi.
