### ISSUE TITLE
Murder Hiba 2

### ISSUE THREAD

**Issue by poma123** [andris155/TheOld-Crafters#1063]
Mindig buggos, és nem lehet megölni egymást, ha a Detektív (vagy aki felveszi) és a Gyilkos marad a végére

![image](https://user-images.githubusercontent.com/25465545/32344539-7e16f8f8-c007-11e7-8eb5-d57bbb3604de.png)

**Comment by andris155** [comment]
?

**Comment by poma123** [comment]
Végül a gyilkos tudja a detektívet megölni, ha kilövi az íjat. Mikot ez megtörtént, a fenti kép fogadott.

**Comment by poma123** [comment]
A party okozta. #1104
