### ISSUE TITLE
murder/pb fejlelsztés

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#1064]
kaphatna $-t az a játékos, amelyik legtovább bírta murderben illetve pb-n(itt az egész csapat), mint SG-n,

**Comment by andris155** [comment]
és mennyit adjon a murder vagy mit adjon?

**Comment by HELLCATGHOST** [comment]
A győztes kaphatna 2000-et.

2017. nov. 3. 12:45 ezt írta ("Marczinkó András" <notifications@github.com

**Comment by andris155** [comment]
beállítva, sajnos a pb nem támogatja.

**Comment by andris155** [comment]
254 OCD
