### ISSUE TITLE
Minemarket

### ISSUE THREAD

**Issue by HELLCATGHOST** [andris155/TheOld-Crafters#1065]
**# Szia Andris!**
Minap keresgéltem minemarkethez hasonló pluginokat,és találtam az **Enjin**-nek 1 
"**DonationCraft**" pluginját,ami egészen letisztult,szép webadmint ad.
Illetve a InGame-Shopja, ahonnan elméletileg lehet vásárolni stb.
Be lehet állítani hogy csak Forinttal fizessenek, de ahogy láttam a listát,lehet bőven mivel fizetni.:D
(van alkalmazása telefonra is)
Szerintem érdemes próbát,jobbnak látszik mint a minemarket.
Link az **Enjin**-hez: [[Katt]](https://www.enjin.com/features)

>[Az **Enjin** árazásai:](https://www.enjin.com/pricing)

> [**Enjin app**](https://play.google.com/store/apps/details?id=com.enjin.mobile&ah=nf511xXtiOhQjkWRcDW2rhQrpZA) 

-------------------------------------------------------------------------------------------------------------------
**# Buycraft**
Ezt a plugint,illetve webshopot sok eredetis szerver is használja, ez után nem nagyon néztem utána,
nem lehet rossz,ha eredetis szerverek használják és a spigot oldalon is kint van.
Link a **Buycraft**-hoz: [[Katt]](https://www.buycraft.net/features/)

>[A **BuyCraft**-nak árazásai](https://www.buycraft.net/pricing)

**Comment by andris155** [comment]
Egyelőre jó nekem a MineMarket.
