### ISSUE TITLE
Szerverre szavazás

### ISSUE THREAD

**Issue by AnnaMastersong** [andris155/TheOld-Crafters#1066]
Lehet, hogy csak az én gépem lassú, de a második szavazó link (http://topg.org/Minecraft/in-414536) nem tölt be. Mármint igazolom, hogy nem vagyok robot, beírom a felhasználó nevem, majd beküldöm a szavazatot, de csak forog az a kis köröcske középen, órákon át... A segítséget előre is köszönöm.

**Comment by andris155** [comment]
![kepkivagdas](https://user-images.githubusercontent.com/8324198/32392324-7fd10d72-c0d5-11e7-8f74-c12083511ffe.PNG)
![kepkivagas](https://user-images.githubusercontent.com/8324198/32392327-81d98e50-c0d5-11e7-9379-cdff5c4b596b.PNG)

**Comment by andris155** [comment]
Adblockot nem szerencsés használni ha használsz lehet az tiltja. Nekem tökéletesen működik.
