### ISSUE TITLE
Kreatív védelem - savsziget

### ISSUE THREAD

**Issue by poma123** [andris155/TheOld-Crafters#1068]
Helló. Az a gond, hogy mivel a kreatív védelem savszigeten az utóbbi időben mindenkire vonatkozik, nem tudunk tartani ládás eventeket, és megnehezíti olykor a dolgunk, ha építünk valamit, amit dekorálni kell (eventek akár, warpok, stb.).

Üdv, [Admin]poma123

**Comment by andris155** [comment]
beállítva
