### ISSUE TITLE
Aukció vagy akció?

### ISSUE THREAD

**Issue by AnnaMastersong** [andris155/TheOld-Crafters#1070]
A /warp pénznél a tábla, ami eligazít, hogy merre van az aukció, a lottó, és a többi pénzszerzési lehetőség leírása, el van rontva, mivel az aukció felirat helyett akció van írva.

**Comment by AnnaMastersong** [comment]
![kep](https://user-images.githubusercontent.com/32579927/32417725-594be304-c25e-11e7-8aa2-37dd7f6edb3a.png)

**Comment by andris155** [comment]
javítva

**Comment by andris155** [comment]
Köszönjük
