### ISSUE TITLE
Telek chat hirdetés

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#1071]
A /p chat paranccsal bekapcsolható telek chaten lehet hirdetni, káromkodni, stb, staffok nem látják.

![image](https://user-images.githubusercontent.com/16057404/32407442-6b6c4130-c189-11e7-9ed1-e61edd1d3fb5.png)

**Comment by andris155** [comment]
A /plot chat paranccsal is engedi?

**Comment by UDPSendToFailed** [comment]
Igen, azzal is be lehet kapcsolni ezt a chatet.

**Comment by andris155** [comment]
De azzal is enged hirdetni?

**Comment by UDPSendToFailed** [comment]
Igen.

![image](https://user-images.githubusercontent.com/16057404/32429258-0d6723ba-c2ca-11e7-955a-a1ba18deded9.png)

**Comment by andris155** [comment]
javítva

**Comment by andris155** [comment]
508 OCD
