### ISSUE TITLE
wither kreában!!!

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#1072]
kreában is meglehet idézni a withert, méghozzá ugy, hogy nem a lélekhomokra teszed a fejet, hanem ahova a fej kéne mögé teszel egy blokkot és arra teszed a fejet, igy nem a lélekhomokon lesz a fej, de mégis felette, igy megidáződik a wither kreatívban!! örök csillag forrás elit rangtól!!!

**Comment by andris155** [comment]
videót készítsd erről kérlek

**Comment by skrisz0101** [comment]
ömm nem tudom hogy kell xd de küldök képet minden lépésről, egy pillanat

**Comment by skrisz0101** [comment]
Facebookra küldöm képeket, nem értem ez a githubot :D

**Comment by andris155** [comment]
Köszönjük

**Comment by andris155** [comment]
holnap jó lesz elvileg

**Comment by andris155** [comment]
1016 OCD
