### ISSUE TITLE
A /vote nem írja a top szavazókat

### ISSUE THREAD

**Issue by AnnaMastersong** [andris155/TheOld-Crafters#1073]
![kep](https://user-images.githubusercontent.com/32579927/32442500-f6a75c26-c2fb-11e7-81aa-d34b1ee86408.png)

**Comment by AnnaMastersong** [comment]
![kep](https://user-images.githubusercontent.com/32579927/32442517-016b74b2-c2fc-11e7-9a26-04386e7e802b.png)

**Comment by andris155** [comment]
Jelenleg tökéletes működik.
