### ISSUE TITLE
MineMarket - új termékek

### ISSUE THREAD

**Issue by andris155** [andris155/TheOld-Crafters#1075]
- Totem - megvalósítva.
- Több telek jog (örök) - elvetve.
- Ládák és kulcsok
- Átalakulás jog valamelyik ranggal. - elvetve, a több verziós támogatás miatt nem jó ötlet protocol-okat ilyen szinten használni plugin-al.

**Comment by Paxelcfg** [comment]
- Skin jog [Nem ranghoz kötve], Pwarp jog

**Comment by andris155** [comment]
A skinhez eredeti kell ezen nem is akarok változtatni. Aki akar skint vegye meg a játékot!

**Comment by Paxelcfg** [comment]
Akkor pwarp jog, Több sethome, Több telek, Ajándékláda

**Comment by poprundelHD** [comment]
A ranghoz alapból van több sethome, több telek, illetve pwarp jog. Az ajándékláda nem tudom mit takar, de jó ötletnek hangzik. :D

**Comment by AnnaMastersong** [comment]
-nether star
-wither skull head

**Comment by poprundelHD** [comment]
A boszorkány seprű hozzávétele a járművekhez.

**Comment by andris155** [comment]
A boszorkány seprű túl gyors.

**Comment by Sherox** [comment]
Gps,Cargo manager,blistering ingot (66%,100%),carbonado capacitor, auto (dis)enchenter,advanced programmable android.
