### ISSUE TITLE
Pénz

### ISSUE THREAD

**Issue by Levytheking** [andris155/TheOld-Crafters#1079]
Egy kis ötlet lenne, hogy ugye kapunk 50$-t 10p online törlöm ideőért. Ha nagyobb rangod van annál több pénzt kapsz online töltött idő miatt. Meglehetne oldani?

**Comment by andris155** [comment]
és melyik rang mennyit kapjon?

**Comment by Levytheking** [comment]
Hát kb

-Tag+ 100$
-VIP 300
-elit 500 
-Prémium 1000
-Old 1500

Szerintem kb enyi de lehet hogy kevés vagy sok

**Comment by Levytheking** [comment]
Ha megoldható lenne akkor minigame után kapnak $-t a nyertesek, de persze a nagyobb rangosok többet kapnának ha nyernek.

**Comment by andris155** [comment]
beállítva.
