### ISSUE TITLE
Kreativ

### ISSUE THREAD

**Issue by Paxelcfg** [andris155/TheOld-Crafters#1081]
Kreativban lehet ci-zni. Ez hiba vagy sem?

**Comment by Levytheking** [comment]
Miért lenne hiba?

**Comment by andris155** [comment]
Ez egy hasznos dolog. PE-en egy ideig nem ment kreatívba egy párszor idegbajt is kaptam amikor tele volt az invem és egyesével törölgethettem (ott nincs a shiftes megoldás elvileg), de már ott is megy kreatívban is szerencsére.
