### ISSUE TITLE
Bedöglött chatcontrol

### ISSUE THREAD

**Issue by Viktor1969TOC** [andris155/TheOld-Crafters#1082]
![2017-11-10_09 30 58](https://user-images.githubusercontent.com/32791069/32649428-3f05b7dc-c5fa-11e7-8147-5b48c4593844.png)
![2017-11-10_09 30 50](https://user-images.githubusercontent.com/32791069/32649429-40311552-c5fa-11e7-8e1f-a9f181faf650.png)

**Comment by andris155** [comment]
Szóval ha berakom az update mappába és úgy frissül megdöglik. Nagyszerű. :D
