### ISSUE TITLE
Táblák és levédések

### ISSUE THREAD

**Issue by AnnaMastersong** [andris155/TheOld-Crafters#1087]
A telkeken, ahol eredetileg nem lehet kiütni blockot, vagy bármit csinálni, azt vettem észre, működik a gát kinyitása és becsukása. Nem tudom, működik-e a híd, vagy a lift, de ezek után, valószínű...

![kep](https://user-images.githubusercontent.com/32579927/32699873-f0b97a5e-c7bc-11e7-93c8-9c0c677959fa.png)

![kep](https://user-images.githubusercontent.com/32579927/32699881-0c17fc9e-c7bd-11e7-9ede-206889e13032.png)

**Comment by andris155** [comment]
A ládabolt miatt engedélyezve van alapból az érintkezés a táblákkal. A /p flag set user null paranccsal lehet ezt kikapcsolni.
