### ISSUE TITLE
Soulbound Sword halálkor ki esik ha...

### ISSUE THREAD

**Issue by TamasB14** [andris155/TheOld-Crafters#1088]
Soulbound Sword halálkor ki esik ha pont akkor ölnek meg miközben teszed át az inventoriba más slotba pl.: bent vagy a PVP arénában és mikor észreveszed hogy nincs márt senki átt akarod rakni a soulbound cuccokat [nem csak karddal müködik] hogy kényelmesebben elő tudd venni és hátulról valaki meg öl miközben tetted át a cuccot és akkor ki esik az a cucc és az ellenfél felveszi

**Comment by AnnaMastersong** [comment]
Ha közben az egérrel ,,fogsz" egy item-et, akkor ha meghalsz, az kiesik. Ugyan ez van, ha pl. a barkácsasztalban pakolászol, az egérrel ,,fogod" az item-et, majd kilépsz, a fogás közben, akkor is kiesik az inventory-dból.

**Comment by Levytheking** [comment]
Ezzen nem lehet javítani:D

**Comment by andris155** [comment]
Ez nem hiba.
