### ISSUE TITLE
Bugos In, és Output-ok

### ISSUE THREAD

**Issue by AnnaMastersong** [andris155/TheOld-Crafters#1089]
Az in, és output-ok gyakran elbugolnak, használhatatlanná vállnak. Ez ellen lehet tenni valamit? mert ha elbugol, csak egy Admin tudja kicserélni, de ha nincs fent Admin, akkor nem lehet vele mit tenni...

**Comment by andris155** [comment]
A hibáról tudunk. Sajnos egyelőre megoldást nem tudunk rá.
