### ISSUE TITLE
Romano5 nagyon szépen beszél...

### ISSUE THREAD

**Issue by AnnaMastersong** [andris155/TheOld-Crafters#1090]
![kep](https://user-images.githubusercontent.com/32579927/32732545-37111e96-c88d-11e7-846c-6c91775ee9b1.png)

**Comment by Fr3lly** [comment]
Ez nem hiba. Az oldal hiba jelentésre szolgál.
Az ilyen dolgokat inkább facebook oldalon szoktuk jelenteni.

**Comment by andris155** [comment]
némítást kapott.
