### ISSUE TITLE
Ocd ah-on

### ISSUE THREAD

**Issue by AnnaMastersong** [andris155/TheOld-Crafters#1091]
Szerintem nagyon jó lenne, ha /ah-on lehetne kitenni item-eket eladásra akár ocd-ért is . Pl. ha valamit ki akarok rakni ah-ra, lehetne /ah sell 100 ≈ 5 parancs, és a 100 jelentene sima pénzt, az 5 az OCD-t. és ha valaki meg akarja venni az item-et, akkor a biztos meg akarod venni? ablak előtt, vagy után felugorhatna egy mivel kívánsz fizetni? ablak.

**Comment by andris155** [comment]
Sajnos nem tudom megoldani, mivel ha 0 OCD-ből vonok le sem ad vissza hibakódot a MineMarket API.
