### ISSUE TITLE
Lakatolt ajtók, mejek csak fizetés után nyithatók

### ISSUE THREAD

**Issue by AnnaMastersong** [andris155/TheOld-Crafters#1092]
Szerintem nagyon jó lenne, ha meg lehetne oldani, hogy pl. az ajtó fölé rakok egy táblát, ráírom hogy:
[Locked]
o:100

(az o az open-t jelentheti)(a 100 a nyitásért fizetendő pénzt)

**Comment by andris155** [comment]
Sajnos a jelenlegi plugin-t a lockette pro-t nem fejlesztik. De köszönjük az ötletet. Adok érte azért OCD-t.

**Comment by AnnaMastersong** [comment]
köszönöm
