### ISSUE TITLE
Slimefun Carbonado, stb kemencék!

### ISSUE THREAD

**Issue by Raxoray** [andris155/TheOld-Crafters#1094]
Eddig működött, most tapasztaltam, hogy megint nem mennek normálisan, ugy mennek mint a sima kemencék!
Most írtam át a nevem, valamiért Raxoray-t mutat még mindig! Ha OCD-t kapok, Trymer névre küldd.

**Comment by Raxoray** [comment]
Újra megy!

**Comment by andris155** [comment]
Sajnos előfordul. De erről tudtam.
