### ISSUE TITLE
Login - földrajzi elhelyezkedés mutatása

### ISSUE THREAD

**Issue by poma123** [andris155/TheOld-Crafters#1095]
Jelenleg a /seen és a /whois sem mutatja az adott ember ip címe fölött az országot.
![image](https://user-images.githubusercontent.com/25465545/32799268-7f4a9bd4-c977-11e7-9069-89df79e39ea0.png)

**Comment by andris155** [comment]
Melyik szerver?

**Comment by poprundelHD** [comment]
Savsziget gondolom :D

**Comment by Levytheking** [comment]
Szerintem a loginban van.

**Comment by poma123** [comment]
Login szerver :D Ott írtam a címben is.

**Comment by poma123** [comment]
Login..

**Comment by andris155** [comment]
Ott nincs ilyen még ilyen, de akkor rakok majd.

**Comment by andris155** [comment]
Raktam
