### ISSUE TITLE
Ejtőernyő

### ISSUE THREAD

**Issue by Levytheking** [andris155/TheOld-Crafters#1096]
Ki lehetne írni minemarketben a járművekhez info-ba hogy pl: hogyan lehet lőni a tankkal vagy miben más a gyenge és a profeszionális ejtőernyő.

**Comment by Levytheking** [comment]
Egyszerűbben: bővebb eszközleírás a járművekhez.

**Comment by poprundelHD** [comment]
Tényleg egyszerűbb lenne egy bővebb leírás a járművekről, de erre van kb. 7 staff aki szívesen segítene jármű ügyben. .-.

**Comment by Levytheking** [comment]
Megkérdeztem 3 staff-ot ők nem tudták mi a különbség az ejtőernyők között ezért írtam ide hogyha jobb lenne ha alapból lenne.

**Comment by andris155** [comment]
Egy jó része már jelenleg is ki van írva a MineMarket oldalra, de majd akkor kiegészítem.

**Comment by andris155** [comment]
kész

**Comment by andris155** [comment]
204 OCD

**Comment by Levytheking** [comment]
Köszönöm.
