### ISSUE TITLE
Bugos kijelző

### ISSUE THREAD

**Issue by AnnaMastersong** [andris155/TheOld-Crafters#1097]
Egy auto enchantert leraktam valahova, de miután kiütöttem, ottmaradt a kijelzője
![kep](https://user-images.githubusercontent.com/32579927/32856587-832b117e-ca45-11e7-94d5-6e1f484f637c.png)
![kep](https://user-images.githubusercontent.com/32579927/32856592-873d039e-ca45-11e7-8a55-b3992e15211b.png)
![kep](https://user-images.githubusercontent.com/32579927/32856603-8d53161a-ca45-11e7-8058-dd1674fe6a40.png)

**Comment by andris155** [comment]
Jelentett hiba, egy admin vagy tulaj tudja törölni.
