### ISSUE TITLE
spleef admin/segítő nélkül

### ISSUE THREAD

**Issue by AnnaMastersong** [andris155/TheOld-Crafters#1099]
![kep](https://user-images.githubusercontent.com/32579927/32858455-d71b3d62-ca4b-11e7-918e-73fe41201f2d.png)

**Comment by Mousking** [comment]
Miért kell beszökni engedély nélkül egy eventre?

**Comment by andris155** [comment]
Gondolom valaki véletlen nyitva hagyta vagy nem tudom. Előfordul ilyen.
