### ISSUE TITLE
Ez meg mi??

### ISSUE THREAD

**Issue by AnnaMastersong** [andris155/TheOld-Crafters#1100]
Tudom, hogy ez nem ide való, de ez meg mi? XD olyan, mint egy zombimalac és egy Iron golem gyereke XD
![kep](https://user-images.githubusercontent.com/32579927/32877724-35f69352-caa3-11e7-8d64-718ed2337445.png)

**Comment by AnnaMastersong** [comment]
![kep](https://user-images.githubusercontent.com/32579927/32877796-80e6a988-caa3-11e7-8591-6d5e4a11174a.png)

**Comment by Levytheking** [comment]
Ezek nem githubra való. Ide csak a hibákat/ötleteket kell írni.

**Comment by AnnaMastersong** [comment]
Elnézést :(

**Comment by poprundelHD** [comment]
Ahogy Levi mondja. :p

**Comment by andris155** [comment]
Az első képen lévő szörny valószínűleg a pokolból van, mivel ott előfordulnak ilyenek.

**Comment by MrZero1** [comment]
Bébi zombi-malacember a hivatalos neve.
