### ISSUE TITLE
Kreatív blockok felhasználhatóak

### ISSUE THREAD

**Issue by AnnaMastersong** [andris155/TheOld-Crafters#1101]
a kreatív módban lerakott blockokat kiütés után megkaptam, és nem írta ki a chat, hogy ez a block kreatívban lett lerakva...

**Comment by Levytheking** [comment]
Nem kreás block lehetett.

**Comment by andris155** [comment]
Régebbieknél előfordul sajnos ilyen. A hibáról tudok, de köszönöm a bejelentést.
