### ISSUE TITLE
Creative

### ISSUE THREAD

**Issue by Levytheking** [andris155/TheOld-Crafters#1102]
Ha lelockolunk creatívban egy ládát vagy bármit amit lelehet lockolni és kiütjük a lock tàblát Survivalban akkor megkapjuk a táblát.

**Comment by andris155** [comment]
Jelentett hiba, de szerintem a tábla nem ér annyit, hogy megérne ezzel foglalkozni. Vannak ennél fontosabb hibák is, amiket javítani kell mindig.
