### ISSUE TITLE
Murder hiba

### ISSUE THREAD

**Issue by Paxelcfg** [andris155/TheOld-Crafters#1104]
Ha valaki egy partyban partyban van valakivel és ugy mennek murderezni. egyik a gyilkos a másik a  detektiv akkor nem tudják egymást ölni.
![murderhiba](https://user-images.githubusercontent.com/24989931/32961893-0e2012d2-cbd3-11e7-8938-35832f3af291.png)
![murder hiba 2](https://user-images.githubusercontent.com/24989931/32961895-0fea23fa-cbd3-11e7-85fd-5aa845b82d1e.png)

**Comment by poma123** [comment]
Akkor ezek szerint a party okozta ezt is ugyanígy: #1063

**Comment by andris155** [comment]
Nem támogatott plugin.
