### ISSUE TITLE
WorldEdit hiba! - Trymer

### ISSUE THREAD

**Issue by Raxoray** [andris155/TheOld-Crafters#1106]
Egyik nap megkértem Zerot, hogy wezzen be nekem egy falat, mi azt kicsit megbontottuk mert csinálni akartunk redstonet, és ide adta a wezett cuccot.

**Comment by andris155** [comment]
Nem menti a WorldEdit-et a kreatív plugin. Ezen nem is szeretnék módosítani, mivel lassabb lenne sokkal a WorldEdit, vagy óriási késést okozna (lag).
