### ISSUE TITLE
Sf fejek.

### ISSUE THREAD

**Issue by Levytheking** [andris155/TheOld-Crafters#1107]
Sokszor elbuggolnak a sf fejek. A kicserélésükre admin kell. Lehetne egy állandó shopcreeper ami a buggos fejeket váltja be és nem kellene admin hozzá. Lehetne ez a shopcreeper a beváltó warpnál.

**Comment by andris155** [comment]
A hibáról tudunk. Teljes megoldás keresünk rá majd inkább.
