### ISSUE TITLE
Mob itemek kreában

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#1109]
Ha kiütök egy ládát, amiben mob drop-ok vannak (pl enderpearl, mint a képen), kreában fel lehet venni az itemeket.

![2017-11-21_10 02 19](https://user-images.githubusercontent.com/16057404/33063878-277e0670-cea4-11e7-96de-8423619ba907.png)

**Comment by andris155** [comment]
Videót tudsz erről készíteni? Nagy segítség lenne!

**Comment by UDPSendToFailed** [comment]
https://youtu.be/aHQROiZVBEo

**Comment by andris155** [comment]
Nem sikerült reprodukálni a hibát.
