### ISSUE TITLE
Inv törlés

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#1110]
Az inv törlés üzenetet nem lehet kikapcsolni, így mindig 2x kell beírni a /ci, /clear parancsot.

![image](https://user-images.githubusercontent.com/16057404/33066048-801c7838-ceaa-11e7-92fe-fdbf0752ce93.png)

**Comment by andris155** [comment]
Javítva!
Köszönjük a hibajelentést!
