### ISSUE TITLE
GameBox elírás

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#1111]
![image](https://user-images.githubusercontent.com/16057404/33068816-bfcdeca2-ceb2-11e7-922c-adb8ff32dc3a.png)

![image](https://user-images.githubusercontent.com/16057404/33069047-854258c4-ceb3-11e7-9422-2ad9f0f9c243.png)

![image](https://user-images.githubusercontent.com/16057404/33069083-9ff45ed8-ceb3-11e7-8052-4e60c2e49e4e.png)

**Comment by andris155** [comment]
javítva, holnap tölt be.

**Comment by andris155** [comment]
javítva, holnap tölt be

**Comment by andris155** [comment]
204 OCD
