### ISSUE TITLE
Kérdés

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#1117]
Szia. 

Volt róla szó, anno, mikor bekerült a prémium támogatás, hogy lehet majd venni skin parancsra jogot.
Aktuális-e, lesz ilyen? Jó lenne. :)

**Comment by andris155** [comment]
Lehetőség lenne rá, de nem élek vele. Én szerintem ez így korrekt a Mojang-al szemben, hogy az eredetiseknek lehet skinük, és nekik és csak a sajátjuk.
