### ISSUE TITLE
GameBox

### ISSUE THREAD

**Issue by baumannkitti** [andris155/TheOld-Crafters#1119]
Azoknál a játékoknál,  ahol meg lehet hívni játékost,  nem engedi azokat meghívni,  akiknek a neve kis betűvel kezdődik, mert amikor beírom a chatbe a nevét nagy betűvel írja és az írja a játék, hogy "Nincs  ilyen nevű online játékos"

**Comment by andris155** [comment]
videót tudsz erről készíteni?

**Comment by Paxelcfg** [comment]
https://youtu.be/WSBDasOjfOE
Megcsináltam helyette :)

**Comment by andris155** [comment]
@baumannkitti nincs szükségünk olyan staffokra akik 10 percet nem tudnak rászánni egy videóra, és ezzel segíteni a tulajnak.

**Comment by andris155** [comment]
Sajnos ezt nem tudom javítani.

**Comment by andris155** [comment]
204 OCD Paxelcfg-nek
