### ISSUE TITLE
Hirdetés elleni védelem kis fejlesztés?

### ISSUE THREAD

**Issue by Treuce** [andris155/TheOld-Crafters#112]
![2016-04-01_18 16 26](https://cloud.githubusercontent.com/assets/17810007/14213018/f9426b70-f835-11e5-951d-3dec19dda6fd.png)
Amikor valaki ilyet akarna lerakni a Pipes pluginnal akkor a szerver kiüti a táblát és hirdetésre figyelmeztet..

**Comment by andris155** [comment]
Húha ezt nem is nagyon tudom hirtelen, hogy javítsam.

**Comment by Treuce** [comment]
Átírni hogy 4 kettőspontot érzékeljen egymást követve nem pedig összeségében? Ha mondjuk ,-vel elvan választva vagy valami akkor ne érzékelje?

**Comment by andris155** [comment]
Meg fogom majd nézni, amint lesz rá időm.

**Comment by andris155** [comment]
Kérj meg majd egy Admint, vagy Tulajt, hogy rakjon le neked ilyen táblát.
