### ISSUE TITLE
Moderátor - fly kikapcsolása másoknak

### ISSUE THREAD

**Issue by poma123** [andris155/TheOld-Crafters#1120]
Nincs jogunk kikapcsolni a játékosoknak a fly-t, főleg eventeken lenne hasznos.

Üdv, [Moderátor]poma123

**Comment by andris155** [comment]
A staffokat kell megkérni, mivel bekapcsolás és kikapcsolás parancs tiltása is ugyan az.

**Comment by poma123** [comment]
Én staff vagyok, és nem tudjuk másnak váltani a fly-t. Csak saját magunknak. Ez segítőtől már hasznos lenne.

Köszi, [Moderátor]poma123
