### ISSUE TITLE
SlimeFun GPS kreatívban

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#1124]
Ha kreában ráállok egy sf-es GPS teleporter-re, nem történik semmi, mert le van tiltva az inv-ek megnyitása. Eddig oké, de ha visszaváltok survival-ba, és úgy állok rá, akkor se csinál semmit, mert a sf úgy veszi, hogy egyszer már meg van nyitva az az inventory, csak szerver restart után lehet újra használni. Relog, teleporter kiütés - visszarakás nem oldja meg.

**Comment by andris155** [comment]
Sajnos erre nincs megoldás. Restart hajnalban szokott lenni. Szóval én szerintem nem akkora tragédia.
