### ISSUE TITLE
Hologram projector - hirdetés, káromkodás

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#1125]
![2017-11-24_14 57 33](https://user-images.githubusercontent.com/16057404/33213497-155e509a-d128-11e7-82ae-14e8af8d8acf.png)

**Comment by andris155** [comment]
Hogy kell megadni ezt a szöveget?

**Comment by UDPSendToFailed** [comment]
Jobbklikk a kvarclapra, text, majd a chatbe kell beírni.

**Comment by andris155** [comment]
Nem tudok ezzel mit kezdeni sajnos, alapból ezt nem olyan egyszerű megszerezni sem. Kell hozzá szint és tudás is. Szerintem nem ezzel fognak trollkodni.
