### ISSUE TITLE
Fly állítása a játékosoknak

### ISSUE THREAD

**Issue by poma123** [andris155/TheOld-Crafters#1128]
Jelenleg nem tudjuk (staffok) állítani a játékosok repülését. Ez nagyon hasznos lenne, ha eventen véletlenül úgy maradna valakinek.

Köszi, [Moderátor]poma123

**Comment by poma123** [comment]
Segítő rangtól már lehetne. :D

**Comment by andris155** [comment]
Moderátortól elérhető.
