### ISSUE TITLE
Trymer kérelem

### ISSUE THREAD

**Issue by Raxoray** [andris155/TheOld-Crafters#1129]
Szia Andris! Azt szeretném kérni, hogy az építész ranghoz, vagy nekem kérlek rakj egy pwarp set jogot, mert szükségem lenne rá ha boltot vagy valami más dolgot szeretnék nyitni, és így nem tudok.

**Comment by andris155** [comment]
Miért kell az építésznek boltot nyitni?

**Comment by Raxoray** [comment]
Igaz hogy építész vagyok, de sokat vagyok online tag ként is, és azért kéne nekem bolt hogy legyen miből vásárolni dolgokat, amire szükségem van, mint játékos.

**Comment by andris155** [comment]
Trymer néven?

**Comment by Raxoray** [comment]
igen.

**Comment by andris155** [comment]
Bérelj boltot a /warp plázában oda van warp.
