### ISSUE TITLE
Biome állítás telkeken

### ISSUE THREAD

**Issue by AwesomeFM** [andris155/TheOld-Crafters#1131]
Nem lehetne a /p biome parancson egy kicsit finomítani, hogy ne többszáz, és 10-20 betűs biome-okat tartalmazzon, hanem csak pár alap biome-ot? Rengeteg biome van jelenleg, és ha beírjuk a parancsot ki sem fér a chatbe, a másik pedig hogy nagyon hosszú/bonyolult biome nevek vannak. Van rengeteg olyan is, amit pontosan írok be, de nem csinál semmit, ilyen például az ARTIC biome, de még sorolhatnám. 
A telkek warpon pedig hibásan van kiírva, mert olyan parancs nincs, hogy /p biomes, hanem a /p biome írja ki a biomeok neveit.

![2017-11-26_13 29 08](https://user-images.githubusercontent.com/18013708/33239969-0f850394-d2ae-11e7-818a-197049acffc7.png)

**Comment by andris155** [comment]
A Spigot API-ból kéri le ezeket a neveket, mivel bármikor változhatnak talán ez a legjobb megoldás, mivel így a lista mindig naprakész és nem kell frissíteni ha változik.
