### ISSUE TITLE
Fatelep->McMMO

### ISSUE THREAD

**Issue by Mousking** [andris155/TheOld-Crafters#1132]
A fatelep szerintem jobb lenne, ha engedélyezve lenne ott az McMMO, esetleg úgy, hogy sima world-be lenne átrakva.

**Comment by MrDinamit88** [comment]
Meg a smilefun!

**Comment by andris155** [comment]
Szerintem ezt esélytelen megoldani, mivel a parancsblokkok koordinátákhoz vannak kötve, és azokat nagyon hosszú lenne újraírni.
