### ISSUE TITLE
érc növény kiütés védet helyen

### ISSUE THREAD

**Issue by AnnaMastersong** [andris155/TheOld-Crafters#1133]
Az érc plant-eket (pl diamond plant) ki lehet ütni levédtt terepen is.
Tudom, hogy már jelentve van/volt, de még mindig fennáll ez a probléma, pedig tudtommal le lett zárva...

**Comment by andris155** [comment]
Egyelőre nem tudtam rá jönni, hogy lehetne erre levédést írni. A hibáról tudunk.
