### ISSUE TITLE
szuper zúzó képesség lagg

### ISSUE THREAD

**Issue by AnnaMastersong** [andris155/TheOld-Crafters#1134]
A szuper zúzó képesség használata után, mivel olyan gyorsan üti ki a csákány a blockokat, hogy nem tudja néha érzékelni az mc, bele lehet akadni, akár bele halni a nem létező blockokba.

**Comment by Mousking** [comment]
Ez a bug fennáll egyjátékos módban is, illetve a szerveren az X enchantos csákányoknál, tehát nem szerver hiba.

**Comment by andris155** [comment]
Sajnos a kliens és a szerver szinkronizálás hibája. Ilyenkor a /spawn majd a /back megoldja a hibát.
