### ISSUE TITLE
auto enchanter hiba

### ISSUE THREAD

**Issue by AnnaMastersong** [andris155/TheOld-Crafters#1135]
az auto enchanter nem rak fel enchantot egy tárgyra, ha abból az enchantból már van az adott tárgyon.
(pl. egy hatékonyság 3-as csákányra nem rak hatékonyság 2-est)
És ezek után az enchant könyv is elveszik, csupán könyv marad belőle.

**Comment by Mousking** [comment]
Szerintem ez csak jó, idegesítő lenne, ha egy Hat Xes csákányra raknék Hat V Gyengéd érintést, és levinné a Hatékonyság szintjét.

**Comment by andris155** [comment]
Ez nem hiba, a nagyobb enchant-ot hagyja meg.
