### ISSUE TITLE
PE Szerverfájl hibajelentés

### ISSUE THREAD

**Issue by Mousking** [andris155/TheOld-Crafters#1136]
A Readme.md-ben még jelen van a már nem működő PE szerver hibajelentési linkje.
![screenshot_20171127-212241](https://user-images.githubusercontent.com/25939300/33287534-47adee1e-d3b9-11e7-8033-45ece22c6d94.png)

**Comment by andris155** [comment]
Javítva!
Köszönjük a hibajelentést!
