### ISSUE TITLE
Mypet átüt a falakon/tárgyakon

### ISSUE THREAD

**Issue by Kayalafur** [andris155/TheOld-Crafters#114]
A petek tudnak támadni a fal mögött lévő mobokra is. Sajna most a mobkert látta a kárát. Minden ott lévő mob meg lett ölve. Petb aggro -ról beszélek

**Comment by andris155** [comment]
Szerintem inkább a monsters törlő vitte el, majd visszarakom a mobokat, ha akarod.

**Comment by Kayalafur** [comment]
Köszönöm Andris, viszont el voltak nevezve így is el tudja vinni a törlő?

**Comment by Kronox12** [comment]
Jelentve a fejlesztőnek.

**Comment by andris155** [comment]
lehetséges sajnos.

**Comment by andris155** [comment]
Köszönjük Kronox12

**Comment by Kronox12** [comment]
Sajnos a sima Minecraftos mobok is képesek erre, és révén, hogy a plugin az alap AI-t használja, nem igazán lehet javítani :/ Esetleg annyit tud csinálni a fejlesztő, hogy a közelharci támadások hatótávolságát csökkenti.

**Comment by Kayalafur** [comment]
olyat nem lehet megoldani, hogy a petb aggro-t tiltani területeken? valamivel egyszerűbb lenne ez a megoldás szerintem. vagy az adott területre megidézett petek automatikusan normal behaviorra váltsanak, és tiltva tartani az aggro állapotot?

**Comment by andris155** [comment]
Nem nagyon lehet, mivel ennek folyamatosan a mozgást kéne néznie, ami nem valami processzor barát, amikor 60 játékos mozgását nézi a szerver.
