### ISSUE TITLE
ChatControl R.I.P.

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#1142]
- Nem működnek a ki-belépés üzenetek, helyette az alap mc-s van (xyz joined / left the game)
- Nem lehet másnak privátban írni, nincs rá jog
- A mondatot nem nagybetűvel kezdi, a végére nem rak .-ot, :), :(, <3 jelek nem működnek, hirdetés + káromkodás védelem nincs

**Comment by andris155** [comment]
Javítva
