### ISSUE TITLE
Plugin Ötlet

### ISSUE THREAD

**Issue by warsajt** [andris155/TheOld-Crafters#1147]
Javaslom hogy tegyünk be egy lőfegyveres plugint. A fegyvereket kategóriáik szerint osztanánk be.

Maroklőfegyver, pisztoly = 332OCD
SMG / Személyvédelmi fegyver = 508OCD
Nagy kaliberű fegyver / Esetleges rakétavető = 1016 OCD

https://www.spigotmc.org/resources/gunsmith.31040/

:) :) :) 

És igen. Lenne igény efféle pluginra.

**Comment by andris155** [comment]
Más irányba fejlesztünk inkább, de köszönjük az ötletet.
