### ISSUE TITLE
nem elérhetőek a kitek

### ISSUE THREAD

**Issue by Levytheking** [andris155/TheOld-Crafters#1148]
![screen shot 2017-12-03 at 10 50 33](https://user-
images.githubusercontent.com/20252996/33524169-f5fa4be0-d817-11e7-8c9c-81a46c631aa5.png)

**Comment by Levytheking** [comment]
![screen shot 2017-12-03 at 10 50 33](https://user-images.githubusercontent.com/20252996/33524174-18bc47be-d818-11e7-9a83-8c8e4acf0f99.png)

**Comment by andris155** [comment]
Ebben mi a hiba?

**Comment by Levytheking** [comment]
a szín könyvet nem tudtam lehívni:/

**Comment by andris155** [comment]
Megszűnt. /info színek
