### ISSUE TITLE
McMMO flood

### ISSUE THREAD

**Issue by AwesomeFM** [andris155/TheOld-Crafters#1149]
Nem lehetne az McMMO-ban ezt az "** ELLENSÉG VÉRZIK **" üzenetet kikapcsolni? Mikor több mobot ölünk nagyon idegesítő tud lenni, mert a chatből semmi sem látszik sok esetben. 

![2017-12-03_18 16 09](https://user-images.githubusercontent.com/18013708/33528904-1629fa90-d869-11e7-9367-2ffc963a7cd1.png)

**Comment by andris155** [comment]
szerintem csak ezzel lehet
![kepkivagas](https://user-images.githubusercontent.com/8324198/33529829-439601c4-d876-11e7-95ff-04a68ca39cf0.PNG)

**Comment by UDPSendToFailed** [comment]
A /mcnotify paranccsal ki lehet kapcsolni.
