### ISSUE TITLE
Lasszó

### ISSUE THREAD

**Issue by poma123** [andris155/TheOld-Crafters#1153]
Ha valaki kreatív játékmódban egy lasszóval néhány állatot befog, aztán felrepül velük magasra, majd utána kikapcsolja a fly-t-> leesnek az állatok vele együtt, meghalnak, és amennyi állat volt, annyi lasszó kerül kidobásra az állatok halálozási pontjához.

Üdv, [Moderátor]poma123

**Comment by andris155** [comment]
Nem akarom tiltani a lasszót is kreatívban.
