### ISSUE TITLE
Csont a piacban

### ISSUE THREAD

**Issue by Kreestee** [andris155/TheOld-Crafters#1154]
Nem lehet eladni se csontot se nyilat a piacban.Minden mas szorny cuccokat el lehet adni csak ezeket nem.

**Comment by MrZero1** [comment]
Kikerült az ' Egyéb itemek ' kategóriához. Legközelebb a piaccal kapcsolatos észrevételt, ötletet a warpnál található ötletládába írd meg. 
MrZero
