### ISSUE TITLE
Programmable android + mypet xp addolás

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#1155]
A programmable android (butcher) megöli a pet-et, és a petként beállított mob ad xp-t. Ezt végtelenszer meg lehet csinálni, csak a pet respawn idejét kell megvárni. 

![image](https://user-images.githubusercontent.com/16057404/33734486-d09c7882-db8c-11e7-9d20-c664a6644359.png)

**Comment by andris155** [comment]
Nyilván nem támogatja. Sajnos erre nincs megoldás. De köszönjük a hibajelentést.

**Comment by andris155** [comment]
330 OCD
