### ISSUE TITLE
*nagy sf ötlet*

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#1157]
Meglehetne oldani azt, hogy a bányász android hozzávalóit belehessen váltani admin+ nál rendes bányász andridra, és miután letettük egy kőgenerátor mellé(csak arra használná az egész szerver), csatlakoztattunk hozzá cargo-t, (admin felügyelettel) és az admin körbe vonná bedrokkal, de a cucc megy tovább a cargo-n keresztül. De így nem lehet admin nélkül kiütni az androidot és más célokra(kreatív blokkot üttetni) használni, de mágis sokkal hatékonyabb lenne minden gyár.
Vagy nem is váltja be, hanem scak is az admin teszi le, ugy hogy odaadjuk neki a craft receptet
remélem nem hagytam ki semmit :v

**Comment by poma123** [comment]
nyelvtani hibak miatt elutasitva!

**Comment by skrisz0101** [comment]
Neeee :(
