### ISSUE TITLE
Craftbook hiba

### ISSUE THREAD

**Issue by Kelvin172** [andris155/TheOld-Crafters#1158]
A csőrendszer nem működik megfelelően, legalábbis a színesüveg része. Hiába van csatlakoztatva a sima üveghez a színes és a pistonra rátéve a [Pipe] adott item ID-je nem oda szelektálja, ahova kellene.

**Comment by andris155** [comment]
Most jó?

**Comment by Kelvin172** [comment]
Itt a videó róla: https://youtu.be/YKjzzW71E88

**Comment by andris155** [comment]
Eltudod készíteni a videót angol táblákkal? Vagy ha angolul leírnád az sokat segítene. Több OCD is járna.

**Comment by Kelvin172** [comment]
Készítettem a videó alá fordítást, csak remélhetem, hogy jól fordítottam, meg tudod nézni légyszíves?

**Comment by andris155** [comment]
![kepkivagas](https://user-images.githubusercontent.com/8324198/34301841-935d6726-e72e-11e7-8385-95fae420331b.PNG)

**Comment by CoolIfAI** [comment]
Tudom, zárva már a téma, de ha megnézed; azt írtad, a gyémánt csak abba a dobozba kerül, és ez így is van. Mivel arra a dobozra nem írtad rá hogy mi kerüljön bele, így minden kerül bele, nem csak gyémánt.
Azért írtam le, ha esetleg más is nézi, lássa mi a megoldás.
Sajnos a cső rendszerhez nincs kizárás. Avagy egyéb.
