### ISSUE TITLE
Spawner xp poti bug

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#116]
Ha jobbklikkelek egy spawnerre, megkapom az xp szintem felét potiban, de az itemet nem lehet felvenni.

**Comment by Treuce** [comment]
Ha minden igaz akkor a CraftBook következő verziójában javítva lesz, de most 30as szintig működik egyébként.

**Comment by andris155** [comment]
Már dolgoznak a megoldáson.

**Comment by Treuce** [comment]
A fejlesztő írta, ha lehet akkor frissítsd ha nem lenne frissítve és amint lesz lehetőségem felmenni tesztelem 70-es szinttel.

"I've just done another test where I gave myself intervals of 1500 xp. It worked every time. 

Please ensure that you are running the latest versions of spigot.

If everything still fails with updated versions of spigot, I have added debug nodes to XPStorer in the latest build of CraftBook. If you enable debug mode in the config, and add the 'xpstorer' debug flag, it will enable it.

Once that is done, please try using xpstorer with the amounts of XP that cause issues, and send me the log."

**Comment by andris155** [comment]
Nem tudod tesztelni azon a szerveren, amit a jelentésbe írtál?

**Comment by Treuce** [comment]
Sajnos nincs is szerverem amin tudnám :/ Nem írtam pontosan hogy milyen verzió mert a tietekről tudtam a bugot és úgy jelentettem de van 1-2 infó:
"CraftBook v3.9-SNAPSHOT b24
Spigot 1.9.2 git-Spigot-a1b8bf3-f01861f"
Ezen nem volt még jó
és a Craftbook ezen verzióján sem.
"I've updated to the recent release 3.9u5 and the issue still exists."

**Comment by andris155** [comment]
A Toc szerver verzió: git-Paper-689 (MC: 1.9.2)

**Comment by Treuce** [comment]
Még mindig nem az igazi, 71es szintért 1 stack +4 db XP potit kaptam ami elég kevés, de ezt már fel tudtam venni..

**Comment by andris155** [comment]
Letudod tesztelni házi szerón, és elküldeni a fejlesztőnek a debugot?

**Comment by andris155** [comment]
A Toc szerverfájlja: https://ci.destroystokyo.com/job/PaperSpigot/

**Comment by Treuce** [comment]
Házi szeróval nem nagyon próbálkozok, mert egy laptopon amin a játék se megy rendesen nem az igazi..

**Comment by andris155** [comment]
Most jó?

**Comment by UDPSendToFailed** [comment]
Teszteltem lvl30 és lvl40 xp szinttel, működik.

**Comment by andris155** [comment]
Akkor elvileg javítva.
