### ISSUE TITLE
Játékos statisztikák parancs javítása és a többi szerverre való megírása.

### ISSUE THREAD

**Issue by poma123** [andris155/TheOld-Crafters#1160]
A játékos statisztikák parancs _(/stats)_ beütése után, a Játékidő másodperc része "m"-nek van írva, "mp" helyett.
![image](https://user-images.githubusercontent.com/25465545/33806070-9c838666-ddc2-11e7-9598-0d97ad8b1859.png)

Üdv, [Moderátor]poma123

**Comment by andris155** [comment]
Javítva, és berakva a 3 fő szerverre.

**Comment by andris155** [comment]
204 OCD

**Comment by andris155** [comment]
Holnap tölt be rendesen.
