### ISSUE TITLE
Falusi, ló, farkas, ocelot, slime, papagáj, és egyéb mobok "addolása"

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#1164]
Kell hozzá egy SlimeFun spawner, üllőben törölni a nevét, le lehet rakni, majd egy spawn tojással jobbklikk rá, azt a mobot fogja végtelenszer spawnolni, amilyen fajta spawnegg volt. Ha így kiütöm pickaxe of containment-el, még powered spawner-t is lehet belőle csinálni.

**Comment by skrisz0101** [comment]
Durva :o

**Comment by andris155** [comment]
Elvileg javítva.

**Comment by andris155** [comment]
508 OCD
