### ISSUE TITLE
Slimefun/Acient Altar/Item duplicate

### ISSUE THREAD

**Issue by Barakaazeredeti** [andris155/TheOld-Crafters#1171]
hali Andris, épp Blank Rune-t gyártottam és mivel úgy kb 64-et kellett gyártnom ezért sietősen amint az Altar megkezdte a cuccok beszívását én már tettem is a helyükre az újakat.Eközben eggyet másodperc pontosságra raktam be és vissza is kaptam, ugyanakkor az Altar elvégezte a receptet és megkaptam a Blank Rune-t is.Ez pedig másodszorra is sikerült.Konklúzió: megszületett a 64 Blankrune nekem pedig 2-vel több Magical Lump I-esem volt mint kellett volna.Köszi a figyelmedet!

**Comment by andris155** [comment]
Erről kellene egy videó.

**Comment by Barakaazeredeti** [comment]
meglesz...elér hétvégéig?

**Comment by andris155** [comment]
elér

**Comment by andris155** [comment]
Tárgytalan már.
