### ISSUE TITLE
Bájitalok warp | /recipe <id> táblák

### ISSUE THREAD

**Issue by poma123** [andris155/TheOld-Crafters#1175]
A bájitalok warpnál ki van írva a /recept (id) parancs, de ugye az le van tiltva, a zöld könyv miatt.

![image](https://user-images.githubusercontent.com/25465545/34125081-710c956c-e435-11e7-9883-f5a43d46d3e3.png)

Üdv, [Moderátor]poma123.

**Comment by andris155** [comment]
Javítva!
Köszönjük a hibajelentést!

**Comment by andris155** [comment]
204 OCD
