### ISSUE TITLE
Ancient Padestal bug

### ISSUE THREAD

**Issue by Mousking** [andris155/TheOld-Crafters#1177]
Ha az Ancient Padestalban van cucc, és kiszedjük a Padestalt, akkor a cucc ottmarad, és felvehetetlen lesz

**Comment by andris155** [comment]
https://github.com/andris155/TheOld-Crafters/issues/1171

**Comment by andris155** [comment]
Ez nem ugyan az?

**Comment by Mousking** [comment]
Nem, mivel az véletlen duplikáció, ez pedig az, hogy felvehetetlen lesz az item.

**Comment by andris155** [comment]
Kérlek nyiss újat videóval.
