### ISSUE TITLE
Minemarket bug

### ISSUE THREAD

**Issue by Sizarra** [andris155/TheOld-Crafters#1178]
![nevtelen2](https://user-images.githubusercontent.com/34820798/34329589-ff4e426e-e906-11e7-94f6-49d823b1efa8.png)
![nevtelen](https://user-images.githubusercontent.com/34820798/34329590-044a24a4-e907-11e7-9aee-332dd72157cf.png)
2017.12.24-én kellett volna lejárni a rangomnak, de nem járt le, és már reloggoltam is.
Üdvözlettel: sizarra

**Comment by andris155** [comment]
Elvileg már elvette.

**Comment by Sizarra** [comment]
Elvette, csak kicsit későn azért írtam.

**Comment by andris155** [comment]
Kicsit késik, de inkább hosszabb legyen a rang és ne rövidebb. :D

**Comment by Sizarra** [comment]
Igaz-igaz :D
