### ISSUE TITLE
Pweather bug

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#1179]
Plot-on ha átállítom magamnak az időjárást, és bemegyek egy telekre, majd vissza az útra, a beállított pweather "elbugol". 

https://youtu.be/iSwl0AfTPOo

Az akadozás csak a videóban van az OBS miatt, amúgy nincs köze a problémához.

**Comment by andris155** [comment]
A telkeken azt hiszem külön lehetne állítani az esőt, ezért törli a pweather-t.

**Comment by andris155** [comment]
Egy api-ra épül a 2 és a telkes magasabb priority-n fut.
