### ISSUE TITLE
Murder warp hiba

### ISSUE THREAD

**Issue by Sheep04** [andris155/TheOld-Crafters#1180]
Üdv! Ha bemegyek az egyik Murder játék várakozásba, és kilépek, akkor az életpontom, meg ételcsíkom feltöltődik, de az xp-m megmarad.
Fotók:
![2017-12-25_17 06 54](https://user-images.githubusercontent.com/34780638/34341356-327cc28e-e996-11e7-92e3-9167c27a2e8d.png)
![2017-12-25_17 07 06](https://user-images.githubusercontent.com/34780638/34341358-3da0ea8c-e996-11e7-8984-a396004570c9.png)
![2017-12-25_17 07 16](https://user-images.githubusercontent.com/34780638/34341360-3fe2fc18-e996-11e7-8f54-f03218edf689.png)

Sheep04

**Comment by andris155** [comment]
Sajnos ezzel nem tudunk mit tenni. Azért tölti fel, hogy teljes élettel kajával kezd a játékot. A plugin zárt forráskódú valószínűleg az 1.13-ban le is lesz cserélve.

**Comment by Sheep04** [comment]
Köszönöm!
