### ISSUE TITLE
Farm Nyúl hiba

### ISSUE THREAD

**Issue by Sheep04** [andris155/TheOld-Crafters#1181]
Üdv! Mikor a farmon vagyok, akkor minden sarokban van a lépcsőnél egy kis lyuk, ahova a nyulak be tudnak menni, ott maradnak, és nem lehet őket megölni, illetve olyan rések, ahol meg beragadnak, és nagyon könnyen meg lehet ölni, anélkül, hogy a nyúl elrohanna.
Fotó:
![2017-12-25_17 01 27](https://user-images.githubusercontent.com/34780638/34341316-9c9807b0-e995-11e7-8ca8-c21e15d45664.png)

**Comment by Sheep04** [comment]
Nos akkor ez nem hiba?

**Comment by andris155** [comment]
Ez nem igazán hiba.
