### ISSUE TITLE
PlotSquared és SlimeFun hiba

### ISSUE THREAD

**Issue by ArmaCell** [andris155/TheOld-Crafters#1183]
A lényeg annyi, hogy akkor is letudom aratni más slimefunos növényeit ha nem vagyok hozzáadva a telkéhez. A mellékelt videón majd lehet látni ahogyan közöm nincs a telekhez, mégis learatom a növényeket.

**Comment by AnnaMastersong** [comment]
#1133  #1077  Ez már 2-szer is jelentve van, csak a plugin nem nem támogatott sajnos

**Comment by andris155** [comment]
Nem támogatja a PlotSquared-et sajnos. Ez nem hiba inkább hiányosság.
