### ISSUE TITLE
Tábla hiba

### ISSUE THREAD

**Issue by Sheep04** [andris155/TheOld-Crafters#1186]
Üdv! Éppen kreatívban építem a boltomat, és amikor kiírtam a táblára, hogy tessék a kő, meg lehet venni, félregépeltem, ami miatt ledobta a táblát itemként a földre, amit fel tudtam szedni túlélőben. Szóval nem kell elmenni fát vágnom, hanem megyek kreatívba, hibásan írogatok dolgokat, akkor leesik, túlélőben felveszem, és tessék ingyen tábla.
Fotók:
![2017-12-30_14 29 49](https://user-images.githubusercontent.com/34780638/34454606-0f6a3a1a-ed6f-11e7-9bff-9b3d0445d19e.png)
![2017-12-30_14 29 53](https://user-images.githubusercontent.com/34780638/34454607-14df4bd4-ed6f-11e7-8b82-ca402a7d4d1e.png)
![2017-12-30_14 29 59](https://user-images.githubusercontent.com/34780638/34454610-17293440-ed6f-11e7-8ad5-63835095adb7.png)
Így van ez a híd építésénél is. Ha megépítem a hidat, és úgy döntök, szétszedem, úgy, hogy a híd blokkjai nem látszódnak, és a táblával kezdem a szétszedést, akkor az összes blokk amivel építettem a hidat itemekké droppolnak ,és survivalban fel tudom venni.

Újabb fotók:
![2017-12-31_13 22 26](https://user-images.githubusercontent.com/34780638/34461575-f507eed2-ee2d-11e7-862a-0f8c51638324.png)
![2017-12-31_13 23 08](https://user-images.githubusercontent.com/34780638/34461576-f9fe98a0-ee2d-11e7-89ad-fecccb134655.png)
![2017-12-31_13 23 26](https://user-images.githubusercontent.com/34780638/34461579-fd13aeb8-ee2d-11e7-84bf-02ac4f50b997.png)
![2017-12-31_13 23 32](https://user-images.githubusercontent.com/34780638/34461581-ff59e278-ee2d-11e7-96a6-e9953bb2552a.png)
![2017-12-31_13 23 37](https://user-images.githubusercontent.com/34780638/34461582-0188d9c8-ee2e-11e7-9793-53e64ef60a49.png)
![2017-12-31_13 23 43](https://user-images.githubusercontent.com/34780638/34461583-045884fa-ee2e-11e7-8f4d-4ee734c86263.png)

Sheep04, avagy Sanyi, a vízálló bárány!

**Comment by Sheep04** [comment]
Fontos lenne kijavítani, mert így lehet szerezni egy **csomó** kvarc blokkot ez esetben.

**Comment by andris155** [comment]
A tábla nem sokat ér. A kvarc blokkot kiszedtem a híd blokklistából. Illetve írtam a fejlesztőnek is.

**Comment by andris155** [comment]
508 OCD
