### ISSUE TITLE
YouTube magyar fordítás [OCD]

### ISSUE THREAD

**Issue by andris155** [andris155/TheOld-Crafters#1188]
Segítség kellene a YouTube Bridge plugin lefordításában persze OCD-ért.

**Comment by andris155** [comment]
https://github.com/andris155/TheOld-Crafters/blob/master/Ford%C3%ADt%C3%A1sok/YouTubeBridge/StyleFile.yml

**Comment by Paxelcfg** [comment]
Csinálom

**Comment by andris155** [comment]
Nem fogod tudni mit lehet fordítani és mit nem. Majd megcsinálom, amint lesz rá időm.
