### ISSUE TITLE
SURVIVAL GAMES HIBA

### ISSUE THREAD

**Issue by Sheep04** [andris155/TheOld-Crafters#1189]
Üdv!
Survival Gamessel játszottam a ToC-on, van a "hegyvidék" mapen egy ágy, amibe bele akartam feküdni, és kiírta, hogy beállítva spawnpointnak vagy ilyesmi, majd meccs után megnéztem, és működik. Szóval  meccs után ott tudtam lenni, mikor az itemek is ott maradtak. (azóta az ágyhomeot töröltem)

Sheep04, avagy Sanyi, a vízálló bárány!

**Comment by Sheep04** [comment]
Vagy röviden: sg gamesben ágyra ha rákattintok akkor home lesz.

**Comment by andris155** [comment]
Javítva!
Köszönjük a hibajelentést!

**Comment by andris155** [comment]
204 OCD
