### ISSUE TITLE
Játékosokkal kapcsolatos aprócska ötlet

### ISSUE THREAD

**Issue by Sheep04** [andris155/TheOld-Crafters#1190]
Üdv! 
  Rövidke ötletem abból állna, hogy ki lehetne-e kapcsolni a játékosok "lökdösését", mivel mario meg lépcső eventen folyamatosan lelökjük egymást?
  Előnyök:
   -kényelmesebben, egymás zavarása nélkül játszhatunk
   -Precznek is előnyére válna, mivel folyamatosan lelököm, ha a kerítésen rohangál :D
  
Hátrányok:
   -miért lennének ebből hátrányok? :)
 
 Sheep04, avagy Sanyi, a vízálló bárány!

**Comment by andris155** [comment]
Az mcmmo és nametagedit együtt nem igazán támogatja egymást ha kikapcsolom a lökdösést. Szóval ezért nincs kikapcsolva.
