### ISSUE TITLE
Híd, Ajtó, Kapu blokkok, és redstone dust addolás

### ISSUE THREAD

**Issue by Sheep04** [andris155/TheOld-Crafters#1191]
Üdv!

  Korábban jelentettem a hidas hibát a kvarccal kapcsolatban, csak az a probléma, hogy más hídon, ajtón, és kapun használható blokkot is lehetséges addolni.
  Egy másik hiba, csak úgy gondolom, ide is lehet írni, mert addolással kapcsolatos: Ha kreatívban redstone szerkezetet építek, és az nem működik rendesen, akkor kidroppolja itemmé a redstonet és survivalban fel tudtam szedni (bár lehet, hogy alóla vettem ki blokkot).
  Fotót nem küldök, mivel korábban a hídnál bemutattam.

Sheep04, avagy Sanyi, a vízálló bárány!

**Comment by andris155** [comment]
Amennyire lehetett megoldottam. :/
