### ISSUE TITLE
Bájital főzés

### ISSUE THREAD

**Issue by AnnaMastersong** [andris155/TheOld-Crafters#1192]
Magical essence-ekkel is lehet bájitalt főzni, Blaze Powder helyett.
![kep](https://user-images.githubusercontent.com/32579927/34485928-5f11430a-efcd-11e7-9382-cf970e0fead3.png)
![kep](https://user-images.githubusercontent.com/32579927/34485931-665a5d4a-efcd-11e7-90cf-fac3088af0e4.png)

**Comment by andris155** [comment]
És ezt könnyebb megszerezni?

**Comment by AnnaMastersong** [comment]
Szerintem igen. A Blaze-t megölni egy kezdő játékosnak szerintem nehezebb, mint pl. szén ércet szerezni gyengéd érintéssel, majd abból pl. coal plant-et csinálni, és várni, amíg terem.

**Comment by Sherox** [comment]
Semmivel sem egyszerűbb megszerezni.
Kell hozzá Xp mivel feloldod a sfbe meg a lecraftolása sem olcsó.
-./Sherox/.-
