### ISSUE TITLE
Mobok ölése kreatívban

### ISSUE THREAD

**Issue by Sheep04** [andris155/TheOld-Crafters#1193]
Üdv!
Találtam egy csirkét, vettem a kreatív inventoryból egy gyémánt kardot, és megöltem. Később meg egy tintahalat meg tehenet, azokat is sikerült megölnöm.
Nem tudom mennyit számít, de az alsó részükre reagált inkább a sebzés. Vagy a fejükre. Már nem teljesen tudom, bár a csirke elég kicsi :D 
Sheep04, avagy Sanyi, a vízálló bárány!

**Comment by Kronox12** [comment]
Ez hol volt pontosan? Régi/Új szabad, Telek?

**Comment by Sheep04** [comment]
/warp tájakat beírtam, és a dzsungelt választottam. Nem tudom, hogy ez szabad vagy újszabad :( de valamelyik szabad :)

**Comment by Sheep04** [comment]
Netherben is működik.

**Comment by Sheep04** [comment]
Meg telkeken.

**Comment by andris155** [comment]
Elvileg javítva.

**Comment by andris155** [comment]
204 OCD
