### ISSUE TITLE
Levédés bug

### ISSUE THREAD

**Issue by AnnaMastersong** [andris155/TheOld-Crafters#1194]
Én vagyok a zóna tulaja, mégis az alábbi történik, amikor hozzáadnék valakit :
![kep](https://user-images.githubusercontent.com/32579927/34493652-31a09036-efed-11e7-93bd-54b0472c26c7.png)
![kep](https://user-images.githubusercontent.com/32579927/34493665-400fd370-efed-11e7-9c41-65b497bb0d48.png)
![kep](https://user-images.githubusercontent.com/32579927/34493671-445a5158-efed-11e7-802f-020202d77f2a.png)

**Comment by andris155** [comment]
A zóna eredeti létrehozója valószínűleg más volt. Ki kellene töröltetni a zónát majd újra létrehozni, de ez esetben már neked.
