### ISSUE TITLE
sethome bug

### ISSUE THREAD

**Issue by AnnaMastersong** [andris155/TheOld-Crafters#1195]
Nehéz elmagyarázni, de itt a kép:
![kep](https://user-images.githubusercontent.com/32579927/34494151-500a8246-efef-11e7-8749-48b2fb4f98eb.png)
![kep](https://user-images.githubusercontent.com/32579927/34494156-566a7f74-efef-11e7-94d7-1440ee1fef09.png)
![kep](https://user-images.githubusercontent.com/32579927/34494166-63371212-efef-11e7-85e3-8010e89c4773.png)
![kep](https://user-images.githubusercontent.com/32579927/34494169-67433912-efef-11e7-8665-d3ae1b253d54.png)

**Comment by AnnaMastersong** [comment]
Magyarán a sethome-nál hiába írok á-t, _-lesz belőle

**Comment by andris155** [comment]
Nem támogatja sajnos az ékezetes betűket.

**Comment by andris155** [comment]
https://github.com/EssentialsX/Essentials/issues/1742#issuecomment-354884427
