### ISSUE TITLE
Wither necrotic skull-ból

### ISSUE THREAD

**Issue by AnnaMastersong** [andris155/TheOld-Crafters#1196]
Withert lehet idézni wither csontváz fej helyett necrotic skull fejjel is. Amennyiben kell róla videó, holnap délutánra meglesz. A felvétel már megvan, csak az utómunkálatokat már csak holnap tudom megcsinálni. Ha nem kell a videó, akkor ha lehet holnap délután 1-ig jó lenne, ha szólnál, mert akkor nem akarok vele feleslegesen dolgozni.

**Comment by andris155** [comment]
Ilyet könnyebb szerezni mint sima Wither fejet?

**Comment by AnnaMastersong** [comment]
Igazándiból nem. a necrotic skull a wither csontváz fejéből van.

**Comment by andris155** [comment]
Akkor ezt sok értelme nem lenne javítani. Ki az aki többet szenvedni egy wither-ért? :D
