### ISSUE TITLE
Hibás AreaShop szöveg.

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#120]
![2016-04-10_12 24 37](https://cloud.githubusercontent.com/assets/16057404/14409575/b5560a64-ff17-11e5-8755-9a7bc0e124f5.png)

![2](https://cloud.githubusercontent.com/assets/16057404/14409594/4b71484c-ff18-11e5-8fbe-64f74ac6b610.PNG)

**Comment by andris155** [comment]
Javítva, köszönjük a bejelentést!
