### ISSUE TITLE
Ha van nálam egy fej, bugos a pajzs helye

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#121]
![1](https://cloud.githubusercontent.com/assets/16057404/14411128/ca54360c-ff3f-11e5-9a64-ee8a3488fd8b.png)
![2](https://cloud.githubusercontent.com/assets/16057404/14411126/ca471ecc-ff3f-11e5-8196-d4e119b65123.png)
![3](https://cloud.githubusercontent.com/assets/16057404/14411127/ca4dddb6-ff3f-11e5-888a-5a3b44bf904d.png)

Ha van nálam egy fej, bugos a pajzs helye, egy fekete kocka lesz az ikon helyén. Ha a fej fölé viszem a kurzort, vagy lerakom/eldobom a fejet, jó az ikon.

**Comment by UDPSendToFailed** [comment]
A "Sebzés jelző" is bugos

![2016-04-10_17 22 29](https://cloud.githubusercontent.com/assets/16057404/14411179/f74f32b4-ff40-11e5-92ec-d86765145495.png)

**Comment by andris155** [comment]
Ez a játék hibája, amit nem tudunk javítani.
A játék hibákat kérlek itt jelentsd: https://bugs.mojang.com/browse/MC
