### ISSUE TITLE
Táblára felírt parancsok végrehajtása

### ISSUE THREAD

**Issue by Kayalafur** [andris155/TheOld-Crafters#122]
Kronival tegnap beszéltem, hogy van-e lehetőség olyan dologra, hogy a táblán felírom a flag parancsot például, és arra kattintva végrehajtódjon, pl:

Készítettem egy turi eventet, de mivel a területemen a ládákba nem lehet belenyúlni a WG védelem miatt, így az event használatához ezt át kell állítanom, erre egyszerűbb lenne ha csak táblán lenne a parancs (erre az esetre konkrétan a 2 tábla így nézne ki)
/rg flag jk40 interact allow <- Bekapcsolás 
/rg flag jk40 interact <- Kikapcsolás

Vagy a másik eset, amikor hasznos, mob farmon a spawnolás ki-be kapcsolása, mivel hosszú a parancs, kényelmesebb lenne használni, mivel nincs makró.

Természetesen tudom, hogy ezek a parancsok csak azoknál az embereknél müködnek, akiknek van joga ilyeneket állítani.

**Comment by andris155** [comment]
Jobb megoldás, ha a régión belül kérsz mégegy régiót, ami priority 1-es, és akkor arra lehet külön flagoakt állítani.

**Comment by Kayalafur** [comment]
Igen, az event részre valóban megoldás, bár a mob spawnerekre hasznos lenne, tegnap konkréten sikerült a laggolás miatt bebugolnom egy mobfarmra, és alig bírtam kikapcsolni, mert mire begépeltem a parancsot ledobott a szerver (persze ez a netem hibája is) de ezt annó makróval ki tudtam küszöbölni, hogy egy gombnyomásra beírta a parancsot helyettem.

**Comment by andris155** [comment]
A Macro módra még várni kell tudtommal.

**Comment by andris155** [comment]
Sajnos a táblás parancsok jelenleg nem oldhatóak megy, hogy játékosként írja be a tábla.
