### ISSUE TITLE
Rangok elvétele rangnév szerint, ha lejár.

### ISSUE THREAD

**Issue by LinterX** [andris155/TheOld-Crafters#123]
Szia Andris! LinterX vagyok,tegnap vettem egy Elit rangot, meg is jött csak mára eltűnt. Tudsz segíteni?

**Comment by andris155** [comment]
A rangot visszaadtam, ha lesz időm megpróbálom beállítani, hogy a rangok ne keveredjenek annyira.

**Comment by Kayalafur** [comment]
Andris ezzel kapcsolatban tényleg kéne némi fejlesztés, mivel már kezd ugyan bevett szokássá válni, hogy megvárjuk még lejár a rang és utána vesszük a másikat, mivel a lejáró rang elviszi az új vásárolt rangot. 

Persze ilyenkor jót piszkálódunk, hogy "Tag lettél?" és megy a várakozás az újra vásárolt rang megérkezésére, de tényleg kényelmesebb lenne, ha működne az átfedéses vásárlás.

**Comment by andris155** [comment]
A rangok elvétele beállítva rang szerint.
