### ISSUE TITLE
Spawn OG ládák, infóbox

### ISSUE THREAD

**Issue by MrZeroTOC** [andris155/TheOld-Crafters#124]
Üdv, Andris.

Két dolgot szeretnék leírni.

1. Spawnon található ládák áthelyezése, majd a sethome lehetőség letiltása a spawnon. Ugyanis több tag lerakja a sethomeokat a ládákhoz, majd XY item cserébe megmutatja más játékosoknak.
Így a kereső feeling elveszik. Kérem, a ládák áthelyezését, ill. sethome parancs letiltása

2. Infóboxban található linkek (fb, host stb) színének megváltoztatása, ugyanis a szürke egyáltalán nem látszik, így nem láthatóak a linkek. 

( Talán az SG szöveg is bent van még )

Üdv, MrZero

**Comment by andris155** [comment]
Üdv!
1. Majd az új kezdőhelyen lesz ez megoldva.
2. Milyenre?
