### ISSUE TITLE
Új pláza beállítása

### ISSUE THREAD

**Issue by andris155** [andris155/TheOld-Crafters#125]
/home andris155:pl_za

**Comment by Treuce** [comment]
ETA?

**Comment by andris155** [comment]
Hogy jön ide a porszívó márka? xD

**Comment by Kronox12** [comment]
ETA alatt gondolom a hátralevő időre gondolt.

**Comment by andris155** [comment]
1-2 héten belül.

**Comment by Treuce** [comment]
porszívó márka? xD
Amúgy arra amit Kroni mondott. És köszi a választ!

**Comment by Treuce** [comment]
rg üzenetet dob hogy nincs jogunk ha rálépünk a földön található nyomólapokra.

**Comment by andris155** [comment]
kész
