### ISSUE TITLE
Mocsár warp - Slime spawnolás

### ISSUE THREAD

**Issue by Kayalafur** [andris155/TheOld-Crafters#130]
Nem annyira hiba DE : 
Slime-ért mindenkit a mocsár warpra küldenek, tegnap megnéztem a warpot, nagyon szép, de a környezete alkalmatlan arra, hogy normális mértékben spawnoljon slime (sajna ez szinte 0)

A slime spawnoláshoz nagy sík terület szükséges, ami a jelenlegi warpnál nincs meg egyáltalán, megnéztem a környékét is a területnek, nem túl nagy kiterjedésű a mocsár. Némi átalakítás kéne, hogy legyen legalább 20*20 as sík terület a spawnoláshoz. Ezt pár fa eltüntetésével lehetne orvosolni, vagy a warp közelében kialakítani egy megfelelő rétet/szigetet, és oda irányítanák a segítők a játékosokat.

Azért ide írom, mert nagyon sok játékostól jött az, hogy "nem spawnol slime a mocsár warpon".

**Comment by andris155** [comment]
Kész
