### ISSUE TITLE
Megtalált OldGold ládák helye

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#134]
A /tchest list paranccsal meg lehet nézni a már megtalált OldGold ládák helyét (x/y/z).

![kepernyofelvetel 31](https://cloud.githubusercontent.com/assets/16057404/14763390/74f0d490-0994-11e6-8d29-6fb77b8f9f4d.png)

**Comment by andris155** [comment]
Na az úgy nem rossz. xd

**Comment by andris155** [comment]
javítva, köszönjük a bejelentést!
