### ISSUE TITLE
Bugos /jobs toggle

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#135]
![kepernyofelvetel 32](https://cloud.githubusercontent.com/assets/16057404/14766251/b54016fa-0a02-11e6-9df3-bf782507d086.png)

**Comment by andris155** [comment]
Egyáltalán megvannak a munka adatok?

**Comment by UDPSendToFailed** [comment]
Igen

**Comment by Treuce** [comment]
Ugyanannyit ad a jobs 60-70es szinten mint 1esen véleményem szerint ami nem túl jó..

**Comment by andris155** [comment]
Javítva!
