### ISSUE TITLE
Bugos munkák

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#136]
Ha kilépek egy munkából, amiben már volt szintem, majd belépek, nem 0. szintről kezdődik.

![kepernyofelvetel 36](https://cloud.githubusercontent.com/assets/16057404/14767393/515cb41e-0a24-11e6-8c5a-08e335b3b8f4.png)

**Comment by Treuce** [comment]
UDP, nem rakja vissza 0-ra. Ha kilépsz valamelyikből majd /jobs archive-ban megnézed akkor zárójelben kiírja hogy honnan kezded újra. Legalábbis szerintem

**Comment by Kronox12** [comment]
Ha kilépsz egy munkából, akkor nem törli az addig megszerzett szintjeidet abban a munkában, csak nem ad fizetést érte.

**Comment by LeonidasMC** [comment]
Helló olyan probléma merült fel a Vadász munkával hogy warp sivatagon nem kapok pénzt és xp-t se ha csontvázat ölök,ezt jelentetem egy moderátornak de ő se tudta megoldani a problémát és mondta hogy írjak ide.próbáltam leadni és ujra felvenni is de nem működött.

**Comment by andris155** [comment]
Hamarosan frissítem majd a jobs plugint, addig már nem akarok a régiről hibákat jelenteni a fejlesztőnek, mert lehet már az újban javította.

**Comment by andris155** [comment]
@LeonidasMC ha 2 hét múlva is él az a jobs hiba, kérlek nyiss majd egy hibajelentést. Köszönöm.
