### ISSUE TITLE
Érdekes mob spawnolás

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#137]
Van egy kb 100x100-as kiásott hely 35-ös szinten, teljesen sötét van. Néha spawnol 10-20 mob is egyszerre, ez például 10 perc afk után van:

![2016-04-26_17 00 14](https://cloud.githubusercontent.com/assets/16057404/14832014/65e9d9cc-0bf8-11e6-8b44-3b6749971af4.png)
![2016-04-26_17 08 21](https://cloud.githubusercontent.com/assets/16057404/14832013/65e94afc-0bf8-11e6-8967-6fa42264fd6c.png)
![2016-04-26_17 20 05](https://cloud.githubusercontent.com/assets/16057404/14832015/65ec87c6-0bf8-11e6-96cd-001af252ff07.png)

Máskor sokáig, néha 10-15 percig sem spawnol semmi...

**Comment by andris155** [comment]
Írok majd a Papernak holnap.

**Comment by andris155** [comment]
Jelentve a Paper-nak.
