### ISSUE TITLE
/warp farm-on fejlődik a vadász munka

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#138]
/warp farm-on fejlődik a vadász munka, kapok pénzt és xp-t is az ölésekért.

**Comment by UDPSendToFailed** [comment]
Újabb bug: A bányász munka minden ölésért ad pénzt és xp-t, mint a vadász, az összes mob benne van.

**Comment by andris155** [comment]
Most tesztelted?

**Comment by UDPSendToFailed** [comment]
Most is adnak.

**Comment by andris155** [comment]
A spawnerest megírtam a fejlesztőnek, de úgy látom ez 1.9 gond, hogy a RAM-ban tárolja, hogy a mob spawneres, vagy nem.
