### ISSUE TITLE
A teljes hp visszatöltődik pár másodperc alatt.

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#139]
Az kimaradt a videóból, hogy ha fullon van a kajacsík, alig sebződök az eséstől.

https://www.youtube.com/watch?v=xePD1Sq5fcU

**Comment by andris155** [comment]
Egyjátékos módban is így van?

**Comment by UDPSendToFailed** [comment]
Igen

**Comment by andris155** [comment]
Arról is tudsz videót készíteni?

**Comment by UDPSendToFailed** [comment]
Rosszul láttam, lehet hogy a mozgás miatt ment le az 1-2 csík. Itt a videó, érdekes hogy amikor rámtámad a zombi, nem tölti vissza a hp-t. 

https://www.youtube.com/watch?v=NrMsMsGY9pg

**Comment by andris155** [comment]
Szerintem ez nem igazán hiba, bár nem tudom. Viszont ha hiba szerintem nincs jelentősége ennek, inkább a nagyobb hibák megoldásával foglalkoznék ha nem gond.
