### ISSUE TITLE
Slimefun hiba

### ISSUE THREAD

**Issue by Kelvin172** [andris155/TheOld-Crafters#1391]
Az Automated Ignition Chamber (ami eltartja a smeltery-t tűzzel, ha Kovakő és acél van benne) hopperként szolgál, amit nem kéne, hogy tegyen. Átteszi a Kovakő és acél itemet a smeltery adagolójába.

**Comment by skrisz0101** [comment]
Az nagyon különleges eset lehetett :o

**Comment by andris155** [comment]
Erről kellene egy videó.

**Comment by andris155** [comment]
Nem sikerült reprodukálni.
