### ISSUE TITLE
Youtube plugin izé ötlet

### ISSUE THREAD

**Issue by akos222** [andris155/TheOld-Crafters#1394]
Nem tudom, megoldható-e de menő lenne, ha a [Youtube] ranggal rendelkező playerek név előtagja kattintható lenne, és behozná a Youtube csatornájukat.
Vaaaaaaaaaaaaaagy lenne egy külön rész a Támogatók warpon, ahol minden Youtube rangos neve kint lenne, egy gomb társaságában, ami a csatornájukra visz.
  köszipuszi:
akos_

**Comment by skrisz0101** [comment]
10k ocdt neki

**Comment by andris155** [comment]
Sajnos nem megoldható.
