### ISSUE TITLE
Survival Games hiba

### ISSUE THREAD

**Issue by Sheep04** [andris155/TheOld-Crafters#1398]
Amikor lánc cuccot hordok magamon a Survival Gamesben, akkor 10 másodpercenként kiírja ez az item tiltott ebben a világban.

**Comment by andris155** [comment]
Hát abban a világban le van tiltva a Slimefun.

**Comment by andris155** [comment]
Ez igazából nem hiba.

**Comment by Sheep04** [comment]
Viszont... ez láncruházat. Ez is slimefun?
