### ISSUE TITLE
/warppetparancsok tábla hiba

### ISSUE THREAD

**Issue by AnnaMastersong** [andris155/TheOld-Crafters#1399]
Az egyes rangokban elérhető petek száma nőtt azóta, hogy a tábla a warpon utoljára módosítva lett volna. (vagyis csak gondolom, nem hiszem hogy amikor a táblákat felrakták, ugyanennyi pete lehetett egy x rangos embernek, és valaki meg csak úgy random számokat írt be helyettük)
![kep](https://user-images.githubusercontent.com/32579927/34683548-a4561344-f4a2-11e7-93d6-86aa00c0a19f.png)

**Comment by MrZero1** [comment]
Javítva.

**Comment by andris155** [comment]
Javítva

**Comment by andris155** [comment]
204 OCD
