### ISSUE TITLE
Vasember bug.

### ISSUE THREAD

**Issue by Kyren562** [andris155/TheOld-Crafters#140]
Az lenne a problémám hogy nekem az armor jelzőmet teljesen mutatja hogy armorba vagyok pedig nincs semmi a slotomba szóval olyan védelmem van "meztelenül" mint akármelyik véd4 tör3-as szettesnek csak éppenséggel nekem nem törik semmim.. Kronox-al is próbáltuk míg ő belém 1 szívet sebzett ugyan olyan karddal ő neki maradt 4 szíve a legjobb íjjal belém 2,5hpt sebez míg én megölöm vele.
![2016-04-29_19 45 17](https://cloud.githubusercontent.com/assets/12587428/14924451/f3a9b56a-0e42-11e6-83ce-5f821dbcdb3e.png)
![2016-04-29_19 45 21](https://cloud.githubusercontent.com/assets/12587428/14924452/f3aed054-0e42-11e6-9dca-687ecb2f5a39.png

**Comment by andris155** [comment]
Mióta ilyen, ha meghalsz, akkor is ilyen marad?

**Comment by UDPSendToFailed** [comment]
Ezt én is láttam, azt hittem hogy csak a páncél jelző bugos.

**Comment by Kyren562** [comment]
Ilyen marad nekem.. legalábbis de akkor UDP is látta ezt.

**Comment by andris155** [comment]
Videót tudtok nekem erről készíteni?

**Comment by andris155** [comment]
Illetve, mitől lett ilyen?
