### ISSUE TITLE
Plotme

### ISSUE THREAD

**Issue by Sizarra** [andris155/TheOld-Crafters#1400]
Angol lett a plotme rendszer.

**Comment by Kronox12** [comment]
Lehetőségek:
- Fordításban valamilyen oknál fogva hiba lépett fel, így a konfig újrabetöltésekor új "nyelv" fájlt generált.
- Valamiért EN nyelvezetet használ hu_HU helyett.

!!!Ezek csak javaslatok!!!

**Comment by andris155** [comment]
javítva
