### ISSUE TITLE
Mobok ölése kreatívban

### ISSUE THREAD

**Issue by Sheep04** [andris155/TheOld-Crafters#1401]
Eddig csontvázzal, csirkével, tehénnel, tintahallal, VÉGZETSÁRKÁNNYAL, creeperrel, zombival, husskal sikerült. Azaz amit eddig kipróbáltam.

**Comment by Kronox12** [comment]
#1397

**Comment by andris155** [comment]
Az mcmmo-val valóban lehet. Bár elég lassan. Ez nem hiba és nincs belőle gond.

**Comment by andris155** [comment]
204 OCD
