### ISSUE TITLE
Condense visszafele pl.: 7 smaragdblokkból 63 smaragdot csinál

### ISSUE THREAD

**Issue by Sheep04** [andris155/TheOld-Crafters#1402]

**Comment by Kronox12** [comment]
1 Smaragdblokk = 9 Smaragd
7 Smaragdblokk = 7*9 = 63 Smaragd
Ugyanúgy visszafele, nem értem pontosan a problémát, fejtsd ki bővebben.

**Comment by andris155** [comment]
Ebben nem értem mi a hiba.

**Comment by Sheep04** [comment]
Úgy értem, hogy ez egy ötlet. Vagy, ha alapból csinált olyat, akkor ez a hiba, hogy nem engedi visszafele a condense parancs.
