### ISSUE TITLE
Levédés ötlet / kérelem

### ISSUE THREAD

**Issue by AnnaMastersong** [andris155/TheOld-Crafters#1403]
(végig Tag ranggal fogok példálózni) Szerintem a jelenlegi rendszer, hogy egy tag 3x50x50-et tud levédeni, egy kicsit túl kötött. Szerintem jobb lenne, ha le lehetne védeni 150 blockot, és annyi részletben, amennyiben a játékos szeretné. így szerintem kicsit könnyebb lenne gazdálkodni a levédhető blockok számával.

**Comment by andris155** [comment]
Sajnos ezt a blokkos megoldást nem támogatja a plugin. :/
