### ISSUE TITLE
Slimefun hiba: backpack crafting

### ISSUE THREAD

**Issue by Icecroft** [andris155/TheOld-Crafters#1405]
Ha az Enhanced Crafting Table-n készítünk small backpack-et, akkor az azonnal kap egy UUID-t, ami hiba, mert csak akkor kellene, ha először kinyitjuk.
Elméletileg nem lehetne upgradelni, de mégis műkszik az upgradeje, egészen a guilded backpackig.
Viszont a guilded backpacket nem lehet upgradelni Soulbound backpack-é, az UUID miatt.

Tehát az elvárt működés az lenne, hogy az új craftingolt backpack ne kapjon azonnal UUID-t.

**Comment by andris155** [comment]
Semmilyen backpack-t nem lehet újítani a Soulbound backpack-ra nem?

**Comment by Icecroft** [comment]
csak a Guilded backpacket lehetne Soulbound-á alakítani. De ehhez az kell, hogy ne legyen UUID-je.
Az Enhanced Crafting table-n pedig bármilyen backpacket csinálok, az azonnal UUID-t kap, holott azt csak akkor kellene, ha először kinyitom.

**Comment by andris155** [comment]
Jelentett hiba már a Slimefun-nak is.
