### ISSUE TITLE
Üllő bug.

### ISSUE THREAD

**Issue by balazs145** [andris155/TheOld-Crafters#1406]
Ha egy (Fejre ,cserépre ,fákjára,vöröskőfákjára,gombra,palántára,virágra,szőnyegre,hóra) üllőt ejtenek
akkor az eltünik és nem a rendeltetésszerű módon  kidobódik. Most ez nem tűnhet fontosnak de vegyünk egy példát: Van a házam amit 240 block magasságra védtem le és játékosok fejével díszítem. Egyszer egy troll arramegy és felépít magasabbra és rádobja a fejekre az üllőket és ezután már  mégha utána meg is benná nem tudja visszaadni D":     

 (kreába bármennyi üllőt le tud dobni)

**Comment by Kronox12** [comment]
Jelentett tárgyak (zárójelben) mind tesztelve esetleges tárgyakkal egyetemben.

Eredmény:
- Vagy az üllő vagy a blokk amire ejtették széttörik, de itemet nem dob egyik sem (kreatívban)
- Ha ez mégsem így történik, az üllő simán átesik az adott tárgyon (PL: fákja, kapcsoló, gomb a falon).

**Comment by andris155** [comment]
Ilyen a játék. :D Egyébként a kreás blokk nyilván nem fog blokkot dobni.
