### ISSUE TITLE
Slimefun Hiba: Tome of Knowledge Sharing craftolása

### ISSUE THREAD

**Issue by RacoonFish** [andris155/TheOld-Crafters#1407]
Barátommal le szerettük volna craftolni a tome of knowledge sharinget - érthető okok miatt -, mindent unlockolt a barátom, de nem sikerült lecraftolnia a végleges itemet. Mindent lecsekkoltunk, és nem működött. Kértünk segítséget /helpop-ban is de nem tudtak segíteni. Barátoim mail-ben küldött üzenetet, de átirányítottak minket ide. Az én játékosnevem RacoonFish, és a barátomé SBT95.

**Comment by andris155** [comment]
Mit kellene ennek a tárgynak csinálnia?

**Comment by RacoonFish** [comment]
Slimefunos tudást lehet átadni vele egy másik playernek.

**Comment by andris155** [comment]
Tárgytalan már.
