### ISSUE TITLE
Spawn világ god engedélyezése

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#1410]
Spawnon hiába kapcsolom be a god-ot, ugyanúgy megy le a kajacsík és sebződök. Ha ott afkolok, más player simán meg tud ölni SlimeFun-os cuccokkal.

![image](https://user-images.githubusercontent.com/16057404/34798279-b40697ae-f65b-11e7-9e69-7e2ee1cd2b0e.png)

**Comment by andris155** [comment]
Valami miatt ott is le lett tiltva.
