### ISSUE TITLE
/msg parancs hiba

### ISSUE THREAD

**Issue by RacoonFish** [andris155/TheOld-Crafters#1412]
a /msg paranccsal nem tudok üzenni, azt írja
![2018-01-11_17 06 25](https://user-images.githubusercontent.com/35267623/34834361-233ae198-f6f2-11e7-8ff2-97332ebfa525.png)
![2018-01-11_17 06 29](https://user-images.githubusercontent.com/35267623/34834394-349752be-f6f2-11e7-8aad-1e527c9a8174.png)

 ki, hogy "nincs engedélyed ezt a parancsot használni".

**Comment by Sheep04** [comment]
Most hibás a chatcontrol, Kronox ott van és javítja.

**Comment by RacoonFish** [comment]
Oké köszi az infót :D

**Comment by poma123** [comment]
Elméletileg már jó
