### ISSUE TITLE
Rémrom2 murder aréna - hiányzó barrier

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#1413]
A rémrom2 murder arénából nézőként ki lehet repülni flatworld-be, hiányzik a barrier a tetejéről. Lehet, hogy a többinél is így van, nem tudtam még tesztelni.

![2018-01-11_18 07 00](https://user-images.githubusercontent.com/16057404/34837346-c8e93a9c-f6fa-11e7-82b0-2bdfd664eaae.png)

**Comment by MrZero1** [comment]
Pótolva! A Rémrom1 arénánál volt barrier.

**Comment by andris155** [comment]
Köszönjük.
