### ISSUE TITLE
fa addolás gm 1 és sf kombinációval

### ISSUE THREAD

**Issue by AnnaMastersong** [andris155/TheOld-Crafters#1414]
![kep](https://user-images.githubusercontent.com/32579927/34838251-b5248de2-f6fd-11e7-828a-785d91e8ef10.png)
![kep](https://user-images.githubusercontent.com/32579927/34838262-beb7d29c-f6fd-11e7-8747-dce41dd37012.png)
![kep](https://user-images.githubusercontent.com/32579927/34838267-c4074e94-f6fd-11e7-8acd-4ceb56feb154.png)
(egy jobb klikk)
![kep](https://user-images.githubusercontent.com/32579927/34838299-e2f0c664-f6fd-11e7-9d34-df56ca8ceccf.png)
![kep](https://user-images.githubusercontent.com/32579927/34838302-e740cf98-f6fd-11e7-8776-c6782850fc85.png)

**Comment by Sheep04** [comment]
Hallod Anna... csuklok. :D

**Comment by Paxelcfg** [comment]
Ki a rák fog fát addolni?😂😂😂 Jármű, SF a lényeg😂😂

**Comment by andris155** [comment]
A fatelepen is adolt fa van, ha úgy nézzük. Túl kicsit hiba. Nem érdemes foglalkozni ezzel.
