### ISSUE TITLE
/rules chat 1 illetve 2 YouTube jogok

### ISSUE THREAD

**Issue by Sheep04** [andris155/TheOld-Crafters#1415]
Üdv!
Amióta YT, illetve annak + változatai megjelentek, a következő szabályok (egy  esetben a részét) értelmét veszítették **SZERINTEM**:
![2018-01-11_19 08 56](https://user-images.githubusercontent.com/34780638/34839978-c8b5da5e-f703-11e7-9839-920c64f6469b.png)
![2018-01-11_19 09 12](https://user-images.githubusercontent.com/34780638/34839982-d1459362-f703-11e7-8d69-5ceada28b1d1.png)

Sheep04, avagy Sanyi, a vízálló bárány!

**Comment by andris155** [comment]
javítva, 330 OCD
