### ISSUE TITLE
Citromfa bug

### ISSUE THREAD

**Issue by RacoonFish** [andris155/TheOld-Crafters#1417]
Ennek a citromnak vagy nemtudom minek nincsen custom neve és nem lehet megenni.

/RacoonFish
![2018-01-12_16 55 39](https://user-images.githubusercontent.com/35267623/34883323-99b79902-f7b9-11e7-8c3f-031cfff3749c.png)
![2018-01-12_16 55 51](https://user-images.githubusercontent.com/35267623/34883324-99e58bfa-f7b9-11e7-8bb9-d4cc758517f0.png)

**Comment by Sheep04** [comment]
Mert egy fej xD

**Comment by RacoonFish** [comment]
De hát ezek a gyümölcsfák gyümölcsei általában fejek és meg lehet őket enni.

**Comment by Sheep04** [comment]
Igazad van... :D

**Comment by andris155** [comment]
Néha nem menti tökéletesen az adatbázis. A cargo-t használók tudják jól. Slimefun hiba, egyelőre nincs megoldás rá.
