### ISSUE TITLE
Tábla bugg.

### ISSUE THREAD

**Issue by Heronheaf** [andris155/TheOld-Crafters#1418]
Ha gamemode 1be csinálok 1 láda boltot és elírom a nevét akkor a tábla eldobódik a tábla és     
 gamemode 0-ba felbirom venni. És gondolom ezt jelentem. By: Heronheaf

**Comment by Sheep04** [comment]
#1186

**Comment by andris155** [comment]
Sok dolog épül erre, hogy eldobódik a tábla. Igazából nem érdemes vele foglalkozni. Nyilván tilos, de nem ér valami sokat a tábla. Vannak nagyobb hibák is amire szívesebben szánjuk rá az időnket.
