### ISSUE TITLE
party :v

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#1419]
csináltam egy partyt, de fogalmam se volt hogy hogyan megy ez, angolul annyira tudok hogy sehogy, ezért meg kevésbé értettem, és az aktuális staff se tudott midnent ezügyben, ezért jó lenne, ha lenne egy warp a party-ra vagy esetleg egy fordítás

**Comment by MrDinamit88** [comment]
hihi

**Comment by andris155** [comment]
Folyamatban az mcmmo fordítás.
