### ISSUE TITLE
Lasszóval való kikötés bugos

### ISSUE THREAD

**Issue by Tyloendis** [andris155/TheOld-Crafters#142]
A kikötött állatról elég gyakran elszakad a lasszó, ha nincs játékos a közelben.
De ha nem is szakad el, akkor se lehet látni magát a lasszót, csak a kikötést. (a képen is látható, textura pack nélkül is)
![2016-05-01_00 27 30](https://cloud.githubusercontent.com/assets/18756547/14938946/457d4c2e-0f35-11e6-8d82-bcd0993b59a4.png)

**Comment by andris155** [comment]
Ez egyjátékos módban nem így van?

**Comment by Tyloendis** [comment]
Bár singleplayerben nem tudok elteleportálni, de látszólag nem. A lasszó néha más szerveren is elszakadt, de itt jóval gyakrabban. Az hogy nem látszódik csak a kerítésen az viszont biztosan 1.9 óta van.
![2016-05-01_00 58 54](https://cloud.githubusercontent.com/assets/18756547/14939044/e8b72688-0f37-11e6-9c4f-b71ebf626263.png)

**Comment by andris155** [comment]
Teszteltem, jelentettem a fejlesztőnek. A bejelentést köszönjük!
