### ISSUE TITLE
Tárgy visszaváltás

### ISSUE THREAD

**Issue by Mousking** [andris155/TheOld-Crafters#1420]
Szia! Gondoltam meglátogatom a toct annyi hosszú idő után és maradt pár ocds cuccom, nem váltanád vissza? Durván 1.5 misiről lenne szó de ha 1milliot vissza adsz már király köszi.
![received_1775973732475540](https://user-images.githubusercontent.com/25939300/34907114-bd9fb42e-f879-11e7-8993-76fa9d73c21f.jpeg)

**Comment by UDPSendToFailed** [comment]
Az úgy szép addolás. :D

**Comment by skrisz0101** [comment]
xd

**Comment by MrZero1** [comment]
Nevetséges vagy.
