### ISSUE TITLE
LockettePro csak létező játékosok nevének hozzáadása

### ISSUE THREAD

**Issue by Sheep04** [andris155/TheOld-Crafters#1421]
![2018-01-13_17 02 58](https://user-images.githubusercontent.com/34780638/34907776-f16c367e-f883-11e7-94c8-9efad39a630d.png)

**Comment by Sherox** [comment]
Bárki feljőhet azzal a névvel amit felírsz ez arra jó ha valaki meg szeretné osztani azzal a barátjával aki még nem játszik a szerveren de fel fog jönni.

**Comment by Sheep04** [comment]
Okés...

**Comment by andris155** [comment]
Felesleges plusz ellenőrzés szerintem.
