### ISSUE TITLE
A láda beragad a táblába, ha kinyitom.

### ISSUE THREAD

**Issue by Sheep04** [andris155/TheOld-Crafters#1422]
Üdv!
  Ha esetleg nem számít megfelelő hibának, akkor ez egy megoldási kérelem lenne, hogy a táblákat egy oszloppal arrébb helyezzék.
  A fotók:
![2018-01-13_19 48 48](https://user-images.githubusercontent.com/34780638/34909109-8d1d2eae-f89b-11e7-99ad-f3e75403278e.png)
![2018-01-13_19 48 54](https://user-images.githubusercontent.com/34780638/34909112-8ee05202-f89b-11e7-8926-ff668c074fc2.png)

  Sheep04, avagy Sanyi, a vízálló bárány!

**Comment by andris155** [comment]
Játék effekt hiba, nem szerver. Itt jelentsd kérlek: https://bugs.mojang.com/projects/MC/

**Comment by Sheep04** [comment]
Okés.
