### ISSUE TITLE
PaintBallban gm 1ben :D

### ISSUE THREAD

**Issue by balazs145** [andris155/TheOld-Crafters#1423]
Már nem is tudom hogyan de valahogy átjutottam pb-re full inventoryval (Valószinűleg valakire tpztem csak már észre se vettem :D) és ott gamemodeok között tudtam váltani és a túlélő inventoryból itemeket dobáltam :O (Lekéne tiltani ott a tpacceptet) 
![2018-01-13_20 11 22](https://user-images.githubusercontent.com/35241181/34909328-6ad64066-f89f-11e7-8a78-a06f11acab8f.png)
![2018-01-13_20 11 10](https://user-images.githubusercontent.com/35241181/34909333-7bdf472c-f89f-11e7-9f3d-cb6401037cea.png)

**Comment by Paxelcfg** [comment]
Minek szólsz?😂😂😂

**Comment by Mousking** [comment]
Uh mindjárt veszek egy Elitet.

**Comment by poma123** [comment]
Ez csak a várakozó. Ide warppal lehet eljutni. (`/warp paintball`) A pályára kizárólag túlélő módban tudsz, és semmilyen parancsot nem lehet közben használni. + Amit felveszel a várakozóba, az nem lesz nálad a pályán is.
