### ISSUE TITLE
Csille plugin

### ISSUE THREAD

**Issue by MrDinamit88** [andris155/TheOld-Crafters#1424]
Szia! itt lenne egy nekem tetsző plugin ami a csilléket összekapcsolja!
~
~
~
https://www.spigotmc.org/resources/traincarts.39592/
~
~
~
Remélem segíthettem a szervernek ebben! By: Dina

**Comment by andris155** [comment]
Forráscsomag kell hozzá egyelőre nem akarom keverni a meglévő plugin forráscsomagját ezzel.
