### ISSUE TITLE
Végtelen enchant bugoltatás

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#1427]
McMMO jobbklikkes skill-nél +5 szint hatékonyságot rak ásóra / csákányra / baltára, amit SlimeFun-os auto disenchanter-el le lehet szedni, és feltenni másra. Alapból ha kiveszem az inv-emből, azonnal törli róla a +5 szintet, de ha eszközkeretbe rakom, onnan kiütöm úgy, hogy tölcsérbe essen, aztán cargo-val elvezetem az auto disenchanter-be, nem veszi le róla. Így kb végtelen szintű enchant-ot lehet csinálni, igaz sok értelme nincs, mert a lucky cuccok alapból X-esek, annál jobb nem lesz.

![image](https://user-images.githubusercontent.com/16057404/34918916-85d0c8a2-f95b-11e7-9faf-b14c75117e77.png)

**Comment by andris155** [comment]
erre nincs megoldás

**Comment by UDPSendToFailed** [comment]
Még mindig működik.
@poma123
