### ISSUE TITLE
Seismic Axe

### ISSUE THREAD

**Issue by balazs145** [andris155/TheOld-Crafters#1428]
A Seismic axeel a /warp farmon (Valószinűleg szinte mindenhol) Lehet lökdösni az armor standeket.

**Comment by andris155** [comment]
Nem gravitációs armor stand-et kell lerakni.

**Comment by balazs145** [comment]
Ez egy nagyon jó megoldás, csak az a baj ,hogy a playerek nemtudnak ilyet
csinálni :/ De erre már szerintem nincsen megoldás.

2018-01-15 11:42 GMT+01:00 András Marczinkó <notifications@github.com>:
