### ISSUE TITLE
Bugoltatás

### ISSUE THREAD

**Issue by Kelvin172** [andris155/TheOld-Crafters#1429]
A /vote parancsnál megnyitott itemeket valaki, valahogyan kibugoltathatta az inventoryjába. Egy játékos találta elszórva az itemeket.
![2018-01-14_19 56 23](https://user-images.githubusercontent.com/29312767/34919501-758a62fa-f965-11e7-90b1-57aa4e09767a.png)

![2018-01-14_19 56 19](https://user-images.githubusercontent.com/29312767/34919498-6edcd280-f965-11e7-8015-676dc6f3a88a.png)

![2018-01-14_19 56 15](https://user-images.githubusercontent.com/29312767/34919496-69eb7100-f965-11e7-99af-36dd400d9923.png)

![2018-01-14_19 55 32](https://user-images.githubusercontent.com/29312767/34919492-6057dc3c-f965-11e7-9055-0ea75c39295a.png)

![2018-01-14_19 55 31](https://user-images.githubusercontent.com/29312767/34919487-5ab6e516-f965-11e7-9c29-d26085cb21ab.png)
A /vote parancsnál megjelenő itemek, amik megjelölik az oldalakat valaki, valahogy kibugoltathatta azt.
![2018-01-14_19 55 29](https://user-images.githubusercontent.com/29312767/34919485-54da095c-f965-11e7-8993-a70f2e326c92.png)

**Comment by andris155** [comment]
elvileg javítva

**Comment by andris155** [comment]
204 OCD
