### ISSUE TITLE
Favágó megkurtítása:

### ISSUE THREAD

**Issue by Kayalafur** [andris155/TheOld-Crafters#143]
Azt megértem, hogy a bőr cuccok ki lettek véve a favágóból, de a deszka cuccok miért lettek kivéve?
még az sem, hogy átkerült volna az építészhez.

Logikusnak találtam pl, hogy a deszkák használata a favágóban van mint "ács" rész, de sehol nincs most, hogy ha deszkával építkezel, vagy bontasz, az most semmit nem ad sehol.

Javaslatként tudnám mondani, hogy a deszka lerakás vagy kitütés (mindegy, bár a lerakás inkább):
deszka bármilyen: 1/2-ed a rönkhöz képest
lépcső bámilyen (fa) 1/3-ad a rönkhöz képest
fél lap bármilyen (fa) 1/2 a deszkához képest

Vagy az építészhez kerüljön be, mert sokan használnak fát sok helyre, és lenne értelme így. (nem csak én)

**Comment by Kronox12** [comment]
Favágó nem egyenlő Áccsal. Nem láttam értelmét annak, hogy pénzt kapjon azért, hogy falépcsőt, -félblokkot, -blokkot, -ajtót tesz le.

**Comment by Kayalafur** [comment]
Akkor viszont átkerülhetne az építészhez szerintem, mert ott se láttam fa blokkal való foglalkozás díjazását.

**Comment by Kayalafur** [comment]
![2016-05-01_14 12 52](https://cloud.githubusercontent.com/assets/17968738/14941732/f9003222-0fa6-11e6-9627-e0893c00dad0.png)
![2016-05-01_14 12 56](https://cloud.githubusercontent.com/assets/17968738/14941733/f90db168-0fa6-11e6-8a55-16609f3a1cca.png)
![2016-05-01_14 12 58](https://cloud.githubusercontent.com/assets/17968738/14941734/f9199e9c-0fa6-11e6-8cbb-c937f1254195.png)
![2016-05-01_14 13 01](https://cloud.githubusercontent.com/assets/17968738/14941737/fdf32050-0fa6-11e6-9087-ab2b400bcae5.png)
![2016-05-01_14 13 03](https://cloud.githubusercontent.com/assets/17968738/14941736/fdf0f2bc-0fa6-11e6-8b6a-0393eb2a4da8.png)
![2016-05-01_14 13 05](https://cloud.githubusercontent.com/assets/17968738/14941735/fd9ce5b4-0fa6-11e6-8c3d-a1bc93ac15d0.png)
 Mellékelem az építész szakma leírását, és ott nincs benne.

**Comment by andris155** [comment]
@Kronox12

**Comment by Kronox12** [comment]
Kész.
