### ISSUE TITLE
Bank plugin meghalt

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#1431]
![image](https://user-images.githubusercontent.com/16057404/34982177-f6172396-faa9-11e7-92bb-2681f81622cc.png)

**Comment by andris155** [comment]
Megvenni semmi értelmét nem látom a fizetős verzióját. Írtam a fejlesztőnek, ha nem javítja, akkor szerintem kiszedem.

**Comment by andris155** [comment]
Az alapjával van valami baja, majd holnap elemzem a hibát.

**Comment by andris155** [comment]
Javítva!
Köszönjük a hibajelentést!
