### ISSUE TITLE
Ötletek (nem büfés kocsi)

### ISSUE THREAD

**Issue by MosoMackoHUN** [andris155/TheOld-Crafters#1435]
Kedves Staffok,Adminok,és Moderátorok
Egy plugint mutatnák be nektek.
A plugin lényege a mozgó kalózhajók! Klánharcokkal
Na visszatérve... Nem mindegy mekkora a hajó, mert kell a rang amit játékidővel lehet elérni. Ezt a plugint egy szerveren láttam ami sajnos megszünt, így a plugin szabad! A klánok abból álnak hogy van egy Nexus,és egy boss. A klánharcoknál előjön a boss és védi a helyet ahol van a Nexus. Ha a Nexust kiütik, a klán elveszett. Jut eszembe vannak tengeralattjárók is. A Nexust lehet fejleszteni amivel a klán feljutt a ranglistára és a boss erősödik. Így nehezebb lesz befoglalni! A plugint elkérhetjük az InfiniumPirate Facebook oldalán ahol a tulaj aktív. Linket sajnos nem tudok adni de a nevet pontosan leírtam.
Ha ez megvalósul akkor szeretnék részt venni a készítésében példálul a texture packot. Elérhetőségem a Skype vagy a Viber vagy Steam ahol elérhettek. Viber nevem Kövesdy Milán Skype nevem kovesdy.milan a Steam pedig Kitty Kat Kitty #bhopforlife. Köszönöm hogy elolvastátok Ágyő uraim :D

**Comment by andris155** [comment]
Nem ebbe az irányba fejlesztünk most, de köszönjük az ötletet.
