### ISSUE TITLE
Slimefun

### ISSUE THREAD

**Issue by Blen72** [andris155/TheOld-Crafters#1438]
A Slimefun információt még írja automatikusan.

**Comment by Blen72** [comment]
Hamarabb vettem észre mint MrZero xD
Pont most írtam én is csak regisztráltam. xD
A lényeg hogy jelentve van.

**Comment by andris155** [comment]
Javítva!
Köszönjük a hibajelentést!

**Comment by Blen72** [comment]
OCD-t kaphatok? Ha nem kérlek írj hogy nem!
