### ISSUE TITLE
Tpa változások?

### ISSUE THREAD

**Issue by Kayalafur** [andris155/TheOld-Crafters#144]
![tpa](https://cloud.githubusercontent.com/assets/17968738/14941904/2f61959e-0fad-11e6-81ba-ad699d8a6731.PNG)

El akartam utasítani egy tpa-t meglepetésemre nem tudtam volt ebben változás? Mikor bekértem csak ennyi parancsot engedélyezett amit a képen is látni.

**Comment by andris155** [comment]
Nem lett elvileg módosítva ebben semmi.

**Comment by Kayalafur** [comment]
Arra írja a teleport felkérés elutasítva, csak eddig meg ment a tpadeny is, azért raktam ki a screent, mert meglepett, hogy nem megy, mondom lekérem. köszi, akkor majd ezt fogom használni

**Comment by andris155** [comment]
Elvileg a tpdeny-nek is jónak kellene lennie.
