### ISSUE TITLE
Akvárium event hiba

### ISSUE THREAD

**Issue by Sheep04** [andris155/TheOld-Crafters#1441]
Üdv!
Tegnapi történések: belépek az eventre, úgy, hogy előtte még kreatívban voltam. Gm 0-ba szeretnék váltani, de nem engedi. Szóltam pomának, ő túlélő módba rakott.
Mai történések: elmentem piacra vasért akvárium előtt, és bekapcsoltam a repülés módot, hogy gyorsabban odaérjek. Megvettem, mentem az akvárium eventre, és nem vettem észre, hogy bekapcsolva maradt. Nem mentegetőzni szeretnék, a labirintus végén tényleg repültem véletlenül, és poma kizárt. Szóval nem jó, hogy ezt nem oldották meg, mert tovább játszhattam volna...
Tegnapi történések fotói:
![2018-01-19_22 03 37](https://user-images.githubusercontent.com/34780638/35186795-474890d8-fe1a-11e7-801a-72000fdd7b76.png)
![2018-01-19_22 03 41](https://user-images.githubusercontent.com/34780638/35186799-4e013c90-fe1a-11e7-9235-73aaa4d6b909.png)
Sheep04, avagy Sanyi, a szomorú már nem vízálló bárány... :(

**Comment by poma123** [comment]
Javítva. Az event indulásánál kikapcsolja a fly-t, a god-ot és túlélő játékmódba állítja a várakozóban lévőket.

**Comment by andris155** [comment]
204 OCD
