### ISSUE TITLE
Slimefun megint :D

### ISSUE THREAD

**Issue by Blen72** [andris155/TheOld-Crafters#1442]
A mine marketben van egy kis baj:
![screenshot 2018-01-20 20 06 22](https://user-images.githubusercontent.com/35607857/35187099-a72ac5d0-fe1e-11e7-9420-ee90ad807353.png)
Az előző jelentésre kapok OCD-t? És erre? Ha nem írj!

**Comment by andris155** [comment]
Javítva

**Comment by andris155** [comment]
204 OCD

**Comment by andris155** [comment]
Blen72 még nem regisztrált a http://theold.minemarket.hu/ oldalon.

**Comment by Blen72** [comment]
Ja a minecraftos nevem v5v6v7v8v9

**Comment by Blen72** [comment]
v5v6v7v8v9 a minecraftos nevem.

2018-01-20 20:24 GMT+01:00 András Marczinkó <notifications@github.com>:

**Comment by Blen72** [comment]
Le lehet valahol tölteni azt világot ami újra lesz generálva? (world2)

**Comment by andris155** [comment]
Sokan nem örülnének, ha kiadnánk az építményeiket így sajnos nem. Azonban a saját építményeket ki lehet kérni schematic fájlban bármikor.

**Comment by Blen72** [comment]
Oh. Értem. Ez igaz. Kitől lehet elkérni?

2018-06-12 13:31 GMT+02:00 András Marczinkó <notifications@github.com>:
