### ISSUE TITLE
industrial #2

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#1445]
nem lehet letenni az industrial itemeket

**Comment by andris155** [comment]
Holnap kerül javításra. A world világban le lehet.

**Comment by UDPSendToFailed** [comment]
Nekem a Generator-t nem engedi letenni world-ben se:

![image](https://user-images.githubusercontent.com/16057404/35195434-9499cdee-fec3-11e7-8245-98d05cc448a8.png)

Jetpack-et se lehet csinálni:

![image](https://user-images.githubusercontent.com/16057404/35195442-abe06878-fec3-11e7-8df7-ee853999a019.png)
