### ISSUE TITLE
Safari Net falusi duplázás

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#1446]
Safari Net-el ha befogok egy Shopkeeper falusit, és aztán leteszem, sima falusi spawnol. Ezzel csak az a baj, hogy a Shopkeeper végtelenszer visszaállítja magát, így bármennyit lehet duplázni.

**Comment by MrZero1** [comment]
Ezenkívül levédett területről is belehet fogni a Safari net-be, illetve a játékosokat is betudják fogni, a befogott ember nem tud a chat-be írni semmit, parancsot se. Relogolni kell.

**Comment by andris155** [comment]
330 OCD
