### ISSUE TITLE
/feed elírás

### ISSUE THREAD

**Issue by Sheep04** [andris155/TheOld-Crafters#1450]
Üdv!
![2018-01-21_17 02 20](https://user-images.githubusercontent.com/34780638/35196111-05ee3d7c-fece-11e7-8bde-5089087f9ebf.png)
Helyesen meg lettél etetve.
Sheep04, avagy Sanyi, a most már ismételten vízálló bárány! 😃

**Comment by andris155** [comment]
Javítva!
Köszönjük a hibajelentést!
