### ISSUE TITLE
A pláza fordítás keveri a magyar nyelvet az angollal

### ISSUE THREAD

**Issue by Sheep04** [andris155/TheOld-Crafters#1451]
Üdv!
![2018-01-21_17 09 59](https://user-images.githubusercontent.com/34780638/35196132-441246c0-fece-11e7-8369-d493b0202c74.png)
![2018-01-21_17 10 10](https://user-images.githubusercontent.com/34780638/35196133-4a1a257e-fece-11e7-8b35-f2ee5d0c47b4.png)
![2018-01-21_17 10 14](https://user-images.githubusercontent.com/34780638/35196135-4e452950-fece-11e7-98ce-211d8fd0adca.png)
Sheep04, avagy Sanyi, a vízálló bárány!

**Comment by andris155** [comment]
A hónap nevek sajnos angolok. A többit elvileg javítottam.

**Comment by andris155** [comment]
204 OCD
