### ISSUE TITLE
Ötlet a /rules tájépítéssel kapcsolatban

### ISSUE THREAD

**Issue by Sheep04** [andris155/TheOld-Crafters#1452]
Üdv!
Megjelent az Industrial MC, így bekerültek a Battery Bankek, és mivel a videóban a plugin kitalálója figyelmeztetett, hogy ne építsünk olyan sok Battery Banket, mert a szervernek nem tesz jót, így gondoltam, lehetne a /rules tájépítésbe berakni, hogy pl.: max 4 db. Battery Banket lehet lerakni egy telekre/zónára. Ha sikerült végigolvasnod akkor gratulálok!
Sheep04, avagy Sanyi, a vízálló bárány!

**Comment by andris155** [comment]
330 OCD
