### ISSUE TITLE
Industrial blockok elbugolnak

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#1454]
Ez egy storage unit monitor volt, miután wrench-el jobbklikkeltem rá, hogy eltávolítsam a block-ot, ezt kaptam vissza. Ha ezt lerakom, már semmire se reagál, sima spawner block lesz belőle, így elég sok értékes cucc elveszik.

![image](https://user-images.githubusercontent.com/16057404/35198091-cb611f78-fee9-11e7-8e21-63e6b0e28165.png)

**Comment by UDPSendToFailed** [comment]
Azóta egy storage unit memory és egy nuclear reactor is elveszett. :( 

![image](https://user-images.githubusercontent.com/16057404/35198372-34471e12-feee-11e7-8e74-129d73b1b458.png)

**Comment by andris155** [comment]
330 OCD
