### ISSUE TITLE
pár industrial hiba+észrevétel

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#1457]
Ugye a generátort még mindig nem lehet letenni sehol.
És az elevator  nem is reagál a megnyitásra 

Észrevettem hogy nagyon kevés gépezet található, ez még nem is lenne rossz, de nagyon hamar meglehet unni. Nem lehet automatizálni (ha lehet esetleg nagyon keveset) sec perc alatt össze lehet dobni a gépeket, 100k-ból veszel pár sztekk érctömböt és már van rengeteg géped. Alapból a plugin nem rossz, csak kevés és olcsó

Légyszíves, mihelyst kijön az új slimefun, rakd vissza, az sokkal élvezetesebb, és nem lehet megunni egyhamar :c

\skrisz01\

**Comment by andris155** [comment]
Mi ír a generátor megnyitásnál? Ezekről videó kellene és akkor te is több OCD-t kapnál.

**Comment by andris155** [comment]
330 OCD
