### ISSUE TITLE
eléggé nagy bug ind-ben

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#1459]
a képek magukért beszélnek
![2018-01-22_17 37 13](https://user-images.githubusercontent.com/29951969/35232410-abe0201a-ff9b-11e7-9cc4-0c85b23d2696.png)
![2018-01-22_17 37 23](https://user-images.githubusercontent.com/29951969/35232418-afe9fe10-ff9b-11e7-8bdf-e445e88c2abe.png)
![2018-01-22_17 37 29](https://user-images.githubusercontent.com/29951969/35232425-b26bb48a-ff9b-11e7-8474-0c6404f4d0ea.png)

**Comment by andris155** [comment]
Mi ebben a bug?

**Comment by skrisz0101** [comment]
az, hogy egy ind-es blokkot fixelek, balta lesz

**Comment by skrisz0101** [comment]
![minecraft 1 12 2 2017 11 04 22_05_17](https://user-images.githubusercontent.com/29951969/35286895-6af0d858-0061-11e8-8910-4fd02ca046a0.png)

**Comment by andris155** [comment]
Nem teljesen bug, ez inkább a plugin megoldása, nyilván nem a fix-re van tervezve.
