### ISSUE TITLE
Potatium block-ot bárhol le lehet rakni

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#1460]
WG védésen, más telkén, stb. 

![image](https://user-images.githubusercontent.com/16057404/35232855-dd3dfe10-ff9c-11e7-8687-8d8b99370e46.png)

**Comment by Sherox** [comment]
Megint megcsináltátok. Grt

**Comment by andris155** [comment]
330 OCD
