### ISSUE TITLE
Industrial bug.

### ISSUE THREAD

**Issue by Dreed1992** [andris155/TheOld-Crafters#1462]
![nevtelen](https://user-images.githubusercontent.com/35728669/35273472-05b5c39a-0039-11e8-8503-21307dcb9205.jpg)

Megduplázódik belépéskor a turbina és egymásba ragad. a vezetékek end-ruddá változnak és nem működik,pár turbina összeragadása után már érezhető a lag,valamint a gépek zenedobozzá,a solár sima érzékelőkké változik vagy csak eltünnek.

**Comment by andris155** [comment]
330 OCD
