### ISSUE TITLE
PvP bugg

### ISSUE THREAD

**Issue by Heronheaf** [andris155/TheOld-Crafters#1464]
Sziasztok! Ha elmegyek a mobarénába és ott kilépek akkor bedob a "szurkoló térbe" és ott hiába hogyha 1 másik embernek is levan tiltva a pvp meg nekem is akkor is lehet sebezni a másikat. By Heronheaf

**Comment by poma123** [comment]
Javítva, a pvp letiltva ahol szükséges.
Köszönjük a hibajelentést!

**Comment by andris155** [comment]
Javítva!
Köszönjük a hibajelentést!

**Comment by andris155** [comment]
204 OCD
