### ISSUE TITLE
Baby wither név

### ISSUE THREAD

**Issue by Tyloendis** [andris155/TheOld-Crafters#147]
Kicsit érdekesen néz ki, hogy a kis wither neve nem a feje fölött van, mint a többi mypetnél, hanem az eredeti wither magasság felett.
![2016-05-04_14 30 17](https://cloud.githubusercontent.com/assets/18756547/15014221/0a442006-1205-11e6-8ee5-a0305c7b12ed.png)

**Comment by Kronox12** [comment]
Erre sajnos nincs megoldás.

**Comment by andris155** [comment]
Fogalmam sincs hogy létezik ilyen wither amúgy, a mypeten kívül nem is láttam még másban. De elvileg protocolt használ, és azzal módosítja a sima withert, mivel a játékban elvileg nincs is ilyen ezért sajnos nem tökéletes. De szerintem ennek ellenére elég jó pet, talán a legjobb.
