### ISSUE TITLE
Vanilla Additions 

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#1472]
![eszkozok](https://user-images.githubusercontent.com/29709854/35384657-536735c2-01c6-11e8-8d46-7bf86f156323.png)

Szia. Az eszközök fixálás után elvesztik a kinézetüket, viszont a tulajdonságaik megmaradnak. (pl Ender bow továbbra is teleportál).

A másik: Az ender bow letiltása a Survival Games világba  vagy csak az eventeken hogy megoldható?

**Comment by andris155** [comment]
Most le van tiltva?

**Comment by andris155** [comment]
Javítva mind.
