### ISSUE TITLE
Vanilla Additions chisel

### ISSUE THREAD

**Issue by akos222** [andris155/TheOld-Crafters#1473]
A chisel mcmmo-s használat után csákánnyá válik, és végtelenszer kilehet vele bányászni a blockokat, minden alkalommal megkapjuk a kibányászott tárgyat is.
-akos_

**Comment by andris155** [comment]
Videó kellene erről.

**Comment by akos222** [comment]
holnap megcsinálom, ha nem előz meg valaki

**Comment by andris155** [comment]
egyelőre letiltásra került.

**Comment by andris155** [comment]
A fejlesztőnek jelentve.
