### ISSUE TITLE
Védett hely 

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#1474]
![2018-01-25_18 10 41](https://user-images.githubusercontent.com/29709854/35401895-2578252e-01fb-11e8-97a6-6c9fc668c0f0.png)

Duplafejű balta használa esetén védett területről is kiüti a fát.

**Comment by MrZero1** [comment]
+ Tűzgyújtás levédett helyen, warpon, spawnon. (Nether eszközökkel) tiltani kellene.

**Comment by andris155** [comment]
![27393113_1345378672234641_591647495_o](https://user-images.githubusercontent.com/8324198/35441124-8fb410d6-02a2-11e8-8f23-5879b09e9957.png)

**Comment by andris155** [comment]
Egyelőre letiltásra kerültek. A fejlesztőnek mind jelentve lett.
