### ISSUE TITLE
Additions fordítás

### ISSUE THREAD

**Issue by Saii1** [andris155/TheOld-Crafters#1476]
Ha a kezünkbe van egy eszköz a képernyő tetején írja, hogy: Item Durability in Main Hand: ( item élete ) Ezt szerintem magyarosítani kéne. 
![kepkivagas](https://user-images.githubusercontent.com/35837478/35438275-27c48eb2-0296-11e8-999b-9e956c4f4ae1.PNG)

**Comment by andris155** [comment]
Kész, holnap tölt be. A tárgy neveket inkább hagytam angolul, úgy egyszerűbb utána járni mire jók.

**Comment by andris155** [comment]
204 OCD
