### ISSUE TITLE
belépés hiba

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#1477]
valami baj lehet a szerverrel, mivel szinte senkit se enged fel egyszerre, valamikor második csatlakozáskor enged fel, valamikor 7.-re sem, eddig ez nem volt így, és nem csak velem van ez, mert látni a cseten
tudnál ez ügyben valamit tenni?

**Comment by andris155** [comment]
mit ír ki ha nem enged fel?

**Comment by Kelvin172** [comment]
Én ehhez annyit tudok szólni, hogy aki nem engedélyezi a texture packet, azt automatikusan ledobja a szerverről. Viszont egy olyan is fennáll, hogy engedélyezve van a texture és fellépve fél-1 percen belül ledob a szerver ,,Time out" indokkal, ezt akár 2x 3x is.

**Comment by andris155** [comment]
Letiltottam a kényszerített forráscsomagokat.
