### ISSUE TITLE
Vanilla additions bug

### ISSUE THREAD

**Issue by MrDinamit88** [andris155/TheOld-Crafters#1480]

**Comment by MrDinamit88** [comment]
nem irtam semmit xd
Na van ez az ezközös plugin
és ha godban vagyok pvp off és ütnek megy a páncélnak a sebzése és egyre kevesebb ereje lesz
BY DINA

**Comment by MrDinamit88** [comment]
ja és andris fbn küldök vidit

**Comment by telapoittvan** [comment]
ne jelencsd használd ki

**Comment by poma123** [comment]
Isten mód nélkül is, PvP mentes övezetben is, a páncél durabilityje csökken.

**Comment by andris155** [comment]
Most is?

**Comment by poma123** [comment]
Már nem.

**Comment by andris155** [comment]
Javítva!
Köszönjük a hibajelentést!

**Comment by andris155** [comment]
330 OCD
