### ISSUE TITLE
/p h:<játékosnév>

### ISSUE THREAD

**Issue by Kayalafur** [andris155/TheOld-Crafters#150]
Valamikor régen mikor másik szerveren voltam a ládaboltot mindenki a saját telkén üzemeltette, így ezzel a parancsal bármikor a bolthoz lehetett menni. itt nem müködik ez, csak egy felvetés, hogy lehetne-e használni.

**Comment by andris155** [comment]
Jelenleg a PlotMe 0.13b fut a szerveren. Ebben jelenleg nincs ilyen lehetőség, később lehetséges, hogy lesz ilyesmi.
