### ISSUE TITLE
PC Szerver Pénz farmolás Bányász Job

### ISSUE THREAD

**Issue by Endruw01** [andris155/TheOld-Crafters#151]
Nos annyi a lényeg, hogy ha bányászként dolgozok, akkor ugye miután ki szedek egy ércet, azért pénzt kapok és xp-t. Ha gyengéd érintéssel ütök ki valamit érc formában le tudom tenni, ez ugye le vonja az XP-t és a pénzt is. De nem minden blocknál.. Ilyen a Redstone-Érc is. Akár mennyit le tehetek ha bányász vagyok és nem vonja le a pénzt, majd azt újra ki tudom szedni és meg kapom ugyan azt a pénz és XP összeget amit előtte (szint lépés esetén egyre többet is persze, a tematikáját el nézve a job-oknak).
By: Endruw

**Comment by andris155** [comment]
Köszönjük a bejelentést!

**Comment by Kronox12** [comment]
Beállítás kész, várakozás a konfig fájl frissítésére.

**Comment by andris155** [comment]
Javítva.
