### ISSUE TITLE
1-2 hiba???

### ISSUE THREAD

**Issue by Treuce** [andris155/TheOld-Crafters#153]
1. PvParéna warpnál ha petünk még nálunk van és nem küldtük el mielőtt belépnénk az arénába elkezdi spamolni hogy újraéledt minden sebzés nélkül. Nem tudom hogy ezt ti állítottátok be így vagy egy bug. ?
2. OP alma elnyelt életerő 4t ad, pár napja még ez tudtommal csak 2 volt. Nem tudom erről se hogy direkt van-e így vagy bug.
    EDIT: Minecraft változás.

**Comment by andris155** [comment]
1. @Kronox12 ez mitől lehet?
2. Egyjátékos módban mennyit ad?

**Comment by Treuce** [comment]
2. Egyjátékosban is annyit ad szóval minecraft változtatás gondolom..

**Comment by Kronox12** [comment]
1. Ha eddig még nem csinált ilyet, akkor bug. Nem tudom mi okozza.

**Comment by Icecroft** [comment]
Hasonló esetem volt ma: a petemmel a /warp petparancsokra mentem, azonnal spammelni kezdett, hogy újra éledt a petem, kb másodpercenként egyszer

**Comment by Kronox12** [comment]
Valószínű, hogy Regions bug, mivel csak ott fordult elő, de még vizsgálódok

**Comment by Kronox12** [comment]
Pontosan mikor jelentkezett a bug?

**Comment by Treuce** [comment]
Tegnap mikor felléptem akkor vettem észre, azelőtti nap még nem volt ilyen tudtommal.

**Comment by andris155** [comment]
A 2.-es akkor nem hiba.

**Comment by andris155** [comment]
Az 1.-t akkor jelenteni kellene fejlesztőnek. Tudsz neki írni @Kronox12 ?

**Comment by Kronox12** [comment]
Amint lesz időm, azonnal

**Comment by embervagyok2** [comment]
ciganykurvak anyatok roman szorostalpu fasszopo fereg patkany gecik tetves fasszopo @Shryxx anyadat basszam teherbe ukran vendegmunkas @andris155
