### ISSUE TITLE
Pet plugin probléma

### ISSUE THREAD

**Issue by Icecroft** [andris155/TheOld-Crafters#154]
Amíg tag voltam és csak egy petem volt nem volt hiba a falusiak befogásával.
Most visztont elitként /pswitch store-al mentettem az első petem és befogtam egy farmer falusit 2. petnek, elszállítottam és /petrelease-el elengedtem. Pásztor lett a farmerből, az első 4 farmer-ajánlata (búza, répa, krumpli, smari vásárlás) megmaradt, a további ajánlatai már a pásztoré (szines gyapjuk)
Ezzel a problémával nem csak én találkoztam eddig. Üdv, Icecroft

**Comment by Kronox12** [comment]
Ez fura, ennek nem kéne megtörténnie, teszteltem, és tökéletesen ment. De hát ki vagyok én, hogy megkérdőjelezzem a Minecraft logikáját, ugye? xd
Uána járok a dolognak

**Comment by andris155** [comment]
@Kronox12 jelentetted a fejlesztőnek, vagy nem sikerült reprodukálni?

**Comment by Kronox12** [comment]
Nem sikerült reprodukálni. Nekem tökéletesen megmaradt minden statja a petnek.
