### ISSUE TITLE
Mypet ötletek

### ISSUE THREAD

**Issue by Treuce** [andris155/TheOld-Crafters#155]
1. Petbeacon beállítása különböző skilltreeknek.
Aminek egyáltalán nincs a beacon skill:
-PvP
-Haszon
-Farm
Amiket hozzá lehetne adni:
Haste 2/3 akár.
Withernek talán 1-2vel több lehetőség

**Comment by andris155** [comment]
Szerintem amelyik skillben jelenleg nincs beacon abba ne is legyen.

**Comment by Tyloendis** [comment]
a haste tényleg jó lenne valahova

**Comment by Treuce** [comment]
De mondjuk egy haszonnak egy haste az logikus lenne de még a skillje sincs meg hozzá. Szerintem ha  kicsit ez át lenne tervezve az nem ártana semminek egészen addig amíg nincs minden petnek minden effekt, mert ha a withernek több van és hasznosabb akkor esélyes hogy fognak venni vagy pedig több petért rangot szóval ha látják hogy 1 pet mennyit segíthet ilyen téren akkor nagyobb eséllyel támogatnak több/jobb petért..

**Comment by Kronox12** [comment]
A Haszon kap majd egy Haste II-t. A többihez nem rakok Haste-t. Azok jól vannak úgy. Esetleg a Witherhez rakok egy nagyobb szintű Haste-t.

**Comment by Treuce** [comment]
Nagyobb range a petbeaconnek esetleg? Mert pl ha witheremtől elmegyek pár blokkot már nem adja az effektet, de utánam nem jön még..

**Comment by Kronox12** [comment]
Wither kapott +2 blokk távolságot továbbá egy Haste III-at. A Haszon egy Haste II-t. A PvP-hez betettem pár Beacont.

**Comment by Tyloendis** [comment]
A +2 blokk távolságot nem igazán lehet érzékelni. Ahogy Treuce is írta, csak akkor adja az effektet ha ugyanazon a blokkon állsz vele. A képen látható távolságból már nem adja.
![2016-05-16_22 26 15](https://cloud.githubusercontent.com/assets/18756547/15302912/ab97d178-1bb5-11e6-9e80-0582b3c91995.png)

**Comment by Kronox12** [comment]
Teszteltem, tökéletesen megy. A Wither hamarabb kezd el téged követni, minthogy kilépj a beacon hatásköréből.
