### ISSUE TITLE
Jobs átgondolás

### ISSUE THREAD

**Issue by Treuce** [andris155/TheOld-Crafters#156]
**Mint a facebook csoportban is lehetett olvasni a Jobs jelenlegi állásával van néhány probléma szóval gondoltam leírom hogy szerintem mivel lehetne kordában tartani:**
Olyan fizetés és XP amivel ha elér valaki nagy szintet amiért igenis megdolgozott akkor tud magának pénzt szerezni és nem rögtön egy ember miatt nerf a vége mert előbb-utóbb el lehet érni olyan szintet hogy az már sok. Emellé mondjuk lehetne hogy Jobs szintért lehetne venni bizonyos dolgokat vagy egy max szintet beállítani. Vannak munkák ahol 1-2 dolog kb 200%al többet ér mint az egyik alap pillére a munkának de mégse olyan nehéz rátalálni és kiütni vagy akármiért ad is pénzt, de pl halásznál van a hal ami alap dolog mint bányásznál a kő és a legtöbbet adó cucc pedig hat-hétszeresét adja annak és közbe még nem is feltétlen olyan ritka. Persze van kivétel mondjuk vadászban a wither ami sokat ad de nem is 2 perc megszerezni 1re a cuccot.

**Vélemények/egyéb ötletek amivel el lehetne indulni? Mindenkit szeretnék megkérni arra, hogy ne értelmetlen dolgokat írjon hogy áttekinthető legyen hanem próbálja kifejteni a nézőpontot..**

**Comment by Tyloendis** [comment]
Mint a játék minden területén, itt is a content bővítés mellett vagyok. Az embereknek kell valami jutalmat adni, ami nem feltétlenül csak a pénz lehet. Ugye a legújabb jobs verzióban van ez a pontrendszer. Emellé társul egy beépített shop is, ami elvileg szabadon konfigurálható(jobs wikin olvastam). Ezzel lehetne ütyködni, ha valaki jó nagy szintet elérne, plusz jó sok pénzt kiperkálna, vehetne ebből a shopból az adott szakmához tartozó eszközt. Nyilván ez jobb lehetne, mint amit vanilla survivalban megszerezhetsz. Teszem azt bányásznak egy hatékonyság 6-7 csákány. A buktató ebbe mondjuk annyi, hogy nem minden munkánál lehet ezt alkalmazni, de azért ötletnek bedobom.

**Comment by Kronox12** [comment]
Erre gondoltam én is, de még átgondolandó a pontrendszer.

**Comment by Treuce** [comment]
A pontrendszer jó dolog lenne de nem menne mindennél főleg ahol craftolnod kell stb..bonus rendszernek lenne értelme ami ugye több pénz vag xp de lényeg hogy szerintem jót tenne a szervernek ha nagyobb jutalmat kapnánk

**Comment by Tyloendis** [comment]
Ötlet 2. Esetleg valami title a név mellett, adott jobs szint elérése után.

**Comment by Kronox12** [comment]
A cím az alapból ott van a munkákban, csak nincs engedélyezve, mert zavaró lenne a chatben.

**Comment by Kayalafur** [comment]
A túl sok title valóban zavaró a chatben, viszont az olyan munkáknál, amivel csak crafolással tudsz fejlődni, sztem lehet extra item nem kell feltétlenül bonuszt adnia. Erre volt poén, amikor OLD kemencét javasoltam, semmi haszna de jól hangzik. Lehetnek olyan itemek, amik inkább egyediek, és pont emiatt értékesek és így nehéz a megszerzésük.

**Comment by Tyloendis** [comment]
Nem értek egyet. Egy olyan itemért, aminek semmi értelme sincs, nincs értelme megküzdeni. Az ilyesmik valók aukcióra, ahol azok akik nem tudnak mit kezdeni a több száz milliárdjukkal megvehetik.

**Comment by Kayalafur** [comment]
Pedig látod máris van értelme, el lehet adni :D 

Amúgy nem tudom mennyire megoldható a dolog, de pl lehetne jobs +5% barkácsasztal (csak egy példa) vagy ilyesmi.
