### ISSUE TITLE
Boltban nincs mypet

### ISSUE THREAD

**Issue by Kayalafur** [andris155/TheOld-Crafters#157]
Jelenleg vissza került a boltba a tárgyak eladása, viszont a petemet nem tudom megidézni a boltban, hogy az inventoríjában lévő itemeket is el lehessen adni. 

Tegnap kiteszteltem ezt a rész, csak 1db balta volt nálam itemként így a többi helyre csak fát raktam be ami 2240 db fa volt ez 4900$ -t hozott. Tudom sokan nem ilyen extrémek, én fel szoktam tölteni a petjeim inventoriját is. (2 petemnek 1-1 dupla ládányi helye van).

Sajnos most az eladás csak úgy oldható meg, ha eladom az invem tartalmát, elportolok, pet elő, átpakolok, majd vissza portolok. Kliens oldalról valamiért nem jó ez a sok portolás. 

Ezzel a dologgal lehet valamit kezdeni?

**Comment by Treuce** [comment]
A bolt az SG világában van és ezért nincs mypet. Az egész világra kihat ez a dolog de ha meglehetne oldani csak az arénákra akkor jobb lenne szerintem..
