### ISSUE TITLE
Falusi

### ISSUE THREAD

**Issue by warsajt** [andris155/TheOld-Crafters#158]
Miután szaporítottam a falusiakat, azután a "kis falusival" való üzletelésnél, nem fordítja az angol szöveget magyarra..

**Comment by andris155** [comment]
Pontosabban?

**Comment by warsajt** [comment]
"Szaporított falusinál, az itemeket ill a falusi nevét, nem fordítja magyarra...

**Comment by andris155** [comment]
Ez mc hiba nem?

**Comment by warsajt** [comment]
SinglePlayerben fordítja..

**Comment by andris155** [comment]
1.9.4?

**Comment by warsajt** [comment]
Igen.

**Comment by andris155** [comment]
Még az 1.9.4-es támogatás csak pluginnal van megoldva, a szerverfájl még 1.9.2, mivel az 1.9.4-sben elég komoly hibák vannak még. Valószínűleg ez okozza a hibát.
