### ISSUE TITLE
Ládabolt bug

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#159]
A ládabolt a páncél helyére is rak cuccokat.

![2016-05-15_15 06 55](https://cloud.githubusercontent.com/assets/16057404/15274316/3c754f5c-1aaf-11e6-9cc4-b4723bfae0d1.png)

**Comment by andris155** [comment]
Jelentettem a hibát a fejlesztőnek. Köszönjük a bejelentést.

**Comment by andris155** [comment]
A Chestshop 5.0 verzióban lesz javítva. Amint lesz stabil verzió berakom a szerverre.
