### ISSUE TITLE
Furcsa aukció visszaszámlálás

### ISSUE THREAD

**Issue by Tyloendis** [andris155/TheOld-Crafters#160]
![2016-05-15_19 04 59](https://cloud.githubusercontent.com/assets/18756547/15275605/82a9ec78-1ad0-11e6-87a2-d341649422fe.png)

**Comment by Tyloendis** [comment]
![2](https://cloud.githubusercontent.com/assets/18756547/15275797/72b21e58-1ad5-11e6-9508-c64eb383f724.png)

**Comment by andris155** [comment]
Köszönjük!
Jelentettem a fejlesztőnek.

**Comment by andris155** [comment]
Ja és a képen a sok ládából ha lehet szelektálj, ha nem kell mind. Köszönjük.

**Comment by Tyloendis** [comment]
Nem az én telkem. De majd átadom a tulajdonosnak.
