### ISSUE TITLE
Spawn házban láda levédés bug

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#161]
Vettem spawnon egy házat, levédés nélkül ki tudják nyitni a ládámat, levédeni pedig nem tudom.

![2016-05-16_20 17 21](https://cloud.githubusercontent.com/assets/16057404/15299163/7012ab9e-1ba3-11e6-81c4-4c5330ff8f57.png)

**Comment by andris155** [comment]
Túlélőben letudod védeni?

**Comment by UDPSendToFailed** [comment]
Nem, kinyitja a ládát és a chatre ugyanezt kiírja.

**Comment by andris155** [comment]
Az úgy érdekes.

**Comment by andris155** [comment]
javítva.
