### ISSUE TITLE
RG Flag/Piston védelem bug

### ISSUE THREAD

**Issue by Treuce** [andris155/TheOld-Crafters#164]
Ha tiltom a blokkok kiütését rg területen flaggel akkor a pistonok nem tudják mozgatni a blokkokat.

**Comment by andris155** [comment]
De alapból minek tiltani a kiütést, ha az alapból úgy is tiltott annak aki nincs hozzáadva?
Egyébként gondolom azt is blokk kiütésnek veszi, vagy nem tudom, de ez nem hiba. Ez így van megírva a pluginban.

**Comment by Treuce** [comment]
Mert ha pl saját védésben nem akarom hogy véletlen kitudjak ütni valamit?

**Comment by andris155** [comment]
Kérj külön védést arra amit használhasson az akit nem akarsz a régióhoz adni. (1 gombot is lehet védeni akár) A levédőnek mond, hogy írja be ezt /rg régió setpriority 1
