### ISSUE TITLE
InvTweaks modot hacknek érzékeli

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#167]
Egy dupla ládában akartam rendet rakni, ami tele van 64-be stackelt ércekkel, amikor kidobott:

![kepernyofelvetel 53](https://cloud.githubusercontent.com/assets/16057404/15367090/bd7a9934-1d27-11e6-9e4c-e195fdb90d6f.png)

Megpróbáltam mégegyszer, ugyanez.

**Comment by andris155** [comment]
Túl sok adatot küld egyszerre az invtweaks. Mivel ez a védelem jól tud jönni, ezért nem nagyon akarom állítani. Értelemszerűen mindent néz igazából a kattintások számától kezdve az ugrások számáig mindent, és ha valamiből valaki túl sokat csinál egyszerre kickel. Talán a fél ládát tudja rendezni, már ha egyáltalán tudja, mert spigoton eddig nekem mindig visszadobálta a cuccot ha rendezni akartam.

**Comment by UDPSendToFailed** [comment]
Elég random működik, 10 ládából 7-8 nem dobálja vissza a cuccokat, attól függ, mi van benne.

**Comment by UDPSendToFailed** [comment]
One click crafting ugyanez.

**Comment by andris155** [comment]
Miket használsz te xd
Ha küldesz linkeket, akkor ha lesz időm ránézek erre.

**Comment by UDPSendToFailed** [comment]
http://mods.curse.com/mc-mods/minecraft/231597-one-click-crafting
