### ISSUE TITLE
Mypet ötlet

### ISSUE THREAD

**Issue by Treuce** [andris155/TheOld-Crafters#168]
Jelenleg a petek 30as szintig kapnak skilleket, a wither 45ig. Arra gondoltam hogy lehetne talán efölött is még csak nem szintenként, így lenne értelme minnél tovább vinni a petet. Szóval pl 50,75-100nál valami kis skillt kapna vagy mondjuk 60 és 100nál. Gondolok itt több életre vagy kicsit több sebzésre és akár lehetne úgy is hogy mondjuk 50-en kap valami kis skillt, 75ön egy fokkal jobbat, mondjuk valami effekthez nagyobb esélyt és 100nál meg még ennél is jobbat, ha kell akkor gondolkozok konkrét dolgokon, de ez az alap ötlet.

**Comment by Kronox12** [comment]
Nyáron ha lesz időm ránézek.

**Comment by Kayalafur** [comment]
Való igaz lenne értelme tovább fejleszteni, amúgy ha nem is skillt rakni neki, de pl életet lehetne picit növelni, így kicsit érdekesebbek lennének  a petharcok is, mert ha vagy egy pvp-s peted X szinten, lehet ki tud állni ellene akár egy Haszon pet ha elég magas a szintje pl. Elég lenne némi támadóerő és hp növelés nekik.

csak ennyit akartam hozzáfűzni.

**Comment by andris155** [comment]
@Kronox12 akkor van időd? :D

**Comment by Kronox12** [comment]
Holnap talán

**Comment by Kronox12** [comment]
Jobban szétszórom a skilleket, 100-as szintig fognak fejlődni, de lesz olyan szint is, amikor nem kap semmit sem.

**Comment by andris155** [comment]
90-es szintig kap a pet képességeket.
