### ISSUE TITLE
Elytra bugg

### ISSUE THREAD

**Issue by Hapikacsa** [andris155/TheOld-Crafters#169]
Helló a mai napokba találtam egy buggot.
leugrottam az elytrával a pók hálóba és nem tudtam tovább menni csak ha levettem az elytrát ha feljönnél a szerverre meg muttanám. 
Üdv hapikacsa

**Comment by andris155** [comment]
Szia!
Ez valószínűleg abból következik, hogy a cheat védelmi plugin még alpha 1.9.4-re.
Ajánljuk, hogy használd az 1.9.4-es verziót optifine moddal.
