### ISSUE TITLE
halál bugg.

### ISSUE THREAD

**Issue by Hapikacsa** [andris155/TheOld-Crafters#170]
helló

kb 1 órája elmentem lementem a szerveröl mindenem nálam volt és amire vissza mentem meghaltam és nem voltak ott a cuccaim.Elytra old balta átnevezne alvilágra ez a kettő értékes cucc volt nálam.
kérlek titeket hogy segitsetek.
Üdv hapikacsa

**Comment by andris155** [comment]
Üdv!
Valószínűleg párbaj közben léptél ki.
