### ISSUE TITLE
Jobs hiba:Bányász

### ISSUE THREAD

**Issue by Kronox12** [andris155/TheOld-Crafters#172]
Blokk lerakás:Büntet, ahogy kell.
Blokk kiütés:Nem fizet.

Oka:Keresés folyamatban....

Jelentette: clooby

**Comment by Kronox12** [comment]
Teszt szerveren nem sikerült reprodukálni 1.9.2-vel a hibát.

**Comment by andris155** [comment]
Nem tudom erre nincs ötletem.

**Comment by andris155** [comment]
Olyan blokkal tesztelted a szerveren, amit nem játékos rakott le?
Elvileg azért nem ad pénzt amit játékos rakott le.

**Comment by Kronox12** [comment]
Azonnal megnézem

**Comment by andris155** [comment]
Tehát akkor nem hibás? Csak a védelem nem tetszik a játékosoknak, mert eddig bugoltatták a munkát?

**Comment by Kronox12** [comment]
Lényegében.
