### ISSUE TITLE
SG Hiba

### ISSUE THREAD

**Issue by Treuce** [andris155/TheOld-Crafters#173]
Régebben volt az hogy ha az új old cuccokkal ami + hpt ad stb belépünk SGbe akkor mikor kilépünk megkapjuk a hpt. Ez azóta már javítva lett de van helyette más.
Ha SGben veszünk fel páncélt és kilépünk a szerverről, mikor visszajövünk nem vagyunk SGben és a páncélt is leveszi rólunk de a hotbar-nál jelzi azt hogy rajtunk van és nem csak jelzi hogy van hanem úgy is érzékeli vagyis kevesebb sebzést kapunk.
Nekem a tesztelés egy old cipőbe került, ezt vissza lehetne kapni? :d Illetve kellene fog egy acc reset mivel én be is bugoltam.. :/ Ha lehetséges egy figyelmeztetést azért kérnék hogy mikor nem kéne semminek rajtam lennie.. :D

**Comment by andris155** [comment]
Elvileg holnap jó lesz, addig az SG-t ki töltöttem, mivel ez egy kritikus bug.
