### ISSUE TITLE
Jobs hiba: Favágó -> egyezik a bányásszal 

### ISSUE THREAD

**Issue by Kayalafur** [andris155/TheOld-Crafters#174]
Ha lerakok egy rönköt és kiütöm ugyanúgy fizet érte a jobs mivel fával építek így természetes, hogy rakok le rönköket, ami nem, hogy a jobsnak ilyenkor már nem kéne fizetnie, főleg, ha azt veszük alapul, hogy a bányászban is tiltva van.

**Comment by andris155** [comment]
Amit játékos rak le blokkot az már nem ad pénzt, ha kiütik.

**Comment by andris155** [comment]
@Kronox12

**Comment by Kayalafur** [comment]
De ad most ebben a pillanatban is megnéztem és ad.

**Comment by Kronox12** [comment]
Kreában letéve: nem fizet
Survivalban letéve: fizet
Megoldás: pénz- és xp büntetés rönk lerakásért a jobs részéről

**Comment by andris155** [comment]
Elvileg nem kéne adnia, de amúgy sem tartom jó ötletnek a farönk lerakásért a pénz levonást, mert nagyon sokan abból építkeznek.

**Comment by andris155** [comment]
Meg egyébként ha azt nézzük a fatelepen rengeteg farönk van, ha most valaki lerakja és újra kiüti a farönköt nagyon sok előnye nem lesz belőle.
