### ISSUE TITLE
Új PvPAréna

### ISSUE THREAD

**Issue by Treuce** [andris155/TheOld-Crafters#175]
Szerintem kéne egy olyan aréna ahonnan nem lehet csak annyival kijutni hogy elfutsz/bújsz a másik elől amíg letelik a párbaj(ami ilyenkor nem sok idő) és simán kiteleportálsz. Mert amikor valaki harmadszorra csinálja meg ezt hogy bebújik egy oszlop mögé az aréna másik felén és mire a másik odaér addigra kiteleportál az egy elég frusztráló dolog.. Tiltani kéne a teleportálást és helyette mondjuk egy pár blokknyi "folyosó"val aminek pl soulsand van az alján lehetne biztonságba jutni..

**Comment by andris155** [comment]
Milyen paranccsal teleportálni ki azonnal? Mert az Essentials parancsainál várni kell.

**Comment by Treuce** [comment]
Gondolom PlotMe telekre teleportálnak, mert ott nem kell várni..

**Comment by Kronox12** [comment]
/tp játékos >>> Essentials - várni kell
/p h >>> Plotme - nem kell várni, viszont ez csak saját telekre visz el

**Comment by andris155** [comment]
Majd tiltom a parancsot a régión.

**Comment by andris155** [comment]
Tiltottam.
