### ISSUE TITLE
Szabályzat módosítás (kérés/ötlet)

### ISSUE THREAD

**Issue by Kayalafur** [andris155/TheOld-Crafters#176]
Tiltani kéne, hogy a chatcolor-ban rendszer szineket használhassanak a játékosok, sajna megint jött a szokásos Chat trollkodás Otniel részéről. 
Legegyszerűbbnek azt tartanám, ha tiltott lenne a rendszerszin.
![chattroll](https://cloud.githubusercontent.com/assets/17968738/15471231/327c55da-20f5-11e6-8993-34275225364f.PNG)

**Comment by Kronox12** [comment]
Ez ellen már tettünk. Más színnel írja mostantól az összeget. Aki meg nem figyel, és nem veszi észre, az magára vessen. Viszont az efféle trollkodást még mindig büntetjük.

**Comment by andris155** [comment]
Javítva. vörös színt nem tud támogató írni.
![kepkivagas](https://cloud.githubusercontent.com/assets/8324198/15473958/e845efa4-2102-11e6-9d5e-2a03d8585190.PNG)

**Comment by andris155** [comment]
Mivel sokan jelentették ezt a hibát ezért most nem jár sajnos jutalom.

**Comment by andris155** [comment]
De a bejelentést köszönjük!

**Comment by Kayalafur** [comment]
Nem jutalomért jelentettem :D 
A jutalom olyan, ha úgy itélitek van, ha nincs nincs inkább köszönöm a javítást :D
