### ISSUE TITLE
Mypet ellopja az xp-t

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#177]
Ha be van kapcsolva a /petpickup, a pet felveszi az xp-t is, de nem fejlődik tőle.

**Comment by Kronox12** [comment]
Valamit valamiért.

**Comment by andris155** [comment]
Ez most hiba, vagy nem hiba @Kronox12 ?

**Comment by andris155** [comment]
@Kronox12
