### ISSUE TITLE
Bot védelem

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#1771]
kicsit uncsi loginban a 20 bot, ami folyamatosan váltja egymást

**Comment by Zeroapja** [comment]
Igen bazd meg vele anyádat, köszi

**Comment by Zeroapja** [comment]
Najó nem :(
Ha gondolják tolják feljebb a Lobby határt, most se fér el a sok bot, elszomorító

**Comment by AnnaMastersong** [comment]
-.-

![kep](https://user-images.githubusercontent.com/32579927/35589069-e2b1dcc4-0602-11e8-9406-c736fa040526.png)
![kep](https://user-images.githubusercontent.com/32579927/35589090-f4a2df78-0602-11e8-99c8-876c710775c0.png)
![kep](https://user-images.githubusercontent.com/32579927/35589094-f9ccdd64-0602-11e8-8ae1-ada0f9002df6.png)
![kep](https://user-images.githubusercontent.com/32579927/35589098-03de745c-0603-11e8-8de0-93a80f1c63e7.png)

**Comment by Zeroapja** [comment]
Van hogy lemegy 19-re :(

**Comment by andris155** [comment]
Kész
