### ISSUE TITLE
Spam

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#1772]

**Comment by Zeroapja** [comment]
Ki mondta hogy a Githubot ők baszták meg? :x

**Comment by MrZero1** [comment]
Akárki vagy, ha megtudom, ki volt, nem lesz jóvége. :D Tanulj egy kicsit a médiajogokról. :)

**Comment by Zeroapja** [comment]
Papa mizu a jogaiddal?

**Comment by Zeroapja** [comment]
Már nem azért az 500 Forintért de ha érdekel ilyen indokkal bannoltok folyton, mit tegyek én, hivatkozzak én is arra? Nem vagytok jobbak mint mi, úgy látszik.

**Comment by MrZero1** [comment]
Miért, talán mi botoljuk saját magunkat? :D Jobbak vagyunk, van bennünk gerinc, veled/veletekkel szemben.

**Comment by OldCancer** [comment]
A szerver sérti a Mojang EULA-t, azzal, hogy offline módban van futtatva, és pénzt kérnek a rangokért. Ajánlom átolvasni.

**Comment by MrZero1** [comment]
EULA-val könnyű dobálózni kérlek. :D Mellesleg nincs offline módban futtatva. Mi lenne, ha inkább hasznosak lennétek? Akármelyik értelmi vagy.

**Comment by OldCancer** [comment]
Csak, hogy idézzek belőle:

> you only give access to your server to users who have a genuine paid for version of Minecraft;

**Comment by Sizarra** [comment]
Vagytok annyira tökösök, hogy elmondjátok kik vagytok? 😂

**Comment by MrZero1** [comment]
Tök? :D Ugyanmár. Gerinc sincs bennük. Ne várj sokat az ilyen emberektől, sok az idejük. (:

**Comment by skrisz0101** [comment]
Nem xd

**Comment by Sizarra** [comment]
Most igy elképzeltem: kis 9éves gyerek ül a gép előtt, és arra veri magát hogy valamit tudott kezdeni, amivel semmit nem ér mivel az addolt cuccok törlésre kerülnek 😂

**Comment by MrZero1** [comment]
Ilyenkor anyu, apu merre van? :D

**Comment by Sizarra** [comment]
Gyereket csinálni könnyű , felnevelni nem :)

**Comment by MrZero1** [comment]
Akkor védekezzen jobban az idióta :D

**Comment by Zeroapja** [comment]
Ti is csak kiszöktetek nyugi :)

**Comment by Sizarra** [comment]
Felkéne az ilyeneket akasztani 😂

**Comment by MrZero1** [comment]
Persze persze. :D Nem mi vagyunk a gerinctelen férgek, akik a nevüket sem merik felvállalni.. :D Nevetséges ez

**Comment by Sizarra** [comment]
1000+1 kínzási módszert tudnék az ilyeneknek kitalálni 🤗

**Comment by OldCancer** [comment]
![27400296_1545778352138325_1934667780_n](https://user-images.githubusercontent.com/35972412/35589154-2ab135e2-0603-11e8-8429-75b0a3d04f78.jpg)

**Comment by Sizarra** [comment]
Kedves "Zeroapja" 
Azt üzenem önnek, fedje fel igazi kilétét, hiszem ha már ön, beleszól itt a dolgokba, legyen önben annyi tisztelet, hogy elmondja kicsoda valójában. 
Köszönöm, üdvözlettel: 
~sizarra

**Comment by MrZero1** [comment]
Siza, hagyd, nem szorult belé értelem :D

**Comment by AnnaMastersong** [comment]
Szizi :D Ezek után megkérdem, ez te lennél? 
![kep](https://user-images.githubusercontent.com/32579927/35589217-6afa2f96-0603-11e8-9ee5-020e29c0b6c8.png)

**Comment by Sizarra** [comment]
Hagyom inkább látom nem voltak ott az észosztásnál 🤣

**Comment by Sizarra** [comment]
Nem anna, én sizarra voltam vagyok és leszek is 😊

**Comment by AnnaMastersong** [comment]
Igen, rájöttem, hogy nem tudok olvasni XD

**Comment by OldCancer** [comment]
![kep](https://user-images.githubusercontent.com/35972412/35589302-af6cfb0e-0603-11e8-8ce2-da9291ca582a.png)

**Comment by Sizarra** [comment]
Amugy wtf volt az a kep 🤣🤣🤣🤣

**Comment by MrZero1** [comment]
PoprundelHD-ra tippelnék, ő volt ennyire értelmi :D Vagy GT, akár mindkettő, de kitudja melyik okos ez :D

**Comment by Sizarra** [comment]
Lol😂😂😂

**Comment by Sizarra** [comment]
Sok nyomorék 😂😂😂

**Comment by OldCancer** [comment]
![asddd](https://user-images.githubusercontent.com/35972412/35589366-e335f9cc-0603-11e8-8a8e-515328de59f7.png)

**Comment by MrZero1** [comment]
_Retard alert_

**Comment by Sizarra** [comment]
Te vagy a multkori addolo, akivel beszelgettem savon? 😁

**Comment by OldCancer** [comment]
![26814735_158251194955082_3392210700618167799_n](https://user-images.githubusercontent.com/35972412/35589444-27075bb4-0604-11e8-99cb-ac2e1529d369.jpg)

**Comment by OldCancer** [comment]
![ddddo](https://user-images.githubusercontent.com/35972412/35589489-4ba1bdc0-0604-11e8-869b-03a3949b595c.png)

**Comment by OldCancer** [comment]
Nem, @Sizarra

**Comment by Sizarra** [comment]
Szüleid tudják hogy nyomorék vagy? 😁

**Comment by MrZero1** [comment]
Persze, támogatják is

**Comment by OldCancer** [comment]
![17553570_1024169117727741_1164889441121648949_n](https://user-images.githubusercontent.com/35972412/35589601-afb43478-0604-11e8-8f20-7c50ace89cc4.jpg)

**Comment by Sizarra** [comment]
Huha de kis vicces vagy 😂

**Comment by Sizarra** [comment]
Ghost 15 éves létedre ilyeneket csinálni, nem szégyelled el magadat? 😂

**Comment by OldCancer** [comment]
![untitledd](https://user-images.githubusercontent.com/35972412/35589700-fdf809de-0604-11e8-9675-098bd8301946.png)

**Comment by OldCancer** [comment]
Az előbb még NNASH voltam... :D Olyan jó, hogy csak így ráfogjátok bárkire.

**Comment by Zeroapja** [comment]
Zero kár a képtörölgetés, ez olyan mint a szerveren a bannolgatás. Engedd el nem fog menni :D Ha bugokat mondanánk nektek még akkor se lennétek előrébb xd

**Comment by OldCancer** [comment]
Amúgy, egyik se talált.

**Comment by Sizarra** [comment]
Aham ok, kifogytál a dolgokbol guszti? 😂

**Comment by MrZero1** [comment]
Nem törlöm a képeket, nincs jogom, de biztosan ügyes gyerek vagy te :D

**Comment by Sizarra** [comment]
Figyelem hiányos csak egyszerűen 😃

**Comment by Sizarra** [comment]
Ezzel akarja felhívni a figyelmet

**Comment by MrZero1** [comment]
PoprundelHD esetleg :D Ő volt ennyire figyelemhiányos. :D Naponta sírt, hogy banoljam, de csak mert azért, mert a kutya se figyelt rá

**Comment by Zeroapja** [comment]
Nem talált, kérlek próbáld újra.

**Comment by OldCancer** [comment]
![hrre](https://user-images.githubusercontent.com/35972412/35589884-7d848d80-0605-11e8-889c-8ff7d3d0191a.png)

**Comment by MrZero1** [comment]
Dede.

**Comment by OldCancer** [comment]
Nyaljátok meg. :(

**Comment by MrZero1** [comment]
Ha ennyire ferdehajlamú vagy, ott a lehetőség :D

**Comment by Sizarra** [comment]
Sajnálom, hogy nem figyel rá az anyukája/apukája. 🙁

**Comment by MrZero1** [comment]
Csoda, ha van neki anyja vagy apja. :D Eddig csak az enyémmel foglalkozott, lásd a nevét. :D Tök kreatív

**Comment by OldCancer** [comment]
![kep](https://user-images.githubusercontent.com/35972412/35589967-bf290f68-0605-11e8-8e1f-84f793b57b2c.png)

Ne legyetek laposak. Az nem jó.

**Comment by Sizarra** [comment]
Igazad van, lehet nincs neki szuloje :( milyen rossz elete lehet, hogy csak a maseval foglalkozik :(

**Comment by MrZero1** [comment]
Ezekre a képekre élvezkedik, miközben botolja a szervert gondolom. :D Micsoda jó lehet

**Comment by Sizarra** [comment]
Rendezzünk adomány gyujtest: segitsen adoja 1%-aval a mentalisan serult ghostinak es popnak!

**Comment by OldCancer** [comment]
Basszátok már ki ezt a plugint. 

![kep](https://user-images.githubusercontent.com/35972412/35590073-07bc8584-0606-11e8-9e4a-8bd905ca55aa.png)

**Comment by MrZero1** [comment]
Kár lenne ilyenekre költeni.

**Comment by OldCancer** [comment]
Felrakom VPS-re, és mehet 0-24 is. :D

**Comment by Zeroapja** [comment]
Megbocsáss de erre csak ünnepnapokon csapom ki

**Comment by Sizarra** [comment]
Haha csicska vagy 😂

**Comment by MrZero1** [comment]
Minden nap ünnepnap, nem Pop?

**Comment by OldCancer** [comment]
Szerintem ő theodis!

**Comment by MrZero1** [comment]
Egykutya

**Comment by Sizarra** [comment]
Kétlem

**Comment by Zeroapja** [comment]
Szerintem ő Szikszai. Ja hogy rólam van szó

**Comment by Sizarra** [comment]
De nincs bennetek annyi emberseg h elmondjatok

**Comment by MrZero1** [comment]
Szikszainak kicsit több esze van.. :D

**Comment by Sizarra** [comment]
Nemhiszem h szik vagy 😂

**Comment by OldCancer** [comment]
Kyren!

**Comment by MrZero1** [comment]
GT ( :

**Comment by OldCancer** [comment]
Ne bántsátok ghost-ot, ő már leszarja a szervert. :D

**Comment by Sizarra** [comment]
Unalmas az elet ghost?

**Comment by MrZero1** [comment]
Tökmindegy melyik az, unalmas és nem kap elég figyelmet :D

**Comment by Sizarra** [comment]
Olje meg magat 😉

**Comment by Sizarra** [comment]
Na kifogytak a kepekbol

**Comment by MrZero1** [comment]
Támogatom Siza :D

**Comment by akos222** [comment]
csicskák vagytok :D

**Comment by MrZero1** [comment]
Áh, gyorsan ráguglizik :D

**Comment by Sizarra** [comment]
Tudok ongyilkossagi modszereket, kuldjek facebookon? ;)

**Comment by OldCancer** [comment]
![kep](https://user-images.githubusercontent.com/35972412/35590408-13723594-0607-11e8-888f-7767597d112c.png)
![kep](https://user-images.githubusercontent.com/35972412/35590413-1af4a090-0607-11e8-89b2-bdec652cbb4d.png)
![kep](https://user-images.githubusercontent.com/35972412/35590430-26a3975c-0607-11e8-826e-7962293d9516.png)

Ne buzuljatok már.

**Comment by Zeroapja** [comment]
![porn_of_the_dead](https://user-images.githubusercontent.com/35968655/35590448-3659a380-0607-11e8-92c9-c06e811cf9aa.jpg)

**Comment by MrZero1** [comment]
Mondtam, hogy gyorsan gugliznak ki képeket Siza :D Látod látod xd

**Comment by Sizarra** [comment]
Jaja 😂

**Comment by Zeroapja** [comment]
Hát te kérted most meg panaszkodsz?

**Comment by Sizarra** [comment]
Kicsoda 😂

**Comment by Zeroapja** [comment]
Zero

**Comment by Sizarra** [comment]
Na es te ki vagy? 😊

**Comment by MrZero1** [comment]
Ohjaj, én nem kértem xd Siza nevet ezeken a képeken..xd

**Comment by OldCancer** [comment]
Szép volt így a spawn, kérvényezem a visszaállítását!

![kep](https://user-images.githubusercontent.com/35972412/35590740-0a44f12c-0608-11e8-83ac-1e1151550326.png)

**Comment by Sizarra** [comment]
Jo vicces vagy 😂

**Comment by Zeroapja** [comment]
+1 Szavazat

**Comment by MrZero1** [comment]
Kár nektek az élet. Erre is +1 szavazat? : )

**Comment by poma123** [comment]
+1 szavazat @MrZero1 -nek!

**Comment by OldCancer** [comment]
![kep](https://user-images.githubusercontent.com/35972412/35590797-325be184-0608-11e8-8b33-2c2cc55a6bb5.png)
![kep](https://user-images.githubusercontent.com/35972412/35590823-45300204-0608-11e8-9d8a-a40db177a416.png)

Hogyan csinálj jó szervert sok játékossal kezdőszett.

**Comment by Sizarra** [comment]
+1 @mrzero1 -nek

**Comment by akos222** [comment]
Hogyan ne legyen életed? Tutorial by két szerencsétlen

**Comment by AnnaMastersong** [comment]
+1 @MrZero1 Tőlem is :D

**Comment by MrZero1** [comment]
Haha, ennyit erről :D

**Comment by Zeroapja** [comment]
akos sokan vannak itt, kérlek ha szeretnél mondani valamit, vagy valami bántja a szíved akkor öntsd ki nekünk ide, nevekkel megjelölve. Itt elfogadjuk a másságot.

**Comment by Sizarra** [comment]
Felnegyelni oket! 😂

**Comment by Zeroapja** [comment]
@Sizarra azt írták te röhögsz az ilyeneken
![received_1410499532366962](https://user-images.githubusercontent.com/35968655/35591051-f3fb60ee-0608-11e8-8d66-50fea1c38c23.jpeg)

**Comment by akos222** [comment]
Nem az én pici érzéseim szenvedtek el akkora sérülést, hogy hetekig ne tudják feldolgozni, és botolással fejezzem ki azt :D

**Comment by Sizarra** [comment]
Nem vagy vicces 😊

**Comment by Sizarra** [comment]
De ha neked jol esik mesztelen ferfiakat nezni, hajra. Nem itelem el a melegeket c:

**Comment by Zeroapja** [comment]
Hetekig való feldolgozás? Hm. mitől gondolsz te ilyeneket?

**Comment by Zeroapja** [comment]
Siza én sem, tudod a képet csak neked tartogattam :)

**Comment by OldCancer** [comment]
![kep](https://user-images.githubusercontent.com/35972412/35591165-588f43b8-0609-11e8-985b-24c859cc302d.png)

**Comment by akos222** [comment]
abból babám, hogy napjaitok mennek el erre :D látszik mennyire unalmas lehet az életetek

**Comment by Sizarra** [comment]
Ti is feladhatnatok az eletet c:

**Comment by akos222** [comment]
néhány sértődött kisgyerek, akik nem tudnak mit kezdeni magukkal. ezek vagytok

**Comment by MrZero1** [comment]
Szeretethiányos, figyelemhiányos, élettelen gyerekek ezek, akiknek a világ gondja az, hogy Ákos staff lett xd

**Comment by Zeroapja** [comment]
Nektek is napjaitok mennek el a staffkodásra. Mi ezt egy kicsivel másba öljük de ugyanazon a téren. Most, most akkor kinek nincs élete? Ugyanúgy fent vagytok ti is ha még nem tűnt volna fel :D

**Comment by MrZero1** [comment]
Mi hasznos dolgot teszünk, ti pedig szimplán csak nyomorékok vagytok. Vagy nem tűnt fel?

**Comment by akos222** [comment]
Igenám, fent vagyunk, de mi felváltva töltjük el azt az időt a szerveren, amit ti egyhuzamban elbasztok naponta :D

**Comment by OldCancer** [comment]
![kep](https://user-images.githubusercontent.com/35972412/35591275-ae351c84-0609-11e8-919f-5373026439dc.png)
![kep](https://user-images.githubusercontent.com/35972412/35591304-c5c00d8c-0609-11e8-9a0b-0f9b5c5a1628.png)

Elvan a gyerek, ha játszik. :D

**Comment by MrZero1** [comment]
Ha valakinek a neve tükrözi a valóságot (lásd cancer), akkor persze, hogy megköveteli az ilyen dolgot, mint Poma is csinált :D Ismét csak azt írom, hasznos dolgot teszünk, próbálunk az ilyen névtelen férgektől megszabadulni :)

**Comment by Zeroapja** [comment]
Felváltva? Mikor van köztetek aki 7 órát van? Mesélj még

**Comment by akos222** [comment]
Inkább rólatok meséljünk már :D napközben login szerveren olvassátok a privátokat, éjszaka meg feljöttök addolni meg szerencsétlenkedni. emellett a 7 óra fentlét eltörpül szerintem

**Comment by MrZero1** [comment]
Hasznos tagja a közösségnek. Ti pedig haszontalanok vagytok, voltatok és lesztek is. Mert te napi 2-3 órát se tudtál teljesíteni..:D

**Comment by Zeroapja** [comment]
Milyen én? Mit gondolsz te, ki vagyok?

**Comment by MrZero1** [comment]
Egy névtelen senki :D True tho

**Comment by Zeroapja** [comment]
Attól hogy te felvállalod olyan kemény lettél hirtelen?

**Comment by OldCancer** [comment]
Zero, azért ne minecraft-ban keress magadnak barátot. :(

![kep](https://user-images.githubusercontent.com/35972412/35591548-adfc1f5a-060a-11e8-938c-91e168d07696.png)

**Comment by MrZero1** [comment]
Nem, csak ez mutatja meg, milyen ember valójában :D Névtelenül az interneten bohóckodni az a gerinctelenség jele. De nembaj, feltörekvő generáció vagy, ne várjunk mást.

**Comment by MrZero1** [comment]
Wexthory lehetsz, vagy Taro, esetleg mindkettő. Plusz minusz. :D Köszönöm szépen a tanácsodat, nem itt keresek  barátokat. Viszont én is adnék neked egy tanácsot: Ne légy nyomorék.  Ez egy tömör tanács, sokrétegű. :D

**Comment by OldCancer** [comment]
Én is meleg vagyok amúgy, nem olyan nagy dolog az. Elfogadunk téged így @MrZero1. <3

**Comment by akos222** [comment]
Majd, ha lesz benned annyi, hogy a pofádat is add ahhoz, amit csinálsz, akkor beszélhetsz mások keménységéről :D

**Comment by Zeroapja** [comment]
Igazad van te olyan kurva idős vagy, életed kenyerének a felét már megetted nemde?

**Comment by MrZero1** [comment]
Király :D Veled szemben (életkorodat mutatja amit csinálsz) biztosan többet éltem már meg :D

**Comment by Zeroapja** [comment]
![received_921654271345149](https://user-images.githubusercontent.com/35968655/35591963-e76d2922-060b-11e8-9e84-688c37d521de.jpeg)
Magamról nem találtam csak rólatok, bocsi

**Comment by OldCancer** [comment]
Tehát... Először NNASH voltam, aztán Ghost, most pedig Wex? Naon megborított ez a cucc dylym, aggyámá nekem is.

**Comment by akos222** [comment]
senki vagy

**Comment by Zeroapja** [comment]
@OldCancer szerintem Andris vagy

**Comment by OldCancer** [comment]
Nem is, mert Herobrine... :(

**Comment by MrZero1** [comment]
Sherox is lehetsz, ő is nyomorék :DDDDDDDD ő utálta a legjobban Ákost, pedig nem is ismeri a nub

**Comment by Zeroapja** [comment]
Zero szerintem ne lottózz

**Comment by MrZero1** [comment]
Van rá pénz, miért ne 
nekem nem kell minemarket rendeléseket csalnom, ugye Pop?:D

**Comment by akos222** [comment]
nem kéne, ha nem lennétek full töketlenek

**Comment by Zeroapja** [comment]
Most válaszolnék igenlően, de sajnos nem Pop vagyok, sad :(

**Comment by MrZero1** [comment]
Pedig ott a ponty, amit küldtél kép

**Comment by OldCancer** [comment]
Hax
![kep](https://user-images.githubusercontent.com/35972412/35592646-f489f700-060d-11e8-853d-24fabc1a6ae1.png)

**Comment by akos222** [comment]
húha nagyon profik vagytok :o
![hahayx](https://user-images.githubusercontent.com/20407410/35593129-6026378e-060f-11e8-873b-0f6528bf31c0.png)
