### ISSUE TITLE
AntiJoinBot

### ISSUE THREAD

**Issue by poltergeist84** [andris155/TheOld-Crafters#1773]
Sziasztok!
Annak idején egy nagyobb szerveren segédkonfigoskodtam.
Egy [AntiJoinBot](https://dev.bukkit.org/projects/easy-anti-join-bot-proxie) nevű plugint használtunk proxy szűrésre. Nem fejlesztik egy ideje, de talán jó lesz ehhez a verzióhoz is. Vagy találtok valami hasonlót.
Hozzá lehet adni a feltétlenül proxy-n keresztül csatlakozókat a fehérlistához, úgyhogy megoldja a bot problémát - legalábbis nálunk jó volt erre a célra.

Üdv,
p84

**Comment by andris155** [comment]
Nincs értelme. Naponta nyílnak új proxy-k.
