### ISSUE TITLE
Pipe - hirdetés - ID

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#1774]
Szia, nem tudom lehet-e valamit kezdeni vele, gondoltam jelentem, hátha.
Szóval az ID-ket hirdetésnek veszi, ezért nem tudják a játékosok használni a Pipe-t. 
Nem minden esetben, szerintem a több ID-nél csinálja csak ezt. 
![pipe](https://user-images.githubusercontent.com/29709854/35593661-c72841ba-0610-11e8-8874-d758f29f3b75.png)

**Comment by andris155** [comment]
javítva
