### ISSUE TITLE
elit rang 6 nap-ig

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#1775]
mutatom a képeket, az elit rangom elszállt 6 nap alatt, a minemarket azt jelzi hogy 
aktív, de szerveren sima tag+ vagyok (og-s tag+, ezért az az alap nálam)
a minemarketes kép kommentben
![2018-01-31_17 04 09](https://user-images.githubusercontent.com/29951969/35634433-fc4985fc-06ab-11e8-91a0-146b84a923ea.png)

**Comment by skrisz0101** [comment]
áhh nem tudom ide behelyezni telórol a készített minemarket fotót, mert csak telóval tudtam lefotózni, András, ha kell elküldöm privibe

**Comment by andris155** [comment]
Nem kellene egymásra venni 2 ugyan olyan rangot.

**Comment by skrisz0101** [comment]
Miért mondja mindenki ezt?
Lejárt az elitem, és utána vettem, mondjuk mindegy mert próbaidőszak segítő létrem xd

**Comment by skrisz0101** [comment]
Próbaidős*

**Comment by Sheep04** [comment]
"próbaidőszak"
