### ISSUE TITLE
Rossz malackaja kiírás a boltban

### ISSUE THREAD

**Issue by Baazsaa** [andris155/TheOld-Crafters#178]
Nos, a minap lettem figyelmes, a (szerintem figyelmetlenségből eredő) problémára. Mivel nekem a MyPetem malac, így csak azt tudom mondani, persze lehet, hogy a többiben is van hiba.

A malac répát eszik, ellenben a boltban céklát ír. Kipróbáltam mind a kettőt, gondolva arra, hogy lehet mind a kettő remek étel neki, de kizárólag a répát fogadta el.

**Comment by andris155** [comment]
javítva.
