### ISSUE TITLE
"Addolható" növények

### ISSUE THREAD

**Issue by daemonic01** [andris155/TheOld-Crafters#1788]
Hello!

Épp az imént - az automata farmok építése közben - jöttem rá, hogy **kreatívból lehetőség van a búzamagot, a répát, a krumplit, és a céklamagot átvinni a survival inventoryba.** A dolog onnét jött, hogy a falusiak által működtetett farmjaim többsége a blokkfrissülést használja arra, hogy a falusiak eldobják a begyűjtött termést. A falusiak, akiknél étel van, adnak belőle azoknak a falusiaknak, akinél nincs, de a farm ezt a kidobott ételt elvezeti és így kapom meg én. Na most ahhoz, hogy a farmer mindíg megtalálja ezt az éhes falusit, utóbbi elé egy olyan megművelt földblock kerül, amely vizet kap, de elegendő fényt nem, így mikor odamegy a farmer, hogy elvessen ott valamit a korábban említett növények közül, oda és visszaútján is rálép egy nyomólapra, amely a körülötte lévő blockokon frissülést idéz elő, így hiába vetette el a cuccot, az azonnal kiugrik a földből, így ez egy csekély veszteség mellett, de hatékonyan működik.
Na most, ha ezt használva, a fényhiányos blockra kreatívban ültetünk el valamit, majd előidézünk egy frissítést, vagy megvárjuk míg magától frissül, a növény, vagy annak magja kipattan, és survival módban felvehetővé válik.

Bár meggazdagodni iszonyat macerás és hosszadalmas folyamat lenne a módszerrel, a visszaélés esélye ettől függetlenül még adott.

**A megoldás** véleményem szerint az lenne, ha a búza és cékla magját, valamint a krumplit és a répát nem lehetne lerakni kreatívban, hiszen ez már önmagában is csalás lehetne. Ugyan ez igaz a cukornádra is, de ott az előbb megfogalmazott "addolási mód" nem működik.

**A tesztelés során megszerzett illegális itemek megsemmisítésre kerültek.**

**Üdv.:** daemonic01

**Comment by daemonic01** [comment]
Hát...van rá esély, estefelé vagy legkésőbb holnap teszek egy próbát.

**Comment by poltergeist84** [comment]
[https://www.dropbox.com/s/yiqt6oymdg0z3wz/bug_d%26p_seedadding.wmv?dl=0]Ezen(url) a videón jól látszik a művelet. ;-)

**Comment by poltergeist84** [comment]
[Ezen](https://www.dropbox.com/s/yiqt6oymdg0z3wz/bug_d%26p_seedadding.wmv?dl=0) a videón jól látszik a művelet.

**Comment by andris155** [comment]
Jelentve a fejlesztőnek.

**Comment by andris155** [comment]
Elvileg javítva.

**Comment by andris155** [comment]
330 OCD
