### ISSUE TITLE
Spawn pláza hiba

### ISSUE THREAD

**Issue by Sheep04** [andris155/TheOld-Crafters#1789]
Üdv!
Nemrég találtam meg ezeket a spawnos plázákat amik emeletesek. Kibéreltem egyből kettőt, de nem tudtam építeni egyiken se.
![2018-02-03_10 20 45](https://user-images.githubusercontent.com/34780638/35765817-769eba08-08cc-11e8-8650-1e05540a4136.png)
![2018-02-03_10 21 20](https://user-images.githubusercontent.com/34780638/35765819-7fe70660-08cc-11e8-846e-84f4f03e8517.png)
Nem tudom mennyit jelent ez, de megnéztem fakarddal, az alső szinten Poma a tag, felső szinten én (meg poma), tulaj "none", szóval senki.
![2018-02-03_10 21 29](https://user-images.githubusercontent.com/34780638/35765837-e2f3f56a-08cc-11e8-837c-aef22a3836f0.png)
![2018-02-03_10 21 40](https://user-images.githubusercontent.com/34780638/35765840-e8303ac0-08cc-11e8-828c-a79cf7830a11.png)

Esetleg egy zone flag a hiba, vagy valami más?
Válaszodat előre is köszönöm,
Sheep04, avagy Sanyi, a vízálló bárány!

**Comment by andris155** [comment]
Egy Admin-t keress fel ezzel a szerveren.

**Comment by poma123** [comment]
Javítva.
Köszönjük a hibajelentést!

**Comment by telapoittvan** [comment]
noobs
