### ISSUE TITLE
Aukció + krea védelem + teli inv = felvehetetlen item

### ISSUE THREAD

**Issue by Kronox12** [andris155/TheOld-Crafters#179]
Geb vett 500 db tojást aukción. 18x16, így adta az invjébe, 18 db 16-os stack tojás. Viszont nem volt elég helye mindre, így a rendszer a maradék tojást a földre dobta. A probléma az, hogy a földre dobott item kreatív védelemmel van ellátva, én se tudom felvenni, ő se.

**Comment by andris155** [comment]
Jelentett aukció bug - nincs köze a kreatív védelemhez.
