### ISSUE TITLE
Hová lett a pay és a ci parancs megerősítés?

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#1790]
Szia.

Tegnap vettem,vettük észre, hogy a pay illetve a ci parancsoknál már nem szükséges a megerősítés (tehát elég egyszer beírni a parancsot).

**Comment by andris155** [comment]
Alapból ki van kapcsolva. Sajnos csak paranccsal lehet újra engedélyezni.

**Comment by andris155** [comment]
https://github.com/EssentialsX/Essentials/commit/fcc7c3af78d664b259685044531bec1d323a3088
