### ISSUE TITLE
Slimefun a weboldalon

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#1792]
Szia. Nem aktuális, így (gondolom) felesleges kint lennie. 
![sf](https://user-images.githubusercontent.com/29709854/35816430-f9dc0df6-0a9a-11e8-8c74-65746f52b69c.png)

**Comment by andris155** [comment]
Javítva!
Köszönjük a hibajelentést!

**Comment by telapoittvan** [comment]
@MrZero1  buggos a szero
