### ISSUE TITLE
SurvivalGames bug

### ISSUE THREAD

**Issue by asdlol911** [andris155/TheOld-Crafters#180]
Üdvözlet!

Szeretnék egy bugot jelenteni, amit véletlen fedeztem fel:

TP ellenőrzést végeztem, inventorymban csak 1 stack OldGold volt. Rá portoltam véletlen az egyik SG-n részt vevő játékosra aki éppen a halálba zuhant, tehát én is le estem vele együtt és meghaltam. Itt jön a bug része, hogy amikor visszaportoltam (/back) 2 stack OldGold volt ott utána, tehát így az SG miatt a szerver készített belőle még egy stacket (?). Később ezt teszteltem az általam készített Old Íj javítóval ellátott másolatával és azt is duplázta.

~asdlol911

**Comment by andris155** [comment]
Normális ember elvileg be se jut oda tp-vel, se backel.

**Comment by asdlol911** [comment]
Normális ember nem, de aki rendelkezik /tp-vel már be tud oda jutni

**Comment by andris155** [comment]
Nem sikerült reprodukálni a hibát.
