### ISSUE TITLE
Érdekes bug

### ISSUE THREAD

**Issue by Treuce** [andris155/TheOld-Crafters#181]
Ládaboltból vettem szenet és tele volt az inventorym viszont nem volt rajtam mellvért és nadrág, ennek a 2 dolognak a slotjába került 2 stack szén. Nem vagyok biztos benne hogy máshogy is lehetséges-e de így történt szerintem.

**Comment by andris155** [comment]
Jelentett bug.
A Chestshop új verziója javítja majd.
