### ISSUE TITLE
Szerverfájl hiba

### ISSUE THREAD

**Issue by 26emeleteshajobol** [andris155/TheOld-Crafters#1810]
https://www.planetminecraft.com/project/slime-lobby/
https://www.planetminecraft.com/project/medieval-lobby-4087938/
https://www.planetminecraft.com/project/jungle-spawn-with-some-parkour-etc/

~Zero

**Comment by andris155** [comment]
Az egész szerver világot felrakhatnátok már akkor. Meg egy térképet is csinálhatnátok róla. :)

**Comment by 26emeleteshajobol** [comment]
Jó ötlet!

**Comment by skrisz0101** [comment]
ezt azért csinálod mert....?
