### ISSUE TITLE
MobArena 

### ISSUE THREAD

**Issue by poma123** [andris155/TheOld-Crafters#1815]
Szia Andris!
Azt kellene beállítani, hogy a _Halhatatlan_ MobArena class-t V.I.P. rangtól lehessen lehívni, és a _Hiperugrás_ MobArena class-t pedig Prémium rangtól. 
Továbbá, majd kellene a jelenlegi `config.yml` fájl, újragondolni a megmaradt `old` arénák nevét.

_Üdv, [Admin]poma123_

**Comment by andris155** [comment]
Kész, az aréna nevekre pedig várom az ötleteket.

**Comment by poma123** [comment]
Az old4 neve legyen Kert, az old5 neve Híd, és az old6 pedig Falu. Kösziii
