### ISSUE TITLE
Rangok és jogok v3

### ISSUE THREAD

**Issue by andris155** [andris155/TheOld-Crafters#1816]

**Comment by Sheep04** [comment]
Ez azt  jelenti, hogy új rangok lesznek?

**Comment by andris155** [comment]
Inkább a meglévők jogait akarom rendezni és optimálizálni. Kicsit káoszos, mert néha csak a joglista végére írtam az újakat.

**Comment by andris155** [comment]
Ettől függetlenül egyébként új rang neveket lehet jó lenne kitalálni.

**Comment by andris155** [comment]
optimalizálva, és rendezve.
