### ISSUE TITLE
plots.admin.interact.road

### ISSUE THREAD

**Issue by mdtank** [andris155/TheOld-Crafters#1817]
Alulról a második sor a lényeg: A következő engedélycsomag hiányzik: plots.admin.interact.road
A hibaüzenet természetesen helyes, de át lehetne fogalmazni/eltüntetni a játékos elől.

![oldmc](https://user-images.githubusercontent.com/36288065/36010857-f3d2adbe-0d53-11e8-8e04-415dc22e20d0.png)

**Comment by andris155** [comment]
Javítva!
Köszönjük a hibajelentést!
