### ISSUE TITLE
SurvivalGames stats

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#1819]
Szia. Az /sg stats név parancsnál nullát ír. (Multons az egyik, ha nem a legjobb SG-s játékos, azért az ő neve van a képen) 
![sgstats](https://user-images.githubusercontent.com/29709854/36043204-c875fa88-0dce-11e8-8dcd-40b1898533d1.png)

**Comment by MrZero1** [comment]
SurvivalGames világban és más világban is 0.

**Comment by andris155** [comment]
Ez eddig működött?

**Comment by skrisz0101** [comment]
Nem tudni

**Comment by andris155** [comment]
Sajnos ez nem működik. Nem tudtam rájönni én sem miért. :/

**Comment by andris155** [comment]
Később lehet lesz újabb és jobb plugin.
