### ISSUE TITLE
Tölcsér,Falusi arány módosítás

### ISSUE THREAD

**Issue by Dreed1992** [andris155/TheOld-Crafters#1822]
Üdv.
Sav-on akik már karcolják a tölcsér max darabszámát nagy sziget szinttel, jó lenne legalább 10el növelni,vagy a sziget szintjével párhuzamosan. A max 30 állatot is jó lenne, mert ha túllépi, véletlenszerűen falusiakat töröl elsőnek. amit nem könnyű összeszedni könyvtárosnak. Azt is észrevettem,ha lovas csontik spownolnak  viharok közben,azt is beleszámolja és megint csak törlődik a falusi.(a mob meghal de a ló marad)
+ Ötlet ládival kezdeni valamit mert tele dobálják szeméttel.
++Netherbe elég bajos az átjutás mivel Fagyás,láva és csontváz spowner fogadja őket. Teljes dia szettben is macerás az átjutás.
A csonti ,szellem,és az őrláng spowner is a telek határán van,így kiépíteni azt is nehézkes.valamint ott a mobok védett zónába spownolnak. ha másképp nem megoldható,akkor szerintem jó megoldás lenne ha lehetne netheren belül áthelyeztetni.
Üdv. -Agronaut.

**Comment by andris155** [comment]
A limit növelve.

**Comment by andris155** [comment]
204 OCD
