### ISSUE TITLE
Hogyan csinálj Murderből Paintballt 1 lépésben? Hát így! (Nem clickbait)

### ISSUE THREAD

**Issue by Sziatoc** [andris155/TheOld-Crafters#1823]
Üdv. Véltem felfedezni egy másolást a szerveren. Az egyik itteni Paintball map (név szerint Tábor) megegyezik egy külföldi szerveren található Murder mappal, talán csak annyi a különbség hogy az itteninek nagyobb a kiterjedése. A fal, a lakhelyek külseje és belseje illetve a talaj is megeggyezik, a helyek kialakítása is ugyanaz. Képek a külföldi mapról:
![received_1812539708818942](https://user-images.githubusercontent.com/36346292/36067875-1526f96e-0ec8-11e8-8171-82dcd76a6d70.png)
![received_1812539915485588](https://user-images.githubusercontent.com/36346292/36067877-1dbe4a50-0ec8-11e8-818d-54821ff4b3b4.png)
![received_1812539705485609](https://user-images.githubusercontent.com/36346292/36067880-24cb2c28-0ec8-11e8-8298-57bd59b74195.png)

Üdvözlettel,
Anonim senki

**Comment by andris155** [comment]
Biztosan inspirálta az építőket a pálya. Ilyen előfordul.
