### ISSUE TITLE
Old Múzeum hiba

### ISSUE THREAD

**Issue by Saii1** [andris155/TheOld-Crafters#1825]
Ellopták a soulbound szettet a múzeumból! /warp kiállítás ott van egy lehet kopizni

**Comment by andris155** [comment]
Valakinek meg tetszett aztán elvitte? XD Egyébként ez hol van a múzeumban?

**Comment by poma123** [comment]
Volt egyáltalán soulbound szett az oldmúzeumban? xD Hogy vitte volna el bárki is, ha lett volna, és le van védve?

**Comment by MrZero1** [comment]
Obstruction blokk törölte, szerencsére már nincs ilyen. Pótolom.
