### ISSUE TITLE
Kódos-kulcsos ajtó mod ami talán lehetne plugin

### ISSUE THREAD

**Issue by Sheep04** [andris155/TheOld-Crafters#1826]
Üdv!
Találtam egy modot mellyel le lehetne zárni szóval,, vagy pin kóddal az ajtót.
Nagyon a pluginokhoz (meg a modokhoz) nem értek, de remélem eme modot lehet használni a szerveren, feldobná egy picit és akkor nem kell lock tábla az AJTÓKRA.
A mod: http://www.9minecraft.net/key-and-code-lock-mod/
Sheep04, avagy Sanyi, a vízálló bárány!

**Comment by andris155** [comment]
Nem futtatunk mod-os szervert.

**Comment by Sheep04** [comment]
Illetve redstone rendszereknél pluszban segíthet.
Pl.: nyithatő kerítés (természetesen kóddal).

**Comment by Sheep04** [comment]
okés
