### ISSUE TITLE
Nem működő bancidbyname parancs a PEszerverenken

### ISSUE THREAD

**Issue by NikeboyHU** [andris155/TheOld-Crafters#183]
A '/bancidbyname <név>' parancs nem mindig müködik a PE szervereken, és elég gyakran nem ír kis semmit. A hiba helye ismeretlen számomra, mivel nincs hiba, se log róla.

**Comment by andris155** [comment]
/bancidbyname online játékos - tesztelve tökéletesen működik.
(offline játékossal nem működik)
