### ISSUE TITLE
hiba

### ISSUE THREAD

**Issue by elliot2018** [andris155/TheOld-Crafters#1830]
Szombaton we-ztek nekem és másnapra kicserélődött we más blokkra és a blokkok szabálytalanul állnak.
Tegnap leraktam a seprűmet egy dzsungel fa lombjára de eltűnt .

**Comment by andris155** [comment]
Nem találtam elliot névre seprű vételt. A wordedit-tel kapcsolatban keresd fel az adminisztrátorokat.

**Comment by Sheep04** [comment]
Nem vehette másik játékostól?
