### ISSUE TITLE
oldcrafters.net/parancsok

### ISSUE THREAD

**Issue by Sheep04** [andris155/TheOld-Crafters#1831]
Üdv!
A weboldalon jártam, mikor feltűnt, hogy a /auc parancs még mindig ott van, mikor ki lett véve.
Illetve a MobAréna, hiszen a mobaréna nevek nermég megváltoztak.
Sheep04, avagy Sanyi, a vízálló bárány!
behehee

**Comment by andris155** [comment]
204 OCD

**Comment by andris155** [comment]
Javítva!
Köszönjük a hibajelentést!
