### ISSUE TITLE
UltraCosmetics magyarosítás [OCD-ért]

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#1833]
Szia.

Királyak az új lobby-s effektek, szükséges lefordítani ezt? Ha van rá mód, persze.

**Comment by andris155** [comment]
Le lehet fordítani igen, de elég sok szöveg.

**Comment by andris155** [comment]
Kitől?

**Comment by akos222** [comment]
bárkitől, nem válogatok

**Comment by akos222** [comment]
adc lang fájlt?

**Comment by andris155** [comment]
https://github.com/andris155/TheOld-Crafters/tree/master/Ford%C3%ADt%C3%A1sok/UltraCosmetics

**Comment by akos222** [comment]
holnapra megvan na nem kell bántani

**Comment by akos222** [comment]
sorry mégse
majd ha lesz időm foglalkozok vele
ha valaki akarja csinálhatja

**Comment by poma123** [comment]
https://github.com/andris155/TheOld-Crafters/commit/bc79f2eb7c9294cf8c2775058bedc9d9070af73c
