### ISSUE TITLE
Jármű üzemanyagának töltése miközben nem az én tulajdonom

### ISSUE THREAD

**Issue by Sheep04** [andris155/TheOld-Crafters#1834]
![2018-02-15_19 25 26](https://user-images.githubusercontent.com/34780638/36274420-0552cdec-1288-11e8-8172-ef0b2eff88de.png)
![2018-02-15_19 25 29](https://user-images.githubusercontent.com/34780638/36274429-0a325a62-1288-11e8-9632-6bd0089671f8.png)

**Comment by Sheep04** [comment]
Bocsi, a töltésről nem tudtam fotót készíteni.

**Comment by andris155** [comment]
Ki töltené csak úgy más járművét, vagy az miért baj? :D
