### ISSUE TITLE
Tank "életre kel", ha menet közben váltunk skint a /skin paranccsal

### ISSUE THREAD

**Issue by Sheep04** [andris155/TheOld-Crafters#1835]
![2018-02-15_19 30 50](https://user-images.githubusercontent.com/34780638/36274506-39359e78-1288-11e8-8471-42ca92009e1b.png)
![2018-02-15_19 31 52](https://user-images.githubusercontent.com/34780638/36274512-3d575a32-1288-11e8-8c5e-969364c76392.png)

![2018-02-15_19 37 27](https://user-images.githubusercontent.com/34780638/36274526-452eb4a8-1288-11e8-8080-6bbee71fa36b.png)

**Comment by andris155** [comment]
Majd holnap letiltom a parancsot.

**Comment by andris155** [comment]
kész

**Comment by andris155** [comment]
204 OCD
