### ISSUE TITLE
Weboldal - SavSziget szabályzat

### ISSUE THREAD

**Issue by poma123** [andris155/TheOld-Crafters#1837]
Szia. Felmerült már, hogy addig nem igazán érvényes a SavSziget szabályzata (Már tavaly október felé készen volt.) ameddig nincsen fent a weboldalon. (https://oldcrafters.net/szabalyok)
Most csatolom a SavSziget szabályzatának különbségeit a Survival szabályzatához képest: [Szabályzat](https://github.com/poma123/TheOld-Crafters/commit/ef89807fbef6124b3e3490f3a5702ce2f3961a8d#diff-a4f86f7bfc24194b276c22e0ef158197).

Üdv, poma123

**Comment by andris155** [comment]
Fejlesztve.
