### ISSUE TITLE
SavSziget Kemence értéke.

### ISSUE THREAD

**Issue by Dreed1992** [andris155/TheOld-Crafters#1838]
Üdv.
Sav szigeten a kemence értéke 10 pontot dob a sziget szintjén(az obszidián értéke szintén 10).
Mellékelten csatolom a képet, Sokan felhalmozzák, a sziget alját kitöltik vele,így hatalmas szigetszintet emelhetnek, szimpla zúzottkő segítségével rövid idő alatt.
![nevtelen](https://user-images.githubusercontent.com/35728669/36317459-6f4e54d6-133d-11e8-96f4-b307d07a3945.jpg)

Üdv. -Agronaut

**Comment by poma123** [comment]
Ez mostani kép? A fordítás már bőven több, mint 2 hete javításra került.
![image](https://user-images.githubusercontent.com/25465545/36319719-1c3b1016-1344-11e8-8f4d-1ffee259edc4.png)

Egyébként valós a hiba, majd megnézem mennyi pont lenne az ideális.

**Comment by poma123** [comment]
Javítva. Köszönjük a hibajelentést!
A pont maradt 10, de 10 kemence lerakása után nem számolja bele a többi kemence pontját a sziget szintbe.
