### ISSUE TITLE
MCMMO Fűrészes csapás vérzése átmegy MyPetre

### ISSUE THREAD

**Issue by yghrt** [andris155/TheOld-Crafters#1839]
Üdv, a probléma az lenne hogy az MCMMO-s fűrészes csapás vérzése procol a mypetre is, ha mellette van a körzetében egy olyan mob amire lehet vele sebezni. Mellékelek egy videót. 
https://www.youtube.com/watch?v=umRuv5ZFyrM

-yghrt

**Comment by andris155** [comment]
Sajnos a MyPet-et nem támogatja a plugin.
