### ISSUE TITLE
SkyPvP Rang Bug

### ISSUE THREAD

**Issue by geri5200** [andris155/TheOld-Crafters#184]
Mivel SkyPvP-n Killekből volt egy Elit rangom és arra rávettem egy Prémium rangot Old Goldból akkor ugye bár annak kellet volna történnie, hogy a Prémium ranggal együtt az Elit is lejár. De ez nem így történt és valami Bug folytán még mindig Elit vagyok.

**Comment by andris155** [comment]
A killeknél nincs elvételi parancs norrys-nak kellet volna elvenni.
