### ISSUE TITLE
Beváltó

### ISSUE THREAD

**Issue by Blen72** [andris155/TheOld-Crafters#1840]
A beváltónál vagy elírás van vagy rosszul lett megcsinálva a falusi.
Képek:

![kep](https://user-images.githubusercontent.com/35607857/36322610-416b3758-134e-11e8-98a7-741a28124e5a.png)

![kep](https://user-images.githubusercontent.com/35607857/36322651-7159f77e-134e-11e8-8e19-2a6840ca998b.png)

(v5v6v7v8v9 / Blen72)

**Comment by andris155** [comment]
Valentin napig volt ennyi.
