### ISSUE TITLE
/seen

### ISSUE THREAD

**Issue by Blen72** [andris155/TheOld-Crafters#1841]
Kitiltva: Nem használt multiaccount.

Szerintem ennek így kéne kinéznie:
Kitiltva: Multiaccountot használt.
Vagy valami ilyesmi.
Kép (/seen Andris):
![kep](https://user-images.githubusercontent.com/35607857/36323502-684d0ce0-1351-11e8-9296-3075cd3deed9.png)

Ha úgy jó hogy nem használt multiaccount akkor is kell egy -ot (multiaccountot).
(v5v6v7v8v9 / Blen72)

**Comment by poma123** [comment]
A ,,nem használt" itt tulajdonságot jelöl, tehát nem használt karakter. Egyébként az éppen büntető staff határozza meg a büntetés indokát.
