### ISSUE TITLE
/warp levédés-nél játékos által használható flagek egy részére nincs jogosultság.

### ISSUE THREAD

**Issue by yghrt** [andris155/TheOld-Crafters#1842]
A /warp levédés-nél található kiírás szerint, a balra található flagek közül ami a játékosok számára elérhető, néhány mégsem érhető el.

Játékos által használható flagek:
- chest-access
- damage-animals
- deny-spawn
- enderpearl
- interact
- mob-spawning
- potion-splash
- pvp
- use
- vehicle-destroy
- vehicle-place
![flag1](https://user-images.githubusercontent.com/35996682/36356611-ab214640-14f4-11e8-9e1e-f892a157ce81.png)

Játékos által nem használható flagek:
- pistons
- block-place
- block-break
- entity-painting-destroy
- entity-item-frame-destroy
- build

Videó a jogosultság hiányáról: https://www.youtube.com/watch?v=fvyVJ24IGcs

**Comment by andris155** [comment]
Javítva!
Köszönjük a hibajelentést!

**Comment by andris155** [comment]
330 OCD
