### ISSUE TITLE
Föld, homok addolás mcmmoval

### ISSUE THREAD

**Issue by akos222** [andris155/TheOld-Crafters#1843]
Kreában lerakott földet, homokot, és ehhez hasonló blockokat az mcmmo-s tombolással ki lehet szedni survivalban
-akos_

**Comment by andris155** [comment]
Videó kellene erről.

**Comment by akos222** [comment]
Délután leszek gépközelben, megcsinálom majd.

**Comment by akos222** [comment]
https://www.youtube.com/watch?v=-z__NmlhT80

**Comment by andris155** [comment]
Nem lehet javítani. De szerintem nem ebből gazdagszik meg senki.

**Comment by andris155** [comment]
204 OCD
