### ISSUE TITLE
Zone expand kiírás hiba

### ISSUE THREAD

**Issue by akos222** [andris155/TheOld-Crafters#1844]
Zone túl nagy felfelé expandolásánál azt írja, hogy "Nem mehetsz a bedrock alá", túl nagy lefelé expandolásnál pedig "nem mehetsz a magasságlimit fölé". fordítva kéne lennie
-akos_

**Comment by andris155** [comment]
Most jó?

**Comment by akos222** [comment]
Délután leszek gép közelben, megnézem majd.

**Comment by akos222** [comment]
már jó

**Comment by andris155** [comment]
Javítva!
Köszönjük a hibajelentést!
