### ISSUE TITLE
igény szörny spawner-re.

### ISSUE THREAD

**Issue by Dreed1992** [andris155/TheOld-Crafters#1845]
Üdv. 
Rengetegen jelezték hogy igény lenne mob spawnerekre savon. az állatok benn vannak,de sokakat érdekelne szellem,wither csontváz,sima csontváz,és őrláng is. illetve a kérdés is felmerült ,hogy ha lenne,mennyit rakhatnának le a szigetre? 
A másodlagos pedig hogy eventen az acid money már nem vonza a játékosokat,hogy ezügyben is lehetne tenni valamit.
Válaszotokat előre is köszönöm!
Üdv. Agronaut

**Comment by poma123** [comment]
A szörny spawnerek szerintem jó ötlet minemarketre. @andris155 

Az AcidMoney jövőjéről pedig majd beszélni fogunk.

**Comment by andris155** [comment]
Pontosan milyen spawner-ek legyenek amik a játékélményt sem teszik azért tönkre?

**Comment by poma123** [comment]
Zombi, Pók, Csontváz szerintem.

**Comment by andris155** [comment]
Ezeket beraktam.

**Comment by Dreed1992** [comment]
+ Igény lenne őrláng és wither csontváz spawnerre is.
