### ISSUE TITLE
Weboldal - SavSziget Szabályzat (+ Tiltott Gépek)

### ISSUE THREAD

**Issue by poma123** [andris155/TheOld-Crafters#1846]
Szia Andris. Egy olyan régebbről ismerős szabály történt átalakításra, amely az AFK gépekkel volt kapcsolatos. Viszont, ez a szabály nem volt benne a szabályzatban, ezért átbeszéltük a dolgot, és döntöttünk.
Itt található a szabályzat legutóbbi változtatása: [Szabályzat](https://github.com/poma123/TheOld-Crafters/commit/cb3bd089aa6c187dea4b181521c85daa446db3be#diff-a4f86f7bfc24194b276c22e0ef158197)

Üdv, poma123.

**Comment by andris155** [comment]
Megváltoztatva.
