### ISSUE TITLE
A WorldEdit, és a lusta játékosok

### ISSUE THREAD

**Issue by poltergeist84** [andris155/TheOld-Crafters#1847]
Üdv Mindenki!

Mint sokan tudjátok, nemrég tiltásra került a szerveren az adminos WorldEdit segítség a játékosok számára.
Ennek oka az ellustulásunk volt, mivel sokan egyszerűbb feladatokra is admint kértek meg, hogy fill-eljen, vagy töröljön, stb. Emiatt abszolút érthető is a büntetés, mivel az Adminoknak is nyilván van jobb dolguk, mint ilyen piszlicsáré dolgokkal foglalkozni.
Viszont azoknak, akik nagyobb projektbe vágnák a fejszéjüket (ásójukat, csákányukat, kapájukat, etc...) nagyon hiányzik ez az opció. Köztük nekünk is daemonic01-gyel. Épp [guardian farmot](https://user-images.githubusercontent.com/35973839/36517915-85ef5a5a-1784-11e8-8d88-0c9144306582.jpg) terveztünk építeni, ami - valljuk be - az ominózus segítség nélkül elég brutális feladat. :( A lényegi része készen van WorldEdit nélkül is, de a spawn zóna szűkítéséhez szükség lenne 4 hatalmas falra, és a víz levegőre cserélésére a zölddel jelölt részről (lásd a képen) ami ugyan nem megoldhatatlan feladat, de sok időt (értsd: órákat) megspórolna nekünk a segítség. Utána a felső dekorációval már elboldogulnánk, de így csak feleslegesen áll az amúgy már működőképes, és több funkciós épület a víz alatt.

Bátorkodnék javasolni valamit. Részemről azt tartanám megoldásnak, ha a WE-t vagy ranghoz kötnétek, vagy fordított arányosságban kerülne pénzbe, OCD-be, vagy akár XP-be. (értsd: kis projektek nagyon drágán, hogy ne érje meg igénybe venni, de nagyobbak, vagy indokoltak pedig valamivel olcsóbban) Esetleg a kettőt kombinálva, hogy mindenki jól járjon.

Nekünk nagyon fontos volt ez a segítség, hiszen sem a Spleef Arénánk, sem a tornyunk nem készült volna el soha, ha ez nincs.  (képek a facebook csoportban)

Kérlek Benneteket, kedves Vezetőség, hogy gondoljátok át újra ennek a lehetőségnek a rendelkezésünkre bocsájtását.

Köszönettel,
poltergeist84

**Comment by andris155** [comment]
Az Admin-okkal beszélj ezzel kapcsolatban a szerveren.
