### ISSUE TITLE
OldCrafters ''szerver szétkúrás''

### ISSUE THREAD

**Issue by StromeX123** [andris155/TheOld-Crafters#1848]
Üdv OldCrafters.net.

Felettébb szokatlan problémám van.
Kép megtalálható itt: https://cdn.discordapp.com/attachments/405005172259946497/416189810978324491/28312917_561122950921111_801572253_o.png

A mai napon megtekintettem a régi lobby szervermet és mikor felléptem rá az fogadott ami a képen látható.
Ismerem az oldcrafterst és tudom, hogy nem tenne ilyet, viszont ez ronthat a hírnevének.

Mivel a régi developerem kilépett töllünk aztán csak neki volt * joga a 2 hónapja meg nem tekintett lobby szerveren valószínüleg õ tehette.
Némi információ rólla:

Jelenlegi szerver: WoodCraft
Pozíció: Developer
Játékosneve: Skyvko6607
Életkora: 16

Ezt az egészet szeretném megbeszélni a vezetõséggel, szeretném ha ez a kép nem látna napvilágot.
Viszont ez az oldcrafters partnerére hozhat szégyent a WoodCraftra.

Választ elõre is várom!

Üdvözlettel:
ShadowCraft.hu Vezetõség

**Comment by andris155** [comment]
Bárki csinálhatta. Ehhez nekünk nincs közünk. Leginkább a te hibád ha tudtak ilyet csinálni.
