### ISSUE TITLE
SurvivalGames világ - Bájital Effektek

### ISSUE THREAD

**Issue by poma123** [andris155/TheOld-Crafters#1849]
Szia Andris. Felmerült egy csalási lehetőség az eventeken, ami ugye nem megengedett, viszont nincsenek folyamatos ellenőrzés alatt a staff nélküli eventek, ezért bájitallal nagyon könnyen előnyt lehet szerezni. Van arra lehetőség, hogy  a bájital használata a SurvivalGames világban letiltásra kerüljön? Befolyásolja ez a letiltás a SurvivalGames minigame bájital használatát? (Mivel egy világban vannak az eventek és a survivalgames arénák is)

Üdv, poma123

**Comment by andris155** [comment]
Nem tudok ilyen WorldGuard flag-et.
