### ISSUE TITLE
Kreatív védelem

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#185]
Minden blokkot / tárgyat, ami kiesik ha a mellette / alatta lévő blokk eltűnik lehet addolni, nem lesz rajta a jelzés, fel lehet venni, használni is. Facsemeték, tábla, nyomólapok, redstone, homok, sóder, stb.

**Comment by asdlol911** [comment]
A bejelentés rögzítve, tesztelve és valós. 

~asdlol911

**Comment by u5tamas** [comment]
akk jó

**Comment by andris155** [comment]
Folyamatban a megoldása.

**Comment by andris155** [comment]
key bug

**Comment by andris155** [comment]
Dispenser, pet interact tiltása.

**Comment by andris155** [comment]
pickup event

**Comment by andris155** [comment]
ore kreatív

**Comment by pacica12342** [comment]
Szia, szeretném jelenteni hogy, a PE tulélő szerveren, egy Elit rangos akinek van creatív joga, letudja tenni a telkére a sárkány fejet, és kiüti Surviban. És a többi fejet is.

**Comment by andris155** [comment]
Egy jó része a hibáknak már javított. Majd nyitok újat új jelentésnél.
