### ISSUE TITLE
Mobarena problémák

### ISSUE THREAD

**Issue by yghrt** [andris155/TheOld-Crafters#1850]
**Több probléma is jelen van a mobarénákkal kapcsolatban.**

- Az első a Hiperugrás kasztra vonatkozik, a probléma csak annyi vele hogy a végtelen íjjhoz, legalább 1x nyílnak jelen kell lennie az inventoryban, amit a Hiperugrás kaszt nem ad, ergó nem fog az íjj működni anélkül. https://minecraft.gamepedia.com/Enchanting#Infinity
![mobarena1](https://user-images.githubusercontent.com/35996682/36568473-6cd5218e-182a-11e8-8d6a-76f9ad95d4d8.png)

- A következő probléma hogy a Völgy arénában nem lehet megölni a hullámban spawnolt farkast, nincs rá jog, vagy egy flag hiba lehet. Erről videót készítettem:
https://www.youtube.com/watch?v=OFZTZxerDhU

- És az utolsó hiba pedig a Gömb arénában történik, ahol egyszerűen túl gyors a wavek váltási ideje, még lehet az első mob sincs megölve, már a következő wave kezdődik, és szinte lehetetlen ezt így végigcsinálni bármennyire is legyen skilled az illető aki nekiáll. Hibának veszem ezt, a videó segít az eldöntésben.
https://www.youtube.com/watch?v=_g1-13fKiK0

**Comment by poma123** [comment]
> Az első a Hiperugrás kasztra vonatkozik, a probléma csak annyi vele hogy a végtelen íjjhoz, legalább 1x nyílnak jelen kell lennie az inventoryban, amit a Hiperugrás kaszt nem ad, ergó nem fog az íjj működni anélkül. https://minecraft.gamepedia.com/Enchanting#Infinity

Javítva!

> A következő probléma hogy a Völgy arénában nem lehet megölni a hullámban spawnolt farkast, nincs rá jog, vagy egy flag hiba lehet. Erről videót készítettem:
https://www.youtube.com/watch?v=OFZTZxerDhU

Javítva!

> És az utolsó hiba pedig a Gömb arénában történik, ahol egyszerűen túl gyors a wavek váltási ideje, még lehet az első mob sincs megölve, már a következő wave kezdődik, és szinte lehetetlen ezt így végigcsinálni bármennyire is legyen skilled az illető aki nekiáll. Hibának veszem ezt, a videó segít az eldöntésben.
https://www.youtube.com/watch?v=_g1-13fKiK0

Javítva!

**Köszönjük a hibajelentést!!**

**Comment by andris155** [comment]
508 OCD
