### ISSUE TITLE
/rules és /info hibá(cská)k

### ISSUE THREAD

**Issue by Sheep04** [andris155/TheOld-Crafters#1852]
# Üdv!
### Javaslatokat :green_apple: színnel jelöltem.
![2018-02-24_12 33 39](https://user-images.githubusercontent.com/34780638/36631323-347602fc-1976-11e8-88bc-4a6b48981a9e.png)
1. kép: 
- az ő; ö betűk helyett õ betűnek látszódó betűk vannak valamiért
- segédprogram, illetve világletöltő szót egybeírjuk
- 2.13, kétszer van

![2018-02-24_12 35 01](https://user-images.githubusercontent.com/34780638/36631326-3bb1927a-1976-11e8-9697-28d06617c053.png)
2. kép:
- felkiáltójel hiányzik
- vessző hiányzik

![2018-02-24_12 35 27](https://user-images.githubusercontent.com/34780638/36631402-971616a8-1977-11e8-9049-927bb5cf7008.png)
3. kép:
- nem kell vessző oda

![2018-02-24_12 37 26](https://user-images.githubusercontent.com/34780638/36631407-a6d3d97c-1977-11e8-8064-039fd476385d.png)
4. kép:
- ugyanazt egyben van
- Lag szónál két 'g' helyett egy van

![2018-02-24_12 38 10](https://user-images.githubusercontent.com/34780638/36631408-abaa4274-1977-11e8-852c-842a38371778.png)
5. kép:
- ő; ű betűk a játékban unicode karakterek, többször előfordulhatnak egy mondatban

![2018-02-24_12 40 26](https://user-images.githubusercontent.com/34780638/36631410-b02ef7c2-1977-11e8-83d0-edf66c232639.png)
6. kép:
- spawn világában nem lehet (képtelenség) építkezni
- pályák helyett pályákat, mivel több van

![2018-02-24_12 42 20](https://user-images.githubusercontent.com/34780638/36631429-dcec8310-1977-11e8-9a70-a16214e59d2b.png)
7. kép:
- a hibajelentés linkjét /rules chatben is meg lehetne nyitni a szögletes zárójelek elhasználásával

![2018-02-24_13 27 33](https://user-images.githubusercontent.com/34780638/36631431-e85cef28-1977-11e8-8b1c-628c19f70dfb.png)
8. kép:
- új Discord link: https://discordapp.com/invite/CA7GAuc

![2018-02-24_13 30 45](https://user-images.githubusercontent.com/34780638/36631432-ee0a19d2-1977-11e8-8877-a0de20cb4b8b.png)
9. kép:
- ismételten az õ szerű betűk
- Aukciós Ház ki lett véve

![2018-02-24_13 31 11](https://user-images.githubusercontent.com/34780638/36631433-f287cd24-1977-11e8-8e61-8ec36b922fed.png)
10. kép:
- az õ betűs dolog ũ szerű betűvel

![2018-02-24_13 31 42](https://user-images.githubusercontent.com/34780638/36631435-f5592a3e-1977-11e8-9850-cabf9eab1897.png)
11. kép:
- ez esetben világoszöld szín

![2018-02-24_13 33 21](https://user-images.githubusercontent.com/34780638/36631438-fe7394e2-1977-11e8-992b-7c27462c57f2.png)
12. kép:
- Minecraft (legalábbis a gép) által felismerhetetlen karakterek

![2018-02-24_13 33 54](https://user-images.githubusercontent.com/34780638/36631449-04034fa6-1978-11e8-8828-bf49f6c6f537.png)
13. kép:
- night angolul éjszaka

## Sheep04, avagy Sanyi, a vízálló bárány!

**Comment by Sheep04** [comment]
2 és fél órán keresztül dolgoztam ezen, remélem, ért valamennyit :joy:

**Comment by andris155** [comment]
javítva - 1016 OCD
