### ISSUE TITLE
Apró kiírás hiba rangvételnél, mivel nincs már /ah

### ISSUE THREAD

**Issue by yghrt** [andris155/TheOld-Crafters#1853]
Üdv, egy apróbb kiírás hiba van rangvételnél, és a ranginfóknál, mivel nincs már /ah, és nem tudni egy darabig hogy újra be fog e kerülni valamilyen formában, gondoltam jelzem addig, ezek a kiírások egyébként mindegyik rangnál megtalálhatóak.

- PL.: 
![aukc1](https://user-images.githubusercontent.com/35996682/36632219-3eb800a4-1984-11e8-98be-0b13ba8853c8.png)
- És PL.: /info tag+jogok 
![aukc2](https://user-images.githubusercontent.com/35996682/36632236-6a724cea-1984-11e8-9a01-4b7ffb5c2efc.png)

**Comment by Sheep04** [comment]
#1852

**Comment by andris155** [comment]
Már jelentett hiba.
