### ISSUE TITLE
Obszidián és a ládabolt esete

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#1854]
Nincs jog admin alatti játékosoknak obszidiánt eladni ládabolton keresztül

**Comment by skrisz0101** [comment]
De miért? Teljesen mást irtam

**Comment by skrisz0101** [comment]
Admin rang alatt nincs ládabolt nyitás lehetőség (jog)

**Comment by poma123** [comment]
Javítva mindkét szerveren!
Köszönjük a hibajelentést!
