### ISSUE TITLE
JátékDoboz fordítási hiba

### ISSUE THREAD

**Issue by poma123** [andris155/TheOld-Crafters#1855]
Az Amőba játék neve angolul ,,ConnectFour", ami Csatlakozás4-re lett fordítva ,,Amőba" helyett.

![image](https://user-images.githubusercontent.com/25465545/36643694-9ba5a2a0-1a4f-11e8-80e7-9564c6a2349c.png)

**Comment by andris155** [comment]
Javítva, holnap betölt.
