### ISSUE TITLE
Info tag jogok tábla

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#1856]
Szia. A tag ranghoz is jó lenne egy [info] tábla, ahol a fontosabb dolgok le vannak írva (pl.: levédés mennyisége, sethome mennyiség stb.)
A parancsok parancsnál nem írja ezt, pedig igencsak fontos.

Üdv

**Comment by andris155** [comment]
Ez eddig csak pár sor. Mik legyenek még benne?

**Comment by MrZero1** [comment]
A fontosabb Tag jogok. Nyilván amik kint voltak a rangok warpon, míg le nem lett ütve.

**Comment by andris155** [comment]
/info limitek néven hoztam létre egy újat.
