### ISSUE TITLE
Szivacs nem szárad ki a netherben, Vanilla Additions plugin

### ISSUE THREAD

**Issue by yghrt** [andris155/TheOld-Crafters#1857]
Üdv, egy újabb apró hibát találtam, elvileg a Vanilla Additions pluginnak van egy olyan része hogy a netherben lerakott vizes szivacs intstant kiszárad, erről megkérdeztem MrZero-t is szerinte is így kéne működnie, ő is megnézte és neki sem jó és elvileg működött ez még múltkor.

A hibáról készítettem videót: https://www.youtube.com/watch?v=ixZsuAoKWZ8

**Comment by andris155** [comment]
Paper-on valamiért nem megy, mert a fejlesztőnek elvileg működik. Szerintem ez nélkül a funkció nélkül lehet élni.

**Comment by andris155** [comment]
204 OCD
