### ISSUE TITLE
Szabályzattal kapcsolatban..

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#1858]
Szia.

Láttam, hogy Sheep04 jól  összeszedte a hibákat, nekem lenne pár javaslatom. Célszerűbb, ha ide írom, mint Facebookon. :D 

Szóval, tájépítés:
4.9 felesleges, úgyis kiütik a tövénél a cukornádat, kaktuszt.
A Strongholdok, falvak, endcity-s dolgok és a dungeonokra vonatkozó szabályok is feleslegesek, aki szeretné, úgyis elbontja teljesen. 
Módosítanám: Levédésük, kifosztásuk megengedett, elbontásuk, rongálásuk nem ajánlott. 

Chat:
1.10 szabályzat végén a pont lemaradt.

Támogatók:
7.1 - Piros, vörös és fekete. (&c , &4 , &0)
7.4 Szintúgy +vörös

Nem "bugok", inkább elírások, javaslatok. :)

**Comment by andris155** [comment]
kész
