### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by DrBoomer** [andris155/TheOld-Crafters#1859]
Új és korlátlan ideig tartó meghívó link :    https://discord.gg/MRTmV89

**Comment by DrBoomer** [comment]
https://discord.gg/MRTmV89
https://discord.gg/MRTmV89
https://discord.gg/MRTmV89

**Comment by poma123** [comment]
@andris155 Szia. Erre kellene lecserélni majd az /info discord-nál, a ChatControl broadcast szövegénél a Discord meghívó linket. 
Egész véletlenül amikor az /info discord parancsot beírtam, a broadcast is utána nem sokkal kiírta.
![image](https://user-images.githubusercontent.com/25465545/36719327-0b12108c-1ba5-11e8-9608-b9423ea5f0e7.png)

**Comment by andris155** [comment]
frissítve
