### ISSUE TITLE
MyPet tárgy duplázás

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#186]
MyPettel lehet tárgyakat duplázni, ha felajánlom másnak (/pettrade), és mielőtt elfogadja, megnyitom az inv-jét (/peti). Ha elfogadta, mindent ki lehet pakolni, az inv nem záródik be, a másik playernél a pet-ben pedig megmarad az összes cucc.

**Comment by andris155** [comment]
A trade jogokat egyenlőre töröltem.

**Comment by andris155** [comment]
@Kronox12  ezt jelentetted aztán a fejlesztőnek?

**Comment by Kronox12** [comment]
Igen

**Comment by andris155** [comment]
és javította?

**Comment by Kronox12** [comment]
Amint a spigot engedi, hogy a fájl, elérhető lesz. Volt egy kis hiba a spigot részéről.

**Comment by andris155** [comment]
A 2.1.6-ban akkor már javították?

**Comment by Kronox12** [comment]
Igen

**Comment by andris155** [comment]
Köszi. :)
