### ISSUE TITLE
SavSziget - Sziget beállítások

### ISSUE THREAD

**Issue by poma123** [andris155/TheOld-Crafters#1860]
Szia. Szerintem lenne igény a sziget beállításokhoz (vagy töredékükhöz). Itt lehet beállítani többek között, hogy a szigetünkön a látogatók tudnak-e tojást dobni, PvP-zni, itemet felvenni/kidobni, Falusival kereskedni, használni a portált, a nether szigetünkön pvpzni, tejet fejni, mobot megütni, kemencét kinyitni, és még sok minden mást. Az összes jogot ami ezzel kapcsolatos
 összeszedtem egy [gist](https://gist.github.com/poma123/b9a8bd39896c7b00ba82b96eeab6f19a)-be.

> /is settings

![image](https://user-images.githubusercontent.com/25465545/36697082-507994b0-1b46-11e8-88d3-e4e51cbabfa2.png)

Meg vannak adva a `config.yml`-ben az alap beállítások, amiben szerintem van egy hiba. A kemencébe való belenyúlás engedélyezve van a látogatóknak alapból, így a nem levédett kemencékből ki lehet lopni bármit, sajnos. Én ezt kijavítanám, ha te is úgy gondolod, hogy ez hiba.

Üdv, poma123

**Comment by andris155** [comment]
Ezt a fejlesztést rád bízom. De jól gondold át mire adsz nekik jogot, mert a játékosok gyakran nem olvasnak el semmit csak állítgatnak mindent. :D

**Comment by poma123** [comment]
Okés.

**Comment by poma123** [comment]
A kemencés hiba javítva, és ezeket a jogokat kapták meg (default rang):
```
acidisland.settings.bed
acidisland.settings.door
acidisland.settings.eggs
acidisland.settings.portal
acidisland.settings.pressure_plate
acidisland.settings.redstone
acidisland.settings.visitor_item_pickup
```
Ezeket a beállításokat tudják állítani, amelyek a sziget látogatóira vonatkoznak. Üdv.
