### ISSUE TITLE
CraftBook pluginnal addolás kreatívból

### ISSUE THREAD

**Issue by yghrt** [andris155/TheOld-Crafters#1861]
Üdv, újabb hibajelentés, ezúttal a **CraftBook plugin** okozott egy kis meglepetést, miután kreatív módban elkészítettem egy **[Gate]** és egy **[Bridge]** szerkezetet, úgy döntöttem lecserélem az alapanyagot, és úgy jött össze hogy kiütöttem a táblát survival módban, és mivel a **[Bridge]** visszahúzott állapotban volt, (olyankor a táblán rajta van a tárolt érték hogy mennyi block volt a két **[Bridge]** tábla között), az a mennyiség amivel kiraktam ki is fog esni felszedhető állapotba survivalmódban miután ki van ütve a tábla olyan állapotban. Ez szintén vonatkozik a **[Gate]**-re is, de itt a táblát is oda adja. A **[Pipe]** dologgal különösebb probléma azon kívül nem volt, hogyha kreából egy táblát bárhova lerakunk csak annyi szöveggel a második soron hogy [Pipe] akkor a táblát is kidobja felvehető állapotba.

A jelenségekről videókat is készítettem:
- **[Bridge] és [Gate]**
https://www.youtube.com/watch?v=H5c3qYErQgc

- **[Pipe] tábla**
https://www.youtube.com/watch?v=8YHW68T0z6I

**Comment by andris155** [comment]
Jelentett hiba, de nem éri meg vele foglalkozni. Azt hiszem nem tábla csalásból fog megélni senki.
