### ISSUE TITLE
Spawnerek könnyebben

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#1862]
NEm tudom van-e ilyen plugin, de nem megoldható, hogy gyengéd érintéses csákánnyal kilehessen szedni a spawnereket? Szerintem nagyon hasznos lenne
Remélem van rá mód
helo-helo

**Comment by andris155** [comment]
Más is örülne ennek?

**Comment by poma123** [comment]
Igen, és Savszigeten is hasznos lenne. :D

**Comment by andris155** [comment]
Sajnos a plugin tiltja a meglévő nem lerakott spanwer-eket. Így inkább nem lesz ilyen.

**Comment by Sheep04** [comment]
Már van :P
