### ISSUE TITLE
Napi ládák és kulcsok a Survival szerverre

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#1865]
Szia.

Szó volt már a napi/heti ládákról a Survival szerverre, hasonló módon, mint a Savszigeten, bevezethetnénk a Survival szerverre.

A láda tartalmáról már gondolkodtam, ha elfogadod, mint fejlesztés és bekerül a napi láda oda, a Facebook csoportban a többi Staffal közösen kivesézzük részletesebben.

Üdv.

**Comment by andris155** [comment]
A ládák tartalma azért érdekelne. Egyébként akadálya nincs, hogy bekerüljön, de jó lenne pár OCD-s kulcsot, vagy ládát is kitalálni hozzá.

**Comment by MrZero1** [comment]
A napokban a staffcsoportban megbeszéljük akkor.

**Comment by Sheep04** [comment]
Már nagyon várom :D

**Comment by andris155** [comment]
Egyelőre az 1.13-as frissítés majd fontosabb lesz mint ez.
