### ISSUE TITLE
Minemarket hiba

### ISSUE THREAD

**Issue by akos222** [andris155/TheOld-Crafters#1867]
Nem lehetett az akos_ névre küldeni ocd-t, azt írta, hogy "Nem található játékosnév", ezért átírtam a nevem akos_1-re, így megkaptam az ocd-t, de most nem engedi visszaírni akos_-ra "Hibás név váltás" üzenettel, és regisztrálni sem engedi azt a nevet, mert már foglalt. Így most semmit sem tudok venni minemarketen.

**Comment by andris155** [comment]
Válts nevet a szerveren.

**Comment by akos222** [comment]
más megoldás?
