### ISSUE TITLE
savsziget-szurvi kommunikáció

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#1868]
nem lehet a szerverek közt írni /m és /r-ben írni

**Comment by Sheep04** [comment]
Jajj akkor kellett volna jelentenem, amikor észrevettem, csak fáradt voltam, és nem volt időm :D

Egyébként csak a savsziget fele nem megy a kommunikáció (akkor gondolom /t-ben, /msg-ben se működik).
![2018-03-03_14 33 54](https://user-images.githubusercontent.com/34780638/36934877-467aeea2-1ef0-11e8-906c-7e94f44c69b6.png)
![2018-03-03_14 34 02](https://user-images.githubusercontent.com/34780638/36934880-4abcae1a-1ef0-11e8-8751-f2f91a95b7ff.png)

**Comment by andris155** [comment]
elvileg javítva
