### ISSUE TITLE
Chat hibácska

### ISSUE THREAD

**Issue by Sheep04** [andris155/TheOld-Crafters#1869]
Üdv!
Írni akartam egy üzenetet olyan játékosnak, aki nincs is fent, akkor azt hittem, azt írja majd ki, hogyez a játékos nincs online, végül annak írta, akire leginkább hasonlít a neve a rendszer szerint.

Fotók:
![2018-03-03_14 27 59](https://user-images.githubusercontent.com/34780638/36934918-ddfcbb70-1ef0-11e8-8c18-82104aacc725.png)
![2018-03-03_14 28 03](https://user-images.githubusercontent.com/34780638/36934919-e13fcb88-1ef0-11e8-8449-c9cd7691ea1d.png)

Üdvözlettel,
Sheep04, avagy Sanyi, a vízálló bárány!

**Comment by andris155** [comment]
elvileg javítva
