### ISSUE TITLE
Tortaevés egyszerűen tutorial (hiba)

### ISSUE THREAD

**Issue by Sheep04** [andris155/TheOld-Crafters#1870]
Üdv! 
Kreatívban dísznek leraktam egyszer egy tortát, majd úgy gondoltam, enni próbálok belőle, és valahogy sikerült is ennem. Meg másnak is :smiley: 

Ezeken a fotókon szemléltetem a történteket:
![2018-03-03_14 42 41](https://user-images.githubusercontent.com/34780638/36934966-9bb819d4-1ef1-11e8-8df3-ee3291caa081.png)
![2018-03-03_14 42 47](https://user-images.githubusercontent.com/34780638/36934969-9e99777e-1ef1-11e8-841e-e151fc74d3a2.png)
![2018-03-03_14 42 49](https://user-images.githubusercontent.com/34780638/36934970-a0d9e46a-1ef1-11e8-9f5b-54d995e756c9.png)

Sheep04, avagy Sanyi, a vízálló bárány!

**Comment by andris155** [comment]
Milyen levédésen?

**Comment by andris155** [comment]
Nem látom értelmét tiltani ezt. A farmon szinte ugyan így ingyen van a kaja.
