### ISSUE TITLE
Murder scoreboard hiba

### ISSUE THREAD

**Issue by Sheep04** [andris155/TheOld-Crafters#1871]
Üdv!
Beléptem Murderbe, aztán ki, majd mentem a falldown eventre, ahol megmaradt a scoreboard, halálom után is.

Fotók:
![2018-02-26_18 54 23](https://user-images.githubusercontent.com/34780638/36935050-785d4008-1ef2-11e8-878b-a80739bdf671.png)
![2018-02-26_18 55 30](https://user-images.githubusercontent.com/34780638/36935053-7f5807c6-1ef2-11e8-9885-bb8baccf297d.png)
![2018-02-26_18 55 38](https://user-images.githubusercontent.com/34780638/36935059-88948e5e-1ef2-11e8-989c-fdfbe4388627.png)

Sheep04, avagy Sanyi, a vízálló bárány!

**Comment by Sheep04** [comment]
Plusz nem tudom mennyire hiba, de tagként (meg akkor, ha fly off volt alapból)  is kiírja az eventeknél hogy repülési mód letiltva.

**Comment by Sheep04** [comment]
Scoreboard itt se tűnik el, de nem az volt a hiba tárgya:
#1055

**Comment by poma123** [comment]
#1031

**Comment by Sheep04** [comment]
Lezárhatom?

**Comment by andris155** [comment]
A plugin hibája. A fejlesztőnek már régebben jelentettem. Valamiért nem javítja. :/
