### ISSUE TITLE
Vote megoldása a szerverkezelőre, és jutalom szerverenként beállítása.

### ISSUE THREAD

**Issue by Dreed1992** [andris155/TheOld-Crafters#1873]
Üdv.
Az alap elgondolás az lenne,hogy a vote rendszert bevezetnénk savra is.
Több honlappal,és a szavazásokért cserébe pontokat gyűjthetnének.
Ezeket összegyűjtve kulcsokra válthatnák amiből ládát nyithatnának vele. 
Ezzel hirdetné mindenki a szerót is,illetve jutalomban is részesülnének.
A jelenlegi vote survin működik,de savon ez nincs,így szerintem sok lehetőségtől elbukunk.
persze a jutalom átgondolható,módosítható ,de az alap az lenne,hogy nagyobb hírnevet szerezzünk,és több játékosnak adjunk lehetőséget. 
-Agronaut.

**Comment by andris155** [comment]
A rendszer beállítva. A jutalmak beállítása után használatra kész.
