### ISSUE TITLE
safsziget music

### ISSUE THREAD

**Issue by akos222** [andris155/TheOld-Crafters#1874]
safszigeten a spawnon ott van a muzsikás npc izé de nem lehet megnyitni mer nincs engedélyezve a /music parancs

**Comment by andris155** [comment]
És ha simán beírod a parancsot?

**Comment by poma123** [comment]
A spawnon nem volt engedélyezve a /music parancs. Javítva.

**Comment by akos222** [comment]
köx

**Comment by andris155** [comment]
Javítva!
Köszönjük a hibajelentést!
