### ISSUE TITLE
Mobaréna nyeremények

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#1876]
Nem lenne rossz ha mobarénán lennének értelmes nyeremények,mert a mostani nyeremények (pl sóder, bot) semmit sem érnek, ha lenne valami jó nyeri jönnének mobarénára

Másik: a bosst lelehetne gyengíteni, mert amióta játszok a szerveren (1 éve)
Senki se győzte le a bosst
Szóval lehetetlen győzni

A hipervándor nyíl hiány 
nem tudom megvan-e még

**Comment by poma123** [comment]
A ~~hipervándor~~ hiperugrás nevezetű class-ban már hetek óta van nyíl.

**Comment by andris155** [comment]
Kész

**Comment by andris155** [comment]
330 OCD
