### ISSUE TITLE
PvP aréna hibák

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#1877]
A /warp eventek-nél található PvP arénákban van pár hiba.

- **Nether**: Nem lehet nyitni se a ládát, se az enderchest-et, még a teleport helyén lévő nyomólap se működik.
- **Spawn**: Egy üres, sötét lyukba visz a tp tábla:
![image](https://user-images.githubusercontent.com/16057404/36950419-eab59d36-1ff5-11e8-8382-2b77dff6a478.png)
- **Piac**: Nincs enderchest és közös láda.

**Comment by poma123** [comment]
1. Javítva.
A teleport-táblával kell belépni az árénába.
2. Javítva.
3. Javítva

Köszönjük a hibajelentést!

**Comment by andris155** [comment]
330 OCD
