### ISSUE TITLE
/m nem megfelelő működése.

### ISSUE THREAD

**Issue by Dreed1992** [andris155/TheOld-Crafters#1879]
Üdv.
Amikor üzenetet szeretnének küldeni egymásnak a játékosok,de az egyik fél lelép,az üzenet szövegét véletlenszerűen másnak küldi el.
![2018-03-06_19 24 40](https://user-images.githubusercontent.com/35728669/37050603-96e61be2-2174-11e8-9f5b-48e4b41c81ab.png)

**Comment by skrisz0101** [comment]
Csak savsziget és szurvi közt nem jó
Már jelentettem

**Comment by Dreed1992** [comment]
köszkösz
