### ISSUE TITLE
Savsziget rang hiba!

### ISSUE THREAD

**Issue by sweetan2** [andris155/TheOld-Crafters#1881]
Safeepapee neveben irok. Elvileg vett a tegnap este old rangot es meg is kapta de ma mikor fel jott mar nem volt meg az old rangja. Azt mondja a minemarketen aktivnak mutatja de a jatekba mar nem.

**Comment by poma123** [comment]
31 napja vett old rangot, és 20 órája lett tőle elvéve automatikusan.

**Comment by andris155** [comment]
javítva
