### ISSUE TITLE
Szavazás

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#1882]
- **Problem 1**: Sokkal kevesebb (2) szavazó oldal van beállítva a pluginban, mint lehetne, pedig több helyen is fent van a szerver, pont a népszerűbb oldalak lettek kihagyva.

- **Problem 2**: Ezeken az oldalakon a szerver leírása már egy ideje nem volt frissítve, sok helyen még iZone levédés, Slimefun, SkyPvP, stb van.

![kep](https://user-images.githubusercontent.com/16057404/37141177-805091a0-22b4-11e8-9759-d4d2dbe46503.png)

_Pár link, amit be lehetne rakni a pluginba (ahol nem megy a vote, odaírtam), esetleg frissíteni a leírást, a jutalmakat is ennek megfelelően kéne módosítani, shop-ban új tárgyakat beállítani._

http://minecraft-server-list.com/server/346469/ (Régi leírás)
http://minecraftservers.org/server/206927
https://mcserverstatus.com/viewserver/27314 (Itt a szavazás nem menne playernévvel, de a leírás régi, PlotMe, Jobs, stb.)
https://www.planetminecraft.com/server/theold---crafters-survival/ (Régi leírás, vote off.)
https://www.minecraftiplist.com/server/TheOldCrafters-2330 (Régi leírás, a szavazás egyszerűbb, nem kell recaptcha-val szórakozni.)
https://minecraft-tracker.com/server/3130/ (Régi leírás)
https://minecraftlist.org/server/786 (Régi leírás)
https://minecraft-statistic.net/en/server/oldcrafters.html (Régi leírás)
https://topminecraftservers.org/server/524 (Régi leírás, a videó se jó már.)
https://www.minecraftforum.net/servers/6151-theold-crafters (Régi leírás)
https://minecrafthub.com/server/theold-crafters
https://www.mc-szerverek.hu/szerverek/id/85
http://mclistserv.com/server/3810 (Régi leírás)
https://minecraftservers.biz/servers/8703/ (Régi leírás)

**Comment by andris155** [comment]
A legtöbbet átnéztem és próbáltam aktualizálni a leírást. Szavazást én nem szeretnék több helyre. A magyarra lenne jó, de a szavazásnál inkább a fizetett szerver hirdetések vannak előtérbe helyezve. Másnak pedig nem fogom hirdetni ezzel a szerverét, mert sajnos nem mindig minőségi szerver vesz ott kiemelt hirdetést.

**Comment by andris155** [comment]
A minecraftforumossal amúgy nem tudok mit csinálni. Twitch account-ot kér hozzá, de az nekem nincs. Meg még egyre nem tudtam belépni

**Comment by andris155** [comment]
Amúgy azért nem akarok többi angolra, mert amiken most van szavazás azokra rá lehet találni Google-n. De a többire nem igazán ha magyarul keresel rá, hogy minecraft szerverek.

**Comment by andris155** [comment]
1016 OCD
