### ISSUE TITLE
Crazy Auctions

### ISSUE THREAD

**Issue by Sheep04** [andris155/TheOld-Crafters#1884]
Üdv! Most jött be egy másik aukciós házas plugin.
1.:
Itt az lenne a probléma, hogy miközben kiírja, hogy az ár nem lehet 10$ alatt, csak 50$-ért engedi eladni a tárgyat minimum.
2.:
Nem lehet optimalizálni esetleg, hogy egy adott rangnak hány aukciózható tárgya legyen? Jelenleg 2-t enged nekem, sizarrának meg valahogy sikerült 3.
3.:
Majd ki lesz írva infóként?
Fotók:
1.:
![2018-03-10_12 35 50](https://user-images.githubusercontent.com/34780638/37241927-6b05d8ba-2461-11e8-8aba-395687da9472.png)
![2018-03-10_12 35 52](https://user-images.githubusercontent.com/34780638/37241939-702f8b06-2461-11e8-9088-aaa31bcbb9a2.png)
2.:
![2018-03-10_12 49 44](https://user-images.githubusercontent.com/34780638/37241952-9099fe26-2461-11e8-93c8-235ee5481fbc.png)

Sheep04, avagy Sanyi, a vízálló bárány!

**Comment by Sheep04** [comment]
Illetve még az lenne a kérésem, hogy a szövegfájlt a fordításokhoz rakod? Lefordítanám...

**Comment by andris155** [comment]
https://github.com/andris155/TheOld-Crafters/tree/master/Ford%C3%ADt%C3%A1sok/CrazyAuctions

**Comment by Sheep04** [comment]
Köszi

**Comment by andris155** [comment]
Még majd a config fájlban kell lefordítani pár dolgot.

**Comment by andris155** [comment]
kész.
