### ISSUE TITLE
/warp bolt

### ISSUE THREAD

**Issue by Sheep04** [andris155/TheOld-Crafters#1885]
Üdv!
A bolt warpon az emelkedőszerűség, híd oldalán nincs betömve, így be lehet jutni alá.
A fotókat a keleti szárnyból készítettem.
![2018-03-10_12 54 06](https://user-images.githubusercontent.com/34780638/37242016-90627248-2462-11e8-8e82-c1b8d27ccc24.png)
![2018-03-10_12 54 11](https://user-images.githubusercontent.com/34780638/37242017-93a94dfa-2462-11e8-8f69-fa7d3d246c07.png)
![2018-03-10_12 54 17](https://user-images.githubusercontent.com/34780638/37242018-968bacac-2462-11e8-95b8-09281482c0dd.png)

Sheep04, avagy Sanyi, a vízálló bárány!

**Comment by MrZero1** [comment]
Javítva! Köszönjük.
