### ISSUE TITLE
GameBoxba bezavar a ChatControl

### ISSUE THREAD

**Issue by Sheep04** [andris155/TheOld-Crafters#1886]
Üdv!
Amőbát szerettem volna játszani valakivel, hívnám is meg, de kiírja, hogy "Nincs Foltos. nevű játékos.", ugyebár Foltos. tényleg nincs, és a ChatControl a végére pontot rak.
Fotók:
![2018-03-09_18 51 01](https://user-images.githubusercontent.com/34780638/37242113-3c0e587c-2464-11e8-90fd-935a30c6d4a6.png)
![2018-03-09_18 51 10](https://user-images.githubusercontent.com/34780638/37242115-40bbc27e-2464-11e8-83db-193dc874ee32.png)
![2018-03-09_18 51 20](https://user-images.githubusercontent.com/34780638/37242116-4a210da6-2464-11e8-895b-01d12cfe8be6.png)
![2018-03-09_18 51 38](https://user-images.githubusercontent.com/34780638/37242121-5395258e-2464-11e8-9160-fecedc666db9.png)
![2018-03-09_18 51 49](https://user-images.githubusercontent.com/34780638/37242123-594b75aa-2464-11e8-97b6-df26a0b3d1b7.png)

Sheep04, avagy Sanyi, a vízálló bárány!

**Comment by Sheep04** [comment]
Jaj ha tudnék videót felvenni xD

**Comment by poma123** [comment]
> ,, ...mert az olyan szó, amelyet mondatnak értékel."

Egy meghatározott hosszúság után tesz pontot, nem csak válogat a szavak között. Egyébként köszönjük a jelentést.

**Comment by andris155** [comment]
javítva

**Comment by andris155** [comment]
204 OCD
