### ISSUE TITLE
Tájépítés új szabály v1

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#1888]
Szia. Szabályzatba véssük bele a következőt: A tájat ne rongáld, rondítsd el. 

Lásd: 
![2018-03-11_16 05 11](https://user-images.githubusercontent.com/29709854/37254987-43b1e5fc-2546-11e8-9935-bcc6dd141691.png)

**Comment by andris155** [comment]
![kepkivagas](https://user-images.githubusercontent.com/8324198/37284225-045f63c4-25fb-11e8-8213-b1b03c21de41.PNG)
Már létező szabály

**Comment by MrZero1** [comment]
Nem építmény, ezért is jeleztem, de ok.
