### ISSUE TITLE
Nincs chunk load

### ISSUE THREAD

**Issue by NikeboyHU** [andris155/TheOld-Crafters#189]
A PE szervereken egyre több embernek akad olyan gondja, hogy nem tölt be a map betöltéskor, csak chat, és inventory van. Move event update bugra tippelek, valószínű annak lesz valami hibája, mivel nem tud sehova elteleportáni a játékos, azzal a céllal, hogy hátha begenerál.

**Comment by andris155** [comment]
A network beállításokat visszaállítottam az alapra.
