### ISSUE TITLE
Privát üzenet

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#1890]
Szia. Nem tudom, jelentették-e már hivatalosan itt, de a szerverek közötti privát üzenetküldés még mindig nem jó. 
Próbáltam szemlélteni, hogy Savszigeten lévő Kelvin172-nek címezve más kapta meg Survivalon. 
(Tudom, hogy a Facebook staff csoportban szóltak róla, de jobban szereted ha itt jelezzük.:D) 

![priv](https://user-images.githubusercontent.com/29709854/37255968-a2fcae76-2554-11e8-902d-ca6b761c3c1f.png)

**Comment by MrZero1** [comment]
ui.: Bocsi, nem tudom mennyire hivatalos ez, azért satíroztam ki, habár semmi bizalmas infó nem volt, de jobb így, na. :D

**Comment by skrisz0101** [comment]
Valamennyire már volt jelentve, 2x is

**Comment by MrZero1** [comment]
"Valamennyire"

**Comment by poma123** [comment]
#1868 
Egyébként a hiba javítva lett, a következő plugin frissítésben már jó lesz. kangarko/ChatControl-Pro#618

**Comment by andris155** [comment]
Már jelentett hiba.
