### ISSUE TITLE
Új küldetések savra.

### ISSUE THREAD

**Issue by Dreed1992** [andris155/TheOld-Crafters#1891]
-Név: Dekoráló.
 Gyűjts össze 16 üveglapot minden színből!  (x100)
 Jutalom: 32 Netherkvarc,100$.

-Név: A fejvadász.
 Szerezz 64 Enderman fejet! (x100)
 Jutalom: 32 Szén.

-Név: Vagyonos
 Gyűjts 32 arany,vas és gyémánt blokkot. (x1)
 Jutalom: 1 Nethercsillag.

-Név: Forró a talaj
 Készíts 16 magmablokkot.  (x1)
 Jutalom: 10 szivacs, 300$

-Név: A Díszítő.
Szerezz 16 nyitott térképet , 16 kísértet könnyt, 16 festményt. (x100)
Jutalom:32 Páfrány, 32 pókháló,2 virágcserép. 

-Név: Céklaleves bohóc
 Főzz 32 céklalevest, 32 nyúl pörköltöt,és szerezz 16 bohóchalat. (x100)
 Jutalom: 1 Withercsontváz-koponya, 1 endkristály.

-Név: Lángoló tekintet.
 szerezz 64 őrláng fejet.  (x100)
 Jutalom: 32 lángrúd.

-Név:Lőszeres
 Gyárts le 64 éjjellátás nyilát. (x1)
 Jutalom:  +1 szív. <3

**Comment by skrisz0101** [comment]
Jó ötletek

**Comment by poma123** [comment]
1.13 előtt nem nagyon szeretnék ilyen dolgokat fejlesztgetni, mivel úgyis át kell majd írni. De az ötletek jók.

**Comment by andris155** [comment]
Szerintem lehet nem kell átírni.

**Comment by poma123** [comment]
Kész
