### ISSUE TITLE
Bolt hiba

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#1893]
/warp bolt-ból ki lehet jutni a félblockos ablakoknál, csak el kell valahová teleportálni, és backelni.

![kep](https://user-images.githubusercontent.com/16057404/37303830-fa1e0ee4-262f-11e8-9675-8b9158c8bfdd.png)

**Comment by MrZero1** [comment]
Javítva.

**Comment by andris155** [comment]
204 OCD
