### ISSUE TITLE
Új támogatói jogok

### ISSUE THREAD

**Issue by andris155** [andris155/TheOld-Crafters#1894]
- Több aukció
- Chatcontrol color

**Comment by MrZero1** [comment]
Ötletként felvettettük már a csoportban, hogy rangtól lehetne bővíteni az enderchest slotot.

**Comment by andris155** [comment]
Az Enderchest-es plugin viszonylag sok erőforrást használ. Illetve arang lejárata után elvesznének belőle a tárgyak, ami meg nem szerencsés.

**Comment by andris155** [comment]
A többi megvalósítva

**Comment by Sheep04** [comment]
Akkor chc color csak prémiumtól van?

**Comment by andris155** [comment]
elit
