### ISSUE TITLE
/m hiba

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#1895]
Szia. Próbáltam szemléltetni, de nem jó a privát üzenet küldés, immáron szerveren belül.

Elliotnak akartam üzenni, elején egy másik tagnak küldte, aki fent sem volt, azonban most már el sem küldi, viszont konzolban a parancsot látom. Csatolom ezt, máshogy nem tudtam szemléltetni. Valamint csatolom elliot hibajelzését is, megerősítés képpen.

Fejlemény 2 : Elküldi, megkapja, viszont visszacsatolás (a kis email ikon plusz a szöveg) nem jelenik meg.
![privt](https://user-images.githubusercontent.com/29709854/37352176-f44886a4-26dc-11e8-83d3-85dc1a1fef1f.png)
![2018-03-13_16 31 40](https://user-images.githubusercontent.com/29709854/37352231-150e1ac0-26dd-11e8-9379-5275661a3778.png)

**Comment by andris155** [comment]
Állítottam a dolgon. TESZTELNI kellene mennyire jó. Nekem jól működött így.
