### ISSUE TITLE
Kedves andris155!

### ISSUE THREAD

**Issue by s1ckzar** [andris155/TheOld-Crafters#1897]
A mai napon támadás érte a szerverünket, minden map-ot és felhasználói adatot törölt egy bizonyos andris155 nevű játékos. Szeretném megkérni, hogy álljon le ezzel, ellenkező esetben sajnos meg kell tennünk a szükséges lépéseket.

Üdv: s1ckzar

**Comment by MrZero1** [comment]
Ne légy buta, szerinted mi célja lenne Andrisnak erre? Mellesleg se ideje, se indoka nincs más szervereket támadni. Naponta kapunk mi is támadásokat, mégsem adunk egy fake acc. szavára (jelen esetben nevére). Bárki használhatja az Ő nevét.
 Üdv, MrZero

**Comment by s1ckzar** [comment]
Nem tudom, nem ismerem, ezt a szervert hirdette ott. Mentésből az adatok nagy részét vissza tudtuk állítani, remélem a jövőben nem lesz több ilyen. Mellesleg a játékosok viselkedése elég szép a szerverükön...

**Comment by s1ckzar** [comment]
Nem tudom, nem ismerem, ezt a szervert hirdette ott. Mentésből az adatok nagy részét vissza tudtuk állítani, remélem a jövőben nem lesz több ilyen. Mellesleg a játékosok viselkedése elég szép a szerverükön...

![2018-03-14_16 34 04](https://user-images.githubusercontent.com/37375860/37413303-05afd22e-27a7-11e8-9b3a-3994255b36f4.png)

**Comment by andris155** [comment]
Nem foglalkozok más szervereivel. A TheOld - Craftersre is alig van időm mostanában.

**Comment by Sheep04** [comment]
@s1ckzar ezt mellesleg úgy hívják, hogy irónia
