### ISSUE TITLE
ChestShop táska hiba

### ISSUE THREAD

**Issue by Lordi88** [andris155/TheOld-Crafters#190]
**Vásárláskor ha már nincs szabad hely az inventoryban akkor a megvett tárgyak a felszerelés helyére kerülnek.
Kép:http://kepfeltoltes.hu/160608/2016-06-08_16.14.10_www.kepfeltoltes.hu_.png**

**Comment by UDPSendToFailed** [comment]
#181 #159

**Comment by andris155** [comment]
Mêg mindig várok a stabil kiadásra, de lehet berakom akkor a devet, ha ez ennyire gond.

**Comment by andris155** [comment]
Hát kerestem, de valamiért törölte a fejlesztő a Chestshop 5-t, még utána kérdezek hátha elküldi, de ha nem küldi el ezt nem tudom megoldani.

**Comment by andris155** [comment]
Nem küldte el, egyenlőre áll a ChestShop fejlesztése.

**Comment by Krumpli2** [comment]
Szia! 
A ChestShop alapból egy remekül működő, stabil és erőforrás kímélő kiegészítő.
Ezt a hibát magadnak okoztad, mivel nem figyeltél megfelelően. 
Viszont abban igazad van, hogy ez egy óriási plugin hiba.
Andris, neked sok sikert a plugin megszerzéséhez!

**Comment by andris155** [comment]
1.9-ben megváltozott a tárgykezelés, azért nem jó, és nem miattam...

**Comment by Krumpli2** [comment]
Tudok róla. A Mojang mindig csinál valami hülyeséget..

**Comment by andris155** [comment]
Ez nem hülyeség...

**Comment by andris155** [comment]
Attól, hogy valamit megváltoztatnak az nem hülyeség, persze vannak hülyeségek is, de ez pont nem az.

**Comment by Krumpli2** [comment]
Szerintem az, mások szerint nem.. De még mindig nem értem, hogy mi értelme van, ezért tartom hülyeségnek.

**Comment by andris155** [comment]
Továbbra sem fejlesztik a ChestShopot sajnos.

**Comment by andris155** [comment]
javítva
