### ISSUE TITLE
Warp járművek Minemarket link hibás

### ISSUE THREAD

**Issue by mdtank** [andris155/TheOld-Crafters#1900]
![2018-03-15_18 19 54](https://user-images.githubusercontent.com/36288065/37479955-42bb0576-287e-11e8-86ed-55f4c2e35a7c.png)

**Comment by Sheep04** [comment]
Hogy mindig későbbre akarom hagyni a hibajelentéseket xD Mindegy, ha a fordítás jól megy, megtérül :D

**Comment by MrZero1** [comment]
Javítva, habár parancsblokk és gomb segítségével.
