### ISSUE TITLE
Staff tagok figyelmen kívül hagyják és támogatják a szabályszegést

### ISSUE THREAD

**Issue by ArmaCell** [andris155/TheOld-Crafters#1903]
Jelenlegi poszt a kedves főadmin úrról, MrZero-ról szólna legfőképp.
A történet röviden annyi, hogy poénból akos_ csinált egy tízparancsolatot, amit aztán osztogattunk játékosok közt, illetve nálunk is volt belőle egy pár dolog.
Mikor az egyik példányát a könyvnek megmutattam egy játékosnak, kedves DOMI nevű játékosunk is érdeklődést kapott a könyv iránt, elszerette volna olvasni Ő is. Elkérte, hogy ELOLVASHASSA ( nem hogy megkapja örökbe), én meg mitsem gondolkodva oda is adtam neki, mi baj is lehet belőle, úgyis csak elolvassa és vissza is adja. Aztán persze nem így történt, kedves DOMI barátunk nem szerette volna visszaadni a könyvet, a főadmin úr pedig a megsemmisítésére bíztatta.
Hát mit is mondjak, szóltam neki, hogy adja vissza, mire Zerótól azt a választ kapta hogy nyugodtan törölje a könyvet, nem lesz belőle baj. (Mellékelt log erről a részről: https://pastebin.com/GywD9iJh )
Ezekután megkérdeztem a kedves staff társaságot, hogy ez számukra eltűrendő-e, mire azt a választ kaptam, hogy ""Nem vállalunk semmiért és senkiért felelősséget". (Mellékelt log erről a részről: https://pastebin.com/wWa8r1Vd )
Ez egyértelműen lopásnak számít, amit a Szabályzat Játékmenet 2.1-es pontja tílt.
Ezesetben a staffok nem jártak el helyesen, sőt, a majdnem legmagasabb rangú staff tag még bíztatta is a játékost a szabályszegésre.
Utána viszont én részesültem büntetésben, mikor (szerintem jogosan) egy nagy nullának neveztem a kedves FőAdmin urat.

**Comment by andris155** [comment]
Ez nem ide való. Vedd fel a kapcsolatot MrZero-val.
