### ISSUE TITLE
SurvivalGames

### ISSUE THREAD

**Issue by Sheep04** [andris155/TheOld-Crafters#1905]
Üdv!

Éppen játszottam sg-ben, és, mint ahogy  szokott lenni sokszor, láthatatlanul mutatja a türelmi időben a játékosokat. 
### DE!
A türelmi idő végeztével is  láthatatlanok voltak számomra, így nem tudtam megölni senkit, miközben engem hamar meg is öltek... :clap:
Bocsi, videót nem tudtam csinálni (sose tudtam :wink:)

Sheep04, avagy Sanyi, a vízálló bárány!

**Comment by andris155** [comment]
Ilyen hiba sajnos nálam is volt. Szerintem lecserélem majd az SG plugin-t.

**Comment by andris155** [comment]
Ez az 1.13-as frissítés része lesz.
