### ISSUE TITLE
Robbanós pokol

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#1908]
Szia. Az ágyak a pokolban rongálnak, elég alaposan. Nem tudom, hogy direkt nincs tiltva ez. Csatolom a képeket.

![2018-03-23_18 58 23](https://user-images.githubusercontent.com/29709854/37845948-689b619c-2ecc-11e8-8001-c0aa957d7eb7.png)
![2018-03-23_18 58 25](https://user-images.githubusercontent.com/29709854/37845949-68c469ca-2ecc-11e8-82ed-4246ebbbb932.png)

**Comment by andris155** [comment]
Savsziget?

**Comment by MrZero1** [comment]
Survival.

**Comment by andris155** [comment]
Csak Admintól lehet lerakni ágyat ott.
