### ISSUE TITLE
safsziget bena forditas

### ISSUE THREAD

**Issue by akos222** [andris155/TheOld-Crafters#1909]
![image](https://user-images.githubusercontent.com/20407410/37852032-5cebf2c0-2ee1-11e8-91fa-2190d7e0a736.png)
nem hozzá adva kell lenniük, csak a szigeten a közeledben

**Comment by akos222** [comment]
meg am eleg gagyi a forditas kb mindenhol nem csak a kuldiknel

**Comment by poma123** [comment]
Javítva!
Köszönjük a hibajelentést
