### ISSUE TITLE
MyPet éhenhalás szöveg hibás

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#191]
Nem hal meg a pet, és a szöveg rosszul van írva.

![2016-06-09_19 01 43](https://cloud.githubusercontent.com/assets/16057404/15938758/e52de93c-2e74-11e6-9b1d-07d99a2f72d9.png)

**Comment by andris155** [comment]
@Kronox12  ezt tudod javítani kérlek?

**Comment by Kronox12** [comment]
Javítva, a fájl berakásra várakozik

**Comment by andris155** [comment]
berakva, holnap betölt.
