### ISSUE TITLE
Savszigetre fejek

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#1911]
Szia!

A /heads boltot savszigetre is szeretnék, igény lenne rá, szívesen költenék ott is a pénzüket. Ha megoldható, legyen.:)

**Comment by andris155** [comment]
Mennyibe kerüljön egy fej?

**Comment by MrZero1** [comment]
5000 $ / darab.

**Comment by MrZero1** [comment]
Kérvényeznénk az árak átírását Survivalon is, 10k / darab, valamint savon is ez az ár legyen.

**Comment by andris155** [comment]
kész
