### ISSUE TITLE
Leírhatatlan bug

### ISSUE THREAD

**Issue by Sheep04** [andris155/TheOld-Crafters#1912]
Üdv!
Éppen murdereztem, aztán kiléptem, és
![2018-03-25_16 56 10](https://user-images.githubusercontent.com/34780638/37876586-ccba8ada-304e-11e8-83a2-b9f34c3a0d20.png)
![2018-03-25_16 56 55](https://user-images.githubusercontent.com/34780638/37876588-d17a613a-304e-11e8-9143-86422d30a2a6.png)
![2018-03-25_17 02 13](https://user-images.githubusercontent.com/34780638/37876591-d4a99178-304e-11e8-9b4b-205c578cb73c.png)
:neutral_face:

**Comment by Sheep04** [comment]
+remegés (szóval folyamatosan haldokoltam xD)

**Comment by andris155** [comment]
Ez játék hiba lesz. Sajnos nem tudom javítani.
