### ISSUE TITLE
Chat Control ismét... :/

### ISSUE THREAD

**Issue by Sheep04** [andris155/TheOld-Crafters#1913]
Vajon mi is itt
    a probléma?
    Hát ez:
![2018-03-25_17 49 03](https://user-images.githubusercontent.com/34780638/37877020-ff14db42-3054-11e8-9540-e677e46da877.png)
![2018-03-25_17 49 05](https://user-images.githubusercontent.com/34780638/37877025-0d94f4e0-3055-11e8-8e78-ca52ba6ae692.png)

Üdvözlettel:
Sheep04

**Comment by poma123** [comment]
Az r az a reply-t jelenti, vagyis a választ. Annak a játékosnak küldené el az üzenetet, aki legutóbb írt neked. Akárkit írsz az r után, azt nem érzékeli annak, hogy neki akarod küldeni. Használd az /m-et vagy a /tell-t. Ez nem hiba.

**Comment by Sheep04** [comment]
Nem is vettem észre, hogy /rben írtam xD
Köszi az észrevételt :D
