### ISSUE TITLE
Szabályzat

### ISSUE THREAD

**Issue by Kelvin172** [andris155/TheOld-Crafters#1914]
A szabályzatban a területen lévő (békés) mobok számát lehetne korlátozni levédésenként 35 helyett 100x100-as területen 35-re és így a régiós levédéseknél nem lehet belekötni, hogy egy levédésen (vagyis akár 1000x1000-es területen) 35 békés állat.

**Comment by andris155** [comment]
Töröltem a szabályt erre.
