### ISSUE TITLE
Bolt bug.

### ISSUE THREAD

**Issue by Sanszi** [andris155/TheOld-Crafters#1915]
A mai napon találtam egy bugot a boltban miszerint a búza blokkot megvéve, átalakítva búzává, majd azt eladva a boltban pénzt lehet "csalni".

Üdv: Sanszi

**Comment by andris155** [comment]
Annyira jól lehet ezzel keresni, hogy megérje?

**Comment by Sanszi** [comment]
szerintem néhány nap alatt milliókat lehet vele összeszedni.. szóval igen.

**Comment by MrZero1** [comment]
Javítva. Köszönjük az észrevételt.
