### ISSUE TITLE
Chc Colour hiba

### ISSUE THREAD

**Issue by Sheep04** [andris155/TheOld-Crafters#1919]
Üdv!

Feljöttem a szerverre, akkor az a látvány fogadott engem, hogy
![2018-03-29_08 04 11](https://user-images.githubusercontent.com/34780638/38079819-20d02f5a-3340-11e8-965f-7c56b176de69.png).
Szóval rang lejárta után megmaradt a chatcolor.
A hibát jelentettem kangarkonak, de ide is, hátha tudtok valamit kezdeni a hibával :D

Sheep04, avagy Sanyi, a vízálló bárány!

**Comment by andris155** [comment]
javítva 330 OCD
