### ISSUE TITLE
Tehénfej

### ISSUE THREAD

**Issue by Sheep04** [andris155/TheOld-Crafters#1920]
Üdv!

Aprócksa hibácska:
A tehén helyett Steve fej van / azzá vált.
![2018-03-29_09 07 32](https://user-images.githubusercontent.com/34780638/38080036-aff5dc8e-3340-11e8-83c2-ee9b24152098.png)

Sheep04, avagy Sanyi, a vízálló bárány!

**Comment by andris155** [comment]
Frissítve
