### ISSUE TITLE
Sivatag random tp

### ISSUE THREAD

**Issue by Sheep04** [andris155/TheOld-Crafters#1921]
Üdv!

A sivatag warp random tpje ide hozott:
![2018-03-29_09 09 47](https://user-images.githubusercontent.com/34780638/38080141-f9d848be-3340-11e8-8f80-0b8fb452e9a6.png)

Sheep04, avagy Sanyi, a vízálló bárány!

**Comment by andris155** [comment]
Üdv!
Sajnos nem olyan nagy a sivatag ezért rakott oda.
