### ISSUE TITLE
Vas addolás vasgólemekkel

### ISSUE THREAD

**Issue by Sheep04** [andris155/TheOld-Crafters#1923]
Üdv!

Ha kreatívban lerakjuk a vasat, és túlélőben a tököt, majd a vasgólemet megöljük, ingyen vasra thetünk szert.
![2018-03-30_11 33 46](https://user-images.githubusercontent.com/34780638/38133209-8ac0e232-340e-11e8-9d88-1e0ec351489b.png)
![2018-03-30_11 34 13](https://user-images.githubusercontent.com/34780638/38133217-90beb63c-340e-11e8-923a-8a9519e61653.png)
![2018-03-30_11 34 18](https://user-images.githubusercontent.com/34780638/38133289-e569c5be-340e-11e8-94d3-4859db7f5078.png)
![2018-03-30_11 34 44](https://user-images.githubusercontent.com/34780638/38133221-94cd8cbc-340e-11e8-8f23-b421d79e2a41.png)

Sheep04, avagy Sanyi, a vízálló bárány!

**Comment by andris155** [comment]
Erről videó kellene.

**Comment by Sheep04** [comment]
jó

**Comment by Sheep04** [comment]
De nincs, mert nem tudom felvenni. Szóval max. úgy tudom megmutatni, hogy feljössz a szerverre.

**Comment by UDPSendToFailed** [comment]
@Sheep04 

https://obsproject.com/hu/download
https://www.bandicam.com/downloads/

**Comment by andris155** [comment]
csináltam videót én.
