### ISSUE TITLE
Pet Arénánál hiányzó barrier

### ISSUE THREAD

**Issue by Sheep04** [andris155/TheOld-Crafters#1924]
![2018-03-30_17 41 12](https://user-images.githubusercontent.com/34780638/38143959-25fdb6ba-3443-11e8-9ec0-8b3b1182ebe0.png)

Sheep04

**Comment by Sheep04** [comment]
![2018-03-30_18 30 31](https://user-images.githubusercontent.com/34780638/38145385-4b1be358-3449-11e8-8d34-565f33de5085.png)
![2018-03-30_18 31 45](https://user-images.githubusercontent.com/34780638/38145388-4cdbc00a-3449-11e8-8db3-91f981eefb6e.png)

**Comment by poma123** [comment]
Javítva!
Köszönjük a hibajelentést
