### ISSUE TITLE
Chatszabály frissítés

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#1926]
Szia. Egy új chatszabályra lenne szükség, kezd zavaró lenni mostanság, és mivel a szabályzatra hivatkozva nem fejezik be, ezért kérvényezzük ezt.
+ A chatet használd normálisan, úgy, hogy az ne zavarjon más játékosokat.

Vagy valami ilyesmi, igazából a lényeg, hogy az értelmetlen írásmód és a nem odaillő témákat ne a szerveren vitassák meg. Köszi.

**Comment by andris155** [comment]
A chat kulturált használata?

**Comment by MrZero1** [comment]
Igen, az jó lenne.

**Comment by andris155** [comment]
1.12, A chat kulturálatlan használata tilos! [Szándékos helytelenül írás, nem odaillő téma stb...]
