### ISSUE TITLE
Pettel aktiválódhat más redstone lapja.

### ISSUE THREAD

**Issue by Sheep04** [andris155/TheOld-Crafters#1931]
Nem tudom kinyitni.
![2018-04-01_21 07 05](https://user-images.githubusercontent.com/34780638/38176522-d30c8a76-35f0-11e8-950c-dae7605613f9.png)
Józsi kinyitja.
![2018-04-01_21 07 31](https://user-images.githubusercontent.com/34780638/38176523-e380f09a-35f0-11e8-89bb-2b365bf30323.png)

**Comment by Sheep04** [comment]
Ja igen, a texture pack :laughing:

**Comment by akos222** [comment]
a barlangom :( 
vigyázzatok rá

**Comment by andris155** [comment]
Mivel a pet mob-nak számít és a mob-tól nem lehet bekérni jogokat így tudja aktiválni.
