### ISSUE TITLE
Savsziget: Szavazóbolt infó hiány

### ISSUE THREAD

**Issue by Icecroft** [andris155/TheOld-Crafters#1933]
Hali! Ha a szavazóboltban akarok vásárolni, nem tekinthetem meg, hogy mennyi pont áll még a rendelkezésemre. Csak az eddig leadott összpontszám.

**Comment by poma123** [comment]
Survival-on sem kerül kiírásra, nem?

**Comment by Icecroft** [comment]
Ebben csak az a kellemetlen, hogy néhány vásárlás után már nem emlékszem, mennyit költöttem, nem tudom visszaszámolni, hogy mennyim maradt.
