### ISSUE TITLE
ChatControl color probléma

### ISSUE THREAD

**Issue by poma123** [andris155/TheOld-Crafters#1934]
Sizarra valamiért elit ranggal is színesen ír, pedig nincs joga a /chc color-hoz. Nem ír színkódot, szóval nem értem miért van ez.
![image](https://user-images.githubusercontent.com/25465545/38191006-25febea4-3667-11e8-97ab-791cc12b9792.png)

Üdv, poma123

**Comment by akos222** [comment]
https://github.com/andris155/TheOld-Crafters/issues/1919

**Comment by andris155** [comment]
Javítva!
Köszönjük a hibajelentést!
