### ISSUE TITLE
Raktárvadász event egyik részén a parancsok nincsenek letiltva

### ISSUE THREAD

**Issue by Sheep04** [andris155/TheOld-Crafters#1936]
Üdv!
Volt ez a tp-s dolog is, ehhez kapcsolódik, hogy kreatív játékmódba is tudtam lépni eventen belül.
(képen egy blokkal léptem arrébb)
![2018-04-03_18 23 33](https://user-images.githubusercontent.com/34780638/38262065-6cf129b8-376c-11e8-9743-75f5f3c31d3b.png)
![2018-04-03_18 23 36](https://user-images.githubusercontent.com/34780638/38262067-6e8482a2-376c-11e8-9741-fa726a64a4d6.png)
Sheep04, avagy Sanyi, a vízálló bárány!

**Comment by andris155** [comment]
Nem találtam meg ezt a raktárvadász eventet.
