### ISSUE TITLE
WE a pokolban

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#1937]
Szia. A múltkor is rossz volt, most se jó.
Amikor gömböt akarok csinálni a pokolban (lásd kis kép, parancs) megcsinálja, viszont bugosan(?), mert nem látom, relative láthatatlan, viszont ott van mert úgy érzékeli, mintha ott lenne, ha újratöltöm a chunk-ot nem látom, csak ha világot váltok, majd visszatérek oda. 
Más világban egyből létrehozza és látom is. 
Nem tudom, bug vagy mi ez, gondoltam jelentem. 
![we](https://user-images.githubusercontent.com/29709854/38319786-fe8f29b2-3832-11e8-84f2-bec108c0712c.png)
![2018-04-04_18 00 39](https://user-images.githubusercontent.com/29709854/38319803-10c67892-3833-11e8-94f9-8dc98e886581.png)
![2018-04-04_18 06 02](https://user-images.githubusercontent.com/29709854/38319804-10f03c0e-3833-11e8-9c6a-89c35356d9ce.png)
![2018-04-04_18 06 10](https://user-images.githubusercontent.com/29709854/38319806-111b4480-3833-11e8-9dd3-716eec529508.png)

**Comment by andris155** [comment]
Szerintem ez inkább játék hiba lesz. :/

**Comment by andris155** [comment]
Optifine nélkül vagy Optifine-al próbáld meg. Én szerintem ez kliens hiba.
