### ISSUE TITLE
A szerver lefordítása magyar nyelvre OCD-ért

### ISSUE THREAD

**Issue by andris155** [andris155/TheOld-Crafters#1939]
## UltraCosmetics fordítás (50%) - 2540 OCD
https://github.com/andris155/TheOld-Crafters/tree/master/Ford%C3%ADt%C3%A1sok/UltraCosmetics

**Comment by Sizarra** [comment]
Határidőhőz van kötve?

**Comment by Sizarra** [comment]
Ha nem, lehet elvállalom.

**Comment by andris155** [comment]
Nincs határidő.

**Comment by Sizarra** [comment]
Rendben, akkor elkezdem

**Comment by Sheep04** [comment]
Én is belevállakozok valamennyibe :D 
A rangjogok átalakítása után van is az ocdre szükség :wink:

**Comment by poma123** [comment]
#1973

**Comment by Sheep04** [comment]
Ha sizarra nem tart igényt az UltraCosmetics config lefordítására, talán lefordítom. Ha sikerül a 3000 sorból valamennyit is lefordítanom :smiley:

**Comment by Sizarra** [comment]
Forditom :D

**Comment by andris155** [comment]
Igazából le van fordítva, csak nem jól. Viszont a nem jóból lehet csinálni egy jót kb. akár 0 angol tudással is.

**Comment by poltergeist84** [comment]
EpicSpawner kész. Teszt szükséges, aztán átírom ahol kell. ;-)

**Comment by andris155** [comment]
Ami nincs kész valószínűleg le lesz cserélve, mert tele van hibával és már nem fejlesztik.
