### ISSUE TITLE
SkyPvP Old Rang 

### ISSUE THREAD

**Issue by geri5200** [andris155/TheOld-Crafters#194]
Nem tudom, hogy skypvp.n aki kifizet egy old rangot az miért nem kaphat chatcolor jogot. Ennyi kis fejlesztést szeretnék közölni.

**Comment by andris155** [comment]
Mert a chatcolort csak online játékostól lehet elvenni, és az oldgold plugin nem képes ezt nézni, hogy ki online, vagy ki nem.
