### ISSUE TITLE
Építész+ rangok

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#1940]
Szia. Beszéltünk az Építész+ szerveren lévő rangokról, a jelenlegi Építész rangot két részre bontani. 

Valamint a Murder kikerülésével az Információs boxot átírni: SurvivalGames, Mobaréna és más Minigame-ek: /warp eventek

Köszi.

**Comment by Sheep04** [comment]
Kikerült a Murder? :o 
Lesz új helyette?

**Comment by andris155** [comment]
Szia!
Milyen jogokat kellene másik rangba rakni és mi legyen a rang neve?

**Comment by MrZero1** [comment]
Építész - a //download és az egyéb schematikba való letöltés parancsot tiltani, WE és Voxel engedélyezve (igazából a jelenlegi rang, csak a letöltés parancsra nem lenne joga.)
Építész+ - A jelenlegi rang, a download parancsra is van engedélye.

**Comment by andris155** [comment]
kész
