### ISSUE TITLE
SurvivalGames

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#1941]
Szia. A játékba való becsatlakozást követően, ha megvan az 5 ember, lehet szavazni arénákra. Minden ilyen szavazásnál 3 arénát dob fel, ezt lehet növelni. Kellene is, 5 arénára, mivel relative sok aréna van.
A másik, amikor valaki megnyeri a játékos, kilépteti az arénából, a nála lévő cuccokat pedig a földre dobja, ezeket a cuccokat elvileg a végső villámcsapás, ami jelzi hogy ő nyert, törölné, de nem törli, így a következő játéknál fel lehet venni, ami nagy előny, ha egy jó kard volt nála az előző körben.
Ezzel lehet valamit kezdeni?

**Comment by andris155** [comment]
Mint már korábban írtam. Új plugin kellene. De ahhoz újra be kellene állítani minden arénát.
