### ISSUE TITLE
Fordítási hiba

### ISSUE THREAD

**Issue by Konc0321** [andris155/TheOld-Crafters#1952]
Savszigeten az aknakereső játékban vettem észre ezt a hibát. Az angol "mine" szónak nem a megfelelő értelmében lett lefordítva, ugyanis ebben az esetben nem bányát, hanem aknát jelent.
![kepkivagas](https://user-images.githubusercontent.com/38163260/38457775-1bc96eac-3a95-11e8-856d-84fccff07a41.PNG)

**Comment by andris155** [comment]
Konc0321 még nem regisztrált a http://theold.minemarket.hu/ oldalon.

**Comment by andris155** [comment]
Kinek adjam az OCD-t?

**Comment by Konc0321** [comment]
Regisztráltam ^^

**Comment by andris155** [comment]
204 OCD
