### ISSUE TITLE
Savsziget Old szett

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#1954]
Szia. Nézegettem a Minemarketet, látom, hogy Savszigetre sokkal gyengébb az Old szett, mint Survivalon (Survivalon X-es enchantúak, Savon 3-4-5 szintes). Az lenne a kérésem, hogy Savszigetre is ugyanaz a szett (tehát X-es enchantos) kerüljön be, mint Survivalon van (ugyanolyan áron).

**Comment by andris155** [comment]
Magyarul ugyan azok legyenek ott is mint a túlélő szerveren?

**Comment by MrZero1** [comment]
Igen igen.

**Comment by andris155** [comment]
kész
