### ISSUE TITLE
Privát üzenet stílus

### ISSUE THREAD

**Issue by GGeery** [andris155/TheOld-Crafters#1957]
Nagyon zavaró a kis posta ikon, tőle xy és az üzenet. A szín és a (számomra) szokatlan módszer által elveszik a chat-en, és nem nagyon lehet látni, nehéz észrevenni ha írnak neked. Ötletként ajánlanám a stílus megváltoztatását, vagy esetleg maradjon, de akkor hangot játszon le a játékosnak (pl.: 1x vagy 3x egy noteblock hang).

**Comment by andris155** [comment]
Ha valakinek a nevét @-al írod le, akkor elvileg kap hangjelzést. A privát üzenet formázását én jónak látom.
