### ISSUE TITLE
/vote buggoltatás

### ISSUE THREAD

**Issue by Sizarra** [andris155/TheOld-Crafters#1958]

**Comment by andris155** [comment]
Erről videó kellene.

**Comment by Sizarra** [comment]
https://www.youtube.com/watch?v=gITEmkJ79rI&feature=youtu.be Itt a videó

**Comment by Sizarra** [comment]
A /bolt és a /ah-val ez nem működik, még akkor sem ha először a /votet írom be

**Comment by andris155** [comment]
Jelentettem a fejlesztőnek.

**Comment by andris155** [comment]
Paper-re nem hajlandó fejleszteni a plugin fejlesztője. Nincs javítás.

**Comment by andris155** [comment]
1016 OCD
