### ISSUE TITLE
Savsziget több ember

### ISSUE THREAD

**Issue by GGeery** [andris155/TheOld-Crafters#1959]
Nem tudom mennyi egy szigetre a max befogadó ember, de növelni kéne, mert a mi részünkről minimum 10-en megvagyunk, és egy szigetet szeretnénk "művelni". Megoldható lenne, hogy több embert tudjak meghívni a szigetre, mint 6? Köszönöm :)

**Comment by poma123** [comment]
Frissítve.
Köszönjük a tanácsot!

**Comment by andris155** [comment]
Kész
