### ISSUE TITLE
Elírás

### ISSUE THREAD

**Issue by Konc0321** [andris155/TheOld-Crafters#1962]
A savsziget játékmenüjében hogyha a 2048 játék fölé viszem az egeret a következő szöveg jelenik meg: 
![kepkivagas](https://user-images.githubusercontent.com/38163260/38626859-ce05a76e-3dad-11e8-816c-f977adad44a1.PNG) 
A fordítást kétféle módon lehetne átírni:
1.) Mozdíts el ,,Csempéket" és add össze őket (Csempék előtti "a" eltüntetése)
2.) Mozdítsd el a ,,"Csempéket" és add össze őket. (A "Mozdíts" szó végére egy "d" betű helyezése)

**Comment by skrisz0101** [comment]
Andris kihirdette az újbóli forditást ocd-ért
Nézd meg leljebb

**Comment by andris155** [comment]
Javítva!
Köszönjük a hibajelentést!
