### ISSUE TITLE
Event világ jogok

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#1964]
Elég idegesítő, hogy event világban nincs kb semmire jog, el kell teleportálni, mielőtt használni tudnék valamit. 

Pár példa:

- /p h és /home előtt spawnra kell menni 
- /me 
- /tpa (/tpaccept nem kell)
- /ocd egyenleg
- /help
- /ec
- /partychat
- /lottery
- /ci
- /pay
- /seen
- /ptime
- /pweather
- /nick
- /afk
- /bal
- /baltop

**Comment by andris155** [comment]
Ez nem is az én megoldásom. Talám poma megoldása (?). Amúgy egyetértek ez így nincs jól megoldva, és abban a világban egyáltalán nem csak event van.

**Comment by UDPSendToFailed** [comment]
Boltban, és több warpon is ugyanez van.

**Comment by andris155** [comment]
Elvileg javítva amennyire lehetett.

**Comment by andris155** [comment]
204 OCD
