### ISSUE TITLE
Nocheat hiba

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#1965]
Ha víz melletti termőföld blokkon próbálok mozogni, miközben magasugrás beacon van a karakteren, bebugol, és nem lehet elmenni onnan, vagy csak nehezen.

https://www.youtube.com/watch?v=lU98XYFNEsY

**Comment by andris155** [comment]
megkérdezhetnéd mit ír ilyenkor az Admin-nak ha fent van vagy tulajnak.

**Comment by poma123** [comment]
Teszteltük, ugyanúgy néha bebugol a játékos, de nem jelez semmit.

**Comment by andris155** [comment]
Elvileg javítva.

**Comment by andris155** [comment]
508 OCD
