### ISSUE TITLE
UltraCosmetics rakéta

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#1966]
Ki lehet repülni a lobby-ból.

![2018-04-13_13 42 41](https://user-images.githubusercontent.com/16057404/38733069-dc035a68-3f20-11e8-9a41-3153a2003e00.png)

**Comment by andris155** [comment]
Van rajta világhatár meg a világban nem lehet építeni. Szerintem ennyi fun kell is bele. :D
