### ISSUE TITLE
Közös Láda

### ISSUE THREAD

**Issue by IcyAlex** [andris155/TheOld-Crafters#1969]
Nem tudom, hogy lehet e a Közös Ládát craftolni, de, ha nem akkor szerintem jó lenne, mert gyakrabban használnák.

**Comment by Sheep04** [comment]
Közös ládát nem lehet craftolni, az elnevezés is asszem parancsoktól függ, de ha rosszul mondom, javítsatok ki.

**Comment by andris155** [comment]
Ha üllőben átnevezed, akkor más lesz a neve.
