### ISSUE TITLE
Hibás aukció szöveg

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#197]
![2016-06-11_09 24 38](https://cloud.githubusercontent.com/assets/16057404/15983891/a43325b2-2fb6-11e6-9372-2b19a53d5d47.png)
![2016-06-11_09 24 40](https://cloud.githubusercontent.com/assets/16057404/15983890/a42ea384-2fb6-11e6-95d5-a9cb2c799b32.png)

**Comment by andris155** [comment]
Tudom több ilyen is van. Az 1.8 fordítása alapján lett csinálva ami azért valamivel közelebb állt a magyarhoz mint a mostani...

**Comment by andris155** [comment]
Viszont ez kivételesen jobb lett, szóval átírom.

**Comment by andris155** [comment]
javítva
