### ISSUE TITLE
Információ box

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#1971]
Szia.

Információs box-ba kellene hirdetni, hogy az Újszabad2 világba telepedjenek le, ott védjenek le házat stb.
Valamint a world és world2-ben letiltani a /zone create védést, tehát ebben a 2 világban ne tudjanak többet levédeni. (Védést törölni tudjanak, csupán csak levédeni ne tudjanak).

**Comment by poma123** [comment]
A második részét megcsináltam. world-ben és world2-ben.
![image](https://user-images.githubusercontent.com/25465545/38775648-23254d9e-4088-11e8-957f-4599e0bacc46.png)

**Comment by andris155** [comment]
ki is szedheted mert ezt nem így kell tiltani

**Comment by andris155** [comment]
Tiltottam rendesen.

**Comment by poma123** [comment]
:(

**Comment by andris155** [comment]
Mi az az információs box?

**Comment by andris155** [comment]
A zone-t tiltottam a kérd világokban meg a vég és pokolban is.

**Comment by andris155** [comment]
kész
