### ISSUE TITLE
End és pokol reset tábla

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#1974]
/warp tájak-nál, és az end / nether-ben is 2016 van a táblákon.

![2018-04-15_16 58 38](https://user-images.githubusercontent.com/16057404/38779853-8260246e-40ce-11e8-90d0-14ca3c84f0b0.png)
![2018-04-15_16 59 03](https://user-images.githubusercontent.com/16057404/38779854-82822852-40ce-11e8-9371-8d4efeba00dd.png)

![2018-04-15_17 02 14](https://user-images.githubusercontent.com/16057404/38779873-d77e0394-40ce-11e8-9610-862559fdb665.png)
![2018-04-15_17 02 30](https://user-images.githubusercontent.com/16057404/38779874-d7a115aa-40ce-11e8-9bf8-30185fe60a65.png)

**Comment by MrZero1** [comment]
Javítva.
