### ISSUE TITLE
Elbugolt repülő

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#1975]
Repülőben voltam, mikor kidobott a szerver, mire visszamentem, érdekes dolog történt vele. Shift + balklikkre megnyitja az üzemanyag cuccos inv-et, de jobbklikkre és shift + jobbklikkre nem reagál, más játékosnak se, tehát semmit se lehet csinálni vele. Raktam oda home-t rep néven.

**Comment by MrZero1** [comment]
Poma már visszaadta, ha jól tudom.

**Comment by andris155** [comment]
akkor megoldva
