### ISSUE TITLE
Bőr bug SavSziget

### ISSUE THREAD

**Issue by Viktor1969YO** [andris155/TheOld-Crafters#1976]
Ha bőrrel a kezemben akarom kinyitni a ládát akkor előhozza a WorldGuard-ot
![2018-04-16_17 26 58](https://user-images.githubusercontent.com/38433879/38819345-6d2c9ab4-419b-11e8-9f6e-cf4644b4dd37.png)

**Comment by andris155** [comment]
Ezzel az admin védés neveket látod. Ez nem bug.
