### ISSUE TITLE
Warp jogok #2

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#1978]
- /warp petaréna-ban nincs jog a pet-es parancsokra, így ennek a helynek semmi értelme.

- Boltban is jók lennének a pet-ek, ha sok itemet kell eladni, petinv-ben egyszerűbb szállítani. /back is tiltva van, így elég nehéz odavinni több láda cuccot. A /fly engedélyezése se ártana, most rangosként is végig kell sétálni az egész bolton.

- Plázában ugyanúgy tiltva van minden, mint boltban.

- /warp bánya - /fly vagy teleport táblák

- /warp fatelep - /fly 

Szerintem újra át kéne nézni a warpokat, mert így nem a legjobb megoldás, hogy egy global védéssel tiltva van minden.

**Comment by poma123** [comment]
- Javítva.
- Javítva.
- Javítva.
- Javítva.
- Javítva.

**Comment by andris155** [comment]
Javítva!
Köszönjük a hibajelentést!

**Comment by andris155** [comment]
330 OCD
