### ISSUE TITLE
Old Csizma és a Beacon

### ISSUE THREAD

**Issue by ksricsi** [andris155/TheOld-Crafters#1979]
Helló!

Találtam egy jó kis bugot(?). A Beacon Speed 2es effektje és az old csizmán lévő +50% speed Nem nagyon jön ki jól egymással. Mondhatni sehogy.:D Amikor guggolva szeretnék menni visszadobál és megakad. Arra emlékeztet, mint mikor rang nélkül próbál az ember repülni és letiltja. Van egy videóm is, ha elmondjátok hogy tudom ide feltölteni meg is tudom mutatni.:D
Remélem tudtok valamit kezdeni vele

**Comment by andris155** [comment]
Elvileg javítva. De ha nem akkor nem nagyon lehet sajnos javítani.

**Comment by andris155** [comment]
508 OCD
