### ISSUE TITLE
1.10

### ISSUE THREAD

**Issue by MrZeroTOC** [andris155/TheOld-Crafters#198]
Üdv Andris.

1.10 átállás után lehetne generálni egy vadon 2 világot, ahol megtalálhatóak lesznek az igluk (1.9), illetve a jegesmedvék, a biomváltozások stb.
Ezáltal a mob spawnolás is megoldódik, gondolom. Itt ki szeretnék térni, a pokol világ újra generálására. (Szintén új blokkok, stb.)

Üdv, MrZero

**Comment by Tyloendis** [comment]
Én már láttam iglut, a jelenlegi map határa előtt generálódik. Tehát 1.9 generálás már van. Gondolom ha a világ határ kijjebb lenne húzva, az új generálás már 1.10-es lenne.

**Comment by andris155** [comment]
A jelenlegi világ sincs legenerálva bőven van még mit generálni. Egyébként a jegesmedve spawnol elvileg 1.9-es helyeken is, az iglu meg szerintem annyira nem fontos.

**Comment by andris155** [comment]
A pokolban 1 db. új blokk lett, illetve lett még pár ami végül nem került be, hanem lehet 1.11-es újítás lesz, szerintem az új pokollal lehet kellene várni az 1.11-ig, egyébként a pokol világból is lehet még bőven generálni részeket, majd átrakom a warpot olyan helyre akkor, ami már 1.10-es lesz.

**Comment by Treuce** [comment]
A pokol világot megérné újra generálni mert ott a mob spawn tényleg nem jó, a vadon világot pedig hagyni kéne kb ahogy van és nem tovább generálni mert sok chunk hiba van így is benne szerintem és akkor lehetne helyette 1 új talán de kisebb világ

**Comment by andris155** [comment]
A pokol világban nem a világ hibája ha nem spawnol sok mob.
A world világban pedig 1 hibás chunk sincs, te az 1.6, és 1.7 elválasztó vonalat láthattad.

**Comment by Treuce** [comment]
nem hiszem hogy azt láttam volna és a másik hogy ezekkel a lagokkal is baj van ami ha jól tudom tárhely hiba szóval nem lenne rossz valami jó megoldást találni rá szerintem pl kisebb nether világot generálni, az SG világnak beállítani valami olyan határt ami kell és még elfér pár dolog oda vagy végső esetben egy új vadon de úgy hogy lenne idő elpakolni onnan..

**Comment by andris155** [comment]
Treuce ha lehet ne szólj bele azokba a dolgokba amikről semmit se tudsz.

**Comment by andris155** [comment]
A Tárhely gondot eddig is megoldottuk, és a jövőben is meglesz.

**Comment by andris155** [comment]
A laggok legutóbb akkor voltak mikor 3 hét után frissítettem 1 rakat plugint. A vizsgák miatt vártam vele ennyit. Ezek után várható volt, hogy valami nem lesz jó.

**Comment by andris155** [comment]
Persze azóta meglett oldva.

**Comment by andris155** [comment]
Szóval:
A sima világ marad.
A pokol is marad, de rakok 1.10-es helyre majd warpot.
