### ISSUE TITLE
Csirke-Macska nézeteltérések

### ISSUE THREAD

**Issue by Sheep04** [andris155/TheOld-Crafters#1980]
Üdv! A farmon voltam, mikor észrevettem, hogy a vadmacskák a csirkéknél tanyáznak.
![2018-04-23_09 16 50](https://user-images.githubusercontent.com/34780638/39111976-57553e3a-46d7-11e8-85db-372b110ff341.png)
![2018-04-23_09 17 07](https://user-images.githubusercontent.com/34780638/39111985-5dfe3c8c-46d7-11e8-849e-9f29a6299747.png)
![2018-04-23_09 17 09](https://user-images.githubusercontent.com/34780638/39111986-5f964238-46d7-11e8-903e-a89b36fa7ea2.png)

A macskákat ne tessék megölni, max elvinni máshova :D 

Sheep04, avagy Sanyi, a vízálló bárány!

**Comment by andris155** [comment]
XDD

**Comment by andris155** [comment]
A dzsungel biome előnyei xd

**Comment by andris155** [comment]
javítva.
