### ISSUE TITLE
Víz-Denevér bug

### ISSUE THREAD

**Issue by Sheep04** [andris155/TheOld-Crafters#1981]
Üdv! Asdragon pwarpján voltam, és még mások, valakinek van egy denevér petje. Nem vagyok hozzáadva a zónához, de kreaívban (talán túlélő módban is) sikerült leraknom vizet a denevér helyére.
 
![2018-04-23_15 06 44](https://user-images.githubusercontent.com/34780638/39128580-699842d2-4708-11e8-924c-6ee7f15e9dac.png)
![2018-04-23_15 07 45](https://user-images.githubusercontent.com/34780638/39128582-6b6b8e66-4708-11e8-9d0f-a622e8fde1ea.png)

Sheep04, avagy Sanyi, a vízálló bárány!

**Comment by Sheep04** [comment]
Másoknak nem látszódott a víz, csak, hogy úszom a semmiben. Illezve ők nem tudtak úsznia az "én vizemben". Az anticheates plugin próbáld megállítani a "repülesben" amikor túlélő módban voltam.

**Comment by poma123** [comment]
Ezt csak te látod, nem raktál le oda semmit. Csak a te kliensedben látszódik ameddig nem frissíted a chunk-okat.

**Comment by Sheep04** [comment]
Tudom.

**Comment by poma123** [comment]
Nem tudsz letenni vizet ahol nincs rá jogod (nem vagy hozzáadva), tehát nincs probléma. Akkor mi a gond?

**Comment by Sheep04** [comment]
Az a probléma, hogy nekem látszik és úszok benne. És azt mások is látják ha én úszok benne, viszont a vizet nem. Illetve, ha a levegőben van a másoknak láthatatlan víz, akkor bekapcsolódik az anticheat és lagoltat a levegőben.

**Comment by andris155** [comment]
Szerintem ez játék hiba. Nem szerver.

**Comment by Sheep04** [comment]
Akkor jelentem a Mojangnál, ha nagyon zavarna engem vagy bárki mást később...

**Comment by andris155** [comment]
Ha a Mojang-nál jelented nézd meg nem MyPet-es denevérrel is.
