### ISSUE TITLE
Elytra + tűzijáték kreatívban

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#1982]
https://youtu.be/Gq-0j2IUacA

Ez a sima repülésnél sokkal gyorsabb, és elvileg az is tiltott a szabályzatban.

![kep](https://user-images.githubusercontent.com/16057404/39184781-12380708-47c5-11e8-8782-0325a8445ae3.png)

**Comment by andris155** [comment]
javítva
