### ISSUE TITLE
Fordítás problémák

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#1985]
Pet plugin:

![image](https://user-images.githubusercontent.com/16057404/39246201-231e258a-4896-11e8-862f-fe2d25c0ad8d.png)

Krea védelem:

![image](https://user-images.githubusercontent.com/16057404/39246245-4aeda964-4896-11e8-83a3-d1b6d8d6a575.png)

**Comment by andris155** [comment]
204 OCD
