### ISSUE TITLE
YouTube rang tájékoztatás

### ISSUE THREAD

**Issue by yghrt** [andris155/TheOld-Crafters#1986]
Üdv, rég jelentettem be hibát, de ha aktuális már a YouTube rang fejlesztés ami ki lett posztolva, akkor cserélhetitek a YouTube rang tájékoztató warpnál a változásokat.

Pl.:
![nemaktualis](https://user-images.githubusercontent.com/35996682/39314267-2952779c-4974-11e8-864c-e52d87bc0d31.png)

-yghrt

**Comment by yghrt** [comment]
Továbbá a /warp rangok leírásánál még az áll hogy csak 30 napig érvényesek.
![nevtelen2](https://user-images.githubusercontent.com/35996682/39317213-5a1431a2-497b-11e8-9bf9-1d394bc55061.png)

**Comment by MrZero1** [comment]
Átírva, köszi.

**Comment by andris155** [comment]
204 OCD
