### ISSUE TITLE
Chc color

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#1987]
Szia.

Survival szerveren melyik rangtól van jog erre a parancsra? Ha van még. Ha nincs, lehetne szerintem. 
Valamint Savsziget szerverre Prémium rangtól elérhető lehetne ez a jog? 
![chc](https://user-images.githubusercontent.com/29709854/39319749-46f4e31c-4982-11e8-8793-839e792c84c8.png)

**Comment by andris155** [comment]
Nem tudok rá parancsot, amivel lehetne törölni az adott ember chat színét. Így csak adatbázis törléssel lehet másét törölni, ami pedig nem túl jó megoldás.
