### ISSUE TITLE
Savsziget end reset

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#1988]
Szia.

Szó volt az end resetről savszigeten, ám erről nem érkezett tájékoztatás feléd (ahogy hallottam róla).
Április 30.-án a survival szerveren lévő end és nether resettel együtt meg lehetne ejteni savszigeten is, kizárólag az END világ resetelését. Köszi

**Comment by andris155** [comment]
Szia!

A savszigeten trimeltem a világot így már csak 3 GB körül van. Biztosan legyen így is világ reset ott is?

**Comment by andris155** [comment]
Kész
