### ISSUE TITLE
PvPAréna

### ISSUE THREAD

**Issue by Treuce** [andris155/TheOld-Crafters#199]
1. Aréna áthelyezése egy másik világba(mobaréna) hogy ne lehessen egyáltalán godban bemenni mert jelenleg kilehet játszani.
2. Mindenféle teleport tiltása az arénából, helyette 2 kijárat ami valami módon be van lassítva és így ha van valami utol lehet érni azt aki szökni akar és miután valaki átér ezen a "határvonalon" lehetne engedélyezni a teleportokat és így lehetne elhagyni az arénát.
3. Ha marad az a warp pont ami most van hogy létrával lehet bemenni akkor azt egyel feljebb emelni mert jelenleg magasugrással kilehet menni oda a pvp zónából.

**Comment by andris155** [comment]
megoldva.
