### ISSUE TITLE
mcMMO hiba.

### ISSUE THREAD

**Issue by KingDeadZ** [andris155/TheOld-Crafters#1992]
Az mcMMO Baltászat 1-ik képességével el lehet ütni állatokat mások telkéről/levédéséről.
Mi okozza ezt? Az "Erős ütés"nek van 1 olyan tulajdonsága, hogy elég szépen hátralöki az állatokat.

**Comment by andris155** [comment]
Erről tudsz videót csinálni?

**Comment by andris155** [comment]
Ha jól értelmezem ez lenne az nem?
https://github.com/IntellectualSites/PlotSquared/issues/1874

**Comment by KingDeadZ** [comment]
Nem ad XPt az adott skillnek. Csak az abilityvel lehet ellökni entitásokat.

**Comment by andris155** [comment]
Sajnos a fejlesztő nem igazán akarja ezt javítani egyelőre. Addig nem tudok ezzel én sem mit csinálni.
