### ISSUE TITLE
SurvivalGames

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#1994]
Szia.

Az SG minigame-ben, a becsatlakozást követően, ha meg van az 5 játékos, egy szavazást kínál fel, ahol 3 map közül lehet választani (láda, ugye.)
Ennek a számát nem lehet növelni 5-re?
Rengeteg aréna van, legyen miből választani.

**Comment by andris155** [comment]
szia!
Elvileg kész, majd le kellene tesztelni.
