### ISSUE TITLE
Spawner menü

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#1996]
A spawner menü nem működik, jobbklikkre nem csinál semmit, csak akkor nyitja meg, ha plot világban van lerakva a spawner.

**Comment by UDPSendToFailed** [comment]
+1: Pár szóköz hiányzik a fordításból.

![kep](https://user-images.githubusercontent.com/16057404/39630005-47b1b4f6-4fae-11e8-8896-1cc38be0a696.png)

**Comment by andris155** [comment]
Ki is javíthatnád egy pull-ban azzal több OCD-t is kapnál.

**Comment by andris155** [comment]
Javítva

**Comment by andris155** [comment]
204 OCD
