### ISSUE TITLE
Gépelési hiba szigetről való kitiltásnál

### ISSUE THREAD

**Issue by Konc0321** [andris155/TheOld-Crafters#1998]
Savszigeten amikor kitiltok valakit a szigetemről  a következő szövegek jelennek meg: 
![rekettyes](https://user-images.githubusercontent.com/38163260/39641097-553b9e7e-4fcd-11e8-9061-3bba6cfeabbb.png)
1. [név] kiLiltva a szigetről
2. Ban tiltott [név]

**Comment by poma123** [comment]
Javítva!
Köszönjük a hibajelentést.
