### ISSUE TITLE
Savsziget Küldetés nyeremény eltérés+elírás

### ISSUE THREAD

**Issue by Csipeszto** [andris155/TheOld-Crafters#1999]
Savszigeten a Lehetetlen küldetésnél a nyeremény 1 gyémánt, de ténylegesen 10-et kaptam.
A küldetés neve is el van írva: Lehetlen.

![kuldiajielteres](https://user-images.githubusercontent.com/38987705/39641427-5e852f80-4fce-11e8-8d19-a4a276703dff.png)

Üdv. Csipeszto

**Comment by poma123** [comment]
Javítva!
Köszönjük a hibajelentést.
