### ISSUE TITLE
Survival games kikapcsolt pvp-vel.

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#2]
Survival games-re (/sg join) be lehet lépni kikapcsolt pvp-vel, kb lehetetlen megölni azt, aki így játszik.

**Comment by andris155** [comment]
Tegnap elvileg beállítottam délután. Most is belehet, és ha igen akkor kikapcsolva is marad?

**Comment by andris155** [comment]
Javítva. A PvP kezelő frissítve.

**Comment by andris155** [comment]
Javítva ismét:
A SurvivalGames világ hozzáadva a kivételekhez a PvP kezelőben.
