### ISSUE TITLE
Nick adása más játékosnak.

### ISSUE THREAD

**Issue by Kronox12** [andris155/TheOld-Crafters#20]
Ha beírom a /nick parancsot,akkor csak a saját nevemet tudom átszínezni.De tegyük fel,hogy Józsi kék névvel rendelkezik egy előző rangból,de a rang lejár,a név viszont marad.
A helyzet a következő: beírom ezt a parancsot : /nick Józsi Józsi ,de csak azt kapom vissza,hogy a becenevekben csak a színek változtathatóak.Mondom okés,próbáljuk meg így: /nick Józsi &fJózsi.
Így sem ment.De viszont ha a saját nevemet akarom átszínezni(pl: /nick Kronox12 &fKronox12),akkor rendesen müködik,de más nevénél nem.

**Comment by andris155** [comment]
Üdv!
Most jó?

**Comment by Kronox12** [comment]
Igen,mostmár jó :D

**Comment by andris155** [comment]
:)
