### ISSUE TITLE
EpicSpawners

### ISSUE THREAD

**Issue by Sheep04** [andris155/TheOld-Crafters#2002]
Üdv!
Ki akartam ütni két spawnert (silk touchal természetesen), és nem droppolta ki.
Fejlesztett emerald pickaxe, a két spawner egymáson volt (nem omni, mert shifteltem), redstone blokkal próbáltam kreában befedni, mert le akartam állítani, sikertelenül...xd

Sheep04

**Comment by Sheep04** [comment]
Illetve a spawner 'kiírása' megmaradt.
![2018-05-05_10 07 05](https://user-images.githubusercontent.com/34780638/39661073-3c3f55a8-504c-11e8-8bd0-eda2b237e37e.png)

A csákánynak nem töltöttem be a forráscsomagját.

**Comment by andris155** [comment]
Rakj a helyére egy másik spawner-t és próbáld meg azt kiütni.
