### ISSUE TITLE
Additions

### ISSUE THREAD

**Issue by Sheep04** [andris155/TheOld-Crafters#2003]
Üdv!

Fejlesztettem a smaragd csákányomat silk touchra tegnap, és a neve rEmerald Pickaxe lett mivel nem lehet § karaktert használni. Ha nem is fejlesztem, akkor, ha a másik oldalán venném ki, úgy veszi, mintha átneveztem volna, mert írt költséget.
Itt most karddal mutatom be:
![2018-05-05_10 27 21](https://user-images.githubusercontent.com/34780638/39661296-7a63a2aa-504f-11e8-9c04-0012312a6d04.png)
![2018-05-05_10 27 46](https://user-images.githubusercontent.com/34780638/39661298-7fd355f0-504f-11e8-8833-48b557599649.png)
![2018-05-05_10 27 54](https://user-images.githubusercontent.com/34780638/39661300-84eb4476-504f-11e8-82b7-7a9fb0a16c9f.png)

Sheep04

**Comment by andris155** [comment]
Erről videó kellene.

**Comment by Sheep04** [comment]
Akkor nem lesz egyhamar megjavítva :(

**Comment by Sheep04** [comment]
Tessék, a várva várt videó:
(A videót 8DaveedHun18 vette fel, mellesleg...)
https://youtu.be/adeXKYzTDXM?t=45s

**Comment by andris155** [comment]
Nincs berakva a forráscsomag(?)

**Comment by andris155** [comment]
Ez a videó így érvénytelen.

**Comment by andris155** [comment]
Jó lesz a kép. Megoldom azzal a jelentést a fejlesztőnek.

**Comment by Sheep04** [comment]
Ezek szerint nincs betöltve a forráscsomagja, de forráscsomag betöltésével is ilyen problémás volt. Miért lenne érvénytelen a videó? Na mindegy is, legközelebb másnak szólok, hogy segítsen...

**Comment by andris155** [comment]
Sajnos a fejlesztő nem igazán foglalkozik a plugin-al. Annyira nem tartom nagy hibának. Talán majd a jövőben javításra kerül, de inkább a komolyabb hibákat javítjuk elsősorban.
