### ISSUE TITLE
Utalásnál nyelvtani helytelenség

### ISSUE THREAD

**Issue by Csipeszto** [andris155/TheOld-Crafters#2004]
OCD feltöltése utalással leírásban van egy nyelvtanilag elírt szó. 

![utalaseliras](https://user-images.githubusercontent.com/38987705/39664656-99acdb4a-5086-11e8-9b02-43b21904341c.png)

Az "adatokat" szóra nem kell rag.
Helyesen: A számlázási adatok kitöltése kötelező...

**Comment by andris155** [comment]
javítva

**Comment by andris155** [comment]
204 OCD
