### ISSUE TITLE
Weboldal szabályok és parancsok

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#2005]
Pár helyen van benne elírás.

**Szabályok:**

![kep](https://user-images.githubusercontent.com/16057404/39672939-a9753a2e-5133-11e8-8630-5ee0e2adbf13.png) (&7 nem kell.)

![kep](https://user-images.githubusercontent.com/16057404/39672947-bbe83328-5133-11e8-8d12-9cd6190d9559.png) (1 ember után nem kell vessző.)

![kep](https://user-images.githubusercontent.com/16057404/39672970-1ea55a9a-5134-11e8-8eb3-9fd4ae227678.png) (. vagy !)

**Parancsok:**

![kep](https://user-images.githubusercontent.com/16057404/39673024-0d32a9e2-5135-11e8-8baa-3e2c14cc8f92.png) (Helyesen fakarddal.)

![kep](https://user-images.githubusercontent.com/16057404/39673050-9b97c2bc-5135-11e8-9bc9-404570cd6d3b.png) (Vesszők hiányoznak, üreset.)

![kep](https://user-images.githubusercontent.com/16057404/39673069-dc796c90-5135-11e8-848e-9d40c76c3791.png) (Kisállat.)

![kep](https://user-images.githubusercontent.com/16057404/39673075-f1b17bfc-5135-11e8-8c02-02afb8bab9fe.png) (Nincs jog a parancsra a szerveren.)

- Murder rész - nincs bent a plugin.

![kep](https://user-images.githubusercontent.com/16057404/39673087-37393002-5136-11e8-8837-1bb9df12d01a.png) (Megnyitja.)

![kep](https://user-images.githubusercontent.com/16057404/39673088-44c853b0-5136-11e8-87ea-2a61ce347f4c.png) (Megnyitja.)

![kep](https://user-images.githubusercontent.com/16057404/39673096-580bb5b6-5136-11e8-8d36-e6aa14ba448a.png) (Ez nem tudom, mi lenne, de így nem túl értelmes mondat.)

![kep](https://user-images.githubusercontent.com/16057404/39673107-725a0bd4-5136-11e8-998d-8b0d2cc65042.png) (Teljes hozzáférés biztosítása a játékosnak a szigetedhez.)

![kep](https://user-images.githubusercontent.com/16057404/39673123-b4d4edda-5136-11e8-9221-f4883fe4af60.png) (/ai ban a kitiltás, ez csak elveszi a jogot.)

![kep](https://user-images.githubusercontent.com/16057404/39673129-c469a196-5136-11e8-8a06-9cfb61f5435d.png) (Aki coop, teljes joga van a szigethez, de nincs oda bezárva.)

Illetve több helyen is vesszőhibák, hiányzik a pont a mondat végéről, és / vagy kisbetűvel van kezdve, ezekről nem csináltam külön képet.

**Comment by andris155** [comment]
Sajnos Microsoft Word-öm nincs, hogy kiírja a vesszőhibákat. Ahol tudom, hogy kell oda persze kirakom, de én se tudok sajnos minden nyelvtani szabályt pontosan.

**Comment by andris155** [comment]
A savsziget fordítása vicc, azt nem a szerver fordította.

**Comment by andris155** [comment]
Javítva amit sikerült megtalálni.

**Comment by andris155** [comment]
508 OCD
