### ISSUE TITLE
EpicSpawners fejlesztés hiba

### ISSUE THREAD

**Issue by KingDeadZ** [andris155/TheOld-Crafters#2006]
Nem tudtam fejleszteni a spawnereket, mert nem volt ott a lehetőség.
![2018-05-06_15 42 34](https://user-images.githubusercontent.com/38157910/39673931-edb9f4c0-5144-11e8-8102-1a210d1be39c.png)

**Comment by andris155** [comment]
Megszűnt a lehetőség. Már csak úgy lehet fejleszteni ha egymásra rakod a spawnereket.
