### ISSUE TITLE
Vonatos plugin

### ISSUE THREAD

**Issue by Sheep04** [andris155/TheOld-Crafters#2008]
Üdv!

Nézegettem egy plugint, amivel össze lehet kapcsolni a vonatokat és fejjel lefele is haladnak. Van hozzá resource pack is, de az olyan csúnya, hogy azt nyugodtan lehet mellőzni.
A plugin: https://www.spigotmc.org/resources/traincarts.39592/

Sheep04

**Comment by andris155** [comment]
Egyelőre más irányba fejlesztünk. Később lehetséges, hogy ez is bekerül.
