### ISSUE TITLE
Repülő P-61 - BUG

### ISSUE THREAD

**Issue by poma123** [andris155/TheOld-Crafters#2011]
Ritkán ha féllapra szeretnénk letenni a repülőt kiveszi a kezünkből a ládát, de sehol sincs a jármű.
Eddig kétszer hallottam és egyszer láttam ilyet, Saii1 szólt, hogy elbugolt neki a P-61-es repülő, és láttam, hogy egy féllapból készült tető legfelső rétegére tette le. Utána én is kipróbáltam, és szintén ugyan oda tettem, majd elbugolt. Épp úgy, ahogy az első sorban írtam.

A tető:

![image](https://user-images.githubusercontent.com/25465545/39699961-c8f174a8-51fb-11e8-94cd-93e3899fd327.png)

**Comment by andris155** [comment]
Nem tudom mitől lehet. Mindenképp add neki vissza.
