### ISSUE TITLE
Hp regen hiba (szerintem, mivel nem annyira 1.7es a szerver :s)

### ISSUE THREAD

**Issue by KingDeadZ** [andris155/TheOld-Crafters#2013]
Annyi lenne az egész, hogy nem úgy regenerálódok a steaktól, mint eddig hanem úgy mint régen 1.7ben. Az éhséget ugyan úgy viszi le, mint 1.12.2ben  de a hpt csak úgy adja mint 1.7ben.

                         Ha ez nem 1 hiba, akkor sorry.

**Comment by KingDeadZ** [comment]
1.12.2 Forge. Semmilyen olyan modot nem használok ami ezt bezavarná. (Kiegészítő modok pl: Minimap,WAILA stb)

**Comment by KingDeadZ** [comment]
![2018-05-07_14 56 51](https://user-images.githubusercontent.com/38157910/39703020-0b17cf02-5207-11e8-92dc-90fa2c9ed73f.png)
Ez a teljes listája a modoknak, amikkel játszom. (3 új modot raktam be ma, macro keybinds,appleskin,BetterFPS lehet hogy majd megnézem úgy is a hp regent, hogy szépen sorban kiveszem mind a 3 modot.)

**Comment by KingDeadZ** [comment]
Update: SGben normális volt a hpregen, semmilyen modot nem vettem ki.

**Comment by andris155** [comment]
javítva
