### ISSUE TITLE
EpicSpawners

### ISSUE THREAD

**Issue by KingDeadZ** [andris155/TheOld-Crafters#2014]
A reggeli restart után mindenkinek befagyott mobokat spawnol a spawnerje.

(Igazolatlan: Ha 3 fajta spawner van az Omni Spawnerben, akkor csak 2 fajtát tudsz belőle kiszedni. Ez tesztre vár, 2x ütöttem szét az omni spawnert ami 3 fajtából áll, és csak 2t adott vissza mindíg.)

**Comment by brtamas0** [comment]
KingDeadZ tipp: este amikor lelépsz üsd ki silk touchal spawnert.

**Comment by KingDeadZ** [comment]
Kiütöttem, 3 fajta spawner volt az omnispawnerben, abból csak 2t droppolt ki.

**Comment by UDPSendToFailed** [comment]
Nekem is megvan ugyanez a hiba.

**Comment by andris155** [comment]
Holnap frissül a plugin, ha nem oldódik meg, akkor nyissatok új hibajelentést. Ezenkívül én is állítottam rajta dolgokat.
