### ISSUE TITLE
Door craftbook

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#2016]
Szia.

Érdekesen működik a [Door] craftbook.
Elliot szólt, hogy nem jó, üvegből akart csinálni. Kiírta, hogy nem lehet ebből a blokkból, de lehet, teszteltem, sikerült csinálnom. Aztán mégsem működött. Vagyis furán. Csatolok pár képet. 
![2018-05-08_13 04 07](https://user-images.githubusercontent.com/29709854/39753937-d68b4fd8-52c0-11e8-9277-ad8b540ac1bb.png)
![2018-05-08_13 04 23](https://user-images.githubusercontent.com/29709854/39753938-d6abb246-52c0-11e8-8d7f-9232f0262fa5.png)
![2018-05-08_13 04 26](https://user-images.githubusercontent.com/29709854/39753939-d6cab98e-52c0-11e8-8683-6d63d7b04bdd.png)

**Comment by andris155** [comment]
Teszteltem és nekem tökéletesen működött.
![2018-05-08_17 26 39](https://user-images.githubusercontent.com/8324198/39766618-059c4894-52e5-11e8-949f-f1e259fca6dd.png)

**Comment by andris155** [comment]
Ahogy írja is. Több üveg kell hozzá neki.
