### ISSUE TITLE
Plugin javaslatok.

### ISSUE THREAD

**Issue by KingDeadZ** [andris155/TheOld-Crafters#2017]
https://www.spigotmc.org/resources/crafting-essential.56128/

Mindenféle craftolást hoz vissza/rak be a játékba.
Például ezeket:
Nyereg
Notch Alma
Almás Pite
Lópáncélok

https://www.spigotmc.org/resources/divineitemsrpg-1-9-1-12.40007/
Ezt nem tudom különösebben leírni.

https://www.spigotmc.org/resources/minions.52696/
Ebből van 1 ingyenes, és 1 prémium verzió is. 
Az ingyenesben 1 bányász minion van.
A prémiumban pedig sok.
Az SFes androidokhoz tudnám leginkább hasonlítani ezeket...
Konfigurálható árat lehet nekik megszabni, stb.

**Comment by andris155** [comment]
Egyelőre más irányba fejlesztünk.
