### ISSUE TITLE
Hibás kijelzés minemarketen 

### ISSUE THREAD

**Issue by KingDeadZ** [andris155/TheOld-Crafters#2018]
![image](https://user-images.githubusercontent.com/38157910/39763185-bf79a814-52dc-11e8-9f52-5f769d147c13.png)
 
![2018-05-08_16 25 43](https://user-images.githubusercontent.com/38157910/39763224-d40aefb8-52dc-11e8-8b47-7088202e5ac7.png)

**Comment by andris155** [comment]
Javítottam
