### ISSUE TITLE
Barátságos lények

### ISSUE THREAD

**Issue by MatiasX** [andris155/TheOld-Crafters#2019]
Az a gond hogy a falusiakat és kb az összes állatot képes az új plugin össze rakni (stackelni) 
emiatt kissé fura a játék menete, illetve mondjuk pár mobon állaton jól lehet farmolni így.

![falusikep](https://user-images.githubusercontent.com/36680020/39775186-66cf5cd8-52fd-11e8-97a2-b2e4ed09fb71.png)
![2018-05-08_20 06 41](https://user-images.githubusercontent.com/36680020/39775201-7362dc0e-52fd-11e8-9b8d-ed1f817119a5.png)

**Comment by andris155** [comment]
A falusinál letiltottam ezt.

**Comment by andris155** [comment]
Ui.: Telepítsd fel a driver-eket a Windows-ra illetve ne felejtsd el frissíteni az új build-re!
