### ISSUE TITLE
kedves andras kerem olvassa el

### ISSUE THREAD

**Issue by lavjuh** [andris155/TheOld-Crafters#2023]
mrzero adott nekem end kirstalyt es aztan ki tiltott !

![image](https://user-images.githubusercontent.com/39122961/39811969-1ce4ea3c-538b-11e8-8b46-20ecb21ba505.png)

**Comment by MrZero1** [comment]
Szellemi retardációóóó.

**Comment by KingDeadZ** [comment]
Adom
