### ISSUE TITLE
bizonyitek

### ISSUE THREAD

**Issue by lavjuh** [andris155/TheOld-Crafters#2024]
andras irtam facebookon is

![z1](https://user-images.githubusercontent.com/39122961/39815799-7dcd6cee-5399-11e8-850e-72979b6d5792.png)

![z2](https://user-images.githubusercontent.com/39122961/39815817-8842e4ba-5399-11e8-98a1-79c57b4558db.png)

**Comment by MrZero1** [comment]
Az a helyzet, hogy mikor ez a plugin volt, nem voltam Főadmin. Nice try
