### ISSUE TITLE
Elírások

### ISSUE THREAD

**Issue by Sheep04** [andris155/TheOld-Crafters#2028]
![2018-05-10_21 57 54](https://user-images.githubusercontent.com/34780638/39894153-3f678a9e-54a6-11e8-832f-dc072ac8dbfe.png)

Az "őt" után kell kettőspont.

![2018-05-11_13 22 12](https://user-images.githubusercontent.com/34780638/39922230-6d91c3c6-551e-11e8-87f8-f87ca94f9c26.png)
A "védd le" után felkiáltójel helyett vessz kell oda, **mert** különben kicsit értelmetlen.

**Comment by andris155** [comment]
javítva!
