### ISSUE TITLE
Prémium jobs booster

### ISSUE THREAD

**Issue by Treuce** [andris155/TheOld-Crafters#203]
Valami oknál fogva néha megvan az 50% boost a prémium jogú playereknek, néha pedig nincs. Nem egyszeri hiba és nem csak nekem. UDPvel mindketten észrevettük. Szerintem valami relog dologgal lehet a baj.

**Comment by andris155** [comment]
Elvileg nem kéne, hogy legyen valami új jogok vannak.

**Comment by Treuce** [comment]
És visszakerül vagy marad úgy hogy nincs?

**Comment by andris155** [comment]
Ha Kronox előkerül és megfejti a jogokat visszakerül. xd

**Comment by Treuce** [comment]
oké, köszi xD

**Comment by andris155** [comment]
Most jó?

**Comment by UDPSendToFailed** [comment]
Elvileg jobs.boost.[jobname].both a jog neve, de hogy az 50% hová kell, nem tudom...

**Comment by Treuce** [comment]
Andris, a 50%-t a rang jogaihoz írtátok?

**Comment by andris155** [comment]
Megvan adva a jó permission mégsem megy.

**Comment by andris155** [comment]
A configban van az 50%, de az is jól van beállítva.

**Comment by UDPSendToFailed** [comment]
Úgy látszik, jó, csak nem írja.

![2016-06-13_12 10 32](https://cloud.githubusercontent.com/assets/16057404/16004047/f061f92c-315f-11e6-8461-00e14b0ef54c.png)

**Comment by andris155** [comment]
Akkor a pénzt jól adja, de nem írja ki browse-nál, meg infónál?

**Comment by UDPSendToFailed** [comment]
Így van, /bal parancsnál is megvan a pénz.

**Comment by Treuce** [comment]
212$t ad egy kőért ami nem 50%.

**Comment by UDPSendToFailed** [comment]
80%

**Comment by UDPSendToFailed** [comment]
Most meg 106$ xD

**Comment by Kronox12** [comment]
Teszteltem, nekem tökéletesen írja úgy a /jobs browse, mint a /jobs info. A vicc az, hogy a permet nem állítottam még át xd

**Comment by andris155** [comment]
@Kronox12  remélem a jobsot frissítetted.
