### ISSUE TITLE
Beállítási hiba

### ISSUE THREAD

**Issue by KingDeadZ** [andris155/TheOld-Crafters#2031]
Nincs letiltva az event világban a /ptp accept (McMMO-s party tp)

**Comment by Sheep04** [comment]
nyugodtan elfogadom helyette az ocdt ;)

**Comment by KingDeadZ** [comment]
Sheep, nem kapsz semmit :c

**Comment by Sheep04** [comment]
Megelégszem a semmivel is :)

**Comment by poma123** [comment]
Javítva.
Köszönjük a hibajelentést!

**Comment by Sheep04** [comment]
Ne zárd le, Andris még adhat ocd-t... :D
