### ISSUE TITLE
Mobarena mob

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#2032]
Szia. 
A Spawneres plugin miatt a mobarénában is stack-elődnek a mobok.
![2018-05-11_19 18 54](https://user-images.githubusercontent.com/29709854/39938007-c7e00ab2-5551-11e8-9f32-72f7359d24ef.png)
![2018-05-11_19 19 14](https://user-images.githubusercontent.com/29709854/39938008-c802dcf4-5551-11e8-9d55-3d7cbba89c30.png)

**Comment by brtamas0** [comment]
Örülj neki :D

**Comment by andris155** [comment]
Írtam a flag-ról a chat csoportba. :)

**Comment by andris155** [comment]
entity-stacking flag
