### ISSUE TITLE
Szerverhirdetés

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#2033]
Szia. Most hirdettek, nem tiltotta le.
![2018-05-11_19 34 04](https://user-images.githubusercontent.com/29709854/39938345-eb22a254-5552-11e8-82f2-b515af414bbd.png)

**Comment by KingDeadZ** [comment]
96 levél? xD Na, neked sem fogok küldeni leveleket. :D

**Comment by andris155** [comment]
Ezzel nem tudok mit tenni. Ezt már max egy mesterséges intelligencia tudná megkülönböztetni, hogy ez hirdetés nem pedig sima szöveg.
