### ISSUE TITLE
Aukció

### ISSUE THREAD

**Issue by brtamas0** [andris155/TheOld-Crafters#2034]
Amikor már nem tudok több cuccot feltenni aukcióra akkor hibásan van leírva a hibaüzenet. 
![image](https://user-images.githubusercontent.com/23553862/39940362-533cdbc4-5559-11e8-8224-c0f9886ab42a.png)

Helyes: Jelenleg nem tudsz több tárgyat feltenni az őrült aukcióba.

**Comment by andris155** [comment]
javítva
