### ISSUE TITLE
EpicSpawners bug

### ISSUE THREAD

**Issue by KingDeadZ** [andris155/TheOld-Crafters#2038]
Leraktam a spawnereket (oldalasan, a blockra rá, meg úgy alapból ahogy szoktam, a felső block alá.
![2018-05-12_12 43 06](https://user-images.githubusercontent.com/38157910/39959685-9d235eb8-5615-11e8-8176-57ac65d28fde.png)
![2018-05-12_12 44 49](https://user-images.githubusercontent.com/38157910/39959686-a1e2891a-5615-11e8-8322-098efd988f93.png)
![2018-05-12_12 46 20](https://user-images.githubusercontent.com/38157910/39959688-a6adc1b2-5615-11e8-9a8c-3ffa6392fbf0.png)
![2018-05-12_12 46 40](https://user-images.githubusercontent.com/38157910/39959689-a9d382b4-5615-11e8-9301-fbeaad9d38c9.png)

Utána megpróbáltam telekvilágban, ott már működött normálisan.
![2018-05-12_12 49 32](https://user-images.githubusercontent.com/38157910/39959698-c2d3f618-5615-11e8-83d2-dbbfc1d2e556.png)

**Comment by andris155** [comment]
A plugin frissült az 5-ös verzióra. Ha még mindig él a hiba ebben is, akkor nyiss új hibajelentést. Köszönöm.
