### ISSUE TITLE
spawner beváltó

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#2039]
találtam egy reinforced skeleton spawnert otthon, de nem lehetett beváltani, nem, nem volt letéve, a ládában gubbasztott hónapok óta :D
képek:
![2018-05-12_18 24 37](https://user-images.githubusercontent.com/29951969/39960007-da9b0e8a-561a-11e8-9655-7482091376b2.png)
![2018-05-12_18 24 39](https://user-images.githubusercontent.com/29951969/39960008-dabaf416-561a-11e8-86a3-0fed19b6e8d7.png)
![2018-05-12_18 24 41](https://user-images.githubusercontent.com/29951969/39960009-dada2548-561a-11e8-82af-2cb4b17a079f.png)

**Comment by andris155** [comment]
Kérj meg egy admint, hogy váltsa be illetve cserélje ki a beváltóban is.
