### ISSUE TITLE
Bugos aukció

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#204]
Az aukció stackelve adja vissza az olyan itemeket, amiket amúgy nem lehetne stack-be tenni.

![2016-06-13_18 37 39](https://cloud.githubusercontent.com/assets/16057404/16015514/4cd3cea2-3196-11e6-8900-51f0cc5b6dc5.png)

**Comment by andris155** [comment]
Toc fejlesztő:
"És ezt nem igazán lehet másképpen megoldani :D
A plugin így tud a legtakarékosabban givelni"
