### ISSUE TITLE
Savsziget END bug

### ISSUE THREAD

**Issue by Viktor1969YO** [andris155/TheOld-Crafters#2040]
Véletlen ütöttem egy blokkot mikor bementem az end-be és ezt  az írást kaptam:
![2018-05-12_21 03 49](https://user-images.githubusercontent.com/38433879/39960761-b3b4cd98-5628-11e8-99ba-11c59343dc57.png)

**Comment by poma123** [comment]
Javítva.
Köszönjük a hibajelentést!

**Comment by andris155** [comment]
330 OCD
