### ISSUE TITLE
Káromkodás kicsillagozása.

### ISSUE THREAD

**Issue by Dreed1992** [andris155/TheOld-Crafters#2043]
Mi lenne ,ha a híresések és káromkodások,kiszűrése érdekében nem kicsillagozná a szöveget,hanem meg sem jelenne.  mint pl. az admin chat használatakor a "-_-"-szöveg. ezzel rengetek probléma megoldódna,és kevesebb probléma hárulna az adminokra.  Pl. *** helyett szóközzel helyettesíteni. http://kepkuldes.com/images/d97e2bb2d0e1d775b664d0dbe560266f.png

**Comment by andris155** [comment]
Nem tudok erre megoldást és szerintem a kicsillagozás rendben van. Egyébként az admin chat-ben azért nem jelenik meg, mert valamiért úgy veszi mintha a parancsbeállításai közé tartozna. /chc ach-val elvileg engedi a - -t is.
