### ISSUE TITLE
UltraCosmetics fordítási hiba...

### ISSUE THREAD

**Issue by Sheep04** [andris155/TheOld-Crafters#2045]
![2018-05-13_21 14 43](https://user-images.githubusercontent.com/34780638/39970836-c7c8bf4a-56f2-11e8-8ce1-8e9a1e4f9d72.png)

**Comment by andris155** [comment]
Nincs lefordítva teljesen.

**Comment by Sheep04** [comment]
Igazából a ,,Lehív Glaciális Paripára" gondoltam.
