### ISSUE TITLE
Luckyblock v2

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#2047]
Luckyblockból:
Giant, amit belehet fogni petnek:
![2018-05-14_16 51 14](https://user-images.githubusercontent.com/29709854/40005068-6bde0492-5797-11e8-80da-8afbe9c2405b.png)

Stack-elődő zombik:
![2018-05-14_16 52 45](https://user-images.githubusercontent.com/29709854/40005123-844c6d8e-5797-11e8-9a73-c0c54afd0b04.png)

**Comment by MrZero1** [comment]
Withert is spawnol, nem tudom baj-e.

**Comment by andris155** [comment]
Had örüljenek a Giant-nak amit elvileg pet-nek is be lehet fogni. A Wither pedig szerintem jó ha benne van. Valaki szerencsés valaki nem. :D
