### ISSUE TITLE
Auc bug

### ISSUE THREAD

**Issue by Treuce** [andris155/TheOld-Crafters#205]
Ha pl 1000 vagy 100000t állítunk be auc startnál a növekedésnek akkor már az első bid is ez alapján megy ami eddig nem így volt hanem az első bid az a kezdőlicit mindig és ezután növekedik azzal amit megadunk. A bugot "Pendehaw" találta.
Iletve egy apróság: Az auto nyerés összegét az egész auc elejére írja, ami előzőleg a legvégén volt,

**Comment by andris155** [comment]
Az első jó így, vagy legyen változtatva?

**Comment by andris155** [comment]
A 2. jó így, vagy legyen változtatva?

**Comment by Treuce** [comment]
Legyen szerintem. Logikus hogy a kezdőlicittel kezd és utána Xel emelkedik és szerintem jó is volt így.

**Comment by Treuce** [comment]
Mindkettő legyen szerintem, régebbi beállítással jobban tetszet nekem meg szerintem többieknek is.

**Comment by andris155** [comment]
javítva.
