### ISSUE TITLE
Falusi stack.

### ISSUE THREAD

**Issue by Dreed1992** [andris155/TheOld-Crafters#2050]

**Comment by Dreed1992** [comment]
A falusi össze stackelődik survin (pl.falusi x10)és nem lehet így kihasználni,lehetne erre valami megoldás? választ előre is köszönöm. -Agro

**Comment by poma123** [comment]
A MobStack plugin-ra gondol, hogy nincs már értelme, mivel ki lett véve az EpicSpawners plugin. Nem lehet már olyan fullos spawnereket kihozni, mint amit lehetett. Mellesleg mobaréna közben is össze stack-eli a mob-okat, és a falusiakat egyaránt.

**Comment by andris155** [comment]
kivettem a plugint

**Comment by poma123** [comment]
Köszi!
