### ISSUE TITLE
Spawnerek

### ISSUE THREAD

**Issue by asdlol911** [andris155/TheOld-Crafters#2052]
Szép napot/estét bármikor is olvassátok.

Szeretném kérvényezni a spawnerek számának szabályozását levédésenként, mint ahogy a moboknál volt.
Indok és példa, hogy itt van skrisz01ék spawnerei, oké, hogy farmot csinál, de ez a sok spawner egyszerre nagyon sok, nem beszélve arról, hogy azonnal 1-2 fps-e lesz a játékosnak, aki oda megy és a sok spawning animáció is laggolhat eléggé.

~asdlol

![2018-05-18_19 47 15](https://user-images.githubusercontent.com/17855326/40249827-88c76c16-5ad4-11e8-97d7-a849be5be9f5.png)

**Comment by andris155** [comment]
Nem tudok rá plugin-os megoldást.
