### ISSUE TITLE
Fordítás hiba

### ISSUE THREAD

**Issue by KingDeadZ** [andris155/TheOld-Crafters#2055]
![2018-05-20_15 07 23](https://user-images.githubusercontent.com/38157910/40279256-9b14b1d2-5c3f-11e8-8aa7-569876434920.png)

Nem teleportálni, hanem teleportáltatni lenne az szerintem.

**Comment by Sheep04** [comment]
Az teljesen mindegy ;)

**Comment by poma123** [comment]
Szerintem jó az úgy.
