### ISSUE TITLE
MobAréna fly

### ISSUE THREAD

**Issue by Sheep04** [andris155/TheOld-Crafters#2056]
Üdv!
Ha kilépünk a MobArénából, akkor nem kapcsolja ki a fly-t, és így lehet repülni.
Ezzel csak, akkor van probléma, ha
nincs barrier.
![2018-05-20_18 19 04](https://user-images.githubusercontent.com/34780638/40280931-b5e0d64c-5c5a-11e8-8965-0ecadbabead0.png)

Sheep04

**Comment by andris155** [comment]
Elvileg tiltotta ma fly-t a régióban.

**Comment by andris155** [comment]
330 OCD
