### ISSUE TITLE
Gyors chatelés

### ISSUE THREAD

**Issue by Sheep04** [andris155/TheOld-Crafters#2057]
Üdv!
Gyorsan írtam be a parancsokat, és ideiglenesen ki lettem tiltva. Ezzel nincs baj, de kiírja, hogy ,,kérlek, várj 1 másodpercet", viszont egyből kitilt.
Szóval, vagy ne legyen kiírva, hogy várjak 1 másodpercet, vagy azután a közeljövőben történő második gyors chatelés alkalmával tiltson ki.

Sheep04

**Comment by andris155** [comment]
Üdv!
Sajnos ez a legkisebb beállítás. Fél másodpercet nem támogat. Ez a védelem azért muszáj, mert ha valaki egy programmal flood-ol valami parancsot, akkor nagyon nagy késést (laggot) okozhatna vele.
