### ISSUE TITLE
Youtube

### ISSUE THREAD

**Issue by KingDeadZ** [andris155/TheOld-Crafters#2058]
Túl nagy jogokat kaptak a youtuber rangal a különböző emberek.

Javaslatok:

VIP-Elit-Prémium jogok az Elit-Prémium-Old helyett

Hetente legalább 1 videó a szerverről, ami legalább 10perces.

Sokan kihasználják ezt, hogy pl felsubol a családja, valami pár accot regel, hogy jej 50sub, a nézettséget meg meg tudja csinálni magának..
És így könnyen megszerezte az Elit rang jogait, amíg más megveszi az OCDt rá/Fordításokból és hibajelentésekből megveszi azt a rangot.

**Comment by andris155** [comment]
Folyamatosan szűrjük a minőségtelen vagy csalással megszerzett YouTube rangosokat.
