### ISSUE TITLE
Kis jobs bug

### ISSUE THREAD

**Issue by Treuce** [andris155/TheOld-Crafters#206]
Jobs info és a jobs browse parancs is a kezdő fizetést és XPt írja ki, nem számolja bele ha nagyobb a szintünk.

**Comment by Kronox12** [comment]
Tökéletesen működik, más is igazolja.

**Comment by andris155** [comment]
Elvileg most sem írja teljesen jól.

**Comment by Treuce** [comment]
Már jól írja. Zárom.
