### ISSUE TITLE
Próbaidős segítő rang

### ISSUE THREAD

**Issue by asdlol911** [andris155/TheOld-Crafters#2060]
Üdvözletem!

Egy olyan kérésem lenne, hogy a próbaidős segítő rang jogaiból ki kellene venni a vanish és ahhoz tartozó parancsokat, mert ahogy látom, a pár próbaidős segítő (nem mondok neveket) inkább arra használja ezt, hogy kibújjon a munka és kötelezettség alól.

_~asdlol911_

**Comment by andris155** [comment]
MrZero mit mond erre?

**Comment by andris155** [comment]
kész
