### ISSUE TITLE
lottó

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#2063]
lottó hirdetés vevésnél ugye kiírja azt a rendszer hogy pl "skrisz01 vett 5 szelvényt!"
De ha az utolsó 2 percben vásárlunk, kiírja hogy eredményhírdetésig még xy perc mp, na itt a hirdetést hosszú í-vel írták, és helyesen: hirdetés 
Nem nagy cucc, csak szemet szúrt :D

**Comment by andris155** [comment]
Javítva!
Köszönjük a hibajelentést!

**Comment by andris155** [comment]
204 OCD
