### ISSUE TITLE
Old cuccok - önjavítás enchant

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#2064]
Az old tárgyakon nincs önjavítás enchant, ha pedig valaki rá akarja tenni, elveszik a neve. Szerintem lehetne rajtuk alapból.

**Comment by Sheep04** [comment]
Az önjavítás egy oldkardon nem drága egy kicsit...?

**Comment by KingDeadZ** [comment]
Ha enchantal ráraknád nem az. 
Javaslat: Old eszközökre lehessen rakatni önjavítás/suhintás enchantot (kard)
