### ISSUE TITLE
Manuális event javaslat.

### ISSUE THREAD

**Issue by KingDeadZ** [andris155/TheOld-Crafters#2065]
Ez egy sima mcMMO-s xprate növelős event lenne. Pl tartana 1 óráig, és az alap 1x-es helyett lenne 2x-es vagy esetleg 3as akár.

**Comment by MrZero1** [comment]
Elképzelés? A leírtakon kívül. Vizuális vagyok, de ebben nem látom, hogy épül fel az event. Köszi.

**Comment by KingDeadZ** [comment]
Lenne 1 megszabott idő akár minden nap/csak a hétvégéken amikor fel lenne húzva az mcMMO-nak az xp szorzója.

(Ez hasznos is lenne, hiszen az alchemy skillben eléggé kevés xpt kapsz potifőzésért.)

Példa:
Kiírná ezt, amikor elkezdődik az event:
A képességek tapasztalati szorzója megemelkedett! A szorzó eddig tart: 19:00

Vagy akár még 1 javaslat.

Lehetne venni 1 megszabott pénzért szorzó növelést az egész szervernek 1 órára.

**Comment by MrZero1** [comment]
Ez inkább valamiféle "áldás" (hűű, ez nem hangzik kopisnak :'D) dolognak tűnik. :D
