### ISSUE TITLE
érintkezés és alaphasználat flag

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#2066]
Ugye ezt a 2 flaget engedélyezni tudjuk az rg levédésünkön. Na, ha bármelyiket engedélyezzük, majd letiltjuk, akkor az rg tagok és az rg tulajok se tudják pl kinyitni az ajtót. Ezt csak az rg törlésével lehetséges kijavítani. az alaphaználatnál ha jól emlékszem nem lehet tiltás után senkinek se ajtót nyitni, barkácsasztalt/kemencét/encsi asztalt/potifőzőt/üllőt nyitni (rg tagoknak se!)
Az érintkezés flag meg még rosszabb, mert az kihat a ládanyitásra is, szóval ha letiltjuk senki se tud ládába nézni, de ha engedélyezzük, akkor meg mindenki.
szerveren be tudom mutatni egy rég használz rg-n

**Comment by andris155** [comment]
A myzone-al elvileg none-vel lehet törölni a zónáról az rg-nél meg nem írsz utána semmit és akkor törli.
