### ISSUE TITLE
Eszközök

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#2067]
Szia.

Tesztelhetnénk a duplafejű baltát? Hiányolják, engem pedig érdekel, valóban kiüti  más védésén a fát. (Elvileg ugye nem lehet ütni más területén blokkot)

**Comment by andris155** [comment]
Elvileg már javították.

**Comment by andris155** [comment]
Majd le kell tesztelni.

**Comment by MrZero1** [comment]
Ha engedélyezed, tesztelem. A vöröskőszettről van infó? Illetve a vésőről.

**Comment by andris155** [comment]
Az RPG-n nem tudjátok ezeket tesztelni ha oda berakom vagy poma berakja?

**Comment by MrZero1** [comment]
Ott is tudjuk.:)

**Comment by poma123** [comment]
Le tudnánk tesztelni. :D

**Comment by andris155** [comment]
kész
