### ISSUE TITLE
Fegyverkovács munka hiba

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#207]
Ha üllőben átnevezek egy vasat / aranyat / gyémántot, megadja a javításért járó pénzt és XP-t, mintha egy eszközt javítottam volna vele. Ezzel csak annyi a baj, hogy a tárgy átnevezésért von le az XP szintemből, igaz, 1-2 potiból megvan 1 szint.

**Comment by andris155** [comment]
@Kronox12

**Comment by Kronox12** [comment]
Amint időm engedi

**Comment by Kronox12** [comment]
Milyen munkában dolgozol a Fegyverkovácson kívül? @UDPSendToFailed

**Comment by andris155** [comment]
Ezekbe dolgozik:
![kepkivagas](https://cloud.githubusercontent.com/assets/8324198/16237909/ae512cee-37de-11e6-871b-d2f72896da90.PNG)

**Comment by Kronox12** [comment]
Nem von le semmit, viszont rájöttem, hogy pár dolog hiányzik a fegyverkovácstól.

**Comment by UDPSendToFailed** [comment]
Nem a munka XP-ből von le, a sima XP szintből az átnevezésért.

**Comment by Kronox12** [comment]
Direkt... így van a játék. Írj a Mojangnak.
