### ISSUE TITLE
fejkiütés

### ISSUE THREAD

**Issue by asdragon** [andris155/TheOld-Crafters#2071]
A fejboltos fejeket nem tudom rendesen kiütni a területemen és andminnak bejelzi speedmine-ként.
Ha először rakja le az ember még kiüthető de második lerakáskor bebuggol és csak pistonnal lehet kicsapni.

**Comment by andris155** [comment]
Sima fejjel is ez a helyzet?

**Comment by MrZero1** [comment]
Tesztelve (ploton), első lerakás után kilehet ütni, másodjára csak pistonnal. Sima fejjel nincs gond, csak a heads boltossal. Képeket tudok mellékelni.

**Comment by andris155** [comment]
Várom a képeket.

**Comment by MrZero1** [comment]
Első lerakás után kitudja ütni:
![2018-05-30_11 44 24](https://user-images.githubusercontent.com/29709854/40782272-0ba51c8c-64df-11e8-967c-a5e5aa4c8c78.png)
Második lerakás után már csak pistonnal tudja kiütni:
![2018-05-30_11 44 51](https://user-images.githubusercontent.com/29709854/40782299-2255ef92-64df-11e8-8f31-af536eca16f8.png)
![2018-05-30_11 44 28](https://user-images.githubusercontent.com/29709854/40782300-22805b7e-64df-11e8-9eea-8cfaf35012d5.png)

Chat-ben a speedmine jelzés valamint a 'beszélgetés', írja is, hogy nem bírja kiütni másodjára:
![2018-05-30_11 44 52](https://user-images.githubusercontent.com/29709854/40782340-3795c4b8-64df-11e8-864f-e433ba76c40e.png)

**Comment by andris155** [comment]
Most működik?

**Comment by andris155** [comment]
Javítva
