### ISSUE TITLE
+ szabály

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#2073]
Plusz szabály:

AFK/TPkill tilos.

Régen volt ilyesmi szabály, most nem találom a weboldalon leírva, ezért gondoltam, hogy le lehetne írni, mert volt belőle baj.

**Comment by andris155** [comment]
Mindkét szerverre?

**Comment by MrZero1** [comment]
Igen

**Comment by andris155** [comment]
Kész
