### ISSUE TITLE
Kapuk

### ISSUE THREAD

**Issue by SurvivorTheReal** [andris155/TheOld-Crafters#2074]
Mikor nether téglával akarok kialakítani egy kaput, nem engedi a rendszer.

Az első sorba beírom a táblán odaírom a nether tégla ID jét, nem jó. Odaírom nevét angolul, alsóvonalla, nem jó.
A kapu kerete tetszőleges ügye, az nem lehet baj.
A megengedett anyagok között ott van a pokoltégla, másnéven nether tégla.
Szóval a lényeg a lényeg, nether téglával nem engedi annak ellenére hogy engednie kéne.

**Comment by andris155** [comment]
A pokolkő kerítéssel működik a kapu.

**Comment by andris155** [comment]
De itt a pontos lista:
```
        - FENCE
        - IRON_FENCE
        - THIN_GLASS
        - NETHER_FENCE
        - ACACIA_FENCE
        - BIRCH_FENCE
        - DARK_OAK_FENCE
        - JUNGLE_FENCE
        - SPRUCE_FENCE
```
