### ISSUE TITLE
Jármű eltünés

### ISSUE THREAD

**Issue by Pandikusz** [andris155/TheOld-Crafters#2075]
a szerveren már többször előfordult velem és haverommal hogy a járművek eltűntek ha letettük.
pl. haverom próbálta lerakni a repülőt és az elbugg-olt.
a Nimbusz is elbugg-olt pont így hogy letettem és nem jelent meg de az item-et elvette tőlem.
és már nem 1-szer történt meg ez :(

**Comment by andris155** [comment]
Érdekes mód másnak lerakja. Erről kellene egy videó vagy pontos leírás mikor történik ez.
