### ISSUE TITLE
Szabály (savsziget)

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#2077]
Szia. A savsziget szabályzatban a 4. pont, tájépítés szabályzatban a " 4.4, Max. 60 tölcsér szigetenként! " elavult, a limit 100 tölcsér, annyi is marad. 

Valamint a 7. pontnál a "  7.5, a gyors repüléssel szigorúan tilos a világot generálni!! " kezdetű szabály kis 'a' betűvel kezdődik, ez csak elírás.

**Comment by andris155** [comment]
Javítva!
Köszönjük a hibajelentést!
