### ISSUE TITLE
Segítőknek CoreProtect jog

### ISSUE THREAD

**Issue by Konc0321** [andris155/TheOld-Crafters#2078]
Szia ^^ Többen jelezték, hogy xy valamilyen módon kárt okozott neki, legyen ez rombolás, vagy lopás. Ezért javaslom a segítőknek a nagyon alap CoreProtect jogokat, pl /co i vagy a rollback.

**Comment by poma123** [comment]
Inspect (/co i) és Lookup (co l <oldal>) jogok megadva a segítő ranghoz!
Értelemszerűen ezt csak a __Savsziget__ szerveren kellett beállítani, mivel a Survival szerveren eddig is volt jog hozzá. Köszönjük a javaslatot!

**Comment by Konc0321** [comment]
Én köszönöm ^^

**Comment by andris155** [comment]
Kész

**Comment by andris155** [comment]
330 OCD
