### ISSUE TITLE
Savsziget mob spawning bug

### ISSUE THREAD

**Issue by Icecroft** [andris155/TheOld-Crafters#2079]
Sziasztok, tegnap délután óta a netherben nem spawnolnak új mobok (zombimalac, ghast stb), csak a spawnerek működnek. Ez más szigetén is így van.
Valami oknál fogva a szigetemen lévő mobspawnerben is csak nagyon ritkán jönnek a mobok, amióta megint tudnak csoportosulni. Valami nem stimmel. Lehet egy resi is segít.

**Comment by andris155** [comment]
Lecseréltem a plugint és a Ghast-ot már nem stackeli.
