### ISSUE TITLE
SG ölés szöveg

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#208]
![2016-06-13_21 19 43](https://cloud.githubusercontent.com/assets/16057404/16033750/1028926c-320e-11e6-8bfe-f1ab1b68ec78.png)

**Comment by Treuce** [comment]
SGhez kapcsolódóan:
- Ha lehetne akkor a /r és /m parancsokat engedélyezni.
- Új lootok a ládákba ami 1.9es PvP rendszerhez jobban illik mert jelenleg a fabalta erősebb kb mint az összes kard.
- Nagyobb nyeremény?

**Comment by andris155** [comment]
A fordítást javítottam.

**Comment by andris155** [comment]
Mennyi legyen a nyeremény?

**Comment by Treuce** [comment]
Szerintem 500$/kill és a végén meg talán 2-3k. A /msg meg nem elég gyors szerintem ha pvpben vagyunk, /r és /m lenne a legjobb megoldás.

**Comment by andris155** [comment]
200-at játékos ölésért
2000-et nyerésnél
Treuce újra konfigolta a chestlootot
A fordítás javítva.
