### ISSUE TITLE
Fordítási hiba

### ISSUE THREAD

**Issue by Sheep04** [andris155/TheOld-Crafters#2080]
![2018-06-02_19 20 07](https://user-images.githubusercontent.com/34780638/40879602-00c57b16-66a3-11e8-9a79-86d52a38142f.png)

Helyesen: [név] párbajt kezdeményezett veled!
Illetve, ha a szöveget nem lehet nagyon piszkálni: Párbajt kezdeményezett veled ő: [név] (hiányzik a kettőspont)

Sheep04, avagy Sanyi, a vízálló bárány!

**Comment by andris155** [comment]
Javítva!
Köszönjük a hibajelentést!
