### ISSUE TITLE
Plugin ötletek

### ISSUE THREAD

**Issue by andris155** [andris155/TheOld-Crafters#2082]
## Ide lehet írni azokat az ötletek, hogy milyen plugin-ok kerüljenek be és melyik szerverre.

**Comment by DlamondBarna03** [comment]
Pl. hogy chaten írja hogy mennyi 1+1 És aki elősször beírja jutalmat kap?

Minden szerverre.

**Comment by Sheep04** [comment]
összekapcsolható csillés plugin
olyasféle, hogy a síneket lehet pl függőlegesen rakni
leginkább survival szerverre

**Comment by KingDeadZ** [comment]
Egy olyan plugin, amivel lehet csinálni 1 bosst, ami X Időnként újraéled.

Példa:

Nick: "Ami még a Sárkánynál is erősebb"
HP: 20000 (World boss lenne ez)
Attack: 20
Defense: 10 (Páncéllal/Resistance effektel megoldva)
Drop: X mennyiségű pénz,aki belesebzett legalább 5%ot, az kap 5darab gyémántblockot.

**Comment by Sheep04** [comment]
Ez tök jó, csak a rangjogokkal könnyen kijátszható.

**Comment by KingDeadZ** [comment]
Pl tiltva lennének a helyen a jogok :D

**Comment by MrZero1** [comment]
A reakcióeventhez hasonló, matekos dolgot már Pomával nézegettük, olyanról volt már szó. Ez a Boss-os dolog pedig jól hangzik.
