### ISSUE TITLE
Savsziget mob spawning bug again

### ISSUE THREAD

**Issue by Icecroft** [andris155/TheOld-Crafters#2083]
Sziasztok! Bocs hogy e miatt új issuet indítok, de a "Savsziget mob spawning bug #2079" issueban leírt probléma nem szűnt meg. A netherben semmilyen mob nem spawnol már két napja. Légyszi próbáljátok meg, Nálam a zombi malacok szépen spawnolnak normál esetben a nagy sík felületen, de most semmi.
Úgy néz ki, a stackelős plugin kivétele nem segített.

**Comment by andris155** [comment]
Nem tudok vele mit csinálni. Én nem állítottam semmit ezzel kapcsolatban.

**Comment by poma123** [comment]
Én sem.
