### ISSUE TITLE
Ender íj=Mégtöbb OC

### ISSUE THREAD

**Issue by Konc0321** [andris155/TheOld-Crafters#2086]
Az event világban sincs letiltva az új enderíj, így ha a staff aki tartja az eventet figyelmetlen, a játékosok könnyen kijátszhatják ezt a "bugot", és jutnak egyszerűen OC-hoz.
https://youtu.be/yFC2iWg2-os

**Comment by andris155** [comment]
Javítva!
Köszönjük a hibajelentést!

**Comment by andris155** [comment]
204 OCD
