### ISSUE TITLE
Hiba.

### ISSUE THREAD

**Issue by elliot2018** [andris155/TheOld-Crafters#2087]
2 hibát találtam. Az első hiba a Paintballban van, amikor elkezdődik a kör akkor kapunk ajándékokat, de valamikor amikor sokszor kantintok rá ameddig számol vissza akkor 2 db ládát ad.(eddig 2 szer fordult elő velem,1 hónapon belül)
A második hiba az, hogy ha a mobarénában  meghalok és beírom, hogy  /ma l akkor még mindig megbír ölni az idéző.
elliot

**Comment by poma123** [comment]
Az elsőt én nem tudom javítani, de az utóbbit javítottam.

**Comment by andris155** [comment]
Az elsővel én se tudok mit csinálni.

**Comment by andris155** [comment]
330 OCD

**Comment by elliot2018** [comment]
![image](https://user-images.githubusercontent.com/36449228/41111792-5ee1be20-6a7d-11e8-8bcd-e1aff0dc169d.png)
![image](https://user-images.githubusercontent.com/36449228/41111867-8e5b3974-6a7d-11e8-8959-a86db5e94d2a.png)
![image](https://user-images.githubusercontent.com/36449228/41111898-a4cda408-6a7d-11e8-9fd1-275de1038b48.png)
