### ISSUE TITLE
Új event=Elytra+Tűzijáték

### ISSUE THREAD

**Issue by Konc0321** [andris155/TheOld-Crafters#2088]
A Zuhanás eventen ha elraksz az enderládádba pár elytrát+tűzijátékot és úgy hagyod el az event területét akkor az enderchestedben lévő elytrákat nem veszi el. Ez csak az Oldosokat érinti, mivel csak ők tudják bárhol megnyitni a végzetládájukat
https://youtu.be/9lBN0P5b0rE

**Comment by poma123** [comment]
Nem lehet ott megnyitni a végzetládát, le van tilva. Viszont a staffok számára nincsen. :D

**Comment by andris155** [comment]
Akkor a videón miért működik?

**Comment by andris155** [comment]
Remélem csak a nem próbahetes segítő fér hozzá.

**Comment by poma123** [comment]
Savszigeten nincs külön rang, én ezt már megkérdeztem kell-e, és a válasz nem volt.

**Comment by Konc0321** [comment]
Ohh rendben, ezt nem tudtam ^^ Köszi :3
