### ISSUE TITLE
Old új jogok?

### ISSUE THREAD

**Issue by Treuce** [andris155/TheOld-Crafters#209]
-nagyobb jobs boost? 60% vagy 70% talán?
-/fixall: Ha megoldható hogy monjuk 1000$t számoljon/item és ne egy adott árért menjen hanem attól függjön hogy mennyit javítunk.
-Több munka egyszerre? Ezt már rangokhoz is gondoltam már, pl elitnek lehetne 3, préminek 4 és oldnak meg 5, de nem vagyok benne biztos mennyire megvalósítható vagy hogy mennyire lenne kihasználható.
Más nem jutott eszembe, de ha van ötlet írjátok ide minthogy 5 helyen legyen ugyanaz.

**Comment by andris155** [comment]
A jobs boost csak 1 jog, nincs több lehetőség, pl egyik rang 80% a másik 50%

**Comment by andris155** [comment]
A fix sajnos nem oldható meg máshogy.

**Comment by andris155** [comment]
A több munka hát nem tudom, ezt még át kell gondolni.

**Comment by andris155** [comment]
De úgy tudom erre sincs jogkód amúgy.

**Comment by Treuce** [comment]
Jobs fejlesztőnek írjak hogy ha lehet akkor ezeket csinálja meg a kövi frissítésbe?

**Comment by andris155** [comment]
Nem kell.

**Comment by andris155** [comment]
A jobsot már nem akarom tovább maxolni, így is rengeteg pénzetek van.
