### ISSUE TITLE
Bugot találtam 

### ISSUE THREAD

**Issue by 8DaveedHUN18** [andris155/TheOld-Crafters#2090]
https://www.youtube.com/watch?v=jvUX9VlBd_I&feature=youtu.be

Itt a link a videónak by: 8DaveedHUN18 & asdlol911

**Comment by Sheep04** [comment]
Wow. Újszabadban nálam is ment a teleportálás, csak nem  tudtam mozogni, mert ott volt egy visszateleportálós dolog (akármi is legyen az xd).

**Comment by andris155** [comment]
Javítva és törölve a feleslegesen generált részek.

**Comment by andris155** [comment]
1016 OCD

**Comment by andris155** [comment]
Milyen névre adjam?

**Comment by 8DaveedHUN18** [comment]
8DaveedHUN18

András Marczinkó <notifications@github.com> ezt írta (időpont: 2018. jún.
8., P 10:51):

**Comment by 8DaveedHUN18** [comment]
Elnézést kérek hogy késön válaszoltam

8Daveed HUN <alex066785@gmail.com> ezt írta (időpont: 2018. jún. 21., Cs
7:43):

**Comment by andris155** [comment]
Megadtam.
