### ISSUE TITLE
Savsziget javaslatok

### ISSUE THREAD

**Issue by Icecroft** [andris155/TheOld-Crafters#2093]
1.) Jó lenne, ha a savszigeten a /warp piac -on is el lehetne adni a megtermelt fát, mint a survin
2.) A fenti javaslatot már beadtam régebben is a spawnon, de semmi reakció nem történt.
Ezért a második javaslatom, az, hogy ha valakinek van valami ötlete az ötletládában, arról az illető kap valamilyen tájékoztatást mail-ben, hogy OK vagy nem. Ez lehet survin se lenne rossz.
3.) A chaten rendszeresen megjelenő infók közé érdemes lenne felvenni olyan tájékoztatásokat is, hogy épp aktuálisan milyen vátoztatások történtek. (pl épp most változtak meg a kőgenerátor tulajdonságai a savszigeten.) Ezeket a hireket érdemes lenne 3 napig keringetni. Ez survin is működhetne.

**Comment by poma123** [comment]
1.) Eddig is el lehetett adni a fát.
2.) Nem történt reakció, mivel már volt előtte is fa eladás lehetőség.
A második felében nem én döntök.
3.) Kérdés, hogy mikor lenne idő arra, hogy ezeket az infókat folyamatosan frissítsük.

**Comment by andris155** [comment]
Aki szeretne reakciót a dolgokra írjon ide inkább.
