### ISSUE TITLE
Stacked mobs hiba

### ISSUE THREAD

**Issue by Sheep04** [andris155/TheOld-Crafters#2097]
Üdv!

A mobok neve csak egy szám (pl.: 19 skeletons helyett 19)
![2018-06-09_21 19 28](https://user-images.githubusercontent.com/34780638/41195314-f25796d0-6c2a-11e8-9c4a-9f7252ae7594.png)

Sheep04

**Comment by andris155** [comment]
A spigot egyik fejlesztője készítette ezt a plugint és szinte semmi erőforrást sem használ. A másik plugin zabálja a processzort. Ez a lehető legegyszerűbb de tökéletesen működik.
