### ISSUE TITLE
Hardcore szerver ötlet

### ISSUE THREAD

**Issue by BaHuu** [andris155/TheOld-Crafters#2099]
Szia! A szerver ötlet a következő lenne:
Adott a szerver, te erre fel lépsz. Itt van egy terület ami játékosonként nő (World border, kb.: 30-40 blockot)
Itt lenne levédés, de nem sok, felfele és lefele persze "végtelen". A levédés persze nem olyan mint akár melyik survival szerveren, olyan, ami csak akkor van érvényben amikor a játékos offline a hardcore szerveren. Amikor fent van akkor saját magának kell védenie a cuccait, **DE** vehet védőket, őrzőket amik védelmezik a területet amit megadsz nekik, persze ezek ingyenesen kraftolhatók lennének, de az erősebbek OC-ért kaphatóak.
_Ezeknek kiadhatsz tulajdonságokat (mint a peteknek) hogy járőrözzenek vagy egy területet védjenek.
Na de mindegy ez csak egy kitérés. Ugyan úgy lennének Emeráld cuccok, meg stb._ 
Lenne End, és lenne Nether, ezek alap dolgok lennének, a shop az cserekereskedelemmel menne, pl.: 10 cobblestone az 5 db. sima kő. Pénz az nem lenne, shoppot lehetne csinálni kint a rendes survivalon, de nem pénzért hanem tárgyakért, meg ilyesmi. **(Ezt el lehet vetni, és akkor úgy lenne  a shop mint a survivalon, de csak eladásra lenne a rendes shop.)**
Remélem tetszik az ötletem, ha lenne kifogás akkor azt írjátok le, nagyon várom! Ha nem tetszik akkor, ez van nem én csinálom.

> Üdvözlettel: [BaHuu](https://www.youtube.com/channel/UCHJlFEOQIYaYB_VMKoBOc3w)

_UI.: Ha esetleg másnak megtetszik akkor ő is írjon ötleteket!_

**Comment by MrZero1** [comment]
Nem rossz ötlet. A megvalósítás már más kérdés.

**Comment by BaHuu** [comment]
Hát, megvalósítás. Az bajos, még a worldborder-es dolgot meglehetne könnyen oldani, A tárgyas boltot azt nem muszáj. A védelmezőknek pedig nem kötelező megcsinálni azt hogy kilehessen adni nekik parancsokat, az is elég hogy van egy "totem" amit lelehet idézni, és annak a körzetében sebzi az embereket.
Vagy, lehetne csapdákat építeni, vagy kész csapdákat amiket a csapat épít, vagy az ember csinál csapdát magának, vagy plugin. :)

**Comment by andris155** [comment]
Köszönjük az ötletet, de egyelőre más projekteken dolgozunk.
