### ISSUE TITLE
Mypet gondok.

### ISSUE THREAD

**Issue by Kronox12** [andris155/TheOld-Crafters#21]
2016.01.07-én minden Mypet eltűnt,valahogyan törlődhetett az adatbázisból.Ha van biztonsági mentés,azt jó lenne visszaállítani,mihamarabb.Már többen is írtak a gond miatt.

**Comment by andris155** [comment]
2016.01.05. 19:31 órai mentés visszaállítva.

**Comment by andris155** [comment]
A hibát okozta: https://github.com/andris155/TheOld-Crafters/issues/19
