### ISSUE TITLE
Szabályok frissítése.

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#210]
A szabályok könyvből hiányzik a fly a megvehető rangoktól.

![2016-06-14_12 10 28](https://cloud.githubusercontent.com/assets/16057404/16039294/3646aaea-3229-11e6-9f0e-4885ace0d429.png)

**Comment by andris155** [comment]
https://github.com/andris155/TheOld-Crafters/issues/195

**Comment by andris155** [comment]
2.14, TP-kill tilos!
9.6, Gyors repüléssel szigorúan tilos a világot generálni!!
8.2, Ha találtál hibát jelezd felénk! [Online staffnak vagy GitHub-on]

**Comment by andris155** [comment]
5.9, Búza, nád, kaktusz [tövestül való] elcsenése tilos!
