### ISSUE TITLE
Telkek plugin hiba (?)

### ISSUE THREAD

**Issue by asdlol911** [andris155/TheOld-Crafters#2100]
Üdvözletem!

Tag ranggal nem lehet használni a /p merge és a /p merge all parancsokat, hibát ír ki: "Nincs szomszédos telked a megadott irányban, vagy a megadott méret nem engedélyezett."

Új játékossal is tesztelve lett, nem tudott, tehát nem(csak) azon múlik, hogy hány telke van/volt eddig.

_asdlol911_

**Comment by rangatozo** [comment]
mert szar .

**Comment by MrZero1** [comment]
Néha van ez a hiba, de alapjában működik. Tehát lehet használni tag ranggal is
