### ISSUE TITLE
Hiba

### ISSUE THREAD

**Issue by elliot2018** [andris155/TheOld-Crafters#2103]
Sziasztok
Megkértek, hogy írjam le pontosan a szavazásos hibát.
Elsőnek az tűnt fel, hogy szavaztam és nem kaptam meg érte a pénzt, de az xp-t megkaptam. A staffok is kipróbálták, de ők megkapták a pénzt. Ma megkértem Matiasx-et, hogy mennyen fel savra és nézze meg, hogy mennyi pénzem van, mielőtt felmegyek. Megnézte, hogy 120,481$ om van, felmentem és akkor kiírta, hogy eddig mennyit szavaztam, akkor újra megnézte, hogy mennyi pénzem van és akkor 121.081$ lett.
Ha jól tudom akkor egy szavazásért kellene kapnom 500$-árt. Az xp-t az mindig megkaptam. Lehet, hogy azért nem kapom meg a pénzt mert fellépek és mindig próbálja betölteni a világot(ekkor nem látom, hogy hányszor szavaztam)és mivel nemtudta betölteni ezért mindig kidob a szerver. Miután sikerült belépnem csak akkor látom, hogy nem kaptam meg a pénzt.(Volt olyan is, hogy más se kapta meg a pénzt). Most amit észrevettem az, hogy szavazok mind a 3 honlapon, de a szerveren csak 2 szer írja ki, hogy szavaztam, de a /vote top-ban azt írja, hogy mind a 3-szor szavaztam. Tudok olyan képet küldeni ahol látható, hogy mennyi pénzem volt szavazás előtt és szavazás után.
elliot

**Comment by andris155** [comment]
Nem sikerült reprodukálnom a hibát.
