### ISSUE TITLE
MineMarket

### ISSUE THREAD

**Issue by andris155** [andris155/TheOld-Crafters#2105]

**Comment by KingDeadZ** [comment]
Ez mire való? 

Írjunk ide ötleteket, hogy miket lehetne megvásárolni? :D

**Comment by andris155** [comment]
Akár

**Comment by Sheep04** [comment]
Olyat lehetne megcsinálni, hogy minemarketen keresztül nevezze el a kardját az ember, és akkor az lesz a neve amit ő szeretne. Bár lehetséges, hogy ez kivitelezhetetlen :c

**Comment by andris155** [comment]
Sajnos a MineMarket nem tud olyat.
