### ISSUE TITLE
Bugos a Minemarket

### ISSUE THREAD

**Issue by Victatorkiller** [andris155/TheOld-Crafters#2106]
A játékba van 2032 OCD-m : /ocd egyenleg Victator_killer
De a Minemarketen azt írja nincs egy se és ezért nemtudok semmitse venni :
![image](https://user-images.githubusercontent.com/40245916/41369519-67ba8e2e-6f45-11e8-9121-57ed51e2fcec.png)
Kérem tudnak segíteni? nemakarok 2032 Forintot elpazarolni :)

**Comment by andris155** [comment]
Van egy Victator_killer és victator_killer néven regisztrált felhasználó is. 2 különböző e-mail címmel.

**Comment by andris155** [comment]
Az OCD a Victator_killer néven van.
