### ISSUE TITLE
Pet fejlesztés szöveg hibás

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#211]
![2016-06-15_07 33 04](https://cloud.githubusercontent.com/assets/16057404/16069056/d0275cac-32cb-11e6-8538-37ab2d74ad9c.png)
![2016-06-15_07 34 51](https://cloud.githubusercontent.com/assets/16057404/16069057/d0d11e7c-32cb-11e6-9e43-d8c999921a61.png)

Többször is írja, hogy 54 férőhelyes inv-je van, és az a 34 perc is soknak tűnik... :D

**Comment by Treuce** [comment]
Olyan is van hogy 2x lépi át ugyanazt a szintet.

**Comment by andris155** [comment]
@Kronox12

**Comment by Kronox12** [comment]
Amint időm engedi

**Comment by Kronox12** [comment]
Skilltree?

**Comment by Kronox12** [comment]
@UDPSendToFailed  @Treuce

**Comment by UDPSendToFailed** [comment]
Nekem haszon és pvp pettel is írta.

**Comment by andris155** [comment]
Elvileg javítva.
