### ISSUE TITLE
Egy hatásos csapda mindenki ellen

### ISSUE THREAD

**Issue by TamasB14** [andris155/TheOld-Crafters#2111]
Ha csinálunk nether portált ami működik de nem teleportál sehova, akkor ha abba valaki belemegy és bezárjuk, nem tud elteleportálni,irni,chatet használni, szóval ott marad örökre. Egy youtube link hogy honnan találtam https://www.youtube.com/watch?v=QS2N2X2cjMU

**Comment by andris155** [comment]
Undorítóan néznek ki ezek a HD skinek. Szerintem ez csak ront a játékon. Egyébként ezért vannak megcsinálva, hogy még a telkeken is működjenek a portálok. Nálunk ez nem működik a szerveren.
