### ISSUE TITLE
sok fordítás hiányosság egy issue-ban +elírás

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#2112]
back jog event világban:
![2018-06-21_09 48 19](https://user-images.githubusercontent.com/29951969/41706593-79c56b00-753c-11e8-83ae-33208848b7cd.png)
Pár warpolásnál automatikusan kiírja ezt a feliratot: "You don't have a mypet'":
![2018-06-21_09 48 26](https://user-images.githubusercontent.com/29951969/41706659-a4aee594-753c-11e8-815d-f784caa1df7b.png)
back jog a boltban: 
![2018-06-21_09 48 54](https://user-images.githubusercontent.com/29951969/41706712-c15323ae-753c-11e8-9f34-5b436e3651b1.png)
Épp szemet szúrt mikor fordításokat kerestem. Alapbó helyett Alapból:
![2018-06-21_09 49 46](https://user-images.githubusercontent.com/29951969/41706761-df57eb50-753c-11e8-88ff-5d44f52461df.png)
Ha megpróbálok flaget állítani spawnon:
![2018-06-21_09 50 17](https://user-images.githubusercontent.com/29951969/41706806-00222c6a-753d-11e8-96e9-8bcc5ebf250a.png)
Mod-Damage flagot szerettem volna állítani. Se jog, se fordítás:
![2018-06-21_09 50 48](https://user-images.githubusercontent.com/29951969/41706886-2c6a3d26-753d-11e8-8340-f4c622249d46.png)
Spawnon nwm tudok pvp-zni kiírás:
![2018-06-21_09 52 48](https://user-images.githubusercontent.com/29951969/41706970-58bd24a6-753d-11e8-8624-5ab3e240f5fc.png)
/rg flag parancs:
![2018-06-21_09 57 12](https://user-images.githubusercontent.com/29951969/41707017-7584c27e-753d-11e8-990c-324c0e013d4c.png)
/rg parancs:
![2018-06-21_09 57 20](https://user-images.githubusercontent.com/29951969/41707037-7eb281ba-753d-11e8-8cd5-e074982bb18c.png)
Nem tudok blokkot ütni spawnon kiírás:
![2018-06-21_09 58 52](https://user-images.githubusercontent.com/29951969/41707122-b5d722cc-753d-11e8-93bc-eb81c63a604a.png)
Nem tudok "Hamarosan"-ra felmenni kiírás:
![2018-06-21_10 04 37](https://user-images.githubusercontent.com/29951969/41707173-d1e264ae-753d-11e8-8e52-a42d2856fe59.png)
Szerintem a yt-t lehetne fordítani, Tény hogy sokaknak alap, de sok ember van aki nem tudja. Ehhez nem csatolok képet.
Falusi bolt alkotásnál az egyik bolt fajta nincs fordítva:
![2018-06-21_10 05 23](https://user-images.githubusercontent.com/29951969/41707327-2010eac4-753e-11e8-8c94-61fa8b5a4f9c.png)
Itt lett kész a bollt:
![2018-06-21_10 05 24](https://user-images.githubusercontent.com/29951969/41707380-43dc53bc-753e-11e8-9daa-92d376eb3b20.png)
Additions:
![2018-06-21_10 14 31](https://user-images.githubusercontent.com/29951969/41707456-6c81c324-753e-11e8-8cf4-3fbc2fa56eea.png)
![2018-06-21_10 14 45](https://user-images.githubusercontent.com/29951969/41707465-6fc38838-753e-11e8-9ec2-2292dc46dc37.png)
Megpróbáltam gm1-ben inni egy vizespalackot és ezt dobta ki, szerintem nem ezt kéne:
![2018-06-21_10 15 12](https://user-images.githubusercontent.com/29951969/41707510-8ee5a020-753e-11e8-9ce8-2e1a8aeaec2d.png)

Remélem volt haszna hogy ennyit keresgéltem. \skrisz01\

**Comment by andris155** [comment]
Sajnos a WorldGuard-nak nincs fordítás fájlja. A legértelmesebb átírni lenne a forráskódban, de az mindig plugin frissítésnél elég nagy munka lenne. Ezenkívül még a protocol-al lehetne átírni, de az meg már ugye erőforrást is használ valamennyit így maradt angol az a szöveg, mert szerintem ennyit csak tud mindenki angolul azért. :D

**Comment by skrisz0101** [comment]
és a többi? :D

**Comment by andris155** [comment]
Sajnos a többet sem tudtam lefordítani.

**Comment by poma123** [comment]
Az AdditionsAPI fordítási probléméval kapcsolatban írtam a fejlesztőnek.
