### ISSUE TITLE
Bug/Survival

### ISSUE THREAD

**Issue by kartinmc** [andris155/TheOld-Crafters#2113]
Végtelen arany
Lépései
Craftolj egy kö kardot
warp bolt és ott cserekereskedelem 
laci beváltja neked arany kardra
Mcmmo miatt az aranyblokra kattintva az aranykardból arany lesz minélmagasabb a szint annáltöbb aranyat kapsz
Játékos nevem kartin

**Comment by MrZero1** [comment]
Javítva. Köszönjük a hibajelentést!

**Comment by andris155** [comment]
5080 OCD

**Comment by andris155** [comment]
Milyen névre adjam?

**Comment by kartinmc** [comment]
kartin és köszönöm
