### ISSUE TITLE
A kanyonon lévő teleport. 

### ISSUE THREAD

**Issue by PreczPerec** [andris155/TheOld-Crafters#2114]
A kanyonon lévő gomb, ami fölé az van írva, hogy "Lejutáshoz nyomd meg", egy mocsárszerű helyre dob, ami mellett pár blokkra egy 3x2es lyuk van, alján nyálkablokkal, pedig az épület földszintjére kéne dobnia, ahonnan elérhető a mesa biome.

**Comment by MrZero1** [comment]
Javítva. Köszönjük a hibajelentést!
