### ISSUE TITLE
Skin bug

### ISSUE THREAD

**Issue by FoxyLeBel** [andris155/TheOld-Crafters#2115]
Hali!
Prémium felhasználóként nekem elvileg kéne hogy látszódjon a skinem. Beírtam kétszer a parancsot, de semmi nem változott, mindent próbáltam már vele. Újra feltöltöttem, relogoltam stb.. Más szerveren látszódik, de egyedül itt nem.

**Comment by MrZero1** [comment]
Szia. 

A login lobbyban a /premium parancs kétszeri beírása után relogolni kell. Az is megvolt?

**Comment by FoxyLeBel** [comment]
megvolt

**Comment by andris155** [comment]
Van egy limit is mennyiszer lehet lekérni hozzá az adatokat, szóval néha időbe telik.

**Comment by andris155** [comment]
De miután egyszer jó utána már végleg jó :D
