### ISSUE TITLE
Barkácsasztalos dolog.

### ISSUE THREAD

**Issue by tamoooka** [andris155/TheOld-Crafters#2118]
Dugattyú készítése közben történt, az inventorymban két szabad slot volt, a többi tele.
Beraktam a hozzávalókat a barkácsasztalba (fa, vas, redstone, kő), viszont a vas és redstone helyét felcseréltem, ezért nem tudtam lecraftolni. 
Ezért rákattintottam a crafting bookban a dugattyúra, hogy újra megnézzem a receptet. Ekkor a barkácsasztalból a cuccaim visszadobta az inventorymba, és megmutatta előzetesben a receptet.
A probléma ugye az volt, hogy 2 szabad helyem volt. A fát és követ visszakaptam, viszont a redstone és a vas eltűnt. Többször ellenőriztem, nem esett ki a crafting table mellé, és az inventorymba se stackelődött be többi redstone mellé, hiszen nem volt nálam. 
Hogy leellenőrizzem, újra megcsináltam a folyamatot, és újra megtörtént. 
(ha nem érthető, csak szólj, aztán videó mellett eljátszom harmadszorra is.)

**Comment by tamoooka** [comment]
Ha relog megoldaná, akkor gondolom a mellettem levő player látta volna az itemeket, ahogy kiesnek.

**Comment by andris155** [comment]
Videó kellene erről, illetve hajnali 4-es újraindítás után készítsd el.

**Comment by tamoooka** [comment]
Vettem uram.

**Comment by tamoooka** [comment]
https://youtu.be/BVnqQSKASI0
Orbitális nagyságú lett a videó, szóval feltöltöttem youtubera.

**Comment by tamoooka** [comment]
Orbitális nagyságú lett, úgyhogy feltöltöttem youtubera.
Valószínűleg borzasztó a minősége és 5 fps, de a lényeg látszik. A 64+3 vasamból 64 marad, a craftoláshoz használt hármat felszívja az űr.
https://youtu.be/BVnqQSKASI0

**Comment by andris155** [comment]
Mondjuk szerintem ilyet csak úgy nem csinál semmi. Vannak fontosabb fejlesztések és javítások amivel inkább foglalkozok ez helyett. Ha egyjátékos módban is működik akkor a Mojang jira oldalán kellene ezt jelenteni.
