### ISSUE TITLE
Szimpla pénzbug.

### ISSUE THREAD

**Issue by KingDeadZ** [andris155/TheOld-Crafters#2119]
Megveszek 16 farönköt  350ért, átcraftolom bottá és átalakítom seeddé. 984 et keresek. Majdnem hogy megtriplázom a pénzemet :D 
![2018-06-23_19 08 24](https://user-images.githubusercontent.com/38157910/41811941-4b12fe6a-7719-11e8-8afa-e809ab6daf35.png)
![2018-06-23_19 09 12](https://user-images.githubusercontent.com/38157910/41811944-544ba702-7719-11e8-8173-009d4041f181.png)
![2018-06-23_19 09 56](https://user-images.githubusercontent.com/38157910/41811945-5d354bf2-7719-11e8-9a2e-cda60ff2a755.png)

**Comment by andris155** [comment]
2032 OCD
