### ISSUE TITLE
Parancsokat kiírja a chatre

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#212]
Ez mégis mi lehet? Felmegyek a szerverre, egy ideig jó volt, aztán 20 perc után megint elkezdte. Pár napja volt ilyen, 1.9 forge / sima 1.9 is csinálta, most az 1.10 is...

https://www.youtube.com/watch?v=GbEHHW0zcC0&feature=youtu.be

**Comment by andris155** [comment]
Nem támogatjuk a Mac OS rendszert.
