### ISSUE TITLE
Bármennyi levelet lehet bugoltatni.

### ISSUE THREAD

**Issue by KingDeadZ** [andris155/TheOld-Crafters#2122]
Ha valaki kreatívban lerakja a leveleket, és te kiütöd baltával a lefélfújó képességgel, akkor kidroppolja.

**Comment by andris155** [comment]
Ha jól emlékszem az mcmmo-nak nincs külön api része erre így nem tudott mit kezdeni vele a kreatív védelem fejlesztője. Meg ez olyan apró dolog, hogy szerintem is érdemes ezzel foglalkozni. De köszönjük a jelentést.
