### ISSUE TITLE
Ötlet By Skrisz01 & KingDead

### ISSUE THREAD

**Issue by KingDeadZ** [andris155/TheOld-Crafters#2123]
Hali! Lenne egy ötletem egy új rangra: [MiniSegítő]

Célja: A próbaidősöknek segít, és a játékosoknak (Így már volt Teljes jogú segítőnek kellett lennie)
       
Jogai: A Helpop látása.
       /mute

       És érvényesül a jelenlegi rangjának a joga is.

       Ugyan úgy játszhat, mint a többi játékos csak látja a helpopot, és ha a próbaidős segítő nem tud válaszolni esetleg (Ami néha valószínű) Akkor ő válaszol.

**Comment by skrisz0101** [comment]
szerintem inkább te ötletelted ki :D én csakk hallgattam :D

**Comment by KingDeadZ** [comment]
![image](https://user-images.githubusercontent.com/38157910/41869754-4765e58c-78ba-11e8-8d20-0f53fc88d78f.png)

**Comment by KingDeadZ** [comment]
Stafflétra: MiniSegítőből<--Próbaidős<---Teljes jogú segítő<---Moderátor<---Admin

**Comment by KingDeadZ** [comment]
Fontos: A minisegítő tapasztalt legyen :D (És ha úgy van, feljebb tudjon lépni próbaidőssé esetleg)

**Comment by brtamas0** [comment]
![image](https://user-images.githubusercontent.com/23553862/41917618-223fe2c0-795b-11e8-9dfd-de608e283ed7.png)

**Comment by brtamas0** [comment]
![image](https://user-images.githubusercontent.com/23553862/41917644-30838ada-795b-11e8-9f82-57334fbdc752.png)
