### ISSUE TITLE
Dupla fejű balta bug

### ISSUE THREAD

**Issue by KingDeadZ** [andris155/TheOld-Crafters#2124]
Hiába törik be a balta, tovább vágja a fát. Mostanába ezt bugoltatják, és szereznek vele csomó pénzt, mivel egybenő a mamutfenyő..
https://www.youtube.com/watch?v=vI-fOB9cpB0&feature=youtu.be

**Comment by skrisz0101** [comment]
amit lehet mcmmo-s fadöntéssel is csinálni

**Comment by MrZero1** [comment]
Lehet én nem értem, de a duplafejű balta lényege ez. Egyszerre vágja ki a fát.

**Comment by KingDeadZ** [comment]
Példa: Megnövesztesz vagy 20 mamutfenyőt. És 1 fabaltával kivágod az egészet úgy, hogy már az elsőnél betörne.

**Comment by andris155** [comment]
Valószínűleg már csak az 1.13-as frissítésnél javítja ezt a plugin-ban a fejlesztő.

**Comment by andris155** [comment]
Még mindig él a hiba?
