### ISSUE TITLE
Tölcsér - Csillés láda bug

### ISSUE THREAD

**Issue by brtamas0** [andris155/TheOld-Crafters#2125]
Andris valami optimalizációról beszélt hogy ez miatt nem működhet. ha fölül van egy tölcsér és alatta egy csillés láda akkor nem viszi át az itemet.

**Comment by andris155** [comment]
Igen sajnos ez annak a hibája, már régebben jelentették egyébként. Sajnos ez az optimalizáció muszáj a szerver zökkenőmentes működéséhez.
https://github.com/PaperMC/Paper/issues/354
