### ISSUE TITLE
Kreatív védelem - Craftbook hiba

### ISSUE THREAD

**Issue by brtamas0** [andris155/TheOld-Crafters#2126]
Ha kreatívban teszünk le craftbookos pipe táblát akkor működik de ha el megyünk pl telekre és vissza megyünk a farmhoz akkor ott marad a kreatívos [pipe] tábla de nem működik ezért le kell ütni majd újra le kell tenni.

**Comment by andris155** [comment]
Hát ne kreatívban rakd rá a táblát. :D
