### ISSUE TITLE
Eventek hiba

### ISSUE THREAD

**Issue by KingDeadZ** [andris155/TheOld-Crafters#2127]
A spleef eventen lehet /additions repair-t használni.
![2018-06-27_17 07 36](https://user-images.githubusercontent.com/38157910/41982896-dd49edb4-7a2c-11e8-92c1-b246c16dd38d.png)

**Comment by brtamas0** [comment]
örülj neki :D

**Comment by MrZero1** [comment]
Ezt a parancsot lehetne tiltani az egész SurvivalGames világban. @andris155

**Comment by andris155** [comment]
kész

**Comment by andris155** [comment]
330 OCD
