### ISSUE TITLE
Login és lobby szerver - PlaceholderAPI, NTE

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#2129]
Nem tudom, mi történt ezzel a 2 pluginnal, de ha ki lettek véve, tabról törölni kéne a nem működő részeket.

![kep](https://user-images.githubusercontent.com/16057404/42020870-6c413e00-7ab9-11e8-9dfe-0693424ac8da.png)
![kep](https://user-images.githubusercontent.com/16057404/42020925-96f5e2ae-7ab9-11e8-90b2-7091ddbadb72.png)

A login belépési üzenete se túl szép így, jobbak voltak az előző színek.

![kep](https://user-images.githubusercontent.com/16057404/42021263-7541fdae-7aba-11e8-86e8-435350cb3b16.png)

**Comment by andris155** [comment]
A belépési üzenet adott, de nem tudom hogy lehetne jobban elrendezni. Sajnos a forráscsomagos dolgot muszáj beleírni, mert ezzel kapcsolatban rengeteg probléma volt már.

**Comment by andris155** [comment]
Javítva
