### ISSUE TITLE
Old csizma lelassul

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#213]
Mentem SG eventre, a petem inv-jébe tettem az old csizmámat, sg közben meghalt a netem. Mire visszaértem, és kivettem a pet-ből az oldcsizmát, nem volt rajta a +50% sebesség, hiába írta, ugyanolyan lassú volt mint egy sima csizma.

**Comment by andris155** [comment]
A relog elvileg megoldja.
