### ISSUE TITLE
Nagyobb enderchest

### ISSUE THREAD

**Issue by Sheep04** [andris155/TheOld-Crafters#2130]
Üdv!
Lehetne OCD-ért nagyobb enderchest slotot venni, nem ranggal együtt, teljesen külön, úgy, mint a skin jognál.
Sheep04

**Comment by andris155** [comment]
-----------------
Tesztelés alatt!
-----------------

**Comment by andris155** [comment]
https://www.oldcrafters.net/2018/07/01/elerhetoek-a-plusz-enderladak-a-minemarket-oldalunkon/

**Comment by andris155** [comment]
508 OCD
