### ISSUE TITLE
Telkek - ollóra gyengéd érintés

### ISSUE THREAD

**Issue by poma123** [andris155/TheOld-Crafters#2131]
Admin joggal működik.
![image](https://user-images.githubusercontent.com/25465545/42023684-c26a41f8-7ac0-11e8-8c03-7d3c6904aa80.png)

**Comment by andris155** [comment]
Admin joggal sem megy, ha nem vagy kreatívban szerintem.

**Comment by andris155** [comment]
Ollóra nem lehet ilyet rakni ez az alap játék része.

**Comment by andris155** [comment]
Ezeket lehet rá: Curse of Vanishing, Efficiency, Mending, Unbreaking

**Comment by poma123** [comment]
Ehh.
