### ISSUE TITLE
Ajánlatok

### ISSUE THREAD

**Issue by KingDeadZ** [andris155/TheOld-Crafters#2137]
https://www.spigotmc.org/resources/furnacelevels.57673/
Fejleszthető kemencék.

https://www.spigotmc.org/resources/moar-bows.36387/
Jobbnál jobb fajta különleges íjak.

https://www.spigotmc.org/resources/one-hundred-days-mini-game.58305/
Egy egyszerű játék a szerverre. 
Elképzelésem ezzel kapcsolatban: Időnként lenne tartva egy ilyen fajta event, amiben sok OCt esetleg OCDt lehetne nyerni.

**Comment by andris155** [comment]
Egyelőre saját gép és telefon nélkül nem akarok nagyobb fejlesztésekbe vágni.
