### ISSUE TITLE
Savsziget pénz bug

### ISSUE THREAD

**Issue by KingDeadZ** [andris155/TheOld-Crafters#2138]
Veszel 64 homokot 240$ért, majd kisütöd így lesz 64 üveg amit el tudsz adni 400$ért.
![2018-07-07_01 35 40](https://user-images.githubusercontent.com/38157910/42404071-469af302-8186-11e8-9911-0fe6caa170c5.png)
![2018-07-07_01 35 48](https://user-images.githubusercontent.com/38157910/42404075-499a9c10-8186-11e8-8171-8f4a4dcab938.png)

**Comment by poma123** [comment]
Javítva.
Köszönjük a hibajelentést!

**Comment by andris155** [comment]
330 OCD
