### ISSUE TITLE
Kreatív bug

### ISSUE THREAD

**Issue by KingDeadZ** [andris155/TheOld-Crafters#2139]
Amit régebben építettek kreatívban az emberek, azt ki lehet ütni gm0ban, és meg is kapod. (Videót erről nem szeretnék készíteni, mert nem tudnám sehogy sem bebizonyítani :D Ki lehet próbálni a szerveren olyanon, ami kreában lett építve.)

**Comment by Sheep04** [comment]
#1439 
kb ez xd
