### ISSUE TITLE
Ender Dragon idézés

### ISSUE THREAD

**Issue by geri5200** [andris155/TheOld-Crafters#214]
Amikor End Kristállyal megidézem a sárkányt akkor amikor az utolsó kristályt mindig vissza adja itemként.

**Comment by andris155** [comment]
Ez egyjátékos módban is így van?

**Comment by geri5200** [comment]
nem tudom de megnézem

**Comment by Treuce** [comment]
Már jelentett bug. Én jelentettem.

**Comment by geri5200** [comment]
hop akkor bocsi

**Comment by geri5200** [comment]
De survivalban nem kapom vissza

**Comment by andris155** [comment]
Akkor egyjátékos módban nem így van?

**Comment by geri5200** [comment]
egyjátékosban nem így van

**Comment by andris155** [comment]
Teszteltem házi szerveren nem adta vissza a kristályt, elvileg a szerveren  sem kellene.
