### ISSUE TITLE
Shop bug [SAV sziget]

### ISSUE THREAD

**Issue by Conan-iwnl** [andris155/TheOld-Crafters#2140]
Ha 2 lávát veszünk egyszerre és lerakjuk mikor stack-elve van úgy érzékeli mintha 1 lávát tettünk volna le és eltűnik a másik. (Képet nem tudok csatolni nincs pénzem már lávára.)

**Comment by andris155** [comment]
Ezt talán poma tudja megoldani.

**Comment by poma123** [comment]
A boltban „több vásárlása” funkciót csak minden terméknél lehetne letiltani, ami nem előnyös. Legfeljebb azzal tudnék játszani, hogy amikor klikkelsz az inventoryban a lávásvödörre, akkor kidobná az összeset ami az eszköztárban van, vagy mondjuk mikor klikkelnél a lávásvödrökkel, és több van belőle, akkor megszakítaná a folyamatot, és ugyanúgy kidobná ami nálad van. Jobb ötletem egyelőre nincs.

**Comment by andris155** [comment]
Egyszerűbb figyelmeztetni őket inkább erre valahol, hogy erre figyeljenek és ne stack-elve használják a lávás vagy vizes vödröt.
