### ISSUE TITLE
Savsziget: mcmmo lag

### ISSUE THREAD

**Issue by Icecroft** [andris155/TheOld-Crafters#2141]
A reset óta az az mcmmo fadöntés skillje nagyon laggoltatja a szervert.
Mindössze 6 fát ütök ki, de fél percig nem tér magához, a fák nem azonnal robbannak szét, visszadobál, nem üti ki végül mindegyiket, a többiek pedig panaszkodnak, mekkora a lag. Ilyen a survivalen nem volt, sem a reset előtt. Valószínüleg valami újdonsággal összeakad, de csúnyán. Lehet a twerkelő pluginnal?

**Comment by poma123** [comment]
Elvileg javítva.
Köszönjük a hibajelentést!

**Comment by Icecroft** [comment]
Szuperül megy mint régen :)
