### ISSUE TITLE
Old ranggal kreatívban meg tudom sebezni/megölni a Magmakockát

### ISSUE THREAD

**Issue by ColaKing00** [andris155/TheOld-Crafters#2143]
Old rangom van, át megyek kreatívba és meg tudom sebezni/meg tudom ölni a Magmakockákat.

**Comment by andris155** [comment]
Videót erről nem tudsz készíteni?

**Comment by ColaKing00** [comment]
De tudok. nemsokára küldöm.

**Comment by Sheep04** [comment]
#1401

**Comment by ColaKing00** [comment]
És ezzel magmakrémet is lehet így akkor addolni.
(Kreatívban megölöm, eldobja a magmakrémet, átmegyek túlélőbe, felveszem és
kész.)

2018-07-11 15:24 GMT+02:00 O Duoling <oduoling@gmail.com>:

**Comment by andris155** [comment]
Már volt jelentve ha ez az mcmmo segítségével történik.

**Comment by ColaKing00** [comment]
Nem használtam mcmmo képességeket.



2018-07-11 15:38 GMT+02:00 András Marczinkó <notifications@github.com>:

**Comment by ColaKing00** [comment]
Elméletileg e-mailben küldtem erről videót de nem tudom hogy megérkezett-e.

**Comment by ColaKing00** [comment]
Nem használtam mcmmo képességeket.

2018-07-11 17:26 GMT+02:00 Sheep04 <notifications@github.com>:

**Comment by andris155** [comment]
nem kaptunk semmilyen videót

**Comment by poma123** [comment]
https://youtu.be/nnwABLdOzsQ

**Comment by andris155** [comment]
köszönöm a videót!

**Comment by poma123** [comment]
Nincs mit. :D

**Comment by ColaKing00** [comment]
Igen... Sajnos én ilyen minőségű videót nem tudtam csinálni, amit elvileg
elküldtem de nem érkezett meg azt is a telefonommal csináltam. De én is
köszönöm Poma hogy felvetted. 😄

Poma123 <notifications@github.com> (időpont: 2018. júl. 16., H, 9:50) ezt
írta:

**Comment by andris155** [comment]
Elvileg javítva.

**Comment by andris155** [comment]
508 OCD

**Comment by mr00000** [comment]
kaka pisi kaka @ColaKing00 @andris155 @Sheep04 @poma123

**Comment by Sheep04** [comment]
Mi a gond, @mr00000?
