### ISSUE TITLE
Old ranggal tudok sötéttölgy ajtót addolni.

### ISSUE THREAD

**Issue by ColaKing00** [andris155/TheOld-Crafters#2146]
Átmegyek kreatívba leteszem az ajtókat. Utána átmegyek túlélőbe kiütöm a lerakott ajtókat ÉS MEGKAPOM ITEM FORMÁBAN.

**Comment by ColaKing00** [comment]
(csak sötéttölgy ajtóval!)

**Comment by poma123** [comment]
https://www.youtube.com/watch?v=n_Y2Kd43dzU

**Comment by poma123** [comment]
Igazából csak annyi a lényege, hogy a plugin egy blokkot ment az adatbázisba, az ajtó alsó blokkját, és ha fönt ütöd ki akkor odaadja az ajtót. Mindegyik ajtóval működik.

**Comment by andris155** [comment]
köszönöm a videót.

**Comment by poma123** [comment]
Szívesen.

**Comment by ColaKing00** [comment]
És ez nem baj?

Poma123 <notifications@github.com> (időpont: 2018. júl. 15., V, 21:57) ezt
írta:

**Comment by ColaKing00** [comment]
Igen utána rájöttem hogy minden ajtóval működik

O Duoling <oduoling@gmail.com> (időpont: 2018. júl. 17., K, 22:19) ezt írta:

**Comment by andris155** [comment]
Elvileg javítva

**Comment by andris155** [comment]
508 OCD
