### ISSUE TITLE
/bolt nem működik

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#2147]
Hiába kattintok bármire a megnyíló menüben, nem történik semmi.

![ezgif-1-10964357fe](https://user-images.githubusercontent.com/16057404/42621709-c71e9902-85be-11e8-8de5-e3f9649cac81.gif)

**Comment by andris155** [comment]
Másnak se működik?

**Comment by andris155** [comment]
javítva

**Comment by andris155** [comment]
508 OCD
