### ISSUE TITLE
végtelen használhatatlan tej

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#2148]
ha tehén/gombatehén peted van, és jobb klikkelsz egy vödörrel a petre, kapsz tejet, de nem éehet becraftolni és ha megiszod, megmarad, azaz végtelen :v

**Comment by andris155** [comment]
Erről videót tudsz készíteni?

**Comment by skrisz0101** [comment]
őő talán

**Comment by skrisz0101** [comment]
megpróbálom

**Comment by poma123** [comment]
Először is, nem keletkezik tej. Egy sima vödröt tartunk a kezünkben azután is, miután klikkeltünk a tehénre. Tudniillik a klienst csapja be az a klikk, mivel ha tehén petre klikkelünk elvileg megszakítja az eventet. Tehát igazából egy üres vödröt tartunk a kezünkben, és a kliens azt hiszi, hogy ez tejes vödör. Ezért van textúrája is, és ha meg szeretnénk inni, akkor végtelen ideig csinálja (mivel az üres vödröt nem lehet meginni, bármeddig tartjuk nyomva a gombot). És egyébként ha kliensoldali eszközkeret frissítés megy végbe (pl. ládanyitás, ráklikkelés bármelyik dologra az eszköztátban) akkor visszaváltozik a tényleges üres vödörre.

Összefoglalva mikor ráklikkelünk a tehénre nem kapunk tejet, egy üres vödröt tartunk a kezünkben, de a kliens mégis azt hiszi, hogy az a tehén tejet adott.

Szóóval igazából ezzel semmilyen előnyt nem lehet elérni.

**Comment by skrisz0101** [comment]
like
