### ISSUE TITLE
Redstone fáklya nem eladható (talán ID miatt)

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#2149]
képen látható a redstone fáklya fura ID-je. Valszeg amiatt nem lehet eladni.
![2018-07-14_19 13 39](https://user-images.githubusercontent.com/29951969/42726783-561d4450-879a-11e8-8874-d03b76270140.png)

**Comment by andris155** [comment]
Kérd meg az adminokat, hogy javítsák majd.

**Comment by andris155** [comment]
Néhány ID megváltozott, amiért frissült a Chestshop. Ezt a verziót már az 1.13-ra tervezték elsősorban.
