### ISSUE TITLE
Dugattyú kreatív bug

### ISSUE THREAD

**Issue by BBenceX** [andris155/TheOld-Crafters#2154]
Mag addolás: A növények ültetéséhez szükséges fény is. És ha ez nincs meg a mag kiesik. És ha kreatívban ültetünk erre a sötét helyen lévő terméketlen földre akkor ugyan úgy kiesik a mag és megkapod a magot túlélőben is.                                                                                                                                                         Ajtó addolás: Ajtót pedig ha le teszem akkor ugye két blockos na most ha a felső blockját ütjük ki akkor az ajtó megkapható item formában és szintén túlélőben is fel tudjuk szedni.

**Comment by Viktor1969YO** [comment]
Shulker boxnál is lehet addolni. Pistonnal el lököd és utána ha túlélőben kiütöd megkapod.

**Comment by poma123** [comment]
@BBenceX a második már jelentve lett. #2146

**Comment by andris155** [comment]
Erről is videó kellene,

**Comment by poma123** [comment]
https://youtu.be/3Bt9Mn4cAw0
Nem vagyok robot, hogy mindig én csináljak videót, ha valaki nem tud akkor oldja meg, viszont ha feltétlenül nekem kell akkor nekem is jár egy kis OCD szerintem.

**Comment by BBenceX** [comment]
Igazán nem értem mit kell hisztizned egy 5perces munkán. Már nem azért de legközelebb akkor inkább nem jelentem mert nem kell az hogy tele hisztizd a chatet. (Ezt muszáj volt leírnom bocsánat)

**Comment by poma123** [comment]
te kértél meg engem, és kábé 15 percig hátráltattál miközben már rég elkészíthettem volna, végül 20 perc lett belőle az általad említett 5 perc plusz miatt. szóval köszönöm az időhúzást, és hogy ismét nagyon jó napom lett tőled.

**Comment by BBenceX** [comment]
Nagyon szívesen. Szép napot igen!

**Comment by poma123** [comment]
saját magad alatt vágod a fát.

**Comment by BBenceX** [comment]
Nem mert éppen bányászok. :) Egyébként azért nem vesztek fel mert utáltok akkor meg nem tök mindegy mennyire utáltok? :D

**Comment by poma123** [comment]
ki kérdezte hogy miért nem veszünk fel? és mióta publikus?

**Comment by BBenceX** [comment]
Csak hozzá tettem. És mi mióta publikus? Az hogy utáltok? :D

**Comment by poma123** [comment]
miért kell többes számban beszélni? 1 senki nem mondta hogy utál 2 ha én annyira utálnálak nem is válaszoltam volna amikor rám írtál 3 nem adjuk ki hogy kit miért nem veszünk fel, szóval akkor úgy tűnik nagyon érzed, hogy nem vagy a szívem csücske amikor 15 percig arról van szó hogy meg tudom-e érteni amit leírtál, és hogy biztosan értem-e, mikor azzal kezdtem hogy igen tudok olvasni, megértem.
amúgy először megy a nyali, és ha nem sikerül utána összeakasztjuk a bajszunkat mindig? már párszor eljátszottad ezt és unalmas, és ez a kontextus ahogy beszélsz rólam ugyanúgy.

Andris amúgy majd nyugodtan töröld ezeket a hozzászólásokat, bár eléggé vicces az egész. xd

**Comment by BBenceX** [comment]
Akkor csináljátok meg ti mert én nem tudok :) És ezért fordultam pomához mert Andris azt mondta ha nem tudom megcsinálni szóljak neki.

**Comment by MrZero1** [comment]
Akkor meg ne hátráltasd a videó elkészítésében. Aztán meg ne ilyen hangnemben beszélj vele. Ennyi.

**Comment by poma123** [comment]
megint ugyanaz azt az előre nem gondolkodok mielőtt bármit is írok viselkedést produkálod. nagyon jól tudod min kaptam fel a vizet, szóval fejezzük be a szórakozást mert nevetséges.
kész vége.

**Comment by BBenceX** [comment]
Nagyon is jól tudom hogy mit miért írok és eddig igen próbáltam kedves normális lenni mert ugye nem jó egy olyan szerver játszani ahol nem számíthatsz admini segítségre ha bármi gondod van. Na de ha nem díjjazzátok akkor lehetek kicsit modortalanabb is felőlem aztán..

**Comment by poma123** [comment]
nyugodtan úgyis lesz következménye..!

**Comment by MrZero1** [comment]
A játékos hozzáállása, modora nem befolyásolja a staffok segítségét. Lehet akármennyire ellenszenved és/vagy idegesítő és/vagy irritáló stb stb. az illető, függetlenül bárkinek bármilyen segítünk. De mivel Mi is emberek vagyunk, így elvárjuk azt, hogy a másik fél normálisan közeledjen felénk. Lehet ragozni, felesleges. 
Ami alatt pedig Te modortalanságot gondolsz, már bőven egy másik kategóriát üt meg. :wink:

**Comment by BBenceX** [comment]
Rendben van tehát akkor legyen úgy ahogy mondod és bár pomát nem értem mi következményt akar ennek. Viszont én először igen is normálisan mondtam meg mit szeretnék. De teljesen igazad van Zero ne ragozzuk. :)

**Comment by Roar3** [comment]
Poma, engem is ki nem állhatsz, mégis mindig visszaírsz, szóval szerintem hagyjuk ezt a honnan gondolta dolgot.

**Comment by UDPSendToFailed** [comment]
![tenor](https://user-images.githubusercontent.com/16057404/42961499-3b9c0aa0-8b8f-11e8-9767-0eff5aefcffa.gif)

**Comment by andris155** [comment]
Köszönöm a videót.

**Comment by andris155** [comment]
Javítva!
Köszönjük a hibajelentést!

**Comment by andris155** [comment]
508 OCD
