### ISSUE TITLE
[Ötlet]Régi OldGold, OldDiamond beváltása

### ISSUE THREAD

**Issue by Tyloendis** [andris155/TheOld-Crafters#2155]
Helo!
Régen, mikor még nem volt oldcoin, ugyanúgy meg kellett dolgozni az oldgoldért, illetve az old diamondért, de jelenleg semmi hasznuk nincsen. Esetleg nem lehetne átváltatni őket az új pénznembe?

**Comment by MrZero1** [comment]
Nem nagyon lesz ilyesmi, anno sok OldGold lett duplikálva/addolva. Szeretnénk majd a jelenlegi rendszert is megoldani, ne legyen ilyesmi a közeljövőben.
