### ISSUE TITLE
YT rang

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#2156]
Szia. Kérésre. :D 

https://www.youtube.com/channel/UC2tmGVwmrJfp8Ufx3rcuKjw

A játékos (csabamc24) nem kapta meg a rangot. Manuálisan megadva.

**Comment by andris155** [comment]
Fogalmam sincs miért nem jó. Ha pedig nem támogat több beállítási lehetőséget, akkor miért van benne ilyen lehetőség. Beszélni kellene a fejlesztővel, de az én angol tudásom szerintem ehhez kevés.

**Comment by andris155** [comment]
https://discordapp.com/invite/GmuPTqb

**Comment by andris155** [comment]
Újra beállítottam és máshogyan. Talán sikerült ezzel megoldani.

**Comment by andris155** [comment]
Most meg a megadási parancs nem jó elvileg. :/

**Comment by andris155** [comment]
Elvileg már jó
