### ISSUE TITLE
Magok + nincs fény bug kreatív

### ISSUE THREAD

**Issue by BBenceX** [andris155/TheOld-Crafters#2160]
Piston addolás: Kreatívban ha leteszel egy vöröskő blockot és mellé teszel egy pistont akkor az aktiválódik. Na most a piston 2 block és ha a második blockját kiütöd akkor kiesik a piston és fel lehet venni surviban.

**Comment by poma123** [comment]
itt a videó, ugyanaz a megjegyzés hozzá mint az előzőhöz.
https://youtu.be/LV6XlXoZ-ys

**Comment by andris155** [comment]
Köszönöm a videót.

**Comment by andris155** [comment]
Javítva!
Köszönjük a hibajelentést!

**Comment by andris155** [comment]
508 OCD
