### ISSUE TITLE
petparancsok warp - minemarketes petek

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#2161]
a táblákon van pár elírás:
![2018-07-21_11 45 23](https://user-images.githubusercontent.com/29951969/43035089-7cf71fe8-8ce9-11e8-9ce9-61f0822d96a0.png)

**Comment by andris155** [comment]
Ez nem elírás, hanem a plugin így rakja rá sajnos. De egyébként fomázatlan írással sem férne ki mind neve.

**Comment by skrisz0101** [comment]
értem
