### ISSUE TITLE
petparancsok warp megint :D

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#2162]
![2018-07-21_14 51 19](https://user-images.githubusercontent.com/29951969/43035787-9ce0b65a-8cf5-11e8-84cc-51622c9766d2.png)

a szamár, öszvér, láma, zombiló, csontvázló állatokat is be kell törni mielőtt befogod

**Comment by MrZero1** [comment]
Javítva. Köszönjük a jelentést.
