### ISSUE TITLE
Paintball hiba

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#2163]
Szia. 

Paintball játék indítás után ezzel a hibaüzenettel dob ki (azt, aki épp PB-n van, majd a játék indítását követően kidobja)
![pbhiba](https://user-images.githubusercontent.com/29709854/43044302-d801cd6a-8da3-11e8-9f4f-42316f15c2ae.png)

A becsatlakozást követően jó, majd ha 2 ember megvan, kidob. 

![2018-07-22_11 36 08](https://user-images.githubusercontent.com/29709854/43044306-edd9eb90-8da3-11e8-934a-9bd566150bbb.png)

**Comment by MrZero1** [comment]
A hibát FairyAnime és falcon0607 jelentette, Én csak teszteltem. 
Verzió: 1.12.2

**Comment by andris155** [comment]
Most jó?

**Comment by MrZero1** [comment]
Már jó. Köszönjük!
