### ISSUE TITLE
Fejlesztés

### ISSUE THREAD

**Issue by Viktor1969TOC** [andris155/TheOld-Crafters#2164]
Esetleg nem lehet megoldani miután kijöttek az 1.13-mas pluginok, hogy telefonos minecraft-tal is be lehessen lépni? (1.5-re gondoltam az az Aquatic Update telefonon)

**Comment by andris155** [comment]
Jól egyelőre ezt nem lehet megoldani. De valószínűleg a jövőben sem lesz. Mivel ezen a verzión nekünk is külön kellene tesztelni mindent, hogy megfelelően működjön.
