### ISSUE TITLE
Páncél bug

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#217]
Megtaláltam a #140 -re a megoldást, ha mobaréna közben kilépek a szerverről, rajtam marad a páncél védelme, Survival Games ugyanez, de mobarénában többet lehet bugoltatni a gyémánt páncél miatt. Egy playert páncél nélkül élesség V karddal 1-2 ütés megölni. Ha kilépés előtt leveszem a páncélt, relog után eltűnik a védelem.

https://www.youtube.com/watch?v=os85fwGnhLw&feature=youtu.be

**Comment by andris155** [comment]
Nincs megoldás. A mobaréna egy zárt forráskódú plugin, amit már nem fejlesztenek.
