### ISSUE TITLE
Survival /m parancs hiba

### ISSUE THREAD

**Issue by Tapperr** [andris155/TheOld-Crafters#2173]
A Survival szerveren ha hosszabb üzenetet küldünk valakinek akkor nem mindig küldi el.
/m

"DreaKii

**Comment by andris155** [comment]
Az 1.13-al játszóknál van ez a hiba. Használjátok az 1.12.2-őt. Az 1.13 támogatás egyelőre csak érdekességként van bent.

**Comment by andris155** [comment]
holnap már jó lesz.
