### ISSUE TITLE
Bugg

### ISSUE THREAD

**Issue by ggbani2** [andris155/TheOld-Crafters#2174]
Nem lehet eladni az ender bow-t ah-n vmiért és a többi ilyen jellegű itemet sem(pl emerald pick).
Bye: **Samurai**

**Comment by andris155** [comment]
Hol szeretnéd ezeket eladni?

**Comment by andris155** [comment]
Azért nem, mivel töröttnek számít, de akkor állítok ezen.

**Comment by andris155** [comment]
Elvileg most működik.

**Comment by andris155** [comment]
330 OCD
