### ISSUE TITLE
Mobaréna tárgyak kibugoltatása

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#218]
2 player kell hozzá, mindketten belépnek egy mobarénába. Player 1 relogol, miután belépett, ott van a mobarénában, de survival-ban. Player 2, aki addig bent volt, odaadja neki a mobarénás cuccait, páncél, kard, potik, stb, ezután player 1 elwarpolhat, megmaradnak nála a tárgyak.

**Comment by andris155** [comment]
javítva.
