### ISSUE TITLE
Telek hiba

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#2180]
Van egy telek, aminek nincs tulaja, nem lehet lefogalni. 
![kep](https://user-images.githubusercontent.com/29709854/43690140-69c3a98c-9905-11e8-8da1-00e2eda28429.png)

**Comment by andris155** [comment]
regional telke elvileg az adatbázis szerint.

**Comment by andris155** [comment]
![jegyzet](https://user-images.githubusercontent.com/8324198/43727998-e986950a-99a3-11e8-8bb6-4ab3ea2d14f3.png)
le van foglalva
