### ISSUE TITLE
Kiszedhető Enderchest üveglapok

### ISSUE THREAD

**Issue by Huntermaster0** [andris155/TheOld-Crafters#2183]
Az Enderchestből az üveglapok kiszedhetőek, ha a teleport/halál után még nem töltött be az MC. Ha hosszasan nyitogatni próbálom az enderchestet, nyilván egy idő után betölt az mc és megnyílik a chest, de ezt van, hogy bugosan teszi (ahogy észrevettem, elég kis %-ban teszi ezt), és ilyenkor kiszedhetőek az üveglapok.

**Comment by andris155** [comment]
Nálad is maradnak a lapok miután ki majd belépsz?

**Comment by MrZero1** [comment]
Nála maradtak, oda is adta nekem.

**Comment by Huntermaster0** [comment]
Igen, leteszteltem magam is, egy ládába raktam le.

**Comment by andris155** [comment]
Erről tudsz egy videót készíteni?

**Comment by Huntermaster0** [comment]
Az a baj, hogy nem. A gépem nem bírná el.

**Comment by andris155** [comment]
Telefon esetleg? Vagy kamera?

**Comment by Huntermaster0** [comment]
Ja hogy ilyen minőségben is jó? Akkor meglesz :D

**Comment by andris155** [comment]
Videó nélkül ezzel nem tudok mit kezdeni.
