### ISSUE TITLE
Telek bugg

### ISSUE THREAD

**Issue by ggbani2** [andris155/TheOld-Crafters#2187]
több telkem /p merge-vel össze lett kapcsolva és ez által elvüleg 1 p h tp kéne legyen,de ez helyett /p h:2
/p h:3 és mind a kettő ugyan ott van ._. (hogy ez bugg-e nem tudom biztosan 😞  )

**Comment by andris155** [comment]
gondolom a telek ID miatt külön kezeli a rendszer.
