### ISSUE TITLE
Telekszám limit túllépése

### ISSUE THREAD

**Issue by Huntermaster0** [andris155/TheOld-Crafters#2188]
Mivel valamennyire spamelhetőek a parancsok (maximum 8 db/10 másodperc), így külön a /p auto is spamelhető. Viszont a szerver a telekfoglalást nem dolgozza fel olyan gyorsan, mint ahogy Macro segítségével (vagy ha hardcore módszereket választunk akkor simán spamelve (így nekem nem sikerült csak 5 telek, de így is teszteltem)) le tudjuk foglalni a telkeket. Ha a Macroval csináltam, akkor a Tag rangból maximálisan kihozható 10 telket sikerült elérni (alapból 3 telke lehet egy Tagnak). Persze itt nem a Macroval van a gond, hanem a telek pluginnal.
![2018-08-10_02 58 23](https://user-images.githubusercontent.com/42183895/43934931-e21442da-9c51-11e8-8305-29fe8f4f55dd.png)

**Comment by andris155** [comment]
Ez csalásnak számít, amiért kitiltás jár.

**Comment by andris155** [comment]
Készíts róla videót esetleg. Akkor adok OCD-t is. :)

**Comment by Huntermaster0** [comment]
Esetleg így?

https://imgur.com/4dxJaJZ

**Comment by andris155** [comment]
köszi
