### ISSUE TITLE
Minemarket, /info és Paintball elírások

### ISSUE THREAD

**Issue by Huntermaster0** [andris155/TheOld-Crafters#2189]
-A szerveren a /info tagjogok -nál 3 telek van írva, és 4 telek összevonása egybe. Mivel csak 3 telke lehet egy Tagnak, így nem tud négyet összevonni.

-A minemarketben a Savsziget Bányapók spawnernél Survival szerver van odaírva.
![screenshot_20180810-025510_chrome](https://user-images.githubusercontent.com/42183895/43933301-296d73f8-9c49-11e8-9d8b-4a365b815fd7.jpg)

**Comment by Huntermaster0** [comment]
Valamint a Paintball fordításban 1 elírást és 1 pont hibát vettem észre (tudom a pont szinte semmi, de ha már ott az elírás is, gondoltam jelentem ezt is).

-A pont hiba a /pb leave parancs 2. soeában van, dupla pont van ott.

-Az elírás a /pb toggle parancsnál van, üzenek van odaírva üzenetek helyett.
![2018-08-10_04 04 07](https://user-images.githubusercontent.com/42183895/43934775-3d747d3a-9c51-11e8-894d-22c59411fce6.png)

**Comment by andris155** [comment]
Javítva.
508 OCD
