### ISSUE TITLE
Hiányzó petkiírások

### ISSUE THREAD

**Issue by Huntermaster0** [andris155/TheOld-Crafters#2190]
-A /warp petparancsok warpon az OCDért vásárolható petek között nincs tábla az alábbi petekhez:
-Óriás Zombi
-[ALPHA]Végzetsárkány
-Csontvázló (csak a sima nincs kint, a Baby verzió kint van)
![2018-08-10_03 38 21](https://user-images.githubusercontent.com/42183895/43934854-88962b1a-9c51-11e8-9eff-633811115bf4.png)

-A viselkedési módoknál a Rajtaütés és az Aggresszív mód nincs kiírva.
![2018-08-10_03 51 05](https://user-images.githubusercontent.com/42183895/43934866-95483312-9c51-11e8-9f3c-499a860efad4.png)

**Comment by andris155** [comment]
Javítva!
Köszönjük a hibajelentést!

**Comment by andris155** [comment]
330 OCD
