### ISSUE TITLE
Run3 automata eventen bugol az első akadály

### ISSUE THREAD

**Issue by falcon0607** [andris155/TheOld-Crafters#2191]
Ha itt leugrunk akkor bugolunk a levegőben és csak a /home parancsal lehet kiszabadulni
![2018-08-10_15 32 42](https://user-images.githubusercontent.com/40804615/43960613-d8f70140-9cb2-11e8-8727-1e0108ad9665.png)

**Comment by MrZero1** [comment]
Javítva.
