### ISSUE TITLE
ChatControl Pro hiba tab hiba

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#2192]
![kep](https://user-images.githubusercontent.com/29709854/43964088-5d9c1580-9cbc-11e8-8c0d-124e981bb832.png)

Nem tudom, direkt van vagy sem, de nem lehet neveket tabozni. Tegnap este még lehetett, akkor tudtam nick nélküli emberek neveit tabozni, most ezt írja ki.

**Comment by andris155** [comment]
https://github.com/kangarko/ChatControl-Pro/issues/884

**Comment by andris155** [comment]
elvileg javítva
