### ISSUE TITLE
Hammer hiba

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#2193]
Szia. A Hammer (kalapács) nem megy (csak admin ranggal/op-val).
Illetve, ha valaki használja (kiüt vele blokkot) Aimbot, Noswing-ként jelez.

![2018-08-12_14 57 02](https://user-images.githubusercontent.com/29709854/44002509-f1c92792-9e43-11e8-8a2d-2830cd249963.png)

Matias próbálja a kalapácsot, de nem megy. 
![2018-08-12_14 55 13](https://user-images.githubusercontent.com/29709854/44002514-0577dae0-9e44-11e8-8470-65232c5f2016.png)
![2018-08-12_14 55 16](https://user-images.githubusercontent.com/29709854/44002515-059168f2-9e44-11e8-8b43-c8e708645ce2.png)

**Comment by andris155** [comment]
Hát nem meglepő módon az anticheat ezzel nem tud mit kezdeni. :D

**Comment by andris155** [comment]
A Noswing a fenét se érdekelné, de a másik elég fontos védelem a nuker hack ellene. Szóval 2 plugin fejlesztő közül valamelyik csak megoldja vagy megmondja, hogy lehetne megoldani ezt.
