### ISSUE TITLE
SuperTrailsPro elírások

### ISSUE THREAD

**Issue by Huntermaster0** [andris155/TheOld-Crafters#2199]
Találtam pár elírást a SuperTrailsPro fordításban.

-Ritkasád van írva Ritkaság helyett
-Elérhető a Eső és Szárny építőben. Az Eső szó elé "az" kell.
![screenshot_20180814-144013_chrome](https://user-images.githubusercontent.com/42183895/44093846-e64b171c-9fd4-11e8-9485-df3c5801c47d.jpg)

-A jelenlegi csíl nem támogatott ezzel a móddal! A csík helyett ,,csíl" van írva.
![screenshot_20180814-144156_chrome](https://user-images.githubusercontent.com/42183895/44094020-5070ead6-9fd5-11e8-92a7-90d6e3409c74.jpg)

-Kattincs van írva Kattints helyett
![screenshot_20180814-144300_chrome](https://user-images.githubusercontent.com/42183895/44094104-8dd90dd6-9fd5-11e8-8a39-bd8d5912ec64.jpg)
![screenshot_20180814-144304_chrome](https://user-images.githubusercontent.com/42183895/44094112-93f9937a-9fd5-11e8-98d2-58f18d6aaa2b.jpg)

-Komfetti van írva Konfetti helyett
![screenshot_20180814-152225_chrome](https://user-images.githubusercontent.com/42183895/44094246-f3618822-9fd5-11e8-911b-fcedec0783c3.jpg)

-Anygyal van írva Angyal helyett
![screenshot_20180814-144530_chrome](https://user-images.githubusercontent.com/42183895/44094290-0f9045a6-9fd6-11e8-8aa5-5f36aecd106e.jpg)

-A Szivárvány előtt spcciális karakter van (vagy mi az) és nincs aposztróf között
![screenshot_20180814-144619_chrome](https://user-images.githubusercontent.com/42183895/44094562-caabefde-9fd6-11e8-978d-11877819b6ca.jpg)

-főmenö van írva főmenü helyett
![screenshot_20180814-144645_chrome](https://user-images.githubusercontent.com/42183895/44094597-e15e32a0-9fd6-11e8-9c9a-6f38c41f63c8.jpg)

-csíkod van írva csíkot helyett
![screenshot_20180814-153105_chrome](https://user-images.githubusercontent.com/42183895/44094680-21909b60-9fd7-11e8-8726-bc7ad1a4136e.jpg)

**Comment by andris155** [comment]
Nyithatnál volna pull-t. Neked is gyorsabb lett volna a képek helyett.

**Comment by Huntermaster0** [comment]
Bocsi :D. Ez nem jutott eszembe, ha legközelebb lesz ilyen, úgy csinálom.

**Comment by andris155** [comment]
204 OCD
