### ISSUE TITLE
FB, Socialspy

### ISSUE THREAD

**Issue by MrZeroTOC** [andris155/TheOld-Crafters#22]
Szia. A facebook oldalon téged keres Joó Alexander!
Illetve, a socialspy eddig jelezte azt, hogyha egy staff (kivéve admin) írt valamit /bc-ben, most viszont nem látom melyik staff hírdette az eventet. (példa)

Üdv, MrZero

**Comment by andris155** [comment]
Üdv!
Lehet ki van kapcsolva, de Adminnak eddig se lehetett látni más Adminét, vagy Tulajét.

**Comment by MrZeroTOC** [comment]
Adminet nem is de segito hirdeteset sem latom:/
