### ISSUE TITLE
PvP aréna hibák

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#220]
PvP arénában nincs PvPManager plugin, harc közben ki lehet lépni a szerverről halál nélkül. A másik, hogy a warpon letiltja a fly-t a commandblock, de utána vissza lehet kapcsolni, és bent is repülni.

**Comment by andris155** [comment]
nincs megoldás

**Comment by UDPSendToFailed** [comment]
De van, /rg flag pvpspawn blocked-cmds /fly, /fly on, /pvp off, /god, /god on

**Comment by andris155** [comment]
Az tiltva lett, de a pvpkezelőt nem lehet oda.
