### ISSUE TITLE
Vanilla Additions NoCheatPlus kompatibilitási hibák

### ISSUE THREAD

**Issue by andris155** [andris155/TheOld-Crafters#2200]
Ezek nem működnek:
- Minden Hammer, Double Axe, és Sickle és a Smaragd balta

**Comment by andris155** [comment]
Az új verzió elvileg javítaná a hibákat, de ehelyett egy csomó hibát ír csak. Sajnos a fejlesztő még nem válaszolt ezekre a hibákra.

**Comment by skrisz0101** [comment]
Valami hír erről? :/

**Comment by andris155** [comment]
A hibák azóta is javítatlanul állnak. Fogalmam sincs mi van a plugin fejlesztőjével.

**Comment by TamasB14** [comment]
Sajnos... se a sarló, se a kalapács nem működik :( Most már nincs többé kommunista uralom

**Comment by andris155** [comment]
Javítva
