### ISSUE TITLE
Shulkerdoboz a shulkerdobozban

### ISSUE THREAD

**Issue by KyourakuShunsui** [andris155/TheOld-Crafters#2201]
A csőrendszerrel lehetőség van a shulkerdobozt egy másik shulkerdobozba rakni. Beleteszünk egy shulkerdobozt a bemeneti sima ládába, aktiváljuk az átvitelt, és a kimeneti ládába ami nem sima láda hanem egy shulkerdoboz megérkezik a shulkerdoboz. Ezt megint bele lehet helyezni egy újabb shulkerdobozba.
Játékosnevem: Wolverine

**Comment by KyourakuShunsui** [comment]
https://youtu.be/FE9rKcrAEZI

**Comment by andris155** [comment]
A fejlesztő nem javította a hibát. Hiába írtam meg neki. Sajnos nem tudok ezzel mit tenni.

**Comment by andris155** [comment]
508 OCD

**Comment by andris155** [comment]
Nem találtam KyourakuShunsui nevet a MineMarket-en.

**Comment by KyourakuShunsui** [comment]
Minemarket nevem: Wolverine

**Comment by andris155** [comment]
Az 1.13-as build-ban elvileg már javítva lett. Az 1.12.2 már nem támogatott verzió.

**Comment by andris155** [comment]
Szóval majd az 1.13-as frissítéssel lesz javítva.
