### ISSUE TITLE
Addolás (Duplikálás)

### ISSUE THREAD

**Issue by Huntermaster0** [andris155/TheOld-Crafters#2204]
Egy 1 perces időtartammal lehet duplikálni akármit.
Pontokba szedve:
-Kellékek: Shulker a legegyszerűbb; de akármi jó lehet. Valamint páncélállvány, és gamemode 1 jog (Old)

Módszer: Lerakjuk a páncélállványt, kézbe a cuccot. Átváltunk /gm 1-be, kiszedjük az állvány kezéből a cuccot, belerakjuk abba amelyikből kiszedtük és a másik állványba(akármennyi állvány lehet, a módszert a végtelenségig lehet csinálni). Visszaváltunk /gm 0-ba, és íjjal szétlőjük az állványokat. Állvány kiesik, cucc kiesik, dupla/tripla vagy akár százszoros cucc.

**Comment by andris155** [comment]
erről videót nem tudsz készíteni?

**Comment by Huntermaster0** [comment]
Készítettem, az a baj, ha imgurra megpróbálom feltenni, feltölti aztán eltűnik

**Comment by andris155** [comment]
YouTube

**Comment by Huntermaster0** [comment]
Este van, ez hogy nem jutott eszembe? xdd

**Comment by Huntermaster0** [comment]
Végül felvettem újra, engedte
https://imgur.com/a/Nv3lgJy

**Comment by Huntermaster0** [comment]
Újrateszteltem, simán úgy is megy, hogy kreatívban rakunk valamit az armorstand kezébe, majd /gms-ben kiütjük.

**Comment by andris155** [comment]
Javítva. Túlélőben később lehet majd módosítani újra a páncélállványt.

**Comment by andris155** [comment]
2032 OCD
