### ISSUE TITLE
Saválló szett Savsziget MineMarket

### ISSUE THREAD

**Issue by andris155** [andris155/TheOld-Crafters#2205]
Diamond Helmet#3R
Diamond Chestplate#3S
Diamond Leggings#3T
Diamond Boots#3U

csgive

**Comment by KingDeadZ** [comment]
Lol... 1x beszélgettem még 1 sráccal hogy lehetne valami saválló ruha ami X perc után tönkremegy... (ez által lett volna craftreceptje)

Nem rossz ötlet! 

UI: Ha water breathing effektet adna a teljes szett, akkor javaslom hogy valamilyen oxigén tároló dolog is legyen a Chestplate hátán.

**Comment by andris155** [comment]
kész
