### ISSUE TITLE
SurvivalGames világ bájital ivás letiltása

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#2206]
Szia. A bájital ivást le kellene tiltani a világba. @poma123  megcsinálta, viszont úgy, hogy az egész világba tiltotta, így az SG-n sem lehet bájitalt inni. (Ha csak így oldható meg, rip)

**Comment by poma123** [comment]
Igen. :c

**Comment by Sheep04** [comment]
(úgy, hogy fogalmam sincs, mi történik)
Esetleg a SurvivalGamest egy másik világba rakni?
Vagy az már terhelné a szervergépet?

**Comment by poma123** [comment]
nem flag tiltja, blacklist.txt-ben az interakció van letiltva, mivel sima bájital ivásra nincs is flag.

**Comment by andris155** [comment]
Arra én se tudok megoldást. :/

**Comment by poma123** [comment]
Megoldva mégis, írtam egy bájital ivást letiltó flag-et a worldguard-hoz. SG arénákon engedélyezve a bájital ivás, és tesztelve.
