### ISSUE TITLE
Zuhanás bug

### ISSUE THREAD

**Issue by Huntermaster0** [andris155/TheOld-Crafters#2207]
Ha az endben Survival móddal fly közben nyomunk egy dupla space-t, úgy, hogy semmi nincs alattunk, akkor ledob a -2-es magasságra. Ha a god mód engedélyezve van, akkor nyilván nem halunk meg, ha zuhanunk, de akinek ez éppen nincs bekapcsolva, az elveszheti a cuccát.

**Comment by andris155** [comment]
Milyen interneted van otthon és mennyire stabil?

**Comment by Huntermaster0** [comment]
Annyira nem stabil, van, amikor belassul, de odahívtam mást is, és ő is ezt tapasztalta. Plusz teszteltem, ez csak Survival módban van így, ha kreatívban vagyok nem dob le.

**Comment by KingDeadZ** [comment]
Aláírom, amikor savoztam és az elytrával felfedeztem, folyamatosan ez volt...

**Comment by andris155** [comment]
Kellene erről videó.

**Comment by Huntermaster0** [comment]
https://imgur.com/a/C97xhap

**Comment by Huntermaster0** [comment]
Illetve egy másik, ehhez kapcsolódó bug, repülés majd dupla space után van, hogy zuhanás közben feldob.
https://imgur.com/a/z4zVWOf

**Comment by andris155** [comment]
Az 1.13-ban ez eléggé megváltozik. Kérlek majd akkor nyisd újra ha még él a hiba.

**Comment by andris155** [comment]
508 OCD
