### ISSUE TITLE
Vanish érzékelése

### ISSUE THREAD

**Issue by Huntermaster0** [andris155/TheOld-Crafters#2208]
Vanish után
1.-a staffoknak lehet írni /t és tab egészen a nevéig, vagy csak simán utánaírjuk a nevét.

2.-nem ad hozzá -1 értéket a TAB billentyű lenyomásával megjeleníthető Összes játékos: <szám> -hoz. Ide persze az is jön, hogy ebben az RPG és a HardcoreX szerveren levő staffok is benne vannak, de ha valaki egy staff vanishezése előtt és után is nézi a tabot, akkor az láthatja, hogy a Survival/Savsziget számláló változik, de az Összes játékos számláló nem.

3.-A /stats <név> parancsnál ugye az online játékosok rangját is kiírja a neve elé, így amelyik staff vanish közben online, annak is kijelzi a neve előtti rangját a /stats használatával.

4.-/pettrade <név> engedi a trade felkérést a vanishben lévő staffnak is

5.-/pvps <név> megmutatja a vanishben lévő staff pvp állapotát is

**Comment by andris155** [comment]
Soha nem fogja az összes plugin ezt támogatni. Amennyire lehet elvan rejtve.
