### ISSUE TITLE
Kreatívos páncél átvitele survival-ba

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#221]
Ez igazából nem is bug, mert használhatatlan a páncél, de érdekes, hogy az adagoló kidobja / a tölcsér felveszi, azt lehet tiltani?

https://www.youtube.com/watch?v=vUSEqYkBggs&feature=youtu.be

**Comment by andris155** [comment]
A hopper eventet lehet cancelozni, de az anélkül is laggos, szóval azt nem akarom ezzel rontani.
A dispensert lehetne, de arra nem mostanában lehet időm.

**Comment by andris155** [comment]
https://github.com/andris155/TheOld-Crafters/issues/185
