### ISSUE TITLE
/rg list

### ISSUE THREAD

**Issue by Treuce** [andris155/TheOld-Crafters#222]
Szerintem hasznos lenne ha letudnánk kérni hogy milyen RG védések vannak a nevünkön vagy mikhez vagyunk hozzáadva.

**Comment by andris155** [comment]
Ha megfejted milyen perm kell hozzá, akkor be is állítom :D

**Comment by Treuce** [comment]
worldguard.region.list.own.*	Be able to use /rg list and have it show one own’s regions.
Ha minden igaz ennek kell lennie a jónak. a sima worldguard.region.list minden létrehozottat kilistázna de azzal is meglehetne csinálni de ez elméletben egyszerűbb.

**Comment by andris155** [comment]
Ez a jog már megvan adva.

**Comment by Treuce** [comment]
Akkor bugos. Zárok.
