### ISSUE TITLE
PvPManager

### ISSUE THREAD

**Issue by Treuce** [andris155/TheOld-Crafters#223]
Hali, Miért nincs a survival szerveren pvpmanager jelenleg?

**Comment by andris155** [comment]
Csak a pvparénában nincs, mert abban világban le van tiltva.

**Comment by Treuce** [comment]
Csak az a baj hogy kitudnak lépni pvp közben most hogy abban a világban van az aréna.

**Comment by andris155** [comment]
Csak a pvparénára nem akarok világot létrehozni.
