### ISSUE TITLE
Savsziget - Lottó elírás

### ISSUE THREAD

**Issue by Konc0321** [andris155/TheOld-Crafters#2236]
Ha letiltom a ,,Globális vásárlási üzenet kapcsolása"-t, akkor a következő - nyelvtanilag értelmetlen - szöveg fog megjelenni:
![2018-08-20_12 12 39](https://user-images.githubusercontent.com/38163260/44334727-a9651080-a472-11e8-9db9-7dd59c8960f4.png)

Helyesen: Többé nem fogsz kapni vásárlási értesítéseket amikor valaki szelvényt vásárol!

**Comment by andris155** [comment]
Javítva!
Köszönjük a hibajelentést!
