### ISSUE TITLE
Gamebox - barrier

### ISSUE THREAD

**Issue by Konc0321** [andris155/TheOld-Crafters#2237]
Ha megnyitom a gameboxot és elindítok egy játékot, majd kilépek az "esc" billentyűvel a hotbarom tartalma megmarad. Köztük a barrier is, amit viszont nem lehet letenni, de ott van. Az inventorym tartalmát visszatudom szerezni úgy, ha megnyitom a gameboxot, de nem indítok el egy játékot sem, majd megnyomom az "esc"-et.  Ha azokat a barriereket elrakom egy ládába/enderládába az inventorym tartalma visszaszerzése után ottmarad az akadály blokk az előbb említett ládába/enderládába
Videó:
https://www.youtube.com/watch?v=2afGcHguN_Q&feature=youtu.be

**Comment by andris155** [comment]
Windows + G legközelebb. Az sokkal egyszerűbb és ingyenes.

**Comment by andris155** [comment]
Javítva
