### ISSUE TITLE
Világhatár

### ISSUE THREAD

**Issue by TheChaosLord** [andris155/TheOld-Crafters#224]
Nem működik rendesen.
</img>http://i.imgur.com/Nh0VFD1.png<img>
(A csoportba kirakhatod a képet nyugodtan.)

**Comment by andris155** [comment]
Bővebb információ esetleg?

**Comment by TheChaosLord** [comment]
Át lehet rajta jutni. Nem jelent akadályt.

**Comment by andris155** [comment]
Nekünk nem sikerült csak úgy átmenni rajta.
