### ISSUE TITLE
Enderchest bug

### ISSUE THREAD

**Issue by KingDeadZ** [andris155/TheOld-Crafters#2241]
https://youtu.be/cGwVpM2RCeI

Nem tudom kinyitni a ládát ha shiftelve vagyok, mert sima enderchestként érzékeli, de viszont ha nem shiftelve nyitnám ki akkor engedi. 

(A telekhez nem voltam hozzádva)

**Comment by KingDeadZ** [comment]
Hogyan tudom igazolni a hibát?

**Comment by andris155** [comment]
Akár lehetett volna direkt is így. De a fejlesztő igazolta, hogy ez hiba.

**Comment by andris155** [comment]
Remélhetőleg javítja majd a fejlesztő.
https://github.com/utarwyn/EnderContainers/issues/13
