### ISSUE TITLE
Duels fordítás

### ISSUE THREAD

**Issue by Huntermaster0** [andris155/TheOld-Crafters#2242]
Lefordítottam a Survival szerveren lévő Duels plugin lang.yml fájlját. Mivel itt még nem volt kint fájl, így Spigotról töltöttem le, viszont nem tudom Pull requestbe lehet-e így rakni (ahogy láttam nem).

https://pastebin.com/zwb86aYS

**Comment by andris155** [comment]
Köszönjük!

**Comment by andris155** [comment]
1016 OCD

**Comment by Huntermaster0** [comment]
Az ocd Huntermaster névre lett küldve? Mert ugyanannyi van, mint amennyi tegnap volt.

**Comment by andris155** [comment]
Arra

**Comment by Huntermaster0** [comment]
Elírtam az egyik szót,+volt 2 dolog, ami magyarul nem fért ki a várakozó táblájára, így azt rövidítettem. Elvileg így már ki fog férni.
https://pastebin.com/XmP1DR7K
