### ISSUE TITLE
Gamebox bug

### ISSUE THREAD

**Issue by ZsombGuy16** [andris155/TheOld-Crafters#2243]
Gameboxban afkoltam kb. 10 percet. Miután vissza jöttem, a szigetemen semmilyen eldobott itemet nem tudtam felvenni, ha én, ha más dobta el. Egy felé képpen tudom csak felvenni az itemeket, ha előtte /gb-zek, és utána kilépek belőle, akkor az eldobott item hozzám kerül. Ez csak Sav Szigeten van így. Próbálkoztam a gépem újraindításával, de az sem használt.
Üdv: ZsombGuy16

**Comment by ZsombGuy16** [comment]
Lenne rá valamilyen megoldás? Mert elég idegesítő, hogy amikor valamilyen cuccot fel akarok szedni, meg kell nyitni a Gameboxot. 
Előre is köszi: ZsombGuy16

**Comment by andris155** [comment]
Elvileg javítva.
