### ISSUE TITLE
MobArena bug

### ISSUE THREAD

**Issue by Huntermaster0** [andris155/TheOld-Crafters#2245]
A Mobarénában a kiválasztott kitek itemjeinek helyeit lehet módosítani az inventoryban (pl. tudom a kardot az 1. Slotról a 2. slotra tenni), így engedi, hogy csak rákattintsunk a tárgyra, és akkor épp nem az inventorynkban van. Ha használjuk a LiteLoader ExtendedHotbar modját, bemegyünk a Mobarénába, kiválasztunk egy kitet és megnyomjuk az R betűt, majd beírjuk, hogy /ma l ,akkor az 1. slotban lévő item a hotbar 1. slotjára kerül, és így kihozható a Mobarénából. Erre van egy másik módszer is, csak az a LiteLoader Macro modjával. Rákötünk egy scriptet (pl.   $${WAIT(4000ms);ECHO(/ma l);}$$    ) az egyik gombra, majd miután csatlakoztunk a mobarénába és kiválasztottuk a kitet, csak megnyomjuk a gombot, megnyitjuk az inventorynkat, gyorsan rányomunk az egyik itemre (itt mindegy melyikre), és amint letelt a script WAIT() ideje, automatikusan kilép a Mobarénából, és a cucc amire kattintottunk, a hotbarunk 1. slotjában lesz. Teszteltem a bújócska, az sg és a Paintball várakozóban is, ott belépéskor nem lehet módosítani az inventoryt.

**Comment by andris155** [comment]
Nem támogatjuk a Macro módot és ez komoly csalásnak bizonyul.
