### ISSUE TITLE
A minemarketben a régi andris fej látszik

### ISSUE THREAD

**Issue by falcon0607** [andris155/TheOld-Crafters#2248]
![kepernyofelvetel 82](https://user-images.githubusercontent.com/40804615/44631950-8e633680-a973-11e8-8647-d69c2e58ac34.png)

**Comment by andris155** [comment]
Frissíts majd Windows 10-re. A Windows 8 egy borzalom és ezt infósként mondom.  https://www.microsoft.com/hu-hu/software-download/windows10

**Comment by andris155** [comment]
Frissítettem a fej skint. Köszönjük a jelentést.
