### ISSUE TITLE
Cookie Clicker

### ISSUE THREAD

**Issue by IcyAlex** [andris155/TheOld-Crafters#2249]
Tegnap(2018.08.27.) a Cookie Clicker-rel játszottam(/gb-n), és mikor ma(2018.08.28.) megnyitottam újra, amit játszottam Tegnap az eltűnt onnan.

**Comment by KingDeadZ** [comment]
Velem is volt ilyen. Eltűnt minden upgradem amit csak vásároltam.

**Comment by andris155** [comment]
Nem tudom mitől lehet. Remélhetőleg a fejlesztő javítja majd, ha ez tényleg hiba.
