### ISSUE TITLE
Petrelease probléma

### ISSUE THREAD

**Issue by asdlol911** [andris155/TheOld-Crafters#225]
Üdv!

Sokan jelentették már a szerveren, hogy a befogás előtt passzív mobok (pl tyúk, tehén, falusi) elengedés után eltűnik, mintha a föld nyelte volna el.

~~asdlol911

**Comment by Kronox12** [comment]
Csak a falusi tűnik el.

**Comment by andris155** [comment]
De ez hiba nem?
Tudod jelenteni a fejlesztőnek?

**Comment by Kronox12** [comment]
Jelentve.

**Comment by andris155** [comment]
Köszi. :)
