### ISSUE TITLE
Savsziget hiba: a gombák elnevezése

### ISSUE THREAD

**Issue by Icecroft** [andris155/TheOld-Crafters#2250]
Sziasztok, a savszigeten jelenleg mindkét fajta gomba nevét "gomba"-ra magyarosították.
250-es Alkímia szinten lehetne piros gombából magasugrás potit főzni, de ez nem működik.
Az alkímia help "piros gomba"-t kér. 
![2018-08-28_22 48 54](https://user-images.githubusercontent.com/19332825/44750418-978c0900-ab15-11e8-88b2-fe9e66d500e5.png)

Az angol helpben is ez van:
Red Mushroom (Potion of Leaping)
Tehát ott is megkülönböztetik a két gombát,

**Comment by Icecroft** [comment]
Leellenőriztem a survin is, ott sem megy a magasugrás poti főzése piros gombából. Ott is ugyanaz a neve a két gombának. Korábban ott működött, amíg az MCMMO nem volt magyarítva.

**Comment by KingDeadZ** [comment]
Ezért nem kell lemagyarosítani minden alap minecraftos tárgyat. :P Úgy tökéletesen működik minden,aki angolul szereti játszani a minecraftot mint pl én, meg az is aki magyarul szereti játszani a minecraftot.

**Comment by andris155** [comment]
Valószínűleg a hopper optimalizáció miatt nem működik. De enélkül az optimalizáció nélkül a szerver működésképtelen. Jobb processzorra pedig nincs lehetőségünk.
