### ISSUE TITLE
Hideandseek

### ISSUE THREAD

**Issue by KingDeadZ** [andris155/TheOld-Crafters#2251]
Amikor egy arénába belépünk, és játszunk egy ideig (totál random meddig) random becrashel a minecraft.

Mások is jelezték, hogy becrashel a minecraft tök random amikor bújócskáznak, mint ahogy nekem is.

**Comment by andris155** [comment]
Kérlek küld el a crash reportot. Illetve, hogy milyen verzió és milyen launcher.

**Comment by andris155** [comment]
A .minecraft mappában a crash-reports mappában van.

**Comment by KingDeadZ** [comment]
[crash-2018-07-14_14.10.35-client.txt](https://github.com/andris155/TheOld-Crafters/files/2335967/crash-2018-07-14_14.10.35-client.txt)

(Ez nem tudom, hogy az-e de a játékosok alapján annak ítélem, hogy ez még a HNS  nyitása utáni crashem, megpróbálom másoktól is elkérni a crashreportot.)

**Comment by KingDeadZ** [comment]
[crash-2018-08-30_14.08.24-client.txt](https://github.com/andris155/TheOld-Crafters/files/2336077/crash-2018-08-30_14.08.24-client.txt)

Friss crash report :D 

1.12.2 - SkLauncher

**Comment by andris155** [comment]
Kérlek teszt le modok nélkül. Csak optifine-al maximum.

**Comment by andris155** [comment]
Sajnos a plugin nincs 1.13.1-re így jelenleg nem aktuális ez a hiba.
