### ISSUE TITLE
Telek látogatás

### ISSUE THREAD

**Issue by SaltyUmbrella** [andris155/TheOld-Crafters#2256]
A /warp telkek-nél van egy segítő tábla, amelyen ez áll: "/plot visit [név]"
nos a gond az, hogy ehhez nincs jogom/jogunk!
![1](https://user-images.githubusercontent.com/42703224/44877070-1cf0f400-aca3-11e8-90d7-353fb34713c7.png)
![2](https://user-images.githubusercontent.com/42703224/44877102-3003c400-aca3-11e8-9b19-14485bd47167.png)

**Comment by andris155** [comment]
Javítva!
Köszönjük a hibajelentést!
