### ISSUE TITLE
Dinnyeblokk bug - HardcoreX

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#2259]
HardcoreX szerveren nem lehet felmenni a dinnyeblokk tetejére, és ha másik blokkról sétálok át, bebugol, csak warpolással lehet kijutni.

https://youtu.be/8IgPYzlkLps

**Comment by andris155** [comment]
Egyelőre a cheat védelem plugin nem teljesen támogatja az 1.13-as verziót

**Comment by andris155** [comment]
https://github.com/andris155/TheOld-Crafters/issues/2270
