### ISSUE TITLE
Pet étel magyarítás

### ISSUE THREAD

**Issue by Treuce** [andris155/TheOld-Crafters#226]
Az itemek amikkel a peteket kell etetni /petinfo-ban angolul vannak kiírva. Megoldható hogy magyar legyen?

**Comment by Kronox12** [comment]
Ránézek.

**Comment by Kronox12** [comment]
Nem igazán találok rá fordítást a fájlokban :/ de még nézelődök ezzel kapcsolatban.

**Comment by andris155** [comment]
Szerintem a fejlesztőnek kell ezért írni, hogy legyen külön fordítható tárgylista.

**Comment by Kronox12** [comment]
Írva.

**Comment by andris155** [comment]
köszi :)
