### ISSUE TITLE
HardcoreX Börtön kiengedés

### ISSUE THREAD

**Issue by Tapperr** [andris155/TheOld-Crafters#2263]
Mikor letellik a börtönbüntetés vissza dob arra a pontra ahol meghaltam és addig tudok lootolni illetve blockot ütni . Viszont amint megmozdulok rögtön kidob a spawnra. 

- DreaKii

**Comment by poma123** [comment]
Erről tudnál egy videót készíteni?

**Comment by poma123** [comment]
Tesztelve, és nincs jelen ez a hiba.
