### ISSUE TITLE
HardcoreX /addbounty elírás

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#2264]
![kep](https://user-images.githubusercontent.com/16057404/44932465-cdbfc780-ad65-11e8-9bbd-4678108fb1e6.png)

**Comment by UDPSendToFailed** [comment]
+1: Itt szerintem annak kéne lenni, hogy küldetés teljesítve, mert az után írta a szöveget.

![kep](https://user-images.githubusercontent.com/16057404/44933915-352c4600-ad6b-11e8-894d-5bd05f999273.png)

**Comment by poma123** [comment]
Mindkettő javítva.
Köszönjük a hibajelentést!
