### ISSUE TITLE
HardcoreX mob nametag

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#2265]
Alapból így spawnolt, hogy volt rajta, megölni sem lehet, 0 sebzést ír. 

![ezgif-1-4d53545f6e](https://user-images.githubusercontent.com/16057404/44932880-59862380-ad67-11e8-87ea-8994e81e3c7c.gif)

**Comment by poma123** [comment]
Amikor még a plugin nem támogatta megfelelően az 1.13-at, akkor miután meghaltam és letette a hullát, nagyon sok hasonló tehenet spawnolt a hulla helyére. Ezeket megöltem, lehetséges maradt 1-2 hátra.
Nem hinném, hogy alapból spawnolt volna.

**Comment by poma123** [comment]
Ha találsz még ilyet légyszi szólj.
