### ISSUE TITLE
HardcoreX parancs tiltás

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#2266]
A /thirst ignite paranccsal fel tudja magát gyújtani a player, ezzel lehet trollkodni.

/setrequesetmethod a szavazós pluginból valami, az sincs tiltva.

![kep](https://user-images.githubusercontent.com/16057404/44933805-b46d4a00-ad6a-11e8-876e-277d29f75c00.png)

**Comment by poma123** [comment]
Javítva. Köszönjük a hibajelentést!
