### ISSUE TITLE
HardcoreX- Hulla

### ISSUE THREAD

**Issue by KingDeadZ** [andris155/TheOld-Crafters#2268]
2x belenéztem a csapattársam hullájába, majd eltűnt.

(Nem volt elegendő hely az invemben, és jött volna felszedni :p, de hát ha nem engedi akkor bug pls)

Lényeg: 2x belenéztem a hullába majd eltűnt úgy hogy nem vettem ki semmit.

**Comment by poma123** [comment]
Szóval te voltál ott egyedül, és kétszer néztél bele a hullába, aztán eltűnt úgy, hogy nem vettél ki semmit?
Mennyi ideje volt ott a hulla kb.?
Biztos nem volt ott esetleg másvalaki?

**Comment by KingDeadZ** [comment]
Csak én voltam ott, amint meghalt a társam egyből odamentem (akkor tpzett oda pont amikor meghalt xD) Maximum 2-3percig lehetett ott a hulla.

**Comment by poma123** [comment]
Két perc után eltűnik a hulla, szóval pont akkor tűnhetett el.
