### ISSUE TITLE
/ocd egyenleg

### ISSUE THREAD

**Issue by Huntermaster0** [andris155/TheOld-Crafters#2269]
Miután kiírta, hogy a hónap szavazója lettem beírtam, hogy /ocd egyenleg , majd befagyott a szerver pár másodpercre. Egy hibaüzenet jött vissza, miszerint ?cNem érkezett válasz a kiszolgálótól. Pár perc után újra beírtam a parancsot, akkor nem volt lagg, rendesen kiírta az ocd egyenlegemet.

**Comment by andris155** [comment]
Sajnos a MineMarket oldala nem igazán elérhető mostanában néha. Ezzel sajnos mi nem tudunk mit kezdeni.
