### ISSUE TITLE
Zmod bug

### ISSUE THREAD

**Issue by Treuce** [andris155/TheOld-Crafters#227]
Ma leakartam védeni egy beacont, kreában akartam csinálni és amikor kiakartam jelölni a faásó szétütöte a beacont és nem írt ki semmit. ZFisher is látta az esetet.

**Comment by andris155** [comment]
A zmod, az end, nether, és world világban működik csak. Illetve lehet nem tetszett neki a kreás ásó, próbáld meg survivalban.

**Comment by andris155** [comment]
Nem tudom javítani az async miatt megvan határozva mennyiszer futhat le a kijelölés event egy adott időn belül. Azért kell ez, hogy ne fogyasszon feleslegesen sok cpu-t, legközelebb inkább Survivalban jelöl ki a dolgokat a zmodhoz.
