### ISSUE TITLE
1.13.1 Cheat védelem

### ISSUE THREAD

**Issue by andris155** [andris155/TheOld-Crafters#2270]
Egyelőre a HardcoreX csalás védelme nem teljesen támogatja az 1.13-as verziót.
Ismert hibák:
- Az úszás nem igazán működik.
- Néhány blokkra nem lehet rámenni, vagy felugrani.

**Comment by Viktor1969TOC** [comment]
Na meg müködik a Scaffold, Tower hibátlanul AAC nélkül Fast 3x3 módban de ez asszem a savszigeten is megy nem csak HardcoreX-en.

**Comment by andris155** [comment]
Viszonylag jól működik már.
