### ISSUE TITLE
Egy jó ötlet

### ISSUE THREAD

**Issue by buldozer22** [andris155/TheOld-Crafters#2273]
A új szerveren a HardCoreX-en, a hullák mellet azt is meg lehetne csinálni hogy ha kilép az illető a karaktere ott maradjon fekve, mint egy hulla, és ha megtalálja valaki ki tudja rabolni

**Comment by poma123** [comment]
A hulla az hulla, aki lecsatlakozik nem hal meg feltétlenül, plusz nem sok értelme lenne, mivel 2 perc után eltűnik.
