### ISSUE TITLE
"144"

### ISSUE THREAD

**Issue by SaltyUmbrella** [andris155/TheOld-Crafters#2274]
A "144" automata event végén, még ben maradt a Szülinapi Láda, szerintem ez az utolsó a játékban.
![1](https://user-images.githubusercontent.com/42703224/44946102-c2b47800-adf5-11e8-85e7-1cc03ef9e60b.png)
![2](https://user-images.githubusercontent.com/42703224/44946103-c5af6880-adf5-11e8-9864-d2c7e05f8932.png)

**Comment by poma123** [comment]
Javítva. Köszönjük a hibajelentést!
