### ISSUE TITLE
HardcoreX ötlet

### ISSUE THREAD

**Issue by MatiasX** [andris155/TheOld-Crafters#2275]
Sziasztok, nemtudom hogy megvalósítható ötlet, de egy fajta faction (klán) módot rakni a szerverre, amire jó lenne, pl ha valaki pénzért vesz egy klánt az lesz a tulaj, a klán a minél több ember van annál nagyobb területet lehetne levédeni vagy levédést vásárolni, a klánnak lenne egy homeja ami mindenkinek elérhető, a területeket egy fajta klán kasszából lehetne fizetni a klán kasszába pedig mindenki tud beküldeni pénzt de kivenni viszont nem, egyenlőre ennyi amit tudok róla írni ha lesz még akkor azt leírom

**Comment by MrZero1** [comment]
Szia. Egyelőre nincs tervbe ilyesmi. A levédésen lehet beszélgetni viszont: /földek chat.
