### ISSUE TITLE
HardcoreX

### ISSUE THREAD

**Issue by buldozer22** [andris155/TheOld-Crafters#2276]
Az összes kincses térkép egy helyre visz

**Comment by poma123** [comment]
Szerintem sincs ilyen jellegű hiba.

**Comment by KingDeadZ** [comment]
![2018-09-04_15 34 58](https://user-images.githubusercontent.com/38157910/45035246-d3fdbe80-b059-11e8-804a-26fde6420ac4.png)
ugyan az? nem :p
