### ISSUE TITLE
Pet az Aukción

### ISSUE THREAD

**Issue by IcyAlex** [andris155/TheOld-Crafters#2277]
Sziasztok!
Arra gondoltam lehetne /ah-ra feltenni az eladni kívánt petet. (pl.:/petah [ár])
/ah-n kiírja a pet nevét(a valódi nevét nem azt amire ellett nevezve).

Üdvözlettel: IcyAlex

**Comment by MrZero1** [comment]
Szia. Van lehetőség egymás között eladni a peteket. /warp petparancsok. /pettrade.
