### ISSUE TITLE
Földek - Javaslat

### ISSUE THREAD

**Issue by KingDeadZ** [andris155/TheOld-Crafters#2278]
A föld chat ki/be kapcsolására nincs valami módszer? :D Nagyon jó lenne :)

**Comment by KingDeadZ** [comment]
Esetleg szövetség/háború opció is közbejátszhatna. :c Szép húzás lenne a fejlesztőtől.

**Comment by poma123** [comment]
A másodikról szerintem egyelőre ne beszéljünk, viszont az első valóra vált, megcsináltam. :D
Szintaktika: /földekchat toggle <Földnév>
Persze működik ékezet nélkül is.
Kilépéskor resetelődik és a plugin leállásakor is.
