### ISSUE TITLE
Music 

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#2279]
![kep](https://user-images.githubusercontent.com/29709854/44949744-38d9ce80-ae38-11e8-96ec-52a9cbd0465a.png)

Szia, a /music gui-ban az utolsó sorban lévő egyik CD-nek nincs neve. Mellékeltem a képet, a bal oldalin van, ami mellette van CD, annak nincs.

Jelentette: Jakalev2006

**Comment by andris155** [comment]
Teljesen mindegy. Ez a plugin már úgy sem lesz sajnos 1.13.1-en.
