### ISSUE TITLE
HardcoreX levédés hiba

### ISSUE THREAD

**Issue by KyourakuShunsui** [andris155/TheOld-Crafters#2282]
A HardcoreX szerveren egy chunk-ot levédve tulajként nem lehet tűzet gyújtani, azon kívül a szabadban viszont lehet, és ezt beállítani a levédés menüjében nem lehet, sem a tagok jogosultságát nem lehet beállítani, csak parancsokkal hozzáadni, vagy eltávolítani.

**Comment by poma123** [comment]
Amint lesz időm, megnézem.

**Comment by poma123** [comment]
Az 1.13.1-re való átálláskor lesz lehetőség ezt javítani. Mivel addig sajnos csak a plugin utolsó 1.13-ra kiadott verziója fut a szerveren, azok frissítések amiben az új hibajavítások vannak már csak az 1.13.1-től működik.

**Comment by andris155** [comment]
Remélhetőleg javította az 1.13.1
