### ISSUE TITLE
Nincs esési kár a kitinszárnynak köszönhetően #2

### ISSUE THREAD

**Issue by Sheep04** [andris155/TheOld-Crafters#2283]
Üdv!
Nemrég 1.12.2-ben leellenőriztem, ott meghaltam kitinszárny használatakor az esés miatt.
Videót nemsokára tölthetek felfele, ha szeretnél hozzá "igazolást".
Sheep04

Update: Még megvizsgáltam két szervert, azok is kijátszhatóak.

**Comment by andris155** [comment]
Jelentett hiba. Az 1.13.1-ben a rengeteg változás miatt valószínűleg meg fog változni ez is. Az 1.12.2-es Savszigeten egyelőre nem tudtam javítani a hibát.
