### ISSUE TITLE
Hulla bug

### ISSUE THREAD

**Issue by Eror32** [andris155/TheOld-Crafters#2284]
Hello! Nemtudom hogy rajtam kívül még ki tapasztalta, de van amikor a hullák eltűnnek.. Szóval arról beszélek, hogy amikor meghalok,utána kb. 1 percre amikor kilootolnának a csapat társaim, már nincs ott a hullám.. Lehetséges hogy nem is "spawnolt le"? Vagy csak nekem tűnt 1 percnek? (pl. az utóbbi eseteben, amikor az "ösvényen" (ha ásóval jobb klikkelünk a fű blockra, akkor azt kapjuk belőle (a nevét nemtudom, de szerintem ez :p) haltam meg.. De akár az is lehet a gond hogy beszorúlt valami módon a falba.. sajnos nemtudom, de elég jó cuccaim vesztek oda e miatt (vagy csak mert szimplán béna voltam :D), de remélem javítva lesz. Ha esetleg nem bug volt csak eltűnt, akkor elnézést kérek, csak ezzel mára már "be telt a pohár" (ha mondhatjuk így).

**Comment by MrZero1** [comment]
Szia. A hulla eltűnésének az ideje 2 perc volt, mától 5 perc lett.

**Comment by poma123** [comment]
Szerintem a 2 perc miatt eltűnt, ahogy Zero írta, mától kezdve 5 percig marad a hulla a helyén. Ha továbbra is tapasztalsz esetleg hibát a hulla lespawnolásával kapcsolatban, ha lehet készíts róla videót.
