### ISSUE TITLE
HardcoreX

### ISSUE THREAD

**Issue by KingDeadZ** [andris155/TheOld-Crafters#2286]
https://youtu.be/4IJ4APwkAqg

Elmentünk a spawnra, amikor visszajöttünk ez fogadott minket. (amik már látszódtak a videóban ládák, azok ki lettek nyitva előtte)

**Comment by andris155** [comment]
1.13.1, illetve melyik optifine ha használtál?

**Comment by KingDeadZ** [comment]
1.13.1, nem használtam optifineot. Sima vanilla 1.13.1

**Comment by KingDeadZ** [comment]
És mindenki tapasztalta a bugot, nem csak én :)

**Comment by andris155** [comment]
1.13-al sem jó?
