### ISSUE TITLE
HardCoreX bug 

### ISSUE THREAD

**Issue by Viktor1969TOC** [andris155/TheOld-Crafters#2287]
Mikor szavazok azt irja kaptam 50$-t (2x lehet szavazni naponta mert 2 link van) De 150$-t ad. Magyarul 100 helyett 300$-t kapunk naponta.  Bizonyitékot leghamarabb holnap birok szerezni ugy hogy lefotozom az egyenlegem szavazok es megint lefotozom

**Comment by andris155** [comment]
Ez lehetetlen.
