### ISSUE TITLE
Shopkeepers hiba

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#2288]
Szia. Szerettem volna lerakni 2 shopkeeperst a beváltó warpra, ám amikor leidéztem, 10-20 darab falusit kaptam, majd amikor megöltem őket, ott volt a shopkeepers, de bugosan, a GUI-t megnyitotta, de törölni nem tudtam, ahogy kiléptem a gui-ból, újabb falusiakat idézett le.

**Comment by andris155** [comment]
Szia
Azóta sem sikerült ezt megoldani?

**Comment by MrZero1** [comment]
Nem bizony.

**Comment by MrZero1** [comment]
Na, szóval az a helyzet, hogy sok sok óra Old karddal való ölés, lávában állás után eltűntek a végtelennek tűnő falusik (amikkel amúgy lehetne trade-elni). :+1:

**Comment by MrZero1** [comment]
Újakat raktam le, most jó.
