### ISSUE TITLE
Telkek hiba

### ISSUE THREAD

**Issue by Kelvin172** [andris155/TheOld-Crafters#2289]
A telkeken nem működik a /plot merge parancs és a /p xy paranccsal semmi nem használ, csak /plot-al

**Comment by andris155** [comment]
mit ír ki a /p-re?

**Comment by KingDeadZ** [comment]
@andris155 egy nem staffnak azt írja, hogy nincs hozzá joga, és forduljon egy adminhoz.

a /p i sem működik rövidítésként a plot infora :p

**Comment by andris155** [comment]
Staffnak mit ír?

**Comment by andris155** [comment]
átírtam /pv-re holnap majd betölt.
