### ISSUE TITLE
MyPet skill-ek 1.12.2 -> 1.13.1

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#2290]
![image](https://user-images.githubusercontent.com/29951969/45111116-67abb980-b144-11e8-8e1b-856be8770d67.png)
fordítás hiányzik itt

**Comment by andris155** [comment]
Magyar nyelvre van állítva a játékod?

**Comment by skrisz0101** [comment]
persze, amúgy hogy tudom igazolni azon túl hogy küldtem képet? O_o

**Comment by andris155** [comment]
Javítva!
Köszönjük a hibajelentést!
