### ISSUE TITLE
Falusi 1.13.1

### ISSUE THREAD

**Issue by SaltyUmbrella** [andris155/TheOld-Crafters#2291]
Nem tudom ez így is lett betervezve, de a falusiakkal nem tudok "tradelni".
![nevtelen](https://user-images.githubusercontent.com/42703224/45111224-b9ecda80-b144-11e8-80e5-67044296c8f1.png)
Ezt a hibaüzenetet írja ki minden alkalommal, mikor próbálkoznék jobb klikkel.

**Comment by csuvi11** [comment]
azzal nem is tudsz a többivel lehet

**Comment by poma123** [comment]
Javítva. Újraindítás után lép érvénybe.
