### ISSUE TITLE
Új levédési rendszer- Survival

### ISSUE THREAD

**Issue by csuvi11** [andris155/TheOld-Crafters#2292]
A levédési rendszert én ajánlottam, és úgy gondolom, hogy az óránkénti 100 block +, az sok. Ugyanis a telek sokkal könnyebben testreszabható és a játékosnak nem muszáj arányosan haladnia mind a 4 irányba, így nagyon nagy sávokat is le lehet védeni. Több szerveren is ahol láttam ezt a plugint, belépésnél egy könyvet kaptunk automatikusan, ami egy egyszerű és könnyen érthető videóhoz vezetett egy linken keresztül a youtube-ra, ahol az összes lehetőséget az új pluginnal kapcsolatban megtudunk. Ezt ajánlom nektek is, akár egy saját szerver chanellre is mehet így a nézettség is jön + nagy segítség ugyanis az alkalmazását is látjuk és nem csak a commandokat a táblákon ingame. :)

**Comment by andris155** [comment]
Mennyi legyen akkor óránként?

**Comment by csuvi11** [comment]
És a videós linkes dologgal kapcsolatban láttam hogy pl amikor lerakom a chestet, alapból csinál, talán egy chunk-nyi területet és akkor kiírja linkben a chatbe hogy nézd meg ezt a videót, vagy ehhez hasonlót.

**Comment by andris155** [comment]
Hát percek alapján is adja a blokkokat, ha jól tudom. Illetve kilépésnél nyilván nem vesznek ezek el.

**Comment by andris155** [comment]
Sajnos nincs olyan lehetőség, hogy rangonként változtatható legyen a blokkos része.
