### ISSUE TITLE
Egy parancshoz több plugin parancs tartozik

### ISSUE THREAD

**Issue by SaltyUmbrella** [andris155/TheOld-Crafters#2293]
Ezzel a hibaüzenettel az elmúlt 10 percben legalább háromszor kidobott a játék: beszürkül a képernyő, majd kiírja miután kidobott a játék. 
![nevtelen](https://user-images.githubusercontent.com/42703224/45112869-2a95f600-b149-11e8-8970-ff54d6ce8f06.png)
A szám az szokott változni, volt más -110 is pl.

**Comment by andris155** [comment]
Most működik?

**Comment by SaltyUmbrella** [comment]
igen, most már működik

**Comment by andris155** [comment]
Szuper, köszi.
