### ISSUE TITLE
Addolható páncélállvány

### ISSUE THREAD

**Issue by Huntermaster0** [andris155/TheOld-Crafters#2294]

**Comment by andris155** [comment]
Folyamatban van a javítás. A szerver log-ban egy szép error is van erről. Szóval ha nincs fent staff is tudjuk ellenőrizni ki csal ezzel.

**Comment by andris155** [comment]
Most is működik a páncélállvány dolog? Esetleg videót tudsz róla készíteni?

**Comment by Huntermaster0** [comment]
Most nem működik, mivel tiltva lett a letétel.

**Comment by andris155** [comment]
kellene ezekről videó
