### ISSUE TITLE
Oldmúzeum

### ISSUE THREAD

**Issue by SaltyUmbrella** [andris155/TheOld-Crafters#2296]
A /warp oldmúzeumban elvesztek a "map artok", nem sürgős meg életbevágó hiba, de mégse így van rendjén.
![1](https://user-images.githubusercontent.com/42703224/45114864-74cda600-b14e-11e8-9234-1b8db9ed5131.png)
![2](https://user-images.githubusercontent.com/42703224/45114867-75fed300-b14e-11e8-9629-8f9d1ae27585.png)

**Comment by andris155** [comment]
Mivel ezt a spigot a fő világ könyvtárában tárolja így ezek törlődtek a világgal együtt. Erről tudunk. Amint lesz időnk pótolva lesznek, vagy átalakításra kerülnek.
