### ISSUE TITLE
/warp bolt

### ISSUE THREAD

**Issue by SaltyUmbrella** [andris155/TheOld-Crafters#2300]
A /warp boltnál hiányoznak a nyomólapok, amik elteleportálnák a játékost.
![nevtelen](https://user-images.githubusercontent.com/42703224/45119033-7b621a80-b15a-11e8-8eea-731cfde7a392.png)

**Comment by MrZero1** [comment]
Csupán csak a tppos parancs nem megy 1.13 verzióban, ezért ütöttem ki őket. Addig ott a 'szuper effekt'.
