### ISSUE TITLE
Építész szerver hiba lista.

### ISSUE THREAD

**Issue by baawoof** [andris155/TheOld-Crafters#2301]
- Iszonyatos fps droppok az új verzió óta ok nélkül, optifine csak rontott rajta.
- /give BaaWoof minecraft:debug_stick játék nem ismeri fel a tárgyat (single-be működik pedig)
- World edit hiba kód: No allowed region (bypass with /wea or disable 'region-restrictions' in config.yml)
- Voxel: You have no current allowed region

**Comment by andris155** [comment]
1. Az optifine mód sokat segít rajta. Ezenkívül meg a gép hardver fejlesztés is sokat segíthet ezen.
2. Ez nem építésre való.
3. Javítva.
4. Javítva.
