### ISSUE TITLE
Survival MCMMO bányászás hiba

### ISSUE THREAD

**Issue by csuvi11** [andris155/TheOld-Crafters#2306]
Itt a videó amin látszik, hogy írja az ender stone-t de xp-t mégse lehet kapni belőle!
https://youtu.be/Yj_FujU7bac

**Comment by andris155** [comment]
Persze, hogy nem megy. Már nincs Ender_Stone. Csak End_Stone.

**Comment by andris155** [comment]
Holnap jó lesz.

**Comment by andris155** [comment]
Javítva!
Köszönjük a hibajelentést!

**Comment by andris155** [comment]
330 OCD
