### ISSUE TITLE
Építész szerver

### ISSUE THREAD

**Issue by baawoof** [andris155/TheOld-Crafters#2307]
WE mask parancs után a brush a jól megszokott hibakódot írja: Outside allowed region (bypass with /wea, or disable 'region-restrictions' in config.yml)

**Comment by baawoof** [comment]
Plugin hiba lehet, ha a mask-ot idvel írom akkor jó, ha beírom a block nevét akkor nem jó.

**Comment by andris155** [comment]
Tudnak a hibáról. Remélhetőleg hamarosan javítják: https://github.com/boy0001/FastAsyncWorldedit/issues/1079
Itt tudod követni a hibajelentést.
