### ISSUE TITLE
Mondom 200$-t ad a vote 100$ helyett HardcoreX-en..

### ISSUE THREAD

**Issue by Viktor1969YO** [andris155/TheOld-Crafters#2308]
![image](https://user-images.githubusercontent.com/38433879/45150201-9d47b580-b1cb-11e8-9984-c9d7ce73295c.png)
![image](https://user-images.githubusercontent.com/38433879/45150225-a8024a80-b1cb-11e8-9d18-90333badc7d5.png)

**Comment by KingDeadZ** [comment]
Hogyha mind a kettő oldalon szavazol egy nap, akkor jutalomban részesülsz ami valószínűleg az a +100$ :)

**Comment by poma123** [comment]
Ez nem hiba, KingDead ismét leírta előttem a frankót, alapból 50$-t ad egy szavazás, és ha szavazol egy nap mindkét helyen kapsz +100$-t.
