### ISSUE TITLE
rg hiba

### ISSUE THREAD

**Issue by Laaszlo** [andris155/TheOld-Crafters#231]
Mikor rg-ben a mob-spawning-ot allow-ra állítom és elenegem pl a petemet ugyanúgy eltűnik, mint amikor deny-re lenne állítva és úgy engedném el.

**Comment by andris155** [comment]
ne írj semmit a mob-spawning után, úgy se megy?

**Comment by Treuce** [comment]
mob-spawning none és úgy mennie kéne szerintem de deny-spawn flag nincs rajta?

**Comment by Laaszlo** [comment]
úgyse megy

**Comment by andris155** [comment]
Mi a védés neve? és a védésen kívül megy?
