### ISSUE TITLE
Új havi top szavazó jutalmak

### ISSUE THREAD

**Issue by andris155** [andris155/TheOld-Crafters#2312]

**Comment by AwesomeFM** [comment]
Ha megoldható, némi toke
Esetleg, valami szett, ami a neve miatt lenne értékes, vagy eszközök akár
Vaagy választhatna egy itemet (Pl. totem, vagy valami ilyesmi) vagy úgy, hogy megadott listából valamit kiválaszthat, vagy bizonyos határokon belül bármit. :x

**Comment by andris155** [comment]
Mennyi token elsőnek és másodiknak?

**Comment by andris155** [comment]
1. 2032 OCD
2. 1016 OCD
