### ISSUE TITLE
OCD-s vásárlási hiba.

### ISSUE THREAD

**Issue by Invikehh** [andris155/TheOld-Crafters#2313]
Rendeltem OCD-ér pár cuccot, és kettő jármű nem jött meg. InvadeR néven történt a vásárlás.

**Comment by poma123** [comment]
A minemarket-es termék lekérése arra a névre történik, amilyen néven lett vásárolva. Ha nevet váltottál minemarket-en is válts nevet.

**Comment by Invikehh** [comment]
Azzal tisztába vagyok. A vásárlás még a név válltás előtt volt... És váltottam nevet minemarketen. Old cuccok megjöttek, a járművek nem.

**Comment by andris155** [comment]
Visszaadtam a járművek árát. A régebbi járművek már nincsenek. Lesznek majd újak.
