### ISSUE TITLE
Segítő tgf - spawn

### ISSUE THREAD

**Issue by SaltyUmbrella** [andris155/TheOld-Crafters#2314]
El lett írva a név.

**Comment by SaltyUmbrella** [comment]
![nevtelen](https://user-images.githubusercontent.com/42703224/45175451-c4bf7200-b20d-11e8-990b-edf075e8a580.png)

**Comment by SaltyUmbrella** [comment]
Meg a "Kezdés" menüpontos is
![nevtelen](https://user-images.githubusercontent.com/42703224/45175494-e15baa00-b20d-11e8-941f-6260b525b716.png)

**Comment by SaltyUmbrella** [comment]
Valamint a Spawn világában lévő Üllők használatakor kiírt hibaüzenet is furcsa kicsit: 
![nevtelen](https://user-images.githubusercontent.com/42703224/45175622-2a136300-b20e-11e8-9151-c516ed0f80fd.png)

**Comment by andris155** [comment]
Nekem jól írja ki a neveket.

**Comment by andris155** [comment]
A WG üzeneteket javítottam.

**Comment by andris155** [comment]
330 OCD
