### ISSUE TITLE
Farm - Spawn

### ISSUE THREAD

**Issue by SaltyUmbrella** [andris155/TheOld-Crafters#2315]
Mondtátok ugye, hogy a /warp farm törlésre került és nem is lesz több, nos a Spawnon még itt vannak a spawnerek meg az állatok.
![nevtelen](https://user-images.githubusercontent.com/42703224/45181700-774c0080-b21f-11e8-9f83-e16a3bc442cf.png)

**Comment by andris155** [comment]
Én úgy tudom ez direkt maradt meg.
