### ISSUE TITLE
Nem lehet felcsatlakozni a survival szerverre

### ISSUE THREAD

**Issue by Sheep04** [andris155/TheOld-Crafters#2317]
Üdv!
Vadonban keresni akartam magamnak helyet, hát rákattintottam a RandomTP táblára.
Azután nem reagált semmit, majd a következőhöz hasonló üzenetet dobott ki:
> A szerveren, amin előzőleg játszottál, leállt.

Feljöttem ismét a szerverre, és a következő látvány fogadott:
![2018-09-07_08 50 47](https://user-images.githubusercontent.com/34780638/45203212-b314b380-b27b-11e8-99a8-24ca9739762b.png)
Én (könnyen lehet, hogy tévesen) arra gyanakodtam, hogy lefagyott az egész szerver (és lehet, hogy miattam).
Remélem végig tudtad olvasni :)
Sheep04

**Comment by andris155** [comment]
Javítva
