### ISSUE TITLE
Nem tudok fellépni a szerverre

### ISSUE THREAD

**Issue by BlueR3x** [andris155/TheOld-Crafters#232]
Alapból nem írja ki h hány ember van fent vagy ilyesmi, csak tölt. De amikor rácsatlakoznék kb. 5percig csak tölt majd ezt írja: Java.net.ConnectException: Connection timed out: no further information:
Mi lehet a probléma? (az újraindítás nem ment, már 3x megtörtént)

UI.: sürgős lenne mert épp megynertem a candyup eventet survivalon.

**Comment by andris155** [comment]
Host hiba
