### ISSUE TITLE
Elírás? 

### ISSUE THREAD

**Issue by Viktor1969TOC** [andris155/TheOld-Crafters#2322]
Ügye mikor szavazunk legalábbis HardcoreX-en kapunk 100+100-at (100 a 2 szavazásért és még 100 mert mind2 oldalon szavaztunk) Nos de a weblap (s1.oldcrafters.net) azt írja hogy "$500" jár a szavazásért. (A kép telefonon készült) 

![screenshot_20180907-170000](https://user-images.githubusercontent.com/32791069/45226620-a154ff80-b2bf-11e8-9836-d4520578e89f.jpg)

**Comment by andris155** [comment]
Kiírtam részletesebben: https://www.oldcrafters.net/szavazas/

**Comment by andris155** [comment]
330 OCD
