### ISSUE TITLE
Survival Water logg hiba

### ISSUE THREAD

**Issue by csuvi11** [andris155/TheOld-Crafters#2323]
Úgy gondolom, hogy az 1.13 as frissítés egyik legnagyobb változtatása hogy olyan dolgokat is tudunk water loggolni amiket eddig nem tudtunk: akármilyen slab, kerítés, rács, stb.. én eddig csak a sima oak kerítéssel próbáltam de sehogy sem lehet water loggolni

**Comment by andris155** [comment]
Azért nagyon nem ez a legnagyobb. De rá fogok nézni a hibára. :D

**Comment by csuvi11** [comment]
Nem csak az eféle tárgyakkar van hiba, szerintem valami nem jó alapból a water loggolással, pl a Kelp( Hínár)-t se tudom lerakni normálisan mert eltünik a víz meg bugol összevissza

**Comment by andris155** [comment]
Valamivel működik, valamivel nem. Szerintem az is befolyásolja ha valami kreatívban lett lerakva.

**Comment by andris155** [comment]
Később biztosan jobban fog működni.
