### ISSUE TITLE
Savsziget - Üvegház kiegészítő újrafordítása OCD-ért

### ISSUE THREAD

**Issue by Konc0321** [andris155/TheOld-Crafters#2324]
![image](https://user-images.githubusercontent.com/38163260/45226329-d90f7780-b2be-11e8-9903-7a62cc132622.png)

Amikor rányomok a /greenhouse parancson belül az üvegre, hogy megnézzem, hogy kell üvegházat készíteni a fent látható üzenet fogad, ami hemzseg a nyelvtani hibáktól, ezért gondoltam kijavítom őket.

Készíts egy dobozt üvegből négy fallal, vasajtóval, tetővel. Rakj le egy tölcsért az ajtó alá  és töltsd meg vizesvödörrel. Nézd meg a különböző éghajlatok üvegházainak leírását, hogy megtudd, mi kell az adott üvegházhoz.

Ennyit tudtam kibogozni ebből, örömmel lefordítom rendesebben, ha megkapom az eredeti, angol szöveget.

**Comment by Viktor1969TOC** [comment]
Google fordító forditotta magyarra? Xd

**Comment by Sheep04** [comment]
Nem, KingDead :3

**Comment by poma123** [comment]
Itt megtalálható az eredeti angol fájl:

https://github.com/andris155/TheOld-Crafters/commit/1c7c7591d7508a27847c678bff3a1bb55a99fc14#diff-2e893faff1e92f14765008cd5f4ff9e9

**Comment by poma123** [comment]
Itt megtalálható az angol változat: https://github.com/andris155/TheOld-Crafters/commit/1c7c7591d7508a27847c678bff3a1bb55a99fc14

**Comment by Viktor1969TOC** [comment]
Szívesen leforditanám lehetenne is csak nem bíróm tesztelni :/

**Comment by Huntermaster0** [comment]
Úgy nem engedte fordítani, ezért letöltöttem Spigotról, és úgy fordítottam le. Remélem így is megfelel.

https://pastebin.com/nirGZqh6

**Comment by andris155** [comment]
508 OCD
