### ISSUE TITLE
hiányzó party fordítás (resi előtt megvolt)

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#2329]
![image](https://user-images.githubusercontent.com/29951969/45230399-ff3a1500-b2c8-11e8-877a-e8a8979ecbdf.png)
![image](https://user-images.githubusercontent.com/29951969/45230416-11b44e80-b2c9-11e8-9ffc-23e090313763.png)
ez mind resi előtt magyar volt, uténa lett angol

**Comment by skrisz0101** [comment]
![image](https://user-images.githubusercontent.com/29951969/45230473-42948380-b2c9-11e8-9182-40d0edfb7125.png)

**Comment by andris155** [comment]
Holnap betölt a jó fordítás.

**Comment by andris155** [comment]
330 OCD
