### ISSUE TITLE
Építész +jog

### ISSUE THREAD

**Issue by Wexthory** [andris155/TheOld-Crafters#233]
Hali na akkor írom ide is. :D 
-/hat 
Bármerről nézzük ennek nincs hátránya, a hasznos része pl ha valaki valami olyat épít ami kész verzióba is sötét lesz akkor nem kell folyton kivilágítani, ha van shaders + /hattal a fejünkön egy fáklya.
- slimeblcok kreába
Jelenleg nem rakhatjuk le, de mindenkinek tiltva van kb, hogy ne építsenek automata mozgó szerkezeteket. Az építész rangnál viszont lehetne engedélyezni, mert dísznek egészen jó tud lenni és nem hiszem, hogy bármelyikőnk építene egy folyton haladó csillagrombolót vagy bármi mást.
- /tp
Ugye negatívum, hogy valaki trollkodni fog vele, de ez a veszély ugyan úgy fent áll a segítő rangnál is. Viszont naponta 2-3 ember mutat valami építményt és mindenki csak néz, hogy mi az, hogy nincs tp jog. A próbaheteseket (főként építészeket) mi is megtudjuk nézni, hogy mit is csinál. Mostanság egyre többet van olyan főként az esti órákba, hogy csak építészek vannak fent és olyankor mi vagyunk a segítők is. Amikor ilyen van elég hasznos tud lenni a tp, hogy ne ott sima chatbe (azért sima, mert a /m-et az ilyen agybaj játékosok nem tudják használni és olvasni) kelljen elmagyarázni neki ezt-azt, hogy rg levédést így kell megnézni stb. Olyannal is találkoztam, hogy én menjek oda segíteni, meg mondjam, hogy mit csináljon, de a tpa-t nem fogadja, mert biztos meg akarom ölni. Ugye ha nincs fent segítő, akkor több perces szerver stb szidás követi és lelép, stb... Erről regényt nem szeretnék írni mert fölösleges. A lényeg, hogy számos alkalommal igen hasznos tud lenni, csak próbáljon meg gm3,tp nélkül tpaval el lenni valaki akinek van tp joga, rájön, hogy mekkora könnyítés.

+mellékes
Jó lenne ha lenne egy hely ahol keretbe lennének olyan blockok amik nincsennek krea invbe, de kóddal kézbe rakhatóak. A keretből görgővel már ki lehet másolni.

**Comment by Kronox12** [comment]
A /hat-hoz: Felesleges shader, már Optifine beállítás is van a Dynamic Lighting-ra. Azaz a fényt adó blokkok itemként is fényt adnak, de ez csak kliens oldali, illetve csak az látja, akinek engedélyezve van ez a funkció.

Specifikus item engedélyezése kreában specifikus rang számára. Úgy emlékszem, hogy ez nem lehetséges, bár régről van az infó, szóval ez nem biztos.

TP felesleges. Már elrendeztük, hogy az építészek kapnak GM3-at, mert segítheti őket a munkájukban. Abban van tp is.

A mellékest pedig kérlek magyarázd el mégegyszer.

**Comment by andris155** [comment]
A tp-t, és nyálkablokkot nem akarom engedélyezni építésztől.
A hat-ot engedélyeztem.

**Comment by Wexthory** [comment]
A tp-t azért hoztam fel, mert a gm3 volt az alap ötlet, de az építész csoportba az volt, hogy az nem lesz, mert ad speedet meg mindenfélét ami fölösleges és csak laggoltat. A specifikusos dolgot legutóbb is beszéltük és szerintem lehet rangonként, mert példának ott a vizes vödör és a láva, de ez már mindegy mert csak a slime kellett volna, de nem.  

A mellékes meg, hogy pl ott van a piros meg barna gombablock is. Ezek ugye kreatív invbe nincsenek, ezeket én kreatívba úgy szoktam átrakni, hogy berakok egy survisat (mert ugye egyedi craftos) képkeretbe, átváltom kreatívra és görgővel kimásolom a keretből így kreatívba is le tudom tenni. Ezt ugye csak olyan blockokkal lehet amik kézbe vehetőek, mert másképp nem rakható a keretbe, pl a minden irányba kérges fát nem lehet, mert az csak we-vel működik. Állítólag vannak egyéb ilyen kézbe vehető de krea invbe nem megtalálható blockok (egyáltalán nem biztos, hogy kézbe vehető sose volt lehetőségem tesztelni), ilyennek mondták a gomba szárat, a gombák aljának a barnás részét stb.

**Comment by andris155** [comment]
A vizes vödör engedett mindenkinek.

**Comment by andris155** [comment]
A láva nyilván nem nagyon lesz. Amik nincsenek krea invbe azt kérjetek. Egyébként gomba blokkok gyengéd érintés csákánnyal kiszedhetőek.
