### ISSUE TITLE
Eldobott tárgyak nevei

### ISSUE THREAD

**Issue by SaltyUmbrella** [andris155/TheOld-Crafters#2330]
Mikor eldobtam régen egy pl: Lucky Kardot, kiírta sárgán a nevét, de most már nem látszódik eldobáskor. (a képen egy Old Csákány szerepel) az a gond ezzel, ha mondjuk játékbeli pénzért vennék bármilyen értékesebb, színezett nevű tárgyat, nem tudok biztosra menni eldobáskor, hogy azt adja-e oda.
![image](https://user-images.githubusercontent.com/42703224/45231254-bd5e9e00-b2cb-11e8-9395-4b23d674e9ed.png)

**Comment by SaltyUmbrella** [comment]
Amúgy van egy szerintem személyes bugom, de nincsen sötét ott, ahol az F3 0-ás fényerőt jelez ki.

**Comment by andris155** [comment]
Nem létező dolog amit írtál. Valószínűleg a kliensedben valami mód írta ki.
