### ISSUE TITLE
Ötlet

### ISSUE THREAD

**Issue by SaltyUmbrella** [andris155/TheOld-Crafters#2331]
Ez nem hibajelentés, ez csak egy szimpla ötlet, az új /warp vadon kinézete szerintem elég egyhangú, a kőnek beállított 2 fajta blokk miatt, WE-vel  vagy szabadkézzel lehetne bele rakni variációt több fajta blokkokból, 1,13 miatt ajánlanám a száraz korallt is.
![image](https://user-images.githubusercontent.com/42703224/45232570-22b48e00-b2d0-11e8-8efb-97544ce834e4.png)

**Comment by andris155** [comment]
Neked, hogy nincsenek fény bugok ott?

**Comment by MrZero1** [comment]
Nekem sincsenek. Majd alakítunk rajta.

**Comment by SaltyUmbrella** [comment]
Andris, ezt írtam.. ugyan ez van a barlangokban is, nincsen sötét. Kitti talán? azt írta erre, hogy első napokban a páyla betöltődése miatt lehetett egy kis bug de még azóta is tart.

**Comment by poma123** [comment]
A WE alapjáraton rengeteg fénybuggal illeszti be a vágólapon lévő dolgokat is, és csak kézzel lehet eltűntetni, de még az sem néha hatásos. A saját javítója pedig semmit nem csinál. Néha megjelennek a fénybugok néha eltűnnek.

**Comment by andris155** [comment]
Kézzel el lehet tüntetni, csak sok idő. :D

**Comment by andris155** [comment]
Remélhetőleg majd javítják.
