### ISSUE TITLE
Nem működnek az mcmmo parancsok (pl.: /bányászat, /favágás)

### ISSUE THREAD

**Issue by falcon0607** [andris155/TheOld-Crafters#2332]
![kepkivagas](https://user-images.githubusercontent.com/40804615/45250567-0a775a00-b336-11e8-9f77-b263d3f1a7af.PNG)

**Comment by SaltyUmbrella** [comment]
a /bányászat helyett /bányászás lett, arról tudok

**Comment by poma123** [comment]
Javítva.
