### ISSUE TITLE
Mcmmo kiírási hiba

### ISSUE THREAD

**Issue by SaltyUmbrella** [andris155/TheOld-Crafters#2333]
![image](https://user-images.githubusercontent.com/42703224/45251158-a5296600-b341-11e8-920d-8c2fadc50172.png)
 Mind a Chatben lévő szöveg, mint a "Scoreboard" eléggé furcsán írja ki a dolgait.

**Comment by SaltyUmbrella** [comment]
![image](https://user-images.githubusercontent.com/42703224/45251174-02bdb280-b342-11e8-8616-ec5a20f199e3.png)
![image](https://user-images.githubusercontent.com/42703224/45251182-0ea97480-b342-11e8-9cae-d61d75845878.png)
 Még pár kép, hogy mire is gondolok, az egész Pluginnal lehet valami, minden kiírása ilyen.

**Comment by SaltyUmbrella** [comment]
![image](https://user-images.githubusercontent.com/42703224/45251194-41536d00-b342-11e8-8eb7-3a2db7f4cd3f.png)

**Comment by falcon0607** [comment]
Ezzel lehet kapcsolatban az én gondom is, ugyan is nem működnek az mcmmo-s parancsok.

**Comment by poma123** [comment]
Javítva.
