### ISSUE TITLE
Survival Levédés Ötlet

### ISSUE THREAD

**Issue by csuvi11** [andris155/TheOld-Crafters#2334]
Azt tudom hogy ranggal változóan nem lehet több / kevesebb blockot levédeni, tehát hogy ez akkor nem megoldható, de ranggal változóan nem lehet több területet levédeni? tehát hogy ne csak 1 et tudjunk levédeni hanem többet is?

**Comment by csuvi11** [comment]
mint pl az oldnak régen 50 lehetett

**Comment by andris155** [comment]
Sajnos nincs ilyen lehetőség.
