### ISSUE TITLE
Survival - MCMMO Fishing

### ISSUE THREAD

**Issue by csuvi11** [andris155/TheOld-Crafters#2335]
A szerveren most nekem van a legnagyobb mcmmo horgaszasi szintem valahol 200 felett. Old horgaszbottal horgaszok vegig es eddig nem kaptam 1 vanilla lootot sem (enchanted konyveket, horgaszbotot, ijjat, es az ujjabb nautilus shellt sem) csak az mcmmost targyakat amik leather armorok meg fa cuccok a jelenlegi szintemen. Tobb mint 350x horgasztam kb es meglepo hogy eddig 1 vanilla cuccot nem kaptam.. Utana neztem, hogy masnak van e ilyen, es ott azt mondtak, hogy a configban engedelyezni kell a vanilla lootot, nem tudom, hogy a szerveren ez szandekosan van e igy, de szerintem eleg zavaro, ugyanis igy semmi lootot nem kapunk es senkinek nem lesz meg a motivacioja, hogy egyaltalan felvigye maxra az mcmmo-t. Emellett nem tudom, hogy lehetseges e, de nagyon orulnek ha a haszontalan krakent kivennenk, de ez mar mellekes :)

**Comment by andris155** [comment]
Beállítva.

**Comment by andris155** [comment]
1016 OCD

**Comment by csuvi11** [comment]
Köszönöm szépen, és már működnie is kéne?
