### ISSUE TITLE
Login - nincs jog az effektekhez

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#2336]
![kep](https://user-images.githubusercontent.com/16057404/45255027-dcb80280-b381-11e8-87ec-42b6edf22ef5.png)

![kep](https://user-images.githubusercontent.com/16057404/45255037-e7729780-b381-11e8-8e6f-8c999d664b3c.png)

**Comment by andris155** [comment]
Javítva!
Köszönjük a hibajelentést!
