### ISSUE TITLE
Új enchantolt aranyalma recept

### ISSUE THREAD

**Issue by Treuce** [andris155/TheOld-Crafters#234]
Ha lehetséges berakni egy új receptet az enchantolt aranyalmára mivel ez 1.9ben ki lett véve minecraftból, de szerintem egy fair dolog lenne ha egy sima aranyalmát kéne körberakni 8 oldgolddal például és így lehetne enchantoltat craftolni.

**Comment by Kronox12** [comment]
Tökéletes ez így ahogy van. Sok baj volt vele

**Comment by andris155** [comment]
Egyetértek Kronoxal.
