### ISSUE TITLE
Telkek - /plot delete, clear, merge és /p parancs

### ISSUE THREAD

**Issue by poma123** [andris155/TheOld-Crafters#2341]
Nem csinál semmit, nem tűnnek el a telken lévő dolgok. Ugyanez igaz a merge-nél is, az utak ott maradnak.

**Comment by poma123** [comment]
És ismét a /p parancsnál a voxelsniper „lép működésbe”

**Comment by andris155** [comment]
Holnap jó lesz a /p. A többiről a PlotSquared fejlesztője tud.
