### ISSUE TITLE
Wither pet

### ISSUE THREAD

**Issue by Treuce** [andris155/TheOld-Crafters#235]
Nem tudom hogy mi történt vele de az 1.8hoz képest lesüllyedt egy sima pet szintjére támadásban mivel pl az endermant se tudja megölni mert nincs távolsági sebzése mint régen vagy nem tudom és szerintem jó lenne ha vissza lehetne állítani azt hogy nagyobb távból is tud támadni..

**Comment by Kronox12** [comment]
1.9/1.10

**Comment by Kronox12** [comment]
De utána járhatok.

**Comment by Treuce** [comment]
Igen, rémlik hogy volt a távolsági sebzéssel valami mert átlőnek blokkokon is de szerintem úgyhogy ez lelett véve csak gyengébb lett a wither de jobb nem.. :/

**Comment by Kronox12** [comment]
Az, hogy egy sima mob szintjére süllyedt, egy eléggé túlzott kijelentés. A Wither még így is a legerőssebb pet. 30-as szinten az egyszerű petek még ki tudnak állni ellene valamilyen szinten, de az esetek 75%-ban (minimum 75%) a Wither nyer.
