### ISSUE TITLE
Survival teknős tojás

### ISSUE THREAD

**Issue by csuvi11** [andris155/TheOld-Crafters#2350]
Nem nagy hiba, de greefelésért és trollkodásért lehet gond, utánanéztem és magát a tojást a rádobott item is sebzi, azaz ki lehet szedni ha rádobsz egy random mennyiségű blockot (vagy lehet hogy adott)
Zeroval tegnap teszteltem es amikor lerakott egy tojast kitudtam szedni ugy hogy a telken nem volt jogom es csak par itemet dobtam a tojasra

**Comment by andris155** [comment]
Ez a greifprevention levédésen sem védett?

**Comment by csuvi11** [comment]
ha zero feljon tesztelem vele

**Comment by andris155** [comment]
https://github.com/andris155/TheOld-Crafters/issues/2429
