### ISSUE TITLE
Nem működik a kar és gomb lerakás kreatívban

### ISSUE THREAD

**Issue by Greg89hun** [andris155/TheOld-Crafters#2352]
Ploton szerettem volna egy rejtett lépcsőt csinálni kreatívban, de nem enged redstone fáklyát, kapcsolót, valamint gombot lerakni.

Most vagy tiltva lett ezeknek is a lerakása, mint régebben a hopperé is, vagy valami van a konfiggal, de eléggé körülményes és idegesítő egyfolytában gm 0 és gm1 közt váltogatni.

**Comment by andris155** [comment]
Egyelőre ez csak túlélő módbz működik. A hibáról tudunk.

**Comment by andris155** [comment]
https://github.com/andris155/TheOld-Crafters/issues/2400
