### ISSUE TITLE
HardcoreX: Herobrine javaslat

### ISSUE THREAD

**Issue by Icecroft** [andris155/TheOld-Crafters#2354]
Ma szembesültem, hogy a HardcoreX-en van herobrine, ami a biztos halál. Így rögtön elvetettem annak a gondolatát, hogy old eszközöket vásároljak, de gondolom más se fog.
Javaslom, hogy herobrine-halál esetén az inventory tartalma ne vesszen el, vagy valami más módon visszakapjuk a dolgainkat. (a börtön büntetés miatt nincs idő visszatérni és a hullánkat kipakolni.)
De azt se bánnám ha herobrine eltűnne :)

**Comment by skrisz0101** [comment]
Öltek már meg herobrinet nem 1x, én magam is túléltem már 1x, és tudod, hardcore :D (amúgy vesznek old cuccokat rendesen)

**Comment by andris155** [comment]
Hardcore szerver. Szerintem poma nem akarna változtatni ezen.
