### ISSUE TITLE
End-ben és nether-ben robban az ágy

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#2355]
![kep](https://user-images.githubusercontent.com/16057404/45453284-b0351b00-b6e0-11e8-803c-16ae7dd5166c.png)

![kep](https://user-images.githubusercontent.com/16057404/45453245-93004c80-b6e0-11e8-98c8-b0d71ff9bfc1.png)

**Comment by andris155** [comment]
Hoppá ez kimaradt. :D

**Comment by andris155** [comment]
Melyik színűt lehet lerakni? Vagy mindet?

**Comment by UDPSendToFailed** [comment]
Az összes színnel működik.

**Comment by Viktor1969TOC** [comment]
Ez az alap MC-ben is benne van szerintem ez nem "Hiba"

**Comment by andris155** [comment]
Javítva.

**Comment by andris155** [comment]
508 OCD
