### ISSUE TITLE
Színes zászlók addolása.

### ISSUE THREAD

**Issue by ColaKing00** [andris155/TheOld-Crafters#2356]
Rá kell tenni a zászlókat a falra kreatívban, majd kiütni a mögötte levő blokkot így a zászló kiesik tárgy formában. Utána már csak át kell menni túlélőbe és felvenni a zászlókat. Videó: https://www.youtube.com/watch?v=nxnJGsVE4aw

**Comment by Huntermaster0** [comment]
Ez benne volt a #2294 ben, csak nem tudtam róla videót készíteni.

**Comment by ColaKing00** [comment]
Én pedig az ágy addolásra jöttem rá sokkal korábban, MatiasX jelentette is elvileg de pontos számot nem tudok. Ráadásul én tudtam videót készíteni a zászlósról szóval... ;)

**Comment by ColaKing00** [comment]
Ezzel mit akarsz mondani?

**Comment by Huntermaster0** [comment]
Cola én ezt csak arra mondtam, hogy minek lett neki másik jelentés xd Amúgy arról nem tehetek, hogy nem tudok róla normális minőségű videót rögzíteni.

**Comment by Huntermaster0** [comment]
Csak annyit akartam ezzel, hogy miért lett másik jelentés.

**Comment by ColaKing00** [comment]
Nem láttam a jelentésedet, és az a jelentés alapvetően nem a zászlósról
hanem a páncélállványról szólt.

Huntermaster0 <notifications@github.com> (időpont: 2018. szept. 13., Cs,
18:44) ezt írta:

**Comment by Huntermaster0** [comment]
Alapból ez igaz, mert mikor reset után feljutottam a szerverre egyből hibát kerestem, és amit találtam azt jelentettem, és a többit már csak melléraktam, a cím meg nem lett módosítva.

**Comment by ColaKing00** [comment]
Igen a cím nem változott. Figyelj én abból a jelentésből annyit láttam hogy
bejelentettél valami páncélállványos bugot, nem írtál leírást se videó se
semmi. Aztán valahol az alján megemlíted hogy lehet zászlót addolni meg
ágyat vagy valami ilyesmit. Aztán bejelentem most én normálisan, külön,
videóval együtt ezt a zászlós bugot és te jössz nekem azzal, hogy ezt te
már valahol valamikor egy másik hiba alatt megemlítetted. Na.

Huntermaster0 <notifications@github.com> (időpont: 2018. szept. 13., Cs,
18:52) ezt írta:

**Comment by Huntermaster0** [comment]
Írtam leírást, csak mivel olyan hiba, így a leírása törlésre került :D Amúgy nem vitázni akartam, csak írtam, hogy szerepelt máshol.

**Comment by ColaKing00** [comment]
Jó.

**Comment by andris155** [comment]
Erről a hibáról már tudtam. Illetve már javítva is lett.
