### ISSUE TITLE
Megadtam az email címem, ez után is kéri minden belépéskor

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#2358]
Ha megadom az /email add paranccsal újra, azt írja ki, ami az utolsó sorban van.

![kep](https://user-images.githubusercontent.com/16057404/45491978-60e7fc80-b76b-11e8-9e46-8a3a26d619e8.png)

**Comment by andris155** [comment]
Az a szöveg, csak információ jellegű. Nem tudja, hogy megadtad-e vagy sem.
