### ISSUE TITLE
bug- itemek sehol

### ISSUE THREAD

**Issue by HELLCATGHOST** [andris155/TheOld-Crafters#236]
Problémám : lelépek a szerverről és mikor vissza lépek holtan találom lelkem..... és cuccaim sehol.....
Hála a clear lag-nak :)

**Comment by andris155** [comment]
clearlagg nincs a szerveren mármint autó törlés, valószínűleg harc közben léptél ki, a cuccokat meg már valaki felszedte, vagy eltűntek, mert clearlagg nélkül is eltűnnek. (tárgyanként 5 vagy 6 perc alatt.)
