### ISSUE TITLE
Táblák addolása.

### ISSUE THREAD

**Issue by ColaKing00** [andris155/TheOld-Crafters#2364]
Csak annyi hogy kreatívban le kell tenni táblát, és ilyen unicode karaktereket kell ráírni. Így a rendszer kiüti a táblát, átmegyek túlélőbe és felveszem. Videó: https://www.youtube.com/watch?v=nVzcQURCZ4I

(Ha már jelentve lett akkor bocsi nem szoktam nézegetni a lezárt bejelentéseket.)

**Comment by andris155** [comment]
Sokszor volt már jelentve. Szerintem nem érdemes vele foglalkozni, mivel a tábla nem ér sokat.
