### ISSUE TITLE
Kreatív védelem fáklya hiba

### ISSUE THREAD

**Issue by elliot2018** [andris155/TheOld-Crafters#2366]
Ha kreatívban lerakok egy üveg blokkot, és rárakok egy fáklyát, utána kreatívban egy csákánnyal kiütöm az üveg blokkot, akkor megkapok a fáklyát.
![image](https://user-images.githubusercontent.com/36449228/45562834-d1fee100-b84b-11e8-8a2c-7f8a4f122d95.png)
![image](https://user-images.githubusercontent.com/36449228/45562855-e04cfd00-b84b-11e8-842b-6ed1b4d0b20d.png)
![image](https://user-images.githubusercontent.com/36449228/45562921-14282280-b84c-11e8-8a0a-6bee9659691b.png)
![image](https://user-images.githubusercontent.com/36449228/45562933-1ab69a00-b84c-11e8-873a-03684c67bc37.png)

**Comment by TamasB14** [comment]
Miért nem kaphatok youtuber rangot xD

**Comment by Viktor1969TOC** [comment]
TamasB14 az a lényeg hogy a gyerek egy külföldi csatornát akart leregisztrálni DE a gép nem engedte mivel még TheOld - Crafters nevű videó sincs azon a csatornán.

**Comment by TamasB14** [comment]
De mi van ha átnevez egy videót? :D

**Comment by andris155** [comment]
Ez a védelem jó a kreatív védelem plugin-ban. Viszont az FAWE miatt valamiért nem működik.

**Comment by andris155** [comment]
https://github.com/andris155/TheOld-Crafters/issues/2400
