### ISSUE TITLE
Craftbook lift bug

### ISSUE THREAD

**Issue by AwesomeFM** [andris155/TheOld-Crafters#2368]
A lift a táblát is blocknak érzékeli és úgy viselkedik, mintha akadályozva lenne a cél.

https://www.youtube.com/watch?v=gZZkia3xijo&feature=youtu.be

**Comment by Viktor1969TOC** [comment]
Szerintem az 1.13 miatt csinálja mert a tábla lehet waterlogged ez által blokként viselkedik.

**Comment by andris155** [comment]
Szerintem ez most már ilyen. A fejlesztő nem változtatott rajta.
