### ISSUE TITLE
Üllő addolás.

### ISSUE THREAD

**Issue by repce16** [andris155/TheOld-Crafters#237]
GeryParkOur mutatta nekem: Két pókhálót leteszel alulra felé valamilyen blokk majd felé két üllő. Amint kiütöd a blokkot alattuk az üllő elindulnak lefelé a 2. pókhálóhoz érve pedig a kreatívban lerakott üllők felvehetők lesznek és normális üllőként kezeli őket a szerver.

**Comment by Treuce** [comment]
#185

**Comment by andris155** [comment]
Talán valamikor javítva lesz, de már jelentett hiba.
