### ISSUE TITLE
PlotSquared LockettePro támogatás

### ISSUE THREAD

**Issue by Huntermaster0** [andris155/TheOld-Crafters#2370]
Szerintem a PlotSquared nem teljesen támogatja a LockettePro levédéseit, mivel ha egy levédésnél (pl. ajtó) egy táblát úgy helyezünk el, hogy az a telken kívülre tartozik (a telekszél fölött van), akkor a tábla nem üthető le onnan, így az ajtó sem szedhető ki.

**Comment by andris155** [comment]
Ezt eddig is tudtuk. Sajnos a LockettePro-t már nem igazán fejlesztik. :(
