### ISSUE TITLE
Survival Pipe plugin hiba??

### ISSUE THREAD

**Issue by csuvi11** [andris155/TheOld-Crafters#2371]
Valamilyen úton módon, más tárgyat ugyan azzal a cső rendszerrel tudok szállítani, de Prismarine Crystals/Shard-ot és a sült halat sem tudom szállítani :( ?

**Comment by csuvi11** [comment]
Megoldottuk, csak nem tudtuk hogy szóköznél kell alsó vonal _, így akkor szerintem /craftbooknál jó lenne ha kiírnánk hogy ilyen esetben használni kell az alsó vonalat _____

**Comment by csuvi11** [comment]
Viszont a Guardian fejének nincs idje amivel átlehetne vinni pipeon nagyon úgy néz ki

**Comment by andris155** [comment]
Ezekkel működik a legtöbb plugin: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
(Kivétel a legacy nevűek)
