### ISSUE TITLE
Spawn - Delfinek

### ISSUE THREAD

**Issue by SaltyUmbrella** [andris155/TheOld-Crafters#2372]
A Spawnon rengeteg delfin és teknős spawnol, meg lehet ölni őket.
![nevtelen](https://user-images.githubusercontent.com/42703224/45594457-37151c80-b99b-11e8-927f-0858b984dda6.png)

**Comment by andris155** [comment]
Ha szeretnéd nyugodtan öld meg őket. Tudtommal spawnol-olni nem spawnol-nak oda.
