### ISSUE TITLE
Levédés

### ISSUE THREAD

**Issue by SaltyUmbrella** [andris155/TheOld-Crafters#2373]
556 blokknyi levédésem van már harmadik napja, de nem működik az, hogy óránként kapnék hozzá plusszokat. A /claimlist ugye 2000 blokkot ír mint maximum de ha tényleg annyi lenne a max, ami után már nem nőhet a szám, az nagyon kevés. Mondtátok még ugye, mikor betettétek ezt az új levédési rendszert, hogy admin levédésre nem lesz szükségünk, mert állandóan nőni fog a levédhető mennyiség. Nos ugye nálam is, ez megállt 2000-nél. Nem tudom, ezt így szerettétek-e volna de nem lehet sok mindent kezdeni ilyen kevés blokkal.

(Csak választ szeretnék kapni erre :D)

**Comment by andris155** [comment]
Később lesz növelve főleg ranggal!
