### ISSUE TITLE
Survival Guardian farm

### ISSUE THREAD

**Issue by csuvi11** [andris155/TheOld-Crafters#2374]
Mai nap épült meg a farm, és nagyon jól mműködött egészen addig, amég be nem lett téve, hogy a guradianok is mostantól stackelődnek, tehát egymásba mennek és megjelenik a szám felettük. Nem csak az ,hogy a farm így már semmit nem ér, hanem amikor leesnek a mobok a három negyede mindig eltünik így kb a 50 guardianból lesz 5 folyamatosan, és a rendszerben van egy olyan rész, ahol a guardianok lesegbződnek, hogy egy ütés legyen, ezzel megint az a gond hogy így egymásba stackelődnek, majd lesebződik, de ha megölöm a következőnek max élete van. Valószinűleg nem kivitelezhető, de nekem nagyon nem tetszik, lényegében az összes mob farm egyenlő a nullával :/

**Comment by csuvi11** [comment]
és a szervert nem is terhelné, annyira ugyanis úgy van megépítve, hogy egy ütés az összes, így azonnal meghalnak, de abban is biztos vagyok, hogy ez az én farmom miatt került be...

**Comment by csuvi11** [comment]
szerintem máshogy kéne megoldani, ezeket a stackelődéseket a farmoknál, én elhiszem hogy terhelheti egy idő után a szervert, de a játék élményt is elveszi, azt viszont eléggé ha az ember 3 napig épít a semmiért 👎 🤕

**Comment by csuvi11** [comment]
Ha nem megoldható, akkor meg legalább az legyen megoldva, hogy nem tűnnek el full random

**Comment by SaltyUmbrella** [comment]
Na igen, ehhez csatlakoznék én is. Még ha a legtöbb mindenért meg kell küzdeni, ez azért már nagyon nagy nehezítés.

**Comment by andris155** [comment]
Nem érdekel senkit az fps. Jelenleg nincs pénzünk jobb szervergépre így korlátozásokat kellet bevezetnünk, mivel a szervergépet terheli elég rendesen a sok őrződ.
