### ISSUE TITLE
Kreatív védelem Kelp hiba

### ISSUE THREAD

**Issue by SaltyUmbrella** [andris155/TheOld-Crafters#2376]
Ha egy kreatív módban letett Kelp-re ráraksz még 2 szintet akkor az automatikusan kiütődik, ezzel survival módban felszedhetővév válik. (Poma csatol videót)

**Comment by poma123** [comment]
https://youtu.be/snUWox5QKPc

**Comment by andris155** [comment]
https://github.com/andris155/TheOld-Crafters/issues/2400

**Comment by andris155** [comment]
330 OCD
