### ISSUE TITLE
Plot - clear, reset, delete, merge nem módosít a telkeken

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#2379]
Hiába írom be bármelyik parancsot, nem állítja vissza a telket alap állapotba, megmarad minden ami rajta van.

![kep](https://user-images.githubusercontent.com/16057404/45616226-1cac7300-ba6f-11e8-83a4-fa0972d91447.png)

**Comment by andris155** [comment]
A hibáról már jó ideje tudunk. Sajnos azóta sem érkezett erre javítás.

**Comment by andris155** [comment]
https://github.com/IntellectualSites/PlotSquared/issues/2086

**Comment by andris155** [comment]
Javítva.
