### ISSUE TITLE
Zmod pvp hiba

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#238]
Ha egy zmod zónában le van tiltva a pvp, és íjjal meglövök mást, sebzi.

**Comment by UDPSendToFailed** [comment]
Akkor is működik, ha a 2 player pvp-je ki van kapcsolva (/pvp off).

**Comment by andris155** [comment]
Pedig ez a védelem biztos benne van. Nem tüzes íj az?

**Comment by UDPSendToFailed** [comment]
De, az.

**Comment by andris155** [comment]
Nem tudok ró eventet.

**Comment by andris155** [comment]
Hamarosan wg lesz a zmod helyett.
