### ISSUE TITLE
McMMO fordítás hiba

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#2380]
/mcscoreboard keep parancs beírása után.

![kep](https://user-images.githubusercontent.com/16057404/45619933-5b482a80-ba7b-11e8-831f-363f1eba0ffb.png)

**Comment by andris155** [comment]
Ezzel mi a gond?

**Comment by TamasB14** [comment]
Úgy lenne a jó szerintem, hogy: Az mcMMO scoreboard látható marad, az eltüntetéséhez, használd a /mcscoreboard clear parancsot! (Ez egy 2OCDs fordítás bizony :+1:  )

**Comment by andris155** [comment]
Javítva. Holnap betölt.
