### ISSUE TITLE
random nincs peted kiírás fordításhiányosság

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#2381]
![2018-09-17_15 53 03](https://user-images.githubusercontent.com/29951969/45627350-0fed4680-ba92-11e8-93c2-bef6bf3e425f.png)
allulról a 4. sor

**Comment by andris155** [comment]
Egyelőre ez snapshot verzió. Naponta frissül néha. Lehetnek benne kisebb hibák.
