### ISSUE TITLE
ládán slab-en beragadás

### ISSUE THREAD

**Issue by Gerii12** [andris155/TheOld-Crafters#2389]
ládákon alsó félblock-okon beragad az ember, ha a ládát kinyitja becsukás után le lehet ugrani de félblockról nem csak elteleportálással, mikor valaki beragad akkor az adminoknak Fly/Spider/Step hack használatát jelzi.

**Comment by Gerii12** [comment]
az sajna lemaradt hogy ez 1.12.2-ben (ami az ajánlott) savszigeten. 
már jópár napja és mindenkinek. :P

**Comment by andris155** [comment]
Megvan a megoldás, csak még nem értem rá berakni. Holnap reggel megcsinálom. :)

**Comment by Gerii12** [comment]
rendben köszönjük :)
épp most észleltem a bekapált blockon is beragadok :D

**Comment by andris155** [comment]
Frissítettem rajta. Most működnie kellene.
