### ISSUE TITLE
Tag+kulcs aktiválás (hardcorex)

### ISSUE THREAD

**Issue by xpolyak** [andris155/TheOld-Crafters#2393]
Az aktiválásnál hibaüzenetet ír ki: "2 nap játékidő szökséges az aktiváláshoz"; a /stats parancs alapján bőven megvan a 2 nap.
[https://imgur.com/hHeVAAr](url)

**Comment by poma123** [comment]
Elméletileg javítva.
Kérlek erősíts meg benne, hogy működik.
Köszönjük a hibajelentést!

**Comment by poma123** [comment]
Javítva!

**Comment by xpolyak** [comment]
Első próbálkozásra hibát írt ki, másodikra sikerült. Köszönöm a javítást.
(An internal error occured while attempting to perform this command)

**Comment by poma123** [comment]
Ránézek.

**Comment by poma123** [comment]
Ez is javítva!
