### ISSUE TITLE
Kreatív bugok

### ISSUE THREAD

**Issue by SaltyUmbrella** [andris155/TheOld-Crafters#2395]
1. Nem enged egymás tetejére tenni 2 gyapjú szőnyeget. (úgy sem, ha alatta fonál lenne) Kittiék mondtak olyamit, hogy ha az alatta lévőt kiütöm, akkor addolok, mivel felvehetővé válik survival módban. Nos attól még ez építésnél eléggé idegesítő és nagyban lelassítja a munkát.

2. Ha üvegre kattintok vizes vödörrel a kezemben, nem törtönéik semmi, nem teszi le.

**Comment by andris155** [comment]
https://github.com/andris155/TheOld-Crafters/issues/2400

**Comment by andris155** [comment]
330 OCD
