### ISSUE TITLE
Több blokk védés játékpénzért

### ISSUE THREAD

**Issue by andris155** [andris155/TheOld-Crafters#2398]

**Comment by KingDeadZ** [comment]
Lehetne a VIP-nek vagy az Elitnek 10240blockos levédhető területje, ami pontosan 40 chunknak felel meg.

Vagy esetleg, lehetne chunkokra számolni pontosan a levédhető blockokat. :)

**Comment by ColaKing00** [comment]
Szerintem az sokkal jobb lenne ha ahelyett, hogy több blockot lehet levédeni, inkább több levédést lehetne létrehozni.

**Comment by MrZero1** [comment]
Úgy szerettük volna, hogy rangonként a max blokk változik, Kitti ki is számolta, viszont ez nem lehetséges. Így marad az az opció, hogy $-ért lehet blokkot venni.

**Comment by andris155** [comment]
kész
