### ISSUE TITLE
Kreatív Védelmi Plugin

### ISSUE THREAD

**Issue by Kronox12** [andris155/TheOld-Crafters#24]
Nem működik.Leteszek kreában egy dia ércet,kiütöm Old csákánnyal,dob egy diát,amin van a sárga írás.Leteszem megint,kiütöm a Gyengéd Érintéses Old csákánnyal,itt is a sima diát dobja.Eddig megy a plugin.De utána leteszek 3 ércet egymásra,kiütöm a gyengéd érintéses csákánnyal,kidobja az ércet,de sárga írás nélkül,azaz szabadon csinálhatok vele amit akarok.Ugyan ez a probléma több blokkal is előfordult,mint pl. Nekem a homoknál nem is írta a sárga írást csak egy üres sort,de le tudtam tenni,majd felvenni és az üres sor elment.UDP tesztelte,és ez történt nála is a földdel.

**Comment by andris155** [comment]
A plugin beállítás alatt volt ma, jelenleg ki is lett szedve, kérlek holnap teszteld majd.

**Comment by andris155** [comment]
https://github.com/andris155/TheOld-Crafters/issues/24

**Comment by Kronox12** [comment]
Értettem Mon-Capitan.

**Comment by andris155** [comment]
Javítva:
CreativeControl visszarakva.
