### ISSUE TITLE
Aukció - teli eszköztár

### ISSUE THREAD

**Issue by RyanSmake** [andris155/TheOld-Crafters#240]
Amennyiben úgy vesz valaki valamit aukción, hogy teli van az eszköztára akkor a plugin automatikusan eldobja azt, oda, ahol a játékos van, de nem tudja felvenni azután se, hogy kiürítette az eszköztárát.

**Comment by Treuce** [comment]
Jelentett bug ha minden igaz. Valamiért néha átrakja addolt vagy nem is tudom milyen itemnek, ezért nem lehet felvenni.

**Comment by andris155** [comment]
Nem tudok vele mit csinálni sajnos, az aukciós plugint nem nagyon fejlesztik már, egyébként a hiba már jelentett neki is. Ha jól értelmeztem amúgy -ba, vagy 0-ba megy a tárgyak száma, és azért nem lehet felvenni.
