### ISSUE TITLE
kreatív védelem/bug

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#2402]
kreatív játékmódban is fel tudja venni az emberke az itemeket

**Comment by andris155** [comment]
Erről videót nem tudtok csinálni?

**Comment by andris155** [comment]
Kérlek nyiss új hibajelentést, ha ez előfordul és írd le mikor vagy mit kell hozzá csinálni. Nekem ezt nem sikerült reprodukálni.
