### ISSUE TITLE
Javítás vasblockkal

### ISSUE THREAD

**Issue by Bannoltboci** [andris155/TheOld-Crafters#2404]
![2018-09-22_10 03 56](https://user-images.githubusercontent.com/43493917/45916667-30d6e280-be6a-11e8-9919-061a8c50b234.png)

Ha vasblockkal akarsz javítani akkor eltűnik az enchant az intemről. /Zero mondta hogy írjam ide is le/

**Comment by KingDeadZ** [comment]
Ez nem egy hiba. Ez így lett megtervezve. Részletesebben tudsz olvasni róla itt: http://mcmmo.wikia.com/wiki/Repair

Along with this, there is a chance for a downgrade on the enchantment. For example, a Power II Bow could potentially become a Power I Bow.

Javasolnám a downgrade-t trueról falsera állítani :p (Az old itemes esetek miatt)
