### ISSUE TITLE
Minemarket

### ISSUE THREAD

**Issue by Bannoltboci** [andris155/TheOld-Crafters#2405]
A minemarketbe valamiért kis betűvel írja a felhasználó nevemet. (Bannoltboci) Illetve ha veszek OCDből egy tárgyat akkor a tárgy "leírásában" is kicsivel kezdi. Ha nevet szeretnék váltani az oldalon akkor azt írja ki hogy Hibás név váltás. 
![toc](https://user-images.githubusercontent.com/43493917/45916727-34b73480-be6b-11e8-8fb5-59b665918b5a.jpg)

**Comment by KingDeadZ** [comment]
Eléggé broken dolog már mostanában a minemarket :s Egyébként, nekem jól működött még év elején amikor beregisztráltam. 
![image](https://user-images.githubusercontent.com/38157910/45917364-e52a3600-be75-11e8-9553-ab49c1ef8d4f.png)

**Comment by andris155** [comment]
Hát esetleg próbálj meg valami más nevet megadni. Aztán visszaírni a helyesre. De lehet ezután már azt se fogja engedni. Szóval csak saját felelősségre.

**Comment by andris155** [comment]
@KingDeadZ Ha már egy elavult Windows-t használd legalább a frissítéseket telepítsd fel, mert így elég veszélyes használni. Meg az utorrent tele van biztonsági hibákkal cseréld le inkább Qbittorrent-re, de ne felejtsd át állítani a max feltöltések számát többre.
