### ISSUE TITLE
1v1 hiba.

### ISSUE THREAD

**Issue by Bannoltboci** [andris155/TheOld-Crafters#2407]
Néha 1v1ben kezdés előtt lehet mozogni amikor még csak visszaszámol. Jól lehet látni a csatolt képen hogy még csak 1nél jár a számláló de én már a pálya közepe fele tartok. 
![2018-09-22_23 19 52](https://user-images.githubusercontent.com/43493917/45921952-66a6b600-bec0-11e8-9429-2ff0418e5d64.png)

**Comment by MrZero1** [comment]
Nem tudom, mi baja lehet, eredetileg nem mozdulhatsz addig, míg le nem jár a számláló. Engem nem szokott elengedni legalábbis.

**Comment by Bannoltboci** [comment]
Ahogy megfigyeltem eddig csak winek után engedett(néha) futni kezdés előtt. Ha akarod tesztelhetjük a szerveren hogy hogy is tudok mozogni.

**Comment by andris155** [comment]
Én sem értem mi baja.

**Comment by andris155** [comment]
Ha megint tapasztaltok ilyet nyissatok egy új hibajelentést. Jó lenne erről egy videó is.
