### ISSUE TITLE
1v1 pálya bug.

### ISSUE THREAD

**Issue by Bannoltboci** [andris155/TheOld-Crafters#2408]
Az egyik pályán általában a föld alá spawnolódunk amitől sebződünk és ha nagy nehezen kiszenvedtünk magunkat a föld alól kevesebb HPval kezdünk. 
![2018-09-23_12 06 47](https://user-images.githubusercontent.com/43493917/45926915-a609ec80-bf2a-11e8-8dc7-730fb0b047c2.png)
![2018-09-23_12 06 56](https://user-images.githubusercontent.com/43493917/45926920-b6ba6280-bf2a-11e8-8fe7-efba1fa831b4.png)

**Comment by MrZero1** [comment]
Érdekes, eddig nem volt vele baj. A spawnpontokat áthelyeztem.
