### ISSUE TITLE
Végtelen OldGold

### ISSUE THREAD

**Issue by RyanSmake** [andris155/TheOld-Crafters#241]
Na, produktív vagyok mostanság! :D
Ha valaki új névvel jön fel, akkor újra használatba veheti a spawnon található OldGold ládákat. Ezen itemeket átadhatja főkarakterének, majd /unregister paranccsal a lobbyban megszabadulhat a felesleges karaktertől (nem próbáltam ki, mekkora a szerver user/ip limitje, de így nyilván végtelen).

**Comment by andris155** [comment]
Az unregister jó ha van, ha azért is nekünk írnának nem lenne a legjobb, nyilván ezzel a módszerrel elég hamar le lehet bukni, mivel a staffok látják ki hány karakterrel lépett be.

**Comment by Treuce** [comment]
Hozzáfűzni való annyi részemről hogy késő este kilehetne használni amikor nincs fent staff,

**Comment by andris155** [comment]
kivettem végül az unregistert.
