### ISSUE TITLE
Varázslóasztal és Shulkerdoboz levédés

### ISSUE THREAD

**Issue by Huntermaster0** [andris155/TheOld-Crafters#2411]
A levédés warpon kint van, hogy a varázslóasztal is védhető a Lockette által, viszont valójában nem lehet levédeni. Ez valahogy megoldható lenne, hogy arra is mehessen a Lock tábla?

+Minden shulkerdoboz levédhető, kivéve a nem színezett (alapból ugye ilyen lilás színe van), azt valamiért nem engedi levédeni.

**Comment by andris155** [comment]
Elvileg már működik.
