### ISSUE TITLE
Eltűntek az eddigi vote pontok

### ISSUE THREAD

**Issue by Huntermaster0** [andris155/TheOld-Crafters#2412]
Ma délben mikor felmentem, nem jelentek meg a szavazati pontok a vote menüben, illetve az egyéniben is 0-t írt.
![kepkivagas3](https://user-images.githubusercontent.com/42183895/45947494-c43c1f00-bff4-11e8-9c30-7be1a61ac0b2.PNG)

**Comment by SaltyUmbrella** [comment]
Ehhez hozzáfűzném még, nem jól jelzi ki a /vote parancs, hogy mire tudok már szavazni illetve mire nem:
![image](https://user-images.githubusercontent.com/42703224/45970001-a642de80-c035-11e8-8aba-f464f8816005.png)
(Szavaztam már mindkettőre a mai napon, de zölddel írja ki)

**Comment by andris155** [comment]
Én nem nyúltam ehhez a plugin-hoz és szerintem más sem. Nem értem így ezt az egészet. Ha lesz laptopom, akkor tudok max ennek bővebben utána nézni.

**Comment by andris155** [comment]
Nem tudom mitől történt ez.
