### ISSUE TITLE
EssentialsX 1.13

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#2413]
Ha valaki levegőben lévő 1.13-as blokkra állít be sethome-t, 1.13-as blokkra /back-el halál után, vagy olyan játékosra tp-z, aki 1.13-as blokkon áll, akkor az essentials úgy veszi, mintha nem lenne alatta semmi, és a földre teleportálja. Világváltás nélkül néha jó, néha nem.

https://youtu.be/4zxEKXTp7Bo

**Comment by andris155** [comment]
Egyelőre csak kompatibilis módban fut az Essentials 1.13.1-en.

**Comment by andris155** [comment]
frissítve.
