### ISSUE TITLE
/music parancs gm 1-ben

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#2414]
![kep](https://user-images.githubusercontent.com/16057404/45951871-6f54d480-c005-11e8-9a4e-c8809f319e79.png)

Szerintem lehetne tiltani, úgyse tudja megnyitni az inv-et a kreavédelem miatt.

**Comment by MrZero1** [comment]
Ha jól tudom, nincs music parancs.

**Comment by UDPSendToFailed** [comment]
@MrZero1 

![kep](https://user-images.githubusercontent.com/16057404/45970241-44cf3f80-c036-11e8-851a-b8f65a7f2872.png)

**Comment by MrZero1** [comment]
Oh, jó tudni róla. Azért lett kivéve az Információs boxból, mert elvileg nincs. :D

**Comment by andris155** [comment]
Javítva. Tesztelni sajnos nem tudom mert ma vitte el a futár a laptopom garanciáztatni.

**Comment by andris155** [comment]
@MrZero1 a közös chat-re írtam, hogy visszakerült.
