### ISSUE TITLE
XP átváltás

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#2415]
A mostani megoldással annyi üvegpalackot kell craftolni, amennyi xp-t át akarok váltani, ez így elég zavaró, főleg nagyobb szinteknél, ahol lehet több 1000db is. Jobb lenne a régi plugin, van már 1.13-ra.

https://www.spigotmc.org/resources/bottledexp.2815/

**Comment by MrZero1** [comment]
Szerintem tökéletesen megfelel a célra a jelenlegi, nincs szükség külön pluginra. Aki el akarja tárolni az XP-t,  készít palackot. :D

**Comment by UDPSendToFailed** [comment]
Ezzel csak az a probléma, hogy több óra lenne ehhez elegendő palackot craftolni. Így az enchantoláson kívül kb semmire se használható az xp, nem lehet eladni sem, halálkor pedig elveszik tag ranggal.

**Comment by MrZero1** [comment]
Ha szükséges, el lehet adni. A palackozása pedig a Survival egyik folyamat része.

**Comment by UDPSendToFailed** [comment]
Hardcore-n még oké, de szerintem egy survival szerveren értelmetlen ennyire megnehezíteni a játékot, főleg a rang nélküli tagok számára.

**Comment by andris155** [comment]
Alapból a játékban nincs is ilyen lehetőség. Szóval nem értem mi a gond ezzel.
