### ISSUE TITLE
Ender Dragon Idézéssel addólás.

### ISSUE THREAD

**Issue by Viktor1969YO** [andris155/TheOld-Crafters#2416]
![2018-09-24_14 46 33](https://user-images.githubusercontent.com/38433879/45953325-ff951880-c009-11e8-8ec8-6846b527e351.png)
Nos mikor lerakom az end kristályt a blokk mellé akkor kiírja hogy nem rakhatom oda és visszaadja, de az idézés megkezdődik hiába "nincs ott" (A képen azt is látni hogy 4db end kristályt vettem csak)

**Comment by ColaKing00** [comment]
Én tudok pillanat és küldöm.

**Comment by ColaKing00** [comment]
Itt van: https://www.youtube.com/watch?v=MB-eeVIAtI4

UI.: A videókészítésért jár OCD? :D

**Comment by andris155** [comment]
Milyen flag-ek vannak engedélyezve a blokkok helyén?

**Comment by Viktor1969TOC** [comment]
A /warp Vég-en idéztem. Videót meg köszönöm Cola :3

**Comment by KingDeadZ** [comment]
Ez még akkor is jelen volt, amikor 1.12.2ben volt a szerver :p (Nem nagyon hittem azt, hogy ez egy bug hanem hogy direkt visszaad 1et idk why, mindíg felrobbantottam xd)

**Comment by andris155** [comment]
A staffoknak szóljatok, hogy nézzék a flagokat. Szerintem azokkal lesz gond.

**Comment by andris155** [comment]
Block place flag-et kellene talán engedélyezni.

**Comment by ColaKing00** [comment]
Rendben szólok.

András Marczinkó <notifications@github.com> (időpont: 2018. szept. 25., K,
19:56) ezt írta:

**Comment by ColaKing00** [comment]
Megpróbáltam szólni, de staff nem tud flag-et állítani tehát Adminnak kell.

**Comment by poma123** [comment]
Javítva.
Köszi a hibajelentést

**Comment by andris155** [comment]
Köszi poma

**Comment by ColaKing00** [comment]
OCD-t nem kap az aki bejelentette(nem én)?

És videókészítésért?
Csak kérdés.

András Marczinkó <notifications@github.com> (időpont: 2018. szept. 26.,
Sze, 14:39) ezt írta:

**Comment by mr00000** [comment]
kaka plguni 1. verzio beta 1
https://github.com/andris155/TheOld-Crafters/pull/3517
