### ISSUE TITLE
A boltban bele lehet nézni az ötletládába.

### ISSUE THREAD

**Issue by ColaKing00** [andris155/TheOld-Crafters#2418]
Ha a tölcsér szélére kattintok akkor ki tudom nyitni a bolt warpon lévő ötletláda tölcsért. 
Videó: https://youtu.be/8ki9IMEYnhU

**Comment by MrZero1** [comment]
Ez csak a tölcsér. Az ötletláda jóval alatta van. Levédem majd a tölcsért, bár ez egyből elszívja, szóval különösebben nem okoz problémát.
