### ISSUE TITLE
Lock tábla

### ISSUE THREAD

**Issue by Ladykutya** [andris155/TheOld-Crafters#242]
Ha leteszel egy táblát egy nem levédhető blokkra, és beírod az első sorba, hogy [Lock], a második sorba a neved, akkor egy tábla helyett dob vagy 4-5 öt. Tehát ha türelmes vagy bármennyi táblát tudsz farmolni, ami nem nagy előny, de hát... Remélem érthető és hasznos volt :)

**Comment by andris155** [comment]
https://github.com/andris155/TheOld-Crafters/issues/185
