### ISSUE TITLE
1.13.1 - 1.12.2

### ISSUE THREAD

**Issue by SaltyUmbrella** [andris155/TheOld-Crafters#2420]
Mikor be szeretnék lépni a szerverre (Login-ra elsősorban), ezt a hibíüzenetet írja ki:
![image](https://user-images.githubusercontent.com/42703224/46058565-edc38a80-c15b-11e8-9229-be9d78ebb83d.png)
Viszont, amikor 1.12.2-vel jönnék fel a szerverre, beenged de nem tudom csatlakozni ugye a survival szerverhez, mivel az 1.13-as:
![image](https://user-images.githubusercontent.com/42703224/46058603-1a77a200-c15c-11e8-8b73-5feeea09cf0a.png)

**Comment by MrZero1** [comment]
Andris javította azóta.
