### ISSUE TITLE
Spawner kiütés

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#2422]
Találtam egy bányapók spawnert, kiütöttem, 2x írta a szöveget. Mikor leraktam újra, hogy teszteljem, sima pók spawner lett belőle.

![kep](https://user-images.githubusercontent.com/16057404/46142931-cd2d2a80-c258-11e8-9b72-8bbfed825998.png)

![kep](https://user-images.githubusercontent.com/16057404/46142967-e46c1800-c258-11e8-8703-fe51f9e55405.png)

**Comment by UDPSendToFailed** [comment]
Egy másik bányapók spawnerrel is ugyanez történt. 

![ezgif com-gif-maker](https://user-images.githubusercontent.com/16057404/46143403-1e89e980-c25a-11e8-8a74-cca0296a0fbe.gif)

**Comment by UDPSendToFailed** [comment]
Vissza, csak szerintem nem direkt, hanem frissítette magát.

**Comment by andris155** [comment]
Sajnos össze lett keverve egy másik Epic nevű plugin-al így került be véletlenül. Kárpótlásul 1016 OCD-t adok. Ha rakott le lebegő szöveget azt töröltessétek egy adminisztrátorral.

**Comment by poma123** [comment]
Most már jó. :)
