### ISSUE TITLE
Indokolatlan csatlakozási szöveg

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#2423]
Nem tudom, mi ez, tegnap is volt.

![kep](https://user-images.githubusercontent.com/29709854/46145678-35800a00-c261-11e8-8fcd-a4e0a2f3c3ac.png)

**Comment by andris155** [comment]
A legjobb benne, hogy én se tudom mi ez vagy mi írja 😂

**Comment by andris155** [comment]
Nem valami kliens dolog? Nálam nem írt ilyeneket tegnap szerintem.

**Comment by MrZero1** [comment]
Más is látta, tegnap is, ma is.

**Comment by andris155** [comment]
Nem sikerült reprodukálnom és nem is találkoztam ezzel a szöveggel.

**Comment by andris155** [comment]
Ez melyik szerveren volt egyébként?

**Comment by MrZero1** [comment]
Survival

**Comment by poma123** [comment]
![image](https://user-images.githubusercontent.com/25465545/47174073-fb5dd180-d30f-11e8-82ae-5720522d7b6d.png)
Megtaláltam. A ChatControl nyelvi fájljában rejtőzködött, viszont nem mindig jelenik meg. Ez hardcore-on készült.
![image](https://user-images.githubusercontent.com/25465545/47174167-2fd18d80-d310-11e8-92f0-93d64b46ce9e.png)

**Comment by andris155** [comment]
javítva

**Comment by MrZero1** [comment]
Ma is megtörtént ez :(

**Comment by andris155** [comment]
Elvileg javítva, ha újra előfordul mindenképpen írjatok.
