### ISSUE TITLE
Moderátor jogok

### ISSUE THREAD

**Issue by Kelvin172** [andris155/TheOld-Crafters#2424]
Azzal a kéréssel szeretnék írni, hogy ugye a moderátorok megkapták azt a jogot régebben, hogy a telkek útján bontani lehessen (a telkekről kilógó fák miatt). A kérésem pedig az lenne, hogy az építési jogot is megkaphassák, mivel ha véletlenül kiütnek egy blokkot, akkor arra nincs joguk hogy vissza is építsék, csak adminnak van joga.

**Comment by andris155** [comment]
Nincsenek már kilógó fák.
