### ISSUE TITLE
Új 1v1 plugin

### ISSUE THREAD

**Issue by SaltyUmbrella** [andris155/TheOld-Crafters#2425]
Nos, mikor 2 ember harcol egymás ellen az új 1v1 rendszerben, ha valaki meghal ilyen üzenetet ír ki a rendszer:
![image](https://user-images.githubusercontent.com/42703224/46235022-c0075d00-c378-11e8-8bd5-6a382180f7bb.png)
"death.attack.magic.player" - ezen van a lényeg a képen.

**Comment by andris155** [comment]
Ez magának a játéknak a hibája. Vagy esetleg a szerverfájlé. De lehet a kliensé is ha nem eredetit használsz.

**Comment by SaltyUmbrella** [comment]
Eredetit használok pedig
