### ISSUE TITLE
McMMO inspect jog

### ISSUE THREAD

**Issue by Huntermaster0** [andris155/TheOld-Crafters#2427]
Az inspect paranccsal meg lehetett nézni más McMMO szintjeit (legalábbis 1.12.2.-ben). Most az McMMO helyett a FAWE dob egy üzenetet, hogy egy permission hiányzik. Gondolom mindkettőben van /inspect parancs, megoldható, hogy menjen az McMMO inspect?

**Comment by Huntermaster0** [comment]
Az működik, csak simán az inspect egyszerűbb lenne. És 1.12.2ben is távolsághoz volt kötve az inspect parancs?

**Comment by andris155** [comment]
Szerintem igen

**Comment by andris155** [comment]
Holnap betölt a javítás.
