### ISSUE TITLE
Stackelődési probléma

### ISSUE THREAD

**Issue by SaltyUmbrella** [andris155/TheOld-Crafters#2428]
Nos, pár mob nem stackelődik, mint ahogy a képen fog látszani, a guardianok sem. (Blaze--vel sem működött) és elég nagy laggot okoz nekem is mint a szervernek. Kérném ennek mielőtti hejreállítását, mivel nemszeretnék ártani a szerver TPS szintjének.
![image](https://user-images.githubusercontent.com/42703224/46257487-bab22b80-c4ba-11e8-85f4-032966acd8d4.png)

**Comment by andris155** [comment]
A farmot kellene megszűntetni inkább.
