### ISSUE TITLE
A /kittycannon, és a tárgyak széttörik a teknőstojást

### ISSUE THREAD

**Issue by Huntermaster0** [andris155/TheOld-Crafters#2429]
A jelenlegi levédés plugin nem igazán támogatja a teknőstojásokat, pettel illetve /kittycannon paranccsal is szét lehet törni a levédésen lévő tojást.
https://youtu.be/AvADyCvbL3A

**Comment by andris155** [comment]
Ez inkább az Essentials hibája.

**Comment by andris155** [comment]
A petek már török szét.
