### ISSUE TITLE
MCMMO - bányászat

### ISSUE THREAD

**Issue by SaltyUmbrella** [andris155/TheOld-Crafters#2430]
A "Prismarine Brick" block nem ad mcmmo bányászat skillbe tapasztalatpontot mikor kibányászom.

**Comment by KingDeadZ** [comment]
A wikipédián nem ír prismarine bricket, csak sima prismarinet. Szóval.. nem hinném hogy ez hiba. :D http://mcmmo.wikia.com/wiki/Mining

**Comment by andris155** [comment]
Rá fogok nézni. Gondolom megint a Material nevekkel van baja...

**Comment by andris155** [comment]
Ez nem hiba.
