### ISSUE TITLE
Survival rangok NPC elírás

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#2431]
![kep](https://user-images.githubusercontent.com/16057404/46262383-a002a580-c500-11e8-8fde-38b114998c2c.png)

**Comment by UDPSendToFailed** [comment]
+1, a McMMO résznél

![kep](https://user-images.githubusercontent.com/16057404/46262395-dfc98d00-c500-11e8-85d9-169e990caf7d.png)

**Comment by poma123** [comment]
Javítva.
Köszi a hibajelentést
