### ISSUE TITLE
Kreatív - Túlélő inventory törlődés.

### ISSUE THREAD

**Issue by baawoof** [andris155/TheOld-Crafters#2433]
Törlődött valamiért a túlélős inventorym (tegnap 4-kor újra indult a szerver és azóta nincsenek meg a cuccaim, Kreatív alatt léptetett ki). Nem volt sok minden nálam csak egy old ásó ami érték.

**Comment by andris155** [comment]
Legközelebb lép ki ez előtt az újraindítás előtt. A tárgyakat pedig kérd vissza egy stafftól.
