### ISSUE TITLE
Kreatív Védelem - Botlódrót hiba

### ISSUE THREAD

**Issue by SaltyUmbrella** [andris155/TheOld-Crafters#2438]
Ha kreatív módban, leteszek egy Botlódrótot bármilyen szilárd blokkra, majd kiütöm megkapom a tárgyat survivalos, felszedhető móban. (nincsen videó felvevő programom)
![image](https://user-images.githubusercontent.com/42703224/46311960-fedd2300-c5c3-11e8-8784-dfc03054f5bf.png)
![image](https://user-images.githubusercontent.com/42703224/46311974-04d30400-c5c4-11e8-9ca1-ac9d16be8733.png)
![image](https://user-images.githubusercontent.com/42703224/46311996-0e5c6c00-c5c4-11e8-9125-538cc70a7b78.png)

**Comment by andris155** [comment]
Erről a hibáról már tudtam.

**Comment by andris155** [comment]
https://github.com/andris155/TheOld-Crafters/issues/2400
