### ISSUE TITLE
Enderpearl-al ki lehet bugolni /warp bolt-ból

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#2439]
![kep](https://user-images.githubusercontent.com/16057404/46315016-9181c000-c5cc-11e8-9219-e0ac7c3385fb.png)

**Comment by UDPSendToFailed** [comment]
Eventek warp ugyanez.

**Comment by MrZero1** [comment]
Jelentősége nincs, javítva. Köszönjük!
