### ISSUE TITLE
Tekős páncél (sapka) bug

### ISSUE THREAD

**Issue by SaltyUmbrella** [andris155/TheOld-Crafters#2440]
Nos, a teknős sapka tulajdonsága, hogy 10mp-ig tartó vízalatti légzés effektet ad, nos SingPlayerben nem, de multiplayerben elveszik az idő lejártával.
![image](https://user-images.githubusercontent.com/42703224/46371348-66f53d00-c688-11e8-97f7-0bfd52effeac.png)
![image](https://user-images.githubusercontent.com/42703224/46371359-6eb4e180-c688-11e8-9a09-0c86bac0af0b.png)
A 2. képen látszódik is, ahogyan egyre evesebb lesz a levegőm.

**Comment by SaltyUmbrella** [comment]
BobMarley vetette fel az ötletet, én teszteltem.

**Comment by andris155** [comment]
Talán szerverfájl hiba lehet.

**Comment by andris155** [comment]
Nem sikerült reprodukálni. Nálam folyamatosan 10s
