### ISSUE TITLE
/petinventory bug

### ISSUE THREAD

**Issue by SaltyUmbrella** [andris155/TheOld-Crafters#2441]
Mikor megpróbálnám megnyitni a petem eszköztárát, ezt a hibaüzenetet írja ki.
![image](https://user-images.githubusercontent.com/42703224/46391165-b749ba80-c6db-11e8-9432-6526603d2e06.png)

**Comment by KingDeadZ** [comment]
Old rang? :D

**Comment by andris155** [comment]
Javítva
