### ISSUE TITLE
Inventory/Item felvétel hiba(?)

### ISSUE THREAD

**Issue by daemonic01** [andris155/TheOld-Crafters#2442]
Survival játékmódban teli inventory esetén és képes vagyok felvenni tárgyakat, amelyek azonban hely hiányában vélhetően megszűnnek létezni. Ez valami új erőforráskímélő plugin műve, vagy tényleg gázos a rendszer? :D

(Próbáltam videót készíteni de valamiért a Fraps nem volt hajlandó képet felvenni, csak hangot.)

**Comment by andris155** [comment]
Most is él a hiba?

**Comment by daemonic01** [comment]
Most ahogy látom nem.
