### ISSUE TITLE
/voteshop hiba

### ISSUE THREAD

**Issue by SaltyUmbrella** [andris155/TheOld-Crafters#2445]
Nem csinál semmi a /voteshop parancs, úgy sem, ha a sima /vote menüpontból szeretném elérni:
![image](https://user-images.githubusercontent.com/42703224/46432732-3e844600-c74f-11e8-86e1-4afdad432ba5.png)
![image](https://user-images.githubusercontent.com/42703224/46432743-45ab5400-c74f-11e8-8293-46ae1745d936.png)

**Comment by andris155** [comment]
Javítva.

**Comment by andris155** [comment]
330 OCD
