### ISSUE TITLE
Pcst választás

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#2446]
Szia. A facsemete helyett nem lehetne ismét 1-1 különböző item? (/pcst ablak)

![kep](https://user-images.githubusercontent.com/29709854/46433620-9fad1900-c751-11e8-92fb-e101a144c03a.png)

**Comment by poma123** [comment]
A régi id-ket használja, átírom material-ra.

**Comment by andris155** [comment]
Holnap betölt a javítás.

**Comment by poma123** [comment]
Már most betöltött a javítás.
