### ISSUE TITLE
Petek + Víz

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#2447]
Szia. Szóval, befogtam egy delfint petnek, a ride skillt választottam neki, majd ráültem, a delfin nem mozdult semerre, csak elkezdett bugolni a földbe, én nem tudtam mozogni, leszállni, majd a delfin meghalt, én bebugoltam a semmibe (?), konzolból a spawnra teleportáltam magam. Nem tudom, hogy hiba e vagy sem, de furcsa volt.

![kep](https://user-images.githubusercontent.com/29709854/46433848-3bd72000-c752-11e8-91dd-9e5b27f28453.png)

Vízben volt. Több pettel is megnéztem, mind lemerül és nem lehetett leszállni róluk, írni se lehetett a chat-be, semmit se lehet tenni.

**Comment by andris155** [comment]
Egyelőre ez a plugin alpha. Lehetnek benne hibák.

**Comment by andris155** [comment]
Egyelőre ez nincs benne a plugin-ban. Talán valamikor a jövőben.
https://github.com/xXKeyleXx/MyPet/issues/605
