### ISSUE TITLE
Szigony dobás után nem jön vissza egy plugin által levédett helyen 

### ISSUE THREAD

**Issue by kova97** [andris155/TheOld-Crafters#2448]
A szerveren eldobtam agy old szigonyt, amelyen volt hűség 10.  A fejem főlé céloztam, simán vissza kellett volna esnie rám. Amikor elérte a dobás tetejét egyszerűen annyit irt a chat hogy: 
[P2] A következő engedélycsomag hiányzik: plots.admin.interact.road 
És nem jött vissza szigony.

**Comment by andris155** [comment]
Ez nem hiba.
