### ISSUE TITLE
A táblákon lévő feliratok nem müködnek.

### ISSUE THREAD

**Issue by kova97** [andris155/TheOld-Crafters#2451]
A boltban lévő táblákon nem működik a felirat, azt írja hogy Economy account from the shop owner doesn't exist. 
Másra használt táblák sem működnek mint a lift, ott nem kap a játékos szöveget. 
Tegnap még működtek, mai nap már nem.

**Comment by daemonic01** [comment]
Nem megy se a bolt, se a Lock táblás rendszer, bárki belenyúlhat bármibe ha nincs levédett területen. Előre látom hányan fognak nyavajogni mert kirabolták őket.

**Comment by andris155** [comment]
Javítva!
Köszönjük a hibajelentést!
