### ISSUE TITLE
CombatLogX hiba (?)

### ISSUE THREAD

**Issue by SaltyUmbrella** [andris155/TheOld-Crafters#2453]
Amikor a spawnon lévő állatfarm szerűségen megölök egy csirkét ezek az üzenetek fogadnak (tegnap még nem volt ilyen):
![image](https://user-images.githubusercontent.com/42703224/46568680-40b1f480-c949-11e8-9e27-418658e4941e.png)

**Comment by SaltyUmbrella** [comment]
heylesbítek ismeét: a /warp vadon-osvilágban ugyanezt nem írja ki

**Comment by MrZero1** [comment]
![kep](https://user-images.githubusercontent.com/29709854/46570198-bc6b6b80-c960-11e8-904a-8f07a37b6fd0.png)
Nekem páncélállványnál írja ki.. :D

**Comment by kova97** [comment]
Ha ellenséges mobot ölsz akkor is kirija például az endbe, endermannél! 
![2018-10-06_13 04 59](https://user-images.githubusercontent.com/43828722/46570701-b6798880-c968-11e8-8723-41fa7b2b7de4.png)

**Comment by daemonic01** [comment]
Tehát nem én tapasztaltam ezt először...
Elég idegesítő, mit ne mondjak, de szerintem az is teljesen felesleges, hogy kiírja ezeket:
"ELŐKÉSZÍTETTED AZ ÖKLEIDET"
"LEENGEDED AZ ÖKLEIDET"
"ELLENSÉG VÉRZIK"

Napestig sorolhatnám és engem végtelenül idegesít, mert nagyban nehezíti a tényleges chat olvasását és használatát.
Javaslom - amennyiben lehetőség van rá - ezeket az üzeneteket vegyétek ki, végtére is senkit nem érdekel hogy az a mob amit megöl épp vérzik, meg az se hogy épp hol vannak az öklei. Ez nem szöveges minecraft :D

**Comment by andris155** [comment]
Javítva
