### ISSUE TITLE
Fadöntés - mcmmo, favágás

### ISSUE THREAD

**Issue by SaltyUmbrella** [andris155/TheOld-Crafters#2454]
Mikor a fadöntés képességet használom a 2x2 vastag fenyőkön, így vágja ki őket leggyakrabban:
![image](https://user-images.githubusercontent.com/42703224/46570802-71eeec80-c96a-11e8-84bd-4e521c506837.png)

**Comment by andris155** [comment]
Sajnos nem tökéletes ez. :/
