### ISSUE TITLE
Slime Vödör hiba

### ISSUE THREAD

**Issue by SaltyUmbrella** [andris155/TheOld-Crafters#2455]
A slime Vödör működni működik, de sokkal gyakrabban mutatja a "Slime Chunkot" mint amennyi valójában lenne. Zero azt mondta, a kétfejű baltás hibához lehet köze

**Comment by andris155** [comment]
Valószínűleg majd javítja a fejlesztő. Egyelőre nem igazán foglalkozik sajnos a plugin-al.
