### ISSUE TITLE
telekvédelem

### ISSUE THREAD

**Issue by asdragon** [andris155/TheOld-Crafters#2456]
Viktor1969 képes volt megölni egy megszelidített kutyát a telkemen.
Lehívott egy petet, használta a fogazott pengét és lecsapta egy kardal.

**Comment by Viktor1969YO** [comment]
:c Te engem elárultál c.c Nem kell pet hozzá se fogazott penge. elég csak ütögetni az mcmmo Végett nekiáll az ellenség vérezni és meghal

**Comment by KingDeadZ** [comment]
Nem telekvédelem, hanem mcmmo hiba. Öltem már meg a petemet farmolás közben így. q.q

**Comment by andris155** [comment]
Nem igazán támogatja a telkes plugin-t sajnos az mcMMO.
