### ISSUE TITLE
Napi eventek

### ISSUE THREAD

**Issue by SaltyUmbrella** [andris155/TheOld-Crafters#2458]
A Napi eventeken (pl: run, famászás, sulijump,..) 
1. lehet repülni (gondolom ebből adódóan god módot is használni)
![image](https://user-images.githubusercontent.com/42703224/46753957-83652b00-ccc1-11e8-85d0-1b537902739e.png)

2. a végén a ládák üresek
![image](https://user-images.githubusercontent.com/42703224/46753989-97109180-ccc1-11e8-9beb-5dad2734d9f4.png)

**Comment by SaltyUmbrella** [comment]
Ugyanakkor készültek a képek, csak elraktam a tárgyakat az eszköztáramból.

**Comment by MrZero1** [comment]
Az összes napi eventen lehet repülni és üresek a ládák?

**Comment by poma123** [comment]
Egy WG hiba miatt lehet repülni és godolni. Amint lesz rá érkezésem javítom.

**Comment by poma123** [comment]
Mindkettő sikeresen javítva.
Köszi a jelentést
