### ISSUE TITLE
Telken spawnolnak tengeri lények

### ISSUE THREAD

**Issue by Viktor1969YO** [andris155/TheOld-Crafters#2461]
Eddig nem spawnolt a telek méretű akváriumomba Squid, Gömbhal, sima hal, delfin Esetleg ezt meg lehetne oldani hogy ne spawnoljanak újra? Vagy valamilyen módon kikapcsolni egyedileg?

**Comment by andris155** [comment]
Szerintem ez inkább előnyös. Ehhez nem nyúlok.
