### ISSUE TITLE
HardcoreX hiba: 2. föld lefoglalása

### ISSUE THREAD

**Issue by Icecroft** [andris155/TheOld-Crafters#2462]
Vásároltam egy old rangot, hogy lehessen egy 2. földem is, viszont a rendszer továbbra is csak 1 földet engedélyez a számomra:
![2018-10-12_23 30 32](https://user-images.githubusercontent.com/19332825/46895173-94f03380-ce77-11e8-8aac-9066027ec970.png)

**Comment by poma123** [comment]
Javítva. Köszönjük a hibajelentést
