### ISSUE TITLE
Színkód hiba - petek

### ISSUE THREAD

**Issue by SaltyUmbrella** [andris155/TheOld-Crafters#2463]
Kidob a szerver, ha beírom a /petrelease [név] parancsot egy olyan petemnél, akinek tegyük fel piros, fekete, vörös van a nevében.

**Comment by SaltyUmbrella** [comment]
De: csak akkor, ha a /petrelease parancs után tab megnyomásával írom ki í nevét, hogy időt spóroljak, akkor dob ki, mert ugye érzékeli a nemn legális színkódot.

**Comment by andris155** [comment]
kérlek küldj képet a kick üzenetről.

**Comment by SaltyUmbrella** [comment]
Elképzelhető, hogy akkor is ez történne, ha ilíesmi nevet szeretnék beállítani a petemnek? (amiben van vörös, piros vagy fekete)
![image](https://user-images.githubusercontent.com/42703224/46962707-162c0e00-d0a4-11e8-8348-bda93fc04aa2.png)

**Comment by andris155** [comment]
Csak a release-nél van ilyen hiba?

**Comment by andris155** [comment]
javítva
