### ISSUE TITLE
HardcoreX: A ládabolt nem megy levédésen + javaslat

### ISSUE THREAD

**Issue by Icecroft** [andris155/TheOld-Crafters#2465]
Szia Poma, a ládabolt nem működik levédett területen, a vásárlóim üres kézzel mennek haza. Légyszi konfiguráld be, hogy a védett területen is működjön.
Javaslat: Jó lenne, ha lehetne pénzt átutalni egymás közt

**Comment by poma123** [comment]
Egyelőre nem tudom hogyan lehetne ezt javítani, viszont a /trade parancsot kereskedésre lehet használni.

**Comment by andris155** [comment]
Elvileg javítva.
