### ISSUE TITLE
Nem "Csillagozza" ki a következő szót

### ISSUE THREAD

**Issue by SaltyUmbrella** [andris155/TheOld-Crafters#2468]
![image](https://user-images.githubusercontent.com/42703224/47022379-a67a5980-d15d-11e8-835a-1d6efcbfd95e.png)

**Comment by andris155** [comment]
Kérlek holnap teszteld le, hogy ki csillagozza-e.

**Comment by SaltyUmbrella** [comment]
még azóta sem csillagozza ki

**Comment by andris155** [comment]
javítva
330 OCD
