### ISSUE TITLE
CombatlogX - kreatív mód

### ISSUE THREAD

**Issue by SaltyUmbrella** [andris155/TheOld-Crafters#2469]
Mikor harcolok éppen/már befejeztem de tart még a Combatlog, akkor át tudok váltani kreatív módba, de ugye a repülés letiltása miatt nem enged felemelkedni. Erre bármi megoldás lehetséges?

**Comment by andris155** [comment]
Megvárod még lejár a combat. Nem akarom engedélyezni repülés közben a combat-ot.

**Comment by SaltyUmbrella** [comment]
igazából arra gondoltam, le kellene tiltani a kreatív módot is, ez egy alternatív menekülési utat jelenthet számomra, ha vesztésre állnék. mint a god-mód bekapcsolása harc közben.
