### ISSUE TITLE
Láda bug

### ISSUE THREAD

**Issue by HELLCATGHOST** [andris155/TheOld-Crafters#247]
Szia Andris! Minap történt velem 1 bug,méghozzá az hogy nemtudtam kinyitni a ládámat...
Üzenet ami fogadott a kinyitás helyett:
"Hey! Sorry,but you can't open that here.
És a zónában engedélyezve van a láda hozzáférés és a használat is.

**Comment by andris155** [comment]
Üdv!
Mi a levédés neve?

**Comment by HELLCATGHOST** [comment]
HELLCAT

**Comment by andris155** [comment]
Megoldva.
A flagok alapból védenek mindent, csak akkor kell átállítani, ha valamit nem kell, hogy védjen. Pl.: Hogy mindenki tudja nyitni a ládákat, az is aki nincs hozzáadva.
