### ISSUE TITLE
/partychat

### ISSUE THREAD

**Issue by SaltyUmbrella** [andris155/TheOld-Crafters#2473]
Ha színes üzenetet szeretnék írni a "Klán"-nak, akkor a /partychat &dSziasztok! üzenet nem lesz rózsaszín, hanem kiírja a számot is meg az "&" jelet is.
Viszont, ha bekapcsolom a /partychat-et és utána írok színesen akármit, akkor már működik.
![image](https://user-images.githubusercontent.com/42703224/47259232-f2533880-d4a6-11e8-8f34-d80e949c65b4.png)

**Comment by andris155** [comment]
Szerintem a paranccsal alapból nem lehetne színezni. Viszont ha simán írsz, akkor ugye az Essentials színezi.
