### ISSUE TITLE
/heads - oldalszám hiba

### ISSUE THREAD

**Issue by SaltyUmbrella** [andris155/TheOld-Crafters#2474]
Miután a /heads egyik menüpontjában (pl:FOOD) ellapoztam már minimum 64 oldalt, az oldalszám kiíró (a nyílvesszők száma) megakad ugye 64-en, mivel annyi a maximum érték amennyi egyszerre lehet. Erre bármi megoldás?
![image](https://user-images.githubusercontent.com/42703224/47260365-9397ba00-d4ba-11e8-8bb9-b12026b9d670.png)
![image](https://user-images.githubusercontent.com/42703224/47260366-9abec800-d4ba-11e8-8b7d-bec21e360ea0.png)

**Comment by poma123** [comment]
Ez sajnos ilyen.
