### ISSUE TITLE
Indokolatlan valami 

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#2475]
![kep](https://user-images.githubusercontent.com/29709854/47260855-5e439a00-d4c3-11e8-977c-8cdf85596caa.png)

Mindenkinek (?) kiírta ezt a cheat-es szöveget.

**Comment by andris155** [comment]
Rá fogok nézni.

**Comment by MrZero1** [comment]
Okés :)

**Comment by andris155** [comment]
Elvileg javítva.
