### ISSUE TITLE
/warp pláza

### ISSUE THREAD

**Issue by SaltyUmbrella** [andris155/TheOld-Crafters#2477]
Pontosan a /warp pláza fölött ott maradt egy Homok blokk.
![image](https://user-images.githubusercontent.com/42703224/47434243-799ff500-d7a2-11e8-9951-599814337873.png)

**Comment by SaltyUmbrella** [comment]
Meg, tudtommal már csak itt található közös láda.

**Comment by MrZero1** [comment]
Javítva. Köszönjük a hibajelentést.
