### ISSUE TITLE
Kérgezett Farönk Home / Back probléma.

### ISSUE THREAD

**Issue by yghrt** [andris155/TheOld-Crafters#2478]
Sziasztok, apró hibával jelentkeznék,

A home illetve back paranccsal ha Kérgezett Farönk blockra portolunk akkor azt ignorálva bele esünk, és nem mellé, ez problémás volt nálam mert beszorulva meg lehet halni ha duplán van. 

A videós bizonyítékot mellékelem az adott hibáról.
[https://youtu.be/fa4412l_5QI](https://youtu.be/fa4412l_5QI)

**Comment by andris155** [comment]
https://github.com/andris155/TheOld-Crafters/issues/2413
