### ISSUE TITLE
Nem lehelyezhető facsemeték. 

### ISSUE THREAD

**Issue by Denis9559** [andris155/TheOld-Crafters#2479]
Szia/sztok,
építettem egy fafarmot, de csak a föld felére tudok csemetét tenni, tovább nem engedi.
Kértem már segítséget Segítőtől valamint Főadmintól is, nem tudtak sajnos segíteni, így ide fordulok.
Üdvözlettel: Denis9559

**Comment by MrZero1** [comment]
Valóban, én sem tudtam lerakni.
