### ISSUE TITLE
GriefPrevention Flags

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#2482]
Survival szerveren levédésre szeretnének flag-eket, pvp-t hiányolják főleg. De az érintkezés is fontos.

**Comment by andris155** [comment]
https://www.spigotmc.org/resources/griefprevention-flags.55773/

**Comment by andris155** [comment]
AllowPVP
NoMobSpawns
flag-ekre adtam alapból jogot mindenkinek.
Alapból pedig nincs pvp a védéseken.
/SetClaimFlag <flag>
/UnSetClaimFlag <flag>
