### ISSUE TITLE
Kreatívbeli probléma

### ISSUE THREAD

**Issue by Kelvin172** [andris155/TheOld-Crafters#2483]
Az lenne az észrevételem, hogy régen pár hete letettem kreatívban cukornádat és kaktuszt, azonnal nem nőtt meg, de mostanra már megnőtt és túlélőmódban leszedhető és begyűjthető.

**Comment by andris155** [comment]
Letiltottam kreatívban ezeket.

**Comment by andris155** [comment]
508 OCD
