### ISSUE TITLE
ChestShop nem ismeri fel a tárgyakat ID alapján

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#2484]
Próbáltam egy Lucky Block-os ládaboltot nyitni, de hiába írtam a táblára számos ID-vel, head, skull névvel, ezt a hibát kaptam:

![kep](https://user-images.githubusercontent.com/16057404/47913114-2eb96800-de9b-11e8-871c-55cafe660305.png)

Player_head-al engedi, de azzal nem fér ki a táblára az egész ID (player_head#1F), így nem használható a bolt. 

Nem csak a fejekkel van ez, egyik tárgynál se ismeri fel a számos ID-t, vagy a rövid neveket.

**Comment by andris155** [comment]
Nem létezik már számos ID.

**Comment by UDPSendToFailed** [comment]
A rövidebb neveket se lehet megoldani, hogy működjenek?

**Comment by andris155** [comment]
Utána fogok nézni mi van ilyenkor. Tuti gondoltak rá a Chestshop-nál.

**Comment by andris155** [comment]
![2018-11-02_15 41 07](https://user-images.githubusercontent.com/8324198/47921785-bca24c80-deb5-11e8-83ff-c1118f9bbc5f.png)
Nem kell hozzá _ és így működik.
