### ISSUE TITLE
Mob ölés.

### ISSUE THREAD

**Issue by Bannoltboci** [andris155/TheOld-Crafters#2487]
Nem lehet mobot ölni a vadonban nem levédett területen. EDIT:Saját telken sem lehet.
![2018-11-03_10 37 32](https://user-images.githubusercontent.com/43493917/47950644-40f7dc80-df55-11e8-8234-1daedc4d9cf1.png)

**Comment by Bannoltboci** [comment]
![2018-11-03_11 07 12](https://user-images.githubusercontent.com/43493917/47950841-aac5b580-df58-11e8-863f-af58794c75e2.png)

**Comment by andris155** [comment]
javítva
