### ISSUE TITLE
pvp levédés hiba

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#2488]
semmit se lehet sebezni levédésen bellül. Az se tud pl állatot sebezni, akié a terület.
Ez a hiba mindenkinél előfordul.

**Comment by Bannoltboci** [comment]
Lehet sebezni csak a /setflag allowpvp-t kell beírni hozzá. :D Inkább az a gond hogy ott nem lehet ölni ahol nincs levédve.. ._.

**Comment by andris155** [comment]
megoldva
