### ISSUE TITLE
falusi bug

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#2489]
Ha megnyitok egy falusit, fél mp-re látom mit ad és vége, kidob a falusiból. Nagy nehezen megoldottam hogy ne dobjon ki, minden szipi szuper, eltpzek vissza, és megint kidob belőle. Nem minden falusinál van ez, tök random jön elő a falusiaknál (ilyen eddig nem volt)

**Comment by Icecroft** [comment]
Ez a bug tegnap délután óta (11. 02.) a Poma reset után HardcoreX-en is jön.
