### ISSUE TITLE
Bugok a tegnapi reset óta (11.02.)

### ISSUE THREAD

**Issue by Icecroft** [andris155/TheOld-Crafters#2491]
1.) A falusik viselkedése megváltozott (lásd #2489 issue)
    - a falusi menüje csak fél másodpercre villan fel random módon
    - a falusik nem lépnek rá (nem is tolhatóak rá) sínekre
    - a falusik nem csoportosulnak éjszaka (ez nem is hiányzik)

2.) Ha a Hatékonyság 5 baltával aratom a dinnyét és tököt, van olyan blokk amit 4-8-szor is ki kell ütni. Korábban csak végig szaladtam a soron és kész. Most elég lassú lett a dolog.

3.) A vízre bocsátott csónak elsűllyed. Nem lehet csónakkal közlekedni!

**Comment by andris155** [comment]
Kérlek holnap ellenőrizd le ezeket. Elvileg meg kell oldódni ezeknek a hibáknak a szerverfájl frissítéssel.

**Comment by Icecroft** [comment]
Szia Andris! HardX-en leellenőriztem mindhárom jelentett problémát, zökkenőmentesen megy minden újra.

**Comment by andris155** [comment]
szuper, köszi
