### ISSUE TITLE
Block törés.

### ISSUE THREAD

**Issue by Bannoltboci** [andris155/TheOld-Crafters#2492]
Ásásnál (Hatékonyság 5 gyémántásó) visszateremnek a blockok és többször is ki kell őket ütni
Állítólag bányászásnál is így van de erről nem tudok nyilatkozni. //Videó hamarosan//

**Comment by Bannoltboci** [comment]
**a videó a világ legrosszabb minőségében van de a lényeg látszik, több játékos is írta chatre hogy valami nem okés mivel többször kell kiütniük a blockot tehát nem nálam van a hiba**
https://www.youtube.com/watch?v=DU1VXk7Mwrw

**Comment by Bannoltboci** [comment]
![2018-11-03_22 42 48](https://user-images.githubusercontent.com/43493917/47957644-3c194400-dfba-11e8-9704-2cc02565732b.png)

**Comment by andris155** [comment]
https://github.com/andris155/TheOld-Crafters/issues/2491
