### ISSUE TITLE
Napi eventeken potizás.

### ISSUE THREAD

**Issue by Bannoltboci** [andris155/TheOld-Crafters#2493]
Ha /ec be beteszed a potit PL: Telken majd elmész a napievent kezdőhelyéről  és ott ECből kiveszed a potit, beiszod akkor rajtad marad az  effekt. Tipp: /ec parancs letiltása úgy mint a /fly és társait.
![2018-11-03_22 53 08](https://user-images.githubusercontent.com/43493917/47957719-63bcdc00-dfbb-11e8-8fd0-f81a96a75969.png)

**Comment by MrZero1** [comment]
Elvileg javítva, de azért megpróbálnád ismét? @Bannoltboci
