### ISSUE TITLE
Tárgy felvétel hiba

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#2495]
Ha kitöltöm az inv-em homokkal, nem veszi fel a földön lévőt. 

https://youtu.be/HaqzllQ5pAA

**Comment by andris155** [comment]
Fura egy bug. Egyjátékos módban nem így van.

**Comment by andris155** [comment]
Szerintem ez nem olyan óriási hiba. A szerverfájl készítőnek jelentettem. Egyelőre nincs megoldás.
