### ISSUE TITLE
Nem lehet a /ec parancsot használni a boltban.

### ISSUE THREAD

**Issue by baawoof** [andris155/TheOld-Crafters#2497]
a címbe ott van minden
![2018-11-05_20 54 50](https://user-images.githubusercontent.com/43015473/48023073-149eb480-e13d-11e8-9983-3337710b39d6.png)

Ja és valaki szóljon már a staff csapatnak ha nem tudja a kérdésre a választ akkor legalább ezt írja a kérdésre mert az ha nem ír semmit az nem segít. (pl sweetan)

**Comment by MrZero1** [comment]
Raktunk le 2-2 enderládát minden részhez, sajnos az eventek miatt lett letiltva. Mellesleg erre való a helpop, a global chat elúszik.

**Comment by baawoof** [comment]
Minden tábla alá kellene egy láda az a 2 semmit nem ér ott, vagy ha nem akkor meg az OCD-t vissza akarom igényelni mert így használhatatlan.

**Comment by MrZero1** [comment]
Biztosan sok idő odafordulni.

**Comment by baawoof** [comment]
28 db ládát kell kipakolni, ha egyről lenne szó nem lenne gond.

**Comment by MrZero1** [comment]
Esetleg átrakhatom másik világba a boltot, pl a spawn világba, és akkor petet is lehet előhívni.

**Comment by baawoof** [comment]
Van itt megoldás csak ki kell mindig húzni az emberből :/

**Comment by MrZero1** [comment]
Nem kell, csak le kell írni nyugodt hangnemben.. :D

**Comment by baawoof** [comment]
De nem tudom leírni nyugodt hangnemben mikor fel idegesít az admin hogy "Valószínű azért nem válaszoltunk mert nem tudjuk a választ" és nekem ezt tudnom kéne na ez basz fel

**Comment by MrZero1** [comment]
Miért nem írsz nekem inkább? xd

**Comment by MrZero1** [comment]
Megpróbálom átvinni majd, de addig vannak enderládák
