### ISSUE TITLE
GriefPrevention elírások. 

### ISSUE THREAD

**Issue by Bannoltboci** [andris155/TheOld-Crafters#2498]
A legelső képen : " Levédve Bannoltboci álltal" ( Az által 1 L-el helyes.)
2. képen:  "Megoszt barátaiddal"  (Nekem valahogy ez a szócska nem nagyon szimpatikus. A megoszt az egyes szám 3. személy pl: Ő megoszt valamit a facebookon. De az hogy TE megossz valamit az nem igazán így van (zárójelben zárójel, ha valamit esetleg én is elnéznék azért elnézést). )
3. A félbe szócskáról lekerült az ékezet. 

![2018-11-05_21 41 42](https://user-images.githubusercontent.com/43493917/48025866-d60cf800-e144-11e8-8508-71c5e46b9c86.png)
![2018-11-05_21 17 36](https://user-images.githubusercontent.com/43493917/48025887-ddcc9c80-e144-11e8-8754-64d7beb7be15.png)
![2018-11-05_21 17 03](https://user-images.githubusercontent.com/43493917/48025927-f89f1100-e144-11e8-92c9-ddb226988c56.png)

**Comment by Bannoltboci** [comment]
Ládát szerettem volna kinyitni másnak a levédett területén de ez a mondat fogadott. "Kérj Woltix tőle"
![2018-11-05_22 07 57](https://user-images.githubusercontent.com/43493917/48026786-4f0d4f00-e147-11e8-9975-33d1c71532c4.png)

**Comment by andris155** [comment]
javítva 1016 OCD
