### ISSUE TITLE
Levédés fordítás

### ISSUE THREAD

**Issue by FelberDani** [andris155/TheOld-Crafters#2499]
Van egy levédés, ha nem vagy hozzáadva és megpróbálsz kinyitni egy ládát, ezt a hibaüzenetet írja ki:
Nincs engedélyed,hogy ezt használd.  Kérj dani_13(%player%) tőle.
Ezt lehetne pontosítani,hogy Kérj %player% tól/től
Vagy esetleg kérj engedélyt,hogy ezt használhasd.

**Comment by Bannoltboci** [comment]
#2498 Hamarabb írtam :v:  :D
