### ISSUE TITLE
Pet öltöztetés

### ISSUE THREAD

**Issue by Ladykutya** [andris155/TheOld-Crafters#250]
Ha ráraksz páncél a petedre, akkor a peted is felhúzza, meg te  is. Ugyan nem ad páncél bónuszt, és ha le akarod venni, vagy  egy másik világba teleportálsz, akkor  eltűnik rólad, de a kinézeted alapján ott van rajtad.

**Comment by Kronox12** [comment]
Grafikai bug, sok jelentősége nincs. Bár ha kell, jelentem a fejlesztőnek.

**Comment by Ladykutya** [comment]
Nem zavar, csak gondoltam szólok :D
