### ISSUE TITLE
Info parancs

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#2500]
![kep](https://user-images.githubusercontent.com/29709854/48026866-9267bd80-e147-11e8-9a42-dead3d4d8aef.png)

Ugye rossz az info parancs, viszont vannak olyan információs boxok, amikben a /info van, ezeket átlehetne írni /inform-ra vagy olyanra, ami jó?

**Comment by andris155** [comment]
átírva
