### ISSUE TITLE
Információ bugok a spawn világban.

### ISSUE THREAD

**Issue by Sarberon** [andris155/TheOld-Crafters#2501]
https://youtu.be/yRzJKgnR68A

A videóban látható, amint próbálok kattintani az egyik opcióra a /informacio menüben, és bárhogyan is próbálkozok nem enged. Ezt a hibát eddig csak a spawn világban észleltem.

**Comment by andris155** [comment]
Még azt se tudom melyik plugin ez. xd

**Comment by andris155** [comment]
Ez poma megoldása.

**Comment by Sarberon** [comment]
Csakhát, playereknek zavaró lehet hogy a GUI-ban nem tudnak semmit sem megnyitni. :D

**Comment by poma123** [comment]
a plugin a /info <szoveg> parancsot futtatja le, es mivel a we belekotnyeleskedik az aliasba ezert nem az essentials info parancs futodik le

**Comment by poma123** [comment]
futtassa azt akkor

**Comment by poma123** [comment]
info aliasnak beteve commandsba
