### ISSUE TITLE
A Wither pet és Wither skill probléma

### ISSUE THREAD

**Issue by TamasB14** [andris155/TheOld-Crafters#2502]
90-es szinten se lehet használni a jelzőfény skill-t
![2018-11-06_15 05 09](https://user-images.githubusercontent.com/26002677/48069469-e0c39d80-e1d5-11e8-99f9-4d8d6bd339a4.png)

**Comment by TamasB14** [comment]
Mióta megvettem, olyan pár hónapja, azon nap már nem kaptam semmilyen skill-t, még 18-as level volt akkor.

**Comment by TamasB14** [comment]
Szerintem a minemarket előzményekben megtudod nézni mikor vettem.

**Comment by TamasB14** [comment]
Körül-belül azóta nem működhet, amióta a reset volt. Kivéve persze, ha mások megvették azután és működött. Ki kellene matematikázni! Megkérdezni azokat akik még én előttem vették, hogy működik-e nekik, ha igen, akkor ezt valamikor későbben csinálta. Egy skála példának 

Reset- - - (1. Ember)Működik - - - (2. Ember)Működik - - - (Időpont mióta nem működik)- - - - (Én)Nem működik.

**Comment by andris155** [comment]
javítva
