### ISSUE TITLE
Táblák optifine-al

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#2503]
Optifine-al azok a táblák, amiken hosszabb szöveg van, nem jelennek meg normálisan, így értelmetlen lesz a leírás. Sima minecrafttal jó, de ha már belépéskor is hirdetve van az optifine használata, szerintem érdemes lenne átírni ezeket. A legtöbb ilyen a craftbook warpon található, de a többi plugin leírásánál is van pár.

![kep](https://user-images.githubusercontent.com/16057404/48080928-2c367580-e1ef-11e8-9cf0-624014c95ebb.png)
![kep](https://user-images.githubusercontent.com/16057404/48081477-73713600-e1f0-11e8-96aa-5e24aa5c900a.png)

**Comment by andris155** [comment]
Az optifine jó. Használj más forráscsomagot.

**Comment by MrZero1** [comment]
Sajnos ez minden táblánál így van, viszont emiatt átírni nem fogjuk. Reméljük majd ezt javítják vagy valami.

**Comment by andris155** [comment]
A forráscsomagból ha kiszeded az egyedi betűtípust már jó is. Bár én mostanában az újabb Minecraft-ost használom ami szerintem egész jó lett.
