### ISSUE TITLE
GriefPrevention fordítás fejlesztések 2

### ISSUE THREAD

**Issue by Bannoltboci** [andris155/TheOld-Crafters#2505]
Ha építeni szeretnék mások levédésén akkor ezt írja. "Nincs xy engedélyed , hogy itt építs." 
Jobb lenne ha úgy lenne átírva mint a másik pl: "Nincs engedélyed , hogy itt építs. Kérj engedélyt tőle XY. :)

![2018-11-06_18 51 06](https://user-images.githubusercontent.com/43493917/48084494-298c4e00-e1f8-11e8-87b1-5a84b1d305f5.png)
![2018-11-06_18 54 54](https://user-images.githubusercontent.com/43493917/48084498-2beea800-e1f8-11e8-9ea3-7c8a70225e3d.png)

**Comment by FelberDani** [comment]
Ejj, már megint beelőztél :D

**Comment by andris155** [comment]
Niythatnál pull request-et a javításokkal.
https://github.com/andris155/TheOld-Crafters/blob/master/Ford%C3%ADt%C3%A1sok/GriefPrevention/messages.yml

**Comment by andris155** [comment]
javítva
