### ISSUE TITLE
GriefPrevention 3

### ISSUE THREAD

**Issue by Bannoltboci** [andris155/TheOld-Crafters#2508]
Tegnap ( @andris155 )küldtél 1 linket a jelentésem alá. Az a helyzet hogy azt nem nagyon tudom hogy kell átírni vagy egyáltalán mit kell vele csinálni. Discordon is leírtam de azért ide is kiírom biztos ami biztos mielőtt valaki beelőz mivel jól jön az az OCD mennyiség. =D 

527 ResizeClaimTooNarrow:
    Text: Ez a levédés túl kicsi. Bármilyen levédés minimum {0} blokk szélesnek kell
      lennie.blokk szélesnek kell lennie.

517  BookDisabledChestClaims:
    Text: Ezen a szerveren, ha leteszel egy ládát, az NEM fog levédni telet is körülötte!

  429 AdvertiseACandACB:
    Text: Használhatod az /ACB-t, hogy adj meg több levédés blokkot, vagy /AdminClaims-ot
      egy ingyenes Admin levédés létrehozásához.

  390 NoTNTDamageClaims:
    Text: 'Figyelmeztetés: A TNT nem fog blokkokat elpusztítani levédet területen.'

 380  UnclaimCleanupWarning:
    Text: A földön, aminek feloldottad a levédését, lehet, hogy más játékosok építeni
      fognak, vagy egy Admin meg fogja tisztítani. Ha valamit építettél ott és meg
      akarod tartani, lehet vissza kéni vonni a feloldást.

  372 BuildingOutsideClaims:
    Text: Más játékosok is építhetnek itt. Gondolkozz el a terület levédésen, hogy
      megvéd, amit építesz!

 351 ConfirmFluidRemoval:
    Text: Ha elhagyod ezt a levédett terület, a benne lévő lává el lesz távolítva.
      Ha biztos vagy akkor /AbandonClaim újra!

 125  NoSiegeDefenseless:
    Text: Ez a játékos védtelen. Válasz egy számodra egyenlő ellen felett.

92  DeletionSubdivisionWarning:
    Text: Ez az levédés, parcellákat tartalmaz. Ha biztos vagy benne, hogy törölni
      szeretnéd, használd ismét a /DeleteClaime-t.

**HIBÁK**
92 hiba: " Ez az levédés. " <-- (Ez a levédés* és a /deleteclaime parancs nem létezik. Az az E betű a végén felesleges. )
125 hiba: "Válasz", "ellen felett" <-- (Válasz helyett láva, ellen felett-et egybe kell írni 1 T vel a végén.)
351 hiba: a benne lévő "lává" el lesz távolítva <-- (A lává helyett láva)
372 hiba: hogy "megvéd", amit építész <-- (A megvéddet 2dvel kellett volna írni)
380 hiba: lehet vissza "kéni" vonni a feloldást.  <-- (Kéni helyett kéne)
390 hiba: A TNT nem fog blokkokat elpusztítani "levédet" területen <--( Levédet helyett levédett)
429 hiba: Használhatod "az /abc-t" <--( a /acd-t"
517 hiba: az NEM fog levédni telet is körülötte! <-- (Levédni helyett levédeni, A telet helyett nem tudom mi a helyes oda de biztos nem Telet kellett volna írni. :D)
527 hiba: 2x van leírva hogy blokk szélesnek kell lennie

**Comment by andris155** [comment]
Miért nem pull request-et nyitottál? Neked is egyszerűbb lett volna sokkal.

**Comment by Bannoltboci** [comment]
Mivel arra még nem sikerült rájönnöm hogy mit is kell azután csinálni miután rákattintottam. Ez nekem gyorsabbnak,egyszerűbbnek tűnt.

**Comment by andris155** [comment]
Az eredeti fordításban is ACB van.

**Comment by andris155** [comment]
508 OCD
