### ISSUE TITLE
Átírandó Wither leírás a Minemarketen.

### ISSUE THREAD

**Issue by Kronox12** [andris155/TheOld-Crafters#251]
Új leírás:
Több információ a Wither-ről: http://minecraft.gamepedia.com/Wither

/pcst - Wither - Külön képességek csak a withernek:

A peted a 90. szinten ezekkel a képességekkel fog rendelkezni:

 - Jelzőfény: Erő II, Elnyelt Életerő II, Magasugrás I, Regeneráció I, Védelem II, Tűzállóság I, Sietség II
 - Irányítás
 - Viselkedés Módok: Normál, Barátságos, Agresszív, Farm, Párbaj
 - Sorvasztás: 75% -> 15 mp
 - Élet: +25.0
 - Sprint
 - Pajzs: 40% esély -> Játékosra Mért Támadások Erősségének 80%-a
 - Élet regeneráció: +25.0 HP -> 1 mp
 - Dobbantás: 50% -> 15.0 sebzés
 - Lovaglás: gyorsaság: +50% (Tud repülni)
 - Tárgyfelvétel: Hatótávolság: 3,00 Blokk
 - Távolsági Sebzés: 15,38 lövés/perc -> 45.0 ütés
 - Sebzés: -> 30.0 sebzés
 - Tüske: 30% -> 45% sebzés
 - Táska: 3 Sor.

**Comment by andris155** [comment]
köszi
