### ISSUE TITLE
Minemarket - A Felhasználónév már foglalt

### ISSUE THREAD

**Issue by lDefalt** [andris155/TheOld-Crafters#2510]
Egy héttel ez előtt vettem az LDefalt nevű accontra rangot. Beléptem ma ugyan azzal az e-mail címmel amivel előtte és a nevem más lett nem LDefalt. Próbáltam visszaváltoztatni de vagy azt írja hogy foglalt vagy azt hogy Hibás név váltás.

**Comment by andris155** [comment]
Sajnos ezt csak új névre váltással lehet megoldani.
