### ISSUE TITLE
Border és az ender bow

### ISSUE THREAD

**Issue by geriboy09** [andris155/TheOld-Crafters#2513]
19:34-kor véletlen kilötem az ender bow-ot és kidobot a borderen kivül, és egyből one shotolt így minden cucom oda veszet, Mrzero probálta megkeresni, több kevesebb sikerrel. Így most semmim nincs eszközök terén. bye: Database

**Comment by andris155** [comment]
Logikus, hogy ha a világhatáron kívülre kerülsz meghalsz ez nem a mi hibánk.

**Comment by geriboy09** [comment]
de eddig sose volt még ilyen, kiirt valamit h nem birsz átmenni v valami :X
