### ISSUE TITLE
Új minigame hiba (?)

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#2514]
![kep](https://user-images.githubusercontent.com/29709854/48230512-8f6d0700-e3ab-11e8-81f6-26c1ea2f01b0.png)

Tesztként 2 játékossal játszottunk 2 kört, és megmaradt nekik az XP, amit összeszedtek a játék alatt.
A hajnali resi után megnézzük, megmarad e ismét, ha igen, jelzem.

**Comment by andris155** [comment]
Szerintem erre nincs megoldás.

**Comment by andris155** [comment]
javítva
