### ISSUE TITLE
Lands fordítás - 2540 OCD

### ISSUE THREAD

**Issue by andris155** [andris155/TheOld-Crafters#2522]
A /land parancsot nem kell /földre fordítani. A jövőben csak a /land vagy /lands fog működni.
https://github.com/andris155/TheOld-Crafters/tree/master/Ford%C3%ADt%C3%A1sok/Lands

**Comment by mdtank** [comment]
Elkezdem

**Comment by brtamas0** [comment]
készül

**Comment by andris155** [comment]
Az OCD-t legminőségibb fordítást készítő kapja. Nem aki a leggyorsabb. Célszerű lehet összedolgozni és akkor felesben kapjátok az OCD-t

**Comment by brtamas0** [comment]
mdtank tied a gui. az rövidebb.

**Comment by brtamas0** [comment]
van amihez picit hozzá toldok mert ismerem a plugint és használtam és az alap mondattal nekem van hogy nem esett le mit kell tennem.

**Comment by mdtank** [comment]
Most fejeztem be a hosszabbat

**Comment by mdtank** [comment]
A GUI-nál csak a lore texteket kell fordítani? a felső néhány sor nekem változóknak tűnnek.

**Comment by mdtank** [comment]
a GUI-t meghagyom brtamas-nak

**Comment by brtamas0** [comment]
akkor feltöltöm majd mind 2-t :/

**Comment by brtamas0** [comment]
Mdtank
van egy probléma. végig telekhez igazítottad csak hogy ez levédés és olyan mint a zmod

**Comment by brtamas0** [comment]
bocsi hogy belekötök

**Comment by brtamas0** [comment]
Ja és Mdtank pont után nagybetű :)

**Comment by brtamas0** [comment]
hova lehet föltölteni?

**Comment by mdtank** [comment]
https://github.com/mdtank/TheOld-Crafters/blob/patch-1/Ford%C3%ADt%C3%A1sok/Lands/hu-HU.yml

Átfogalmaztam a telket területre és javítottam kisebb hibákat.

**Comment by brtamas0** [comment]
oké :) Én már feltöltöttem. Ha gondolod keress hibákat :)

**Comment by brtamas0** [comment]
készül a Gui yml

**Comment by brtamas0** [comment]
Bár nem hiszem hogy lesz erőm mert ebbe a 300sorba is belement 5órám

**Comment by brtamas0** [comment]
de elkezdem. remélem megkapom az 5000ocd-t mert kell rangra és nincs pénzem :(

**Comment by Bannoltboci** [comment]
Ha együtt csináljátok akkor felesbe kapjátok. 


https://github.com/mdtank/TheOld-Crafters/blob/patch-1/Ford%C3%ADt%C3%A1sok/Lands/hu-HU.yml
Ezt végignéztem, nem találtam egyetlen hibát sem. Szép munka! :)

**Comment by mdtank** [comment]
Rendben, meghagyom a GUI-t Tamásnak.

**Comment by brtamas0** [comment]
Köszönöm :) Remélem lesz erőm megcsinálni. kifolyt a szemem és a végén jöttem rá hogy van blackground

**Comment by brtamas0** [comment]
He eltünt a munkám... hova kell feltölteni?

**Comment by brtamas0** [comment]
https://github.com/mdtank/TheOld-Crafters/compare/patch-1...brtamas0:patch-2

**Comment by mdtank** [comment]
https://github.com/andris155/TheOld-Crafters/pull/2526/files itt van egy pull request

**Comment by andris155** [comment]
A hu-HU fordítás kész mdtanknak köszönhetően. 2540 OCD-t kapott érte.

**Comment by andris155** [comment]
Milyen névre adjam?

**Comment by mdtank** [comment]
név: yak

**Comment by mdtank** [comment]
tamas, nem csinálod a GUI-t?

**Comment by brtamas0** [comment]
csinálom

**Comment by brtamas0** [comment]
csak jóval több mint a másik :D a másikba van 100sor olyan amit nem kell fordítani
itt meg max 30

**Comment by brtamas0** [comment]
holnapra kész lesz remélem

**Comment by brtamas0** [comment]
még 150sor

**Comment by poma123** [comment]
![image](https://user-images.githubusercontent.com/25465545/48979477-938f6900-f0bb-11e8-8876-688fcf505a20.png)
Lehet máskor nem kellene ennyire elsietni a fordítást :D Nem csak itt van ilyen hiba.

**Comment by brtamas0** [comment]
[halffinished.txt](https://github.com/andris155/TheOld-Crafters/files/2613311/halffinished.txt)

**Comment by brtamas0** [comment]
akinek van kedve, fejezze be. Nincs időm rá. Remélem tetszik, nem várok érte semmit

**Comment by poma123** [comment]
Nem tudom, én anno amikor a szervert raktam össze, 2 és fél órán belül lefordítottam mindkettő fájlt hibátlanul úgy, hogy nem volt felajánlva érte semmi se. Na mindegy

**Comment by andris155** [comment]
annyit frissítik ezt a plugin-t, hogy nem is igazán érdemes lefordítani.

**Comment by mr00000** [comment]
kaka pisi
