### ISSUE TITLE
Forráscsomag hiba lehet?

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#2523]
Akárhogy próbálok csinálni kalapácsot, néhány itemből nem lehet. Vagyis lehet, csak mást mutat.

![kep](https://user-images.githubusercontent.com/29709854/48376060-0b2bc400-e6ca-11e8-9cc3-3f3594fbbe6c.png)

**Comment by AwesomeFM** [comment]
Ezeknél is mást mutat, mint kéne.

![2018-11-12_22 31 31](https://user-images.githubusercontent.com/18013708/48376389-0ca9bc00-e6cb-11e8-8ebd-ac44748d69e2.png)
![2018-11-12_22 31 36](https://user-images.githubusercontent.com/18013708/48376392-0ca9bc00-e6cb-11e8-88ef-f5ba213317da.png)

**Comment by andris155** [comment]
Melyik szerver? Milyen verzió? Melyik forráscsomag? Az amit a szerver használ vagy te szedted le még régebben?

**Comment by andris155** [comment]
De Github-ról van, vagy az amit a szerver felajánl belépésnél?

**Comment by MrZero1** [comment]
Githubról van

**Comment by andris155** [comment]
Akkor azt töröld ki és használd azt amit a szerver küld belépésnél. Az csak arra volt, hogy ameddig 1.12.2-es volt a szerver addig aki 1.13-al lépett be annak is működjön.

**Comment by MrZero1** [comment]
Értem. Köszi! :D Szerintem sokaknak még az van meg amit akkor kellett leszedni githubról

**Comment by andris155** [comment]
Majd írni kellene a csoportba erről szerintem.
