### ISSUE TITLE
Sárkány pet magasabban ülés és blockba bugolás

### ISSUE THREAD

**Issue by DanikaLike3** [andris155/TheOld-Crafters#2527]
Hali.
**Ugye köztudott ,hogy a sárkány pet kicsit bugos a mypet pluginban.**

A Sárkányt beállítottam **"Ride"** üzemmódra, craftoltam egy lasszót és felültem rá, az első dolog ami szembetűnt az az, hogy **a petre amikor ráülök kb. 5 blockkal magasabban ülök mint maga a sárkány.**

itt van 2 kép is:
[https://imgur.com/gallery/pbFo00K](url)
[https://imgur.com/gallery/zgSFBhT](url)

Ebből adódóan **amikor elküldöm alólam a sárkányt (/psa),de egy block van alattam:**
A: **Felkerülök a block tetejére.**
B: **Belebugolok a blockba és nem tudok csak telekre tpzni.**. 
_(a következő csak személyes probléma)_ Viszont amikor a telekre a home-ra tpzek (/p home), 24,000 blockkal arrébb dob le a home valódi koordinátáitól és instant meghalok. Ha backelek akkor is instant halál.

**Comment by andris155** [comment]
Nem véletlen van kiírva, hogy ALPHA.
