### ISSUE TITLE
/m [név] hiba

### ISSUE THREAD

**Issue by SaltyUmbrella** [andris155/TheOld-Crafters#2528]
Mikor írnék az egyik játékosnak, aki (kihangsúlyozom) fent van a szerveren, ez a hibaüzenet fogad:
![1](https://user-images.githubusercontent.com/42703224/48509305-080f1000-e851-11e8-9c46-bce60c4dd716.png)
![2](https://user-images.githubusercontent.com/42703224/48509307-08a7a680-e851-11e8-89a4-d134706ed195.png)

**Comment by andris155** [comment]
A szerverkezelő volt reload-olva ezért nem működött.
