### ISSUE TITLE
HardcoreX: Zombik átváltozása nem megy

### ISSUE THREAD

**Issue by Icecroft** [andris155/TheOld-Crafters#2530]
A spawnolt zombikat ha megfullasztottam, akkor átváltoztak vízbefúlt harcossá. Egy jó pár napja, ez nem történik meg, az átváltozás hangja ugyanaz, de eltűnik a mob, nem marad helyette vízbefúlt harcos.

**Comment by andris155** [comment]
Frissítem majd a szerverfájlt.

**Comment by andris155** [comment]
Most működik?

**Comment by Icecroft** [comment]
Kipróbáltam, nem megy.
Tegnap Sweetannal kisérleteztünk, azt mondta, hogy levédetlen területen az átváltoztatás gond nélkül megy. Ez a hiba kb akkor jelent meg, amikor utoljára a levédéseket módosítottátok a Hardcore-on.

**Comment by andris155** [comment]
melyik flag ez?

**Comment by Icecroft** [comment]
/földek menu => Settings => Land settings
![2018-11-18_16 13 38](https://user-images.githubusercontent.com/19332825/48674493-39d3ef80-eb4d-11e8-9b90-09a7f997439a.png)
Ha ráklikkelek, azt mondja, hogy nincs jogom hozzá:
![2018-11-18_16 14 01](https://user-images.githubusercontent.com/19332825/48674499-4f491980-eb4d-11e8-9ac7-a0c4686a3653.png)

**Comment by andris155** [comment]
Most engedélyezve van?

**Comment by Icecroft** [comment]
Még mindig nincs jogom változtatni. Ugyanaz a szituáció, mint korábban.

**Comment by andris155** [comment]
De nem állítani hanem, hogy alapból mire van-e állítva?

**Comment by Icecroft** [comment]
Alapból a mobok spawnolása le van tiltva, ez az 1. screenshoton jól látszódik:
"Status: Nem"

**Comment by andris155** [comment]
Megfogom majd nézni akkor bővebben.

**Comment by Icecroft** [comment]
A legjobb lenne, ha mindenki maga állíthatná be, hogy mit akar, azaz az első screenshoton az Unlocked: Nem helyett jobb volna az igen.

**Comment by andris155** [comment]
Egyetértek

**Comment by andris155** [comment]
Adtam rá jogot.

**Comment by Icecroft** [comment]
Sikerült átállítanom, elméletileg kellene spawnolniuk a moboknak a levédésemen is, de egyenlőre nem teszik.
Próbálkoztam egy reloginnal, de utána sem. A zombik átalakulása sem megy továbbra sem.
Vajon miért nem spawnolnak a mobok?

**Comment by andris155** [comment]
Lands fejlesztő: “Nvm, found the issue. Forgot to change this. Bugfix will be online tomorrow.
Thanks for reporting! :)„

**Comment by Icecroft** [comment]
Köszi az infót, várjuk a "holnapra" ígért update-et. :)

**Comment by andris155** [comment]
javította a fejlesztő.
