### ISSUE TITLE
Zombie Villager

### ISSUE THREAD

**Issue by SaltyUmbrella** [andris155/TheOld-Crafters#2533]
Zombi Falusi petet fogtam be, csak az az egy gondom van vele, hogy láthatatlan.
![image](https://user-images.githubusercontent.com/42703224/48663498-7b9f6000-ea91-11e8-99b1-49c0f0f60eed.png)

**Comment by andris155** [comment]
más sem látja?

**Comment by andris155** [comment]
Ezt ajánlom: https://www.microsoft.com/hu-hu/software-download/windows10

**Comment by SaltyUmbrella** [comment]
nem látta pl: Dani_13 sem

**Comment by andris155** [comment]
javítva
