### ISSUE TITLE
Additions repair jog Survival

### ISSUE THREAD

**Issue by poma123** [andris155/TheOld-Crafters#2534]
Nincs jog /additions repairhoz [v.i.p.+]-ként (ami az old jogai elvileg) és [v.i.p.]-től van /additions repair.
![image](https://user-images.githubusercontent.com/25465545/48663648-76431500-ea93-11e8-852e-b65130e792b8.png)

**Comment by andris155** [comment]
A savszigeten javítva.

**Comment by andris155** [comment]
A survival-on lehetetlen ez a hiba.

**Comment by poma123** [comment]
nem lehetetlen a hiba, tegnap még nem működött, ott készült a kép is :) most már jó köszi
