### ISSUE TITLE
Lucky Block - Repülő XP palack

### ISSUE THREAD

**Issue by SaltyUmbrella** [andris155/TheOld-Crafters#2535]
Eddig a denevérek, amiknek a "hátán" vannak az xp palackok, láthatatlanok voltak, de most láthatóak, és eléggé érdekes látványt nyújtanak.

**Comment by andris155** [comment]
Más is látja?

**Comment by SaltyUmbrella** [comment]
volt mellettem egy másik játékos, ő is elcsodálkozott a látványon

**Comment by andris155** [comment]
tudsz róla képet csinálni?

**Comment by andris155** [comment]
F2-vel csak a játékról készít képet.

**Comment by SaltyUmbrella** [comment]
naszóval, skrisz01 barátom segített a tesztelésben, és neki láthatatlanok voltak a denevérek. Nem tudom, változtattatok-e valamit azóta vagy nálam volt a gond, de megjavult, úgy néz ki.

**Comment by andris155** [comment]
Akkor ez megoldódott.
