### ISSUE TITLE
Búvárkodás közben emelkedés (SavSziget)

### ISSUE THREAD

**Issue by CoolIfAI** [andris155/TheOld-Crafters#2537]
Savsziget Búvárkodás közben emelkedéskor rángat, állandóan visszaesek egy keveset.
Illetve nem tudok shift-szóközzel lerakni aktív objektumokat pl. csapóajtó egymásra.
1.12.2-ben ez problémamentes volt,

**Comment by andris155** [comment]
Most jó?

**Comment by CoolIfAI** [comment]
Képernyőkép:
![2018-11-21_21 28 09](https://user-images.githubusercontent.com/25465311/48866858-95fc7500-edd4-11e8-9310-017928e42211.png)

**Comment by andris155** [comment]
Akkor a hiba javítva. A csapóajtósra szerintem nem igazán van megoldás.
