### ISSUE TITLE
Inventory törlődés

### ISSUE THREAD

**Issue by Bannoltboci** [andris155/TheOld-Crafters#2538]
Ha /gm 1 ben beírod hogy /lobby és visszalépsz a szerverre ahonnan kiléptél és visszaváltasz gm0ba akkor üres lesz az inventoryd. Ennek hála elbuggolt 1 oldkardom amit Zero már vissza adott.

**Comment by poma123** [comment]
https://www.youtube.com/watch?v=jFpzN2v6YdE

**Comment by Bannoltboci** [comment]
Köszönöm. Az én gépem kenyérpirító ahhoz hogy ne laggoljon a kép felvételnél.

**Comment by andris155** [comment]
Letiltottam kreatívban. A fejlesztő tud a hibáról.
