### ISSUE TITLE
Recept könyv 1.12.2 -> 1.13.2

### ISSUE THREAD

**Issue by CoolIfAI** [andris155/TheOld-Crafters#2539]
Savszigeten a recept könyv megnyitásakor kidob a program, azzal az üzenettel, hogy "[Proxy] Megszakadt a kapcsolat a szerverrel.".

**Comment by andris155** [comment]
https://github.com/andris155/TheOld-Crafters/issues/2541

**Comment by CoolIfAI** [comment]
Értem én, nehogy az én általam jelzett hiba legyen megoldva...
;-)
