### ISSUE TITLE
Pet követés bug

### ISSUE THREAD

**Issue by dingdong2000** [andris155/TheOld-Crafters#254]
Lehet másik petjét állítani, hogy kövesse vagy ne.

**Comment by BigFlori** [comment]
Khm.. én találtam a bugot, dingdong csak a segítségemre volt! Én vettem észre, hogy áttudja állítani.

**Comment by andris155** [comment]
Akkor mindkettőtök kap majd jutalmat.

**Comment by andris155** [comment]
@Kronox12 ez valóban hiba, ha igen akkor kérlek tudnád jelenteni?

**Comment by Kronox12** [comment]
Már javítva vala elvileg. A következő mypetben. Legalábbis így láttam.
