### ISSUE TITLE
Ajtónak csak a fele nyílik ki

### ISSUE THREAD

**Issue by CoolIfAI** [andris155/TheOld-Crafters#2540]
Savsziget Minecraft 1.13.2
Ha közelről nyitom az ajtót, akkor csak a fele marad nyitva:
<img width="601" alt="2018-11-22" src="https://user-images.githubusercontent.com/25465311/48916342-2a70e100-ee82-11e8-81ab-cdbd48a55e8b.png">
<img width="601" alt="2018-11-22 1" src="https://user-images.githubusercontent.com/25465311/48916354-3b215700-ee82-11e8-8de0-9a490f2aeed2.png">

**Comment by MrZero1** [comment]
1.12.2 + 1.13.2 = ilyen szépséghibák

**Comment by andris155** [comment]
Menő a Windows 10 lejátszó. :)

**Comment by andris155** [comment]
javítva.

**Comment by CoolIfAI** [comment]
Ja, filmként akartam feltenni
