### ISSUE TITLE
block törés baltával Savsziget

### ISSUE THREAD

**Issue by CoolIfAI** [andris155/TheOld-Crafters#2542]
A szigeten sok esetben ideiglenes blokként csapóajtót teszek le. Sokat.
észrevettem, hogy (obsi)baltával amikor töröm ki, gyakran kitörés elött tovább megyek. Azaz nem ugyanannyi idő alatt töri a blokkokat. Megnéztem alaposabban, és látom, hogy valameddig kitöri, majd újrakezdi a törést.
Sajnos csak vidin tudnám bemutatni, azt viszont nem tudok mellékelni.

**Comment by CoolIfAI** [comment]
Nem egyértelműen de sorozatos törés esetében nagyjából minden harmadik blocknál kezdi újra.

**Comment by andris155** [comment]
Sajnos ez ilyen. Erre nincs megoldás. Ez az 1.12.2-es alap miatt van így.
