### ISSUE TITLE
HardcoreX: állatok eltűnése

### ISSUE THREAD

**Issue by Icecroft** [andris155/TheOld-Crafters#2543]
Az új /földek plugin megoldotta a zombik átalakítása problémát, de eltűnt az összes tehenem (kb 60 db), nagyon sok birka a levédett területemről. Van valami korlátozás vagy ez is bug?

**Comment by andris155** [comment]
Korlátoznom kellett az élőlényeket, mert egyesek állat módjára tartottak 100-200-at is teljesen feleslegesen... Úgy is az a lényeg amit ad ha megölöd. Szóval nem is értem az ilyen embereket. Egyébként a szokásos állatokból összesen 40-et lehet tartani. Ugyan így van a szörnyeknél is. Több pedig külön van korlátozva pl.: A vizi élőlények.
