### ISSUE TITLE
Belépés után nem megy chet (Savsziget)

### ISSUE THREAD

**Issue by CoolIfAI** [andris155/TheOld-Crafters#2544]
A Savszigetre miután belépek, amig meg nem mozdulok, az alábbi hibaüzenetet írja ki:
![image](https://user-images.githubusercontent.com/25465311/48972136-d2beab00-f024-11e8-8e7f-ada1afb9ae77.png)
Pedig nem is mozgok...

**Comment by poma123** [comment]
Ez körülbelül 2017 eleje óta így van, és igen a szövegnek így nincs értelme, de azt akarja jelenteni, hogy meg kell ahhoz mozdulnod hogy írni tudj. Szóval inkább a megfogalmazáson kellene változtatni.

**Comment by CoolIfAI** [comment]
Értem, és hogy tudok ebben segíteni?

**Comment by andris155** [comment]
Frissítettem a fordítást.
