### ISSUE TITLE
Javaslat

### ISSUE THREAD

**Issue by SaltyUmbrella** [andris155/TheOld-Crafters#2545]
Jó és hasznos ötletnek tartom, hogy lehessen küldeni egymásnak a levédhető földterület mérteinkből. Ma esti eset volt, hogy skrisz01 barátommal a közös házainknál a levédett területet szerettük volna bővíteni, de neki nem volt rá elég blockja, mivel övéa levédés, csak ő nyúlhat bele. Míg nekem van 7350~ blockom, nem tudtam segíteni ebben az ügyben.

**Comment by andris155** [comment]
Nincs ilyen lehetőség sajnos védés rendszerben jelenleg.
