### ISSUE TITLE
Old ásó

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#2546]
Valahogyan 2 old ásóm lett. Utánanéztem a minemarketen, én csak 1et vettem.
Mindig kölcsönbe szoktam adni elliotnak,  ezért nem tűnt fel idáig. Szóval valahogyan 1 ásóból lett 2. Még tippelni se tudok mikor történt.

**Comment by andris155** [comment]
Nem tudok vele mit kezdeni, ha nem tudod hogyan történt ez.
