### ISSUE TITLE
Eszközkeret

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#2547]
Ugye tiltva van az eszközkeret gm1ben.
De észrevettem hogy nem lehet kivenni azt a tárgyat belőle, amit beleraktunk gm1ben. Azaz kiesett egy addolási módszer 

Kérdés: nem lehetne engedélyezni az eszközkeret gm1ben?

**Comment by andris155** [comment]
Marad is tiltva. Nem szerencsés ha valaki sok entitást rak le kreatívban, mert ugye végtelen van belőle.
