### ISSUE TITLE
Telekvilág - kétfejű balta+tölgyfa

### ISSUE THREAD

**Issue by SaltyUmbrella** [andris155/TheOld-Crafters#2549]
Telek világban a tölgyfát nem vágja ki a kétfejű balta, csak egyesével mintha sima balta lenne. A nyírfánál, fenyőnél és dzsungelnél működik, többit még tesztelem.

**Comment by andris155** [comment]
Jelentettem a fejlesztőnek már. Nem igazán kezdett vele még semmit. Sajnos elég inaktív.
