### ISSUE TITLE
/ah "kategóriák"

### ISSUE THREAD

**Issue by SaltyUmbrella** [andris155/TheOld-Crafters#2557]
Egyiknél magyarul, míg a másiknál angolul van kiírva ugyan az a szöveg:
![image](https://user-images.githubusercontent.com/42703224/49687800-48844580-fb00-11e8-8436-7935033f23a2.png)
![image](https://user-images.githubusercontent.com/42703224/49687803-4fab5380-fb00-11e8-85e8-3a8a6059bf3a.png)

**Comment by SaltyUmbrella** [comment]
![image](https://user-images.githubusercontent.com/42703224/49687805-5cc84280-fb00-11e8-9cf5-8f30e0fdc9dd.png)
 na ezen látszódik a másik is

**Comment by SaltyUmbrella** [comment]
hmm, nem látszódik a képen valami miatt (rajta volt a kurzor) de ott "Jelenlegi kategóriának" írja

**Comment by andris155** [comment]
Te hogy fordítanád le?

**Comment by SaltyUmbrella** [comment]
igazából ugyan úgy mint, ahogyan a másik oldalon kiírja. Csak az egyik oldal angolul van, míg a másik magyarul, és így fura számomra.

**Comment by andris155** [comment]
Elvileg javítva.
