### ISSUE TITLE
Savsziget Ajtó vöröskő hiba

### ISSUE THREAD

**Issue by CoolIfAI** [andris155/TheOld-Crafters#2559]
A savszigeten újra pöttyös a vöröskő
És újra csak a fele nyílik az ajtónak, de úgy hogy az egyik szárny nyitva is csukva marad
![2018-12-11_12 00 59](https://user-images.githubusercontent.com/25465311/49796242-76ee6480-fd3c-11e8-940a-fe23865d57da.png)

![2018-12-11_11 58 54](https://user-images.githubusercontent.com/25465311/49796136-2c6ce800-fd3c-11e8-86ca-94ecb5635dcf.png)

![2018-12-11_12 00 34](https://user-images.githubusercontent.com/25465311/49796257-7d7cdc00-fd3c-11e8-856e-2a099893ab2e.png)

**Comment by andris155** [comment]
Javítva.
