### ISSUE TITLE
Fejlesztés: pet pluginhoz

### ISSUE THREAD

**Issue by BigFlori** [andris155/TheOld-Crafters#256]
A prémium és attól felfelé joggal rendelkező embereknek lehetne egy olyan új funkció amivel bele tudnak nézni mások petjének az inventoryjába.

**Comment by andris155** [comment]
Ilyen jog van a mypetben?

**Comment by BigFlori** [comment]
Nincs ilyen jog a mypetben de úgy értem hogy Kronox vagy Liverfler megcsinálhatná vagy ha nem tudják akkor mypet keszitőjének elküldhetnék az ötletet, mert lehet hogy bele rakná ezt a funkciót.

**Comment by Krumpli2** [comment]
@BigFlori szerintem ez fölösleges. Mi értelme van annak, hogy mások cuccaiban kutakodj? Főleg ha bugos lenne, és így lopnák a más pet inventoryjából a dolgokat.. Akkor balhé lenne.... 
Ezt a fejlesztést én **nem** támogatom.

**Comment by andris155** [comment]
Staffnak lesz ilyen jog.

**Comment by andris155** [comment]
Admintól elérhető, hamarosan lesz Segítőtől is.
