### ISSUE TITLE
Savsziget Open recipt book

### ISSUE THREAD

**Issue by CoolIfAI** [andris155/TheOld-Crafters#2563]
A krafting padon a recept könyv kifagy!

Illetve kezes esetben sem jelennek meg a receptek. 
Ez 1.12.2 alatt működött.

Értem én, hogy tudjuk kívülről a recepteket... 

Üdv KulGery

**Comment by andris155** [comment]
jelentett hiba.

**Comment by CoolIfAI** [comment]
Bocsánat, nem láttam a hibák között.
