### ISSUE TITLE
Semmi miatti kidobás (Empty packet hiba)

### ISSUE THREAD

**Issue by SaltyUmbrella** [andris155/TheOld-Crafters#2565]
![image](https://user-images.githubusercontent.com/42703224/50006828-524df300-ffaf-11e8-8350-b1ee57d33332.png)
Szépen nyugodtan beszélgettem a chatben, erre ezzel a hibaüzenettel kidob a szerver. Bárkinek bármi ötlet?

**Comment by andris155** [comment]
Savsziget?

**Comment by SaltyUmbrella** [comment]
Survival szerver

**Comment by andris155** [comment]
Egy Empty Packet-et küldtél a szervernek, ezért dobott ki. Lehet túl nem volt megfelelő az internetkapcsolatod. Illetve a elavult Windows 7 is okozhat hibákat.

**Comment by andris155** [comment]
Mit csináltál pontosan, amikor kidobott?
Esetleg ha más is járt így nagy segítség lenne, ha ő is leírná.
A kliens log-ban mit ír ennél résznél, amikor ez történt?

**Comment by andris155** [comment]
nem jelentős hiba és nagyon ritkán fordul elő.
