### ISSUE TITLE
Eltérő petnév

### ISSUE THREAD

**Issue by SaltyUmbrella** [andris155/TheOld-Crafters#2569]
A Chat-ben leírt neve illetve maga az állat fölött megjelenő név eltér egymástól.
![2018-12-17_20 02 15](https://user-images.githubusercontent.com/42703224/50109051-0dd48880-0237-11e9-9462-4ee23f078bbf.png)

**Comment by andris155** [comment]
letudod írni pontosan milyen paranccsal adtad meg a pet nevét?

**Comment by SaltyUmbrella** [comment]
/petname Hermaeus Mora az alábbi módon:
a színkódok: "c", "4" és formázás pedig vastagra történt (&4&lH&c&le&4&lr&c&lm&4&la&c&le&4&lu&c&ls &4&lM&c&lo&4&lr&c&la)

**Comment by andris155** [comment]
javítva
