### ISSUE TITLE
Pet bug!

### ISSUE THREAD

**Issue by BigFlori** [andris155/TheOld-Crafters#257]
Ha a pet annyira elkezd éhezni, hogy már nem ad semmilyen jelzőfény effektet és megeteted annyira hogy adjon effeketet akkor utána nem menti el, hogy mik voltak a beállítások és újra be kell az effekteket állítani.

**Comment by Kronox12** [comment]
Nem hinném, hogy ez akkora tragédia.

**Comment by BigFlori** [comment]
De buggnak bug..

**Comment by andris155** [comment]
Büntetés amiért éhezteted szegény petet. :D

**Comment by andris155** [comment]
Ez nem bug, ez inkább hasznos. :D
