### ISSUE TITLE
Vöröskő eszközök

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#2570]
Szia. Nem tudom, volt e már jelentve, de a vöröskő eszközök (kard, balta stb.) nem aktiválja (pl) a lámpát. Elvileg van nekik egy ilyen tulajdonságuk, de nem megy

**Comment by andris155** [comment]
Erre szerintem nincs megoldás. Magában a kódban van a hiba és a hibát már elküldtem még korábban a fejlesztőnek egy hibakód formájában. Nyilván az a megoldás, ha a fejlesztő javítja, de elég inaktív már egy ideje.

**Comment by andris155** [comment]
https://github.com/andris155/TheOld-Crafters/issues/2594
