### ISSUE TITLE
HardcoreX: Lands bug

### ISSUE THREAD

**Issue by Icecroft** [andris155/TheOld-Crafters#2572]
A bossok okozta villámlás a védett területeken ki tudja ütni az eszközkeret tartalmát, vagy a páncélállványokat.

**Comment by andris155** [comment]
Az egyedi boss-ok?

**Comment by Icecroft** [comment]
Igen, az egyedi bossok-ról van szó.

**Comment by andris155** [comment]
Hogyan ütődnek ki? Tűz? Robbanás?

**Comment by andris155** [comment]
Most jó a védelem?

**Comment by Icecroft** [comment]
tesztelni fogom

**Comment by andris155** [comment]
sikerült tesztelni?

**Comment by andris155** [comment]
Elvileg működnie kell.

**Comment by Icecroft** [comment]
Szia Andris, még nem teszteltem, de bízzunk benne, hogy menni fog a dolog.
