### ISSUE TITLE
lottó

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#2574]
![2018-12-22_10 41 50](https://user-images.githubusercontent.com/29951969/50372941-ae300180-05d7-11e9-9f19-42ffa2550688.png)

**Comment by andris155** [comment]
Most jó?

**Comment by SaltyUmbrella** [comment]
még mindig %time%-ot ír

**Comment by skrisz0101** [comment]
ennél jobban nem tudom igazolni. 19:35 -> még minfig %time%-t ír

**Comment by andris155** [comment]
javítva
