### ISSUE TITLE
Chorus Fruit

### ISSUE THREAD

**Issue by SaltyUmbrella** [andris155/TheOld-Crafters#2575]
Nem tudok eszközkeretbe tenni Chorus Fruitot, mert az írja, hogy nem használhatom azt. Gondolom a megevését tiltó plugin ezt is letiltotta, erre valami megoldás?
![2018-12-22_11 16 41](https://user-images.githubusercontent.com/42703224/50373188-4f6c8700-05db-11e9-991c-92619a5a1e56.png)

**Comment by andris155** [comment]
Kérj meg egy Admint, hogy rakja bele neked.
