### ISSUE TITLE
EnderContainers plugin íngol kiírási hiba

### ISSUE THREAD

**Issue by SaltyUmbrella** [andris155/TheOld-Crafters#2576]
A kép magáért beszél.
![2018-12-22_11 19 00](https://user-images.githubusercontent.com/42703224/50373218-aa05e300-05db-11e9-8f3a-a03f7cb6ab2d.png)

**Comment by andris155** [comment]
Miért mit írjon ki, ha nem ezt?

**Comment by SaltyUmbrella** [comment]
ez az egy hibaüzenet amit angolul ír ki, a többi mind magyar. Erre próbáltam célozni

**Comment by andris155** [comment]
Írtam a fejlesztőnek ezzel kapcsolatban, de nem tartom olyan nagy hibának ezt.

**Comment by andris155** [comment]
javítva
