### ISSUE TITLE
Szerver általi kidobás

### ISSUE THREAD

**Issue by SaltyUmbrella** [andris155/TheOld-Crafters#2580]
Andris, ha vissza tudnád nézni kérlek, hogy mi miatt dobott ki a szerver (előzőleg EmptyPatch-et küldtem a szervernek) azt megköszönném, mert ugyanis kreatív módban voltam, ami miatt meg minden Túlélő módos eszköztáramban lévő tárgy elveszett.

**Comment by andris155** [comment]
https://github.com/andris155/TheOld-Crafters/issues/2585
