### ISSUE TITLE
Vanilla Additions Double Axe 'csalás'

### ISSUE THREAD

**Issue by ZsombGuy16** [andris155/TheOld-Crafters#2589]
Ha Double Axe-el kiütöm egy fa egyik blokkját, majd gyorsan eldobom a baltát, akkor sokkal kevesebb megy le a tartósságából, mint amennyinek 'kellene' (kb. csak a harmada, negyed). Ezzel a techinkával, egy fa dupla baltával akár 4-5, de az ügyesebbek 6 nagy dzsungel fát is kivághatnak.

**Comment by andris155** [comment]
videót tudsz erről csinálni?

**Comment by ZsombGuy16** [comment]
https://www.youtube.com/watch?v=8JXanU-r2gk

**Comment by ZsombGuy16** [comment]
Ezen a linken megvan a videó :D

**Comment by andris155** [comment]
https://github.com/andris155/TheOld-Crafters/issues/2594
