### ISSUE TITLE
/pettype parancs - nem található

### ISSUE THREAD

**Issue by Dreed1992** [andris155/TheOld-Crafters#2591]
A pet infó táblán ez a parancs áll: /pettype
Ez a parancs nem működik.

![2019-01-02_13 43 20](https://user-images.githubusercontent.com/35728669/50592439-6a20e480-0e94-11e9-853f-fc57c07558e7.png)

**Comment by andris155** [comment]
Nem a tábla hibás, hanem a parancs nincs meg.

**Comment by andris155** [comment]
Direkt vette ki a fejlesztő. Ez nem hiba.
