### ISSUE TITLE
/ci tárgynév

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#2595]
Régebben lehetett a /ci itemnév paranccsal egy féle tárgyat törölni az invből úgy, hogy minden más megmaradt, most ez nem működik, semmit sem csinál.

![kep](https://user-images.githubusercontent.com/16057404/50684216-f78b4280-1014-11e9-9806-06fc2bb48bb7.png)

**Comment by andris155** [comment]
A régi id nevek nem támogatottak. Használd az 1.13-asokat.

**Comment by andris155** [comment]
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html

**Comment by UDPSendToFailed** [comment]
Pont ez a probléma, /ci ender_pearl-t írtam be, és úgy nem jó.

**Comment by andris155** [comment]
/ci név tárgynév szám a számot megadtad úgy sem működik?

**Comment by UDPSendToFailed** [comment]
Így már jó. Érdekes, eddig nem kellett megadni, hogy mennyit akarok törölni.
