### ISSUE TITLE
lucky block

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#2596]
![2019-01-04_16 36 08](https://user-images.githubusercontent.com/29951969/50696239-2fa77b00-103f-11e9-93a2-c4705e4d1733.png)

Ha kiütjük a luckyBlockot, ilyen fejet ad.

**Comment by andris155** [comment]
Ha nem telken használod akkor szerintem működik még nincs javítva a hiba.

**Comment by skrisz0101** [comment]
nem telken nyitottam

**Comment by andris155** [comment]
Holnap betölt elvileg a javítás.

**Comment by skrisz0101** [comment]
nem köszi, 1 luckyblock az semmi :D

**Comment by andris155** [comment]
javítva
