### ISSUE TITLE
Mcmmo bug

### ISSUE THREAD

**Issue by Huntermaster0** [andris155/TheOld-Crafters#2597]
Az mcmmoban a bányászat maxos a 216os szinten (de már 157nél is az volt), 45 másodperces Giga Drill és 100%-os dupla drop, eddig 1000nél volt maximális. Ha beírom, hogy /bányászat felül írja, hogy Dupla Esés: TESTING Szuper Törés: TESTING.
Update: Szerintem minden képességnél ezt írja, pld. az ásás is brutál, 810es szinten 164 másodpercre jelzi a giga drillt.

**Comment by andris155** [comment]
100 lett a max szint benne.

**Comment by andris155** [comment]
A Testing-et én se értem.

**Comment by Huntermaster0** [comment]
This is not a bug, you are just running development code in its unfinished state.

Szóval ha jól értelmezem, ez nem egy bug, csak egy fejlesztői változat van futtatva a szerveren, ami még nincs befejezve. Ezt az 1. closed issue-k közt írta, ugyanezt jelentette valaki. Akkor gondolom megoldja a hibát az, ha másik McMMO verzió kerül futtatásra.

**Comment by andris155** [comment]
Hát akkor még várni kell majd a frissítésre. A fejlesztői változatot használjuk, mivel sok fordítás változik benne így pedig talán egyszerűbb megtalálni benne a hibákat illetve frissíteni ha nem egyből kerül be a sok változtatás.
