### ISSUE TITLE
Harc közben engedélyezhető a /god

### ISSUE THREAD

**Issue by Renarchon** [andris155/TheOld-Crafters#2599]
https://www.mediafire.com/folder/z20et1712mtwj/

Szintén csak így tudtam megoldani :/ Sry

**Comment by EHzy001** [comment]
Harc közben még mindig aktiválható a /god és a /gm 1. (Tesztelve)

**Comment by andris155** [comment]
javítva.

**Comment by andris155** [comment]
330 OCD
