### ISSUE TITLE
Furniture Plugin emlékeztető.

### ISSUE THREAD

**Issue by Kronox12** [andris155/TheOld-Crafters#26]
Ha lesz időd,mint mondtad,ránézhetsz,hogy bugos-e még.

**Comment by andris155** [comment]
Rá fogok majd nézni. :+1:

**Comment by andris155** [comment]
Kronox12 tesztje:
http://timings.aikar.co/?url=14544611

**Comment by andris155** [comment]
Lassítja a chunk betöltést, ami így sem valami gyors.
