### ISSUE TITLE
TS IP kiírásának engedélyezése tagoknak is

### ISSUE THREAD

**Issue by AwesomeFM** [andris155/TheOld-Crafters#260]
Ha a tagok ki szeretnék írni a jelenlegi TS IP-t nem tudják, mert hirdetésnek veszi a plugin.
IP: 92.121.55.41:34083

**Comment by andris155** [comment]
Ez egy nem hivatalos ts3, amin ráadásul hirdetés is van. Bármikor megszűnhet, ezért inkább nem engedélyezem.
