### ISSUE TITLE
Kreatív - Fáklya ,  Vöröskő fáklya bug

### ISSUE THREAD

**Issue by Foxol01** [andris155/TheOld-Crafters#2601]
Ha kreatív módban leraksz 1 fáklyát vagy vöröskő fáklyát a földre majd kiütöd alatta a blokkot akkor az megjelenik tárgyként a földön és túlélő módban fellehet venni.

**Comment by andris155** [comment]
Jelentett hiba.
https://github.com/andris155/TheOld-Crafters/issues/2400
