### ISSUE TITLE
Piston head bug

### ISSUE THREAD

**Issue by Huntermaster0** [andris155/TheOld-Crafters#2605]
Ha a Survival szerveren egy pistont a fejénél ütök ki, akkor bebugol, a feje ott marad a hátulja pedig eltűnik. Ezután nem lehet kiütni a fejét, csak akkor ütődik ki, ha mögé rakunk egy blockot.

**Comment by andris155** [comment]
Elvileg javítva

**Comment by andris155** [comment]
330 OCD
