### ISSUE TITLE
Nagyontitkosújjáték - hibák

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#2608]
1. Néha ha olyan blokkra dob, ami alatt nincs semmi, akkor oda dob alá (azaz a padló alá pl)

2. Ha vége a játéknak, nem mindenkit dob ki a játék spawnjára, hanem ott maradnak játékosok a mapon (a saját cuccukkal) és van pvp is

3. nem bug, csak egy rémálom: Tűzijáték. 60fps-ről simán ledob 0-ra

4. Néha a játékosok emberként jelennek meg a mapon, úgy hogy fognak 1 blokkot a kezükben, és az van a fejükön is.

5. Az ütés is néha bugos. Megütök valakit, de nem sebződik. (bár ez lehet csak a netem miatt volt xd)

Szerintem ennyi, több hibát nem találtam.
Ha fordítani lehetne a shopot, az király lenne.

**Comment by poma123** [comment]
+ még annyit hozzátennék hogy a CombatLogX játék közben is működik, nem tudom esetleg le lehet-e tiltani, mert igazán nincs rá szükség

**Comment by MrZero1** [comment]
Az adminoknak a WE miatt az iránytű nem valami jó párosítás, ha átlehetne rakni a spektrálisnyílra, jó lenne

**Comment by andris155** [comment]
Az elsőnél talán ha állíthatók ezek a pontok feljebb kellene rakni, meg betömni a padló alatt a lyukat.

A második szerintem inkább plugin hiba.

A harmadik. Elvileg kikapcsoltam a tűzijátékokat.

A negyedik. Az fura. Talán meglehetne próbálni Libs Disguise-al? A fejlesztő mondjuk az iDusguise-t ajánlotta inkább hozzá.

Az ötödik. A rossz net miatt lehetett.

A CombatLogX-et jelenleg csak világonként lehet tiltani. De írtam a fejlesztőnek, hogy jó lenne ha WorldGuard régiónként is lehetne. Ez utóbbi ettől sajnos még nem biztos, hogy bekerül.

**Comment by andris155** [comment]
Az iránytű elvileg átállítva a spektrális nyílra.

**Comment by andris155** [comment]
- 'SPLASH_POTION:16428 : 2'
ezt kell átírni a megfelelő ID-re, amiket így fejből én sem tudok.

**Comment by andris155** [comment]
Elvileg NBT-t használ nem ID-t a játék már a bájitalokra.

**Comment by MrZero1** [comment]
A tüzijáték szükséges az aréna közben, nemcsak pontot ad, hanem azzal is kell jelezni a kereső(k)nek, ki merre van.

**Comment by andris155** [comment]
Mik biztosan plugin hibák, amiket jelentsek a fejlesztőnek?

**Comment by poma123** [comment]
Az elteleportálósat lehet megoldottam azzal, hogy átírtam ezt true-ra.
![image](https://user-images.githubusercontent.com/25465545/51181698-21bde980-18cc-11e9-9f1d-812a2f199f12.png)

Ha a LibsDisguises-el megy rendesen, akkor már csak a tűzijátékot kéne megoldani. Kell a játékba.

**Comment by andris155** [comment]
Beraktam a Libs-t. Ez valamivel jobban is van optimalizálva. Szóval remélem ezzel jobban működik.

**Comment by MrZero1** [comment]
Volt teszt ismét, írom a hibákat:

Volt akinek a neve látszott míg a kereső (én) várakoztam, az egész játékos látszott, a fején a blokkal.
Mikor megütöttem a bújót, aki (pl) üllő volt, átbugolt a kinézete sima kőre (kép).
A combatlogx miatt nem tpzi ki azokat az embereket, akik megütötték egymást (kereső-bújó). Ott maradnak az arénában.
A bájital továbbra sem a sebzés bájitala.

![kep](https://user-images.githubusercontent.com/29709854/51800835-ed381f00-2235-11e9-8cfa-9e49996f796c.png)

**Comment by andris155** [comment]
A CombatLogX csak világonként tiltható.

**Comment by andris155** [comment]
Nem tudom ezek olyan alap hibák, amiket fejlesztőnek is látnia kellene ha foglalkozna vele bővebben.

**Comment by MrZero1** [comment]
Szerintem a Combatlogx nem szükséges a survivalgames világba. Ott vannak az 1v1 arénák mondjuk. De minden eventen le van tiltva a pvp

**Comment by andris155** [comment]
Letiltottam a SurvivalGames világban.
