### ISSUE TITLE
Halászat közbeni kickelés

### ISSUE THREAD

**Issue by Icecroft** [andris155/TheOld-Crafters#2609]
Ha csónakból halászok, egy idő után el kezd rázkodni a csónak, ha nem szálok ki időben, a szerver kidob: You are sending too many packets! hibaüzenettel.
Igazából nem tudom, hogy ez 1.13 bug vagy az mcmmo okozza, de elég fárasztóvá teszi a pecázást.

**Comment by andris155** [comment]
Melyik szerveren?

**Comment by Icecroft** [comment]
Ez a probléma survin jelentkezett, de szerintem teszteljük még, mert tegnap is horgásztam és nem jelentkezett a probléma. Ha ma este sem lesz gond, akkor jelzem és lezárhatjuk.

**Comment by Icecroft** [comment]
A probléma sajnos aktuális, gyakorlatilag pár perc csónakos horgászat után jelentkezett:
![kicked](https://user-images.githubusercontent.com/19332825/51128797-08179600-1829-11e9-823b-ad12133a91ab.png)

**Comment by andris155** [comment]
Hamarosan megszűnik a Windows 7 támogatása. Érdemes lenne frissíteni 10-re.

**Comment by andris155** [comment]
elvileg javítva 330 OCD

**Comment by andris155** [comment]
majd azért nézd meg
