### ISSUE TITLE
event

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#2610]
Nem halálos eventen nem lehetne a ,,Páncélzat tilos" szabályt kiivenni? 

Sok ember nem nézi a csetet, mikor rászólnak  hogy ,,xy szettet le!"
Aztán szegény kezdők azért kapnak börtönt.
Konkrét példa: Srác vasnadrágban eventezett endrunon, rá lett szólva 2-3x, de nem nézte a csetet, és börtönt kapott. 

Szerintem teljesen felelsleges ez a szabály, egyedül az oldcipő tud segíteni jump eventeken, amit ki lehetne emelni.

**Comment by MrZero1** [comment]
A szettre vonatkozó rész a tűzállóság és a többi hasonló enchant miatt van. Szeretnénk majd kikerülni azt, hogy ne tudjatok szettben eventezni. 
Ha egy staff pedig jelzi a játékos felé, hogy ne viseljen szettet, de az nem reagál rá, teljesen jogos a börtön. A szabály tábla is kint van.

**Comment by MrZero1** [comment]
Ha lesz megoldás erre, az minden eventre érvényes lesz.
