### ISSUE TITLE
Pipe rendszer

### ISSUE THREAD

**Issue by SurvivorTheReal** [andris155/TheOld-Crafters#2613]
Ha olyan itemet akarok elszortírozni, aminek a neve nem fér el a pistonon lévő táblán egy sorban, akkor az adott itemet nem szortírozza el, és/vagy mást tesz helyére. 
Pl: red_nether_bricks-->az "s" már nem fér ki, és nálam az adott ládába, stone-t tesz, azaz sima követ.
A /iteminfo és /itemdb parancsokkal megjelenő nevekkel sem működik.
További ilyen itemek: prismarine_crystals, fermented_spider_eye, az aranyröggel összecraftolt dinnye szelet(nem tudom a nevét pontosan), phantom_membrane, és az end_stone_bricks
A mossy stone bircks és a mossy cobblestone is ilyen.

Survior

**Comment by SurvivorTheReal** [comment]
Teszteltem a phantommembrane-t egy külön, sokkal kisseb rendserben 2 out 1 in-el, ugyanúgy nem teszi bele. Biztos ami biztos alapon.

**Comment by CoolIfAI** [comment]
Savszigeten még elfogadja az ID-t így küszöböltük ki a problémát. Annak a motorja viszont 1.12-es amiben még van ID.

**Comment by SurvivorTheReal** [comment]
ID-kkel így utólag megoldottam 1-2 itemet, de még sok van aminek nincs ID je, és nem fér ki sajnos.
Én csak erre tudok gondolni: mojang, mire volt ez jó, hogy eltüntetjük az itemek ID jét?

**Comment by andris155** [comment]
Sajnos a fejlesztő nem akarja megoldani máshogy. Azt írta lehet változókat használni hozzá, de az meg inkább adminoknak való dolog, mivel azzal más más dolgokat is belehet állítani, amit játékosnak nem nagyon kellene.
