### ISSUE TITLE
Crazy Enchantments + fordítás - 5080 OCD

### ISSUE THREAD

**Issue by andris155** [andris155/TheOld-Crafters#2614]
A # utáni mindig komment. Amiket nem kell lefordítani. A többi dolog a szokásos a többi fordításhoz képest.
https://github.com/andris155/TheOld-Crafters/tree/master/Ford%C3%ADt%C3%A1sok/CrazyAuctions

**Comment by EHzy001** [comment]
Neki kezdtem a fordításnak :)

**Comment by EHzy001** [comment]
Elkészültem:
Config - https://pastebin.com/R4whqyiu
Massages - https://pastebin.com/60WbXp4a
Enchantments - https://pastebin.com/FsfeLYDr

Ha valamit nagyon elrontottam volna, szólj neki kezdek a korigálásnak :D 
- EHzy

**Comment by andris155** [comment]
Ezt sajnos nem tudom elfogadni. Rengeteg hiba van benne, és több dolog nincs is lefordítva. Illetve olyan dolgokat is lefordítottál, amit nem kellett volna.

**Comment by andris155** [comment]
A konfig-ban javítottam pár dolgot: https://github.com/andris155/TheOld-Crafters/commit/a7d785a80a381fff4660a0c706d260279ab41b20

**Comment by EHzy001** [comment]
Melyik részében vannak hibák? KIjavítom őket :D Szabadidőm bőven van

**Comment by EHzy001** [comment]
Mondjuk inkább másra hagyom... Ha ez nem sikerült jól, akkor nincs sok értelme újra neki vágnom

**Comment by andris155** [comment]
Igazából csak javítani kellene.

**Comment by EHzy001** [comment]
Melyik részét kellene javítani?

**Comment by EHzy001** [comment]
Gondolom az Enchantments részén átírogatni a Name, Enabled, Item szövegeket vissza
elsősorban

**Comment by EHzy001** [comment]
Enchantments javítása: https://pastebin.com/tDHy3A8e

**Comment by EHzy001** [comment]
Massages javítása: https://pastebin.com/mmD72HCH

**Comment by EHzy001** [comment]
ha még van hiba javítom :DD

**Comment by andris155** [comment]
Egyelőre mégsem kerül be, mert sok kompatibilitási hibát okoz. De köszönjük a fordítást. 508 OCD-t adtam érte.
