### ISSUE TITLE
Survival: Mcmmo változás

### ISSUE THREAD

**Issue by Icecroft** [andris155/TheOld-Crafters#2615]
Ma reggel óta a kb 10-szeresére nőtt az mcmmo skillek szintugrásának követelménye. Sehova se lehet fejlődni, még old ranggal sem. Ez vajon valami bug vagy szándékos "feature"

**Comment by andris155** [comment]
Egyelőre ez szándékosan ilyen, de még biztosan fog változni, mivel ez nem a végleges kiadás.

**Comment by andris155** [comment]
A végleges verzióba ezek fognak valószínűleg bekerülni, vagy hasonló dolgok:
https://github.com/mcMMO-Dev/mcMMO/milestone/8

**Comment by Icecroft** [comment]
Az 1 hónappal ezelőtti kiegyensúlyozott és használható mcmmo-t sikerült teljesen elrontani. Gratula a fejlesztőknek :(
