### ISSUE TITLE
Stackmob HP hiba

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#2618]
Normál esetben az endermaneknek 43 blokk esés után 1 hp-juk marad, de amint a plugin stackeli őket, fullhp lesz mind, így olyan mobok jönnek létre, amiket 20x kell megölni teljes életerőről. Ugyanez a probléma a guardianokkal is, 3-4 hp-ra sebződnek a lávától, esés közben stackelődnek, és fullhp-n esnek le.

**Comment by andris155** [comment]
Ezek már nem stack-elődnek: enderman, guardian, villager
Elveszett villager esetén az oldalra kell írni.
