### ISSUE TITLE
Pistonos blockeltűnés v2.0

### ISSUE THREAD

**Issue by Huntermaster0** [andris155/TheOld-Crafters#2619]
Az előzőben nem a pulzár volt a lényeg, itt sem az, hanem 2 egymás után beérkező jel. A videóban az observer érzékeli a redstone törést és lerakást is, ebből kapja a piston a 2 egymás utáni jelet.

https://www.youtube.com/watch?v=84CIIBzAnUM

**Comment by andris155** [comment]
Kreatívos homok?

**Comment by andris155** [comment]
hmm érdekes egy hiba.

**Comment by Huntermaster0** [comment]
Ja és survivalos homoknál annyi a különbség, hogy droppolja a homokot, de ott is zavaró az eltűnése.

**Comment by andris155** [comment]
Ez egyjátékos módban is ilyen. Ez Minecraft hiba, nem szerver.
