### ISSUE TITLE
Tintahal + lélekhomok

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#2620]
Úgy bugolnak a tintahalak, mintha a nocheat dobálná vissza őket, más mobokkal nincs ilyen probléma.

![ezgif-2-8dbe2ff2d19a](https://user-images.githubusercontent.com/16057404/51355242-d74c9080-1ab6-11e9-9425-88a523c3b522.gif)

**Comment by andris155** [comment]
Egyjátékos módban is ilyen. Ez Minecraft hiba. Nem szerver.
