### ISSUE TITLE
Lucky Block /iteminfo

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#2621]
Néhány régebben craftolt Lucky Block-ra ezt írja a /iteminfo:

![kep](https://user-images.githubusercontent.com/16057404/51356644-a458cb80-1abb-11e9-851e-c804a70e6954.png)

**Comment by andris155** [comment]
wow nem semmi hiba.

**Comment by andris155** [comment]
A régivel már nem lehet mit kezdeni. Használjátok az újat azzal működik.
