### ISSUE TITLE
Teknős és delfin lopás

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#2622]
Plot telekről és GriefPrevention védésről is el lehet lopni a teknősöket és a delfineket, elég csak egy vizesvödörrel jobbklikkelni rájuk.

**Comment by andris155** [comment]
Frissítettem a kiegészítőt. Még mindig él ez a hiba?

**Comment by UDPSendToFailed** [comment]
A teknős már jó, nem engedi védésről felvenni, de a delfint védésen kívül sem lehet, nem történik semmi jobbklikkre.

**Comment by andris155** [comment]
Most sem lehet a védésen felvenni? Illetve a védésen kívül már működik?

**Comment by UDPSendToFailed** [comment]
Szabad területen fel lehet venni, védésen belül nem, így most jó. Már csak annyi a gond, hogy angolul van az item leírása:

![kép](https://user-images.githubusercontent.com/16057404/55160409-91b9dd00-5163-11e9-88bd-2d538191cc95.png)
![kép](https://user-images.githubusercontent.com/16057404/55160498-c168e500-5163-11e9-867f-c34a4a4f3f81.png)

**Comment by andris155** [comment]
Elvileg ez is javítva.

**Comment by andris155** [comment]
1016 OCD
