### ISSUE TITLE
Vanilla Addititions

### ISSUE THREAD

**Issue by CoolIfAI** [andris155/TheOld-Crafters#2647]
Az obsidian dupla balta nem működik, az additions repair is azt mondja, törhetetlen
Csak egy rönköt tör ki.
![2019-01-20_08 14 24](https://user-images.githubusercontent.com/25465311/51436447-9ce91c00-1c8d-11e9-90c4-37eca0538da1.png)
![2019-01-20_08 15 50](https://user-images.githubusercontent.com/25465311/51436449-a2466680-1c8d-11e9-91a3-5881eca17398.png)

Üdv. KulGery

**Comment by andris155** [comment]
A hibáról tudunk.
https://github.com/andris155/TheOld-Crafters/issues/2594
