### ISSUE TITLE
Tp "BUG"

### ISSUE THREAD

**Issue by geri5200** [andris155/TheOld-Crafters#265]
Ha tpzek és lejár a tp ideje akkor is el kell fogadjam a tpt mert ha nem fogadom el akkor a másik embernek azt írja hogy már 1x tpzett rám.

**Comment by andris155** [comment]
Jelentett hiba már az EssentialsX-nek.

**Comment by andris155** [comment]
A /tpno egyelőre megoldás erre a hibára.
