### ISSUE TITLE
Hibás adat a /warp bájital részen

### ISSUE THREAD

**Issue by EHzy001** [andris155/TheOld-Crafters#2650]
A /warp bájital warpon, a negatív bűjitalok részen hibásan van feltüntetve a lomhaság (slowness) bájital készítése.

A kiírás szerint szökkenő (jump boost) szérum kell hozzá, holott gyorsaság (speed) bájitalhoz kell hozzá keverni, az erjesztett pókszemet.
-EHzy

**Comment by MrZero1** [comment]
Félig igazad van, lomhaság bájitalt gyorsaság és szökkenés potiból is lehet csinálni. Kiraktam a gyorsaságot is. ☺
