### ISSUE TITLE
Védett láda kiütés

### ISSUE THREAD

**Issue by ayedeil** [andris155/TheOld-Crafters#2651]
Ha egy láda csak táblával van levédve, azt ki lehet ütni luckyblock segítségével. Ha a player aki kiüti a luckyblock-ot a láda mellett áll, és a luckyblock bezárja valamilyen kalitkába, akkor a láda felülíródik, és a benne lévő itemek kiszóródnak. Ez a módszer használható end portal kiütésére, és esetlegesen bedrock kilukasztására is (ez nem próbáltam ki).

**Comment by andris155** [comment]
Szerintem nem nagyon fogja ezt megcsinálni a fejlesztő. Erre az egyetlen megoldás, ha figyelsz, hogy ne tároló mellett nyiss Lucky Block-ot.
