### ISSUE TITLE
Partychat

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#2652]
![kep](https://user-images.githubusercontent.com/29709854/51444141-ff750300-1cf3-11e9-85d0-be2473dd6825.png)

Nem tudom mire vélni, partychat bevolt kapcsolva, oda írtam, de elküldte globálba is, holott nem kapcsoltam ki (lásd kép)

Nem tudom, hiba e vagy sem, de jelzem azért

**Comment by andris155** [comment]
de tagoknak meg jól működik?

**Comment by MrZero1** [comment]
Nem szoktam így figyelni, nem jelezték még.

**Comment by EHzy001** [comment]
Nálam már 3-4 alkalommal fellépett ugyanez a hiba
Általában kisebb lagg van közben

**Comment by andris155** [comment]
Talán ez az Asyn chat-es error, amit már jelentettem, de utána fogok nézni.

**Comment by andris155** [comment]
Egy jó ideje már nem volt ez a hiba. Ha megint előfordulna nyissatok új hibajelentést erre hivatkozva.
