### ISSUE TITLE
Hibák az Areashop fordításban 

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#2655]
![kep](https://user-images.githubusercontent.com/29709854/51445298-af05a180-1d03-11e9-8cd3-ec6a8f1637e6.png)

Kibérelted a(z) pl5 területet ennyi időre: 2019. February 20. Meghosszabbíthatod a bérlést a táblára való jobb kattintással vagy a /as rent paranccsal. 

---

![kep](https://user-images.githubusercontent.com/29709854/51445331-158abf80-1d04-11e9-8103-684830566aa5.png)

A(z) pl5 terület ki lett bérelve MrZero által, 2019. February 20., 22:29-ig.

---

![kep](https://user-images.githubusercontent.com/29709854/51445374-6c909480-1d04-11e9-9c72-de475f9073ed.png)

Itt csak egy plusz szóköz van a 'területen' és az év között. 

---

![kep](https://user-images.githubusercontent.com/29709854/51445395-98137f00-1d04-11e9-84bf-0a027bb9b4e0.png)

Itt a kérdés értelmetlen számomra, mivel törölni akarom a területet, érdemes arra rákérdezni.

Biztos, hogy törölni szeretnéd a lefoglalt területet (pl5)? 
[Kattints, hogy megszüntesd a bérlést (pl5)!]

Ennyi, ami elsőnek szembetűnt nekem. Apró hibák (..), de fontosak, ha már bőséges OCD volt a jutalom érte.

**Comment by MrZero1** [comment]
A hónapok nevét nem írtam, mert gondolom nem lehet lefordítani magyarra azokat.

**Comment by MrZero1** [comment]
![kep](https://user-images.githubusercontent.com/29709854/51445476-aca44700-1d05-11e9-9fd1-44f790c047ce.png)

(..) 31 napig. Az "ideig" felesleges oda, értelmetlen is így.

**Comment by andris155** [comment]
Ezeket a hibákat javítottam.

**Comment by MrZero1** [comment]
Holnap tölt be?

**Comment by MrZero1** [comment]
Láttam, ez még most sem jó.
![kep](https://user-images.githubusercontent.com/29709854/51478234-2df1ed00-1d8b-11e9-86cd-d0aa9bc81bf9.png)

**Comment by andris155** [comment]
ez is javítva
