### ISSUE TITLE
Automata Eventláda Ötlet

### ISSUE THREAD

**Issue by EHzy001** [andris155/TheOld-Crafters#2656]
Már sokszor estem abba a hibába, hogy automata eventek végén mikor a ládát kinyitottam, még nem telt le a 24 óra, így később újra kellett próbálkoznom (ilyenkor is megeshet hogy még mindig nem telt le az idő) az eventtel, ami sok időt elvesz.

Arra gondoltam (feltéve ha megoldható) lehetne egy olyan mechanizmus, az Automa Eventládáknál, hogy kinyitáskor kiírja az chatn, hogy mennyi idő múlva lesz benne újra a nyeremény.
Így a játékosok tudnák mihez viszonyítani, mikor csinálják meg újra, ne feleslegesen töltsenek el egy eventen akár 10-15 percet.
- EHzy

**Comment by poma123** [comment]
Nem igazán oldható meg. :/

**Comment by EHzy001** [comment]
Nem gond, csak egy ötlet volt :D 
Köszi a visszajelzést ^^
