### ISSUE TITLE
chunkbetöltés

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#2657]
Rengeteg chunk nem tölt be. De nem csak nekem, hanem senkinek se. Se a f3+a, se a relog nem segít. Egyszerűen nem tölti be. Sok helyen van ez. 
2 kép a plázámban készült, senkinek se tölt be.

![2019-01-21_16 03 38](https://user-images.githubusercontent.com/29951969/51482274-4e737480-1d96-11e9-9815-b34ddc4fa801.png)
![2019-01-21_16 02 32](https://user-images.githubusercontent.com/29951969/51482287-5a5f3680-1d96-11e9-89ef-0728cacc8652.png)

**Comment by andris155** [comment]
Mivel a chunk betöltés több szálon fut előfordulhat, hogy néha nem tölt be, mivel a több szálon futtatás rettentően meggyorsítja ezt a folyamatot, viszont sajnos az a hátránya, hogy nem olyan stabil mintha a főszálon futna ez is a már így is túl folyamat mellett. A játékosok szerint ha leraksz egy blokkot az megoldja és annál mindenképpen jobb, mintha akadna a szerver.

**Comment by skrisz0101** [comment]
azért írtam, mert kb 30 percen át nem töltöt be pár chunk a területemen, és ha belementünk, bebugoltunk. Blokkot ha beletettem, eltűnik, nem segít. Értem én hogy több szálin fut, de ilyesmi nem volt eddig.

**Comment by skrisz0101** [comment]
töltött*

**Comment by skrisz0101** [comment]
köszönöm, kipróbálom
