### ISSUE TITLE
Rombolható az End!!!!

### ISSUE THREAD

**Issue by EHzy001** [andris155/TheOld-Crafters#2660]
Nem régiben (kb 5-10 perce) sárkányt idéztem az endben, mikor észre vettem, hogy az élettöltőit nem csak kilőni hanem kiütni is tudom, illetve az utánuk hagyott tüzet!
Ezen kívül kíváncsiságból kipróbáltam hogy az oszlopokat is lehet-e, és...
IGEN! A rácsokat, és az obszidián oszlopokat lehet rombolni, fentről lefelé egy bizonyos pontig.

Egy oszlopban több dupla ládányi obszidián is kijöhet egy toronyból, és kb 8-10 van.
Hangsúlyozom nem az EndCityban, hanem a sima ENDBEN! tudtam rombolni!
- EHzy

**Comment by EHzy001** [comment]
![end](https://user-images.githubusercontent.com/46755427/51498876-7085ea80-1dc8-11e9-8423-5b877a87678a.png)
![end2](https://user-images.githubusercontent.com/46755427/51498881-74b20800-1dc8-11e9-869e-641af81a1bb8.png)

**Comment by andris155** [comment]
Azért ilyen, hogy akinek nincs fly joga feltudja magát építeni és kiütni a kristályt meg a rácsokat.
