### ISSUE TITLE
Magától Eltűnő token

### ISSUE THREAD

**Issue by EHzy001** [andris155/TheOld-Crafters#2661]
A mai nap folyamán, (mint minden nap) neki fogtam a napi eventek végig játszásához. A /token top-on néztem éppen aktuális egyenleget, vártam mikor lépek feljebb a token helyezésekben.  Már 4-5 eventet végig játszottam de a tokeneim száma, változatlanul 307 volt, mint tegnap este. Beírtam a /token bal parancsot hogy hátha akkor frissült, és ekkor azt írta, hogy csupán 15 tokennel rendelkezem. Még pár eventet kijátszottam, de nem jött vissza az a 307 token, és a token top sem frissült. Egyetlen tokenem sem költöttem el, semmit nem csináltam. Magától eltűnt. Örülnék, ha vissza tudnátok szolgáltatni :D 

- EHZy

![token png](https://user-images.githubusercontent.com/46755427/51543962-1edc6f00-1e5f-11e9-8308-589f4dc4b5dd.jpg)

**Comment by andris155** [comment]
Lehet újraindítás után lesz csak jó. Kérlek próbáld meg majd holnap és másokat és értesíts erről.

**Comment by EHzy001** [comment]
Még mindig nincs meg az eltűnt token mennyiségem

**Comment by andris155** [comment]
Szóval. Elírtam a nagybetűket a nevedben. Elnézést érte.

**Comment by andris155** [comment]
![jegyzet 2019-01-23 212242](https://user-images.githubusercontent.com/8324198/51634642-0b133480-1f55-11e9-9fc7-7b626867a954.jpg)
Javítva
