### ISSUE TITLE
Chunk error

### ISSUE THREAD

**Issue by asdtmyasd** [andris155/TheOld-Crafters#2665]
Még mindig tele van chunk errorokkal a szerver és néha nagyon zavaró , de még élvezhető a játék , de gondoltam jelentem a hibát! Üdv:tmy

**Comment by andris155** [comment]
Holnap tölt be a megoldás. Remélem ez már tényleg megoldja. Majd kérlek nyisd újra ezt vagy írj új jelentést ha nem.
