### ISSUE TITLE
mcmmo fordítás

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#2667]
![2019-01-25_14 24 02](https://user-images.githubusercontent.com/29951969/51784157-1af16b00-2145-11e9-98b6-d90d97817ac3.png)

Csetet kell nézni

**Comment by skrisz0101** [comment]
és a felugró szöveget

**Comment by andris155** [comment]
Érdekes, mert ezt elvileg kivették a fordításból.

**Comment by skrisz0101** [comment]
egy ideig nem volt a csetena  szintnövekedés, de új dizájnal megint mutatja

**Comment by andris155** [comment]
Még most is így írja?

**Comment by skrisz0101** [comment]
még most is ilyen

**Comment by andris155** [comment]
Javítva.
