### ISSUE TITLE
Grass path /home bug

### ISSUE THREAD

**Issue by Tyloendis** [andris155/TheOld-Crafters#267]
Ha az új 1.10-es ledöngölt fűre(elnézést nem tudom a magyar nevét), állítasz egy home-ot, és odateleportálsz akkor bugol a karakter, furcsán ugrál, nem tud mozogni.
Az alattad lévő blokk kiütésével megoldódik, szóval nem olyan vészes bug, de azért idegesítő lehet.

**Comment by andris155** [comment]
Nem sikerült reprodukálnom. Nekem tökéletesen működött.
