### ISSUE TITLE
Üllő addolás 

### ISSUE THREAD

**Issue by Huntermaster0** [andris155/TheOld-Crafters#2670]
Gm1-ből addolható az üllő a következő módszerrel. Videó:

**Comment by EHzy001** [comment]
Pillanatokon belül fel töltöm youtubre.
Addig gyors leírás:
Ha egyik játékos levédéséről (esetünkben Huniéről) üllőt lősz át másik ember levédésére (esetünkben az enyémre) gm1-ben, akkor az kiütődik és megkapod.
