### ISSUE TITLE
Nem működő parancs

### ISSUE THREAD

**Issue by EHzy001** [andris155/TheOld-Crafters#2674]
Tegnap (és azelőtt is) tökéletesen működött a /p h <telek száma> parancs, mely az éppen kiválasztott telekre teleportált.

Ma mikor megpróbáltam a parancsot, akkor azt írta, hogy Nincs jogosultságom ennek a használatára.
Ezen kívűl még működik a /plotme home <telek száma>, /plotme h <telek száma>, /plot home <telek száma> illetve, a /plot h <telek száma>.
Egyszerűbb be írni 2 betűt és egy számot, mint végig írni a parancsot (véleményem szerint) és gyorsabb is :D

**Comment by andris155** [comment]
javítva
