### ISSUE TITLE
Cave spider

### ISSUE THREAD

**Issue by LordAdam55** [andris155/TheOld-Crafters#2675]
Survivalon ha a cave spiderek össze stackelődnek akkor át tudnak menni a félblokkokon.

**Comment by EHzy001** [comment]
a cave spider ill. a rendes pók is átfér a fél lapokon :D 
Nekem is szoktam ily módon kiszökni a mob farmból

**Comment by andris155** [comment]
Akkor ez magyarul nem hiba.
