### ISSUE TITLE
Telek-láda

### ISSUE THREAD

**Issue by LordAdam55** [andris155/TheOld-Crafters#2676]
A telkeimen ha lerakok egy ládát megkapom azt az üzenetet amit a vadonban is,
![2019-01-28_19 25 36](https://user-images.githubusercontent.com/46933798/51857539-d1ff0980-2332-11e9-8e63-7207e042ec3e.png)

**Comment by Huntermaster0** [comment]
+Emiatt nem működnek a telkeken a pistonok. A jelet felveszik, de ha block is van előttük, akkor ugyanúgy nem tolják el, mint a levédett területeken.

**Comment by LordAdam55** [comment]
![2019-01-29_14 21 58](https://user-images.githubusercontent.com/46933798/51911129-4d16fd00-23d1-11e9-9ab7-497e28ae9d7f.png)

**Comment by andris155** [comment]
Javítva lett.

**Comment by andris155** [comment]
330 OCD
