### ISSUE TITLE
Aukciós Ház

### ISSUE THREAD

**Issue by poma123** [andris155/TheOld-Crafters#2677]
![image](https://user-images.githubusercontent.com/25465545/51926826-75632380-23f2-11e9-8868-ac941e2bee55.png)
Nem működik ez a funkció. Admin ranggal ezzel adminként leveszi aukcióról, de játékosként nem működik megfelelően.

**Comment by andris155** [comment]
Tudtommal eddig is csak Admin tudta levenni ezeket.
