### ISSUE TITLE
McMMO és az arany

### ISSUE THREAD

**Issue by Huntermaster0** [andris155/TheOld-Crafters#2678]
Az McMMO plugin nem ad dupla droppot az arany kibányászásakor. Más ércnél tökéletesen megy, 2-t ad 1 érc (100%-os az esélyem rá), de az aranynál 1 érc 1-et ad.

Ránéztem mégegyszer, konkrétan Gyengéd érintéses csákánynál van csak így, Hatékonysággal ugyanúgy duplán adja.

**Comment by andris155** [comment]
Szerintem lehet szándékosan ilyen.

**Comment by andris155** [comment]
Holnap frissül, aztán lehet változik. De nem tudom eldönteni azt sem, hogy direkt ilyen vagy sem.
