### ISSUE TITLE
Ismét Scoreboard

### ISSUE THREAD

**Issue by geri5200** [andris155/TheOld-Crafters#268]
A scoreboard ismét nem jó 2015. aug 5.

**Comment by andris155** [comment]
![kepkivagas](https://cloud.githubusercontent.com/assets/8324198/17448347/182cdabc-5b54-11e6-8a50-ecf7c7f523d2.PNG)

**Comment by andris155** [comment]
holnap elvileg jó lesz

**Comment by andris155** [comment]
javítva
