### ISSUE TITLE
item felvétel

### ISSUE THREAD

**Issue by LordAdam55** [andris155/TheOld-Crafters#2680]
![2019-01-30_10 12 07](https://user-images.githubusercontent.com/46933798/51972753-75a80100-247c-11e9-8b4f-925ffd65ebfb.png)
sokszor az eldobott itemet nem veszi fel a karakter csak ha leteszek egy blokkot

**Comment by andris155** [comment]
Hogyan lehet ezt a hibát reprodukálni pontosan?

**Comment by LordAdam55** [comment]
ha több stack item van egy helyen egyszerre eldobva akkor nem mindet veszi fel, valamit csinálni kell pl:lerakni egy blokkot,itemet váltani a kézben

**Comment by andris155** [comment]
Nem sikerült reprodukálnom. Lehet netes probléma is ez.
