### ISSUE TITLE
Törhetetlen cuccok

### ISSUE THREAD

**Issue by LordAdam55** [andris155/TheOld-Crafters#2681]
![2019-01-30_15 50 27](https://user-images.githubusercontent.com/46933798/51989210-d4827000-24a6-11e9-8ed1-6b0d198def27.png)

-256 a kopása

**Comment by andris155** [comment]
Már jelentett hiba.
https://github.com/andris155/TheOld-Crafters/issues/2594

**Comment by andris155** [comment]
Ez nem hiba. Engedélyezd a szerver forráscsomagokat és fent egy csíkban írja meddig jó. De van egy ilyen hiba, hogy sajnos tényleg lehet törhetetlen is.
https://github.com/andris155/TheOld-Crafters/issues/2594
