### ISSUE TITLE
Item buggoltatás GameBox-ba

### ISSUE THREAD

**Issue by EHzy001** [andris155/TheOld-Crafters#2682]
Ha eldobok úgy egy itemet, hogy csak egyetlen szabad slot van az invemben, akkor azt nem tudom felvenni, de ha megnyitom a gambeox invet (/gb), akkor oda kerül az item, majd ha kilépek belőle eltűnik.
Erről egy videót is készítettem (hátha így érthetőbb):
https://youtu.be/6hi3pjgMeGQ

**Comment by andris155** [comment]
Már nem lényeges. De az OCD jár 330 OCD
