### ISSUE TITLE
nem észlel a játék parancsot

### ISSUE THREAD

**Issue by LordAdam55** [andris155/TheOld-Crafters#2683]
ha beirom hogy /info vagy tovább írom ugyanúgy pirosnak színezi és mást javasol
![2019-01-30_21 36 55](https://user-images.githubusercontent.com/46933798/52011208-9f424600-24d7-11e9-82a6-89d7a305ec75.png)

**Comment by EHzy001** [comment]
Hiába javasol mást, úgyanúgy működik
