### ISSUE TITLE
repairt nem érzékeli

### ISSUE THREAD

**Issue by LordAdam55** [andris155/TheOld-Crafters#2684]
Ha beirom h /additions azt még érzékeli de a továbbírásnál nem rakja oda a repairt csak a giveot
![2019-01-30_21 44 31](https://user-images.githubusercontent.com/46933798/52011472-5b037580-24d8-11e9-9c7d-0102b2aa760a.png)

**Comment by EHzy001** [comment]
Ha utána írod a reapirt működni fog ugyanúgy

**Comment by andris155** [comment]
Írd oda, hogy repair. Sajnos ez a kiegészítő nem mostanában frissült így gondolom ezt nem írták meg hozzá.
