### ISSUE TITLE
pet etetés

### ISSUE THREAD

**Issue by LordAdam55** [andris155/TheOld-Crafters#2685]
https://youtu.be/NSVR1Scqh7c

**Comment by andris155** [comment]
Mi itt a hiba?

**Comment by LordAdam55** [comment]
A petemet megetettem de a répát vissza kaptam ha kinyitottam egy ládát

**Comment by andris155** [comment]
Ha a /petinfo-nál megnézed megeszi a pet?

**Comment by LordAdam55** [comment]
ott azt írta megette

**Comment by andris155** [comment]
javítva.
