### ISSUE TITLE
netherrack eszközök

### ISSUE THREAD

**Issue by LordAdam55** [andris155/TheOld-Crafters#2686]
Lehet ez nem aktuális, nem tudom hogy ez mióta nem működik, de nem lehet netherrack eszközöket craftolni
![2019-01-31_11 38 22](https://user-images.githubusercontent.com/46933798/52049588-7e690780-254e-11e9-9838-2c0b75aa8b04.png)

**Comment by andris155** [comment]
Direkt van letiltva, mivel szinte mindent felgyújtottak ezekkel.
