### ISSUE TITLE
Survival bújócska #3

### ISSUE THREAD

**Issue by jokoboy** [andris155/TheOld-Crafters#2693]
Nem a megfelelő helyen jelenik meg a powerup.
https://imgur.com/a/wgcjdIv

Doge voltam.

**Comment by skrisz0101** [comment]
aranyblokkra spawnolnak a PowerUpok, gondolom ez véletlen spawnol ott.

**Comment by poma123** [comment]
Gyakorlatilag csak mi tesszük oda az aranyblokkot, ahova beállítjuk a powerupok helyét. Akkor majd teszek egyet oda is. Köszi
