### ISSUE TITLE
Vote plugin szavazási idő

### ISSUE THREAD

**Issue by jokoboy** [andris155/TheOld-Crafters#2694]
hibásan mutatja az időt a minecraft-mp.com-nál.
https://youtu.be/jSTH6ks3JW4

Doge voltam. :)

**Comment by andris155** [comment]
mennyi időnként lehet ott szavazni?

**Comment by jokoboy** [comment]
13 óránként, legalábbis én úgy tapasztaltam. Meg szavaztam egy random szerverre erre az oldalon kíváncsiságból, majd megint megpróbáltam rá szavazni és azt írta, hogy 13 óra múlva tudok újra.

**Comment by andris155** [comment]
Beállítottam napira, de mivel az oldal más időzónában így sem 100% pontos.

**Comment by andris155** [comment]
330 OCD
