### ISSUE TITLE
Pláza

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#2695]
Szia. Plázabolt lemondásakor az UNKNOWN fura ott. Eddig nem volt ott (?)

![kep](https://user-images.githubusercontent.com/29709854/52170421-2d256780-274a-11e9-8fde-865ac124238a.png)

**Comment by jokoboy** [comment]
én úgy tudtam, hogy a plázabolt megszűnt, ugyanis warp sincs oda.

**Comment by MrZero1** [comment]
Felújítás alatt van. :)

**Comment by andris155** [comment]
A lemondásra gondoltam. Furcsa akkor én sem értem.
