### ISSUE TITLE
HideAndSeek item kibugoltatás

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#2696]
Ha kreában lépek be (/has join aréna), aztán kilépek belőle, megkapom a lobby itemeket a survival invembe.

![kep](https://user-images.githubusercontent.com/16057404/52178054-d19abe80-27c9-11e9-9e47-a1e5336decea.png)

**Comment by UDPSendToFailed** [comment]
+1 -Lobbyban lehet ládát / enderchestet nyitni:

![kep](https://user-images.githubusercontent.com/16057404/52178098-86cd7680-27ca-11e9-922e-c2c538d2b04e.png)

**Comment by andris155** [comment]
letiltottam a parancsot kreatívban.

**Comment by poma123** [comment]
Ezt jó tudni!

**Comment by UDPSendToFailed** [comment]
Nether arénában is nyitható az enderchest, és a seekernek nincs joga eldobni a potit.

![kep](https://user-images.githubusercontent.com/16057404/53289283-80606800-3794-11e9-95d5-225017328f2b.png)
![kep](https://user-images.githubusercontent.com/16057404/53289291-8bb39380-3794-11e9-9db6-0a78389551a4.png)

**Comment by andris155** [comment]
Még él ez a hiba?

**Comment by UDPSendToFailed** [comment]
A tábla még mindig hibás, szerintem a szín miatt. A lobby-ban &2[&6Bújócska&2], ez nem működik, az arénák kezdőterületén viszont &2[&5Bújócska&2], ez a jó, jobbklikkre kiírja a statokat. 

Ha a védés jogok nem lettek változtatva, szerintem a másik probléma is megvan, aréna lobby-ban megnyitja az enderchestet, játékban még nem tudtam tesztelni.

**Comment by andris155** [comment]
Egyelőre ez nem aktuális. Sajnos nem úgy tűnik, hogy fog frissülni 1.14-re a plugin.
