### ISSUE TITLE
Telek

### ISSUE THREAD

**Issue by LordAdam55** [andris155/TheOld-Crafters#2700]
Valamiért nem tudok interakcióba lépni a telkem egy részén a blokkokal
![2019-02-05_14 13 23](https://user-images.githubusercontent.com/46933798/52275620-5f081b00-2950-11e9-9b4b-5b85a7a5555e.png)

**Comment by andris155** [comment]
Érdekes. Remélem a jövőben a PlotSquared fejlesztője stabilabb frissítéseket ad ki...
