### ISSUE TITLE
reggeli resi + pet

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#2703]
Egy srác állítása szerint írom ezt.
Fent játszott a szerveren, mellette a fantom pete, mikor jött a reggeli resi, és ki is dobta persze.
Azt vette észre, mikor feljött a resi után, hogy nincs meg a pete, a /pc is azt írja hogy nincs pete.
Szólt, megírtam.

**Comment by andris155** [comment]
Ez lehetetlen. A pet plugin nem volt módosítva. Esetleg próbáljon meg petet váltani.
