### ISSUE TITLE
Napi event csalások!!!!!

### ISSUE THREAD

**Issue by powaa** [andris155/TheOld-Crafters#2704]
Hali. Napi eventekkel van egy két probléma. Könnyen végig lehet vinni tárgyakkal.
Temple run : gyorsaság nyilával könnyen végig vihető
RageRun: a mapp elején a fal blokkokat és taposókat ki lehet játszani egy kézben tartott potival és nem érzékeli a taposó ha áthalad rajta egy játékos. ugyan ez a többi taposós eventen is.

Falldown: lassú zuhanás nyila engedélyezett.

Kamikaze1 illetve 2 mapon is engedélyezett a lassu zuhanás nyila.

Útvesztő, pokol labirintus, unikornis, traplabirintus: minimap és fáklyák segytségével végig vihető.

eddig ennyi hibát találtam az eventek között, igazából nem nagy hiba de akkor is csalás így!!!!!!
Az összes map csalását megkeresem még a héten és leírom!!
 :D :P

**Comment by poma123** [comment]
Nyilasok javítva, és a bájitalos is.

**Comment by poma123** [comment]
A fáklya sehol sincs tiltva, minimap pedig ilyen eventnél segédprogramnak minősül.

**Comment by andris155** [comment]
330 OCD
