### ISSUE TITLE
Eventvilág pet

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#2706]
Alapból eventvilágba teleportáláskor elküldi a petet, és nincs is jog a /pc parancshoz, viszont ha /warp bolt-ban magamhoz hívom, onnan minden eventre és minigame-re be lehet vinni. A legjobb megoldás talán a bolt áthelyezése lenne másik világba.

**Comment by poma123** [comment]
Most jó?

**Comment by UDPSendToFailed** [comment]
"Jó", de a /pc letiltása miatt nem lehet petinvben cuccokat szállítani, sok itemnél ez eléggé hátráltatja az eladásukat.

**Comment by MrZero1** [comment]
Ezzel a WE-vel biztosan nem lesz átrakva a bolt sehova.

**Comment by andris155** [comment]
A másik már lehet sosem frissül normálisan. Esetleg részenként lehetne.

**Comment by MrZero1** [comment]
Részenként? 100 blokkot nem lehet úgy WE-zni, hogy ne kellene várni és/vagy ne írna ki valami hibát. Ha elég bátor vagy hozzá, hajrá.

**Comment by andris155** [comment]
Ha megmondod hova másolhatom, akkor átrakom az egyik reggel. De a régiből ne felejtsük el törölni a táblákat. Nehogy később vissza éljenek a régi árakkal majd.

**Comment by andris155** [comment]
kész
