### ISSUE TITLE
HideAndSeek - tűzijáték hiba

### ISSUE THREAD

**Issue by EHzy001** [andris155/TheOld-Crafters#2707]
Bújócskázás közben, a bújóknak lehetősége van arra, h 10 mp-enként egy tűzijátékot használjanak, ami 3 érmét ad.

Ha ezt a tűzijátékot bal kézből lövöd fel akkor nem kapsz érmét.
Én már 2-3x megjártam ezzel

**Comment by andris155** [comment]
Egyelőre ez nem aktuális. Sajnos nem úgy tűnik, hogy fog frissülni 1.14-re a plugin.
