### ISSUE TITLE
Tiltott színek használata a party chatbe

### ISSUE THREAD

**Issue by EHzy001** [andris155/TheOld-Crafters#2709]
A vörös, piros és fekete szín tiltva van a chaten, ám nekem party chatbe egy véletlen folytán sikerült ezekkel a színekkel írnom.

Képet is csatolok róla:
![tiltottszin png](https://user-images.githubusercontent.com/46755427/52638703-d3a00400-2ed2-11e9-944a-2267be29852c.jpg)

**Comment by MrZero1** [comment]
![kep](https://user-images.githubusercontent.com/29709854/52638775-f92d0d80-2ed2-11e9-95f1-ceed29a75554.png)

**Comment by andris155** [comment]
Ezt poma saját plugin-ja tiltja, amihez csak ő ért. Talán köze lehet ennek az asynchat-es mcMMO hibának is.

**Comment by poma123** [comment]
ahhoz biztos nincs köze mert csak akkor fut le ha valaki tiltott színt használ

**Comment by poma123** [comment]
kesz ☺☺☺
