### ISSUE TITLE
Munka "BUG"

### ISSUE THREAD

**Issue by KKozma22** [andris155/TheOld-Crafters#271]
(Ezt a farmer munkánál vettem észre.) Ha olyan dolgot csinálsz a munkában ami xp-t vesz le és ezt sokáig csinálod akkor nem csökken a munkának a szintje csak mínuszba megy az XP szint. És a pénzt is utána a megfelelő szinthez képest adja.

**Comment by andris155** [comment]
Direkt ilyen.
