### ISSUE TITLE
Falon átbuggolás enderbow segítségével

### ISSUE THREAD

**Issue by Icecroft** [andris155/TheOld-Crafters#2711]
Az enderbow-val, ha megfelelő szögben lövünk a falba, akkor bele lehet buggolni, illetve át lehet menni, bárkinek a védett területén is. A screenshoton épp a boltom falába léptem be:
![2019-02-15_20 19 57](https://user-images.githubusercontent.com/19332825/52879527-aa47d800-315f-11e9-9497-51259a6e08a7.png)

**Comment by andris155** [comment]
Ilyet szerintem a simával is lehet. Sajnos ez ilyen. :/
