### ISSUE TITLE
MCMMO javaslat

### ISSUE THREAD

**Issue by Icecroft** [andris155/TheOld-Crafters#2712]
Jelenleg az mcmmo retro változatát használjuk, ahol 1000 a legmagasabb szint. Viszont történt egy masszív XP követelmény emelkedés (kb 10szeres), aminek hatására nem lehet fejlődni szinte semmit. Aki valamit korábban elért, azok az eredmények "befagytak", akik valamit fejleszteni akarnak semmi esélyük.
Ezt a problémát már a fejlesztőknek is felvetették:
https://github.com/mcMMO-Dev/mcMMO/issues/3794
Javaslom, hogy térjünk át az új mcmmo-ra, induljon mindenki egyenlő eséllyel.

**Comment by andris155** [comment]
Az új mcMMO van bent. De gondolom az új szint rendszer csak adatbázis reset-el lép életbe.

**Comment by Icecroft** [comment]
Részemről mehet a dolog. Majd felfejlesztem újra a dolgokat. Még mindig jobb, mint most a fejleszthetetlen javítás, halászat, alkímia stb.

**Comment by andris155** [comment]
Majd a savszigeten kérlek próbáld ki, hogy ott az adatbázis reset-el új és jó-e lett a rendszer.

**Comment by Icecroft** [comment]
OK

**Comment by andris155** [comment]
most jó?

**Comment by Icecroft** [comment]
Igen, csak a bányászatot próbáltam, minden jónak tűnik. Normálisan lehet fejlődni is. Tesztelgetem tovább.

**Comment by andris155** [comment]
megvalósítva.
