### ISSUE TITLE
Ötlet

### ISSUE THREAD

**Issue by IcyAlex** [andris155/TheOld-Crafters#2713]
Sziasztok!
Támadt egy olyan ötletem hogy kellene egy command amivel az összes szerveren lehet egyszerre beszélgetni.(pl.:Beírom a chatbe a commandot és még mellé hogy ,,Sziasztok!" és akkor azt az összes szerveren látják(Survival,Savsziget,Hardcore...)).

**Comment by andris155** [comment]
Ez sok esetben zavaró lenne inkább csak. Privát üzenetet lehet küldeni másnak is akkor is, ha más szerveren van. Szerintem ez a lehetőség arra az esetre, ha a barátod más szerveren játszana és beszélni szeretnél vele teljesen jó. Egyébként meg szerintem nem fontos, hogy mit beszélnek azon a szerveren, amin éppen nem játszol.

**Comment by IcyAlex** [comment]
Ez igaz.
