### ISSUE TITLE
Saját kereskedő - hibák

### ISSUE THREAD

**Issue by EHzy001** [andris155/TheOld-Crafters#2714]
A minap rászántam magam, hogy készítsek egyedi tradekkel bíró falusiakat, de számtalan hibát tapasztaltam.

1. Félre fordítások.
4 opció közül lehet választani a falusi típusnál:
'tárgyakkal kereskedik a játékosokkal'
'könyveket ad el'
'tárgyakat ad el a játékosoknak'
'tárgyakat vásárol a játékosoktól'

A 'tárgyakat vásárol a játékosoktól' opciót én úgy értelmezem, hogy mi tárgyakat, ő pedig smaragdot ad nekünk, holott ez fordítva van. Nekünk kell adni smaragdod, h vásárolhassunk tőle.

A 'tárgyakat ad el a játékosoknak' opciónak pedig szerintem úgy kellene működnie, hogy mi adunk neki x tárgyat, amiért ő ad x smaragdot. Ez az opció is pont a fordítottja. 

2. Nem működő opciók.
Az előbb felsoroltak közül, csak a 'tárgyakat ad el a játékosoknak' opció működik (az is hibásan).
A többinél nem jelenik meg a csere lehetősége. Tehát, hogy mit mire cserél.

330 OCD-t költöttem a 20 falusi tojásra, melyeket mind elhasználva szomorúan kellett tapasztalnom:
AZ ami nekem kell nem működik, az egész csak pénzkidobás volt számomra.

- EHzy

**Comment by EHzy001** [comment]
![kep1](https://user-images.githubusercontent.com/46755427/52906654-a3e55900-3250-11e9-841f-049054ea080f.png)
![kep3](https://user-images.githubusercontent.com/46755427/52906655-a647b300-3250-11e9-9ca5-02702748dd1e.png)
![kep4](https://user-images.githubusercontent.com/46755427/52906656-a9db3a00-3250-11e9-9155-b5188ad93b25.png)
![kep2](https://user-images.githubusercontent.com/46755427/52906658-ac3d9400-3250-11e9-9dfe-5c7c6a8d9c6c.png)
![kep5](https://user-images.githubusercontent.com/46755427/52906660-af388480-3250-11e9-996a-09525baacbb8.png)

**Comment by EHzy001** [comment]
![kep6](https://user-images.githubusercontent.com/46755427/52906673-d7c07e80-3250-11e9-9de2-1e542a917b18.png)

**Comment by MrZero1** [comment]
Skrisz01 régi pwarp boltján vannak kereskedők, ott pl. spawnereket lehet cserélgetni. 
![kep](https://user-images.githubusercontent.com/29709854/52939251-f3687980-3363-11e9-8d28-83798b456a9b.png)

**Comment by andris155** [comment]
Teszteltem és nekem mindegyik tökéletesen működik. A fordítások is jók.
