### ISSUE TITLE
/sell parancs engedélyezése

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#2715]
Essentials-ban van egy olyan funkció, amivel közvetlenül az inv-ből el lehet adni a tárgyakat egy paranccsal. Szerintem ez sokkal egyszerűbb, mint a boltba járkálni, ami néha 60-80+ oda-vissza teleportálást is jelent. A jelenlegi árak maradnának, csak el kell osztani, és beírni a worth.yml-be.

**Comment by EHzy001** [comment]
Támogatom az elgondolást. :D egy csomó időmet megspórolná.

**Comment by andris155** [comment]
Nincs benne ilyen funkció. Ez egy külön Essentials modul. Ha már paranccsal lenne bolt, akkor a shopgui sokkal jobb. De a többi staff úgy döntött, hogy a bolt jobb megoldás. Én már régebben is inkább a menüs rendszert támogattam, mert az sokkal fps, tps és játékos barátabb megoldás.

**Comment by Huntermaster0** [comment]
Támogatom, rengeteg idő elmegy a warpolgatással meg a Sell-re kattolással.

**Comment by UDPSendToFailed** [comment]
Esetleg egy szavazás lehetne róla fb csoportban.

**Comment by andris155** [comment]
Nyiss egyet. :D
