### ISSUE TITLE
Tökmag addolás

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#2717]
![ezgif-2-043e6285223d](https://user-images.githubusercontent.com/16057404/53093218-20a95900-3517-11e9-902d-b44005cc5f43.gif)

**Comment by IcyAlex** [comment]
Ez mióta addolás?

**Comment by UDPSendToFailed** [comment]
Ha valamit kreatívból át lehet vinni survivalba, az addolás.

**Comment by andris155** [comment]
javítva

**Comment by andris155** [comment]
1016 OCD
