### ISSUE TITLE
Telek Ötlet

### ISSUE THREAD

**Issue by IcyAlex** [andris155/TheOld-Crafters#2718]
Szerettem volna építeni mob farmot, de rá kellett jönnöm hogy a telekrendszerbe nem spawnol ellenséges mob és nem akarok építeni a vadonba mert egyszerre 2 helyen nem tudok lenni(úgy hogy a telkemen is működjenek a farmjaim meg a vadonban is). Azon gondolkozta, kellene a telekrendszerben is spawnolniuk az ellenséges moboknak is, arra a területre ami már valakinek a tulajdonában van, és oda is csak akkor ha a tulaja elérhető(és lenne rá külön telek command hogy ha valaki nem szeretné hogy a telkére spawnoljon ellenséges mob).

**Comment by andris155** [comment]
A spawner-eket elvileg külön is lehetne engedélyezni, de nem találtam rá megoldást a plugin-ban. Írtam a fejlesztőnek.

**Comment by IcyAlex** [comment]
Köszönöm.
:)

**Comment by andris155** [comment]
Sajnos nem úgy tűnik, hogy a fejlesztő megvalósítaná ezt. Ha a jövőben mégis megvalósítja, akkor be fog kerülni. Viszont addig nem tudok mit tenni.
