### ISSUE TITLE
Smaragd balta

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#2719]
Hali! 

Nem lehet smaragd baltát csinálni, mást igen (sisak, csákány stb.) Más itemből viszont lehet.

![kep](https://user-images.githubusercontent.com/29709854/53183666-05644980-35fc-11e9-9d40-be41d3ed98d7.png)

(Nincs forráscsomag engedélyezve, viszont más sem tudott csinálni)

**Comment by andris155** [comment]
Elvileg ez kiszedi a teljes fatörzsét ezért lett tiltva. Vagy nem így van?

**Comment by MrZero1** [comment]
A duplafejű balták szedték ki teljesen a fát, a smaragd baltáról nem tudok, hogy lenne ilyen tulajdonsága.

**Comment by andris155** [comment]
engedélyeztem ismét. holnap betölt.
