### ISSUE TITLE
Pokol

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#2720]
![kep](https://user-images.githubusercontent.com/29709854/53270693-b8ac6b80-36ec-11e9-9e54-a104239464d6.png)

Kicsit fura

**Comment by MrZero1** [comment]
Vég
![kep](https://user-images.githubusercontent.com/29709854/53271973-49387b00-36f0-11e9-810f-9332268a0c2d.png)

**Comment by andris155** [comment]
F3 + A megoldja. Egyelőre igen tudom, hogy nem tökéletes a chunk betöltés, de folyamatosan javítgat rajta a Paper.
