### ISSUE TITLE
Login NPC

### ISSUE THREAD

**Issue by AwesomeFM** [andris155/TheOld-Crafters#2723]
Mikor a Survival szerverre próbálok az NPC-n keresztül belépni, a következő hibaüzenetet kapom (csak a Survival esetében):

![2019-02-24_12 12 55](https://user-images.githubusercontent.com/18013708/53298421-1bf1e700-382e-11e9-87cd-b09f5c1d1977.png)

**Comment by andris155** [comment]
elvileg javítva.
