### ISSUE TITLE
Weboldal rossz ip cím

### ISSUE THREAD

**Issue by g3ri66** [andris155/TheOld-Crafters#2725]
Tegnap akartam az ip címet megnézni és először a weboldalon néztem de ott rossz van megadva ahogy a képen is lehet látni. 
![image](https://user-images.githubusercontent.com/45896686/53316793-73916080-38c9-11e9-9fe0-8a329dd7ae62.png)

s1.oldcrafters.net helyett s1.oldcraftets.net van írva.

- geri66

**Comment by andris155** [comment]
javítottam, sajnos így jár aki fáradtan is a szerverrel foglalkozik. :D

**Comment by andris155** [comment]
Nézz majd rá miért ír felkiáltójelet a Defender és ne felejtsd el frissíteni a Java-t sem. :)
