### ISSUE TITLE
Savsziget hibák

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#2726]
A spawnon nincs jog a /survival (szerver váltás) parancsra, máshol működik.

**Comment by UDPSendToFailed** [comment]
Pár elírás:

![kep](https://user-images.githubusercontent.com/16057404/53371089-a120ed00-394f-11e9-95dc-30b720506d78.png)
![kep](https://user-images.githubusercontent.com/16057404/53371131-ba299e00-394f-11e9-97b6-3d43cc0180f4.png)
![kep](https://user-images.githubusercontent.com/16057404/53371173-d62d3f80-394f-11e9-9e56-d4492eaea187.png)
![kep](https://user-images.githubusercontent.com/16057404/53371198-e04f3e00-394f-11e9-81dc-7ddeef56e197.png)

**Comment by UDPSendToFailed** [comment]
Több leírásos teleporton is ki lehet jutni a flat világba, elég csak a félblokkos ablakba állni, elmenni a spawnra, majd backelni.

![kep](https://user-images.githubusercontent.com/16057404/53371685-37094780-3951-11e9-9b1b-02dd430394bf.png)

**Comment by UDPSendToFailed** [comment]
Az egyik küldetésnél a szükséges tárgyak listája túl hosszú, így egy része nem látható.

![kep](https://user-images.githubusercontent.com/16057404/53371930-d7f80280-3951-11e9-8599-95028030d4ed.png)

**Comment by UDPSendToFailed** [comment]
Ezek a parancsok nincsenek letiltva, szerintem tagoknak nem kéne rá jog, HardcoreX-en és Survival-on is mennek.

//searchitem
//toggleplace
/trigger
/minecraft:help

**Comment by andris155** [comment]
A minecraft:help nem működhet.

**Comment by andris155** [comment]
A searchitem nem rossz dolog szerintem tagnak sem. A toggleplace nem csinál semmit, ha nem tudsz pozíciót kijelölni.  A trigger-hez scoreboard is kell. De egyébként jogot se találtam hozzá.

**Comment by andris155** [comment]
A minecraft:help-t kivettem, mert felesleges tagnak.

**Comment by poma123** [comment]
![image](https://user-images.githubusercontent.com/25465545/53423612-f7d70700-39e1-11e9-8d7f-39d9b6f60e56.png)
Az ehhez hasonló levédési leírások a nyelvi fájlból hiányoznak, a plugin fejlesztőjének kell javítania. Folyamatban.

Backkelős glitch javítva.

**Comment by poma123** [comment]
a többi javítva

**Comment by UDPSendToFailed** [comment]
Valami a vote pluginnal se jó, az első belépés óta már szavaztam, és nem adta meg.

![kep](https://user-images.githubusercontent.com/16057404/53447613-c8da8880-3a15-11e9-8190-fc7575a6b6d1.png)

**Comment by andris155** [comment]
508 OCD
