### ISSUE TITLE
Savsziget - Küldetések

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#2729]
Képeket nem fogok csatolni mert lusta vagyok.

kezdő könyv: Korallgyüjtő küldetés
Nem lehet sehonnan se szerezni korallt :) egyedül a paradicsom szigeten van pár darab
Még shop-ban se lehet venni. 

Kezdő könyv: Céklaleves bohóc
Honnan kéne szerezni nyulat? (ugye nyúlhús kell a nyúlpörkölthöz)
+nem tudom kezdésnél kapunk-e céklát/céklamagot.

Kezdő könyv: Dekoráló
vegyük bármelyik szigetet, nem lehetséges előállítani mind a 16 féle színt, most külön kiemelek egyet: sárga (lehet 1-2 mapon található), de a lényeg, hogy közel se lehet mind a 16 féle színt megszerezni.
Amúgy annyi homokot se lehet szerezni annyi üveghez, csak a piramis szigeten szerintem

A küldetések lényege egyrészt (szerintem) az, hogy shop nélkül is meg tudd szerezni a küldihez kellő itemeket.

Még csak a kezdőkönyvnél tartok, ennyire futotta

Küldetésötletek: hamarosan, kommentben

**Comment by skrisz0101** [comment]
küldetés neve: Maugli
Össze kell gyűjteni 8 mohás zúzottkövet, 8 mohás kőtéglát, és 8 indát
Jutalom:  10 céklamag

**Comment by skrisz0101** [comment]
A céklaleves bohóc-nál szerintem elég kivenni a nyúlpörköltet, és maradhat, viszont a nyereményhez hozzátetetném a 2db indát, ebből jönne a maugli küldetés

**Comment by skrisz0101** [comment]
Küldetés neve: Asztalos
Készítsen (bármilyen fából) 4 ládát, 15 kerítést,  12 lépcsőt és 6 ajtót
jutalom: 32 pink korall pl, + 5 tengeri uborka

**Comment by skrisz0101** [comment]
Küldetés neve: uborkavadász
Szerezzen 64 tengeri uborkát
Megjegyzés: Ha korall tesz valaki uborkát, majd csontlosztezi, akkor sokszorozódik.
Jutalom: 2 kakaóbab + 16 dzsungel rönk

**Comment by skrisz0101** [comment]
Küldetés neve: sütiszörny
Csinálj 128 csokissütit és 1 tejesvödröt

**Comment by skrisz0101** [comment]
Küldetés neve: Cukrász
Készíts 5 tortát, és 10 tökpitét
Jutalom: 32 vas + 32 vöröskő

**Comment by skrisz0101** [comment]
Küldetés neve: Éhenkórász
Gyűjts 96 rohadt húst 
Jutalom: 5 krumpli

**Comment by skrisz0101** [comment]
Küldetés neve: McDonald's-os krumpli-imádó
Süss ki 2x 64 krumplit (azaz szerezzen 2x 64 sültkrumplit)
Jutalom: 5 répa

**Comment by skrisz0101** [comment]
Küldetés neve: Redstone kapitány
Craftolj 8 kidobót, 4 adagolót, 2 tölcsért,  8 vörösköfáklyát, 2 dugattyút
Jutalom: 2x 64 vöröskő + 16 sín

**Comment by skrisz0101** [comment]
Küldetés neve: raktáros
Craftolj 32 sima, és 32 csapdaládát
Jutalom:  2 napraforgó, 2 bazsarózsa, 2 .... mittomén a nevüket, minden 2blokk magas virágból 2db  xd

**Comment by skrisz0101** [comment]
Küldetés neve: raktáros
Craftolj 32 sima, és 32 csapdaládát
Jutalom:  2 napraforgó, 2 bazsarózsa, 2 .... mittomén a nevüket, minden 2blokk magas virágból 2db  xd

**Comment by skrisz0101** [comment]
Küldetés neve: Halász
Süss ki 32 tőkehalat
Jutalom: 32 tintazsák

**Comment by skrisz0101** [comment]
Küldetés neve: haloween
Craftolj 32 töklámpást,  5 erjesztett pókszemet, és 32 cukrot
Jutalom: Tehéntojás

**Comment by skrisz0101** [comment]
Küldetés neve: Noob
Craftolj 1 bőr szettet (bőrcsizma, bőrnadrág, bőrmellvért, bőrsisak)
Jutalom: 5 gyémánt + 10 arany

**Comment by skrisz0101** [comment]
2. küldetéskönyv.

Családi hangulat küldi jutalmához hozzátetetném a 2 kakaóbabot 

Sütemény küldi:
Sütiszörny küldinév menőbb 🌵 
A jutalom a mostani helyett lehetne 5 répa

Farmer küldi jutalmából ki lehetne venni a kakaót, most már felesleges

Az angler küldi jutalmához hozzá tetetném a 2 akácia csemetét

#szar_vagyok_angolból_kéne_magyarfordítás :C

**Comment by skrisz0101** [comment]
Küldetés neve:  Levélmániás
Gyűjtsön 16 levelet mind a 6 fajta fából
jutalom: 5 répa

2. küldetéskönyv

**Comment by skrisz0101** [comment]
az angler küldijéhez még mindig kéne a jutalom 2 akáciafa csemete, mert nem lehet azt szerezni sehonnan :c

**Comment by skrisz0101** [comment]
Küldetés neve: Kagylóvadász
Pecázz 1 nautiluszhéjat
Jutalom:  1 Tenger szíve

2. küldetéskönyv

**Comment by skrisz0101** [comment]
Küldetés neve: Harcos
Készíts 1 pajzsot, 1 vasszettetl, és 1 vaskardot
Jutalom: 8 smaragd + szamáridéző tojás

**Comment by skrisz0101** [comment]
Küldetés neve: Potifőzés előtt...
Készíts 15 potifőzőt, 32 üvegpalackot, és gyűjts 48 bibircsókot
Jutalom: 5 lávás vödör, 5 obszidián és 16 vas

**Comment by skrisz0101** [comment]
Küldetés neve: Csirkefarm
Gyűjts össze 48 tojást és 64 tollat
Jutalom: Gombaboci tojás + lassú esés bájital

3. küldetéskönyv

**Comment by skrisz0101** [comment]
Küldetés neve: Virágárus
Gyűjts 48 pitypangot, és 48 pipacsot
Jutalom: 10 nagy páfrány, 10 sima páfrány,  16 magas fű, 8 sima fű, 2 naprafordó, 2 bazsarózsa

3. küldetéskönyv

**Comment by skrisz0101** [comment]
Küldetés neve: Enchanter
Gyűjts 2 enchant asztalt, 20 könyvespolcot, 12 könyvet, 16 lapislazulit, és 16 xp palackot
Jutalom: 1 ünjavítás és 1 gyengédérintés könyv

3. küldetéskönyv

**Comment by skrisz0101** [comment]
Küldetés neve: Pokol fafarmja!
Gyűjts 2x 64 órrókőt (blokkot) és 64 sódert
Meghegyjéz: Használd hozá az izzókő-fákat!
Jutalom:  1 életmentés toteme

**Comment by skrisz0101** [comment]
Küldetés neve:  EnderSteve
Farmolj 15 refrénvirágot, és 64 refréngyümölcsöt
Jutalom: 2 Nyúltojás

4. küldetéskönyv

**Comment by skrisz0101** [comment]
Küldetés neve: Felkészülés!!
Craftolj 4 enderkristályt, 1 gyémántszettet, 1 gyémántkardot, 1 íjat, 1 pajzsot, 1 regeneráció potit, és 48 nyilat
Jutalom: Végtelenség és láng enchantkönyv + 1 faragott tökfej + 800xp

**Comment by skrisz0101** [comment]
@poma123 és még nem fejeztem be :D
De lassan már kifogyok az ötletekből xd

**Comment by poma123** [comment]
Egyelőre nem kerül be több.

**Comment by mr00000** [comment]
woodoo baba pisi kaka
