### ISSUE TITLE
Munka elhagyás bug

### ISSUE THREAD

**Issue by akos222** [andris155/TheOld-Crafters#273]
Több játékosnál előfordult, hogy leadtak egy munkát, de még utána sem tudtak másikat felvenni helyette, és a jobs stats is kijelezte mindkét munkájukat. Admin paranccsal sikerült megoldani, hogy felvegyek nekik másik munkát. A hibát még nem sikerült reprodukálni.
-akos_

**Comment by andris155** [comment]
Elvileg javítottam már, de talán /jobs leaveall megoldja.
