### ISSUE TITLE
Savsziget Dispenser

### ISSUE THREAD

**Issue by CoolIfAI** [andris155/TheOld-Crafters#2733]
A savszigeten a dispenser nem működik, ha teszek bele pl. vizet! Egyszerűen nem csinál semmit.
Pontosabban, ha a mellette levő kőre teszem a gombot, akkor második alkalom után már vezérli, de ha vöröskővel viszem a jelet, akkor nem

**Comment by poma123** [comment]
Tudnál erről videót készíteni?

**Comment by CoolIfAI** [comment]
Sajnos nem, mert spéci gépről dolgozom.
de egyértelmű leírást tudok adni:
A dispenser fölött van zúzott kő, és vizszintesen megy 8 kocka távolságot, rajta vöröskőpor.
a 8. kőre tettem kő, illetve fa gombot.
Benyomtam, halottam a kattintást, hogy működik
Beraktam a vizes vödröt, majd újra megnyomtam, de már nem adta ki a vizet.
Emiatt próbábóltt a dispenser főlött levő kőre is raktam fagombot.
megnyomtam, semmi nem történt. megnyomtam mégegyszer, majd kiadta a vizet, és utána vissza is vette.
ezek után a dispenser feletti gomb teljesen jól vezérelte a dispensert
Aztán újra néztem a vöröskőú vezérlésen keresztül a 8. kövön levő gombot, elsőre működött is, de második alkalommal már nem, és attól kezdve nem.
Újra az felette levő kövön nyomtam meg. Elsőre nem, másodikra, és attól működött.

**Comment by CoolIfAI** [comment]
Még mindig fenn áll

**Comment by CoolIfAI** [comment]
Hogy tudok mp4-t csatolni?

**Comment by CoolIfAI** [comment]
[https://youtu.be/JblOHI6i06s](url)

**Comment by andris155** [comment]
![Annotation 2019-03-16 121857](https://user-images.githubusercontent.com/8324198/54474487-b3bb7300-47e5-11e9-873b-8e4ba54c1fca.jpg)

**Comment by CoolIfAI** [comment]
Jogosultság átállítva

**Comment by andris155** [comment]
Elvileg a játék hibája. Próbálj meg redstone repeater-t használni a dispenser-hez. Talán megoldja.

**Comment by andris155** [comment]
330 OCD

**Comment by andris155** [comment]
Nem találtam CoolIfAI nevet a MineMarket-en.

**Comment by andris155** [comment]
Vagy próbáld meg egyből a dispenser-be vezetni a redstone jelet.

**Comment by CoolIfAI** [comment]
;-) KulGery
