### ISSUE TITLE
savsziget - küldikönyv

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#2736]
Nem lehet az előző küldetéskönyvre visszamenni. (Több küldetést meg lehet ott csinálni többször is, + van ami kész sincs
![2019-03-02_03 06 42](https://user-images.githubusercontent.com/29951969/53680597-26085f80-3cde-11e9-899d-4c7682751009.png)

**Comment by CoolIfAI** [comment]
Nen csak ha kész vagy én csak a zúzott köves küldetést csináltam meg, mégsem látom az első oldalt. Pedig még 10-es sincs a szigetem

**Comment by skrisz0101** [comment]
@poma123 :(

**Comment by poma123** [comment]
![image](https://user-images.githubusercontent.com/25465545/53698641-ee81dc00-3ddf-11e9-88ed-cd2a04365408.png)
nekem van most, előbb nem volt.

**Comment by DumetDH** [comment]
Még mindig fennáll a probléma.
![savsziget_hiba](https://user-images.githubusercontent.com/48296360/53908657-21caa200-4050-11e9-9d7c-28f3043605c4.jpg)

**Comment by poma123** [comment]
Megvan miért, az egyik küldetés hibás.

**Comment by skrisz0101** [comment]
Jeeee :D
Melyik volt az? :o

**Comment by poma123** [comment]
Forró a talaj. Elírtam az azonosítóját, és ékezet került bele. xd Egyszerre két szintben is benne volt.

**Comment by poma123** [comment]
javítva
