### ISSUE TITLE
Shulkerben lévő itemek slotszámra történő kivétele

### ISSUE THREAD

**Issue by Huntermaster0** [andris155/TheOld-Crafters#2738]
Ha egy adott slotszámról a shulkerbe akarok tenni 1 itemet (tehát mondjuk az invem 8. slotjában van 1 item, a shulkerben rámegyek egy slotra és megnyomom a 8-as gombot), akkor az itemet nem rakja be, és egy hibát ír ki: [Crates] Error: You may not perform this action with shulker boxes.

Ez visszafele is megy, tehát ezzel a módszerrel kivenni sem lehet az itemet egy shulkerboxból.

**Comment by andris155** [comment]
javítva
