### ISSUE TITLE
Savsziget bug

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#2740]
Első belépéskor vettem egy szigetet, másnap már semmit se tudtam csinálni rajta. Azt hittem, én rontottam el valamit, így generáltam egy újat, viszont most pár nappal később az is elbugolt, másé lett:

![kep](https://user-images.githubusercontent.com/16057404/53737172-10d13380-3e8c-11e9-9aa9-772e7945fe34.png)

A koordinátán lévő ládát én raktam le, így elvileg a coreprotect is bizonyítja a hibát.

**Comment by andris155** [comment]
Lehet ráférne a plugin-ra egy frissítés. De remélem poma ránéz erre, mert ő ért ehhez leginkább.

**Comment by UDPSendToFailed** [comment]
Mégsem az én szigetem volt, az /is go parancs visszavitt:

![2019-03-05_11 36 25](https://user-images.githubusercontent.com/16057404/53799599-03bf4d80-3f3b-11e9-95c7-6609146d98e0.png)

Azt még mindig nem értem, hogyan került oda a karakter, X koordinátában egyezik a 2 hely.
