### ISSUE TITLE
Redstone Clock

### ISSUE THREAD

**Issue by IcyAlex** [andris155/TheOld-Crafters#2742]
Lehetne a szervernek egy nem annyira laggoltató redstone clock-ja, mert nagyon kevés lehetőség van az üveges szelektáló automatizálásához.

**Comment by Huntermaster0** [comment]
A Pipe automatizálásához rengeteg megengedett rendszer van, van redstone clockos és anélküli is. Redstone clockos pl. Etho redstone clockja (piston-comparator-redstone block-hopper), ez a fajta clock azt hiszem minimum 64 itemmel engedélyezett. Ha mobfarmról van szó, oda talán a borlódrótos megoldás a legegyszerűbb. Ha egy sima ládából/hopperből kellene kiszedned az itemet, simán leraksz mellé egy comparatort, csak tapasztalat szerint az a Pipe kiszívásánál bebugol, és benne marad a jel, így ajánlott a pistonba egy observerrel belevezetni a jelet, és úgy a Pipe is megoldva, és a comparator sem bugol be.

-Huntermaster

**Comment by skrisz0101** [comment]
lusta megoldás:_ leteszel 6 sínt amin megy körbe 1 csille, és az ad jelet (:

**Comment by IcyAlex** [comment]
Köszi sk. :-)
