### ISSUE TITLE
nem stackelődnek a mobok

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#2743]
nem stackelődnek a mobok,  Ehelyett csak eltűnnek
-szurvi

**Comment by IcyAlex** [comment]
Milyen fajta mobok?
És a zombiepigman-okat látom össze stack-elődni.
:-)

**Comment by andris155** [comment]
Stack-elődnek, de ami már a limiten túl van az eltűnik értelemszerűen.
