### ISSUE TITLE
Enderchest Ötlet

### ISSUE THREAD

**Issue by IcyAlex** [andris155/TheOld-Crafters#2744]
Ugyebár az enderládában fekete és lime(ha több tárgy van benne lehet piros, narancssárga) üveglapok vannak.
A lime(piros, narancssárga) üveglapok az enderláda számát és tartalmát írja.
Lehetne esetleg egy command amivel a lime(piros, narancssárga) üveglapoknak a nevét át lehetne írni(a tartalmának a számát nem lehetne átírni), ezzel könnyebben meg lehet keresni ha esetleg valaki szépen elosztja benne a felszerelését(pl.: ,,Enderláda 1" helyett átnevezni ,,Páncélzat"-ra).

**Comment by andris155** [comment]
Kérlek itt írd meg a javaslatokat a kiegészítőhöz angolul: https://github.com/utarwyn/EnderContainers/issues
