### ISSUE TITLE
tag+ és vip jogok

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#2745]
![2019-03-07_16 20 51](https://user-images.githubusercontent.com/29951969/53967474-9ad00500-40f5-11e9-83a4-7bacac46bf90.png)
![2019-03-07_16 21 02](https://user-images.githubusercontent.com/29951969/53967485-9dcaf580-40f5-11e9-88ae-2b6e63873060.png)

a vipnél van megjelenítve a /pswitch, mikor erre már tag+nak is van joga

**Comment by skrisz0101** [comment]
tank kaszt már nincs is :c

**Comment by andris155** [comment]
Miért mi lett vele?

**Comment by skrisz0101** [comment]
Hát amióta új kasztok és Pályák vannak, azóta nincs

**Comment by andris155** [comment]
A jog megvan rá adva. Később még használhatjuk máshol. A többit javítottam.

**Comment by andris155** [comment]
330 OCD
