### ISSUE TITLE
Gyors Eladás Ötlet

### ISSUE THREAD

**Issue by IcyAlex** [andris155/TheOld-Crafters#2746]
Ha valaki sokat termel(pl.: kaktusz, cukornád rotten flesh) és a bolt warp-on akarja eladni, akkor járkálni kell, és ha nagyon sok van abból amit termel az akár órákba is telhet.
Lehetne egy command amivel (az inventorymban és a ládában lévő tárgyakkal együtt) egyszerre sok tárgyat lehetne eladni enélkül hogy a boltba kellene elrohanni 1000x.
-------------------------------------------------------------------------------------------------------------------
Command ötlet: 
/sell all [item ID/angol név] [darabszám]      (ha az inventorymban és a ládámban lévő tárgyakat együtt akarom eladni)
/sell hand [item ID/angol név] [darabszám] (ha  az inventorymban lévő tárgyat akarom eladni)
/sell chest [item ID/angol név] [darabszám] (ha a ládáimban lévő tárgyakat akarom eladni)

**Comment by andris155** [comment]
https://github.com/andris155/TheOld-Crafters/issues/2715
