### ISSUE TITLE
Kezdő NPC

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#2747]
![2019-03-08_15 58 31](https://user-images.githubusercontent.com/29951969/54036241-5e66dc80-41bb-11e9-99fb-969342c6ea2a.png)
Alapból (ha jól tudom), egyszer lehet a kezdő NPC-t használni.
Na, szerintem jobb lenne ha lehetne 3-4x is, mert lehet hogy valaki rákattol, lelép és semmi, értitek.
Amúgy maga a hiba: a képen. Kicsit sokat kell várni

**Comment by andris155** [comment]
elvileg nincs rá limit.

**Comment by poma123** [comment]
de, van rá limit. ha valaki rákattol és lelép, újra lehet kezdeni. szoktam gondolni minden végletre.

**Comment by skrisz0101** [comment]
és maga a hiba, amiért jelentettem? ':D

**Comment by poma123** [comment]
Nekem nem csinál semmi ilyesmit.

**Comment by poma123** [comment]
Lezárható.
