### ISSUE TITLE
Jobs, OLD rangtól nagyon boost.

### ISSUE THREAD

**Issue by dingdong2000** [andris155/TheOld-Crafters#275]
Old rangtól lehetne +100% jobs boost, az old rang az amúgy is 5080ft edmsmel és 2540ft paypallal.
Szerintem simán beleférhetne a jobs boost, vagy legalább 1016 OCDért + 50% jobs boost 1 hónapig.
[http://theold.minemarket.hu/](url)

**Comment by andris155** [comment]
Csak egy boost jog van, ezért van csak a prémiumnál.
