### ISSUE TITLE
Savsziget: nem lehet Nautilus shellt horgászni

### ISSUE THREAD

**Issue by Icecroft** [andris155/TheOld-Crafters#2750]
A horgászszintem már 102, de egyetlen nautilus shellt sem fogtam eddig, amíg a survin gyakrabban jönnek mint a bohóchalak.

**Comment by andris155** [comment]
Az mcMMO beállítások ugyan azok a 2 szerveren. Azóta sem sikerült fogni?

**Comment by Icecroft** [comment]
Sajnos nem sikerült.

**Comment by andris155** [comment]
Fogalmam sincs miért nem jó. Ötletem sincs.

**Comment by andris155** [comment]
Kitesztelni is rengeteg idő lenne. Nem tudok mit csinálni ezzel.
