### ISSUE TITLE
Savsziget: biom probléma

### ISSUE THREAD

**Issue by Icecroft** [andris155/TheOld-Crafters#2751]
A tajgáról sivatagra állítottam a szigetem biomját, de a hófoltok és a jég a vízekről egyáltalán nem tűnik el, pedig órákkal korábban átraktam már.
![2019-03-09_22 15 35](https://user-images.githubusercontent.com/19332825/54077481-58572580-42b9-11e9-9477-080f3aed54a5.png)

**Comment by poma123** [comment]
nem is fog eltunni magatol, csak az eghajlatot allitja at

**Comment by poma123** [comment]
lezarhato
