### ISSUE TITLE
Savsziget: Állatok eltűnése

### ISSUE THREAD

**Issue by Icecroft** [andris155/TheOld-Crafters#2753]
A szigeten lévő állataim apránként eltűnnek. A csirkék tehenek pótlása még nem gond, de a szines birkáknál már zavaró. Van valamilyen mechanizmus ami öli a zárt helyen lévő állataimat?

**Comment by andris155** [comment]
mennyi állatot tartasz összesen?

**Comment by Icecroft** [comment]
38 birka, 18 tehén, 13 csirke + a falusik

**Comment by andris155** [comment]
Növeltem a limitet.
