### ISSUE TITLE
[Ötlet] Telek vásárlási lehetőség

### ISSUE THREAD

**Issue by Huntermaster0** [andris155/TheOld-Crafters#2755]
A minap jöttem rá, hogy elhasználtam mind az 50 szabad telkemet, összevontam egyben 36-ot építésre, 12-t redstoneozásra és 2 telken terül el a Redstone Amőba. Szerintem ilyen esetekre jó lenne, ha lehetne venni telket valamilyen magas áron.

**Comment by MrZero1** [comment]
Gyorsan megnéztem, és mivel van /plot buy jog, így lehetne erre is jog.

A játékos beállítja az eladni kívánt telek árát - /plot flag set price ár - majd a másik játékos megveszi - /plot buy.

Gondolom ez csak úgy lehet, ha a rang még letud foglalni telket.  

![kép](https://user-images.githubusercontent.com/29709854/54149220-f5d76400-4435-11e9-9278-5865db26bc60.png)

**Comment by MrZero1** [comment]
* Csak úgy lehet, ha tudsz még alapból telket foglalni. De szerintem ígyis hasznos lenne, mivel nem minden rangos maxolja ki a telkét (khm Hunti :D), a tagok is szívesen vesznek telket, ha megéri.

**Comment by andris155** [comment]
Nincs ilyen lehetőség a plugin-ban, hogy a vétellel túl lehetne lépni a limitet.

**Comment by MrZero1** [comment]
Valóban nincs rá lehetőség, de szerintem attól még lehetne rá jogot adni, szerintem élnének a lehetőséggel.

**Comment by andris155** [comment]
Eladásra?
