### ISSUE TITLE
Survival - belépés hiba (?)

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#2757]
Ma már 3-4x volt ilyen.

![kép](https://user-images.githubusercontent.com/16057404/54208788-dba49100-44dc-11e9-92d8-05dc17798e41.png)
![kép](https://user-images.githubusercontent.com/16057404/54208861-fd057d00-44dc-11e9-96a6-8adf77d4364b.png)

**Comment by andris155** [comment]
Ez azóta is így van?

**Comment by UDPSendToFailed** [comment]
Nem sokat voltam fent, nem tudom. :/ Lehet, hogy ennek van valami köze a "szerver leállt" üzenetes kickeléshez.

**Comment by andris155** [comment]
```
[15:33:32] [Server thread/INFO]: Icedhermelin lost connection: Kidobott a rendszer, mert 15 percnél tovább voltál távol.
[15:33:32] [Server thread/INFO]: [ChatControl] [-] Icedhermelin
[15:33:32] [Server thread/INFO]: [ChatControl] [+] Icedhermelin
```

**Comment by andris155** [comment]
Fogalmam sincs ez, hogy történhetett meg, de szerintem ez a hiba nem igazán fordult azóta elő.

**Comment by andris155** [comment]
Ha megint előfordul nyiss új hibajelentést erre hivatkozva és akkor írok a fejlesztőnek.
