### ISSUE TITLE
Savsziget - Bolt

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#2758]
Shop
Hogy növényeket ne lehessen venni /shop-ból, mivel a küldetések nagy része azért van, hogy megszerezd azt az adott növényt, legyen az sima cékla, vagy akár endnövény. 
Kikerülése nélkül szerintem túl könnyű a növények szerzése.

Esetleg ha az ércek esélyének drasztikus csökkenése mellett döntenétek, akkor ajánlom hogy vegyétek ki az érceknek az eladását /shop-ból. 
 
-------------------------------------------------------------------------------------------------------------------

Több ember jelezte baja/gondját, azért írtam, és részben meg is értem mind a 2 oldal
mint a staffok szemszögéből, mint a játékosok szemszögéből is.

Remélem senki se fog örjöngeni ettől :v

**Comment by poma123** [comment]
Nem lehetetlenít el semmit az generátor, teljesen reálisan van beállítva.

**Comment by poma123** [comment]
Az endnövény és a cékla vásárlását letiltom.

**Comment by skrisz0101** [comment]
ez csak 2 példa volt xd

**Comment by poma123** [comment]
A többi növényt nem tudod megszerezni olyan könnyen, + nem is olcsók. Így marad. :)
