### ISSUE TITLE
Pet plugin hiba

### ISSUE THREAD

**Issue by dingdong2000** [andris155/TheOld-Crafters#276]
Hiba történik amikor a /ps parancsot beírjuk. A pvp pluginnál a pvpd státuszát írja ki.
A mypet pluginnál pedig a peted lestoppolása lenne [https://wiki.mypet-plugin.de/doku.php?id=en:commands](url) <- Itt olvasható.

**Comment by andris155** [comment]
![kepkivagas](https://cloud.githubusercontent.com/assets/8324198/17643574/9d3e3e2e-616e-11e6-8134-2ef56bdfa3b1.PNG)

**Comment by dingdong2000** [comment]
De megy, csak ez egy rövidítése.

**Comment by andris155** [comment]
Néha sajnos ütköznek az aliasok a pluginoknál, de azért van ott a másik 2 parancs.
