### ISSUE TITLE
Fly+Magmablock

### ISSUE THREAD

**Issue by Huntermaster0** [andris155/TheOld-Crafters#2760]
Ha fly kikapcsolása után (vagy csak simán) leesünk egy magmablockra, dobál, leesik a karakter majd visszarakja oda ahol volt, és újra leejti, és ez folyamatosan ismétlődik.

+teszt, emiatt sétálni sem lehet a magmablockon

**Comment by andris155** [comment]
Videót kérlek tudsz erről csinálni?

**Comment by Huntermaster0** [comment]
https://youtu.be/kwBKlEX_oF0
