### ISSUE TITLE
1v1 hiba

### ISSUE THREAD

**Issue by Konc0321** [andris155/TheOld-Crafters#2763]
Nem olyan rég egyik barátommal 1v1-eztünk pár kört a survival szerveren, majd miután meguntuk, kiléptünk. Én amikor másnap visszaléptem a spawnon éledtem, neki viszont a halálképernyő jelent meg, ebből adódóan minden cucca elveszett. Nem volt nála semmi pótolhatatlan, de másnál a későbbiekben lehet, hogy lesz, és elveszti.

**Comment by andris155** [comment]
Valószínűleg még harcban voltatok, ezért megölt a kilépésért.
