### ISSUE TITLE
Luckyblock & PlotSquared

### ISSUE THREAD

**Issue by Huntermaster0** [andris155/TheOld-Crafters#2766]
Mivel a Luckyblock kinyitása után a ketrecet (ugye a 3x3 alapú kőketrec) oda rakja, ahol állsz, így akár az útra is mehet a ketrec, ami a telkeken néha zavaró lehet.

**Comment by andris155** [comment]
https://github.com/SickSkillz/SLB-Tracker/issues/13

**Comment by andris155** [comment]
elvileg javításra került.
