### ISSUE TITLE
Beváltó Ládák

### ISSUE THREAD

**Issue by EHzy001** [andris155/TheOld-Crafters#2768]
a /beváltónál vehető láda kulcsok elégé nem érik meg.
Pl. a 'leggyengébb' is 100 token, és lehet kapsz egy pajzsot, vagy lánc szettet. Még a trident sem ér annyit, 12 tokenért lehet venni,
A legdrágább 250 token... ne vicceljünk már. 64 szivacs? 64 obszidián? A enchant nélküli cuccokról pedig szó se essen. 
Szerintem elégé főlé lett lőve az áruk :/
- EHzy

**Comment by MrZero1** [comment]
Úgy gondolom, egy teszt jelleggel bekerült dolog miatt felesleges az ilyen stílusú közlés.

**Comment by GetOut101** [comment]
Nem működnek a frissítés után a ládák. A kulccsal amit tokenen vettem nem bírom kinyitni.

**Comment by Huntermaster0** [comment]
Get, #2910
