### ISSUE TITLE
Savsziget AFK farmolás

### ISSUE THREAD

**Issue by KulGery** [andris155/TheOld-Crafters#2770]
2 perc után, noha személyesen nyomom végig a törés gombot, megszakítja AFK farmolással.
Nem is gond. Szakítsa is meg.
Viszont. Hiába írok szöveget (csevegek) hiába megyek el onnan, utána ugyanúgy berakja második-harmadik törésre, a bedrockot, és kiírja hogy AFK török. Ez viszont nagyon nagy hiba.
Ha ott ülök a gép elött, miért nem törhetek sok követ. Akár úgy, hogy két percenként "pihenek"? De személyesen ott vagyok. Olvasom a Chetet stb.

**Comment by CoolIfAI** [comment]
Aki meg beállítja a poharat, akármit, hogy AFK farmoljon, az úgyis megakad 2 perc után.
Tehát jó lenne, ha észrevenné a törésjelző, hogy a törést abbahagytam, és teljesen más dolgot csinálok. pl elsétálok, vagy csetelek stb.

**Comment by CoolIfAI** [comment]
Más szerveren ezt úgy oldották meg, hogy AFK idő lejárta után (5 perc) mikor is kiírja, hogy az adott játékos AFK,. akkor nem engedi a játékosnak hogy felvegye a törést. Tudom itt gondot jelent a tölcsér, mely elnyeli a szerzeményt.

**Comment by CoolIfAI** [comment]
Nem hiszem, el, még fél percig sem zúztam... Hát hogy bányásszam így a követ???

**Comment by KulGery** [comment]
Bányásztam.. tegyük fel 3 percig. Be is rakta a bedrockot, vagy mittomit
Gondoltam, másik oldalról szerzek még pár követ, mert nyolc percnyi búvárkodás közben többet tudok lerakni...
Viszont egy rosz mozdulat miatt kiütöttem két tölcsérem, elmosta a víz, és még bedrock is lett. Hogy lenyugodjak, kimentem a kétharmadnyi kővel, búvárkodni.
Mikor viszajöttem, rendbe akartam tenni a kőgent, de a hozzáférés miatt ki kellett ütnöm néhány zúzott követ. Pontosabban csak kettőt, mert rögtön berakta a bedrockot. Pedig 6 percig nem törtem követ egyáltalán!
Ne mondjátok, hogy ez így jól működik!
Ja és végig a kezecském kicsike ujjacskájával nyomtam a gombot, miközben aktívan részt vettem a játékban. Tehát amikor AFK miatt "jogosan" letiltott, akkor sem AFKoltam!

**Comment by KulGery** [comment]
Remélem nem kértek, egy 10 perces klippet, melyen újra eljátszom a jelenetet...

**Comment by KulGery** [comment]
[https://1drv.ms/v/s!AngEoMrRBC3GhHVEuzhPkxIeMSWx](url)
kb 3 perc várakozás
[https://1drv.ms/v/s!AngEoMrRBC3GhHR4DDb5F7Poi-qA](url)

**Comment by KulGery** [comment]
Ne mopst komoly? Gondoltam, horgászok néhány pufi halat a vízlégzéshez. Összesen egyszer engedett fogni, utána azt mondta a fogás pillanatában, hogy túlhorgásztam! meg sem adta amit kifogtam!

Szóljatok, ha játszható lesz a szerver.

**Comment by MrZero1** [comment]
Lezárva, mert a hozzáértők részéről nem jött rá válasz.

**Comment by KulGery** [comment]
Újra próbáltam abszolút nem AFKolva követ törni, azaz fél percig törtem, majd kemencéztem, majd törtem kemence stb. Stopperral mértem... Kerek két perc törés után betette a bedrockot.

Értem, hogy ez nem hiba, hanem direkt ilyen, de miért kell szivatni a nem AFK-os játékosokat?
Ráadásul azt mondja, 20 sec-t pihenjek, De 20 másodperc pihi után ugyanúgy  berakja a bedrockot.

**Comment by andris155** [comment]
Mert nem afk-val kellene másokkal szemben előnyt szerezni. Meg nem afk-olni kell járni a szerverre, hanem játszani. Csak tönkreteszed vele magadnak is a játékélményt azzal, hogy így szerzel meg mindent.

**Comment by KulGery** [comment]
Kedves András!

 

Tudod mikor AFK-oltam utoljára?

 

Még az 1.12.2-es verziónál, de azzal is felhagytam, pont azért mert rontja a játékélményt.

 

Pont ez a bajom, hogy nem AFKolok, mégis azt hiszi a rendszer, és utána úgy letilt, hogy nem tudok normálisan játszani!

 

Vagy az AFK, hogy a kezemmel nyomom a törés gombot, és figyelek a chetre is, és reagálok is rá?

Az AFK, hogy félpercenként, direkt félbehagyom a saját kezem által törést, kiégetek, búvárkodom (8perc) és utána ugyanúgy letilt, ha letelik a két perc? A két perc után meg ki tudja, minek kell történnie, hogy újra engedje a törést?

 

Míg Dealer folyamatosan online, mégsem válaszol, addig én még a nádfarmhoz sem csináltam autóarató gépet. A jelen szigetemet az egészet úgy építettem, hogy itt ültem a gép előtt. Nem voltam Away From Keyboard, azaz távol a billentyűzettől.

 

Ha valakinél kell keresned, akkor nem nálam az AFK-ot.

De ez a plugin ezekkel a beállításokkal a nem AFKolós, azaz Sitting Front Keyboard sem játszható. Ezért vagy ti nézzétek meg, hogy beállítható-e, vagy a fejlesztő, vagy inkább használjatok más plugint.

Habár asszem van egy módszerem, mellyel ki tudom kerülni, de szerintem nem kerülgetni kell. És nem AFK-olós, hanem kifejezetten mászkálva kell úgy törni a sok követ.

Igaz így lassabb lesz, de ha már a szakértők nem tudnak hozzászólni, és még te is azt hiszed, hogy AFK-olok, akkor kénytelen vagyok ezt bevetni.

 

Üdv. KulGery

Tester & Player
