### ISSUE TITLE
Állatok

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#2774]
Egyik srác hív: volt 30 tehene, most már csak 4 + 2 pici. Mire odatpztem, már csak a 2 pici maradt.
A csirkék közvetlenül mellette voltak, abból nem tűnt el semmi. 
Ez a moblimit hogy is van? Mert sztem nem tökéletes :/

**Comment by andris155** [comment]
Melyik szerver?

**Comment by skrisz0101** [comment]
szurvi, de már asszem szólt ice is savon

**Comment by andris155** [comment]
Növeltem a limitet.
