### ISSUE TITLE
Delfin

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#2776]
Nem lehet lovagolni a delfinen, teknősön, witheren.
Befogni se lehet őket vödörrel

**Comment by andris155** [comment]
Most működik?

**Comment by nicolettie** [comment]
delfinen és teknősön próbáltam és lehet rajtuk lovagolni :) [11:50]

**Comment by andris155** [comment]
köszi

**Comment by andris155** [comment]
javítva
