### ISSUE TITLE
PVP védelem

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#2779]
![kép](https://user-images.githubusercontent.com/29709854/55002730-65715580-4fd7-11e9-99d7-1259388f3b5a.png)

Helló! Megdobtam egy játékost tojással, majd kiírta, hogy pvp-ben vagyunk, majd felakartam venni a földön lévő itemeket, erre ezt kezdte el spamelni, de mint állat. :D

**Comment by andris155** [comment]
Javítva.
