### ISSUE TITLE
Lucky Block

### ISSUE THREAD

**Issue by nicolettie** [andris155/TheOld-Crafters#2780]
A Lucky Blocknak kézben nincs skinje, csak egy alap steve fej, viszont a neve rendesen megjelenik, letéve már skin is van rajta és működik is. Ez lehet hiba? :)
![2019-03-27_11 44 48](https://user-images.githubusercontent.com/48986609/55070100-d0796580-5085-11e9-96f6-011a904ff304.png)

**Comment by andris155** [comment]
Néha túl sok a skin lekérés a szerveren ilyenkor, ami a limiten túl lenne annak nem tudja lekérni a skinét. Sajnos ezzel nem lehet mit csinálni. Leginkább szerver indításnál szokott ez gond lenni, mert van pár plugin, ahol a top listához, ekkor kéri le a skineket.
