### ISSUE TITLE
Kérés.

### ISSUE THREAD

**Issue by Viktor1969TOC** [andris155/TheOld-Crafters#2784]
A survival szerverre lehetséges egy "Bank" plugint behelyezni? (Hitel részletes visszafizetéssel, Pénz be van rakva és kamatozik, stb.)

**Comment by MrZero1** [comment]
Volt, bugos volt, azóta nem tudom milyen, mik vannak.

**Comment by andris155** [comment]
Valószínűleg visszaélnének ezzel, ha lenne. Szóval ilyen nem lesz.
