### ISSUE TITLE
Savsziget MCMMO

### ISSUE THREAD

**Issue by Raxoray** [andris155/TheOld-Crafters#2785]
Úgy tudom a napokban kilett véve az MCMMO vízszint alatti duplázás miatt.
Most hallottam hogy frissítve lett és be lett rakva az új ennek ellenére a duplázás még mindig fennáll, szuper törésnél viszont néha triplázza is generált itemet.
Az esetleges OCD-t Trymer névre szeretném.

**Comment by skrisz0101** [comment]
A generált item alatt pl kőre célzol vagy mire?

**Comment by Raxoray** [comment]
Minden generálható dolog.

2019. márc. 31., V 20:12 dátummal skrisz0101 <notifications@github.com> ezt
írta:

**Comment by andris155** [comment]
,,Úgy tudom a napokban kilett véve az MCMMO vízszint alatti duplázás miatt." Erről sem én sem poma nem tud.
