### ISSUE TITLE
Savsziget - Napi event WILDRUN

### ISSUE THREAD

**Issue by Raxoray** [andris155/TheOld-Crafters#2786]
A Wildrun nevezetű event végén található egy sátor ággyal, ha abba az ágyba lefekszünk, akkor lerakja a bed nevezetű homet, ezáltal bármikor oda tudunk menni erőfeszítés nélkül. 
Az esetleges OCD-t Trymer névre szeretném.

**Comment by MrZero1** [comment]
Javítva.
