### ISSUE TITLE
Automata eventek

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#2787]
Pettel is belehet csatlakozni. 
![2019-03-31_12 18 57](https://user-images.githubusercontent.com/29709854/55287886-60355180-53af-11e9-94bc-0ea7c1d57546.png)

**Comment by MrZero1** [comment]
@poma123

**Comment by poma123** [comment]
Hamarosan egy jobb rendszerrel lesz ez megoldva, majd javítom

**Comment by poma123** [comment]
Javítva
