### ISSUE TITLE
Mob sebzés bug

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#2788]
Alig lehet ölni a mobokat, hiába ütöm őket, egyszerűen nem sebez a kard, csak néha javul meg egy kis időre. 

https://youtu.be/LQQN-RjQOtI

**Comment by andris155** [comment]
Mikor ütötted pontosan így a mob-okat?

**Comment by UDPSendToFailed** [comment]
03. 31. 12:53:39-kor indítottam el a felvételt, de kb végig így bugolt amíg fent voltam.

**Comment by andris155** [comment]
mekkora ping-el szoktál játszani?

**Comment by UDPSendToFailed** [comment]
A net sebessége nem változott mostanában, pár napja még simán lehetett ölni őket. Ma is próbáltam, ugyanúgy bugol.

![kép](https://user-images.githubusercontent.com/16057404/55331262-2fc6e380-5493-11e9-838f-7765938277bb.png)

**Comment by andris155** [comment]
Most sem jó?

**Comment by UDPSendToFailed** [comment]
Sajnos nem. :/ Érdekes, hogy ha fly-al átmegyek a másik sarokba, akkor 1-2 ütésig megjavul.

**Comment by andris155** [comment]
Hol tudom tesztelni ezt?

**Comment by andris155** [comment]
Most sem jó?

**Comment by UDPSendToFailed** [comment]
Nem 100%-osan, de már sokkal jobb mint volt, 10-ből 8-9 ütés sebez is.
