### ISSUE TITLE
Aukció tárgy törlődés

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#2789]
Ha lejár egy aukció, átrakja a tárgyat oda, ahonnan vissza lehet venni, régebben innen nem törlődtek a cuccok. Így viszont elég rossz, 20-30 enchantkönyvet eltüntetett amíg nem voltam fent.

![kép](https://user-images.githubusercontent.com/16057404/55291707-f84c2e80-53e1-11e9-8ca4-48124f044fdb.png)

**Comment by andris155** [comment]
Ez nem igazán hiba. Azért törlődnek, mert törlés nélkül az adatbázis egy idő után tele lenne feleslegesen tárolt tárgyakkal is, ami pedig lelassítja.
