### ISSUE TITLE
Plugin javaslat

### ISSUE THREAD

**Issue by dingdong2000** [andris155/TheOld-Crafters#279]
[https://www.spigotmc.org/resources/friends2-0-mc1-7-1-9.12063/](url) ezt a plugint ajánlom a szerverre, nagyon áttekinthető. :dancer:

**Comment by andris155** [comment]
Ez valamelyik szerver már van?

**Comment by dingdong2000** [comment]
Magyar szerveren még nem láttam, de a magyarosítás is nagyon egyszerű.

**Comment by dingdong2000** [comment]
https://youtu.be/HW8JGhf0dKE
