### ISSUE TITLE
/god 

### ISSUE THREAD

**Issue by Nkiraly3** [andris155/TheOld-Crafters#2790]
ma öltem a sárkányt és úgy mentem oda hogy a páncélomnak a hp-ja kb több mint a felénél voltak mikor be fejeztem a sárkény ölést észre vettem hogy az old sapkám eltört pedig a /god parancsom be volt nyomva  ez ügyben mi lehetne tenni ?:/

**Comment by andris155** [comment]
Úgy tűnik god-al is eltudnak törni a tárgyak.
