### ISSUE TITLE
Savsziget hibás küldetés

### ISSUE THREAD

**Issue by Maflacs** [andris155/TheOld-Crafters#2791]
A savszigeten a haladó küldetések közül az Alkémikus összesen 8 potiont kér, de hiába van az inventoryban minden kért bájital, mégis azt írja ki, hogy You do not have enough Potion to complete this challange!

_Ecu_

**Comment by MrZero1** [comment]
@poma123

**Comment by poma123** [comment]
Regen II. (0:22)
Erő II. (1:30)
Láthatatlanság (8:00)
Azonnali sebesülés II.
Azonnal gyógyulás II.
Gyorsaság (3:00)
Lassúság (1:30)
Tűzállóság (3:00)
ezek kellenek hozzá.
