### ISSUE TITLE
Savsziget: valami új plugin hiba

### ISSUE THREAD

**Issue by Icecroft** [andris155/TheOld-Crafters#2793]
A savszigeten valami új plugin van az mcmmo mellett, ami "crafting"-ért "walking"-ért stb szinteket ad. Ezek a szintek teljesen random számoknak tűnnek, a folyamatos tűzijáték pedig elég zavaró:
![2019-04-01_10 09 02](https://user-images.githubusercontent.com/19332825/55321266-845d6500-5479-11e9-9fcf-4d592d966f24.png)

**Comment by andris155** [comment]
Mi lehet ez?

**Comment by Icecroft** [comment]
Az mcmmo Olvasztás skillje csak a Bányászathoz és Javításhoz ad pontokat. Crafting skillt, eddig nem láttam, sem Walking-ot, sem Wrecking-et
A kiírás stílusa is különbözik az mcmmo-tól
A hibát csak ma reggeltől tapasztaltam.

**Comment by poma123** [comment]
Április elseje miatt.
![image](https://user-images.githubusercontent.com/25465545/55346053-c904f280-54b1-11e9-94d2-f51f3b070eb1.png)
