### ISSUE TITLE
MCMMO vízalatti homok ásás

### ISSUE THREAD

**Issue by jokoboy** [andris155/TheOld-Crafters#2794]
https://youtu.be/e5oo42G30wk
Ha a víz alatt ásom azt a homokot amit én rakok le, azért is kapok mcmmo ásás-xp-t.

Doge

**Comment by andris155** [comment]
A víz felett ez nem megy?

**Comment by jokoboy** [comment]
a víz felett nem.

**Comment by Icecroft** [comment]
csak azokért a blokkokért jár mcmmo pont, amiket nem te raktál le. Ha a homokblokk odaesik és kiásod, akkor jár. Ez függetlenül attól, hogy víz alatt vagy felett történt.

**Comment by andris155** [comment]
Tudom teszteltem.

**Comment by andris155** [comment]
elvileg javítva.

**Comment by andris155** [comment]
330 OCD
