### ISSUE TITLE
Jogok, rangok

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#2795]
Hali. Többször szóba jött, hogy a prémium rang, ami az egyik legkelendőbb, szürke színe nagyon csúnya. Erre jött a javaslat, lehetne &5 színű. Szerintem tök jó lenne, nem is csúnya a szín. :D

A másik, a 3 szín a névben szabályzat eléggé elavult, főleg, hogy sokan élnek vele. Szerintem lehetne 4 akár 5 szín is a névben, hisz a chat attól szép, ha színes és ha pörög. ☺

**Comment by JohnnyMoarr** [comment]
+1

**Comment by nicolettie** [comment]
(+1) támogatom a javaslatot :)

**Comment by MrZero1** [comment]
![kép](https://user-images.githubusercontent.com/29709854/55480751-44d17d00-5621-11e9-9faf-68b7453c56c1.png)

Ilyen lett. Szerintem szép, jobb, mint a szürke.

**Comment by andris155** [comment]
Lila átszínezések:
- [x] Rang prefix (Essentials, nte, Luckperms
- [ ] Rangok npc menü átszínezés
- [ ] Survival rangok terrakotta átszínezés.
- [ ] MineMarket rang kép átszínezés.

A szabály átírva max 5 színre.

**Comment by andris155** [comment]
Le kell majd töltenem a Photoshop-ot, amit a Windows Sandbox-ban akartam, de sajnos egy ideje nem jó a Windows Sandbox. Szóval majd felrakom simán, ha lesz időm.

**Comment by poma123** [comment]
kuldd el a .psd-t

**Comment by andris155** [comment]
kész
