### ISSUE TITLE
[Info] ?

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#2796]
![kép](https://user-images.githubusercontent.com/29709854/55483556-1a82be00-5627-11e9-9a7d-e6ecc3e47dbb.png)

Ezek direkt nem mennek?

**Comment by andris155** [comment]
Javítva. A többi ilyet kiszedtem, mert úgy is ki van írva a kezdőhelyen meg a MineMarket-ben is.
