### ISSUE TITLE
Spawn labiritus

### ISSUE THREAD

**Issue by EHzy001** [andris155/TheOld-Crafters#2797]
Ha végig viszem a spawnon lévő labirintust, majd kiszedem a lootot, és kilépek a szerverről, a ugyanott, a kincs mellet leszek belépés után.
Illetve /back-al is vissza lehet menni oda.

- EHzy

**Comment by MrZero1** [comment]
Azért kicsi az esélye annak, hogy 1 ember 24 órát ott afkol vagy csak azért lép fel, hogy kilootolja.:D De ha igen, akkor pacsit neki.:D A /back is csak addig visz oda, míg el nem megy más helyre.
