### ISSUE TITLE
Mcmmo ötlet, illetve kérdés is egyben

### ISSUE THREAD

**Issue by SurvivorTheReal** [andris155/TheOld-Crafters#2798]
Azon gondolkoztam van-e bármilyen bónusz az MCMMO skilleknél lvl 100 után. Akár 500 as szinten, vagy később. Ha van, akkor tárgytalan amit most fogok írni.

Lehetne valami bónusz minden skillnél ha a player eléri a lvl 1000 et, vagy 1500 at, ha van 1500 egyeltalán. Nem gondolok itt semmi nagyon OP bónuszra, de olyasvalami amiért megéri ennyit tolni az adott skillt. Esetleg egy új alskill, mint bányászatnál a szuper törés vagy a dupla esés vagy már meglévő alskill fejlődése. Gondolok itt arra hogy a  dupla esés helyett mondjuk tripla esés legyen. Lehet nem a legjobb ötlet, de ez csak egy példa.

Nem tudom van-e realitása az ötletnek, de egy próbát megér.

**Comment by andris155** [comment]
Az mcMMO ötleteket kérlek az mcMMO-nak írd meg.

**Comment by andris155** [comment]
https://github.com/mcMMO-Dev/mcMMO/issues
