### ISSUE TITLE
BountyHunters - HCX

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#2799]
![kép](https://user-images.githubusercontent.com/29709854/55586217-bba56d80-5728-11e9-8668-6912ef127b26.png)

@poma123

**Comment by poma123** [comment]
A configban meg lehet változtatni. Nem tudom miért kellek én hozzá feltétlenül.

**Comment by poma123** [comment]
Javítva, a kedves fejlesztő átváltoztatta ezt az egyet %player%-re, nagy titokban.
