### ISSUE TITLE
Támogatói rangok fejlesztése

### ISSUE THREAD

**Issue by andris155** [andris155/TheOld-Crafters#280]
- Több munka.

**Comment by Kayalafur** [comment]
Ha meg tudod oldani, hogy több munkát vehessenek fel a rangosok, az egy jó megoldás. A duplázás, már ott van a prémium rangban, de kevesen használják ki. Ha az emberek pénztárcáját nézzük, akkor a sok kicsi sokra megy stratégia felé kellene elmenni.

**Comment by andris155** [comment]
Több munka - kész
