### ISSUE TITLE
Infó (rangjogok) 

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#2801]
A /infó tagjogok, vipjogok, stb eléggé hasznos volt. Nem tudja senki se kívülről hogy hány petje lehet egy elitnek, vagy épp milyen jogai vannak a tag+nak.
Hogyhogy kikerült? Szerintem hasznos volt

**Comment by andris155** [comment]
A tagjogok működik. A többi a MineMarket-en elérhető illetve a kezdőhelyen.
