### ISSUE TITLE
Fordítási hiba - SAVSZIGET

### ISSUE THREAD

**Issue by Raxoray** [andris155/TheOld-Crafters#2802]
TOKENMANAGER:
A tokenmanager pluginban a /tokens balance [név] parancs beírása után olyan üzenetet kapunk vissza hogy: "Ehhez nincs tokenmanager.use.balance.others jogosultságod." Illetve /tokenmanager parancsra ezt adja ki "Ehhez nincs tokenmanager.admin jogosultságod."

COREPROTECT: a /co leírása nincs magyarosítva, ha beírod akkor is angol szöveget kapsz.

**Comment by andris155** [comment]
A tokenmanager fordítása szerintem rendben van, hiszen nincs olyan jogod hozzá. A co-t pedig nem is lesz lefordítva, mivel nem a játékosoknak van.
