### ISSUE TITLE
Buborék lift használhatatlan -megint-

### ISSUE THREAD

**Issue by Konc0321** [andris155/TheOld-Crafters#2803]
Egy korábbi posztban megjelenő probléma ismét elő jött, miszerint ha felfelé próbálok menni buborék liftben, (alul lélekhomok, fölé víz) akkor kb 15 blokk után visszadob 3-at, így drasztikusan lelassítva az egész utazásos folyamatot. Meglehetősen zavaró tud lenni

**Comment by andris155** [comment]
Videó kellene erről, amit eltudok küldeni a fejlesztőnek.

**Comment by SurvivorTheReal** [comment]
Konc ha nincs olyan programod ami felveszi, vagy esetleg a gép nem elég erős hozzá, bár kétlem, szerintem Doge szívesen felveszi neked.

**Comment by andris155** [comment]
Most sem jó?

**Comment by Konc0321** [comment]
Most jónak tűnik, köszi 😄

**Comment by andris155** [comment]
508 OCD
