### ISSUE TITLE
Savsziget: Event spamming

### ISSUE THREAD

**Issue by Icecroft** [andris155/TheOld-Crafters#2804]
A rendszer 2 percenként spammel a chaten automatikus Run eventtel, de soha nem indul:
![2019-04-05_22 38 03](https://user-images.githubusercontent.com/19332825/55655273-0809af80-57f4-11e9-8737-1442e427cb93.png)

**Comment by andris155** [comment]
Láttam én is. Fogalmam sincs miért.

**Comment by poma123** [comment]
azért mert 5 játékos alatt nem indul el, de hamarosan új rendszer lesz.

**Comment by poma123** [comment]
egyébként 10 perc után ha nem indul el magától leáll.

**Comment by Icecroft** [comment]
A probléma az volt, hogy a 10 perces limit nem működött, ment egész délután.
