### ISSUE TITLE
Wither boss felrobban

### ISSUE THREAD

**Issue by SurvivorTheReal** [andris155/TheOld-Crafters#2811]
Ha leidézem a wither-t, akár overworldben akár netherben, álldogál egy darabig, villog is, és pár másodperc múlva felrobban és eltűnik. MrZero-t megkértem tesztelje ő is, neki is ugyanez.

**Comment by andris155** [comment]
world_nether világ?

**Comment by SurvivorTheReal** [comment]
Ezt most nem értem, igen a netherben is ez a helyzet, ahova a /warp pokol rak. Ahol már tudok építeni onnét kicsit messzebb próbálkoztam, sikertelenül.

**Comment by andris155** [comment]
De akkor mi az az overworld?

**Comment by andris155** [comment]
Az lenne az end?

**Comment by SurvivorTheReal** [comment]
Ömm, az overworld a vadon, ne haragudj :D először fogalmaztam, hogy mondjam, na mind1 túlbonyolítottam. Most hogy mondod end-ben is megpróbálom megidézni, hátha. De ezt majd holnap, hétfőn.

**Comment by andris155** [comment]
Ez gáz, hogy nem működik. :/

**Comment by andris155** [comment]
javítva

**Comment by andris155** [comment]
508 OCD

**Comment by andris155** [comment]
Milyen névre adjam?

**Comment by MrZero1** [comment]
Ismét él a hiba, vagy azóta is, nem tudom. Leraktam mindent, vártam, hogy "elkészüljön", majd BUMM :bomb: :c 

![2019-05-01_22 51 26](https://user-images.githubusercontent.com/29709854/57042044-ec16f380-6c63-11e9-9c0c-f910d42a1e35.png)

Itt a meghalós szöveg is. 
![kép](https://user-images.githubusercontent.com/29709854/57042131-27192700-6c64-11e9-9146-52fac00baacc.png)

**Comment by MrZero1** [comment]
Hát, Ehzy és Huntermaster is csinált, nekik nem halt meg. Akkor csak engem nem akar szeretni :(
