### ISSUE TITLE
Teleportálás szöveg

### ISSUE THREAD

**Issue by nicolettie** [andris155/TheOld-Crafters#2812]
"Teleportálás **mosten** belül. Ne mozogj!"
![2019-04-12_14 04 23](https://user-images.githubusercontent.com/48986609/56036023-0aa46180-5d2c-11e9-921c-5e42fb981d02.png)

**Comment by andris155** [comment]
Sajnos máshogy nem lehet megoldani a fordítást ez esetben, hogy mindenhogy jó legyen. Ha átírnám, hogy {time} múlva, akkor is hülyén nézne ki a most múlva.
