### ISSUE TITLE
Inventorymove check hiba kreatívban

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#2813]
![kép](https://user-images.githubusercontent.com/29709854/56054834-2faec980-5d58-11e9-84d1-5ab3de02e886.png)

Szóval, ha nincs a táskádban olyan blokk, amit leakarsz másolni görgővel, hibát ír ki. Tehát guggolsz és görgőzől, hibát ír ki, nekem is, másnak is.

**Comment by andris155** [comment]
Most működik?

**Comment by MrZero1** [comment]
Most jó nekem.

**Comment by MrZero1** [comment]
Ehzy tesztelte, neki is jó, nem jött ilyen hibaüzenet a chatre.

**Comment by andris155** [comment]
Akkor javítva.
