### ISSUE TITLE
Ötlet

### ISSUE THREAD

**Issue by Raxoray** [andris155/TheOld-Crafters#2815]
Esetleges spawnerrel működő mobfarmoknál sok mobnál felléphet nagy lag, ezt köszöbölhetni lehetne a StackMobs nevezetű pluginnal. 
Videó a pluginról: https://www.youtube.com/watch?v=2gZD_TOge7Y

**Comment by andris155** [comment]
Volt a szerveren, de nem nagyon rajongtak érte a játékosok. Sajnos gagyi ilyen szempontból a játék, mert nem tudja kihasználni a több magos processzorokat.

**Comment by andris155** [comment]
Persze lehet venni egy magon erős processzort, de szerintem már nincs sok értelme, mert a többi játék már egyre jobban támogatja a több magot. Így egy Ryzen-el sokkal jobban jár az ember sokkal jobb áron az egy magon erős Intel-kel szemben.

**Comment by andris155** [comment]
Ha esetleg még nem telepítettél Optifine módot azt mindenképpen ajánlom.
