### ISSUE TITLE
Pweather clear

### ISSUE THREAD

**Issue by nicolettie** [andris155/TheOld-Crafters#2816]
[a vadonban vagyok] beírtam, hogy ./pweatherclear, hogy elállítsam az esőt, eddig működött, most viszont eláll, majd körülbelül 2-3 másodperc múlva megint elkezd esni. (eddig működött a parancs)
![2019-04-13_22 24 32](https://user-images.githubusercontent.com/48986609/56084928-2e0a0200-5e3b-11e9-8885-b8b928c32a1c.png)

**Comment by andris155** [comment]
Nem olyan védésen vagy, ami felülírja?

**Comment by nicolettie** [comment]
nem voltam levédésen, lucky blockokat "nyitottam", tehát biztosan nem volt védés :)

**Comment by andris155** [comment]
Azóta sem működik?

**Comment by nicolettie** [comment]
ma próbáltam 11:51-kor, és még mindig ugyan az a hiba.

**Comment by nicolettie** [comment]
a pweather clear, és a pweather sun paranccsal is pár másodperc után visszavált esőre sajnos.

**Comment by andris155** [comment]
Most sem működik?
Frissítettem a szerverfájlt.

**Comment by andris155** [comment]
https://github.com/andris155/TheOld-Crafters/issues/2839
