### ISSUE TITLE
Savsziget - Tag+, V.I.P. szavazásért

### ISSUE THREAD

**Issue by Raxoray** [andris155/TheOld-Crafters#2817]
Lehetne a Savsziget szerverren is szavazói Tag+, és VIP rang mint a survival szerveren?

**Comment by MrZero1** [comment]
Jó ötlet. Főleg, hogy mostanában többen játszanak ott is.

**Comment by andris155** [comment]
@poma123

**Comment by poma123** [comment]
lehetne, mivel az en megoldasom el lett tavolitva a beka ala, nem nekem kellene megcsinalni, nem tudom hogy van a tobbi szerveren

**Comment by andris155** [comment]
A Luckperms-el van időre adva rang, amikor megveszik. A másik szerveren ott a Votingshop konfig résznél a parancs, de Tag+ nincs a Savszigeten.

**Comment by andris155** [comment]
Beraktam a vipet szavazásért.
