### ISSUE TITLE
Rang upgrade

### ISSUE THREAD

**Issue by nicolettie** [andris155/TheOld-Crafters#2818]
Ez inkább egy ötlet, mint probléma. Láttam egy külföldi szerveren a rang upgrade-et, ami talán ide is hasznos lenne. Bár náluk véglegesek a rangok, így kicsit más, de hátha tetszik az ötlet. 

Tehát Mondjuk a Tag+ 330 OCD, a VIP 508 OCD, ha valaki jelenleg Tag+, de úgy érzi hogy szeretne inkább VIP lenni, viszont inkább megvárná míg lejár a Tag+, de az meg például még 1 hónap, akkor az 508 OCD helyett fejleszthetné a rangját mondjuk a VIP rang árának feléért, 254 OCD-ért VIP-re, hogy mégse teljes áron kelljen megvegye, és az előző vásárlás értéke elvesszen. (mert ugye így nem használta ki teljesen a rangot amit megvett 330 OCD-ért, ezért fejleszthetné fél áron az egyel feljebb lévő rangot, így a pénz így balance-olva lenne a játékos számára is a szervernek is).

[Tag+]-ról [V.I.P.]-re 254 OCD
[V.I.P.]-ről [Elit]-re 508 OCD
[Elit]-ről [Prémium]-ra 1016 OCD
[Prémium]-ról [Old]-ra 2540 OCD
(ezek csak példa összegek a demonstráláshoz)

**Comment by andris155** [comment]
A MineMarket-ben sajnos ilyen lehetőség.
