### ISSUE TITLE
blokkok kimaradnak

### ISSUE THREAD

**Issue by KulGery** [andris155/TheOld-Crafters#2819]
Ha sorozatban teszem le a blokkokat, akkor elég sűrűn, és több méteren kimaradnak.
https://youtu.be/RYai9LHl3jg

**Comment by andris155** [comment]
most sem jó?

**Comment by KulGery** [comment]
Most sem... Persze lehet hogy a netemmel van baj,. de az eddig nem így jelentkezett... Akkor csak utólag építette be amit leraktam. Mondjuk ötméterenként utánam ugrott a blokkok.

**Comment by KulGery** [comment]
De már megyek is...

**Comment by andris155** [comment]
Letudod tesztelni újra, és megtudod mondani pontosan hánykor tesztelted és melyik nap?
