### ISSUE TITLE
Savsziget - Bolt ötlet (érc eladás)

### ISSUE THREAD

**Issue by Raxoray** [andris155/TheOld-Crafters#2824]
Savszigeten a sima érceket is lehessen eladnia shopban, kevesebb pénzért(aranyérc,vasérc stb..).

**Comment by andris155** [comment]
@poma123

**Comment by poma123** [comment]
ha lesz idom ranezek

**Comment by poma123** [comment]
Sweetre várok, hogy küldjön árakat.

**Comment by andris155** [comment]
Azóta sem küldte el?

**Comment by poma123** [comment]
hat a helyzet hogy nekem nem lesz idom megcsinalni, akar elkuldi akar nem szoval legyen akkor kinyitva egy uj jelentes miutan meg lesz beszelve hogy ki csinalja meg ha lesz-e egyaltalan

**Comment by andris155** [comment]
Én megcsinálom, csak az árakat várom hozzá.

**Comment by andris155** [comment]
Én ezt feladtam. Árak nélkül nem tudom mit kezdeni ezzel és már elég rég várok rá.

**Comment by poma123** [comment]
ezert zartam be en is :DDD
