### ISSUE TITLE
WorldEdit és WorldGuard védés játékosoknak

### ISSUE THREAD

**Issue by Huntermaster0** [andris155/TheOld-Crafters#2825]
Nos még régen meg lett szűntetve az a lehetőség, hogy az Adminok WorldEditeznek a játékosoknak pénzért cserébe. Ez nagyobb projekteknél hasznos volt, jól jött mikor ki kellett szedni pl. 300 000 követ. Aztán sokan már kisebb dolgokért is kértek segítséget az Adminoktól, ellustultak. Viszont ezzel el lett vágva a nagyobb projektek útja, mert ha valami nagyba fog az ember, jelenleg 60%-ban az a vége, hogy előtte ki kell szedni több teleknyi földet (példa erre BaaWoofék építménye a telekvilág egyik sarkában). Ezzel nem is lenne semmi gond, én magam is ezelőtt állok, survivalban már rég megoldottam volna TNTvel, de mivel az a szerveren nem elérhető, a régebben elérhető Admin WE nagy segítség lett volna nekem. Ez egy elfeledett téma, sokan már nem is tudják, hogy volt régen WE lehetőség, de ahogy polter is megírta (#1847) régebben, szerintem is jó lenne visszahozni a játékosoknak WorldEditezést. Többen kezdenének bele nagyobb projektekbe, ez akár még a szerver gazdaságát is felpörgethetné. Kerülhetne ugyanúgy pénzbe vagy akármi másba, de meg lehetne szabni, hogy csak x block felett van WEzés a játékosoknak, és azzal ki lenne küszöbölve az is, hogy valaki 200 block miatt Admint hív. A másik, hogy reset óta nincs RG levédés játékosoknak, ez ugyanúgy visszafogja az építést, kevesen, de akik elhivatottak ilyen téren azoknak kevés lehet az a 316x316-os (+egy kis hamaradék) terület, ugyanúgy, ahogy a régebbi levédés pluginnál is volt, akiknek kevés volt a terület. Szerintem attól sem kell tartani, hogy telítődik a szabad, 60000x60000 blockon még a régebbi nagy RG levédések is kényelmesen elférnének. Az RG levédés is lehetne ugyanúgy pénzes, mint régen, akár ugyanazzal a számítási móddal ahogy régen volt (ha jól emlékszem gyök alatt(hosszúság x szélesség)×1000), akár másikkal. Szerintem ennek a 2 dolognak a visszahozatala nagyot dobna a projektek méretén, és ez együtt egy aktívabb közösséget is hozna magával.

-Hunter

**Comment by MrZero1** [comment]
Folyamatosan szó van róla, nem tudok most semmit mondani egyelőre. Addig nyitva a jelentés.

**Comment by SurvivorTheReal** [comment]
Eléggé jól jönne ennél egy kis WE, ez csak a fele, ennyit tölt be.Falaztam egy ideig, de 2 hét múlva talán végeznék ha napi 5-6 órát csinálnám, csak ezt.
![2019-04-19_18 49 29](https://user-images.githubusercontent.com/39741913/56434308-58910a80-62d4-11e9-8ef5-f2561417ac5e.png)

**Comment by Wexthory** [comment]
A we nem feltétlen kell, mert pénzért más játékosok is kiássák neked és az még a gazdaságra is jobban hatna, amennyiben nem csak kiszedni hanem le is raknának úgy már más a helyzet, meg talán csökkennne a játékban lévő pénz mennyisége. A wg viszont farmok szempontjából hasznos lenne mob spawnolás letiltásával (ha lehet a jelenlegi védésnél is akkor elnézést), gombás biomra alakítás lehet megoldaná ezt a dolgot, de nem vagyok benne biztos, hogy ez elérhető egyáltalán, ha mégis akkor is csak oldnak.

**Comment by andris155** [comment]
Lehet jelenleg is.
Pl.:
/setclaimflag NoMobSpawnsType ocelot
/setclaimflag NoMobSpawnsType creeper;zombie;wandering_trader;cat
vagy minden monster tiltása:
/setclaimflag NoMonsterSpawns

**Comment by andris155** [comment]
vagy minden mob tiltása:
/setclaimflag NoMobSpawns

**Comment by MrZero1** [comment]
Továbbra sem tartom jónak, hogy az amúgyis 'remek' WE a játékosok számára legyen elérhető, RG védés helyett pedig ott a 200k levédés, amit igény szerint tudunk bővíteni. Ráadásul arra is kell pénzt költeni, ha valaki extra levédésblokkot akar venni hozzá. Flag-ekre meg itt is van lehetőség, plusz farmoknál amúgy sem WE-ztünk, védtünk le.  Lezártnak tekintem ezt a jelentést, persze javaslatokat továbbra is elfogadunk.
