### ISSUE TITLE
[Survival] érc kreatív módban

### ISSUE THREAD

**Issue by Huntermaster0** [andris155/TheOld-Crafters#2830]
Tudtommal azért van tiltva kreatívban az érc letétel, mert régebben volt olyan bug, hogy egy idő után a kreatívban lerakott blokkok survivalban felszedhetőek voltak. Viszont én már hónapok óta nem tapasztaltam ilyet. Ez a téma ma a chaten jött elő, valaki kérdezte, hogy milyen szinten limitált az Old gmc-je, és akkor került elő, hogy miért is van még tiltva? (mert ugye az érctömbök lerakhatóak)

**Comment by andris155** [comment]
kész
