### ISSUE TITLE
Online térkép [Survival]

### ISSUE THREAD

**Issue by Huntermaster0** [andris155/TheOld-Crafters#2831]
Rengeteg nagyobb szervernek van online térképe (pl. külföldön), nem tudom mennyire lenne megoldható ez, de szerintem sokan örülnének neki, ha megnézhetnék a térképet a neten.

**Comment by andris155** [comment]
Túl sok adatforgalmat igényel és legalább több TB tárhely is kellene a world térképéhez, aminek jelenleg nincs.
