### ISSUE TITLE
Discord összekapcsolása a szerverekkel

### ISSUE THREAD

**Issue by Huntermaster0** [andris155/TheOld-Crafters#2832]
Rátaláltam erre a pluginra (https://www.spigotmc.org/resources/discordmc.17067/), aminek a lényege az lenne, hogy egy külön Discord szobából lehetne írni a szerver chatjére, és elvileg visszafele is megy, tehát mindkét irányba lehet kommunikálni. Ez praktikus lenne, ha mondjuk valaki meg akarja mondani az egyik játékosnak akivel együtt játszik, hogy ezt vagy azt majd ő megcsinálja, azt hagyja stb., vagy csak simán egy egyszerűbb chatezést tenne lehetővé azok számára, akik néha DCn beszélnek a szerveren offline játékosokkal. Így csak a chatre kellene írniuk, és már látná is a másik.
(+A staffoknak is hasznos lehet ez, ha épp DCn vannak, de a szerveren nem, láthatják a chatet offline is).
Talán feldobná a Discordot használó játékosok számát is, biztos lenne, aki szeretné ezt a funkciót.

**Comment by andris155** [comment]
Van erre sokkal jobb plugin is, de nem tudom hogy mennyire használnák ezt az emberek.

**Comment by MrZero1** [comment]
+1

**Comment by andris155** [comment]
Megnézem majd a lehetőségeket a másik plugin-al.

**Comment by poma123** [comment]
chatcontrol tudja cenzurazni amit dcrol irnak a szerverre?

**Comment by andris155** [comment]
Mivel ahhoz kapcsolható lehetséges, hogy igen. Utána kell majd nézem meg tesztelni esetleg.

**Comment by poma123** [comment]
https://www.spigotmc.org/resources/discordsrv.18494/
Szerintem ez előnyösebb lenne, a fejlesztő elérhető, kicsit több a letöltés és 1.13-at is támogatja.

**Comment by poma123** [comment]
Biztonsági okokból sajnos nem valósítható meg egyelőre.
