### ISSUE TITLE
Savsziget - Bolt ötlet (víz részleg)

### ISSUE THREAD

**Issue by Trymer1** [andris155/TheOld-Crafters#2833]
Ha már Vég és Pokol részleg is van, lehetne Víz részleg is, pl a prizmarinblockoknak, mehetne oda a prizmarinszilánk, prizmarinkristály..

**Comment by andris155** [comment]
@poma123

**Comment by poma123** [comment]
ha lesz idom ranezek

**Comment by poma123** [comment]
Sweetre várok, hogy küldjön árakat.

**Comment by andris155** [comment]
Azóta sem küldte el?

**Comment by poma123** [comment]
hat a helyzet hogy nekem nem lesz idom megcsinalni, akar elkuldi akar nem szoval legyen akkor kinyitva egy uj jelentes miutan meg lesz beszelve hogy ki csinalja meg ha lesz-e egyaltalan

**Comment by andris155** [comment]
Én megcsinálom, csak az árakat várom hozzá.

**Comment by poma123** [comment]
a vizeset megkaptam még régebben csak időm nem volt rá, de akkor itt van. nem tudom aktuális-e még az árai, júniusi termés.
[viz.xlsx](https://github.com/andris155/TheOld-Crafters/files/3638425/viz.xlsx)

**Comment by andris155** [comment]
De ezek az árok már nem igazán jók. Én pedig már jó rég várok az újakra. De ha nincsenek akkor nem tudok mit kezdeni ezzel.

**Comment by poma123** [comment]
ezert zartam be en is :DDD
