### ISSUE TITLE
survival Mobaréna (falu) glitch/bug spot

### ISSUE THREAD

**Issue by Tarifnya** [andris155/TheOld-Crafters#2834]
doktor kaszt al magasugrás potit dobsz magadra és a hát hátulján fell lehet menni majd a  kissebb hátra lehet ugrani onnan fel lehet ugrani a ""vizesés"" tetejére ahol nem tud megtalálni semilyen mob

**Comment by MrZero1** [comment]
Javítva. Köszi!
