### ISSUE TITLE
Kreatív védelem hiba (fáklya, vöröskő fáklya)

### ISSUE THREAD

**Issue by Huntermaster0** [andris155/TheOld-Crafters#2835]

**Comment by Huntermaster0** [comment]
Videó a hibáról:
https://youtu.be/5xwsbmrna3Y

**Comment by andris155** [comment]
Legközelebb kérlek az videózza a hibát, aki éppen reprodukálja.

**Comment by Huntermaster0** [comment]
Felvenném én, csak nem tudom.

**Comment by andris155** [comment]
https://github.com/andris155/TheOld-Crafters/issues/2890

**Comment by andris155** [comment]
330 OCD
