### ISSUE TITLE
Savsziget - mcMMO növénytan hiba

### ISSUE THREAD

**Issue by Icecroft** [andris155/TheOld-Crafters#2838]
Egy ideje az mcmmo növénytan duplaitem skillje nem működik. A szintem 181, de mindenből csak 1-et dob a 2 helyett. Próbáltam cukornáddal, sárgarépával, burgonyával, céklával. Minden esetben csak 1 itemet kapok aratáskor.

**Comment by andris155** [comment]
Kérlek holnap teszteld le újra.

**Comment by Icecroft** [comment]
Ma reggel tettem egy próbát újra, A cukornád szimplán dobott még, de a többi növény (tök, dinnye, sárgarépa, cékla) rendben volt. A cukornád vajon miért kivétel?

**Comment by andris155** [comment]
Nem tudom sajnos mitől lehet.
