### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Hoyhi** [andris155/TheOld-Crafters#284]
A mai nap csináltam 2 kaput  és egyszerre nyitja ki az egyiket és csukjabe a másikat a 2 tábla pedig nem is kapcsolodnak egymáshoz meg semmi , Akos is probálta megcsinálni és mondta hogy irjak ide neked , Elölre is köszönöm ha elolvasod és megnézed ezt fent a szerveren nálam

**Comment by andris155** [comment]
megnézem majd

**Comment by andris155** [comment]
megoldva
