### ISSUE TITLE
spawn bug

### ISSUE THREAD

**Issue by asdragon** [andris155/TheOld-Crafters#2841]
![spawnbug](https://user-images.githubusercontent.com/36716076/56460967-4930c080-63ab-11e9-93e0-a43c7f8149b3.jpg)
meghaltam az endcity-be és folyamatosan a semmibe spawnol ahol újra meghalok a folyamatos zuhanás miadt pegig tpzni se tudok

**Comment by andris155** [comment]
A /home bed-hez tp-z. Gondolom ott nincs semmi (?)

**Comment by andris155** [comment]
javítva
