### ISSUE TITLE
Eltűnő hopperes csillék

### ISSUE THREAD

**Issue by Huntermaster0** [andris155/TheOld-Crafters#2842]
Ma délután BigFlori kiírta a chatre, hogy eltűnt pár hopperes csilléje. Írtam neki, hogy szerintem az lehetetlen, mivel nálam már hónapok óta tökéletesen fut mindegyik. Közben futkároztam a telkemen, majd rá pár percre észrevettem, hogy a sütőmnél 2 hopper lebeg+a szén, ami a csillékben volt. Fogalmam sincs hogy történt, a telkemhez senki sincs hozzáadva, én meg nem ütöttem ki egyiket sem.

**Comment by SurvivorTheReal** [comment]
Azthiszem nekem is rá kell néznem a sütőre akkor xd

**Comment by andris155** [comment]
Ez elvileg lehetetlen. Nem lehet, hogy nem védett a telken?

**Comment by Huntermaster0** [comment]
Megnézte EHzy, lőtt rá, ütötte karddal, ugyanúgy a helyén maradt a csille (annyi változással, hogy kigyulladt). A telkemre amúgy sem jár senki, mivel nem /p auto -val választottam, és amikor észrevettem 2 napja, hogy a csille ninca meg, az itemek úgy voltak szétszórva, mintha csak egy chestet ütne szét az ember.

**Comment by andris155** [comment]
Egyelőre ezt lezárom, ha megint előfordul mindenképpen írjatok és megpróbálok utána járni. Bár nem egyszerű egy ilyen hibának ami ennyire random.
