### ISSUE TITLE
SavSziget Blocklerakási hiba

### ISSUE THREAD

**Issue by Trymer1** [andris155/TheOld-Crafters#2843]
Amikor gyorsan pakoljuk egymás után a blockokat sokszor nem engedi lerakni azt.

**Comment by MrZero1** [comment]
Be is jelez rá.
![kép](https://user-images.githubusercontent.com/29709854/56532123-81740280-6555-11e9-875c-8449cbf16bee.png)

Valamint Survivalon is többen panaszkodnak erre, hogy ahogy lerakják a blokkot (gyorsabban), eltűnik.

**Comment by andris155** [comment]
Most jó a Savszigeten?

**Comment by Trymer1** [comment]
Ideiglenesen nem vagyok elérhető szombatig, szólok ismerősnek nézze meg.

2019. ápr. 23., K 20:37 dátummal András Marczinkó <notifications@github.com>
ezt írta:

**Comment by andris155** [comment]
Esetleg más tudja tesztelni?

**Comment by Trymer1** [comment]
Működik.

**Comment by andris155** [comment]
330 OCD

**Comment by MrZero1** [comment]
Azt mondják, ez a hiba még most is él.

**Comment by MrZero1** [comment]
@andris155

**Comment by MrZero1** [comment]
Viszont nem jelez már be.
