### ISSUE TITLE
Gm1-es gyanús eltűnés

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#2845]
BigFlori nevű játékosnak előjött ez a hiba,(gm1-ben kilép, majd vissza, és eltűnik a gm0-s cucc)  páran leteszteltük, nem tapasztaltuk. De a szemem előtt megmutatta, és tényleg így volt neki. Mi befolyásolhatja a cucceltűnést? Ő eredetis mi meg nem? vagy nem értem.

**Comment by andris155** [comment]
Ő írjon. Ne pedig más!
