### ISSUE TITLE
Nem működő /p parancs

### ISSUE THREAD

**Issue by nicolettie** [andris155/TheOld-Crafters#2846]
a ./p h parancs nem működik, csak a ./plotme home

**Comment by nicolettie** [comment]
![2019-04-25_15 49 02](https://user-images.githubusercontent.com/48986609/56740680-b066c000-6771-11e9-91d1-f6296e37436a.png)

**Comment by andris155** [comment]
Holnap betölt a javítás.

**Comment by andris155** [comment]
javítva
