### ISSUE TITLE
Kreatív block?!

### ISSUE THREAD

**Issue by nicolettie** [andris155/TheOld-Crafters#2848]
A kreatív menüben van egy "megkövült tölgyfa lap" nevű item, ami egy az egyben sima tölgyfa lap. Direkt? Van valami funkciója?
![2019-04-25_20 20 44](https://user-images.githubusercontent.com/48986609/56758770-b7082e00-6797-11e9-83a0-4e3005f72e6c.png)

**Comment by skrisz0101** [comment]
Nem ég el +csákival lehet gyorsan kiütni a balta helyett
