### ISSUE TITLE
Partycset. Más partyjába írtam??!!

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#2849]
Képen látható, hogy nasiék partyjába írtam, mikor én Ehzy partyjában vagyok.  Küldhetek akár logot is hogy Dogeval, ehzyval meg huntermasterrel beszélgettem mikor észrevettem hogy nem írt ki egy üzenetet. gondoltam elbugolt vagy nemtom. Hát, Nasiék partyjába került az üzenetem. Tippem sincs hogyan.
(Lenoras Nasiék partyjában van, ő csinálta a képet)

https://prnt.sc/ngw81x

**Comment by skrisz0101** [comment]
Hogy igazoljam?

**Comment by poma123** [comment]
![image](https://user-images.githubusercontent.com/25465545/56846337-6810e480-68ce-11e9-83e9-ff8b88a70e29.png)
Érdekes.

**Comment by andris155** [comment]
Frissítettem az mcMMO-t. Ha megint nem lenne jó, akkor kérlek írj.
