### ISSUE TITLE
Banknotes ötlet

### ISSUE THREAD

**Issue by nicolettie** [andris155/TheOld-Crafters#2850]
Az ötlet háttere, hogy nyitunk egy boltot hárman, a bevételt három fele kellene így osztani, úgy az igazságos tekintve hogy felépítettük, feltöltöttük. És sokat gondolkodtam rajta, hogy ezt milyen módon lehetne számon tartani, hogy melyik nap mennyi volt a bevétel, anélkül, hogy mindig számon kellene tartanom a bolt előtti egyenlegem.

Arra gondoltam, hogy a Banknotes elég hasznos lehetne, akár egy kis "role play" érzést is nyújthatna, mivel elég sok játékos vállal másik játékostól munkát (pl, aratás, anyag beszerzés mint favágás, stb.) és Banknote egy afféle új fizetési mód lenne például a role play-re nézve  vagy akár automatikus eventeknél is lehetne találni banknote-ot a ládákban. Szerintem hasznos is lenne meg egy kicsit fun is, remélem bekerül :) 
![maxresdefault](https://user-images.githubusercontent.com/48986609/56817284-95fe1680-6845-11e9-9f93-7978b2b818b2.jpg)

**Comment by MrZero1** [comment]
Mire jó? Azonkívül, hogy új pénzszerzési lehetőség? Hogyan működik ez?

**Comment by Huntermaster0** [comment]
https://www.spigotmc.org/resources/banknotes.3200/
Szerintem erről a pluginról van a kép is, YT bemutató videónál is használták ugyanezt.
A plugin 2015-ös, nagyjából annyi, hogy ki lehet szedni a pénzed papír formába, aztán később vissza lehet váltani számlapénzre (ami jelenleg a szerveren van). Ha jól értem ilyen a működése.

**Comment by MrZero1** [comment]
Van 1.13-ra is?

**Comment by andris155** [comment]
Nincs. Ez egy régi plugin.

**Comment by Huntermaster0** [comment]
Csak 1.12-est találtam még, 1.13as Banknotes plugint nem.

**Comment by MrZero1** [comment]
Nem tudom, mennyire lenne jó amúgyis így eltárolni a pénzt, ha jön egy duplikálós hiba, valaki kihasználja, máris megvan a baj :(

**Comment by poma123** [comment]
ilyen volt amúgy savon anno, és a duplikálásba bukott bele.
