### ISSUE TITLE
Automatikus event díjazás.

### ISSUE THREAD

**Issue by Bannoltboci** [andris155/TheOld-Crafters#2852]
Rosszul adja a nyereményeket az automatikus event 

![event](https://user-images.githubusercontent.com/43493917/56848634-a2d54580-68eb-11e9-959f-b721dd0b8fe5.PNG)

**Comment by MrZero1** [comment]
@poma123

**Comment by poma123** [comment]
én se nézem mindig a githubot légyszi majd máskor írjatok fb-n is
