### ISSUE TITLE
FAWE hiba

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#2854]
Survival. Kijelöltem egy kisebb területet, törölni akartam, törölte is, kivéve az egyik falat. Aztán kiakartam ütni a falat kézzel, így ütötte ki a blokkokat.
![2019-04-27_18 51 24](https://user-images.githubusercontent.com/29709854/56854830-3c791300-693d-11e9-80e4-af1df267106c.png)
![2019-04-27_18 51 26](https://user-images.githubusercontent.com/29709854/56854831-3c791300-693d-11e9-8ca2-ed3772b05948.png)

**Comment by andris155** [comment]
Szerintem ez már nem volt ott, csak nem frissült a kliens-edben.
