### ISSUE TITLE
Craftbook hibák

### ISSUE THREAD

**Issue by andris155** [andris155/TheOld-Crafters#2859]

**Comment by MrZero1** [comment]
A Bridge sem megy, azt írja, ebből a blokkból nem lehet hidat csinálni. De tesztelgetjük még.

**Comment by andris155** [comment]
Nem is fog egy jó ideig szerintem. Nem kompatibilis az FAWE vele teljesen. :/

**Comment by andris155** [comment]
https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues/51

**Comment by andris155** [comment]
javítva
