### ISSUE TITLE
Bolti eladás

### ISSUE THREAD

**Issue by Huntermaster0** [andris155/TheOld-Crafters#2860]
A boltban más összeget ad az eladás tábla ha shift klickelünk rá, mint amikor nem. Ha shift clickelünk akkor a kiírt eladási ártól lefele vagy felfele adja. 
Pl. szén shift click 760.32$
     szén shift click nélkül 760$

**Comment by andris155** [comment]
Most sem jó?

**Comment by nicolettie** [comment]
Még most sem.
![2019-04-29_10 01 04](https://user-images.githubusercontent.com/48986609/56883024-bc020180-6a65-11e9-8fe9-6d59d0cd9d8e.png)

**Comment by andris155** [comment]
javítva

**Comment by andris155** [comment]
330 OCD
