### ISSUE TITLE
Vote parancs hiba

### ISSUE THREAD

**Issue by nicolettie** [andris155/TheOld-Crafters#2861]
A "./vote" nem működik. "Ismeretlen parancs"

**Comment by andris155** [comment]
Nagyszerű, hogy az auto frissítés kinyírja néha. :D

**Comment by MrZero1** [comment]
Most sem jó nekik. Elvileg nincs rá jogosultságuk.

**Comment by nicolettie** [comment]
![2019-04-29_11 57 12](https://user-images.githubusercontent.com/48986609/56889223-1e62fe00-6a76-11e9-95de-3a7282e8e5b4.png)

**Comment by nicolettie** [comment]
működik! :)
