### ISSUE TITLE
Ocelot tojás/pet telken

### ISSUE THREAD

**Issue by mestertrefa** [andris155/TheOld-Crafters#2865]
Ha leteszek egy ocelot tojást egy telekre, akkor a tojás elveszlődik, de nem rakja le az ocelotot a telekre, és ha azt próbálom, hogy egy ocelot petet engedek el a telken, akkor pedig az elengedett pet csak eltűnik. - trefamester

**Comment by andris155** [comment]
Le van tiltva az ocelot abban a világban, mivel a dzsungel telkeken túl sok idéződik le. Hasonló a csontváz ló is, ami pedig azért van, mert a csontváz nélkül idéződik, mivel a csontváz ló a játék alapján állat, a csontváz pedig szörny.
