### ISSUE TITLE
Tölcséres Csille a levédett láda alatt

### ISSUE THREAD

**Issue by mestertrefa** [andris155/TheOld-Crafters#2866]
Ha teszek egy tölcséres csillét egy másik játékos által levédett láda alá, akkor az kiszappantja onnan az itemeket. Ezt nagyon sokan használhatják rablásra, esetleg úgy, hogy egy játékos hozzáadja a másikat, a terület levédéshez, de a ládákhoz nem. Na de ő meg tudja oldani ezt egy tölcséres csillével.

**Comment by andris155** [comment]
Védje le a területet. Optimalizáció miatt van ez így.
