### ISSUE TITLE
./m bug

### ISSUE THREAD

**Issue by nicolettie** [andris155/TheOld-Crafters#2867]
ha írok ./m-be például Zeronak, nem jelzi a chat, hogy elküldtem.. 
(a képen már "elvileg" elküldtem az üzenetet amit láttok beírva, de nem jelzi a chat"
![elküldve](https://user-images.githubusercontent.com/48986609/56962301-80933000-6b56-11e9-8c8a-16faf7e44dc3.png)

**Comment by MrZero1** [comment]
![kép](https://user-images.githubusercontent.com/29709854/56962380-b7694600-6b56-11e9-8000-03955d8c997d.png)

Én csak ennyit látok. Maga az üzenet nem jött meg

**Comment by MrZero1** [comment]
![kép](https://user-images.githubusercontent.com/29709854/56962432-d36ce780-6b56-11e9-90ed-cb17a420af0a.png)

:cactus:

**Comment by andris155** [comment]
Ez most sem jó?

**Comment by Huntermaster0** [comment]
Már jó, elküldi az üzenetet

**Comment by andris155** [comment]
Akkor szerintem a szerverkezelőn való kiegészítő frissítés miatt volt. Sajnos máshogy azt nem igazán lehetett megoldani.
