### ISSUE TITLE
Munka

### ISSUE THREAD

**Issue by sypersyper** [andris155/TheOld-Crafters#287]
Az lenne a problemam, hogy mar ketszer eltunt a munam teljesen mind a ketto es zerorol kellet kezdjem. Mind a ketszer banyasz es fegyverkovacs voltan. Kb 40 es banyasz es 30 as fegyverkovacs eloszor masodszor 35 es 20 korul! S most megint ujra kellet kezdjem!

**Comment by andris155** [comment]
megoldva
