### ISSUE TITLE
Automatikus event hiba

### ISSUE THREAD

**Issue by asdragon** [andris155/TheOld-Crafters#2870]
nem tudnak sebezni a mobok a pokol labirintusban

![eventbugg](https://user-images.githubusercontent.com/36716076/57020122-b3a5f400-6c28-11e9-9527-6ea3603206d8.jpg)

**Comment by MrZero1** [comment]
Ez nem napievent? Ha az, ott direkt nem sebeznek.

**Comment by poma123** [comment]
mivel nincs ilyen auto event, akkor ez napi event.
és mivel zero írta hogy direkt, ezért lezárom
