### ISSUE TITLE
PocketGames fordítás - 5080 OCD

### ISSUE THREAD

**Issue by andris155** [andris155/TheOld-Crafters#2871]
Csak a name és lore részeket kell lefordítani. A szövegek szélessége kb. ugyanakkora maradjon ugyan azokkal a formázásokkal és színkódokkal. A lore-nál, ha hosszabb a szöveg inkább legyen több soros, ne pedig szélesebb a szöveg.
https://github.com/andris155/TheOld-Crafters/tree/master/Ford%C3%ADt%C3%A1sok/PocketGames/GameConfigurations

**Comment by nicolettie** [comment]
ha még nem kezdte el senki akkor bevállalom :) csak feleslegesen ne dolgozzunk rajta egyszerre öten szinkronban :)

**Comment by andris155** [comment]
Tudtommal még senki sem kezdte el.

**Comment by nicolettie** [comment]
Akkor én most elkezdem :)

**Comment by MrZero1** [comment]
@Huntermaster0 nevét hallottam, de majd kijavít, ha tévedek. Matcheljétek le egymással :D :crossed_swords:

**Comment by nicolettie** [comment]
Hát én már a felét megcsináltam, akkor is elküldöm amikor kész leszek, sokat dolgoztam vele :)

**Comment by Huntermaster0** [comment]
Én végül nem kezdtem bele, mivel niki írta, hogy ő elkezdte. Ketten felesleges megcsinálni :D

**Comment by nicolettie** [comment]
Elküldtem a theoldcrafters@gmail.com címre tömörítve, meg írtam hozzá pár szót is az e-mailben. :) Remélem jó lett. ^^

**Comment by andris155** [comment]
Holnap átnézem. Köszönjük!

**Comment by andris155** [comment]
Kérlek nézzétek át, hogy minden jó-e benne. Én átnéztem és ami olyan volt azt javítottam.

**Comment by MrZero1** [comment]
![kép](https://user-images.githubusercontent.com/29709854/57134222-b8dc7d80-6da5-11e9-8f6c-c9d194e7a43b.png)

A játékok leírását nem lehet lefordítani?

**Comment by andris155** [comment]
Nem raktam be a fordításokat, még nem néztétek át. :D

**Comment by andris155** [comment]
Majd az a következő lépés, hogy a játékban jó-e.

**Comment by MrZero1** [comment]
![kép](https://user-images.githubusercontent.com/29709854/57134566-d4945380-6da6-11e9-978b-d05f4f6d79f9.png)
De van ami magyar. Vagy ez eddig is az volt?

**Comment by andris155** [comment]
Az a fő fordítása. Az magyar volt. De fogalmam sincs ki fordította le. :D

**Comment by MrZero1** [comment]
Ja, akkor nem szóltam :laughing:

**Comment by nicolettie** [comment]
Hát mondjuk aki ezt fordította nem tudom ki volt, de a "PocketGames" kifejezést én személy szerint nem fordítanám le például. Kicsit hasonló mint a FlappyBirds, ugye annak ez a neve, magyarra lefordítva butaság lenne (már ha le lehet fordítani értelmesen, bár kétlem), én magát az angol nevet mint "PocketGames" meghagynám egyfajta brand szimbólumként. De ez staffoknak kell átnézni, meg játékosoknak akik figyelik a githubot, hogy mit gondolnak :D Sok helyen tükörfordítást használtam és törekedtem a rövid lényegre törő fordításra, itt viszont aki fordította például a Bal meg Jobb klikkes résznél szépen kerek mondatokba fordított, én viszont csak szimplán írtam át. Hát ezt főleg a staffok illetve a tulaj döntse el, hogy rövid instrukciókat szeretnétek látni, vagy hosszabb mondatokat. Bár ilyenkor praktikusabbak a rövidebb fordítások. Csak hamar átfutja a játékos, aztán már játszhat is, az átolvasás az ne vegyen el tőle sok időt, rövid de tömör infókat lásson véleményem szerint. Ha valami elég gáz megfogalmazást találtok, akkor azt kell javítani szerintem. Meg ha valahol nincs lefordítva akkor szóljatok. Bár én átnéztem, de 6 órán keresztül csináltam egyhuzamban, és már késő volt, tehát biztos van amit nem vettem észre. :)

**Comment by MrZero1** [comment]
Mikor kerül be :question: :thinking:

**Comment by andris155** [comment]
Bekerült.
