### ISSUE TITLE
Kreatív védelem hiba bolt tábla

### ISSUE THREAD

**Issue by nicolettie** [andris155/TheOld-Crafters#2874]
Kreatívban a falra raksz egy táblát, megírod, mintha saját bolt lenne, mivel nem érzékel ládát a tábla alatt (ezt írja is: [Bolt] Nem található a láda a tábla alatt!!) ezért ledobja magát a tábla a falról, viszont kreatívban nem tudom felszedni, de gm 0-ban igen.

**Comment by SurvivorTheReal** [comment]
Eddig se lehetett gm 0 ban felszedni semmit, viszont az hogy kreába rakod le és ledobja, az már hiba.

**Comment by andris155** [comment]
Videót tudsz erről készíteni? Hogy elírod a bolt táblát kreatívban és kidobja a táblát.

**Comment by nicolettie** [comment]
elküldtem e-mailben!

**Comment by andris155** [comment]
https://github.com/andris155/TheOld-Crafters/issues/2890

**Comment by andris155** [comment]
330 OCD
