### ISSUE TITLE
Bolt ládák

### ISSUE THREAD

**Issue by SurvivorTheReal** [andris155/TheOld-Crafters#2875]
Eddig nem sokan nyitottak boltot közösen, talán sk és salty egyedül. Most pedig én és nici és tréfa. Az lenne az ötlet, hogy parancsal hozzá lehetne adni játékost a bolt ládákhoz. Ez azért lenne jó, mivel nem csak az látna bele a ládákba akié a bolt, hanem az is akiben megbízik az illető annyira, hogy adna neki ilyen engedélyt. Jó lenne abból a szempontból is, ha a tulaj nincs fent, de valami kifogy akkor újra lehet tölteni. Na igen, erre van az hogy pipeval töltünk, viszont nem lehet mindent pipeval tölteni, és pipeval nem tudom lecsekkolni mennyi van az adott ládában. Esetleg kell-e tölteni, vagy hálisten még sok van nem kell elmenni szedni stb. Elég kockázatos fejlesztés, mert akik nem óvatosak azok rosszul jöhetnek ki ebből, esetenként nagyon toxic helyzetek is kialakulhatnak, szidkozódás és az arzenál többi tagja. Ezek a negatívum,ok viszont sajnos elég nagy negatívumok.

**Comment by andris155** [comment]
Kérlek ide írd meg az ötletet angol nyelven, ha még nem írta más: https://github.com/ChestShop-authors/ChestShop-3/issues
