### ISSUE TITLE
Akármi2, avagy tele a chat ezzel 

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#2879]
![kép](https://user-images.githubusercontent.com/29709854/57134108-4f5c6f00-6da5-11e9-960d-8236ffb42ec1.png)

Tudom, hogy nem olyan eget rengető hiba, de telespameli a képernyőt. A játékos csak egy őrszem farmot épített, majd öli a mobokat. :disappointed:

**Comment by andris155** [comment]
https://github.com/andris155/TheOld-Crafters/issues/2891
