### ISSUE TITLE
flyhackelek folyamatosan

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#2880]
feljöttem a szerverre ,,kicsit" sok pinggel. Ugrálok, ugrálok, random kirak flyért. Később már 1 ugrás is elég volt hogy kidobjon, ezzel nem lehet csinálni valamit? Mer voltak már gondok ezzel.
Elytra volt rajtam.
végülis mind1, elytra nélkül is ledob

**Comment by MrZero1** [comment]
Konzolban is jelzi, pedig elit rangosként nincs is neki repülésre joga.

![kép](https://user-images.githubusercontent.com/29709854/57143600-817aca80-6dbf-11e9-8fa2-9399303d0304.png)

**Comment by andris155** [comment]
Sok ping-el mindent cheat-nek fog nézni.

**Comment by skrisz0101** [comment]
de eddig nem volt ilyen, jöhettem akár 2500 pinggel, akkor se dobott ki flyért

**Comment by skrisz0101** [comment]
főleg nem egy random ugrásért

**Comment by andris155** [comment]
https://github.com/andris155/TheOld-Crafters/issues/2891
