### ISSUE TITLE
chunk-betöltés

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#2883]
szerintem nem csak engem zavar / tűnt fel. Hiába van 10, 12, 16 chunkon a beállításomon.
kettőt látok minden irányba és kész. (az még a semmi kategória)
Nem lehetne ezzel valamit kezdeni?

**Comment by MrDinamit88** [comment]
kitudja

**Comment by nicolettie** [comment]
sk, napok óta gondolkodtam ezen, hogy megemlítsem-e staffnak :D

**Comment by andris155** [comment]
Egy jobb szervergép kellene ahhoz, hogy sok játékossal is sok chunk-t lehessen látni. Sajnos erre egyelőre nincs lehetőség.

**Comment by skrisz0101** [comment]
És van rá esély hogy lesz?

**Comment by andris155** [comment]
Igen, de egyébként ha nagy ping-ed akkor se tölt be több chunk-ot.
