### ISSUE TITLE
Petnév

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#2884]
![kép](https://user-images.githubusercontent.com/29709854/57181318-51e8c280-6e92-11e9-9c88-ec7742a9f219.png)

Az unicode miatt nem tudja elengedni (mondtam neki, változtassa meg, úgy sikerülni fog), kérdés, hogyan tudott egyáltalán ilyen nevet adni neki.

![kép](https://user-images.githubusercontent.com/29709854/57181325-7349ae80-6e92-11e9-87d5-f2dd40a60ada.png)

**Comment by MrZero1** [comment]
(Ma lépett be elsőnek)

**Comment by andris155** [comment]
Nem tudom mitől lehetett, de ha átnevezi tudja törölni. Ha ismét előfordul ilyen mindenképpen nyissatok egy új hibajelentést.
