### ISSUE TITLE
End(/Nether) + ágy = tűz

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#2885]
#2355 

Ugyanaz. Robban az ágy mindkét világban :fire: :bed:

**Comment by MrZero1** [comment]
+ Más levédésben is robban

**Comment by andris155** [comment]
Csak a tulaj és az admin tudja lerakni. Ők csak nem robbantgatnak nem?

**Comment by MrZero1** [comment]
Nem tudtam, hogy csak mi tudjuk lerakni. Nyilván nem. :+1:
