### ISSUE TITLE
afk

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#2888]
![2019-05-05_14 26 50](https://user-images.githubusercontent.com/29951969/57194235-dac03680-6f44-11e9-8c97-6bb527b844e3.png)

Képek látni: Bannoltbocinak írtam üzenetet mikor afkolt
1.: Nincs lefordítva az az afkos üzenet.
2.: sokszor ki se írja hogy afk.

**Comment by andris155** [comment]
lefordítottam

**Comment by andris155** [comment]
330 OCD
