### ISSUE TITLE
Blokkba-bugolás

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#2889]
Ez is már többször előfordult. Chatelek nagyban egyhelyben állva, egyszer csak belebugolok a blokkba amin állok. Ki lehet tpzni, de rohadt zavaró hogy az állástól is  bel het bugolni. A napon fénypontja az volt hogy 20 blokkot estem le kövön át a blokkba-bugolás miatt. Álltam, és Leestem 20blokk vastag kövön Az alattam lévő helyiségbe. Ez ellen is kéne valami mert rohadt zavaró,

**Comment by andris155** [comment]
Még mindig nem tudunk mit kezdeni azzal, ha nagy ping-ed.

**Comment by skrisz0101** [comment]
et nem nagy pinggel volt... 
szó szerint lebugoltam 30 blokkot és utána vígan szaladgáltam az alattam lévő barlangban vagy miben

**Comment by skrisz0101** [comment]
semmi köze se volt a pinghez

**Comment by skrisz0101** [comment]
@andris155
