### ISSUE TITLE
Plugin Lista SkyPvP-re

### ISSUE THREAD

**Issue by Kyren562** [andris155/TheOld-Crafters#289]
- Pluginok -
- Lottery
+ Aukció ami a survivalon van
+ Szövetség plugin, én egy átalakított Clan-os pluginban gondolkoztam
+ Duel plugin avagy 1v1 plugin én a DuelMe pluginban gondolkoztam
- Építmények -
/ Új spawn, szigetek -teddmelk február után várható
/ Új börtön most építi IroloX és Zerk

**Comment by andris155** [comment]
- Lottery van
- Aukció - lesésnél felrakják a tárgyat és nem veszik el
- Szövetségre nem tudok plugint
- Duelre se tudok
- Az építmények nem rajtam múlnak.
