### ISSUE TITLE
Delfin és a parancsok

### ISSUE THREAD

**Issue by Bannoltboci** [andris155/TheOld-Crafters#2892]
Delfin lovaglás közben nem lehet parancsokat írni a chatre. Próbáltam a /sethome, /god , /fly , /help , /helpop és egyéb alap parancsokat viszont egyik sem működött

<a href="https://imgur.com/j0l6oRG"><img src="https://i.imgur.com/j0l6oRG.png" title="source: imgur.com" /></a>

**Comment by andris155** [comment]
Sok parancs hibát okozna lovaglás közben ezért vannak tiltva. Szerintem letudsz róla szállni addig még valami parancsot szeretnél használni. :D
