### ISSUE TITLE
Fordítási hibák (Pocketgames)

### ISSUE THREAD

**Issue by Bannoltboci** [andris155/TheOld-Crafters#2893]
1. Dgyémánt -> Gyémánt
2. Párosítást -> Párosítás
3. Értetendő -> Értendő
4. Szerencse játék -> Szerencsejáték
5. egyjátékos játékos -> egyjátékos játék (de nem biztos hogy ez akart lenni)
6. megválzotak -> megváltoztak 
7. főmenű -> főmenü 
<a href="https://imgur.com/d2gKDFD"><img src="https://i.imgur.com/d2gKDFD.png" title="source: imgur.com" /></a>
<a href="https://imgur.com/dbOSYzH"><img src="https://i.imgur.com/dbOSYzH.png" title="source: imgur.com" /></a>
<a href="https://imgur.com/p5RBKTT"><img src="https://i.imgur.com/p5RBKTT.png" title="source: imgur.com" /></a>
<a href="https://imgur.com/hNaS27N"><img src="https://i.imgur.com/hNaS27N.png" title="source: imgur.com" /></a>
<a href="https://imgur.com/FYyaRDl"><img src="https://i.imgur.com/FYyaRDl.png" title="source: imgur.com" /></a>
<a href="https://imgur.com/sndOzPJ"><img src="https://i.imgur.com/sndOzPJ.png" title="source: imgur.com" /></a>
<a href="https://imgur.com/5ZIF2GD"><img src="https://i.imgur.com/5ZIF2GD.png" title="source: imgur.com" /></a>

**Comment by poma123** [comment]
Javítom őket.

**Comment by poma123** [comment]
kész
