### ISSUE TITLE
Savsziget szerveren az Instant Health Beer Nem működik/Nem történik semmi mikor megiszom

### ISSUE THREAD

**Issue by D4nii** [andris155/TheOld-Crafters#2896]
Savsziget szerveren az Instant Health Beer Nem működik/Nem történik semmi mikor megiszom

**Comment by MrZero1** [comment]
A többi jó?

**Comment by D4nii** [comment]
A többit jónak találtam.


MrZero1 <notifications@github.com> ezt írta (időpont: 2019. máj. 8., Sze,
18:34):

**Comment by andris155** [comment]
@poma123

**Comment by poma123** [comment]
Nem én vagyok a plugin fejlesztője :/

**Comment by andris155** [comment]
Ez melyik plugin?

**Comment by poma123** [comment]
Brewery

**Comment by andris155** [comment]
<img width="599" alt="Annotation 2019-07-15 143150" src="https://user-images.githubusercontent.com/8324198/61216335-57258180-a70d-11e9-95e4-c6b2560ec939.png">

**Comment by poma123** [comment]
Azóta se javította a kedves fejlesztő? :D

**Comment by andris155** [comment]
Nem sajnos

**Comment by MrZero1** [comment]
Szerintem lezártnak tekinthetjük ezt is, ha esetleg bármikor javításra kerülne, majd visszakerül a nem működő recept a sörfőzés warpra.
