### ISSUE TITLE
Time telek flag hiba

### ISSUE THREAD

**Issue by nicolettie** [andris155/TheOld-Crafters#2897]
Olyan bugot hoztam nektek, hogy besírtok. 🤣 

A telkemen be lett állítva hogy a ptime mindig nappal legyen. Elmegyek a telkemre, majd a warp vadonra, és használom a random teleportot, lerak egy random helyre VISZONT nem halad az idő, tehát nem megy le a nap, hanem "visszadobálja magát" folyamatosan nappal van, pont mint a telkemen ahonnan teleportáltam.
Ha előtte nem megyek a telkemre (ahol be van állítva az állandóan nappal), akkor nincs ez a bug, rendesen megy le a nap és jön fel a hold.
A videót elküldtem e-mailben.

**Comment by poma123** [comment]
besírok :(

**Comment by andris155** [comment]
Sajnos nem nagyon foglalkozik ezzel a fejlesztő.
