### ISSUE TITLE
Szerver váltó parancsok login-ra és lobby-ra

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#2898]
Ha megoldható, szerintem érdemes lenne berakni login és lobby szerverre a /survival, /savsziget parancsokat. Így pl. a [PickaxeChat](https://play.google.com/store/apps/details?id=com.pickaxe.android&hl=hu) használhatóvá válna, ami talán a staffoknak is segítség, ha muteolni kell valakit, de nincsenek gépnél, stb.

**Comment by andris155** [comment]
Ezzel az újítással a bot-oknak is szabadutat adnék a szerverekre. Szóval ez nem valami jó megoldás.

**Comment by andris155** [comment]
Meg maga az alkalmazás is elég hülyeség így, mert a chunk-okat ugyan úgy betölti ha felmész teljesen feleslegesen.
Ha annyira szeretnél telefonon chat-elni meg játszani akkor ha erősebb telefonod van Boardwalk 2-őt ha össze építed, akkor feltudsz menni vele normálisan játszani. Nem csak chat-elni.
https://github.com/zhuowei/Boardwalk

**Comment by andris155** [comment]
Vagy később szerintem ebbe is bekerülnek az újabb verziók is és itt könnyen lehet modolni is.
https://www.google.hu/amp/s/net-minecraft-kdt.en.aptoide.com/amp

**Comment by UDPSendToFailed** [comment]
Próbáltam a Boardwalk-ot, sajnos csak eredeti mc-vel működik. Igazából a staffok, meg talán néhány játékos miatt gondoltam, hogy lenne értelme, de botokkal így tényleg kihasználható. :/
