### ISSUE TITLE
Saját ültetvény kitaposása

### ISSUE THREAD

**Issue by Huntermaster0** [andris155/TheOld-Crafters#2899]
Azt hiszem ez kb. 2 héttel ezelőtt tiltva lett, viszont most újra kitaposhatóak az elültetett növények. Ez zavaró lehet, főleg, hogy mindenki hozzászokott már, hogy nem lehet letaposni.

**Comment by andris155** [comment]
A játék része. Azért volt tiltva, mert a kreatívos dolgokat is ki lehetett taposni mint kiderült. De már javítva lett.
