### ISSUE TITLE
Duel hiba

### ISSUE THREAD

**Issue by falcon0607** [andris155/TheOld-Crafters#2900]
Egy kis hiba jelentés:

Se a segítők se a moderátorok nem tudnak ráteleportálni (Gm 3 gyorsgombbal sem) olyan emberre aki 1v1-ezik. Ez egy kicsit zavaró mivel nehezebb megfogni a csalókat.

![Képkivágás](https://user-images.githubusercontent.com/40804615/57573211-7f9ab200-7424-11e9-9e7d-81518e151f0f.PNG)

üdv: falcon0607

**Comment by andris155** [comment]
Adtam rá jogot.
