### ISSUE TITLE
ChestShop fordítás frissítése

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#2901]
Pwarpomon aranyat nem csak megvenni, eladni is tudják. Tivyy épp eladni akart, de kiírta ezt: tele a láda stb..stb.  Nincs lefordítva
![2019-05-12_18 34 23](https://user-images.githubusercontent.com/29951969/57586134-9fe47280-74f1-11e9-91a3-9251bdee37cb.png)

**Comment by andris155** [comment]
Frissítettem. Lehet csak holnap tölt be.

**Comment by andris155** [comment]
330 OCD
