### ISSUE TITLE
Kreatív jog esetén néhány játékosnak nem menti el túlélő inventory-t

### ISSUE THREAD

**Issue by andris155** [andris155/TheOld-Crafters#2903]
Célszerű túlélőre váltani kilépés előtt, vagy lerakni a túlélőből a tárgyakat.

**Comment by MrZero1** [comment]
AFK kidobás esetén sem "menti" el.

**Comment by MrDinamit88** [comment]
és spam miatt is kidobott, eltünt mindenem

**Comment by MrZero1** [comment]
Most szintén AFK miatt dobott ki egy Old játékost kreatívban, oda mindene.

**Comment by MrZero1** [comment]
:angry:

**Comment by andris155** [comment]
elvileg javítva
