### ISSUE TITLE
Fly

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#2905]
13.05 21:08:18 [Server] WARN MrZero was kicked for floating too long! 
13.05 21:08:18 [Disconnect] User MrZero has disconnected, reason: Flying is not enabled on this server 
13.05 21:08:18 [Server] INFO [ChatControl] [-] MrZero

Nem tudom, mennyire normális (adminnál), de kidobott fly miatt. :thinking:

**Comment by andris155** [comment]
Ez az alap játék védelme. Nem foglalkozik nagyon jogokkal ahogy látom. :(

**Comment by andris155** [comment]
Ezzel nem tudok mit kezdeni sajnos. Ha jó ping-el többször fordul elő, akkor mindenképpen írj.
