### ISSUE TITLE
Falusi pet után ismétlődő játék crash

### ISSUE THREAD

**Issue by Kismalax** [andris155/TheOld-Crafters#2911]
Az új, 1.14-es vadonban befogtam egy falusit mypetnek, ekkor azonnal crashelt a játék "The game crashed whilst ticking entity" hibával. Azóta, ha fellépek a survival szerverre, amint betölt, ugyanilyen hibával kidob azonnal. Eredeti, moddolatlan játékot használok. Mellékeltem a crash report filet.
[crash-2019-05-16_23.20.33-client.txt](https://github.com/andris155/TheOld-Crafters/files/3189158/crash-2019-05-16_23.20.33-client.txt)

**Comment by andris155** [comment]
Kérlek teszteld le újra. Lett egy ilyesmi javítva.

**Comment by Kismalax** [comment]
Most jónak tűnik, be tudtam lépni.
