### ISSUE TITLE
Pipe, petparancs-/peti

### ISSUE THREAD

**Issue by SurvivorTheReal** [andris155/TheOld-Crafters#2912]
A pipenál, ha rárakok egy pistonra egy oak_sign-t pl, akkor azt irja hogy failed to find pipe, aztán, ha beirom hogy /peti amikor elő van véve a petem (van 7 sor invje), akkor ezt írja: An internal error occured while attempting to perform this command.
Edit: a pipe gyeltalán nem megy xd

**Comment by MrZero1** [comment]
Mypet előhívható kreatívban (Multons jelezte)

**Comment by SurvivorTheReal** [comment]
azt nem próbáltam, de még van 1 hiba, amit már jeleztem andrisnak DC-n, csak, rosszul értelmezte és nem fejeztem ki magam tisztán ami az én hibám.
