### ISSUE TITLE
Setflag nomonsterspawns

### ISSUE THREAD

**Issue by SurvivorTheReal** [andris155/TheOld-Crafters#2913]
Ha levédésemen beírom hogy /setflag nomonsterspawns akkor is spawnolnak mobok.

**Comment by andris155** [comment]
Most sem jó?

**Comment by Huntermaster0** [comment]
Jelenleg a szerver sem megy.

**Comment by SurvivorTheReal** [comment]
Ömm, valszeg összefüggésben van azzal a hibával amiről már zeronak is beszéltem és amiről beszélt veled messengeren ,ha jól láttam a képen amit DC-n küldött. Úgyhogy ha az megjavul, valszeg ez is.

**Comment by andris155** [comment]
A védések már jók. :)
