### ISSUE TITLE
Elírás /is biomes menüben

### ISSUE THREAD

**Issue by Dreed1992** [andris155/TheOld-Crafters#2915]
Terület nagyság csökkentése (-1) zöld gomb. Ezzel hozzáad nem pedig elvesz. a piros és zöld oszlop végig el van írva.
![2019-05-20_14 43 13](https://user-images.githubusercontent.com/35728669/58023930-55767d80-7b11-11e9-99b1-836b9df1a3e4.png)

-Agronaut

**Comment by andris155** [comment]
@poma123
