### ISSUE TITLE
Savsziget - Napi event

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#2916]
Kevés a napi event savon, kB 7 van, akár a mostani automatikus eventekből is lehetne áttenni napiba, mert ez így tök kevés.

**Comment by MrZero1** [comment]
Nyilván kevés, Survivalon már 2014-ben eventek voltak, nehéz lenne behozni az éves lemaradást savszigetre. Tervben vannak új napieventek. :unamused:
