### ISSUE TITLE
Megvásárolt EC oldalak eltüntek

### ISSUE THREAD

**Issue by SurvivorTheReal** [andris155/TheOld-Crafters#2918]
Vásároltam plussz 8 EC oldalt , és most az 1.14.1 es survivalon (ami hálisten már megy, és tök jól, nincs lagg se semmi) nem tudom őket elérni, azt most hadjuk mi veszett el, annyi a lényeg hogy nincsenek meg az oldalak.
![2019-05-24_08 22 56](https://user-images.githubusercontent.com/39741913/58306917-6408b180-7dfd-11e9-9b11-300c36db3d4b.png)

**Comment by poma123** [comment]
Semmi nem veszett el, csak a plugin egyelőre nem támogatja az 1.14-et.
