### ISSUE TITLE
Eszközkeret!!!

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#2919]
Eltűnt a szerverről az összes lerakott eszközkeret (survival)
Ez néhol szerintem egész nagy probléma :c

Megjegyzés:
Nekem pl az összes színes nevű szett eszközkereteken volt kiállítva :) 
#szülinapi kalap#Húsvéti szett#Szellem szett#minden más :)

**Comment by mestertrefa** [comment]
Velem is ugyanez történt. A múzeumomban sok item volt az eszközkeretekben, amik elég ritkák voltak.

**Comment by MrZero1** [comment]
Nem tudom, mi számít összesnek, de pl. az Oldmúzeumban megvannak.

**Comment by skrisz0101** [comment]
Telken és vadonban, ha minden igaz

**Comment by andris155** [comment]
Inkább arra tippelnék, hogy a kreatívban lerakottak. Ha nem olyan rég lett lerakva, akkor Admin vagy tulaj visszatudja állítani. Ha nagyon rég, akkor sajnos nem tudjuk ezeket visszaállítani.

**Comment by skrisz0101** [comment]
Kafa :)

**Comment by skrisz0101** [comment]
@andris155 kreatívban nem lehet letenni eszközkeretet. Old ranggal sem

**Comment by andris155** [comment]
De kreatívban is lehetett bele tárgyakat rakni. Akkor viszont így nem tudom mi alapján van ez.

**Comment by skrisz0101** [comment]
Hát én nem raktam bele Kreában szülinapi kalapot meg gyűjthető szettet, az is biztos
