### ISSUE TITLE
Szerverleállások - survival

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#2921]
Eddig ma 2x tapasztaltam, gondoltam jelentem. Pár percig van ez, majd felenged mindenkit.
![2019-05-24_12 19 15](https://user-images.githubusercontent.com/29951969/58321362-3c761100-7e1e-11e9-859b-86d1d0cce5c2.png)

**Comment by andris155** [comment]
Ki volt írva, hogy összeomlik néha. De elvileg javítva lett ez is.
