### ISSUE TITLE
Szavazás hiba

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#2925]
Survival-on 85 szavazatom van erre a hónapra (ami lehetetlen 25 nap alatt), savszigeten 50 (ennyi se lehet, pár napot kihagytam), és másét is hibásan írja.

![kép](https://user-images.githubusercontent.com/16057404/58374796-645f9480-7f44-11e9-946e-2632a51a0569.png)

![kép](https://user-images.githubusercontent.com/16057404/58374787-4e51d400-7f44-11e9-9734-f12c63e6a28a.png)

**Comment by andris155** [comment]
Szerintem a kimaradt napok miatt megkeveredett.

**Comment by andris155** [comment]
Kérlek nyiss majd új jelentést, ha a következő hónapban is hibásan számolja.
