### ISSUE TITLE
Csákány, additions parancs és endermite eltűnés hiba

### ISSUE THREAD

**Issue by DerFlasHUN** [andris155/TheOld-Crafters#2927]
Üdv!
**Csákány készítés** 
Minap vettem észre, hogy nem lehet lehet fa,emeráld,obsidian csákányt készíteni. Mellékelem a képeket.
![obsi](https://user-images.githubusercontent.com/32020200/58379268-28f7b100-7faa-11e9-9a15-80aa9c8c7195.PNG) 
![facsákány](https://user-images.githubusercontent.com/32020200/58379297-4462bc00-7faa-11e9-9175-096af1e9f31a.PNG)
![emeráld](https://user-images.githubusercontent.com/32020200/58379354-d23ea700-7faa-11e9-96ab-1bb265f0ecf0.PNG)

**Additions repair hiba**

Nem tudom megjavítani a cuccaimat a /additions repair paranccsal (VIP rangom van), mivel kiad egy hibaüzenetet és nem történik semmi. 
![repair](https://user-images.githubusercontent.com/32020200/58379314-77a54b00-7faa-11e9-9926-ca434f89a984.PNG)

**Endermite eltűnés**

Hiába van elnevezne az Endermite ugyan úgy eltűnik még ha csak pár block távolságra is megyünk tőle.

//DerFlasHUN_

**Comment by andris155** [comment]
javítva
