### ISSUE TITLE
OLD Kard

### ISSUE THREAD

**Issue by GetOut101** [andris155/TheOld-Crafters#2928]
Minap savszigeten mobok irtása közben eltűnt (EHzy) OLD kardja amit erre a célra adott nekem kölcsön. Egyik pillanatról a másikra nem volt a kezemben a kard. Eltörni biztos, hogy nem tört mert zöldön volt az élete. Ezzel kapcsolatban szeretnék segítséget kérni.

**Comment by andris155** [comment]
Kérlek ide írj: https://www.oldcrafters.net/kapcsolat/
