### ISSUE TITLE
Endermite - Savsziget

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#2929]
Mivel senki nem írta meg ide, mert minek(...), de tegnap óta az endermite despawnol. Enderman farmokhoz kell, elnevezzük és rá pár másodpercre el is tűnik.

**Comment by MrZero1** [comment]
Most látom, #2927 endermite, de még mindig él a hiba.

**Comment by andris155** [comment]
30 a limit rá, de ez mindig így volt és nem lett változtatva sosem ezen.

**Comment by MrZero1** [comment]
Még most sem jó sajnos :(

**Comment by andris155** [comment]
Úgy olvastam az mcMMO tiltotta le, hogy ne lehessen vele farmolni.

**Comment by MrZero1** [comment]
Survivalon jó, bár nem tudom ugyanaz a verzió van mint savon.
