### ISSUE TITLE
Savsziget - Mcmmo ásás

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#2930]
Nem megy az ásás a savszigeten az acidisland világban, viszont a flat-ben igen.

![kép](https://user-images.githubusercontent.com/29709854/58385858-3dae6600-7ff7-11e9-9bd9-c09d5bfb98a0.png)
 
Ez a flatben van, itt növekszik, de a saját szigetemen nem megy

**Comment by MrZero1** [comment]
Fejlemény: Van akinek megy az ásás, van akinek nem (játékosok közül)

**Comment by andris155** [comment]
Lerakott blokkokat nem fog beleszámolni. Akkor sem ha leeső homokról vagy stb...-ről van szó ha úgy rakták le.

**Comment by Dreed1992** [comment]
viszont akkor nincs értelme az old ásónak,mivel savon nem fogsz olyat ásni ami nem "lerakott"és aki megvette az nem megy semmire vele.

**Comment by andris155** [comment]
Sima ásóval sem megy akkor nem?

**Comment by Dreed1992** [comment]
sima ásóval van akinek megy. simával húzom most én is a szintet , pl sódert is simával ütöm megy,adja a sódert és az exp-t is,oldal csak kovakövet dob. egyszerűen használhatatlan az old.
pl _ecu_ sima ásóval kap exp-t.
Azért érdekel lesz e valami változás vagy becserélitek e az ásómat másra mert hasztalan jelenleg.

**Comment by andris155** [comment]
Amit nem én vagy más játékos rak le azzal nekem tökéletesen működik.
