### ISSUE TITLE
Mob fejek plugin (A régi fejlesztése megszűnt.)

### ISSUE THREAD

**Issue by andris155** [andris155/TheOld-Crafters#2931]

**Comment by Kismalax** [comment]
Ma reggel szereztem néhány fejet survivalon, a creeper, denevér és fantom fejeknek "null" a nevük. Terveztem neki issue-t nyitni, de akkor inkább ide írom.  Ami feltűnt még, hogy sokkal gyakoribb a fej dropp, mint korábban.

**Comment by andris155** [comment]
Az teszt jelleggel volt csak. Bekerült egy másik megoldás.
