### ISSUE TITLE
Savsziget szint

### ISSUE THREAD

**Issue by GetOut101** [andris155/TheOld-Crafters#2932]
A Savszigeten EHzy barátom tapasztalta, hogy nem annyi szintet ad az adott block amennyit kéne. Ezzel így kb. 200 szintet buktunk.

**Comment by EHzy001** [comment]
A beacon szó szerint 0 pontot adott a szigethez (pár szint még le is ment :D) , az encderchest pedig jóval kevesebbett mint amennyit kellett volna neki (110-120-szal)

**Comment by andris155** [comment]
Ezeket talán @poma123 állította (?)

**Comment by poma123** [comment]
Nem állítottam rajta, de megnézem

**Comment by poma123** [comment]
mindkettő "limitálva" van a kezdetek óta, a beacon addig ad szintet amíg max. 3 db van a szigeten, utána nem, az enderchest pedig 10 darab után nem ad.
