### ISSUE TITLE
Pipe hiba

### ISSUE THREAD

**Issue by Huntermaster0** [andris155/TheOld-Crafters#2933]
A Pipe csak akkor megy a survival szerveren, ha a tábla a piston tetejére van rakva (ezt senki se használja így). Ha az oldalára rakom akkor a "Failed to find pipe!" hibát írja ki.

**Comment by andris155** [comment]
Most működik?

**Comment by Huntermaster0** [comment]
Nézem csak kb. 10 perce kifagyott a survival.

**Comment by Huntermaster0** [comment]
Most jó, megy az oldalára rakás, és jó a szelektálás is.

**Comment by Huntermaster0** [comment]
Közben Survi is tesztelte, kiderült, hogy csak sima Oak táblával megy, a többivel nem.
