### ISSUE TITLE
Login szerver ajánlott mc verzió

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#2934]
1.13.2 van kiírva, de csak 1.14.1-gyel lehet felmenni.

![kép](https://user-images.githubusercontent.com/16057404/58437239-643cd180-80c9-11e9-8a44-6bdab9469ceb.png)

**Comment by andris155** [comment]
Hopp. Ezt elfelejtettem átírni. :D

**Comment by andris155** [comment]
javítva
