### ISSUE TITLE
Petinventory

### ISSUE THREAD

**Issue by SurvivorTheReal** [andris155/TheOld-Crafters#2935]
Amit berakok pet inventory-ba 1.13.2 es világban, az nem lesz ott 1.14.1 es világban ugyanazon pet inventoryjában.  
Videót nem tudok feltenni mert 42 mega tömörítve. De discordon képernyőmegosztásban megmutathatom.

**Comment by andris155** [comment]
Most jó?

**Comment by SurvivorTheReal** [comment]
Megtekintem
1p

**Comment by SurvivorTheReal** [comment]
Ömm, nem jó, betettem 6 stack papírt, eltpztem az 1.14.1 es világba , beírtam /peti és nem voltak ott. Még úgyse hogy előtte elteszem mielőtt eltpzek.

**Comment by andris155** [comment]
akkor majd holnap lesz jó

**Comment by SurvivorTheReal** [comment]
Oké, köszönöm ^^ mindenki nevében akik pettel hurcolkodnak :D

**Comment by andris155** [comment]
elvileg már jó
