### ISSUE TITLE
Savsziget-Creeper pusztít / tnt csílle jutalom felesleges a küldiért

### ISSUE THREAD

**Issue by Dreed1992** [andris155/TheOld-Crafters#2936]
Az a zöld retek felrobbantja a csíléket és darabokra húlik,valamint a TNT csílle  felesleges jutalom a küldiből,hiszen nem is engedi lerakni.

![2019-05-28_16 02 34](https://user-images.githubusercontent.com/35728669/58484913-53409e80-8163-11e9-8265-1a8bb205816a.png)
![2019-05-28_16 02 38](https://user-images.githubusercontent.com/35728669/58484915-53409e80-8163-11e9-9f28-5223b2274a18.png)
![2019-05-28_16 11 35](https://user-images.githubusercontent.com/35728669/58484916-53409e80-8163-11e9-8180-8f65c2049787.png)

**Comment by andris155** [comment]
Szerintem csillét nem gond, ha pusztítja.

**Comment by andris155** [comment]
A csillét @poma123 tudja kivenni.

**Comment by poma123** [comment]
On it.

**Comment by poma123** [comment]
Ez pontosan melyik küldetés, @Dreed1992 ?

**Comment by andris155** [comment]
Néztem a challenges-ekben de azokban nem volt TNT csille.

**Comment by poma123** [comment]
dreed úr úgy döntött nem válaszol nekünk, leszarja a jelentését és minket is, csak normális játékos akar lenni, szval ezt bezárom
