### ISSUE TITLE
Építész+ [Tag+] rang - Minemarket

### ISSUE THREAD

**Issue by poma123** [andris155/TheOld-Crafters#2938]
Kérlek tedd be minemarketre a [Tag+] rangot a következő jellemzőkkel:
Ár: 1016 OCD

Tag jogai plusz:
* /nick - Színes név pl.: zöld név /nick &2név
* /heads - Fej adatbázis megnyitása
* /pwarp set - Saját warp beállítása.
* /pweather - Eső ki/be kapcsolása saját magadnak.
* /ptime day, night - Saját idő változtatása. (day = nappal, night = éjszaka)
* Színes írás színkódokkal. pl.: &3
* 40 telek
* 10 otthon
* Weather telek flag - Időjárás állítása a telkeken. (clear vagy rain)
* A beállított warp a rang lejárata után is megmarad.

_Köszi_

**Comment by andris155** [comment]
kész

**Comment by andris155** [comment]
https://theold.minemarket.hu/category/rangokpitesz

**Comment by poma123** [comment]
köszi
