### ISSUE TITLE
Pipe rendszer hiba

### ISSUE THREAD

**Issue by Frenzy79** [andris155/TheOld-Crafters#2939]
Szia Andris! Nem működik a Pipe rendszer! Bármit belerakok a szelektálóba nem szétválogatja hanem eltünteti (nem kerül bele a ládákba), így elég sok mindenem elszállt mire észleltem!

**Comment by SurvivorTheReal** [comment]
Nekem tegnap tökéletesen működött, /m ezz rám ha fent vagy (Survior) és megnézem.
Gyors kérdés: átnéztél minden ládát?

**Comment by andris155** [comment]
Szerintem ma is működnie kell, ha tegnap is működött.

**Comment by andris155** [comment]
Ha nem működik, akkor ide írd meg, hogy mi nem.
https://github.com/andris155/TheOld-Crafters/issues/2937
