### ISSUE TITLE
SkyPvP kizuhánás bug

### ISSUE THREAD

**Issue by geri5200** [andris155/TheOld-Crafters#294]
Amikor 1 ember kiesik/kilökik és beírja a /lobby parancsot azután automatikusan vissza rakja a spawnra az embert és nem hal meg. A bugot DOMI vette észre.

**Comment by andris155** [comment]
A /lobby parancsot engedi párbaj közben is?

**Comment by geri5200** [comment]
Párbaj közben nem de ha eszi az aranyalmát akkor addig sikerül neki kimenjen pvpből és még a lobby parancsot is be tudja írni

**Comment by andris155** [comment]
javítva
