### ISSUE TITLE
Pet skill tree gui

### ISSUE THREAD

**Issue by SurvivorTheReal** [andris155/TheOld-Crafters#2940]
Nem írja mikre lesz képes az adott skill treevel 85 ös szinten. Tudom ott van a /warp petparancsok warp, viszont ott nem írja milyen jelzőfényekre lesz képes, vagy csak vak voltam és nem láttam.

**Comment by andris155** [comment]
Melyik mob és melyik skilltree?

**Comment by andris155** [comment]
Ahol nincs kiírva ott nem képes a pet jelzőfényre. Átnéztem és mindenhol ki van írva ahol viszont igen.
