### ISSUE TITLE
Nether portal hiba

### ISSUE THREAD

**Issue by Huntermaster0** [andris155/TheOld-Crafters#2941]
Ha a netherben csinálok egy portált és az az overworldben meghaladná a 10000 x vagy z koordinátát, akkor csak 10000ig visz el, hiába kéne mondjuk 20000ig. Ha ugyanezt fordítva csinálom és mondjuk az overworld 12000. blocknál csinálok nether portált akkor a netherben jó helyre rak.

**Comment by Huntermaster0** [comment]
Most látom, hogy a world114 le van korlátozva 10k blockra, de a nether portált a sima worldbe rakta, gondolom az új map miatt érzékelte a 10k blockot.

**Comment by andris155** [comment]
A Spigot megszüntette a portálos event-et. Csak nms-el működne, de azt nem szerencsés használni, mert minden verzió frissítésnél változik.
Egyelőre a Multiverse-Core nem oldotta meg ezt a problémát.

**Comment by andris155** [comment]
javítva amennyire lehetett.
