### ISSUE TITLE
Levédés határa után piston bug

### ISSUE THREAD

**Issue by Huntermaster0** [andris155/TheOld-Crafters#2943]
Ha egy szerkezet eléri a levédés határát és tovább működik, akkor van rá esély, hogy kidobódik a piston (ez gmcben épített dolgok esetében addolás is, bár engem leginkább csak idegesített). Ez néhány szerkezetnél a teljes újjáépítést jelenti, ami így eléggé zavaró. Szerintem jobb lenne, ha legalább megállna a levédés határánál, vagy simán menne tovább. Még pontosan nem tudom, hogy mikor dobja ki, de a szerveren meg tudok mutatni egy szerkezetet, aminél ez gondot okoz (és valószínűleg nem csak ennél okoz gondot, régebben is volt már ilyen problémám, de akkor nem gondoltam a levédésre).

**Comment by andris155** [comment]
Minden levédésnél így van, vagy csak megint egy helyen hibás?

**Comment by Huntermaster0** [comment]
Eddig netherben lett tesztelve, ott így volt. És visszagondolva arra amikor egy helyen hibás volt, hát ott is levédés volt. Nerherben több helyen teszteltem már, délután tesztelem szabadban is akkor.

**Comment by andris155** [comment]
Szerintem ezzel nem nagyon lehet mit kezdeni. Nem találtam rá beállítást sem.
