### ISSUE TITLE
Tábla problémák gmcben

### ISSUE THREAD

**Issue by Kismalax** [andris155/TheOld-Crafters#2945]
Kreában nem lehet táblát tenni pistonra, nem történik semmi, nem teszi le a táblát.
Ha kreában nem piston blokkra teszek [Pipe] táblát, kidobódik (!) a tábla.

**Comment by SurvivorTheReal** [comment]
Most nem kötekedésből, de ha nem pipe "alkatrészre" teszel pipe táblát, csoda hogy nem találja?

**Comment by Kismalax** [comment]
> 
> 
> Most nem kötekedésből, de ha nem pipe "alkatrészre" teszel pipe táblát, csoda hogy nem találja?

A kidobódik alatt azt értem, hogy fel lehet venni utána a táblát, azaz "addolásra" ad lehetőséget.

**Comment by SurvivorTheReal** [comment]
Így már más c:

**Comment by andris155** [comment]
A tábla sokat nem ér, ha lesz gépek akkor mindenképpen utána nézek ennek azért.

**Comment by andris155** [comment]
Nem nagyon lehet sajnos ezzel mit csinálni.
