### ISSUE TITLE
Warp bolt

### ISSUE THREAD

**Issue by SurvivorTheReal** [andris155/TheOld-Crafters#2946]
Ha eltpzek /warp bolt-ra kifagy a szerver, nem újraindul vagy ilyesmi, egyszerűen kidob mindenkit a szerver pár másodperc után.
A hab a tortán, hogy mivel warp boltban leszel miután belépsz a szerverre, egyből kifagy megint :D

**Comment by Kismalax** [comment]
Szerintem ez bolttól független, néhány percenként újraindul a szerver :(

**Comment by SurvivorTheReal** [comment]
Igen, de ha arra a warpra megyek fixen kidob mindenkit. Annyival meg lehet oldani ha az a valaki nagyon akar játszani aki ott dobódott ki, hogy amint belép ,villámgyorsan ctrl+V vel a /p h paranccsal a telkére megy, ha van persze.

**Comment by andris155** [comment]
A Spigot privátte tett egy olyan részt a szerverfájlban, amit sok plugin használt. Ez eredményezte a hibákat. :/ De már javítva lett.
