### ISSUE TITLE
Mcmmo

### ISSUE THREAD

**Issue by nicolettie** [andris155/TheOld-Crafters#2948]
A növénytan szintem már 100-as (több is), viszont az 1.14-es virágokból csak 1 db-ot kapok (a régiekből ugye 2-t dob mindig), viszont az mcmmo szintet növeli amikor kiütöm. Nem tudom ez hiba-e.

**Comment by andris155** [comment]
Ha lesz számítógépem megnézem a konfigban hogy van bővebben.

**Comment by andris155** [comment]
Frissítettem a konfigokat, ha továbbra sem dob, akkor ez nem hiba. Vagy még nem készítette el a fejlesztő.
