### ISSUE TITLE
csn

### ISSUE THREAD

**Issue by nicolettie** [andris155/TheOld-Crafters#2949]
beírtam a ./csn history parancsot hogy megnézzem az eladásokat, erre az olvasatlanokat olvasottá tette. :( mijjjért? :D 
![csn](https://user-images.githubusercontent.com/48986609/58949895-d37f8900-878d-11e9-9e16-780273f4ba01.jpg)

**Comment by andris155** [comment]
Elvileg teljesen nem is működik nem?

**Comment by nicolettie** [comment]
2 hete körülbelül még működött rendesen! Amikor beírtam hogy /csn history akkor kiadta rendesen hogy ki miből mennyit vett és mennyiért. :/

**Comment by andris155** [comment]
Sajnos jelenleg nem támogatja a legújabb szerverfájl verziót. :(

**Comment by andris155** [comment]
Most működik?

**Comment by nicolettie** [comment]
Igen!

**Comment by andris155** [comment]
508 OCD
