### ISSUE TITLE
Endercontainers EssentialsX hook javítása

### ISSUE THREAD

**Issue by Huntermaster0** [andris155/TheOld-Crafters#2951]
Survival szerveren nem megy a /ec az Old rangosoknak.

**Comment by andris155** [comment]
A /endercontainers:ec vagy :enderchest-el működnie kell, ameddig nincs javítva.

**Comment by Huntermaster0** [comment]
Ma EHzy javasolta nekem a /endchest-et, az is megy.

**Comment by skrisz0101** [comment]
Amit Skrisz javasolt Ehzy-nak :(

**Comment by andris155** [comment]
javítva
