### ISSUE TITLE
Smaragd páncél nem használódik el.

### ISSUE THREAD

**Issue by BacsDomi** [andris155/TheOld-Crafters#2952]
D4nii javasolta, hogy jelentsem az alábbi hibát!

Smaragd páncélszett nem törik/használódik el. Egeret ráhúzva vagy az itemet kézbe véve lehet látni, hogy mínuszban írja az élettartamát.

Hogy jobban szemléltetni tudjam, csatoltam képet.
![2019-06-06_18 17 51](https://user-images.githubusercontent.com/36732838/59049870-3b66ca00-8889-11e9-8e6f-9ea7ae07aca3.png)

**Comment by Huntermaster0** [comment]
#2594
•Nem használódnak el a páncélok

**Comment by andris155** [comment]
Ahogy írták jelentett hiba.
