### ISSUE TITLE
Spawner kiütés limit növelés rangonként

### ISSUE THREAD

**Issue by SurvivorTheReal** [andris155/TheOld-Crafters#2956]
tag+ ugyanúgy 5
v.i.p 6 spawner/nap
elit 7
prémium 8
old 10

Nem tudom jó ötlet-e, csak eszembejutott.

**Comment by nicolettie** [comment]
én mindenképpen támogatom az ötletet, már nekem is szembe jutott, örülök hogy javasoltad :D

**Comment by andris155** [comment]
Szerintem jó ötlet.

**Comment by UDPSendToFailed** [comment]
#2737

**Comment by andris155** [comment]
Csak azóta már nincs Ridables úgyhogy lehet jó lenne valami újabb jog helyette

**Comment by poma123** [comment]
szólhatott volna valaki fbn hogy van ilyen ötlet, rég megcsináltam volna xd

**Comment by poma123** [comment]
Survival-on kész, "tesztüzem" de elvileg jó. 1 hétig marad itt, ha jó többi szerveren is be lehet vezetni.
![image](https://user-images.githubusercontent.com/25465545/59611268-4805e080-911b-11e9-9080-93c809c853a6.png)

**Comment by andris155** [comment]
Köszönjük
