### ISSUE TITLE
/ah fps lag spike

### ISSUE THREAD

**Issue by SurvivorTheReal** [andris155/TheOld-Crafters#2957]
Nem tudom hogy ez normális-e egy szerintem elég erős gépen.
Amint beírom hogy /ah egyből 0-1 fps pár másodpercig. Továbbá minden egyes "gomb" mint az oldal újratöltése gombnál is ugyanez van. 
![ah](https://user-images.githubusercontent.com/39741913/59157444-f3bf8880-8aaa-11e9-9279-79e19c53d26d.png)

Még valami.
Nem, nem én szerkesztettem oda azt az 1-2 pixel széles csíkot.

**Comment by UDPSendToFailed** [comment]
Nálam hibátlanul működik egy sokkal régebbi laptopon, texturepack nélkül próbáltad?

![kép](https://user-images.githubusercontent.com/16057404/59158751-515dd000-8abf-11e9-9400-f846bb0ed2b9.png)

**Comment by andris155** [comment]
A fej skinek betöltése okozhat akadást, ha jól emlékszem
