### ISSUE TITLE
Pay összeg

### ISSUE THREAD

**Issue by nicolettie** [andris155/TheOld-Crafters#2959]
Szerettem volna küldeni skrisznek 69,69$-t, be is írtam hogy ./pay 69,69 és 6969$-t küldtem el. 
mivel sk-nak küldtem tőle nem sajnálom, de ha másnak küldtem volna akkor lehet hogy már nem venném így félvállról :)

**Comment by andris155** [comment]
Mivel angol a formátum ezért ponttal kell írni. Ha lesz gépem megfogom nézni. Azt hiszem állítható csak le kell tesztelni.

**Comment by poma123** [comment]
```

# The format of currency, excluding symbols. See currency-sumbol-format-locale for symbol configuration.
#
# "#,##0.00" is how the majority of countries display currency.
#currency-format: "#,##0.00"
```

**Comment by andris155** [comment]
Sajnos a space-t nem támogatja így nem tudom magyarra állítani. De ha már $ szerintem jobb is, ha formátum is az.

**Comment by poma123** [comment]
oke
