### ISSUE TITLE
Zone hiba

### ISSUE THREAD

**Issue by akos222** [andris155/TheOld-Crafters#296]
Bedrock alá expandolásnál nem hibaüzenetet ír, hanem azt, hogy sikeres nagyobbítás. A nagyobbítást viszont nem végzi el.
/zone owners <zónanév> add <játékosnév> parancs használatánál Ismeretlen parancs hibát jelez.

**Comment by andris155** [comment]
Elvileg javítva.

**Comment by akos222** [comment]
Tesztelve, működik.

**Comment by akos222** [comment]
További zonehoz tartozó hiba:
/zone delete parancsnál internal errort jelez. A parancs végbemegy, és törli is a kívánt zónát, de a hibaüzenetet így is kidobja.

**Comment by andris155** [comment]
Most is írja?

**Comment by akos222** [comment]
Igen

**Comment by andris155** [comment]
Most jó?

**Comment by akos222** [comment]
Igen, köszi.
