### ISSUE TITLE
Építész+ | Másoknak addolható fejek

### ISSUE THREAD

**Issue by Rysten546** [andris155/TheOld-Crafters#2960]
Építész+ szerveren a fejeket be lehet tenni egy másik játékos telkén egyes dolgokba ha hozzá vagyunk adva a telekhez, ezáltal a játékos megkapja azt és tudja használni. Pl.: Kemence, Tárolócsille, Tölcséres csille, Csapdaláda, Enderláda és Shulkerdoboz. Ezeknek a letiltása jó ötlet, nem lehet bele nyúlni de a probléma az, hogy ami le van tiltva azt ha egyszer le teszi az ember, azt nem tudja többet kiütni. (Láda, Adagoló, Kidobó)

**Comment by poma123** [comment]
Most jó?
