### ISSUE TITLE
Szavazás hiba again

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#2963]
Survivalon megint hibásan számolja a szavazatokat, savszigeten jó. minecraft-mp.com-on 14 szavazatom van, plusz topg.org-on ugyanennyi vagy több, de survivalon csak 12-t ír, és a vote pontokat se adja meg érte. Raynor 12 szavazattal egyáltalán nincs benne a havi topban, szerintem az egész lista hibás így.

- Survival:
![kép](https://user-images.githubusercontent.com/16057404/59495114-ed585480-8e8e-11e9-9d5e-5ea37182f2db.png)

- Savsziget:
![kép](https://user-images.githubusercontent.com/16057404/59494459-78384f80-8e8d-11e9-8374-b10427484027.png)

**Comment by andris155** [comment]
Azt hiszem ennek majd komolyabban utána kell néznem. :/

**Comment by andris155** [comment]
Most jól számolja? Állítottam rajta.

**Comment by UDPSendToFailed** [comment]
Nem, néhány playernél hiányoznak a szavazatok, másnál sokkal több van, mint kéne.

- Survival:
![kép](https://user-images.githubusercontent.com/16057404/59707992-1ae12d00-9204-11e9-8bc7-d93911f56956.png)

- Savsziget:
![kép](https://user-images.githubusercontent.com/16057404/59707949-00a74f00-9204-11e9-9e72-41c3fc1a8e1b.png)

**Comment by andris155** [comment]
Beállítottam az egész rendszert újra. Ha most sem jó, akkor már csak az adatbázisra tudok maximum tippelni, ami miatt nem jó.

**Comment by andris155** [comment]
Nyilván a régiek akkor sem változnak meg, ha most jól számolja.
