### ISSUE TITLE
Automatic doors – Automata ajtók

### ISSUE THREAD

**Issue by nicolettie** [andris155/TheOld-Crafters#2964]
**Automatic doors – Automata ajtók**
https://www.spigotmc.org/resources/autodoors-automatic-doors.30576/
Hasonló, mint a gate-es plugin szerintem, én hasznosnak találom, hogy végre ajtót is lehet ilyen módon csinálni és nem kell bonyolult redstone rendszereket építeni hozzá, mert ez nem igényel redstone-t.
![Screenshot_1](https://user-images.githubusercontent.com/48986609/59522778-cec67d80-8ecf-11e9-959c-152a6168fd87.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/48986609/59522780-cec67d80-8ecf-11e9-96df-86dba5da53b3.jpg)

**Comment by MrZero1** [comment]
Ez azért is jó, mert jelenleg nincs gate, door, meg mittudomén milyen craftbookos cuccli.

**Comment by andris155** [comment]
Le kellene tesztelni a Craftbook-ost is mennyire laggos most.

**Comment by Huntermaster0** [comment]
Nincs benne redstone :(

**Comment by nicolettie** [comment]
@Huntermaster0 ez a legjobb benne :D megkönnyíti mindenki dolgát :P

**Comment by MrZero1** [comment]
A Craftbookos ajtó jól megy (a gate, bridge nem).

**Comment by andris155** [comment]
A Craftbook-os ajtó mivel működik ennek így nincs értelme.
