### ISSUE TITLE
ChestSort – Ládaelrendező

### ISSUE THREAD

**Issue by nicolettie** [andris155/TheOld-Crafters#2965]
**ChestSort – Ládaelrendező**
https://www.spigotmc.org/resources/1-8-1-14-chestsort-api.59773/
Na ez az ami szerintem naagggyon sok játékosnk hasznos lenne, magamból kiindulva én borzasztó rendetlen vagyok és ha elmegyek bányászni vagy raidelni vagy felfedezni, akkor összeszedek mindenféle itemet, blokkot és otthon csak beszórom a ládába és eléggé megnehezíti a szortírozást utána, ez a plugin viszont átláthatóvá tenné a chesteket és azok tartalmát. A fejlesztő elmondása szerint semmi esély nincs itemek elvesztésére, addolásra vagy duplikálásra! (_There is absolutely no chance of item loss / duplication or metadata corruption! Guaranteed!_ )
![chestsort-screen1](https://user-images.githubusercontent.com/48986609/59522684-91fa8680-8ecf-11e9-9d65-1705ef59f69f.jpg)
![chestsort-screen2](https://user-images.githubusercontent.com/48986609/59522685-91fa8680-8ecf-11e9-9163-fa8c7ce26feb.jpg)

**Comment by MrZero1** [comment]
Ez amúgy savszigeten is hasznos lehet, márcsak az ércgenerátor miatt.

**Comment by andris155** [comment]
Jobb erre kliensbeli modot használni.
Pl.: Invtweaks

**Comment by MrZero1** [comment]
:angry: :question:

**Comment by nicolettie** [comment]
Ha ugyan olyan vagy hasonló akkor még mindig javaslom/támogatom :D

**Comment by UDPSendToFailed** [comment]
Invtweaks-ból 1.12-es a legújabb verzió, és régen se nagyon működött a nocheat miatt. :/ 
+1 a pluginra

**Comment by Huntermaster0** [comment]
Erre van maruohon 1.14.2es ItemScrollere, a csávó csinálja a Litematic-ot is, próbálja minden modját a legfrissebb verzión tartani.

**Comment by andris155** [comment]
Az itemscroller másra van ahogy látom. Más mod erre nincs is?

**Comment by poma123** [comment]
Megnézem a teszt szerveren, ami fel van tüntetve.

**Comment by poma123** [comment]
nagyon menő. én betenném

**Comment by poma123** [comment]
![image](https://user-images.githubusercontent.com/25465545/59624850-2b2bd600-9138-11e9-8f85-4b9c07d8ae5b.png)
a láda bezárása és újrakinyitása után:
![image](https://user-images.githubusercontent.com/25465545/59624875-354dd480-9138-11e9-8f0f-d6b0fb6836dc.png)

**Comment by D4nii** [comment]
Mindkettő szerverre nagyon jól jönne szerintem én támogatoma  bekerülését!

**Comment by andris155** [comment]
Ha jól láttam már bekerült. :D

**Comment by poma123** [comment]
bekerült mindkét szerverre

**Comment by andris155** [comment]
508 OCD

**Comment by nicolettie** [comment]
a shulker box tartalmát is elrendezi, nagyon jó ez a plugin!
köszönöm Andris az OCD-t :)
