### ISSUE TITLE
Quests – Küldetések

### ISSUE THREAD

**Issue by nicolettie** [andris155/TheOld-Crafters#2966]
**Quests – Küldetések**
https://www.spigotmc.org/resources/quests.3711/
Mivel a szerver nem rpg alapú, ezért ezt igazság szerint csak egy „mellék” pluginnak gondolnám, az elképzelésem az lenne, hogy napi 4-5 ilyen mini küldetést lehetne megcsinálni, ami főleg a tag rangú játékosoknak kedvezni, például tudnának egy kis pénzt szerezni vele, vagy némi ércet, bármit ami apróság de mégis segíti őket a játékban. Ha esetleg ez bekerülne, már ötleteim is vannak, hogy milyen küldetéseket lehetne beírni.

**Comment by MrZero1** [comment]
Hm..

**Comment by andris155** [comment]
A túlélő szerver másról szól. Szerintem nem ide való. Ha valaki nagyon RPG-zni akar nem itt fog játszani úgy sem.

**Comment by andris155** [comment]
A savon, ami van teljesítményes plugin az nem lenne rossz, de azt meg nem bírná el már a túlélő szerver, mivel elég sok erőforrást használ.

**Comment by skrisz0101** [comment]
@andris155 pár küldetés csak dobna a játék élményem 😕

**Comment by poma123** [comment]
az a teljesítményes plugin amúgy így "köztünk szólva" nem nagy szám
