### ISSUE TITLE
PinataParty – Pinata/Pinyáta buli

### ISSUE THREAD

**Issue by nicolettie** [andris155/TheOld-Crafters#2967]
**PinataParty – Pinata/Pinyáta buli**
https://www.spigotmc.org/resources/50-off-pinataparty.59318/
Ez egy nagyon aranyos kis „easter egg” ha úgy vesszük. A lényege hogy ha a szerver elér egy bizonyos mennyiségű szavazatot, akkor a spawnon megjelenik egy láma különböző színekben tüzijáték effekttel, meg van adva neki X életerő (x=ahányszor ütni kell), végül „felrobban” és dobál mindenféle jóságot. Tud zenélni is meg minden ilyesmi. Igazából ez egy ösztönzés a játékosoknak, hogy szavazzanak a szerverre, és persze legyenek is aktívak, hátha felbukkan egy pinata bulis láma :D Tudom, hogy a szavazásért lehet kapni most is szavazati pontokat, de hátha megtetszik ez a plugin. A hátulütő, hogy fizetős a plugin, 2,50 euroba kerül, ami 800 forint körül van, viszont ez nem egy nagy összeg szerintem.
![c60d631241664d29c399862e55c882906465b902](https://user-images.githubusercontent.com/48986609/59522693-9a52c180-8ecf-11e9-9173-711d37491e62.gif)

**Comment by MrZero1** [comment]
Ezt akár most meg is venném..:D

**Comment by SurvivorTheReal** [comment]
Ilyet anno csináltak egy mmorpgben is ilyen privát szerveren, nagyon szerettük :)

**Comment by Huntermaster0** [comment]
+1

**Comment by andris155** [comment]
Ha lesz gépem bővebben megnézem majd. Ha jó, akkor mindenképpen bekerül.

**Comment by poma123** [comment]
megvettem, teszteljük

**Comment by poma123** [comment]
berakva survira

**Comment by andris155** [comment]
508 OCD
