### ISSUE TITLE
VKBackPack – Hátizsák

### ISSUE THREAD

**Issue by nicolettie** [andris155/TheOld-Crafters#2968]
**VKBackPack – Hátizsák**
https://www.spigotmc.org/resources/vkbackpack.10117/
Ez egy nagyon jó kis pluginnak tűnik, főleg azoknak akik sokat bányásznak (és valamiért mindig hazaviszik a sok „felesleges” zúzottkövet), ugyanis a bányászott blokkok automatikusan eltárolódnak a hátitatykóba és nem kell az itemeket izzadva rendezgetni az inventoryba amikor valaki tele van, hogy mégis hova tegye az ezredik stack zúzottkövét :D (csak vicc, de értitek mire akarok célozni). 
HA van rá lehetőség, akkor ahogy az enderchestet, ezt is össze lehetne valahogy kötni a minemarkettel és ott lehetne venni plusz hátitáskát. Viszont ez a plugin fizetős, 16 USD-be kerül, ami kb 4500 Forint.
![tRQp8At](https://user-images.githubusercontent.com/48986609/59522713-a3439300-8ecf-11e9-9ae9-092f71ba0fee.png)

**Comment by MrZero1** [comment]
Van, ami megéri az árát, kérdés, hogy megéri e :D

**Comment by andris155** [comment]
Úgyhogy ingyen is van ilyen szerintem nem éri meg. Meg így kitudja, hogy megy-e Java 11-en. Nagyon írják ott, hogy Java 8 kellene hozzá.

**Comment by andris155** [comment]
Ott az EnderContainers. Szinte ugyan ez. Ott is lehet egy csomó tároló helyed is és paranccsal is működik.

**Comment by MrZero1** [comment]
Ami ugye nincs, meg ocd-s jog
