### ISSUE TITLE
LumberJack – Favágó

### ISSUE THREAD

**Issue by nicolettie** [andris155/TheOld-Crafters#2969]
**LumberJack – Favágó**
https://www.spigotmc.org/resources/1-13-1-14-lumberjack.60306/
Tudom hogy az mcmmo képességek között már van olyan ami könnyíti a favágást, mégis érdemes ránézni erre a pluginra, ez főleg azoknak kedvez akiknek nincs fly joguk. Annyit tud ez a plugin, hogy ha a fa alját kivágod, akkor a fa törzsének többi része egy blokkal lejjebb esik és nem kell felmászni, hogy a felsőbb részeket is elérjük.

**Comment by MrZero1** [comment]
Hasznos dolognak tűnik.

**Comment by SurvivorTheReal** [comment]
Ha jól értem, ha beírjuk a parancsot, csak a kiütött log felett esik le a cuccli? Ez nagyon nagyon jó :D

**Comment by andris155** [comment]
Az mcMMO-s favágás miatt ez nem kerül be.
