### ISSUE TITLE
Use flag, Lift tábla

### ISSUE THREAD

**Issue by GetOut101** [andris155/TheOld-Crafters#2974]
A Lift Up/Down tábla nem működik use flag nélkül vagyis a flag use:[wall_sign] elvileg van a telken de a táblák nem mennek vele.

**Comment by andris155** [comment]
Csak a fali tábla megy alapból. A sima nem. Sőt a többféle fás sem. Megpróbálom majd újra beállítani, de legutóbb csak egyet sikerült.

**Comment by GetOut101** [comment]
A fali tábla sem ment.

**Comment by andris155** [comment]
Ja igen. Át kell majd írni a nevét. Nappal megcsinálom

**Comment by GetOut101** [comment]
Köszi.

**Comment by andris155** [comment]
A tölgyfa táblának már működnie kellene.

**Comment by andris155** [comment]
Egyelőre nem működik.
https://github.com/IntellectualSites/PlotSquared/issues/2358
Sajnos ezzel én sem tudok mit csinálni.

**Comment by andris155** [comment]
Holnaptól elvileg oak_sign-el működnie kell.
