### ISSUE TITLE
Ládából eltűnő Old eszközök

### ISSUE THREAD

**Issue by Areon1216** [andris155/TheOld-Crafters#2975]
Üdv. A mai napon eltűnt pár old cuccom. Építgettem, bányásztam majd beleraktam otthon az "Eszközök 3" ládába. Leléptem, elintéztem a ház körül pár dolgot, mire feljöttem, körülbelül ezelőtt 10 perce, addigra a ládából az amit beleraktam eltűnt.

**Comment by MrZero1** [comment]
Eltűnt, belerakta, de nem vette ki, megnéztem.

**Comment by MrZero1** [comment]
![kép](https://user-images.githubusercontent.com/29709854/59556934-8e005e80-8fcc-11e9-9bf6-a9b367b3db78.png)
Most meg rajta volt, kilépett majd vissza, és így volt rajta a szett. :question:

**Comment by andris155** [comment]
Szerintem a játék hibája lesz. De legalább meglett.

**Comment by MrZero1** [comment]
Visszaadtam neki, nem lett meg. Szóval a hiba él.

**Comment by Areon1216** [comment]
Régebben volt olyan, hogy építettem egy kvarc házat, kivettem a chestből kb 2 blocknyit, majd a szerver random újraindult, mikor visszaléptem a kezemben volt, majd visszamentem a chesthez, hogy lepakoljak és benne volt az előzőelg kivett kvarcbock. Ha ilyen történne mégegyszer, és mondjuk valaki kivesz mittudom én egy teljes old szettet, akkor akár kaphat még egy old szettet? Mert ez elég nagy nem is tudom, hibának gondolom
