### ISSUE TITLE
/iteminfo -> számszeríj

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#2976]
Meg szerettem volna nézni a számszeríj ID-jét a bolthoz. De ezt írta ki mikor beírtam hogy /iteminfo (kezemben a számszeríj)
![2019-06-16_09 58 29](https://user-images.githubusercontent.com/29951969/59561183-79988200-901d-11e9-8714-df857d7bf6fb.png)

**Comment by andris155** [comment]
Az érdekes :D

**Comment by andris155** [comment]
Mikor írtad be ezt pontosan?

**Comment by skrisz0101** [comment]
1 perccel azelőtt hogy ide megírtam

**Comment by andris155** [comment]
Letudod írni dátumra és órára pontosan mikor történt ez?

**Comment by skrisz0101** [comment]
Gépközelben talán

**Comment by andris155** [comment]
Vagy legalább azt milyen számszeríj az. Mert a simával tökéletesen működik nekem.

**Comment by andris155** [comment]
![Annotation 2019-06-18 170932](https://user-images.githubusercontent.com/8324198/59696502-65ef4600-91ec-11e9-9534-7eac32baef4d.png)

**Comment by andris155** [comment]
A fejlesztő a teljes logot kéri, amit nem fogok neki elküldeni. Nekem mindenhogy működött. Ha nem megy, akkor amit elküldtem képet ott a teljes neve. Szerintem ez nem olyan lényeges így.

**Comment by skrisz0101** [comment]
Ott a neve igen, de a táblás eladás nem megy vele :(

**Comment by andris155** [comment]
:/

**Comment by andris155** [comment]
Enchant-os vagy milyen az? Mob dobta?

**Comment by andris155** [comment]
Honnan van az a számszeríj?

**Comment by skrisz0101** [comment]
Asszem raidből

**Comment by andris155** [comment]
F3 + H-t bekapcsolva eltudod küldeni mit ír rá pontosan ha ráviszed az egeret?
