### ISSUE TITLE
Beváltó

### ISSUE THREAD

**Issue by nicolettie** [andris155/TheOld-Crafters#2977]
(survival szerver) a ./beáltó-nál szeretném javasolni az életmentés toteme helyett az elytrát, mivel a totemet már a raidekből lehet farmolni elég rendesen, viszont az elytrákat már kiszedték az endből és mobarénából sem lehet már szerezni, csak eventen, de ott meg nagyon alacsony az esélye. A szerencse bájital helyett is lehetne más item, mert az teljesen felesleges, másra is elkölthetnék a tokenjeiket a játékosok, ami hasznos is lehetne.

**Comment by andris155** [comment]
Elytra-t lehet venni OCD-ért. A bájitalos szerintem nem rossz pedig. Plusz dolog akár bekerülhetne. De nem adhatunk mindent tokenért.

**Comment by skrisz0101** [comment]
Azért egy OldElytra 1k ocd-ért.. ':D nem engedheti meg magának mindenki xd
A sima elytra pedig mindenkinek jó lenne, régebben is lehetett kapni beváltónál.

**Comment by andris155** [comment]
Néha van új end generálva olyankor lehet elytra-kat találni. Szerintem reális az OCD-s ár érte, mivel elég értékes tárgyról van szó.

**Comment by nicolettie** [comment]
Egy elytra maximum 50k-t ér survivalon. 1 ocd 1000$, azaz 1016 ocd 1millió és 16k $ :) egy elytra még 330 OCD-t is alig ér meg, max ha old és tele van rakva enchantokkal. :)

**Comment by andris155** [comment]
Levittem az árát 330-ra.

**Comment by andris155** [comment]
MrZero: ,,Most nem lesz változtatva a beváltó shopos cuccok." ,,Majd valamikor, amikor Poma is ráér"

**Comment by andris155** [comment]
Addig esetleg nyiss egy új jelentést majd ötletekkel, hogy pontosan mik is legyenek.

**Comment by MrZero1** [comment]
A beváltó shopban lévő itemeket szoktuk váltani, a jelenlegi itemek előtt volt elytra. Majd lesz megint frissítve, amikor egy új színesnevű szett lesz. Amikor a jelenlegi Legendás szett ára fele lesz, utána jön az új szett, ami hozza az új cuccokat is.:) 

Ötleteket meg bármikor, tudod :D
