### ISSUE TITLE
Mcmmo - Újrahasznosítás

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#2978]
Ha újrahasznosítok 1 tárgyat aranytömbbel, akkor kiírja hogy mennyi alapanyagot kaptam vissza, csak nem épp magyarul. Nincs lefordítva :(.
![2019-06-17_12 21 23](https://user-images.githubusercontent.com/29951969/59597680-acfd0e80-90fa-11e9-9009-08b6431a0b07.png)

**Comment by andris155** [comment]
Lefordítottam. Hamarosan bekerül majd.
