### ISSUE TITLE
/oldcore bolt al kapcsolatos furcsa bugg

### ISSUE THREAD

**Issue by Daverino111** [andris155/TheOld-Crafters#298]
Beírtam hogy /oldcore bolt minden normális volt mikor átváltottam 9 ogt 1 oldgoldblockra akkor így minden stackből elvett 9-et vagyis úgy írta hogy 55 úgye és csak egy oldgoldblockot kaptam majd mikor vissza tettem a chestbe persze vissza váltottam az oldgoldblockot mindegyik újra 64 lett

**Comment by andris155** [comment]
A falusiakkal lett megoldva a parancs helyett.
