### ISSUE TITLE
telek spawn bug

### ISSUE THREAD

**Issue by asdragon** [andris155/TheOld-Crafters#2980]
fantomok spawnolnak a telkekre
![image](https://user-images.githubusercontent.com/36716076/59624963-6cbc8100-9138-11e9-8b79-b2dfff9f0230.png)

**Comment by andris155** [comment]
Lehet a fantom már nem monster lenne (?)

**Comment by andris155** [comment]
A fantom se monster se animal a spigot alapján.
Ajánlom, hogy limitáld le az FPS-t maximum 120-ra úgy már nem nagyon esik 60 alá semmilyen helyzetben. De így csak feleslegesen terheled a géped és feleslegesen eszi a sok áramot.

**Comment by andris155** [comment]
Letiltottam a telkeken.
