### ISSUE TITLE
Eltűnő cuccok EC-ből

### ISSUE THREAD

**Issue by Kismalax** [andris155/TheOld-Crafters#2981]
Survivalon 9db enderchestem van, most azt látom, hogy a 2. teljesen üres.
Ma délelőtt 9:30-10 körül játszottam kb fél órát, akkor pakoltam a 2. ec-be, akkor még megvolt minden. Akkoriban volt szerverleállás, és időtúllépés miatti kidobás is, lehet, hogy ezeknek köze van a problémához. Elég kellemetlenül érint, mert értékes cuccokat tartottam benne...

**Comment by andris155** [comment]
Valószínűleg az összeomlás miatt történt ez. Sajnos egyelőre nem stabil a túlélő szerver.
