### ISSUE TITLE
Plázás pwarpok

### ISSUE THREAD

**Issue by Spilerr** [andris155/TheOld-Crafters#2982]
Ez eredetileg faramuci ötlete de én írom meg, Lehetne egyfajta pwarp system a plázákhoz pl én nyitok egy plázát  amit boltként használok akkor lehetne egy warp amivel a többi játékos oda tud jönni,szerintem ez egy jó ötlet,lesz ami lesz

**Comment by UDPSendToFailed** [comment]
Van ilyen funkció az AreaShop pluginban, /as settp és /as tp régiónév, csak jog kéne, hogy lehessen más boltjába teleportálni.

**Comment by andris155** [comment]
Elvileg van rá jog nem, vagy nem megy?

**Comment by skrisz0101** [comment]
máséra nem lehet menni

**Comment by andris155** [comment]
Az a probléma ezzel, hogy sokaknak van a spawn-on is régiójuk és szerintem örülnének, ha oda tp-znének a játékosok.

**Comment by skrisz0101** [comment]
Ezzel mi a probléma?

**Comment by MrZero1** [comment]
A pláza felújítása után beszéltünk erről, de csak saját bérelt régióra lehetett akkor tpzni, pedig jó lenne, ha máséra is lehetne.

**Comment by andris155** [comment]
Megadjam nekik most a jogot?

**Comment by andris155** [comment]
areashop.teleportall
