### ISSUE TITLE
Savsziget nem működő npc-k

### ISSUE THREAD

**Issue by andris155** [andris155/TheOld-Crafters#2986]
Jobb klikkel nem csinál semmit.

**Comment by poma123** [comment]
melyik andris?

**Comment by andris155** [comment]
Egyik se ment amikor néztem

**Comment by andris155** [comment]
De lehet már jó

**Comment by poma123** [comment]
sztem kompatibilitási hiba vagy nemtom de eddig jó volt :D

**Comment by poma123** [comment]
viaversion sztem

**Comment by andris155** [comment]
:/

**Comment by poma123** [comment]
Már működnek.

**Comment by andris155** [comment]
Megcsináltad, vagy azért mert frissítettem a Citizens-t?
