### ISSUE TITLE
Savsziget auto pickup

### ISSUE THREAD

**Issue by Niccolettie** [andris155/TheOld-Crafters#2987]
"highly recommended" pluginként tekintenék rá több tényező miatt is.
-kőgenerátor: hát körülbelül 10ből 4 alkalommal amikor bányászod a zúzottkövet akkor a láva elviszi, ez simán kiküszöbölhető lenne a pluginnal.
-aratás: kezdőként nem sok lehetőségem volt normális "kertet/veteményest" csinálni, kezdésnek a szigetem szélére ültettem a növényeket, amikor arattam akkor volt hogy beleesett a vízbe(savba) pl a búza, vetőmag, répa, stb.
-mobfarm: ez lehet előny és hátrány is, ha valakinek nincs mobfarmja akkor elmegy egy másik játékos pwarpjára, és ha mondjuk a hopperes-leesős mobfarmot használja akkor kicsi az esély rá, hogy a mobdropp hozzá esik, általában ugye a tölcsérbe esik a sziget tulajának. ez jó a tulajnak, hiszen farmolnak neki, az auto pickupnál ilyen már nem lenne. hát döntse el mindenki maga hogy ez negatív-e vagy pozitív.

**Comment by nicolettie** [comment]
ez csak egy demonstrálás, hogy nagyjából milyenre gondoltam, de ezt rátok bízom, ha találtok megfelelőt, akkor remélem bekerül :)
https://www.spigotmc.org/resources/autopickup.7623/

**Comment by MrZero1** [comment]
Mennyi esély van arra, hogy ilyennel duplikálni lehessen? Nem lenne jó.

**Comment by andris155** [comment]
Szerintem nem lehet vele. Több ezren használják ezt.

**Comment by MrZero1** [comment]
Ha nem lehet vele, akkor nincs akadálya, hogy bekerüljön.

**Comment by andris155** [comment]
Azért @poma123 véleménye is érdekelne. Leginkább az ő munkája a Savsziget szerver így szerintem neki kell erről dönteni.

**Comment by nicolettie** [comment]
@poma123 poma123 assigned nicolettie and poma123 5 days ago
valószínűleg ez magába foglalja a véleményét, egyébként mielőtt az ötlet kikerült volna githubra, én pomának megemlítettem és neki is tetszett az ötlet, eddig nem találtam olyat hogy addolni lehetne, de nyilván tesztelni kell, azt meg bekerülés után lehet.

**Comment by andris155** [comment]
Részemről bekerülhet

**Comment by poma123** [comment]
bekerül ha lesz rá időm :)

**Comment by poma123** [comment]
Bekerült. Ha van hiba, nyiss(atok) új jelentést.
