### ISSUE TITLE
Cserekereskedők - Nincs fordítás(hiányos)

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#2989]
Cserekereskedőt akartam létrehozni, de szinte a fele nincs lefordítva
![2019-06-20_12 48 43](https://user-images.githubusercontent.com/29951969/59844009-16c72380-935a-11e9-9d86-049423c44d98.png)
![2019-06-20_12 47 58](https://user-images.githubusercontent.com/29951969/59844014-19c21400-935a-11e9-866b-89bfc5d4a67d.png)

**Comment by nicolettie** [comment]
Segítsek @andris155 ?

**Comment by MrZero1** [comment]
Jó lenne, @nicolettie :smile:

**Comment by andris155** [comment]
Letudom fordítani, ha lesz monitorom.

**Comment by andris155** [comment]
Jól jönne a segítség a fordításban. Persze OCD-ért.
https://github.com/andris155/TheOld-Crafters/blob/master/Ford%C3%ADt%C3%A1sok/Shopkeepers/config.yml

**Comment by nicolettie** [comment]
bármikor kell fordítani akkor szólj és csinálom :) nekiállok most ennek akkor :D amint kész, küldöm e-mailben!

**Comment by nicolettie** [comment]
elküldtem! :)

**Comment by andris155** [comment]
Köszi, holnap még átnézem azért. Aztán bekerül.

**Comment by Niccolettie** [comment]
jó lett? :)

**Comment by andris155** [comment]
igen. 2032 OCD
