### ISSUE TITLE
Cserekereskedők 

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#2990]
Tegnap (csütörtökön) tettem le cserekereskedőket, állítottam nekik tradekat, nevet, minden jót. Mikor ma (pénteken) feljöttem, már nem voltak ott.

**Comment by andris155** [comment]
Visszaraktam a plugin-t. Teszt jelleggel szedtem ki.

**Comment by skrisz0101** [comment]
Falusitojásaimat visszaigényelhetem? 🙃

**Comment by andris155** [comment]
Nem vesztek el a már lerakottak.
