### ISSUE TITLE
Halászat

### ISSUE THREAD

**Issue by Banyasz12** [andris155/TheOld-Crafters#2991]
Azt tapasztaltam, hogy mikor horgászni próbáltam 1.6-os horgászat volt, nem pedig az új, fejletebb.
Lehet hogy egy plugin miatt van, lehet az mmo miatt. Így csak halat lehet fogni, nem lehet íjat, enchant könyvet stbt fogni.

**Comment by andris155** [comment]
mcMMO beállítás volt. Kikapcsoltam. Holnap már jónak kellene lennie.
