### ISSUE TITLE
Shulkerek Respawnolása egy Datapack-el

### ISSUE THREAD

**Issue by CsaliHUN** [andris155/TheOld-Crafters#2994]
Szerintem nem olyan nehezen megoldható, a neten is elég könnyen lehet találni hasonló (sőt azonos) funkciójú Datapacket.

Az End egy kissé kihalt, és a Shulkerekre sokaknak lenne szükségük.

**Comment by MrZero1** [comment]
Vagy bővítjük a világhatárt, vagy újra fogjuk generálni a Vég és Pokol világokat.

**Comment by andris155** [comment]
Datapack nem igazán van szerverre. Erre mondjuk értelmetlen is lenne, mert plugin-nal jobban meglehetne oldani. Viszont sok király dologra jó lenne, csak sajnos még egyelőre ez nem igazán terjedt el és ameddig egy csomó szerver még mindig 1.8-on fut egy jó ideig nem is fog.

**Comment by andris155** [comment]
Igazából erre nem igazán van megoldás. Csak az, hogy néha újra generáljuk az end-t és nerher-t. Esetleg növeljük a világhatárokat. De ameddig megvan a sima world világ tárhelyünk már nem igazán van sokat növelni ezeket.
