### ISSUE TITLE
Spawner ládás spawner

### ISSUE THREAD

**Issue by SurvivorTheReal** [andris155/TheOld-Crafters#2995]
A minap Bannoltboci nyitott egy mushroom_cow spawner-t a spawneres ládából, utána egy 30 perccel később már farm is volt hozzá, viszont nem spawnoltak a tehenek. Kizárólag myceliumra spawnolnak. Úgy érzem hogy az ilyen korlátozás felesleges. Normális farmot nem is lehet köré építeni így. Max olyan redstone renszerrel aminek nem örülne a szerver(szerintem).

**Comment by MrZero1** [comment]
A gombatehén amúgyis csak micéliumra spawnol, nem?

**Comment by skrisz0101** [comment]
De

**Comment by Huntermaster0** [comment]
Ez vanillában is így van, a farm hozzá meg nem nagy cucc, tripwire hook+string, az érzékeli és egy dispenser lemossa.

**Comment by MrZero1** [comment]
Akkor milyen korlátozás van?

**Comment by skrisz0101** [comment]
Nekem nem volt bajom, hunti ötletét már tegnap megépitettem

**Comment by andris155** [comment]
Ez a játék megoldása. Nem a szerver korlátozása.
