### ISSUE TITLE
TopG.org szavazás

### ISSUE THREAD

**Issue by nicolettie** [andris155/TheOld-Crafters#2996]
nem lehet szavazni ezen az oldalon, amikor beírom a játékosnevem meg az ellenörzőt kipipálom és szavaznék, ezt írja ki:
"Forbidden
You don't have permission to access this on this server."

**Comment by andris155** [comment]
![Screenshot_20190622-154038_Chrome](https://user-images.githubusercontent.com/8324198/59964693-38640e80-9504-11e9-91b9-1dcccb559138.png)
Nekem is azt írja sajnos.

**Comment by nicolettie** [comment]
már működik!
