### ISSUE TITLE
Lock

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#2998]
A [Lock] levédés mikor lesz jó? Egyszerűbb volt mindenkinek, hogy csak lekellett rakni a táblát.
(Sokan nem értik, hogy mit kell és hogyan ráírni)

**Comment by andris155** [comment]
Sajnos a levédés nem támogatja ezt így a védett területeken ezze lelehet védeni más dolgait. Nem véletlen lett ez letiltva.

**Comment by MrZero1** [comment]
Szomorú :disappointed:
