### ISSUE TITLE
[Prémium] Rang át tud változni playerekre.

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#3]
A [Prémium] rang át tud változni playerekre, pedig a minemarket leírásban csak állatok vannak, [Old]-nál vannak más játékosok.

**Comment by andris155** [comment]
Javítva:
- -libsdisguises.disguiseplayer.* jog törölve a Prémium rangtól.
- libsdisguises.disguiseplayer.* jog törölve Old rangtól.
- -libsdisguises.disguise.player jog hozzáadva a Prémium ranghoz.
- libsdisguises.disguise.player jog hozzáadva az Old ranghoz.

**Comment by embervagyok2** [comment]
ciganykurvak anyatok roman szorostalpu fasszopo fereg patkany gecik tetves fasszopo @Shryxx anyadat basszam teherbe ukran vendegmunkas @andris155
