### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by TheChaosLord** [andris155/TheOld-Crafters#300]
A szerveren lévő staffokkal több gond is van:

- nincs humorérzékük
- terrort alkalmaznak
- a tevékenységük ellentétes az 1948. 12. 10-én elfogadott Emberi Jogok Egyetemes Nyilatkozatával, azaz korlátozzák az alapvető emberi jogokat.

Ebből több komolyabb problémám is született, ezért kérném a teljes staff állomány lecserélését kompetens emberekre, továbbá a szerver szabályzatának az újragondolását.

TheChaosLord

**Comment by andris155** [comment]
A staffok terén lesz egy nagyobb változtatás is majd.
