### ISSUE TITLE
Mcmmo

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#3000]
Az mcmmo szintezés el van csesződve. 
10x-es XP kell
És az mcmmonak már vannak frissebb verziói is. 
Legfrissebb: 2.1.88
Szerón ez van: 2.1.85

**Comment by andris155** [comment]
Frissítettem

**Comment by Huntermaster0** [comment]
De még mindig 10x annyi xp kell :c

**Comment by andris155** [comment]
És mit csináljak?

**Comment by Huntermaster0** [comment]
Nem tudom, nincs rá valamilyen config beállítás? Mert így befagytak az McMMO szintek, kiszedtem 3 chunknyi követ és léptem 220ról 235re, aki már 800as szinten van az kb. szintet sem tud lépni.

**Comment by andris155** [comment]
Itt a konfig:
https://github.com/mcMMO-Dev/mcMMO/tree/master/src/main/resources

**Comment by andris155** [comment]
Én nem tudom melyik beállítással lehet állítani.

**Comment by skrisz0101** [comment]
@poma123

**Comment by poma123** [comment]
Talán ebben? Itt vannak az XP értékek lebontva skillekre vagy mikre.
https://github.com/mcMMO-Dev/mcMMO/blob/master/src/main/resources/experience.yml

**Comment by Huntermaster0** [comment]
+van egy RetroMode funkció, ami elvileg a régi rendszer, szóval ami most 800k xp az elvileg ott 80k xp lenne. Ez a config elején van
