### ISSUE TITLE
Vanillia additons - tárgyak

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#3003]
Nem lehet semmiféle vanillias itemet craftolni, de ha véletlen megpróbálnád, ír egy rövid regényt neked ajcsiba.
Próbáltam: Szén, smaricuccot. Gondolom a többi se megy.
Kép:
![2019-06-24_15 35 53](https://user-images.githubusercontent.com/29951969/60023424-126e7380-9696-11e9-96f1-b6b4e135373a.png)

**Comment by andris155** [comment]
Újraindítással menni fog.
