### ISSUE TITLE
Szelidítés probléma 1.14.3

### ISSUE THREAD

**Issue by Kismalax** [andris155/TheOld-Crafters#3005]
Úgy tűnik, hogy az 1.14.3 frissítés óta nem lehet lovakat és lámákat szelidíteni, nekem se, és falcon0607-nek sem sikerült.

**Comment by Kismalax** [comment]
Most működik. Lehet, hogy ez is MyPet probléma volt?

**Comment by andris155** [comment]
Lehetséges. Egyelőre akkor lezárom aztán, ha ismét él a hiba nyissátok újra.
