### ISSUE TITLE
Savsziget /hat parancs

### ISSUE THREAD

**Issue by geriboy09** [andris155/TheOld-Crafters#3007]
Szia Andris!
A szerveren vettem egy VIP-et amivel jár a /hat parancs és ha elkezd esni az eső és megsebzötsz akkor ami a fejeden volt item eltünik, igy jártam egy enderchesttel, válaszod elöre is köszönöm!

**Comment by poma123** [comment]
Hát azt ajánlom hogy sisakot vegyél fel a fejedre és akkor nem sebez az eső.

**Comment by geriboy09** [comment]
köszönöm ezt a bő és kedves információt és megoldását, én nem jelentek soha többet semmit :)
