### ISSUE TITLE
Savsziget rangok

### ISSUE THREAD

**Issue by Niccolettie** [andris155/TheOld-Crafters#3008]
Tudom, hogy leginkább @poma123 munkája a szavsziget, ahogy múltkor említve lett az auto pickup plugin ötlet alatt, de azért ide githubra is kiírom ötletnek.
Javasolnám, hogy valaki legyen a Savsziget Vágó Istvánja, és mint a Legyen Ön is milliomos!-ban, használja el a "felezés" segítséget a savsziget rangokra.
Az az igazság, hogy szerettem volna venni rangot amiben god és főleg fly van, ami jelenleg az old (amiben fly is van, god elittől is van), viszont semmi olyan jelentős plusz dolgot nem ad ezeken kívül amiért megérné venni.
Nem ugyan az a kettő igaz, de a survivalhoz hasonlítva sokkal kevesebb előnyt adnak a savszigetes rangok, így mint játékos/vásárló jobban esne a májamnak ha fele annyiba kerülne az OLD rang, és valószínű kapósabb is lenne (lásd survivalon néha 10 OLD játékos is van fent egyszerre, míg savszigeten heti egyszer látni OLD rangost). 
Ha bátrabban lehet javasolni, akkor akár azt is mondanám hogy a 4 rangból simán lehetne 3 rangot csinálni, mert olyan kevés plusz jog van:
vip-nek 10, elitnek 5, prémiumnak 6, oldnak 9 - ehhez képest survivalon 15-20 jogot tartalmaz egy rang, azért ez jelentős különbség, főleg ebből "szúrja a szemem", hogy az áruk viszont megegyezik. :(

**Comment by Niccolettie** [comment]
@poma123

**Comment by poma123** [comment]
ezt nem én döntöm el egyedül, és nem is fogom, meg kell beszélni staffokkal közösen hogy hogy legyen aztán andrisnak kell minemarketen módosítani a rangokat (egyébként nélkülem is meg lehet oldani, nem csak én tudok rangokhoz jogot adni na mindegy).

**Comment by MrZero1** [comment]
Hamarosan. :)

**Comment by andris155** [comment]
Szerintem nem rossz dolog, hogy több rang van, mert legalább mindenki jobban eltudja dönteni milyen jogok is kellenek neki. + később bővülhetnek a jogok.
Az Old pedig nem lesz olcsóbb.
