### ISSUE TITLE
Survival Tábla hiba

### ISSUE THREAD

**Issue by falcon0607** [andris155/TheOld-Crafters#3010]
Nem lehet survivalban táblára írni. Ha megpróbálom ezt írja ki a console: 
![image](https://user-images.githubusercontent.com/40804615/60189111-b429c800-9830-11e9-98b7-43a67e5f0350.png)

**Comment by MrZero1** [comment]
![kép](https://user-images.githubusercontent.com/29709854/60201665-1abae000-9849-11e9-966b-67b1559104c1.png)

Nem táblázik Mokito, de mégis kiírta, többször is

**Comment by andris155** [comment]
Javítva
