### ISSUE TITLE
Survival bányászat

### ISSUE THREAD

**Issue by Huntermaster0** [andris155/TheOld-Crafters#3012]
Survin már a 20 tps sem 20 tps, resi után mikor még egyedül voltam bányásztam kb. fél percig, a kiszedett kövekből volt amit visszarakott. Most 15en vagyunk fent, ugyanúgy rakja vissza, idegesítő. Más is érzékelte, szerintem nem a netemmel van baj. 1.14.2ben még jó volt.

**Comment by MrZero1** [comment]
![kép](https://user-images.githubusercontent.com/29709854/60200851-3b823600-9847-11e9-9f59-95879e4309a8.png)

Nem tudom, köze van e hozzá, de ezt jelzi.

**Comment by andris155** [comment]
Most jó?

**Comment by Huntermaster0** [comment]
Nálam még visszarakja

**Comment by andris155** [comment]
És most?

**Comment by Huntermaster0** [comment]
Mintha kevesebbszer, de még visszarakja.

**Comment by Huntermaster0** [comment]
+Ezt sem csak én tapasztalom, visszadobál a szerveren és beakad. Megyek oldalra és megakaszt a rendszer, csak rezeg és nem mozdul a karakter.

**Comment by andris155** [comment]
Azt tudom, hogy visszadob néha. Szerintem valami memória hibás és, amikor betelik a RAM akkor dobál vissza.

**Comment by andris155** [comment]
A bányászás azóta sem jobb?

**Comment by Huntermaster0** [comment]
Hát már az első percekben is visszadobott, ami úgy elég érdekes. Máris megnézem, hogy jobb-e azóta.

**Comment by Huntermaster0** [comment]
Megnéztem. Nem lett jobb, visszamegy a kő.

**Comment by Areon1216** [comment]
Én is tapasztaltam, elég sokszor. Megyek valamerre gm1-ben, beakad, rezeg a kép mint egy epilepsziás gyerek, aztán visszaugrik. Blockok eltűnnek stb...

**Comment by andris155** [comment]
Javítva
