### ISSUE TITLE
Róka pet

### ISSUE THREAD

**Issue by Huntermaster0** [andris155/TheOld-Crafters#3013]
Eltűnik az item a róka szájából, ha befogom petnek.

**Comment by MrZero1** [comment]
Ami szerintem annyira nem nagy baj :D

**Comment by EHzy001** [comment]
Ha véletlenül felveszi az OLD kardot, akkor van egy kis gond :'D

**Comment by MrZero1** [comment]
Akkor dobj neki mást mielőtt befognád, és ne úgy fogd be petnek, hogy oldkard van a szájában 😃
