### ISSUE TITLE
Savsziget pionír küldetés

### ISSUE THREAD

**Issue by Niccolettie** [andris155/TheOld-Crafters#3017]
nem engedi teljesíteni a küldetést, pedig itt a map a kezemben, miért van ez?
![2019-06-27_12 32 57](https://user-images.githubusercontent.com/48986609/60259518-b8f58700-98d7-11e9-9709-cd0d668cc1f4.png)

**Comment by andris155** [comment]
@poma123

**Comment by Niccolettie** [comment]
Pandikusz segített, sima térkép kell hozzá, nem kell használni, csak félrevezetően van írva
