### ISSUE TITLE
Re: Re: Error 404

### ISSUE THREAD

**Issue by TheChaosLord** [andris155/TheOld-Crafters#302]
Lehet, hogy lesznek, ám ez még nem nyújt teljes megoldást.

Ami még probléma az a szerver jogsértő módon való működése, amely miatt súlyos problémáim keletkeztek. Azon kéne nagyrészt változtatni. Ha magatoktól nem vagytok képesek elkészíteni, majd megcsinálom én. 

Azonban a korábban jelzett problémákból adódó kellemetlenségeimért valamilyen szintű kártérítést nem ártana adni. Mármint azokra, aminél egyértelműen lehet bizonyítani, hogy a staff volt  hibás, mint pl. a legutólsó esetben.

The Chaos Lord

**Comment by andris155** [comment]
Ha letudod írni mely esetekben volt hibás a staff, és melyik staff akkor tudok ez ellen csak tenni.
