### ISSUE TITLE
Ideiglenesen nincs MyPet

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#3022]
teszt miatt?

**Comment by andris155** [comment]
Elvileg az okozta a memória hibát is. Egyelőre nem lesz bent egy ideig ha ez igaz.

**Comment by skrisz0101** [comment]
:(

**Comment by SurvivorTheReal** [comment]
A fenébe, rip wither pet xd

**Comment by andris155** [comment]
Nem lesz többé szerintem MyPet.
