### ISSUE TITLE
pinata bug

### ISSUE THREAD

**Issue by Niccolettie** [andris155/TheOld-Crafters#3023]
A spawnon mutatja ezt a csillogós effektet és kiírja hogy 50 ütés van hátra, viszont nincs lespawnolva pinata
![2019-07-01_19 21 35](https://user-images.githubusercontent.com/48986609/60454954-8203d600-9c35-11e9-9d1a-b5377867531f.png)

**Comment by poma123** [comment]
Elvileg jó, nyiss újat ha legközelebb nem lesz jó

**Comment by poma123** [comment]
Próbálok rájönni miért van ez :(

**Comment by andris155** [comment]
A fejlesztőnek nem tudsz írni ezzel kapcsolatban? Kicsit fura lenne, ha én írnék, mert te vetted meg ezt. :D

**Comment by poma123** [comment]
Szerintem azzal lesz a probléma, hogy a spawnon le van tiltva az állatok spawnolása, bár csináltam neki egy külön régiót oda de úgy tűnik mégsem akarja lespawnolni

**Comment by poma123** [comment]
elvileg most már jó lesz, nyissatok új jelentést ha nem, és akkor ezt újranyitom

**Comment by poma123** [comment]
Nem jó, akkor lenne jó ha nem töltene ki a chunk

**Comment by andris155** [comment]
Nem tölt ki. Folyamatosan a memóriában van.

**Comment by poma123** [comment]
mégis csak akkor spawnol le ha vannak ott játékosok

**Comment by andris155** [comment]
Sok dolog változott a chunk-okkal kapcsolatban. Ez szerintem egyértelműen plugin hiba.

**Comment by andris155** [comment]
Nem is írt vissza azóta sem a fejlesztő. Sajnos ezzel így nem tudok mit csinálni.
