### ISSUE TITLE
Szomjúság

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#3024]
Be lehetne vezetni a szomjúságot, mint ami annó volt hardcoreX-en, kis nehezítés :D
(ezzel együtt a sörfőzés (?)) Szerintem jót tesz a változatosság.

**Comment by MrZero1** [comment]
Survival vagy Savsziget?

**Comment by skrisz0101** [comment]
Survin

**Comment by skrisz0101** [comment]
Mondjuk sztem savon se ártana

**Comment by andris155** [comment]
A plugin jól működik és nem eszik sok erőforrást sem. Illetve frissítik is rendszeresen. Szóval részemről bekerülhet.

**Comment by poma123** [comment]
felolem is :)

**Comment by andris155** [comment]
És MrZero szerint?

**Comment by MrZero1** [comment]
MrZero szerint is, aki szerint Savra is jó lenne, de Sweetan szerint nem kell oda (hajonki pedig nem lenne rossz, meginni a savasvizet biztos fincsi) :potable_water:

**Comment by poma123** [comment]
andris beteszed?

**Comment by MrZero1** [comment]
Ja, az a plugin, ami savon van, sörfőzés, az survira nem akarom, szóval önmagában a szomjúság jöhet.

**Comment by andris155** [comment]
Mivel legyen kiíratva a szomjúság? Legyen hozzá olyan oldalsáv mint a Hardcore-n volt?

**Comment by skrisz0101** [comment]
Milyen módok vannak rá?

**Comment by andris155** [comment]
Bossbar vagy scoreboard

**Comment by andris155** [comment]
vagy actionbar

**Comment by skrisz0101** [comment]
sztem scoreboard

**Comment by skrisz0101** [comment]
Az az actionbar az milyen?

**Comment by andris155** [comment]
![af4c50a9a55aa729a0ffd53216ca0a07936a30f7](https://user-images.githubusercontent.com/8324198/60544620-712c9080-9d19-11e9-9bd0-55b1f435ee63.gif)
ilyesmi csak nem ezzel a szöveggel.

**Comment by skrisz0101** [comment]
Szerintem jó a scoreboard

**Comment by poma123** [comment]
inkább legyen bossbar vagy actionbar

**Comment by andris155** [comment]
A bossbar az mcMMO-hoz van már használva. Az action bar szerintem idegesítő. Szóval én inkább a scoreboard-ra szavaznék.

**Comment by poma123** [comment]
annyi bossbart lehet csinalni amennyit akarsz, a scoreboard is hasznalva van ennyi erolvel az mcmmo-hoz meg az auto eventeknel is

**Comment by poma123** [comment]
nem  csak egy bossbar lehet

**Comment by MrZero1** [comment]
scoreboard szerintem zavaróan felesleges ennyihez

**Comment by andris155** [comment]
Én így ennek nem látom értelmét. Ez mindenhogy zavaró akárhová is rakom.

**Comment by skrisz0101** [comment]
😐😐😐

**Comment by poma123** [comment]
XD nehogy már azért ne legyen mert zavaró xddd

**Comment by MrZero1** [comment]
Bossbar miért nem jó?

**Comment by andris155** [comment]
Szerintem az is zavaró.

**Comment by skrisz0101** [comment]
Mi lenne ha be lenne téve tesztként, és meg lenne kérdezve hogy kit zavar? :) 🙂🙂🙂🙂🙂🙂🙂🙂

**Comment by Huntermaster0** [comment]
Ha ez szavatnak számít én az ActionBar-ra szavazok. Ott a legkisebb a felület, amit kitakar.

**Comment by andris155** [comment]
Legyen róla szavazás a csoportban. Ne pár ember döntse ezt el szerintem.

**Comment by andris155** [comment]
Illetve akárhogy is lesz, úgy kell megoldanunk, hogy kikapcsolható legyen, mert kreatívban nagyon felesleges és zavaró.

**Comment by MrZero1** [comment]
Szerintem az actionbar legyen, aztán akit zavar, kikapcsolhatja.

**Comment by skrisz0101** [comment]
Max szomjanhal xd

**Comment by poma123** [comment]
https://www.facebook.com/groups/theoldc/permalink/2844027752336144/

**Comment by poma123** [comment]
na akkor ezzel mi lesz?

**Comment by skrisz0101** [comment]
Meg lett szavaz a :v

**Comment by andris155** [comment]
Sajnos az ActionBar csak üzenetekre van mint rájöttem a plugin-ban. Normálisan csak scoreboard-al látható mindig.

**Comment by skrisz0101** [comment]
jó az úgy is, oldvillagen se zavaró a város kiírása meg +indók, pedig az 10x nagyobb

**Comment by poma123** [comment]
jó a scoreboard kesz

**Comment by andris155** [comment]
De akkor meg az eventen fog bugolni nem?

**Comment by MrZero1** [comment]
Jó szerintem hanyagoljuk, ne legyen és kész.

**Comment by andris155** [comment]
Szerintem se legyen így inkább. Lehet a jövőben bekerül a játékba is remélhetőleg normálisan.

**Comment by MrZero1** [comment]
Csak kínlódás van vele.

**Comment by mr00000** [comment]
pisi kaka pisi kaka
