### ISSUE TITLE
Pluginjavaslat - Erősebb mobok

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#3025]
Survival szerver. Ami volt plugin HardcoreX-en (MythicMobs), lehetne Survivalon a vadon(ok)ban. 
Volt egy szavazás a játékoscsoportban, ott elég magas arányban akarták ezt, aztán nem lett belőle semmi (aztán jött a szuperjó 1.14).

Nyilván dobnának valamit, akár pénzt, akár itemet, nemtudom mit. 

Na most azt nem tudom, 1.14-re van e, valamint van e rá igény. Aki látja, írja le.

**Comment by skrisz0101** [comment]
+1

**Comment by MrZero1** [comment]
Nyilván az elsődleges szempont az, hogy ne használjon sok erőforrást, mert ha így van, akkor felejtős (survira legalábbis)

**Comment by andris155** [comment]
Van 1.14-re

**Comment by poma123** [comment]
viszont en nem tartok igenyt a bekonfigolasara 😢

**Comment by andris155** [comment]
Én sem, mert nagyon túlélőztem és így nem is tudnám reálisan beállítani.
