### ISSUE TITLE
1v1

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#3027]
Információban ki van írva, minigame menüben is ott van, de a plugin nincs bent.

![kép](https://user-images.githubusercontent.com/16057404/60584647-0d907a80-9d8e-11e9-95cf-3a28994448ca.png)

**Comment by MrZero1** [comment]
Mivel ami volt, nincs 1.14-re.

**Comment by andris155** [comment]
Van, csak a tábla kezelője laggos. De már nagyon rég jelentettem a fejlesztőnek.
