### ISSUE TITLE
Tag+ - Pet befogás

### ISSUE THREAD

**Issue by Tarifnya** [andris155/TheOld-Crafters#3028]
tag+ 2 pettel rendelkezhet    de csak 1 petet enged pefogni a játék

**Comment by poma123** [comment]
egyelőre bent sincs a mypet

**Comment by Niccolettie** [comment]
pár napja bent volt :O

**Comment by andris155** [comment]
Tesztelve volt, mivel a fejlesztő megpróbálta javítani. De sajnos továbbra sem lett jó.

**Comment by andris155** [comment]
Egyet el kell raktározni, és csak úgy tudsz még pluszban 1-et. Ha újra lesz MyPet és így sem működik kérlek nyiss majd új jelentést. Vagy írj ide.
