### ISSUE TITLE
 A   /bind  command

### ISSUE THREAD

**Issue by Tarifnya** [andris155/TheOld-Crafters#3029]
mit szólnátok ahoz ha  a szerveren lenne /bind add ... command? :D szerintem hasznos lenne
gyorsabb lenne a rangosoknak is és tagoknak  is beírni bizonyos dolgokat és sokak életét könnyítené
gyorsabbá tenné a home-okra való közlekedést  stb stb
hasznos tudna lenni

**Comment by SurvivorTheReal** [comment]
támogatom

**Comment by poma123** [comment]
Ezt csak slot-hoz lehetne hozzárendelni, billentyűparancs-ot nem küld ki a kliens a szerver felé ilyen módon. (Tehát úgy nem lehet megcsinálni, mint a macro modot). Az meg másik kérdés hogy hogyan legyen az adott parancs aktiválva mikor kijelöli valaki a hotbar-on a slotot.

**Comment by andris155** [comment]
Használjatok erre valamiféle mod-ot. Szerintem a parancsokat nem nehéz beírni főleg, hogy sokat ki lehet tab-al írni.
