### ISSUE TITLE
AutoPickup - savsziget

### ISSUE THREAD

**Issue by Icecroft** [andris155/TheOld-Crafters#3030]
- [x] autoenable jog elvétele
- [x] betétele [informacio]-ba

[Original issue by Icecroft starts here:]
- Az autopickup megakadályozza az önjavítós tárgyak "gyógyulását", hiába töröm az érceket.
- **Ha tele az inventory a tárgyak nem kerülnek többé a földre, hanem egyszerűen elvesznek. Ez az egyik legidegesítőbb tulajdonsága!**
Íjászkodva észre sem veszem, de tele lesz az invem minden szeméttel, amit nem is akartam felvenni.
- horgászatnál nem látom mit fogtam (ez érdekel a legkevésbé)

[end of the original issue]

**Comment by andris155** [comment]
Mi értelme ennek, ha úgyis mindenki kikapcsolja?

**Comment by Niccolettie** [comment]
honnan veszed ezt Andris?
nem kapcsolja ki mindenki.

**Comment by poma123** [comment]
az kapcsolja ki akit zavar, akit nem zavar használja. mcmmo scoreboardnak mi értelme ha mindenki nem hagyja bekapcsolva? petbefogónak mi értelme ha nincs mindig bekapcsolva tartva? partychat togglenak mi értelme ha nincs mindig partychatre állítva a chat? ezt napokig sorolhatom ha kell :)

**Comment by andris155** [comment]
De akkor inkább legyen úgy, hogy alapból ki legyen kapcsolva, és aki szeretné bekapcsolja magának.

**Comment by Icecroft** [comment]
Köszi az infót! Lehet érdemes lenne betenni a rendszeresen megjelenő infók közé.

**Comment by poma123** [comment]
A jog elv már jó, ha relogolsz bekapcsolva van, @Icecroft ?

**Comment by poma123** [comment]
kész
