### ISSUE TITLE
savsziget eventek

### ISSUE THREAD

**Issue by Niccolettie** [andris155/TheOld-Crafters#3031]
Pár eventet be lehetne rakni savszigetre is, ami survin is van, mert ez a 7 napi event nagyon kevés :(
![2019-07-06_11 42 32](https://user-images.githubusercontent.com/48986609/60754564-2ba2e880-9fe3-11e9-81b8-3208396d3c20.png)

**Comment by MrZero1** [comment]
Amíg nincs FAWE Survivalon, nem tudunk onnan átvinni könnyedén eventeket. Van pár, ami nem került még be savon, majd bekerülnek, valamint lesznek továbbiak is.

**Comment by andris155** [comment]
Szerintem a kimásolás így is működik. A fájlokat meg át tudom másolni.
