### ISSUE TITLE
Survival Spawn - pvp akármi bug 

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#3033]
![kép](https://user-images.githubusercontent.com/29709854/60772880-e2df5280-a0fc-11e9-95b5-994cdce47ef1.png)

**Comment by poma123** [comment]
AdditionsAPI hiba lesz (i think)
/*mindig enderbow hibát ír a konzol szoktam látni*/

**Comment by andris155** [comment]
A combatlogx hibája. Azt a hibát nem írja egy ideje.

**Comment by andris155** [comment]
Most is működik. Esetleg videót tudtok róla csinálni, ha igen?

**Comment by andris155** [comment]
nyissatok új jelentést, ha még él a hiba.
