### ISSUE TITLE
Ép+ robbanó ágy

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#3035]
Építész+-on az end biomot letiltani a ploton, mivel ott is robban az ágy (a nether tiltva van)

**Comment by andris155** [comment]
le lett tesztelve?

**Comment by MrZero1** [comment]
Egyik játékos jelezte

**Comment by poma123** [comment]
robban, de nem rombol blokkokat

**Comment by poma123** [comment]
nekem nem robban

**Comment by andris155** [comment]
Én is úgy tudtam, hogy void-al nem robban, ezért is nem tiltottam le eddig.
