### ISSUE TITLE
Nem működő lectern védelem PlotSquared és GriefPrevention

### ISSUE THREAD

**Issue by Huntermaster0** [andris155/TheOld-Crafters#3036]
A lectern egyik funkcióját akartam használni a szerveren, írni egy könyvet, majd azt kirakni a pwarpomra egy lecternbe. Mikor teszteltem, kiderült, hogy telken és levédésen is simán ki tudják venni a könyvet, visszatenni már nem. Szóval ha arra akarom használni, amire van (úgy kirakni egy írást, hogy az bárki által elolvasható legyen, de mégis védett mindenféle trollkodástól), akkor azt nem tudom megtenni.

**Comment by andris155** [comment]
Rakd ki tárgykeretbe a könyvet és úgy jobb klikkel eltudják olvasni.

**Comment by Huntermaster0** [comment]
Nem tudják, ahogy nézem ez a funkció nem megy. Terület tulajaként még én sem tudom.

**Comment by andris155** [comment]
A Griefprevention-nal kapcsolatban már jelentették a hibát: https://github.com/TechFortress/GriefPrevention/issues/537

**Comment by andris155** [comment]
Telken alapból is kitudják szedni, vagy csak, akkor ha adsz rá jogot a use flag-al, hogy tudják használni?

**Comment by Huntermaster0** [comment]
Csak use flaggel

**Comment by andris155** [comment]
Megírtam a PlotSquared-nek is.

**Comment by andris155** [comment]
letudod tesztelni újra a ploton?
