### ISSUE TITLE
Savsziget: Mcmmo Horgászat hiba

### ISSUE THREAD

**Issue by Icecroft** [andris155/TheOld-Crafters#3038]
A savszigeten amióta az új "retro" mcmmo van, a horgászat gyakorlatilag nem működik:
- a kifogott tárgyak teljesen megegyeznek az mcmmo nélküli horgászattal, hiába 525 a szintem
 (lásd screenshotok)
- amikor közli, hogy valami mágikus a kapással, akkor semmit sem kapok
- az mcmmo adta előnyök sem működnek: pl mesterhorgászat semmivel sem jobb, mint a partról vagy mcmmo nélkül.
- a horgászat során szerzett mcmmo xp-t összvissza számolja, van amikor sokáig semmi, majd egy fogás után akár 3 szintet is ugrik.
![2019-07-08_22 24 26](https://user-images.githubusercontent.com/19332825/60840866-b72d9c80-a1d0-11e9-958f-81cde7a4ad08.png)
![2019-07-08_22 25 16](https://user-images.githubusercontent.com/19332825/60840867-b72d9c80-a1d0-11e9-9aaf-ae21e32c6d6e.png)

**Comment by andris155** [comment]
Most sem jó?

**Comment by Icecroft** [comment]
Szia Andris, nem javult, hanem romlott a helyzet, már csak halat lehet fogni. Épp elkaptam egy screenshottal, ahogy kiírja: "valami mágikusat...", (még halványan látszódik), de valójában semmit sem kaptam:
![2019-07-10_12 57 14](https://user-images.githubusercontent.com/19332825/60964129-d5031a80-a312-11e9-82dd-dbdec25c0076.png)

**Comment by andris155** [comment]
A jelenlegi mcMMO verzióval sem működik? Illetve a túlélőn sem jó?

**Comment by Icecroft** [comment]
Szia Andris, a savszigeten tegnap este próbáltam, rendben működik az mcmmo horgászat. A túlélőn nem teszteltem még, de ott most az új "retro" miatt elég alacsony a szintem, gyakorlatilag csak halat fognék.
Szerintem jó lesz így.

**Comment by andris155** [comment]
köszi

**Comment by andris155** [comment]
508 OCD
