### ISSUE TITLE
lákiblokkkk

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#3040]
ha kidobom az invemből a lákiblokkkkot, majd valaki felveszi, akkor sima játékos drop-os fej lesz
![2019-07-09_13 57 50](https://user-images.githubusercontent.com/29951969/60886186-95c0c500-a251-11e9-8b0a-80780044ea0a.png)
Tamas1432 vett tőlem 4 luckyblockot (frissen craftolt), majd utána egyből nekem dobta, és ilyen lett. Amikor még nála volt, akkor még sima luckyblock volt, a ládában is sima luckyblock van. de ha eldobja és valaki felveszi, ilyen lesz. 
Minemarkete nevem skrisz01, köszönöm

**Comment by poma123** [comment]
@andris155

**Comment by MrZero1** [comment]
Ilyen, ha a luckyblockot elmossa a víz. Nincs baja, lehet használni ugyanúgy

**Comment by andris155** [comment]
elvileg javítva.
