### ISSUE TITLE
Ötlet - OldVillage

### ISSUE THREAD

**Issue by poma123** [andris155/TheOld-Crafters#3044]
Állatok elraktározása ( esetleg egy vödörbe ) és így könnyebb elszállítani
Ötlet by: KingDead

**Comment by andris155** [comment]
Biztosan jó ötlet ez? Szerintem ez eléggé rombolja már a játékmenetet.

**Comment by poma123** [comment]
nem vödörbe lett, hanem mob befogó van 5ös szinttől egy hógolyóval lehet befogni és kidobja a tojást. 100$-ba kerül egy befogó és 20-at levon a befogáskor is
