### ISSUE TITLE
Survival itemek pozíciója

### ISSUE THREAD

**Issue by Huntermaster0** [andris155/TheOld-Crafters#3045]
Survin már egy ideje bugos a kiütött itemek helyzete, kiütés/leesés után elég gyakran teleportálnak (vagy nem tudom hogy mondjam) az itemek. A videón is látszik, hogy miután leesnek az itemek, egy idő után némelyik visszamegy fentre. Ez elég idegesítő, tönkrevág egy csomó szerkezetet, de simán survivalban is megesik, hogy próbálom felvenni, csak nem megy, mert közben máshol van.

https://youtu.be/t7N4IlLqJ3A

**Comment by andris155** [comment]
Optimalizáció miatt egybe próbálja őket rakni a lehető legjobban a tárgy 6 blokkos körzetében.
