### ISSUE TITLE
Ötletek és hibák - OldVillage

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#3048]
Minden általam talált hibát, általam kitalált ötletet ide írok/fogok írni később konnentben

1. [ötlet] mikor egy játékos beregisztrál a szerverre, szerintem dobja a kép elé 20-25mp-ig, addig ne tudjon mozogni. Mindenkinek az az első kérdése hogy mit kell csinálni, sztem hasznos lenne.

2. [ötlet] spawn kezdőpontjához közelében egy hely, ami pár alap információt ad, pl /warp bánya, /parancsok idomítás, bármi.
Esetleg egy helyiség ahol nyomólappal el lehet jutni a warpokra (kis leírással), kiíratni a parancsokat, amik segíthetnek + magyarázat. (egy központból lehetne tpzni mindenhova)
 
3. [hiba] a metróból csomószor ki lehet bugolni a föld alá
 
4. [javaslat] Szerintem lehetne nagyobb távok is a metróval, mert így kicsit felesleges. Tényleg jó dolog, ötletes meg minden, csak picit kicsik a távoj (távoj) sztem.
 
5. [ötlet] Mcmmo (?)
 
6. [Ötlet] A Városok nevei, esetleg lehetnének (a chaten) szürke []-k között, és utána lenne a játékosok nevei. Kb mint szurvin a rang. Lehet úgy szebb lenne a CHAT, átláthatóbb
 
7. [Hiba/Ötlet/Javaslat] a /town spawn csak vadonban elérhető, mért? : ( még netherben se lehet használni, pedig sztem jó lenne, főleg mikro csak 1 homed lehet xd

Hirtelen ennyi, majd editelem ha jobban körbenézek.

**Comment by skrisz0101** [comment]
@poma123

**Comment by poma123** [comment]
**1. - közelebb tettem, és szembe a spawn pontot.**
**2. - erre lesz egy [információ] [customtext] meg [warp] tábla fal**
3. - ezzel nem nagyon lehet kezdeni valamit :(
4. - egyelőre nincs hova menjen a metró xd
5. - nem
**6. - nem rossz ötlet**

**Comment by poma123** [comment]
+ az sfes részt töröltem xd

**Comment by poma123** [comment]
[Ötlet] Vásárcsarnokban szerintem jó lenne egy End részleg, ha már van nether is :v 
Esetleg egy víz részleg 
Esetleg nagyobb növény választék (?) :c

**Comment by poma123** [comment]
[Ötlet] Trade plugin, ami régen volt szurvin. (csak itemekkel)

**Comment by skrisz0101** [comment]
Városon bellül ki lehet kapcsolni a PVP-t, szerintem így elég nehéz elfoglalni egy várost ':D
Ezt a funkciót nem lehetne kinyomni? mert így kb nincs is értelme ennek. köszpusz

**Comment by poma123** [comment]
> Városon bellül ki lehet kapcsolni a PVP-t, szerintem így elég nehéz elfoglalni egy várost ':D
> Ezt a funkciót nem lehetne kinyomni? mert így kb nincs is értelme ennek. köszpusz

ha a település határán belül van kívülálló nem lehet állítani a pvp-t

**Comment by Kismalax** [comment]
[hiba] Nem lehet megenni a répát OldVillage szerón.

**Comment by poma123** [comment]
> [hiba] Nem lehet megenni a répát OldVillage szerón.

tudnál kicsit több infóval szolgálni? melyik világban, városon kívül/belül, hányas szinten stb.?

**Comment by Kismalax** [comment]
> tudnál kicsit több infóval szolgálni? melyik világban, városon kívül/belül, hányas szinten stb.?

Nem sikerült rájönnöm, hogy mitől függ, loot világban, és vadonban is előfordul, hogy nem lehet megenni, a húst pedig mindig meg lehet enni. Most kipróbáltam, ide-oda tpzés után ugyan azon a helyen egyszer engedi, máskor meg nem. Városon kívül, 17-es szinten vagyok.

**Comment by poma123** [comment]
Meg fogom nezni. Kerlek tovabbi otleteket hibakat kulon jelentesbe irjatok
koszi
