### ISSUE TITLE
Mending enchant nem javul, OldVillage 

### ISSUE THREAD

**Issue by KingDeadZ** [andris155/TheOld-Crafters#3052]
Ha mendinges csákánnyal szeded ki az ércet/ölsz meg mobot, nem javul. Ugyanez kardra, az eszközökre kivéve horgászbot.

Config alapján ezt a 2 dolgot kéne kikapcsolni:

Auto Block XP

Mob.Auto XP

Ha Savszigeten is be vannak kapcsolva, akkor ott is ki lehetne kapcsolni.

Csak XP orbból javít a mending, de instant megkapjuk az xpt, így nem javít semmit.

**Comment by poma123** [comment]
kész
