### ISSUE TITLE
OldVillage szavazási ötlet

### ISSUE THREAD

**Issue by KingDeadZ** [andris155/TheOld-Crafters#3054]
Minden 25 vagy 50 szavazat után kapna mindenki, aki nagyobb mint 5-ös szintű egy véletlenszerű kulcsot.

**Comment by MrZero1** [comment]
Én max. szavazati pontért raknék be ládakulcsot, a meglévő ládák mellé

**Comment by poma123** [comment]
Szavazatpontert van ladakulcs
