### ISSUE TITLE
Ötlet - OldVillage

### ISSUE THREAD

**Issue by KingDeadZ** [andris155/TheOld-Crafters#3056]
Egy olyan plugin, amivel hogyha jobbclickelünk a növényre akkor nem esik ki a növény, csak leszedi.

**Comment by MrZero1** [comment]
Nagyon megkönnyítené a farmokat szerintem

**Comment by poma123** [comment]
ilyen nem lesz. lesz amúgy növényidomítás azzal lehet gyorsítani a növést
