### ISSUE TITLE
Kitörlődött az enderchestem :)

### ISSUE THREAD

**Issue by Huntermaster0** [andris155/TheOld-Crafters#3057]
A Survival szerveren Old cuccokkal, színes nevű+régi itemekkel, spawner tojásokkal együtt eltűnt az egész 11. enderládám. Ezt valahogy mentésből vagy nem tudom honnan vissza lehetne szedni? Csak az értékes cuccaim tartom enderláda, bár ezután szerintem inkább nem használom erre csak az 1.-t.

**Comment by MrZero1** [comment]
@andris155

**Comment by andris155** [comment]
Írj a szerver weboldalon ezzel kapcsolatban.

**Comment by Huntermaster0** [comment]
Írtam.
