### ISSUE TITLE
Kérdések

### ISSUE THREAD

**Issue by TheChaosLord** [andris155/TheOld-Crafters#306]
Volna pár kérdésem a szerver működésével kapcsolatban:

1. A szerver szabályzata mióta mond ellent az ENSZ által elfogadott Alapvető Emberi Jogok Nyilatkozatának és az Alaptörvénynek is?

2. Mióta kap ip bant egy olyan személy, aki nem szegett meg egyetlen szabályt sem?

Várom a válaszokat.

The Chaos Lord

**Comment by andris155** [comment]
1. Nem tudom melyik szabállyal van bajod, de ez egy játék akinek nem tetszik a  szabályzat nem jön fel.

2. Szerintem közel több mint jó ok az ip banra, hogy állításod szerint simán meghackelted a tulaj gépét, és hozzáférsz teljesen.

**Comment by TheChaosLord** [comment]
1. Nem nekem van bajom a szabályokkal. Hanem a törvénynek. 
 Nézzük csak az alábbi szabályt: 
1.13, Ne irkálj idegen nyelven! [angolul pár [nem trágár] szó, mondat belefér]
Ez egyértelműen korlátozza a szólásszabadságot, ami alapvető emberi jog. Itt nem számít, hogy játék-e vagy sem. A törvény mindenhol érvényes. Ha nem tetszik, akkor ne jöjjön fel? Ez milyen hozzáállás? Ha nem tetszik egy törvény, akkor ne tartsam be? Ezzel ugyanis ezt az álláspontot képviseled. Tudod, hogy a szerver szabályzata törvényellenes, de ezt ignorálod.

2. Soha nem állítottam ilyet. Ha olvastad volna a chatet, amit ezek szerint nem tettél, valószínűsíthetően  csak átpörgetted, így vonva le téves következtetéseket. 
    2.1 Amit én mondtam először az csupán annyi volt, hogy az előzmények mást mutatnak.
    2.2 Utána minden olyan kérdésre, amivel azt szeretted volna megtudni, honnét tudom ezt, kitérő     választ adtam.
   2.3 Továbbá még csak utalás szintjén sem jelent meg a mondataimban, hogy bármilyen mértékben hozzáférnék a géphez.
   2.4 Ülj le és gondolkozz el egy picit. Ha nem jössz rá, miért kéne, segítek benne.

**Comment by andris155** [comment]
1. Jó lenne ha a többi szabályt is leírnád, amikkel ilyen gondok vannak.
2. ??

**Comment by TheChaosLord** [comment]
1. Ahhoz akkor átnézem a szabálykönyvet. Teljesen.

2. A józan eszedet kéne használnod. Tegyük fel, hogy A. bejut B. gépébe. Akkor miért lenne annyira hülye, hogy egy halom ember előtt ezt elmondja B.-nek? Egyszerűen nincs értelme. Tehát ha bárki ilyesmit mond, nyilván szórakozik. Erre kellett volna rájönnöd. Jó, lehet kicsit túlszaladtam, de ha valaki gondolkodott volna egy kicsit egyszerűbben is elintézhette volna. Magyarán előbb lőttél és aztán kérdeztél csak. Ami nem jó. Előbb kérdezni kell. Kivizsgálni az ügyet. Meg természetesen gondolkozni. Használni a központi idegrendszert. Ha már egyszer van.

**Comment by andris155** [comment]
1. ok
2. És valóban sikerült meghackelni a gépem amúgy? Mondjuk az alapján amit írtál nem hiszem, mert nem néztem olyan oldalakat vagy mit.

**Comment by TheChaosLord** [comment]
2. Persze, hogy nem. It was just a prank, bro. Csak kár, hogy túl komolyan vetted.

**Comment by Kayalafur** [comment]
Az első kérdésedre/problémádra : Egy közösségben a szólás szabadságot úgy gyakorolhatod, hogy az ne legyen teher a közösség számára, vagy zavaró. Ez is ott van a törvényben szépen megfogalmazva. Közösségen bellül egyéni elbirálású szabályok érvényesek, melyek nem feltétlen felelnek meg az alapvető szabályozásnak. Illetve mivel a szerveren nem személyesen veszel részt, hanem otthon a géped mögül, így teljes más elbírálás alá esel. A netiket ilyenkor felülírja az alapvető szabályozást. 

A példák:
1 Ha sokszor írsz ki valamit (flood) alapvetően annyiszor mondasz el valamit, ahányszor szeretnéd, de mivel netes közegben van, belefutsz a flood szabályába.
2 Ha angolul kezdesz el beszélni, de csak 1 ember akivel ezen a nyelven kommunikálsz, és a többieket ez zavarja, mivel van privát üzenet lehetőség a közösségi kommunikáció szabályai szerint köteles vagy a privátot használni.
3 Amennyiben mélyen vallásos vagy, jogod van elmondani a véleményed, amíg nem sérted vele más emberek vallási nézetét, de mivel ebből rendszeresen vita van. Így a vallási megnyilvánulások netes környezetben tilosak.

Remélem erre a kérdésedre kielégítő választ kaptál, és sikerül megértened, hogy az emberi alapjogok és a netes jogaid köszönő viszonyban sincsenek egymással. Ha szerver szabályait szeretnéd firtatni a Netiket az irányadó nem más. A többi itt érvénytelen. 

Személyi jogaid gyakorlásához szükség van:
Az arcodra, a nevedre, személyes megjelenésedre. A szerveren ez nem történik meg.

**Comment by TheChaosLord** [comment]
Még egy dolog: Itt elismerted, hogy nem követtem el azt, ami miatt kaptam a bant. Ebben az esetben nem lenne célszerű legalább az IP bant feloldani és az új karakterre átrakni a régi levédéseit? (Vagy a régi karakternél is feloldani.)

**Comment by andris155** [comment]
A tiltást feloldottam.

**Comment by andris155** [comment]
Az 1.13, szabály törölve.
