### ISSUE TITLE
OldVillage ötletek

### ISSUE THREAD

**Issue by Tapperr** [andris155/TheOld-Crafters#3060]
SavSziget szerverről áthozni az 1vs1 plugint, így lehetne arénázni nyertesnek pénz jutalom. 

Itemek amik különleges képességeket adnának +1 hp vagy hasonló enchantok.  Ezeket pedig úgy lehetne megkapni,  hogy a játékosok megvennék a boltban dollárért. 

--DreaKii

**Comment by poma123** [comment]
sajons nem lehet állítani az idomítást harc közben, szóval sima aréna lesz.
