### ISSUE TITLE
OldVillage - Heads hiba/túl drága

### ISSUE THREAD

**Issue by KingDeadZ** [andris155/TheOld-Crafters#3061]
A fejeknél nem mutatja az árát, hogy mennyibe kerül. Ez az összeg 10k$ ami valljuk be, elég sok... Lejjebb lehetne venni, jó lenne ha kiírná.

**Comment by MrZero1** [comment]
Mondjuk 1500$?

**Comment by KingDeadZ** [comment]
Jópár fokkal jobb :D

**Comment by poma123** [comment]
kész
