### ISSUE TITLE
15percenkénti pénz hiba - OldVillage

### ISSUE THREAD

**Issue by KingDeadZ** [andris155/TheOld-Crafters#3062]
![image](https://user-images.githubusercontent.com/38157910/61162918-237b0980-a50b-11e9-8a3b-9cbf6f0e4cc9.png)

![image](https://user-images.githubusercontent.com/38157910/61162929-3097f880-a50b-11e9-9dbe-099278deb63d.png)
Szerintem mindent megmagyaráz, nem resetelődött a pénzösszeg.

**Comment by poma123** [comment]
Elvileg már jó
