### ISSUE TITLE
Lock-olt ajtó nyitása idomítással.

### ISSUE THREAD

**Issue by GetOut101** [andris155/TheOld-Crafters#3063]
Minap az OldVillage szerveren be akartam menni Boomer házába és Lockolva volt az ajtó. Kitaláltam, hogy mi lenne ha idomítással buggoltatnám és sikerült. Írjatok rám és megmutatom a hibát.

**Comment by poma123** [comment]
nem hiszem hogy ehhez csinálnának támogatást :(

**Comment by KingDeadZ** [comment]
Ha van plot, levédi és pár blockkal beljebb rakja az ajtót, így nem lehet kibugoltatni. (2-3nál már teljesen jó)

**Comment by andris155** [comment]
Nem nagyon foglalkoznak ezzel a plugin-nal már. Az is csoda, hogy az új verziókra megírta egy fejlesztő.

**Comment by andris155** [comment]
Esetleg az idomítás plugin fejlesztőjének lehet még írni ezzel kapcsolatban, hogy csinálja meg.
