### ISSUE TITLE
Kick bug

### ISSUE THREAD

**Issue by GetOut101** [andris155/TheOld-Crafters#3064]
A képességemmel repültem és kikickelt azzal az indokkal, hogy A repülés nincs engedélyezve ezen a szerveren.

**Comment by KingDeadZ** [comment]
Ha van egy minimális lag, flynak érzékeli azt kidob. tornádóval csinálta velem ezt :P

**Comment by andris155** [comment]
Erre szerintem nincs megoldás. Nem nagyon kompatibilis a cheat védelem ezzel a plugin-nal.

**Comment by andris155** [comment]
Később, ha lesz normálisabban működő fly védelem, akkor le lesz cserélve. De addig csak ez van.

**Comment by MrZero1** [comment]
Járulékos veszteség (?) :D
