### ISSUE TITLE
Survival

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#3068]
1.13 világban (ha még nincs) letiltani a levédés lehetőségét. Esetleges, ismétlem és kiemelem, esetleges 1.15 előtti világtörlés miatt, megelőzzük az új játékosok letelepedését abban a világban.

**Comment by andris155** [comment]
Elvileg beállítottam, majd le kell tesztelni.

**Comment by MrZero1** [comment]
Jó, azt írja ki a játékosoknak, hogy nem lehet levédeni. Köszi!
