### ISSUE TITLE
Jobs plugin hiba

### ISSUE THREAD

**Issue by Icecroft** [andris155/TheOld-Crafters#307]
I am using the farmer and miner jobs. The required XP to next level was changed to 2147483647 XP for both jobs. This was changed about the last weekend. I have a lvl 77 miner and lvl 94 farmer, but i am unable to develep them to next level with this requirements. See my screenshots below.
I am not the only one, who is affected, see the incorrect requirements of the player St3am3r on the next screenshot.

A következő jobs szinthez szükséges pontszám nem jó, a 77-es bányászom és a 94-es farmeremnek is 2147483647 XP kell a kövi szinthez, ami biztos, hogy nem jó. Ez a probléma még pénteken nem volt.

**Comment by Kayalafur** [comment]
Átnézem a táblázatot, köszi hogy szóltál

**Comment by Icecroft** [comment]
![2016-09-12_13 39 11](https://cloud.githubusercontent.com/assets/19332825/18434601/6dbd5d28-78ee-11e6-9538-da7873ea4f00.png)

**Comment by Kayalafur** [comment]
![jobs1](https://cloud.githubusercontent.com/assets/17968738/18435050/3c4575b6-78f1-11e6-9790-d7b214c0724e.PNG)
 Utána néztem, valamiért csak nálad van ez a hiba fogalmam sincs, hogy miért.

**Comment by Icecroft** [comment]
Szerintem St3am3r bányásza sem jó, ahogy a screenshotodat nézem.
Szerintem nem csak engem érinthet.

**Comment by andris155** [comment]
javítva.
