### ISSUE TITLE
OldVillage névtelen város

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#3072]
Ha a /town create parancshoz káromkodást írok be, nem lesz neve a városnak.

![kép](https://user-images.githubusercontent.com/16057404/61238320-b0f17000-a73c-11e9-9b64-0c0858ba264d.png)

**Comment by poma123** [comment]
/town set name - Újra tudod nevezni, ezzel senkinek nem ártasz és nem is szerzel előnyt

**Comment by MrZero1** [comment]
Ezért sem kell csúnyán beszélni :laughing:
