### ISSUE TITLE
Rákos Blokkba-buggolás - OldVillage

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#3078]
Számtalanszor jön elő ez a bug, sok embernek.  Nekem pl 2 óra alatt minimum 5x fordult elő, ami jobb estben /spawn-al megoldható. Néha tpz*kor fordul elő, de úgyis előfordult már, hogy beírtam /town toggle pvp -> bebuggoltam, ha még 4x írtam be a parancsot, akkor még 4x buggoltam be.
Jó lenne ezzel csinálni valamit mert nagyon zavaró : (

**Comment by andris155** [comment]
Ha valakivel harcban vagy nem lehet belépni pvp nélküli zónára.

**Comment by skrisz0101** [comment]
???

**Comment by poma123** [comment]
Ha combatban vagy, nem léphetsz be pvp nélküli zónára. Ezt látványosan kipróbálhatod az arénában. Lépj be, és hívj valakit. Lépj át a piros vonalon támadd meg, majd próbálj visszamenni a piros vonalon belülre.

**Comment by skrisz0101** [comment]
Pvphez nincs köze, most pl fakusikereskedés közben történt

**Comment by andris155** [comment]
Ha ismét előfordul kérlek nyiss új jelentést.
