### ISSUE TITLE
Táblabolt hiba (?)

### ISSUE THREAD

**Issue by akos222** [andris155/TheOld-Crafters#308]
Ha fullos inventoryval próbálunk meg vásárolni a táblaboltból, akkor az a cipő, nadrág, mellvért, vagy sisak helyére teszi a vásárolt tárgyat, ezzel Tag ranggal is lehet blockot tenni a fejre.

**Comment by andris155** [comment]
https://github.com/andris155/TheOld-Crafters/issues/190
