### ISSUE TITLE
Levédett területen való nyitogatás - OldVillage

### ISSUE THREAD

**Issue by KingDeadZ** [andris155/TheOld-Crafters#3082]
Minden féle trapdoort/doort ki lehet nyitni, ami nem sima tölgyből van.

**Comment by andris155** [comment]
A 0.94-es Towny-ban javították, de manuálisan kell frissíteni a konfigot is hozzá. @poma123 
http://towny.palmergames.com/release-version-towny-advanced-0-94-0-0-1-13/
