### ISSUE TITLE
Korlátlan Elem váltás joggal való hiba - OldVillage

### ISSUE THREAD

**Issue by KingDeadZ** [andris155/TheOld-Crafters#3083]
Amikor lelépek a szerverről, majd visszalépek bármikor, ha előtte bármilyen elem volt kiválasztva (tűz,víz,föld,levegő) akkor elveszi az elememet. De ha a Chi van kiválasztva, akkor megmarad belépés után is.

**Comment by poma123** [comment]
Nem nagyon értem, én kipróbáltam játékos jogokkal és nem törli. Nem tudnád esetleg ezt valahogy dokumentálni?

**Comment by KingDeadZ** [comment]
Megpróbálom

**Comment by KingDeadZ** [comment]
Most nem jött elő a hiba, ha újra előjönne akkor újranyitom.
