### ISSUE TITLE
OldVillage hibajenetés

### ISSUE THREAD

**Issue by Tapperr** [andris155/TheOld-Crafters#3086]
A mai nap arénáztam és amikor kiléptem onnan többször is elwarpolt/teleportáltam majd  mikor beirtam a /back parancsot visszarakott az arénába és amikor (rajtam volt  a szett,  tehát belehet vinni itemeket)  kiléptem eltűnt minden cuccom. 

-DreaKii

**Comment by poma123** [comment]
Köszi :D
