### ISSUE TITLE
OldVillage - vásárcsarnok

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#3087]
Vásárcsarnok eladás bővítése, kategóriák szerint. Cserefalusiak továbbgondolása.

Plusz: Javaslatot, ötletet szívesen elfogadunk.

**Comment by MrZero1** [comment]
"[Ötlet] Vásárcsarnokban szerintem jó lenne egy End részleg, ha már van nether is :v
Esetleg egy víz részleg
Esetleg nagyobb növény választék (?)"

 #3048

**Comment by KingDeadZ** [comment]
A mob dropok kivétele a cserekereskedőktől, saját részegre való átkerülésük.

**Comment by RayderHUN** [comment]
Egy fejvadász bolt a bolton belül, ahol a mobok fejeit lehet eladni. Minél ritkább egy mob annál drágábban persze.

**Comment by Danesmasteer** [comment]
Kaktusz a cserekereskedőknél vagy a vásárcsarnokban eladásra.

**Comment by MrZero1** [comment]
Továbbra is lehet írni javaslatokat, de ezt lezárom.
