### ISSUE TITLE
Szél idomár OldVillage (pomának)

### ISSUE THREAD

**Issue by RayderHUN** [andris155/TheOld-Crafters#3091]
Nem terveztem feljönni erre az oldalra, de most bebizonyosodott az amitől féltem, és amit a fél szerver is tud és jelzett természetesen előre.
Próbálom egy kellemes és nyugodt hangsúlyban összeszedetten kifejteni a dolgokat, ha nem jön össze az indulat hevében elnézést kérek már most előre.
A szél idomárral valamit kezdeni kell, mert ez nem állapot.

PvP szituáció: A semmiből meglepem az illetőt, harcolok vele majd ha úgy gondolja neki elég, nem bírja elrepül, ismétlem olyan gyorsan elrepül amit más idomár nem tud utolérni.

Második szituáció, harcolok 6 ember ellen (full diás harc) majd odajön egy szett nélküli kis sima játékos és a szélfelhajítással azzal szórakozik hogy felhajigál 40 blockra.. Mit tudunk ez ellen kezdeni, semmit!

Harmadik szituáció, sima felszerelés nélküli megint semmit nem érő játékos odajön a 6v1-es gyémánt felszereléses harcba és elfújja a szövetségeseket, akár engem úgy, hogy mozogni sem tudok mert falnak fúj.. mit tudunk kezdeni, semmit!

PvP szituációban a széllel semmit nem lehet kezdeni, és ezzel meg is öli a pvp-t. 

Azt nem fogom elfogadni válasznak, hogy a szélidomár tud ellen érni valamit (ami szerintem nem igaz) Egy pvp szerveren ahol 4 idomár van nem válasz az, hogy 2 idomár ér a szél ellen valamit! Egyensúlyban kell lennie a 4 idomárnak!

A gyors választ, megoldást és intézkedést előre is köszönöm.

**Comment by poma123** [comment]
rakok több visszaszámlálási időt a levegő képességekre :)
