### ISSUE TITLE
Oldvillage szint kiírás bug

### ISSUE THREAD

**Issue by LordAdam55** [andris155/TheOld-Crafters#3092]
A játékos mikor belép a chaten nem a valós szintjét mutatja, már velem is megtörtént, megjavul egy idő után.

a chaten így néz ki:
![Képkivágás](https://user-images.githubusercontent.com/46933798/61547021-d0451180-aa4a-11e9-8fcf-d06fe84ebe5b.PNG)
míg a tabon így: 
![képkivágás2](https://user-images.githubusercontent.com/46933798/61547667-24042a80-aa4c-11e9-9c10-ca6ff872b90c.PNG)

**Comment by poma123** [comment]
ez még mindig az egykori rossz újraindítás miatt van, aki azóta nem volt fent és feljön azóta először rosszul fogja mutatni, de egy pénz eladás javítja.
