### ISSUE TITLE
OldVillage Shulker

### ISSUE THREAD

**Issue by Huntermaster0** [andris155/TheOld-Crafters#3093]
Levédett területen más is ki tudja nyitni a shulkerdobozokat.

**Comment by Kismalax** [comment]
Lehet használni más levédésén az üllőket és főzőállványokat is.
A shulkerekkel kapcsolatban azt tapasztaltuk, hogy csak a nem színezett, alap lila színűeket tudja bárki kinyitni.

**Comment by andris155** [comment]
A 0.94-es Towny-ban javították, de manuálisan kell frissíteni a konfigot is hozzá. @poma123
http://towny.palmergames.com/release-version-towny-advanced-0-94-0-0-1-13/
