### ISSUE TITLE
Világból kibuggolós izé

### ISSUE THREAD

**Issue by Bannoltboci** [andris155/TheOld-Crafters#3095]
Valamitől többen is kibuggoltunk a világból, meghaltunk a cuccunkat nem tudtuk visszaszerezni mert a /back máshova dobott és amúgy is kizuhantunk a világból. Zero mondta hogy írjam meg ide.
Rayder szerint valami chunk reload plugin az okozója 

<a href="https://imgur.com/nKcfT11"><img src="https://i.imgur.com/nKcfT11.png" title="source: imgur.com" /></a>
<a href="https://imgur.com/r2ThJ8P"><img src="https://i.imgur.com/r2ThJ8P.png" title="source: imgur.com" /></a>

**Comment by andris155** [comment]
Remélem nem 1.14-el játszol ezen a szerveren. Mert szerintem az a probléma.

**Comment by Bannoltboci** [comment]
1.14el játszok mivel az is elérhető a szerveren :x

**Comment by MrZero1** [comment]
Énis 1.14 verzióban játszok de ilyen sosem volt nekem

**Comment by andris155** [comment]
A hiba tök egyszerű, hogy miért jön létre. Az OldVillage-nél van async chunk betöltés, tehát a világ betöltése több szálon történik azonban mivel a processzor túl van terhelve így a folyamatnak várnia kell, így a világ csak később tölt be addig pedig kizuhansz a világból. Ezt csak az új gép oldja meg.

**Comment by andris155** [comment]
https://github.com/andris155/TheOld-Crafters/issues/3146

**Comment by andris155** [comment]
Kérlek nyisd újra, ha még él a hiba, mert akkor bővebb elemzést igényel.
