### ISSUE TITLE
Kreatív mód hiba

### ISSUE THREAD

**Issue by falcon0607** [andris155/TheOld-Crafters#3102]
Kreatívban visszadobál a játék ha kiütsz 1 blockot. Ami nem is lenne zavaró ha kb 1x csinálná de ezt minden blocknál eljátsza. @andris155

**Comment by andris155** [comment]
már jónak kell lennie.

**Comment by Huntermaster0** [comment]
Még mindig rossz

**Comment by andris155** [comment]
Most jó?
