### ISSUE TITLE
WG hiba

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#3104]
Nem írom ki mi, de nem jó, és lehet használni azt a valamit, ott ahol nem kéne. Már néhány napja jeleztem ezt.

**Comment by andris155** [comment]
Most tudják használni?

**Comment by MrZero1** [comment]
Most nem

**Comment by poma123** [comment]
akkor ezt bezárom

**Comment by andris155** [comment]
Ha lesz időm utána járok mi baja a flag-nek.

**Comment by andris155** [comment]
Érdekes egy hiba. Saját szerveren egyelőre reprodukálni se tudtam. Komolyabban utána kell majd járnom ennek mitől lehet.

**Comment by andris155** [comment]
kb. 07.05-06-tól él a hiba. (hibakereséshez hasznos)

**Comment by poma123** [comment]
De már jó. Az a lényeg hogy ne tudják használni azt a tárgyat ha le van tiltva (nem?)

**Comment by andris155** [comment]
Én kíváncsi vagyok a flag miért nem jó. Úgyhogy megfogom keresni mi okozza. :)

**Comment by andris155** [comment]
Valószínűleg más hibát is okozhat az ilyen ezért is érdemes javítani.

**Comment by poma123** [comment]
Konklúzió: a flag továbbra sem jó, hanem máshol lett letiltva a dolog (pl wg ). így már értem :D

**Comment by andris155** [comment]
javítva
