### ISSUE TITLE
OldVillage ( Nemzet ötlet )

### ISSUE THREAD

**Issue by RayderHUN** [andris155/TheOld-Crafters#3105]
A nemzet pluginhoz jó lenne egy olyan fejlesztés, hogy ha valaki nemzetet csinál, akkor 1 nap múlva vagy esetleg több idő múlva bonthassa azt fel.

Mert jelenleg ki-be csukiznak emberek. A ki-be csuki azt takarja, hogy megvárja egy Town hogy az ellenséges nemzetben fent legyen 3 játékos, ellenséges Townban pedig 2 gyenge játékos és ekkor nemzetet csinál elfoglalja a területeket, és feloszlatják a nemzetet.

Amennyiben az ötlet elfogadható és kivitelezhető, még egy olyat javasolnék mellé, hogy háború kezdetekor resetelődjön az idő és kezdje el újra számolni, mert  várhatnak emberek 23 óra 40 percet és 20 perc után vagyis háború után bonthatják is.

/Rayder/

**Comment by poma123** [comment]
Nem rossz ötletek, nem tudom mi oldható meg és mi nem. Meglátjuk.

**Comment by RayderHUN** [comment]
Én hiszek benned :P <3

**Comment by poma123** [comment]
#3114
