### ISSUE TITLE
Ötlet-Oldvillage

### ISSUE THREAD

**Issue by mestertrefa** [andris155/TheOld-Crafters#3107]
Lehetne egy olyan, hogy minden mittomén hanyadik éjszaka(minecraft éjszaka) lehetne egy bloodmoon, és olyankor egész este(minecraft este) mindenhol lenne PvP.

**Comment by Tarifnya** [comment]
jobb lenne inkább seasonosan megoldani ezt ugy értem hogy pl minecraft szerint 50 nap PvE townokban
de 51-55 nap PvP lesz és igy 50 minecraft napig lehet készülni d elehet akár 200 nap is xd

**Comment by poma123** [comment]
ilyen biztos nem lesz, olyan max lehet majd csak halloweenkor hogy pár napig mindenhol pvp van.
