### ISSUE TITLE
PVP-PVE a townban

### ISSUE THREAD

**Issue by Eror32** [andris155/TheOld-Crafters#3108]
Alapból pve-re van kapcsolva a town, nem lehet megváltoztatni. 2 csapat van: a védekező és a támadó. Ha a támadó csapat támadni készül (erre lehetne akár egy parancs), akkor max fél percük van a védekezőknek felszerelkezni, összegyűlni (és legalább 4-4 embernek kell ott lennie). Ha letelik a fél perc, elkezdődik a csata és nem lehet kimenni, illetve bemenni a csatatérre. A támadóknak 1, míg a védekezőknek 2 életük van. Ha meghal valaki, bekerülne a támadás alatt álló csapat börtönébe, míg véget nem ér a csata. Ha a támadók győznének, van 1 percük hogy falusiakat lopjanak, (szinttől függően) X nem lockolt ládából lopjanak és egy 500-900$-os nyereményt is kapnának fejenként. Ha viszont a másik csapat nyer, akkor 2 órán át börtönben lennének a vesztes támadók, amit alkudozással rövidíteni, vagy kiváltani is lehet, illetve kapnának 1500-2300$-os fizetséget a sikeres visszaverésért, megint csak fejenként. A vesztes féltől levon pl. 700-1600$-t (fejenként). A csata végén a területre nem léphet be idegen 4-5 órán át.

**Comment by Eror32** [comment]
Lehet hogy nehezen megvalósítható meg eltértem egy kicsit a témától, de remélem tetszik az ötlet és ha nincs más kérlek valahogy próbáljátok megvalósítani kisebb-nagyobb módosításokkal. :)

**Comment by poma123** [comment]
nagyon kesze-kusza és nem hiszem hogy olyan egyszerűen megvalósítható :(
