### ISSUE TITLE
mozgás +ugrás közben fel lépő "tp bug"

### ISSUE THREAD

**Issue by Tarifnya** [andris155/TheOld-Crafters#3109]
Sokszor tapasztalom hogy magas helyről (nemfeltétlen kell magasnak lennie bármilyen magasságban tapasztalható s lehet szakadék is) leugorva  nincs zuhanási idő 
hanem azonnal   a legalsó blockra dob/teleportál.. elég gyakran tapasztalom 
Szakadék átugrásánál is fel szokott ez lépni 
át akartam ugrani 1 nagyob szakadékot és mid air ban le tpzett a szakadék aljára

**Comment by andris155** [comment]
melyik szerver?

**Comment by skrisz0101** [comment]
Oldvillage

**Comment by andris155** [comment]
Most sem jó?

**Comment by Tarifnya** [comment]
továbbra is fel lép nálam a hiba
néha

**Comment by Tarifnya** [comment]
még mindig

**Comment by andris155** [comment]
Kérlek írjatok, ha még él a hiba. Az új szervergép erősebb és kisebb a ping is. Szerintem ennek meg kell oldania a problémát.
