### ISSUE TITLE
MineMarket PE hiba

### ISSUE THREAD

**Issue by NikeboyHU** [andris155/TheOld-Crafters#311]
Timer hiba: 
16.09 20:55:15 [Server] Server thread/CRITICAL Could not execute task MineMarket\ScheduleTask: Call to undefined method MineMarket\ScheduleTask::getServer()
16.09 20:55:15 [Server] Server thread/CRITICAL Error: "Call to undefined method MineMarket\ScheduleTask::getServer()" (EXCEPTION) in "/MineMarket_v0.1.0.phar/src/MineMarket/timer" at line 46

**Comment by andris155** [comment]
http://forum.infinityhosting.hu/t/minemarket-pe-hiba-hogyan-lehetne-javitani/922

**Comment by andris155** [comment]
javítva
