### ISSUE TITLE
Ötlet a townok közti harcokban

### ISSUE THREAD

**Issue by Tarifnya** [andris155/TheOld-Crafters#3110]
feltételezzük hogy 2-3 town akik szeretnének harcolni egymás közt  de nation nemtudnak harcolni mert a town ban pve van
  Szerintem lehetne 1 olyan  command  hogy /town war Town1 (vagy valami hasonló)(town 1 a town neve) amit a leader tud inditani
/town war accept és igy bele lehetne kezdeni 1 townok közti war ba és bármennyi townal lehet egyszerre harcolni vagy invitelni townokat segitségként ( /town war invite Town3)
a /town war accept után lenne pl 4 óra felkészükési idő vagy annyi amennyi és
a 4 óra lejárta után a  harcban álló townok 90 percek keresztül townon belül tudnák ölni egymást /terület foglalósat játszani

**Comment by poma123** [comment]
a városok nem fognak egymással harcolni, az biztos. azt még megfontolom, hogy mi van akkor, ha engedélyezem a pvp-t azon a chunkon amit éppen háborúban támadnak a nemzettel.
