### ISSUE TITLE
Városalapítás alapbeállításai

### ISSUE THREAD

**Issue by Huntermaster0** [andris155/TheOld-Crafters#3111]
Ha valaki várost alapít, alapból public az egész és bárki oda tud teleportálni. Ezt jó ötletnek tartom megváltoztatni, mivel ha egy kezdő alapít egy várost, akkor egyből oda tudnak tpzni a már tapasztalt playerek és simán megölik őt.

**Comment by poma123** [comment]
kész, már tegnap javítottam nem kellett volna kitenni de m1
