### ISSUE TITLE
Nem lehet townok mellé/townokba homeolni akkor miért ne legyen mindenhol pvp?

### ISSUE THREAD

**Issue by Kiphleee** [andris155/TheOld-Crafters#3112]
beleírtam a címbe mert amúgy senki sem olvasná el

**Comment by Niccolettie** [comment]
Az egy dolog, hogy nem lehet homeolni, ettől függetlenül van parancs a townokba teleportálásra, de a legegyszerűbb módon is oda lehet jutni: véletlenül találsz egyet.
A pvp akkor igazságos (és sírás/nyavajgás mentes, na jó, sose az, de ilyenkor legalább egyszerűbb kezelni) a legtöbb esetben ha mind a két fél tisztában van vele, hogy nem a békés búza aratás közben veregeti valaki hátba a dia kardjával, mert nincs a városában pvp, stb  :)
