### ISSUE TITLE
[Információ] javaslat

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#3113]
![kép](https://user-images.githubusercontent.com/16057404/61784918-ecf69600-ae0a-11e9-8224-9a4283d84ed1.png)

Ez a mondat így elég értelmetlen, "segítségkérés esetén" / "ha segítségre van szükséged" jobb lenne.

**Comment by UDPSendToFailed** [comment]
+1:

Weboldalon is lehetne szebben fogalmazni ezt a részt.

![kép](https://user-images.githubusercontent.com/16057404/61785307-ba996880-ae0b-11e9-9408-d5b395db8dd2.png)

**Comment by MrZero1** [comment]
A weboldal szabályzatra ráférne egy teljes frissítés, akár szerverekre lebontva a szabályzat.

**Comment by andris155** [comment]
A szerveren az EssentialsX/rules.txt-t vegyem alapul?

**Comment by MrZero1** [comment]
Még ne, majd elküldöm privátba az új szabályzatot, már dolgozom rajta.

**Comment by andris155** [comment]
A jelentésben szereplő dolgokat átírtam. A szabályzatot meg majd akkor, ha megkapom.
