### ISSUE TITLE
Hibajelentés Oldvillage

### ISSUE THREAD

**Issue by Bannoltboci** [andris155/TheOld-Crafters#3117]
Harc közbe ha nyitogatsz 1 lockolt ajtót áttudsz rajta futni (buggolni)

Tesztelve skrisz01en és Kiphleeen

**Comment by poma123** [comment]
Ez csak úgy működik, ha 1.14.x-es verzióval játszol. Sajnos ez az 1.14-es támogatás hibája :(

**Comment by andris155** [comment]
Nem 1.13.2-vel működik?
