### ISSUE TITLE
Hibajelentés Survival

### ISSUE THREAD

**Issue by falcon0607** [andris155/TheOld-Crafters#3120]
A lock tábláknál ha létrehozom a [Több név]-es táblát majd jobb click rá és beszeretném írni a többi nevet azt írja ki minden alkalommal hogy "Kérlek válaszd ki újra a táblát". @andris155

**Comment by KingDeadZ** [comment]
Helyes írások: több név, Több Név
simán a Több név-el nem hoz létre kiegészítő táblát

**Comment by andris155** [comment]
[Több Név] vagy [több név] táblával fog csak működni, és kell hozzá lennie rajta egy [Lock] vagy [lock] táblának is.
