### ISSUE TITLE
AreaShop Rent - Hibajelentés

### ISSUE THREAD

**Issue by Silderon** [andris155/TheOld-Crafters#3121]
Spawnon két területet is szabadnak jelez a rendszer (h3,h12)
De egyiket se engedi kibérelni amikor rákattintok a táblára hibaüzenet:
Nincs engedélyed, hogy béreld a területet.

/as rent 
Paranccsal ugyan ez a helyzet.

**Comment by poma123** [comment]
hányas szinted van? :D

**Comment by Silderon** [comment]
13-as

**Comment by poma123** [comment]
1-3as szintig lehet házat bérelni....
