### ISSUE TITLE
Más világba teleportáláskor automatikus túlélő mód letiltása

### ISSUE THREAD

**Issue by falcon0607** [andris155/TheOld-Crafters#3122]
Meglehetne azt oldani hogy ha valakire rátpzek gm 3-ban és az a személy eventen van ne váltson vissza gm 0-ba. @andris155

**Comment by andris155** [comment]
Melyik szerver?

**Comment by MrZero1** [comment]
Survival, Savsziget ahol vannak eventek.

**Comment by poma123** [comment]
vagy multiverse vagy a worldguard váltja át, még nem jöttem rá

**Comment by andris155** [comment]
Most jó?

**Comment by MrZero1** [comment]
Még mindig átrak

**Comment by poma123** [comment]
@andris155

**Comment by andris155** [comment]
Melyik világból melyikbe történő teleportálásnál rak át, és melyik szerveren?

**Comment by poma123** [comment]
Kipróbálom ma

**Comment by poma123** [comment]
Pl. Oldv-n spawnról(kormedie) vadonba(world) átrak gm3-ból gm0-ba

**Comment by andris155** [comment]
mv.bypass.gamemode.világneve, add meg a jogokat azokra a világokra, ahol nem szeretnéd, hogy átváltson nekik. Ha az összesnél szeretnéd, hogy ne váltson át akkor mv.bypass.gamemode.*

**Comment by poma123** [comment]
danke

**Comment by andris155** [comment]
Működik?

**Comment by poma123** [comment]
aha
