### ISSUE TITLE
MineMarket PE hiba (ismételten)

### ISSUE THREAD

**Issue by NikeboyHU** [andris155/TheOld-Crafters#313]
27.09 20:12:51 [Server] INFO Warning: simplexml_load_file(): php_network_getaddresses: getaddrinfo failed: Name or service not known in phar:///plugins/MineMarket_v0.1.0.phar/src/MineMarket/timer.php on line 22
27.09 20:12:51 [Server] INFO Warning: simplexml_load_file(http://minemarket.hu/get_purchase.phpo=9e357c9564ac811b2fa41f7d9387f8944e8d6ed1): failed to open stream: php_network_getaddresses: getaddrinfo failed: Name or service not known in phar:///plugins/MineMarket_v0.1.0.phar/src/MineMarket/timer.php on line 22
27.09 20:12:51 [Server] INFO Warning: simplexml_load_file(): I/O warning : failed to load external entity "http://minemarket.hu/get_purchase.phpo=9e357c9564ac811b2fa41f7d9387f8944e8d6ed1" in phar:///plugins/MineMarket_v0.1.0.phar/src/MineMarket/timer.php on line 22

**Comment by andris155** [comment]
ERROR 404 - Not Found! Szerintem ez a weboldal részen lesz valami hiba.
