### ISSUE TITLE
Statisztika.

### ISSUE THREAD

**Issue by RayderHUN** [andris155/TheOld-Crafters#3133]
Statisztikákba az úszott távolság betevése ( Ha megoldható )

**Comment by poma123** [comment]
@andris155

**Comment by andris155** [comment]
Szerintem visszakerülhetne az, ami offline is működik. Nekem sajnos az offline-osnak nincs meg a forráskódja.

**Comment by poma123** [comment]
hát én fejlesztettem csak aztán átírtad kizárólag onlinera v mi de akkor majd megcsinálom :D

**Comment by poma123** [comment]
Amit te visszamódosítottál csak online megnézhetőre, a forráskódban volt változás?

**Comment by andris155** [comment]
Nem. De 1.14.4-re lehet célszerű lenne frissíteni a túlélőre. :D

**Comment by poma123** [comment]
okés, ha lesz szeró meg is mavenesítem, megcsináltam amúgy a kódban az úszást

**Comment by poma123** [comment]
- [x] OldVillage
- [ ] Survival
- [ ] Savsziget
- [ ] Építész+
