### ISSUE TITLE
Oldvillage - Írható könyv törlés hiba

### ISSUE THREAD

**Issue by RayderHUN** [andris155/TheOld-Crafters#3134]
Ha egy írható minecraft könyvbe írunk több soros szöveget, és azt ki szeretnénk törölni az egész játék ki crashel. Teszteltem egy másik játékossal is, törölt a könyvből (próbált) és ki crashelt.
Nem tudom mivel lehet összefüggésben, de szerver hiba.

**Comment by poma123** [comment]
1.14-es támogatás hiba, mivel 1.13-ban még nem lehetett. inkább ne csináljátok.
