### ISSUE TITLE
Slot növelési petíció

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#3135]
![kép](https://user-images.githubusercontent.com/16057404/62006282-f2235000-b13e-11e9-879c-bd2aaa6a542d.png)

**Comment by falcon0607** [comment]
Támogatom!!!!

**Comment by andris155** [comment]
Holnap növelve lesz. Sajnos csak a szerverkezelő újraindításával megoldható.

**Comment by skrisz0101** [comment]
Lehet kevés lesz az a 110 😅😅

**Comment by MrZero1** [comment]
:heart:

**Comment by MrZero1** [comment]
110 kevés lesz szerintem is. 
Plusz #3136

**Comment by andris155** [comment]
Meglátjuk. Többre nem akarom állítani annál, amennyi kell.

**Comment by falcon0607** [comment]
@andris155  Értsd meg, hogy ha 10-el emeled a maxot az lóf@szt nem fog érni. Megéri az neked, hogy minden nap cseszegetni foglak azzal, hogy emeld meg a max játékos számot, csak azért, mert most nem emeled annyival, hogy az elég legyen. Ha egy új nem tudok feljönni 3-4 probálkozás után sem, akkor itt fogja hagyni a szervert és az NEKED lesz a legrosszabb. Mert én személy szerint elvagyok 30-40 játékossal, de, ha épp egy olyan akar feljönni aki hajlandó perkálni az extrákért, de nem tud, ugyan is kevés a max a szerveren. Minimum egy 50-nel kéne növelni.

**Comment by poma123** [comment]
Vita off. Legyen megnövelve 150-re. Ha jól megy, egy idő után ígyis-úgyis el fogjuk azt a számot érni, felesleges 10-esével felfelé állítani naponta. De egyelőre még mindig cselekvőképtelenek vagyunk.

**Comment by andris155** [comment]
Meglátjuk mennyi játékos marad, ha futni fog a szerver. Szerintem lehet a 100 is elég lesz. :(

**Comment by poma123** [comment]
először legyenek játékosok is
