### ISSUE TITLE
Privát üzenet

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#3137]
![kép](https://user-images.githubusercontent.com/29709854/62009977-4e00cf80-b165-11e9-9874-1b6d3133b770.png)

Ez elég fura. Dreakii írta a privátot (spy) aztán más játékost ír ki.

**Comment by andris155** [comment]
Többször is előfordult?

**Comment by MrZero1** [comment]
Volt már hasonló eset is, az többször mondjuk. Írtam valakinek, de teljesen más ember kapta meg az üzenetet.

**Comment by andris155** [comment]
Az új ChatControl szerintem megoldja.
