### ISSUE TITLE
mcMMO plugin Herblore skill problem

### ISSUE THREAD

**Issue by Icecroft** [andris155/TheOld-Crafters#314]
![2016-10-01_17 11 35](https://cloud.githubusercontent.com/assets/19332825/19014961/972f9d2c-87fa-11e6-9586-24828e141dab.png)
Az mcmmo plugin Herblore skillnek van egy "Double Drop" képessége, ami megduplázza az éppen learatott termést. Ha gyengédérintéses baltával szedem a dinnyéket, akkor a duplázáskor a 2. dinnyét nem egészben, hanem szeletekben kapom. Ez a probléma. Mostmár 200 felett van a Herblore szintem, nagyon gyorsan tele lesz az inventorym dinnyeszeletekkel.

There is a problem with Herblore skill Double Drop ability: If i harvest the watermelons with a silktouch enchanted axe, I get the second melon in slices and not in block, like the first. I am over level 200 in Herblore, my inventory is full with melon slices very fast.

**Comment by andris155** [comment]
Köszönöm, profi jelentést!

**Comment by andris155** [comment]
Jelentettem a fejlesztőnek, de úgy látom nem nagyon javítja a hibákat. :/

**Comment by Icecroft** [comment]
Szia Andris, ez miért ne lenne hiba? A dinnyeblokkokat nem megduplázza, hanem 1 blokkot és néhány szeletet ad.

**Comment by andris155** [comment]
Átraktam hibára.

**Comment by andris155** [comment]
https://github.com/andris155/TheOld-Crafters/issues/348
