### ISSUE TITLE
Towny hibák javítása

### ISSUE THREAD

**Issue by poma123** [andris155/TheOld-Crafters#3140]
Hibák: #3093 #3082 

A 0.94-es Towny-ban javították, de manuálisan kell frissíteni a konfigot is hozzá.
http://towny.palmergames.com/release-version-towny-advanced-0-94-0-0-1-13/

**Comment by KingDeadZ** [comment]
Ha ez is elveszett, újra le kéne frissíteni ha lehetséges, mivel még működnek.
