### ISSUE TITLE
Party hiba

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#3142]
Egyszerre 3 játékos is "kilépett", pedig nincsenek fent.

![kép](https://user-images.githubusercontent.com/16057404/62319116-91c54300-b49d-11e9-91d9-cb111860a3fb.png)

`[20:43:33] [main/INFO]: [CHAT] ClearLag Kilépett a partyból!
[20:43:33] [main/INFO]: [CHAT] Multons Kilépett a partyból!
[20:43:33] [main/INFO]: [CHAT] EHzy Kilépett a partyból!`

**Comment by skrisz0101** [comment]
Nem voltak fent 1 hétig (?)

**Comment by andris155** [comment]
Ha van ilyen, amit @skrisz0101 mond, akkor ez nem hiba.

**Comment by KingDeadZ** [comment]
Ha 1 hétig nincs fent valaki, automatán kidobja a partyból.
