### ISSUE TITLE
Old szett HP bug

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#3143]
Hiába lépek ki max HP-val, miközben Old szettben vagyok, belépés után csak egy sornyi lesz. Újra kell neki generálódni, ezzel kajacsíkot vesztek, és ha olyan helyen vagyok, ahol nem elég az egy sor, meg is halok.

https://youtu.be/vTnlh71Eubo

**Comment by andris155** [comment]
Az alap játékban gondolom így van.
