### ISSUE TITLE
Hibajelentés - OldVillage

### ISSUE THREAD

**Issue by KingDeadZ** [andris155/TheOld-Crafters#3147]
Mi a helyzet a backkel? Ki lett véve? (adnám ha ki lenne véve ne essen félreértés,csak érdekes.)
![image](https://user-images.githubusercontent.com/38157910/62372759-9428ab00-b538-11e9-8d2c-15b0870dab0f.png)

**Comment by poma123** [comment]
A spawnra nem lehet vissza back-elni :))))
