### ISSUE TITLE
Oldvillage: A zombik 90%-a eltűnik fulladáskor

### ISSUE THREAD

**Issue by Icecroft** [andris155/TheOld-Crafters#3148]
Ha zombikat fullasztok, akkor azok nagyrésze egyszerűen eltűnik.
Nem amikor vízbefúlttá válik, hanem előtte, amikor "átváltoznak" remegő állapotba.
Hasonló probléma már volt a Hardcore-on, amit akkor sikerült javítani.
a.) lehet, hogy a városvédelemmel függ össze
b.) lehet, hogy a mob mozgások tiltása okozza?

fulladás előtt:
![2019-08-03_10 29 25](https://user-images.githubusercontent.com/19332825/62410257-c2af9000-b5e3-11e9-91ca-f831a3d038f5.png)

fulladás után:
![2019-08-03_10 30 06](https://user-images.githubusercontent.com/19332825/62410268-d78c2380-b5e3-11e9-88e8-b63d17d89dda.png)

**Comment by poma123** [comment]
Hát ha le van tiltva az állatok spawnolása a területen akkor törli őket, nem tudom, hogy amikor átváltozik a zombi vízbefúlttá akkor ez hogyan változik.

**Comment by Icecroft** [comment]
A területen nincs letiltva a mobok spawnolása, a zombikat spawnerből kapom.

**Comment by poma123** [comment]
@andris155 az a mob optimalizátornak vagy minek lehet ehhez köze?

**Comment by andris155** [comment]
Szerintem nincs köze hozzá.

**Comment by Icecroft** [comment]
Érdemes lenne tesztelni levédetlen területen, az rögtön kizárhatná, hogy a városvédelem okozza-e a problémát.

**Comment by andris155** [comment]
Még mindig nem jó?

**Comment by andris155** [comment]
Jónak kell lennie. De lehet befolyásolja az is, hogy a Drowned memória hibás. De ez azt 1.13.2-ben már szerintem soha nem fogják javítani sajnos.
