### ISSUE TITLE
Ötlet - Oldvillage: falusik mozgásblokkolása

### ISSUE THREAD

**Issue by Icecroft** [andris155/TheOld-Crafters#3149]
Ha a szerver terhelt, blokkol minden mobmozgást. Ennek következménye, hogy a falusikat nem tudom csillébe rakni, illetve nem is szaporodnak.
Javaslom, hogy finomítsátok a dolgot, és legalább a falusiakra ne vonatkozzon a blokkolás.

**Comment by andris155** [comment]
https://github.com/andris155/TheOld-Crafters/issues/3146
