### ISSUE TITLE
mcMMO plugin Acrobatics skill problem

### ISSUE THREAD

**Issue by Icecroft** [andris155/TheOld-Crafters#315]
![2016-10-02_11 35 33](https://cloud.githubusercontent.com/assets/19332825/19019854/d4aace42-8895-11e6-9c26-edc323bec272.png)
![2016-10-02_11 35 37](https://cloud.githubusercontent.com/assets/19332825/19019859/ec35ad7a-8895-11e6-8c01-4a8ee50bc7d7.png)
Az Akrobatika skill fejlődése nálam megállt, hiába szerzek sérüléseket esésből, nem kapok XP-t érte.
Így megrekedtem a 10-es szinten :(

My Acrobatics skill is on lvl 10, but I can't get more XP from falldamage (see screenshots)

**Comment by andris155** [comment]
Még most sem fejlődik tovább?

**Comment by Icecroft** [comment]
Szia Andris, ez valószínüleg nem hiba, hanem feature. Ha többször próbálkozom ugyanarról a helyről akkor nem ad xp-t. Ha váltogatom a helyeket, akkor kapok xp-t. Sajnos a leírásban erről nincs semmi, de szerintem nyugodtan törölheted ezt az issue-t.
