### ISSUE TITLE
AntiAFK plugin

### ISSUE THREAD

**Issue by Huntermaster0** [andris155/TheOld-Crafters#3152]
Ha annyi ármódosítás és szabálymódosítás kell az AFK farmok miatt, akkor ez a plugin lehet, hogy hasznos lenne. (vagy valamelyik hasonló plugin, ez fizetős)

https://www.spigotmc.org/resources/antiafk-prevent-afk-farming-1-7-1-14.21208/

**Comment by MrZero1** [comment]
Szerintem 5 euro nem sok érte, ha jól működik.

**Comment by poma123** [comment]
Nem rossz ötlet. Majd még utánanézek.

**Comment by poma123** [comment]
Nagyon jól bevált, köszi Hunter :D
