### ISSUE TITLE
Hibajelentés

### ISSUE THREAD

**Issue by ClearLag14** [andris155/TheOld-Crafters#3153]
Savszigeten az ellenséges és barátságos mobok nem droppolnak xp-t. (Több játékos is panaszt tett nállam) * ClearLag

**Comment by KingDeadZ** [comment]
Ha savon bent van ez az autopickupos plugin, akkor ki kell kapcsolni a configot, hogy automatán hozzád kerüljön mert nem mending kompatibilis :S

**Comment by poma123** [comment]
kész, köszi
