### ISSUE TITLE
Bérház bérlés 4-es szinttől a kezdőhelyen

### ISSUE THREAD

**Issue by RayderHUN** [andris155/TheOld-Crafters#3154]
Szerintem kicsit dobna a hangulaton ha nem mindenki tudna lepakolni pwarpokat, hanem külön lenne bérelhető "piac" tér a spawnon ahol szintén van adó, és Shopkeeperekkel lehetne árulni dolgokat. Példa: ( Mint Arcadiában a kis bolt shopkeeperekkel )

**Comment by KingDeadZ** [comment]
Lehetne az akkor lvl 4-5től elérhető, és így nem lenne az sem hogy egy kis szintű megveszi a lejárt boltot és megvan mindenje ami csak kell :))

**Comment by MrZero1** [comment]
@poma123

**Comment by poma123** [comment]
@MrZero1 már le lett tiltva 1-3 szinten a bérház, lesz valami jobb. :D
