### ISSUE TITLE
Belépés utáni meghalás

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#3156]
Az egyik játékos jelezte, hogy már másodjára van az, hogy belép a Survival szerverre és meghal, majd visszatér oda (azonnal) és a cuccai már nincsenek ott.

**Comment by poma123** [comment]
Lehet tudni időpontot, hogy ez mikor történt?

**Comment by MrZero1** [comment]
Ami jelentve lett, a második meghalás az vasárnap (múlthétvégén) 0:53, legalábbis ekkor írtak nekem dc-n

**Comment by andris155** [comment]
Gondolom lassan tölt be a chunk. Tök felesleges ezt megírni Github-ra.

**Comment by andris155** [comment]
https://github.com/andris155/TheOld-Crafters/issues/3146
