### ISSUE TITLE
Resourcepack

### ISSUE THREAD

**Issue by KingDeadZ** [andris155/TheOld-Crafters#3157]
Néhány embert kidob ha be akarja tölteni a resourcepackokat. Nem lehetne letölthetővé tenni, és aki akarja, berakja magának? Úgy nem lenne akkora hirtelen lag amikor felmegyünk a szerverre.

**Comment by MrZero1** [comment]
Máshol parancs is van rá, hogy bármikor betudja tölteni. Ha megoldható, ez is tök jó lenne.

**Comment by KingDeadZ** [comment]
Ha nagyobb városban lépsz ki, még egy jobb géppel is okozhat problémát a resource pack betöltése :D

**Comment by poma123** [comment]
A plugin ami jelenleg kiküldi a forráscsomagot (illetve ami el is készíti..) nem igazán tartalmaz ilyet.
@andris155 van esély megoldásra?

**Comment by poma123** [comment]
Egyébként ez most azért lehetett, mert egy kicsit elírtam egy textúra nevet. De csak oldvillage-n. Holnap már jó lesz, addig nem ajánlom a betöltését OldVillage-n.

**Comment by poma123** [comment]
Elvileg mától jó, tesztelem.

**Comment by poma123** [comment]
Már jó
