### ISSUE TITLE
homeolás hiba

### ISSUE THREAD

**Issue by ROxOR924** [andris155/TheOld-Crafters#3158]
Volt a havernak a telke én oda tp-ztem de ő akkor pont kitiltott a telekről engem meg eldobott egy másik telekre ami kék fallal volt körbevéve és meghaltam mert beszorultam a falba
mikor backeltem nem volt ott a cuccom

**Comment by ROxOR924** [comment]
.

**Comment by poma123** [comment]
Sajnáljuk, hogy ez történt, de sajnos ez nem egy konkrét hiba. Gondolom a saját telkedre dobott miután tiltott a telkéről, ami be volt építve. Nem tudunk felelősséget vállalni a cuccaidért
