### ISSUE TITLE
Survival/Savsziget szerver újítások

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#3159]
- [x] Bújócska minigame beállítás
- [x] Éhezőkviadala minigame beállítás
- [x] Napieventek várakozóaréna (főleg szett viselete miatt) - máshogy megolda (köszipoma♥) [szivi ♥]
- [x] Születésnapi láda (még kérdőjel az egész)
- [x] 1v1 Survivalra @andris155 
- [x] Pláza jelenlegi helyzete, ha nem használják, kikerül, spawnon van rengeteg bérelhető ház
- [x] Warpok, leírások esetleges frissítése
- [x] Szabályzat frissítése
- [x] Savsziget üvegház (??)
- [x] Survival bolt (warp) 1.14 itemek 
- [x] Szavazói láda szavazatipontért (survival, savsziget)
- [x] Savsziget pet plugin (ami oldvillagen van)
- [x] /beváltó shopba új szett, itemek, szervertől függően - Survival, Savsziget
- [x] Napieventek ládajutalmak változtatása

**Comment by MrZero1** [comment]
Ez a lista nekem van, hogy tudjam, mivel vagyok elmaradva. 
Ha bővíteni kell, szerkesztem, ha van ötlet, mi változzon, esetleg valami újítás, azt bárki jelezheti.
A listát szeretném a héten befejezni.

**Comment by andris155** [comment]
A savsziget 1.14.4 frissítés elmarad?

**Comment by poma123** [comment]
a régi gépen biztos nem lesz.

**Comment by andris155** [comment]
Az új gépen gondoltam majd.

**Comment by MrZero1** [comment]
Csak azon.

**Comment by andris155** [comment]
Az üvegházhoz kell a legújabb BentoBox és modulok, ami még kompatibilis az 1.13.2-al egyelőre. Frissítsem?

**Comment by poma123** [comment]
igen 1.13.2-n maradjon még arra lehet frissíteni

**Comment by andris155** [comment]
Frissítettem. Bent van az üvegház is.

**Comment by andris155** [comment]
Nem biztos, hogy a spawn-ra raknám azt a sok eszközkeretes boltot a pláza helyett. Szerintem ezt mindenképpen külön helyre kellene megoldani.

**Comment by MrZero1** [comment]
Mit?

**Comment by MrZero1** [comment]
#3235

**Comment by poma123** [comment]
#3235 - old láda is kész
