### ISSUE TITLE
MCMMO Skill plugin

### ISSUE THREAD

**Issue by asdlol911** [andris155/TheOld-Crafters#316]
Üdv!
Zárt helyen tapasztalt:
Elsüt egy játékos valamilyen skillt (favágás, bányászás, harcos), a skill elnyomásából keletkezett tűzijáték nagyon erős FPS esést okoz a zárt helyen bent lévőknek, számítógép minőségtől függetlenül.
Nyílt helyen:
Elsüt egy játékos valamilyen skillt (favágás, bányászás, harcos), a skill elnyomásából keletkezett tűzijáték gyenge (max 5-10) FPS esést okoz a tűzijáték közelében lévőknek, számítógép minőségtől függetlenül.

**Comment by asdlol911** [comment]
Valamint másik bug.
Kreatívban épített és növesztett fát megütöttem baltával (skillel együtt) és utána fel tudtam venni az összes fát, kivéve azt az egyet amit megütöttem.

**Comment by andris155** [comment]
Erre új jegyet kellene nyitni! És az nem kreatívos hanem mínuszba számolja, ezért nem engedi felvenni mert az vagy 0 vagy 0 alatti szám.

**Comment by andris155** [comment]
A Tüzijáték kikapcsolva.
