### ISSUE TITLE
Cat/ocelot despawn

### ISSUE THREAD

**Issue by Tarifnya** [andris155/TheOld-Crafters#3160]
tamelt és elnevezett  macskát használtam creeper farmhoz
5 chunkra a home om tol
letettem a farmba 3 macskát
/home oltam aztán /back és az elnevezett  macskák despawnoltak
(lefoglaltam előtte a  chunkot)
ezt a despawnt 4 x 3 macskával teszteltem
(OLDVILLAGE)

**Comment by KingDeadZ** [comment]
Velem is megtörtént, hogy elhomeoltam, majd eltűnt a macska, és Rayderrel is.

**Comment by poma123** [comment]
Csak a macskák tűnnek el így?

**Comment by KingDeadZ** [comment]
A kutyák ottmaradnak a helyükön, tehát igen.

**Comment by andris155** [comment]
Módosítottam a limiten. Elvileg már nem fognak eltűnni.

**Comment by andris155** [comment]
Jó lett?

**Comment by poma123** [comment]
ezt sosem tudjuk meg xd

**Comment by KingDeadZ** [comment]
jeleztem tarinak hogy tesztelje, de semmi :(

**Comment by KingDeadZ** [comment]
Kipróbáltam,nem tűntek el.

**Comment by andris155** [comment]
Szuper. Köszi.
