### ISSUE TITLE
Építész+

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#3163]
Armor Stand Editor és a goBrush iteme a kovakő (flint), nem lehetne az ASE-nek másik  itemet beállítani?

**Comment by poma123** [comment]
megnézem

**Comment by poma123** [comment]
Az ArmorStEd.-nak lehet állítani az itemét. Mi legyen?

**Comment by poma123** [comment]
Átírva blazerod-ra

**Comment by MrZero1** [comment]
Lehet azóta, de nem működik. Sem a lángrúddal, sem a kovakővel. @andris155

**Comment by andris155** [comment]
Mert el lett írva a material név így persze, hogy nem működik.

**Comment by andris155** [comment]
Már jónak kell lennie.

**Comment by MrZero1** [comment]
Köszi!
