### ISSUE TITLE
Hungergames beállítás

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#3167]
Tesztként újra beállítottam egy arénát, most már jobb a helyzet, de van még pár hiba, amit észrevettem 2 kör alatt:

- A kites részt kikellene venni, vagy tiltani azt. /hg kit <kitneve>
![kép](https://user-images.githubusercontent.com/29709854/62819993-a79dcc80-bb5d-11e9-8742-08fafd0cb420.png)

- A szövegekről a vastagítást szerintem lelehetne venni, eléggé csúnya, valamint a visszaszámlálásnál a fehér szín helyett lehetne mondjuk a &c (piros).
![kép](https://user-images.githubusercontent.com/29709854/62819997-c3a16e00-bb5d-11e9-9af0-3be883189449.png)

- Itt a PvP Engedélyezve részhez kicsi 'e' betű kell. 
![kép](https://user-images.githubusercontent.com/29709854/62820006-e59af080-bb5d-11e9-9d13-3c6b29a4c25b.png)

- Az item nevét nem lehet átírni (gondolom nem) angolról magyarra?
![kép](https://user-images.githubusercontent.com/29709854/62820012-f9deed80-bb5d-11e9-8066-bc23d3f640b3.png)

- Tejesvödör, véggyöngy, OP almák (amik alapból tiltva vannak az eventvilágban) kivenni a lootchestekből (random rakja bele a cuccot a ládákba), mert nem lehet használni őket és csak probléma lenne/van belőle.
![kép](https://user-images.githubusercontent.com/29709854/62820020-1d099d00-bb5e-11e9-99cf-3a3c1ac93763.png)

- Nem tudjál használni a /hg leave parancsot, a játék tiltja. Amikor vége a játéknak, nem dobja ki a lobbyba, és ezt írja ki nekik:
![kép](https://user-images.githubusercontent.com/29709854/62820044-838ebb00-bb5e-11e9-8701-ece75164e819.png)

Így úgy érzékeli, hogy van bent játékos, és nem is lehet csatlakozni újra abba az arénába

Plusz ami engem zavar, hogy 3 tábla kell 1 aréna csatlakozásához. Erre van valami beállítási lehetőség?

![kép](https://user-images.githubusercontent.com/29709854/62820058-ccdf0a80-bb5e-11e9-9ad8-9c8de99361f4.png)

**Comment by falcon0607** [comment]
Ha egy játékos le lövi a másikat azt fogja írni a játák, hogy egy csontváz lőtte le nem pedig az adott player.

plusz van még egy kis szöveg hiba is.
![Képkivágás](https://user-images.githubusercontent.com/40804615/62820127-285dc800-bb60-11e9-8b6b-d3bb5e8c117f.PNG)

**Comment by andris155** [comment]
Az internal error-t pontosan mikor írta a játékosnak?
A többit javítottam.

**Comment by andris155** [comment]
Holnap betölt a javítás.
