### ISSUE TITLE
Furniture Bugok.

### ISSUE THREAD

**Issue by HELLCATGHOST** [andris155/TheOld-Crafters#317]
Minap felléptem a szerverre és észrevettem hogy a furniture-os dolgaim eltűntek.

**Comment by Kayalafur** [comment]
Csatlakozom HELL kollégához, eltünt amit csináltam furnis cucc, illetve a strandon volt még furnis cucc az is eltünt, azt nem én csináltam.

**Comment by andris155** [comment]
Ha ismét eltűnik akkor írjatok. Köszönöm!

**Comment by andris155** [comment]
elvileg megoldódott
