### ISSUE TITLE
Nem megy a vote

### ISSUE THREAD

**Issue by andris155** [andris155/TheOld-Crafters#3170]
Nyitni kell hozzá lan-ban portot, hogy a Docker-ek tudjanak egymással kommunikálni. Sajnos csak újraindítással tölti ezt be így csak holnap lesz jó.

**Comment by poma123** [comment]
a holographic displays se tudott mit kezdeni a localhost ipk-kel, de akkor holnapra lesz elérhető/nemelérhető felirat loginban :D

**Comment by andris155** [comment]
Annak nem biztos, hogy az a baja. Próbáld meg a 172.18.0.1-es IP címmel.

**Comment by poma123** [comment]
nem jó

**Comment by andris155** [comment]
`use-RedisBungee: true`
mi ilyet nem használunk, lehet ez a baja.

**Comment by poma123** [comment]
kikapcsoltam, úgy se jó :)

**Comment by andris155** [comment]
A vote már jó. Mi nem működik a holographic displays-ben? A játékosokat úgy láttam kiírja.

**Comment by poma123** [comment]
a {status: server} nem működik. a játékosok száma sem működik, azt placeholderapi-val oldottam meg. (holo-val {online: server} lenne.)

**Comment by andris155** [comment]
A 172.18.0.1-vel pedig működnie kellene. Azon futnak a szerverek. Esetleg még próbálkozz meg a 172.18.0.2-vel. De ha ezek nem jók, akkor nincs ötletem erre.

**Comment by poma123** [comment]
azzal se jó

**Comment by andris155** [comment]
Akkor nem tudom mi baja. Az összes szerver pedig a 172.18.0.1-es IP-en fut lan-ban.
