### ISSUE TITLE
OldVillage - "Számla"

### ISSUE THREAD

**Issue by poma123** [andris155/TheOld-Crafters#3171]
Egy olyan egyenleg, ami csak a ládabolt eladásokat és vásárlásokat nézi, illetve a 15 percenkénti online időért járó pénzt. Ezzel nagyon sok kijátszás előzhető meg. A szintlépés ezt az egyenleget fogja ellenőrizni.

**Comment by poma123** [comment]
Illetve ezzel elérhetővé válhatnak a bérházak 4+ szinten.
(#3154 )

**Comment by Niccolettie** [comment]
okay but i have one more question. és a lottó? :D

**Comment by SurvivorTheReal** [comment]
Ez tök jó amúgy, mert nem az van hogy elköltöd a pénzed valami fontosra és akkor megint farmolsz 1-2 napot, csak farmolsz, hogy tudj majd szintet lépni

**Comment by poma123** [comment]
> okay but i have one more question. és a lottó? :D

kész

**Comment by poma123** [comment]
a lotto, a chatreaction es a szavazas is a szamlara is ad penzt.
