### ISSUE TITLE
Vélemény: hogyan lehetne jobbá tenni az Oldvillage szervert!

### ISSUE THREAD

**Issue by falcon0607** [andris155/TheOld-Crafters#3172]
Sziasztok, sokat gondolkodtam azon, hogyan lehetne jobbá tenni az oldvillage szervert. Félreértés ne essék, poma egy igazán remek szervert hozott létre, de egyre több olyan válzotás történt ami rossz irányba sodorta Magyarország egyetlen ilyen szerverét. Ezért azt szeretném kérni az adminoktól, hogy ezt a bejegyzést ne zárják be mind addig míg nem jutottak a játékosok és a staffok egy közös megegyezésre. A játékosoktól pedig azt kérem, hogy normálisan, kulturált körülmények között vitassák meg ezt a témát. :D

**Comment by MrZero1** [comment]
Úgy gondolom, olyan változások történtek, amelyeket a szerver hosszútávú fennmaradását eredményezi. 
Gondolok itt az antiafk pluginra. Egy olyan szerveren, ahol a játékidő a nagyúr, másképp nem lehet szűrni az afkfarmosokat. 
Inkább ez, mint a piaci árak módosítása olyan irányba, ami nem fair. (már volt ebből is gond)

Bármiféle észrevételt, negatív, pozitív kritikát elfogadunk persze.

**Comment by poma123** [comment]
Barmi konkret eszrevetelt vagy otletet, kritikat elfogadunk, ugyhogy ezt most bezarom
