### ISSUE TITLE
Ötlet

### ISSUE THREAD

**Issue by Trymer1** [andris155/TheOld-Crafters#3174]
Survival szerveren hatékonyabb, gyorsabb eladási lehetőség, árváltozás nélkül. A nagy "termelőknek" így nagyon sokat kell mászkálni és ezt nagyon meg lehet unni hamar, ezzel lehetne könnyíteni egy kicsit, szerintem sokan használnák.

**Comment by MrZero1** [comment]
Talán a leghatékonyabb megoldás a shopGUI lenne, de azzal meg jó sok munka van (@poma123 tudja, savon mennyi idő volt az a kevés dolgot beállítani). De ha van rá igény, átgondoljuk

**Comment by andris155** [comment]
Lehet letölteni hozzá kész konfigokat az mc-market-ről. Ott max az árakat kell átírni.

**Comment by MrZero1** [comment]
Az remek, de a boltban nem kész konfig van az mc-marketről.:D

**Comment by poma123** [comment]
Csak az arakat nehez xdd

**Comment by poma123** [comment]
nem olyan egyszeru

**Comment by andris155** [comment]
Ez szerintem nagy segítség hozzá. Bár sajnos az mcMMO-t és egyéb extra módosításokat ez nem veszi figyelembe.
https://www.planetminecraft.com/blog/how-to-create-stable-prices-system-on-your-server/

**Comment by Trymer1** [comment]
SellWand plugin egész egyszerű, igaz sok árat kell állítani hogy minden meglegyen benne. Akár OCDért is lehetne venni sokszor használható ilyen eszközt.

**Comment by andris155** [comment]
Ha akarunk ilyen inkább EssentialsXXMPP legyen hozzá.

**Comment by andris155** [comment]
Mivel van bolt és 2 helyen pedig nem fogja senki átírni mindig így szerintem ez nem fog bekerülni.
