### ISSUE TITLE
Pet

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#3175]
Survival és Savsziget szerverre az Oldvillage-s pet berakása.

Mobbefogó survivalra (feltéve ha a falusit nem lehet vele befogni), szavazói pontért.

**Comment by andris155** [comment]
Ugyan úgy legyen beállítva mint az OldVillage-n?

**Comment by MrZero1** [comment]
Írok privátot ezügyben.

**Comment by MrZero1** [comment]
Így, hogy visszakerült Survivalra a mypet, savszigetre lehetne csak a pet/mobbefogó (esetleg).

Kérdés, hogyan juthatnának hozzájuk? Játékpénzért?

**Comment by andris155** [comment]
Én szívesen berakom, de oda legyen külön beállítva, vagy ugyan úgy? Az, hogy hogyan jutnak hozzá pedig szerintem inkább közös döntés legyen a staffokkal.

**Comment by MrZero1** [comment]
Küldetéseken keresztül megoldható lenne? @andris155

**Comment by andris155** [comment]
szerintem meg.

**Comment by MrZero1** [comment]
Akkor jár a küldetések után pet? @andris155

**Comment by andris155** [comment]
Egyelőre semmi leírást nem kaptam, hogy melyik küldetés után mi járjon. :D

**Comment by MrZero1** [comment]
Ha nem kérsz, úgy nem tudjuk, mi kell hozzá.

**Comment by andris155** [comment]
Kellene az, hogy melyik küldetés adja és milyen petet? Illetve, ha új küldetések adják, akkor az is, hogy pontosan milyen küldetések.

**Comment by MrZero1** [comment]
Sweetan javaslata:
“ Youtube - Youtube Pet

Kuldik: Fejezetenkent
1. Kezdo: - Fold sarkany
	  - Goblin sarkany
	  - Jegesmedve
	  - Superman
 
2.Hozzaerto: - Sarga Sarkany
	     - Sotet Sarkany
	     - Oroszlan
	     - PedoMaci (ha lehet akkor meg valtoztatni a nevet ha nem akkor maradhat ugy is)
 
3. Szakerto: - Magikus Sarkany
	     - Mistikus Sarkany
	     - Zsiraf	
	     - Beka
 
4. Halado: -Szellem 
	   - BB-8
	   - Momo
	   - Kacsa

5. Elit: - Jeg Sarkany
	 - Tuz Sarkany
	 - Kutya 
	 - Potato man 



Token Shop:
	   - Groot
	   - Pikachu
	   - R3D3
	   - Panda
 	   - Teknos
	   - Mini onmagad”

**Comment by MrZero1** [comment]
Valami? @andris155 @poma123

**Comment by MrZero1** [comment]
Akkor ez egy nem.
