### ISSUE TITLE
Oldvillage

### ISSUE THREAD

**Issue by poma123** [andris155/TheOld-Crafters#3176]
- [x] első 4 szinten lévő játékidő feltétel törlése
- [x] Négyes szint "felszerelés" kit fejlesztése
- [x] Állítás az AFK pluginon
- [x] Horgásztó 1-3 szinten

**Comment by SurvivorTheReal** [comment]
Lehet olyat kérdezni mi fog változni az afk pluginon?

**Comment by poma123** [comment]
> Lehet olyat kérdezni mi fog változni az afk pluginon?

10pnel 15pnel kidob

**Comment by skrisz0101** [comment]
[pipa] Új warp
