### ISSUE TITLE
Craftbook

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#3177]
A craftbook-os dolgokhoz csak sima tölgytábla használható, a többi féle táblával nem jó. Nem tudom, hiba e vagy sem, vagy hogy támogatja e egyáltalán a többi táblát

**Comment by andris155** [comment]
Mivel 1.13-al nem lenne kompatibilis így egyelőre nem írta meg a fejlesztő ezt.

**Comment by MrZero1** [comment]
Köszi a választ.

**Comment by andris155** [comment]
Elvileg már támogatja a többi táblát is.
