### ISSUE TITLE
Javaslat

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#3178]
Old Szerszámíj a Minemarketbe. Ha jól tudom, 2 féle maxos számszeríjat lehet csinálni, mivel 1-1 enchant nem kompatibilis a másikkal. 

Ha bekerül, megcsinálom az itemet

**Comment by andris155** [comment]
melyik nem kompatibilis?

**Comment by MrZero1** [comment]
@andris155  többszörös lövés és átdöfés

**Comment by andris155** [comment]
Megcsinálhatod, ha szeretnéd aztán berakom.

**Comment by andris155** [comment]
kész
