### ISSUE TITLE
Ötlet MCMMO

### ISSUE THREAD

**Issue by KulGery** [andris155/TheOld-Crafters#3179]
Igazság szerint egy szerintem hiba miatt kiváncsi lennék hogy az egyes tulajdonságok melyik szintnél lépnek, azaz pl a fadöntés ideje mikor változik, és mennyivel. 
Nekem most 77-es szintem van, ennél a szintnél milyen hosszú kellene legyen a fadöntés?
Ugyanígy a bányászásnál a szupertörés hossza, 64-es szinten van a bányászásom, milyen hosszú kellene legyen a szupertörés?

Tehát akár itt a github-on, akár a OldCraft weboldalán, jó lenne, ha lenne egy táblázat, amin látható lenne. Már csak hibaelemzés miatt is.

A múltkor, amikor fejlesztés volt, arra fogtátok, hogy alacsony lett a szint. akkor megdolgoztam, hogy újra nőjön meg. De most megint nem stimmel...

Üdv. KulGery

**Comment by andris155** [comment]
A Wiki oldalon van, amit tudni lehet. https://mcmmo.org/wiki/Main_Page
Ennél többet az oldcrafters sem tudna kiírni. De nem lesz kiírva, mert olyan sokszor változik, hogy rengeteg munka lenne mindig frissíteni.

**Comment by KulGery** [comment]
Köszi
