### ISSUE TITLE
Kreatív limitáló plugin hiba. (plotworld)

### ISSUE THREAD

**Issue by AtiPLS** [andris155/TheOld-Crafters#318]
Ha kreatívban leraknak egy blokkot a telekre akkor az kreatívossá válik.
Ezzel nincs semmi gond de ha a telek resetelve lessz és törölve lesznek a blokkok, a plugin azt hiszi hogy még mindíg ott van.
Ha egy túlélőben lerakott blokkot viszont a helyére teszünk, a plugin azt hiszi hogy nem változott semmit, kreatívos a blokk.
[Példa](https://gyazo.com/c61542b6642b07b8f782936278e677ae)

**Comment by andris155** [comment]
https://github.com/andris155/TheOld-Crafters/issues/185
