### ISSUE TITLE
OldVillage repülés (bug)

### ISSUE THREAD

**Issue by poma123** [andris155/TheOld-Crafters#3180]
Van egy kis probléma az alap repülés ellenőrzővel, mert sokan mondják hogy kidobja őket pedig nem repülnek. Ezen lehetne állítani, @andris155 ?

**Comment by andris155** [comment]
A vanilla Minecraft server része. Nem lehet rajta állítani, csak ki és be kapcsolni. De kikacsolni nem jó ötlet szerintem.

**Comment by SurvivorTheReal** [comment]
Akkor eddig miért nem csinálta ezt? +belaggolok tőle 10 másodpercekre néha.

**Comment by skrisz0101** [comment]
Nekem is feltűnt hogy mostanság egyre ritkábban jelez be

**Comment by skrisz0101** [comment]
Gyakoribban* xd

**Comment by poma123** [comment]
Az ncp nem képes letiltani a repülést vagy mi? Kajak vanilla mechanicot használunk a fly ellen?

**Comment by andris155** [comment]
Az ncp-s szerintem még hibásabb, de kipróbálhatjuk ha gondolod.
