### ISSUE TITLE
Ötlet - luckyblock

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#3181]
Ha már van lucky csáki, kard, stb, akkor lehetne már lucky ásó, balta, kapa is. Akár horgászbot

**Comment by andris155** [comment]
Ezt kérlek a plugin fejlesztőjének írd meg angolul: https://github.com/SickSkillz/SLB-Tracker/issues
Lehetne egyedit belerakni, de szerintem ennek inkább az alap plugin-ban lenne helye.

**Comment by skrisz0101** [comment]
Jaj a Google fordítós angolt remélem majd megérti
