### ISSUE TITLE
OldVillage - Küldetések

### ISSUE THREAD

**Issue by poma123** [andris155/TheOld-Crafters#3182]
skrisz :)

**Comment by skrisz0101** [comment]
<név>

8 endvirág
48 refréngyümi
48 purpueblokk

Jutalom 1v2 shuljerhéj

**Comment by skrisz0101** [comment]
POKOL

Pokoli túrázó:
64 lélekhomok
48 magmablokk
64 netherrák
48 nethertégla
48 izzókőporblokk
Jutalom:  1/2 withercsontifej

Tűzmérnök
5 lávásvödör
32 magmakrém
64 lángrúd
jutalom: 3x64 sín

Pokoli gyilkos
64 lángrúd
32 magmakrém
1 withercsontifej
5 szellemkönny
32 rohadthús
1 gyémántkard
Jutalom:  1 életmentés toteme

**Comment by skrisz0101** [comment]
VÍZ

A tenger lelke
1 csatorna és 5 tenger szíve
Jutalom: szigony

KorallGyűjtő
#lustavagyokleírni
32 mindenfajta korallból (blokk)
16 macskaköröm (ami oldalra is nő)
8 macsakaköröm (a nagyobbik)
Jutalom: 8db vízbefúlt tojás

Akvárium
32 lazac
16 tőkehal
8 trópusi hal
5 gömbhal
Jutalom:  1db vén őrszemet idéző tojás

**Comment by KingDeadZ** [comment]
nagyon limitált lenne szerintem a tenger lelke küldi, mert nincs akkora a map hogy 20-30 ember tudja teljesíteni akár xD

**Comment by skrisz0101** [comment]
Akkor mondj te valamit

**Comment by poma123** [comment]
tudsz sk helyette másikat?

**Comment by skrisz0101** [comment]
Neee :(
 @poma123
