### ISSUE TITLE
OldVillage Hibajelentés

### ISSUE THREAD

**Issue by JAndrasS** [andris155/TheOld-Crafters#3185]
Ha a netherben lebegő sóderen használom a collapse (földidomár ) képességet akkor az amikor lejjebb megy kőblokká vátozik.

TheLord

**Comment by poma123** [comment]
Igen, ez nem hiba, ez direkt van így. Ahogy a képesség összenyomja a sódert, az úgy összetömörül, hogy tömör kő lesz :D
