### ISSUE TITLE
Hibajelentés - Survival-Eventek

### ISSUE THREAD

**Issue by Niccolettie** [andris155/TheOld-Crafters#3188]
Run eventen voltam, át akartam menni egy másik eventre és nem engedett "üres eszköztárral és túlélő módban" kellett volna lennem :D (és valószínűleg nem túlélő mód van az eventeken mert a kaja és élet nem fogy/regenerálódik)

**Comment by poma123** [comment]
melyik eventen voltál?

**Comment by Niccolettie** [comment]
sima run-ról akartam átmenni a run2-re

**Comment by MrZero1** [comment]
A kaja flag miatt nem fogy, azt a napokban állítottam be. Felfedező (gm2) játékmód van némelyik eventen, azért nem enged át.

**Comment by poma123** [comment]
ready
