### ISSUE TITLE
Hibajelentés - Survival-hg

### ISSUE THREAD

**Issue by Niccolettie** [andris155/TheOld-Crafters#3190]
ha az oldalon valaki old cuccot vesz és közben belép HG arénába akkor is bedobja a tárgyat az invjébe és így pl. OLD kardja lehet :)

**Comment by MrZero1** [comment]
Tudunk róla, viszont nem tudunk mit csinálni vele. Aki vesz, az így járt, mert ha vége a meccsnek, törli az invet
