### ISSUE TITLE
Figyelemhiány:(

### ISSUE THREAD

**Issue by riddimordie** [andris155/TheOld-Crafters#3191]
Szellemileg sérült személyiség vagyok, akire az égvilágon senki sem figyel. Pedig igényli a figyelmet, különben nem itt hívja fel a figyelmet magára. Hali

**Comment by MrZero1** [comment]
xdddddd

**Comment by riddimordie** [comment]
És mellesleg szeretnék egy happy meal menüt! :(

**Comment by riddimordie** [comment]
és hogy leugorj egy hídról, MrZero! :D

**Comment by MrZero1** [comment]
Köszönöm a jókívánságokat, szerintem te előbb teszed meg, amilyen lelkisérült vagy. :D

**Comment by riddimordie** [comment]
Ahogy mondod!

**Comment by MrZero1** [comment]
puszi neuro!

**Comment by MrZero1** [comment]
Ajánlom Bimbó Melinda, Pszichológust Pesten, Teréz krt. 45, 1067 a címe. Tárt karokkal vár! ♥ Kitartást neked!
