### ISSUE TITLE
Hibajelentés - Survival

### ISSUE THREAD

**Issue by Niccolettie** [andris155/TheOld-Crafters#3192]
Falldown event elejéről eltűnt a pókháló, így nem lehet elkezdeni az eventet, mert mindenhogyan halálos az első 2 másodpercben :)

**Comment by MrZero1** [comment]
Teljes átalakítást igényel az event, így, hogy nem kell élelmet vinni. Pókhálóval vagy félperces event, anélkül lehetetlen.

**Comment by MrZero1** [comment]
Majd egy tesztelő kellene, aki megnézi, mennyire halálos most.

**Comment by Niccolettie** [comment]
tökéletes, kivihető :)
