### ISSUE TITLE
Savsziget

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#3193]
Most ez bug e vagy sem, nem tudom, de jelezték, teszteltük. Mutatom.

Pandikusznak jelezték, hogy lehet bugoltatni a vizet (?). Szigeten kívül, ami már nem a játékosé.
Pandi szemszöge: 
![kép](https://user-images.githubusercontent.com/29709854/63706550-063a9a00-c830-11e9-8448-bcbdbaf608ca.png)

Enyém:

![kép](https://user-images.githubusercontent.com/29709854/63706568-0fc40200-c830-11e9-8427-5f268b323f0a.png)

Elvileg így lehet a vízalatt építkezni vagymi, de én nemtudom bugnak minősül e. Gondolom blokkváltozásnál visszatér oda a víz.

**Comment by andris155** [comment]
Csak úgy látja, de attól még ott van. Szerintem ezt nem lehet másképp megoldani sajnos.
