### ISSUE TITLE
Telkeken nem megy a táblásbolt 2

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#3194]
Ismét nem megy a ploton a ládabolt. #2611

Annál a hibajelentésnél a /p flag remove use parancsot írtad, de most ezt írja ki a játékosoknak rá:
![kép](https://user-images.githubusercontent.com/29709854/63756395-958b9000-c8b8-11e9-84fa-2590af48cc22.png)

**Comment by andris155** [comment]
Csak akkor törölje, ha mindent engedélyezett rajta.

**Comment by andris155** [comment]
Adja hozzá az use flag-al melyik tábla működjön.

**Comment by andris155** [comment]
Ezek a lehetséges értékek.
- ACACIA_SIGN
- ACACIA_WALL_SIGN
- BIRCH_SIGN
- BIRCH_WALL_SIGN
- DARK_OAK_SIGN
- DARK_OAK_WALL_SIGN
- JUNGLE_SIGN
- JUNGLE_WALL_SIGN
- OAK_SIGN
- OAK_WALL_SIGN
- SPRUCE_SIGN
- SPRUCE_WALL_SIGN
