### ISSUE TITLE
Hibajelentés - Survival NPCk

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#3195]
A falusiak a spawnon, nem reagálnak a játékosokra. Elvileg nem ír ki semmit, de nem csinál semmit. Nekem igen.

Namost, van benne pár dolog ami változott.

Építész TGF leírása

Itt már más a menete. Esetleg a weboldalon lévőt belelehetne írni, plusz a tagfelvételes oldalra irányíthatna az is.

Segítő TGF link 
![kép](https://user-images.githubusercontent.com/29709854/63770059-93cfc580-c8d4-11e9-9ff6-2bd038675593.png)

Új link ugye ez : https://www.oldcrafters.net/tagfelvetel/

**Comment by MrZero1** [comment]
Ép TGF: 
![kép](https://user-images.githubusercontent.com/29709854/63770235-ffb22e00-c8d4-11e9-8b2d-192308cac9da.png)

Már nem ez a menete ennek, azért elavult

**Comment by andris155** [comment]
Lehet majd csak újraindítással lesz rá joguk.

**Comment by andris155** [comment]
De talán jobb is, ha nem is jó a szöveg még. :D

**Comment by poma123** [comment]
csinalok hozza konfigot h ne a kodban legyen a szocveg

**Comment by poma123** [comment]
kesz, konfigban atirhato
