### ISSUE TITLE
Ötlet - levédés az életteleneknek

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#3196]
A max 100k levédést lehetne növelni, hátha valami élettelen kimaxolja (vagy már kimaxolta :x)

**Comment by MrZero1** [comment]
Te már kimaxoltad :open_mouth: :thinking:

**Comment by MrZero1** [comment]
Lehet 200-300k is, főleg, hogy nincs RG (mert nincs rá normális rendszer :((()

**Comment by andris155** [comment]
átírtam 200e-re
