### ISSUE TITLE
OldVillage - Városhatáron átlépéskor title

### ISSUE THREAD

**Issue by poma123** [andris155/TheOld-Crafters#3198]
### Legyen ehhez hasonló cím megjelenítve, amikor valaki belép vagy kilép egy város területéről?
![image](https://user-images.githubusercontent.com/25465545/63890219-c49e2080-c9e2-11e9-9153-418dff22b742.png)

                 👍 = Igen                                                   👎 = Nem

**Comment by MrZero1** [comment]
:likemen: (like) (y) jesz

**Comment by poma123** [comment]
Holnap betölt :D
