### ISSUE TITLE
OldVillage város telekrendszer

### ISSUE THREAD

**Issue by Kelvin172** [andris155/TheOld-Crafters#3199]
Az lenne a problémám, hogy én egy város telkén vagyok. Úgy van beállítva, hogy rajtam kívül csak a polgármester tudjon hozzáférni a dolgaimhoz, viszont áthívtam egy másik városban lévő játékost és ő bele tudott nézni a shulker boxaimba és be tudott tenni és ki tudott venni itemeket belőle. A shulker boxomon kívül semmihez nem tudott hozzáférni. Csak a shulker box a probléma.

**Comment by poma123** [comment]
pedig nincs engedélyezve, milyen színű box volt?

**Comment by poma123** [comment]
@Kelvin172

**Comment by KingDeadZ** [comment]
sosem tudjuk meg, szerintem fölösleges itt pingelni xD

**Comment by poma123** [comment]
kingdead köszi a véleményed, viszont ha van ilyen hiba az elég rossz :D ha nem válaszol úgy is le fogom zárni :)

**Comment by KingDeadZ** [comment]
érdemes lenne máshol felkeresni szerintem egyébként

**Comment by poma123** [comment]
én nem fogok utána futkosni. mivel válaszol lezárom
