### ISSUE TITLE
Craftbook Pipe Gondok

### ISSUE THREAD

**Issue by Kronox12** [andris155/TheOld-Crafters#32]
A csövek nem küldenek itemeket hopperekbe,és brewing standekbe(főzőállványba).Továbbá még mindig fenn áll az a gond,hogy néha kiírja az area.us-permission szöveget,ezt megoldja az,ha arrább rakjuk az input pistont,de kicsit zavaró.Valamint kérek majd a plugin írótól egy másik módot,amivel a piston mindig aktív,és redstone jel nélkül is továbbít minden itemet.

**Comment by andris155** [comment]
Nálad se küld a teszt szerveren tárgyakat, a főzőállványba, és a tölcsérbe?

**Comment by Kronox12** [comment]
Nem beza.

**Comment by andris155** [comment]
Akkor plugin hiba lesz.
