### ISSUE TITLE
Buggot találtam

### ISSUE THREAD

**Issue by Doma75** [andris155/TheOld-Crafters#320]
A szerveren nem működik a szíkrábol pattant echant

**Comment by andris155** [comment]
Üdv!
Mi a gond vele?

**Comment by geri5200** [comment]
Nekem se megy próbáltam OldKarddal mind a kettő fajtával és sima szikra enchantos karddal egyikkel se gyűjtotta fel a mobokat

**Comment by andris155** [comment]
javítva elvileg.
