### ISSUE TITLE
Hibajelentés - eltűnik a panda

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#3200]
Levédett területen akartam petnek befogni pandát. De ha megütöm egy lasszóval, akkor eltűnik. Kipróbáltam kb 6 pandával, mind eltűnt. (MrZero-nak megmutattam)

**Comment by MrZero1** [comment]
Ellenben nekem azon a levédésen jó volt, betudtam fogni petnek

**Comment by SurvivorTheReal** [comment]
Lehet azért mert főadmin vagy, csak egy ötlet.

**Comment by MrZero1** [comment]
Igen, lehet azért, de ez azt jelenti, hogy alapjáraton jónak kellene lennie

**Comment by skrisz0101** [comment]
@andris155

**Comment by andris155** [comment]
videó kellene erről.

**Comment by skrisz0101** [comment]
nem csak akkor történik ez ha lasszóval ütöm meg, hanem ha csak simán megütöm.

**Comment by skrisz0101** [comment]
nem támogatja az mp4-et, hogy küldjem be? ':D

**Comment by andris155** [comment]
youtube

**Comment by skrisz0101** [comment]
Megoldottam. A nomonsterspawn flag zavar be. Ugye ha mob van a területemen akkor, ha tiltva van a spawn és megütöm, akkor eltűnik.
Valamiért mobnak érzékeli a pandát
@andris155

**Comment by andris155** [comment]
De azért videót nem csináltál. :/

**Comment by skrisz0101** [comment]
Csináltam de nincs yt csatim és lusta vagyok csinálni 😂

**Comment by andris155** [comment]
A Google fiókhoz szerintem kb. mindenkinek van.

**Comment by andris155** [comment]
Javítva
