### ISSUE TITLE
Minemarket

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#3201]
Hali, lehet csak nekem nem jó, de ha erre a részre kattintok, üres oldalra dob be.

![kép](https://user-images.githubusercontent.com/29709854/63927594-4c6d4480-ca4e-11e9-9600-edda0703a0ce.png)

![kép](https://user-images.githubusercontent.com/29709854/63927602-53945280-ca4e-11e9-96d3-ca76dff02113.png)

**Comment by andris155** [comment]
Már nincs ilyen oldal.

**Comment by andris155** [comment]
Kivettem.
