### ISSUE TITLE
poma123 pluginjai frissítésre szorulnak a savszigeten

### ISSUE THREAD

**Issue by andris155** [andris155/TheOld-Crafters#3202]
@poma123 
Eventrendszer, kezdes stb...

**Comment by poma123** [comment]
...

**Comment by poma123** [comment]
szuper amikor nem vagyok frissiteni kell 1.14re

**Comment by andris155** [comment]
Fogalmunk sincs mikor vagy, vagy mikor leszel sajnos.

**Comment by poma123** [comment]
inkább fbn beszéljük ezt ne itt

**Comment by poma123** [comment]
kész
