### ISSUE TITLE
Savsziget termés "bevonzása" Hibajelentés

### ISSUE THREAD

**Issue by KulGery** [andris155/TheOld-Crafters#3204]
A nádföldemen 1.13.2-ben a teéjes beacon mellett futva végigmenve is fölszedte mind a lehulott termést.
1.14.4-ben viszont még a méterre levő termést is otthagyja, úgy, hogy lassan sétálok.

Visszafele sétálásnál már felszedi... Csak így kétszer kell végig sétálnom ugyanazt a területet.

**Comment by andris155** [comment]
Ez milyen plugin? Vagy ez az alap játék része?

**Comment by KulGery** [comment]
Én nem tudom, hogy ezt plugin vagy mi csinálja, csak a tapasztalatomat írom le. 
1.13.2-ben mindent felszedett ahogy futottam "teljes fényben" azaz két +1 lovas beaconnal.
1.14.4 ben meg még ha sétálok akkor is van, hogy nem szedi fel, hanem hátam mögött marad.
Persze lehet hogy az 1.14.4 hosszabb a válaszideje, és így túlsétálok rajta mikorra felvehető lesz. Vagy mittomén.

**Comment by andris155** [comment]
Azóta jobbnak kell lennie. Ha nem jobb, akkor nem tudok sajnos ezzel mit kezdeni.
