### ISSUE TITLE
/warp eventek hiba

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#3207]
Ki lehet bugoltatni a piros üveglapot, elég csak a számgombokkal berakni valamelyik craft slotba, kikapcsolni a netet amíg kickel a szerver, aztán visszamenni, átkerül a survival invbe.

**Comment by andris155** [comment]
Ez amúgy minden menüvel megy nem?

**Comment by andris155** [comment]
@poma123 ez a menü a te plugin-odban van szerintem.

**Comment by andris155** [comment]
<img width="262" alt="Annotation 2019-09-02 215554" src="https://user-images.githubusercontent.com/8324198/64131967-7e730380-cdcc-11e9-83e2-502f6913974a.png">

**Comment by andris155** [comment]
<img width="601" alt="Annotation 2019-09-02 215938" src="https://user-images.githubusercontent.com/8324198/64132056-f8a38800-cdcc-11e9-94b0-228c6e19d066.png">

**Comment by poma123** [comment]
kellene egy video rola

**Comment by UDPSendToFailed** [comment]
@poma123 https://youtu.be/78LH3UZSsgI

**Comment by poma123** [comment]
ez a bújócskás várakozóban is megy?

**Comment by UDPSendToFailed** [comment]
Nem, ott nem engedi a számgombokkal átrakni más slotba a menü itemeket.

**Comment by poma123** [comment]
lol és tényleg működik

**Comment by andris155** [comment]
508 OCD

**Comment by andris155** [comment]
+ pont a minőségi videóért és ugye, hogy nem volt nehéz? Mások itt sírnak, hogy nem tudnak videót csinálni...
