### ISSUE TITLE
Hibajelentés - Survival levédés

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#3208]
RedDead levédte, kb július közepén, 33 órája pedig Faramuci rongált a levédett területén.

![kép](https://user-images.githubusercontent.com/29709854/64069637-c4558d80-cc4d-11e9-9ff8-a46d5ce990c6.png)

**Comment by MrZero1** [comment]
![kép](https://user-images.githubusercontent.com/29709854/64069642-d7685d80-cc4d-11e9-9f2f-11949215d4e2.png)

**Comment by andris155** [comment]
Talán hozzá volt adva (?)

**Comment by MrZero1** [comment]
Elmondása szerint nem volt hozzáadva

**Comment by andris155** [comment]
Nem tudom sajnos, akkor hogyan szedte ki.
