### ISSUE TITLE
Savsziget cobblestone item eltűnik Hibajelentés

### ISSUE THREAD

**Issue by KulGery** [andris155/TheOld-Crafters#3209]
A kitört, vagy eldobott cobblestone item 15 secundum után eltűnik
Hídat bontottam, és nem tudtam felszedni a itemeket, mert mire a felszínre ért el is tűnt.
Egyenlőre csak a cobble stone, farönk, és fáklya nem.

**Comment by andris155** [comment]
Holnap jó lesz.
