### ISSUE TITLE
Furniture lerakás

### ISSUE THREAD

**Issue by NBabi** [andris155/TheOld-Crafters#321]
3 db Fence furniture van a telken, 16 a limit, a 6. fence-t (kerítést) már nem engedte lerakni, és a képen látható szöveget írja ki. Amikor leraktam a 16 megengedett itemet, még engedte. Most már nem enged lerakni. ( A maradék 3 kerítést bútort illetve a 13 másikat is, körülbelül 121 órája raktam le co i szerint.)
![2016-10-19_17 03 54](https://cloud.githubusercontent.com/assets/22939109/19524582/7bf680ca-961e-11e6-900e-1b2266a9b522.png)

**Comment by andris155** [comment]
Másnap sem frissült a limit?

**Comment by NBabi** [comment]
megoldódott :) :+1:
