### ISSUE TITLE
Hibajelentés - Survival - 1v1

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#3210]
![kép](https://user-images.githubusercontent.com/29709854/64081867-350cb080-cd07-11e9-9b33-d4eb88478957.png)

Ez túl fura. :D Képen minden rajtavan

**Comment by andris155** [comment]
Talán a bújócska + Vanilla Additions együttes hibája miatt van ez. A fejlesztőnek már jelentettem. Szerintem lehet soha nem kerül sajnos ez már javításra.
