### ISSUE TITLE
Savsziget: védelmi hiba

### ISSUE THREAD

**Issue by Icecroft** [andris155/TheOld-Crafters#3212]
A savszigeteken az édes bogyókat bárki leszüretelheti, azok is akiknek semmi jogosultságuk sincs a szigeten.

**Comment by MrZero1** [comment]
Ez sajnos survivalon is így van.

**Comment by andris155** [comment]
A telkeken vagy a griefprevention védésen nem védett?

**Comment by andris155** [comment]
A griefprevention-nak védenie kell ezt, akkor a telkeken nem védett?

**Comment by andris155** [comment]
javítva
