### ISSUE TITLE
Hibajelentés - Duels

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#3213]
![kép](https://user-images.githubusercontent.com/29709854/64196113-67431d00-ce83-11e9-8ccb-b23f99156dcf.png)

Létező hiba, de hűség enchanttal nem jön vissza 1v1-nél a trident, ami tök logikus, hisz nem lehet cuccot felvenni ha eldobsz (bármit) az arénában. Nem tudom, a fejlesztője javítja e vagy sem majd :D

**Comment by MrZero1** [comment]
Tesztként csináltam megint egy ilyen kitet, de csak lebegnek meg mozognak össze vissza a levegőben

**Comment by andris155** [comment]
Eddig jelentetlen hibát hogy javított volna?

**Comment by MrZero1** [comment]
Jelented neki és ha tudja, javítja. 🤔

**Comment by andris155** [comment]
Jelentettem a fejlesztőnek, de nem nagyon foglalkozott eddig sem a jelentéseimmel. Szóval szerintem ne nagyon várjuk a javítást. Ha mégis javítaná, akkor mindenképpen írok.

**Comment by andris155** [comment]
javítva

**Comment by MrZero1** [comment]
![kép](https://user-images.githubusercontent.com/29709854/79427636-491acf00-7fc5-11ea-8a78-17900332a6cc.png)
Most ismét megpróbáltuk, továbbra sem jön vissza a szigony. A játékos körül kering, de nem veszi fel.

**Comment by andris155** [comment]
Az már inkább szerintem a levédés miatt lehet.
