### ISSUE TITLE
OldVillage - Spawner kiszedés

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#3214]
Kb. 100 spawnert szedtünk ki egy kis helyről Sweetannal, kezdő (4. szinttől) könnyen kifarmolják magukat, mind xp mind loot. Így nincs értelme a loot, end és nether resinek, mert azok szedik ki a spawnert, akiknek van 100+. @poma123

**Comment by andris155** [comment]
@poma123

**Comment by poma123** [comment]
spawnert utottek ki vagy a loot az ami sok? mert a spawners plugin csak a lerakast es a kiutest kontrollalja, a tobbi mechanic vanilla (pl. mob spawning)

**Comment by poma123** [comment]
a pwarp tulajdonosának kéne szólni hogy azért álljon meg a menet vannak határok
