### ISSUE TITLE
MineMarket táblák tesztelése/javítása túlélő

### ISSUE THREAD

**Issue by andris155** [andris155/TheOld-Crafters#3215]

**Comment by andris155** [comment]
Ezt maximum @poma123 tudja javítani majd.

**Comment by poma123** [comment]
de ír valamilyen hibát???

**Comment by poma123** [comment]
Javítva, de muszáj az api-version: 1.13 minimum.

**Comment by andris155** [comment]
Akkor nem lesz tábla. Azért köszi.
