### ISSUE TITLE
Ötlet Savsziget Cserepiac

### ISSUE THREAD

**Issue by KulGery** [andris155/TheOld-Crafters#3216]
Jó lenne ha phantom membrán is vasra lenne cserélhető.
Úgysem lehet tól gyorsan szerezni. Egy nap csak három körben jönnek a phantomok, az max 9 phantom. Nem tudom az old kard mennyivel szoroz, de nekem nem jött össze egy nap 64 membrán.

**Comment by MrZero1** [comment]
Tehát vasért membránt?

**Comment by MrZero1** [comment]
Kész. Ha van még javaslat, DC-n írj

**Comment by KulGery** [comment]
Nem! Vasat membránért, mint a csontnál, illetve puskapornál pl.

**Comment by MrZero1** [comment]
Szerintem ha annyi fantom lenne, mint survin, érthető lenne, hogy felgyülemlik sok membrán, de ahogy írtad, egy nap egy stack se gyűlik össze.
