### ISSUE TITLE
Ötlet-Survival-Cserekereskedők

### ISSUE THREAD

**Issue by Niccolettie** [andris155/TheOld-Crafters#3217]
64 Kiégetett kő -> 64 Zúzottkő
16 Izzókő -> 64 Izzókő-por
64 Netherkvarc -> 16 kvarcblokk
(és akár fordítva is)

**Comment by skrisz0101** [comment]
1 izzókó 4 port ad :/

**Comment by Niccolettie** [comment]
uhh tényleg, kijavítottam :D

**Comment by MrZero1** [comment]
1 izzókő 3-4 darabot ad, változó, de lehet kevesebb is.

**Comment by MrZero1** [comment]
Bíbircsók, kvarc (16 blokkból lehet visszanyerni a 64 kvarcot), és a kő bekerült, a többinek nem látom értelmét. Ha van még más javaslat, DC-n írhattok.
