### ISSUE TITLE
Ötlet Sziget szint számolás Savsziget

### ISSUE THREAD

**Issue by KulGery** [andris155/TheOld-Crafters#3219]
Szervusz!

Azon gondolkodtam, hogy a szigetszint számolásnál, pl. a gyémántblokk le van korlátozva. Méghozzá elég kis számra.
Viszont a főzőállvány, enchant asztal, illetve enderláda nincs korlátozva, pedig elég nagy mértékben növelik a sziget szintjét.
No már most. a korlátozás miértje miatt úgy gondolom, hogy azok a tárgyak is legyenek korlátozva, melyek radikálisan emelik a sziget szintjét, viszont funkcionálisan csak egyet, maximum párat használunk belőle. Azaz főzőállvány, enchant asztal szerintem lehetne akár 1-re korlátozva, az ender chest meg mondjuk a kincs blokkokhoz hasonlóan 10-re.

Tudom, ennek sokan nem örülnének, hiszen egy csomó pénzt/energiát öltek a rengeteg főzőállvány/enchant asztal/enderládába.

Avagy a kincses blokkokon levő korlátozásst is oldjátok fel.

Üdv. KulGery

**Comment by poma123** [comment]
Ebből volt már probléma anno, hogy mindent lekorlátoztunk és akkor már a szigetek úgy néztek ki, hogy mondjuk vöröshomokkal feltölti az egészet mert az adta már a legtöbb szintet... Maradnak az ércek lekorlátozva és ami még le van korlátozva. Hogyha megint elkezdődik mondjuk az enderládás szintfelhúzás akkor megint az lesz, mint múltkor és arra is rakunk korlátot.
Amíg nincs rá ok (most nincs rá különösebb ok, hogy szigorítsunk), addig nem fogjuk ezt tovább korlátozni.
