### ISSUE TITLE
/bukkit:me

### ISSUE THREAD

**Issue by NBabi** [andris155/TheOld-Crafters#322]
Gyakran előfordul, hogy egy játékos mute-ot kap bizonyos okok miatt, majd a /bukkit:me parancsot kihasználva folytatja az írogatást.

**Comment by andris155** [comment]
![kepkivagas](https://cloud.githubusercontent.com/assets/8324198/19696344/06e0f658-9ae7-11e6-9e17-3da0963f2785.PNG)
