### ISSUE TITLE
 CustomCrafting Fordítás 2032 OCD-ért

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#3220]
Customcrafting plugin fordítás OCD-ért.

**Comment by andris155** [comment]
https://github.com/andris155/TheOld-Crafters/blob/master/CustomCrafting/lang/hu_HU.yml

**Comment by andris155** [comment]
https://github.com/andris155/TheOld-Crafters/blob/master/Ford%C3%ADt%C3%A1sok/CustomCrafting/lang/hu_HU.yml

**Comment by Niccolettie** [comment]
Még senki nem írt ide, hogy elkezdte volna, szóval akkor megcsinálom :D

**Comment by andris155** [comment]
De kérlek a frissített változatot fordítsd le.
https://github.com/andris155/TheOld-Crafters/blob/master/Ford%C3%ADt%C3%A1sok/CustomCrafting/lang/hu_HU.json
Köszi

**Comment by Niccolettie** [comment]
ezt kell lefordítanom ami a linken van? még angolul sem értem ne viccelj már :O Jó, értem az egészet, de van ahol csak úgy lehet lefordítani magyarra, hogy vagy félig angol félig magyar, vagy pedig ha teljesen magyar akkor borzasztó kókány munka lenne :S

**Comment by Niccolettie** [comment]
például: 

 "recipe_editor":{ 
               "not_existing":"\u0026cThe recipe \u00266%RECIPE% \u0026cdoesn\u0027t exist!",
Számomra itt tiszta sor hogy mi a fordítás, "A recept nem létezik", de a szövegkörnyezet nem mindegy, egyrészt minecraftról beszélünk, nem biztos hogy a "recept" szó a legmegfelelőbb magyarul, valószínű hogy a "craft" célszerűbb lenne, valamint a szöveg formázását nem látom át, sokat segítene az egész fordításban ha látnám valahol a plugint vagy kipróbálhatnám, mert átnéztem a sorokat és van amelyikkel nem tudok mit kezdeni mert "nem értem a feladatot" kb :D

**Comment by andris155** [comment]
\u0026c - ezek a színkódok.
 "msg":" - Ezeket nem szabad fordítani. Ebből tudja a plugin mikor írja ki a szöveget.

**Comment by andris155** [comment]
\u0027 ez meg az aposztróf.

**Comment by andris155** [comment]
de frissítem neked. vagyis megpróbálom

**Comment by andris155** [comment]
Frissítettem neked.

**Comment by andris155** [comment]
Ez a plugin az.
https://www.spigotmc.org/resources/customcrafting-advanced-custom-recipe-plugin-mysql-1-13-2-1-14-4.55883/
Ez pedig kell hozzá:
https://www.spigotmc.org/resources/wolfyutilities-core-plugin-api-1-13-2-1-14-4.64124/

**Comment by andris155** [comment]
Kérlek majd a frissített fordítást vedd alapul.

**Comment by andris155** [comment]
Frissítettem a fordítást, hogy egyszerűbb legyen lefordítani.

**Comment by Niccolettie** [comment]
Így sokkal átláthatóbb, köszönöm! Készül már :)

**Comment by skrisz0101** [comment]
Hajrá @Niccolettie

**Comment by poma123** [comment]
hajra nici a tuzijatek hosszu u ha lenne benne! <3

**Comment by skrisz0101** [comment]
Túzi

**Comment by Niccolettie** [comment]
@andris155 Kész lett, e-mailben elküldtem, ahogy szoktam :) Remélem jó lett! :D Ha bármit javítani kell, akkor szólj :)

**Comment by andris155** [comment]
Holnap megnézem. Köszi.

**Comment by andris155** [comment]
köszönjük @Niccolettie

**Comment by MrZero1** [comment]
Mikor kerül be? :)

**Comment by andris155** [comment]
már be van rakva

**Comment by Niccolettie** [comment]
elvileg /cc <option> vagy /customcrafting <option> a parancs, de nincs rá jog. vagy én írok be rossz parancsot?

**Comment by Niccolettie** [comment]
vagy ez nem survivalra került be?

**Comment by andris155** [comment]
valamiért visszaírta magát angolra, majd holnap betölt a magyar.

**Comment by andris155** [comment]
Ezenkívül MrZero nem tudom mire szeretne jogot adni. Ezeket fogalmam sincs, hogy egyáltalán látja-e játékos. Nekem ez a szerkesztő fordításának tűnt az adminok számára.

**Comment by MrZero1** [comment]
Sokmindenhez nem férnek hozzá, ez a szerkesztő ablak, ami adminoknak kell még mindig angol. A játékos igazából csak barkácsasztalt használ majd ehhez.

**Comment by andris155** [comment]
javítva
