### ISSUE TITLE
A megkapált föld blockot nem lehet kiugrálni.

### ISSUE THREAD

**Issue by maryhonaly** [andris155/TheOld-Crafters#3221]
A megkapált föld blockot nem lehet kiugrálni. Nem dob vissza, nem rángat, az ugrás animációja lemegy. Saját levédésen se, másén se, telekvilágban, vadonba se. Kittinek engedte, nekünk nem.

**Comment by skrisz0101** [comment]
Ez direkt van nem? 😂

**Comment by andris155** [comment]
Nem direkt.

**Comment by MrZero1** [comment]
Pedig jó lenne, mert elég kellemetlen ha más levédésén kilehet ugrálni

**Comment by maryhonaly** [comment]
Más területén eddig se ment, de most már a sajátodon se

**Comment by andris155** [comment]
A fejlesztő azt írta, hogy vannak ennél fontosabb hibák is, amikkel foglalkoznak. Nem valószínű, hogy mostanában lesz javítva, ha egyáltalán lesz.

**Comment by andris155** [comment]
elvileg javítva

**Comment by maryhonaly** [comment]
Gyakorlatban is, működik!

**Comment by andris155** [comment]
köszi
