### ISSUE TITLE
Random kidobódott a fél szerver - 15:41

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#3222]
Nem mindenkit, de a 22ből rengeteg embert egyszerre dobott ki, nem csak szurvin

**Comment by skrisz0101** [comment]
@andris155

**Comment by andris155** [comment]
Pontos időt és percet tudsz mondani mikor volt?

**Comment by skrisz0101** [comment]
Szerintem a címben a 15:41 elég egyértelmű

**Comment by andris155** [comment]
javítva
