### ISSUE TITLE
Ötlet - Survival

### ISSUE THREAD

**Issue by Niccolettie** [andris155/TheOld-Crafters#3223]
OldVillage mobbefogó jól jönne survivalra (szintén pénzért, ahogy pl. OV-n is 350$).
Költöztetem a telkem és vinném a falusiakat is, viszont ha petként befogok egy már kifejlesztett falusit, majd elengedem akkor sajnos a trade más lesz, viszont az OV mobbefogóval nem tűntek el a tradejeik :)
igaz OV nem 1.14, de valószínűsítem, hogy talán a munkájuk sem tűnik el, ha például egy befogott könyvtárost egy másik olvasóállvány mellett engedek el. (remélhetőleg) :D

**Comment by andris155** [comment]
A MyPet-et kell javítani. Nem egy 91. plugin-t berakni arra amit már tud egy másik szerintem.

**Comment by Niccolettie** [comment]
áhh, azt nem tudtam hogy a mypetnek "tudnia" kellene ilyet :O akkor nem szóltam, vegyük úgy hogy plugin hibát jelentettem :D

**Comment by andris155** [comment]
Javítva.
330 OCD
