### ISSUE TITLE
Oldvillage: /ah probléma

### ISSUE THREAD

**Issue by Icecroft** [andris155/TheOld-Crafters#3225]
Régebben a szintemtől függött, hogy mennyi itemet rakhattam fel aukcióba. Most jóval kevesebbet tehetek fel 19. szinten, pedig mások ugyanezen a szinten 10 felett. Mi lehet a probléma?

**Comment by andris155** [comment]
20. szinttől lehet 15-öt. Viszont az tény, hogy nem a legjobban van megírva, mivel nem lettek megírva az elvételi jogok, amiből lehetnek hibák. Az aukcióhoz megcsináltqm.

**Comment by andris155** [comment]
4. szint - 5 aukció
20. szint - 15 aukció
21. szint - 17 aukció

**Comment by Icecroft** [comment]
Köszi az infót! Érdemes lenne a /szintek leírásba újból betenni.
