### ISSUE TITLE
Új küldetések a régiek helyett

### ISSUE THREAD

**Issue by andris155** [andris155/TheOld-Crafters#3226]
* **Szerver**: Savsziget

**Comment by skrisz0101** [comment]
Én annó rengeteg küldetést írtam, ami mind egymásra épültek

**Comment by Niccolettie** [comment]
https://github.com/andris155/TheOld-Crafters/issues/2729

**Comment by andris155** [comment]
kész, majd a tesztelés után kerül lefordításra.
