### ISSUE TITLE
Survival hibajelentés

### ISSUE THREAD

**Issue by Niccolettie** [andris155/TheOld-Crafters#3227]
a "./pc" parancs eredetileg a petcall parancs rövidítése, ami a mypethez tartozna, viszont jelenleg a ./partychat rövidítéseként érzékeli a szerver.
![2019-09-16_19 44 20](https://user-images.githubusercontent.com/48986609/64980620-7b8f0d00-d8ba-11e9-9897-1e25416e29ff.png)

**Comment by poma123** [comment]
@andris155

**Comment by skrisz0101** [comment]
A partycseté lehetne esetleg ,,/pac"?

**Comment by andris155** [comment]
Szinte biztosan még lesz ilyen, hogy elfelejtem kivenni az alias-t az mcMMO plugin.yml fájljából. Ilyenkor inkább Facebook-on írjatok. Ehhez felesleges a hibajelentés.
