### ISSUE TITLE
Sk-Launcher

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#3228]
Láttam valahol hogy azért nincs kint az sk launcher letöltés link a weboldalon, mert nem fejlesztik (ami szerintem nem igaz) 
Vagy hh nincs a weboldalon a letöltés link? 
A tlauncherrel szemben ez nem cseszi szét a skineket és a fejeket

**Comment by KingDeadZ** [comment]
Másfél éve bétában van..

**Comment by andris155** [comment]
Nem nagyon fejlesztik. Viszont kirakok majd egy másikat, amit igen és az eredeti skin rendszert használja.

**Comment by KingDeadZ** [comment]
Mikorra lesz várható?

**Comment by andris155** [comment]
Kiraktam. Ebben jók a skinek?

**Comment by andris155** [comment]
Sokak szerint a tlauncher-rel is az eredeti skineket látják jelenleg. Nem is igazán értem így már.

**Comment by andris155** [comment]
De ott a másik ha az a jobban tetszik. Viszont érdemes lenne megvenni az eredetit inkább. Az FPS is több vele meg jobban működik.

**Comment by poma123** [comment]
a tlauncherben lehet latni a skineket ugyan ugy, csak akkor nem, ha valaki a gyarilag bent levo kék [TL] -es optifine-t inditja el. Abban nem. Le kell szedni manualisan optifinet.net
