### ISSUE TITLE
Farkasok létszáma

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#3229]
![2019-09-17_17 43 51](https://user-images.githubusercontent.com/29951969/65057753-61fdcc00-d973-11e9-8a05-9a3c0bf81203.png)
Nem tudom mi ez, de.
1.: Nincs lefordítva.
2.: Ez milyen plugin? xd
3.: Miért van korlátozva hogy mennyi farkas lehet nálam? :(

**Comment by andris155** [comment]
Egyszerű optimalizáció ez is. Miért akarod, hogy több mint 6 farkas kövessen?

**Comment by skrisz0101** [comment]
Csak a szelidítés szintet akartam növelni.
Ennyi.

**Comment by andris155** [comment]
növeltem a limitet és lefordítottam.
