### ISSUE TITLE
Savsziget: Új küldetéssorhoz javaslat

### ISSUE THREAD

**Issue by Icecroft** [andris155/TheOld-Crafters#3230]
Az új küldetéssorokat majdnem végigvittem, de a tapasztalatom elég rossz: a jutalmak az előző küldetésekhez képest nagyon szerény. Az ismételhető küldetések egyikében sincs semmi haszon, biztos, hogy senki sem fog ismételni a nagy ráfizetés miatt.
A régi küldikben egyszerüen lehetett tehén, csirke, malac spawntojásokat szerezni (Farmer), ami a kezdőknek nagy segítség volt. Később a birka és gombatehén spawntojások is jól jöttek. Most semmi. Érdemes lenne a jutalmakat még átgondolni.
(megjegyzés: Az egyik legjobban összerakott küldisor anno a SkyBlockon volt. Ez persze magánvélemény)

**Comment by andris155** [comment]
Melyik küldetéseknél kellene módosítani a jutalmakat? Illetve mire?
Vagy több küldetés kellene?

**Comment by andris155** [comment]
Ezek vannak most: https://github.com/BentoBoxWorld/Challenges/blob/develop/src/main/resources/default.json

**Comment by andris155** [comment]
@Icecroft

**Comment by poma123** [comment]
> @Icecroft

inkább szerón kéne mailt írni neki sztem

**Comment by Icecroft** [comment]
Sorry, kicsit elfoglalt voltam, ma összeírom a változtatási javaslataimat.

**Comment by Icecroft** [comment]
Novice szinten:
- új küldetés: Smooth stone maker: 64 db csiszolt kőért 4 db édesbogyó
- új küldetés: Sweetberry picker: 64 db édesbogyóért 4 db bambusz
- új küldetés: Bamboo picker: 64 bambuszért 1 db bőr lópáncél

Competent szinten:
- új küldetés a céklafarm után: Farmer (mint régen): 64 Búza, 64, Krumpli, 64 tök, 64 dinnye, 64 sárgarépa, 64, cukornád, 64 édesbogyóért 1 Tehén + 1 csirke + 1 malac spawntojás (100-szor ismételhető)

Advanced szinten: a Chef küldetés jutalma lehetne egy gombatehén spawntojás (mint régen)

**Comment by andris155** [comment]
A halak nem nagyon értem, hogy miért nem spawn-olnak egyelőre. Mondjuk a savban lehet logikus, hogy nincsenek halak, de akkor nem értem minek van hozzá flag is. A küldetésekből, amiket jónak láttam azokat megvalósítottam.

**Comment by andris155** [comment]
508 OCD
