### ISSUE TITLE
Nagy laggok magas tps-el - 14:31

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#3231]
szurvi szeró. Sztem leírtam mindent.
Mindenki érzékelte a nagy laggokat.
(gondoltam szerver logból kiderül mitől lehetett)

**Comment by MrZero1** [comment]
@andris155

**Comment by poma123** [comment]
tegnap a tps se volt magas, 12-10 koruli.

**Comment by skrisz0101** [comment]
Mary mondta hogy jó a Tps :/

**Comment by poma123** [comment]
en pedig megneztem tegnap amikor fent voltam es nem volt jo :D

**Comment by andris155** [comment]
Nem fog kiderülni semmi a logból. Akkor kellett volna látni. Ha megint lesz ilyen inkább Facebook-on írj kérlek és ne az oldalra hanem nekem. Köszi.
