### ISSUE TITLE
Felkészülés a Survival szerver End és Nether resetre

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#3232]
Szerintem felesleges írni bármi egyebet, rég volt újragenerálva, szükséges már.

**Comment by MrZero1** [comment]
A pontos dátumot még megbeszéljük és előre fogjuk jelezni a közösségi platformjainkon.

**Comment by andris155** [comment]
Addig lehetne időpont még nem találtam munkát, mert a Griefprevention védéseket nem olyan egyszerű törölni ezekből a világokból, ahogy emlékszem. Így jó lenne valamikor reggel megoldani, amikor ez senkit sem zavar.

**Comment by MrZero1** [comment]
Írok privátot ezügyben.

**Comment by andris155** [comment]
Kész
