### ISSUE TITLE
survival - nem sebződött egy játékos

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#3233]
buldozer22 nevű játékos nem sebződött, relog után már igen. 
![kép](https://user-images.githubusercontent.com/29709854/65344009-c4a2d200-dbd6-11e9-890c-4c547e4e80fd.png)

Víz alatt volt, nem sebződött, majd villámoztam és akkor sem

**Comment by andris155** [comment]
Egyszeri hiba volt szerintem csak. Ha megint előfordul, akkor majd nyissatok új jelentést. Köszi.
