### ISSUE TITLE
Survival - Plot - Mod

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#3234]
Survival szerver, Moderátoroknak volt joguk a plot világban az utakon kiütni (slimefun miatt anno), erre lehetne jogot adni nekik megint, plusz a lerakásra, hisz a Luckyblock erőszeretettel rak le 'börtönöket'

**Comment by andris155** [comment]
Most jó?

**Comment by andris155** [comment]
Szerintem jónak kell lennie.
