### ISSUE TITLE
Survival - Spawneres/Old láda :(

### ISSUE THREAD

**Issue by Niccolettie** [andris155/TheOld-Crafters#3235]
Heoo, vettem 2032 OCD-ért 8 spawner ládakulcsot. Enyhén ergya a felhozatal.
16 creeperidéző tojás, 64 papagájidéző tojás, 16 bosszancsidéző tojás, 16 őrszemidéző tojás, 16 pandaidéző tojás, 1 blaze spawner és egy 1 csirke spawner.
Értem én, hogy ennek kb zsákbamacska lényege van, de legalább ne csak 16 őrszemidéző tojás legyen hanem 32 vagy 64 mert ez így semmit nem ér :D 
Old ládát is nyitottam kb 1 hónapja, 4 itemből tudjátok mi jött? 1 életmentés toteme (most már 10db jön, de ez sem változtat semmin), 2x8 tenger szíve és 16 harang. Ez tudjátok mennyit ér? MAXIMUM 25k, úgy hogy a 16 harang 0$-t ér :) 1016 OCD a 4 kulcs ami 1millió és 16ezer dollár a szerveren.
Én most a fordításra kapott OCD-t költöttem el, de megmondom őszintén akár az ablakon is kidobhattam volna :( picit elszomorító :( Nem lehetne a nagyon értéktelen dolgokat kivenni, és berakni értékesebbeket amik úgy ahogy megérnék? nem 100% haszonra gondolok, de jó lenne ha az OCD legalább 75%-a visszajönne item formájában :) Remélem megvalósítható :D

**Comment by andris155** [comment]
Szerintem jó ahogy van. Meglehet venni külön az Old tárgyakat, ha nem a szerencsére szeretnéd bízni ezt.

**Comment by Niccolettie** [comment]
Főleg a spawneres ládára gondoltam, mert amilyen spawnerek ott vannak, azokat nem lehet megvenni külön.

**Comment by skrisz0101** [comment]
És az oldládába is vannak olyan oldcuccok, amiket nem lehet, pl:
Oldbot, oldolló, oldtekisisak, old pajzs, meg mittomén

**Comment by poma123** [comment]
szerintem alapból nem éri meg 4 kulcsba megvenni az old kulcsot, maga a kulcs nem éri meg, plusz amit kapsz belőle se. szerintem pénzkidobás, bár a másik oldalról nézve meg bevétel :D

**Comment by poma123** [comment]
plusz ha olyan van benne ami nem vehető spawner, akkor az úgy szerinted megéri, hogy 8szor kipörgeti és csak akkor jön meg, ami összesen 2032ocd de a spawner ára pedig 330 lenne? @andris155

**Comment by poma123** [comment]
szerintem ha ennyire nem éri meg akkor egyáltalán értelme sincs a ládának ocd-ért.

**Comment by MrZero1** [comment]
Poma, amikor lett csinálva, miért nem tudtad leírni? :) Utólag könnyű okosnak lenni.
