### ISSUE TITLE
Minemarket elírás...

### ISSUE THREAD

**Issue by poma123** [andris155/TheOld-Crafters#3236]
Ez az a híres szóösszetétel amitől agykukit kapok.

![image](https://user-images.githubusercontent.com/25465545/65386690-575e8080-dd3f-11e9-91aa-d8a0e5c81cb3.png)

Ehhez hasonló a `meg lehet (csinálni, enni, stb..)` vagy `meg lehetne (tudni, csinálni, javítani, stb..)`, ahol ugyanúgy külön kell írni.

> **A „ki” igekötőt, a „tudod” igét és a „nyitni” igét különírjuk az alábbi szabály alapján:
> Az igekötő külön szó marad, ha közte és igéje (vagy igeneve) között más szó is van. [AkH11-131c]**

**Comment by andris155** [comment]
Ha van időd átnézhetnéd az oldalakat. Biztosan vannak még ilyen hibák. :/

**Comment by poma123** [comment]
egyszer végigmentem az egész githubon, a jelentések felében van lehetne szó, rossz tagolással :D

**Comment by poma123** [comment]
amúgy minemarketen most (csak) az összes kulcsnál van elírva :D

**Comment by andris155** [comment]
Sajnos a 2014-es szerkesztő a MineMarket-ben nem támogatja a Chrome helyesírás ellenőrzőt így több dolog is van ott szerintem még elírva.

**Comment by andris155** [comment]
javítva
