### ISSUE TITLE
Survival - telek/falusi

### ISSUE THREAD

**Issue by Niccolettie** [andris155/TheOld-Crafters#3237]
szeptember 11-én elengedtem a telkemen egy falusit, raktam le neki ágyat is és olvasóállványt de azóta nem akarja felvenni a munkát, sima barna ruhás falusi.

**Comment by andris155** [comment]
Honnan tudjuk miért nem akarja?

**Comment by poma123** [comment]
Szerintem invitáld be abba a puha ágyba utána menni fog dolgozni.. ;)
