### ISSUE TITLE
manuális, napi, automatikus eventek

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#3238]
Szerintem ezt már régebben megírtam, de most megint eléggé aktuális.
Mostanában Oliverhahn, meg úgy tényleg az egész staffcsapat napi szinten tart manuális eventeket (talán többször is 1 nap). Ez tényleg jó, régebben volt, hogy heti 1 manuális ha éppen volt :/. Ezzel csak annyi a gond, hogy kb 4 event közül lehet választani ':D, és persze a kvíz, maradjtalpon event tartása pici macerába is fáj.
na szóval.

néhány napi eventet lehetne duplikálni,  lenne napi eventként is pl egy dragonrun event, és lenne egy manuális eventként is,mert így elég gyatra, hogy 4 event közül lehet csak választani 
a szegény staffoknak :( 
ez az átmenet lehetne persze az automatikus eventeknél, hogy pár napi eventet át lehetne vinni automatikusba IS. 

még1x, konkrét példa: dragonrun Manuális eventként, Dragonrun Napi eventként, esetleg Dragonrun automatikus eventként IS.
(az eventnév csak random jött, nem ragaszkodom a dragonrunhoz xd)

Savsziget más téma, de az már eléggé ki lett vesézve szerintem :D

**Comment by KingDeadZ** [comment]
Amikor fent vagyok, akkor nem lehet választani csak spleefet szóval... :)

**Comment by skrisz0101** [comment]
Túl sok a haszontalan infód :/

**Comment by MrZero1** [comment]
Mennyire van igény még staffos eventre?

**Comment by skrisz0101** [comment]
Napi szinten többet is tartanak, azért írtam :D

**Comment by MrZero1** [comment]
Került be pár új event, illetve kerülni is fog még be jópár. Ezenkívül a napi eventeket is tudják majd tartani a staffok, ha igény van rá.
