### ISSUE TITLE
Savsziget: VIP sziget javaslat

### ISSUE THREAD

**Issue by Icecroft** [andris155/TheOld-Crafters#3239]
A Savsziget VIP szigeten az "Értékek" npc-nél a vasat minden egyéb más ércre át lehet váltani, kivéve a redstone-t. Korábban ez szerepelt a listában, de most kimaradt. Légyszíves rakjátok vissza.

**Comment by MrZero1** [comment]
Kész! Köszi, hogy jelezted. :)
