### ISSUE TITLE
Kreatív bug

### ISSUE THREAD

**Issue by NBabi** [andris155/TheOld-Crafters#324]
Kreatívban ha lerakunk például egy blokkot, arra egy cserepet, majd kiütjük a blokkot alóla, survival módba váltunk és a cserepet fel lehet szedni, így lehetőség nyílik pl: virágok, facsemeték, gomba, kaktusz addolására.

**Comment by andris155** [comment]
https://github.com/andris155/TheOld-Crafters/issues/185
