### ISSUE TITLE
Ötlet

### ISSUE THREAD

**Issue by AK9911** [andris155/TheOld-Crafters#3240]
Mindegyik szerverre vonatkozik, van egy plugin csak most még nem jut az eszembe hogy hogy hívják per pillanat, ami a moderátoroknak is egy kellemes játékbeli időtöltést tudna nyújtani, anélkül hogy a szerveren való előnyeiket tudnák is bármilyen módon használni. Emlékszem hogy még egy régen csinált szerveremen használtam, és csak egy parancsot kellett beírjanak a staffjaim meg az építészeim hogy a "munkájukat felvegyék".
Mindenféleképp még fogok commentelni ehhez a tickethez hogyha eszembejut a plugin neve, megkönnyebbíti sokmindennel az embernek az életét

**Comment by KingDeadZ** [comment]
Hogyha ez mellett lehetne egy külön rangjuk, pl old akkor értelmet nyerne a havi staff szavazásos OCD is :D Szerintem jó ötlet, így nem éreznék azt hogy le vannak limitálva.

**Comment by MrZero1** [comment]
OV-n nem voltak "lelimitálva", meg is lett a böjtje. Kivételezések, nem figyeltek, mert játszottak. De várom a javaslatodat.

**Comment by KingDeadZ** [comment]
OV teljesen más, nem érdemes összehasonlítani.

**Comment by AK9911** [comment]
https://dev.bukkit.org/projects/duties itt van a link, és a plugin, nagyon egyszerű de könnyen lehet formázni, és ezáltal kiküszöbölni a kisebb problémákat (játékos-staff közötti korruptság kezelése, moderátorokat normális playereknek lehet tekinteni, és tudnak tradelni a játékosokkal, és más dolgokat is csinálni)

**Comment by andris155** [comment]
Ez a plugin sajnos már nagyon régi. Nem fog működni 1.14.4-en.

**Comment by poma123** [comment]
> Ez a plugin sajnos már nagyon régi. Nem fog működni 1.14.4-en.

igen, plusz ha kellene se tudnám frissíteni mert szörnyű a kód, plusz nagyon nagyon nagyon régi
