### ISSUE TITLE
Savsziget: VIP sziget állatidomár fejlesztése

### ISSUE THREAD

**Issue by Icecroft** [andris155/TheOld-Crafters#3242]
A VIP szigeten az állatidomár npc-nél 2 receptben is lehet teknős idézőtojást venni.
Javaslom, hogy az egyik esetben teknős helyett pl nyúl idézőt lehessen venni.
Egy tintahal idéző sem lenne rossz, mivel az egyik küldetésben tintahal is kell, ami nagy szigetek esetén már ritkán spawnol, nem rakható vödörbe stb.

**Comment by MrZero1** [comment]
Kész. Köszi!
