### ISSUE TITLE
Savsziget fordítások fejlesztése OCD-ért

### ISSUE THREAD

**Issue by andris155** [andris155/TheOld-Crafters#3243]
**Szerver**: Savsziget

Azokat a szövegeket, amiket sehol sem látnak a játékosok a szerveren nem kell lefordítani. Ahogy azokat sem, amiket csak az adminok látnak.
https://github.com/andris155/TheOld-Crafters/tree/master/Ford%C3%ADt%C3%A1sok/BentoBox/locales

**Comment by Niccolettie** [comment]
Csinálom! :)

**Comment by Niccolettie** [comment]
Elküldtem!

**Comment by andris155** [comment]
Köszönjük

**Comment by andris155** [comment]
Lehet már csak következő vasárnap tudom majd megnézni.

**Comment by andris155** [comment]
A Likes-ből semmit sem fordítottál le. Direkt?

**Comment by andris155** [comment]
A többiben is sok rész van, ami nem azért lett lefordítva, mert ne látnák a játékosok.

**Comment by andris155** [comment]
A többiben is sok rész van, ami nem azért nem lett lefordítva, mert ne látnák a játékosok.

**Comment by andris155** [comment]
Sok üres, de nem felesleges entert töröltél a fordításokból. Ezekre legközelebb kérlek figyelj majd.

**Comment by andris155** [comment]
Töltsd le zip fájlként a fordításokat inkább. Ne a GitHub-ról másold ki. Gondolom ezért vesztek el az enterek belőle.

**Comment by andris155** [comment]
Vagy a GitHub-ról másolod, akkor használd „Raw” gombot és onnan az oldalról másold ki az egészet.

**Comment by Niccolettie** [comment]
Igen, kimásoltam és valószínűleg azért tűntek el az enterek, erre figyelek legközelebb. 
A Likes yml-t lefordítottam, csak rosszat küldtem el, bocsi, elküldöm, amint gépnél leszek!

**Comment by Niccolettie** [comment]
Elküldtem! Most már a lefordítottat! :D

**Comment by andris155** [comment]
A like egy angol szó és helytelen a magyarban is ezt használni.

**Comment by andris155** [comment]
Bekerült. Köszi.

**Comment by andris155** [comment]
2032 OCD
