### ISSUE TITLE
Savsziget: Hiba a vízi állatkert küldetésben

### ISSUE THREAD

**Issue by Icecroft** [andris155/TheOld-Crafters#3244]
- **A szükséges halakból a lazac nem megoldható**, nem spawnol egyik biomban sem, sem üvegházban!
- A **delfin annyira ritka**, hogy csak egyszer láttam még a savszigeten, ezt is érdemes lenne valahogy megoldani.

- Tőkehal óceán biomban spawnol (kevés tőkehal + sok vízbefúlt)
- Tintahal sok spawnol az óceán üvegházban
- Gömbhal meleg óceán biomban spawnol
- Trópusi halak szintén a meleg óceánaban (remélhetőleg a küldetés teljesíthető a különféle trópusihal változatokkal.)
- Teknős szaporítható

Ha másként nem megy esetleg spawntojásokat lehessen valahogyan szerezni, például plussz küldetésekkel:
64 kihorgászott lazac => 1 lazac spawntojás vagy lazac vödörben (100-szor teljesíthető)
64 tőkehal+ 64 lazac + 16 trópusihal  => 1 delfintojás vagy delfin vödörben (100-szor teljesíthető)

**Comment by andris155** [comment]
Ez a 2 küldetés legyen? Illetve melyik szinten?

**Comment by Icecroft** [comment]
Szerintem legyenek 3-as szinten (Haladó)

**Comment by andris155** [comment]
Növeltem a spawn limitet. Most sem spawnol több vízi élőlény?

**Comment by Icecroft** [comment]
Eddig egy csoportban 2-3 tőkehal spawnolt, most kb 4-8. A vízbefúltak spawnrate-je még mindig magasabb: elkaptam 8 tőkehalat és szereztem 7 stack zombihúst + 2 szigonyt.
Lazac továbbra sem spawnol! De delfinse.

**Comment by andris155** [comment]
Holnap majd még kérlek nézd meg. Aztán, ha nem spawnolnak jobban, akkor megcsinálom a küldetéseket.

**Comment by Icecroft** [comment]
A halak spawnrate-je valóban nagyobb lett, de a lazac és a delfin problémáját nem oldotta meg.
Ennél a rate-nél viszont nem okoz gondot a tőkehal és trópusi halak beszerzése.

**Comment by poma123** [comment]
![image](https://user-images.githubusercontent.com/25465545/66342684-4e2e0000-e94a-11e9-8260-bad15ca01f24.png)

**Comment by KingDeadZ** [comment]
![image](https://user-images.githubusercontent.com/38157910/66342801-8b928d80-e94a-11e9-8fca-b6ab6fb68930.png)

**Comment by KingDeadZ** [comment]
Delfin is volt, de az elúszott valahova

**Comment by andris155** [comment]
Akkor már van minden?

**Comment by KingDeadZ** [comment]
Elméletileg igen. Ha lenne probléma nyitok újat.

**Comment by andris155** [comment]
Rendben, köszi. Kell nehezebb küldetés is, de így talán már teljesíthetőbb szerintem.

**Comment by Icecroft** [comment]
Bocs, de szerintem egyáltalán nem megoldott a dolog. A screenshotokon csak tőkehal és trópusi halak vannak. LAZAC nincs és nem is lesz, mert nem spawnol.
Még 1.13-ban a halak spawnolásának korlátozása előtt is ritka volt a delfin, de most a lehetetlenség határát súrolja.

**Comment by KingDeadZ** [comment]
Egy chunkot raktam át a szigeten meleg óceánra, majdnem h egyből spawnoltak. Persze, azóta nem spawnoltak... Ötlet: Az óceán üvegházba spawnolhatna kis eséllyel delfin,lazac.
(Vagy ha van rá lehetőség, külön egy meleg óceán üvegház, ahová a delfin spawnolna, a tőkehal és a trópusi hal, egy hideg óceán üvegház, ahova csak a lazac spawnolna)

**Comment by Icecroft** [comment]
Az óceán üvegházban csak tintahal spawnol, más nem. Persze jobban nézne ki, ha emellett delfin, lazac és tőkehal is lenne benne. Kérdés, hogy ez megoldható-e. A küldetés sort azért javasoltam, mert talán egyszerűbb, mint az üvegházas kód módosítása, de ezt persze nem én döntöm el.

**Comment by andris155** [comment]
Akkor mi legyen a megoldás?

**Comment by Icecroft** [comment]
Ha lehet, az óceán üvegházban spawnoljanak, ne csak tintahal legyen, hanem delfin, tőkehal és lazac is.
Ha ez nem megoldható, akkor a delfint és lazacot küldetésből lehessen megszerezni.

**Comment by andris155** [comment]
<img width="599" alt="Annotation 2019-10-13 112930" src="https://user-images.githubusercontent.com/8324198/66713585-bea2aa00-edac-11e9-9791-2cf864bdbe50.png">
Majd tesztelni kellene, hogy működik-e.

**Comment by Icecroft** [comment]
Andris, kellene még finomítani rajta: a lazac csak a cold_ocean biomban spawnol, de mi nem tudunk COLD_OCEAN biomot beállítani, csak sima OCEAN-t vagy WARM_OCEAN-t. Légyszi add hozzá a lazacot (salmon) is az OCEAN biomhoz.

**Comment by andris155** [comment]
Miért nem tudtok?

**Comment by Icecroft** [comment]
A Cold_ocean nincs a menüben, csak a sima ocean és warm_ocean:
![2019-10-13_18 51 56](https://user-images.githubusercontent.com/19332825/66719029-eb75b200-edea-11e9-84e8-6fbeeec82034.png)

**Comment by Icecroft** [comment]
Bocs benéztem. Sikerült teljesíteni a küldetést, lezárhatod!

**Comment by andris155** [comment]
Köszi. 1016 OCD

**Comment by mr00000** [comment]
kaka
