### ISSUE TITLE
Savsziget: újabb küldetés ötlet [1.15]

### ISSUE THREAD

**Issue by Icecroft** [andris155/TheOld-Crafters#3245]
A küldetések 2. szintjén lehetne egy új 1.14-es küldetés:
64 pipacs beadásáért 3 honeycomb a jutalom, egyszer teljesíthető. (ezzel már el lehetne kezdeni kaptárt építeni)

**Comment by KingDeadZ** [comment]
A honeycomb nem 1.15s? :D

**Comment by Icecroft** [comment]
bocs ez csak 1.15-ben

**Comment by andris155** [comment]
Nem baj, ha előre kitalálunk küldetéseket.

**Comment by andris155** [comment]
Egyelőre lezárom, mivel még nagyon bizonytalan mi is lesz az 1.15-ben. Ha megjelenik a végleges verzió, majd az alapján írd meg újra ezt vagy akár új ötleteket is, ha lesznek benne még plusz dolgok.
