### ISSUE TITLE
Ötlet

### ISSUE THREAD

**Issue by KingDeadZ** [andris155/TheOld-Crafters#3246]
Lehetne csinálni egy-egy ötletes posztot itt githubon, és azt hirdetni a szerveren.
Biztos vagyok benne, hogy sok embernek lenne ötlete, de nem tudja hogy hogy adja át vagy egyáltalán nem adja át ezt, ez talán segíthetne benne.

**Comment by andris155** [comment]
Bárki írhat a Github-ra ötleteket. Jobb, ha mindenki külön posztban ír inkább.
