### ISSUE TITLE
ChatControl link

### ISSUE THREAD

**Issue by poma123** [andris155/TheOld-Crafters#3247]
![image](https://user-images.githubusercontent.com/25465545/66000289-6364e380-e49f-11e9-93c5-2777176919c2.png)

**Szerver**: Survival

**Verzió**: 1.14.4

**Comment by andris155** [comment]
Talán a Facebook-ot engedélyeztem úgy emlékszem.

**Comment by andris155** [comment]
A Facebook engedélyezve van.

**Comment by poma123** [comment]
ok
