### ISSUE TITLE
Elírás - Savsziget

### ISSUE THREAD

**Issue by KingDeadZ** [andris155/TheOld-Crafters#3249]
Savsziget
![image](https://user-images.githubusercontent.com/38157910/66118821-97dbbb00-e5d7-11e9-928a-3973ef2181c7.png)

**Comment by KingDeadZ** [comment]
4-et ad, nem pedig csak 1-et

**Comment by KingDeadZ** [comment]
![image](https://user-images.githubusercontent.com/38157910/66119637-521ff200-e5d9-11e9-9b68-850771b01119.png)
"kő tégla" Helyesen kőtégla
"varázlat" leírásban.
![image](https://user-images.githubusercontent.com/38157910/66119711-80053680-e5d9-11e9-96ba-66e78f6e2e67.png)
"éges" szintén leírásban
![image](https://user-images.githubusercontent.com/38157910/66119732-90b5ac80-e5d9-11e9-8631-6432ac10be26.png)
"homokssá" szintén leírásban Egyébként, ez a küldetés is 4-et ad nem csak 1-et.
![image](https://user-images.githubusercontent.com/38157910/66119920-face5180-e5d9-11e9-97de-b10854dfca76.png)
a kezdő kihívás nagybetű, nem pedig kisbetű

**Comment by KingDeadZ** [comment]
![image](https://user-images.githubusercontent.com/38157910/66120341-f35b7800-e5da-11e9-8568-7f69879b0d23.png)
clay blockot ad, nem pedig ballt.

**Comment by KingDeadZ** [comment]
A Dinnye Farm küldetésnél a farm nagybetűvel kezdődik, az összes többi farmos küldetésnél (kezdő szinten) kicsivel.

**Comment by andris155** [comment]
Ha olyan küldetést teljesítesz, ami többször teljesíthető, akkor persze, hogy más jutalmat ad utána.
