### ISSUE TITLE
Furniture limit bug

### ISSUE THREAD

**Issue by NBabi** [andris155/TheOld-Crafters#325]
(tegnap vettem észre) Már le van rakva 16 fence furniture (kerítés) a telkemre, de próbáltam lerakni még többet, és engedte, és a képen látható 1/16 limitet újra elkezdi számolni, mintha az előző 16 kerítés nem tartozna ebbe a limitbe.
![2016-10-26_14 21 06](https://cloud.githubusercontent.com/assets/22939109/19725845/41e8074a-9b88-11e6-8cfc-57fd64c22f30.png)

**Comment by andris155** [comment]
Jelentettem a hibát a fejlesztőnek.
