### ISSUE TITLE
Savsziget hiba

### ISSUE THREAD

**Issue by KingDeadZ** [andris155/TheOld-Crafters#3250]
![image](https://user-images.githubusercontent.com/38157910/66120531-577e3c00-e5db-11e9-93b7-342e92068a6c.png)
Valamit nem számol bele, 13at teljesítettem.
Teljesített küldetések:
Zúzottkő generátor 1
Fafarm 2
Cukornád farm 3
Tök farm 4
Dinnye farm 5
Kaktusz farm 6
Alma gyűjtő 7
Papír készítő 8
Kőtégla készítő 9
Vágott kőtégla barkácsoló 10
Repedezett kő tégla 11
Csiszolt kő készítő 12
Dinnye gyűjtő 13
![image](https://user-images.githubusercontent.com/38157910/66120751-eab77180-e5db-11e9-9f5d-feead180a07f.png)
Remélem kivehető hogy mi van készen, a kép bizonyítékként.

**Comment by KingDeadZ** [comment]
Update: Elírás volt ez is, mivel megcsináltam egy másik küldit és 14re ugrott fel.

**Comment by andris155** [comment]
Nem tudom mi alapján számolja. Szerintem működnie kell ettől függetlenül a rendszernek.
