### ISSUE TITLE
Hiba - Savsziget

### ISSUE THREAD

**Issue by KingDeadZ** [andris155/TheOld-Crafters#3251]
Nem lehet vásárolni beetroot seedet, és kaktuszt. A paradicsom szigeten nem volt a ládában, kérdeztem mást is aki azt választotta és neki sem volt.

**Comment by Icecroft** [comment]
Kaktuszt sivatagi üvegházból lehet szerezni, ha az üvegház tölcsérébe csontport teszel.
Lehet mástól is vásárolni, mert más típusú szigeteken van kaktusz, de ott nincsenek pl korallok.

**Comment by andris155** [comment]
beetroot seed szerzésre valami ötlet?

**Comment by KingDeadZ** [comment]
Egy olyan küldetés, ami 48 kaktuszért ad 3db beetroot seedet, a legalapabb küldetés sorba.

**Comment by Icecroft** [comment]
A céklamag az endhez kötődik nálam, ezért én egy olyan küldetéshez kötném, amiben pl 64 endkövet kell beadni 4 magért.

**Comment by skrisz0101** [comment]
Céklamag miért kötődik az endhez?

**Comment by Niccolettie** [comment]
Céklamagot inkább olyan küldetésből kellene szerezni, ahol más növényekért cserébe kap a játékos, pl 64 répáért 4 mag vagy 32 répa+32krumpliért 4 mag. (ezek csak példák, nem törvényszerűek ezek a mennyiségek)

**Comment by andris155** [comment]
Melyik szinten legyen ez a küldetés?

**Comment by Niccolettie** [comment]
szerintem a legelső szinten legyen, hiszen elég alap dolog ha magokról/növényekről beszélünk

**Comment by andris155** [comment]
kész

**Comment by andris155** [comment]
330 OCD
