### ISSUE TITLE
Savsziget - csapat max létszám

### ISSUE THREAD

**Issue by poma123** [andris155/TheOld-Crafters#3253]
**Szerver**: Savsziget

Hali, jó lenne ha nem csak 4-en lehetnénk egy szigeten, legalábbis most nem enged több embert. Legyen 8 vagy 10. Van akik 8-an vannak, mert régebben még lehetett.

konfigban a hely: 
![image](https://user-images.githubusercontent.com/25465545/66211147-b87d4100-e6bb-11e9-8fcf-091ba9389352.png)

köszi!

**Comment by andris155** [comment]
Szerintem ez ranggal elérhető jog lesz majd.

**Comment by poma123** [comment]
Azt nem lehet, hogy alapból is 8 legyen?

**Comment by andris155** [comment]
kész

**Comment by poma123** [comment]
Köszi
