### ISSUE TITLE
új világ Szurvira

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#3254]
Szerintem mindenki látja milyen sokan játszanak OldVillagen (sajna :( )
De ez a városépítős ötlet nagyon jó/jó volt, imádtam az oldvillaget miatta .:D 
Mi lenne, ha lenne egy towny világ A Szurvi szerveren a vadon(ok) mellett? (és a telek mellett)
Szerintem jó lenne, mert ezzel tényleg igazi városokat lehet csinálni, és nem csak díszeket, vagy olyat hogy mindenkit hozzáadok, aztán talán nem rombolja szét.

EZ PERSZE CSAK AKKOR, HA NEM ZÁR(NA) BE AZ OLDVILLAGE!!!!
(Bár kitudja :/)

Mondjuk a gm1-el, god-al, fly-al kéne valamit kezdeni (csak abban  a világban), mert ugye a townyban benne van a nemzet is, a nemzetben meg a ,,háború", az meg esetleges pvp-ket szülne. 
Fura lenne ha mittomén 2 emeberke üt másik kettőt, a 3. meg beépíti őket obszival kreában, vagy valami. Vagy esetleg egy olyat csinálni, hogy ha az adott nemzetnek van kitűzve ellenséges nemzet, vagy éppen őket ,,célozták" meg ellenséges nemzetnek, akkor a nemzettagok (egyik oldalon se) nem tudnának átváltani god-ba, gm1-be, esetleg fly-elni. 

Ezen a háborús dolgon eléggé el lehet töprengeni, de MEGÉRNÉ!

Mondjuk az Old Cuccokkal is van egy kis bökkenő ezügyben, mert konkrétan nincs is értelme akkor, ha valaki oldszettben jön. Lehet a háború részét ki kéne venni, vagy nem is tudom.
Valami megoldást úgy is kiötlenek az okosabbak (vagy nem :( )
De szerintem sokat dobna szurvin (HA NEM LESZ OLDVILLAGE)

Ötletféléket várom kommentben és a boltomban! - Akciós a Vödrös hal! (Elfogyott!)
ÉPÍTSÜK MEG EGYÜTT AZ ÚJ Loli Hentai-t!

**Comment by MrZero1** [comment]
Már csak azért is rossz az ötlet, amit Te is írtál, hogy ott a kreatív, istenmód, repülés, oldcuccok. Ha meg létre is hoznánk egy külön világot erre, akkor azt is minden következő vagy utáni frissítésben újragenerálni? Elég szerintem a vadonnal ezt eljátszani. 

Az, hogy nem lesz OV, nem tudom ki honnan szedte, de jól félre van tájékoztatva.

**Comment by skrisz0101** [comment]
Senki se mondta hogy nem lesz ov

**Comment by skrisz0101** [comment]
Ez csak egy egyszerű gondolatfuttatás :/

**Comment by poma123** [comment]
igen a szándék jó, csak az ötlet megvalósítása szerintem lehetetlen. sehogy se lehetne megoldani hogy ne kerüljenek ide oda a cuccok meg a világ frissítés is kín lenne. plusz még sok egyéb.
valami konkrét terv amúgy van ov-vel hogy így most 0n áll vagy ez maradni fog esetleg?

**Comment by Niccolettie** [comment]
a kreatívot, god-fly jogokat nem lehet úgy letiltani mint az event mapon? bár ha lehetne is, az itemek okoznák a legnagyobb gondot, illetve... amikor valaki erre a mapra akar teleportálni le lehetne tiltani mindent, mint az event világban, üres inventoryval lehetne csak oda menni, fly god krea minden nélkül, majd abban a világban letiltani a gm váltást, és ugyan úgy ha valaki spawnra akar teleportálni akkor üres inventoryval teheti meg, stb.

**Comment by poma123** [comment]
> a kreatívot, god-fly jogokat nem lehet úgy letiltani mint az event mapon? bár ha lehetne is, az itemek okoznák a legnagyobb gondot, illetve... amikor valaki erre a mapra akar teleportálni le lehetne tiltani mindent, mint az event világban, üres inventoryval lehetne csak oda menni, fly god krea minden nélkül, majd abban a világban letiltani a gm váltást, és ugyan úgy ha valaki spawnra akar teleportálni akkor üres inventoryval teheti meg, stb.

igen de a jelenlegi körülmények miatt lehetetlen :(

**Comment by andris155** [comment]
Mivel a Minecraft egy magon fut nem jó ennyire vegyíteni a dolgokat. A túlélőn is legszívesebben szét bontanám jobban a dolgokat külön szerverekre. Bár meglehetne oldani úgy, hogy külön szerveren vannak mondjuk az eventek de az event pontok meg inventory megosztott lenne. Ez egy elég nagy projekt lenne. Ha a jövőben több játékos lesz, akkor lehet meglesznek valósítva ilyen megoldások is.

**Comment by andris155** [comment]
De a Towny-ra mindenképpen jobb szerintem egy külön szerver. Teljesen más játékmód mondhatni.
