### ISSUE TITLE
ChatControl "cocák"

### ISSUE THREAD

**Issue by poma123** [andris155/TheOld-Crafters#3255]
**Szerver**: Összes

**Verzió**: 1.14.4

Ha valaki kiírja, hogy "cocák", csúnya szónak veszi.

**Comment by MrZero1** [comment]
Nem kell használni. problem solved 🤔

**Comment by poma123** [comment]
ok, attól még szerintem hiba hogy ezt annak veszi

**Comment by skrisz0101** [comment]
Coca poma

**Comment by andris155** [comment]
A staffoktól kérdezhetnél egy ID-t, amit kiír, amikor írod.

**Comment by poma123** [comment]
most kiírtam megint és kérdeztem egyik se válaszol. konzolban nem tudod nézni?

**Comment by poma123** [comment]
ID: unset, de küldök képet mindjárt

**Comment by poma123** [comment]
![image](https://user-images.githubusercontent.com/25465545/66261302-12b8f780-e7cb-11e9-9953-2e2a3b4afd2c.png)

**Comment by andris155** [comment]
Hát így nem lesz egyszerű megtalálni. De legalább tudom azt is, hogy kell ezeknek ID-t adni.

**Comment by poma123** [comment]
szerintem meg van melyik az, a 'cock' nál érzékeli a plusz ékezetes betűt a c és a k között

**Comment by andris155** [comment]
javítva
