### ISSUE TITLE
Savsziget eventek hiba

### ISSUE THREAD

**Issue by KingDeadZ** [andris155/TheOld-Crafters#3257]
Az eventekre nem lehet bevinni ételt, de nem töltődik magától.

**Comment by andris155** [comment]
A túlélőn ez, hogy működik?

**Comment by KingDeadZ** [comment]
Ha jól tudom, ott sem lehet bevinni tárgyakat, de ott töltődik az étel.

**Comment by andris155** [comment]
@MrZero1 flag-el van ez megoldva, vagy mivel?

**Comment by poma123** [comment]
Flag igen. a __global__ régión van feed-amount és feed-delay. (az első 20, a második pedig 5 mondjuk)

**Comment by MrZero1** [comment]
Köszi, majd Sweet megcsinálja, leírtam neki a parancsokat.

**Comment by MrZero1** [comment]
Köszi mégegyszer, küldtem némi OCD-t.

**Comment by KingDeadZ** [comment]
Köszönöm! :)
