### ISSUE TITLE
Savsziget: /is top hiba

### ISSUE THREAD

**Issue by Icecroft** [andris155/TheOld-Crafters#3258]
A savszigeten az /is top nem a helyes értéket mutatja, hanem azt az értéket, ami az 1.13/1.14 váltásnál benne maradt. Ha kiadok egy /is level-t, akkor a saját szintemet újra jól mutatja, de a következő loginnál minden visszaáll a régire.

**Comment by andris155** [comment]
most jó?

**Comment by Icecroft** [comment]
Igen, jónak tűnik relogin után is. Szerintem ha holnap is OK a hajnali szerver restart után, akkor lezárhatjuk.

**Comment by andris155** [comment]
Továbbra is jó?

**Comment by Icecroft** [comment]
Szia Andris, most próbáltam, jól működik. Zárhatod az incidenst nyugodtan.

**Comment by andris155** [comment]
Köszi

**Comment by andris155** [comment]
508 OCD
