### ISSUE TITLE
Mcmmo potik - szurvi, sav

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#3259]
Ugye az mcmmonak az alkímia része konkrétan az újfajta potikkal foglalkozik (+11 fajta potival) 
 
Na, ez tök jó meg minden, DE:
-játékosok 99%-a azt se tudja mi az, mert egyszerűen elérhetetlen :) 
-ha valaki esetleg tudja, nem tudja előállítani

Elég hasznos potikat ad, szóval sztem nem kéne ennyire elhanyagolni :(

Na de igazából csak ennyit akartam:
Az alkímia skill XP követelését jó lenne minimum a 10-edére venni, ha nem többre. 
Úgy még értelme is lenne a dolognak :) 

Mert így kB lefőzhetek 1000 potit hogy meglegyen 100as szint (1000 a,, max")

**Comment by KingDeadZ** [comment]
Akkor fel lehetne tolni az alchemy exp rate-t 5xre, ha van rá lehetőség. az sztem tök korrekt.

**Comment by skrisz0101** [comment]
10x

**Comment by KingDeadZ** [comment]
Nagyon könnyű lenne akkor... Ahhoz képest nagyon op dolgokat ad be az mcmmo, hogy fél óra alatt ki lehessen maxolni.

**Comment by andris155** [comment]
Nem szeretnék ezen módosítani.

**Comment by skrisz0101** [comment]
@andris155 akkor feleslegesen van bent :/
1 éve senki se csinálta még, mert elérhetetlen :D

**Comment by skrisz0101** [comment]
Hm @andris155
