### ISSUE TITLE
Szavazásért kulcs

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#3261]
Sav és Survi szerveren 1 szavazás után járhatna Fortuna kulcs, plusz ami most is, így hátha többen szavaznának.

**Comment by andris155** [comment]
minden szavazás után akkor? vagy az első szavazás után?

**Comment by MrZero1** [comment]
Minden szavazás után

**Comment by andris155** [comment]
Nem lenne az már úgy kicsit sok érte? A szavazás lényege, hogy nekünk és a játékosoknak is megérje. De az sem jó, ha túlságosan megéri a játékosoknak, mert az meg már a játékélményt fogja rontani.

**Comment by MrZero1** [comment]
Úgy gondolom, hogy nem rontja, ez a kulcs amúgyis elérhető 8 óránként (1db), olyan sok érték nincs benne

**Comment by MrZero1** [comment]
@poma123  majd ha lesz jogod ☺

**Comment by poma123** [comment]
majd holnap :)')')')')

**Comment by Wexthory** [comment]
Szavazói ládából nyithatóvá tenni a szavazói szettet? :v

**Comment by poma123** [comment]
kész

**Comment by MrZero1** [comment]
A szavazói szett elég OP ahhoz, hogy a ládából nyitható legyen. Esetleg egy másik, hasonló nevű de nem X-es szettet csinálhatok, azt berakhatjuk ha jó
