### ISSUE TITLE
Szavazós VIP rang 

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#3262]
Ez a szavazós rang is 30 napra szól, nem?

**Comment by MrZero1** [comment]
![kép](https://user-images.githubusercontent.com/29709854/66717874-1574a780-edde-11e9-8001-2f2c1b7f02d9.png)
kép lemaradt bocsi

**Comment by andris155** [comment]
Ez a leírás miben van?

**Comment by MrZero1** [comment]
/rangok és a VIP leírásra (üveglap) kattints és ott írja ki ezt

**Comment by andris155** [comment]
javítva
