### ISSUE TITLE
SlimeFun 1.14.4 - folyamatos javítások - TesztSzervert!

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#3263]
Több fejlesztő is továbbvitte a slimefun fejlesztését!
Pomával kipróbáltuk milyen, 1-2 régi addolási lehetőséget kipróbáltunk, JAVÍTOTTÁK!
DE:
-Ki kéne próbálni egy tesztszerveren (tocon bellül), hogy mennyire működik, vagy épp nem működik jól, hogy mennyire laggoltat, vagy épp nem laggoltat. ahogy néztük,, nagyon friss verziók vannak. poma kettőt mutatott, egyik valami szeptember vége, a másik október 13 (tegnapi xd)

Azaz folyamatosan fejlesztik, (de szerintem a hibajavításokra megy még a fejlesztő)
Szóóóval, ki lehetne próbálni egy külön tesztszerveren, mint annó az 1.14-et.
funnak is jó volt, és tesztnek is jó volt. szerintem nincs vele semmi vesztenivaló

+Ugye mindenki tudja (aki volt annó), hogy mennyit dob a játékélményen és a játékhosszon.
(segítség: SOKAT)

ha ez bekerülne, akkor szerintem nem is kell a craftolós plugin (ami tervben van), mert ebbe ugyanúgy lehet sütéseket, craftokat csinálni, csak sokkal szélesebb körben.
(nem tudom melyik lenne nagyobb macera craftbeállításoknál, sf vagy az új craftos) 

@poma123 - egyéb megjegyzés?
@MrZero1 remélem pozitívan állsz hozzá :(
@andris155 légyszi ne zárd le egyből, köszi :(
@KingDeadZ mondj te is valamit 
@UDPSendToFailed régi bugok jöhetnének ide, hogy lehessen tesztelni.

Egyéb emberkék véleménye is jöhet nyugodtan, de aki negatívan ír, azt megeszem 💯 
Ötletek jöhetnek boltomba is!  [/Pwarp skrisz01] - akciós a vödrös hal! (elfogyott)

**Comment by UDPSendToFailed** [comment]
Támogatom, így lenne értelme a játéknak azok számára is, akik a survival részét már "végigvitték". A tesztelésben tudok segíteni, időm van rá.

**Comment by KingDeadZ** [comment]
Én is támogatom, és szivesen részt vennék a tesztelésen ha lenne rá lehetőség.

**Comment by KingDeadZ** [comment]
Hogyha lenne tesztelés, és nem lenne vele semmi gond, azonban úgy lenne megítélve, hogy a laggosság miatt nem kerülne be survira, akár lehetne egy másik szerveren is, ami a slimefunra épül, de úgy mondjuk hogy ott nem lenne kreatív,fly,god a rangoknak.

**Comment by skrisz0101** [comment]
De azért ha lehet maradjunk a szurvinál :c

**Comment by KingDeadZ** [comment]
Esetleg, ha nagyobb rendszereknél laggos lenne, meglehetne próbálni a cargo-k nélkül.

**Comment by MrZero1** [comment]
Ha esetleg lenne, akkor bizonyos dolgokat mindenképp lekellene tiltani (cargo spawner pl).

**Comment by skrisz0101** [comment]
a ,,laggoltat-e vagy sem"-kor pont a cargora gondoltam ':D

**Comment by poma123** [comment]
Javítanék, először is TheBusyBiscuit, vagyis a fő fejlesztő vitte tovább, bár kis Pull Requestekkel.
[Slimefun tabil verziók](https://thebusybiscuit.github.io/builds/TheBusyBiscuit/Slimefun4/stable/)
[Slimefun dev verziók](https://thebusybiscuit.github.io/builds/TheBusyBiscuit/Slimefun4/master/) /_ezt nem ajánlott nyilvános szerveren használni_/

**Comment by poma123** [comment]
Egyébként a teszt szerverről annyit, hogy a mostani állapotok miatt (elég sokszor van lag) szerintem nem lenne eredményes a "lag" teszt azon a külön teszt szerveren, mivel úgyis kevesebb RAM lenne oda megadva, mint pl. Survival-ra. Tegnap este kedvet kapva összedobtam egy hamachis otthoni teszt szervert, és ott néztük sk-val a dolgokat. "Nagy lag teszt" még nem volt, amire majd sort kellene keríteni pl. cargoval kapcsolatban. Mindenesetre optimisták vagyunk. :D

**Comment by skrisz0101** [comment]
Leginkább a régi addolási lehetőségek és a bugkihasználások miatt kéne a tesztszeró.

**Comment by poma123** [comment]
Így van, viszont azt a localon is tudjuk tesztelni, ha megtalálnám a ghost régi videóját. :D
Ja, btw ghost ha ezt olvasod küldd már el a youtube linkjét az sf addolás videónak :D

**Comment by andris155** [comment]
Teszt szerverre nincs se kedvem se időm. Ha bekerülne biztosan a sima szerverre kerül csak majd be egyből.

**Comment by andris155** [comment]
Az Exotic Garden a világ tönkre tételére nagyon jó. A sok fej iszonyú akadásokat generál az FPS-ben. Ez soha nem fog bekerülni.

**Comment by andris155** [comment]
A Vanilla Additions kikerülésével kerülhetne ez be. Döntsétek el melyik kell. A 2 együtt nem fog így működni. Vagyis nem szeretném már ennyire vegyíteni a dolgokat.

**Comment by KingDeadZ** [comment]
Szerintem lehetne erről a facebook oldalon/a facebook csoportban egy szavazás hogy Melyik lenne a jobb.

**Comment by poma123** [comment]
írtam Andris fb-on majd nézd meg, bocsi hogy így össze-vissza írok :D

**Comment by poma123** [comment]
teszt szerverként pedig én tudok funkcionálni, csak a hamachi-t kell letölteni és adok ipt meg jelszót ha valaki fel akar jönni, viszont nem fut mindig, csak ha gépnél vagyok és szükség van rá :D

**Comment by skrisz0101** [comment]
Ha időm lesz (ma és holnap kevés),
Akkor letesztelem hogy a cargo mennyire tud laggoltatni, mennyire működnek a gépek(vagy sem) +az addolási lehetőségeket
@poma123

**Comment by poma123** [comment]
oké, viszont ahhoz én is kellek majd :D

**Comment by skrisz0101** [comment]
@andris155 szerintem ha dönteni kéne, akkor a slimefun, az azért sokkal többet ad mint a vanília :D
(mondjuk nemtom miért nem fér el egymás mellett, de nem vagyok telhetetlen xd)

**Comment by poma123** [comment]
És majd el kell dönteni, hogy az sf-es electricspawnerek és broken spawnerek legyenek (kell majd beváltani a mostani spawnereket), vagy a mostani saját pluginom.

**Comment by KingDeadZ** [comment]
Andris nem szeretné vegyíteni annyira, azt mondta. De inkább a közösséggel kéne megszavaztatni, minthogy pár ember vagy az adminok döntsenek efelől szerintem.

**Comment by poma123** [comment]
Ma este egyébként tesztelni fogunk a hamachis szerón, legalábbis skval ketten biztos, 20:30/21:00 körül. Ha valaki még jönni szeretne írjon privátot (fbon, dcn vagy spigotmcn is lehet akár.)

**Comment by skrisz0101** [comment]
@KingDeadZ csak hogy nem mindenki emlékszik egy 2 éves pluginra, elég valószínű hogy az ujak is szavaznak akik nem is hallottak róla. Így még értelmét vesztené a szavazás :/

**Comment by poma123** [comment]
Összegzés: #3265

**Comment by poma123** [comment]
Szerintem ez a jelentés lezárható, az összegzésben van feltüntetve minden fontos infó :D.

**Comment by MrZero1** [comment]
Az ügyet a #3265 jelentésen folytatjuk tovább.
