### ISSUE TITLE
Survival - levédés elnevezése és törlése távolról / teleportálás a levédésre

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#3264]
Régebben levédtem pár helyet, amikre már nincs szükségem, de ha nem állok a védésen belül, nem lehet törölni. Több 10.000 blokkot kéne sétálnom csak azért, hogy törölhessem őket.

![kép](https://user-images.githubusercontent.com/16057404/66785195-d24d2e00-eedc-11e9-8805-fd61b0cbd4c8.png)

**Comment by poma123** [comment]
ha van API hozzá, plugin szinten megoldható csinálni egy külön parancsot(akár gui-t de az kicsit több idő :D) ahol kilistázza a saját a levédéseket és ott törölni. fogalmam sincs, hogy és miképp. esetleg ha lesz időm utánanézek

**Comment by andris155** [comment]
A /AbandonAllClaims paranccsal tudod törölni az összeset. Vagy esetleg kérj meg egy admint, hogy menjen el oda, amelyiket törölni akarod és törölje neked a /AbandonClaim paranccsal.
