### ISSUE TITLE
Slimefun teszt - összegzés

### ISSUE THREAD

**Issue by poma123** [andris155/TheOld-Crafters#3265]
![image](https://user-images.githubusercontent.com/25465545/67131727-135b8000-f206-11e9-8e26-4249d06e660d.png)
<h2 align="center">Slimefun összegzés</h2>

_(A poszt folyamatosan frissül)_

### A SLIMEFUN BEKERÜLT A SZERVERRE!

Slimefun stabil verzió: [link](https://thebusybiscuit.github.io/builds/TheBusyBiscuit/Slimefun4/stable/#2)
ExtraGear kiegészítő (dev. verzió, de jól működik): [link](https://thebusybiscuit.github.io/builds/TheBusyBiscuit/ExtraGear/master/#3)
Luckyblock kiegészítő (dev. verzió, de jól működik): [link](https://thebusybiscuit.github.io/builds/TheBusyBiscuit/luckyblocks-sf/master/#13)
~~ElectricSpawners kiegészítő (dev. verzió, de jól működik): [link](https://thebusybiscuit.github.io/builds/TheBusyBiscuit/ElectricSpawners/master/#5)~~
ElectricSpawners nem lesz, mivel túl sok állatot idéz le, ami többek között lagot okozna.
<br>
<details><summary><b>A tesztelésről (Kattints ide!)</b></summary>
<br>
Teszteltük a mai nap folyamán (2019. 10. 15.) a Slimefun régi hibáit, illetve gondolkodtunk picit.
Ha valaki emlékszik régi addolási módra, hibára, kérlek ide írjon, hogy mi volt az pontosan.
(Az ötlet legelső „felvetése” a #3263 -es jelentésben található.)

### Javított hibák / Tesztelt dolgok:
1. Nem működik a régi addolás, leteszteltük.
2. Nem működik már az ancient altaros addolás sem.
3. A régi block placeres addolási mód sem műküdik.
4. A lucky block és pandora box lerakás jól működik, más levédésén és telkén nem lehet letenni és kiütni.
4. A robbanó itemek jól működnek, más levédésén és telkén nem robban.
5. Az Elemental Staff - Storm item jól működik, más levédésén és telkén nem sebzi az állatokat.
6. A két legutóbbi youtube-os addolás nem működik.

### Hibák:
1. A bányász android kibányássza a kreatívban letett blokkokat is, ezért a bányász androidot le kell majd tiltani.
2. A Seeker csákány nem működik, kivehető. (errort ír konzolban)
![image](https://user-images.githubusercontent.com/25465545/66868289-5961db00-ef9d-11e9-893b-1a139b78605e.png)

  3. **A GriefPrevention info bot sem jó, mivel ha sf-es item egy bot, akkor az az sf-es item nem fog működni. Át kellene tenni mondjuk bőrre, vagy más itemre a griefp. infó botot.**

### Egyéb tapasztalat:
1. A spawnerekkel kapcsolatban arra jutottunk, hogy ajánlott lenne visszatenni az sf-es spawnereket ahogy voltak, és egy falusis átváltót, hogy az én pluginom által kontrollált spawnereket át lehessen váltani brokenre. (Az átállás után ha leteszi valaki az én pluginom általi spawnereket, sima malac spawnerek lesznek)
2. A lucky blockokkal pedig arra jutottunk, hogy jobb lenne visszatenni az sf-es lucky/pandora blokkokat, és letiltani azokat az eseményeket, amik nem jók (pl. **Void Hole**: a 0-256-ig levegőoszlopot csináló cucc, stb.).
3. Plusz a cargoval kapcsolatban, igaz, nem teszteltük 100 cargoval, de nem észleltem semmi lagot, szóval az lenne ajánlott hogy egy tesztidőszakra, pl. 1 hétre (ha bekerül az sf) bent hagyni a cargot is, és hogyha lagot okoz, akkor kivenni. Szerintem így lehetne ezt élesben tesztelni.
4. FRISSÍTÉS: A Digital Minereket ajánlott kivenni, mivel alapból is ki lesznek véve, és túl op-k.

### Ajánlott tesztelések élesben TOC-on:
1. Tesztelni a cargot egy hétig például, és ha a hét folyamán laggot okoz, akkor letiltani.
</p>
</details>
<hr>

<details><summary><b>Teendők /<i>telepítés után</i>/ (Kattints ide!)</b></summary>
<br>

### Módosítás:
- [x] Kivenni az én spawner pluginomat, és beváltó falusit létrehozni átváltáshoz broken spawnerekké.
- [x] Módosítani a GriefPrevention info itemet botról valami másra.
- [x] Sf warpon kicserélni a rainbow glass, rainbow glass pane, rainbow clay, rainbow wool-okat.
- [x] Sf warpon megcsinálni a Saw Mill pontos új kinézetét.
### Letiltás:
- [x] Digital Miner
- [x] Advanced Digital Miner
- [x] Seeker Pickaxe
- [x] Miner Android
### Új tárgyak sf warpon:
- [x] Elemental Staff - Storm (Leírás: Villámokat szórhatsz vele.)
</details>

**Comment by andris155** [comment]
Miért kellett egyáltalán kilépned? Oké az OldVillage nem sikerült, de attól a túlélőn meg savszigeten még maradhattál volna segíteni. Meg akkor ott lenne a teszt szerver is.

**Comment by andris155** [comment]
Ha maradtál volna most nem kellene saját szerveren vagy nem tudom hol tesztelgetni. Illetve normálisan le lett volna tesztelve. Mert így biztosan maradnak hibák, amik csak később derülnek majd ki.

**Comment by poma123** [comment]
leírom privátba.

**Comment by UDPSendToFailed** [comment]
Tölcsérbe kellett esnie a kreás itemnek, onnan ment át a block placerbe, ami lerakta, de azóta változtatva lett védelmi plugin, nem lesz item a kiütött blokkokból.

**Comment by poma123** [comment]
> Tölcsérbe kellett esnie a kreás itemnek, onnan ment át a block placerbe, ami lerakta, de azóta változtatva lett védelmi plugin, nem lesz item a kiütött blokkokból.

Rendben, köszi!

**Comment by MrZero1** [comment]
Az remek, ha a régi addolásos/duplikálós dolgok már nem mennek, de mi az esély, hogy ezáltal nem lettek újak? Azért ennek is érdemes lenne utánanézni (google, yt), hogy van e, és ha van, az valóban működik vagy sem. Továbbá, Spawnert és Cargot nem szeretnék. Az, hogy egy tesztszerveren néhány nem okozott gondot, az szuper, de ha már minden második ember többet lerak a szerveren, akkor úgy már lehet. Luckyblock lehet, amennyiben az X-es szett kikerül belőle. Vàrom a további fejleményeket. ⚙️

**Comment by KingDeadZ** [comment]
A lucky block egy sf addon, és mivel már van bent egy lucky blockos plugin, így fölösleges lenne berakni.

A spawner szerintem jó ötlet lenne viszont, mert jelen pillanatban az összes spawner ingyen működik, így legalább lenne egy kis költsége annak, hogy működjön. A cargo tényleg felesleges, az tény.

Mivel a plugin folyamatos fejlesztés alatt van, így a bugok valószínűleg javítva lesznek, és ha vannak duplikációs bugok, akkor azokat az itemeket le lehetne tiltani/módosítani a craft receptjét hogy ne lehessen használni, ameddig nincs kijavítva.

**Comment by skrisz0101** [comment]
@MrZero1
Luckyblock: igen, lehet kicsit op az x-és cucc, de akkor lehetne a helyébe valami olyasmi mint ami a mostaniból jön.
@KingDeadZ: mostani lucky kikerülne, mert az sf-s jobb (szerintünk)
Bár esetleg lehetne olyat is csinálni hogy egyesítjük, és a jó dolgokat átrakjuk egyikből a másik fajta luckyblock pluginba. 
Pl a mostani lucky pluginból a giant zombispawn mehetne az sf-s luckyba, remélem érthető mit írtam xd

Spawner: a mostani spawnerpluginnal annyi  spawnert szedsz, amennyit csak akarsz, de azt teljesen ingyért le is rakhatod
Azért a slimefunos spawnerért eléggé meg kell küzdeni, hogy le tudd rakni 
(sf spawner annyit spawnol mint a sima) 

Cargo: ez viszi a játékléményt a végtelenbe. 
Azért lett írva a teszt, hogy le lehessen tesztelni MÉG laggoltat-e, vagy sem. 
1 hét alatt meg amúgy se lehet megváltani a világot cargoval. 

Újabb hibák: hát erre nem tudok mit mondani, 2-3 új dolog került be csak, azon kívül az égatta világon szerintem semmit se változtattak. 
+1,, hír" : a digital minert ki fogja venni a fejlesztő, szóval ki lehetne venni azt is.

**Comment by poma123** [comment]
Oké, nem muszáj a cargo, és nem is tudtuk tesztelni, mivel nem lett volna értelme. Ezért írtam hogy egy hétig teszt üzenben benthagyni, aztán ha laggoltat kivenni. De persze csak egy ötlet volt :D.

Nekem igazából teljesen mindegy hogy melyik spawner meg lucky van. Tény, hogy az sf-es spawnerért többet kell küzdeni.

**Comment by skrisz0101** [comment]
(amúgy az sf-s luckyblock is drágább)

**Comment by poma123** [comment]
új infók a "FRISSÍTÉS:" után mindig.

**Comment by poma123** [comment]
ElectricSpawners is tesztelve :)
![image](https://user-images.githubusercontent.com/25465545/67044073-c99e6700-f12b-11e9-9896-06e7bd002c5e.png)

**Comment by skrisz0101** [comment]
@poma123 a spawner Ugyanúgy lesz, mint ahogy leírtad. Az electricspawner már annak a Továbbfejlesztett változata. 
Ugyanúgy sf-s spawnerek lennének

**Comment by poma123** [comment]
K
