### ISSUE TITLE
Survival: Pet a flatworldben; ládás bolt

### ISSUE THREAD

**Issue by Wexthory** [andris155/TheOld-Crafters#3266]
1. Néhány warpon ami flat worldben van a /petswitch kód működik és így elő lehet hívni a petet amivel ki lehet buggolni a warpról és a pet tudja aktiválni a nyomólapokat is.

2. Néhány itemmel nem lehet boltot csinálni, vagy csak én nem tudom hogy kell. Hiába írom be az item nevéhez azt amit /iteminfo-nál ír, elkészül a bolt, a plugin elfogadja és mégse lehet eladni/venni. Pl.: Fortuna kulcs.

**Comment by andris155** [comment]
A petes javítva. A kulcsos nekem működik.

**Comment by andris155** [comment]
![2019-10-16_10 45 01](https://user-images.githubusercontent.com/8324198/66903094-18e87880-f002-11e9-9790-708a4a5028c1.png)

**Comment by Wexthory** [comment]
"Tegnp": Játékosként a tábla írásának bezárása után ahogy megnyitja sikeresen a boltot eltünteti a #65-öt. Kittivel is próbáltuk, amikor ő írta a táblát akkor ott maradt és mégse engedte eladni. (lehet csak elyrás amit nem vettünk észre?)

**Comment by andris155** [comment]
Most is eltünteti a # részt?

**Comment by andris155** [comment]
Illetve a chat-en kitudod írni a #-et, ha eltünteti?
