### ISSUE TITLE
Savsziget

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#3268]
Savsziget fejlesztési javaslatok:

- [x] Rangok árának átgondolása #3008
- [x] VIP sziget változtatás
- [x] Old láda bekerülése
- [x] Pet a küldetésekbe #3175
- [x] Mégtöbb event  #3031
- [x] Tokenes beváltóba új szett, itemek
- [x] Napieventek ládajutalmak változtatása

Folyamatosan bővülő lista.

**Comment by MrZero1** [comment]
Főként azért nyitottam új listát, mert ezek az elsődleges elvégezendő dolgok. 
A beváltóra @poma123  valami olyasmit mondott, hogy csinál hozzá valami opciót. Remélem azzal mi is tudjuk szerkeszteni szerveren belül majd :D

**Comment by Niccolettie** [comment]
https://github.com/andris155/TheOld-Crafters/issues/3008
:((

**Comment by poma123** [comment]
Tokenes beváltó szerkesztőt elkészítettem :D /tokeneditor

**Comment by MrZero1** [comment]
A pet kiesik, mert nem érkezett rá semmiféle reakció, a kérések ellenére sem. Ez van.
