### ISSUE TITLE
Titkos home

### ISSUE THREAD

**Issue by Balint2** [andris155/TheOld-Crafters#327]
ha valakinek túl hosszú a home neve akkor staff nem tudja megnézni, mert az már nem fér ki. Pl.
kifér az hogy /sethome aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
nyilván az is hogy /home aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
de az már nem fér ki nektek hogy /home Balint2:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
/Balint2/

**Comment by andris155** [comment]
A konfigból könnyen meglehet nézni a koordinátákat. Illetve szerintem lehet parancsblokkal is megoldható, hogy oda teleportáljon, esetleg konzollal.

**Comment by Balint2** [comment]
igaz, meg azért gyanús is az a player, aki titkolja, de azért inkább jelentem.
