### ISSUE TITLE
Slimefun - lehetséges XP bugoltatás

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#3271]
Ha a slimefun könyvben elkezdek valamit fejleszteni, és miközben számolja a százalékokat chaten, belépek valamilyen minigame-re, mikor elér 100%-hoz, a minigame területén megnyitja a slimefun könyv invjét.
Egyedül nem lehet bugoltatni, de több játékossal megvan rá az esély, mivel ott a nyitott sf könyv, és a minigame-k idő számlálója, ami általában az XP szintnél írja a másodperceket.

Szerintem survivalgames világban tiltható a slimefun úgy ahogy van, régen se volt engedélyezve.

**Comment by poma123** [comment]
Le lehet tiltani az sf-et survivalgames-ben, meg is történt már tegnap, csak elfelejtettem lezárni.
