### ISSUE TITLE
Ötlet - Survival

### ISSUE THREAD

**Issue by KingDeadZ** [andris155/TheOld-Crafters#3272]
Lehetne átváltó a régi lucky blockról az újra.

**Comment by UDPSendToFailed** [comment]
+1
Ez kb 1-1.5 millió $ értékű lucky block, ami jelenleg max arra jó, hogy házat építsek belőle.

![kép](https://user-images.githubusercontent.com/16057404/67195675-a90b3100-f3f9-11e9-9c70-de675bdc8887.png)

**Comment by MrZero1** [comment]
Akkor ezt lezárom

**Comment by skrisz0101** [comment]
Vagy mégse? @MrZero1
