### ISSUE TITLE
Slimefun teszt szerver - hibajelentések

### ISSUE THREAD

**Issue by poma123** [andris155/TheOld-Crafters#3273]
Kérjük ez alá a jelentés alá írd kommentbe a hibát.

**Comment by poma123** [comment]
Kreás sódert ki lehet ütni gold pan-el

**Comment by skrisz0101** [comment]
Pickaxe of vein mininggel ha több kreás ércet akarok kiütni vele akkor mindegyikből megkapom kivéve amit kiütök
(egyszerre többet üt ki)

**Comment by skrisz0101** [comment]
Elvileg nem maradt semmi se, nem?

**Comment by MrDinamit88** [comment]
nagy lajk sk
