### ISSUE TITLE
Levédés időbeállítás

### ISSUE THREAD

**Issue by MrDinamit88** [andris155/TheOld-Crafters#3274]
**Szerver**: Survival
Jó lenne ha pl nem csak az alap beállításokat lehetne a  levédés időmeghatározáskor használni(day noon night midnight).
Gondolok a digitális időre (08:00) pl vagy tickekre (10000).
Szerintem jó lenne :D

**Comment by poma123** [comment]
ok

**Comment by MrDinamit88** [comment]
ok

**Comment by andris155** [comment]
Kérlek írd meg ide az ötletet, majd angolul.
https://github.com/ShaneBeee/GriefPreventionFlags/issues
