### ISSUE TITLE
Lucky Block plugin

### ISSUE THREAD

**Issue by andris155** [andris155/TheOld-Crafters#3275]
**Szerverek**: túlélő, savsziget

Slimefun lucky block (visszatéve), mivel a régi borzalmasan volt optimalizálva, és hozzá átváltó.

**Comment by MrZero1** [comment]
Átváltó hogy? Nem egy fajta NBT-s luckyblock van.

**Comment by poma123** [comment]
Nem csak 1 nbtje van a kraftolt lucky blocknak?
