### ISSUE TITLE
SF cuccok letiltása eventeken

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#3278]
A cím mindent elárul. Legyenek letiltva, mert van, amivel lehet csalni (multitool, staff megmittudomén). 
@poma123  @andris155

**Comment by UDPSendToFailed** [comment]
#3271

**Comment by poma123** [comment]
amúgy ha megjelöltök itt nem fog nekem semmilyen értesítést küldeni

**Comment by poma123** [comment]
letiltottam
