### ISSUE TITLE
NoCheatPlus fork + konfig hiba

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#3279]
Survivalon már többen is jelezték ezt. Fel és lefelé építkezés
![kép](https://user-images.githubusercontent.com/29709854/67515500-0d9aea00-f69f-11e9-95e8-b7313d06c45e.png)

**Comment by andris155** [comment]
A következő plugin verzió majd biztosan javítja. Viszont addig várni kell még sajnos.

**Comment by andris155** [comment]
Most jó?
