### ISSUE TITLE
MyPet / mcMMO bug

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#328]
Ha karddal jobbklikkelek, és a "Fűrészes csapás aktiválva" szöveg után megütök egy petet, meghal tőle, mintha mob / másik pet ölte volna meg.

**Comment by andris155** [comment]
Angolul nem tudod véletlen a skill nevét?

**Comment by UDPSendToFailed** [comment]
Serrated Strikes

![2016-11-01_11 38 16](https://cloud.githubusercontent.com/assets/16057404/19887444/b378c5f8-a028-11e6-8543-5b2bfae11b98.png)

**Comment by UDPSendToFailed** [comment]
Ezért már nem nyitok újat, ásás skillnél fordítás hiba:

![2016-11-01_11 37 10](https://cloud.githubusercontent.com/assets/16057404/19887489/eb300b28-a028-11e6-990f-e3773ee5e254.png)

**Comment by UDPSendToFailed** [comment]
+1 hiba: A `/mcscoreboard time 3` parancs után kifagy a scoreboard, `/mcscoreboard clear` nem hat rá. 1-2 másodperccel jó, de 3 felett hibás, nem frissül, és csak relog után tűnik el.

**Comment by andris155** [comment]
https://github.com/andris155/TheOld-Crafters/issues/348
