### ISSUE TITLE
Minemarket - Slimefun

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#3280]
Lehetne a minemarketen slimefun rész, mint régen, ha az sf,, tesztszakasza" véget ér. 

Ugyanúgy kB mint régen. 
Neptunium, android, blistering, nukleár reaktor meg nemtom még mik voltak. 

Egy nukleár reaktornyi ocd-t elfogadok az ötletért. Köszpusz

**Comment by Niccolettie** [comment]
vagy inkább az ötletedért cserébe nem vernek agyon félig! :D

**Comment by andris155** [comment]
Sok ötletet írnak meg hibát is, de sokszor csak simán privátban a Facebook-on meg a szerveren is. Ami tök jó, mert legalább szól, de ezeket a legtöbbször nem egy perc megoldani vagy megvalósítani. Így később szoktam vele foglalkozni. Ezért szoktam mondani, hogy inkább ide írjátok, hogy ne legyen elfelejtve. Mert ha jó ötlet, vagy olyan hiba, amit lehet javítani, akkor biztosan meglesz oldva, előbb vagy utóbb.

**Comment by andris155** [comment]
A régiek kerüljenek vissza ugyan azon az áron? @MrZero1

**Comment by MrZero1** [comment]
Sajnos nem tudom mik voltak, de amik régen voltak, azok is visszakerülhetnek, illetve amit úgy gondolnak a játékosok. Összeírom majd a listát, mit érné meg és mennyiért.

**Comment by MrZero1** [comment]
4 db Boosten uranium - 508 OCD
4 db Neptunium - 508 OCD (ennél a név Firebolt (??))
5 db Plutonium - 508 OCD
Blistering Ingot - 508 OCD (ennél a név Nimbus2001, gondolom a seprű lett a helyén?)
Ezeknek van tábla az SF warpon.

**Comment by MrZero1** [comment]
theold.minemarket.hu/category/slimefunsurvival
Régi a link, de nem lehet megnézni mi volt rajta anno?xd

**Comment by skrisz0101** [comment]
Több már le lett ütve. Az 1. 3mat igazából max nukleár reaktorba lehet rakni üzemanyagként és kész, max 1-2 dologra használhatóak.

Blistering az jöhet, fontos dolog. De kicsit drága, lehetne pl 3db 508ocd/330ocd

Aztán szerintem lehetne:
 sima android 508ocd
Nukleár reaktor 1016 ocd
6db reinforced alloy ingot 508ocd
6db redstone alloy ingot 330ocd
6db carbonado  508ocd
2db essence of soul 508ocd

**Comment by poma123** [comment]
web.archive.org - nincs mentés róla
http://cachedview.com/ - nincs mentés róla

**Comment by UDPSendToFailed** [comment]
A neptunium és a plutonium a nuclear reactor melléktermékei, sima uranium-ból ezek lesznek, azt pedig sóderből lehet pár lépésben csinálni. Így, hogy bugos, azt a 4-5 darabot egy óra alatt elégetné a semmiért. 

A komolyabb gépek, amik end-game szintűek, szerintem jobban megérnék az OCD-t.

**Comment by skrisz0101** [comment]
@UDPSendToFailed e-gépeket direkt nem írtam bele :/

**Comment by skrisz0101** [comment]
Nemtom nem-e lenne túlzás az end-game gépeket is beletenni minemarketre

**Comment by andris155** [comment]
A slimefun warpon kint vannak elvileg a minemarket táblák. Azok voltak.

**Comment by skrisz0101** [comment]
Sok már le lett ütve (@poma123 xd)

**Comment by poma123** [comment]
vissza vontam amik ki voltak ütve (1 dbot találtam (xd) )

**Comment by andris155** [comment]
Akkor végül mik legyenek, és mennyi OCD-ért? Sajnos már nekem sincs meg mik voltak régen pontosan.

**Comment by poma123** [comment]
Sokat kutattam, árakat nem tudok még, majd meg kell beszélni.
Régi hasonló poszt, ahol meg volt kérdezve hogy mi legyen vásárolható: #553

**Comment by MrZero1** [comment]
4 db Boosten uranium - 508 OCD
4 db Neptunium - 508 OCD 
5 db Plutonium - 508 OCD
Blistering Ingot - 508 OCD

Ezeket nem tudom, én nem értek ehhez, de Sk javasolta fentebb: 
(kicsit azért módosítottam rajta)

Sima android 508 OCD
Nukleár reaktor 1016 OCD
5db reinforced alloy ingot 508 OCD
5db redstone alloy ingot 508 OCD
5db carbonado 508 OCD
2db essence of soul 508 OCD
1db carbonado capacitor 1016 OCD

**Comment by MrZero1** [comment]
Továbbá, egy Soulbound szett, ami az Old szett tulajdonságait (kicsit gyengítve) tudja? 1016 OCD / 1 szett darab

**Comment by skrisz0101** [comment]
Redstone alloy maradhatna 320, nem ér annyit mint a reinforced. A carbonado meg igazából csak sok szén tömören 😂
A többi szerintem okés

**Comment by KingDeadZ** [comment]
Blistering ingot,boosted uranium,neptunium,plutoniumhoz járhatna shulker doboz, mivel ha valakin nincs anti-rad ruha akkor meghal.

**Comment by andris155** [comment]
Akkor ismét megkérdezem. Végül mik kerüljenek be, és mennyi OCD-ért? :D

**Comment by poma123** [comment]
(ezek shulkerbe ha megoldható)
4 db Boosten uranium - 508 OCD
4 db Neptunium - 508 OCD
5 db Plutonium - 508 OCD
Blistering Ingot - 508 OCD

(ezek simán)
Sima android 508 OCD
Nukleár reaktor 1016 OCD
5db reinforced alloy ingot 508 OCD
5db redstone alloy ingot **320** OCD (elvileg nem ér annyit mint a reinforced, de lehet 508 is)
5db carbonado 508 OCD
2db essence of soul 508 OCD
1db carbonado capacitor 1016 OCD

**Comment by UDPSendToFailed** [comment]
Még pár dolog, ami megérné az OCD-t:

Energized Solar Generator - 1016 OCD
Empowered Programmable Android (Normal) - 1524 OCD
Electric Jetpack (VII) - 508 OCD
Jet Boots (VII) - 330 OCD
16db Cargo Motor - 1016 OCD
Radiant Backpack - 330 OCD
Soulbound szett karddal, csákánnyal, ásóval, baltával, kapával - 1016 OCD

**Comment by andris155** [comment]
Mivel túl sok a pluginban a hiba így nem akarok OCD-ért adni inkább semmit hozzá.
