### ISSUE TITLE
Crates - spawnerek frissítése

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#3281]
Survivalon még a régi spawnerek vannak a ládákban, amiket csak átváltás után lehet használni, ha valaki így lerakja, elbugol.

![kép](https://user-images.githubusercontent.com/16057404/67619926-c842fd80-f801-11e9-85f7-b57c320fc7c1.png)

**Comment by poma123** [comment]
Egyébként nem bugol el, ha valaki leteszi nem engedi letenni. De átrakom majd brokenre (ami nem kis munka lesz)

**Comment by poma123** [comment]
átraktam, nem volt olyan nehéz, mert előtte lementettem az összeshez az sf-es spawner párját :D
