### ISSUE TITLE
Slimefun - nuclear reactor hiba

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#3282]
https://gfycat.com/soggyimpolitecattle

Felmegy 82k-ra az energia, aztán hirtelen leesik 66k-ra, és ezt ismételgeti, amíg van benne anyag ahelyett, hogy szinten tartaná. Így folyamatosan égeti az urániumot értelmetlenül.

**Comment by UDPSendToFailed** [comment]
https://github.com/TheBusyBiscuit/Slimefun4/issues/893

**Comment by andris155** [comment]
Egyszer valamikor lehet javítják. Sok esélyt nem látok rá. Addig sajnos nem tudunk ezzel mi sem mit kezdeni.

**Comment by andris155** [comment]
javítva
