### ISSUE TITLE
Itemek kiszedése a Slimefun Guide-ból.

### ISSUE THREAD

**Issue by LordAdam55** [andris155/TheOld-Crafters#3284]
Néha ki lehet szedni a Slimefun Guide-ból itemeket. Pl. vasat a steel ingot receptjéből.

**Szerver**: survival

**Verzió**: 1.14.4

A slimefun-os smeltery-vel nem tudtam steel-t készíteni,erre azt írta hogy nincs elég tudásom, ekkor a steel-hez tartózó dolgokat nyomogattam a guide-ban, erre egyszer csak kidobott belőle és az inventorymban lett egy steel ingot és egy a guide-on belül visszalapozásra szolgáló könyv.

![2019-10-28_12 30 41](https://user-images.githubusercontent.com/46933798/67675568-b8e9be80-f97f-11e9-9f3e-291527aa4a55.png)

![2019-10-28_12 29 52](https://user-images.githubusercontent.com/46933798/67675576-bd15dc00-f97f-11e9-8748-b5e63aacff21.png)

![2019-10-28_12 30 46](https://user-images.githubusercontent.com/46933798/67675577-be470900-f97f-11e9-8ff3-91c45d777c6d.png)

**Comment by poma123** [comment]
Ezt meg kéne nézni, hogy a mostani verzióban is ilyen-e. Előbb volt újraindítás.

**Comment by LordAdam55** [comment]
Most a restart után megpróbáltam és csak a back könyvet tudtam kivenni, eztán nem nyitotta meg a  guide-ot míg ki nem nyitottam egy shulkerboxot, és most megpróbáltam steel ingotot de vasat dobott ki.
![2019-10-28_13 48 42](https://user-images.githubusercontent.com/46933798/67679692-f2272c00-f989-11e9-8bc7-8b34370ce1b8.png)

**Comment by poma123** [comment]
Köszi. Akkor majd ezt is jelenteni kell.

**Comment by poma123** [comment]
A vasas kiszedőset jelentettem, szerintem összefügg ezzel.

**Comment by poma123** [comment]
Javította a fejlesztő, @LordAdam55 meg tudnád nézni, hogy ami neked volt az működik-e még?

**Comment by LordAdam55** [comment]
Most már rendesen működik és nem sikerül kiszedni.

**Comment by poma123** [comment]
Szuper, köszi!
