### ISSUE TITLE
Slimefun - player_head alapú tárgyakkal nem működik az automated crafting chamber

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#3285]
https://github.com/TheBusyBiscuit/Slimefun4/issues/822

Elvileg javítva lett, mégsem jó.

![kép](https://user-images.githubusercontent.com/16057404/67692743-ebf07a00-f9a0-11e9-8687-6fda11c5ec34.png)

**Comment by poma123** [comment]
Nem hiba, mert 9-et kell tenni, nem négyet.
