### ISSUE TITLE
Slimefun - random elbugoló gépek

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#3286]
Véletlenszerűen eltűnnek a gépek kiütéskor és / vagy CSCoreLib fej lesz belőlük. A Trash Can használhatatlan, amint Cargo-val érintkezik (a működésének a lényege lenne, hogy megsemmisítse az onnan érkező itemeket), azonnal sima player fejjé változik.

**Comment by andris155** [comment]
Szerintem ameddig Slimefun létezik ez így lesz és soha nem fogják ezt javítani. Ha ennyi év alatt nem sikerült nekik továbbra sem fogják tudni megoldani.
