### ISSUE TITLE
SlimeFun

### ISSUE THREAD

**Issue by ZachWithAScythe** [andris155/TheOld-Crafters#3287]
**Szerver**: survival
**Verzió**: 1.14.4 
soulbond backpackot nem lehet megcsinálni és nekem elveszett egy gold plan 3-mam

**Comment by poma123** [comment]
Meg lehet csinálni, csak meg kell várni amíg a villám belecsap.
![image](https://user-images.githubusercontent.com/25465545/67755633-c4e58700-fa38-11e9-93ef-26f1814680fa.png)

**Comment by skrisz0101** [comment]
@poma123 van külön craftja a soul tatyónak

**Comment by poma123** [comment]
meg lehet csinálni azt is, ha a soul tatyára gondoltál @ZachWithAScythe 
![image](https://user-images.githubusercontent.com/25465545/67772096-cb382b00-fa59-11e9-9afe-57e45dcecb24.png)
:)

**Comment by poma123** [comment]
De csak akkor fog menni, ha a recepthez szükséges backpack-ot nem nyitod ki az elkészítés előtt :)
