### ISSUE TITLE
Survival - /warp boltban slimefun cuccok eladása

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#3288]
Lehetne a boltban a dustokhoz, ingotokhoz eladás részleg, sok olyan van, ami alig kell 1-2 itemhez, de kidobni azért drága lenne.

**Comment by poma123** [comment]
megvannak a tárgyak amiket régen el lehetett, kernellel meg skval "kitaláltunk" árakat egyelőre csak a dustokhoz van. de még nem eladható.
![image](https://user-images.githubusercontent.com/25465545/67891382-c2775000-fb52-11e9-9eed-6af0c719b69f.png)
![image](https://user-images.githubusercontent.com/25465545/67891367-bd1a0580-fb52-11e9-9896-43ea9845e9f8.png)

![image](https://user-images.githubusercontent.com/25465545/67891388-c6a36d80-fb52-11e9-968b-095e83b5e369.png)

**Comment by MrZero1** [comment]
Ha kell, beárazom a meglévő táblák alapján

**Comment by poma123** [comment]
Köszi, az nagy segítség lenne. :D

**Comment by MrZero1** [comment]
Dustok kész, a többi itemről beszéljünk valahol

**Comment by MrZero1** [comment]
Kész
