### ISSUE TITLE
Zone PvP hiba

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#329]
Ha egy /zone levédésben allow-on van a PvP flag, és egy player odamegy, a /pvp plugin nem működik, engedélyezi neki a pvp-t, meg lehet ölni.

**Comment by Kayalafur** [comment]
Ez nem hiba, Kényszerített pvp indítás miatt van. Ha be akarod kapcsolni a /zone pvp-t akkor csak töröld a pvp deny flaget, így a /pvp lesz a felsőbrendű a pvp beállításokban. 

Ha pvp zónát akarsz kötelezően létre hozni, akkor hasznos hogy a /zone felüllbírálja a /pvp-t

**Comment by andris155** [comment]
javítva
