### ISSUE TITLE
Slimefun - teszt időszak 

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#3290]
Ki lehet jelenteni hogy vége a teszt időszaknak, nem? :) 
#minemarketre_sf
#warpboltba_sf
#új_sf_addonok_tesztelése

**Comment by poma123** [comment]
új addonok egyébként nem hiszem hogy lesznek, mert így is néha belaggol a dolog.
boltra bekerülnek azok az itemek amiket néztünk, Zero mondta, hogy majd beárazza. :D
minemarketről nem tudok oda mik mehetnének.

**Comment by skrisz0101** [comment]
Minemarketre KB azok mint régen :D
Új addonokra  olyanra gondoltam max ami egyszerű de jó, mint a +kardos/páncélos cuccli. Egyszerű, de mégis jó :D
(persze tesztszerón)

**Comment by andris155** [comment]
A szerver folyamatosan fejlesztés alatt áll. Addon-ból ha van értelmes, ami nem okoz TPS, vagy FPS csökkenést biztosan bekerülnek majd.

**Comment by andris155** [comment]
A tesztelés sosem ér véget. Minden nap egy tesztelés, ha így nézzük, és sokszor jönnek elő új hibák, amik miatt aztán változtatnunk kell a dolgokon. Inkább csak annyit mondanék, hogy terv szerint bent marad a plugin.
