### ISSUE TITLE
Minemarket - V.I.P. Eszközök/páncélzat

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#3291]
Szerintem nem lenne rossz ötlet ha lennének Minemarketen V.I.P. Eszközök és páncélok, úgy, mint az Old cuccok. 
Csak ezek nem X-es enchantúak lennének, hanem pl V-ösek. (ez is gyémánt) És az áruk nem is fele, hanem pl az Old cuccok 75%-a lenne. 

Vagy esetleg olyat hogy 
Az alap az vasszett és azon V-ös enchantok amik fele annyiba kerülnének mint az Old. 
Nemtom mennyire jó/rossz ötlet :/

**Comment by MrZero1** [comment]
Jó ötlet, szerintem illő lenne már új szetteket (plusz hozzávaló eszközöket) is berakni a Minemarketbe.

**Comment by andris155** [comment]
Így is 330 OCD több Old dolog is. Ennél olcsóbban már semmi értelme egy gyengébbnek.
