### ISSUE TITLE
Survival /Energy Regulator

### ISSUE THREAD

**Issue by KriszDj2001** [andris155/TheOld-Crafters#3292]
Sziasztok, egy érdekes dolgot vettem észre, egyik nap lecraftoltam Slimefun-ban az Energy Regulatort, és mikor letettem mellé valamit, akkor eltűnt, de ott maradt, hogy mennyi energia van épp ott. A minap ugyanez megtörtént, de annyi különbséggel, hogy semmit se csináltam, és nem tudom miért történt meg.
![furabug1](https://user-images.githubusercontent.com/57273841/68059310-546e8c80-fcfc-11e9-947e-dbd323f7b223.png)

Még aznap (első eltűnésnél) segítséget kértem elveszített tárgyam ügyében, és 2 Nagyon Rendes ember segítet is, ezúton is szeretném Nekik meghálálni :)
![furabug2](https://user-images.githubusercontent.com/57273841/68059374-95ff3780-fcfc-11e9-9242-0e68024a8357.png)

**Comment by andris155** [comment]
A Slimefun fejlesztőnek már megírtam a hibát. Nem érdekelte és lezárta. Megoldás így nincs.

**Comment by andris155** [comment]
https://github.com/TheBusyBiscuit/Slimefun4/issues/1216

**Comment by skrisz0101** [comment]
Rakj energy capacitort a regulator mellé @KriszDj2001 hátha így jó lesz

**Comment by KriszDj2001** [comment]
Nagyon Szépen Köszönöm a segítségeteket 😀👍

**Comment by andris155** [comment]
Esetleg másold ki az én issue-mat és írd bele a Steps to reproduce the Issue részt. Hátha úgy javítják...

**Comment by poma123** [comment]
van megoldás, le kell írni angolul neki, hogy hogyan lehet reprodukálni...

**Comment by poma123** [comment]
ha nincs leírva, automatikusan bezárhatja és be is zárja.

**Comment by poma123** [comment]
![image](https://user-images.githubusercontent.com/25465545/68076770-4df21a80-fdb9-11e9-8269-97a5e0dc819b.png)
ez így neki azt jelenti hogy invalid jelentés és lezárja

**Comment by andris155** [comment]
Fogalmam sincs hogy kell ezeket reprodukálni csak 100-sával írja a plugin...

**Comment by poma123** [comment]
hát úgy ahogy a kriszdj leírta fent

**Comment by poma123** [comment]
Lehet, hogy javította, nem láttam róla semmi infót. Ha újra előjön kérlek írjon valaki ez alá.

**Comment by poma123** [comment]
Ha megint előjön nyisson új jelentést. Szerintem javítva lett.
