### ISSUE TITLE
SlimeFun /Synthetic Sapphire 

### ISSUE THREAD

**Issue by alidax** [andris155/TheOld-Crafters#3293]
**Szerver**: Survival 

**Verzió**: 1.14.4

a Synthetic Sapphire készítése a Smelteryben nem működik

recept szerint minden berakva 

kar meghúzása után csak az Aluminium Dustot olvasztja Ingot -á

**Comment by poma123** [comment]
Valószínűleg rosszul tetted bele. Le lehet craftolni.
