### ISSUE TITLE
Slimefun - addonok tesztelve

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#3294]
Pomával és kernellel teszteltük az összes sf addont a tesztszerón ami eddig nem volt.
Amik szóba jöhetnek:
- **Chest Terminal** - kicsit bonyi de elég jó cucc. Cargo Továbbfejlesztett változata kB. 
Hibát nem találtunk

- **Hotbarp Pets** - kis mob fejeket lehet craftolni amik különféle effekteket vagy éppen uneffektet adnak ha jobb klikkelsz velük vagy az invedben vannak. Van pár viccesebb is, elég jó szerintem :D
Hibát nem találtunk

- **Ore-chunks** - annyi a lényege hogy geo minerrel ore chunkokat is tudsz szedni az olajon, uránon kívül
(pl cobalt ore) 
Nem találtunk hibát

- **Soul jars** - annyi a lényege, hogy craftolni kell egy jar-t. Ha bent van az invedben és megölsz 128 mobot ugyanabból a fajtából, akkor olyan fajta jar lesz. 
Pl 128 blaze megölésével blaze jar 
A feltöltött jarból lehet broken spawnert craftolni (ezt kapod, ha kiütsz egy spawnert) , amit majd meg lehet javítani 
Nem teszteltük még teljesen. 

Asszem ennyi de lehet van 1-2 amit kihagytam
@poma123 egészítsd ki ha gondolod. 
@UDPSendToFailed valami hozzáfűzés? 

### poma123 kiegészítésésesése:
Ezeken kívül volt még egy olyan, ami színes backpack-eket adott hozzá, semmi újdonság meg fícsör, csak annyi, hogy a játékban lévő összes színben lehet craftolni backpeckeket.

A másik olyan volt, amiben kis fejblokkok szolgáltak tároló ládaként, de azt nem igazán látjuk jónak, mert fps laggot okozna nagy mennyiségben, ha ezeket lepakolják.

Hozzáfűzném még a hotbar pets pár petét érdemes lenne letiltani, mert nem olyan kellemes, ha arra jössz vissza afkból, hogy sárkányköpetbe haltál bele. (jaja, ilyen is van:D)

**Comment by KingDeadZ** [comment]
A chest terminal nagyobb mennyiségben valószínűleg laggot okozna szerintem.

A hotbar pets jó ötlet, és az valószínűleg nem is okozna laggot.

Az ore chunks is jó ötlet, nem hiszem hogy okozna laggot

A soul jars viszont szerintem nem annyira jó, mivel akkor nagyon laggos lenne a szeró a sok mobtól.

**Comment by skrisz0101** [comment]
Soul jars-al broken spawnereket lehet szerezni. Ha ránézel áh-ra, tele van spawnerrel.mindenki tele van spawnerrel DE nem használja @KingDeadZ

**Comment by skrisz0101** [comment]
Chest terminál-t meg egyszerűen lehetetlen nagyobb mennyiségben. Rohadt drága mulatság. Az alkalmazása is csak néha kell. De ha kell, hasznos. @KingDeadZ

**Comment by poma123** [comment]
nem hiszem, hogy laggot okozna a chest terminal. ez az egyik. a másik, hogy a souljars nem egy új fajta spawner vagy más amire gondoltál, önmagában nem lesz ettől több mob vagy kevesebb. egyszerűen sokkal praktikusabb lenne a receptje a broken spawnereknek. az már más kérdés, hogy emiatt több spawnerhez fog-e hozzájutni a nép.

**Comment by skrisz0101** [comment]
@andris155?

**Comment by andris155** [comment]
A Soul jars szerintem túlságosan megkönnyítené a spawner craft-olást. A többi részemről bekerülhet.

**Comment by poma123** [comment]
Akkor majd bekerülnek egyesével, szépen lassan. :D

**Comment by MrZero1** [comment]
A Chest Terminal-t nem szeretném, Kingdead leírta már, egyetértek vele, nagyobb mennyiségben biztosan laggoltat.

**Comment by UDPSendToFailed** [comment]
A Chest Terminal csak egy kiegészítés a sima Cargo-hoz, annyiban más, hogy az 5 blokkos hatókörön kívül lehet vele cuccokat mozgatni a ládák között Channel 17-en, és meg lehet nyitni távolról is. Talán még kevésbé laggoltat, mint 10-20 lerakott Cargo Connector Node, aminek darabja csak 5 blokkra viszi el a tárgyakat.

A Soul Jars pedig Broken Spawner-t csinál, amit utána meg is kell javítani, semmivel sincs előrébb a player ahhoz képest, hogy elmegy a netherbe, és fél óra alatt összeszed 10 blaze spawner-t.

**Comment by skrisz0101** [comment]
Cargora is az lett mondva hogy laggoltat.

**Comment by andris155** [comment]
@skrisz0101 továbbra is laggot okoz, de valamit valamiért. Sajnos nincs jól optimalizálva a plugin.

**Comment by poma123** [comment]
#3300
