### ISSUE TITLE
Világot megváltó javaslat

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#3296]
A konfigos meg a prémi is lila színű. 
Tök zavaró mikor a poma is meg a prémik is írnak és ja. Mi lenne ha az egyik rang színe &d, pink lenne? Szép szín :)

**Comment by poma123** [comment]
mekkora egetrengető problémák vannak itten ni :'('('('(

**Comment by poma123** [comment]
szerintem nem zavaró, most átraktam a nickem szépre. marad lila
