### ISSUE TITLE
SF + bolt

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#3298]
A #3288 jelentésre hivatkozva, ide várom az ötleteket, miket lehessen eladni a boltban (SF cuccok, ofc).

Miből mennyit, mennyiért.

Továbbá, cserekereskedős falusit is szívesen csinálunk, csak mondjátok meg, mit mire lehessen beváltani.

**Comment by MrZero1** [comment]
@UDPSendToFailed @poma123 @skrisz0101 @KingDeadZ

**Comment by UDPSendToFailed** [comment]
A dustok jók lettek volna, de az 512$ / stack senkinek se éri meg. Lehetnének ingotok, uranium félék, coolant cell, carbonado, és a többi hasonló alapanyag, valami normális áron.

**Comment by poma123** [comment]
Hát volt az a kép, azok az árak szerintem jók.

**Comment by MrZero1** [comment]
Sajnos mivel nem tudom mik a 'többi hasonló alapanyag', így nem tudok további dolgokat kirakni, árajánlat (is) hiányában. 
Ami volt a képen, az kint van már a boltban

**Comment by skrisz0101** [comment]
Majd írok könyvben

**Comment by poma123** [comment]
írt könyvben :)
![image](https://user-images.githubusercontent.com/25465545/69899432-2feeea00-1366-11ea-99a6-99e626df1b96.png)

sztem ez off

**Comment by skrisz0101** [comment]
Semmi kedvem sincs árakkal dobálózni
(ami amugy is tizedelve lenne xd)
