### ISSUE TITLE
Flatworld Eventek

### ISSUE THREAD

**Issue by geri5200** [andris155/TheOld-Crafters#330]
Azok az eventek amiknél az oldalánál van lépcső van nagy eséllyel ki lehet bugolni a flatworld be.
Ezek azok amiket találtam
- deathrun
-hallokvíz
-hallospleef
-jegesrafting
-kamikaze
-ragerun
-traprun
-wildrun
+még volt 1 pár event ami le volt zárva és nem tudtam körbe nézni

**Comment by andris155** [comment]
![kepkivagas](https://cloud.githubusercontent.com/assets/8324198/20065579/f6b3c72e-a50e-11e6-89bd-678cb5f615a9.PNG)
