### ISSUE TITLE
Enderchest plugin - Survival

### ISSUE THREAD

**Issue by KriszDj2001** [andris155/TheOld-Crafters#3303]
Sziasztok, a minap felmentem a Survival szerverre, csináltam a dolgaim, és mikor fejleszteni akartam, akkor kellett volna pár dolog, ami az enderchestemben van, de mikor kinyitottam üres volt, nem tudom, hogy mi lehet a baj, rejoinoltam, de nem változott. Ebben szeretném a segítségeteket kérni, hogy mi lehet a baja, és hogy odaveszett-e mindenem vagy nem?
u.i. Megvettem neten az összes ládát, és a duplázót is

Köszönöm Szépen előre is a segítséget,
Szép Napot

**Comment by poma123** [comment]
valamiért nem töltött be, de holnap jó lesz.

**Comment by poma123** [comment]
ma se töltött be @andris155

**Comment by andris155** [comment]
Megnézem holnap majd.

**Comment by poma123** [comment]
sikerült? mert azóta sincs betöltve

**Comment by andris155** [comment]
Reggel nem igazán volt sajnos internet. Így holnapra maradt a javítás.

**Comment by andris155** [comment]
javítva

**Comment by KriszDj2001** [comment]
Köszönöm Szépeen 😄
