### ISSUE TITLE
MineMarket elírás

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#3304]
> prémium MyPet-et jogot

![kép](https://user-images.githubusercontent.com/16057404/68801042-8c11f880-065b-11ea-9738-7f323182468e.png)
![kép](https://user-images.githubusercontent.com/16057404/68801057-9502ca00-065b-11ea-83cf-6727a7e98adb.png)

**Comment by andris155** [comment]
Javítva. Köszi
