### ISSUE TITLE
Slimefun - McMMO hiba

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#3307]
#1427 
@poma123

**Comment by poma123** [comment]
¯\_(ツ)_/¯

**Comment by poma123** [comment]
amúgy egy kis trükkel szerintem megoldható

**Comment by poma123** [comment]
Meg is oldottam, már csak arra várunk hogy el legyen fogadva. :D
[github.com/TheBusyBiscuit/Slimefun4/pull/1244](https://github.com/TheBusyBiscuit/Slimefun4/pull/1244)

**Comment by andris155** [comment]
Elfogadták.

**Comment by poma123** [comment]
![image](https://user-images.githubusercontent.com/25465545/68999981-d815a500-08c8-11ea-96fa-1c3d25748d8e.png)
![image](https://user-images.githubusercontent.com/25465545/68999982-dcda5900-08c8-11ea-9ea0-76429710de07.png)
Holnap betölt! :DD

**Comment by poma123** [comment]
Ezzel egyébként le lehet tiltani most már az összes X-es enchant levételét. Szóval ez tényleg elég hasznos egy kis funkció.

**Comment by poma123** [comment]
Kész, végül ma bekerült
