### ISSUE TITLE
Skin

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#3308]
Mivel hiába jeleztem már többször facebookon, feleslegesen, ezért jelzem itt is. Nem jó a skin. Lehet csak nekem, nem tudom, de nem is érdekel. Hiába van a neten az a skin feltöltve, amit szeretnék látni, csak nem az van a szerveren. :D Skin parancsra meg jogom ugye nincs, miért is lenne.

**Comment by andris155** [comment]
Régebbi skined maradt meg?

**Comment by MrZero1** [comment]
![kép](https://user-images.githubusercontent.com/29709854/68969979-8563bc80-07e6-11ea-9eca-7cd5d0445156.png)
Ez van, ami halloween miatt került be

**Comment by MrZero1** [comment]
Ehelyett lenne a régi/eredeti, a TV-s

**Comment by andris155** [comment]
Most jót tölt be?

**Comment by MrZero1** [comment]
![kép](https://user-images.githubusercontent.com/29709854/69010966-a0a90600-0965-11ea-9434-35f110311139.png)

Most annyira tölt be, hogy én nem látom, de Olivér látja a TV-s skint. Tabon is Alex fej van nekem.

**Comment by andris155** [comment]
És ez gondolom eredeti kliens?

**Comment by MrZero1** [comment]
Igen..

**Comment by andris155** [comment]
Még mindig nem jó?

**Comment by MrZero1** [comment]
Jó már, köszi!
