### ISSUE TITLE
Fly az eventek világban

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#3309]
Olyan helyeken tudnak repülni, ahol eddig nem, vagy nem kéne. Pl eventek lobby. Eddig levolt tiltva egységesen a játékosoknak, csakúgy mint a kreatív. Változott?

**Comment by poma123** [comment]
nem változott, de már írtam a csoportba is hogy meg lesz oldva

**Comment by poma123** [comment]
elvileg Andris letiltotta

**Comment by andris155** [comment]
Hát ha bekapcsolt repüléssel mennek oda, akkor nagyon jó kérdés, hogy tudnak-e repülni.
