### ISSUE TITLE
Kreatív bug

### ISSUE THREAD

**Issue by NBabi** [andris155/TheOld-Crafters#331]
Sínek lerakása kreatívban, majd víz öntése mellé -> a síneket felszedi a víz -> survivalra váltás, és a sín felszedhető. (brtamas jelentette)

**Comment by andris155** [comment]
https://github.com/andris155/TheOld-Crafters/issues/185

**Comment by andris155** [comment]
A hibáról tudunk így sajnos nem tudok jutalmat adni, de azért köszönjük.
