### ISSUE TITLE
Survival - random tp hiba

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#3310]
Ha vadon2 warpon jobbklikkelek a random tp táblára, majd belépek egy minigame-be, kirak a sima survival világba.

![kép](https://user-images.githubusercontent.com/16057404/68976421-070f1680-07f6-11ea-991d-2f962afbb4d3.png)
![kép](https://user-images.githubusercontent.com/16057404/68976445-11311500-07f6-11ea-91a9-5d5774f4f1ab.png)

**Comment by poma123** [comment]
fejlesztőnek majd kellene írni hogy szakítsa meg a countdown-t világváltásnál

**Comment by andris155** [comment]
Csak a /minigame-nél van ilyen probléma?

**Comment by UDPSendToFailed** [comment]
Az összes minigame parancsnál kb, kivéve a mobaréna, onnan nem enged elteleportálni.

**Comment by poma123** [comment]
nincs visszaszámlálás előtte, így nem lehet beírni
