### ISSUE TITLE
Sign/tábla duplikáció

### ISSUE THREAD

**Issue by pixelthec** [andris155/TheOld-Crafters#3311]
**Szerver**: Survival

**Verzió**: 1.14.4
Táblára /gmc-ben unicode karaktert írva a plugin ledobja a táblát, ami /gms-ben felvehető így duplikálva a kreatívban lerakott táblát. 
![2019-11-17_14 43 32](https://user-images.githubusercontent.com/57867069/69008991-b825c600-0948-11ea-9c11-3de5cc11636d.png)
![2019-11-17_14 43 36](https://user-images.githubusercontent.com/57867069/69008992-b825c600-0948-11ea-8adc-c4498cd9bfb8.png)
![2019-11-17_14 43 49](https://user-images.githubusercontent.com/57867069/69008993-b8be5c80-0948-11ea-89e1-235853cc5482.png)

**Comment by UDPSendToFailed** [comment]
#2649 #2364 #2316 #1418 #1186

**Comment by poma123** [comment]
Tudunk róla, de nem igazán sikerült javítani, és nem is prioritás. Ugyanúgy tiltott addolni.

**Comment by andris155** [comment]
Le lehetne tiltani, csak akkor elnyeli a túlélős táblát. Az meg nem biztos, hogy túl korrekt.

**Comment by MrZero1** [comment]
Esetleg a táblán nem lehet engedélyezni külön az unicode karaktereket?

**Comment by andris155** [comment]
Engedélyezni lehet, viszont akkor oda tudnak írni tiltott szavakat is unicode karakterekkel.
