### ISSUE TITLE
FAWE + Voxel kérdés

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#3312]
Mik a lehetőségek ezekkel kapcsolatban? Nagy szükség lenne az építészeknek rá, teddmelk addig bele sem tud kezdeni az új projektekbe.

**Comment by poma123** [comment]
Semmi, mivel még kb el se kezdték 1.14-re a fejlesztést. Én többek között ezért örültem volna, ha maradt volna 1.13 az építész

**Comment by andris155** [comment]
Az egy dolog, hogy nem frissült 1.14-re. Viszont valószínűleg 1.15-re sem fog és az utána lévő verziókra sem. Szerintem 2+ verzió különbség nem valami jó építészeti szempontból hiába a gyors WorldEdit, az új blokkokat nem tudnák elérni.

**Comment by andris155** [comment]
1.14-re egyébként elkezdték a fejlesztést, de tele van hibával. Volt tesztelve is.

**Comment by poma123** [comment]
Már megtaláltam, csak szarul van megcsinálva a jenkins ezen része. A verziókülönbség tök mindegy, mivel úgyse használják az új blokkokat. Ha meg igen, akkor örüljenek, hogy van fawe. De ez a gondolatmenet mind semmit nem ér, mivel nincs.

**Comment by andris155** [comment]
Ezt berakjam esetleg?
https://www.spigotmc.org/resources/asyncworldedit.327/

**Comment by poma123** [comment]
volt már bent régebben, de ez nagyon rossz szerintem

**Comment by poma123** [comment]
Bekerült építészre a FAWE!
