### ISSUE TITLE
Slimefun pet

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#3313]
A creeper SF pet sebez másokat is
![kép](https://user-images.githubusercontent.com/29709854/69352272-ee32b500-0c7c-11ea-9f97-a422635f9dbe.png)

**Comment by MrZero1** [comment]
A Ghast pet is

**Comment by poma123** [comment]
le lesz tiltva

**Comment by poma123** [comment]
Holnap betölt

**Comment by andris155** [comment]
Majd nézz rá a sok hibára is, amit ír. Jelenthetnéd a fejlesztőnek. Neked legalább javítja.
