### ISSUE TITLE
Weboldal javaslat

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#3314]
Nem tudom, mennyire van lehetőség, de a weboldalra egy Fogalomtár részt jó lenne kialakítani. Ide mehetne mindenféle dolog a szerverekkel kapcsolatban. Pl. eventrendszer, OCD, minemarket, AFK, mint fogalom. Plusz más, kapcsolódó tartalom. 

A tartalmi elemeket adminokkal megcsinálnánk.

**Comment by andris155** [comment]
Van rá lehetőség.

**Comment by MrZero1** [comment]
A fogalmakat már elküldtem privátban. 

A másik javaslatom a meglévő szerverek bemutatása, aminek lehetne egy főmenüpontja. Pár kép, a szerver rövid leírása, mi található a szerveren, ilyesmi.

+ A vanilla additions az Egyéb részből kikerülhet.(?)

**Comment by andris155** [comment]
Amit elküldtél az bekerült. Köszönjük. A szerverek bemutatásához is lehet külön oldal. Csak majd kell ahhoz is külön szöveget írni.

**Comment by andris155** [comment]
A vanilla additions-t pedig kivettem az oldalról.
