### ISSUE TITLE
Pet elengedés levédésen.

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#3317]
Bármilyen állatot elengedek (petből) levédésen bellül, eltűnik. Többször is engedélyeztem a spawnt.

**Comment by andris155** [comment]
Megtudod adni a koordinátákat és a világ nevét?

**Comment by skrisz0101** [comment]
Nem láttam hogy írtál :/ ha fent leszek írok kordit. Világ:1.14

**Comment by skrisz0101** [comment]
5609 80 6734 1.14es vadon

**Comment by poma123** [comment]
@andris155

**Comment by andris155** [comment]
<img width="478" alt="Annotation 2019-12-01 140042" src="https://user-images.githubusercontent.com/8324198/69914302-ffc94900-1442-11ea-91f2-f8ce04f330fe.png">
Mivel a mob spawn-t letiltottad így elengedésnél kitörli az entitást.
