### ISSUE TITLE
Hg-n ládába több cucc 

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#3318]
Több fajta cucc is lehetne a ládában, pl számszeríj, pajzs, stb. Régebben volt róla szó nem tudom mi lett az ötlettel, ezért újra felhozom. 
@MrZero1 @poma123

**Comment by MrZero1** [comment]
@andris155  ha elküldi a konfigot, akkor beleírom azokat, meg még más dolgokat. Feltéve ha lehet módosítani.

**Comment by andris155** [comment]
elküldtem

**Comment by MrZero1** [comment]
Mi kerüljön be? @skrisz0101 DC-n vagy Facebookon írd már majd le az ötleteidet. Köszi
