### ISSUE TITLE
Véletlenszerűen felrobbanó Nuclear Reactor-ok

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#3319]
Tegnap Saii1-nek segítettem pár Cargo-t beállítani, mikor teszteltük volna, az Energy Regulator már nem volt a helyén, csak a hologram-os kiírása. Miután visszaraktuk, felrobbant a reaktor úgy, hogy biztosan volt benne elegendő Coolant Cell.

Ma ki akartam volna pakolni a saját reaktoromból a Neptunium-ot, access portból kiszedtem, így már volt nálam egy stack, mikor jobbklikkeltem a reaktorra, az oldalára rakta a blokkot az invemből, és az is felrobbant.

**Comment by andris155** [comment]
Ki kellene találni, hogy mi az amitől pontosan felrobban minden esetben. Pontos reprodukálási lépések nélkül nem hajlandó foglalkozni a Slimefun fejlesztő semmivel. Esetleg saját szerveren is tesztelheted. Paper 1.14.4 a szerver és a legújabb dev. CS-CoreLib és Slimefun fut rajta.
