### ISSUE TITLE
Tintahal spawner

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#3320]
Szurvi.: se vízben, se földön, se levédésen se azon kívül nem spawnol semmit se

**Comment by andris155** [comment]
Elvileg Y46 szint és tengerszint között spawnol csak. Próbáltad így?

**Comment by andris155** [comment]
![2019-11-27_11 39 25](https://user-images.githubusercontent.com/8324198/69716717-e5256600-110a-11ea-8465-6ea5dc5bcc2c.png)
Nekem így működött.

**Comment by skrisz0101** [comment]
Ohh köszönöm.
