### ISSUE TITLE
Láva lerakás engedélyezése Prémium / Old rangtól

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#3321]
Elég hasznos tud lenni néha, így nem kéne folyamatosan zaklatni vele az adminokat, ha pl. valaki több féle farmot is ki akar próbálni, vagy meggondolja magát, és máshová építené, esetleg vízzel véletlenül eltünteti, stb. Aki megveszi a rangot, nem hiszem, hogy kockáztatná az elvesztését csak azért, hogy trollkodjon a lávával, és vízzel is ugyanúgy lehet rondítani a tájat annyi különbséggel, hogy az nem sebez. Elvileg essentials-ban a jog is megoldható.

**Comment by andris155** [comment]
Ilyen nem lesz.

**Comment by UDPSendToFailed** [comment]
Nekem az is jó, ha napi 5x oda kell hívnom egy admint, csak az ő munkájukat tenné ez egyszerűbbé. A trollkodáson kívül, amit szerintem egy Old nem csinálna, ha már megvette a rangot 5000 OCD-ért, nem látok rá okot, hogy tiltva legyen.
