### ISSUE TITLE
GriefPrevention - más levédésén ki lehet ugrálni a veteményt

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#3322]
https://gfycat.com/weeperiodicgalapagospenguin

**Comment by andris155** [comment]
Most is ki lehet?

**Comment by UDPSendToFailed** [comment]
Igen.

**Comment by andris155** [comment]
Nem sikerült reprodukálni.

**Comment by UDPSendToFailed** [comment]
Nálam még mindig működik, több levédésen is próbáltam: https://gfycat.com/adoredunpleasantafghanhound
