### ISSUE TITLE
Egyéni(?) probléma az Old Village szerveren

### ISSUE THREAD

**Issue by Edphedrine** [andris155/TheOld-Crafters#3323]
**Szerver**: Old Village

**Verzió**: ForgeOptiFine 1.14.4

Egyéni problémám van az Old Village szerveren, ugyanis nem találtam olyan hibajelentést ami erről szólna.
Valamiért, adott chunk-ok nem töltődnek be a spawn-on, nem tudok nyomólapokat és gombokat használni. (a parancssal való warpolás működik). Próbáltam újratölteni a chunkokat, állítani a render distance-t, teljesen újratelepítettem a játékot, frissítettem a javát is, viszont nem oldódik meg a gond. De! Van egy gyanúm, hogy talán mi lehet ennek az oka. Egészen pontosan az után kezdtek ilyen problémák fellépni, miután használtam a "tömegközlekedés" dolgot, amiből nem tudtam kisználni, (a CTRL gombbal) majd egy betöltetlen chunkba vitt engem magával (a minecart), majd elkezdtek a játék textúrái random villogni, keveredni. Próbáltam megoldani ezt a "/spawn" paranccsal, úgy tűnt hogy sikerült is a teleportálás, viszont a villogás megmaradt, ezért lecsatlakoztam a szerverről. Következő csatlakozásnál pedig a fentebb felsorolt hibák fogadtak engem. _Nem lehet hogy talán még mindig azt gondolja a szerver/játék/plugin hogy abban a csillében ülök, ezért nem tudok nyomólapokat/gombokat használni?_
Illetve amikor felcsatlakoztam megkért valamilyen textúrák letöltésére, viszont nem tűnt úgy hogy letöltötte vagy betöltötte volna őket.

Csak egy modot használok, Xaero minimapját, viszont anélkül is ugyanez a helyzet.
Kíváncsi lennék hogy eddig csak én találkoztam-e ezzel.

**A továbbiakban még kipróbálok dolgokat, mint például másik klienssel, karakterrel felcsatlakozni, frissítem ezt amint megbizonyosodok arról, hogy működik-e vagy sem valamelyik opció.**

_illetve egy képernyőmentés, a parkour pálya első néhány blokkja töltődik csak be, hiába ugrálok oda, nem triggereli azt hogy betöltődjön a chunk. +az az emlékeztető, hogy barkácsoljak deszkát, még mindig ott van, de ezt kliens-oldali hülyeségnek tudom be._

![2019-11-29_08 48 21](https://user-images.githubusercontent.com/43260496/69854773-3314a800-128a-11ea-961d-ef4e9ffb17aa.png)

szerkesztés:
• **Új karakterrel minden flottul működik, úgy ahogyan kell neki, szóval kiderült hogy magával a karakterrel van gond,** hogyan lehetne ezt orvosolni? _(lásd lentebb a parkour pályát teljes pompájában)_
• Illetve azt elfelejtettem hozzátenni, hogy TLauncher-t használok.
• A karakter neve amit a teszthez használtam: "Edphedrina" ,ne bannold, hátha máskor is kell valaminek, de nyugodtan unreg-elheted, amíg nincs valami gond addig úgysem kell. _(ne zavarjon össze, "e" helyett "a" van a név végén)_
• Másik klienssel nem próbálom meg, úgyis megvan a fő gond.

![2019-11-29_09 40 00](https://user-images.githubusercontent.com/43260496/69856306-a370f880-128d-11ea-9867-4b471a7e41d9.png)

**Comment by poma123** [comment]
kész
