### ISSUE TITLE
[OldVillage] Nem működő vadon kapu és random tp

### ISSUE THREAD

**Issue by Edphedrine** [andris155/TheOld-Crafters#3325]
**Szerver**: OldVillage

**Verzió**: ForgeOptiFine 1.14.4

Elértem a 4. szintet az OldVillage szerveren  és amikor ki akartam menni a vadonba nem működött a teleport ,"No suitable locations found." hibaüzenet jelent meg. Ugyan ez a helyzet a loot világ random tp táblájával is. Amennyiben azért nem működik, mert elsiklottam valami felett (ami szokásom) akkor verjetek meg.

_(azért a gif formátum, mert a lassú internetem miatt sokáig tartott volna feltölteni, illetve azért link-ként, mert ahhoz pedig túl nagy a fájl hogy ide feltöltsem)_
• https://i.imgur.com/AU5v0F7.gif
• https://i.imgur.com/Lm95tS7.gif

**Comment by poma123** [comment]
köszi!

@andris155, légyszi ne frissítsd ov-n se a wildtp-t se a nocheatplust, valamiért letiltja az újabb verziói a random tpzést 1.13-on

**Comment by andris155** [comment]
A Nocheatplus volt, mivel kompatibilis 1.13-al is. A Wildtp nem volt.
