### ISSUE TITLE
Javaslat a Minemarkethoz

### ISSUE THREAD

**Issue by Icecroft** [andris155/TheOld-Crafters#3328]
Lehessen esetleg vásárolni olyan Old sisakot is, amelyen még extrában nightvision van.
Az árát 750 OCD-re tartom optimálisnak. 
Survivalre és savszigetre is felkerülhetne.

**Comment by andris155** [comment]
X felé nem szeretnék menni. Az X is már nagyon magas fejlesztés. Ennél nagyobb szinteken a már a számok sincsenek normálisan megcsinálva.

**Comment by skrisz0101** [comment]
@andris155 nem azt kérte hogy X-nél nagyobb legyen az enchant rajta, hanem hogy adjon éjjellátás effektet mint pl egy slimefunos sisak

**Comment by andris155** [comment]
Egyáltalán működnek a nagyobb szintűek? Meg tényleg jobban látni vele?
