### ISSUE TITLE
Survival - eltűnnek a teknősök

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#3332]
Nem halnak meg, nem sebződnek, egyszerűen csak eltűnnek.

https://gfycat.com/clearcutgreenchameleon
https://gfycat.com/darkthunderousbarasingha

**Comment by andris155** [comment]
Mivel túl mennek a limiten. Ennél több teknős miért kellene bárkinek?

**Comment by UDPSendToFailed** [comment]
Tojás / pikkely farmot akartam építeni, ha túl sok lesz, legyilkoltam volna a felesleget, de így kb lehetetlen szaporítani őket.

**Comment by andris155** [comment]
Növeltem a limitet.
