### ISSUE TITLE
Nem üt blokkot a miner android

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#3334]
Ja

**Comment by andris155** [comment]
Mikor próbáltad pontosan?

**Comment by skrisz0101** [comment]
KB 3-4 órája

**Comment by andris155** [comment]
Pontos idő kellene. Óra:perc.

**Comment by skrisz0101** [comment]
Ha elindul ez a fos akkor tudok küldeni

**Comment by skrisz0101** [comment]
Tegnap 16:11:20-kor

**Comment by andris155** [comment]
Próbáld meg felszedni és újra lerakni. Gondolom elveszett a gagyi mentési rendszer miatt...

**Comment by andris155** [comment]
Már más jelentett ezzel kapcsolatban hibát: https://github.com/TheBusyBiscuit/Slimefun4/issues/1304
