### ISSUE TITLE
Eszközkeret telkeken

### ISSUE THREAD

**Issue by maryhonaly** [andris155/TheOld-Crafters#3337]
Survival szerver, telekvilág:

Az eszközkeret lerakási lehetősége egyik percről a másikra megszűnt. Mindenkinek ugyan ezt csinálja. Vadonban megy rendesen.

https://youtu.be/XGDJSj7TxNU

**Comment by maryhonaly** [comment]
Most szóltak, hogy az enderchestek sem nyithatóak.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by andris155** [comment]
most jó?

**Comment by andris155** [comment]
Elvileg mindkettő javítva.

**Comment by andris155** [comment]
508 OCD
