### ISSUE TITLE
Nem funkcionál a Smelter's Pickaxe

### ISSUE THREAD

**Issue by maryhonaly** [andris155/TheOld-Crafters#3338]
Survival, SlimeFun

A címben említett csákánnyal ütni lehet, viszont a kiégetési funkciója nincs meg neki.

**Comment by andris155** [comment]
Azóta sem jó?

**Comment by maryhonaly** [comment]
Vas és arany blockon teszteltem, működött. Követ nem süti ki, ha nem is kellene, akkor rendben van.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by skrisz0101** [comment]
Szerintem csak az érceket kell kisütnie :D
