### ISSUE TITLE
Eltünő mobok

### ISSUE THREAD

**Issue by ZachWithAScythe** [andris155/TheOld-Crafters#3339]
**Szerver**: Survival

**Verzió**: 1.14.4
Az elneveztett mobok folyamat eltünnek ma(2019.12.20) is panaszkodtak rá de én is már észrevettem

**Comment by andris155** [comment]
Milyen mobok és melyik világ?

**Comment by andris155** [comment]
Illetve mennyi van belőle?

**Comment by ZachWithAScythe** [comment]
Volt olyan hogy 4 darab (zombi)(és legalább 5-6 szor végig próbálam vasfarmhoz hogy nem én hibáztam-e el) volt belőle de ez csak nálam másoknál más mennyiségek voltak. A világ az az én esetemben vadon2 volt másoknál telekvilág (halak tüntek el)

**Comment by andris155** [comment]
Limit mindegyikre van, de nyilván nem 5-6. Vannak dolgok, amiket egyben számol a rendszer pl.: spawner-es élőlények, és állatok. Lehet ezek is befolyásolják ezt. Bár ez a limites plugin meg elvileg nem töröl elnevezett élőlényeket. Szóval én sem teljesen tudom mitől lehet így ez.
