### ISSUE TITLE
Lobby KitPvP kapu nem működik

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#334]
Lobby-ban a KitPvP kapu nem működik, nem csatlakozik a szerverre, és a kiírás is SkyPvP még.

![2016-11-09_14 23 33](https://cloud.githubusercontent.com/assets/16057404/20139825/5dd53044-a688-11e6-828b-42842eb7b674.png)

**Comment by andris155** [comment]
A portál javítva.

**Comment by andris155** [comment]
javítva
