### ISSUE TITLE
Survival mypet hiba: releaselhetetlen petek

### ISSUE THREAD

**Issue by Icecroft** [andris155/TheOld-Crafters#3340]
Eddig van 2 falusi petem is, amelyeket nem tudok a /petrelease <név> paranccsal elengendi. Skrisszel kipróbáltunk mindent, de nem megy.

**Comment by andris155** [comment]
Holnap próbáld majd meg újra.

**Comment by Icecroft** [comment]
Szia Andris, bocs de a petrelease még mindig nem megy. már 5 falusi van letárolva, amit nem tudok elengedni.

**Comment by andris155** [comment]
Mit ír ki?

**Comment by Icecroft** [comment]
Semmilyen üzenet nincs, a falusi a release parancs hatására "rándul egyet", de ugyanúgy pet marad.

**Comment by andris155** [comment]
Az 1.15.1-es verzióval sem jó?

**Comment by andris155** [comment]
Ha azóta sem volt jó, akkor holnap már jónak kell lennie.

**Comment by Icecroft** [comment]
Szia Andris! Ma ismét teszteltem a az elengedhetetlen falusi peteket, de sajnos továbbra sem javult a helyzet. A tünetek ugyanazok, mint korábban leírtam.

**Comment by andris155** [comment]
Törölhetem ha kell valamelyiket tőled.

**Comment by andris155** [comment]
Sajnos úgy tűnik nem fogja megoldani ezt a fejlesztő. Talán valamikor a jövőben. Ha valakinek kell egy petet törölni, akkor szóljon.
