### ISSUE TITLE
Savsziget:napi event:traplabirintus

### ISSUE THREAD

**Issue by KulGery** [andris155/TheOld-Crafters#3341]
**Szerver**: Savsziget

**Verzió**: 1.14.4
A napi eventek között a traplabirintus véleményem szerint nem megoldható. A -3485,5,-1484 koordinátán lehetne csak tovább jutni, viszont az itteni érzékelő visszadob a starthoz, a labirintus magassága miatt meg lehetetlen átugrani...

Én más helyet nem találtam ahol tovább tudnék jutni.

Persze elfér a 7 event között egy lehetetlen event.

**Comment by MrZero1** [comment]
Javítva. Köszi!
