### ISSUE TITLE
Tab-on nem látszanak a rangok

### ISSUE THREAD

**Issue by KulGery** [andris155/TheOld-Crafters#3342]
**Szerver**: Savsziget

**Verzió**: 1.14.4

A tab által megjelenített listán már nem látszanak a rangok.

**Comment by KulGery** [comment]
Lehet, ezzel összefügg, de a sav sem zöld:
![2019-12-21_10 18 21](https://user-images.githubusercontent.com/25465311/71305994-6bb42700-23db-11ea-893d-9fdb891e41e1.png)

**Comment by andris155** [comment]
javítva

**Comment by andris155** [comment]
Sajnos a vízalatti részt én nem tudtam színezni.

**Comment by KulGery** [comment]
Bocsi, akkor az sztornó... ;-)
Úgy emlékeztem, az is zöld...
