### ISSUE TITLE
VIP sziget barkácsasztal

### ISSUE THREAD

**Issue by KulGery** [andris155/TheOld-Crafters#3344]
**Szerver**: Savsziget

A VIP szigeten jó lenne, ha lenne barkácsasztal. Van hogy csak az alapokat viszem, és ott jut eszembe, hogy ebből még csinálni kellett volna valamit, illetve van, hogy az eredményt kell formázni, pl blokkba szedni, hogy mást is tudjak csinálni...

Persze ha a cél az, hogy a kereskedő szegeten csak kereskedés legyen, azt is értem.

**Comment by MrZero1** [comment]
Raktam le
