### ISSUE TITLE
Picike VoteGUI fordítás/konfig bugocska

### ISSUE THREAD

**Issue by Moenish** [andris155/TheOld-Crafters#3345]
![Névtelen](https://user-images.githubusercontent.com/14863100/71345194-54a53e80-256d-11ea-85e5-e227d97fb4e4.png)

**Comment by andris155** [comment]
Érdekes egy hiba. Mit kellene annak az órának írnia?

**Comment by Moenish** [comment]
Előző. Ez a neve, de hogy mire utal, az jó kérdés. A mellette levő iránytű azt mutatja mennyit kell még várni, hogy újra szavazhasson valaki és Következő néven van.

**Comment by skrisz0101** [comment]
Asszem azt h mikor szaclvaztál utoljára
De nem biztos

**Comment by Moenish** [comment]
Valami ilyesmi kellene legyen szerintem is.

**Comment by andris155** [comment]
javítva
