### ISSUE TITLE
Elírás

### ISSUE THREAD

**Issue by mnbTOC** [andris155/TheOld-Crafters#3346]
Hello. Survival szerveren az adventi kalendárban találtam egy cuki elírást :) 
![image](https://user-images.githubusercontent.com/32791069/71364410-681bce00-259c-11ea-9ac6-67fbe4f2e51e.png)

**Comment by MrZero1** [comment]
Szia. Köszi a jelzést, de a mai napig volt a kalendárium, holnaptól már nincs. Kellemes ünnepeket!
