### ISSUE TITLE
Javaslat Slimefun-hoz

### ISSUE THREAD

**Issue by mnbTOC** [andris155/TheOld-Crafters#3347]
Survival szerverre javasolnám hogy a slimefun-hoz bekerüljön az exotic garden addon-t. Szerintem nem egy játékos ürölne neki hogyha újra csinálhatna érc bokrokból kertet. 
https://github.com/TheBusyBiscuit/ExoticGarden

**Comment by andris155** [comment]
Nem fog bekerülni. A rengeteg fej nagyon nagy FPS lagot okoz. Illetve a szerver sem igazán bírja egy idő után mikor már annyi fej van.
