### ISSUE TITLE
Savsziget Küldetés nem enged továbblépni.

### ISSUE THREAD

**Issue by KulGery** [andris155/TheOld-Crafters#3349]
**Szerver**: Savsziget

**Verzió**: 1.14.4

A Szakértő küldetés azt mondja, csak 1-t hagyhatok ki, illetve hogy 11 teljesítettem a 12-ből. Mégsem enged tovább.

![2019-12-25_11 53 03](https://user-images.githubusercontent.com/25465311/71443847-a08ee980-270d-11ea-8700-cf846d90ee16.png)

**Comment by andris155** [comment]
Hol írja, hogy lehet kihagyni?

**Comment by andris155** [comment]
Mert igazából a Szakértő teljes elkészítése a következő szint, és a szakértő szint feloldásánál lehetett kihagyni egyet. De tényleg kicsit furán lett megoldva. A Haladó szint feloldásához nem lehet kihagyni egy küldetést sem.
