### ISSUE TITLE
Hazudás

### ISSUE THREAD

**Issue by Balint2** [andris155/TheOld-Crafters#335]
A ping-gel lehet más nevében káromkodni, azt még csak én látom, de ha beküldi az illető. ![nagy csalas](https://cloud.githubusercontent.com/assets/17943949/20151740/95785d18-a6bb-11e6-8490-c65d5052cd62.png)

**Comment by Balint2** [comment]
am erre olyan megoldást javasolnék, hogy a ping parancsban letiltani a rangneveket, ha lehetséges.

**Comment by andris155** [comment]
Minden lehetséges. :D

**Comment by andris155** [comment]
javítva
