### ISSUE TITLE
Ideiglenesen eltűnő petek

### ISSUE THREAD

**Issue by maryhonaly** [andris155/TheOld-Crafters#3350]
Survival: a régóta meglévő petek, darabszámtól függetlenül, néha eltűnnek. Néhány óra múlva/másnap visszatérnek. 

Ha ezen idő alatt befogsz egyet, az előzőek visszatérésével végleg elveszik.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by andris155** [comment]
Kérlek nyiss új hibajelentést, ha 1.15.1-ben is él ez a hiba.
