### ISSUE TITLE
Explosive Shovel

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#3351]
1.15
Alapbol a működése: 3x3mas helyen áshatsz vele 
Egy robbanás effekt közben. 

Most: 1 blokkot ás ki, de közben ugyanúgy van robbanás effekt

**Comment by andris155** [comment]
Dísznek megírom a fejlesztőnek, de úgyis lezárja :D

**Comment by andris155** [comment]
Erre se lesz gondolom soha megoldás...

**Comment by andris155** [comment]
Majd az újabb Slimefun plugin megoldja max.

**Comment by andris155** [comment]
Majd valamikor a jövőben talán működni fog. Ha nem, akkor nem tudok mit tenni.
