### ISSUE TITLE
1.15-ös update

### ISSUE THREAD

**Issue by KulGery** [andris155/TheOld-Crafters#3352]
**Szerver**: savsziget

**Verzió**: 1.15.1
Az obsidián csákány színe vas
![2019-12-26_20 22 10](https://user-images.githubusercontent.com/25465311/71487763-6a408f80-281d-11ea-84d2-db627932792b.png)

Gondolom a textura kompatibilitás miatt...

**Comment by KulGery** [comment]
Régebbi verzióval nem enged fellépni. Ez azt jelenti, hogy a savszigeten is lehetnek méhek?

**Comment by MrZero1** [comment]
1.15-től a Vanilla additions tárgyak (mint az obszidián eszközök) nem lesznek elérhetőek, ezért látod vasnak.

**Comment by andris155** [comment]
Teljesen 1.15.1-es minden szerver. Az egyedi eszközök törlésre kerültek, mivel már nem fejlesztik ezt a bővítményt.
