### ISSUE TITLE
Ancient Pedestal

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#3354]
**Szerver**: 

1.15.1

Alapból, ha jobb klikkelsz bármiféle tárggyal egy ancient pedestalra (adagoló item) 
Akkor felette fog lebegni. 
(ezzel craftolni lehet) 

Most: megnyitja az adagolót ancient pedestal néven, normál adagolóként szolgál.

**Comment by andris155** [comment]
Azóta sem jó?

**Comment by skrisz0101** [comment]
Javítva
