### ISSUE TITLE
Vanilla add. tárgyak

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#3356]
Törhetetlen eszközök lettek a vanilla additions tárgyak. 

![kép](https://user-images.githubusercontent.com/29709854/71513856-6dc72b80-289c-11ea-91f5-fc39516763b2.png)

Jó sok földet kiástam, de semmi. Volt rajta törhetetlenség 3 enchant, levettem, de ugyanúgy semmi.

**Comment by andris155** [comment]
És mit csináljak? Nem tudom mindenkitől törölni ezeket.

**Comment by MrZero1** [comment]
Valamit akkor is kell kezdeni ezzel

**Comment by andris155** [comment]
Jelenleg azt sem értem mitől ilyenek ezek. Jó lenne, ha valaki tudna egy ilyet adni.

**Comment by poma123** [comment]
Automatikusan törli az unbreaking-et róla.
