### ISSUE TITLE
Savsziget - 1.15.1

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#3359]
Savsziget:

- [x] Shop frissítése 1.15 itemekkel

- [x] Új küldetések (méh tojás szerzés miatt)

- [x] Savsziget eventek - OCD-s jutalom újragondolása. (a TOP1 kapna OCD-t??)

- [x] Essentials-os javítás parancs az additions repair helyett.

**Comment by andris155** [comment]
Az új küldetés helyett bekerült tudtommal egy küldetésbe jutalomként már.

**Comment by MrZero1** [comment]
Igen, plusz a napiládákban is van.

**Comment by andris155** [comment]
Milyen tárgyak kellenének a shop-ba, és mennyiért? Illetve melyik kategóriába?

**Comment by krokii3** [comment]
Sav szigeten a dugattyúk képesek a sziget határon túlra tolni a Blokkokat.
