### ISSUE TITLE
End, nem lehet levédeni

### ISSUE THREAD

**Issue by maryhonaly** [andris155/TheOld-Crafters#3360]
Világ: world2_the_end

Egy játékos az iménti világban épített, és valahogy még le is védte, viszont az építés lehetséges volt mindenkinek. 

A feloldást követően: “Ebben a világban a levédés tiltva van.”

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by maryhonaly** [comment]
A meglévő levédéseket az aranykard nem jelzi, bárki bele tud nyúlni, rombolni!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by andris155** [comment]
javítva
