### ISSUE TITLE
Telek probléma

### ISSUE THREAD

**Issue by AFekexd** [andris155/TheOld-Crafters#3361]
A telek megosztással van gond. Ha valaki hozzáad egy másik személyt/személyeket a telkéhez. Akkor ha tulaj lelép van rá esély, hogy a hozzáadott személyt kitiltsa a telekről vagy hiába van hozzá adva, nem tud hozzáférni semmihez, építeni stb. 
 
**Survival**: 

**1.15.1**: 
![Képernyőfotó 2019-12-28 - 16 32 13](https://user-images.githubusercontent.com/59290179/71545803-a562d000-298f-11ea-9129-85ca1590d3cf.png)

**Comment by skrisz0101** [comment]
P trust, nem p add

**Comment by andris155** [comment]
Megbízottnak kell hozzáadni. Nem tagnak.
