### ISSUE TITLE
Playertime és playerweather flag

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#3362]
**Szerver**: szurvi

**Verzió**:  1.15.1

Ha levédésen beállítom a playertime, vagy playerweather flaget, néha működik néha nem. Néha jó egy darabig, elmegyek onnan majd vissza, és megint nem jó

**Comment by andris155** [comment]
Kellene az, hogy pontosan mikor nem működik.

**Comment by andris155** [comment]
Kellenének a pontos reprodukálási lépések, amikor nem működik.

**Comment by skrisz0101** [comment]
Lépések:
1.: /serclaimflag playertime soon. 
2.: nem történik semmi

**Comment by skrisz0101** [comment]
Ja, egyáltalán nem megy

**Comment by andris155** [comment]
El kell menni a területről, majd vissza és akkor működik.
