### ISSUE TITLE
Pwarp és /back

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#3363]
**Szerver**:  mindenhol ahol van pwarp és back

**Verzió**:  1.15.1

Lehet ez is olyan hiba ami köztudott, és senki se jelentette. 
Ha valahova Pwarpolunk, majd onnan backelünk, akkor nem oda dob vissza, ahonnan Pwarpolunk, hanem egy teleporttal előrébb. 
(remélem érthetően írtam 😕) 

Ugyanez a helyzet a telekre tpzéssel is. 
(/p h)

**Comment by andris155** [comment]
Csak az EssentialsX plugin parancsait támogatja a /back
