### ISSUE TITLE
Elbugolt SF-es dolgok

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#3364]
Eltűnt a játékos területéről, a helyére nem tudunk lerakni semmit. WE-vel raktam a levegő helyére üveget (és követ), kiütöttem majd megkaptam ami ott volt. Ezt megismételtem többször, folyton megkaptam, ami ott volt, viszont a helyére azóta se tudunk semmit lerakni kézzel.
(Ami ott volt: 2 lava generator, 2 energy regulator)

![kép](https://user-images.githubusercontent.com/29709854/71560808-a4ed3680-2a6e-11ea-99cf-cb8014a8de0d.png)

**Comment by MrZero1** [comment]
![kép](https://user-images.githubusercontent.com/29709854/71560839-f39ad080-2a6e-11ea-951a-9277f6a9c5ac.png)

**Comment by MrZero1** [comment]
Update: A játékos elmondta (brycon), hogy 1-1 darab volt, csak megduplázódtak.

**Comment by MrZero1** [comment]
gabooo területén is van egy ilyen blokknyi hely

**Comment by poma123** [comment]
most nem rakódtak vissza? bár lehet nincs köze a javításhoz

**Comment by MrZero1** [comment]
Gabooo-nál ugyanúgy bugos, nem lehet lerakni és nincs ott semmi. A másik játékosnál nem tudom, de gondolom ott is

**Comment by andris155** [comment]
Gondolom van ott egy láthatatlan armor stand, azt kell törölni paranccsal.

**Comment by maryhonaly** [comment]
Sikerült kivakarni onnan a beragadt sf itemeket.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by MrZero1** [comment]
Nem volt láthatatlan páncélállvány, megnéztem. Ahogy leírtam, WE-vel bohóckodtam sokáig, 1 blokkot sikerült így 'törölni', de a többi helyen már nem. Elbugolt fej volt ott, aminek a helyére raktam WE-vel üveget, akkor visszakaptuk azt a fejet, ami ott volt, de továbbra is bugos volt.

**Comment by andris155** [comment]
De akkor már megoldódott?

**Comment by maryhonaly** [comment]
A probléma él, rendre jönnek létre ugyan ilyen kiüthetetlen valamik.
Viszont sikerült egy kicsit sem elegáns megoldást találnom arra, hogy eltávolítsam onnan őket. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by andris155** [comment]
Sajnos a Slimefun mentési rendszere hibás így folyamatosan vesznek el a letett dolgok. Talán majd a Slimefun egy újabb verziója oldja ezt meg.
