### ISSUE TITLE
Automatikus eventek

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#3365]
![kép](https://user-images.githubusercontent.com/29709854/71561129-c05a4080-2a72-11ea-8bc6-64a23d6231a7.png)

Nem igen megy a hirdetés, vagy nem tudom, de nem működik rendesen a vége.

**Comment by MrZero1** [comment]
+ megvan a 3 nyertes, de nem ér véget az event. Scoreboard sincs

**Comment by poma123** [comment]
Valaki nem frissítette, pedig oda volt téve a .jar hogy legyen frissítve :)

**Comment by poma123** [comment]
:)
