### ISSUE TITLE
Redstone kreatív védelem hiba

### ISSUE THREAD

**Issue by TOCMarciTheHUN** [andris155/TheOld-Crafters#3370]
**Survival**: 

**1.15.1**: 

Ha csinálunk egy redstones áramkört, jelenesetben ha egy lámpát szeretnénk felkapcsolni, és a kapcsolót fenntről  kell levezetni, akkor lehet ilyen hiba
![2019-12-30_21 35 31](https://user-images.githubusercontent.com/59374227/71599754-75acf700-2b4c-11ea-83dc-24131157921d.png)
csak akkor meg ha fenntről lefele kell vezetni, ha csak megy egyenesen egy szintben , akkor nem, facebookon küldtem videót is..

**Comment by andris155** [comment]
Nem sikerült reprodukálni. Más helyen szerintem neked sem megy. Kellene az, hogy pontosan, hogy lehet ilyen helyet létrehozni, ahol ez történik.

**Comment by andris155** [comment]
A fejlesztő nem nagyon foglalkozik a hibákkal. Talán egyszer javítva lesz. Bár én reprodukálni sem tudtam sehogy így fogalmam sincs, hogy egyáltalán a plugin hibája-e vagy valami más okozza-e.
