### ISSUE TITLE
Soulbound tárgyak

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#3374]
**Szerver**:  szurvi

**Verzió**: 1.15.1

Nem működik a soulbound-os eszközök képessége:
Ha meghalsz, nálad marad a cucc ami soulbound-os.

**Comment by andris155** [comment]
Nem sikerült reprodukálni a hibát.

**Comment by skrisz0101** [comment]
Hát nekem kb 2 órája se ment

**Comment by skrisz0101** [comment]
6 soul tárggyal és 3 különböző világban megpróbáltam, egyszer se maradt nálam.

**Comment by andris155** [comment]
Holnap elvileg már működni fog.

**Comment by andris155** [comment]
Adtam OCD-t a jelentésért.

**Comment by skrisz0101** [comment]
Jee, köcke
