### ISSUE TITLE
Slimefun-Reloaded teszt és fejlesztés

### ISSUE THREAD

**Issue by andris155** [andris155/TheOld-Crafters#3376]
Ez a Slimefun módosított változata, ami később egy jobb Slimefun-t eredményezhet.
Egyelőre a build-ok csak hibakeresésre vannak. Aki tudja nyugodtan tesztelgesse a plugin-t és jelentse a hibákat a fejlesztőnek.
https://www.spigotmc.org/resources/slimefun-reloaded.73726/

Aki ért hozzá a fejlesztésben is részt vehet.
https://github.com/OpticFusion1/Slimefun-Reloaded

**Comment by poma123** [comment]
Hát, teszt szerveren fent van (nem nyilvános), és hát sajnos még gyerekcipőben jár.
![image](https://user-images.githubusercontent.com/25465545/71646802-eab73280-2cec-11ea-903a-dbec500ffeb4.png)

**Comment by poma123** [comment]
Most már elindul, de egyelőre semmi sem működik benne.

**Comment by skrisz0101** [comment]
Kafa

**Comment by andris155** [comment]
Már egy ideje nem nagyon foglalkozik vele a fejlesztő. Nem hiszem, hogy lesz ebből valami. A sima Slimefun-t most nagyon elkezdték fejleszteni. Szóval egyelőre biztosan az marad.
