### ISSUE TITLE
Minemarket - spawnerek

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#3377]
**Szerver**:  szurvi + sav

Már egy ideje nyithatóak spawner ládakulcsok Mind2 szerveren. 
Azokat a spawnereket, amik a ládában kaphatóak, ki lehetne tenni szerintem külön is minemarketre (természetesen sokkal drágábban, mint a zombi, pók, stb) 
Pl 2032ocd, vagy ilyesmi. 

Ui: a husk/kiszáradt zombi spawnernek nincs értelme, ugyanolyan mint a sima zombi, lehetne valami más helyette.

**Comment by andris155** [comment]
Melyik spawnerekre gondolsz pontosan?

**Comment by skrisz0101** [comment]
Stray, zombimalac, gombaboci, magmakocka, nyuszi, papagáj, bárány, csirke,

**Comment by andris155** [comment]
Ezeket én szeretném meghagyni csak a spawneres ládában inkább. Sokkal értékesebb így, hogy ezeket csak ott lehet megszerezni.
