### ISSUE TITLE
Minemarket - Petek

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#3378]
**Szerver**:  szurvi. 
Lehetnének új petek:
Méh
Bébi méh
Esetleg bosszúálló
Esetleg mini hóróka

**Comment by andris155** [comment]
Melyik teremtmény a bosszúálló?

**Comment by skrisz0101** [comment]
Ahh, hülye vagyok
Pusztítóra gondoltam (ravager)

**Comment by andris155** [comment]
A meglévők közül esetleg van olyan, ami szerinted feleslegesen van a MineMarket-en?

**Comment by MrZero1** [comment]
Szerintem ami most van, azok maradhatnak. Plusz kerülhet be

**Comment by skrisz0101** [comment]
Kivenni felesleges szerintem is

**Comment by andris155** [comment]
Mini rókát könnyen lehet csinálni egy Easter egg-el a nagyból is. Szerintem felesleges berakni.

**Comment by andris155** [comment]
Rengeteget méh van több játékosnak is. Szerintem petnek OCD-ért ennek sincs nagyon értelme.
