### ISSUE TITLE
Minemarket - Játékpénz

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#3379]
**Szerver**:  mindenhol is

Tudom, hogy a staffok, Andris nem biztos hogy annyira tisztában van az ocd-$ árával, de akkor itt leírom hogy szinte mindenki 1000$ = 1ocd-vel kereskedik. 

Na, minemarketen kB 300$-t kapnak 1 ocd-ért, és szerintem fél évente ha 1 emberke vesz $-t minemarketen. Lehetne a mostani összeg duplája, amit kapnak, mert még úgy se éri meg ott venni a $-t, mint eladni szerveren. 

Szóval:
330ocd - 150.000$
508ocd - 300.000$

**Comment by andris155** [comment]
Módosítottam rajta.
