### ISSUE TITLE
/petrespawn auto nem működik

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#338]
Ha beírom: `/petrespawn auto`, nem történik semmi, régebben a pet azonnal újraéledt, és levonta a hátralévő másodpercek árát $-ban (500 másodpercnél 500$), most halott marad a pet, meg kell várni hogy respawnoljon.

**Comment by UDPSendToFailed** [comment]
+1: elírás van a szövegben:

![2016-11-14_12 56 13](https://cloud.githubusercontent.com/assets/16057404/20264082/0d1fea64-aa6a-11e6-8130-e865d156d05b.png)

**Comment by andris155** [comment]
Ezzel kapcsolatban úgy emlékszem már írtunk a fejlesztőnek. Ha azóta sem javította arra nem tudok mit mondani.

**Comment by andris155** [comment]
Az elírás javítva. Köszönjük.
