### ISSUE TITLE
Levédés, biomeváltás + nether biome tiltás

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#3380]
**Szerver**: szurvi 

Ha be állítom a biomeváltást (setclaimflag changebiome biomenév, pl savanna) 
Akkor nem történik semmi. 
Elment mindenki a levédésről a spawnra, aki ott volt, vártunk egy percet spawnon, de semmi. Nem váltott. 2x is próbáltam más-más biommal

**Comment by andris155** [comment]
Gondolom a 3D biome váltást nem támogatja még a plugin.

**Comment by andris155** [comment]
Egyelőre ez a jog megszűnt.
