### ISSUE TITLE
Kézzel nem nyithatóak az Enderchestek.

### ISSUE THREAD

**Issue by maryhonaly** [andris155/TheOld-Crafters#3381]
Szerver: survival , 1.15

Eddig csak telekvilágban tapasztalták a játékosok, hogy az Enderláda kézzel nem nyitható. 
A /ec paranccsal viszont elérhető a tartalma.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by andris155** [comment]
javítva
