### ISSUE TITLE
Ideiglenesen eltűnő petek 2.0

### ISSUE THREAD

**Issue by maryhonaly** [andris155/TheOld-Crafters#3382]
Survival, 1.15 

https://github.com/andris155/TheOld-Crafters/issues/3350

Az egyszer már jelentett jelenség továbbra is létezik, saját petkészletem néha elérhető, néha nem.

Egy ki-be lépés után helyreállt.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by andris155** [comment]
Nem tudom mitől lesz ilyen. Kellene a pontos reprodukálása, hogy tudjam javítani vagy jelenteni a fejlesztőnek.

**Comment by maryhonaly** [comment]
Pontos leírásnak annyit tudok adni, hogy: Belépést követően vagy elérhetőek a petek vagy nem. Semmilyen összefüggést nem fedeztem még fel, de egy puszta relog megoldja. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
