### ISSUE TITLE
Savsziget -> építész

### ISSUE THREAD

**Issue by maryhonaly** [andris155/TheOld-Crafters#3386]
https://github.com/andris155/TheOld-Crafters/issues/3384

Hasonló módon savszigetről építészre se lehet közvetlen átlépni.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by MrZero1** [comment]
#3384
https://github.com/andris155/TheOld-Crafters/issues/3384#issuecomment-570662257

**Comment by andris155** [comment]
Megpróbálom megoldani. Majd holnap kiderül, hogy jó-e.

**Comment by andris155** [comment]
kész
