### ISSUE TITLE
Cheat védelem mézblokk támogatása

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#3387]
Survivalon van ez a jelenség. Leesik a mézblokkra, de visszadobálja és közben jelzi is a rendszer.
![kép](https://user-images.githubusercontent.com/29709854/71764001-be650700-2ee2-11ea-8164-c91c6fdd5b75.png)

![kép](https://user-images.githubusercontent.com/29709854/71764010-d9377b80-2ee2-11ea-8f03-37fbc330d4b6.png)

**Comment by MrZero1** [comment]
janos_vagyok9185 jelentette

**Comment by andris155** [comment]
Ezt ma írta ki rá? Vagy tegnap?

**Comment by MrZero1** [comment]
Ma, amikor jelentettem. Megmutatta és jelentettem. Elvileg felveszi videóra és elküldi neked.

**Comment by andris155** [comment]
A következő verzióban javítani fogja a fejlesztő.

**Comment by andris155** [comment]
Elvileg javítva.
