### ISSUE TITLE
Hg - kezdésvédelem. 

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#3389]
**Szerver**: szurvi

Minden hg meccs elején kapunk kB 30mp védelmet mindenfajta sebzéstől. Ez néha bebuggol és közben megjalhatunk eséstől pl. 
Ez legjobban a rémrom és hupikéktörpikék mapon jön elő (le kell ugrani a kezdésről)

**Comment by andris155** [comment]
Szerintem az esésre nem vonatkozik ez.

**Comment by skrisz0101** [comment]
De vonatkozik, mert kB 8/10 alkalommal megvéd
