### ISSUE TITLE
Nem működik a /ping parancs

### ISSUE THREAD

**Issue by Balint2** [andris155/TheOld-Crafters#339]
A /ping parancs egyáltalán nem működik. ![ping pong](https://cloud.githubusercontent.com/assets/17943949/20270774/bd21a330-aa88-11e6-9b40-208f2209540d.png)

**Comment by andris155** [comment]
nem kellene utána semmit írni.

**Comment by Balint2** [comment]
de annyit se lehet beírni hogy /ping, szóval gyakorlatilag a parancs is le van tiltva.

**Comment by andris155** [comment]
nem kell utána írni semmit, és akkor működik
