### ISSUE TITLE
AFK

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#3391]
Sweet ötlete, nekem tetszik. Remélem megvalósítható.

Szóval, 15 perc AFK után kidobja a szerverről a játékosokat. Ez rendben is van, de mi lenne, ha nem a szerverről dobja ki, csak átrakja őket a lobby-ba? Így nem mennek másik szerverre, ha visszatérnek AFK-ból, hanem visszatérnek valamelyik szerverünkre? :)

**Comment by andris155** [comment]
Nem lehet sajnos így megoldani. Az EssentialsX nem támogat ilyet.

**Comment by skrisz0101** [comment]
@andris155 esetleg minden szerón egy
,,afk szoba"?

**Comment by MrZero1** [comment]
Hamar lelett zárva, gondolom egyszerűbb, mint ötletelni milyen megoldások lennének. Ezvan

**Comment by MrZero1** [comment]
![kép](https://user-images.githubusercontent.com/29709854/71779282-d22d6d80-2fb5-11ea-9ea0-cde52b2c78bb.png)
https://www.spigotmc.org/resources/%E2%9C%85-must-have-lol-%E2%AD%90ultraafk%E2%95%911-8-1-14%E2%95%91bungeecord-shared%E2%AD%90.29839/

esetleg ez, vagy ilyesmi? Szívesen kifizetem, ha prémium plugin.

**Comment by maryhonaly** [comment]
Szerintem is jó ötlet lenne. Kick helyett beteleportálni őket a spawn vagy az az eventvilágba valahova, ahol senkit sem zavarnak. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by andris155** [comment]
Nem szeretnék erre is külön plugint. Így is rengeteg van. Szelektálni kellene inkább a feleslegeseket.
