### ISSUE TITLE
Slimefun táska mozgatása a szám billentyűkkel

### ISSUE THREAD

**Issue by stumperkicsi** [andris155/TheOld-Crafters#3392]
survival

Radiant Backpack ha a kezedben van pl 1 es gomb és beszeretnéd rakni inventorydba akkor nemtudod csak ha nincs a kezedben.

Nemtudom mennyire hiba ez,gondolom szólok:)

**Comment by andris155** [comment]
Elvileg javítva. OCD-t adtam a jelentésért.
