### ISSUE TITLE
Craftbook pipe kemence hiba

### ISSUE THREAD

**Issue by KulGery** [andris155/TheOld-Crafters#3393]
**Szerver**: Savsziget

Csináltam kemence rendszert a csőrendszerrel, a kimenő dugattyú közvetlen a kemencébe rakja az égetnivalót. Működik is gyönyörűen, eltekintve attól, hogy az új égethető dolgokat nem rakja bele, mint például a követ. Tölcsérrel persze belemegy, de ebben az esetben kemencénként 6*64 elem áll sorban... ami nem elég jó elosztás. illetve "zabálja" a tölcséreket.

HIBA: a kemencébe a csőrendszer közvetlenül csak a "régi" elemeket rakja bele, az újakat mint pl. Kő nem.
![2020-01-06_20 59 22](https://user-images.githubusercontent.com/25465311/71844914-810d9e80-30c7-11ea-9a53-fe41187110f7.png)

**Comment by andris155** [comment]
Elvileg javítva.

**Comment by andris155** [comment]
OCD-t adtam a jelentésért és a szerveren való segítségért.

**Comment by KulGery** [comment]
Köszönöm!

**Comment by KulGery** [comment]
Javítás visszaigazolva!
