### ISSUE TITLE
Spawner limit

### ISSUE THREAD

**Issue by maryhonaly** [andris155/TheOld-Crafters#3394]
survival, 1.15

A rangoknál megadott napi kiüthető spawner limit az sf-es csákánynál már nem él. Korlátlant tudnak kiütni.

jelentette: jbala

**Comment by andris155** [comment]
@poma123 megszűnt akkor ez a limit?

**Comment by poma123** [comment]
mivel az sf-es csákányra nincs ilyen beállítás, evidens :D
