### ISSUE TITLE
Sf hiba?

### ISSUE THREAD

**Issue by AFekexd** [andris155/TheOld-Crafters#3395]
Az Ender Talisman of the Miner nem úgy tűnik hogy működne, míg a sima talizmánnál van visszajelzés a működéséről, addig az Ender-nél nincsen. 
Talisman of the Miner és Ender Talisman of the Miner tulajdonságai/leírása közt nincs semmi különbség.

**Comment by skrisz0101** [comment]
Ec-Ben kell tárolni az endert
