### ISSUE TITLE
Szántóföldes akármicsoda

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#3398]
kiratka666 jelentette, hogy ha szántófölden közlekedik, akad a menés, néha vissza is dobja. Az alábbi hibát is kijelezte, mikor sétál rajta.

![kép](https://user-images.githubusercontent.com/29709854/72189181-838c3300-33fc-11ea-9906-968afd1483b2.png)

**Comment by andris155** [comment]
Nem sikerült reprodukálni.
