### ISSUE TITLE
/ping alt parancsainak tiltása, ha írnak utána valamit.

### ISSUE THREAD

**Issue by Balint2** [andris155/TheOld-Crafters#340]
A /ping meg lett csinálva, de a /pong nincs.  ![ping pong2](https://cloud.githubusercontent.com/assets/17943949/20270872/19c2c178-aa89-11e6-81a2-ff568926b4ea.png)

**Comment by andris155** [comment]
Van egy pár alt hozzá na majd holnap megnézem.
