### ISSUE TITLE
Anti xray

### ISSUE THREAD

**Issue by stumperkicsi** [andris155/TheOld-Crafters#3400]
Szerver:Survival

Gyakran előfordul hogy az anti xray bebugol,banyaszas kozben elorehaladsz es csak 10-20mp mulva tunik el,nemtudom masnal hogy van de nalam elofordul,szoltam staffnak de ok azt irjak hogy lassu net miatt,netem stabil nem laggolok

Old csakannyal tapasztalom.simaval semmi gond

**Comment by skrisz0101** [comment]
Gyorsabban ütöd ki a blokkot, minthogy érzékelni az antixray (gondolom)
Ennyi

**Comment by stumperkicsi** [comment]
De ezt nemlehetne valahogy javitani?

**Comment by andris155** [comment]
Erről kellene egy videó, hogy a fejlesztő normálisan megértse meg én is.

**Comment by stumperkicsi** [comment]
Megprobalok kesziteni rola 15.en este
