### ISSUE TITLE
MineMarket újabb elem

### ISSUE THREAD

**Issue by KulGery** [andris155/TheOld-Crafters#3401]
**Szerver**: SavSziget
Szervusztok!

Úgy látom az old ládában több dolgot lehet kapni mint a marketen... 
Nincs Kapa, Páncél, Teknős sapka, és bot.
Kapám van valahonnan, lehet old ládából nyertem, de szeretnék teknőssipkát és páncélt is. Honnan lehet nem véletlenszerűen beszerezni?
Megoldható vagy direkt nem raktátok fel a Marketbe?

Üdv KulGery

**Comment by andris155** [comment]
Direkt nem kerültek ezek be, hogy legyenek olyan speciális tárgyak, amiket csak ott lehet megszerezni.

**Comment by KulGery** [comment]
Köszi, Én is így gondoltam, hogy ezért.
