### ISSUE TITLE
Pipe rendszer Savsziget

### ISSUE THREAD

**Issue by KulGery** [andris155/TheOld-Crafters#3402]
**Szerver**: Savsziget

Jó lenne, ha az alsó sorba is lehetne a szűrési feltételt írni, hogy többet szűrhessen.
Illetve wildcard karakterek a hosszú nevek, illetve a hasonló elemek miatt, pl. *_log az összes rönk.

A csőrendszernél megoldható valahogy hogy csak azt rakja a ládába ami más helyen nincs szűrve? Vagy legalább azt hogy fordított szűrő, az ne kerüljön bele? pl. -string

Tudom ez plugin fejlesztés, de ti vagytok a fejlesztővel kapcsolatban.

Köszi.

**Comment by andris155** [comment]
Ide tudsz írni ötleteket, és hibákat a Craftbook fejlesztőnek persze angolul.
Ha írsz valamit ne felejtsd el kiválasztani a megfelelő kategóriát.
https://dev.enginehub.org/youtrack/issues/CRAFTBOOK
<img width="1014" alt="Annotation 2020-01-16 173116" src="https://user-images.githubusercontent.com/8324198/72543505-2245e300-3886-11ea-8e86-e4ac672060d4.png">

**Comment by andris155** [comment]
WorldEdit version 7.1.0-beta-1;7039dc8
WorldGuard version 7.0.2-SNAPSHOT;bf2593e
CraftBook version 3.10.2-SNAPSHOT;4552-0188261
Ha kérdezik a plugin verziókat jelenleg ezeket használjuk.

**Comment by KulGery** [comment]
Wow köszi.
