### ISSUE TITLE
Youtube rang

### ISSUE THREAD

**Issue by maryhonaly** [andris155/TheOld-Crafters#3403]
Nem az első eset, hogy valakinek meg vannak a feltételek, de a yt plugin nem adja meg a rangot. 
https://www.youtube.com/watch?v=r6TACtZywhM. Régi, de a leírásban és a névben ott van ami kell. 

Cr0ssbt a játékos, illetve az alábbi hibaüzenetet írja neki: "Nincs elég socialvideos"

**Comment by andris155** [comment]
Eddig mindig kiderült, hogy a plugin tökéletes, csak a játékos nem felelt meg a feltételeknek.

**Comment by andris155** [comment]
Még most sem adja meg neki?

**Comment by maryhonaly** [comment]
Most próbálta, nem engedte neki. Ugyan azt írja neki.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by andris155** [comment]
Próbálja meg a videók elejére írni a címet, és a leírás elejére írni a weboldalas szükséges szöveget.

**Comment by MrZero1** [comment]
Azt írta, megpróbálta, de nem jó neki.

**Comment by Crossbt** [comment]
Halihó!
Jelentem eddigi próbálkozások sikertelenek, mind1 hova van írva a kért szöveg, az eredmény ugyan az...
![Screenshot_18](https://user-images.githubusercontent.com/60049230/72671464-f9bb1600-3a4a-11ea-9db2-220c07f729fc.png)

**Comment by andris155** [comment]
Melyik YouTube rangot választod ki?

**Comment by Crossbt** [comment]
Legkisebbet. De egyikel sem engedi

**Comment by Crossbt** [comment]
Na csak sikerült beaktiválni a "Youtube" rangot, felkerült a tegnapi strím videóként a csatira, és így elfogadta, tehát akkor a régi videókat eddig nem látta valamiért a rendszer feltételezem, és ezért írta a hibakódot.

**Comment by andris155** [comment]
Szerintem kell akkor hozzá legalább egy friss videó is vagy nem tudom miért nem működött.
