### ISSUE TITLE
Savsziget jég

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#3404]
**Szerver**: Savsziget

Savszigeten a jég nem olvad el (meleg óceán biom)

![kép](https://user-images.githubusercontent.com/29709854/72554391-df423a80-389a-11ea-96f3-2aff5fce5c01.png)

Small jelentette. A kősor a sziget szélét jelzi, látni, hogy a szigeten belül és kívül sem olvad el.

**Comment by andris155** [comment]
Ez az enchant-os jég?

**Comment by MrZero1** [comment]
Nem

**Comment by andris155** [comment]
Csak úgy magától nem fog elolvadni. Rakjon mellé valamit, ami megolvasztja. Pl.: fáklya
