### ISSUE TITLE
Savsziget petek

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#3405]
**Szerver**: Savsziget

Bekerülhetne a mypet savszigetre is, ha már az a petes dolog nem került be, ami OldVillage-n volt. Tagnak 1, rangtól függően meg több. Mivel rengeteg mob nem elérhető, így akár Minemarket-be is bekerülhetnének azok, amiket nem tudnak elérni a savszigeten.

**Comment by MrZero1** [comment]
Még a mai nap összeírjuk/írom a listát, melyik pet mehetne minemarket-be.

**Comment by MrZero1** [comment]
Beszéltem Sweetan-nal, azt javasolta, legyen úgy, mint Survivalon (beállítás). 
Ami van Minemarket-en pet, az lehetne vásárolható savszigetre is, aztán később még lehetne azt a listát bővíteni.

**Comment by andris155** [comment]
kész
