### ISSUE TITLE
Savsziget bázis betörési lehetőség

### ISSUE THREAD

**Issue by KulGery** [andris155/TheOld-Crafters#3406]
**Szerver**: Savsziget

Víz alatt, ha a fal keskenyebb mint 3 blokk, akkor két játékos be tud hatolni a falon.
Az egyik játékos odaáll a fal mellé, a másik meg tpa-val teleportál. A játék a mellette levő száraz helyre teleportálja, akár 3 méterrel arrébb, azaz a víz alatt a bázisnak három méteres falat kell csinálni, hogy behatolóktól védve legyen

**Comment by KulGery** [comment]
tudom, ez nem a szerver hibája, hanem a MC alaplogikája.

**Comment by KulGery** [comment]
Szerintem így survivalben is be ehet jutni, ha a tulaj nem védi le a területet a faltól kijjebb is

**Comment by KulGery** [comment]
Megoldás lehet, hogy a beállításokba betenni, a TP-t, és vendég ne ugorhasson vendégre a szigeten. Illetve ahogy állítjuk... Ha coopnak is tiltjuk akkor coop-se

**Comment by KulGery** [comment]
Avagy, ha beállítható a TP cél rádiuszát levenni 1m-re

**Comment by andris155** [comment]
Erre nincs megoldás.
