### ISSUE TITLE
SF - Spawnerek

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#3407]
**Szerver**: Survival

Továbbra sem jó. Nem tudom, hogy mivan vele, de megírom, ha majd jó lesz, lezárjuk ezt.

![kép](https://user-images.githubusercontent.com/29709854/72750404-0fe8e380-3bbd-11ea-9778-965ed2de9302.png)

**Comment by andris155** [comment]
Mikor lesz ez ilyen? Amikor megjavítják az altar-ban?

**Comment by skrisz0101** [comment]
Amikor kiütik a javított spawnert

**Comment by maryhonaly** [comment]
Új infó: ha vadonban kis föld alatti teremben generált pl. zombi spawnert ütnek ki, akkor szabályosan brokent kapnak. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by maryhonaly** [comment]
Még egy teszt: ha normál régi spawnert teszem le, és sf csákánnyal ütik ki, akkor is brokent kap.

**Comment by poma123** [comment]
Perceken belül javítva lesz egy resi után :D

**Comment by poma123** [comment]
javítva
