### ISSUE TITLE
Dupla output láda

### ISSUE THREAD

**Issue by TOCMarciTheHUN** [andris155/TheOld-Crafters#3408]
Ha lerakunk egy alap slimefunos gép mellé egy output ládát, és ahhoz a ládához rakunk egy sima ládát , akkor lesz egy dupla output láda.
![2020-01-23_17 43 27](https://user-images.githubusercontent.com/59374227/73004653-f9829800-3e07-11ea-801b-e700a6c58c28.png)

**Comment by KingDeadZ** [comment]
Ha kiütöd is output láda lesz?

**Comment by andris155** [comment]
Itt most mi a probléma?

**Comment by andris155** [comment]
Ez direkt ilyen.
