### ISSUE TITLE
mc1421

### ISSUE THREAD

**Issue by stumperkicsi** [andris155/TheOld-Crafters#3409]
survival

Nem működik megfelelően a [MC1421] órajeles tábla.
Egyszer megy,egyszer nem,lassan számol majd gyorsit.
Valamikor el sem indul a számolás.
Adminok is látták a szerveren náluk sem számol,akadozik.

**Comment by andris155** [comment]
A Slimefun miatt gyakran leesik a TPS az az Tick per second szám. Tehát akkor lassabb, amikor a játékosok szavával ,,laggol" a szerver.
