### ISSUE TITLE
idő

### ISSUE THREAD

**Issue by stumperkicsi** [andris155/TheOld-Crafters#3411]
Jó lenne ha a szerverre bekerülne egy parancs pl. /ido és megjeleniti a pontos irl idot :)

**Comment by KingDeadZ** [comment]
Vagy lenézel a képernyő jobb alsó sarkába, és meglátod az időt.

**Comment by MrZero1** [comment]
Építész+-on lehetne jog erre tagnak? :DD

**Comment by andris155** [comment]
Elvileg nem is kell hozzá, vagy igen?
