### ISSUE TITLE
SF, backpack hiba

### ISSUE THREAD

**Issue by maryhonaly** [andris155/TheOld-Crafters#3412]
Survival, 1.15.2, SF plugin, backpack:

Saii1 jelezte, hogy eltűnt a hátizsákjának a tartalma. Ezt talán még valahogy vissza lehet kérni, poma eldönti. 
A hiba a következő: Elvi síkon ezeket a táskákat nem lehetne lerakni. Amíg levegőbe klikkelsz velük, nincs is probléma, viszont ha egyszer véletlenül egy blockra, akkor letevődnek. A felvételt követően a tartalma az enyészeté lesz. 
![2020-01-28_14 43 23](https://user-images.githubusercontent.com/53797506/73273220-ebf05800-41e3-11ea-97c8-9a186dc7db06.png)
![2020-01-28_14 43 19](https://user-images.githubusercontent.com/53797506/73273221-ec88ee80-41e3-11ea-9581-77d60bead439.png)

Valahol van itt két kép. A sima táskák működnek rendeltetés szerűen, viszont a "Dyed backpack" címkével ellátottakat le lehet rakni, és kész is a baj.

**Comment by andris155** [comment]
javítva
