### ISSUE TITLE
Mobaréna kaszt - rang

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#3415]
Szia.

Nincs már 'Tank' kaszt, VIP-nek csak a Halhatatlan kaszt van. (Prémiumnak csak a Hiperugrás)

![kép](https://user-images.githubusercontent.com/29709854/73579282-44dd1c00-4482-11ea-843f-ca6171238f77.png)

**Comment by andris155** [comment]
Javítva.
