### ISSUE TITLE
Weboldal

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#3416]
Szia. 

Az egyéb résznél, ha nem nyitod le a nyilat, hanem csak rákattintasz az Egyébre, úgy ezt hozza be. Itt nem hozza a fogalmakat és még látszódik a vanilla add.

![kép](https://user-images.githubusercontent.com/29709854/73579393-94bbe300-4482-11ea-81fe-334b2fd2e307.png)

**Comment by andris155** [comment]
Mivel ez egy külön oldal néha elfelejtem frissíteni. :D
Köszi, javítottam.
