### ISSUE TITLE
Savszigeten eltűntek a dolgos parasztok

### ISSUE THREAD

**Issue by KulGery** [andris155/TheOld-Crafters#3418]
**Szerver**: Savsziget

almacsutka észrevette, hogy eltűntek a szakmával rendelkező parasztjai.
Odamentem én is a falumhoz, és nekem sincs meg egy falusim sem. De a vasemberek ott vannak. Illetve az állatok is megvannak

![2020-02-04_19 35 06](https://user-images.githubusercontent.com/25465311/73775270-dcde4c80-4785-11ea-8475-d06034718160.png)

**Comment by andris155** [comment]
Sajnos a Minecraft világ név alapján tárolja a falusiakról az információkat. Eddig volt egy world világ, amiben igazából semmi se volt. Illetve még nether és end is volt hozzá. Ez volt a fő világ, mert amikor készült a szerver még nem igazán működött úgy az egyedi generálás úgy, hogy a fő világhoz van megadva az egyedi generátor. Azonban ezt azóta javították így ezek a felesleges világok törlésre kerültek. De mivel ugye már nem world a fő világ neve, hanem acidisland_world így azok a falusiak, amikről tárolt adatot a szerver elvesztek.
Erre sajnos nincs megoldás.

**Comment by andris155** [comment]
Adtam OCD-t, abból tudsz venni falusi idéző tojást.
