### ISSUE TITLE
Staffok

### ISSUE THREAD

**Issue by MrZeroTOC** [andris155/TheOld-Crafters#342]
Szia Andris!

Szeretném ill. szeretnénk normálisabb staffokat a PC Survival szerverre :D

Köszi, Bence

**Comment by asdlol911** [comment]
Te voltál az egyik olyan, aki tanította a staffokat és ennyi telik tőled?
Kicsit szánalmas, kedves Bence.

**Comment by MrZeroTOC** [comment]
Én speciel nem rád gondoltam, aki kicsit is beszélt velem az pontosan tudja, ki a probléma 😄

**Comment by Balint2** [comment]
Ezt most komolyan te írtad? Vagy valaki Zéró névvel?

**Comment by MrZeroTOC** [comment]
Én speciel nem rád gondoltam, aki kicsit is beszélt velem az pontosan tudja, ki a probléma 😄
