### ISSUE TITLE
Feloldhatatlan tiltások

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#3420]
**Szerver**: Login

Nem lehet feloldani a tiltásokat, ami mondjuk meg, baromi zavaró. Se régit, se újat, se semmit. Azt írja, semmi sem változott, nincs kitiltva az ember. De ki van tiltva, fel se tud jönni. Légyszi:(

**Comment by andris155** [comment]
milyen neveket kell feloldani?

**Comment by MrZero1** [comment]
Esetleg arra nincs mód, hogy a pardon vagy más parancs működjön?

**Comment by andris155** [comment]
Nem tudom, hogy mikor működik és mikor nem. Én próbáltam régebbit tiltással és működött pedig.

**Comment by andris155** [comment]
Ha nem működik szerintem nem olyan nagy probléma, ha írni kell nekem és megcsinálom.
