### ISSUE TITLE
Auto Event TrapLabirintus Bugos

### ISSUE THREAD

**Issue by KulGery** [andris155/TheOld-Crafters#3423]
**Szerver**: SavSziget

Az autoevent traplabirintusban van egy bug,  ami miatt nem sötétít be,  és lehet szaladni.
Erről a bugról hosszabb ideje van tudomásom, de tudtommal nem volt egyértelműen újraidézhető. Nálam összesen egyszer jelentkezett, anno aki észrevette, annál kb 5x de nem élt, vagy nem tudom, hogy élt-e a lehetőséggel.

Regocike06 nem csak a bugot fedezte fel, hanem meg is találta az módját, hogy aktiválja.
Így fölénnyel beelőz mindenkit.

Javaslom, hogy amíg a hiba nincs orvosolva, az adott event legyen lezárva.

Én úgy olvastam Regocike írását, a 4 gombnál (Kék, Piros, Zöld, Sárga) ha ctrl-w-vel nyomjuk be a gombokat, akkor aktiválódik.

Üdv. KulGery

Még egy hiba, chrome-al a https://www.oldcrafters.net/kapcsolat/-lapon nincs captcha... de kiírja, hogy nem oldottam meg helyesen.

![image](https://user-images.githubusercontent.com/25465311/74103386-f3045800-4b4b-11ea-9be1-b21ff6cc8b28.png)

**Comment by andris155** [comment]
Nekem és másoknak is tökéletesen működik a kapcsolat oldal.
<img width="884" alt="Annotation 2020-02-10 191904" src="https://user-images.githubusercontent.com/8324198/74177568-4b198800-4c3a-11ea-8c6d-73b83e57b877.png">

**Comment by MrZero1** [comment]
Köszi a jelentést. Lezárom. Adtam OCD-t is.

**Comment by KulGery** [comment]
A bugot Regocike06 újra kihasználta, és újra gond nélkül azonnal aktiválta, és természetesen első is lett. Elszáguldott mellettünk megint.

**Comment by andris155** [comment]
ctrl + w-vel is működik az effekt. Szerintem talán valami forráscsomaggal belehet csalni, vagy valami módosított klienssel esetleg. Ezek tudatában mondjuk sok értelme nincs így ennek az eventnek. Meg elég nehéz kiszűrni ezt, ha nincs online staff.

**Comment by andris155** [comment]
Javítottam. @MrZero1, aki beállította, annak ezt mond meg majd. Ha pedig te voltál, akkor neked szól.
@p volt megadva, ami azért nem jó, mert csak a legközelebbi játékosnak fogja megadni mindig. Ha van megadva distance, akkor érdemes @a-t használni ennél a paranccsal, mert akkor 100%, hogy mindenki megkapja ott. Az se baj ha többször, de a lényeg, hogy kapja meg az effektet.

**Comment by andris155** [comment]
<img width="586" alt="Annotation 2020-02-22 203330" src="https://user-images.githubusercontent.com/8324198/75098111-9a54a680-55b2-11ea-89f5-a823515d2cdc.png">

**Comment by andris155** [comment]
<img width="586" alt="Annotation 2020-02-22 203330" src="https://user-images.githubusercontent.com/8324198/75098121-b35d5780-55b2-11ea-9701-8e8dbfefb112.png">

**Comment by andris155** [comment]
De ez esetben tényleg fontos a distance, mert ha nincs akkor az online összes játékosra vonatkozik.
