### ISSUE TITLE
BackPack hiba

### ISSUE THREAD

**Issue by nexon97** [andris155/TheOld-Crafters#3425]
**Szerver**: Survival

Szeretnem jelenteni a szinezett backpack hibat 
par nyitogatas es hasznalat utan elbugolnak
en is igy jartam egy kék szinu BackPackel amit tegnap hasznaltam pakoltam bele 2 db ender lump 2 ot meg bibircsokot 
es ma szerettem volna megnyitni es azt irja hogy CSCoreLib feje

**Comment by andris155** [comment]
elvileg javítva
