### ISSUE TITLE
Lucky block anomália

### ISSUE THREAD

**Issue by maryhonaly** [andris155/TheOld-Crafters#3426]
Surival, 1.15.2, SF

Miután a lucky blockokból el lett távolítva minden Lucky szett, kard, a blockok működése kiszámíthatatlan lett. 54-et vettek, 1 fejjé változott (old játékos). Tag rangú játékosnak adtam teszt céllal mind a 3 típusból vagy nyolcat, 2 nyílt ki mindössze. Másoknál is hasonló, 4/1 az arány.

Lehet valami nem az igazi.

**Comment by andris155** [comment]
Nem sikerült reprodukálni a hibát.
