### ISSUE TITLE
Goldie2000 ötletei:

### ISSUE THREAD

**Issue by maryhonaly** [andris155/TheOld-Crafters#3427]
Survival. Goldie2000 ötletei:

"Sziasztok!

Az az ötletem támadt!
A, Verzió: Mi lenne akkor ha bekerűlne a szerverbe a fly rang amit $-ért lehetne megvenni!
mint pl:[Fly]Goldie2000
És csak repűlni lehetne! a /fly paranccsal!

B, verzió: Vagy be kerűlhetne a Morph! videó róla -> https://www.youtube.com/watch?v=PycVf9m7GHU

Meg arra gondoltam mi lenne akkor ha a /klan parancsot beiktatnátok a szerverbe?
Mert ez így rossz hogy van a /party parancs mert így nem élvezetes annyira a játék.
Meg mostmár lenne több értelme szörnyeket (Mobokat) ölögetni hogy kapjanak a játékosok klán pontot
amivel Prefixet,klán otthont,Játékosokat,klán páncélt/Ezközöket lehetne fejleszteni!

Meg be kerűlhetne a /rtp-is a szabadban!

Meg pl: Egy Hard Core-mod lényege ugyan az mint a survivalnak csak nincs /tp Meg ilyenek benne
        Hanem fúl nehézre van állítva. meg hogyha meghalsz 12-óra múlva mehetsz csak vissza!"

**Comment by KingDeadZ** [comment]
Régen volt hardcorex, de nem jártak fel rá ezért már nincs...

A klános dolog felét kicsit átalakítottam, ha tetszik igy.
pár óránként/naponta spawnolhatna valami különleges boss szerű mob, ami adhatna valami jogot. pl. szines nick, vagy különleges itemeket.

**Comment by andris155** [comment]
Egyik sem kerül megvalósításra, de köszönjük az ötleteket.
