### ISSUE TITLE
Survival - Slimefun - Auto Disenchanter hiba

### ISSUE THREAD

**Issue by Sz4rv4s** [andris155/TheOld-Crafters#3428]
**Üdv!**
A Survival szerveren, a Slimefun plugin **Auto Disenchanter** eszköze nem működik, éppen le szerettem volna szedni enchantokat egy csákányról, de nem indult el a folyamat, kértem segítséget egy admintól, Zero próbált segíteni, kicserélte, de nem volt jó továbbra sem.
Remélem segítettem, Szarvas!

**Comment by KingDeadZ** [comment]
Milyen csákányról van szó? Nem volt rajta véletlen X-es enchant?

**Comment by poma123** [comment]
mcMMO-s tárgyakról és olyanokról, aminek egy enchantja 10 vagy annál nagyobb számú, nem engedi disenchantolni. de majd ránézek

**Comment by poma123** [comment]
teljesen jól működik, szerintem vagy mcmmo-s volt az item, vagy x-es enchantos

**Comment by Sz4rv4s** [comment]
Cobalt Pickaxe volt, Szerencse 3-al felturbózva, meg Önjavítással.
