### ISSUE TITLE
Eventrendszer

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#3429]
**Szerver**: Jelen pillatban savsziget

Gondoltam használom a meglévő parancsot, hogy javítsam a bugot az egyik jelentésnél, de nem megy a parancs.
![kép](https://user-images.githubusercontent.com/29709854/74587475-22efa780-4ff3-11ea-8084-077526f810bf.png)

**Comment by MrZero1** [comment]
Plusz vannak olyan auto eventek, ahol 2 főtől is elindul, de így nincs értelme, csak farmoljátok a tokent, pénzt, ilyesmit. 4 főtől induljon mindegyik event. A traplabirintus fixen 2 főtől indul, úgy is ér véget.

**Comment by andris155** [comment]
@poma123

**Comment by poma123** [comment]
/eventrendszer eventtp...

a másikat meg /eventrendszer eventbeallitas-al lehet megcsinálni de majd akk ránézek

**Comment by andris155** [comment]
köszi

**Comment by poma123** [comment]
átállítottam mindent, a labirintus volt az ami 5 főtől indul, gondolom direkt
a parancs pedig továbbra is 
/eventrendszer eventbeallitas
és
/eventrendszer eventtp

egyébként tudsz tabolni az "/eventrendszer" után és ott megtalálod az összes parancsot
