### ISSUE TITLE
Eventrendszer vagy effekt, nemtudom

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#3430]
**Szerver**: Savsziget

Van az eventen olyan nyomólap, ami erősebb lassúságot aktivál, olyat, amivel menni nem lehet, csak ugrálva közlekedni. Vagyis ugrálva lehetne, de nem lehet, mert ahogy ugranál és mennél előre, rángatózik a karakter és nem megy sehova. Megoldható, ha kisebb erősségű lesz az effekt, de az eventen direkt lett úgy.

**Comment by andris155** [comment]
milyen effektet aktivál pontosan?

**Comment by poma123** [comment]
sztem ez inkább ncp lesz

**Comment by andris155** [comment]
Nyilván az, de ha azt se tudom milyen effekt meg hányas akkor nehéz lesz tesztelni és jelenteni a fejlesztőnek. :D

**Comment by MrZero1** [comment]
![kép](https://user-images.githubusercontent.com/29709854/74602884-a4a40b80-50ad-11ea-8547-3d8cc38a49e4.png)

**Comment by andris155** [comment]
A teszt szerveren nem volt gond az NCP-vel. Bővebben kell majd tesztelnem.

**Comment by andris155** [comment]
Nem sikerült reprodukálni a savsziget szerveren tag ranggal. Az effekt tökéletesen működött arra, amit írtál.
