### ISSUE TITLE
Lucky block hiba

### ISSUE THREAD

**Issue by maryhonaly** [andris155/TheOld-Crafters#3431]
1.15.2

https://github.com/andris155/TheOld-Crafters/issues/3426

Vagy 3 külön játékoson teszteltem.  https://www.youtube.com/watch?v=QdVxl-nKY4s

OP mellett nekem is működik.  https://www.youtube.com/watch?v=TChtHxmkJUg

**Comment by poma123** [comment]
akkor ez egy jog lesz

**Comment by andris155** [comment]
Szerintem meg hibás.

**Comment by andris155** [comment]
javítva
