### ISSUE TITLE
Átfolyásjelző nem órajel

### ISSUE THREAD

**Issue by KulGery** [andris155/TheOld-Crafters#3434]
**Szerver**: Savsziget

Tudom, nagy baj van a vibráló vöröskővel.
De én semmilyen órajelet nem használok. Csak a komparátor ad jelet szemmel folyamatos jelnek látszik, miközben a tölcséren folyik át a cucc. Azért, hogy ha átfolyt, el indíthassa a csillét, hogy begyűjthesse a többi begyűjetni valót is.
Pont azért csináltam ilyenre, mert a folyamatosan guruló csille úgy tudom, több procit eszik, mint a bő két percig "vibráló" komparátor. aztán megy még egy kört, majd bő percig vibrál. Utána 15 percen keresztül csendben van. Semmi nem változik, csak a bambusz nő szép csendben.

0:50s csille
3:18 "vibrálás" ami nem látható, de gondolom azért vált át táblára pár kör után...
15 perc nyugalom.

Örülnék, ha lenne megoldás a tölcséren átfolyás végének az ellenőrzésére...

Üdv. KulGery

**Comment by KulGery** [comment]
Érdekes, hogy a figyelő (observer) nem jelez változást... Lehet mégcsak nem is vibrál?

**Comment by KulGery** [comment]
![2020-02-17_20 49 23](https://user-images.githubusercontent.com/25465311/74685677-86363100-51cf-11ea-8278-0ab72cf74bd1.png)
Kitáblázva

**Comment by KulGery** [comment]
![2020-02-17_20 50 08](https://user-images.githubusercontent.com/25465311/74685715-99490100-51cf-11ea-8253-b99b95e6eede.png)
Vissza raktam. És lemértem mennyire igaz amit a tábla ír...

**Comment by KulGery** [comment]
![2020-02-17_21 52 31](https://user-images.githubusercontent.com/25465311/74685790-d1e8da80-51cf-11ea-93a5-1d750c7c0050.png)
Mint kiderült egyáltalán.
A dugattyú csak akkor jelzett jelet, mikor betettem a marék zúzottkövet, meg a végén... Közben nem. Pedig a figyelő minden apró változásért jelez.

**Comment by andris155** [comment]
A plugint nem érdekli te mire használod. Csak a villogás sebességét nézi.

**Comment by maryhonaly** [comment]
Tapasztalat: Ha a tölcsérbe csillén keresztül megy az item, a tölcsér akkora sebességgel adja tovább az itemet, hogy az őt figyelő komparátornak nincs ideje állapotot váltani, valós órajel nem keletkezik, amit órajelnek lehetne használni, de ha a komparátor mintavételi ideje kellően nagy lenne, akkor elvben lehetne órajel. A pwapromon építettem rá teszt gépet. 
Single playerben is megcsináltam, ugyan így működik. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by KulGery** [comment]
Igen, én is azt mondtam, hogy a plugin nézi rosszul... Mivel nemcsak hogy nem órajelnek használom, de nem is használható órajelnek.

**Comment by KulGery** [comment]
Akkor mondja azt a tábla, hogy vibrál, és azért tiltja le. És megértem, hogy az a baja...

**Comment by KulGery** [comment]
Közben végig vizsgáltam a berendezést, és rájöttem, hogy hol az órajel. A ládából, amit tölt a tölcsér, egy mini csőrendszer tölti tovább sulkerekbe. Ennek az időzítője 0.5s. emiatt lesz mégis órajel a comparátoron.
Átállítottam 2s-re így már nem táblázza ki a rendszer...
