### ISSUE TITLE
Slimefun Soulbound

### ISSUE THREAD

**Issue by Ziredus** [andris155/TheOld-Crafters#3435]
Hello!
Survival szerveren a Soulbound runával kombinált sisak halálkor nem marad a playernél. Ugyanakkor a slimefunban készithető "soulbound pickaxe" viszont igen.

**Comment by andris155** [comment]
Nem sikerült reprodukálni.
Tőlem nem veszett el a Soulbound Helmet halálkor tag ranggal.

**Comment by skrisz0101** [comment]
@andris155 soulbound rune-val lett rátéve a soulbound, vagy csak essence-vel?
Írta @Ziredus hogy csak a rune-s nem megy

**Comment by andris155** [comment]
A végeredmény ugyanaz nem?

**Comment by KingDeadZ** [comment]
Tudtommal, ha rúnát dobsz rá akkor megtarthatja a nevét, és nem szimplán átalakul soulbounddá. (na meg megtartja az encsiket)
De valószínűleg máshogy van kódolva.

**Comment by andris155** [comment]
Akkor majd ezt még bővebben tesztelnem kell.

**Comment by andris155** [comment]
Nem sikerült azzal sem reprodukálni. Ha neked sikerül, akkor kérlek írd le pontosan hogyan.
