### ISSUE TITLE
Láva

### ISSUE THREAD

**Issue by maryhonaly** [andris155/TheOld-Crafters#3436]
Survival, 1.15, SF

füge játékos rájött, hogy hogyan lehet lávát lerakni admin nélkül. Videó lent.
![2020-02-18_18 11 15](https://user-images.githubusercontent.com/53797506/74761328-234ea380-527c-11ea-9e7f-d712c41bf6c4.png)
![2020-02-18_18 11 33](https://user-images.githubusercontent.com/53797506/74761330-23e73a00-527c-11ea-81f4-81ae46e6007a.png)

Videón mellékelem. Egy "Crucible" nevű sf itembe kell konkrétan bele buggoltatni (vagy ha így kell menjen akkor nem bug) zúzottkövet, mire az lávát termel. Ki kell ütni az üstöt, és kész a lávaforrás.

https://www.youtube.com/watch?v=_pzoVzdwIv8

**Comment by poma123** [comment]
Holnap betölt
