### ISSUE TITLE
Craftbook kapu

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#3437]
**Szerver**: Survival

![kép](https://user-images.githubusercontent.com/29709854/74970212-4618bd80-541e-11ea-9105-833723054eca.png)

igazából nem hiba, csak nem tudom, hogy normális az, hogy négyszer írja ki egy kattintásra, hogy nincs elég blokk :D

**Comment by MrZero1** [comment]
A kapu átállítva szöveg jó, azt egyszer írja ki, a képen azért van kettő, mert közben nézegettem és nem írt más a chatre :D

**Comment by andris155** [comment]
A fejlesztőnek megírtam. Nem nagyon akarja javítani. De ez szerintem nem olyan nagy probléma.
