### ISSUE TITLE
Setclaimflag

### ISSUE THREAD

**Issue by Niccolettie** [andris155/TheOld-Crafters#3439]
Survival szerveren a levédett területemen beírtam a napos idő flag parancsát _(setclaimflag playerweather sun)_ de nem váltott át napos időre, esett tovább az eső.
![setclaimflag](https://user-images.githubusercontent.com/48986609/75571152-ec854400-5a58-11ea-9a79-d41c6d5ef5c3.png)

**Comment by Niccolettie** [comment]
a s_etclaimflag playertime day_ parancs sem működik.

**Comment by Niccolettie** [comment]
a _setclaimflag playertime day_ parancs sem működik.

**Comment by andris155** [comment]
el kell menni a területről, majd visszamenni.

**Comment by andris155** [comment]
illetve valószínűleg a ptime és pweather felülírja.
