### ISSUE TITLE
/warp bolt elírás?

### ISSUE THREAD

**Issue by lovi-dev** [andris155/TheOld-Crafters#3442]
Survival  szerveren a /warp bolt -ban (slimefun részleg) nem tudunk Flask of Knowledge -et eladni. 
A /iinfo a táblára kiírt ExperieBottle#bA helyett ExperienBottle#fc  -t mond rá.

Üdv, Lovi_

**Comment by MrZero1** [comment]
Javítva, köszi! Nem az első ilyen változás a Slimefun részen, szóval ha lenne még ilyen, jelezd nyugodtan. Köszi!
