### ISSUE TITLE
Részeg MCMMO

### ISSUE THREAD

**Issue by Niccolettie** [andris155/TheOld-Crafters#3444]
29. horgászat szint után 34-re ugrott indokolatlanul.
![lol](https://user-images.githubusercontent.com/48986609/76170265-9ca52c00-6180-11ea-8d86-2a72109cb0f6.png)

**Comment by andris155** [comment]
Nem miért adott több szintet. Biztosan van rá valami magyarázat. Az mcMMO egy nagyon nagy és bonyolult plugin. Teljesen én sem tudom mik vannak benne sajnos és mit ad miért pontosan.
