### ISSUE TITLE
Pipe plugin + tölcsér

### ISSUE THREAD

**Issue by maryhonaly** [andris155/TheOld-Crafters#3445]
Savsziget, Pipe + tölcsér :

Jelentette: hanjo

Amennyiben a pipe rendszer egy MC1421-es tábláról kapja az órajelet, illetve a pipe rendszer egy tölcsérből viszi el az itemeket, akkor: ha azt szeretnéd, hogy az órajel csak akkor menjen, amikor a tölcsérben van item, egyébként álljon, egy komparátorral meg egy negálással megteheted. 
Itt jön a hiba: amennyiben a tölcsérből pipe viszi ki az itemeket, a komparátor nem érez benne mennyiségbeli változást, továbbra is adja a jelet, mintha tele lenne.

**Comment by hanjocraft** [comment]
Egy áttekintő képernyőfotó, ha már megépítettem a demo-t...
![2020-03-09_17 21 07](https://user-images.githubusercontent.com/61683937/76234804-7b991580-622a-11ea-9fd8-b6168a93a139.png)

**Comment by andris155** [comment]
Ez valamiféle Spigot hiba. Sajnos a kód részéhez nem nagyon értek. Nem tudom pontosan melyik részében van a hiba így én nem tudom jelenteni ezt a Spigot-nak. Ha fejlesztő jelentette vagy jelenti, akkor biztosan megoldják majd.
