### ISSUE TITLE
Vak komparátor

### ISSUE THREAD

**Issue by hanjocraft** [andris155/TheOld-Crafters#3446]
**Szerver**: Savsziget

Installáció: 1 üres láda, amelybe valamelyik oldalról üres tölcsér vezet, a ládát pedig komparátor figyeli. Amint egy blokkot beteszek a tölcsérbe, az áttöltődik a ládába, a komparátor pedig jelzi, hogy a ládában van legalább 1 elem. - Simaliba

Ha a fenti installációt annyiban módosítom, hogy az üres ládára teszek egy egész blokkot (amelytől a láda egyébként nem nyitható), majd ezután teszek blokkot a tölcsérbe, a blokk ugyanúgy áttöltődik a ládába, de a komparátor nem ad jelet, hiába van a ládában elem.
Ha az egész blokkot leütöm a láda tetejéről, a komparátor továbbra sem látja, mi van a ládában.
Ha kinyitom, majd becsukom a láda tetejét, a komparátor akkor veszi észre, hogy van vmi a ládában.
![2020-03-08_22 43 25](https://user-images.githubusercontent.com/61683937/76171695-68d10300-618e-11ea-8c9d-f4c1c8f93ff4.png)
![2020-03-08_22 43 54](https://user-images.githubusercontent.com/61683937/76171696-7090a780-618e-11ea-8a94-1eb79c430ccc.png)

**Comment by hanjocraft** [comment]
Még annyit pontosítanék, hogy újabb próbálkozáskor a blokk leütése elég volt arra, hogy a comparátor észrevegye a láda nemüres állapotát és jelet adjon...

**Comment by andris155** [comment]
Ez a játék hibája. Ha még nincs jelentve, akkor a https://bugs.mojang.com/ oldalon tudod angolul jelenteni.
