### ISSUE TITLE
Új szabályzati pontok

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#3447]
**Szerver**: Összes
5. Felhasználók főponthoz:

5.8 Amennyiben új karaktert szeretnél használni, jelezd azt egy Adminnak! A karakterváltásról Neked kell gondoskodni. Rangot és különböző, már elért tulajdonságokat (McMMO, Slimefun, szavazói pont, levédésblokk) átadni nem áll módunkban. A régi, már nem használt neved pedig tiltásra kerül, az 5.7 pont miatt.

7. Támogatók főponthoz:

7.7 Az OCD-ből keletkező károkért nem tudunk felelősséget vállalni! Amennyiben az OCD illegális úton került hozzád, kihatással lesz a további játékmenetedre. Kerüld a bajt! Maradj becsületes!

**Comment by andris155** [comment]
Hozzáadtam ezeket, meg javítottam elég sok helyesírási hibát a meglévőkben. A pluginok és konfigokkal kapcsolatos kikérés tiltásost pedig töröltem. A plugin lista részemről publikus.  A konfigok sem titkosak, de ott kiadni nem nagyon adok semmit, viszont szívesen segítek valakinek ha kell ezzel kapcsolatban.

**Comment by andris155** [comment]
https://www.oldcrafters.net/szabalyok/
