### ISSUE TITLE
Survival -> Savsziget átlépés

### ISSUE THREAD

**Issue by maryhonaly** [andris155/TheOld-Crafters#3449]
1.15, survival & savsziget

Amennyiben átlépés előtt Old itemek vannak a karakteren, amik plusz életet adnak, ill. páncélt, ha /savsziget paranccsal megyünk egyikről a másik szerverre, az életek helye ottmarad, illetve a páncélt úgy érti, mintha rajtam lenne. Videó: (jelszavamat kivágtam)

https://youtu.be/JNunZMOwPOQ

**Comment by andris155** [comment]
Kérlek legközelebb állítsd angolra a játékot ezekhez a videókhoz. A fejlesztők nem tudnak magyarul általában.

**Comment by andris155** [comment]
Szerintem ezt nem nagyon tudják javítani sajnos.
