### ISSUE TITLE
SkinRestorer

### ISSUE THREAD

**Issue by HELLCATGHOST** [andris155/TheOld-Crafters#345]
Szia Andris! Minap "visszatérésem" közben észrevettem hogy a /clearskin parancs nem működik,lehet direkt,lehet nem.Gondoltam szólok.
-HELLCAT

**Comment by andris155** [comment]
Szia

**Comment by andris155** [comment]
Elvileg már nincs benne a pluginban, de ez nem olyan nagy hiba.
