### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by Niccolettie** [andris155/TheOld-Crafters#3450]
Muszáj discordra ez a telefonszámos hitelesítő? Nem igazán szeretném mindenhova beírkálni a telefonszámom, főleg hogy ki tudja ki fér hozzá az ilyen adatokhoz és milyen felhasználásra kerülhet a későbbiekben. Kellemetlen, mert ma is survival szerveren egy Ramirez220 nevű kis takony buzizta a szerver tulaját, meg anyázott mindenkinek meg káromkodott, és nem tudtam senkinek szólni discordon vagy esetleg segítséget kérni bármelyik szobában...

**Comment by andris155** [comment]
Muszáj

**Comment by Niccolettie** [comment]
Oké, akkor a kérdésem annyi, hogy csak és kizárólag Te férsz hozzá a telefonszámokhoz? :).

**Comment by andris155** [comment]
Csak a discord fér hozzá szerintem. Senki más.

**Comment by Niccolettie** [comment]
Köszönöm.
