### ISSUE TITLE
Savsziget - Withercsonti hiány (?)

### ISSUE THREAD

**Issue by poma123** [andris155/TheOld-Crafters#3452]
Egy játékos azt mondja, kell neki wither csonti egy küldihez, de ugye sehonnan nem lehet szerezni.

**Szerver**: Savsziget

**Comment by MrZero1** [comment]
A spawneres ládában van, illetve szeretnénk majd az egyedi receptekkel csinálni tojást.

**Comment by MrZero1** [comment]
Esetleg egyszeri küldetés adhatna 1 tojást?

**Comment by poma123** [comment]
Ez meg lett oldva Sweet közbenjárásával ugye?

**Comment by MrZero1** [comment]
Ugye. :D
