### ISSUE TITLE
Savsziget - Obszidián recept

### ISSUE THREAD

**Issue by poma123** [andris155/TheOld-Crafters#3453]
Páran azt mondják drága az obszi recept. Én nem nagyon tudom eldönteni :C 

![image](https://user-images.githubusercontent.com/25465545/76699092-35203c80-66aa-11ea-94c8-11d3e65dafc4.png)
![image](https://user-images.githubusercontent.com/25465545/76699097-3baeb400-66aa-11ea-9ed2-52f6102e09ac.png)
![image](https://user-images.githubusercontent.com/25465545/76699100-4701df80-66aa-11ea-86cd-36bda9731965.png)

**Szerver**: Savsziget

**Comment by MrZero1** [comment]
A parázs, ami talán drágább, de mivel a sima víz+láva opcióval is lehet csinálni obszit.

**Comment by MrZero1** [comment]
Raktam be a magmablokkra is receptet amúgy
