### ISSUE TITLE
Nem spawnolnak mobok a szigeten

### ISSUE THREAD

**Issue by poma123** [andris155/TheOld-Crafters#3454]
Valamiért egyáltalán nem spawnolnak állatok. Mindenhol engedélyezve van. (konfig, mv modify, gamerule, acid settings, sziget beállítások)

**Szerver**: Savsziget

**Comment by andris155** [comment]
Eddig spawn-oltak, vagy mikortól nem?

**Comment by poma123** [comment]
Erről nincs információ.

**Comment by MrZero1** [comment]
Elvileg 1.15 óta nem spawnolnak neki

**Comment by MrZero1** [comment]
Almacsutka jelezte amúgy, miatta lett nyitva ez is.

**Comment by andris155** [comment]
Az alap warm_ocean biome-n nem is fognak. A biome állítás után működik a mob spawn.

**Comment by andris155** [comment]
<img width="660" alt="Capture" src="https://user-images.githubusercontent.com/8324198/77237935-83629d80-6bcc-11ea-86d8-49f854b083a5.PNG">

**Comment by andris155** [comment]
![2020-03-21_23 34 25](https://user-images.githubusercontent.com/8324198/77237940-8d849c00-6bcc-11ea-8e7b-0c79f8104213.png)

**Comment by andris155** [comment]
A plains biome-n jól spawnolnak az állatok.

**Comment by andris155** [comment]
@poma123 a spawn-limits beállításokon kérlek ne módosíts. Alapból túl magasra van állítva. Nem véletlen van az optimális értékre állítva.
