### ISSUE TITLE
Alvás plugin

### ISSUE THREAD

**Issue by maryhonaly** [andris155/TheOld-Crafters#3456]
1.15, Savsziget, alvó plugin:

Az eddigihez képest mindössze annyi változott, hogy nem írja ki, hogy hány főre van még szükség, az éjszaka felgyorsításához. Teszteltük, 4 embertől indul el. 

Az eddig jól megszokott kiírás hiányzik, mert így csak feleslegesen fekszenek az ágyban, nem lehet tudni, hogy ki alszik vagy ki nem, illetve hogy hány főre van még szükség.

**Comment by maryhonaly** [comment]
Módosítanám:
Ugyan ez a helyzet survivalon is. Nem lehet tudni, hogy érdemes-e az ágyban feküdni és pazarolni az időt, vagy sem.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by MrZero1** [comment]
👍

**Comment by andris155** [comment]
Visszaraktam a régit. Fogalmam sincs miért nem akarta írni a chat üzeneteket.
