### ISSUE TITLE
Sf magnet kraftolás nem működik

### ISSUE THREAD

**Issue by kBalix** [andris155/TheOld-Crafters#3457]
**Szerver**: Survival

Amikor beteszem a slimefunos smeltery - be helyesen a receptet, nem csinál magnetet, csak a dustokat égeti ki.

**Comment by kBalix** [comment]
![IMG_20200318_150740](https://user-images.githubusercontent.com/59265474/76969212-5e4f0000-692a-11ea-9083-4f5548c8e350.jpg)
![IMG_20200318_150754](https://user-images.githubusercontent.com/59265474/76969227-6313b400-692a-11ea-9680-07e18da9b4ff.jpg)

**Comment by skrisz0101** [comment]
És is próbáltam, nekem se ment
