### ISSUE TITLE
Survival - Farm

### ISSUE THREAD

**Issue by KingDeadZ** [andris155/TheOld-Crafters#3458]
A farmon a soulbound cuccok tiltva vannak, tehát pl ha sneakelek (elytrával ez fix) akkor beszól a chaten, szintén ha ütök soulbound karddal.

ui: A /tpaccept parancshoz nincs jog, a tpahoz nem tudom hogy van-e.

**Comment by andris155** [comment]
Vedd le ott, és akkor nem ír chaten semmit.
