### ISSUE TITLE
Customcrafting tudáskönyv

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#3459]
**Szerver**: Savsziget

Lehetne az, hogy aki új játékosként fellép Savra, az kap egy Tudás könyve tárgyat? Az egyedi receptekhez kell ugye.

**Comment by andris155** [comment]
Az EssentialsX nem támogatja a tag-eket, amik azon a könyvön vannak.
Esetleg @poma123 megtudja oldani, hogyha rányom Kezdés npc-re, akkor adja meg nekik a /customcrafting give játékosnév customcrafting:knowledge_book paranccsal.

**Comment by poma123** [comment]
Mondjuk az jó ötlet :D

**Comment by poma123** [comment]
kész
