### ISSUE TITLE
Craftbook <-> Chestshop bug

### ISSUE THREAD

**Issue by brtamas0** [andris155/TheOld-Crafters#346]
A csőrenszerrel a ládaboltból ki lehet szívni a cuccot és újra eladni. kiszív elad a chestshopnak kiszív elad...
És így bárkit ki lehet fosztani. játékosnevem: brtamas

**Comment by andris155** [comment]
Írtam a plugin fejlesztőnek ezzel kapcsolatban.

**Comment by andris155** [comment]
Javítva
require-sign: true
