### ISSUE TITLE
PlotSquared block-ignition true flag nem működik összekötött telkeknél

### ISSUE THREAD

**Issue by maryhonaly** [andris155/TheOld-Crafters#3461]
1.15, Survival, telekvilág. 

Valami sf dologhoz automata tűzgyújtás a legcélszerűbb, ehhez egy adagolóval tesznek le automata módon tüzet és kovakőésacél segítségével. Ez vadonban minden további nélkül működik, viszont telekvilágban nem. Minden telken egységesen rajta van a tűzgyújtást tiltó flag, de néhol megy, néhol meg nem. 
<img width="617" alt="Képernyőfotó 2020-03-18 - 22 13 44" src="https://user-images.githubusercontent.com/53797506/77008063-bf47f980-6965-11ea-9cbd-70a70f1b15fb.png">

**Comment by andris155** [comment]
Az pont az engedélyezése. Az összekötött telkeknél nem megy gondolom.

**Comment by andris155** [comment]
Ameddig nincs javítva, addig a fő telken működik, amihez kötve lettek a telkek.

**Comment by andris155** [comment]
Egyszer valamikor a jövőben talán javítják. A hibáról tudnak.
