### ISSUE TITLE
GriefPrevention blokk növekedés rangok alapján

### ISSUE THREAD

**Issue by Tibo96** [andris155/TheOld-Crafters#3462]
**Tisztelt andris155**
A levédéssel kapcsolatban lenne egy fejlesztési ötletem.
-_Az óránként kapott levédési területet kicsit meglehetne növelni, nagyon lassan gyűlik össze, tudom lehet venni is de rámenne a vagyonunk. :)_
-_És az ötletem pedig az lenne, hogy rang által több levédési terület járna óránként, csak úgy mint a pénznél,rangtól felfelé növekedne a kapott terület mennyisége_.
**Üdvözlettel: Tibo**

**Comment by MrZero1** [comment]
A második részével egyet tudnék érteni, de talán nincs rá mód, legalábbis amikor lecseréltük a levédést, akkor azt mondta Andris, hogy nem megoldható, hogy ranggal több levédés legyen.

**Comment by KingDeadZ** [comment]
Esetleg az megoldható, hogy ranggal olcsóbb legyen a levédésblock?

**Comment by andris155** [comment]
Már nincs messze a hétvége. Akkor érek rá az ötletekkel majd foglalkozni.

**Comment by andris155** [comment]
Elvileg lehet rangonként állítani a levédés blokk növekedést és max levédés blokkot.
De @MrZero1 segítsége kellene ehhez, hogy melyik rangban mennyi legyen ez.

**Comment by MrZero1** [comment]
Alapból van most 200k.

Tag+: 220k
VIP: 280k
Elit: 300k
Prémium: 350k 
Old: 400k

De csak javaslat.

**Comment by skrisz0101** [comment]
Én az első részével is egyetértek

**Comment by MrZero1** [comment]
Lejárat után, tehát ha valakinek lejár a rangja, utána mennyi marad? 200k? És amit már levédett, az megmarad? Vagy hogy néz ki?

**Comment by andris155** [comment]
Gondolom meg.

**Comment by andris155** [comment]
És a növekedés mennyi legyen? Alapból ugye 100 blokkot ad óránként.

**Comment by MrZero1** [comment]
Az szerintem maradhat egységesen 100 blokk.

**Comment by Tibo96** [comment]
Egy minimálisan az nem emelkedhetne egységesen ? Pl. 50 Block-al többet
kapna mindenki? Kezdésnél nagyon nehezen gyülik ám össze mire egy
tisztességes területet lefoglaljon valaki.
(Csak egy ötlet) :)

MrZero1 <notifications@github.com> ezt írta (időpont: 2020. márc. 22., Vas
16:49):

**Comment by skrisz0101** [comment]
Tényleg nagyon lassan tudnak levédéshez jutni a kezdők

**Comment by MrZero1** [comment]
Akkor max a kezdőknek vagy mindenkinek lehetne 150

**Comment by andris155** [comment]
A növekedést átírtam 150-re, viszont ahogy néztem a vásárlásra nem érvényes ez a limit. Tehát, ha valaki vesz védési blokkot több millió védési blokkja is lehet.
Ez a limit csak arra vonatkozik, amit ingyen kap a játékos játékidőért.
Így is növeljem rangonként ezeket?

**Comment by MrZero1** [comment]
Nem gond, ha nincs limit a vásárlásra. Legalább eltudják költeni a pénzüket. Mennyi is most 1 blokk? 150$? Esetleg ezt lehetne emelni 200$-ra, bár nem kompenzálja, de nem baj.  
A limitek úgy jók szerintem.

**Comment by skrisz0101** [comment]
Zéró a 150 így is sok, ne legyen emelve szerintem. Nem hinném hogy milliókat akarnak költeni levédésre
(vagy több 10 milliót) 
Pl: 300k blokk 150$ért az 45milla kb
Senki se fog ennyit farmolni a levédés miatt

**Comment by andris155** [comment]
Beállítva.
