### ISSUE TITLE
Savsziget küldetés

### ISSUE THREAD

**Issue by Niccolettie** [andris155/TheOld-Crafters#3465]
Szakértő szekció - Vaskor
"Készíts vas eszközöket és páncélt!" Minden vas eszköz és páncél is az inventorymban van, mégis azt írja nincs elég vascsizma nálam, miközben ott az egy darab az inventorymban ami kell....

**Comment by andris155** [comment]
<img width="363" alt="Capture" src="https://user-images.githubusercontent.com/8324198/77225651-2d144100-6b71-11ea-9f75-984bdabb6e2b.PNG">
Nekem tökéletesen működött.
Ha ládából van valamelyik, akkor lehet az probléma, hogy az név:számmal van. Sajnos ez a ládás plugin már elég elavult. Ha kell becserélem neked egy jóra, ha ez a probléma.

**Comment by Niccolettie** [comment]
Köszi a tippet, lecraftoltam az egész szettet, és most elfogadta a küldetés! :)
