### ISSUE TITLE
Plot - idő beállítása 

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#3466]
**Szerver**: szurvi
Kipróbáltam sok parancsot, egyikkel se megy

**Comment by andris155** [comment]
/p setflag add time tick érték
Tökéletesen működik, de a ptime lehet bezavarja.

**Comment by MrZero1** [comment]
Hogy van a weather és a time parancs pontosan? Sehogy sem akar menni

**Comment by andris155** [comment]
/p setflag add weather sun vagy rain
