### ISSUE TITLE
BentoBox Challenges fordítás

### ISSUE THREAD

**Issue by Niccolettie** [andris155/TheOld-Crafters#3468]
"néhány macska" helyett inkább "néhány róka", mert fox_spawner_egg van jutalomként írva :) ráférne egy frissítés a fordításra, mert valahol angol a leírás, valahol magyar, eléggé "hunglish" így :D 
![2020-03-21_17 07 48](https://user-images.githubusercontent.com/48986609/77230744-a6725a80-6b96-11ea-925d-c54e0f281794.png)

**Comment by andris155** [comment]
Nekem ezekre nem igazán van időm, de mindegyik fent van GitHub-on. Ha valaki ráér tud segíteni a frodításban.

**Comment by MrZero1** [comment]
@Niccolettie  ha van kedved lefordítani/átnézni teljesen, OCD-t tudok adni érte.:D

**Comment by Niccolettie** [comment]
@MrZero1 Hétfőn elkezdem és megcsinálom! :D

**Comment by andris155** [comment]
átírtam

**Comment by andris155** [comment]
A nagybetűkkel írottak nem fordíthatóak tudtommal.

**Comment by Niccolettie** [comment]
Igen most már én is tudom.
