### ISSUE TITLE
Játékos limit

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#3469]
**Szerver**: Survival vagy mindegyik

Lehetne jog arra egy rangtól (pl Prémium), hogy ha tele van a szerver, akkor feltudjon menni. (stumper ötlete)

(staffoknak is lehetne rá jog, ha nincs)

**Comment by skrisz0101** [comment]
Vagy eltörölni ezt a 40 fős limittlet, mert sokszor sokat kell várni 🙄☹️

**Comment by MrZero1** [comment]
Szerintem a 40 fő jó, rendes suliidőben nincs ennyi ember. Nyáron meg majd fentebb lesz rakva/el lesz törölve.

**Comment by KingDeadZ** [comment]
Szerintem elittől is lehetne simán, tekintve hogy azért is fizetni kell.

**Comment by skrisz0101** [comment]
De az miért volt eddig baj h 60 volt a limit vagymennyi? :/
Ok hogy suliidőben nincsenek ennyien, ez igaz, de kitudja meddig tart ez

**Comment by andris155** [comment]
Azért van limit, mert kb. ennyit bír el a szerver. Mivel ez a Java Edition egy magot tud normálisan kihasználni a 8 fizikai magból.

**Comment by andris155** [comment]
Hozzáadtam a prémiumhoz a jogot.
