### ISSUE TITLE
Mcmmo Javítás hiba

### ISSUE THREAD

**Issue by Kaziki01** [andris155/TheOld-Crafters#347]
Helló
A hiba amit leírok nem túl komoly de azért zavaró lehet.
Az Mcmmo plugin, javítás képességénél ha eléred az 50-es szintet, meg tudod javítani a sérült gyémánt felszerelést. Ami persze működik a tárgyat javítja, DE minden enchantot eltüntet róla. Szóval kb olyan mintha kidobnád a tárgyat a kukába.

**Comment by andris155** [comment]
Helló!
Ez szerintem direkt van így.
