### ISSUE TITLE
Savsziget - slime

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#3470]
**Szerver**: Sav

Javaslatként, kérésként jött: valami megoldás, slime chunk keresésre, ha már nincs vödör. :D

**Comment by andris155** [comment]
A seed alapján lehet slime chunk-ot nézni egy weboldalon:
https://www.chunkbase.com/apps/slime-finder
De ez nem lenne túl nagy könnyítés így? Az alap játékban sem lehet ezt túlélőben megnézni csalások nélkül.

**Comment by andris155** [comment]
Akár azt is meglehetne oldani, hogy valamelyik rangtól meglehessen nézni melyik slime chunk és melyik nem.
https://www.spigotmc.org/resources/slime-chunk-lite.42799/

**Comment by andris155** [comment]
@MrZero1

**Comment by MrZero1** [comment]
Eléggé OP ez a dolog, más megoldás nincs? Ha nincs, akkor ezt belehetne rakni bizonyos rangtól. Old, vagy max Elit

**Comment by MrZero1** [comment]
Elit rangtól legyen akkor ez.

**Comment by andris155** [comment]
A blokk vásárlás?

**Comment by andris155** [comment]
Szerintem ennek így nincs értelme. A tagoknak is megtudnák nézni.

**Comment by andris155** [comment]
Túlságosan nagy könnyítés szerintem a slime chunk-ok megnézhetősége.
