### ISSUE TITLE
Spawner - hibás információ 

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#3471]
![Screenshot_20200323_220955_com android chrome](https://user-images.githubusercontent.com/29951969/77363508-247b6080-6d53-11ea-8d9a-45a214299769.jpg)
Ha kiütik a spawnert, nem kell már megjavítani. Az csak a generált spawnerekre vonatkozik. A javítottra (mint amilyet vesznek), nem.

**Comment by andris155** [comment]
Javítva. 508 OCD
