### ISSUE TITLE
Survival

### ISSUE THREAD

**Issue by KingDeadZ** [andris155/TheOld-Crafters#3473]
vadon2, skrisz területén lévő egyik telekre (amit szétosztott ugye azzal a subdivideclaimmal v miaz)
oda akartam tpzni, és megállt a szerver nekem szinte. a mobok megálltak, ütni se tudtam őket, blockot se tudtam törni a saját levédésemen, mert visszarakta. ha ő akart oda tpahere-ztetni akkor is ez volt. közben írta pirossal a chaten ha próbáltam írni hogy "Cannot send message"

Amikor nagyjából negyedjére újraléptem a szeróra (az újralépés megoldja) MrZero akart oda TPzni skriszhez, de ez azzal zárult hogy neki is beadta ezt, amit nekem is.

**Comment by andris155** [comment]
Erre szerintem nincs megoldás.
Amit lehet már javítottak ezzel kapcsolatban.
https://github.com/PaperMC/Paper/issues/2803
