### ISSUE TITLE
Hg spectate

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#3475]
**Szerver**: szurvi. 
Szerintem tök jó lenne egy olyan megoldás mint mobaénánál. 
Bárki bármelyik arénát tudja nézni felülről. 
+az is tudja nézni, aki meghalt hg-n

+: smaragdot ki lehetne venni a ládákból

**Comment by andris155** [comment]
Nem nagyon lehet megoldani, mivel ezek az arénák általában elég nagyok. Spectator módban pedig szerintem nem lenne szerencsés, mivel kitudnád nézni a láda helyek többségét.
