### ISSUE TITLE
,,figurák"

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#3476]
**Szerver**: mindenhol 
Ez a páncélállvány szerkesztő egy tök jó plugin. Szerintem minden warpra mehetne, mert ezzel mindent fel lehet dobni. 
Hangulatosabb

**Comment by poma123** [comment]
Survi ládáknál lett téve pár :)

**Comment by MrZero1** [comment]
Nekem a max tudásom ezzel annyi, hogy csinálok egy kicsi szellemet.

**Comment by andris155** [comment]
Szerintem ahova van értelme fogunk rakni. De azért túlzásba sem érdemes vinni, mert szerintem az már az FPS kárára megy.
