### ISSUE TITLE
HónapStaffja optimalizáció

### ISSUE THREAD

**Issue by poma123** [andris155/TheOld-Crafters#3478]

**Comment by andris155** [comment]
Kérlek nézd át a Paper api-t és használd ha van olyan dolog, amire van.

**Comment by andris155** [comment]
https://papermc.io/javadocs/paper/1.15/overview-summary.html

**Comment by poma123** [comment]
Kész
_A textúráját a fejeknek a szavazás időtartama alatt (pár nap) lementi akkor, hogyha még nem lett lementve. Tehát az első játékos aki megnyitja, és ha nincs lementve a GUI-ban lévő staffok fejének textúrája, lementi, és onnantól az elmentettet használja, nem kéri le újra._
