### ISSUE TITLE
Skinek

### ISSUE THREAD

**Issue by poma123** [andris155/TheOld-Crafters#3480]
Valamiért történt valami a skin pluginnal, nem tölti be az eredetis skineket, illetve nincs joga senkinek a /skin parancsra, aki vásárolt jogot hozzá.

**Comment by andris155** [comment]
Töröltem az adatbázist, mivel mindenki panaszkodott az elavult skinekre. Holnap majd betölt újra a plugin.

**Comment by andris155** [comment]
Javítva
