### ISSUE TITLE
Savsziget - vip sziget (ötlet)

### ISSUE THREAD

**Issue by Niccolettie** [andris155/TheOld-Crafters#3481]
Vip szigetre be lehetne rakni sárkányleheletet az "Értékek" NPC-hez :)

**Comment by MrZero1** [comment]
Hamarosan új kezdőhely lesz, ott lesz egy új, részletesebb VIP sziget majd.:D

**Comment by mr00000** [comment]
kaka pisi 70/5000
Für den NPC "Values" könnte auf Vip Island ein Drachenatem gesetzt werden :)

**Comment by MrZero1** [comment]
Addig lezárom. :D
