### ISSUE TITLE
Tűz a ploton

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#3482]
**Szerver**: Survival

Atr0n0X jelentette, hogy nem lehet/nem tud tüzet gyűjtani a plot telkeken.
(Nekem megy, de nyilván OP meg ilyenek miatt)

**Comment by Niccolettie** [comment]
#3461 szerintem ez is hasonló

**Comment by andris155** [comment]
A tűzgyújtás megy, de a kidobó és entitások nem tudnak az összekötött telkeken. Már jelentett hiba.
