### ISSUE TITLE
Savsziget - chestsort

### ISSUE THREAD

**Issue by Niccolettie** [andris155/TheOld-Crafters#3483]
A chestsort parancs nem működik :( :( :( 👎 
_Ismeretlen parancs_

**Comment by andris155** [comment]
Megszűnt, mivel már nem fejlesztik a bővítményt.

**Comment by andris155** [comment]
Ha van mod 1.15.2-re ilyen azt nyugodtan használhatod.

**Comment by Niccolettie** [comment]
Nem értem egyébként már rég 1.15.2 a szerver, és 1 hete még teljesen jól működött :( annak ellenére hogy 1.14-es verzió .. egyébként, most utána néztem, és kommenteltek is spigotmc-n:

Xslushedx
Xslushedx  Version: 7.1
Works with Paper 1.15.2 ! No errors or bugs found.
Thank you for this greate plugin and keep it up :-)

Felix2607  Version: 7.1
Works as it should, haven't use all the features. Would comeback if I run into issues. Thank you.
Mar 22, 2020

Tehát elvileg még mindig működnie kéne.
