### ISSUE TITLE
Inventory

### ISSUE THREAD

**Issue by HighmanHuge** [andris155/TheOld-Crafters#3485]
Tök jó lenne, ha tudnánk bizonyos itemeket ignorálni, pl bányászás közben ne vegye fel automatikusan a zúzottkövet / akármit amit nem szeretnénk, nem tudom hogy létezik e ilyen plugin, de ha lennétek olyan ügyik hogy csináltok egy olyan parancsot hogy "ignore cobblestone" attól többeknek örömkönnyek hullanának az arcán :)

**Szerver**:

**Comment by Niccolettie** [comment]
Én azt szoktam csinálni hogy kitöltöm az invemet azokkal az itemekkel amiket fel akarok szedni, pl gyémánt/vas/arany/stb és így a zúzottkövet nem veszem fel, mert nincs hely az invemben :3 200iq megoldásom :D

**Comment by HighmanHuge** [comment]
Én is úgy szoktam, 145+ az iq-m ne félts.
Egyszerűbb lenne a az ignore-os.

**Comment by skrisz0101** [comment]
Egyszerű a megoldás. Adjátok el a követ a /pwarp skrisz01-en.
#hirdetés#pénz

**Comment by andris155** [comment]
@poma123 nem biztos, hogy jó ötlet egy sokadik plugint rakni erre is. Most már azt kellene inkább kitalálni, hogy mi nem kell.

**Comment by poma123** [comment]
Nem a jelenlegi szerverekre lenne. :D

**Comment by andris155** [comment]
Ha ilyesmit csinálsz kérlek a Paper féle pickup api-t használd. Úgy tudom erre is van és az sokkal gyorsabb.
