### ISSUE TITLE
Ocelot / macska telken

### ISSUE THREAD

**Issue by maryhonaly** [andris155/TheOld-Crafters#3486]
1.15.2, Survival, telekvilág

A világban használni kívánt ocelot/macska tojások nem működnek.
Ha adagolóval próbáljuk, a tojást elhasználja, az állat viszont nem jelenik meg.
Amennyiben vadonban teszi le, petnek befogja, majd elengedi a telken, az állat szublimál, eltűnik.

**Comment by andris155** [comment]
Direkt van tiltva, mert nagyon sok idéződik ott az alap biome miatt. Nem lehet engedélyezni csak az idéző tojást. A spawner-t tudtam csak megoldani.
