### ISSUE TITLE
SF kreában

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#3487]
**Szerver**: Survi

Nem tudom, hiba e, de kreatívban lelehet hívni az SF könyvet.

**Comment by andris155** [comment]
Ne lehessen?

**Comment by MrZero1** [comment]
Nincs értelme szerintem :D De ha direkt van engedélyezve, akkor nem tudom

**Comment by andris155** [comment]
Szerintem felesleges még a parancsot is tiltani hozzá. Úgy sem tudnak vele mit kezdeni kreatívban ha lekérik.
