### ISSUE TITLE
Nemtudom bug e

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#3488]
**Szerver**: Ezzel lehet látni a barlangokat. Szerintem alap mc-s bug

![kép](https://user-images.githubusercontent.com/29709854/78389376-eac41880-75e2-11ea-8b64-dd71b27fc450.png)
![kép](https://user-images.githubusercontent.com/29709854/78389394-f283bd00-75e2-11ea-8a7d-0e8133a77aa5.png)

**Comment by andris155** [comment]
Vanilla hiba. Majd gondolom a következő verzió megoldja.
