### ISSUE TITLE
Tábla addolás

### ISSUE THREAD

**Issue by Gabello13** [andris155/TheOld-Crafters#3489]
a Survival szerverén a bolt pluginnal lehet táblát addolni 1. sor Név 2. sor darabszám 3. sor pénzmennyiség utolsó sor Pl.: Asd és ledobja a táblát egy meg kapod surivba

**Comment by andris155** [comment]
Annyi sok hiba van, amit nem jelent senki, de ezt már 3x is jelentették. Mint az előzőekben is írtam a tábla nem túl értékes. Már írtam a fejlesztőnek ezzel kapcsolatban nem nagyon lett rá megoldás. Ettől függetlenül köszönjük a jelentést.
