### ISSUE TITLE
Eltűnő elnevezett szörnyek levédett területről

### ISSUE THREAD

**Issue by SaltyUmbrella** [andris155/TheOld-Crafters#3490]
A cím sokat elmond, rendre eltűnnek a levédett területemről az elnevezett szörnyeim(pl: zombimalac), bármi ötlet mitől lehet ez? 
**Szerver**: survival

**Comment by SaltyUmbrella** [comment]
utóirat: mobspawnolás engedélyezve van

**Comment by andris155** [comment]
Minden szörnyre limit van. Mennyi van neked ebből?

**Comment by skrisz0101** [comment]
@andris155 olyat nem lehet hogy először azokat tűntesse el a moblimit amin nincs cédula?

**Comment by andris155** [comment]
A mob limit nem foglalkozik az elnevezett élőlényekkel. Valószínűleg más miatt tűnnek el.

**Comment by andris155** [comment]
Nem tudom mitől tűnnek el.
