### ISSUE TITLE
Fordítás 

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#3491]
**Szerver**: ???2

A ???2 szerveren használt CB (😉) plugint lelehetne fordítani, vagy fordíttatni játékossal, OCD-ért?

**Comment by andris155** [comment]
4 sor talán a fordítása xD

**Comment by andris155** [comment]
A BentoBox plugin fordítását használja nagyrészt. De az pedig több ezer sor.

**Comment by MrZero1** [comment]
Hát, amit lelehet fordítani, fordíttassuk le.:D

**Comment by andris155** [comment]
https://github.com/andris155/TheOld-Crafters/tree/master/Ford%C3%ADt%C3%A1sok/BentoBox/locales/BentoBox

**Comment by Niccolettie** [comment]
Na, most már tényleg elkezdem lefordítani hétfőn!

**Comment by andris155** [comment]
Arra figyelj, hogy frissült a fordítás fájl.
https://github.com/andris155/TheOld-Crafters/commit/172d6ef0dfd2cd7fbccc19496bbb6a027581623d

**Comment by andris155** [comment]
https://github.com/andris155/TheOld-Crafters/commit/4e4b0ab9f8fb86c314fbdd62fd6c3fcf3e6c7611

**Comment by mr00000** [comment]
kakaplugin v1.0 by vodobaba vanbene automat fordito is nezetek meghttps://github.com/andris155/TheOld-Crafters/pull/3517

**Comment by Lagire** [comment]
Amennyiben lehetséges, átvenném a fordítás megmaradt részét.

**Comment by Niccolettie** [comment]
Lementettem az 1400+ sort és amikor kész teljesen, akkor szoktam átküldeni, tehát nem igazán tudod átvenni, mert amit elkezdek azt szeretem befejezni :)

**Comment by Niccolettie** [comment]
Elküldtem e-mailben :*

**Comment by andris155** [comment]
Amint lesz időm majd átnézem. Köszönjük.

**Comment by andris155** [comment]
Bekerült. Lehet tesztelni a szerveren. Köszönjük a fordítást.
