### ISSUE TITLE
explo shovel

### ISSUE THREAD

**Issue by stumperkicsi** [andris155/TheOld-Crafters#3492]
surv

Megint nem megy az explo shovel.
 Egyszer megy egyszer nem mint a mesékben :DD

**Comment by andris155** [comment]
Holnap teszteld le kérlek újra.

**Comment by stumperkicsi** [comment]
probaltuk volna skrisz01 el de elvileg ki is lett véve

**Comment by andris155** [comment]
poma valamiért letilotta.
