### ISSUE TITLE
Chestsort frissítése Niccolettie kedvéért

### ISSUE THREAD

**Issue by andris155** [andris155/TheOld-Crafters#3493]
**Szerver**: AcidIsland, Survival

**Comment by Niccolettie** [comment]
Úristen, ezt nem mondod komolyan? 😍  IMÁDLAK, KÖSZÖNÖM! ❤️  nincs is jobb érzés, amikor felnézek githubra és ez fogad 😍

**Comment by skrisz0101** [comment]
Lol xd

**Comment by andris155** [comment]
kész

**Comment by Niccolettie** [comment]
Andris, nagyon király vagy! :D 👑 😘
