### ISSUE TITLE
Falon Át Buggolás

### ISSUE THREAD

**Issue by Gabello13** [andris155/TheOld-Crafters#3494]
Szerintem ez egy alap MC-s bugg
![2020-04-04_01 50 31](https://user-images.githubusercontent.com/62840492/78413336-2f69a700-7617-11ea-9038-80c1bbb9a904.png)
![2020-04-04_01 50 19](https://user-images.githubusercontent.com/62840492/78413337-309ad400-7617-11ea-8aa5-626a6aceae58.png)

így át lehet buggolni a falakon

**Comment by andris155** [comment]
Valószínűleg igen. A Mojang jira oldalán tudod jelenteni angolul, ha még nincs.
https://bugs.mojang.com/secure/Dashboard.jspa
