### ISSUE TITLE
Savsziget - mobstack

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#3496]
**Szerver**: Savsziget

Hasznos lenne, talán nem lenne ennyire lagg.

**Comment by andris155** [comment]
Rontana csak a helyzeten. Semmi értelme ennek a megoldásnak.

**Comment by andris155** [comment]
Azért rontana a helyzeten, mert a stack-elt mobokat a memóriában tárolja a szerver így az nagyon gyorsan betelik.
