### ISSUE TITLE
Szabály

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#3499]
**Szerver**: Web
2. Játékmenet

2.14 Ne védd le a portálokat úgy, hogy ne tudja azt használni más játékos. Feleslegesen ne torlaszold el.

**Comment by poma123** [comment]
Egyébként néztem a griefprevention kódban hogy van valami védelem erre, visszarakja a portál másik végére vagy mit csinál

**Comment by andris155** [comment]
Azt hiszem ha kilép meg be, akkor igen van rá valami megoldása.

**Comment by MrZero1** [comment]
Eddig akos_ / sok4_ szórakozott ezzel, levédte direkt, mindenkiét, ma meg egy másik illető. Engem nem dobott vissza, ki sem tudtam lépni, semmit sem tudtam :D

**Comment by andris155** [comment]
Hozzáadtam.
