### ISSUE TITLE
PvPManager pro auto újraéledés bug

### ISSUE THREAD

**Issue by HUNgaryBoy** [andris155/TheOld-Crafters#35]
Skypvp Szerver:
Reconnectelős cuccmegtartós bug:
(Akkor használják,mikor kilökték őket...)
Meg kell várni még lejár a pvps idő,amég nem léphetsz ki,stb kilépsz,visszamész,megvárod még kidob a szerver (bejelentkezési időtúllépés) Visszamész,be login-olsz és a spawnon vagy minden cuccodal,ahellyet hogy kiestél volna,és meg kellet volna hogy halj.

**Comment by andris155** [comment]
Most is működik?
