### ISSUE TITLE
Cobblestone generator

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#3502]
**Szerver**:  Szurvi, slimefun
Szerencsére volt dugiban miner androidom, így tudtam craftolni 2-t. de mikor leteszem a 2.-at, leáll az 1. ha kiütöm a 2.-at, újra megy az 1. röviden: hiába raknék le 4654-t, csak 1 működne.
tipp hogy miért? először arra gondoltam hogy 1 chunkon egy mehet, szóval arrébb raktam kettő chunkkal, de úgy se működött.

Szerzés: Ugye tiltva van a miner android. az pedig kéne a crafthoz. arra gondoltam [Zeronak és pomának már mondtam], hogy lehetne esetleg a /warp beváltó-n egy falusi, aki egy normal android +electric motor-ért adna egy miner androidot [ugyanúgy tiltva lenne, így nem lehet használni, csak craftra cobblestone generatorhoz]. Alapból a craftja is az volt hogy normal android + electric motor +2gyémánt csákány ha jól emlékszem, szóval szerintem elfogadható :D

Azt meg azért kiemelném hogy a zúzottkő [végtelen mennyiségben] nagyon fontos a slimefunban 

Ja, és köszi puszi az új addonokat andris, de valaki megfejthetné a chest terminált mert rohadt nehéz xd 
@UDPSendToFailed térj vissza és magyarázd el köszi.

**Comment by andris155** [comment]
Szerintem majd ki lesz szedve, maximum később kerül vissza ha már jobban működik.

**Comment by mnbTOC** [comment]
Eskám. Van egy kedves mód. Amiben van ugyanez a rendszer (Applied energistics 2)
Ott hirtelen nemtudom hogy van. De itt (Figyelj itt jön elő a paraszt logika) ahogy láttam és olvastam az item leirását. Az összes ládádra raksz 1-1 input és output node-ot (Az input ne legyen olyan hogy csak az adott itemet húzza ki. Az osszes itemet engedd át rajta (kapcsold ki a whitelistet ugy mint a round Robin-t is kapcsold ki)) válasz nekik egy csatornát. Pl 15-ös. Akkor most van egy cargo managgered ami kapcsolatban van az összes ládán lévő input és output node-al. Akkor a cargo manager MELLÉ lerakod a CT input és CT output bust majd egy CT access panelt leraksz oda ahova akarsz (A cargo rendszeren belül ahol még elérni a cargo jele) és kész. Elvileg. De nemtudom. Lehet külön rendszer kell neki ugy hogy egy cargo manager és minden ládádra 1 input bus és egy Output bus majd az acces panel és ugyanugy connector node-al birod a jelet továbbhuzni. Egyszerű. A gépeden a legszarabb mc 1.15.2 szervert feltelepited. Berakod az sf plugint a CT addonnal és leteszteled (Én ezt fogom holnap csinálni)

**Comment by mnbTOC** [comment]
Na megvan a második tippem a jó. Sajnos.
Minden láda el kell legyen látva 1 import es 1 output bus-al de egyenlőre ne állj neki csinálni. Kérek egy angol videót ahol megmutatja majd valaki.

**Comment by mnbTOC** [comment]
Az addon oldalán ennyit írnak. "ChestTerminal is a Slimefun4 Addon that is heavily inspired by the famous mod Applied Energistics. It adds a Chest Terminal that you can hook up to a Cargo System to access all your items that are accessible through Cargo Nodes on the CT-Channel."

**Comment by andris155** [comment]
Ha valakinek sikerül megfejteni csinálhatna róla valami tutorial videót.

**Comment by andris155** [comment]
Zero és poma végül megoldotta?

**Comment by andris155** [comment]
@MrZero1, @poma123

**Comment by mnbTOC** [comment]
Mivel a mai nap folyamán megyek fel tesztelni egy angol gyerekkel az egészet. Ezért ha valaki megmondja hogyan bírom a laptopomra tükrözni az asztali gépemet akkor fekveszem az egészet egy videóba és felrakom yt-re

**Comment by mnbTOC** [comment]
@andris155 @skrisz0101 @MrZero1 @poma123

**Comment by andris155** [comment]
Windows 10 Pro verziónál a távoli asztali kapcsolattal a legegyszerűbb. Windows 10 home-nál pedig TeamViewer-rel.
De egyébként nem értem miért nem az asztali gépen veszed fel.

**Comment by andris155** [comment]
Felvételhez pedig az OBS kell megfelelő beállításokkal!!!
Alap beállításokkal gagyi lesz a videó minősége.

**Comment by mnbTOC** [comment]
Megvan hogyan működik (Egy nagy faszság szerintem az egész ahogy ki lett találva) de veszem a videót. Windows 10 alap rogzitője nem jo?

**Comment by mnbTOC** [comment]
Töltőm fel @andris155

**Comment by mnbTOC** [comment]
@skrisz0101 @andris155 @MrZero1 itt van a videómban hogy hogyan működik. Szerintem kicseszés hogy 17-es channelt csináltak és arra kell mindent kapcsolni..
https://youtube.com/watch?v=6_mdtpQY7zA

**Comment by skrisz0101** [comment]
igazából engem az izgat a legjobban hogy csak  cobblegeneratort tudok lerakni.
erre valami megoldás? xd

**Comment by mnbTOC** [comment]
Gőzöm sincs. Neten keress utána vagy várjál megérdeklődöm a DC szerveren.
Osszeraktam a CT rendszert survin. Egyszerűen. Iszonyú mennyiségű anyagot bír tárolni. @andris155 a Barrels addon nagyon jól jönne a CT mellé.

**Comment by mnbTOC** [comment]
Na hát a Cobblestone generátornak utánakérdeztem. Nem te vagy az első.
Vagy levan limitálva alapból 1 generator/player-re vagy bug.

**Comment by andris155** [comment]
Ha valaki tud angolul itt lehet jelenteni a Cobblestone generator hibákat.
https://github.com/Sfiguz7/ExtraTools/issues

**Comment by andris155** [comment]
De ha leírjátok pontosan röviden, hogy mi a hiba, akkor megírhatom én is.

**Comment by mnbTOC** [comment]
@skrisz0101, Igazábol amugy @andris155 ha jól értelmezem hogy akárhány Cobblestone Generátort rak le akkor is csak 1 működik.

**Comment by andris155** [comment]
A Barrels sajnos hibás, így nem fog bekerülni.
https://github.com/John000708/Barrels/issues/21

**Comment by mnbTOC** [comment]
Kár. Esetleg valami plugin ami nagyobb ládát elérhetővé tenne jó lenne mivel a CT rendszeren alapitom én is ki az új bázisom ami hát. Iszonyu sok láda lesz

**Comment by skrisz0101** [comment]
Igen, annyi a lényeg hogy csak 1 cobble generátor megy, hiába van letéve 2, 3, stb
@andris155

**Comment by andris155** [comment]
Nem sikerült reprodukálni a hibát. Nekem 3 is működik egyszerre.

**Comment by andris155** [comment]
<img width="463" alt="Capture" src="https://user-images.githubusercontent.com/8324198/79002526-f5d1f800-7b50-11ea-8c56-ec33670405c6.PNG">

**Comment by andris155** [comment]
![2020-04-10_17 30 15](https://user-images.githubusercontent.com/8324198/79002555-01252380-7b51-11ea-826a-86c9bf6f9f65.png)

**Comment by skrisz0101** [comment]
Bele is néztél hogy termel - e követ, vagy csak leraktad @andris155?

**Comment by andris155** [comment]
Nyilván bele is néztem. :D

**Comment by skrisz0101** [comment]
Akkor majd ha fent leszel ránézel az enyémre is? Vagy esetleg úgy hogy lecraftolod és úgy rakod le
