### ISSUE TITLE
/szabályzat /rules

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#3503]
**Szerver**:  gondolom mindenhol [?]
először is: csak a /rules van, kikerült a /szabályzat? 

Másodszor: szerintem jó volt az a megoldás hogy kategória szerint felsorolja a szabályokat.
Most csak egy linket dob és sokan szerintem lusták linkezni. [khm esetleg nem bírja a böngészőt és mc-t együtt ]

**Comment by andris155** [comment]
Fent van a weboldalon a szabályzat.
