### ISSUE TITLE
Hunger games

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#3504]
**Szerver**:  szurvi

Szerintem felesleges a hógolyó és a smaragd a ládákba, sztem azokat ki lehetne venni
Esetleg mcmmo-s potikat lehetne 1-2-t beletenni, pl sorvadás, vakság, émelygés [dobhatós]

**Comment by andris155** [comment]
@MrZero1 szerinted ez jó ötlet?

**Comment by MrZero1** [comment]
Igazából az, hogy rak olyan dolgokat is a ládába, ami kevésbé vagy egyáltalán nem hasznos, nem vesz sokat el a játékból, így azt mondanám, hogy maradjanak ezek. Legalább eloszlik az arány.
Potikat lehet belerakni.

**Comment by andris155** [comment]
Szerintem nem érdemes belevonni az mcMMO-t. Nem mindenki ismeri.

**Comment by andris155** [comment]
Meg egyébként ahol az arénák vannak ott tiltott az mcMMO.
