### ISSUE TITLE
Egy pár dolog. 

### ISSUE THREAD

**Issue by mnbTOC** [andris155/TheOld-Crafters#3505]
Survival (Ha savszigeten is van ez a parancs akkor ott is jó lenne szerintem a játékosoknak)
Jó lenne ha a /condense parancs a glowstone dust-ot átalakitaná glowstone-ra.

Illetve mint ötletládába is írtam egy Multi Language is kéne (Legalább Magyar-Angol)
Mivel ezzel sokkal több playerhez elbírna a szerver jutni. (Köszi Gabby a fejet)

Továbbá ha a prémium rang visszakapná a /ec parancs jogot (Vagy csak nálam nem megy?) 

Na és Minemarket-be egy 330 OCD vásárlási lehetőséget SMS-nél mivel Nagyon frusztrál engem hogy mikor veszem az Old csákányokat (Eddig nagyon sokat vesztettem el missclick végett és ügye az az én hibám) és ügye csak 508 OCD-t birokk venni nem 330-at ezért mindig marad 178 OCD-m amit csak eladni tudok. 

Edit: Pluszba az SF-hez egy addon a SoulJars. Igazából 128 Shardból egy kis vasból meg nemtudom mi kell még az ancient altárban bírsz összerakni egy BROKEN spawnert amit utána meg kell javítani (Ez nem fontos mert lehet annyira kihasználná egy pár player hogy 50-60 spawner egy helyre és szétlaggoltatná a szervert.)

**Comment by andris155** [comment]
Elit rangtól elérhető a /condense parancs a savszigeten.

Ez egy magyar szerver és kifejezetten magyar játékosoknak. Biztosan van valami jó bonyolult megoldás, amivel lehetne multi language, de akkor már inkább jobb lenne egy teljesen angol szerver. Viszont utóbbihoz jelenleg nincs elég jó angol tudásom sem. Így nem hiszem, hogy az én vezetésemmel lesz ilyen.

Nem fogja visszakapni. Old rangtól elérhető a /ec parancs.

Nincs olyan SMS szám. Sajnálom. Ajánlom a PayPal támogatást inkább.

Nem lesz a Soul jars. Túl sok spawner van így is már.
