### ISSUE TITLE
Sárkány a végben

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#3506]
**Szerver**: Survi

Van egy sárkány leidézve, kivan ütve minden kristály, mégis visszatöltődik az élete.

**Comment by MrZero1** [comment]
Első kép:
![kép](https://user-images.githubusercontent.com/29709854/78701933-1b1ff580-7908-11ea-827a-a53fe1587c0f.png)

Második kép, néhány másodperccel később:
![kép](https://user-images.githubusercontent.com/29709854/78701876-05123500-7908-11ea-9d43-cb66ab29bab1.png)

**Comment by MrZero1** [comment]
A képeket lehet törölni, ha megnézted Andris.

**Comment by andris155** [comment]
valahogy meg kellene ölni (?)

**Comment by MrZero1** [comment]
megölték hárman, nagy nehezen

**Comment by andris155** [comment]
Tudom mi okozta. Már javítottam.
