### ISSUE TITLE
CustomOreGen 

### ISSUE THREAD

**Issue by poma123** [andris155/TheOld-Crafters#3507]
Valamiért DellosP-nek nem megy a generátor savszigeten, se hiba, se semmi.

**Comment by andris155** [comment]
Nem lenne jobb átállni a BentoBox bővítményre?  A MagicCobbleGenerator-ra?

**Comment by andris155** [comment]
@poma123

**Comment by Niccolettie** [comment]
Más is panaszkodott már rá, hogy csak cobblestone jön és ércek nem 😕

**Comment by andris155** [comment]
Már jónak kell lennie, de a /ércgenerátor parancs frissítésre szorul.
