### ISSUE TITLE
Slimefun warp frissítése

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#3508]
**Szerver**: Survival

Hozzáértő emberekkel jó lenne átnézni a warpot, ami már nincs, kivenni vagy jelezni táblával, ami pedig új és nincs  kint, kirakni.

**Comment by MrZero1** [comment]
@skrisz0101 @poma123 @KingDeadZ  meg aki ért hozzá

**Comment by mnbTOC** [comment]
Chest Terminal részleget beválalom ha lehet.

**Comment by mr00000** [comment]
https://github.com/andris155Repository owner deleted a comment from mnbTOC 12 hours ago
MAGYAR
A lerakat tulajdonosa törölt egy megjegyzést mnbTOC-tól 12 órával ezelőtt/TheOld-Crafters/pull/3517

**Comment by poma123** [comment]
- [x] Hotbar Petek (Endsari, ágy, panda)

**Comment by poma123** [comment]
kész

**Comment by andris155** [comment]
köszönjük

**Comment by MrZero1** [comment]
Köszönöm!
