### ISSUE TITLE
Új plugin.

### ISSUE THREAD

**Issue by mnbTOC** [andris155/TheOld-Crafters#3509]
Survival szerverre egy új plugint szeretnék kérelmezni ha lehetséget.
Plugin neve: SlimeCalculator
Plugin letöltése: https://dev.bukkit.org/projects/slimecalculator/files
Ez egy Third-Party add-on slimefun-hoz ami egy parancsot ad hozzá a /calculate-t
Használat: /calculate (Mennyiség)
A kezedben kell lennie egy SF itemnek. Pl. Energized Solar Generator és a mennyiségbe beirod mennyit akarsz craftolni és kiirja hogy mi kell hozzá.
Az odlalon azt irja hogy 1.13-ig támogat de kiprobáltam és tökéletesen müködik 1.15.2-ben.
SlimeCalculator_v1.0.1.jar 

![](https://i.gyazo.com/7b85490259227aa9dfbcd9a515c0a190.png)

**Comment by andris155** [comment]
Ezt a plugint nem frissítik már így legújabb Slimefun verzión sajnos nem működik.

**Comment by mnbTOC** [comment]
Andris. De. Kompatibilis vele. És az összes többi adonnal. Tegnap délután mikor összeraktam magamnak a skyblockot szerver alapon akkor hibátlanul müködött.

**Comment by andris155** [comment]
Nálam a teszt szerveren be sem töltött. Szerintem te nem a legújabb Slimefun verziót használod.

**Comment by mnbTOC** [comment]
Küldök plugin verziót a /sf versions parancssal.

**Comment by mnbTOC** [comment]
Aha. Nvm a plugin betölt csak a parancs halott. Akármit fogok a kezembe azt irja "Ez nem slimefun-os item!"
