### ISSUE TITLE
bugg

### ISSUE THREAD

**Issue by brtamas0** [andris155/TheOld-Crafters#351]
ha gm 1ben lerakunk 1 blockot /p clear-ozunk gm 0ban leteszünk oda egy blokkot kreásnak érzékeli.

**Comment by andris155** [comment]
Erről a hibáról már tudtunk.

**Comment by andris155** [comment]
https://github.com/andris155/TheOld-Crafters/issues/185

**Comment by andris155** [comment]
De githubra még nem írták.
