### ISSUE TITLE
Eladás

### ISSUE THREAD

**Issue by IcyAlex** [andris155/TheOld-Crafters#3510]
Nem tudom hogy megvalósítható-e, de lett egy olyan ötletem, hogy:
Lenne egy adott block, amibe ha beleteszünk egy olyan itemet ami a boltban eladható, akkor azt automatikusan eladja.

+

Beírtam a chatre hogy "/sell all" és azt írta hogy "Nincs hozzáférésed ehhez a parancshoz", esetleg várható lesz egy ilyesmi gyors eladás?

**Comment by andris155** [comment]
A sell all király lenne és benne van Essentials-ban.
De a bolt mester az @MrZero1 és ez rajta múlik, hogy lesz-e vagy sem.

**Comment by IcyAlex** [comment]
Értem. Hát reméljük hogy @MrZero1 mester megcsinálja. :D

**Comment by mnbTOC** [comment]
Ezzel az a baj hogy pl csákány is el lehet adni. Namost nem szívesen adom el a csákim

**Comment by IcyAlex** [comment]
De egy pl. enchantos csákinak más ugye az ID-je, mármint ugye ha a kezedbe veszed és nyomsz egy /iteminfo-t akkor nem azt dobja ki hogy pl. diamond pickaxe, hanem még mellé számokat is, és így szerintem meglehet különböztetni az itemeket

**Comment by andris155** [comment]
Nyilván csak azt adná el, ami pontosan megvan határozva.

**Comment by MrZero1** [comment]
Nem szeretnék ilyet. Régebben is volt róla szó, de akkor is ellett vetve. A boltnál elég sok minden van, amit ellehet adni, meglehet venni. Szerintem senkinek sincs annyi felesleges kapacitása, hogy azokat ott beállítsa, valamint ha bármi változik a boltban (vételi-eladási ár) akkor azt a konfigban is át kell állítani. Na meg azért van a bolt, hogy oda elmenjen és megvegye. Ennyi erővel lehetne kézishop, mint savon, csakhát tudjuk, hogy az is milyen..

**Comment by MrZero1** [comment]
Arra nincs lehetőség, hogy shiftelés közben ne csak 64 darabot adjon el, hanem többet?

**Comment by mr00000** [comment]
ahh nem ugy megy am az alexem, itten onkenyuralom van
megfigyeles lehetosegek elrontasa esatobbi
ha lenne ilyen bolt, nem tudnanak egyesek csak ugy kenyukre kedvukre valtoztatni az arakon 
nem tudnak ellehetetleniteni a jatekosokat
ahh felejtsd  el @IcyAlex 
vegen meg kiderulne a sok sotet titok es hogy egyesek mit csinalnak
valszeg torolve lesz a kommentem, de hiaba mindent tudok

**Comment by IcyAlex** [comment]
De legalább akkor lehessen használni az SF-es backpacket a Boltban.

**Comment by andris155** [comment]
Nincsen.

**Comment by mr00000** [comment]
igenigen a cenzura
szoval
meg mindig eszakkorea van a szerveren, diktatura
onkenyuralom zeroka altal

**Comment by mr00000** [comment]
Repository owner deleted a comment from mr00000
