### ISSUE TITLE
Cannot Send Chat Message

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#3511]
**Szerver**: Nálam eddig csak Szurvin volt.

ma zsinórban 3x home-ltam ide-oda, mind a háromszor befagyott minden, nem tpzett sehova és írni se tudtam. ezt az üzenetet kaptam:

![2020-04-12_11 13 26](https://user-images.githubusercontent.com/29951969/79065275-727ae880-7caf-11ea-9035-06cbe0d2765d.png)

Mint kiderült, ez csomó embernél előfordul. nem tudom mi lehet a baj, de ma rendkívül sokszor előfordult, pedig még csak délelőtt van :D 

Régebben kingdead is jelentett hasonlót, neki /tpa-nál volt zsinórban 2x ez 
+Zeronak is.

**Comment by andris155** [comment]
Hamarosan bekerül hozzá a javítás.
https://github.com/PaperMC/Paper/issues/3114

**Comment by andris155** [comment]
Mire kell amúgy az a 126 üzenet?

**Comment by IcyAlex** [comment]
Nekem ma már vagy 20x volt ez a "kifagyásos" dolog és kezd nagyon idegesítő lenni. :(

**Comment by poma123** [comment]
1 tp után is kidob, tök szuper. :D

**Comment by skrisz0101** [comment]
hát, emlék xd

**Comment by andris155** [comment]
Holnap reggelre már bekerül a javítás a szerverre.

**Comment by andris155** [comment]
Bekerült a javítás.
