### ISSUE TITLE
Bankjegy

### ISSUE THREAD

**Issue by Conaniwnl** [andris155/TheOld-Crafters#3518]
**Akár mindkettő de legfőképp Savsziget**: 
Meglehetne-e csinálni, hogy bankjegyek lennének a szerveren, ami segítene a falusi-s bolt kereskedésen mivel akkor már nem csak tárgy - tárgy vagy tárgy - smaragd kereskedés lenne elérhető hanem tárgy - pénz is. Lehetne pl papír vagy valami ami x, előre meghatározott értéket képviselne és be lehete állítani a falusiba az legyen az ellenérték. Értelem szerűen kellene egy átváltó is ahol a rendes pénz átlehet váltani bankjegyre.

pl:
![2020-04-14_17 25 13](https://user-images.githubusercontent.com/40923017/79254952-cdfecf00-7e85-11ea-8b7f-ca9bda440f33.png)

**Comment by poma123** [comment]
Egyszer már volt erről szó, be is lett téve, aztán derült ki, hogy teljesen bugos a plugin, és egy kis trükkel végtelen pénzt lehet buggoltatni. Többek között ezért került be a token rendszer, ami nem egy itemként van a játékosoknál, hanem egy adatbázisban a szerver tárhelyén.

**Comment by Conaniwnl** [comment]
Viszont így nincs semmi létjogusultsága a villager tradernek ha pénzért szeretnénk értékesíteni, és azért menőbb lenne egy villagerrel cserélni, minthogy táblákra kattintgatni. Ha nem is ebbe a formában de másképp örülnék egy megoldásnak. Ebben a formában felesleges OCD-ért adni a villager tradereket.
