### ISSUE TITLE
Sav - ércgen

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#3519]
**Szerver**: Savsziget

Savszigeten kevés követ dob a generátor, nagyobb szinteken is.
Ha megoldható, nagyobb szinten több követ, kevesebb sódert, gránitot, andezitet, dioritot dobjon.

**Comment by Conan-iwnl** [comment]
Fentebb írtam egy regényt.

**Comment by MrZero1** [comment]
#3520 ugyanez
