### ISSUE TITLE
Savsziget Generátor

### ISSUE THREAD

**Issue by Conaniwnl** [andris155/TheOld-Crafters#3520]
**Savsziget**: 
Zéró kérésére leírom, hogy  mi a baj az új generátorral: Kevés követ ad nagy szinten. (Bár akkor szerintem már nem az a legkeresetebb alapanyag, de kitudja ki mit csinál vele.) Jó lenne ha kevesebb szemét kő pl: andesite, diorite, granit spawnolna helyette kő jönne. Sokan sírnak a gravel és föld miatt, hogy zavaró, szerintem jó anti-afk nak, de sokan nem értenek ezzel egyet. Jelentősen lassítja az afk bányászást, viszont aki akarja úgyis megoldja *jelenleg nem tiltott* modok segítségével. Véleményem szerint még annyi baja van ennek a rendszernek hogy emeráld szinten a régi *(nemtudom emnnyit adott talán)* 15% de most 5% ot ad ami *(talán)* 10%-al kevesebb, ez jelentősen meglátszik, bár sok jelentőssége nincs a szerveren mint sok másnak, szerintem ha kapna +5%-ot nem esne senki bajára. Ezeket a +%-okat ellehet venni a lapis, redstone, coal trioból amitből jelentősen felesleges mennyiséget lehet szerezni. Ezeket a véleményeket Old eszközök használata alapján írom, de szereintem ez sokat nem befolyásolhat, hisz érc ugyan annyi esik.

**Comment by andris155** [comment]
Én biztosan nem fogok belenyúlni az alap beállításaiba. Annak a staffnak kellene aki a legjobban jártas a savszigetes dolgokban.

**Comment by MrZero1** [comment]
Rajtad meg Pomán kívül más nem fér hozzá a konfighoz. 🤣

**Comment by andris155** [comment]
A konfigot megcsinálom, csak valami hozzáértő mondja az új értékeket. :D

**Comment by poma123** [comment]
Ha megmondjátok mi mennyi legyen, én is beállítom

**Comment by Conaniwnl** [comment]
`tier6:
    min-level: 10000
    name: "Emerald Level"
    blocks:
      STONE: 10
      DIORITE: 1
      GRANITE: 1
      ANDESITE: 1
      COBBLESTONE: 8
      GRAVEL: 3
      DIRT: 5
      GRASS_BLOCK: 1
      COAL_ORE: 10
      IRON_ORE: 10
      GOLD_ORE: 10
      LAPIS_ORE: 5
      REDSTONE_ORE: 10
      DIAMOND_ORE: 15
      EMERALD_ORE: 10`

Én ezt javasolnám, redstone az -10% (ebből túlsokat dobott eddig szerintem), viszont így is maradt 10%, 5%-ot kapott az emeráld, a cobblestone 1% helyett 8% lett (ezzel kipipáljuk a kő hiányát), a sóder pedig 5% helyett 3% (ez a sóder miatt síróknak jó). Ez csak a maxos generátorra gondoltam, a kissebeket nemtudom hogy müködnek.

**Comment by MrZero1** [comment]
Nekem jó így. Kisebb szinteknél a követ lehetne 1-2%-kal fentebb rakni, max a sódert meg 1%-kal csökkenteni.

**Comment by andris155** [comment]
Beállítottam. Holnap elérhető lesz.
