### ISSUE TITLE
Kutyák zavarják a védelmi plugint

### ISSUE THREAD

**Issue by Icecroft** [andris155/TheOld-Crafters#3521]
A kutyák 750-es mcmmo szinten annyira hatékonyak, hogy a védelmi plugin azonnal bejelez, aimbot és egyéb hacktoolok használatával gyanúsít.
Andris, légyszi akkor zárd le ezt az incidenst, ha ez a probléma megoldódott és újra használhatom a kutyákat.

**Comment by andris155** [comment]
Nincs rá megoldás. Már régebben írtam a fejlesztőnek. Az mcMMO támogatást már nem fejlesztik a NoCheatPlus-hoz. Csoda, hogy még működik.

**Comment by andris155** [comment]
Melyik skill ez egyébként illetve mi ez a képesség pontosan?

**Comment by Icecroft** [comment]
A kutyák a szelídités 750-es szintjétől tudják használni a Sharpened Claws skillt, ami kb 5 szíves sebzést tud moboknál okozni, azaz egy csontit akár egy ütéssel kivégez. Van 4 kutyám, amik ha egyszerre mobokat ölnek, akkor a nocheatplus plugin bejelez, mert túl hatékonynak találja a technikámat.
Csak az a kérésem, hogy néha használhassam a kutyákat (ezért is fejlesztettem őket napokig), mert a boltomban a csontok és nyílvesszők feltöltéséhez ez a leghatékonyabb, míg közben én a javítás skillel a páncélokból kiszedem a nyersanyagokat.
