### ISSUE TITLE
Slimefun Vaporizer továbbfejlesztés

### ISSUE THREAD

**Issue by Icecroft** [andris155/TheOld-Crafters#3522]
A slimefunos Vaporizer egy vödör láváért (+ némi energiáért) legyárt 16 szulfátot.
Mivel a vödrök elvesznek ezért ez a szulfát így drága lesz. Érdemes lenne a gépet továbbfejleszteni a. vagy b. módon:
a.) a 16 szulfát mellett visszaadja a vödröt is
b.) elveszi a vödröket, de 16 helyett 32 szulfátot ad.

a jelenlegi helyzetben sajnos jobban megéri a netherrack ipari szintű bányászata szulfátért.

**Comment by skrisz0101** [comment]
+1

**Comment by andris155** [comment]
Holnap frissül a plugin, majd nézzétek meg, hogy ugyanígy működik-e.

**Comment by Icecroft** [comment]
10:21-kor még nincs változás

**Comment by andris155** [comment]
Holnap bekerül a változás. Köszönjük az ötletet.

**Comment by andris155** [comment]
1016 OCD

**Comment by Icecroft** [comment]
Szia Andris, a Vaporizer valóban változott, de rossz irányban, mivel csak 1 szulfátot ad, a vödröt sem kapom vissza.
![2020-05-01_19 59 26](https://user-images.githubusercontent.com/19332825/80829226-02dd8680-8be7-11ea-8347-1436be75f34f.png)

**Comment by andris155** [comment]
Mivel az új verzió nem töltött be visszakellet váltani a régebbire. Talán újra le kell rakni, hogy működjön. De holnap ismét kiderül, hogy jó-e az új verzió már javított változata.
