### ISSUE TITLE
MineMarket fejlesztések 2020

### ISSUE THREAD

**Issue by andris155** [andris155/TheOld-Crafters#3523]
- [x] Nem működő kosár oldal tiltása.

**Comment by MrZero1** [comment]
- [ ] OldVillage háttérkép lecserélése. :D

**Comment by andris155** [comment]
Az oldalt nem tilthattam, mivel csak ott lehet lemondani, ha valaki rá megy úgy a fizetésre, hogy nincs elég OCD-je...
Viszont a gombot sikerült kivenni így ez javításra került.

**Comment by andris155** [comment]
Nincs ötletem milyen sötét kép lenne oda jó helyette.

**Comment by MrZero1** [comment]
![2019-04-04_14 00 37](https://user-images.githubusercontent.com/29709854/80013347-024e3d00-84cf-11ea-98e8-43c213eea851.png)

Esetleg ez? Régebbi, hirdetésekhez szoktam használni. Van pár sötétebb kép

**Comment by MrZero1** [comment]
De szerintem poma biztos csinál pár shaderses képet, sötétebb fényeknél.

**Comment by andris155** [comment]
Az adminunkat kellene inkább megkérni, akinek 4K-s monitora van. :D

**Comment by poma123** [comment]
mérnemjó a mostani? :( nekem tökre bejön

**Comment by MrZero1** [comment]
Mert már nincs OV :(

**Comment by UDPSendToFailed** [comment]
![kép](https://user-images.githubusercontent.com/16057404/80417010-598c4d00-88d5-11ea-955b-db680c0b416e.png)

**Comment by andris155** [comment]
Úgy is jó elvileg. Bár van egy staff tagunk aki natív 4k-s képeket is tud készíteni.

**Comment by andris155** [comment]
Majd megpróbálok készíteni jó képeket hozzá 4k-ban shaderrel legalább 16-os látótávolsággal, hogy minden jól látszódjon rajta.

**Comment by andris155** [comment]
Próbálgattam más képeket, de nem néz ki valami jól úgy. Majd a következő nagy dizájn frissítésnél lesz lecserélve.
