### ISSUE TITLE
Horgászat kézikönyv (nem játékot befolyásoló hiba)

### ISSUE THREAD

**Issue by Lagire** [andris155/TheOld-Crafters#3524]
A túlélő szerveren a horgászat kézikönyv ötödik oldalán úgy van írva, hogy:
"Valamint jobb esély van ezzel élőlény fejet szerezni, ami alapból nem lehetséges túlélő módban."
Ez így egy kisebb tárgyi tévedés, ugyanis az [ITT](https://minecraft.gamepedia.com/Head#From_mob_loot) leírtak szerint ha Charged Creeper öli meg a mobot, akkor kiesik a feje. Nem befolyásolja a játékot, de gondoltam jelzem.

**Comment by andris155** [comment]
Milyen kézikönyv ez?

**Comment by andris155** [comment]
Ráférne arra a fordításra egy frissítés, csak nagyon nagy és nem igazán van rá időm. :(

**Comment by Lagire** [comment]
Akkor megcsinálom, csak kéne az eredeti plugin. Nem a magyar, hanem az angol.

**Comment by andris155** [comment]
https://github.com/mcMMO-Dev/mcMMO/blob/master/src/main/resources/locale/locale_en_US.properties

**Comment by andris155** [comment]
Nyitottam hozzá egy módosítási javaslatot, ha elfogadják, akkor jó lesz a szerveren is.
https://github.com/mcMMO-Dev/mcMMO/pull/4170/commits/9a3b261f07fdced160759c906c5efbd85f914199
,,Valamint lehetőség van ezzel olyan élőlény fejeket is szerezni, amelyeket általában nem lehetséges túlélő módban."

**Comment by andris155** [comment]
Remélhetőleg majd elfogadják. Ha nem, akkor szerintem nem olyan óriási baj, ha úgy marad. Valamikor a jövőben ha lesz időm az egész fordítást átnézem majd és javítom benne a hibákat.
