### ISSUE TITLE
Slimefun Enhanced furnace

### ISSUE THREAD

**Issue by HighmanHuge** [andris155/TheOld-Crafters#3525]
survival szerveren az enchanced furnace-eknek van egy értékük hogy üzemanyaghatékonyság.
ha szén helyett szénblokkot rakok bele, akkor fordítva működik és iszonyat sebességgel kezdi el zabálni a blokkokat. sima szénnel tökéletes.

**Comment by andris155** [comment]
XD tipikus Slimefun hiba.

**Comment by andris155** [comment]
Holnap majd tesztelem.

**Comment by skrisz0101** [comment]
Üsd ki, rakd le újra, majd rakd bele újra a szenet.

**Comment by andris155** [comment]
Más tüzelőanyaggal sem jó?

**Comment by HighmanHuge** [comment]
Kipròbàltam ma reggel szènblokkal meg fa lèpcsővel is működött szòval
megoldòdott a problèma ùgy tűnik.
Előtte is csak a szènblokk volt a hibàs.

**Comment by andris155** [comment]
Nem történt javítás ezzel kapcsolatban. Majd letesztelem újra, de szerintem továbbra sem jó.

**Comment by andris155** [comment]
A hiba továbbra is él. Valamikor a jövőben talán lesz rá javítás. Addig inkább csak sima szenet használj benne.

**Comment by andris155** [comment]
508 OCD

**Comment by HighmanHuge** [comment]
Hàt az van hogy hol jò hol nem, ma pl se szèn se szènblokk, fàval okè volt
többiek szerint blazeroddal mèg nem volt baj.
