### ISSUE TITLE
Savsziget redstone jel hiba

### ISSUE THREAD

**Issue by KulGery** [andris155/TheOld-Crafters#3526]
**Szerver**: Savsziget

Sem a komparátor utáni blokkon levő fáklya, sem a tölcsér utáni komparátor nem érzékeli a környezetét megfelelően. A fáklya alszik, mintha a blokknak lenne jele, de nincs, illetve a komparátor nem ad jelet, pedig a tölcsérben van bot.

![2020-04-23_18 53 40](https://user-images.githubusercontent.com/25465311/80127264-5c650600-8594-11ea-8168-66790c5e2ac3.png)
Az első képen, a bal oldali fáklyák közül a hátsónak bekapcsolva kellene lennie, míg a komparátorból a közelebbinek, ezt a következő ábrán mutatom, hogy van bot a tölcsérben.

![2020-04-23_18 54 01](https://user-images.githubusercontent.com/25465311/80127288-6555d780-8594-11ea-80a0-fdfc304d06ad.png)

Ha kiveszem a botot, és újra beteszem, akkor újjra jól működik

Chunkon belül van a teljes áramkőr

**Comment by KulGery** [comment]
Ja, azt lehagytam, hogy amíg játszom, nem szokott leállni, csak akkor jelentkezik, ha kilépek... De persze az is lehet nem szoktam megnézni kilépés elött... Mostantól arra is figyelni fogok

**Comment by KulGery** [comment]
Tegnap estéről ma reggelre nem,
Viszont most mikor beléptem, azt tapasztalom, áll az összes ugyanúgy ahogy fenn írtam, csak az egyik fordítva. Tehát az is egyértelmű hogy nem kiépítés hiba.

**Comment by KulGery** [comment]
Ma hajnalban leellenőriztem mielött kiléptem, és jól működött mindegyik.
Ma reggel viszont mikor beléptem már állnak.
Tehát úgy áll le a rendszer, hogy nem vagyok ott.
A tölcsér átadja az összes elemet, noha nem vagyok már bejelentkezve (ez nem baj, gondolom amikor valamelyik játékos a szigetemen van, pl boltol) viszont a vöröskő elemek már nem reagálnak a változásra.

**Comment by andris155** [comment]
Nem sikerült reprodukálni.

**Comment by KulGery** [comment]
De sikerült... almacsutka szigetén...
Kiléptünk, úgy hogy működött a rendszer, majd KulLevi /is pwarp almacsutka parancssal odament, ott volt 5 percet, majd elment, vártunk még öt percet, és mikor visszaléptünk, már állt. Kétféle megépítés volt, egyik az én megoldásom, másik a dugattyús. Mind a kettőben a tölcséres rész végigpörgött, és utána leállt, nem léptette a dugattyút, illetve a pálcát az elsó tölcsér párban...

**Comment by KulGery** [comment]
19:42kor léptünk ki, és 19:53kor léptem vissza, almacsutka meg 19:59kor. Én az egyiket már elindítottam, de a dugattyús még nem lett elindítva ekkor.ő

**Comment by KulGery** [comment]
Feltételezésem szerint ha sziget tagja nincs a közelben, de vendég igen, akkor a tölcsér tovább "ketyeg" viszont az vereskőjel nem.

**Comment by andris155** [comment]
Esetleg ha valahova csinálnál egy egyszerűbb szerkezetet, ahova kiírod, hogy melyik redstone jelet is kellene nézni ami utána nem megy, akkor megnézem bővebben.

**Comment by KulGery** [comment]
Elöbb nyisd újra mert reprodukálható

**Comment by KulGery** [comment]
És nincs egyszerübb. A dugattyús könnyebben érthető.. Munka után megmutathatom, de lehet almacsutka is kell mert csak megbízott vagyok a szigetén.

**Comment by andris155** [comment]
Kérlek most teszteld le.

**Comment by KulGery** [comment]
Két játékossal is lett tesztelve, mindkét esetben rendesen működött a visszalépés után is a rendszer.
Köszönjük a javítást.

**Comment by andris155** [comment]
Szívesen.
