### ISSUE TITLE
Slimefun auto enchanter, auto disenchanter

### ISSUE THREAD

**Issue by Lagire** [andris155/TheOld-Crafters#3527]
A survival szerveren, ha kiütjük folyamat közben az auto enchantert vagy az auto disenchantert, akkor eltűnik a tárgy, amit betettünk és csak a kiütött blokkot lehet felszedni.

**Comment by andris155** [comment]
A Slimefun fejlesztő ezt írta rá.
<img width="420" alt="Capture" src="https://user-images.githubusercontent.com/8324198/80313498-7c423700-87eb-11ea-86d5-737adef9bce2.PNG">

**Comment by andris155** [comment]
508 OCD
