### ISSUE TITLE
Szavazás

### ISSUE THREAD

**Issue by Lagire** [andris155/TheOld-Crafters#3528]
A túlélő szerveren szavazásnál, ha tele van a hátizsákunk, akkor eltűnik a kulcs, amit kapnál és nem kapod meg, csakis a pénzt és a tapasztalati pontot.

**Comment by andris155** [comment]
Elvileg kidobja eléd ilyenkor a tárgyat.

**Comment by andris155** [comment]
Erre nincs megoldás. Figyelj, hogy ne legyen tele a táskád.
