### ISSUE TITLE
Sav pet pickup

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#3529]
**Szerver**: Sav

![kép](https://user-images.githubusercontent.com/29709854/80252482-9eb34380-8677-11ea-9b1c-0e24cb402933.png)

Szerintem a petpickup-ot lehetne tiltani savszigeten, emiatt

**Comment by KulGery** [comment]
Vagy az is be legyen téve a settings-be

**Comment by andris155** [comment]
Kikapcsoltam inkább ennek a védelmét. Holnap majd betölt.
