### ISSUE TITLE
Survival levédés

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#3530]
**Szerver**: Survi

Survivalon van olyan parancs, amivel a levédést ténylegesen átlehet adni másik embernek? A "tulaj" jogra gondolok itt.

Illetve, nem tudom milyen parancsok és flag-ek vannak azokon kívül, amik a levédés warpon vannak, de jó lenne átfutni ezeket, mikre van joguk és kiírni azt is a warpra.

**Comment by andris155** [comment]
Nincs

**Comment by andris155** [comment]
https://www.spigotmc.org/resources/griefprevention-flags.55773/
Flags rész

**Comment by andris155** [comment]
https://github.com/ShaneBeee/GriefPreventionFlags/wiki/Flags

**Comment by andris155** [comment]
Ezekre van joguk: AllowPVP,  NoMobSpawns, NoEnderPearl, NoMonsterSpawns, NoMobSpawnsType
