### ISSUE TITLE
/savsziget parancs

### ISSUE THREAD

**Issue by mnbTOC** [andris155/TheOld-Crafters#3531]
Survival > Savsziget
Mikor old szettben beírom a /savsziget parancsot akkor savszigeten bebugol a health bar és az armor bar is ezáltal azt jelezve hogy 2 sor életem van, Dia szettben vagyok.
https://youtu.be/hthJaz9ZclA

**Comment by andris155** [comment]
Már jelentett hiba.
https://github.com/andris155/TheOld-Crafters/issues/3449
