### ISSUE TITLE
mcmmo - íjászat

### ISSUE THREAD

**Issue by SaltyUmbrella** [andris155/TheOld-Crafters#3534]
Hello, mcmmo Íjászat skillben nem kapok XP-t semmi által sem, amit megölnék.
megnéztem, az összes többi másik skill rendben vanm, csak ez az egy nem

**Comment by andris155** [comment]
Szia
Nem sikerült reprodukálni a hibát. Csak olyan élőlényekkel működik, amiket a játék idézett le. A spawner-esekkel nem fog XP-t adni.
