### ISSUE TITLE
Szigony

### ISSUE THREAD

**Issue by Lagire** [andris155/TheOld-Crafters#3535]
Survival szerveren a telkeken, ha egy szigonyt olyan telekre dobsz, amihez nem vagy hozzáadva, akkor eltűnik a szigony.
A hűség sem segít, amint földet ér a tárgy, eltűnik és nem tudod "kihúzni" a földből, mint alapjáraton kellene.

**Comment by andris155** [comment]
Ez sajnos ilyen. Erre nincs megoldás.

**Comment by andris155** [comment]
Ezért lett kivéve az Old szigony is régebben.
