### ISSUE TITLE
Savsziget-Küldetések

### ISSUE THREAD

**Issue by Gigi91970** [andris155/TheOld-Crafters#3536]
Sziasztok!
Savsziget szerveren lenne egy  olyan "probléma-hiba", hogy az utolsó küldetések (/c - ellenséges állatkert pont) lehetetlennek bizonyult nekünk, minden mob elfogható kivéve a Drownedet (próbáltunk zombit átváltoztatni- közben potikkal is próbáltuk életben tartani), de a savas víz miatt nem lehet ezt kivitelezni  és így a küldetéseket sem tudjuk befejezni 
Esetleg lehetne valahol venni drowned tojást, spwanolását beállítani, hogy ne haljon meg a savas vízben?

**Szerver**: Savsziget

**Comment by andris155** [comment]
Elvileg már nincs benne.
