### ISSUE TITLE
Szabály

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#3537]
Weboldal:

7. Támogatók

7.8, A támogatókra vonatkozik a fent leírt összes szabály. Nincs kivételezés!

2. Játékmenet

2.15, Ne önbíráskodj! Ha valami gond van, jelezd egy Staffnak. Amennyiben Te szankcionálsz más játékost, Te is büntetésben részesülhetsz..

**Comment by andris155** [comment]
A 7.8-at szerintem elég gáz, ha bele kell írni. Ez alap dolog.

**Comment by andris155** [comment]
Frissítettem az oldalt.
