### ISSUE TITLE
Survival - Slimefun

### ISSUE THREAD

**Issue by KingDeadZ** [andris155/TheOld-Crafters#3539]
Pár napja ha megölünk egy iron golemet, akkor nem ad basic circuit boardot. (Falusiak által spawnoltatott golemmel is leteszteltem meg olyannal is, amit én idéztem meg)

**Comment by andris155** [comment]
Már jelentett hiba:
https://github.com/TheBusyBiscuit/Slimefun4/issues/1834

**Comment by andris155** [comment]
Valamikor a jövőben talán javításra kerül majd.
