### ISSUE TITLE
Survival - Tábla addolás

### ISSUE THREAD

**Issue by Raxoray** [andris155/TheOld-Crafters#3540]
Röviden és tömören, lényegretörően elmondom a hibát amivel lehet táblát addolni Old ranggal bárkinek, teljesen véletlenül a capslock benthagyása miatt vettem észre.
Tehát vannak színkódok amit táblákon is lehet használni.
&6 - sárga lesz
Számokkal nincsen egyetlen probléma sem.
&d - rózsaszín lesz
Ilyen betűkkel sincs semmi féle probléma.
&D - és egyéb nagy betűvel írt [ & ] színkódokat kiüti a rendszer ilyen indokkal:
-Az unicode karakterek tiltottak!
-A táblád kiütöttük, valami nem stimmelt vele.
Ezt a kettő szöveget egyből kiadja, majd kiüti a táblát amit túlélő módban lehet felvenni.

Remélem segítettem és nem nagyon bonyolult a hiba kijavítása.

Üdv: Trymer (nem engedi átírni a nevem itt és nem akartam újat csinálni..)

**Comment by Niccolettie** [comment]
#2874 #2890
