### ISSUE TITLE
Survival - Mob Spawnrate

### ISSUE THREAD

**Issue by KingDeadZ** [andris155/TheOld-Crafters#3541]
A mostani spawnolási ráta elég lutri.
Viszonyítás képp: Egy mostani enderman farm olyan effektív, mint amennyi wither skeleton jön általánosságba normális spawnraten.

Nem lehetne ezt úgy megoldani inkább, hogy egy pl 50x50es területen belül egy bizonyos pont fölé nem spawnolna ellenséges mob? Szerintem sokkal jobb lenne a játékélménynek, de ez csak az én véleményem.

**Comment by Raxoray** [comment]
Támogatom!

**Comment by skrisz0101** [comment]
Azért lett levéve mert úgy laggolt folyamat a szeró, mint ma xd

**Comment by andris155** [comment]
Ameddig nincsenek jobban optimálizálva az entitások nem akarok növelni a spawn limit beállításokat.
