### ISSUE TITLE
Survival - Slot

### ISSUE THREAD

**Issue by KingDeadZ** [andris155/TheOld-Crafters#3542]
Szerintem lejjebb lehetne venni kicsikét a slotoknak a számát pl. 50-> 45,mivel ha 50en vagyunk fent mindíg nagyon rossz a tps, ami a játékélményt ronthatja.

**Comment by skrisz0101** [comment]
Hetek óta 50en vagyunk fent. Ez a mai nap különlegesnek mondható

**Comment by KingDeadZ** [comment]
Andris elm. megcsinálta, ha megint jelentkezik akk ujranyitom
