### ISSUE TITLE
Fordítások

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#3545]
Meglévő, kiadott fordítások:

- [x] McMMO kézikönyv - Lagire

- [x] Titkos fordítás (en-US.yml) - Niki

**Comment by andris155** [comment]
Amire írták a hibát az mcMMO parancsban az holnap már jó lesz, vagy az egészen fejleszt majd Lagire?

**Comment by andris155** [comment]
Elvileg a titkos fordítás is kész, csak át kell nézni majd.

**Comment by andris155** [comment]
Bekerült mindkettő. Lagire, ha javít még valami fordítást az mcMMO-n majd írjon.
Lehet tesztelni a titkos fordítás a titkos szerveren, aki feltud menni rá.
