### ISSUE TITLE
Lucky Block

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#3546]
**Szerver**:  Szurvi, sf
Szerintem fel lehetne túrbózni a lucky blockot pár dologgal, mert így sztem nem éri meg megcsinálni.
Pár ötlet:
Giant zombi [2x64-ből nem nyitottam szóval gondolom tiltva van]
Pusztító, +egy azon lovagló idéző
Nether csillag [Ez se jött 2x64-ből]
Patriot pet [Hotbar pet]
Carbon chunk / carbonado
ötletesebb cuccok is lehetnének, mint pl az ,,Én vagyok Grrot",  meg a Mr. Rainbow bárányok.
értéktelenebb kulcsok, pl Ultrakirály, legendás

Nem tudom lehet-e %-ot állítani hogy milyen gyakran dobja az adott cuccot, de ha lehet, akkor kis eséllyel lehetne akár értékesebb dolog is benne. pl:
Soulbound rúna 
Soul cuccok/eszközök
Broken spawner
Sárkány tojás

Ne zárjátok le egyből ha lehet, jöhetnének ide +ötletek is másoktól
köszpusz

**Comment by MrZero1** [comment]
Jó ötlet, ha lehet állítani ezen, állítsunk. Negatív dolgokat is lehetne pluszba (mobok). Illetve akár 1-2 kulcs, ha megoldható, hogy parancsot futtasson le (pl. fortuna, vándor)

**Comment by poma123** [comment]
Nem lehet testreszabni egyáltalán.
![image](https://user-images.githubusercontent.com/25465545/80804159-a2355600-8bb4-11ea-88b7-23fb0d06aa51.png)

**Comment by skrisz0101** [comment]
király.. xd Sf fejlesztőre nem lehet ráírni h jó lenne ha testreszabható lenne?

**Comment by andris155** [comment]
Discordon lehet nekik csak ötleteket írni. Ha gondolod írd meg nekik.

**Comment by andris155** [comment]
https://discordapp.com/invite/fsD4Bkh

**Comment by andris155** [comment]
A giant slime brutálisan laggos. Azért van tiltva.
