### ISSUE TITLE
mctop hiba

### ISSUE THREAD

**Issue by SaltyUmbrella** [andris155/TheOld-Crafters#3547]
**Survival**: 
CubeBarack (régebbi nevén Sagittarius69) nevet változtatott, ezáltal megkapta az előző felhasználója mcmmo szintjeit, csakhogy így az előző is ott maradt 3. helyen. Csatolok képet:
![mctop](https://user-images.githubusercontent.com/42703224/80802109-a8c0cf00-8bae-11ea-820a-48c52a55f458.png)

**Comment by SaltyUmbrella** [comment]
pontosítás: ezzel együtt ugye mindegyik másik mcmmo-s skill területben is ott maradt a név és pontszám, ahol eddig is szerepelt

**Comment by poma123** [comment]
ki lesz véve...

**Comment by andris155** [comment]
Most melyiket kellene törölni?

**Comment by andris155** [comment]
<img width="329" alt="Capture" src="https://user-images.githubusercontent.com/8324198/80845629-151cec00-8c0a-11ea-8519-a679b3d3082f.PNG">
Már nincs listában.
