### ISSUE TITLE
Shop

### ISSUE THREAD

**Issue by IcyAlex** [andris155/TheOld-Crafters#3548]
**Szerver**: Survival

A Shop tábla miadt én nem tudom feltölteni a ládákat, és az az ötlet/kérdés jutott az eszembe hogy a pluginhoz hozzálehetne e adni valami olyasmit amivel lehet egy ilyen "shop party-t" létrehozni és akkor a party tagjai is beletudnak nézni a ládába?

**Comment by andris155** [comment]
Nem fér rá több név a táblára. Szerintem meglehet oldani, hogy odaadod a bolt tulajdonosának és ő bele rakja.
