### ISSUE TITLE
Savsziget - Shop

### ISSUE THREAD

**Issue by PappeszHU** [andris155/TheOld-Crafters#3553]
Savsziget - Shop

Ha veszel lávát , de úgy hogy beállítod hogy (1 hozzáadása) vagy stb.. és ha pl veszel így 5db lávát akkor lényegében meg is kapod, de mikor le akarod tenni akkor 1et tesz le és a többi eltűnik.

-Pappesz

**Comment by andris155** [comment]
<img width="401" alt="Capture" src="https://user-images.githubusercontent.com/8324198/80912863-4a2b5a80-8d40-11ea-898b-a1e33493a3e5.PNG">
Ki van írva, hogy csak 1 vödröt érdemes venni.
