### ISSUE TITLE
Sf auto breeder

### ISSUE THREAD

**Issue by HighmanHuge** [andris155/TheOld-Crafters#3557]
Survival serveren, van egy slimefun eszköz: "auto breeder". Organic foodért cserébe szaporítja a közelben található állatokat.
Hiba:
Például ha van két csirkém, beindítom a breedert, ami azonnal felhasznál 2 organic foodot hogy a szaporítás megtörténjen, viszont miután szaporodott a csirke az eszköz továbbra is pumpálja beléjük az organic foodot, szivecske effektek kíséretében. természetesen nem szaporodnak tovább csak a nyersanyag fogy (nem a kicsit eteti, arra van másik eszköz).
Ez így gyakorlatilag használhatatlan.

**Comment by andris155** [comment]
Talán valamikor a jövőben javítva lesz. Bár sajnos a Slimefun fejlesztő nem tudta reprodukálni.

**Comment by andris155** [comment]
508 OCD
