### ISSUE TITLE
"fellépek meghaltam help me"

### ISSUE THREAD

**Issue by poma123** [andris155/TheOld-Crafters#3560]
néha azt mondják h fellépéskor meghalnak pedig kilépéskor nem haltak meg
nyomozni kéne

**Szerver**:  Survi

**Comment by andris155** [comment]
Nem tudok vele mit kezdeni pontos időpontok és nevek nélkül.

**Comment by poma123** [comment]
csak hogy meglegyen itt is.
![image](https://user-images.githubusercontent.com/25465545/81344717-9d423c00-90b7-11ea-9e2e-bd77c11b0c32.png)

**Comment by andris155** [comment]
A játékos nevét továbbra sem tudni. Biztosan nem simán Bence

**Comment by Niccolettie** [comment]
Benceke a neve

**Comment by andris155** [comment]
Rossz volt a nete és valahogy a vízbe került home nevű otthona körül, ahol megfulladt mielőtt ledobta a szerver időtúllépéssel.
```
[09:03:17] [Server thread/INFO]: Benceke issued server command: /home home
[09:07:13] [Server thread/INFO]: Benceke drowned
[09:07:44] [Server thread/INFO]: Benceke lost connection: Timed out
```

Ez nem hiba.
