### ISSUE TITLE
Crop Growth Accelerator és Tree Growth Accelerator

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#3561]
**Szerver**:  Szurvi, slimefun.
1.: Crop Growth Accelerator
Ez a gép arra jó, hogy organic fertilizer-el növényeket növesszen.
1 organic fertilizer-hez 1db növény kell (Búza, répa, krumpli, cékla, búzamag, dinnye, alma, édesbogyó, szárított Hínár) +1tin can.
Na, egy növény megnövesztéséhez kell kb 5 organic fertilizer, azaz 5 növény (vagy akár több)
De ha learatod azt, amit kapsz a megnövesztett növényből, max 2-3 lesz.
Így egyáltalán nem éri meg ezt csinálni, mert többet fogyaszt, mint termel

2. Tree Growth Accelator
Ez is hasonlóan működik. 
Adsz neki organic fertilizert, cserébe megnöveszti a facsemetéket.
Ez egyáltalán nem működik. elhasznál 2-3 fertilizert, majd megáll xd

**Comment by andris155** [comment]
Ötleteket a Slimefun Discord szerverén lehet írni. Jobb lenne, ha inkább te írnád meg, hátha kérdeznek még utána hogy is legyen vagy így jó-e stb...

**Comment by andris155** [comment]
Az nem hiba ha nem éri meg legalábbis a Slimefun fejlesztő szerint biztosan nem.

**Comment by andris155** [comment]
A másikat megírtam, de kérlek legközelebb ne egy hibajelentésbe írj 2 különböző hibát. Ráadásul úgy, hogy az egyik ötlet a másik meg hiba.

**Comment by andris155** [comment]
,,the Tree Growth Accelerator only accelerates their growth, it doesn't make them grow instantaneously."

**Comment by skrisz0101** [comment]
Mindkettőt hibának szántam xd

**Comment by andris155** [comment]
Slimefun Discord szerver: https://discord.gg/fsD4Bkh

**Comment by skrisz0101** [comment]
Nem tudok angolul, nub vagyok ahhoz xd
