### ISSUE TITLE
SlimeFun guide könyv hiba

### ISSUE THREAD

**Issue by SaltyUmbrella** [andris155/TheOld-Crafters#3562]
**Survival**: 
SlimeFun guide könyvben ha rákeresek a sóra (salt a játékban) akkor kihozza, hogy miből, mivel és hogyan kellene csinálnom, de az a baj, hogy 2db homokot ír a recept, amikor 4db kellene.
![SF_1](https://user-images.githubusercontent.com/42703224/81436093-24032180-9169-11ea-9037-c40e38d3a4bd.png)
![SF_2](https://user-images.githubusercontent.com/42703224/81436095-249bb800-9169-11ea-96d4-8a3f2f6b32de.png)

**Comment by andris155** [comment]
Tele van baromságokkal. A fejlesztőnek ez nem számít hibának.

**Comment by andris155** [comment]
Tele van rossz receptekkel a vanilla tárgyakhoz. A fejlesztőnek ez nem számít hibának.

**Comment by skrisz0101** [comment]
De ez nem vanilla recept
Vagy hogy érted? Xd

**Comment by andris155** [comment]
A többi recept mind jó? Gondolom akkor vannak még ilyenek benne.

**Comment by SaltyUmbrella** [comment]
nagyon sok recept van, amik magukon belül is tartalmaznak még következőeket is, stb.. lehetséges, hogy vannak, az nincs kizárva

**Comment by andris155** [comment]
Ha foglalkozik ezekkel a Slimefun fejlesztő, akkor OCD-ért szerintem megérné valakinek végig nézegetni. :D

**Comment by andris155** [comment]
A következő verzióban javításra kerül.

**Comment by andris155** [comment]
508 OCD
