### ISSUE TITLE
Slimefun 

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#3564]
Szerintem már eléggé stabil az sf, vagy épp a szeró optimalizálása elég jó ahhoz, hogy minemarketen legyen slimefun rész mindkettő szerveren.

Ár-érték ötletet szívesen írok

**Comment by andris155** [comment]
Ki kellene találni, hogy mi legyen és mennyi OCD-ért.

**Comment by skrisz0101** [comment]
Holnap összeírom ide

**Comment by MrZero1** [comment]
Itt vannak. #3280

**Comment by skrisz0101** [comment]
Aha, ahhoz még annyit, hogy a Neptunium, boosted uránium, plutonium nem kell.
Szinte semmire se jók

**Comment by Icecroft** [comment]
Lenne nekem is javaslatom az sf részleghez. A bolti eladásaim alapján a legnépszerűbb dolgok a lehetséges árakkal:
1 db Energized Solar generator:  1016 OCD
1 db Nuclear generator: 508 OCD
1 db Cobblestone generátor: 720 OCD
4 db Blistering ingot: 330 OCD
16 db Carbonado: 330 OCD
4 db Afterlife essence: 330 OCD
16 db Infused Hopper: 330 OCD
1 db Cargo manager: 330 OCD
1 db Carbonado furnace: 508 OCD
64 db Electric motor: 508 OCD
64 db Cargo motor: 720 OCD

**Comment by MrZero1** [comment]
Összegezve:

(ezek shulkerbe ha megoldható)
•	4 db Boosten uranium - 508 OCD
•	4 db Neptunium - 508 OCD
•	4 db Plutonium - 508 OCD
•	1 db Blistering Ingot - 508 OCD

(ezek simán)
•	1 db Sima android 508 OCD
•	1 db Nukleár reaktor 1016 OCD
•	4db reinforced alloy ingot 508 OCD
•	4db redstone alloy ingot 508 OCD 
•	4db carbonado 508 OCD
•	2db essence of soul 508 OCD
•	1db carbonado capacitor 1016 OCD
•	Energized Solar Generator - 1016 OCD
•	Empowered Programmable Android (Normal) - 1524 OCD
•	Electric Jetpack (VII) - 508 OCD
•	Jet Boots (VII) - 330 OCD
•	Multi Tool (VII) - 330 OCD
•	Solar Helmet (ez kell az előző 3 cucc feltöltéséhez) - 508 OCD
•	16db Cargo Motor - 1016 OCD
•	Radiant Backpack - 330 OCD
•	1 db Energized Solar generator: 1016 OCD
•	1 db Nuclear generator: 508 OCD
•	1 db Cobblestone generátor: 1016 OCD
•	4 db Blistering ingot: 330 OCD
•	4 db Afterlife essence: 330 OCD
•	8 db Infused Hopper: 330 OCD
•	1 db Cargo manager: 330 OCD
•	1 db Carbonado furnace: 508 OCD
•	16 db Electric motor: 508 OCD


Továbbá, ha megoldható, egy Soulbound szett, ami az Old szett/eszközök tulajdonságait tudja, esetleg valamivel gyengébb (nem X enchant, hanem max VIII pl.) enchantot birtokol. 1016 OCD / 1 db, esetleg még picivel több is.

**Comment by MrZero1** [comment]
Illetve nem tudom, mi az, amit még Shulkerbe kéne tenni. @poma123 @skrisz0101

**Comment by skrisz0101** [comment]
Kicsit összezavarodtam, többet is 2x írtál full más áron xd

**Comment by MrZero1** [comment]
Mit?

**Comment by skrisz0101** [comment]
Néhányat átírtam xd

**Comment by MrZero1** [comment]
Akkor hát:

(ezt shulkerbe ha megoldható)
• 4 db Blistering Ingot - 508 OCD
(ezek simán)
• 1 db Sima android 330 OCD
• 1 db Nukleár reaktor 508 OCD
• 8db reinforced alloy ingot 508 OCD
• 16db redstone alloy ingot 508 OCD
• 4db carbonado 508 OCD
• 2db essence of soul 508 OCD
• 1db carbonado capacitor 508 OCD
• Energized Solar Generator - 1016 OCD
• Empowered Programmable Android (Normal) - 1524 OCD
• Electric Jetpack (VII) - 330 OCD
• Jet Boots (VII) - 330 OCD
• Multi Tool (VII) - 330 OCD
• Solar Helmet (ez kell az előző 3 cucc feltöltéséhez) - 508 OCD
• 12db Cargo Motor - 508 OCD
• Radiant Backpack - 330 OCD – Ha lehet, Soulbound, akkor 508 OCD
• 1 db Energized Solar generator: 1016 OCD
• 1 db Cobblestone generátor: 1016 OCD
• 4 db Afterlife essence: 330 OCD
• 8 db Infused Hopper: 330 OCD
• 1 db Cargo manager: 330 OCD
• 1 db Carbonado furnace: 508 OCD
• 12 db Electric motor: 330 OCD

**Comment by skrisz0101** [comment]
Energized solar generátor 2x van
Amúgy aaz essence of soul-al mire célzol?
A soulbound rune-ra?
@MrZero1

**Comment by MrZero1** [comment]
Nem tudom 👀

**Comment by skrisz0101** [comment]
Akkoregyen az 2db 508 ocd :D

**Comment by andris155** [comment]
Akkor mi a végleges lista, ami valóban bekerüljön? :D

**Comment by MrZero1** [comment]
Akkor hát:

(ezt shulkerbe ha megoldható)
• 4 db Blistering Ingot - 508 OCD
(ezek simán)
• 1 db Sima android 330 OCD
• 1 db Nukleár reaktor 508 OCD
• 8db reinforced alloy ingot 508 OCD
• 16db redstone alloy ingot 508 OCD
• 4db carbonado 508 OCD
• 2db ancient rune [soulbound] 508 OCD
• 1db carbonado capacitor 508 OCD
• Energized Solar Generator - 1016 OCD
• Empowered Programmable Android (Normal) - 1524 OCD
• Electric Jetpack (VII) - 330 OCD
• Jet Boots (VII) - 330 OCD
• Multi Tool (VII) - 330 OCD
• Solar Helmet (ez kell az előző 3 cucc feltöltéséhez) - 330 OCD
• 12db Cargo Motor - 508 OCD
• Radiant Backpack - 330 OCD – Ha lehet, Soulbound, akkor 508 OCD
• 1 db Cobblestone generátor: 1016 OCD
• 4 db Afterlife essence: 330 OCD
• 8 db Infused Hopper: 330 OCD
• 1 db Cargo manager: 330 OCD
• 1 db Carbonado furnace: 508 OCD
• 12 db Electric motor: 330 OCD

**Comment by andris155** [comment]
kész
https://theold.minemarket.hu/category/slimefunsurvival
https://theold.minemarket.hu/category/slimefunsavsziget
