### ISSUE TITLE
Prémium pet

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#3565]
Leírás utolsó sora írja, hogy a szemfényvesztő nem a jog része.
A képen csontváz van :D 
![Screenshot_20200510_125449_com android chrome](https://user-images.githubusercontent.com/29951969/81497264-a8ff4f80-92bd-11ea-9585-ea88e48fb313.jpg)

**Comment by andris155** [comment]
Javítottam. köszi.
