### ISSUE TITLE
slimefun láda

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#3568]
**Szerver**:  Szurvi.
Mivel kirak a rákba a szerverről, ha könyvbe írok, muszáj ide írnom xd

Slimefun láda felesleges dolgai:
ender helmet
multi tool I
flask of knowedge
organic food
tiny pile of uranium
24 karátos arany blokk
nyírfalevél
port jerky
battery
gold pan

egy fajta táska elég lesz benne,
cargo managerből csak 1db legyen benne, mert az sokat ér

ancient pedestal 1 helyett lehetne 8db, mert egy ancient altarhoz 8db pedestal kell

,,felesleges" cuccok helyett jó lenne szerintem:
GPS transmitter
reinforced sword
3db outpot chest
5db electromagnet
4db hardened glass
electric jetpack III
Multi tool III
2db medium energy capacitor
5db magic sugar
grandpas walking stick
4db cargo motor
32 ender lump II

Esetleg a régi Lucky szett is bekerülhetne a ládába kisebb enchantokkal. pl VII-esekkel.

**Comment by MrZero1** [comment]
Kész.
