### ISSUE TITLE
Savsziget --> Survival armor bug

### ISSUE THREAD

**Issue by Shryxx** [andris155/TheOld-Crafters#3569]
**Szerver**: Survival
Ha savszigetről átmegyek survivalra a /survival paranccsal, akkor ha pl. old szett volt rajtam megmarad a + élet izé és az armor is. 
![2020-05-10_21 30 15](https://user-images.githubusercontent.com/65125529/81508640-8c870580-9305-11ea-9e7b-33a0fb0b6892.png)

**Comment by andris155** [comment]
Már jelentett hiba. Lépj ki majd be és az megoldja.
