### ISSUE TITLE
MyPet plugin hiba

### ISSUE THREAD

**Issue by Icecroft** [andris155/TheOld-Crafters#357]
Bármelyik láma színe fehérre változik a befogás után. /petrelease után is fehér marad.

**Comment by andris155** [comment]
Most is él a hiba?

**Comment by Icecroft** [comment]
Annyi változott, hogy a láma megtartotta a színét a befogás után, viszont a /petrelease után fehér lett.
Van egy másik probléma még a pluginnal: korábban jobb klikk a petre azt jelentette, hogy ne kövessen, ez most már nem működik a régi petekkel sem. Ez a lehetőség az 1.11-re váltáskor tűnt el, nem a tegnapi plugin upgrade után.

**Comment by andris155** [comment]
Shift+jobb klikkel elvileg nem követ.

**Comment by andris155** [comment]
Az a hiba még él, hogy ha elengeded a lámát bármilyen típusu volt, mindig fehér lesz?

**Comment by Icecroft** [comment]
Ha a 10 nappal ezelőtti plugin upgrade óta nem változott semmi, akkor él.

**Comment by andris155** [comment]
Nem lehetne tesztelni? :D

**Comment by Icecroft** [comment]
A teszthez kellene egy nem fehér láma is :)
Ma délután megpróbálok felhajtani egyet.

**Comment by Icecroft** [comment]
1 perce teszteltem, a barna láma még mindig átváltozik fehérré a /petrelease után

**Comment by andris155** [comment]
javítva

**Comment by andris155** [comment]
https://github.com/xXKeyleXx/MyPet/issues/934
