### ISSUE TITLE
Savsziget /shop

### ISSUE THREAD

**Issue by Shryxx** [andris155/TheOld-Crafters#3570]
**Szerver**: Savsziget
/shopban lehetne sf-es rész, ahol pl. dustokat lehetne eladni.

**Comment by Icecroft** [comment]
A másik javaslatom a kvarc árának változtatása, egy Energized solar generátorhoz 18 stack kvarc kell, ami itt kb 250k-ba kerül, a survival szerveren 15 perc munka, vagy kb 50k a piaci ára.
Itt a savon kvarc esetén a /shopnak nincs még alternatívája sem.
A javaslatom, hogy ne 2 Netherkvarc kerüljön 100$-ba, hanem legalább 8.

**Comment by D4nii** [comment]
Akkor már adnék egy harmadik javaslatot is, beszállok én is a shop fejlesztésbe. Ugye a kőgenerátorokba bekerült egyebek közt a soder és a szén is, amik elég nagy mennyiségben esnek is belőle. Elég sok hely lenne őket tárolni, viszont eladni nem lehet. Ezen lehetne javítani azzal, hogy /shoban el lehetne  ezeket is adni, akár alacsony áron

**Comment by Icecroft** [comment]
Támogatom D4nii javaslatát, de a sóder és a szén a slimefun alapanyaga, nincs az a mennyiség ami elég lenne belőle.

**Comment by MrZero1** [comment]
@andris155  elküldtem privátba a doksit.

**Comment by andris155** [comment]
Köszi

**Comment by andris155** [comment]
Hétvégén megcsinálom.

**Comment by andris155** [comment]
A jelenlegi shop plugin ellenőrzi a nevet, szóval egyelőre ez nem fog bekerülni még egy ideig. Majd írok a fejlesztőnek, de lehet át kell írni egy másik plugin-ra a boltot.

**Comment by andris155** [comment]
A jelenlegi shop plugin nem ellenőrzi a a tárgy nevet eladásnál, szóval egyelőre ez nem fog bekerülni még egy ideig. Majd írok a fejlesztőnek, de lehet át kell írni egy másik plugin-ra a boltot.

**Comment by andris155** [comment]
Van egy speciális NBT a Slimefun tárgyakon egyelőre ezt nem tudja nézni a plugin. Már írtam a fejlesztőnek ezzel kapcsolatban.

**Comment by andris155** [comment]
Ezt írta a fejlesztő:
> NBT values aren't support by shopgui+ yet. This feature will be most likely added by the end of July.

**Comment by Icecroft** [comment]
Andris, a dustok és egyéb Sf dolgok eladását nem kell feltétlen a /shop-ba beépíteni, az is megoldás, ha egy egyszerű ládás-felvásárlást nyittok a /warp  slimefun-on, esetleg az sf cserekereskedő mögött.

**Comment by andris155** [comment]
Hát a Chestshop biztosan támogatja. Admin bolttal meg lehetne oldani.

**Comment by MrZero1** [comment]
Kész van. A Slimefun warpon, bal oldalt van egy nyomólap ami elvisz a bolt részhez. 
![kép](https://user-images.githubusercontent.com/29709854/85204230-57fa6680-b313-11ea-8e11-2bf9c23a97ab.png)
