### ISSUE TITLE
Savsziget, kőgenerátor - cargo

### ISSUE THREAD

**Issue by Raxoray** [andris155/TheOld-Crafters#3571]
Savszigeten ha a kőgenerátornál a láva alá tesszük az inputot, hogy az kihúzza a tölcsérből a dolgokat, és kiütjük a legenerált érceket, nem generál többet egyátalán az input miatt, poma megnézte látta hogy tényleg az a hiba, amint raktam egy blockot az input helyett jól működött.

**Comment by andris155** [comment]
Valahol meglehet nézni ezt a rendszert?

**Comment by Raxoray** [comment]
Amikor fentvagy és látsz fent engem a szerveren Trymer néven szólj, és megcsinálom úgy hogy volt.

**Comment by andris155** [comment]
Kérlek írd le inkább vagy készítsd róla képet. Ne arra várjunk, hogy éppen valamilyen szerencse folytán éppen akkor megyek fel, amikor te.

**Comment by Raxoray** [comment]
A kőgenerátor úgy néz ki hogy a víz folyik egy blocknyit előre majd lefelé, középen lesz a generált anyag, másik oldalon pedig a láva. Ha közvetlen a láva alá rakjuk bármelyik Cargot(annak érdekében hogy egyből a tölcsérből szívja ki a cuccokat) akkor nem fog generálni semmilyen anyagot.

**Comment by andris155** [comment]
Ha megépíted a szigeteden és odaírod valami táblával, hogy ez a hibás akkor megnézem. De így nekem erre nincs időm, hogy kitaláljam mi is ebben a hiba vagy hogy lehet pontosan.
