### ISSUE TITLE
Kőgenerátor

### ISSUE THREAD

**Issue by KriszLOW** [andris155/TheOld-Crafters#3572]
Savsziget:

Módosítani kéne kőgenerátornál a cobblestone drop rate jét mert keveset ad főleg most hogy bejött a slime fun 10 perc átlagba 3,5 stack!

**Comment by Raxoray** [comment]
Persze ezt úgy érti hogy tízezres szint felett, 
Igen, ezt már én is akartam mondani 10 ezres szint felett az a 18% amit ír a paranccsal ennyit ad átlagban.

**Comment by Icecroft** [comment]
A slimefun cobblestone generátor géppel ez a probléma megoldódik, csak addig kell kihúzni, amíg lesz olyanod. Ha megemelkedik a kövek rate-je, később azt sajnálod, hogy inkább hasznosabb dolgok jönnének.

**Comment by KriszLOW** [comment]
Probléma megoldva most tudtam meg ki lehet kapcsolni az ércek generálást is settings-be!
