### ISSUE TITLE
Survival- Slimefun

### ISSUE THREAD

**Issue by mnbTOC** [andris155/TheOld-Crafters#3575]
Survival szerver, Most véletlen egy missclick által rájöttem hogy az Infused magnetet le lehet helyezni a földre valamiért.. Eredetileg nem lehet (Dc-n utánakérdeztem az SF csoportban :D)

-mnb

**Comment by andris155** [comment]
Más ilyen blokkok is biztosan vannak. OCD-ért szerintem megérné végig próbálgatni valakinek.

**Comment by andris155** [comment]
,,Your issue is not a bug, please only use this issue tracker to report bugs. Any other kind of communication should happen on discord."

**Comment by andris155** [comment]
Írhatsz nekik Discord-on, de szerintem nem nagyon érdemes ezzel foglalkozni. Ha lerakod és kiütöd nem veszik el. https://discord.gg/fsD4Bkh
