### ISSUE TITLE
Survival - könyv írás

### ISSUE THREAD

**Issue by Niccolettie** [andris155/TheOld-Crafters#3576]
Szerver: Survival

-Ha könyvbe írunk és a "kész"-re nyomunk akkor kidob a szerver.
-Ha könyvbe írunk és törölni akarunk belőle akkor crashel a játék.
-Ha könyvbe írunk és "befejeznénk, aláírnánk", kidob a szerver.

**Utóirat: Senki ne törölje ezt a jelentést, mert 20 percig kerestem az előzőt, hogy újra nyissam, de nincs meg, és legközelebb nem fogom jelenteni, pedig elég fontos HIBA!!!!!!!.**

**Comment by skrisz0101** [comment]
Már egyszer én is jelentettem #ikszdé

**Comment by andris155** [comment]
Mivel már javítva van gondolom azért volt törölve.
