### ISSUE TITLE
Survival spectator hiba.

### ISSUE THREAD

**Issue by Shryxx** [andris155/TheOld-Crafters#3577]
**Szerver**: Survival
Ha gm 3-ban rá teleportálunk valakire, aki épp eventen van, át rak valami gm 0-ba. Elég kellemetlen :(

**Comment by andris155** [comment]
Poma plugin-ja miatt volt legutóbb ilyen. Vele beszélj. Elvileg csinált rá javítást. Nem tudom, hogy volt-e tesztelve.

**Comment by Shryxx** [comment]
Azt mondta, hogy ő javította. Valami mégsem jó

**Comment by andris155** [comment]
Majd megnézem akkor ezt is.

**Comment by andris155** [comment]
A remove-fly-n-gm: true flag veszi el, ami poma pluginjában van.

**Comment by poma123** [comment]
dehát hogy a rákba

**Comment by andris155** [comment]
Mert gondolom a remove-fly-n-gm-group lett megcsinálva, de a  remove-fly-n-gm meg nem (?)

**Comment by poma123** [comment]
Nem :D

**Comment by poma123** [comment]
Jobban megnézhetted volna a levédés flag-eket.
![image](https://user-images.githubusercontent.com/25465545/81932070-6a360600-95eb-11ea-98d7-3443d115d62a.png)

**Comment by poma123** [comment]
Ahol még ilyen akkor szóltok, és javítom. :D

**Comment by poma123** [comment]
Kapott a helper rang bypass jogot a remove-fly-n-gm flagre mindenesetre.

**Comment by andris155** [comment]
Nem volt köze ennek a flag-hez hozzá.

**Comment by poma123** [comment]
De volt köze :D

**Comment by andris155** [comment]
Azon a pár védésen ahol van ott igen. De nem ilyen védésen teszteltem.

**Comment by poma123** [comment]
hanem hol tesztelted?

**Comment by andris155** [comment]
Simán rá tp-ztem a világra egy random helyre.

**Comment by poma123** [comment]
Ne kreatívmódban tesztelt, hanem spectator módban. A kreatívból átrak túlélőbe mindenkit :D

**Comment by andris155** [comment]
Az lehet. Akkor azon a pár védésen lesz probléma csak a game-mode flag valóban.

**Comment by andris155** [comment]
A bypass jog szerintem nem kell akkor így.

**Comment by poma123** [comment]
Oké, majd ha hozzáférek a szerverhez a netprobléma után elveszem.
