### ISSUE TITLE
Veteményes hiba telkeken..

### ISSUE THREAD

**Issue by Shryxx** [andris155/TheOld-Crafters#3578]
**Szerver**: Survival
Telkeken nem lehet kiugrálni a veteményest.

**Comment by Niccolettie** [comment]
Ne taposd le a kukoricát!

**Comment by andris155** [comment]
Jelentettem a fejlesztőnek, de szerintem nem mostanában kerül javításra. Meg ez annyira nem fontos dolog. OCD-t azért adtam érte.

**Comment by andris155** [comment]
Vagyis csak adnék mert fogalmam sincs mi a MineMarket nevet.
