### ISSUE TITLE
Pathfinding hiba moboknál

### ISSUE THREAD

**Issue by Csinka** [andris155/TheOld-Crafters#3579]
**Szerver**: Savsziget
Nagyon nehezen találnak utat a játékos felé a mobok, körbe körbe forognak, cikk-cakkban járkálnak így nehéz őket elcsalogatni a helyükre, mindegy hogy ellenséges vagy neutrális mobról van szó. Néhány hete vettem észre a hibát, előtte minden oké volt.

**Comment by andris155** [comment]
A féllapokon szokták ezt csinálni. Ahogy néztem nagyrészt abból áll a szigeteden az út. Cseréld le egész blokkokra.
