### ISSUE TITLE
SF dustok stackelődése

### ISSUE THREAD

**Issue by Shryxx** [andris155/TheOld-Crafters#3580]
**Szerver**: Survival
Tegnap az egyik kifagyás óta nem stackelődnek a dustok. Chaten is látható, másnak is ez van.
![2020-05-15_09 08 43](https://user-images.githubusercontent.com/65125529/82021856-eb44da00-968b-11ea-9bcc-db9e7c6b835c.png)

**Comment by Raxoray** [comment]
Savszigeten is jelen van a hiba.

**Comment by Shryxx** [comment]
Mikor lesz vége a folyamatos leállásnak?! Elég idegesítő már

**Comment by poma123** [comment]
Holnap betölt.

**Comment by andris155** [comment]
Már más jelentette a hibát a Slimefun-nak előbb.
