### ISSUE TITLE
Weboldal elírás

### ISSUE THREAD

**Issue by Raxoray** [andris155/TheOld-Crafters#3581]
4.6 (Savsziget), Az ércblokkok lerakása engedélyezett. [Szint limit aktív.]

A [Szint limit aktív]-ot célszerű lenne levenni ennek a szabálynak a végéről, mivel régen volt de már nincsen ez a szintlimit az ércblokkoknál, annó maximum 10 gyémántblock adott szintet, most bármennyi és ez érvényes a többi blockra is.

**Comment by andris155** [comment]
kész
