### ISSUE TITLE
Minemarket - Old szett

### ISSUE THREAD

**Issue by Shryxx** [andris155/TheOld-Crafters#3582]
**Szerver**: Survival, Savsziget
Ha már van hátralökés nélküli és hátralökéses kard is, lehetne tüskék nélküli páncél is. Elég hamar kopik így és akinek nincs fix joga kéregethet nagyobb rangosoktól, vagy tehet rá önjavítást ami tönkreteszi a szép nevét :(

**Comment by andris155** [comment]
Nem szeretném ennyire megkeverni ezt.
