### ISSUE TITLE
Survival cooler izé

### ISSUE THREAD

**Issue by Shryxx** [andris155/TheOld-Crafters#3586]
**Szerver**: Survival
Coolerből nem lehet kivenni a húst 
![2020-05-27_03 58 05](https://user-images.githubusercontent.com/65125529/82968791-66808700-9fce-11ea-9a81-0a2963165dab.png)

**Comment by poma123** [comment]
Azóta se jó?

**Comment by andris155** [comment]
Hétvégén tudom tesztelni majd illetve jelenteni ha valóban nem jó.

**Comment by andris155** [comment]
Csak Juice-kat lehet belerakni. Nem tudom, hogy a húst neked hogy sikerült beletenni. Nekem beletenni se sikerült nem hogy kivenni.
https://github.com/TheBusyBiscuit/Slimefun4/wiki/Cooler
https://github.com/TheBusyBiscuit/Slimefun4/wiki/Juices

**Comment by andris155** [comment]
Akinek esetleg kell kitudom venni belőle a dolgokat, ami nem bele való és nem lehet kivenni.
