### ISSUE TITLE
Levédésblokk "trade"

### ISSUE THREAD

**Issue by poma123** [andris155/TheOld-Crafters#3587]
**Szerver**: Survival

Megint gondolkodtam, és beugrott az ötlet, hogy nem lenne rossz egy ilyen.
Szimpla parancs, meg kell adni az értéket és a játékost, majd egy megerősítő parancs.
Ha a megtörténik a megerősítés, akkor a küldő játékostól el lesz véve a megadott levédésblokk, illetve annak a játékosnak lesz adva, akinek a küldő elküldte.
**Természetesen csak azokat a levédésblokkokat engedné elküldeni, ami nincs felhasználva levédésre.**

Lenne erre igény?

Szavazás:
👍 = igen
👎 = nem

**Comment by poma123** [comment]
Inkább nem lesz ilyen.

**Comment by skrisz0101** [comment]
Sk szavazata 2-t ér
Döntetlen

**Comment by andris155** [comment]
Az admin és tulaj szavazata többet ér 2-nél is.

**Comment by poma123** [comment]
Miután már lezártam, tökmindegy ki szavaz rá :D :D :D
