### ISSUE TITLE
Jármű plugin!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#3590]
**Szerver**:  Szurvi, (sav)
Már egy ideje fejlesztették 1.15-re, szóval szerintem simán bekerülhetne.
Minemarketet tuti sokan vennék xd
De akár lehetne beváltóban alapabb jármű + A drágább ládákban közepesen jó 
Vagy akár voteshop-ban is 1db
ahogyl áttam, bővítették a  járműveket pár darabbal, tuti bírnák a játékosok :D

https://www.spigotmc.org/resources/%E2%9C%88%EF%B8%8Fvehicles-no-resourcepacks-needed.12446/

**Comment by andris155** [comment]
Túl sok plugin van már így is. Nem fog bekerülni.

**Comment by skrisz0101** [comment]
dobj ki valamit, helyette bekerül

**Comment by MrZero1** [comment]
Pedig milyen jó is volt ez. 😢
