### ISSUE TITLE
Fő a szeretet!!

### ISSUE THREAD

**Issue by Shryxx** [andris155/TheOld-Crafters#3591]
**Szerver**: Survival
![2020-06-03_11 17 46](https://user-images.githubusercontent.com/65125529/83619388-18e6ba00-a58c-11ea-9be2-331f325a3cc3.png)

**Comment by andris155** [comment]
javítva

**Comment by andris155** [comment]
kinek adjam az OCD-t?

**Comment by Shryxx** [comment]
Surviornak. Ő találta meg, én csak jelentettem
