### ISSUE TITLE
Shopkeepers fordítás frissítése

### ISSUE THREAD

**Issue by andris155** [andris155/TheOld-Crafters#3595]
**Szerver**: Savsziget, túlélő

`[Shopkeepers] Could not find language file 'plugins/Shopkeepers/language-hu.yml'!`

**Comment by Niccolettie** [comment]
Valami bővebb infó erről esetleg? :D

**Comment by andris155** [comment]
A konfigból át kell írni egy új fájlba. Semmi extra. :D

**Comment by andris155** [comment]
kész
