### ISSUE TITLE
/tpauto. Survival

### ISSUE THREAD

**Issue by mnbTOC** [andris155/TheOld-Crafters#3596]
Ha event végén vagy. és be van kapcsolva a /tpauto (Automatikus tp fogadás) akkor aki rád tp-zik azt odahozza az event végére.

![2020-06-11_06 47 36](https://user-images.githubusercontent.com/32791069/84346099-793eb280-abaf-11ea-8ce2-17a1cfa6ec40.png)

**Comment by poma123** [comment]
Javítva

**Comment by andris155** [comment]
Mi volt rá a javítás?
