### ISSUE TITLE
Sf kitanulási hiba

### ISSUE THREAD

**Issue by maryhonaly** [andris155/TheOld-Crafters#3597]
1.15.2, survival, sf

Többen jelezték ma kezdő játékosok közül, akik még nem rendelkeznek semmi sf-ből kitanult dologgal, hogy bármilyen blockot ütnek akárhol, akármivel, bejelez, hogy “nincs elég ismereted ennek a megértéséhez”. Próbálgattuk: puszta kéznél nem, ha sima vascsákánnyal üt bármit jelez, ha szénnel üt földet, akkor is. 
Nagyon zavaró nekik, hogy minden kiütött blocknál spameli a chatet.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by andris155** [comment]
Holnap jó lesz.

**Comment by andris155** [comment]
javítva
