### ISSUE TITLE
Nub ajtók

### ISSUE THREAD

**Issue by Shryxx** [andris155/TheOld-Crafters#3600]
**Szerver**: Survival
Néha gondol egyet az ajtó és nem lehet becsukni. Ha megpróbálod kiütni akkor is csak a sokadik próbálkozásra engedi.
**Ui.: MÉG MINDIG NINCS BÚJÓCSKA SCOREBOARD**
Ui.2: Ha reprodukálni szeretnéd akkor el kell indíts egy bújócskát. **Nem a várakozóban kell nézni hanem ha JÁTÉKBAN VAGY**

**Comment by Shryxx** [comment]
Ui.3: Kipróbáltam mind a 6 fa ajtóval, és csak a sima tölgy nem kezdett el bugolni, tegyél köré blokkokat, csak akkor csinálja.

**Comment by andris155** [comment]
Nem sikerült reprodukálni az ajtós hibát. A másikkal nincs időm foglalkozni. Fél nap debug lenne, és kiderülni úgyis, hogy a plugin hibája. A fejlesztője pedig nem nagyon foglalkozik és zárt kódú. Nem nagyon látom értelmét erre időt rászánni.

**Comment by andris155** [comment]
Nem sikerült reprodukálni az ajtós hibát. A másikkal nincs időm foglalkozni. Fél nap debug lenne, és kiderülne úgyis, hogy a plugin hibája. A fejlesztője pedig nem nagyon foglalkozik vele, és zárt kódú is. Nem nagyon látom értelmét erre időt rászánni.

**Comment by Shryxx** [comment]
Tettél keretet az ajtó köré? @andris155 Mert csak akkor fog menni az ajtós cucc. Valamilyen blokkból kell keret köré.

**Comment by andris155** [comment]
és miért nem lehetett normálisan hibát jelenteni és egyből beleírni pontosan mikor történik ez?

**Comment by Shryxx** [comment]
Hát bocs. Akkor legközelebb majd nem lesz jelentve.

**Comment by andris155** [comment]
javítva
