### ISSUE TITLE
Gm 1 ből Gm 0 ból való átlépéskor a fly megszünik, és elkezd a player zuhanni

### ISSUE THREAD

**Issue by SurvivorTheReal** [andris155/TheOld-Crafters#3601]
Szerver:Survival

Ha átváltok Gm 0 ra és a levegőben vagyok, akkor mintha be se írtam volna a /fly parancsot, elkezdek lezuhanni.
Ez igazából csak zavaró tényező ami azzal jár hogy ha átlépsz gm 0 ba akkor lezuhansz, aztán beírod a /fly-t, aztán pedig felrepülsz arra a helyre ahol éppen lebegtél.
Mindenesetre lehetnek helyzetek ahol a /god beírásának elfelejtésével meg is lehet halni.
Például aki endben épít gm 1 el, annak se épp biztonságos, ha ott leesik, akkor elveszik mindene ami nála van és nem soulboundos. Mivel már nem tünnek el a cuccok a gm 0-ás inventoryból, így nyugodtan lehet esetleges eszközök tárolása abban az inventoryban. Gondolok itt silk touchos eszközökre, esetleg old eszközökre, illetve slimefunos eszközökre és gépekre.

**Comment by andris155** [comment]
Mivel a túlélő módnak nem része a fly ez ezért ilyen. Ez nem hiba.
