### ISSUE TITLE
HG poti színek

### ISSUE THREAD

**Issue by SurvivorTheReal** [andris155/TheOld-Crafters#3602]
Szerver:Survival

Utóbbi napokban sokat hunger gameseztünk, és feltünt, hogy a poison poti színe ugyanolyan mint a regen potié, de minimum nagyon hasonlóak.
Hunger gamesen kívül pedig eltérő, a poisonos poti zöld, a regen potié pedig a megszokott színű.

**Comment by poma123** [comment]
Probably Hg plugin hiba, vagy config hiba

**Comment by poma123** [comment]
Javítva, minden poti megkapta a saját vamilla színét.
Köszi a jelentést

**Comment by andris155** [comment]
Köszönjük @poma123
