### ISSUE TITLE
Activator rail

### ISSUE THREAD

**Issue by SurvivorTheReal** [andris155/TheOld-Crafters#3604]
Szerver:Survival

Az adott chunk/chunkok betöltésénél random, van néhány activator rail ami ha jelet kap, úgy marad, mintha folyamatosan lenne rajta egy csille, de nincs.
Ez 15:10 kor készült kép(egy ilyen rail van a képen a mostani 2 ből):
![2020-06-16_15 10 25](https://user-images.githubusercontent.com/39741913/84778821-cffb2080-afe3-11ea-8271-ffdd6fe92708.png)

Ma dél és 1 között vettem ezt észre, nem tudom mióta áll fenn. De akkor 3 másik rail volt ilyen állapotban.
Továbbá nem segít ha kitüöm, és újra leteszem.

**Comment by andris155** [comment]
Ezen folyamatosan megy a csille oda-vissza?
