### ISSUE TITLE
Kreatív - Survival

### ISSUE THREAD

**Issue by Niccolettie** [andris155/TheOld-Crafters#3605]
Már az összes bugyrom tele van a kreatív korlátozással... Nem lehet:

Sf miatt lett tiltva (a pipált, az már azóta feloldva):
- [x] csapóajtót kinyitni/becsukni/kiütni
- [x] üstöt kiütni
- [x] vizet rakni az üstbe
- [x] kidobót/adagolót kiütni

Kreatívvédelem által tiltva (@andris155):
- [x] eszközkeretet lerakni
- [ ] virágot rakni cserepekbe
- [ ] tölcsért lerakni
- [x] jelzőfényt lerakni
- [x] páncélállványt lerakni
- [x] lámpást lerakni

Én személy szerint azért vettem meg az Old rangot, hogy kreatívba tudjak építeni, de ha minden dekoráláshoz szükséges funkció le van tiltva, akkor finoman fogalmazva kitörölhetem a popómat a krea jogommal :) marhára eldurran az agyam (és nem csak nekem) amikor a 125. alkalommal kell /gm 0 után /gm1 aztán /gm 0 és stb, mert be kell csuknom a csapóajtót, vagy lámpást akarok lerakni, stb. Értem, hogy lehet vele bugoltatni, meg az sf-es gépeket is lehet mit tudom én mit csinálni, és azt is értem, hogy egyszerűbb mindent letiltani, de egy idő után el fog fogyni a lehetőség, amit le tudtok tiltani, és nem lesz semmi értelme a kreatív jognak, mert egy idő után már csak az alap blokkokat tudjuk csak lerakni, azért meg felesleges lesz megvenni az old rangot :D

**Comment by andris155** [comment]
Egy részét poma plugin-ja tiltja. Vele kellene beszélned, hogy a Slimefun dolgok miatt ne globálisan tiltsa a dolgokat kreatívban, hanem nézze meg, hogy valóban Slimefun-os blokk a tiltás előtt.

**Comment by skrisz0101** [comment]
mézblokk, harang is tiltva van (sztem indokolatlanul)

**Comment by poma123** [comment]
Minden sf-es eddig tiltás kizárólag az sf-es blokkok/itemekre korlátozódott, szóval ami sima, azt nem tiltja le.

**Comment by andris155** [comment]
Megteszem majd.

**Comment by Niccolettie** [comment]
Köszönöm szépen mind a kettőtöknek <3

**Comment by andris155** [comment]
Engedélyeztem jó pár dolgot, de mindent.

**Comment by andris155** [comment]
Engedélyeztem jó pár dolgot, de nem mindent.

**Comment by skrisz0101** [comment]
@andris155 amit én írtam? :c

**Comment by andris155** [comment]
Majd nézd meg. :D
