### ISSUE TITLE
Luckyblock - Cs-corelib feje

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#3606]
**Szerver**: szurvi (+sav?) 
A luckyblock Cs-corelib fejét dob

**Comment by poma123** [comment]
Régebbi sf került fel, legfeljebb holnap betölt :)

**Comment by andris155** [comment]
Nem maradhatunk a régi verzión sokáig. Már csak hetek kérdése az 1.16 és jó lenne majd frissíteni a szervert rá.

**Comment by andris155** [comment]
A dispsenser-t a régi verzió sem oldja meg.

**Comment by poma123** [comment]
már megint ez a szerverfrissítős mizéria.
de szeretem :)

**Comment by poma123** [comment]
holnap betölt
