### ISSUE TITLE
Csillék eltünnek egy bizonyos szám után

### ISSUE THREAD

**Issue by SurvivorTheReal** [andris155/TheOld-Crafters#3607]
Szerver:Survival

Egy bizonyos számú csille után egy bizonyos területen belül (nem tudom mekkora ez a terület, lehet hogy csak egy chunkon belül) eltünnek a csillék, amiket a "határ" után rakok le.
Kérdés: ez szándékosan van lekorlátozva mint a pistonok? vagy bug?
Elismerem hogy a chunkonkénti 100 piston korlát észszerű.
Van egy farm amit automatára akarok csinálni, elég nagy farm, és mivel pistonnal nem tudom kiütni a dinnyéket, így a flying machine+vasrács+hopperes csille kombót használom.
Nos, még a felénél se vagyok a folyamatnak, de, már nem tudok csillét lerakni.
Megjegyzés: egyeltalán nem akarom az összes csillét egyszerre mozgatni, maximum 4 flying machine menne egyzerre, ami 8 csillét jelent.
@andris155

**Comment by poma123** [comment]
Szerintem már nincs akkora lag a szerveren, mint ami a váltás előtt volt, szóval feljebb lehetne vinni az entitás korlátozásokat.

**Comment by andris155** [comment]
Nem lesz jó vége, ha ilyen brutális nagy farmokat építesz. Miattad nem csak a te farmod lesz még jobban korlátozva, hanem mindenkié.

**Comment by andris155** [comment]
Növeltem a limitet.
