### ISSUE TITLE
szomjúság

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#3608]
**Szerver**:  szurvi, sav
Régen HardcoreX-en volt szomjúság plugin, szerintem bekerülhetne szurvira és savszigetre is, dobna a játékélményen. emellé a sörfőzés plugin is mehetne, ez a kettő együtt mégjobb :D

**Comment by poma123** [comment]
Már volt ötletként, és a scoreboard összeakadások miatt le lett szavazva.
