### ISSUE TITLE
BuildUp event ötlet.

### ISSUE THREAD

**Issue by Shryxx** [andris155/TheOld-Crafters#3609]
**Szerver**: Survival
BuildUp eventen lehetne egy blokk vétel tábla (mint spleefen az ásó), hogy a játékosoknak ne saját blokkot kelljen hozni. Például X zúzottkövet 50$-ért, vagy akármit.

**Comment by MrZero1** [comment]
Rakhatok, de akkor letiltom az invet, és csak üres invvel lehet jönni. Így is legyen?

**Comment by MrZero1** [comment]
![kép](https://user-images.githubusercontent.com/29709854/85203354-7a898100-b30d-11ea-884b-29da7ec0c5b1.png)
Kész van, most már üres invvel lehet menni az eventre, és 2 fajta blokkot és 2 fajta csákányt lehet venni minimális összegért. 
Ezeket az eventen belül lehet, hogy ne legyen az, hogy eventen kívül bárki megtudja venni ezeket majd eladni a boltba, máshol.

**Comment by andris155** [comment]
köszönjük
