### ISSUE TITLE
Shulker box

### ISSUE THREAD

**Issue by NBabi** [andris155/TheOld-Crafters#361]
Ha leteszek egy shulker boxot kreatívban, majd kiütöm, akkor nem eltűnik, hanem droppolódik, mintha survivalba ütöttem volna ki, ezután ha átváltok survivalba, fel tudom venni a shulker boxot és sima survival itemként kapom meg, és ha lerakom majd felszedem, akkor sem válik kreatívos itemmé.

**Comment by andris155** [comment]
Igen ezért van tiltva kreatívban a kiütése. Persze Adminnak nincs tiltva. :D
