### ISSUE TITLE
Scoreboard ütközések

### ISSUE THREAD

**Issue by andris155** [andris155/TheOld-Crafters#3610]
**Szerver**: túlélő

A szerveren sok dolog és plugin használ scoreboard-ot. Bizonyos helyeken így valószínűleg kiütik egymást ezek így nem jelenik meg a scoreboard.

Ismert helyek: Bújócska

Ezt viszonylag nehéz tesztelni, mert több játékos kell hozzá illetve a szerver teljes másolata. Ha lesz időm fogom tesztelgetni majd még bővebben.

**Comment by skrisz0101** [comment]
Nem csak minigamekon és eventeken van?
Azok meg elv nem tudnak ütközni

**Comment by andris155** [comment]
Nagyon nem

**Comment by andris155** [comment]
Igazából egy halom plugin használja. Nem csak az oldalsó menü rész a scoreboard, hanem még egy halom dologra lehet használni, amit pluginok sőt még a szerverfájl is használ.

**Comment by andris155** [comment]
Az mcMMO plugin miatt nem működik sajnos. De ez a HideAndSeek hibája elsősorban. A fejlesztőnek megírtam, de több mint 2 hete nem volt a Spigot-on fent. Lehet ezt már sosem fogja javítani. Kérdéses az is, hogy egyáltalán működni fog-e az 1.16-on ez a plugin.
