### ISSUE TITLE
Láva lerakás

### ISSUE THREAD

**Issue by Shryxx** [andris155/TheOld-Crafters#3611]
**Szerver**: Survival
Segítők, és/vagy moderátorok nem kaphatnának jogot láva lerakáshoz? Nem kellene mindig adminokra várni, és zaklatni sem kellene őket miatta :D

**Comment by Shryxx** [comment]
Eh.. Fejlesztés cucc lemaradt valahogy.

**Comment by andris155** [comment]
Moderátortól nem lenne rossz. @MrZero1 neked mi erről a véleményed?

**Comment by MrZero1** [comment]
Moderátortól lehet Survivalon.

**Comment by andris155** [comment]
Csak elég összecsapott módon volt beállítva eddig.

**Comment by poma123** [comment]
Most csinálom éppen...

**Comment by andris155** [comment]
Legközelebb kérlek ne csapd össze dolgokat. Megcsináltam normálisan.
