### ISSUE TITLE
Slimefun bővítmények

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#3612]
**Szerver**:  Szurvi, sav (bááár, sav attól függ)
Teszt szerón kipróbáltam pár sf addont, volt ami be se töltött, volt ami nem rossz, de volt pár ami egész jó :D 
Le is írnám miket néztem és hogy miért lenne jó/ nem jó

1.: Slimy TreeTaps
Ez az addon kb csak arról szól, hogy könnyebben lehessen plastic sheetet szerezni, semmi másra.
(Akár automatizálva) ez nagy segítség lenne sokak számára, mert eléggé necces a szerzése, chunkonként kell pakolgatni folyamatosan a fluid pumpot, ez eléggé leegyszerüsítené (persze nem 2 földért) - Szóval szerintem ez nagyon jó lenne

2.: SounfMuffler
Az egész addon egy dologból áll. árammal működik, és a 8blokkos környezetében tudod állítani a hangzást. pl ha 0-ra állítod, teszel mellé egy withert, meg se fog szólalni. szerintem tud hasznos lenni néhány esetben, de szerintem mindenki megvan nélküle. - Tőlem jöhet, kárt nem okoz

3.: Mob capturer
Ez egy nagyon jó addon. Craftolni kell egy ,,Mob capturing pellet"-et, egy ,,Mob capturing Cannon"-t, és ha a cannonnal rálősz bármilyen mobra (bossokat kivéve), akkor apró tojásba zárja őket, amit lerakhatsz. (sokkal jobb megoldása a mobok cipelésének, mint a pet, pláne hogy tagoknak csak 1 petje lehet) - Szerintem ez az itteni addonok közül az egyik leghasznosabb, remélem bekerül :D 

4.:  TransEndence
Túlkomplikált, nem kell, felesleges

5.:  LiteXpansion
Hát, ez az addon azért több dolgot hozott be mint az eddigiek.
először is van egy cargo configuratier, ami eléggé hasznos ha valaki ugyanazt a cargo beállítást szeretné több cargon.
másodszor, van egy új kard és egy új mellvért, ami árammal megy. a kard eléggé sokat sebez ha  fel van töltve, a mellvért meg elhárít minden sebzést ha fel van töltve.
Harmadszor, lehet készíteni úgynevezett ,,UU-Matter"-t bármilyen itemből egy elektromos gépben.
Beleteszel nethercsillagot, földet, mindig az lesz belőle. Ebből az ,,UU-matter"-ből lehet jópár alap minecraft itemet craftolni (képet csatolok) nézzetek rá majd, ezt át kell gondolni
Negyedszer, elég op solar generátorok is bekerültek, ezen még gondolkozom hogy nem-e túl op
![2020-06-19_21 34 47](https://user-images.githubusercontent.com/29951969/85173996-c20ffe80-b274-11ea-9037-3a458884e9a4.png)
A receptek 1-9 UU-matterből állnak. item értékétől függ hogy mennyi. Pl a gyémánt 9db, a gyapjú 3

6.: ExtraHeads.
Nem tudom van-e bent mobfejes plugin, de ha nincs, szerintem ez is jó lenne (Ez nincs bent teszten)
Ha meg van már mobfejes plugin, akkor meg nem látszik. kicsit több % kéne a fejdroppnak xd

7.: A visszatérő # 1, electricspawners
Ha bent lenne, nem kénének hatalmas mobfarmok 15-20spawner(/mob)-el, hanem max 1-2. szerintem kevesebb laggot okozna mint a 15-20 spawner. 

8.: Visszatérő # 2, ExoticGarden.
Tudom, világgenerálásnak eléggé szar, de a világgenerálásos része nélkül nem lenne jó? szerintem eléggé jó dolog volt :D Ércfák, gyümölcsök, rakat új kaja, stb

Minden addon (kivéve az extraheads, electricspawners, Exoticgarden) bent van teszt szerveren, ki lehet próbálni. Ha kell, segítek.
Remélmem javarészt bekerülnek :p  

Köcke @poma123 <3

**Comment by Icecroft** [comment]
A Mob capturer és az electric spawnert szívesen látnám :)

**Comment by Komjatius** [comment]
Slimy Tree Taps és Electric Spawner jó lenne.

**Comment by andris155** [comment]
Az összeset ismertem eddig is és nem véletlen, hogy nem kerültek be.

**Comment by andris155** [comment]
Majd ismét átgondolom, de a visszatérőből egyik sem fog bekerülni az biztos. :D

**Comment by skrisz0101** [comment]
Majd ha esetleg arra a döntésre jutsz hogy nem kerül be ez-az, megírnád mellé hogy miért? Köszi 😄

**Comment by Komjatius** [comment]
Igen, jó lenne, ha a döntések a közösség bevonásával születnének meg, hogy legalább tudjuk, mi miért történik vagy nem történik.

**Comment by KingDeadZ** [comment]
Az első szerintem fölösleges, ha valakinek nagyon sok kéne a plasticból (nem tudom miért) az elmehet egy sivatagba 3-4 oil pumpal, eléggé sok olaj jön belőle. (sivatagban egy chunkban kb 50-60 van)
A második, ha nem laggos, szerintem nagyon jó lenne.
A harmadik is jó ötlet lenne, mert ha sima Tag vagy nagyon megkeserítheti ilyenkor az életedet az, hogy pl. a lvl 100as petedet elengeded, hogy birj pakolni, vagy egyesével átvinni 20-30állatot.
Az ötödik az szerintem túl OP egy vanilla szerverre, főleg úgy hogy csinálsz pl. egy kaktusz farmot, és abból csinálsz végtelen gyémántot, vagy bármit amig még lehet az UUmatterből készíteni, a többi részéről nem birok mondani semmit, majd megnézem valamikor.
6-7 fölösleges szerintem
A nyolcadik jó lehetne, ha pl lenne egy részleg rá a boltban/valahogy lehetne korlátozni, hogy mennyit rakhatna le egy játékos. (Az érc plantek nélkül)

**Comment by MrZero1** [comment]
Én nem támogatok mégtöbb spawneres kiegészítőt.

**Comment by andris155** [comment]
én sem

**Comment by andris155** [comment]
1. Slimy TreeTaps
Én kicsit olyan bénának éreztem. Az eredeti mod-ban erre ugye van külön fa, amit lehet termeszteni. De az, hogy minden fa ad és nincs hozzá külön fa szerintem elég gagyi. Nyilván forráscsomag nélkül nehéz lenne megoldani máshogy, de inkább így be se raktam ezt.

2. SounfMuffler
Vedd le a hangot a beállításokban. Nehogy már ezzel keljen terhelni a szerver CPU-t, hogy valaki nem képes kikapcsolni a hangot.

3. Mob capturer
Tesztelgettem és ez jól működik illetve ötletes, de talán kicsit túlságosan is könnyít a dolgokon. Kíváncsi lennék erről @MrZero1 véleményére.

4.: TransEndence
Szerintem hasznos lehet, bár nem teljesen értettem. Azért nem raktam be, mert vannak benne olyan tárgyak amik halálosak és biztosan trollkodna ezzel is valaki. De persze mondjuk le lehet tiltani világonként. Ha kell ez bekerülhet.

5. LiteXpansion
Szerintem ez már túlzás. Túl sok extra dolgot ad már hozzá, amikkel nagyon könnyen lehet a szerveren már duplikációs hibákat csinálni bizonyos barkácsreceptek, bolti árak stb... vegyítésével.

6.: ExtraHeads
Minek, amikor van egy több 10e-es adatbázis, amiből bárki tud fejet venni? :D

7.: ElectricSpawners
Enélkül is brutális mob farmokat építettek egyesek. Nem hiányozna, hogy még ennél is komolyabbak legyenek. A CPU se bír el azért mindent és a játék még mindig csak 1 magon fut, csak pár dolog fut több magon a Paper fejlesztéseinek köszönhetően.

8. ExoticGarden
Ez gyakorlatilag az egész világot tönkre teszi annyi fej lesz ezzel mindenhol. A sok fej betöltése brutálisan laggos FPS szempontjából. Még az Intel processzorokon is. Nem is beszélve a most népszerű Ryzen-nekről, amik egy magon nem túl jók. Ott meg aztán főleg 0 FPS-es betöltéssel menne csak a játék sokszor.

**Comment by andris155** [comment]
> Igen, jó lenne, ha a döntések a közösség bevonásával születnének meg, hogy legalább tudjuk, mi miért történik vagy nem történik.

Ha mindenben a közösség döntene nem sokáig lenne szerver. Vannak olyan dolgok, amikkel kapcsolatban a staffoknak kell meghoznia döntéseket. Illetve olyanok is, ahol pedig a tulajnak.

**Comment by skrisz0101** [comment]
1.: A célnak megfelelne ez az addon :v 
2.: ok
3.: Naugye :p 
4.: Olyan tárgyak is vannak amik szerintem túl op-k egy survival szerverre. pl ellenállás V. kb god modot ad +eléggé kacifántosak a dolgok bent.
5.: Igen, ezen én is gondolkoztam, lehet túl op
6.: Ja, végülis jogos xd. mondjuk az árát szerintem le lehetne vinni. 
7.:  moblimit ugyanúgy van, nem? szerintem lehetne ezt használni arra hogy ahelyett, hogy 20 spawnert rakjanak egy mobfajtára, elég lenne 1
8.:  ezt csak apró reménnyel raktam bele, mondom hátha. okés

**Comment by Komjatius** [comment]
Pl. beválthatsz 10 reinforced spawnert egy ilyenre.

**Comment by andris155** [comment]
A Mob capturer bekerült. A többi egyelőre nem fog.

**Comment by skrisz0101** [comment]
még az se :(
