### ISSUE TITLE
HG itemek

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#3613]
**Szerver**: Survi

Kérésre, új HG itemek kerülnének be, a meglévők mellé. Javaslatokat várok szívesen. 
(A konfigot majd elkérhetem @andris155)

Javaslatok:

- vas
- szén
- fa
- nyers hús
- 1-2 varázskönyv 
- búza
- vasrög
- aranyrög
- mégtöbb bájital (ezeknek nem tudom a neveket, van  valami lista? :D)
- tejesvödör
- véggyöngy/aranyalma nem lesz, mert ezek le vannak tiltva az egész világban.

**Comment by SurvivorTheReal** [comment]
Poti nevek listája, azt teszitek be amiről úgy érzitek hogy bekerülhet:
-Potion of swiftness (speed, már bent van ha jól tudom, azt nemtom melyik szintje, sztem a 2 es)
-potion of slowness(-15% speed alapba,a fejlesztett az -60% speed)
-potion of leaping(magasugrás ha minden igaz, az alap potival 2 blokkot még nem tud ugrani az ember ha jól emlékszem
-potion of strength(ez asszem bent van már, nem vagyok biztos benne)
-potion of healing(bent van a 2 es szintje)
-potion of harming
-potion of poison(bent van a  2 es szintü splashként)
-potion of regeneration (2 es bent van)
-potion of fire resistance
-potion of water breathing
-potion of night vision
-potion of invisibility
-potion of turtle master(lassu leszel de ellenállóbb is)
-potion of slow falling
-potion of weakness

Ez az összes fajta poti ha minden igaz.

**Comment by skrisz0101** [comment]
nem tudom ki kérte ezeket, de miért?
egyiknek se látom hasznát, max a varázskönyvnek + a potiknak

**Comment by MrZero1** [comment]
Survior kérte

**Comment by skrisz0101** [comment]
meg a hógolyót, az is felesleges

**Comment by skrisz0101** [comment]
Amúgy van 11 fajta mcmmo poti is, az is lehetne

**Comment by SurvivorTheReal** [comment]
Sk van értelmük, pl ha van elég vas itemed (páncélra gondolok) akkor ha összegyülik 9, és 6 fa deszka, lesz egy pajzsod

**Comment by skrisz0101** [comment]
@SurvivorTheReal van sima pajzs, sima vasszett, ne kelljen már vasrögökből élni xd
Szén meg tényleg a teljes szemét kategória 
Csónakot adnám, de kB sehol se lenne haszna. 
Kaja is van elég, búza felesleges. Akkor már inkább kenyér

**Comment by SurvivorTheReal** [comment]
A kenyér többet tölt mint az alma, és tovább is tart a kaja csík. Így hogy búzát kell érte keresni(max 1-2 egy chestbe) így nem is lenne belőle sok. Ha elfogy a husi, még mindig van egy jobb kaja forrás mint az alma. Persze csak akkor ha találtál búzát :)
A pajzs pedig nem épp a leggyakoribb dolgok egyike, jó ha van egy körbe 1.
Viszont a szénnek csak ezért lenne értelme ez igaz ,hogy kisüssük a cuccot rögökre, meg a nyers husi miatt. Ha nem lenne tiltva az aranyalma, akkor az arany cuccok kiégetése is elvezet egyszer egy aranyalmához, ami elég nagy előnyt ad ha sikerül összeszedni.

**Comment by skrisz0101** [comment]
Nem lehet sütni szerintem

**Comment by andris155** [comment]
Most akkor kerüljön be végül valami @MrZero1 ?

**Comment by MrZero1** [comment]
Ha elküldöd a konfigot, megcsinálom és visszaküldöm

**Comment by andris155** [comment]
```yml
items:
- STONE_SWORD 1 x:5
- GOLDEN_SWORD 1
- MUSHROOM_STEW 1 x:2
- STONE_HOE 1
- LEATHER_HELMET 1 x:2
- LEATHER_CHESTPLATE 1 x:2
- LEATHER_LEGGINGS 1 x:2
- IRON_HELMET 1 x:2
- IRON_CHESTPLATE 1 x:2
- IRON_LEGGINGS 1 x:2
- IRON_BOOTS 1 x:2
- BOW 1 x:3
- ARROW 20 x:2
- FISHING_ROD 1 enchant:lure:2 name:&6Fogj_egy_harcsát
- COMPASS 1
- STICK 4 x:3
- GOLDEN_HELMET 1
- GOLDEN_CHESTPLATE 1
- BONE 1 x:2 enchant:fire_aspect:3 name:&7Mérges_kutya
- GOLDEN_LEGGINGS 1
- GOLDEN_BOOTS 1
- DIAMOND_SWORD 1 name:&6Halálosztó
- CHAINMAIL_CHESTPLATE 1 x:1
- CHAINMAIL_LEGGINGS 1 x:1
- COOKIE 2 x:3
- MELON_SLICE 1 x:4
- COOKED_BEEF 1 x:2
- POTION potion:SPEED:3600:1 1 x:2 color:7055027
- POTION potion:INSTANT_HEALTH:1:1 1 x:2 color:15804229
- SPLASH_POTION potion:POISON:320:2 1 color:5479765
- SPLASH_POTION potion:REGENERATION:660:1 1 x:2 color:12800189
- APPLE 5 x:10
- DIAMOND 4 x:6
- DIAMOND_AXE 1 enchant:knockback:1 name:&5Daraboló
- CROSSBOW 1 enchant:quick_charge:2 name:&9Rabló_Pista_tulajdona
- SHIELD 1 enchant:unbreaking:2 name:&cAmerika_Kapitányé
- SPECTRAL_ARROW 20 x:2
- TIPPED_ARROW 30 x:3 potion:POISON:320:2 1 name:&aHalálozó_nyílvessző color:green
- DIAMOND_CHESTPLATE 1 enchant:protection:3 name:&aÉletmentő
- DIAMOND_SWORD 1 enchant:sharpness:2 name:&3Az_erő_kardja
- IRON_SWORD 1 enchant:fire_aspect:2 name:&cAlvilági_kard
- STONE_HOE 1 enchant:knockback:3 name:&eKapáláshoz_te_huncut
- TRIDENT 1 enchant:loyalty:2 name:&bPosszeidón_tulajdona lore:&3Volt..
- EMERALD 3 x:3
- LAPIS_LAZULI 6 x:5
- EXPERIENCE_BOTTLE 32 x:10
- SNOWBALL 16 x:3
```

**Comment by andris155** [comment]
Megcsinálod majd @MrZero1, vagy megcsináljam én?

**Comment by MrZero1** [comment]
Megcsinálom, a héten ilyenre nem nagyon van időm. Majd küldöm a végleges konfigot

**Comment by MrZero1** [comment]
1.16-os dolgokat tud kezelni a HG?

**Comment by andris155** [comment]
tud
