### ISSUE TITLE
PomaEnchants survivalra és savra

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#3614]
Esetleg bekerülhetne? Új szettekhez tök jó lenne.

**Comment by poma123** [comment]
A PotionArmorsra gondolsz? xd

**Comment by poma123** [comment]
kész

**Comment by andris155** [comment]
Van már saját enchant pluginod is?

**Comment by poma123** [comment]
Nem enchantra van, PotionArmors a neve. Ezzel potion effekteket lehet rátenni egy adott tárgyra.
