### ISSUE TITLE
/premium nem működik

### ISSUE THREAD

**Issue by diepitepie** [andris155/TheOld-Crafters#3616]
Állítólag rajta vagyok a prémium listán, mégis mindig mikor belépek, kéri a jelszavam.

**Comment by andris155** [comment]
Az adatbázis alapján nincs bekapcsolva a prémium módod. Csak eredeti minecraft.net-es klienssel működik. Ha valóban azzal játszol kérlek próbáld meg újra beállítani.

**Comment by andris155** [comment]
Továbbra sem jó?

**Comment by diepitepie** [comment]
Mielőtt jelentettem a hibát, sehogy sem akart működni, de most jó.
