### ISSUE TITLE
Telek halál

### ISSUE THREAD

**Issue by IcyAlex** [andris155/TheOld-Crafters#3617]
Ha oda akarsz menni a telekre, de kivagy denyzve, akkor néha kidob a worldborderen kívülre és meghalsz, ami akkor nagyon gáz ha például egy fullos Old Szettben, eszközeiddel halsz meg.
Azt hogy mikor dob a worldborderen túlra és mikor nem azt pontosan nem tudom, én csak a pwarpolásnál tapasztaltam.

**Comment by andris155** [comment]
Lehet érdemes lenne letiltani ezt a deny dolgot. Sima védésnél sincs.

**Comment by poma123** [comment]
Nincs a plotsquaredben esetleg valami beállítás arra, hogy egy adott helyre teleportáljon ilyen esetben? Hasznos lenne.

**Comment by poma123** [comment]
Egyelőre elakadtam.

**Comment by poma123** [comment]
Le lett tiltva a /p deny. A már kitiltott játékosok maradnak, őket a /p remove-val lehet leszedni a telek tiltólistáról.

**Comment by andris155** [comment]
Nekem a jelenlegi plotsquared verzión amúgy sehogy se sikerült reprodukálni, hogy a deny-vel a worldborder-en kívülre dobjon.
