### ISSUE TITLE
Shulker Box Bug

### ISSUE THREAD

**Issue by geri5200** [andris155/TheOld-Crafters#362]
![2016-12-12_14 56 58](https://cloud.githubusercontent.com/assets/19761531/21101849/80480298-c07b-11e6-917e-e02bbfab2f88.png)
Ha kreatívba lerakok 1 shulker boxot lerakni letudom de kiütni már nem lehet.

**Comment by andris155** [comment]
https://github.com/andris155/TheOld-Crafters/issues/361
