### ISSUE TITLE
Mob Capturer

### ISSUE THREAD

**Issue by IcyAlex** [andris155/TheOld-Crafters#3620]
**Szerver**: Survival
A slimefun mob capturerrel levédésen lévő mobokat is be lehet fogni.
Edit:
Telken is ugyan úgy.

**Comment by poma123** [comment]
@skrisz0101 Szuper :D Akkor ki lesz véve. 
Holnap kitölt. (ilyet se írtam még le)

**Comment by skrisz0101** [comment]
derossz : (

**Comment by MrZero1** [comment]
😂
