### ISSUE TITLE
randa /beváltó

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#3621]
**Szerver**:  Szurvi, talán sav is(?)
Randa a /beváltó
![2020-06-25_18 13 23](https://user-images.githubusercontent.com/29951969/85757483-cc684780-b70f-11ea-836b-9bd40fbb7dab.png)

Kulcsokat el kéne tolni egyel jobbra, a tag+ aktiválót meg középre kéne rakni

**Comment by MrZero1** [comment]
imádom.. 😃
nyilván direkt van kihagyva hely, mert lesz még másegyéb ott😂🤷🏼‍♂️

**Comment by skrisz0101** [comment]
Akkor is csúnya :(
