### ISSUE TITLE
Talizmánok

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#3622]
**Szerver**: Survival
IvanTheBlack jelezte, hogy tegnap még mentek a talizmánjai (utazás, bányászat), ma ahogy fellépett, egyik sem ment neki. A travellert kicseréltem, ami nála volt, nekem sem ment, de az új igen.

**Comment by MrZero1** [comment]
+ Infused magnet se megy neki

**Comment by Conaniwnl** [comment]
Infused Magnet nekem se működik Savon.

**Comment by Icecroft** [comment]
A hunter talizmán sem megy.

**Comment by andris155** [comment]
@MrZero1 


> Mary kicserélte az összes talizmánom, mindegyik működik újra. Megváltozott a kódjuk, a régiek nem mennek.
> Lehet érdemes lenne egy talizmán beváltót beüzemelni a /warp beváltón, a régiek cseréjéhez

**Comment by MrZero1** [comment]
Az oké, ha újat hívtam le az nekem is ment, de ha csak 2 naponta romlanak el a talizmánok, lehetetlen annyi fajtát berakni egy falusihoz

**Comment by Icecroft** [comment]
Egyenlőre most volt az első alkalom, hogy a talizmánok régi kóddal nem mennek. Hátha nem kell oly gyakran updatelni a beváltót. Igazából csak azt akartam, hogy ne kelljen egyesével átváltanotok a talikat :)

**Comment by andris155** [comment]
Szerintem sem fog túl sokszor változni. Gondolom csak egyszer volt ilyen változás.

**Comment by MrZero1** [comment]
Akkor ha lesz ilyen, majd jelzik
