### ISSUE TITLE
NameTag

### ISSUE THREAD

**Issue by Albinocska** [andris155/TheOld-Crafters#3623]
**Szerver**: Survival
Ha egy állatot megszelidítesz az alap minecraftos módon(én kutyánál találtam) és elnevezed egy nametaggal, akkor a rangod jelzőjét odarakja a neve elé.
pl van egy tag ranggal rendelkező karaktered, szerzel kutyát és nametag-t, majd elnevezed vele(pl oroszlán-nak) akkor a "neve "[tag] Oroszlán" lesz

**Comment by skrisz0101** [comment]
Ez nem hinném h hiba

**Comment by andris155** [comment]
https://github.com/andris155/TheOld-Crafters/issues/3521
Szerintem köze lehet ehhez a hibához ennek.

**Comment by MrZero1** [comment]
Ez amúgy szerintem elég régóta van, senkit nem zavart még 😃

**Comment by poma123** [comment]
Nem hiszem, hogy a NCP-nek köze lenne hozzá. A NoCheatPlus a DamageEvent-et szakítja meg, hogyha túl messze van a játékos a célponttól, és túl nagy a sebzés. (tapasztalat -> thor kalapács, meg varázspálca oldspace-n)

Ez szerintem se zavar senkit, a kezdetek óta ilyen. Legfeljebb a NameTagEdit okozhatja egyébként ezt.

**Comment by andris155** [comment]
De ha összeköti a kutyát a játékossal teljesen mindegy milyen event. Akkor a kutyára fogja írni, hogy csal ha mondjuk túl messze öl mobokat a játékostól.

**Comment by andris155** [comment]
A fejlesztő ezt írta rá:
> Unfortunately, I believe this is a limitation because of Mojang. Possibly could be a way to remove and don't have a fulltime dev at the moment.
