### ISSUE TITLE
SF, Magic Eye of Ender

### ISSUE THREAD

**Issue by maryhonaly** [andris155/TheOld-Crafters#3625]
Survi 1.15.2 SF

Amennyiben egy teljes Ender szettben egy levédett területre dobsz egy Magic Eye of Ender-t, akkor visszakapsz egy Endergyöngyöt, anélkül, hogy a magic eye elveszne tőled. Ha spameled, végtelen endergyöngy.

videjó: https://youtu.be/SA4g0OupItI

jelentette: justvidmanfan

**Comment by andris155** [comment]
Ez a tipikus plugin ütközés probléma. Majd hétvégén foglalkozok ezzel.

**Comment by andris155** [comment]
Jelentettem a fejlesztőnek, de erre szerintem megoldás nem mostanában lesz, ha egyáltalán lesz. Az OCD-t megadtam érte a jelentőnek.
