### ISSUE TITLE
Teleportálások 

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#3627]
**Szerver**: Survi

Komjatius jelezte, hogy valami gond lehet a teleportálással (home, back). "kb. 3 napja megy ez, /home, /back hol megy, hol nem"

![kép](https://user-images.githubusercontent.com/29709854/86152587-b89e5600-bb00-11ea-9e94-ca9f07d07cce.png)

A képen látható, hogy teleportálna egy home-ra, ami egy gyár, újraépítik, mert a levédéstörlésnél rongálták. Viszont nem engedi oda, mert a fenti hibát jelzi. További 2 homejánál is ez van.

**Comment by andris155** [comment]
Az új rendszer alapján minden tesztelésre kerül alapszinten mielőtt bekerül. Hétvégén lesz erre csak időm. 100% biztos vagyok benne, hogy ezt már javította az EssentialsX.

**Comment by andris155** [comment]
Holnap elvileg már jó lesz.
