### ISSUE TITLE
Event

### ISSUE THREAD

**Issue by IcyAlex** [andris155/TheOld-Crafters#3628]
**Szerver**: Survival
Tegnap Szabadulás eventen 3/3x 1. helyen kelett volna végezzek, de a késleltetés miatt nem én kaptam meg, de nem csak hogy az 1.-t de szerintem utolsónak számolt engem.

**Comment by poma123** [comment]
Milyen késleltetés? Tudnál erről videót csinálni?

**Comment by IcyAlex** [comment]
Hát videót nem tudok felvenni a potato pcmel, de dc-n majd leliveolhatom. Annyi csak hogy nem azonnal kapod meg a helyezést hanem 10mp-vel később, és akkor sem a helyes sorrendben

**Comment by andris155** [comment]
Miért ne tudnál? Régen én egy gagyi Intel HD Graphics-al is vettem fel videókat. Lehet nem volt 60 FPS-es, de ez nem is elvárás.

**Comment by andris155** [comment]
Lehet pont a gyenge gép miatt van a késleltetés amúgy. Meg gondolom akkor az internet is gyenge hozzá.

**Comment by poma123** [comment]
Javítva, köszi a jelentést.
