### ISSUE TITLE
mcMMO/Repair skill problem

### ISSUE THREAD

**Issue by Icecroft** [andris155/TheOld-Crafters#363]
Elértem a Repair skillből az 1000. szintet. Itt a leírás szerint még +200% extra repair van (lásd 1. screenshot)
Ez azt jelenti, hogy egy teljesen lehasznált aranyfejszét vagy csákányt egyetlen aranyrúddal 100%-ra fel lehet javítani.
Valójában még sem lesz 100%-os a feljavított eszköz (Screenshot 2.)
Véleményem szerint kerekítési hiba okozhatja (3×33.33 = 99.99)

english version:
I reached level 1000 of the Repair skill. There is an extra 200% extra repair after every repair (see screenshot 1.) It means i could repair a low quality gold axe to 100% with a gold ingot. But it wonn't be 100% repaired in fact, see screenshot 2. Perhaphs it is a rounding problem in the source: (3×33.33 = 99.99)

![2016-12-14_14 03 16](https://cloud.githubusercontent.com/assets/19332825/21187960/0f963c9a-c21a-11e6-84f3-cd34448e33f7.png)
![2016-12-14_14 03 54](https://cloud.githubusercontent.com/assets/19332825/21187959/0f95b860-c21a-11e6-86ee-2dc8fcd35b10.png)

**Comment by andris155** [comment]
Ezt leírást nézted?
https://github.com/mcMMO-Dev/mcMMO/wiki/Play

**Comment by Icecroft** [comment]
Igen, láttam, de szerintem nem olyan alapos a leírás, mint ez:
[http://mcmmo.wikia.com/wiki/McMMO_Wiki](url)

**Comment by andris155** [comment]
Írtam a fejlesztőnek, de előttem már 300-nál is többen írtak nem valószínű, hogy javítja mostanában.

**Comment by andris155** [comment]
https://github.com/andris155/TheOld-Crafters/issues/348
