### ISSUE TITLE
Savsziget 1.16 átállás problémák

### ISSUE THREAD

**Issue by Icecroft** [andris155/TheOld-Crafters#3633]
1.) Nem működik az ércgenerátor, csak zúzott követ ad
2.) /c küldetéslista nem működik
3.) az /is pwarp parancs nem működik
4.) a petparancsok sem működnek

**Comment by andris155** [comment]
Ez igazából a plugin hibája nem is az 1.16.1 verzió miatt van elvileg.

**Comment by andris155** [comment]
most elvileg jó

**Comment by andris155** [comment]
A pet nem frissült 1.16.1-re. Ameddig nem frissül értelemszerűen nem fog működni.

**Comment by Icecroft** [comment]
1.), 2.) és 3.) javítva. Köszi!
A petpluginból pedig várjuk a frissítést.
