### ISSUE TITLE
Savsziget bugok/nem működő parancsok

### ISSUE THREAD

**Issue by KriszLOW** [andris155/TheOld-Crafters#3635]
Savsziget:

- Frost Walker enchant ércet csinál a vízből, jég helyett. Elvileg ez fennáll snowman-el és sima fagyással is.
- Pár embert nem sebzett a víz, ezt nemtudtam magamon reprodukálni, viszont láttam olyan embert akit tényleg nem sebzett. Ez 
  a veszély már lehet nem fenyeget.
- Nincs /m parancs.

**Comment by Conaniwnl** [comment]
- /nick által beállított színek felűl vannak írva a chat-en.

**Comment by Conaniwnl** [comment]
> /msg van helyette egyelőre

Igen jeleztem a játékosoknak, de gondolom meglehet majd csinálni, mert valamivel könnyebb a használata.

**Comment by andris155** [comment]
Amit lehetett javítottam.
