### ISSUE TITLE
Survival szerveren amikor kisütöttem 32 ősi törmeléket,és 38 netherite darabot vettem ki a sütőkből.

### ISSUE THREAD

**Issue by Squidmanus** [andris155/TheOld-Crafters#3636]
**Szerver**:

**Comment by Conaniwnl** [comment]
Azt okozhatja a mcmmo javítás(?) vagy valamelyik másik skill fejlettsége.

**Comment by KingDeadZ** [comment]
Mcmmo okozhatja, tekintve hogy csak ebben a pluginban van ilyen dolog.

**Comment by Icecroft** [comment]
Ez az MCMMO effektje, konkrétan az olvasztás skill, nálam 1000 felett van ez a skill, így kb 60%-al több ércet kapok kisütéskor, ez a skill működik az ősi törmelékre is.
