### ISSUE TITLE
Új Luckyblock-os meglepetések

### ISSUE THREAD

**Issue by poma123** [andris155/TheOld-Crafters#3637]
**Szerver**: Survival, Savsziget

Itt van listába gyűjtve, hogy mi lesz betéve a luckyblockba.

<details><summary><b>Új meglepetések (Kattints ide!)</b></summary>
<p>

Sima Luckyblock:
- [x] Ultrakirály ládakulcs 2 db
- [x] Varázslatos ládakulcs 2 db
- [x] Fortuna ládakulcs 2 db
- [x] ~~Kulcsmester kulcs 1 db~~
- [x] 5000$
- [x] Csirke, malac, tehén, bárány spawnolás (akár 2-2 darab)
- [x] Építőblokkok (10 darab föld, sóder, homok, kövek, fák, könyvespolc, üveg, falevél)
- [x] 2-2 kiszáradt zombi és kóborló
- [x] ~~Alap SF cuccok (walking stick, valami kard (cooper vagy ilyesmi), meg ami nem számít értékesebb SF cuccnak.)~~
- [x] 1-2 token, eventpont
- [x] 2 db minuszos és pluszos luckyblock
- [x] Zombi és csontvázló 1-1 darab

Plusz (+) 80:
- [x] Fortuna kulcs 4 db
- [x] SF kulcs 2 db
- [x] Legendás kulcs 2 db
- [x] Kulcsmester kulcs 1 db
- [x] Panda, róka, méh, macska 2 db idézés
- [x] Értékesebb SF cucc (1db essence of artitle, 1db carbonado, Grandapa sétapálca mindegymelyik, Jetpack 4, Multi tool 4, Ice íj, 4 db reinforced alloy ingot, 2 db Ender rune, 1 db Infused hopper)
- [x] 10.000 pénz
- [x] Gömbhal, trópusi halak 5-10 darab, csak úgy, mert fun és aranyosak ahogy vergődnek a földön :D
- [x] Néhány értékesebb sima MC cucc (nethercsillag 2 db, szivacs 10 db, aranyalma 2-4 db, totem 1 db)
- [x] 3-4 token, eventpont
- [x] Giant 1 db

Minusz (-) 80:
- [x] SF kulcs 1 db
- [x] ~~Kulcsmester kulcs 1 db~~
- [x] Pusztító 1 db, rabló, bosszúálló, illúziósmianeve, idéző 1-2 darab vegyesen
- [x] 2000 pénz
- [x] 1 token, eventpont
- [x] fa eszközök
- [x] Blokkok (pl. 5 föld, sóder) (5 darab föld, sóder, homok, kövek, fák, könyvespolc, üveg, falevél)
- [x] Itemek (2 toll, puskapor, ürespalack, tál, kovakő) (puskapor, kovakő, toll, bot, ürestál, vödör, gomb, kar, virágok, szőnyeg, korall)
- [x] Vén őrszem 1 db, kicsik 3-4 db
- [x] Zombi és csontvázló 1-1 darab
</p>
</details>

(eredeti jelentés: #3599)

**Comment by MrZero1** [comment]
Lenne majd 1-1 szett+eszközök is, talán 1.16-os dolgok is, de erről csak max. a hétvégén lenne lista.
A szett neve lehet speckó (pl. zárójelet tartalmaz, 2 színű stb...)

**Comment by poma123** [comment]
Okés, még egy kérdés, ahol nincs megadva hogy konkrétan mi legyen, oda mi legyen?xd Ami a zárójelben a példaként van, vagy valami más?

**Comment by MrZero1** [comment]
A blokkokra és itemekre gondolsz? 
Az SF cuccokat rád (vagy a másik jelentés alatti sk listára bízom, amit én írnék, az úgysem lenne jó)

**Comment by poma123** [comment]
Igen például a blokkok és itemekre gondolok
Az SF cuccokhoz (mint a játékban lévő érték), én nem nagyon értek, szóval arról majd kellene valami közös egyeztetés, hogy mik legyenek (akár több játékossal összeírni)

**Comment by MrZero1** [comment]
Blokkok alatt én ezekre gondoltam: föld, sóder, homok, kövek, fák, könyvespolc, üveg, falevél - vegyesen, 10-20 darabol
Tárgyak: puskapor, kovakő, toll, bot, ürestál, vödör, gomb, kar, virágok, szőnyeg, korall - ez is vegyesen

De lehetnek értékesebb dolgok is

**Comment by MrZero1** [comment]
De ha nem most akarod beállítani, írok össze kategorizálva egy listát, és elküldöm

**Comment by poma123** [comment]
Akkor mondjuk úgy jó, hogy lesz 1 fajta meglepetés mondjuk a blokkokra, és akkor x esély van külön-külön az összes listában lévő itemre, hogy dobja valamelyik blokkot?
Példa:

```
- föld 10 0.2
- sóder 10 0.2
- homok 10 0.2
```
Ez kb annyit tesz, hogy mindegyikre 20% esély van, hogy dobódjon, és ugye 10 darab

**Comment by MrZero1** [comment]
Úgyis jó, bár én pl. úgy gondoltam, hogy a blokkokból egyszerre dob 10-10-10 darabot

**Comment by poma123** [comment]
Ja jó, azt is lehet, de akkor az összeset dobja ki egyszerre?

**Comment by MrZero1** [comment]
Szerintem igen, de csak 2-3 fajta blokkot/tárgyat egyszerre. Tehát pl egy nyitásnal föld-homok-sóder 10-10-10 darab, másik nyitásnál ha azt nyissa, akkor (pl) üveg-kő-könyvespolc 10-10-10 darab. 
Ugyanígy az itemeknél.

**Comment by MrZero1** [comment]
Illetve, a Vándor ládakulcs helyett a Kulcsmester ládakulcs van, azt is berakhatnád mindhárom Luckyblockba, 1-1-1 darabot

**Comment by poma123** [comment]
Na, beállítottam mindent kivéve az sf-es itemeket
A giant szerintem nagyon idegesítő amúgyxd, szerintem jobb lenne ha nem lenne bent
![image](https://user-images.githubusercontent.com/25465545/86802348-3b7d5e80-c075-11ea-97e8-eb57afb4db73.png)

**Comment by poma123** [comment]
Holnap betölt survin és savon.

**Comment by andris155** [comment]
A Slimefun tárgyak nem fognak bekerülni?

**Comment by poma123** [comment]
> A Slimefun tárgyak nem fognak bekerülni?

Lásd: https://github.com/andris155/TheOld-Crafters/issues/3637#issuecomment-654809976

**Comment by MrZero1** [comment]
1db essence of artitle 
1db carbonado
Grandapa sétapálca mindegymelyik
Jetpack 6 
Multi tool 6 
Ice íj 
4 db reinforced alloy ingot 
2 db Ender rune 
2 db Infused hopper

Plusz a Kulcsmester kulcs most 1-1-1 darabban van, ez legyen csak 1 db, legyen a plusz80-as luckyblockba, a másik kettőben ne

**Comment by poma123** [comment]
Kész, holnap betölt

**Comment by MrZero1** [comment]
Köszi!
