### ISSUE TITLE
Striderek (lávajáró micsodák) 

### ISSUE THREAD

**Issue by TrapSensei** [andris155/TheOld-Crafters#3638]
**Szerver**: Survival szerver
A striderek, vagyis azoka lávaszörnyek akiken lehet menni a lávában, ha fel vannak nyergelve, és funguszos horgászbottal a kezünkbe rájuk akarunk ülni akkor nem lehet. Valamint ha ráülünk, és utána vesszük a kezünkbe akkor meg ledobnak és összevissza ledobnak, de elvileg rajta maradunk. Magyarul én nekem úgy látszódik hogy nem ülök rajta, de valójában még rajta ülök. 
Valamint összevissza dobálnak. Észrevételem szerint csak akkor csinálja ezt ha akadályba ütközik. pl bármi mob vagy block, a block magasságot vált, akkor is ugyan ezt teszi.

**Comment by poma123** [comment]
Valószínűleg a csalásvédelem tiltja ezt le.
@andris155

**Comment by poma123** [comment]
#3644

**Comment by andris155** [comment]
javítva
