### ISSUE TITLE
Warp bolt SF felszerelések bug

### ISSUE THREAD

**Issue by Komjatius** [andris155/TheOld-Crafters#3639]
**Szerver**: Survival
Ha SF szett van rajtam, ugrándozós csizma, gyors futás nadrág, és hosszasabban időzök a warp boltban, egy idő után meghülyül a szett, és nem adja az effekteket.
A hiba csak akkor jelentkezik, ha a warp boltban vagyok.
Jó sokáig úgy is marad, aztán egyszer csak magától visszaáll. Relog sem segít rajta.
Nem tudom, miért vannak a SF cuccok letiltva a warp boltban, de valami nagyon rosszul van megoldva, többet árt, mint használ.

**Comment by andris155** [comment]
Világ váltásnál nem frissíti. A megoldás egyelőre: Vedd le, mielőtt olyan világba mész ahol tiltott.
A survivalgames tehát event világban tiltott, meg a spawn2-ben, ahol a bolt is van.
@MrZero1 a spawn2-ben ezt amúgy nem lehetne engedélyezni? Ott nincs event elvileg, ahol tudnának csalni a páncélokkal.

**Comment by MrZero1** [comment]
Spawn világban szerintem lehet engedélyezni

**Comment by andris155** [comment]
Engedélyeztem a páncélzatokat a spawn2 világban. Holnap betölt a változtatás. Az eventes világba teleportálás előtt viszont érdemes levenni egyelőre ezeket. Később talán javítják majd ezt a hibát.

**Comment by Komjatius** [comment]
Köszönöm.
