### ISSUE TITLE
Lock tábla

### ISSUE THREAD

**Issue by NBabi** [andris155/TheOld-Crafters#364]
A Lock táblával védett kerítés kapuhoz hozzá vagyunk adva többen és egyikünk sem tudja kinyitni, csak akkor ha nincs rajta Lock tábla, ha 2db kerítéskapu van egymás mellet akkor pedig nem az nyílik ki amire kattintok hanem a mellette lévő. Nyomólappal kinyílik. (Linux1230 bejelentése)

**Comment by andris155** [comment]
Javítva
