### ISSUE TITLE
Paintball - mobaréna

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#3640]
Ha a mobaréna tetejéről csatlakozok paintball-ra, majd kilépek, az arénán belülre teleportál vissza, ahol lehet ládákat nyitni.

**Comment by andris155** [comment]
Elvileg letiltottam a pb parancsot a mobaréna területén most.

**Comment by andris155** [comment]
508 OCD

**Comment by andris155** [comment]
Milyen névre adjam?

**Comment by UDPSendToFailed** [comment]
KernelPanic
