### ISSUE TITLE
Soulspeed enchant

### ISSUE THREAD

**Issue by TrapSensei** [andris155/TheOld-Crafters#3641]
**Szerver**: Survival
A szerveren a soulspeed enchanttal ha futunk a lélekhomokon akkor bugos és folyton beakadunk és dobál hátrafelé valamint totálisan leállítja a játékost, míg a soul soil-on tökéletesen működik.

TrapSensei

**Comment by poma123** [comment]
#3644

**Comment by andris155** [comment]
javítva
