### ISSUE TITLE
Plot bug: csónakba szállás

### ISSUE THREAD

**Issue by Icecroft** [andris155/TheOld-Crafters#3642]
A telkemen az 1.16 frissítés óta nincs engedélyem csónak szállni. Ki tudom ütni, le tudom rakni, de nincs beszállás:
![2020-07-08_17 32 12](https://user-images.githubusercontent.com/19332825/86939087-6e8d2400-c141-11ea-8e0a-4a4bebb79d87.png)

**Comment by poma123** [comment]
#3645
