### ISSUE TITLE
Parancsok

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#3643]
**Szerver**: Most épp survin vagyok

/m
/info színek parancsra ezt adja ki: 
![kép](https://user-images.githubusercontent.com/29709854/86953923-6fc84c00-c155-11ea-855d-79fc2ccbd5d9.png)

**Comment by MrZero1** [comment]
/p h sem úgy megy, mint eddig

**Comment by poma123** [comment]
Az /m-et megoldom, de rakhatok aliast az /info-nak az /einfo-ra @andris155? Nem szoktuk használni a WE /info parancsát szerintem.
