### ISSUE TITLE
PlotSquared hibák

### ISSUE THREAD

**Issue by poma123** [andris155/TheOld-Crafters#3645]
**Szerver**: Survival

Az alábbi hibák jöttek elő eddig:
- /p home parancs (most: /p home <neved>) #3626
- Csónakból kiszállás #3642 
- Nem lehet etetni az állatokat
- Nem lehet képkeretbe tárgyakat tenni

**Comment by andris155** [comment]
Holnap elvileg mind jó lesz.

**Comment by andris155** [comment]
Elvileg mind javítva.

**Comment by Icecroft** [comment]
Tegnap este teszteltem a csónakba ki/beszállást, működött
