### ISSUE TITLE
Teleport plugin hiba

### ISSUE THREAD

**Issue by mnbTOC** [andris155/TheOld-Crafters#3646]
/tpa, /home, nagyon nehezen akar müködni. A /tpaccept vagy éppen /tpyes parancsot rengetegszer kell futtatni hogy egyszer elfogadja a teleport kérést. Ezáltal a saját és más chatét is telispammelve.

![2020-07-09_08 54 20](https://user-images.githubusercontent.com/32791069/87007167-1ba78100-c1c2-11ea-88da-7e4b2d64cb0a.png)

**Comment by andris155** [comment]
Ha közben mozog persze, hogy nem fog működni.

**Comment by Icecroft** [comment]
Ha mozgott volna, akkor a chaten látnánk, hogy a teleportálás megszakadt.
Tegnap nekem nem volt ilyen gondom, de régebben többször is előfordult: Ha egyszer nem sikerült a teleport, akkor utána már nem ment egyáltalán a következő login-ig. Gyakorlatilag a kliens levált a szerverről (warpok, teleportok, back, ládanyitások sem mentek), de a chat még működött.

**Comment by andris155** [comment]
Holnap lesz rá megoldás elvileg.

**Comment by MrZero1** [comment]
![kép](https://user-images.githubusercontent.com/29709854/87219825-dcfafd80-c35e-11ea-8e5e-25d9d54ea595.png)

Ez is hozzákapcsolódhat, Chelio jelezte, de már más is, hogy a csónak bugos(?).

**Comment by andris155** [comment]
Az inkább saját net vagy cheat védelem hiba.

**Comment by andris155** [comment]
A teleport javítva lett.
