### ISSUE TITLE
Kreatív védelem bővítése

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#365]
Kreatív módban lehet:

- Etetni az összes pet típust
- Minden mob félét szaporítani (malac, csirke, tehén, birka, láma, stb)
- Farkast és ocelot-ot szelídíteni
- Íjat, kardot a zombi és skeleton pet kezébe adni, páncélt is felveszik

Megoldás: az ilyen itemek használatának letiltása.

**Comment by andris155** [comment]
Javítva
