### ISSUE TITLE
A SF talizmánok nem működnek.

### ISSUE THREAD

**Issue by Lagire** [andris155/TheOld-Crafters#3651]
Többszöri próbálkozás után sem sikerült életrekelteni a talizmánokat a túlélő szerveren. Nem tudom mi lehet a baja, de sem az alap, sem az ender változata nem működik.

**Comment by andris155** [comment]
Szerintem kérj újatkat.
https://github.com/andris155/TheOld-Crafters/issues/3622

**Comment by Lagire** [comment]
És hogy kérjek újat? Admintól?
