### ISSUE TITLE
ChatControl rgb színek

### ISSUE THREAD

**Issue by poma123** [andris155/TheOld-Crafters#3652]
**Szerver**: összes

Ha chaten ír valaki rgb-s színkóddal, unicode miatt bejelez. (Staffoknak adtam jogot rá.) Az mondjuk lehet, hogy chatcontrolos jog is kell rá?
**Edit**: Az essentialsx (essentials.chat.rgb) és a chatcontrol (chatcontrol.chat.rgb) perm is meg van adva, mégis bejelez.
![image](https://user-images.githubusercontent.com/25465545/87229668-4fdd9600-c3aa-11ea-903c-9dfdeff9edd0.png)

**Comment by andris155** [comment]
Ha tudsz nekik hibát jelenteni, akkor megírhatod nekik. Én nem tudok sajnos oda belépni, ahol ezt lehetne.

**Comment by andris155** [comment]
Javítottam a hibát. A ChatControl-t újra kellene tölteni hozzá, de legutúbb nem működtek utána a parancsai. Szóval lehet érdemes megvárni ezzel az újraindítást majd.

**Comment by poma123** [comment]
Oké, köszi!
