### ISSUE TITLE
A telkeken szörnyek idéződnek

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#3653]
**Szerver**: Survi
Telkeken is idéződnek szörnyek, paranccsal és tojással is.

**Comment by andris155** [comment]
???
Nem értem ezen mi a probléma. :D

**Comment by MrZero1** [comment]
Akkor nekem új, eddig úgy tudtam, mobok nem spawnolnak a telkeken, csak állatok

**Comment by andris155** [comment]
Az állat is mob. xd

**Comment by MrZero1** [comment]
vannak állatok, meg vannak mobok

**Comment by andris155** [comment]
Elvileg idéző tojással lehet lerakni szörnyeket. Magától elvileg nem kellene megidézni szörnyeket viszont.

**Comment by MrZero1** [comment]
de ha ez így rendben van, akkor lezárom

**Comment by andris155** [comment]
A tojás nem hiba az biztos. Magától nem kellene szörnyeket idéznie.

**Comment by andris155** [comment]
De biztos, hogy ez probléma? A játékosok örülnek, mert legalább tudnak szörny farmot oda is. Nekünk meg teljesen mindegy, hogy most melyik világban van szörny farm. Úgyis megépítik, ha nem oda, akkor máshova.

**Comment by andris155** [comment]
@MrZero1

**Comment by MrZero1** [comment]
Én jobban örülnék ha a telkeken nem lenne mobfarm. Rangosoknak rengeteg telkük lehet, teleépítik mindet

**Comment by andris155** [comment]
Letiltottam a spawnerek működését a telkeken.
