### ISSUE TITLE
Pandák és rókák sebezhetők más telkén

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#3655]
https://youtu.be/p9ymgOeuQFg

**Comment by UDPSendToFailed** [comment]
Tehenek is

**Comment by andris155** [comment]
Pedig ez még csak nem is dev verzió. Egyre lejjebb adnak a minőségben a fejlesztők ahogy látom.

**Comment by andris155** [comment]
javítva

**Comment by andris155** [comment]
1016 OCD

**Comment by UDPSendToFailed** [comment]
Most sem jó :/
https://youtu.be/QcYaNPc8C1c

**Comment by andris155** [comment]
A PlotSquared szerint ez nem hiba. Nem tudok vele mit kezdeni.
