### ISSUE TITLE
Új szülinapi kalapok elkészítése

### ISSUE THREAD

**Issue by poma123** [andris155/TheOld-Crafters#3662]
**Szerver**: Survival, Savsziget, OldSpace

A szerver szülinapjára a szokásos kalapot elkészíteni a forráscsomaggal. ~~Survivalon automatikus forráscsomag letöltés, a többi szerveren nem, oda~~ Manuálisan lesz érdemes majd letölteni GitHub-ról a forráscsomagot.

![image](https://user-images.githubusercontent.com/25465545/87418581-33bc3d80-c5d2-11ea-9956-b51796fae486.png)      ![image](https://user-images.githubusercontent.com/25465545/87418651-54849300-c5d2-11ea-8606-c11ab9513937.png)

**Comment by andris155** [comment]
Nem szeretnék csak ezért oda forráscsomagot.

**Comment by andris155** [comment]
A betöltése nem túl gyors. Még akkor sem, ha csak egy kalap.

**Comment by poma123** [comment]
ok akkor ott is manuális letöltős lesz :)

**Comment by poma123** [comment]
Kész. 
- Survivalon tettem beváltó warpra egy beváltót, ahol a régi 4. éves és 5. éves kalapok beválthatóak az újabb verzióra.
- Survivalon és Savon minden admin 0.-s enderchestjébe beletettem a ládát, amiben benne van az összes szülinapi kalap. A jelenlegiek az alsó sorban vannak. Az idén lesz a szerver 6. szülinapja, a pink színű kalap.
- OldSpace-n csak Zero ec-jébe tettem ládát, nem tudom, hogy oda hányan fogják átkérni, de biztos ami biztos.
- A textúracsomag letöltési linkje: [Link](https://github.com/andris155/TheOld-Crafters/blob/master/SzulinapiKalap.zip?raw=true)

**Comment by andris155** [comment]
Ez a zöld tábla a legszebb szerintem, de valami más szín jobban illene hozzá a szövegnél. :D

**Comment by andris155** [comment]
Valami menő RGB-s szín :D
