### ISSUE TITLE
Hg bug

### ISSUE THREAD

**Issue by Bazsaaaa** [andris155/TheOld-Crafters#3663]

**Comment by andris155** [comment]
javítva

**Comment by andris155** [comment]
5080 OCD

**Comment by Bazsaaaa** [comment]
Omg tényleg? Nem gondoltam volna hogy ilyen sokat kapok köszönöm szépen

András Marczinkó <notifications@github.com> ezt írta (időpont: 2020. júl.
19., V 13:25):
