### ISSUE TITLE
HungerGames láncmellvért

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#3664]
![kép](https://user-images.githubusercontent.com/16057404/87282067-2a5ca380-c4f4-11ea-8b46-757ee456661e.png)

**Comment by andris155** [comment]
hmm ez melyik Slimefun tárgy lehet?

**Comment by andris155** [comment]
Engedélyeztem. Holnap betölt.

**Comment by andris155** [comment]
330 OCD
