### ISSUE TITLE
A börtönnek semmi értelme,ha lehet ott írni a chatre. Ha például volt egy vita a chaten,és börtönbe került az egyik vagy mindegyik résztvevő,ugyan úgy tudják folytatni a huzavonát.

### ISSUE THREAD

**Issue by Squidmanus** [andris155/TheOld-Crafters#3667]
**Szerver**: Survival

**Comment by skrisz0101** [comment]
Veszekedésért mute jár, nem jail.
Ha meg valamelyik segítő így csinálta, szólj neki h mute kéne neki nem jail

**Comment by poma123** [comment]
@Squidmanus légyszi ne a cím helyére írd a probléma tartalmát, hanem az arra kialakított részre. Köszi.
