### ISSUE TITLE
Discord szerverre szerintem pedig be kellene hozni egy új szobát #játékos-jelentése néven,és oda lehetne küldeni a szabályszegőket.

### ISSUE THREAD

**Issue by Squidmanus** [andris155/TheOld-Crafters#3668]
**Szerver**: Discord

**Comment by MrZero1** [comment]
Globálchat, segítségkérés szobákban nyugodtan lehet ezeket jelezni, külön szobát erre nem szeretnék

**Comment by poma123** [comment]
@Squidmanus légyszi ne a cím helyére írd a probléma tartalmát, hanem az arra kialakított részre. Köszi.
