### ISSUE TITLE
Andris155

### ISSUE THREAD

**Issue by NightMare52** [andris155/TheOld-Crafters#367]
Találtam pár buggot a szerveren Gm kell csak hozzá.El is kezdem sorolni őkent (NightMare52 vagyok ) az összes bugghoz víz kell...
Gamemode 1 ben vannak a fejek amiket ha lerakunk vagy vizbe rakjuk megadja és gamemode 0 ban felbirjuk venni és nyugodtan futhatunk tovább velük.
a második bugg az az hogy ha pl szőnyeget vagy vázát vagy ami benne van a vázában ugyan igy vizzel.
táblákat is lehet buggoltatni de annak nincs értelme mert könnyen lehet craftolni őket.Lerakod a táblát viz ugyan úgy ki tudja vinni és gm 0 ba viheted is.

**Comment by andris155** [comment]
Ezeket a hibákat már jelentették, de azért köszönjük a bejelentést!
