### ISSUE TITLE
Knowledge Book [ Receptek ]

### ISSUE THREAD

**Issue by Conaniwnl** [andris155/TheOld-Crafters#3671]
**Szerver**: Savsziget

A tudás könyvét (Knowledge Book) megnyitván, nem a várt esemény történik,  helyette elveszi a könyvet.

https://www.youtube.com/watch?v=kQlm4EPuLik

**Comment by MrZero1** [comment]
A ‘zene’ a legjobb... 😃

**Comment by andris155** [comment]
Nem frissült még 1.16.1-re sajnos a plugin ezért nem működik.

**Comment by andris155** [comment]
A /customcrafting knowledge paranccsal elérhető.

**Comment by andris155** [comment]
Javítva lett a könyv is, de csak az újabbak működik.
