### ISSUE TITLE
Nether Star addolás

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#3673]

**Comment by andris155** [comment]
Akárhogy próbáltam ezt nem sikerült reprodukálni.

**Comment by UDPSendToFailed** [comment]
Nem lélekhomokból kell építeni, hanem lélektalajból, 1.16-os blokk.

![kép](https://user-images.githubusercontent.com/16057404/87786643-9b74c180-c83a-11ea-8453-b7a1fbfc88a6.png)

**Comment by andris155** [comment]
Ideiglenesen javításra került.

**Comment by andris155** [comment]
5080 OCD
