### ISSUE TITLE
Spawnerek láda

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#3675]
Ennek így kb semmi értelme 330 OCD / kulcs áron, legalább a fele lehetne normális spawner. Egy az, hogy szinte az összes ládából lehet spawn tojásokat nyitni, a másik, hogy ezeket a mobokat pár perc beszerezni farmokból, teljesen ingyen.

![kép](https://user-images.githubusercontent.com/16057404/87771627-eb468f00-c820-11ea-9600-e6ec49438c27.png)

**Comment by andris155** [comment]
@MrZero1

**Comment by MrZero1** [comment]
Ez melyik szerver?

**Comment by MrZero1** [comment]
Csakmert Savszigeten való igaz, hogy nincsen benne spawner, de a maximális méretet feltöltöttem tojásokkal. 
Survivalon pedig nem változott, spawnerek és tojások voltak benne. Én azon nem változtattam.

**Comment by UDPSendToFailed** [comment]
Survival szerver, nincs benne egy spawner sem, csak a tojások, amik a képen vannak.

**Comment by MrZero1** [comment]
Csodálatos! ❤️ 
A többi láda tartalma milyen? 

Hamarosan hazaérek, aztán megnézem és javítom. Nem tudom ki nyúlt hozzá de diszlájkolom őt. 

Ha kész, lezárom majd ezt

**Comment by poma123** [comment]
Én aztán nem nyúltam hozzá.

**Comment by andris155** [comment]
Javítva.
Frissíteni kellett pár tárgy nevet az 1.16.1-es verzióra.
<img width="260" alt="Annotation 2020-07-17 150215" src="https://user-images.githubusercontent.com/8324198/87788971-9580df80-c83e-11ea-87c6-006b2dfaa675.png">
