### ISSUE TITLE
Elbugol a cobblestone generator

### ISSUE THREAD

**Issue by Bazsaaaa** [andris155/TheOld-Crafters#3677]
**Szerver**:
szerver: survival
a sima enchanted crafting table-ba akartam craftolni cobblestone generatort de az lett a vége hogy az itemeket el vette és a generatort nem adta oda mert nem volt hely az adagolóban (azt hittem hogy a vödröket nem adja vissza és lessz hely)

**Comment by andris155** [comment]
Nekem ezt nem sikerült reprodukálni. Oda rakja a dispenser legelső helyére.
<img width="352" alt="Annotation 2020-07-17 215315" src="https://user-images.githubusercontent.com/8324198/87825754-fc6eba80-c877-11ea-8d76-69aff4ae0122.png">

**Comment by andris155** [comment]
A 2 üres vödör pedig elfér benne.
<img width="260" alt="Annotation 2020-07-17 215315" src="https://user-images.githubusercontent.com/8324198/87825829-1f996a00-c878-11ea-85af-0864a9f9b55f.png">

**Comment by Bazsaaaa** [comment]
Én úgy próbáltam hogy három itemet raktam mindegyik helyre és azt hittem
hogy a vödör helyére rakja a generatort és a vödröketmeg el veszi  :)

András Marczinkó <notifications@github.com> ezt írta (időpont: 2020. júl.
17., P 21:55):

**Comment by andris155** [comment]
De ha a vödörben van valami, akkor nem lehet többet egymásra rakni. Szóval nem értem úgy mi értelme.

**Comment by skrisz0101** [comment]
Az, hogy nem kell egyesével mindent berakni, csak a vödröket
@Bazsaaaa használj sf-s ládát

**Comment by Bazsaaaa** [comment]
electric crafting chamberben le tudom craftolni csak szólni akartam hogy így el bugol (ha nem tiszta hogy hogyan bugolt el akkor csinálok egy vidit róla később)

**Comment by Bazsaaaa** [comment]
itt a legigényesebb videó ami bemutatja a bugot :D 
https://www.youtube.com/watch?v=LkKYcdV8Xf8

**Comment by andris155** [comment]
Igazából az szerintem a Slimefun hibája. Van még ilyen recept a Slimefun-ban esetleg?

**Comment by Bazsaaaa** [comment]
Én eddig csak ezt vettem észre

András Marczinkó <notifications@github.com> ezt írta (időpont: 2020. júl.
18., Szo 18:48):

**Comment by andris155** [comment]
Egyelőre ezt lezárom. Akiknek kell tudnak a hibáról. Remélhetőleg lesz rá javítás, de addig az enchanted crafting table-ben csak 1 darabot készítsetek egyszerre.
