### ISSUE TITLE
Piglinek és Slimefunos aranydolgok

### ISSUE THREAD

**Issue by VdszHun** [andris155/TheOld-Crafters#3679]
**Szerver**: Survival

A Piglinek elfogadják a slimefunos aranyrudakat és dobnak is cserébe dolgokat. Eddig teszteltem 4, 12, 24 karátos arannyal de még ma este fogom tesztelni másfajtákkal is mint pl. A Blistering ingot. 
A Slimefunos aranypáncélokat/eszközöket is felveszik, illetve még a 24 karátos aranyblokkot, ezeket viszont visszakapom sértetlenül ha megölöm.

Játékosnév: Vdsz
A Vdsz név Githubon foglalt :(

**Comment by VdszHun** [comment]
33%-os Blistering rudat elfogadták, szinte biztos, hogy a nagyobbak is tetszenek nekik.

**Comment by andris155** [comment]
De az többet ér egy sima aranyrúdnál nem?

**Comment by VdszHun** [comment]
Muszáj volt tesztelnem :D. Az Otthonomban van Uránium gyár és régebbről rengeteg 24 karátos arany. A kissebb karátos aranyrudak viszont olcsóbbak mint egy vanilla.

**Comment by VdszHun** [comment]
Gilded Iron és Brass ingot is jó nekik, tovább nem tesztelem, szerintem mindet elfogadják.

**Comment by VdszHun** [comment]
Utólag eszembe jutott pár más arany dolog is a Slimefunból. Holnap tesztelek még páncélokat, stb.

**Comment by VdszHun** [comment]
Jól sejtettem. A slimefunos arany páncélokat és eszközöket is felveszik, illetve a 24 karátos aranyblokkot is. Viszont azokat visszakapom sértetlenül ha megölöm.
Szerkesztem a címet és a leírást

**Comment by VdszHun** [comment]
![20200725_110200](https://user-images.githubusercontent.com/68443484/88453349-697ce400-ce66-11ea-9940-82c70d04ca06.png)
![20200725_110209](https://user-images.githubusercontent.com/68443484/88453351-6aae1100-ce66-11ea-919c-f590d2bbe559.png)
![20200725_110230](https://user-images.githubusercontent.com/68443484/88453353-6bdf3e00-ce66-11ea-9f58-f2c1163947d2.png)

Úgy néz ki nem tudnak sokat tenni a hiba ellen.

**Comment by andris155** [comment]
Egyelőre ezt lezárom. Talán egyszer lesz rá valami megoldás. Akiknek kell tudnak a hibáról.

**Comment by andris155** [comment]
330 OCD

**Comment by andris155** [comment]
poma megoldotta a hibát.

**Comment by VdszHun** [comment]
Köszönjük Poma! :D
