### ISSUE TITLE
Magma kocka spawner AI 

### ISSUE THREAD

**Issue by VdszHun** [andris155/TheOld-Crafters#3680]
**Szerver**: Survival
Ha magma kocka spawnerből spawnol egy nagy vagy közepes kocka majd megölöm a kissebeknek már lesz AI-ja. Csak egy kicsit kell AFK-nak lenni egy farm közelében és elszabadul a pokol (fotón). A kis FPS a rengeteg kocka miatt volt, szerintem több mint 100 lehetett.
Játékosnév: Vdsz
![invasion](https://user-images.githubusercontent.com/68443484/87824618-e3fda080-c875-11ea-9559-71708b610295.png)

**Comment by andris155** [comment]
Azért ilyen, mivel ez már csak a spawner által lerakott entitásokra vonatkozik. Ha megölöd és létrejön belőle egy másik az már más alapján jött létre. Biztosan meglehetne oldani, hogy kövesse le így is, hogy mi spawner-ből származó, de egy kis nehezítés szerintem nem árt ehhez.

**Comment by andris155** [comment]
Megírtam azért a szerverfájl fejlesztőinek, de nem valószínű, hogy mostanában javítják, vagy valaha javítják ezt. Rengeteg más sokkal fontosabb hiba is vár még a megoldásra.

**Comment by VdszHun** [comment]
Rendben. Köszönöm :)
