### ISSUE TITLE
Nether biome-os telken spawnolnak ellenséges mobok

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#3681]
![kép](https://user-images.githubusercontent.com/16057404/87828322-fa5b2a80-c87c-11ea-95af-57038dcbca1c.png)

![kép](https://user-images.githubusercontent.com/16057404/87828623-a3098a00-c87d-11ea-86e1-b62fe202f6af.png)

**Comment by andris155** [comment]
Csak az fog spawnolni, ami nincs benne a Spigot-ot monster részben. Az pedig szerintem nem problémás.

**Comment by andris155** [comment]
A hoglin és strider tud idéződni. Szerintem ez nem probléma.
