### ISSUE TITLE
Eltűnő vödrök zárt lávás SF rendszerből

### ISSUE THREAD

**Issue by Komjatius** [andris155/TheOld-Crafters#3682]
**Szerver**: Survival

Adott egy zárt lávás SF rendszer.
1 db fluid pump --> (lava bucket) --> 1 db puffer láda
--> (lava bucket) --> 1 db vaporizer --> (bucket) -->
--> (lava bucket) --> 6 db lava generator II --> (bucket) -->
1 db fluid pump
(Remélem, valamennyire érthető a séma.)
A rendszerben van rengeteg vödör, a puffer (dupla) láda tele van lávás vödörrel, és a fluid pumpban van 24 üres vödör.
Aztán kb. 2-3 nap múlva eltűnnek a vödrök, üres a láda, amiben a lávás vödröknek kellene lenni, nincs üres vödör a fluid pumpban, és a gépek csak akadozva dolgoznak, mert nem jön folyamatosan a lávás vödör.
Nem csak nálam, az én rendszeremben jelentkezett a hiba, 1.14 vadonban; ugyanez történt szabilcsnál, telek világban.
Szerintem nem a fluid pump a hibás, mert a vizes rendszerben nem jelentkezik a hiba - szerencsére, mert akkor leolvadnának a nuclear reactorok, ha akadozna a hűtőcella gyártás.

**Comment by skrisz0101** [comment]
Nálam nincs ilyen, pedig én még több felé is szórom a vödröket

**Comment by andris155** [comment]
Nekem az kellene, hogy mi nyeli el pontosan a vödröket. Hiába építem meg ezt a rendszert valószínűleg hibátlanul működne a teszt szerveren. Az is fontos, hogy a hiba reprodukálható legyen mindig. A Slimefun fejlesztő csak ilyet fogad el.
