### ISSUE TITLE
Tree growth accelerator hibás működés

### ISSUE THREAD

**Issue by Komjatius** [andris155/TheOld-Crafters#3683]
**Szerver**: Survival

Hetekkel ezelőtt csináltam auto fa farmot, androidokkal, és leraktam hozzá 5 tree growth acceleratort.
Egy ideig tökéletesen működtek, ahogy az andorid kivágta a fát, rögtön megjelent a zöld csillámlás az egyik csemetén (2x2 óriásfenyőket használok), és megnőtt a fa.
Nem tudom, mióta, mert nem figyeltem, csak ma tűnt fel, hogy nem nagyon jön a fa, nem működnek a tree growth acceleratorok normálisan, úgy, ahogyan kellene, és ahogyan működtek korábban.
Az andorid kivágja a fát, rögtön megjelenik a zöld csillámlás az egyik csemetén, és... Nem történik semmi. Nem nő meg a fa, csak ha kézzel csontlisztet szórok rá.

**Comment by skrisz0101** [comment]
Elvileg direkt nem növeszti meg egyből, hanem csak felgyorsítja picit

**Comment by andris155** [comment]
Elvileg direkt ilyen.
