### ISSUE TITLE
Új nether - mob spawn fent bedrockon

### ISSUE THREAD

**Issue by Komjatius** [andris155/TheOld-Crafters#3684]
**Szerver**: Survival

Nem tudom, hogy biztosan hiba-e, de a nether frissítés után arról volt szó, hogy fent a bedrockon már nem lesz mob spawn.
A frissítés másnapján építettem fent egy nagy házat, elég sokat elidőztem ott, és tényleg nem spawnolt mob.
Ma, miközben nether ice-t geominereztem, egyszer csak elkezdett spawnolni egy csomó piglin, hoglin, és persze rögtön támadtak is.
CoiledFlamee is látta, bár ha ő ott volt, akkor nem spawnoltak újabbak, csak amikor egyedül voltam.
Akkor most rendben van, hogy van mob spawn fent a bedrockon? Lehet akkor pl. építeni wither skeleton farmot? Vagy nem kellene spawnolnia ott mobnak?

**Comment by andris155** [comment]
Melyik változtatás volt ez, hogy nem lesz fent mob spawn? Én ilyenre nem is emlékszem.

**Comment by MrZero1** [comment]
Én sem

**Comment by VdszHun** [comment]
Üdv! Én sem emlékszem, hogy bedrock felett változtattak-e volna a mobspawnoláson. Magára a Bedrock blockra nem tud spawnolni mob viszont ha fölé kezdesz építkezni már tudnak. Pár farmfajta miatt szoktak bedrock felé menni, pl. Zombified Piglin (arany) farm.
Ha jól tudom spawnolható blokkokra csak akkor spawnol mob ha valamennyire eltávolodsz tőlük, amég a házad közelében vagy nem kéne gondnak történnie.
Itt egy fotó spawnolásról (mechanika).
Wither Csontváz farm nem oldható meg Bedrock felett mert a csontik csak a Nether Erődök területén belül spawnolnak. Felfele a legmagasabban lévő részéig tart a terület. A csapatommal készítem szerintem a legnagyobb Wither Csontváz farmot, ha érdekel tudok még mondani pár dolgot a spawn mechanikájukról. :)
![300px-Mob_spawning_ranges](https://user-images.githubusercontent.com/68443484/87937403-f570c380-ca94-11ea-879e-c9298911f90a.png)

**Comment by Komjatius** [comment]
OK, már értem a félreértés okát. Amikor arról volt szó, hogy a bedrockon nem spwnolnak, én úgy értettem, hogy ott fent nem spawnolnak, holott csak magára a bedrock blockra nem... És amikor leraktam a különböző SF cuccokat, a chunk határokat jelző blokkokat stb. azokra már tudnak. Bocsi.
