### ISSUE TITLE
Szín

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#3686]
**Szerver**: mindenhol

![kép](https://user-images.githubusercontent.com/29709854/87879140-1a0f6180-c9e9-11ea-860a-68709eb7928a.png)

![kép](https://user-images.githubusercontent.com/29709854/87879183-65c20b00-c9e9-11ea-88f1-363cfd36c323.png)

A &a szín helyett nem lehetne &c színt használni? Vagy csak az összegnél.

Az utalásnál, fogadásánál is.

**Comment by andris155** [comment]
Az alap fordításban zöld, és nem nagyon szeretném minden fordítás frissítésnél ezeket manuálisan átírogatni. Inkább maradnék a zöldnél. Ez a fordítás sokszor frissül és változik.
