### ISSUE TITLE
Üzenet küldés hiba

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#3687]
Véletlenszerűen elküldi az üzenetet írás közben anélkül, hogy entert nyomnék, másnak is volt már ilyen. Be sem zárja a chatet, csak random azt veszem észre, hogy a szöveg felét már elküldte. Sima 1.16.1-es Optifine kliens, modok nélkül.

![kép](https://user-images.githubusercontent.com/16057404/87885402-fadaf900-ca15-11ea-9301-3f764cbacf9d.png)

**Comment by andris155** [comment]
Több probléma is van ezzel, sajnos a ChatControl oldala hibás így én hibákat nekik jelenteni. De gondolom már mások jelentették ezeket rég. Ettől függetlenül nem sietik el a frissítést a javításokkal sajnos.
Feltettem a csoportban egy ezzel kapcsolatos kérdést. Szólj a játékosoknak, hogy szavazzanak, hogy nekik melyik tetszik jobban. Mert ha a régebbi EssentialsX megoldás jobban tetszik a többségnek én nem sok értelmét látom ezt használni.

**Comment by andris155** [comment]
Több probléma is van ezzel, sajnos a ChatControl oldala hibás így én hibákat nem tudok nekik jelenteni. De gondolom már mások jelentették ezeket rég. Ettől függetlenül nem sietik el a frissítést a javításokkal sajnos.
Feltettem a csoportban egy ezzel kapcsolatos kérdést. Szólj a játékosoknak, hogy szavazzanak, hogy nekik melyik tetszik jobban. Mert ha a régebbi EssentialsX megoldás jobban tetszik a többségnek én nem sok értelmét látom ezt használni.

**Comment by andris155** [comment]
Már egy másik privát üzenetküldési megoldást használunk. Az szerintem jól működik.
