### ISSUE TITLE
Hide and Seek heal potion nem működik

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#3689]
Hiába dobom el, nem ad regenerációt.

![kép](https://user-images.githubusercontent.com/16057404/87927335-598a8c00-ca83-11ea-9850-92d40075410a.png)

**Comment by UDPSendToFailed** [comment]
+1, elírás
![kép](https://user-images.githubusercontent.com/16057404/87928151-a02cb600-ca84-11ea-84e2-3c0ef98768c4.png)

**Comment by MrZero1** [comment]
A bájital már előző verzióban sem ment.

**Comment by andris155** [comment]
Az oké, hogy nem ment, de akkor nem is javítható?

**Comment by MrZero1** [comment]
Én nem tudom. 🤷🏼‍♂️

**Comment by MrZero1** [comment]
Amúgy nem gyógyító, hanem sebző bájital volt

**Comment by poma123** [comment]
kész
