### ISSUE TITLE
Slimefun warp

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#3690]
**Szerver**: Szurvi, ?sav?
Elég gagyi hogy slimefun warpon nem lehet sf guide könyvet nézni :D 
Épp egy kezdőnek akartam segíteni aki slimefunozna, épp a warpon volt.
elég szar futkosni a warp és a sima világok között. nem lehetne áttenni event világból?

**Comment by UDPSendToFailed** [comment]
Akkor már a warp farmot is

**Comment by andris155** [comment]
A spawn2 világba szerintem át lehetne rakni. Maximum több részben kell megoldani okosan a másolást, hogy ne bírja a worldedit plugin, ami csak 1 processzor magot tud kihasználni, amivel ráadásul még a szerveren is osztozik.

**Comment by andris155** [comment]
A spawn2 világba szerintem át lehetne rakni. Maximum több részben kell megoldani okosan a másolást, hogy bírja a worldedit plugin, ami csak 1 processzor magot tud kihasználni, amivel ráadásul még a szerveren is osztozik.

**Comment by MrZero1** [comment]
Hajrá.

**Comment by poma123** [comment]
Sok sikert kívánok hozzá, az összes item frame-ben lévő cuccot pedig akkor lehet egyesével átvinni. Ja és az armorstandeket is.

**Comment by andris155** [comment]
Ameddig nincs iskola kb. sosincs olyan idő, amikor ébren lennék, és kevesen vannak hogy ne okozzak vele nagy laggokat. Talán majd a távoli jövőben megvalósítom. Bár lehet idén már nem is lesz iskola sem, hanem a távoktatás fog továbbra is menni. Ez már lehet csak 2021-ben valósul meg akkor.

**Comment by poma123** [comment]
De durva, hogy már 2021 jön ':D
