### ISSUE TITLE
Survival szerver

### ISSUE THREAD

**Issue by danylUK69** [andris155/TheOld-Crafters#3691]
**Survival**: 1v1 arenaba tobb kit, illetve a delayt kilehetne szedni egy pluginnal. Nagyon sok jatekos 1.8ban pvpzett sokat, es szerintem ez nagyobb sikert jelentene.

**Comment by andris155** [comment]
Az új pvp biztosan nem lesz kiszedve. Valamikor a jövőben változtatnak rajta, de az a rendszer soha nem fog visszakerülni ami az 1.8-ban volt. De talán jobb is. Az új rendszerhez inkább ügyesség kell, nem csak gyorsan nyomkodni az egér gombot.

**Comment by andris155** [comment]
https://github.com/andris155/TheOld-Crafters/issues/3693

**Comment by danylUK69** [comment]
Szia.
Kitoltottem Survival szerverre egy segítő tgf lapot. Mikorra várhatóaz
eredmény?

András Marczinkó <notifications@github.com> ezt írta (időpont: 2020. júl.
20., H 23:29):

**Comment by andris155** [comment]
Csak akkor küldünk választ, ha bekerülsz. 2-3 hét.

**Comment by danylUK69** [comment]
Nem pontosan értem. Ingame nevem az KrissKha. Segítőkész vagyok mindenki
számára, segítettem is nagyon sok embernek. Alap pluginokkal/parancsokkal
tisztába vagyok. Mar jatszok legalabb 2hete a szerveren és nincs olyan
akivel rosszba lennék.

András Marczinkó <notifications@github.com> ezt írta (időpont: 2020. júl.
22., Sze 18:39):
