### ISSUE TITLE
MagicCobblestoneGenerator

### ISSUE THREAD

**Issue by Conaniwnl** [andris155/TheOld-Crafters#3692]
**Szerver**: Savsziget

Szigeteken nem lehet fejleszteni a cobblestone generator-t, nincs ott a gold block a fejlettebb szinteknél, amivel meglehetne vásárolni az adott fejlesztést. 

Ez a fejlesztő githubján már volt jelentve, elvileg az _Upgrades Addon_ használata szükséges a teljes működéshez.

https://github.com/BentoBoxWorld/MagicCobblestoneGenerator/issues/60

**Comment by andris155** [comment]
Elvileg javítva.
