### ISSUE TITLE
Ládás akármi

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#3694]
**Szerver**:Survin vagyok

Nem tudom hiba e, de szerintem eddig nem így volt, és nekem most ez zavaró :D

Szóval, van egy láda, random tárgyakkal benne, össze-vissza.
![kép](https://user-images.githubusercontent.com/29709854/88095823-01907a00-cb96-11ea-83ec-9b322bb4b577.png)

Ahogy szedném ki a cuccokat, lenyomom a shift-et, hogy gyorsabban az invembe rakja, erre a láda tartalma magától rendeződik, bekerül minden az első sorba.

![kép](https://user-images.githubusercontent.com/29709854/88095841-081ef180-cb96-11ea-8a37-b2117855f640.png)

(Más szerveren nincs ilyen, most néztem meg)

**Comment by Conaniwnl** [comment]
Sav-on is jelen van, elég ha bárhová kattintasz 2x a ládában és elrendezi.

https://www.youtube.com/watch?v=ZboCWpwmzLc

**Comment by MrZero1** [comment]
Nem tudom, neked a chestsort be van e kapcsolva, nekem nincs.

**Comment by Conaniwnl** [comment]
Nincs.

**Comment by andris155** [comment]
Majd ki kell kapcsolni a gombokkal való rendezést.

**Comment by andris155** [comment]
javítva

**Comment by MrZero1** [comment]
Most ahogy csinálom az új kiteket, ládába rakom őket, ahogy beraktam, még mindig fennáll a hiba (?)

**Comment by Conaniwnl** [comment]
> Most ahogy csinálom az új kiteket, ládába rakom őket, ahogy beraktam, még mindig fennáll a hiba (?)

Sav-on is dupla kattintás-os dolog elrendezi (Ahogy a videómban van.), viszont ezt a SHIFT-es et nemtudom reprodukálni.

**Comment by andris155** [comment]
Letiltottam elvileg most tényleg véglegesen ezt.
