### ISSUE TITLE
Csalásvédelem OldSpace

### ISSUE THREAD

**Issue by poma123** [andris155/TheOld-Crafters#3695]
**Szerver**: OldSpace

Valamiért ha lovon ülnek behülyül és ledobja őket, de úgy hogy közben másik nézetből rajta ülnek (az én szemszögemből).
Hiba a konzolban:
```
[NoCheatPlus] Exception with AutoListener(fr.neatmonster.nocheatplus.checks.moving.MovingListener.onPlayerMove/org.bukkit.event.player.PlayerMoveEvent/LOWEST), processing org.bukkit.event.player.PlayerMoveEvent: InvocationTargetException See earlier in this log, search for -> log once id=2082522215
```

**Comment by andris155** [comment]
A túlélő szerveren is van ilyen probléma?

**Comment by poma123** [comment]
Nem tudok róla, de a túlélő 1.16os ez pedig 1.15 + 1.16 kamu támogatás

**Comment by andris155** [comment]
A cheat védelem elvileg 1.8-ig visszafelé is kompatibilis. Viszont a kamu támogatást semmi se nagyon preferálja. Majd megpróbálom akkor oda vissza rakni a régebbi cheat védelem verziót. Hátha abban jobb.

**Comment by andris155** [comment]
Holnap betölt a régebbi verzió, kérlek majd teszteljétek újra.

**Comment by andris155** [comment]
Jó lett?

**Comment by poma123** [comment]
Nem volt vele probléma, szóval akkor ez javítva. Köszi

**Comment by andris155** [comment]
Szerintem ameddig nem frissíted 1.16.x-re vagy 1.17-re addig nem fogom ott ezt már frissíteni.

**Comment by poma123** [comment]
Az a baj, hogy legalább egy hétig eltartana az ottani világok frissítése.

**Comment by andris155** [comment]
Szerintem ugyanannyi GB-ra mint a túlélő. Tehát az idő is kb. ugyanannyi.

**Comment by poma123** [comment]
Hát nem tudom.
