### ISSUE TITLE
Óránkénti levédésblokk 

### ISSUE THREAD

**Issue by Shryxx** [andris155/TheOld-Crafters#3696]
**Szerver**: Survival

A jelenlegi 100 blokk/óra a kezdőknek elég rossz.. egy normális kis házat nem lehet annyival levédeni.
Lehetne óránként 200 blokk legalább, vagy ha ez már túl jó lenne, akkor maradhatna a 100 és ha feljön elsőnek a player akkor kaphatna kezdésnek 400 vagy 500 blokkot.

**Comment by andris155** [comment]
@MrZero1 neked mi a véleményed erről?

**Comment by MrZero1** [comment]
Ha kezdőnek be lehet állítani 300-400 blokkot akkor oké, de én nem szeretnék óránkénti 200 blokkot

**Comment by Shryxx** [comment]
150 sem lehetne? Az egyáltalán nem sok.

**Comment by MrZero1** [comment]
Azért figyelembe kell venni a sok afk-olót is, amit hiába nem kellene, mégis afkolnak, pedig elvileg játszani járnak fel a szerverre :D

**Comment by andris155** [comment]
Nem lehet állítani külön a kezdőknek, csak egységesen.

**Comment by skrisz0101** [comment]
Több a nem afkoló mint az afkoló
Nem afkolók nyertek, legyen több ✌️
Pár ember miatt kicseszés lenne a több száz (vagy ezer) kezdővel szemben

**Comment by poma123** [comment]
> Nem lehet állítani külön a kezdőknek, csak egységesen.

Dehogynem lehet, ezt a levédésblokk számot kapják meg a kezdők.
```
InitialBlocks: 100
```

**Comment by MrZero1** [comment]
Akkor legyen a kezdőknek 300 vagy 400 blokk.

**Comment by poma123** [comment]
Beállítottam 300-ra.
