### ISSUE TITLE
[Lock] hiba levédésekben

### ISSUE THREAD

**Issue by VdszHun** [andris155/TheOld-Crafters#3697]
**Szerver**: Survival
Ha trustolok egy személyt egy levédésben ki tud nyitni bárki által lock-olt ládát. Nem muszáj a [lock]-on lennie a nevének.
A Lock táblát viszont csak a láda tulajdonosa tudja kiütni.
Poma tanúja volt a tesztelésnek.
Játékosnév: Vdsz

**Comment by andris155** [comment]
Érdekes egy hiba. Hétvégén majd utána járok ennek.

**Comment by Shryxx** [comment]
Telkeken is jelen van a hiba

**Comment by andris155** [comment]
javítva
