### ISSUE TITLE
Survival: Szuper sisak szépséghiba

### ISSUE THREAD

**Issue by Icecroft** [andris155/TheOld-Crafters#3698]
A szuper sisakon van egy éjjellátás effekt, amin érdemes lenne vátoztatni:
Az éjjellátás 15 másodpercre töltődik fel kb 6-7 másodpercenként, így az 10 másodperc alá is bemegy, amikor az effekt villogó háttérrel jelzi, hogy hamarost vége => Tehát a szuper sisak 6-7 másodpercenként villogó hátteret eredményez ami kellemetlen.
A Night vision google 30 mp-re töltödik, így az soha nem éri el a 10 másodpercet, azaz nem ad villogó hátteret.
Javaslom, hogy a szuper sisak éjjellátás effektjét 15-ről 30 mp-re állítsátok, hogy ne okozzon szemrángást.

**Comment by andris155** [comment]
@MrZero1?

**Comment by MrZero1** [comment]
Mindjárt megcsinálom

**Comment by poma123** [comment]
Javítva, köszi a jelentést.
