### ISSUE TITLE
Survival slime blokk kilövő

### ISSUE THREAD

**Issue by PoopScoop100** [andris155/TheOld-Crafters#3699]
Survival --> A slime blokk kilövő redstoneos építmény tulélő módban nem működik az anti-cheat miatt ami meggátolja a működését.

**Comment by poma123** [comment]
#3644

**Comment by andris155** [comment]
Nem fogja támogatni a Slimefun-t szerintem. Hiába írod bele. Bár egy üzenetet majd megér a fejlesztőnek.

**Comment by andris155** [comment]
508 OCD

**Comment by andris155** [comment]
PoopScoop100 nevet nem találtam a MineMarket-en.
