### ISSUE TITLE
Levédésblokk.

### ISSUE THREAD

**Issue by mnbTOC** [andris155/TheOld-Crafters#3700]
Legföbb Survival.

Szerintem ha meglehet oldani akkor lehetne úgy hogy minnél nagyobb a rang annál több levédésblokkot kapu k oránként most 1 óra alatt az a 10x10-es levédésre elég 100 blokk az semmi..

Pl tag+ az 125 blokk /óra (mert lehet szavazással szerezni a rangot)
A V.I.P az 150 blokk/óra (ugyanugy szavazással szerezhető rang)
Elit az 200 blokk/óra.
Prémium az 250 blokk/óra
Old az 300 blokk/óra

**Comment by andris155** [comment]
Volt már róla szó, de végül az lett a döntés, hogy nem került megvalósításra.
