### ISSUE TITLE
1.16 lépcső

### ISSUE THREAD

**Issue by mnbTOC** [andris155/TheOld-Crafters#3701]
Survival.

Skrisz01 boltjában a nether részlegnél az új fajta Blackstone lépcső van (nether részleg ahol felmész emeletre) és én a mai nap nem birtam felsétálni rajta mivel az anticheat mindig visszarakott az aljára.

**Comment by poma123** [comment]
#3644

**Comment by andris155** [comment]
A következő verzióban javításra került. Amint lesz időm frissítem.

**Comment by andris155** [comment]
javítva
