### ISSUE TITLE
Slimefun - Slimy TreeTaps addon

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#3703]
**Szerver**: Szurv, sav

Ma teszten pomával néztünk valamit és feltűnt h az addonban van egy új cucc. lehet benne már 1.16os új lámpást is craftolni, ami szerintem elég hasznos, mert eléggé nehéz szerezni, pláne ha sok kell. (új nether gombákon nő 1-2db)

Ezen kívül ugye az alap tulajdonsága: Plastic sheetet szerezni automatán. szerintem jó lenne, bekerülhetne.
Régebben szó volt róla h bekerül, de most lett +1 cucc hozzá ami hasznos, jó lenne

**Comment by MrZero1** [comment]
Minden automata, legalább valamivel foglalkozni is kell, ami nem baj. Szerintem.

**Comment by andris155** [comment]
@MrZero1-nek teljesen igaza van.

**Comment by skrisz0101** [comment]
pff
