### ISSUE TITLE
/warp ládák - ládák

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#3704]
**Szerver**: Szurv, sav
Ez az ,,új" ládanyitás nem rossz, de szerintem eléggé lassú. mire végpörög, megunom az életem. nem lehetne ennek az idején csökkenteni? eléggé unalmas ha pl nyitok 20 fortunát és vagy fél órán át itt állok. +Régen volt hang is mellé, szerintem mehetne most is, mert fura némán xd

+Eléggé laggos sokszor, ez mégjobban lassítja

**Comment by MrZero1** [comment]
Nem tudom miért lett kicserélve, nekem az előző jobban tetszett

**Comment by andris155** [comment]
Majd vissza rakom a régebbit. A jelenlegiben több hiba is van.

**Comment by poma123** [comment]
Akkor jó hogy dolgoztam vele :)

**Comment by andris155** [comment]
Nem minden fejlesztés válik sajnos be. Ez sajnos ilyen. :/

**Comment by andris155** [comment]
Elvileg visszaállítottam.
