### ISSUE TITLE
Oldspace hiba

### ISSUE THREAD

**Issue by szofogado** [andris155/TheOld-Crafters#3705]
Oldspace-en ha egy holt vezér, csontvázló, vagy egy zombi amazon hal meg a lávában, akkor a tárgy amit droppol örökké ég. Ilyenkor 1-2 másodpercenként lejátsza az item elégésének hangját. Csak a láva közelében lehet hallani,

**Comment by poma123** [comment]
A mobok által dobott itemek nem égnek el direkt.
