### ISSUE TITLE
Sf láda, legendás láda

### ISSUE THREAD

**Issue by Conaniwnl** [andris155/TheOld-Crafters#3706]
**Szerver**: Savsziget

- Lucky Blockból lehet kapni SF láda kulcsot, de nincs SF láda.
- Ugyan ez Legendás, Ultrakirály, Varázslatos ládával. _EDIT: Legendás láda van, de nem lehet a kulcsal kinyitni._
- /warp ládák-nál a ládák feletti színezés eltűnt.

![2020-07-23_17 12 26](https://user-images.githubusercontent.com/40923017/88316759-991dd600-cd18-11ea-8122-e725f7c2f6e4.png)

**Comment by andris155** [comment]
![2020-07-24_11 31 21](https://user-images.githubusercontent.com/8324198/88378415-3c1a3280-cda1-11ea-8168-c1d69acd48d0.png)
A forráscsomagod nem támogatja a színezett betűket szerintem, mert nekem tökéletesen megjeleníti.

**Comment by andris155** [comment]
Nekem működik a legendás láda nyitása. Neked mit ír ki a nyitásnál?

**Comment by Conaniwnl** [comment]
> Nekem működik a legendás láda nyitása. Neked mit ír ki a nyitásnál?

A lucky blockból kapott kulccsal nem nyitja ki a Legendás ládát, mert az a survis Legendás ládához való.

**Comment by Conaniwnl** [comment]
> A forráscsomagod nem támogatja a színezett betűket szerintem, mert nekem tökéletesen megjeleníti.

Itt támogatja?

![2020-07-24_12 35 16](https://user-images.githubusercontent.com/40923017/88391765-1732b900-cdbb-11ea-8b36-d05c2c94a652.png)


https://www.youtube.com/watch?v=VS_OTfIr20g

**Comment by MrZero1** [comment]
Raktam be váltót a ládák warphoz, egy hóembert kell keresni.

**Comment by andris155** [comment]
A leírt ládákat kiszedtem a nyereménylistából. Holnap betölt a változtatás.
