### ISSUE TITLE
Régi nether home hiba 

### ISSUE THREAD

**Issue by kBalix** [andris155/TheOld-Crafters#3708]
**Survival szerver**
Ha a régi nethernél lévő homeom-ra tp-zek, akkor az új nether tetejére dob.
![received_319777342493617](https://user-images.githubusercontent.com/59265474/88326588-827e7b80-cd26-11ea-88f4-2751c13bd512.png)

**Comment by poma123** [comment]
Mivel a régi home-od ugyanolyan nevű világban volt, mint a mostani. Ennek pont így kell működnie.

**Comment by andris155** [comment]
Nem töröltem ki a fájlokból ezeket az otthonokat. Nem túl egyszerű megcsinálni, hogy csak azt részt törölje, ami hozzá tartozik. A jövőben lehet foglalkozok majd ezzel és akkor ha lesz ilyen világ reset, akkor törölve lesznek a régi otthonok onnan.

**Comment by poma123** [comment]
+ azért dob a tetejére, mert valószínűleg a régi otthonod a blokkokban van, így a legközelebbi biztonságos helyre teleportál, ami úgy tűnik a nether teteje.
