### ISSUE TITLE
/home bed és Falusiak

### ISSUE THREAD

**Issue by WolterFox** [andris155/TheOld-Crafters#3709]
Nos, nem tudom, hogy jött ez elő, de valamiért ha közelben vagy egy falusihoz aki aluszik akkor az lényegében valahogyan egy sethomeot csinál oda. Nem tudom, hogyan áll elő, de elég sokszor (kb 5-6-szor) előfordult miközben falusiakkal babrálok. Ez elég nagy problémák szoktak lenni mert be tudunk ragadni elég szűkös helyekre.

**Szerver**:Survival

**Comment by andris155** [comment]
Nem tudom mitől ilyen. Szerintem a bed-et inkább ne nagyon használd otthonnak.

**Comment by WolterFox** [comment]
10/10 review, köszi andris, nagyon hűvüs

(tudom, hogy nehéz megtalálni és nem fogom nyugi :c)

**Comment by andris155** [comment]
Megpróbáltam reprodukálni, de hiába aludt mellettem több falusi, akkor sem módosult a bed otthonom.

**Comment by andris155** [comment]
Szerintem lehet, amikor kinyitod a a falusi házak ajtaját véletlen rá kattintasz valamelyik ágyra.
