### ISSUE TITLE
Slimefun - Cobblestone Generator probléma

### ISSUE THREAD

**Issue by Komjatius** [andris155/TheOld-Crafters#3710]
**Szerver**: Survival

Nagyon érdekes hiba, mert építettem 4 gyárat, és 3 helyen jelentkezik, 1 helyen pedig nem.

Eredetileg 1 db Cobblestone Generator több cobblestone-t termel, mint amit fel tud dolgozni 2 db LVL II-es Electric Ore Grinder.
Az én saját gyáramban ezért 10 db Cobblestone Generator bőven el tudott látni 24 db Electric Ore Grinder II-t, mindig volt cobblestone a puffer ládákban. 
Angi gyárában 10 db Electric Ore Grinder II-höz 4 db Cobblestone Generator volt, és így volt stabil a rendszer.

Tegnap viszont valami megváltozott. 
Hiába tettem be pluszban 2 db Cobblestone Generatort a saját gyáramba, így már 12 db van, alig termelnek, a puffer ládák folyamatosan üresek, és néha meg-megállnak  az Electric Ore Grinderek, nyersanyag híján.
Hiába tettem be pluszban 1 db Cobblestone Generatort Angi gyárába... Ugyanez.
A mi gyáraink egymás mellett vannak, 1.14 vadonban.
Benszulottnek segítettem ma, kb. 1 órája építeni egy új gyárat, az 1 db Cobblestone Generator nem termel annyit, hogy elég legyen a 2 db Electric Ore Grinder II-nek. Az ő gyára telekvilágban van.
És akkor az extra poén... OikosHUN gyára, szintén telekvilágban, normálisan működik. Nála 6 db Cobblestone Generator van, 12 db Electric Ore Grinder II-re, és folyamatosan tele vannak a pufferládák, túltermelés van cobblestone-ból.

Van erre valami magyarázat? S még inkább megoldás?

Áram, cargo rendben van, nem ez a probléma oka.

**Comment by skrisz0101** [comment]
Röviden: mintha lassult volna a cobble gen termelése, pedig nem kéne

**Comment by Komjatius** [comment]
> Röviden: mintha lassult volna a cobble gen termelése, pedig nem kéne
> (nem minden esetben(?))

Jól van na, jogász vagyok, szeretek hosszan írni.
De igen, nagyjából arról van szó, ahogyan összefoglaltad.

**Comment by VdszHun** [comment]
![20200724_111546](https://user-images.githubusercontent.com/68443484/88377233-1a1fb080-cd9f-11ea-86e6-b0472f69f4b4.png)
A Slimefun szerverén megkérdezte mnb de azt mondták neki, hogy nem piszkálták, max. itt a szerveren lassíthattak rajta. Erre majd válaszolnak andrisék.

**Comment by andris155** [comment]
12-re van állítva.

**Comment by andris155** [comment]
Mivel a brutális nagy cargo rendszerektől laggol a szerver, gondolom azért lassabb. Erre nincs megoldás.

**Comment by poma123** [comment]
Igen, a tps miatt lehet.

**Comment by Komjatius** [comment]
Hát, ezt zseniálisan megmagyaráztátok, megoldottátok... Igaz, hogy nyilván nem igaz, mert van, ahol jelentkezik, van, ahol nem... És olyan helyen is jelentkezik, ahol nincs a közelben semmi nagy cargo rendszer...
De hát lezárni egyszerűbb, mint rájönni a valós okra és megoldani a problémát. :D

**Comment by poma123** [comment]
Van amikor* és van amikor* nem jelentkezik, mivel folyamatosan változik a TPS. Ha lenne egy rövid reprodukálási leírás akár egy videóval, talán jelenteni is lehetne a fejlesztőnek. Semmi hibát nem ír a konzol, így elegendő információ híján ők se fogadnák el a jelentést, ez van. Emiatt nem kellene rögtön támadni :)

**Comment by poma123** [comment]
Saját magát lassítja a Slimefun, hogy megszűnjön a lag. Emiatt lehet, hogy egyik rendszer gyorsan működik, de a másik pedig nem.

**Comment by Komjatius** [comment]
Ha mondjuk valaki, aki illetékes, rászánná az időt, és megnézné a problémát, ahol jelentkezik, ahol nem, és együtt gondolkodnánk, hogy mi változott hirtelen egyik napról a másikra, akkor nem támadnék. De egy nyilván kamu válaszra persze, hogy ugrom.
Mert értem én, hogy sok cargo, meg lag... De tegnapelőttig ezek nem voltak? Most meg egyik helyen vannak, egyik helyen nem?
Az is lehet, hogy van valami valós ok. Hogy valamit én csinálok rosszul. De akkor ezt találjuk ki valahogy együtt.

**Comment by poma123** [comment]
Én sajnos nem értek magához a cargo-hoz mint játékbeli funkció, csak azt tudom hogy hogyan kellene működnie, és mi történik, ezt le is írtam fentebb. Szerintem ha van kedve, @skrisz0101 -el karöltve kellene ennek utánajárni, hogy pontosan mi a különbség a két cargo rendszer között, ahol működik és ahol nem működik. Innen lehetne levonni következtetést, és rálelni a hibára.

**Comment by Komjatius** [comment]
Köszönöm. Tudom, hogy skrisz is meglehetősen elfoglalt, de ha lesz 10 perce, biztosan kiötlünk valamit. Mnb-vel már ötleteltünk tegnap, de azok az ötletek nem váltak be.

**Comment by poma123** [comment]
Vártam, hogy írd, de akkor írom én: Sk-val kiderült, hogy tényleg a TPS miatt lassul le minden Sf gép. Viszont a cargo-tól laggol a szerver, szóval ez nagyon finom.

**Comment by Komjatius** [comment]
OK, tegyük fel, hogy így van. De. Mikor itt nálam este 10 van, nálatok hajnali 4, visszajövök az újraindítás után, egyedül vagyok az egész szerveren, ergo nincs betöltve semmi, csak az én kis világom... Akkor mitől laggol a szerver? Mitől alacsony a TPS? Mert azt még aláírom, hogy nap közben, amikor majdnem minden gyártulajdonos fent van, majdnem minden gyár be van töltve...
Na, mindegy, rakok be pluszba pár cobble gent, oszt' jónapot.

**Comment by skrisz0101** [comment]
Akkor is lassú ha csak te vagy fent?

**Comment by Komjatius** [comment]
Most e percben ketten vagyunk fent, és megcsináltam ugyanazt a trükköt, mint te, hogy blaclkistre tettem a cargot... Nem egyenletesen termelődik a kő, néha belassul, akár 2-3 másodperc is eltelik, de általában normális a sebessége.

**Comment by andris155** [comment]
Szerintem a Slimefun-ban változott valami. De a fejlesztőnek már úgyis megírták GitHub-on. Szóval elvileg tud róla. Megoldani mi nem fogjuk tudni sajnos ezt.
