### ISSUE TITLE
Survival bújócska hiba

### ISSUE THREAD

**Issue by szofogado** [andris155/TheOld-Crafters#3711]
Surivalon a bűjócska nevű minigame-ben, ha megveszed az álca kereső perk-et, majd ha, megveszed az álca választót akkor elvileg szándékosan nem lehet venni speciális blokkokat, hogy ígazságosabb legyen a játék. Viszont, ha elösször az álca választót veszed meg és egy speciális blokkot, majd utánna az álca keresőt akkor vehetsz speciális blokkokat és mind a kettő perk-et használhatod
(ha ez nem számít hibának akkor bocsánat!)

(nem tudtam videót küldeni mert csak ilyen formátumú fájlokat lehet küldeni: GIF, JPEG, JPG, PNG, DOCX, GZ, LOG, PDF, PPTX, TXT, XLSX, ZIP Lehet én nem értek hozzá)
Válaszukat előre is köszönöm!

**Comment by andris155** [comment]
Sajnos nem tudok erre megoldást. Ezt a plugint nem nagyon frissítik így hiába jelentem a hibát a fejlesztőnek nem leszünk vele előrébb. A hibajelentést azért köszönjük.
