### ISSUE TITLE
1.16os old kapa

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#3714]
**Szerver**: Minemarket, Szurvi, Sav
1.16tól lehet már enchantolni a kapákat, esetleg az old kapán is lehetne szerencse X meg valami hasznos mellé, bár nemtom a szerencsén kívül mi lehetne jó xd

/warp beváltó-ra meg lehetne rakni a régi és az új old kapa között cserét

**Comment by MrZero1** [comment]
Eddig is lehetett enchantolni a kapákat, csak most már rálehet rakni a szerencse és gyengédérintés enchantot :D Gyengéddel a lombot adja meg, szerencsével meg csemetét, botot. Illetve bizonyos blokkokat (pl. céltábla, szivacs stb.) gyorsabban üti ki. Viszont most már lehetne Minemarketben egy ilyen, egy olyan kapa.

**Comment by MrZero1** [comment]
![kép](https://user-images.githubusercontent.com/29709854/88415703-37746f00-cddf-11ea-8310-10a428c5ca83.png)
 Ez a 2 új kapa került be a régi helyett, viszont beváltó nem lesz rá, hiszen ez újításként jött be.

**Comment by andris155** [comment]
Cserét semmiképpen se rakjunk szerintem. Aki jobbat szeretne vegyen jobbat. Miért cserélnénk egy rosszabb kapát egy jobbra?

**Comment by MrZero1** [comment]
Ahogy látom, bekerült Minemarketbe, így lezárom ezt a jelentést. Csere nem lesz.

**Comment by andris155** [comment]
Bekerült, igen.
