### ISSUE TITLE
Eltűnődő szigetek

### ISSUE THREAD

**Issue by Conaniwnl** [andris155/TheOld-Crafters#3715]
**Szerver**: Savsziget

Több játékosnál is (eddig 2) elveszett a sziget, olyan értelmben, hogy ottvan viszont még sincs. 

![2020-07-25_19 09 13](https://user-images.githubusercontent.com/40923017/88464460-29941c00-cebb-11ea-862d-97247969856a.png)

A sziget látható viszont a /is info parancs azt adja vissza, hogy "Itt nem található sziget." Semmi joguk, nem tudnak semmit csinálni ebből kifolyólag.

**Comment by MrZero1** [comment]
@andris155

**Comment by Conaniwnl** [comment]
Kingus szigetet megkerűlt /is info is kiadja, már csak majd tulaj jog kell neki. 2. páciens pedig újrakezdte.

**Comment by KulGery** [comment]
Csak halkan szólok, az én szigetemről is kirugtak...
Vagy lehet, hogy frappánsan magamat rugtam volna ki?

**Comment by KulGery** [comment]
![image](https://user-images.githubusercontent.com/25465311/88848210-6b3d0380-d1e8-11ea-923c-bdbba874a076.png)

**Comment by Conaniwnl** [comment]
> Csak halkan szólok, az én szigetemről is kirugtak...
> Vagy lehet, hogy frappánsan magamat rugtam volna ki?
> 
> Azaz a /is info azt írja, nincs tulaja a szigetemnek

Szerencsére ez a történet is boldogan zárult. Mindeki megkapta a magáét, ki jót, ki rosszat, ki a szigetét. De mi jöhet még ezután?

**Comment by andris155** [comment]
Majd végig nézem a szigeteket és újra regisztrálom őket már amelyiknél megtudom nézni kié...

**Comment by andris155** [comment]
Nem tudom miért törlődtek az adatbázisból.

**Comment by andris155** [comment]
Visszaállítottam, amit lehetett a mentésből. Sajnos így is van jó pár sziget, amiknek valószínűleg nincs tulajdonosuk. Mivel több 1000 sziget van nem igazán lehet többet tenni ezzel. Valamelyik verzió valamikor hibás volt a plugin-ból, és elnyelte a fájlok egy részét... Akinek van esetleg szigete és nem került visszaállításra és tudja esetleg hol van, annak visszatudjuk adni manuálisan a szigetét.

**Comment by Conaniwnl** [comment]
A mai álligatás szült egy újjabb problémát, miszerint már parancsal a tulajdonos jogot se tudjuk visszadni (vagyis zéró nemtudja), ami eddig legalább működött. A hiba WolfiGirly02 szigetén jelentkezett (egyelőre), állítása szierint délelött még "javába" játszott.

**Comment by KulGery** [comment]
Igen, örvendek, hogy újra tulajdonlom a szigetemet ;-)
És sajnálom a második LányFarkast, hogy Jávában javában játszva elvesztette tulajdonosi tulajdonságát a szigetén. :.(

**Comment by andris155** [comment]
Milyen hibát ír ki?

**Comment by Conaniwnl** [comment]
> Milyen hibát ír ki?

Erről @MrZero1 tuna pontosan beszámolni, viszont szerintem semilyet. A parancs lefut, viszont a szigethez nem adódik hozzá a tulajdonos, ugyan úgy azt írja, hogy nincs tulajdonos, még ha magát is akarta hozzáadni Zéró. Én így értettem, de Zéró csinálta így őtudja.

**Comment by MrZero1** [comment]
Megcsináltam, beállítottam a szigetét. Sweet elmondta a parancsot (végre): /acid tp név
