### ISSUE TITLE
Sward of beheding bag

### ISSUE THREAD

**Issue by Shryxx** [andris155/TheOld-Crafters#3716]
**Szerver**: Survival
Lefejezős kard nem dobja ki a wither skeletonok fejét elvileg.
Sok szerencsét a reprodukációs folyamathoz.

- **Tanács1**: **Wither** skeletont ölj ne mást.

- **Tanács2**: Ne **vas** karddal csináld hanem **Sf-es** sword of beheading cuccal

**Comment by andris155** [comment]
Legközelebb normálisan írj ha hibajelentést írsz kérlek. Ilyen tanácsokat pedig teljesen felesleges beleírni.

**Comment by andris155** [comment]
Nem sikerült reprodukálni. 25% eséllyel dob, szóval nem mindig.

**Comment by andris155** [comment]
4-ből 3 Wither skeleton dobott nálam fejet.

**Comment by Shryxx** [comment]
Ügyfelem azt mondta neki 20-ból egy sem. Lehet át lettem verve
