### ISSUE TITLE
MCMMO /inspect

### ISSUE THREAD

**Issue by Shryxx** [andris155/TheOld-Crafters#3717]
**Szerver**: Mindegyik ahol van MCMMO
/inspect paranccsal ha egy staff gm 3-ban a közeledben van le tudod nyomozni.
Van rá egy beállítás hogy mindig kiírja a szinteket nem csak amikor a közeledben van a player/staff az jó lenne.

**Comment by andris155** [comment]
Ha elrejti magát a staff, akkor szerintem nem fogod ezzel sem látni. Mindent nem akarok tiltani vagy átállítani ez miatt.

**Comment by poma123** [comment]
Egyébként de, működik akkor is.

**Comment by Shryxx** [comment]
És akkor ennyi? Nézzék nyugodtan a staffokat? Hát ez csodás, akkor ennyi erővel survivalban is lehetne tp-zgetni

**Comment by andris155** [comment]
Aki hozzáfér a konzolhoz látni fogja és legalább lehet tudni, hogy valamit valószínűleg rejteget a játékos és érdemes lenne jobban utána járni.
