### ISSUE TITLE
Explosive Bow

### ISSUE THREAD

**Issue by Shryxx** [andris155/TheOld-Crafters#3720]
**Szerver:** Survival, Savsziget

Vannak páran akik csak trollkodnak vele. Dobálják vele a játékosokat és le is tudják lökni őket valami magas helyről, amibe meg bele is halhatnak. Eléggé idegesítő. Nem lehetne letiltani vagy valami?

**Comment by MrZero1** [comment]
Az lenne a legjobb, ha más területén nem 'robbanna'.

**Comment by poma123** [comment]
Nem szeretnék ezzel is napokat tölteni, amíg beküldöm, átnézik és elfogadják. Inkább legyen akkor letiltva.

**Comment by poma123** [comment]
Holnap betölt.
