### ISSUE TITLE
Slimefun backwards-compatibility kikapcsolása

### ISSUE THREAD

**Issue by poma123** [andris155/TheOld-Crafters#3721]
**Szerver**: Survival, Savsziget

Ezzel rohamosan csökkenni fog a lag, amit a Slimefun okoz. Nekünk nincs szükségünk erre, mivel a Slimefun 2019. októberében került be a szerverre, így nincs olyan sf-es item, ami 2019 nyara előtt készült volna. (Az azelőtt készült itemek nem lennének használhatóak ennek kikapcsolásával.)

**Comment by andris155** [comment]
Legalább már tudom mit takar az a szöveg benne. De amúgy erre nem is kellett volna ide írni. Kikapcsolod és kész. :D

**Comment by poma123** [comment]
Csak hogy tudj róla :D

**Comment by poma123** [comment]
Holnap betölt.
