### ISSUE TITLE
Párbajfelkérés (/1v1, /duel) letiltása.

### ISSUE THREAD

**Issue by Shryxx** [andris155/TheOld-Crafters#3722]
**Szerver**: Survival, akár Savsziget is

Tag rangtól lehetne engedélyezni a párbajfelkérés letiltását, mivel néha elég zavaró, hogy folyamatosan hívogatnak.

**Comment by poma123** [comment]
Ezt múltkor beállítottam nem?

**Comment by Shryxx** [comment]
De, tényleg. Köszi!
