### ISSUE TITLE
Némítás dolgok.

### ISSUE THREAD

**Issue by Shryxx** [andris155/TheOld-Crafters#3723]
**Szerver**: Survival

Régebben nem lehetett táblára írni, ha némítva voltál. Ez nem kerülhetne vissza?

Ha némítva vagy elvileg nem lehet csatlakozni bújócskához.

**Comment by andris155** [comment]
A jelenlegi plugin nem tud ilyen funkciót sajnos, de ez nem hiba.

**Comment by Shryxx** [comment]
@andris155 Bocsi, de a bújócskás részt olvastad?

**Comment by andris155** [comment]
Nem tudunk mit kezdeni a bújócskás hibákkal. Csoda, hogy egyáltalán működik még az a plugin. Nem nagyon fejlesztik és sajnos zárt kódú.
