### ISSUE TITLE
Electric ore grinder

### ISSUE THREAD

**Issue by SurvivorTheReal** [andris155/TheOld-Crafters#3724]
Szerver:Survival

A guide szerint ha sódert teszek az electric ore grinderbe, akkor homokot csinál belőle.
Van egy bibi, csak flintet akar:
Akárhogy teszem bele csak filntet csinál belőle.
Lehet velem van a baj, és vmit nem tudok amit tudnom kéne.

**Comment by skrisz0101** [comment]
2 receptet ír a sóderre ore grinderben
Sóder - > homok 
Sóder - > kovakő

**Comment by poma123** [comment]
Explanation: Az alap Ore Crusherben van a sóder->homok és az alap Ore Grinderben a sóder -> kovakő. Az Electric Ore Grinder pedig mindkét alap gép receptjeit örökli, és a kovaköves van előbb a listában, ezért azt választja ki.

**Comment by skrisz0101** [comment]
@poma123 és ez így is marad?

**Comment by poma123** [comment]
@skrisz0101 muszáj hülyeséget kérdezni? (ne nevetőzze be ezt senki, köszi)

**Comment by andris155** [comment]
Jelentettem a fejlesztőnek. Majd eldöntik, hogy hogyan oldják meg. Egyelőre nem úgy tűnik, hogy mostanában oldanák meg.
