### ISSUE TITLE
Barátrendszer

### ISSUE THREAD

**Issue by Albinocska** [andris155/TheOld-Crafters#3725]
**Szerver**: survival, oldspace, savsziget
A barátrendszer egy olyan plugin, ami az összes szerveren működik. A lényege annyi, hogy ha valakit hozzáadsz barátnak(pl a /friend add {játékosnév} paranccsal), és ő elgfogadja (pl /friend accept {játékosnév}), akkor az összes szerveren átívelve tudtok msg-t küldeni egymásnak(pl /friend msg {játékosnév} üzenet) privát üzeneteket. Itt egy-két példa. Pl a haverod, józsi, ott játszik oldspace-n, te meg túlélőn, és akkor te túlélőröl józsinak az oldspace-re neki msg-t. 
Emellett azt is kiírja, ha a haverod-előbbi példából idézve józsi- feljön a szerverre, és így nem lesz annyira macerás az egyezkedés, hogy pl mikor tudtok felvenni már videót. Nincs az, hogy írsz neki dc-n, de nem elérhető, majd ő vissza ír, de most te nem vagy elérhető, hanem így egyszerűen ha feljön, akkor írsz neki egy-előbb bemutatott- msg-t, és akkor ha van neki is kedve/ideje, már készülhet is az a videó.
Meg még van egy menü is, ahol meg tudod nézni, kik vannak hozzáadva barátnak(pl /friend, /friend menü).

**Comment by Shryxx** [comment]
Eddig is volt globális /m, gondolom valami hiba van vele és most azért nincs. Azt pedig írja a chaten, ha valaki fellép valamelyik szerverre. Szerintem felesleges lenne /msg.

**Comment by skrisz0101** [comment]
Msg majd lesz szerók közt amúgy is, de sztem nem rossz ötlet
Akár lehetne erre építeni is valamit

**Comment by MrZero1** [comment]
Nekem is tetszik az ötlet.

**Comment by Albinocska** [comment]
Egy-két lehetőség még: pl rang vétel neked és egy barátodnak. Ez max 60 napig(mint az alap) tudna tartani. Csak 1 negyed résszel lenne olcsóbb, mint a sima rang 1 embernek(pl józsi akar venni magának, és barátjának, pistinek akar venni old rangot, és így ha pisti neki hozzá van adva barátjának, akkor józsinak 10160 ocd helyett csak 8890 ocd-be kerülne.)

**Comment by andris155** [comment]
A MineMarket-et a clans.hu fejleszti nem, mi. Így oda nem tudunk ilyeneket beállítani.

**Comment by Albinocska** [comment]
Egy-ket-tőt írtam előbb, szóval itt a második:
Barátok bajnoksága
Ez nem túl bonyolult. Egy barátoddal egy duo,coop bajnoság, és a nyertes csapat x összegű ocd-t kap fejenként.
Solve the puzzle
Ennek a minigamenek a lényege annyi, hogy mindenki kap egy random, coop puzzle-t, és amelyik csapat legelsőnek végez/ a legtovább jut bizonyos idő alatt(pl 2-3 perc), az a csapat.
Sajnos több nem jutott eszembe, de ti ki tudtok találni még többet is.

**Comment by poma123** [comment]
Ez a barátrendszer max arra lesz jó, hogy egymásnak üzenetet küldeni másik szerverre, megnézni ki online, hozzáadni, törölni barátot. OCD jutalom pedig főleg nem lesz. A minigamek-re ott a Survival szerver, + elég sok event is van.

**Comment by skrisz0101** [comment]
szerók közötti /m lesz amúgy is, nem?

**Comment by poma123** [comment]
> Msg majd lesz szerók közt amúgy is, de sztem nem rossz ötlet

Ki mondta, hogy lesz? A ChatControl-os privát üzenetnél volt csak szerverek között, az EssentialsX nem épül BungeeCord-ra.
Azért váltottunk EssX-es privát üzenetre, mert a CHC finoman fogalmazva elcseszte az egészet. Az EssX-es hátránya az, hogy ronda és nem megy bungee-n, de legalább működik.

**Comment by andris155** [comment]
A szerver 90%-nak jobban tetszik az EssentialsX megoldás. Leginkább ezért lett leváltva.

**Comment by MrZero1** [comment]
Ha másra nem is, a szerverek közötti üzenetküldésre és az online barátok megtekintésére már jó lenne ez a friendscucc

**Comment by poma123** [comment]
> A szerver 90%-nak jobban tetszik az EssentialsX megoldás. Leginkább ezért lett leváltva.

tök mindegy ki mit szeret, ha a másik el van cseszve.

**Comment by andris155** [comment]
A megoldáshoz kellene MySQL. Egyelőre nem sikerült megoldanom a Docker-be a driver-t. Hétvége felé még próbálkozok vele hátha megtudom oldani.

**Comment by andris155** [comment]
Nem tudtam sajnos megoldani a MySQL driver-t, hogy működjön.
