### ISSUE TITLE
Minemarket spawnerekhez ötlet

### ISSUE THREAD

**Issue by SurvivorTheReal** [andris155/TheOld-Crafters#3728]
Szerver: Survival
 
Minemarketen a spawnerek közé bekerülhetne a wither csontváz spawner, jó drágán, nagyon, nagyon drágán.
Csak egy ötlet, hátha.

**Comment by MrZero1** [comment]
Nem igazán szeretném, hogy ebből is farmokat építsenek

**Comment by andris155** [comment]
Én sem szeretném.
