### ISSUE TITLE
parancsok

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#3729]
**Szerver**: Survi

1. /heads search parancs letiltás eventvilágban.

2. Amúgy a ghelpop tök jó, nem lehetne mindenhol azt használni? esetleg a /helpop parancsnál is ezt használná? valami aliast berakni rá vagy nem tudom.

3. Savon, amíg nem jó a receptes könyv, nem lehetne egy parancsot beállítani, ami előhozza a recepteket? Pl. /receptek

**Comment by andris155** [comment]
1. kész
2. Szerintem bizonyos esetekben zavaró lehet, ha mondjuk van fent mindenhol külön staff tag.
3. kész
