### ISSUE TITLE
Ezüstmoly spawner AI hiba

### ISSUE THREAD

**Issue by VdszHun** [andris155/TheOld-Crafters#3730]
**Szerver**: Survival

Az ezüstmoly spawnerből idéződő ezüstmolyok nagyon gyorsan forgolódnak/rázkódnak.  Egy ideig vicces de utánna kezd rossz lenni a szemnek. :/

Van néhány ezüstmoly ami egész lassan rázkódok/forgolódik de vannak olyanok is amik villámgyorsak.

**Comment by poma123** [comment]
Szerintem ez nem hiba, ilyen a Minecraft.

**Comment by VdszHun** [comment]
Majd megnézem akkor ma egy egyszemélyes világban, ha tényleg akkor lezáróm ✓.

**Comment by VdszHun** [comment]
Ha magában idézem az ezüstmolyt AI nélkül nem rázkódik. (  Parancs mindjárt )

Ha spawnerrel igen. ( /setblock ~ ~ ~ minecraft:spawner{SpawnData:{id:silverfish,NoAI:1}} replace ).

Köszönöm Poma! Ezt a hibát Mojang fele kéne jelenteni, én nem eredetis vagyok így nem nagyon tudom megtenni.

**Comment by andris155** [comment]
Semmi köze nincs az eredetinek a Mojang hibajelentő oldalán. Nyugodtan jelentsd nekik.

**Comment by andris155** [comment]
https://bugs.mojang.com/
