### ISSUE TITLE
Slimefun hiba

### ISSUE THREAD

**Issue by BlackSuit25** [andris155/TheOld-Crafters#3731]
**Szerver**:
Survival szerveren észleltem a hibát. 

A hiba az, hogy ha enchant könyvel próbálunk bármilyen slimefunos tárgyat enchantolni könyvel akkor az XP szintünket levonja az üllő, de nem kapjuk meg a kívánt enchantot az itemre

**Comment by poma123** [comment]
Ez sajnos ilyen. A spigot nem hozott létre megfelelő API-t ehhez, úgyhogy üllőben nem érdemes enchantolni SF-es tárgyakat. Erre ott van az Auto-Enchanter.

**Comment by andris155** [comment]
Már e-mailben is írták ezt a hibát. A fejelsztőnek már jelentettem korábban. Poma leírta azt, amit írt.
