### ISSUE TITLE
Carbonado furnace hiba

### ISSUE THREAD

**Issue by BlackSuit25** [andris155/TheOld-Crafters#3732]
**Szerver**:
Survival szerveren észleltem ezt a hibát

A carbonadó furnacebe nem lehet manuálisan betenni ércet és tüzelőanyagot sem és kivenni sem, mert a furnace kiütődik

**Comment by andris155** [comment]
Nem sikerült reprodukálni. Ha tényleg rossz volt talán az mcMMO egyik verziója okozta talán.
