### ISSUE TITLE
SF gold=>normal gold

### ISSUE THREAD

**Issue by lovi-dev** [andris155/TheOld-Crafters#3733]
Survival szerveren, de gondolom savon is...

9 darab 4 karátos SF-es gold ignotból "sima" goldblokkot lehet craftonli, majd szétszedni 9 "sima" gold ignotra.
Így az SF-es gold 1:1 váltható "sima" goldra.

Lovi_

**Comment by mnbTOC** [comment]
Tudomásom szerint direkt így van megcsinálva mivel gold dustból nacerás megcsinálni hogy karát nélküli aranyat is lehessem csinálni.

**Comment by andris155** [comment]
Ez nem hiba.
