### ISSUE TITLE
Lucky block + cargo manager

### ISSUE THREAD

**Issue by ketezerhat** [andris155/TheOld-Crafters#3735]
**Szerver**: Survival

Ha egy cargo manager ható körébe leraksz egy lucky blockot akkor az kapcsolódik hozzá, felveszi a kék effektet ami elég idegesítő.

**Comment by andris155** [comment]
Gyakorlatilag a sima fejjel is ez történik. Jelentettem a fejlesztőnek.

**Comment by andris155** [comment]
330 OCD
