### ISSUE TITLE
Ancient altar

### ISSUE THREAD

**Issue by ketezerhat** [andris155/TheOld-Crafters#3736]
**Szerver**: Survival

Ha egy levédett területen beleraksz valamit az ancient altarba azt bárki kiveheti hozzáférés nélkül... rgo ha pl csinálni szeretnél egy soulbound rúnát de valaki figyeltéged, vár akkor eltudja gyorsan lopni az alapanyagokat az ancient altarból..

**Comment by andris155** [comment]
Pár nap múlva már védett lesz, amikor frissül a plugin.

**Comment by andris155** [comment]
508 OCD
