### ISSUE TITLE
God mode

### ISSUE THREAD

**Issue by ketezerhat** [andris155/TheOld-Crafters#3737]
**Szerver**: Survival

Megkéne azt csinálni, hogy ha kilépsz a szerverről godmódban akkor maradj is úgy amikor vissza jelentkezel mert elég kellemetlen szituációkat szülhet... pl kidob a szerver miközben úszol godban egy láva tenger közepén stb..

**Comment by poma123** [comment]
Azért tiltja le belépéskor, mert lehet hogy akkor már lejár a rang, és akkor inkább legyen letiltva.
@andris155 van rá lehetőség, hogy csak akkor tiltsa le, ha már nincs joga /god-ra a játékosnak?

**Comment by andris155** [comment]
Szerintem nincs. De majd megnézem.

**Comment by andris155** [comment]
Alapból letiltja elvileg, ha nincs hozzá joga. Ez is valamelyik verzió újítása volt, csak aztán el is felejtettem átállítani.

**Comment by andris155** [comment]
Most már nem kapcsolja ki kilépésnél az isten módot.

**Comment by andris155** [comment]
508 OCD
