### ISSUE TITLE
Kvíz event

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#3738]
**Szerver**: Szurvi
Kvízen kicsit kevés a hely, pláne ha 20 ember játszik xd
Nem lehetne egy nagyobb kvízt kiépíteni? (akár cmd-vel)

**Comment by andris155** [comment]
Szerintem azért annyira nem gyakori, hogy 20 ember játszana egyszerre.

**Comment by skrisz0101** [comment]
De, az

**Comment by DiaGamer321** [comment]
Persze nekem nem lehet szolni sk... Akk már 11 lenne.😎

**Comment by maryhonaly** [comment]
Megpróbálok egy több férőhelyes verziót csinálni, aztán meglátjuk. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by poma123** [comment]
> Sent with [GitHawk](http://githawk.com)

amúgy már van hivatalos Github for Mobile :D

**Comment by poma123** [comment]
Kész
