### ISSUE TITLE
Fluid pump

### ISSUE THREAD

**Issue by mnb124** [andris155/TheOld-Crafters#3739]
Survivalon de szerintem savon is

Mikor kiütöttem a fluid pumpot miközben benne volt a vödör nem dobta ki a vödröket.

**Comment by andris155** [comment]
Valamikor a jövőben remélhetőleg lesz rá megoldás. Addig viszont mindig ki kell szedni a Fluid pump-ból a vödröket mielőtt kiütöd.

**Comment by andris155** [comment]
330 OCD
