### ISSUE TITLE
skyblock küldetés

### ISSUE THREAD

**Issue by NBabi** [andris155/TheOld-Crafters#374]
a "Builders Challenges" küldetések között a Lumberjack küldetés 2 farkas tojást adott, de a küldetés leírásában csak 1 szerepel jutalomként.

**Comment by NBabi** [comment]
ugyan úgy 2 tojást adtak a következő küldetések: Torch Maker ,Tool Maker, Carpenter, Stone Brick Maker.

**Comment by NBabi** [comment]
Ketten vagyunk a szigeten, lehet ezért ad kettőt? Viszont a többi küldetésjutalomból csak a megadott mennyiséget adja, csak a spawn eggből ad duplát

**Comment by andris155** [comment]
Szerintem ezzel nem tudunk mit csinálni. :(
