### ISSUE TITLE
/sf openguide engedélyezése

### ISSUE THREAD

**Issue by mnbTOC** [andris155/TheOld-Crafters#3740]
Survivalon (szerintem savon is) lehetne a normál játékosoknak engedélyezni a /sf openguide (ugy emlékszem igy van a parancs) annyit csinál csak hogy megnyitja a könyvet.

**Comment by MrZero1** [comment]
Ez akár még hasznos is lehet, legalább nem lenne tele könyvekkel a szerver :D Habár a könyvlehívó is fontos
