### ISSUE TITLE
2 kicsi elírás a Slimefun könyvben

### ISSUE THREAD

**Issue by VdszHun** [andris155/TheOld-Crafters#3741]
**Szerver**: Survival de szerintem Savsziget is.

A Slimefun könyvben a **Nether Ice Coolant Cell** receptje csak azt jelzi, hogy 4db-t kapsz a **Heated Pressure Chamber**ből de valójában 8-at ad.

Az **Enriched Nether Ice**-ból a könyv 1-et jelez a receptnél de a **Heated Pressure Chamber** 4-et ad.

**Comment by andris155** [comment]
Pár nap múlva már jól fogja írni, amikor frissül a plugin. 508 OCD.
