### ISSUE TITLE
Dragon pet

### ISSUE THREAD

**Issue by mnb124** [andris155/TheOld-Crafters#3742]
Szerintem le lehetne tiltani a dragon petet ha még nincs.

Lehet vele lőlni azt a lila izét amivel nagyon könnyen lehet trollkodni..

**Comment by andris155** [comment]
Hotbarpets?

**Comment by mnbTOC** [comment]
> Hotbarpets?

Igen.

**Comment by MrZero1** [comment]
Hogy lehet vele trollkodni? Az effekten kívül mást nem csinál, nem sebez

**Comment by andris155** [comment]
Szerintem ez annyira nem trollkodás.
