### ISSUE TITLE
OldSpace Varázslók a földön.

### ISSUE THREAD

**Issue by DiaGamer321** [andris155/TheOld-Crafters#3743]
Az OldSpace szerveren az Föld bolygón hatalmas szerepet játszanak a varázslók. Főleg a varázspálca az, amire szüksége van a playernek kulcsok készítéséhez. De az a sajnálatos baj, hogy a varázslók nagyon ritkán spawnolnak, és nem mindig dobnak pálcát. A pálca kulcshoz kell, ami ahoz kell, hogy mészkövet szerezzünk, azokból dinoszaurusz szem szerzése, és végül mágikus szem elkészítéséhez kell. És  a mágikus szemből 1 stack garantált, hogy kell ahoz, hogy minden küldetést teljesíteni lehessen. Ezért ajánlom, hogy a varázslók spawnolása számát megnöveljék, vagy esetleg varázspálcák beszerzésének alternatívájának bevezetése. (Mint pl: Craft hozzá, kastély ládájába kapható lehessen)

Az oka, hogy megírtam ezt a levelet, az hogy 4-5 napja le vagyok akadva a küldetésekkel, hisz minden mást megcsináltam, csak azok maradtak, amikhez mágikus szem kell, de ahoz pedig varázsló kell. Remélem ez a "hiba" javítva lesz.

Írta:DiamondGamer321

**Comment by poma123** [comment]
Most már több fog spawnolni.
