### ISSUE TITLE
Sok kacat OldSpace-n

### ISSUE THREAD

**Issue by DiaGamer321** [andris155/TheOld-Crafters#3744]
Egy mobfarm elég jól jön minden túlélő szerveren. Sok külömböző mob lootját lehet bezsebelni. De az OldSpace szerveren a Holt Hadvezér képes 10 perc alatt megtömni a ládámat, a szetjével meg nyergével. Ajánlani tudom, a nyereg lootot eltüntetése, és a zafírszet droprateját nagyon lecsökkenteni. (Csak kulcs készítéséhez kell, nem nagy cucc)

**Comment by poma123** [comment]
Lejjebb vettem a szett dobási esélyt.
