### ISSUE TITLE
Savsziget event hiba

### ISSUE THREAD

**Issue by szofogado** [andris155/TheOld-Crafters#3745]
A savsziget-en az automatikus eventeknél az első nyertes mindig megkapja a jutalmát és jobb oldalt is látni lehet a nevét, de ha második vagy és második helyre álsz be akkor csak pénzt kapsz és nem frissül le. Le teszteltem és ha második-ként a harmadik helyre álsz be akkor át teleportál a második helyre és jobb oldalt is ott lesz a neved. Ilyenkor ugyan úgy fent áll ez a hiba csak a harmadik helyezettel. 

Válaszukat előre is köszönöm!

(elnézést, ha valamit értetlenül írtam le. Kicsit fáradt vagyok még.)

**Comment by poma123** [comment]
nem vagyok otthon most, de @andris155 ha ezt látod tedd fel savra a survivalon lévő eventrendszert és megoldódik ez

**Comment by andris155** [comment]
A 2 jar elvileg ugyanaz. Szerintem nem fogja megoldani.

**Comment by poma123** [comment]
akkor ennek semmi értelme :)

**Comment by andris155** [comment]
Sok dolognak nincs értelme. :)

**Comment by andris155** [comment]
Akkor erre nincs megoldás? :/

**Comment by poma123** [comment]
Ez a hiba nem létezik.
