### ISSUE TITLE
Hiányos az Egyedi Falusi bolt létrehozó leírása (MineMarket)

### ISSUE THREAD

**Issue by VdszHun** [andris155/TheOld-Crafters#3746]
Survival és Savsziget oldalon (Tágyak rész) nincs tutorial az Egyedi Falusi bolt létrehozásnál.

Fotók róla: (PC)
![Missing_tutorial_Vdsz](https://user-images.githubusercontent.com/68443484/89101366-82a20980-d3ff-11ea-903d-9693cfe638d6.png)
(Mobil)
![Missing_tutorial_mobile_Vdsz](https://user-images.githubusercontent.com/68443484/89101375-93527f80-d3ff-11ea-8423-d2574cdec11e.png)

**Comment by andris155** [comment]
Javítva.
https://www.youtube.com/watch?v=MRl6n4ZR32E

**Comment by andris155** [comment]
330 OCD
