### ISSUE TITLE
Ancient Pedestal és villámcsapások

### ISSUE THREAD

**Issue by VdszHun** [andris155/TheOld-Crafters#3747]
**Szerver**: Survival
Ha egy villám csap **Ancient Pedestal**-ba tett dologra a dolog megsemmisül. ( **Elemental Staff - Storm**-al teszteltem).

**Comment by andris155** [comment]
Mivel sima tárgyakról van szó persze, hogy megsemmisül. Szerintem erre senki se fogja használni az Elemental Staff - Storm-ot. Annak pedig nagyon kicsi az esélye, hogy pont oda csap le a villám.
