### ISSUE TITLE
Elemental Staff - Storm és levédések

### ISSUE THREAD

**Issue by VdszHun** [andris155/TheOld-Crafters#3748]
**Szerver**: Survival

A levédésekben lévő játékosokat és mobokat meg lehet sebezni/ölni az **Elemental Staff - Storm**-al.

Hamarosan kipróbálom a Telkeken is.

**Comment by andris155** [comment]
Tudok a hibáról, már jelentve lett a fejlesztőnek is. A telkeken nincs ilyen gond.

**Comment by VdszHun** [comment]
Szerencse :D, pont nincs fennt ismerősöm akivel tesztelni tudtam volna.

Lezárjam akkor a hibát?

**Comment by andris155** [comment]
Lezárhatod. Szerintem sajnos megoldás nem mostanában lesz erre.
