### ISSUE TITLE
Skyblock nether

### ISSUE THREAD

**Issue by NBabi** [andris155/TheOld-Crafters#375]
Amikor átmegyek a nether portálon, kidob egy helyre, a portál a netherrack alatt van, 1 szintet tudok bontani, a fölötte lévőre azt írja: " Hey! Sorry, but you can't break that block here.", Lefele pedig csak láva van és bedrock.
![2017-01-02_02 34 05](https://cloud.githubusercontent.com/assets/22939109/21583890/f872f1f6-d093-11e6-9d18-84f592a2b80e.png)

**Comment by NBabi** [comment]
![2017-01-02_02 38 59](https://cloud.githubusercontent.com/assets/22939109/21583912/9ec5b426-d094-11e6-893d-d721c11ff292.png)

**Comment by andris155** [comment]
javítva
