### ISSUE TITLE
Nem müködik a /csn clear

### ISSUE THREAD

**Issue by mnb124** [andris155/TheOld-Crafters#3750]
Ahogy a cím is röviden leírja. Nem megy a /csn clear... Ugyanúgy írja hogy 2500 eladásom volt.

https://youtu.be/uJZqQNaMSqA

**Comment by andris155** [comment]
Nem sikerült reprodukálnom a hibát. Most sem jó?

**Comment by mnb124** [comment]
Már müködik.
