### ISSUE TITLE
Ah

### ISSUE THREAD

**Issue by ketezerhat** [andris155/TheOld-Crafters#3752]
**Szerver**: Survival

Igazán jó lenne ha azt meglehetne csinálni, hogy egy ember csak 5 ugyan olyan tárgyat tudjon feltölteni ah-ra rangtól FÜGGETLENÜL mert nem egy 1-2 ember oldalnyi cuccait szeretném látni... Így se veszi meg senki elég lenne egy fajta tárgyból csak 5 vagy kevesebb...

**Comment by andris155** [comment]
Nem lesz megcsinálva ez.
