### ISSUE TITLE
Vote

### ISSUE THREAD

**Issue by ketezerhat** [andris155/TheOld-Crafters#3753]
**Szerver**: Survival

A vote-t ugye egyesével megköszöni a szerver... Na ezt kilehetne "javítani", hogy 1 nap csak egyszer köszönje meg. Ezzel is elkerülve a chat spamelést.

**Comment by andris155** [comment]
Sajnos nem lehet máshogy megoldani. A /vote ToggleBroadcast lehet kitudod kapcsolni.
