### ISSUE TITLE
Ice bow/"boom bow"

### ISSUE THREAD

**Issue by ketezerhat** [andris155/TheOld-Crafters#3755]
**Szerver**: Survival

Ugye levédésen belül nem lehet harcolni csak ha engedélyezve van. Na de ice és boom bowwal lehet trollkodni.. ugye ice bowwal gyakorlatilag ellehetetleníteni a játékost hisz ha spameled nem tud mozogni hiába levédésen belül van. Boom bow még roszabb mivel ott a fall damagéval még meg is lehet ölni az embereket.

**Comment by VdszHun** [comment]
Az Explosive bow nem le lett tiltva már trollkodás miatt?

**Comment by Shryxx** [comment]
Az explosive bowot már jelentettem, mert sokan trollkodtak vele. Az elvileg le lett tiltva.

**Comment by VdszHun** [comment]
Akkor jól emlékeztem, köszönöm Shryxx :)

**Comment by andris155** [comment]
Letiltottam az Icy Bow-ot is.

**Comment by andris155** [comment]
330 OCD
