### ISSUE TITLE
Területről való kitíltás

### ISSUE THREAD

**Issue by ketezerhat** [andris155/TheOld-Crafters#3756]
**Szerver**: Survival

Meglehetne oldani, hogy a levédett területről kilehessen tiltani bizonyos embereket ezzel is elkerülve a trollkodásokat icy és boom bowwal.

**Comment by andris155** [comment]
Sajnos ezt nem tudjuk megoldani. Ne mond el másiknak, hogy hol laksz a játékban.

**Comment by Shryxx** [comment]
Amúgy ha szólsz staffoknak, hogy xy zavar, akkor általában elrakják spawnra.
