### ISSUE TITLE
Nagyobb pwarpok

### ISSUE THREAD

**Issue by ketezerhat** [andris155/TheOld-Crafters#3759]
**Szerver**: Survival

Nagyon jó lenne ha lenne egy warp vagy valami ami leírja azt a pár nagyobb pwarpot ahol lehet pl. mobokat farmolni. (gondolok ezekre pl: schmekkels, skrisz01, plaster)

**Comment by andris155** [comment]
Mivel folyamatosan változnak nem lesznek kiírva.
