### ISSUE TITLE
PE szerverek chat

### ISSUE THREAD

**Issue by Mayer005** [andris155/TheOld-Crafters#376]
Hogyha a PE szervereken á betűt írunk és mellé egy betűt akkor a két betű összeolvad

**Comment by DlamondBarna03** [comment]
1. Az enchat nem jó 
2. A teleport néha nem muködik (el tp de nem mutatja hogy ott vagyunk ahova teleportaltunk)

**Comment by andris155** [comment]
Az á betűs kliens hiba.

**Comment by andris155** [comment]
A másik 2 hiba javítva
