### ISSUE TITLE
Lucky block mobok.

### ISSUE THREAD

**Issue by ketezerhat** [andris155/TheOld-Crafters#3761]
**Szerver**: Survival

Nagyon idegesítőek a mobok a lucky blockokban.. halak nem spawnolnak a óceánokban de a lucky block rám rak 10 kutyát egy kinyitása után. Ezt kilehetne szedni. Illetve minden lucky blockos mobot mert csak mindenkit hátráltatnak.

**Comment by andris155** [comment]
A Lucky Block ad olyat is, ami idegesítő. Nem lesz megoldva, hogy csak a jó dolgokat adja.
