### ISSUE TITLE
Elytra event

### ISSUE THREAD

**Issue by Zsombec** [andris155/TheOld-Crafters#3762]
**### Szerver:Survival
Elytra Event:**
Mindenki kapna egy elytrát a eventig/maguknak kellene hozniuk
Miről is szólna az event?Az elytrával lehetséges bunnyhoppolni, ezáltal különféle magasságokra felugrani,ez futási blocktól felmérően vonatkoztatható meg. A játékosoknak kellene felugrálni X magasságra, onnan pedig egy "dropper" szerűségbe kerülnének,annyi kitétellel,hogy nem lefelé zuhannának folyamatosan, hanem függőlegesen esnének, és ki kéne kerülniük a különböző akadályokat,amint ezzel megvannak, lehetne egy kisebb parkour,mely elvezet a helyezési pontokhoz.

**Comment by andris155** [comment]
@MrZero1 ?

**Comment by MrZero1** [comment]
Ez valami minigameféleség, nem tudom mennyire kivitelezhető ez plugin nélkül.

**Comment by Zsombec** [comment]
Amennyiben van rá igény,esetleg még meg is épithetném :D @MrZero1

**Comment by MrZero1** [comment]
A megépítés mellett a kivitelezés ami talán fontosabb. 
Úgy tudom elképzelni, mint Hypixelen az Arcade minigame-ben a karikákon átrepülős játékot. @poma123  esetleg?

**Comment by Zsombec** [comment]
Erre van egy jobb ötletem,hogy nem feltétlen a karikákon kellene repülni,hanem egy "barlang" részben,ahol kellene manőverezni, van erre egy hasonló map design,amire gondolok , csatolom is a videóanyagot:https://www.youtube.com/watch?v=dnTkUBvnIW4&t=383s            , csak annyival lenne megspékelve a dolog,hogy nem csak kanyarodni kellene,hanem különféle akadályokat kikerülni. @MrZero1

**Comment by andris155** [comment]
Ez elég menő, de szerintem az a világ 256 blokknál magasabb.

**Comment by Zsombec** [comment]
Igen,magasabb azért mondom hogy ez csak egy design. Másképp meglehetne oldani az egészet,csak megszerettem volna osztanim,hogy egyátalán milyen ötletre is gondolok.

**Comment by poma123** [comment]
Ehhez szerintem nem kell plugin.

**Comment by MrZero1** [comment]
Gondolkozom rajta, jó ötlet amúgy

**Comment by MrZero1** [comment]
Plugint én sem szeretnék erre

**Comment by MrZero1** [comment]
Nekem ilyenre nincs felesleges időm, energiám, ötletládába írd meg, aztán egyszer vagy lesz, vagy nem. Vagy ha valakinek lesz rá ötlete, újranyitja ezt.
