### ISSUE TITLE
Fall damage bugg

### ISSUE THREAD

**Issue by Zsombec** [andris155/TheOld-Crafters#3763]
Survival:

Amennyiben van van magasugrás II effekt rajtunk, és Multi Toolal,teljes mértékbe elkezdünk a föld felé irányulni,semmilyen sebződést nem fogunk kapni,akkor se még ha nem is lefelé irányitjuk a Multi Toolt akkor sem fogunk kapni sebződést.

Videóanyag: https://www.youtube.com/watch?v=0zh6wvd2lew&feature=youtu.be

**Comment by andris155** [comment]
Nem sikerült reprodukálnom ezt.
