### ISSUE TITLE
Fortuna Kulcs

### ISSUE THREAD

**Issue by Zsombec** [andris155/TheOld-Crafters#3764]
Amennyiben kidob/ kilépsz a szerverről,mielőtt kinyitottad volna a kulcsodat,majd visszalépsz, a tüzijáték effekt ott lesz,ahogy kinyitottuk,azonban semmiféle jutalmat nem ad ki a láda ebben a formában.

**Comment by andris155** [comment]
Erre talán az lenne a megoldás, ha lecserélnénk az egész plugint. Bár ha éppen megy a nyitási animáció és közben kilépsz szerintem más plugin se kezd semmit. Később ha lesz időm fogok nézegetni alternatívát. De addig sajnos erre nincs megoldás.

**Comment by poma123** [comment]
Nem kell más plugin, az egyik megoldás az, hogy ne lépjen ki az illető amíg tölt a nyitás, a másik pedig egy azonnali megszakítás a pluginban ha kilép valaki. Majd ránézek.

**Comment by andris155** [comment]
Szerintem annak sincs sok értelme, hogy így-úgy kell javítgatnod folyamatosan ezt a már nem támogatott plugint. Jó lenne a más plugin, csak be kellene újra állítani ami sok idő.
