### ISSUE TITLE
Slimefun mennyiség elirás

### ISSUE THREAD

**Issue by mnb124** [andris155/TheOld-Crafters#3766]
A slimefun guide szerint ha egy olajat heated pressure chamberben müanyaggá nyomunk akkor 1 plastic sheetet kapunk miközben a valoságban 8 sheetet kapunk 1 olajból.

**Comment by andris155** [comment]
Szerintem vannak benne még ilyen elírások. Végig kellene nézni az egészet.

**Comment by mnb124** [comment]
Azt csinálom. Kell az ocd 🤣

**Comment by andris155** [comment]
Amit írtál azt viszont én nem találom. Nálam jól írja.
<img width="260" alt="Annotation 2020-08-02 162556" src="https://user-images.githubusercontent.com/8324198/89125187-e4847100-d4dc-11ea-9383-dec50410f7ae.png">

**Comment by mnb124** [comment]
De 8-at ad andris nem 1-et

**Comment by andris155** [comment]
Ha frissül a szerveren már jól fogja írni.

**Comment by andris155** [comment]
330 OCD
