### ISSUE TITLE
Érdekes "ancient altaros" bug.

### ISSUE THREAD

**Issue by ketezerhat** [andris155/TheOld-Crafters#3767]
**Szerver**: Survival

A lényeg, hogy ha az ancient pedestal-ra teszel bármit pl egy cobblestonet és arra rá "dobsz" egy anvilt akkor kibugol az item és megjelenik ilyen eltünthetetlen cucc formájában és ráadásul elveszik az alapanyag. Tudom hogy nem "nagy" bug de bug

**Comment by poma123** [comment]
Így van, horgászbottal is ki lehet szedni, illetve ha akármilyen blokk kerül az item helyére ami ki tudja tolni.

**Comment by andris155** [comment]
Ha szándékosan nem akarod kibugoltatni a tárgyakat róla szerintem ez nem fordul elő. Lehetne biztosan erre is ellenőrzést rakni, ami megoldaná. De én feleslegesnek látom.
