### ISSUE TITLE
Multi tool

### ISSUE THREAD

**Issue by mnb124** [andris155/TheOld-Crafters#3768]
Ha a multitoolal probálunk kitörni blokkokat kilehet és ugyanúgy müködik mint egy rendes olló csak se nem kopik se nem fogy az áram belőle.

https://youtu.be/CRR9tZDqC_c

**Comment by andris155** [comment]
Ha frissül majd a Slimefun ez javításra kerül.

**Comment by andris155** [comment]
330 OCD
