### ISSUE TITLE
PE szerverek enderpearl

### ISSUE THREAD

**Issue by Mayer005** [andris155/TheOld-Crafters#377]
A PE szervereken a kreatív inventory-ban van ender pearl és ez átmegy a láthatatlan blockon így könnyen kiszöknek eventről stb.. de csak a rangosok még (Elit-től felfelé)

**Comment by andris155** [comment]
Nem használható elvileg kreatívban már

**Comment by andris155** [comment]
Adtam OCD-t mivel PE-n még nincs OldDiamond
