### ISSUE TITLE
Leülés lépcső blokkokra

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#3770]
**Szerver**: Mindenhol is
jó lenne, ha le lehetne ülni a lépcsőkre, mint régen. (event világban lehetne tiltani)

**Comment by andris155** [comment]
Nem lesz tőle jobb a játékélmény. Ez inkább csak ilyen kozmetikai dolog. Szerintem felesleges. Voltak ebből is komolyabb hibák is régen, mert azt hiszem packet-et használ hozzá.

**Comment by skrisz0101** [comment]
@poma123 segíts :(

**Comment by poma123** [comment]
Nem kell packet hozzá. A régi craftbook-os megoldás nem jó, másmilyen kell. 
Pl.: Saját plugin, ami egy nyilat lő ki, és arra ülteti rá a titsztelt játékost.

**Comment by andris155** [comment]
Felesleges szerintem. Inkább a játékélményt fejlesszük ne az ilyen kozmetikai dolgokat.

**Comment by andris155** [comment]
Bekerülhetne az az új Slimefun addon az tényleg hasznos.

**Comment by poma123** [comment]
Végül bekerült. #3798
