### ISSUE TITLE
Slimefun - EcoPower addon

### ISSUE THREAD

**Issue by poma123** [andris155/TheOld-Crafters#3771]
**Szerver**: Survival, Savsziget

Az [EcoPower](https://github.com/TheBusyBiscuit/EcoPower/) egy új menő kis addon, ami a megújuló energiaforrásokat célozza meg. Tartalmaz víz- és szélturbinákat, jobb napelemeket, stb. Röviden tömören ennyi. Én magam is részt vettem a fejlesztésében.

**Comment by andris155** [comment]
Bekerülhet részemről.

**Comment by MrZero1** [comment]
Ez még jól is hangzik.

**Comment by poma123** [comment]
Holnap betölt.
