### ISSUE TITLE
Eventek

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#3772]
**Szerver**: Szurvi, sav
Kb minden mostani napi event régen manuális event volt. (szóval van indítója, kar, végén ,,dobogó")
Semmi különösebb dolgot nem kéne tenni, csak ugyanúgy meghirdetni a napi eventeket és lehetne
azt is ugyanúgy nyomni mint a manuálist, hisz régen manuális volt. annyi változás történt, hogy a végén lett téve egy láda +nyitva mindig az ajtó

Tényleg elég monoton ha valaki csak a meghirdetett eventekre jár (sokan vannak így)

**Comment by MrZero1** [comment]
Régen meg alig mentek eventekre az emberek, ezért is lettek átrakva. Ami meg visszakerült, vagy új event lett (pl parkour) az meg most sem megy nagyon.

**Comment by MrZero1** [comment]
Inkább új eventek kellenek, mintsem a régi 2-4 perces eventek

**Comment by embervagyok2** [comment]
![image](https://user-images.githubusercontent.com/69633425/90135196-97bd5780-dd72-11ea-94c5-36c2cb306024.png)
ciganykurvak anyatok roman szorostalpu fasszopo fereg patkany gecik tetves fasszopo @Shryxx anyadat basszam teherbe ukran vendegmunkas @andris155 @MrZero1 @poma123 @skrisz0101

**Comment by embervagyok2** [comment]
![image](https://user-images.githubusercontent.com/69633425/90135196-97bd5780-dd72-11ea-94c5-36c2cb306024.png)
ciganykurvak anyatok roman szorostalpu fasszopo fereg patkany gecik tetves fasszopo @Shryxx anyadat basszam teherbe ukran vendegmunkas @andris155 @MrZero1 @poma123 @skrisz0101 ![image](https://user-images.githubusercontent.com/69633425/90135196-97bd5780-dd72-11ea-94c5-36c2cb306024.png)
ciganykurvak anyatok roman szorostalpu fasszopo fereg patkany gecik tetves fasszopo @Shryxx anyadat basszam teherbe ukran vendegmunkas @andris155 @MrZero1 @poma123 @skrisz0101 ![image](https://user-images.githubusercontent.com/69633425/90135196-97bd5780-dd72-11ea-94c5-36c2cb306024.png)
ciganykurvak anyatok roman szorostalpu fasszopo fereg patkany gecik tetves fasszopo @Shryxx anyadat basszam teherbe ukran vendegmunkas @andris155 @MrZero1 @poma123 @skrisz0101 ![image](https://user-images.githubusercontent.com/69633425/90135196-97bd5780-dd72-11ea-94c5-36c2cb306024.png)
ciganykurvak anyatok roman szorostalpu fasszopo fereg patkany gecik tetves fasszopo @Shryxx anyadat basszam teherbe ukran vendegmunkas @andris155 @MrZero1 @poma123 @skrisz0101 ![image](https://user-images.githubusercontent.com/69633425/90135196-97bd5780-dd72-11ea-94c5-36c2cb306024.png)
ciganykurvak anyatok roman szorostalpu fasszopo fereg patkany gecik tetves fasszopo @Shryxx anyadat basszam teherbe ukran vendegmunkas @andris155 @MrZero1 @poma123 @skrisz0101
