### ISSUE TITLE
Magmakockák OldSpace-n

### ISSUE THREAD

**Issue by DiaGamer321** [andris155/TheOld-Crafters#3773]
Habár elösször a witch-ekről panaszkodtam, most pedig a Magmakockák spawnolásárol beszélnék. A magmakockák a netherbe nehezen spawnolnak. Ahoz, hogy 1 idéző asztalt meglehessen csinálni, ahoz több mint 50 db magmakrém kell. 20 perc alatt csak egy spawnolt, és az se dobott magmakrémet. 

Javasolni tudom, a következőket:
-A magmakrémek spawnolását megnövelni.
-A magmakrém állandó loot legyen.
-A csillagközi magmakrémet ki lehessen üstbe égetni, és magmakrémet kapnánk cserébe.
-Valamely Földi mob dobhatna Slimeball-t. (Pl: A Witch, Silverfish kis esélyel, hisz van spawnere, de semmit se dob.)

**Comment by poma123** [comment]
Javítva, most már spawnolnak Csillagközi magmák.

**Comment by poma123** [comment]
+ Mostantól több loot-ot dob, és mindig dob sima magmakrémet is.
