### ISSUE TITLE
Slime boots

### ISSUE THREAD

**Issue by ketezerhat** [andris155/TheOld-Crafters#3774]
**Szerver**: Survival

Ha slimeboots-ban vagy és egy shulker meglő akkor bugos, nem tudsz ugrani, vissza dobál. És nem nem az effekt miatt. God módban meglő és nem tudok ugrani slimebootsal mert vissza dobál.

**Comment by andris155** [comment]
Hogy tudnál ugrálni a levegőben, amikor a shulkeres lövéstől elkezdesz felfele szállni?

**Comment by andris155** [comment]
Nem sikerült reprodukálni. Lebegés közben a levegőben nem lehet ugrálni.

**Comment by andris155** [comment]
Nem sikerült reprodukálni.
