### ISSUE TITLE
Kezdés plugin nem létező warp

### ISSUE THREAD

**Issue by andris155** [andris155/TheOld-Crafters#3775]
**Szerver**: túlélő

A túlélő szerveren elvileg a kezdés plugin forráskódjában van az eventek warp, ami már nem létezik.

**Comment by poma123** [comment]
javítva

**Comment by MrZero1** [comment]
Pedig elvileg kellene lennie neki warpnak 😃

**Comment by andris155** [comment]
Pedig nincs. xd

**Comment by poma123** [comment]
Nincs neki warp, egyikünk se nyúlt hozzá.

**Comment by MrZero1** [comment]
Visszaraktam a warpot, a kezdésbe nem muszáj visszarakni
