### ISSUE TITLE
Cheat védelem hiba

### ISSUE THREAD

**Issue by Conaniwnl** [andris155/TheOld-Crafters#3776]
**Szerver**: Savsziget

Az Anti Cheat bejelez ha szertnél kiütni Karmzsin Niliumo-t vagy Torz Niliumot, és nem engedi kiütni, hanem visszateszi egyből. Egyedül csákánnyal lehet, minden más toolt bejelez (speed mine), és nem engedi kiszedni. 

Ez az a block: 
![2020-08-03_13 16 45](https://user-images.githubusercontent.com/40923017/89187052-fb8a9800-d59c-11ea-90ab-e720fb3e0559.png)

**Comment by andris155** [comment]
Sikerült reprodukálnom a hibát. Ez eddig nem értem hogy nem tűnt fel senkinek.

**Comment by Conaniwnl** [comment]
Több új 1.16 -os blockkal is ezt csinálja (netheres új fák, és deszkák). Gondolom akkor minden új blocknál és nem csak amit elsőre írtam.

**Comment by andris155** [comment]
Kellene egy pontos lista a blokkok listájáról.

**Comment by Conaniwnl** [comment]
Hát ebben egy admin vagy moderátor tud segíteni, kreatív nélkül elég nehéz összeszedni. De majd megprobálom holnap megoldani.

**Comment by Conaniwnl** [comment]
Most, hogy véginéztem az összess blockot mégis csak az a kettő ami nem jó (ez miatt bocsánat). Valószínű amikor a deszkákat nem tudtam kiütni lagolhattam, vagy valami környezeti változó miatt nem tudtam, de ma sikerült, ezt a kettőt kivéve:

`Warped Nylium - minecraft:warped_nylium
Crimson Nylium - minecraft:crimson_nylium`

**Comment by andris155** [comment]
Ezekről már tud a fejlesztő. Elvileg a wiki-n hibás értékek voltak és úgy keletkezett ez a hiba. A következő frissítésben javítja majd.

**Comment by andris155** [comment]
Elvileg javításra került.
