### ISSUE TITLE
CratePlus item data (damage) elavult tárgy tárolás javítása

### ISSUE THREAD

**Issue by andris155** [andris155/TheOld-Crafters#3777]
**Szerver**: túlélő, savsziget

A ShulkerBoxoknál, Spawn egg-eknél, Enchanted golden apple-nél, fejeknél a CratePlus elavult módon menti le a tárgyakat. Ezek a tárgyak kapnak egy felesleges nbt-t, amit a Slimefun és küldetéses plugin nem támogat.
Meg kellene csinálni, hogy ne adjon hozzájuk ilyet és az item data 0 maradjon.

<img width="322" alt="Screenshot 2020-08-03 123839" src="https://user-images.githubusercontent.com/8324198/89187064-01807900-d59d-11ea-83d0-7523c243d373.png">

**Comment by andris155** [comment]
Meg elvileg a meta-type: TILE_ENTITY, és meta-type: SPAWN_EGG se kell hozzá.

**Comment by poma123** [comment]
Az ItemMeta az olyan amilyen, azzal nem lehet mit kezdeni, és nem befolyásol semmit.

**Comment by andris155** [comment]
De ha nem rakja rá a Damage: 1-et elvileg az se lesz ott.

**Comment by poma123** [comment]
Mondom, nincs köze hozzá. A damage az 1.12 és azelőtti formátum, az itemmeta 1.13tól került a középpontba.

**Comment by poma123** [comment]
Holnap betölt Survivalon és Savszigeten.

**Comment by andris155** [comment]
köszi
