### ISSUE TITLE
Effektek az iránytűben

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#3778]
**Szerver**: Login, lobby

![kép](https://user-images.githubusercontent.com/29709854/89208102-09034a80-d5bc-11ea-87b7-b5eb7234027d.png)

Hiába kattintok rá, nem hozza elő a GUI-t, csak egy másodpercre, villanásszerűen. Másnak is ez van, de van akinek meg jó.

**Comment by andris155** [comment]
Megváltozott kicsit a működése. A close-on-click: true már mindig kell. Ezt jó ha te is tudod @poma123 
Javítva.
