### ISSUE TITLE
Icy Bow törlése a Lucky blockokból

### ISSUE THREAD

**Issue by VdszHun** [andris155/TheOld-Crafters#3779]
**Szerver**: Survival
Ugye az Icy bow tiltásra került de még megszerezhető Lucky blockból. Törölni kéne abból is vagy a helyére tenni mást.

**Comment by poma123** [comment]
Kivéve.

**Comment by andris155** [comment]
De ha esetleg javítva lesz, akkor majd vissza kell rakni. :D
