### ISSUE TITLE
Gps activation device ->kőlap

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#3782]
**Szerver**: Szurvi, (sav)
*Alap gps-rendszer helyzet*
A GPS teleport matrix-ra(vasblokkra)  GPS activation device-t(nyomólapot) kell tenni, hogy működjön
Ha a gps teleport matrix-ot ütjük ki először, miközben rajta az activation device, sima kőlapot droppol a device helyett

**Comment by andris155** [comment]
Javításra került. Holnap betölt.

**Comment by andris155** [comment]
330 OCD
