### ISSUE TITLE
Ore grinder: Zúzottkő -> sóder (és homok?)

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#3784]
**Szerver**: Szurvi, sav
Ore grinderbe ha teszünk be zúzottkövet, sódert kapunk.
Azonban van egy olyan recept is benne h 8 zúzottkőből készít homokot.
Ez pont így jó, de az a homokos recept oda felesleges

**Comment by andris155** [comment]
https://github.com/andris155/TheOld-Crafters/issues/3724
Már jelentet hiba. Egyébként a homok fog majd maradni ahogy láttam a javításból.

**Comment by skrisz0101** [comment]
@andris155 légyszi nézd meg újra, ez is hasonló hiba, de más

**Comment by andris155** [comment]
Azt írta a fejlesztő, hogy ez nem hiba.
