### ISSUE TITLE
Slimefun industrial minerek

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#3785]

**Comment by andris155** [comment]
Nem fog bekerülni még kiszedik a kreatívban lerakott érceket is.

**Comment by andris155** [comment]
Már megírtam a kreatív védelem fejlesztőnek, de egyelőre nem oldotta meg.

**Comment by andris155** [comment]
Nincs erre megoldás jelenleg.

**Comment by skrisz0101** [comment]
Írtam egyet :(
Kreában tiltani az érc lerakást, abból az ég adta világon senki se építkezik
@andris155

**Comment by poma123** [comment]
De a régen lerakott ércekkel nem lehet mit kezdeni.
