### ISSUE TITLE
Multi tool

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#3786]
**Szerver**: Szurvi ?sav?
Ha multi tool-al pl egy kőre jobb kattolok, ezt írja ki:
![2020-08-03_22 14 25](https://user-images.githubusercontent.com/29951969/89223349-ecc0d700-d5d6-11ea-9a77-6943c6f4c00b.png)

**Comment by andris155** [comment]
Gondolom kreatívos blokk és azért írja.

**Comment by andris155** [comment]
@poma123 Nem lehetne, hogy mielőtt megnézi, hogy kreatív blokk-e megnézi, hogy milyen blokk-e amire kattint és csak akkor nem engedi, ha egyezik a megadott blokk típus + kreatívban lerakott blokk?

**Comment by poma123** [comment]
Csak akkor jelez be ha kreatívban lett letéve

**Comment by andris155** [comment]
Akkor ez gondolom marad így.
