### ISSUE TITLE
Chat

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#3787]
**Szerver**: Mindenhol

Egyik próbaidős jelezte, hogy tök jó lenne egy olyan chat, amivel a közelben lévő emberekkel lehetne chat-elni, pl. /nearchat vagy ilyesmi. Ha megoldható, jó kis dolog lenne

**Comment by andris155** [comment]
A staffoknak így már tényleg össze fog folyni minden ha még ezt is ellenőrizniük kell.

**Comment by andris155** [comment]
Nem tartom egy jó ötletnek. Sajnos kevesen játszanak sok esetben ahhoz, hogy ez hasznos lenne.

**Comment by andris155** [comment]
De kíváncsi lennék mások véleményére ezzel kapcsolatban.

**Comment by MrZero1** [comment]
Ha van ilyen és akár lenne is, akkor ezt is olyan szinten néznék a játékosok, mint a privátot. Tehát ha káromkodna valaki, azt gondolom kicsillagozná

**Comment by MrZero1** [comment]
Ez inkább az adminoknak lehet zavaróbb a spy miatt. De csak egy ötlet, szóval nem kell rá egyből a diszlájk reacc. 🤷🏼‍♂️

**Comment by andris155** [comment]
Nem andris155 reagált rá ha megnézed.

**Comment by MrZero1** [comment]
Tudom.

**Comment by andris155** [comment]
Az EssentialsX tud ilyet viszont a globális chat helyett. Erre is legyen egy 107. plugin?

**Comment by Shryxx** [comment]
Véleményem szerint van elég chat ahhoz, hogy a játékosok tudjanak írkálni. Ott a partychat, ha ketten akarnak ott a @_játékosnév_, ploton a /p chat. Szerintem nem sokan használnák ha bekerülne, de lehet csak én gondolom így.

**Comment by andris155** [comment]
Party chat, telek chat, a savon pedig sziget chat. Szerintem ennyi chat elég egyelőre. :D
