### ISSUE TITLE
Partychat ignore

### ISSUE THREAD

**Issue by Shryxx** [andris155/TheOld-Crafters#3791]
**Szerver**: Survival, Sav (?)

Ha valakit ignoreolok látom partychaten amit ír :( 

![2020-08-04_13 00 46](https://user-images.githubusercontent.com/65125529/89286697-f556f300-d652-11ea-9972-e2aa2b382e3d.png)

**Comment by skrisz0101** [comment]
Staffszidásban

**Comment by poma123** [comment]
Partychatre ez nem vonatkozik. (EssX-ben van az ignore, a partychat pedig McMMO)
