### ISSUE TITLE
Enhanced Furnace X+ és az Ancient Debris

### ISSUE THREAD

**Issue by WolterFox** [andris155/TheOld-Crafters#3796]
**Szerver**: Survival és lehetséges, hogy Savon is!

Érdekesen az Enhanced Furnace X és még azon magasabb színtű kemencékben az Ancient Debris száma nem szokott triplázódni. az mcMMO képesség nem effektálja ezt és az mcMMO képesség (Olvasztás) még nincs be implementálva a játékba, de nem sokára lesz. Valamiért az Enhanced Furnace nem érzékeli olyan ércnek mint pl. a vas vagy az arany az Ancient Debrist. Lehet, hogy ez nem bug és feleslegesen írom ezt, mert lehet, hogy BusyBiscuit nem akarta, hogy lehessen triplázni ezt a ritka tárgyat. Attól függően, megírom ezt.

Az allábbi képen látható az, hogy kiolvasztottam 16 Ancient Debrist és 16-ot kaptam
![2020-08-04_17 51 38](https://user-images.githubusercontent.com/68710185/89315471-2c40ff00-d67b-11ea-9071-a9a4318aca96.png)

Ezen a 2 képen látható, hogy 16 vasat tettem be és sokkal több jöt ki!
![2020-08-04_18 00 26](https://user-images.githubusercontent.com/68710185/89316494-7b3b6400-d67c-11ea-80cc-c5c6969c410c.png)
![2020-08-04_18 01 08](https://user-images.githubusercontent.com/68710185/89316504-7d9dbe00-d67c-11ea-84d8-ddf5f3c197a1.png)

**Comment by poma123** [comment]
Szerintem ez direkt ilyen.

**Comment by WolterFox** [comment]
Megkérdeztem Busy-t és igen... direkt :(

**Comment by andris155** [comment]
Köszi, hogy utána jártál helyettünk is ennek.
