### ISSUE TITLE
Zsombec Elytra eventje, újragondolva.

### ISSUE THREAD

**Issue by WolterFox** [andris155/TheOld-Crafters#3797]
**Szerver**:Survival
Egy elég érdekes logikával lenne ez megoldva. Lényegében van egy óriási nagy lejtő, ahol karikákba kell belerepkedni. Összesen 4 színű karika van: A kék (1 pont) a zöld (3 pont) a sárga (5 pont) és a Narancssárga (10 pont). A lényeg az, hogy egy 3 perces időn keresztül kell repülgetni mindenkinek. A megoldás, hogy hogyan jussunk fel megint? Egyszerű, vagy pressure plate vagy command block detection system. Ezt a systemet lehetne használni a karikáknál is. Lényeg az, hogy akinek a legtöbb a pontja az nyer. 3 helyezet van, Első; Második; Harmadik. Az event elején mindenkinek üres inventoryval kell kezdenie. Akinek nincs elytrája, az vásárolhat, akinek van az hozhat. Ha valaki tüzijátékot használ kibannolják X időre. A nyeremény az elsőnek kulcs eventpont és token. A többieknek is ugyanez, kulcs kivételével.

**Comment by andris155** [comment]
https://github.com/andris155/TheOld-Crafters/issues/3762

**Comment by andris155** [comment]
Ezt inkább oda kellene kommentbe írni. Nem kell ehhez új kérést nyitni.
