### ISSUE TITLE
Skyblock spawn

### ISSUE THREAD

**Issue by NBabi** [andris155/TheOld-Crafters#380]
A spawnon az OldGold ládák már csak sima ládák, nem található bennük OldGold. (nem tudom ez bug, vagy direkt így van, de gondoltam szólok)
![2017-01-06_00 36 10](https://cloud.githubusercontent.com/assets/22939109/21701803/3264c36e-d3a8-11e6-8d20-5b2f6569de4c.png)

**Comment by andris155** [comment]
Egy hiba miatt kivette a Tulaj, mivel a hibát javítottam újra lesz majd oldgold.
