### ISSUE TITLE
SlimeFun tárgy anvilezés

### ISSUE THREAD

**Issue by WolterFox** [andris155/TheOld-Crafters#3800]
**Szerver**:Survival és tán Savsziget.
Ha anvilben enchantolunk egy SlimeFun tárgyat (pl: Smelter's Pickaxe) akkor ugyebár nem lehet, viszont az xp lemegy minden enchantolás próbálással és nem kapjuk vissza.
Itt vannak képek róla:
Előtte:
![2020-08-05_08 39 53](https://user-images.githubusercontent.com/68710185/89380295-90090d80-d6f7-11ea-9f4e-9791467d37be.png)
![2020-08-05_08 39 55](https://user-images.githubusercontent.com/68710185/89380301-91d2d100-d6f7-11ea-8649-2e6d634282cc.png)
![2020-08-05_08 39 57](https://user-images.githubusercontent.com/68710185/89380306-939c9480-d6f7-11ea-
9199-15505c4679f1.png)
Utánna:
![2020-08-05_08 40 07](https://user-images.githubusercontent.com/68710185/89380334-9d25fc80-d6f7-11ea-8a34-1c33f32df1d0.png)

**Comment by poma123** [comment]
De ez is jelentve lett már... és le is lett zárva. Légyszi jelentés előtt nézz már körül, hogy jelentve lett-e már.

**Comment by WolterFox** [comment]
Jólvanna poma, nem tudtam :c
