### ISSUE TITLE
Savsziget 1v1

### ISSUE THREAD

**Issue by szofogado** [andris155/TheOld-Crafters#3803]
A savsziget nevű szerveren az 1v1 minigame-ben automaikosan vissza töltődik a kaja csíkod max-ra ha lemegy. Ezért szinte örökké tartanak azok a küzdelmek amik közelharca épülnek. Megköszönném ha ezt kikapcsolnák. Illetve lehetne behozni olyan kiteket aminél nincsen armor, vagy csak lánc/vas/bőr. 
Meg néhány baltás kit is jó lenne.

Válaszukat előre is köszönöm!

**Comment by MrZero1** [comment]
Ránézek erre is, gondolom a feed flag. Kiteket meg csinálok néhányat

**Comment by MrZero1** [comment]
Megcsináltam, átállítottam a flag-eket, és csináltam pár új kitet, majd még csinálok ha lesz rá időm.

**Comment by MrZero1** [comment]
330 OCD, el is küldtem.
