### ISSUE TITLE
/sit és a paintball

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#3806]
**Szerver**: szurvi
Ha ülés közben /pb join-olunk, akkor nem dob be a lobbyba, de a kitet megkapjuk

Megoldás: egy warpról/warpolással lehetne bejutni pb-re. Mint pl a /warp eventeknél az automatikus eventek

Ez a hiba csak a paintballnál van, teszteltük

 @UDPSendToFailed találta

**Comment by UDPSendToFailed** [comment]
Ezt is én találtam. :(

**Comment by MrZero1** [comment]
Van egy lobby-ja a paintball-nak, a /minigame GUI-ból elérhető. Ha nem lehet máshogy javítani, akkor ott lesz a lobby

**Comment by MrZero1** [comment]
Eventeken amúgy nem lehet átbugolni a falakon vagy ilyesmi?

**Comment by andris155** [comment]
Az event világban le van tiltva.

**Comment by andris155** [comment]
Szerintem erre nincs megoldás. Vagy Paintball-t vagy a leülést ki kell venni.

**Comment by andris155** [comment]
Egyelőre kivettem a leülést így. Komoly gondot is okozhat nem csak paintball-ban ha valaki így lép be valahova vagy tp-zik valahova.

**Comment by MrZero1** [comment]
Ha a paintballra csak táblásan lehetne csatlakozni, akkor sem lenne jó?

**Comment by andris155** [comment]
Nem lehet megoldani minden teleportálós dolgot táblával.
