### ISSUE TITLE
/is setttings 

### ISSUE THREAD

**Issue by laci1324-1** [andris155/TheOld-Crafters#3807]
Szerver: savsziget 
Az Al-tulajdonos nem tudja állítani a /is settings - be a beállításokat.  Jó lenne ha tudná állítani mert ha a sziget tulaj nincs fent és kéne valamit állítani a szigeten  akkor az Al-tulajdonos is meg tudná csinálni. A választ előre is köszönöm.

**Comment by andris155** [comment]
Szerintem ez így jó, hogy csak a tulajdonos fér hozzá ezekhez.
