### ISSUE TITLE
skyblock pex

### ISSUE THREAD

**Issue by NBabi** [andris155/TheOld-Crafters#381]
A rangom V.I.P.+, amit tabon jól mutat, chatben pedig V.I.P.-nek mutatja, a végzetládám pedig Tag Végzetláda.
![2017-01-06_00 37 33](https://cloud.githubusercontent.com/assets/22939109/21701886/9f790df2-d3a8-11e6-9e63-766722930caf.png)
![2017-01-06_00 37 44](https://cloud.githubusercontent.com/assets/22939109/21701887/9f919048-d3a8-11e6-88ee-d36ddcbfa5b4.png)

**Comment by andris155** [comment]
Hát kamu rangod van, megadtam a simát.

**Comment by NBabi** [comment]
köszönöm szépen :)
