### ISSUE TITLE
/god -ban kopik az armor (savsziget)

### ISSUE THREAD

**Issue by diepitepie** [andris155/TheOld-Crafters#3812]
Savszigeten hiába voltam /god -ban, lekopott a netherite old szettem.
Később leteszteltem és pár páncél nem kopik (pl. teknőspáncél, emeráld nadrág, emeráld csizma, bőrnadrág, bőrcsizma), míg pár igen (pl. szavazói sisak, emeráld mellvért, netherite sisak, mellvért, nadrág, csizma)

**Szerver**: savsziget

**Comment by andris155** [comment]
Valamelyik enchant miatt gondolom.

**Comment by andris155** [comment]
Majd tesztelem nappal.

**Comment by andris155** [comment]
Ezek a savban kopnak?

**Comment by diepitepie** [comment]
Ghast farmnál vettem észre, de megnéztem és savban is kopik.

**Comment by andris155** [comment]
Akkor ezt még majd bővebben tesztelnem kell.

**Comment by andris155** [comment]
A thorns enchant miatt megy le a durability-je. @MrZero1 szerinted alapból inkább így ne legyen rajta ilyen enchant?

**Comment by MrZero1** [comment]
Lelehet venni róla azt, ha így működik megfelelően

**Comment by andris155** [comment]
A szerveren beállítottam. Majd még a képeket kell frissíteni a MineMarket-ben.

**Comment by andris155** [comment]
Kész. Az újonnan vásárolt Old szettek már nem fognak sérülni god módban.
