### ISSUE TITLE
Weboldal hibák/ötletek

### ISSUE THREAD

**Issue by Shryxx** [andris155/TheOld-Crafters#3813]
https://www.oldcrafters.net/parancsok/

**Segítség kérése** részhez: /ghelpop

**Szimpla Játékos parancsok** részhez: 

- /1v1 toggle (Párbajfelkérés letiltása/enedélyezése), hasznos. :) 
**Hibák**:
- /tpauto parancshoz nincs jogunk, 
- /dispose parancs nincs, /disposal a szemetes.

_**Survival**_

**Terület lefoglalás a szabadban** részen: nomonsterspawns flaghez nincs jogunk.

**Telekszerzés**: 
- /plot merge all minden telket összevon, hasznos parancs.

**Hibák**:
- /plot deny parancshoz nincs jog, (direkt nincs jog, szóval ezt ki kéne szedni onnnan)
- /plot chat off/on, az off/on nem csinál  semmit, csak a /p chat-tel lehet ki be kapcsolgatni a telek chatet, /plot set parancsokhoz nincs jog.

**Saját bolt**: Nincs már /warp pláza.

**PvP**: NIncsenek ilyen parancsok.

**Survival Games**: Ilyen parancsok sincsenek.

**Játékos teleportok**: /pwarp set mehetne oda.

**_Savsziget_**

**/teleportok menü**: Eszközök warp nincs, mehetne a helyére Slimefun warp.

**AcidIsland (Plugin)**:
 
- /ai helyett lehetne /is a parancsok előtt, mindenki azt használja, és úgy még tabozni is lehet a parancsokat,
- /ai controlpanel nincs, talán a /is info a jó parancs erre.
- /ai minishop nincs, /shop van.
- /ai warp nincs, /is pwarp van.

- /ai invite játékos – Felkér egy játékost, hogy csatlakozzon a szigetedhez.
 /ai leave – Elhagyja a játékos a szigetet.
 /ai kick játékos – Egy játékos kitiltása a szigetről.
 /ai accept/reject – Elfogadja vagy elutasítja a felkérést.
Mindegyik parancs /is team-el kezdődik.

Lényegében az összes savos parancsot át kellene írni a jelenlegire.

**_OldSpace_**

OldSpace-nek is le lehetne írni a parancsait oda.

https://www.oldcrafters.net/fogalmak/

Ide is kerülhetne OldSpace-ről olyan mini leírás mint a többi szerverről.

**Comment by Shryxx** [comment]
Teszteltem minden parancsot amit ide leírtam. Lehet van még ami rossz, vagy lehet, hogy van ami nem rossz, csak én vagyok nub és elnéztem.

**Comment by andris155** [comment]
Biztosan van még benne hiba. Meg hiányosságok is bőven. Sajnos nem mostanában volt időm ezzel foglalkozni. Nyugodtan lehet hozzá ötleteket írni meg a hibákat megkeresni.

**Comment by Shryxx** [comment]
OldSpace cucchoz:

**Alapvető parancsok:**

/teendő - Kiírja, hogy mi a feladat a világban, ahol tartózkodsz.
/party help - Party parancsok
/fix - Tárgy javítás (ár: 5 XP szint)
/rangok - Rangok listája
/leírások - Speciális dolgokhoz tartozó információk.
/receptek - Receptkönyv lekérése
/recipe <tárgy_id> - Vanilla receptek böngészése
/levédés - Parancsok, infók a levédésről
/haza - Teleportálás arra a helyre, ahova a rakétával leszálltál az adott bolygón.
(Ez amúgy a /help-ben van leírva (xd))

**Party parancsok:**

/party create <név> - Party létrehozása
/party invite <játékos> - Játékos meghívása a partyba
/party accept - Party meghívás elfogadása
/party info - Party információ
/party chat - Party csevegő be-/kikapcsolása
/party szövetség - Party szövetség parancsok
/party transfer <játékos> - Tulajdonjog átruházása
/party bázis - Teleportálás az adott bolygón lévő bázispontra
/party setbázis - Adott bolygón lévő bázispont beállítása
/party delbázis - Adott bolygón lévő bázispont törlése
/party kick <játékos> - Játékos kirúgása a partyból
/party quit - Kilépés a partyból
/party disband - Party feloszlatása
(Ez a /party help)

**Levédés:**

A survivalos levédés jöhetne ide. (Ha oldspacen is az van)

**McMMO parancsok (földtől):**

Nincs jogom a help cucchoz szóval azt sem tudom leírni :(

**Comment by MrZero1** [comment]
OldSpace-en a /ignore parancsra van joguk a játékosoknak?

**Comment by MrZero1** [comment]
/ignore név parancsra is van joguk, azt is belelehetne írni

**Comment by andris155** [comment]
A plot merge all az all ott lehet más is szóval azt nem írom bele.

**Comment by andris155** [comment]
Vannak dolgok, amikre pedig van jog és a plot set-tel tudod állítani.

**Comment by andris155** [comment]
Támogatói jogokat nem írunk ide le.

**Comment by andris155** [comment]
Megvalósítottam a leírtakat. Köszönöm a segítséget.

**Comment by andris155** [comment]
A fogalom oldalhoz egyelőre nem írtam szöveget. Annak kellene, aki jobban ismeri az OldSpace-t.
