### ISSUE TITLE
Smelters Pickaxe + Kvarc

### ISSUE THREAD

**Issue by WolterFox** [andris155/TheOld-Crafters#3814]
**Szerver**:Survival; Sav
Érdekesen ha Smelters Pickaxet használsz Fortune III-al kvarcon, a kvarc csak 1 darabot ad.

**Comment by andris155** [comment]
A Smelters Pickaxe-t csak azokra az ércekre használd, amiket ki kellene sütni kemencében utána. Ez nem hiba. Ez inkább helytelen használat.
