### ISSUE TITLE
/ignore fordításhiba

### ISSUE THREAD

**Issue by Shryxx** [andris155/TheOld-Crafters#3815]
**Szerver**: Survival
![image](https://user-images.githubusercontent.com/65125529/89522412-7cd26c80-d7e1-11ea-85dc-982f578f2751.png)

Elsőhöz: Mostantól figyelmen kívül hagyod Játékos-t.
Második: Többé nem hagyod figyelmen kívül Játékos-t.

**Comment by poma123** [comment]
Imádom, hogy az a montlikadani minden plugint lefordít, de olyan szarul hogy az elképesztő.

Legyen így:

- Mostantól figyelmen kívül hagyod {player} játékost.
- Többé nem hagyod figyelmen kívül {player} játékost.

**Comment by WolterFox** [comment]
Poma, tudom, nem segít amit hozzá teszek, de szerintem belerakták egy google fordítóba oszt hagyták, hagy legyen.

**Comment by poma123** [comment]
Az a szomorú, hogy nem.

**Comment by poma123** [comment]
@andris155 a Crowdin-en átírtam, légyszi fogadd majd el.

**Comment by andris155** [comment]
Nem egyszerű ezeket úgy lefordítani, hogy sokszor nem is tudni mi kerül a változó helyére. De biztosan vannak benne még hibák. Nyugodtan vég lehet próbálni a dolgokat az EssentialsX-ben.

**Comment by andris155** [comment]
Elfogadtam, majd frissítem a fájlt.

**Comment by andris155** [comment]
Frissítve.
