### ISSUE TITLE
Effektek az eventen

### ISSUE THREAD

**Issue by szofogado** [andris155/TheOld-Crafters#3816]
Savszigeten ha van traveller talizmánod és aktiválodik, akkor kapsz speed 3 effektet 3 percig, Ameddig tart az effekt  addig eltudsz menni eventezni, ezzel kihasználva ezt a csalást. 

Válaszukat előre is köszönöm!

**Comment by KingDeadZ** [comment]
Valszeg működik akkor survin is, megoldás lehetne az, hogyha levenné az effekteket akkor, amikor valamelyik eventnek a helyére odamész.

**Comment by poma123** [comment]
Le kéne vennie az effektet, kivéve, ha az eventen aktiválódik. Le kell tiltani.

**Comment by andris155** [comment]
Minek kellene levenni az effektek? Szerintem kellene egy ellenőrzés mikor belép az eventre, hogy ne legyen rajta effekt.

**Comment by andris155** [comment]
Az event világban nem tud egyébként aktiválódni, mert le van tiltva és a tiltás működik is. De gondolom úgy mennek oda, hogy rajtuk van az effekt.

**Comment by poma123** [comment]
Van egy flag, amit én csináltam, azért... clear-potion, ez törli az effekteket. Bár lehet hogy savon ez nem lett beállítva

**Comment by poma123** [comment]
Kész

**Comment by andris155** [comment]
Köszi.
