### ISSUE TITLE
Slimefun tárgyak falusiak

### ISSUE THREAD

**Issue by szofogado** [andris155/TheOld-Crafters#3817]
Az sf-es vas rudakat el lehet adni a falusiaknál. A vip warpon eladtam 12 aluminiumot 64 szénért. Nem teszteltem, hogy a coppert is el lehet-e adni, 

savsziget-en találtam ezt a hibát.

Válaszukat előre is köszönöm.

**Comment by poma123** [comment]
Kérdéses, hogy a javítása nem akad-e össze a Shopkeepers-el, egy olyan beváltónál aminél sf itemért lehet beváltani valamit.

**Comment by andris155** [comment]
Lehet igen, de ez meg már a Shopkeepers plugin hibája lesz, hogy nem támogatja a Slimefun-t. :/

**Comment by poma123** [comment]
Javítva
