### ISSUE TITLE
Piston addolás kreatívból

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#3818]
Ha egy aktivált piston-t lerakok 2 összekapcsolt telek közötti útra, majd szétválasztom a telkeket, kidobja a piston-t felvehető survivalos itemként.

**Comment by andris155** [comment]
Már 2x lett kérve PlotSquared támogatás a fejlesztőtől. Sajnos erre más megoldást nem tudok. Tiltani nem szeretném ezt is kreatívban.
