### ISSUE TITLE
skyblock V.I.P.+ rang jogok

### ISSUE THREAD

**Issue by NBabi** [andris155/TheOld-Crafters#382]
jogok amik V.I.P.+-ként elérhetőek nekem:
-/fly
-/heal
-/feed
-/hat
-/afk
-/fix
-/god
-/pweather

jogok amik V.I.P.+-nak elérhető kellene legyen, de nincs jogom:
-/kit (nincs kit a szerveren, pedig a kit színeket írja a minemarket)
-/nick
-színes írás
-/invsee
-/workbench
-/craft
-/me
-az inventory csak 3 soros (V.I.P+-nak 5 soros kellene legyen, ha a Prémium ranggal egyezik)

**Comment by andris155** [comment]
Csak prefixed volt, a rang rendben van.
