### ISSUE TITLE
Bounty plugin

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#3820]
**Szerver**: Szurvi
Régen volt HardcoreX-en bounty, sztem lehetne itt is.
(Fejpénz)

**Comment by poma123** [comment]
Ez volt HardcoreX-en: https://www.spigotmc.org/resources/bountyhunters-legacy.40610/
Ez sajna csak legacy módban megy, sok hibával gondolom. A teljes 1.16 támogatást csak a [prémium verzióban](https://www.spigotmc.org/resources/bountyhunters-premium.72142/) van.

**Comment by andris155** [comment]
Mivel mostanában nagyon kevés a támogató sajnos nem tudjuk megvenni egyelőre.

**Comment by skrisz0101** [comment]
Unbannoljuk ProTechet, pár 100k-t csak megér egy unban

**Comment by andris155** [comment]
Nem rajta múlik, hogy feloldjuk-e a tiltását.

**Comment by andris155** [comment]
Nem rajtam múlik, hogy feloldjuk-e a tiltását.

**Comment by MrZero1** [comment]
Feloldhatjuk a tiltását, de az meg nem jelenti azt, hogy támogatni fog.

**Comment by andris155** [comment]
Egyelőre most ez nem fog bekerülni. De később lehetséges.
