### ISSUE TITLE
Levédés flagek - amik szerintem bekerülhetnének

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#3821]
**Szerver**: Szurvi, ?OldSpace?

NoChorusFruit - Refrén gyümölcs evésének engedélyezése/tiltása
NoOpenDoors - Ajtók nyitása/zárása
NoVehicle - Csillék/hajók engedélyezése/tiltása (nem teheti le)
NoEnterPlayer - Emberek tiltása levédésről
NoGrowth - Növények növekedésének engedélyezése/tiltása
NoIceForm - Jég elolvadásának engedélyezése/tiltása
NoLeafDecay - Levelek eltűnésének engedélyezése/tiltása
NoItemDrop - Item kidobásának engedélyezése/tiltása
NoMobSpawnsType - adott mob spawnolásának engedélyezése/tiltása
NoVineGrowt - Inda növekedésének engedélyezése/tiltása

**Comment by lovi-dev** [comment]
NoMobSpawnsType  volt, kivették, okkal.

**Comment by andris155** [comment]
A NoEnterPlayer-re adtam jogot, mivel már többen kérték ezt. A többi egy része pedig alapból tiltva van. A másik része pedig szerintem nem túlélő szerverre való. A NoMobSpawnsType optimalizáció miatt lett tiltva.
Az OldSpace-n @poma123 eldönti mire ad jogot majd.
