### ISSUE TITLE
Minemarket elírás

### ISSUE THREAD

**Issue by Shryxx** [andris155/TheOld-Crafters#3822]
Ezek csak a survivalos rangok. 
https://theold.minemarket.hu/category/rangok

![image](https://user-images.githubusercontent.com/65125529/89638696-883e9a00-d8ac-11ea-9271-070a44fa2156.png)
(Ez a minemarket, utolsó előtti pontot kell nézni)

Old tud csak belépni, ha tele van a szerver.

![image](https://user-images.githubusercontent.com/65125529/89638743-9ab8d380-d8ac-11ea-9efe-323a9297a9e1.png)
(Ez szerveren a /rangok, itt is az utsó előttit :))

![image](https://user-images.githubusercontent.com/65125529/89643562-4c103700-d8b6-11ea-8ca0-3d66b9eb1097.png)
Szerveren /rangok menüben a V.I.P-hez van írva a /pswitch, minemarketen már a tag+-nak is van joga hozzá.

![image](https://user-images.githubusercontent.com/65125529/89643913-161f8280-d8b7-11ea-871f-259847ec272f.png)
/rangok menüben Elit rang jogainál az utolsó előtti cuccban a ChangeBiome után az a kis kocka direkt van ott? Ha nem, akk ez is hiba.

![image](https://user-images.githubusercontent.com/65125529/89644034-57179700-d8b7-11ea-9dce-6ae049389607.png)
Szintén /rangok menüben a Prémium jogainál ott az a 33,3%-kal jobb az összes MCMMO képesség. Ez a weboldalon nincs leírva.

![image](https://user-images.githubusercontent.com/65125529/89643284-bc6a8880-d8b5-11ea-9445-e3e7735213d3.png)
10. izét kell nézni. 

![image](https://user-images.githubusercontent.com/65125529/89643395-f045ae00-d8b5-11ea-9b46-9a547308c2eb.png)
Itt a 12.-et. Az az 5 levédés nincs leírva /rangok menüben. Van egyáltalán rá korlátozás?

**Comment by Shryxx** [comment]
![image](https://user-images.githubusercontent.com/65125529/89643284-bc6a8880-d8b5-11ea-9445-e3e7735213d3.png)
10. izét kell nézni. 

![image](https://user-images.githubusercontent.com/65125529/89643395-f045ae00-d8b5-11ea-9b46-9a547308c2eb.png)
Itt a 12.-et. Az az 5 levédés nincs leírva /rangok menüben. Van egyáltalán rá korlátozás?

**Comment by andris155** [comment]
A levédés még régről maradt benne, de az vicces kicsit, hogy senkinek se tűnt fel eddig.

**Comment by andris155** [comment]
Az Old is betud lépni nyilván, de a prémium is ha tele szerver. Mondjuk nem hiszem, hogy mostanában tele lenne a szerver.

**Comment by andris155** [comment]
A /pswitch azért van beleírva, mert attól a rangtól van leginkább értelme. Azonkívül max akkor ha lejár a rang, vagy valaki vesz több petet.

**Comment by andris155** [comment]
A többi hibát javítottam. Köszönjük az észrevételt.

**Comment by skrisz0101** [comment]
Tag+nak is több petje lehet

**Comment by andris155** [comment]
Hogy lehetne több neki?

**Comment by andris155** [comment]
2 van beleírva és annyi is lehet.

**Comment by Shryxx** [comment]
@andris155 az a lényeg, hogy minemarketben oda van írva a tag+ rang jogaihoz a /petswitch, szerveren a /rangok menüben pedig a V.I.P-hez van csak.

**Comment by andris155** [comment]
javítottam ezt is
