### ISSUE TITLE
Paintball - pályák

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#3823]
**Szerver**: Szurv,
Paintball minigameban 8 map van
Na, ezeknek egy része nem épp a legjobb a  paintballhoz.

Tökfej: Túl sok a spot, egyszerűen nem pb-hez való

Tábor: Túl nagy, rohadt nagy, kevés spot

Gyártelep:  Map felét nem használják, Elrendezése nem illik pb-hez. a Két csapat bázisa se épp ugyanolyan, a győzelem függ attól is hogy melyik bázist kapod

Hógömb: A gömb alak nem épp a legjobb,  a sima tér jobb lenne, kevés a spot

Híd: Könnyen lehet Spawnkillelni, egyébként az egyik legjobb map

Piac: Itt nem olyan vészes, de a spawnkill azért itt se olyan nehéz. Kicsit túl csicsás, túl sok a 
dísz a ,,Harcmezőn"

Tél: Szerintem ez egy jó map, nincs gond vele

Kert: Tökéletes

**Comment by MrZero1** [comment]
Nem is nagyon van használva a Paintball, így most nem is nagyon lesz ezzel foglalkozva. Majd ahogy időm lesz, javítom meg állítok be új arénákat.

**Comment by skrisz0101** [comment]
Pár napja minden nap megy. Felfuttattam. most is 10-en toltuk kb xd

**Comment by MrZero1** [comment]
Akkor majd szánok rá időt.

**Comment by MrZero1** [comment]
Elkezdtem tegnap este felújítani meg javítani a mapokat.

**Comment by skrisz0101** [comment]
@MrZero1 a Híd mapon csak az volt vészes hogy könnyen lehet spawnkillelni, maga a map sztem tökély volt.
Az indák a hídnál kicsit elveszik a map értelmét, h csak azokon lehet atmenni 
A bambusz is kicsit sokat takar

**Comment by MrZero1** [comment]
Kiszedtem. A tábor átkerül HG-ra, a tökfej meg kikerül.

**Comment by poma123** [comment]
A tábor mégse kerül át, a táborba bekerült 1 airstrike és 2 gránát minden újraéledéskor, szval mindenki kap 50 golyót, 2 gránátot és 1 airstrikeot

**Comment by poma123** [comment]
Minden probléma orvosolva.
