### ISSUE TITLE
Paintball - nem jó a poti

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#3824]
**Szerver**:Szurvi
Ilyen bájitalt kapunk ha veszünk egyet a paintball shop-ból: (Csak játék közben lehet)
![2020-08-06_19 03 57](https://user-images.githubusercontent.com/29951969/89643354-dc01b100-d8b5-11ea-8d05-706a4f91e03c.png)

**Comment by poma123** [comment]
Sajnos ez a pluginban van elcseszve, nincs normálisan megoldva.

**Comment by poma123** [comment]
Kivegyem? Javítani nem hiszem hogy javítják.
