### ISSUE TITLE
Chunk betöltési hiba

### ISSUE THREAD

**Issue by KriszLOW** [andris155/TheOld-Crafters#3825]
Szerver:Savsziget

Több játékos is jelezte beleétrve engemet is hogy vagy rendkívül lassan vagy egyáltalán nem tölt be a chunk és relog se segít rajta!

**Comment by skrisz0101** [comment]
Szurvin is lehet tapasztalni, többször pl a paintball. Map nem akart betölteni

**Comment by andris155** [comment]
Mivel a chunk betöltés async előfordulhat, hogy néha késik. Szerintem ki lehet várni. Egyáltalán betöltéssel én még nem találkoztam. Valószínűleg elég ritka.

**Comment by KriszLOW** [comment]
Tegnak 6-7 játékosnál nem töltött be és volt akinek kb 15 percig semmi se volt vagy csak néha néha egy két chunk

**Comment by andris155** [comment]
Javítottam a szerver teljesítményén, már jobban kell működnie a chunk betöltésnek is.
