### ISSUE TITLE
/back 

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#3826]
**Szerver**: Survival

miyagii játékos a pokolban volt, gyorsan a plot telkére teleportált (gondolom láva miatt), majd vissza akart térni a pokolba, de a back nem akart menni neki. Állítása szerint nem volt az eventvilágban mostanában/előtte.

Ezt írja ki neki, ugye. 
![kép](https://user-images.githubusercontent.com/29709854/89694849-45171200-d912-11ea-9c86-4e4885eb25fe.png)

**Comment by MrZero1** [comment]
Előző előtti helyre szeretné visszarakni, mert kiderült, hogy a farmon is járt nemrégiben.

**Comment by andris155** [comment]
A telket nem nézi a back, mivel az más plugin parancsa. Csak akkor nézi, ha a /home parancsot használja a telekre is. Valószínűleg valahogy az eventes világban volt mégis a telek előtt és oda pedig nincs joga visszamenni.

**Comment by MrZero1** [comment]
Áh, értem.
