### ISSUE TITLE
Paintball elírások

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#3827]
**Szerver**: Survi

![kép](https://user-images.githubusercontent.com/29709854/89719872-dd71cd00-d9cc-11ea-849e-89084202dcd5.png)

Szóközhiány: 
Helyesen: Kaptál egy ajándékot, XY-tól/től! Köszönd meg, majd jobb klikkelj a kibontáshoz.

Kimaradt fordítás(?):
![kép](https://user-images.githubusercontent.com/29709854/89719887-2164d200-d9cd-11ea-8b9f-a7e15be854a4.png)

Esetleg az XY-nak/nek lenne még a jó. A "Készítettél" helyett esetleg "Megajándékoztad" vagy csak "Adtál" lenne még a jobb.

**Comment by MrZero1** [comment]
Ha kapnak ajándékot, és kinyitják, akkor is vannak random angol szövegek. Ezek lefordíthatóak?
![kép](https://user-images.githubusercontent.com/29709854/89721109-e026ef00-d9d9-11ea-8414-0a1bb1415225.png)

**Comment by MrZero1** [comment]
Ha ezeket le lehet fordítani, szívesen lefordítom.

**Comment by andris155** [comment]
Le lehet mindent elvileg.

**Comment by andris155** [comment]
Kb. 6 éve írtuk ezt a fordítást. Szóval igen, biztosan vannak benne hibák. Bár párszor azért át lett talán már nézve azóta. :D

**Comment by MrZero1** [comment]
Ha elküldöd a fordításokat, szívesen átnézem 😄

**Comment by poma123** [comment]
Majd én átnézem

**Comment by poma123** [comment]
Kész

**Comment by andris155** [comment]
Remélem itt nem írtad át a nagybetűs dolgokat.

**Comment by poma123** [comment]
Ne legyünk már ennyire igénytelenek.
