### ISSUE TITLE
Paintball

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#3828]
**Szerver**: Survi

A turret-et (hóembert) ki lehetne venni esetleg? Játékosnak nincs joga megölni, ahogy nézzük.

**Comment by MrZero1** [comment]
Meg alapból nagyon OP, szinte pontosan céloz, jó messziről is kilövi az ellenfelet.

**Comment by andris155** [comment]
Biztosan meglehet oldani, hogy megtudják ölni.

**Comment by MrZero1** [comment]
A damage-animals flag-et néztük, engedélyeztem de akkor sem sebezte a hóembert. OP-val jó amúgy

**Comment by andris155** [comment]
Mivel a hóember nem állat. :D

**Comment by poma123** [comment]
damage-mobs flag kell

**Comment by andris155** [comment]
Ezzel működik akkor?

**Comment by MrZero1** [comment]
Ja, akkor majd délután teszteljük.

**Comment by MrZero1** [comment]
damage-animals flag kell rá.

**Comment by MrZero1** [comment]
Kész. Bár továbbra is kb. lehetetlen megölni.
