### ISSUE TITLE
cserekereskedők

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#3829]
**Szerver**: Szurvi
Próbáltam falusi tojással shopkreepers-t csinálni, de nem ment. ki lett véve? (remélem nem:( )

**Comment by VdszHun** [comment]
Minemarketen lehet venni külön Shopkeeper idézőt (10 db 508 OCD). Nemhiszem, hogy sima falusi idézőből lehet Shopkeepert csinálni.

**Comment by andris155** [comment]
Sima idézőből nem lehet.

**Comment by skrisz0101** [comment]
Hát de régen lehetett, most miért nem? :(

**Comment by andris155** [comment]
Mert aki sima falusit akart lerakni nem nagyon tudott, csak kidobóval maximum így készült hozzá egy külön tojás. A MineMarket-ben megvehető.

**Comment by skrisz0101** [comment]
Bal kézzel is le lehetett rakni
