### ISSUE TITLE
Minemarket

### ISSUE THREAD

**Issue by NBabi** [andris155/TheOld-Crafters#383]
http://theold.minemarket.hu/oldal/szervervalasztas

"Egyéb:" fülnél:
Rangok - WonderLanders
Járművek - WonderLanders

ez a két opció már nem érvényes, hisz a szerver bezárt.
![wonder](https://cloud.githubusercontent.com/assets/22939109/21702156/2d2dd550-d3aa-11e6-9d43-c76c909b0e57.jpg)

**Comment by andris155** [comment]
Virdinia próbál valamit alkotni a helyére, hát majd kiderül mi lesz belőle. Plusz munkát addig nem akarok addig csinálni magamnak, mert ha jó lesz akkor meg már be van legalább félig állítva.
