### ISSUE TITLE
Menci szombólumok

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#3832]
**Szerver**:Mindenhol |$
a <3, :), :(, ;), :star: fel tudja dobni a chatet, lehetne több ilyen is akár, változatosabb lenne a chat :D  (🦀 : crab :)

**Comment by poma123** [comment]
Az a rák pont rossz, mert chaten nem látszik. Csak olyat lehet, amit támogat a Minecraft.

**Comment by poma123** [comment]
![image](https://user-images.githubusercontent.com/25465545/89740029-d35fd500-da85-11ea-8a67-89fe89bad0fb.png)
ezek azok amik mennek. (xd)

**Comment by andris155** [comment]
<img width="497" alt="Capture" src="https://user-images.githubusercontent.com/8324198/89743137-555cf780-daa0-11ea-8990-e403e2abdbd1.PNG">

**Comment by poma123** [comment]
`:skull:` ☠
`:jingjang:` ☯
`:comet:` ☄
`:moon:` ☽
`:sun:` ☀
`:cloud:` ☁
`:umbrella:` ☂
`:snowman:` ☃
`:email:` ✉️
`:flower:` ❀
`:scissors:` ✂

Más valami?

**Comment by skrisz0101** [comment]
Alt 2 :)

**Comment by poma123** [comment]
és mi legyen ennek az idje? ☻

**Comment by skrisz0101** [comment]
:mosoly:

**Comment by skrisz0101** [comment]
Az a sarló és kalapács nem is látszik rendesen, kár érte

**Comment by poma123** [comment]
Na hagyjál békén..xd

**Comment by andris155** [comment]
Ne legyen magyarul, ha az összes többi angol már.

**Comment by poma123** [comment]
:smile: milyen?

**Comment by poma123** [comment]
Akkor ezek bekerülhetnek, @andris155?

**Comment by poma123** [comment]
Bekerültek, nem volt ellenvetés :)

**Comment by andris155** [comment]
Tőlem be.
