### ISSUE TITLE
aukciósház ötlet

### ISSUE THREAD

**Issue by diepitepie** [andris155/TheOld-Crafters#3833]
Lehetne az aukciósházon belül egy opció, hogy megnézd miket adtál el, mennyiért és ki vette meg (meg akár mit vettél, kitől, mennyiért).

**Comment by mnb124** [comment]
Régen úgy emlékszem volt.
Ha lehetne tényleg visszakerülhetne.

**Comment by andris155** [comment]
Ez a plugin sajnos nem tud ilyet, ami jelenleg bent van. Mivel ezzel megvagyok elégedve nem szeretném lecserélni.
