### ISSUE TITLE
Survival paintball bug (vagy nem tudom mi)

### ISSUE THREAD

**Issue by Bazsaaaa** [andris155/TheOld-Crafters#3834]

**Comment by poma123** [comment]
Kivettem a rocket launchert.

**Comment by andris155** [comment]
Majd le kell tesztelni és megírni a fejlesztőnek.

**Comment by poma123** [comment]
Nem kell semmit tesztelni, leteszteltem... és el is lettem küldve arra a szép helyre, mert "mérnemlehetlagnélküljácani???!?!!"
https://pastebin.com/fnC4rvuA

**Comment by andris155** [comment]
Gondolom, hogy kifagyott a szerver. Bár nem értem miért a túlélőn kellett ezt tesztelni. Ilyenkor ott a teszt szerver a szervergépen, vagy saját gépen. A fejlesztőnek pedig pár fontosabb plugin-nal tesztelés után szoktam csak jelenteni. Rengetegszer volt már olyan, hogy más plugin miatt volt hibás egy adott plugin.

**Comment by poma123** [comment]
... ok bocs hogy leteszteltem, máskor nem fogom!

**Comment by andris155** [comment]
Teszteld le, ha van ilyesmi. De ha crash-el a szerver ne a túlélőn ha lehet élesben. :D

**Comment by embervagyok2** [comment]
![image](https://user-images.githubusercontent.com/69633425/90134939-339a9380-dd72-11ea-95ac-9d1d7a799da6.png)

**Comment by embervagyok2** [comment]
![image](https://user-images.githubusercontent.com/69633425/90134956-37c6b100-dd72-11ea-83e0-2d595b6ab627.png)

**Comment by andris155** [comment]
Teszt szerveren amúgy nem sikerült reprodukálni egyelőre ezt.

**Comment by andris155** [comment]
Egy régebbi build-ban sikerült reprodukálnom. A Spigot-ban volt a hiba, de már javították. A mostani Paper szerverfájlban már jó így engedélyeztem újra.

**Comment by andris155** [comment]
A hiba miatt letudták rakni akár a repeater-t is. Majd ha meglátnátok a pályán, hogy hol van üssétek ki.
