### ISSUE TITLE
Savsziget tps gond

### ISSUE THREAD

**Issue by KriszLOW** [andris155/TheOld-Crafters#3835]
Savsziget

Nagyon le esett a tps senki szigetén nem találtunk semmi gyanusat ami levette volna!

**Comment by andris155** [comment]
Az AdvancedAchievements valamiért nem megfelelően működött. Ez nagyon fontos plugin a savszigeten @MrZero1 ?

**Comment by poma123** [comment]
Egyáltalán nem fontos, sőt szerintem idegesítő is.

**Comment by andris155** [comment]
+ rosszul is optimalizált.

**Comment by MrZero1** [comment]
Pedig maga a plugin jó.

**Comment by andris155** [comment]
Akkor maradjon?

**Comment by MrZero1** [comment]
ha laggoltat, vagy nem jó akkor nyilván ne. de nagy kár érte

**Comment by andris155** [comment]
Általában nem okoz problémát. De most akkor ez a plugin fontos vagy sem?

**Comment by andris155** [comment]
Szerintem elfér ez a plugin a szerveren. Eddig nem nagyon volt vele gond, valószínűleg csak egyszeri alkalom volt ez.
