### ISSUE TITLE
Delfinek

### ISSUE THREAD

**Issue by WolterFox** [andris155/TheOld-Crafters#3836]
**Szerver**:Survival
Valamiért, ha nem vagy delfin környékében, a delfinek el despawnolnak. Ki van kapcsolva a nomobspawns és nem értem miért van ez. Adtam neki halat, elneveztem és még mindig eltűnnek.

**Comment by skrisz0101** [comment]
Van felette levegő?

**Comment by WolterFox** [comment]
Igen sk, valamiért, ha nem vagy a közelükben (pl ha az a kifutójukban vagyok és elmegyek pl a te pwarpodra) egyszer csak eltűnnek. Ezt 5-ször teszteltem, mind különböző volt. 1 teszt: Sima delfin, nincs neve. 2 teszt: Sima delfin, nincs neve, halakat adtam neki (nem szoktak akkor despawnolni) 3. teszt: Sima delfin, elnevezett, 4. teszt: Sima Delfin, elnevezett, halakat adtam neki. 5. Teszt: Sima delfin, elnevezet, halakat adtam neki és le volt kötve. Mindegyik esetben, eltűntek.

**Comment by WolterFox** [comment]
Oh, ez van még a random kis trópusi halaimmal, nem tudom, hova tűnhetnek el :c

**Comment by andris155** [comment]
Pontosan mennyi mob van ott típusonként?

**Comment by WolterFox** [comment]
1 db/teszt

**Comment by andris155** [comment]
Mi az a /teszt?

**Comment by poma123** [comment]
1 db per teszt, tesztenként 1 darab...

**Comment by andris155** [comment]
A nomobspawns letiltja a mobok idéződését. Nem befolyásolja az eltűnést. 10 delfin lehet max egy helyen azonfelül törölni fogja a szerver. Sajnos nem tudom mi más miatt törlődhet. Talán a vanilla hibájára vezethető vissza. Ezt nagyon nehéz lenne kideríteni sajnos mitől ilyen.

**Comment by andris155** [comment]
Esetleg próbáld meg ott tartani a delfineket ahol alapból is előfordulhatnak.
,,Dolphins are found in groups of 3-5 in all ocean biomes, except frozen oceans and cold oceans. In Java Edition, they spawn between (exclusively) level 45 and the sea level of the world. Dolphins continuously spawn as long as their spawn requirements are met, similar to squid."
Talán ez okozhatja még a problémát, hogy nem megfelelő biome-n van, vagy nem megfelelő tengerszinten.
