### ISSUE TITLE
Minemarket - saját színes nevű item

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#3837]
**Szerver**:mindenhol
Elv van olyan lehetőség, hogy kérjünk egyedi színes nevű szettrt/tárgyat x ocd-ért
Ezt ki lehetne írni valahova minemarketen, mert kevesen tudnak erről

**Comment by andris155** [comment]
Mivel nem lehet automatizálni, én nem akarok ezzel foglalkozni. Ha az admin ad el OCD-ért az oké, de nem akarom hogy az adminoknak ezzel keljen foglalkozni.
