### ISSUE TITLE
Karmazsin ajtó levédés

### ISSUE THREAD

**Issue by Shryxx** [andris155/TheOld-Crafters#3838]
**Szerver**: Survival

A karmazsin ajtót nem lehet levédeni [lock] levédéssel. Én nemtudom hova kell írni, szóval megírom ide, hogy jó lenne, ha lehetne.

**Comment by andris155** [comment]
Most lelehet?

**Comment by Shryxx** [comment]
Igen, köszi

**Comment by Shryxx** [comment]
![2020-08-11_15 38 23](https://user-images.githubusercontent.com/65125529/89904027-b7c10f80-dbe8-11ea-9530-8e66f4b5a944.png)
így még mindig hiba

**Comment by andris155** [comment]
Az utóbbit később fogja támogatni. Sajnos ami támogatja egyelőre tele van hibákkal. Még azokat ki kell majd javítaniuk.

**Comment by andris155** [comment]
javítva

**Comment by andris155** [comment]
![2020-08-14_16 59 06](https://user-images.githubusercontent.com/8324198/90263110-7bdbb380-de4f-11ea-8f95-9392b58de014.png)
