### ISSUE TITLE
Lockolt ajtó bugoltatás

### ISSUE THREAD

**Issue by ghost** [andris155/TheOld-Crafters#3839]
**Szerver**: Survival, meg mindenhol, ahol van ilyen lock plugin.
[lock] táblával levédett ajtót kreatívban ki lehet nyitni, ha a egyszerre kattintunk kreatívban az ajtóra. Videót nem, de képet tudok mellékelni a dologról.

![2020-08-11_17 41 31](https://user-images.githubusercontent.com/65125529/89918172-ff9c6280-dbf9-11ea-8e62-69a04c486d08.png)
Ezen a képen látszik, hogy az ajtó lockolva van (nem általam).
![2020-08-11_17 41 55](https://user-images.githubusercontent.com/65125529/89918275-1e025e00-dbfa-11ea-9257-562299b5fb2e.png)
Ezen a képen az ajtó nyitva van. Ha nem vagyok hozzá adva az adott levédéshez, akkor is ki tudom nyitni a jobb és a bal klikk lenyomásával. Fontos, hogy egyszerre nyomd meg a két klikket, és kreatív játékmódban legyél.

**Comment by poma123** [comment]
És be is tudsz menni az ajtón?

**Comment by Shryxx** [comment]
Igen

**Comment by andris155** [comment]
Nem sikerült reprodukálnom. Még sprintelve se tudtam átmenni. Mindig visszadob.

**Comment by Shryxx** [comment]
De akkor én miért tudok ki be járkálni?

**Comment by andris155** [comment]
Talán ha csinálnál egy videót látnám mit csinálok esetleg máshogy amiért nekem nem működik.

**Comment by Shryxx** [comment]
Akkor csinálok videót, feltöltöm yt-re és elküldöm neked discordon. Nevet ezért nem akarok váltani

**Comment by poma123** [comment]
Imgurra is felteheted a videót, ha nem szeretnéd a youtube-t használni.

**Comment by andris155** [comment]
YouTube-ra a legegyszerűbb feltenni nem listázott videóként.

**Comment by Shryxx** [comment]
Elküldtem a linket facebookon. Remélem nem baj ha oda írtam xd

**Comment by andris155** [comment]
Raktam rá másik plugint. Lehet csak holnap lesz rá jog.
@poma123 erősen ajánlom, hogy az OldSpace-n is cseréld le a lockettepro-t.

**Comment by andris155** [comment]
Holnap elvileg javításra kerül.
