### ISSUE TITLE
Skyblock V.I.P. rang

### ISSUE THREAD

**Issue by NBabi** [andris155/TheOld-Crafters#384]
[V.I.P.]akos_ a rangja, de a végzetládája Tag Végzetláda. (a neve sem egyezik a rangjáéval, és míg a VIP-nak 4 soros kellene legyen, az övé 3 soros)
Feltételezem más rangoknál is csak Tag végzetláda van, ezt meg kellene nézni!
![15909163_1639723772765172_1434042709_o](https://cloud.githubusercontent.com/assets/22939109/21702235/b5aabe34-d3aa-11e6-8aa1-d7fb5b1f5c4b.png)

**Comment by andris155** [comment]
javítva
