### ISSUE TITLE
/craft

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#3840]
**Szerver**: Survi

![kép](https://user-images.githubusercontent.com/29709854/89932481-fae1a980-dc0d-11ea-914d-89cba6dbf393.png)

Nem jó a zöld könyv nekem. Egy receptet se látok, a kereső se jó. Vadonban, spawnon néztem. Poma feloldotta az összes előrelépést, de úgy se jó

**Comment by poma123** [comment]
Amúgy már működik a /recipe <id> megint.

**Comment by MrZero1** [comment]
Ez hasznos, játékosoknak is?
Mondjuk ettől függetlenül fura ez a receptes könyv.

**Comment by poma123** [comment]
Igen

**Comment by skrisz0101** [comment]
Nek sokszor csak akkor oldja fel az adott receptet, miután lecraftoltam
Nézd meg úgy @MrZero1

**Comment by MrZero1** [comment]
Akkor ott van a könyvben, de alapból, vagyis eddig minden recept ott volt, a keresőben meg lehetett keresni és kiadta. Legalábbis nekem

**Comment by Shryxx** [comment]
A hiba az, hogy a jobb felső oldalon az a kis kocka ki van pipálva neked. Akkor csak azt adja ki, amihez van alapanyagod.
![image](https://user-images.githubusercontent.com/65125529/89978123-1039f080-dc6d-11ea-8dfc-ea4704fda94d.png)
![image](https://user-images.githubusercontent.com/65125529/89978140-19c35880-dc6d-11ea-8802-7b18ec8b1853.png)

**Comment by Shryxx** [comment]
![image](https://user-images.githubusercontent.com/65125529/89978223-4d05e780-dc6d-11ea-9166-286ca54d54c2.png)
Ilyenkor csak azt adja ki amihez van cuccod

**Comment by MrZero1** [comment]
Úgyis néztem, de majd este megnézem megint.

**Comment by andris155** [comment]
Nem sikerült reprodukálnom a hibát.
<img width="600" alt="Capture" src="https://user-images.githubusercontent.com/8324198/90048011-25e20100-dcd3-11ea-8df2-ec351fe3948f.PNG">

**Comment by MrZero1** [comment]
És? Mert neked nem sikerült valamit reprodukálnod, már nem is létezik a hiba? Az szép. Ott a kép, leírtam mi van. 👏🏻
