### ISSUE TITLE
Paintball fegyverek

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#3841]
Így, hogy a rocket launcher kikerült, lehetne valami más a helyén, vagy esetleg a boltban a következő fegyvert engedélyezni az őrmesternek.

![kép](https://user-images.githubusercontent.com/16057404/89939591-79434900-dc18-11ea-8719-40ec62119d81.png)

**Comment by andris155** [comment]
Visszakerül majd ha javítva lesz. De még nem volt időm foglalkozni ezzel.

**Comment by andris155** [comment]
Vissza is került.
