### ISSUE TITLE
Jutalom OldSpace-n

### ISSUE THREAD

**Issue by DiaGamer321** [andris155/TheOld-Crafters#3843]
OldSpace->

Ha egy játékos megcsinálja az összes küldetést az összes bolygón, akkor a "Föld" rang árnyalatos kinézetü lesz. (Mint pl: Survivalon a Staffoknak)

**Comment by skrisz0101** [comment]
Nem 1.16os (még) az OldSpace, ez a lehetőség 1.16tól van

**Comment by andris155** [comment]
@poma123-tól függ, hogy frissíti-e. Ez nem rajtam múlik.

**Comment by poma123** [comment]
Prefix változás biztos nem lesz. 1.16-ra való frissítéssel kapcsolatos véleményemet már leírtam, szerintem sokáig tartana, amire nincs időm egyhuzamban + minden játékos elhúzna a fenébe.

**Comment by andris155** [comment]
Ha így gondolkodnék a túlélőt se frissítettem volna soha. Aki nem bír 1 napot várni a világ frissítés miatt nem is hiányozna senkinek se a szerverről szerintem.

**Comment by poma123** [comment]
Ki mondta, hogy 1 nap lesz?
