### ISSUE TITLE
Lock tábla elpárolgás

### ISSUE THREAD

**Issue by Shryxx** [andris155/TheOld-Crafters#3844]
**Szerver**: Survival
Ha lockolok egy ajtót, lehet az dupla ajtó, vagy csak egy, és kinyitom azt az oldalát, amelyiken van a [lock] tábla, akkor a tábla elpárolog.
![2020-08-12_07 10 57](https://user-images.githubusercontent.com/65125529/89977401-53935f80-dc6b-11ea-8771-b7f5a6aa405c.png)
Fenti képen látszik, hogy az ajtó lockolva van(mindegy, hogy van keret az ajtó körül, vagy nincs. A lényeg, hogy az ajtón legyen a tábla). A lenti képen kinyitottam az ajtót, és a tábla eltűnt róla.
![2020-08-12_07 11 01](https://user-images.githubusercontent.com/65125529/89977445-6c9c1080-dc6b-11ea-86f9-b6c69103dbb7.png)
Az ajtó és a tábla is mindegy, hogy milyen fajta. Mind ezt csinálja.

**Comment by andris155** [comment]
Túlélő módban rakd rá, és akkor nem tűnik el.

**Comment by andris155** [comment]
A fejlesztőnek megírtam, de addig még nincs javítva akkor így van rá megoldás.

**Comment by andris155** [comment]
javítva
