### ISSUE TITLE
Elytra hiba

### ISSUE THREAD

**Issue by TrapSensei** [andris155/TheOld-Crafters#3846]
**Szerver**: Survival szerver
Az elytrákat nem lehet kinyitni rendesen. Földről szinte lehetetlen elugrani elytrával, mert mindig visszateleportál. Ha magasabb helyekről ugrunk le akkor van esély rá hogy talán sikerül kinyitni és nem visszadob.

**Comment by WolterFox** [comment]
Sőt! Ha fly-t akarsz használni és elytra van rajtad, és leugrassz egy magas helyről, megpróbálsz flyolni, de kinyíllik az elytra, bebugolsz és vissza mész oda ahonnét leestél.

**Comment by embervagyok2** [comment]
ciganykurvak anyatok roman szorostalpu fasszopo fereg patkany gecik tetves fasszopo @Shryxx anyadat basszam teherbe ukran vendegmunkas @andris155

**Comment by andris155** [comment]
javítva
