### ISSUE TITLE
Command hiba

### ISSUE THREAD

**Issue by KriszLOW** [andris155/TheOld-Crafters#3848]
Savsziget

/receptek parancs nem müködik (an internal error occurred while attempting to prefer this command)

**Comment by Shryxx** [comment]
/warp receptek, onnan is lehet könyvet szerezni

**Comment by KriszLOW** [comment]
Könyve nem működik ezért volt a /receptek parancs

**Comment by embervagyok2** [comment]
ciganykurvak anyatok roman szorostalpu fasszopo fereg patkany gecik tetves fasszopo @tag+ anyadat basszam teherbe ukran vendegmunkas @youtube ciganykurvak anyatok roman szorostalpu fasszopo fereg patkany gecik tetves fasszopo @tag+ anyadat basszam teherbe ukran vendegmunkas @youtube ciganykurvak anyatok roman szorostalpu fasszopo fereg patkany gecik tetves fasszopo @tag+ anyadat basszam teherbe ukran vendegmunkas @youtube 
![image](https://user-images.githubusercontent.com/69633425/90134426-73ad4680-dd71-11ea-9938-67f9117f8891.png)

**Comment by embervagyok2** [comment]
ciganykurvak anyatok roman szorostalpu fasszopo fereg patkany gecik tetves fasszopo @Shryxx anyadat basszam teherbe ukran vendegmunkas @andris155

**Comment by embervagyok2** [comment]
ciganykurvak anyatok roman szorostalpu fasszopo fereg patkany gecik tetves fasszopo @Shryxx anyadat basszam teherbe ukran vendegmunkas @andris155

**Comment by andris155** [comment]
Elvileg javítva.

**Comment by andris155** [comment]
Már jó a könyv is, csak újat kell csinálni.
