### ISSUE TITLE
skyblock csatlakozás-lecsatlakozás

### ISSUE THREAD

**Issue by NBabi** [andris155/TheOld-Crafters#386]
Nem bug, JAVASLAT!
Szerintem ezt rövidíteni kellene, hasonlóan mint s1-en, ugye ez a megoldás van:
[+]playernév
[-]playernév

A túl hosszú szöveg egyrészt felesleges, másrészt zavaró. (nem csak számomra, más is említette)

[OldCrafters] Csatlakozott a szerverre [Tag]playernév!
[OldCrafters] Lecsatlakozott a szerverről [Tag]playernév!

**Comment by andris155** [comment]
Ez jó ötlet, be is állítottam.
