### ISSUE TITLE
Reformok a játékosok és a staffok részéről egyaránt

### ISSUE THREAD

**Issue by poma123** [andris155/TheOld-Crafters#3860]
**Szerver**: összes, de főleg Survival és Savsziget

Ez alatt a jelentés alatt lehet beküldeni ötleteket, javaslatokat, esetleg problémákat, amikről aztán megbeszélést folytatni. Tartsa mindkét fél tiszteletben a másik fél véleményét. A normális keretek közötti, érdemi ötletelés lenne a célja ennek az egésznek.

<details><summary><b>Leírás (Kattints ide!)</b></summary>
<p>
<h2>Téma hozzáadása</h1>
Ha valaki új témát akar felhozni a listára, akkor a következő sablon szerint kezdje a hozzászólást: Témát szeretnék hozzáadni:</b> Név, és rövid leírás mellé.
<br><br>Példa: <b>**Témát szeretnék hozzáadni: Probléma pomabottal.**</b> Nem megfelelően teljesít, túl lusta, túl kevés szöveget ír. Ez nem ér, jogunk van rá, hogy sokkal több választ kapjunk a pingre!

<br>Ha valaki ezt a sablont használja, akkor törlöm a téma-hozzáadós kommentjét és a téma felkerül a regisztrált témák közé.

<h2>Véleménykifejtés, javaslat, ötletek</h1>
Amikor egy témához szeretnél hozzászólni, használd a következő sablont:
<br><br>
<b>**Téma: <i>Téma neve</i>**</b><br>
Üzenet.
<hr>
</p>
</details>

📚 Eddig regisztrált témák:

1.  **Example topic**: _No description provided. (beküldő: poma123)_

**Comment by andris155** [comment]
Kérlek ezt más platformon old meg. A Facebook csoport lenne a legjobb. A GitHub nem igazán erre lett tervezve.
