### ISSUE TITLE
Skyblock OldGold láda

### ISSUE THREAD

**Issue by NBabi** [andris155/TheOld-Crafters#387]
A spawnon a a börtön (jail) bal oldalán lévő ládában nincs OldGold, de amikor kinyitom, akkor írja hogy "Jaj! Találtál egy kincset! :3"
![2017-01-06_20 39 48](https://cloud.githubusercontent.com/assets/22939109/21730583/a9c7023e-d450-11e6-8d47-3dc2c9785f02.png)

**Comment by andris155** [comment]
javítva
