### ISSUE TITLE
SkyBlock biome váltás

### ISSUE THREAD

**Issue by NBabi** [andris155/TheOld-Crafters#388]
A biome váltásnál nem írja hogy pénzbe kerül a leírásnál, és akkor sem írja ki, hogy levette az összeget amikor biomet váltunk, de 500$-t levon.

**Comment by NBabi** [comment]
Ez nem bug, csak inkább fel kellene tüntetni valahol, hogy egyértelmű legyen a játékosoknak.

**Comment by andris155** [comment]
Gondolom már javítottátok. :)
