### ISSUE TITLE
Skyblock nether kapu

### ISSUE THREAD

**Issue by NBabi** [andris155/TheOld-Crafters#389]
Amikor átmegyünk a nether kapun akkor átvisz a nether világba, DE ha ismét átmegyünk a kapun akkor egy flat world-be rak le.
![2017-01-06_21 07 00](https://cloud.githubusercontent.com/assets/22939109/21731355/4a3a7c20-d454-11e6-8b6f-3f9f3f1ccc18.png)

**Comment by NBabi** [comment]
ohh és a nether placc ahova érkezünk nincs levédve az építmény

**Comment by andris155** [comment]
javítva
