### ISSUE TITLE
Savsziget /rangok parancs

### ISSUE THREAD

**Issue by szofogado** [andris155/TheOld-Crafters#3914]
Savszigeten a rangok parancsban,  ha rá kattintasz az old rangra akkor a survivarra vehető linket adja ki, nem a savét.
Illetve bent van a prémium rang. Amit elvileg csak survin lehetne megvenni.
![2020-08-22_23 21 39](https://user-images.githubusercontent.com/52892955/90966056-7d038500-e4ce-11ea-8820-6f44c9ab36a9.png)
![2020-08-22_23 21 44](https://user-images.githubusercontent.com/52892955/90966057-7e34b200-e4ce-11ea-8e2c-15580d28e162.png)
![2020-08-22_23 21 52](https://user-images.githubusercontent.com/52892955/90966060-7ecd4880-e4ce-11ea-92c8-16e0facc75a7.png)

**Comment by poma123** [comment]
Kiszedtem, és most már nem fogja rámenteni a default configot.

**Comment by andris155** [comment]
Benne se volt amúgy a konfigban. :D

**Comment by poma123** [comment]
Pedig minden betöltéskor rámentette, az volt a baja

**Comment by nandorprohhackerkiller** [comment]
de mér pom

**Comment by nandorprohhackerkiller** [comment]
a
