### ISSUE TITLE
SkyBlock falusi bolt

### ISSUE THREAD

**Issue by NBabi** [andris155/TheOld-Crafters#393]
Bármely idéző tojás van a kézben, falusi boltnak érzékeli..
![2017-01-07_02 48 19](https://cloud.githubusercontent.com/assets/22939109/21738373/18e4a7ce-d484-11e6-991b-00c81da9c919.png)
![2017-01-07_02 49 44](https://cloud.githubusercontent.com/assets/22939109/21738374/1d26cf88-d484-11e6-80ad-e12e8259baf1.png)

**Comment by andris155** [comment]
Igen mert az 1.9-től nbt-ben tárolja, hogy melyik milyen mob, amit a plugin nem nagyon támogat. De ez nem hiba elvileg a többivel is lehet boltot (?)
