### ISSUE TITLE
skyblock ender portal

### ISSUE THREAD

**Issue by NBabi** [andris155/TheOld-Crafters#394]
Igazából a kép mindent elmond, nem működik a portál :)
![2017-01-07_06 37 00](https://cloud.githubusercontent.com/assets/22939109/21739729/ba9b4676-d4a3-11e6-91fc-b85f2f008ddc.png)

**Comment by Cerain** [comment]
Szia!
Szerverünkön nincs End, azért nem működik. :)

**Comment by andris155** [comment]
A portál csak akkor működik a szemekkel, ha generált. De úgy tudom skyblock szerveren nem szokás endet.

**Comment by NBabi** [comment]
Akkor feleslegesen van kirakva boltba az end portal, mert már több játékos is elkezdte venni, és hajnalba csak emiatt 84ezret kifarmoltam, mert 7ezer/db..... szóval ez így nem fair :S
