### ISSUE TITLE
Fejbolt -> új fejek

### ISSUE THREAD

**Issue by Wexthory** [andris155/TheOld-Crafters#398]
A warp fejboltos árak nagyon drágák ahoz képest, ahogy és amennyi pénzt lehet szerezni x időn belül. (11k/fej és a legjobb pénzszerzés 1 óra alatt kb 30k úgy, hogy nonstop dolgoznod kell és nincs levonva az ahoz kellő itemek ára.) Ha nem is levinni az árakat, de néhány új fej bekerülhetne, mert nagyon király kis díszítő item. Amennyiben van rá lehetőség és szükséges, összegyűjtöm a király fejek nevét.

**Comment by andris155** [comment]
Keresek majd még fejeket. :)

**Comment by andris155** [comment]
kész
