### ISSUE TITLE
Skyblock küldetés

### ISSUE THREAD

**Issue by NBabi** [andris155/TheOld-Crafters#400]
Rank: World Food
Hutspot küldetés
Amikor leadom a küldetés a Console küld nekem egy linket, ami egy wikipédia link magáról az ételről..... ez teljesen felesleges :DDDD javaslom a törlését :D 
A World Food rankon belül az összes küldetéshez küld ilyen linket a console, akos_-nak is küldött, amikor megcsinálta az Apfelstrudele küldetést.
![rg](https://cloud.githubusercontent.com/assets/22939109/21746990/38bb73e6-d558-11e6-90f8-0af1270b5776.png)

**Comment by andris155** [comment]
Jó lenne ez, csak magyarul. :D

**Comment by andris155** [comment]
Gondolom sikerült megoldani. :)
