### ISSUE TITLE
Skyblock Prémium prefix

### ISSUE THREAD

**Issue by dingdong2000** [andris155/TheOld-Crafters#401]
A tabon szürkével mutatja a "[Prémium]" rang prefixt.
![image](https://cloud.githubusercontent.com/assets/20629921/21749703/61466482-d5a4-11e6-92d9-ecf9ac8b75ea.png)
De a chatban más színnel, ugyaníg a /listben is.
![image](https://cloud.githubusercontent.com/assets/20629921/21749708/7a51e924-d5a4-11e6-9898-715f53d46941.png)
![image](https://cloud.githubusercontent.com/assets/20629921/21749710/81d1b2c4-d5a4-11e6-8719-09d742695dfc.png)

**Comment by Cerain** [comment]
Szia!
Amint tudom, javítom! Köszönöm!
