### ISSUE TITLE
Skyblock piac egy teljes káosz

### ISSUE THREAD

**Issue by Szikszai60** [andris155/TheOld-Crafters#402]
A piaci árszabás nincs egyensúlyozva, hasra ütés szerűen kitalált árak ezek. Ehhez nem kell mást hozzáfűzni, egy mostohagyerek lehetett a készítéskor, pedig fontos ha gazdaságra épül a szerver. Az OldGold értéke kb. megegyezik két stack kaktuszéval.
Több tárgy kétszer is szerepel, más árakkal, például: üllő, xp palack.
Hiányzik pár elem, például a beetroot, chorus fruit/flower. Küldetés sem épül rájuk (második oldal utolsó két sorához nem férek még hozzá)
Teljesen át kell dolgozni.

**Comment by dingdong2000** [comment]
#408

**Comment by Cerain** [comment]
Szia!
Javítva.
