### ISSUE TITLE
Skyblock EXP ital

### ISSUE THREAD

**Issue by dingdong2000** [andris155/TheOld-Crafters#404]
A spawnon az exp ital 16db/14.000$.
![image](https://cloud.githubusercontent.com/assets/20629921/21749872/81cd2354-d5a8-11e6-82e6-aff7653b814d.png)
De az enchantnál ugyanúgy a spawnon csak 1000$/6db.
![image](https://cloud.githubusercontent.com/assets/20629921/21749873/9a9e5088-d5a8-11e6-9eb1-ee963d3a603d.png)

**Comment by Szikszai60** [comment]
https://github.com/andris155/TheOld-Crafters/issues/402
