### ISSUE TITLE
Skyblock kiesés a szigetről

### ISSUE THREAD

**Issue by dingdong2000** [andris155/TheOld-Crafters#405]
Ha kiesel a szigetről/spawnról akkor a végtelenségig zuhansz /godban és csak a /spawn <név> segíthet rajtad. Erre van egy plugin akár [https://www.spigotmc.org/resources/voidspawn.19350/](url)

**Comment by andris155** [comment]
A plugin elég laggos, mert mindig nézi hol vagy.  A relog megoldja egyébként ezt a hibát persze közben meghalsz.
