### ISSUE TITLE
Survival - Kreatív tárgyak bugoltatása

### ISSUE THREAD

**Issue by CptEdvin** [andris155/TheOld-Crafters#411]
Kreatív módból könnyedén át lehet vinni tárgyakat survivalba.
Videó: **[** https://www.youtube.com/watch?v=Dsj_HUIBcpo **]**
Javaslom ezen tárgyak letiltását kreatív módban,+ a **csontport**,mivel könnyedén lehet fához jutni és az McMMO szintet fejleszteni.
Itt vannak azok a tárgyak,amik bugoltathatók:
![report](https://cloud.githubusercontent.com/assets/24990274/21803066/b6cae1aa-d728-11e6-9a95-c4e9aa70236b.jpg)

**Comment by andris155** [comment]
Már jelentett hiba viszont a listát köszönjük.

**Comment by Wexthory** [comment]
Az addolhato blockok egyike se er semmit a piaci arak alapjan, ezert szerintem nem lenyeges. A letiltasukkal meg megkevesebb ertelme lenne a kreativ rangnak. A csontporral valoban konnyen lehet fat noveszteni es mcmmo szintet novelni, de warp fatelep is van ahol egyebkent gyorsabb.

**Comment by andris155** [comment]
Nyilván máshogy lesz megoldva, ha lesz ötletem erre.
