### ISSUE TITLE
Survival - Új plugin (PlayerWarp)

### ISSUE THREAD

**Issue by CptEdvin** [andris155/TheOld-Crafters#412]
Azon gondolkoztam,hogy mivel többen is warpot kérnek az építményeikhez,ezért ez egy jó megoldás lehetne.Két verziót gondoltam át.

Ebből az egyik verzió az,hogy:
~**Csak a Staffok** tudnak pwarp-ot lerakni,közösen döntik el hogy melyik építmény érdemli meg azt,és ha mindenki rábólint,akkor megadják,ha pedig az ellenkezője,akkor persze nem adják meg.

A másik verzió,hogy:
~**A játékosok** tudnak lerakni maguknak pwarp-ot.
A [Tag]-nak lehetne rá **1** lehetősége,a [Tag+]-nak **2**,a [V.I.P]-nek szintén **2**,az [Elit]-nek **3**...és igazából így haladna felfelé.

Ezeket persze rendszeresen **ellenőrízniük** kell a staffoknak,hiszen nem szeretnénk hogy a parancs begépelése után egy **csapda**,**trágár üzenet**,illetve bármi ilyesmi fogadjon bennünket,de úgy gondolom hogy egy kis plusz munka sosem árt,akik pedig ilyeneket csinálnak,**a jog elvételével fizetnek érte**.

Ez akár **bolt** készítésénél is jó célt szolgál,ha valakinek nem tetszenek a pláza boltok,túl kicsinek érzik,stb.
Külön publikus **kolóniákat** lehetne vele létrehozni,saját magunk által épített **csodákat** megmutatni más játékosoknak anélkül,hogy teleport felkérést kellene küldenünk/elfogadnunk.

A "belső" dolgaihoz nem értek a pluginnak,azonban egy igazán jó tervnek tartom.

**Comment by dingdong2000** [comment]
![image](https://cloud.githubusercontent.com/assets/20629921/21853881/12198a2a-d819-11e6-8ced-9b1bbfec8259.png)
Ehh :'(

**Comment by andris155** [comment]
Mert tudtam, hogy bugos lesz, és 1 óra volt javítani.

**Comment by andris155** [comment]
De mind1 is. A lényeg, hogy bekerült Prémiumtól.
