### ISSUE TITLE
Pár hiba (pe) szervereken

### ISSUE THREAD

**Issue by DragleX** [andris155/TheOld-Crafters#416]
1. Hiba amit észrevettem az effektek nem látszanak a potionoknál és aranyalmánál.
2. Hiba amit eddig még csak SkyPvP-n vettem észre az íj nem működik, nem lövi ki a nyilat de levonja az inventoryból!

**Comment by DragleX** [comment]
A hibák mind három (pe) szervereken érvényesek.

**Comment by andris155** [comment]
pontosan hánykor vetted észre?

**Comment by DragleX** [comment]
Ahogy észrevettem írtam szóval az új szerver fájl okozhatja

**Comment by andris155** [comment]
A 2. javítva.

**Comment by andris155** [comment]
Sajnos ezt nem tudom javítani majd később biztosan javítják.
