### ISSUE TITLE
skyblock customec open bug

### ISSUE THREAD

**Issue by NBabi** [andris155/TheOld-Crafters#425]
Amikor beírom hogy /customec open, akkor nem a saját enderchestem nyitja meg, hanem akiét utoljára néztem, valamint ugyan ez van ha beírom hogy /customec open Babi, vagy bármilyen játékos név. ha a spawnon nyitom ki az enderchestet szintén ugyan ez a hiba.

**Comment by andris155** [comment]
/customenderchest:ec open név
ezzel se jó?

**Comment by NBabi** [comment]
erre a parancsra nem reagál a szerver :(

**Comment by andris155** [comment]
Nekem tökéletesen működött. Nem sikerült reprodukálni a hibát.

**Comment by andris155** [comment]
(A /customec open név paranccsal)
