### ISSUE TITLE
Mypet plugin kisebb hiba

### ISSUE THREAD

**Issue by taliga** [andris155/TheOld-Crafters#426]
Ha egy falusit befogok petnek, az elengedése után megváltozik a szakmája, legalábbis a leírásban.  A kereskedéssel kapható itemek az eredeti szakmájához tartoznak.

**Comment by taliga** [comment]
-Andromeda voltam

**Comment by andris155** [comment]
Arra gondolsz, hogy befogsz egy Farmert, és ha elengeded már nem Farmer lesz?

**Comment by taliga** [comment]
Ugyanolyan ruhája lesz és a kereskedési opciói is megmaradnak. De a szakmája megváltozik. Például Farmerként fogtad be és mondjuk fletcher lesz.

**Comment by andris155** [comment]
Ezt lefogom majd tesztelni.

**Comment by andris155** [comment]
Nem sikerült reprodukálnom.
