### ISSUE TITLE
Aukció kiírás hiba

### ISSUE THREAD

**Issue by otniel2001** [andris155/TheOld-Crafters#428]
![img_1504](https://cloud.githubusercontent.com/assets/24721229/22000243/66d803ce-dc3e-11e6-8b3d-187fb2bd09a5.JPG)

Kiírásban még mindig az van hogy az aukció házba tárgy kirakásnál 100$,-t levon. Pedig ez már megszűnt nem?

**Comment by andris155** [comment]
javítva
