### ISSUE TITLE
Végtelen szett

### ISSUE THREAD

**Issue by AwesomeFM** [andris155/TheOld-Crafters#430]
Ha egy páncélállványon van egy páncél (akár enchantos), és azt kreatívban leszedjük, majd egy másik páncélállványra rakjuk, akkor survivalos lesz, le lehet szedni, és tulajdonképp, végtelen szettet lehet így csinálni.

**Comment by andris155** [comment]
:(

**Comment by andris155** [comment]
Megváltozott az entity type neve, szerencsére csak ennyi volt a baja.
