### ISSUE TITLE
SkyBlock OldGold Farmolás

### ISSUE THREAD

**Issue by Denethor2** [andris155/TheOld-Crafters#433]
DarkMinionHUN felfedezte ,hogy ha a szigetet elkezdjük rgyik fajtába (nem tudom melyik fajta sziget) és lehet kapni 5 OldGold , ha újra kezdjük akkor is megkapjuk ,ha 5x újra kezdjük akkor 5x lehet kapni 5 OldGoldot .

**Comment by andris155** [comment]
Javítva
