### ISSUE TITLE
skyblock is restart

### ISSUE THREAD

**Issue by NBabi** [andris155/TheOld-Crafters#434]
egy játékos kb 10mp-nként lekérheti az oldcraft skyblock szigetet,amin oldgold van a chestben. ha azt az oldgoldot berakja az enderchestjébe,vagy egy barátjának odaadja,akkor készítheti is az új szigetét,amiből következik,hogy végtelen oldgoldja lehet az illetőnek.

**Comment by andris155** [comment]
https://github.com/andris155/TheOld-Crafters/issues/433

**Comment by andris155** [comment]
Javítva
