### ISSUE TITLE
Plázabolt hiba

### ISSUE THREAD

**Issue by asdlol911** [andris155/TheOld-Crafters#438]
Egy játékos (FunPVP05) jelentette, hogy vett egy üres plázaboltot a pláza warpon, berendezte, de amikor véletlen egy táblát rossz helyre tett és kiütötte, úgy adta be hogy "Ezt kreatívban létrehozta lemonizzle". 
Pedig végig néztem ahogy berendezi, amit a saját házából hozott barkácsasztalt az is átment kreatívba.

**Comment by andris155** [comment]
Sajnos ezzel nem tudok mit csinálni, valószínűleg ott maradt valahogy a blokk védés.
