### ISSUE TITLE
Keress jó pluginokat a szerverre(kre) OCD-ért! (PE-re is érvényes.)

### ISSUE THREAD

**Issue by andris155** [andris155/TheOld-Crafters#439]
Aki tényleg hasznos plugin neveket küld, amik nekünk is tetszenek, őt 50 OCD-vel jutalmazzuk! Több hasznos plugin küldés esetén akár több 100 OCD-t is lehet szerezni.

Ezeken az oldalakon lehet keresni:
https://www.spigotmc.org/resources/?order=download_count
https://dev.bukkit.org/bukkit-plugins?filter-game-version=&filter-sort=popularity
https://mods.curse.com/bukkit-plugins/minecraft
https://github.com/search?o=desc&q=bukkit+plugins&ref=searchresults&s=updated&type=Repositories&utf8=%E2%9C%93

Pocket Edition pluginok:
https://github.com/search?o=desc&q=pocketmine+plugins&s=updated&type=Repositories&utf8=%E2%9C%93

**Comment by Paxelcfg** [comment]
http://forums.pocketmine.net/plugins/chestshop.64/

**Comment by Paxelcfg** [comment]
https://www.spigotmc.org/resources/auctions.571/

**Comment by Paxelcfg** [comment]
https://dev.bukkit.org/projects/marriage-master

**Comment by pacica12342** [comment]
ttps://dev.bukkit.org/projects/slapper?gameCategorySlug=bukkit-plugins&projectID=49039

**Comment by pacica12342** [comment]
https://dev.bukkit.org/projects/slapper?gameCategorySlug=bukkit-plugins&projectID=49039

**Comment by pacica12342** [comment]
https://dev.bukkit.org/projects/clickwarp

**Comment by pacica12342** [comment]
https://dev.bukkit.org/projects/shopkeepers

**Comment by pacica12342** [comment]
https://dev.bukkit.org/projects/anticheatplus

**Comment by pacica12342** [comment]
https://dev.bukkit.org/projects/adminfun

**Comment by Linux1230** [comment]
https://www.spigotmc.org/resources/tntrun-recoded-bungee-multi-mode-leaderheads-mysql-scoreboard-api-much-more.7320/

**Comment by Linux1230** [comment]
https://www.spigotmc.org/resources/spawnershop.3005/

**Comment by Linux1230** [comment]
https://www.spigotmc.org/resources/toolstats.28374/

**Comment by killerhun** [comment]
file:///storage/emulated/0/Download/pluginok.zip itt vannak Pe pluginok. Ide kérem az ocd-t MineMarket: Szem

**Comment by UDPSendToFailed** [comment]
Multons nem tud regisztrálni: Omnom, Back Pack, Teams plugin

**Comment by gyzsombor6X** [comment]
MineMarket nevem: gyzsombor6X
StarGate pluginok: (fizetős pluginok)
https://www.spigotmc.org/resources/stargate-ultimate-teleporting-warping-solution.8956/
https://www.spigotmc.org/resources/stargate-bungee-ultimate-teleporting-warping-solution.18406/
Scoreboard:
https://www.spigotmc.org/resources/%E2%96%BA-animatedboard-%E2%97%84.13632/ (fizetős)
Ingyenes próbaverziója: https://www.spigotmc.org/resources/animatedboard-trial.26661/

Vanish plugin: https://www.spigotmc.org/resources/vanish-simple-pro.6197/ (ingyenes plugin)

**Comment by AtiPLS** [comment]
https://www.spigotmc.org/resources/single-player-sleep.20173/

**Comment by andris155** [comment]
Hozzáadtam honnan lehet keresni PE pluginokat, meg egy új PC pluginos oldalt is linkeltem.

**Comment by Crypthu** [comment]
S4-re 1vs1 plugin parancsal: https://github.com/DevGames/1vs1

**Comment by taliga** [comment]
https://mods.curse.com/bukkit-plugins/minecraft/slimefun
https://mods.curse.com/bukkit-plugins/minecraft/exotic-garden
https://mods.curse.com/bukkit-plugins/minecraft/slimefunores

A Csillagkapus pluginról meg csak annyit, hogy játszottam én olyan szerveren, ahol nagy bugokat okozott pl: nem folyt rendesen a víz.

**Comment by MrDinamit88** [comment]
https://www.spigotmc.org/resources/playerheads.15165/

Ez Jó lenne!

**Comment by andris155** [comment]
@Paxelcfg 
A chestshop nem működik sajnos PE-n, az Auctions helyett pedig van más PC-n. A 3. viszont nem rossz ötlet megadtam érte az OCD-t-

**Comment by andris155** [comment]
@pacica12342 A slapper amit küldtél nem működik. 
A clickwarpra parancsblokkot használunk. 
A shopkeepers bent van a szerveren. 
Cheat elleni pluginból van jobb már.
Az Adminfun ez nem rossz ötlet, ezért jár az OCD.

**Comment by andris155** [comment]
@Linux1230 köszönjük az ötleteket, 150 OCD-vel gazdagodtál.

**Comment by andris155** [comment]
@UDPSendToFailed köszönjük az ötleteket, 150 OCD-vel gazdagodtál.

**Comment by Crypthu** [comment]
https://yadi.sk/d/4_o5ln_D33xUZD Minecraft PE marry plugin !

Videó: https://youtu.be/UN_EQ-vuwSo

**Comment by Paxelcfg** [comment]
https://github.com/eddir/ChatShop
https://github.com/BoxOfDevs/MultiLanguage
https://github.com/GoldishKirby/AntiBan
https://github.com/IAmTheMinionBeast/ASimpleCar
https://github.com/AnthonyMuncherz/Factions
https://github.com/ZacHack/Alias
https://github.com/Syntaxious/PartyPE
https://github.com/SalmonGER/StatsPE
https://github.com/TheNewHEROBRINEX/WhatsMyIP
https://github.com/kenygamer/NoCaps
https://github.com/NapolGamer/Slapper
https://github.com/NL-4-DEVS/Pets
https://github.com/NPWorkShop/Teams
https://github.com/Falkirks/RankUp
https://github.com/NL-4-DEVS/PocketRPG

**Comment by Paxelcfg** [comment]
https://github.com/AbelGamerC/ItemName
https://github.com/flaxues/MultiServer
https://github.com/NightmareCybers/StaffList
https://github.com/NightmareCybers/ClansProV6.9

**Comment by Paxelcfg** [comment]
https://github.com/JellyBrick/CreditCards
https://github.com/Darunia18/mcpeMMO
https://github.com/Blubberboy333/Birthdays

**Comment by Paxelcfg** [comment]
https://github.com/MinecrafterJPN/ChestShop
https://github.com/Black-Edge-Project/TeamPVP

**Comment by andris155** [comment]
@gyzsombor6X Jelenleg nem igazán van pénzünk fizetős pluginokra. A csillagkapusnak egyébként sok értelmét nem látom, persze jól néz ki, de haszna nem sok van, ha ingyenes lenne akkor mondjuk már egyből más szemmel nézném, de így fizetősként én többet várnék ettől a plugintól.
Scoreboard lesz bár nem azzal a pluginnal, szintúgy ingyenessel ami ugyan azt tudja vagy még többet is.
A vanishra már lehet jó lenne az Essentials is ha nem akkor ez jó ötlet. 50 OCD-t adok ezért. köszönjük

**Comment by andris155** [comment]
@Crypthu Sajnos oroszul nem tudok.

**Comment by andris155** [comment]
@Crypthu Az 1vs1 hm átgondolandó. Az OCD jár érte.

**Comment by andris155** [comment]
@taliga igen ezek tényleg jók, ezek nagy eséllyel lehet be is kerülnek. Az OCD-t milyen névre adjam?

**Comment by andris155** [comment]
@MrDinamit88 Ilyet tud az Essentials is. Mivel fejet lehet vele adolni csak staff fér hozzá.

**Comment by Paxelcfg** [comment]
https://github.com/R4KT/AuctionHouse

**Comment by Linux1230** [comment]
Szerintem ez se lenne rossz: https://www.spigotmc.org/resources/silkspawners-%E2%98%85-1-11-2-ready-%E2%98%85-1-million-downloads-%E2%98%85.7811/

Ha a spawnershop alternatíva lehet.

**Comment by Linux1230** [comment]
Ezzel lehetne motiválni a playereket :D
https://www.spigotmc.org/resources/advanced-achievements.6239/

**Comment by Linux1230** [comment]
Ez pedig annak lenne jó aki nem ismeri igazán a recepteket(illetve hasonlít a PE craft rendszeréhez):

https://www.spigotmc.org/resources/fastcraft.20544/

**Comment by lajosgames** [comment]
PaintBall!

**Comment by lajosgames** [comment]
https://www.spigotmc.org/resources/staffdisplay.35166/

**Comment by Paxelcfg** [comment]
https://dev.bukkit.org/projects/easy-staff-chat
https://dev.bukkit.org/projects/inventorysql
https://dev.bukkit.org/projects/kettjoey

**Comment by Paxelcfg** [comment]
https://dev.bukkit.org/projects/multilanguage

**Comment by andris155** [comment]
@Paxelcfg adtam 400 OCD-t kb. annyi volt belőle jó ötlet.

**Comment by andris155** [comment]
@Linux1230 A silkspawnert írtam, de azzal az a gond, hogy a hackerek visszaélnének ezzel. Az Advancedet ismerem ez elég laggos szóval ez nem lesz. A fastcraftot átgondolom azért jár az OCD.

**Comment by andris155** [comment]
@lajosgames nincs minigames szerverünk, a 2. egész jó. Megadtam az OCD-t.

**Comment by Paxelcfg** [comment]
https://github.com/luca28pet/AdvancedKits <--- kitbe encsis cucc :$
https://github.com/MWMotors/Car <--- Autó *-*
https://github.com/spandan8055/mech <--- MECH :D 
https://github.com/Corsad/Aution <---Aukcio *-*
https://github.com/mathCodingClub/lotto <---Lotto

**Comment by Paxelcfg** [comment]
https://github.com/Muirfield/KillRate <---s4-5 :d

**Comment by Paxelcfg** [comment]
https://github.com/Phoenix616/RandomTeleport

**Comment by UDPSendToFailed** [comment]
Plugin xray ellen: https://www.spigotmc.org/resources/orebfuscator.22818/

**Comment by Linux1230** [comment]
Ez esetleg jó lenne eventnek:

https://www.spigotmc.org/resources/bedwars-rel.6799/

**Comment by Nighzt** [comment]
https://github.com/kenygamer/ServerRules

**Comment by Nighzt** [comment]
https://github.com/kenygamer/ServerRules

**Comment by Nighzt** [comment]
Nem ezt akkartam

**Comment by Nighzt** [comment]
.-.

**Comment by Nighzt** [comment]
https://github.com/fengberd/FHiddenMine

**Comment by lajosgames** [comment]
Kösziii ;)

2017. jan. 22. 20:01 ezt írta ("Marczinkó András" <notifications@github.com

**Comment by Nighzt** [comment]
https://github.com/Yupai/NoDrops

**Comment by Nighzt** [comment]
https://github.com/XFuryMCPE/HeadOnDeath

**Comment by Nighzt** [comment]
https://github.com/MinecrafterPH/KillEffect

https://github.com/MinecrafterPH/FloatingText

**Comment by Nighzt** [comment]
https://github.com/MinecrafterPH/FloatingText
:D

**Comment by Nighzt** [comment]
https://github.com/linuzo/BloodFX

**Comment by Paxelcfg** [comment]
https://github.com/609176445/ptimer

**Comment by andris155** [comment]
@Paxelcfg a kitest már írtad.
Az autós autó összeszerzéshez van ahogy láttam, nem pedig pluginra. xd
A mech egy weboldal.
Az aukció pedig nem a PE-re van.
A lottó pedig nincs kész.
De köszönjük a pluginokat.

**Comment by andris155** [comment]
@Paxelcfg a killrate egyelőre értelmetlen még nincs scoreboard.
A randomteleport meg sajnos nem PE-re van,

**Comment by andris155** [comment]
@UDPSendToFailed  az x-rays átgondolandó.

**Comment by andris155** [comment]
@Nighzt köszönjük a pluginokat adtam 150 ocd-t érte.

**Comment by andris155** [comment]
@Paxelcfg a ptime az essentialsban is benne van.
