### ISSUE TITLE
SkyBlock: Challenge hiba

### ISSUE THREAD

**Issue by Icecroft** [andris155/TheOld-Crafters#440]
A SkyBlockon megújultak a küldetések egy kicsit. Van egy új küldetés, a "Beaconator", aminek egyik előfeltétele a "Wither Hunter". A régi listában valóban volt ilyen küldetés, de most a megújultban nem lehet ilyet látni, tehát a "Beaconator" és a rákövetkező küldi teljesítése lehetetlen.

**Comment by andris155** [comment]
Ha jól értelmeztem bármelyik küldetést lehet csinálni ebben az új küldetés rendszerben azokból, amik vannak. (?)

**Comment by Icecroft** [comment]
Andris, félre értettél kicsit:
A lenti screenshoton látható a challenge listám, ahol van a Beaconator küldetés, ami lockolva van, mert 2 küldetést kell előtte teljesíteni: az egyik a "wither hunter", amit nemigazán tudok teljesíteni, mert nincs ilyen küldetés a listában. (a küldetés plugin update-je előtt kb 2 hete még volt ilyen küldi, de már nincs)
![2017-01-24_17 36 33](https://cloud.githubusercontent.com/assets/19332825/22256972/ac61eba2-e25c-11e6-8a72-6be411bfb32a.png)

**Comment by andris155** [comment]
új szigetnél nincs ilyen hiba elvileg, és a konfigban elvileg megvan a küldetés.

**Comment by andris155** [comment]
Sajnos nem tudom javítani

**Comment by Icecroft** [comment]
Andris, tegnap megtaláltam a megoldást: a "Wither Hunter" előfeltétele a "Nether fortress" küldetés, ami a screenshoton alvilági kerítéssel van jelezve. Ha azt teljesítem, akkor az átváltozik a "Wither Hunter" küldetéssé, az alvilági kerítés pedig sötét koponyává. Tehát a "Wither Hunter" küldinek nincs külön helye.

**Comment by andris155** [comment]
Szuper ennek örülök. :)
Sajnos erről én sem tudtam.
