### ISSUE TITLE
SkyBlock Suicide

### ISSUE THREAD

**Issue by JohnnyMaorr** [andris155/TheOld-Crafters#442]
Egy olyan ötletem lenne, hogy aki VIP, vagy magasabb rangú, annak lehetne egy olyan parancs, hogy pl.: /vipsuicide

Mert ha /god-al le esel a szigetről, akkor zuhansz a végtelenségbe. És ha /suicide-al ölöd meg magad, akkor el veszíted minden cuccodat.  És szerintem, akik emiatt vettek rangot , azok azért vették, mert nem akarnak mindenbe belehalni, szintet, és itemeket veszíteni. Így azok /vipsuicide-al megölhetik magukat, és nem veszítenek el semmit.

Üdv! :)

**Comment by andris155** [comment]
Az a baj, hogy nem tudok ilyen plugint, de írni mondjuk lehetne. Csak nem értek ilyen szinten a java programozáshoz jelenleg.

**Comment by andris155** [comment]
Te tudsz valami ilyesmi plugint?

**Comment by JohnnyMaorr** [comment]
Hát én sem értek hozzá, de találtam egy ilyet, hátha segít. :)

https://www.spigotmc.org/resources/keepinventory.1638/

**Comment by Icecroft** [comment]
Én épp ma estem le ilyen módon, de nem akartam elveszteni a dolgaimat: a fontosabbakat zuhanás közben felraktam az aukciós házba, a többit pedig /trade -el átadtam egy másik játékosnak. Ezek után kiléptem god-ból, újra spawn és vissza minden holmi. Tehát megkerülhető a dolog, amíg nincs jobb.

**Comment by andris155** [comment]
Elit rangtól elérhető.
Köszönjük az ötletet!
