### ISSUE TITLE
Zone levédés furcsaság

### ISSUE THREAD

**Issue by taliga** [andris155/TheOld-Crafters#444]
A Zone flagek érdekesen működnek.
Hogyha engedélyezel egyet, akkor mindenkinek engedélyezve lesz, ha tag, ha nem tag. Ha tiltva van, mindenkinek tiltva lesz még az Owner-nek is. Egyik beállításnak sincsen semmi értelme.
Egy példa: az interact-ot letiltod, akkor senki nem tud ládát kinyitni, még az owner sem. Ha engedélyezed, akkor meg aki nem tag, az is. Egyiket sem használná az ember soha.
Ami megoldás lehet, mondjuk, ha az ownerre legalább nem vonatkoznának a flagek, így lenne értelme letiltani bizonyos flageket. Vagy ha külön csoportokra/emberekre lehetne flageket beállítani(nem tudom lehetséges-e ezzel a pluginnal).
A másik, hogy nagyon hasznos lenne a flagek resetelése, amire van parancs, csak nincs rá jogunk. Mivel a legtöbbnél csak az alap nem definiált flag a jó.

**Comment by taliga** [comment]
-Andromeda voltam

**Comment by andris155** [comment]
Alapból mindent véd, és nem is kell flagot állítani jobb esetben. A flag törlés az 1.1-es verzióban lesz majd benne.

**Comment by andris155** [comment]
/zone zóna flag none azt hiszem beraktam az 1.1-est
