### ISSUE TITLE
SG hibák

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#446]
- A szavazás nem működik, üres a láda.
- #441 -re a megoldás: SG világban tiltani a mcmmo-t, így event-en se szereznének ezzel a playerek előnyt, pl falldown + lvl1000 akrobatika, stb.
- /m és /r parancsok engedélyezése.
- Egy helyen nincs lefordítva a szöveg:

![2017-01-23_17 10 36](https://cloud.githubusercontent.com/assets/16057404/22211998/525324e6-e18f-11e6-8a6f-8f29170c6f04.png)

**Comment by andris155** [comment]
Nem találtam lehetőséget, amivel világonként tiltható lenne az mcmmo

**Comment by andris155** [comment]
Nincs benne az a sor a fordításban.

**Comment by andris155** [comment]
Beleírtam a /r, és /m parancsot, majd holnap tölt be.

**Comment by andris155** [comment]
most jó a szavazás?

**Comment by andris155** [comment]
javítva mind 2 Old Diamond a jutalmad
