### ISSUE TITLE
Survival Szerver

### ISSUE THREAD

**Issue by poprundelHD** [andris155/TheOld-Crafters#448]
Egy "Database" nevű player elkérte a csákányom,úgy kb. 10 percre. Mikor visszaadta,éppen váltottam volna Survival módra, hirtelen KREATÍVBAN felszedődött a Survivalos csákányom. Ez most egy bug akar lenni? :D Mindenesetre szeretnék segítséget kapni,hogy a Kreatív módban lévő csákányomat,visszakapjam Survival módra.

**Comment by andris155** [comment]
Elvileg ez lehetetlen.
