### ISSUE TITLE
Több embert is ledobott S1-ről a "Valaki már játszik ezzel a névvel!" indokkal.

### ISSUE THREAD

**Issue by Kronox12** [andris155/TheOld-Crafters#45]
Továbbá TAB-on sokaknak gyenge a jele,akiknek meg nagyon kevés,azok egy idő után lecsatlakozódnak.
Ez mind a Lobby betétele után történt.

**Comment by Kronox12** [comment]
Úgy látszik javult a helyzet,már nem csinálja ezt.

**Comment by andris155** [comment]
Lehet valami host net hiba volt.
