### ISSUE TITLE
Kreás cuccokat fel lehet szedni

### ISSUE THREAD

**Issue by otniel2001** [andris155/TheOld-Crafters#450]
![image](https://cloud.githubusercontent.com/assets/24721229/22261187/41e12f1c-e26c-11e6-86c7-38e1a24b8e1a.jpg)

Fel lehet szedni a kreatívos cuccokat és még ha kézzel ütöm is ki őket akkor is megkapom. Vagy kreában létrehozott tárgyként, vagy rendesen lerakható normális tárgyként. A tárgyak amik "Ezt kreatívban létrehozta xyz" felirattal rendelkeznek, nem tudom őket kidobni. Max inv törléssel.

**Comment by andris155** [comment]
Valami leírás, hogy ezt hogy sikerült?

**Comment by otniel2001** [comment]
Kerestem falukat. Amik érintetlenek. És làttam pár redstones cuccot. Gondoltam megnézem mi az. És hát látom hogy csak egymás mellett van sok redstone es semmi értelme, megnéztem le van-e védve. Nem volt és ezeket dobta amik képen is vannak. Volt olyan kreás redstone amit nem engedett felszedni de volt amit igen csak oda írta hogy kreás és nem tudom kidobni invből. Ugyan ez a többi redstone cuccal (rs fákja, jel erősítő).

**Comment by otniel2001** [comment]
A redstone fákja és a jel erősítő alá nem írta oda hogy kreás. De gondolom az mivel hogy egymás mellett voltak.

**Comment by andris155** [comment]
Elvileg javítva!
Köszönjük a hibajelentést!
