### ISSUE TITLE
Stats plugin fejlesztése a SkyBlock szerverhez

### ISSUE THREAD

**Issue by Denethor2** [andris155/TheOld-Crafters#452]
Szeretném megkérdezni ,hogy a SkyBlock szerverre nem szeretnéd berakni a /stats parancsot ,hogy tudjuk használni? :)

**Comment by andris155** [comment]
és miket írjon ki?

**Comment by Denethor2** [comment]
Pl: mennyi az összes idő amit játszott a szerveren. Mikor csatlakozott elöször a szerverre. Hasonló a Survivalé-hoz.

**Comment by andris155** [comment]
Inkább a blokkokra gondoltam, nyilván oda semmi értelme nem lenne az  ércnek azok helyett kellene más.

**Comment by andris155** [comment]
?

**Comment by Denethor2** [comment]
Netherrack, cobblestone quartz pl?

**Comment by andris155** [comment]
kész
![kepkivagas](https://cloud.githubusercontent.com/assets/8324198/22404013/6b448c1e-e627-11e6-86a9-e6a7b7e37fe4.PNG)

**Comment by Denethor2** [comment]
Kőszi. :3
