### ISSUE TITLE
Skyblock

### ISSUE THREAD

**Issue by Rand00m99** [andris155/TheOld-Crafters#454]
A szigetemen nincs jogom trapdoor-t használni. 
![2017-01-24_21 07 50](https://cloud.githubusercontent.com/assets/25331495/22265146/02e4fbae-e27b-11e6-868e-3ef4e57e2c7d.png)

**Comment by Icecroft** [comment]
Nekem ugyanez a problémám, van 7 trapdoorom és mindegyik ugyanezt a hibát produkálja, de csak a mai naptól, korábban működtek.

**Comment by andris155** [comment]
Fail xd

**Comment by andris155** [comment]
Javítva!
Köszönjük a hibajelentést!
