### ISSUE TITLE
Auction House kisebb hibák

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#455]
Elírás:

![2017-01-25_12 20 44](https://cloud.githubusercontent.com/assets/16057404/22288792/c245d748-e2f8-11e6-9211-f63624ed6a0f.png)

Angol szöveg:

![2017-01-25_12 20 48](https://cloud.githubusercontent.com/assets/16057404/22288791/c2424466-e2f8-11e6-82d8-c693b1ba1693.png)

**Comment by andris155** [comment]
Javítva!
Köszönjük a hibajelentést!
