### ISSUE TITLE
Beváltó probléma - Rossz itemre való csere

### ISSUE THREAD

**Issue by Ziredus** [andris155/TheOld-Crafters#4553]
Survival (maybe sav idk)
A /warp beváltónál már lehet cserélni az automated crafting chambereket az új verzió VANILLA crafterére, pedig alapvetően az SF-es verziójára kellene hogy lehessen cserélni.

**Comment by andris155** [comment]
@MrZero1

**Comment by MrZero1** [comment]
De akkor mit kellene mire beváltani?
