### ISSUE TITLE
Szamár és a kreatív

### ISSUE THREAD

**Issue by asdlol911** [andris155/TheOld-Crafters#457]
Kreatív módban meg lehet nyitni a szamár/öszvér invjét és lehet rá tenni kreatívos nyerget
![2017-01-26_18 14 19](https://cloud.githubusercontent.com/assets/17855326/22342074/6a155c0a-e3f3-11e6-9e5f-49cf4744d93f.png)
![2017-01-26_18 14 24](https://cloud.githubusercontent.com/assets/17855326/22342075/6a177cec-e3f3-11e6-9e6c-e2b94653d0bf.png)

**Comment by asdlol911** [comment]
Ráadásul, a rá helyezett ládába is lehet kreás tárgyat tenni.
![2017-01-26_18 16 29](https://cloud.githubusercontent.com/assets/17855326/22342140/9a7c1e60-e3f3-11e6-9904-1855a0dfa330.png)

**Comment by andris155** [comment]
Javítva!
Köszönjük a hibajelentést!
