### ISSUE TITLE
SkyBlock Island Group

### ISSUE THREAD

**Issue by JohnnyMaorr** [andris155/TheOld-Crafters#459]
Nem lehet jogokat adni, mert nem a jó player beállításait hozza be.

Bizonyíték: 
https://i.gyazo.com/0f63ee96bf1f29badd98adac2f396235.gif

Üdv! :D

**Comment by andris155** [comment]
parancs nincs erre?

**Comment by JohnnyMaorr** [comment]
Én nem találtam, mindegyik az "inventorys" kinézetet hozza be.

**Comment by andris155** [comment]
Szerintem ez még nincs kész a pluginban.
