### ISSUE TITLE
Pláza bérlés limit fordítási hiba - Neurofizis 

### ISSUE THREAD

**Issue by Neurofizis** [andris155/TheOld-Crafters#469]
Egy fordídási,tartalombeli hibát kaptam
Amikor bérelni szeretnél egy 3. plázát ugye nem engedi,mert 2 lehet csak
és azt irja,hogy "Nem adhatsz bérbe több ..."

Javaslat : Nem vehetsz bérbe több..

**Comment by Neurofizis** [comment]
Neurofizis

**Comment by andris155** [comment]
Javítva!
Köszönjük a hibajelentést!
