### ISSUE TITLE
Elveszett a Szigetem!!

### ISSUE THREAD

**Issue by poma123** [andris155/TheOld-Crafters#471]
Kedves Andris155!

Az imént felmentem a SkyBlock szerverre és rendesen a szigetemre spawn-olt. De nem engedett semmit felvenni ha ledobtam pl. a csákányomat, és ha beírtam hogy /is h akkor azt mondta nincsen szigetem... Aztán kiléptem a játékból (gondolva hátha csak egy ritka bug lehetett és újrainditáskor megjavul...), és újraindítottam. Ugyan ez... És amikor beirtam hogy /is akkor az a megszokott menü jött ki amikor valaki most van először a szerveren,. Gondoltam ha rányomok az új szigetre akkor sikerül ezt a bugot ellehetetleníteni....Nem ez történt.. Bejött egy új sziget és azóta is az van.... Próbáltam a gépemen lévő minecraft log-ból kiszedni a régi szigetem koordinátáit de nem jártam sikerrel. Kérlek ha neked van bármilyen log fájl a szerverről akkor kérlek keresd meg és próbálj meg segíteni rajtam :)
Üdv, poma123

**Comment by poma123** [comment]
Nagyon fontos lenne :|

**Comment by andris155** [comment]
A régi szigetet törli tudtommal sajnos. :(

**Comment by MrZero1** [comment]
:(
