### ISSUE TITLE
Skyblock és a god

### ISSUE THREAD

**Issue by asdlol911** [andris155/TheOld-Crafters#472]
Sziget építés közben (gondolom elértem az építés határát) leestem a szigetről (god on persze) és nem haltam meg, csak ácsorogtam a semmiben. Próbáltam vissza portolni, de a teleportot azonnal kinyomta. Külön fel kellett hívni Babi-t, hogy vissza portoljon biztonságos helyre (/warp szabályzat).

**Comment by andris155** [comment]
https://github.com/andris155/TheOld-Crafters/issues/470
