### ISSUE TITLE
Addolás

### ISSUE THREAD

**Issue by AwesomeFM** [andris155/TheOld-Crafters#473]
Ugyebár, ha pistonnal kreatívos blockot próbálunk kitolni, nem megy. Viszont ez fordított esetben, vagyis, ha a kreatívos blockot visszahúzni szeretnénk, az megy, ergo survivalban ki tudjuk ütni gond nélkül, és lehet addolni.

**Comment by andris155** [comment]
Ez mikor volt tesztelve?

**Comment by andris155** [comment]
Tegnap javítottam már.
