### ISSUE TITLE
EndDragon Bug

### ISSUE THREAD

**Issue by Neurofizis** [andris155/TheOld-Crafters#475]
Ma reggel megöltem az End sárkányt kétszer.A másodikszor nem kaptam se expet se droppot semmit.Rögtön ekkor lépett be Zalcsi_MC és csodálkozva irta chatbe,hogy honnan van 19 szintje és 1 Sárkánytojása.A hiba egyértelmű - elbugol a drop máshoz.

**Comment by andris155** [comment]
MegaWatt szerint dob tojást, de a legtöbbször a portálba esik az xp szinttel együtt, ami meg kitörli, vagy nem tudom mit csinál vele.

**Comment by andris155** [comment]
Azt mondja bed nélkül ha átmész az endbe ott lesz a tojás, sőt volt hogy 4 tojást is szerzett így, mert más nem ment el érte.
