### ISSUE TITLE
Horgászbug

### ISSUE THREAD

**Issue by Neurofizis** [andris155/TheOld-Crafters#477]
Bármilyen Halászbottal  mobokra való dobálással fejlődik az mcmmo horgászat képesség.

**Comment by asdlol911** [comment]
Mert az McMMo horgász képességnek az egyik használható képessége az, hogy mobról tudsz lerázni tárgyakat. Ez a horgászbot drasztikus romlását eredményezi, de ezzel több zsákmányt tudsz szerezni az adott mobból. Ez is fejleszti a horgászat képességet.

**Comment by Neurofizis** [comment]
Elfogadom.
