### ISSUE TITLE
Buff-Debuff bug

### ISSUE THREAD

**Issue by Neurofizis** [andris155/TheOld-Crafters#478]
A vízalatti kastélyokban a mobok adnak Lassúság Debuffot,ezt Siestég-el (haste) lehetne orvosolni.A szerveren a mozgás ugyan felgyorsul,de a blokk kiütése ugyan olyan nagyon lassú.

**Comment by asdlol911** [comment]
A mobok a kastélyban bányászfáradtság debuffot adnak, a sietség pedig a mozgási sebességet növeli. Lehet bugnak néz ki, de nem az. :/

**Comment by Neurofizis** [comment]
asdlol911 Tévedsz,mert nem a cukorból kraftolt potirol beszélek,hanem az MCMMO-s répából kraftolható HASTE Potion,ami bányászat,kardütés,favágás stb SEBESSÉGET ad,tehát bug

**Comment by Andromeda11** [comment]
Bár még nem láttam ilyen haste potit, de szerintem a vizi erődben a boss által adott debuff  magasabb szintű, mint a haste amit kapsz. Tehát persze, hogy ugyanolyan lassú.

**Comment by andris155** [comment]
Nem tudtam értelmezni a hibát.
