### ISSUE TITLE
MineMarket

### ISSUE THREAD

**Issue by NBabi** [andris155/TheOld-Crafters#479]
Szerintem ezt vegyük ki inkább, sem esztétikailag nem néz ki jól, meg ha nem működik akkor felesleges bele írni!
![rdfg](https://cloud.githubusercontent.com/assets/22939109/22551873/e66368b6-e956-11e6-8994-1bc94f661873.jpg)

**Comment by andris155** [comment]
De bármikor javíthatja a fejlesztő.
