### ISSUE TITLE
skyblock limitek [Kérés]

### ISSUE THREAD

**Issue by NBabi** [andris155/TheOld-Crafters#481]
./is limits növelés
ANIMAL (max. 48) -> lehetne max. 60 (a küldetések miatt, mert valamelyikhez éppen hogy kijön, és hogy ne kelljen megölnie más állatot küldetés miatt a játékosnak)
MONSTER (max. 50) -> maradhat max. 50
VILLAGER (max. 35) -> lmaradhat max. 35
GOLEM (max. 7) -> lehetne max. 10 (mert a vasgólem és a hóember is ide tartozik)

**Comment by andris155** [comment]
sikerült beállítanom?

**Comment by NBabi** [comment]
igen, köszönöm szépen :)
