### ISSUE TITLE
Tervezett pluginok

### ISSUE THREAD

**Issue by CptEdvin** [andris155/TheOld-Crafters#482]
Report, x-ray védelem, Vanish, SlimeFun, SlimeFun extrák

**Comment by andris155** [comment]
https://mods.curse.com/bukkit-plugins/minecraft/slimefun
https://mods.curse.com/bukkit-plugins/minecraft/exotic-garden
https://mods.curse.com/bukkit-plugins/minecraft/slimefunores

**Comment by andris155** [comment]
Az x-ray védelem az i5-t is kiakasztotta, szerintem felejtős, mivel nagyon fps laggos, hiába bírja el a szerver bőven.

**Comment by andris155** [comment]
SlimeFun + extrák berakva.

**Comment by andris155** [comment]
vanish berakva

**Comment by andris155** [comment]
A report nem került be.
