### ISSUE TITLE
Buff-Debuff bug 2.

### ISSUE THREAD

**Issue by Neurofizis** [andris155/TheOld-Crafters#485]
Újra leírom,talán érthetőbben a hibát.

Két ellentétes hatásról van szó.Ha az egyik hatásra megiszod az ellentétes hatást,akkor az utóbbi fog fentmaradni rajtad.

Az Mcmmo alchemynek köszönhetően 125ös szintű képességtől lehet craftolni ezt a két potit.A szerveren jelenleg 5 ember képes rá,ezért nem is láthattátok,nem is kaphattatok bejelentést róla.

A víz alatti kastélyokban a mobok ugyan azt a debuff-ot adják,mint a poti amit lehet főzni tehát semmivel sem rangosabb a hatása mint a potié - ahogy Andromeda11 írta. "Bár még nem láttam ilyen haste potit, de szerintem a vizi erődben a boss által adott debuff magasabb szintű, mint a haste amit kapsz. Tehát persze, hogy ugyanolyan lassú."

Andris ha nem tudod értelmezni,elmagyarázom a játékban.

![gyok](https://cloud.githubusercontent.com/assets/25463405/22592324/e2d6aade-ea21-11e6-9cd5-ecace176483e.jpg)

**Comment by andris155** [comment]
De mi itt a bug?

**Comment by Neurofizis** [comment]
Az,hogy a karakter mozgása ugyan felgyorsul ,a kezével gyorsabban üt de a valós blokkiütődés ugyan olyan lassú marad,tehát a hatás fele él,a másik nem jött létre
