### ISSUE TITLE
a siklószárny

### ISSUE THREAD

**Issue by jokoboy** [andris155/TheOld-Crafters#489]
Ha a siklószárnyal elkezdek repülni egy 3másodpercenként visszadob egy blockot és teljesen megállok majd elindulok. Szerintem nem a netemmel van  a baj mert haveromnak is ezt csinálja.

                                                                                  Doge

**Comment by andris155** [comment]
PE?

**Comment by andris155** [comment]
fly-al, vagy anélkül működik.
