### ISSUE TITLE
Nem főzhető bájitalos nyíl

### ISSUE THREAD

**Issue by Neurofizis** [andris155/TheOld-Crafters#491]
Eltévedt felirat

![2017-02-04_14 20 55](https://cloud.githubusercontent.com/assets/25463405/22618459/5a1484fe-eae5-11e6-94bf-2d2660457553.png)

**Comment by andris155** [comment]
Ezt nem is értem itt mi a hiba?

**Comment by Neurofizis** [comment]
A neve..

**Comment by andris155** [comment]
Nem tudtam reprodukálni.
