### ISSUE TITLE
Slimefun láthatatlan bug

### ISSUE THREAD

**Issue by Andromeda11** [andris155/TheOld-Crafters#492]
Leraktunk egy új növényt, kiütöttük és azóta néha az egyikünk láthatatlan. PiciViziPaci kilépett, de a karaktere ottmaradt a kilépés helyén. Miután visszalépett vagy nem láttam (csak a kilépett korábbi karakterét) vagy kettő volt belőle. 
![2017-02-04_18 23 59](https://cloud.githubusercontent.com/assets/25138776/22620243/ad49192e-eb07-11e6-80c2-2b79c517e08b.png)

**Comment by Andromeda11** [comment]
mindjárt lesz videó is

**Comment by PiciVizipaci** [comment]
A nem mindennapi anomáliáról készült titkos felvétel:
https://www.youtube.com/watch?v=BSwQsjCyx1w&feature=youtu.be

**Comment by GhostTriggerGT** [comment]
Dettó ![2017-02-06_12 47 48](https://cloud.githubusercontent.com/assets/25180705/22646066/b5ee740c-ec6a-11e6-95a6-442490d5092c.png)

**Comment by andris155** [comment]
és mitől lesz ilyen?

**Comment by Andromeda11** [comment]
Először azt hittük, hogy egy slimefunos bokor kiütésétől, de azóta az egyik fejlettebb gép használatánál is előjött. Fogalmam sincs őszintén.

**Comment by Linux1230** [comment]
Ma nekem benvednél jött kiütöttem a bio generátorom és azután benvedet sem láttam, illetve ez eldobott dolgokat sem. Relog után megjavult, majd megint kiütöttem teszt jelleggel de akkor nem volt ez a jelenség.

**Comment by andris155** [comment]
Próbáljatok meg ide írni, persze angolul: https://github.com/TheBusyBiscuit/Slimefun4/issues
A plugin verziók a legújabbak. A szerverfájl git-Paper-1056.
CS-CoreLib Version: 1.5.13
Slimefun Version: 4.1.2
