### ISSUE TITLE
Amikor a multi tool grappling hood módját használom levédet helyen akkor amint az nyíl a falba csapódig egyből adegy lasszót   SFSurvival  Találkoztam vele       

### ISSUE THREAD

**Issue by Sztv23** [andris155/TheOld-Crafters#4975]
**Szerver**:

*Út a hibához:*

> *Dátum és idő:*

**Comment by skrisz0101** [comment]
Nagyon régi hiba, nem nagyon lehet mit kezdeni ezzel

**Comment by MrZero1** [comment]
Köszönjük a hibajelentést, ahogy Skrisz írta, tudunk a hibáról, sajnos nem tudunk mit csinálni vele. A shopban éppen ezért nem lehet eladni a lasszót, csak venni. Lezárom a bejelentést.
