### ISSUE TITLE
Ob - nem fagy mindenhol a víz

### ISSUE THREAD

**Issue by skrisz0101** [andris155/TheOld-Crafters#4976]
Skilljoy szerint csak ott fagy be a víz, ahol esik a hó. A hó esés viszont ilyen random.
Nem tudom mit lehetne ezzel kezdeni, a nem befagyott víz felett sincs semmi blokk.
jóideje ilyen már a hely.
![2023-01-26_16 09 46](https://user-images.githubusercontent.com/29951969/214873124-a38be95b-0a6d-4155-8892-584193b3064b.png)

**Comment by MrZero1** [comment]
A biome paranccsal lehet állítani, hogy chunkonként milyen biom legyen. Ha valahol nincs havas biom, nem fog esni a hó ott.

**Comment by skrisz0101** [comment]
mindenhol jeges óceán a biom

**Comment by MrZero1** [comment]
Fejlesztővel egyeztetve, nem tudja megmondani, mi lehet az oka. Én sem sajna. 😞
