### ISSUE TITLE
Terméketlen föld

### ISSUE THREAD

**Issue by Ziredus** [andris155/TheOld-Crafters#4980]
SF survival

SF survivalon a /bolt boltba a blockok közé be kellene tenni a terméketlen földet is. Egyedi generált vadonban horribilisan nagy mennyiségű terméketlen föld van természetesen generálva, terraformálás során gyakorlatilag csak a szemétbe megy.

**Comment by MrZero1** [comment]
Bekerült, köszi az ötletet!
