### ISSUE TITLE
Láma pároztatás

### ISSUE THREAD

**Issue by VdszHun** [andris155/TheOld-Crafters#4981]
**Szerver**: SFSurvival

*Út a hibához:* Láma pároztatáskor az egyik láma despawnol, megszakítva a pároztatást és teljesen törölve az egyik mobot. Elvesztettem ez miatt egy kereskedő lámát, és később egy sima lámát is újra próbálásnál, tovább nem szeretnék kutatni mert ritkán spawnolnak lámák :(
Edit: Kereskedő lámát kereskedő lámával próbáltam pároztatni, a sima lámát meg simával.

Az első alkalommal vadonban pároztattam, a másodiknál lootvadonban.

> *Dátum és idő:*
Felfedezés: 2023. 02. 06.

**Comment by Sanszi** [comment]
Nem sikerült reprodukálnom a hibát (próbáltam vadon, vadon2-ben de nekem ment rendesen), ettől függetlenül ha szeretnéd akkor visszaadom az elveszett lámáidat.

**Comment by VdszHun** [comment]
> Nem sikerült reprodukálnom a hibát (próbáltam vadon, vadon2-ben de nekem ment rendesen), ettől függetlenül ha szeretnéd akkor visszaadom az elveszett lámáidat.

Most megnéztem én is újra lootvadonban és ezzel az alkalommal sikeres volt, viszont így összekavar, hogy miért despawnolhattak azok a lámák amiket akkor pároztattam.
Az elveszett lámákat szeretném visszakérni, a jelentést pedig lezárom.

**Comment by Sanszi** [comment]
> > Nem sikerült reprodukálnom a hibát (próbáltam vadon, vadon2-ben de nekem ment rendesen), ettől függetlenül ha szeretnéd akkor visszaadom az elveszett lámáidat.
> 
> Most megnéztem én is újra lootvadonban és ezzel az alkalommal sikeres volt, viszont így összekavar, hogy miért despawnolhattak azok a lámák amiket akkor pároztattam. Az elveszett lámákat szeretném visszakérni, a jelentést pedig lezárom.

Nem lehetséges hogy túl sok állat volt már a chunkon ahol pároztatni próbáltál?

**Comment by VdszHun** [comment]
> > > Nem sikerült reprodukálnom a hibát (próbáltam vadon, vadon2-ben de nekem ment rendesen), ettől függetlenül ha szeretnéd akkor visszaadom az elveszett lámáidat.
> > 
> > Most megnéztem én is újra lootvadonban és ezzel az alkalommal sikeres volt, viszont így összekavar, hogy miért despawnolhattak azok a lámák amiket akkor pároztattam. Az elveszett lámákat szeretném visszakérni, a jelentést pedig lezárom.
> 
> Nem lehetséges hogy túl sok állat volt már a chunkon ahol pároztatni próbáltál?

Mindkét alkalommal távol tettem bármi levédéstől, felszínen lakatlan területeken, voltak a környéken állatok, de egy chunkba nem volt tömörülve sok egyik helyen se.
