### ISSUE TITLE
/lobby

### ISSUE THREAD

**Issue by Goldie2000** [andris155/TheOld-Crafters#4985]
**Lobby Szerver**:

Lehetne egy új átjáró az új szerverhez illetve az irány tűvel is a /lobby-ban.

Meg azt a hibát véltem felfedezni hogy a Sima Old Crafters Survival még mindig ott van az iránytűn! Azt hogyha kérhetném akkor el kell távolítani.

Megértésüket köszönöm! Goldie

**Comment by MrZero1** [comment]
Lobby-ban is kicseréltem az iránytűs menüt. Az új szerver akkor kerül majd be és akkor lesz neki NPC, ha megnyit. Köszi a jelentést!
