### ISSUE TITLE
SlimeFun a backpackek belerakhatóak saját magukba

### ISSUE THREAD

**Issue by AtiPLS** [andris155/TheOld-Crafters#499]
Alapértelmezetten nem lehet hiszen ha egérrel rákattintasz visszarakja.
De ha a hotkeyyel csinálod (Ha pl a 8-ason van a backpack akkor a 8-ast lenyomva oda rakja az itemet ahol van az egér)
És így belerakható saját magába.

//Nemtudom kinek jó ez, csak veszteni lehet belőle de kipróbáltam és működött. ( rip backpack :( )

**Comment by Andromeda11** [comment]
A kukát (dust bin) is be lehet rakni egy másik kukába. Gondoltam csaknem működik, de igen és eltűnt :D

**Comment by andris155** [comment]
Igazából a shulker bux-ban is berakható, ez egy összetett hiba a pluginban.
