### ISSUE TITLE
Skypvp bug jelentés

### ISSUE THREAD

**Issue by MatyasHorvath03** [andris155/TheOld-Crafters#5]
A Skypvp szerveren a V.I.P-knak néha bugol a végzetládája,vagyis az elrendezett cuccokat arrébb rakja.

**Comment by andris155** [comment]
Rá fogok nézni majd a pluginra.

**Comment by andris155** [comment]
Egyenlőre nem javítható, de szerintem ez nem okoz komolyabb gondot.
