### ISSUE TITLE
Slimefun bug-"addolás"

### ISSUE THREAD

**Issue by Neurofizis** [andris155/TheOld-Crafters#500]
Kreatívban lerakva arany,vas és más olyan érc ami jellegzetes slimefun dust-okat dobhat,kreatívban is kidobja ha kiütöd a blockot és survivalban felvehető dustokat droppol.

**Comment by jokoboy** [comment]
most akartam ezt leírni :'(      gyorsabb voltál 🥇

**Comment by andris155** [comment]
Letiltásra kerültek kreatívban az ércek.

**Comment by Neurofizis** [comment]
andris,majd a jutalmaimat egy következő bejelentkezésemnél fogom igényelni.Köszi
