### ISSUE TITLE
Chain armor

### ISSUE THREAD

**Issue by nagym97** [andris155/TheOld-Crafters#501]
![2017-02-07_11 56 04](https://cloud.githubusercontent.com/assets/25511763/22688491/d3b76904-ed2c-11e6-89dc-32cf228734c7.png)
A sima chain armor miért slimefun item? "You cannot use Slimefun items in a normal workbench"
Két láncnadrágot próbálnék összekraftolni, de nem lehet.. mert slimefun item, de miért is? - Joskaa

**Comment by andris155** [comment]
Nem tudok sajnos ezen módosítani, próbáld meg SlimeFun-os barkácsasztalban.
