### ISSUE TITLE
Zone Expand 

### ISSUE THREAD

**Issue by Kronox12** [andris155/TheOld-Crafters#502]
Kishúgomnak segítettem levédeni egy területet, de akkor vettem észre, hogy a /zone expand parancsnál 2 irány fel van cserélve. A parancs nem a szokásos XYZ ábra alapján megy (hossz, magasság, szélesség), hanem kicsit felcseréli (XZY) (lehet, hogy a Z helyett X van, a lényeg az, hogy a magasságot felcseréli az egyik szélességgel). Ennek az az eredménye, hogy a max levédési terület egy Tag számára 50 blokk hosszú, 50 blokk magas és 256 blokk széles lehet, ahelyett hogy 50 hosszú, 50 széles és 256 magas lenne.

**Comment by andris155** [comment]
javítva
