### ISSUE TITLE
Minemarket

### ISSUE THREAD

**Issue by otniel2001** [andris155/TheOld-Crafters#507]
#### Minecraft verzió.

* Operációs rendszer: 
* Minecraft verzió: 
* Minecraft launcher (nem kötelező):

**Comment by otniel2001** [comment]
Az OldKardok ereje ugyan annyi mint egy sima él 5 enchantos dia kardé, pedig élesség X van rajtuk.

**Comment by andris155** [comment]
Nem megfelelő hibajelentés
