### ISSUE TITLE
A cica bug

### ISSUE THREAD

**Issue by jokoboy** [andris155/TheOld-Crafters#508]
#### Hiba leírása:
<!---  Ha a cicát megütöm bugol a neve és [Elit]-té válik gondolom mert én is [Elit] vagyok --!>

#### Minecraft verzió:
<!-- 1.11.2 --!>
A játékod, és operációs rendszered pontos verziója. A legújabb nem megfelelő válasz.
------------------------------------------------------------------------------------------------
* Operációs rendszer: Windows 10 Pro
* Minecraft verzió:  1.11.2
* Minecraft launcher (nem kötelező): Team extreme

#### Videók, képek, mód lista és egyéb fájlok:

![2017-02-10_19 15 45](https://cloud.githubusercontent.com/assets/25535014/22840560/450d753c-efce-11e6-82b5-592ab3ede355.png)

![2017-02-10_19 15 48](https://cloud.githubusercontent.com/assets/25535014/22840561/450f1702-efce-11e6-8671-ffadb9a939a2.png)

![2017-02-10_19 15 50](https://cloud.githubusercontent.com/assets/25535014/22840562/4511d5fa-efce-11e6-9f8e-c4f46ab87823.png)

                                                                                    Doge

**Comment by andris155** [comment]
Nem megfelelő hibajelentést
