### ISSUE TITLE
(Slimefun)Enchanted Furnace Fejlesztés

### ISSUE THREAD

**Issue by Andromeda11** [andris155/TheOld-Crafters#509]
Az enchanced furnace "luck multiplier" effektje, azaz hogy egy kiégetés több végterméket is adhat, csak az ércekre van hatással. Tök jó lenne, ha minden kiégetendő itemre hatással lenne, nem csak az ércekre.

**Comment by andris155** [comment]
Ide kellene írni ezzel kapcsolatban a fejlesztőnek: https://github.com/TheBusyBiscuit/Slimefun4/issues
Sajnos angolul.

**Comment by Andromeda11** [comment]
https://github.com/TheBusyBiscuit/Slimefun4/issues/86

Úgy tűnik már tudnak a dologról.
