### ISSUE TITLE
OldGold cuccok

### ISSUE THREAD

**Issue by MrZeroTOC** [andris155/TheOld-Crafters#51]
Üdv.

Az OldBot, Pokol Ostora, Tüzespor, Törött üveg és a gyújtogató fegyvert nem lehet lekérni az /oldgold paranccsal. 
Beírom, hogy /oldgold oldbot elveszi az oldgoldot de nem rakja az invembe.

**Comment by andris155** [comment]
Hiba javítva:
unsafe-enchantments: engedélyezve.
