### ISSUE TITLE
KillRate teszt és, beállítás.

### ISSUE THREAD

**Issue by DragleX** [andris155/TheOld-Crafters#513]
Egy plugint kerestem a [PE] PvP szerverre az első egy killrate plugin lenne: 
http://forums.pocketmine.net/plugins/killrate.1137/
A második a túl élő szerverre lenne a lényege annyi, hogy ha a játékos megtalál egy ércet az ki írásra kerül a chatbe http://forums.pocketmine.net/plugins/orebroadcast.932/

**Comment by MerciGT** [comment]
Hát az az érces egy idő után zavaró lenne, inkább csak a gyémántot írja. O.o

**Comment by DragleX** [comment]
Igaz

**Comment by andris155** [comment]
Az érces elég zavaró még a gyémánttal is.
