### ISSUE TITLE
Addolás (MCMMO)

### ISSUE THREAD

**Issue by AwesomeFM** [andris155/TheOld-Crafters#514]
#### Hiba leírása

Ha kreatívban rakunk le zúzottkövet, majd maggal jobb klikkelünk rá, mohás kő lesz, és az már survivalos lesz, tehát ki lehet szedni.

#### A hiba reprodukálás lépései pontokba szedve

- Zúzottkő lerakása (kreatívban)
- Maggal jobb klikk rá, míg mohás kő nem lesz
- Survivalban kiütés

#### Minecraft verzió.

* Operációs rendszer: Windows 7 Ultimate
* Minecraft verzió: 1.11.2
* Minecraft launcher (nem kötelező): Shiginima

**Comment by andris155** [comment]
Ez slimefun vagy mivel működik ez? Vagy alap Minecraft?

**Comment by asdlol911** [comment]
Megnéztem, kipróbáltam és tényleg működik ez a bug.

**Comment by andris155** [comment]
Annyira nem értékes tárgy, meg nem is tudnám javítani.
