### ISSUE TITLE
Láthatatlan Potion

### ISSUE THREAD

**Issue by MerciGT** [andris155/TheOld-Crafters#515]
Sok player használja, és tilos használni, ezért kéne banitembe rakni.

Az alábbi id-k:

373:8206
373:8270
373:16398
373:16462

* Operációs rendszer: Android
* Minecraft verzió: 1.0.4

**Comment by andris155** [comment]
hát a szerveren biztosan más a kódja.

**Comment by MerciGT** [comment]
Szerintem nem, de megnézem a PE Id-t is akkor.

**Comment by MerciGT** [comment]
Ahogy néztem, szerveren is ennek kell lennie.

**Comment by andris155** [comment]
14 az idje szerveren elvileg.

**Comment by andris155** [comment]
most tiltva van?

**Comment by andris155** [comment]
tiltva
