### ISSUE TITLE
Backpack crafting

### ISSUE THREAD

**Issue by balu514** [andris155/TheOld-Crafters#517]
Hiba leírása
 Nem enged backpacket kraftolni a small backpack kinyitása után . 

A hiba reprodukálás lépései pontokba szedve
 Kinyitottam a small backpacket és utánna próbáltam backpacké alakítani de nem engedte azzal a hibaüzenettel hogy, nem ismerti fel a receptet.

 Minecraft verzió.

* Operációs rendszer: Windows 10 pro
* Minecraft verzió: 1.11.2
* Minecraft launcher (nem kötelező): 

![2017-02-20_16 12 26](https://cloud.githubusercontent.com/assets/25904783/23131015/c7f97f74-f788-11e6-87c6-56092365bef6.png)

![2017-02-20_16 12 14](https://cloud.githubusercontent.com/assets/25904783/23130986/a91eee4a-f788-11e6-84a8-cef11c85dc96.png)

**Comment by Andromeda11** [comment]
Igen ez ilyen, ha kinyitod, már nem lehet nagyobb táskává átcraftolni. Nem hinném, hogy hiba lenne, ez így működik.
