### ISSUE TITLE
Old horgászbot működési zavar

### ISSUE THREAD

**Issue by Hauklin** [andris155/TheOld-Crafters#518]
#### Hiba leírása
Hellósztok. Nemrégiben vettem egy Old horgászbotot a survivor szerveren, de sajnos annak ellenére hogy LureX van rajta, valós időben 5 perc alatt se fogtam egyetlen halat sem (még csak a kapás előtti kígyózás, illetve az azt megelőző csobbanások sem látszanak) egyáltalán nem működik.
Természetesen kipróbáltam a vizet más bottal is, azzal normálisan jött a hal, ráadásul tenger biomon. 
Megpróbáltam orvosolni a problémát úgy hogy elhajintottam, és viszavettem, raktam rá még egy repair enchantot, átneveztem, de az eredmény ugyanaz.

#### Minecraft verzió.

* Operációs rendszer:  Windows 10
* Minecraft verzió: 1.11.2
* Minecraft launcher (nem kötelező):

**Comment by andris155** [comment]
Kérlek ezt teszteld le újra.

**Comment by GhostTriggerGT** [comment]
Igazolt hiba, teszteltem én is.

**Comment by andris155** [comment]
javítva
