### ISSUE TITLE
PocketEdition Plugin

### ISSUE THREAD

**Issue by Mousking** [andris155/TheOld-Crafters#520]
#### Minecraft verzió.

* Operációs rendszer: 
* Minecraft verzió: 
* Minecraft launcher (nem kötelező):

**Comment by Mousking** [comment]
PE Plugint kerestem Xray-re, kis változtatást végeztem rajta, így ez lenne az:
https://www.dropbox.com/s/jigf7xnibjzzgtb/Loader.php?dl=0

**Comment by andris155** [comment]
Nincs kompatibilis plugin az 1.0.0-ás újra írt chunkokra a PE-re.
