### ISSUE TITLE
MyPet-Plugin Bug 

### ISSUE THREAD

**Issue by Linux1230** [andris155/TheOld-Crafters#521]
#### Hiba leírása
Elit ranggal, ha van pet-em és megölök egy megszelídített állatot akkor a képen látható dolgokat írja ki.
Ez elég fura.

#### A hiba reprodukálás lépései pontokba szedve
1. Elit rang, csak ezzel próbáltam, mert jelenleg az van.
2. Kell egy sima lasszó.

3. Megszelídített állat.
4. Meg kell ölni úgy, hogy van petünk, de el van küldve (/psa).

#### Minecraft verzió.

* Operációs rendszer: Windows 10 (1607)
* Minecraft verzió: 1.11.2 [forge mod loader (pontos verzió látszik a képeken)]

#### Videók, képek, mód lista és egyéb fájlok
####Videó:
https://youtu.be/JcY_-OTr80Q (természetesen saját)
####Képek:
![2017-02-22_20 13 34](https://cloud.githubusercontent.com/assets/25261683/23332381/10856ebc-fb79-11e6-9202-16555723a8a0.png)
![2017-02-22_20 13 14](https://cloud.githubusercontent.com/assets/25261683/23332393/49a8b35c-fb79-11e6-9d7b-5f134ee7d629.png)

**Comment by andris155** [comment]
mcmmo + nametagedit bug, sajnos nem tudom javítani. Mivel mind2 scoreboard csapatot használ.

**Comment by Linux1230** [comment]
Köszönöm :D

**Comment by jokoboy** [comment]
Hallod, már azt hittem ezt már jelentették mert mindenki ismeri szinte a szerveren :D
