### ISSUE TITLE
Szavazás fejlesztése 40+

### ISSUE THREAD

**Issue by andris155** [andris155/TheOld-Crafters#523]
Mit adjon a 40., 50. stb... szavazásnál?
10., 20, 30.-nál 5 oldgoldot ad.

**Comment by Linux1230** [comment]
Szia! Szerintem az 50. adhatna egy old diát a 40. meg egy old iront.

**Comment by andris155** [comment]
Minden 10. szavazat 5 OldGold.
1 OldDiamond: 50., 75, 100. szavazat.

**Comment by andris155** [comment]
https://mc-szerverek.hu/szerverek/id/85
