### ISSUE TITLE
SkyBlock: a sárkányidézés nem működik az Endben

### ISSUE THREAD

**Issue by Icecroft** [andris155/TheOld-Crafters#524]
#### Hiba leírása
A Skyblockon a sárkányidézés nem működik az endben, a végkristályokat nem lehet letenni a helyükre. Lásd sceenshot lent.

#### A hiba reprodukálás lépései pontokba szedve
1.) bementem az endbe :)
2.) megpróbáltam az idézőhelyen letenni a végkristályt, mint s1- szerveren, de nincs jogom hozzá

#### Minecraft verzió.
* Operációs rendszer:  Win7
* Minecraft verzió:  1.11.2

#### Videók, képek, mód lista és egyéb fájlok
![2017-02-26_20 46 19](https://cloud.githubusercontent.com/assets/19332825/23343058/7696783a-fc65-11e6-8da9-dc5fdbbbbe5f.png)

**Comment by andris155** [comment]
javítva
