### ISSUE TITLE
SkyBlock: a /back parancs nem visz vissza az Endbe vagy a Netherbe

### ISSUE THREAD

**Issue by Icecroft** [andris155/TheOld-Crafters#525]
#### Hiba leírása
A SkyBlockon a /back paranccsal nem lehet visszajutni a végbe vagy netherbe.

#### A hiba reprodukálás lépései pontokba szedve
1.) elmegyek a végbe vagy netherbe
2.) /is home paranccsal haza teleportálok
3.) /back paranccsal próbálok visszajutni, de nem megy. Ez a funkció az s1 szerveren viszont jól működik.

#### Minecraft verzió.

* Operációs rendszer:  Win7
* Minecraft verzió:  1.11.2

**Comment by andris155** [comment]
Az is parancsot nem menti a back sajnos,
