### ISSUE TITLE
SkyBlock: a szigetem warpja, csak akkor működik, ha loginolva vagyok

### ISSUE THREAD

**Issue by Icecroft** [andris155/TheOld-Crafters#526]
#### Hiba leírása
A szigetemen a warp helyén van egy bolt, de csak akkor tudnak a többiek oda teleportálni, ha én is be vagyok jelentkezve. Ha offline vagyok, senki sem jöhet :(
Valójában nem tudom, hogy hiba vagy feature, de kellemetlen.
Ha hiba, kérlek módosítsátok a dolgot, ha nem hiba, akkor ez egy módosítási javaslat a részemről.

#### Minecraft verzió.
* Operációs rendszer:  Win7
* Minecraft verzió:  1.11.2

**Comment by andris155** [comment]
Valószínűleg olyan megoldást használ a fejlesztő, amiben nem kérhető le offline az UUID kód, így nem tudja a név alapján meghatározni, hogy hova kell vinnie csak online.
