### ISSUE TITLE
mc-szerverek elírás

### ISSUE THREAD

**Issue by Linux1230** [andris155/TheOld-Crafters#528]
#### Hiba leírása
Szerintem ez elírás a https://mc-szerverek.hu/szerverek/id/85 oldalon, a 1.11.2 végén vessző van pont helyett.
(Ha nem ide kellett volna jelenteni bocsi!)

#### Kép:
![kepkivagas](https://cloud.githubusercontent.com/assets/25261683/23374870/60395050-fd26-11e6-9361-539c20d5c3b3.PNG)

**Comment by andris155** [comment]
1.11.2, 1.11.1 a pontos kiírás sajnos az oldal nem támogatja a space-t a verzióban, de írok nekik majd.
