### ISSUE TITLE
SkyBlock: a sárkány utáni portál buggos

### ISSUE THREAD

**Issue by Icecroft** [andris155/TheOld-Crafters#531]
#### Hiba leírása
A sárkány megölése után beléptem a portálba, de se kilépni, se továbbhaladni nem lehet. Az ESC sem visz ki onnan, parancssort nem lehet felhozni. Most is ott vagyok beszorulva.
Ha ESC-t nyomok, egy pillanatra felvillan, hogy nem használhatom más sziget portálját. Lásd screenshot lent.

#### A hiba reprodukálás lépései pontokba szedve
1. Öld meg a sárkányt
2. Lépj be a portálba

#### Minecraft verzió.

* Operációs rendszer:  Win7
* Minecraft verzió:  1.11.2
* Minecraft launcher (nem kötelező): 

#### Videók, képek, mód lista és egyéb fájlok
![2017-03-01_17 16 37](https://cloud.githubusercontent.com/assets/19332825/23469358/a8bef112-fea3-11e6-817d-6aceeb9f5c0b.png)

**Comment by andris155** [comment]
Nekem működött. Most se jó?
