### ISSUE TITLE
Új tárgyak az oldgoldért a Pokol szett helyett **Ötletek** **OCD**

### ISSUE THREAD

**Issue by andris155** [andris155/TheOld-Crafters#532]

**Comment by Kyren562** [comment]
Bérelhető jogok, pl Fly 3napig 64 OCD vagy valami ilyesmi :D

**Comment by MrDinamit88** [comment]
Smaragd szett vagy valami! :D

**Comment by Linux1230** [comment]
Lehetne olcsósítani és mondjuk az egyik enchantot rajta, pl az armorokon a védelmet 10esre emelni.

**Comment by jokoboy** [comment]
OldGoldért lehessen venni OldDiamondot pl. 1000db OldGold az 1db OldDiamond

**Comment by Linux1230** [comment]
Jó lenne ha lehetne pl: old goldért, 10-es enchantokat venni. Ezeket slime funnal párosítva nagyon jól lehetne hasznosítani. Mondjuk 100 old goldért lehetne árulni.

**Comment by Linux1230** [comment]
Lehetne venni 20 oldgoldért lucky blockot.

**Comment by Linux1230** [comment]
Vagy az eddigi Pokol cuccok árán lehetne Lucky armort venni.

**Comment by Alcatrazzy** [comment]
Jobok visszahozása, farmer, munkás, favágó stb $-ért / ogért dolgozol?

**Comment by Linux1230** [comment]
Lehetne eladni fix pénzért az old goldot pl 1500/db-ért az oldgold warpon.

**Comment by Linux1230** [comment]
esetleg lehetne néhány slimefunos ingotot venni aminek idegesítő a receptje, pl: a hardened metal-nak.

**Comment by Linux1230** [comment]
Vagy lehetne venni 256 OldGoldért olyan írott könyvet ami feljogosít, egy tárgy nevének színezéséfe, ha ezt nem lehet megoldani valamilyen pluginnal, akkor ezt a könyvet egy adminnak dobva az megcsinálná.

**Comment by HELLCATGHOST** [comment]
# Soulbound **old szett**  ?
