### ISSUE TITLE
,,Végtelen'' block bug

### ISSUE THREAD

**Issue by jokoboy** [andris155/TheOld-Crafters#533]
#### Minecraft verzió.

* Operációs rendszer: Windows 10 Pro
* Minecraft verzió: 1.11.2
* Minecraft launcher (nem kötelező): Team Extreme

#### Videók, képek, mód lista és egyéb fájlok

https://www.youtube.com/watch?v=sc5T12mj8YQ&feature=youtu.be

Doge

**Comment by jokoboy** [comment]
és ez nem csak aranytömbbel hanem más slimefunos itemmel is működik

**Comment by andris155** [comment]
Nem érhető el a videó

**Comment by jokoboy** [comment]
most már elméletileg jó.

**Comment by andris155** [comment]
Akkor most nem működik?

**Comment by jokoboy** [comment]
A videóra céloztam, hogy már működik

**Comment by andris155** [comment]
A slimeblock mozgatás tiltva
