### ISSUE TITLE
Smeltery arany bugg

### ISSUE THREAD

**Issue by Kiroti** [andris155/TheOld-Crafters#539]
#### Minecraft verzió.

* Operációs rendszer: 
* Minecraft verzió: 
* Minecraft launcher (nem kötelező):

**Comment by Kiroti** [comment]
tanaltam egy buggot amikor a semleteryben ott van EGY aranyrud es viszed fel a karatjat akkor ott marad de lesz meg egy belole ugy ertem az mar karatos lesz

**Comment by HELLCATGHOST** [comment]
Megtalálta: Kiroti 
Telek ID  33;-4 .
Dátum: 2017.03.10 17:13
Tesztelve,az állítás igaz.
"Smeltery használata közben,mikor XY karátos aranyat akarunk csinálni , akkor aranyport elveszi,de az arany ott marad,és megkapjuk az XY karátos aranyat.
~HELLCAT

**Comment by andris155** [comment]
Próbáljatok meg ide írni, persze angolul: https://github.com/TheBusyBiscuit/Slimefun4/issues
A plugin verziók a legújabbak. A szerverfájl git-Paper-1056.
