### ISSUE TITLE
BanIP gondok.

### ISSUE THREAD

**Issue by Kronox12** [andris155/TheOld-Crafters#55]
A moderátorok /banip-kor nem kapnak visszajelzést, de érdekes módon az adminok igen amikor ők írják be, illetve azt is látják, amikor a moderátor sikeresen végrehajtatta a parancsot. Illetve a moderátorok látják az adminok /banip-jét, csak a sajátjukat nem.

**Comment by andris155** [comment]
Most látják?

**Comment by Kronox12** [comment]
A /banip most jó,de az /unban,/unbanip nem megy :x azt írja helytelenül lett betöltve

**Comment by Kronox12** [comment]
/pardon,/pardon-ip is megy elvileg,de azok se adnak visszajelzést

**Comment by andris155** [comment]
Holnap próbáljátok ki majd, és írd le, hogy jó lett-e.
Köszi

**Comment by andris155** [comment]
Megoldva.
