### ISSUE TITLE
Tábla

### ISSUE THREAD

**Issue by GhostTriggerGT** [andris155/TheOld-Crafters#550]
#### Hiba leírása
Ugyanolyan szövegű táblát nem lehetséges lerakni, e-miatt nem lehet liftet sem létrehozni, vagy bármilyen egyéb pluginnal kapcsolatos szöveget, ami táblára kell.

#### A hiba reprodukálás lépései pontokba szedve
Pl. [Lift Up]

#### Minecraft verzió.
* Operációs rendszer: Windows 10 Pro
* Minecraft verzió: 1.11.2
* Minecraft launcher (nem kötelező):

**Comment by andris155** [comment]
javítva
