### ISSUE TITLE
Item vesztős bugg

### ISSUE THREAD

**Issue by brtamas0** [andris155/TheOld-Crafters#551]
Üdv! Ezzel a buggal itemet lehet veszteni. ha az altaros dropper fölé blockot rakunk és jobbkattolunk rá egy  tárgyal az lerepül a földre és nem lehet visszaszerezni.
![2017-03-16_21 11 31](https://cloud.githubusercontent.com/assets/23553862/24016904/2d7bc01a-0a8e-11e7-8261-aa83036a96c1.png)

**Comment by andris155** [comment]
Helló.
Szerintem normális használat mellet senki se rak felé blokkot.

**Comment by brtamas0** [comment]
ok



2017-03-17 16:49 GMT+01:00 Marczinkó András <notifications@github.com>:
