### ISSUE TITLE
Slimefun blockplacer

### ISSUE THREAD

**Issue by GhostTriggerGT** [andris155/TheOld-Crafters#552]
#### Hiba leírása
Blockplacer által lehelyezett érc többszörözhető gyengéd érintés+ szerencse csákánnyal.

#### A hiba reprodukálás lépései pontokba szedve
Blockplacerbe ércek helyezése, majd gyengéd érintéses, szerencsés csákánnyal kiütése.

#### Minecraft verzió
* Operációs rendszer:  Windows 10 Pro
* Minecraft verzió: 1.11.2
* Minecraft launcher (nem kötelező):

**Comment by andris155** [comment]
letiltva, újraindítás kell hozzá
