### ISSUE TITLE
Vásárolható SlimeFun tárgyak ötletek.

### ISSUE THREAD

**Issue by andris155** [andris155/TheOld-Crafters#553]
Sziasztok!
Ide várom azokat az ötleteket milyen SlimeFun tárgyakat lenne jó, ha lehetne vásárolni? Ha valakinek egy meglévő ötlet tetszik, akkor lájkolja. Köszönöm a segítséget.

**Comment by CptEdvin** [comment]
A **Lucky tárgyak**-at javaslom hogy meg lehessen vásárolni.
Az összes fajta gyümölcsöt és bogyót pedig el lehetne adni,így lehetne még valamivel pénzt keresni.

**Comment by GhostTriggerGT** [comment]
-Auto enchanter/auto disenchanter
-Energy capicator-ok
-Programmable Android-ok
-Soulbound cuccok (Páncélok, fegyverek, eszközök)
_[Szerintem]_

**Comment by Linux1230** [comment]
A nagyon idegesítő receptü ingotok: redston aloy vagy mi, meg hardened metal, illetve a blistering ingotok közűl a nether staros. Ezeket nagyon hosszadalmas lecraftolni...
