### ISSUE TITLE
Creás sódert sifted ore-ra

### ISSUE THREAD

**Issue by DrDynamit** [andris155/TheOld-Crafters#554]
Creás sódert sifted ore-ra

1. Csinálok automated gold pan-t
2. Sóderrel használom (rá kattintasz jobb klikkel)
3. És azután ahogy átváltotta a sódert sifted orera , agyagra, flintre 
4. Átváltok survival játékmódra , és felszedem a cuccokat
    Szóval ez ilyen ingyen végtelen sóder ha úgyvesszuk

Minecraft verzió. 1.11.2

    Operációs rendszer: Win7Ultimate
    Minecraft verzió: 1.11.2

Videók, képek, mód lista és egyéb fájlok
http://www.img.tpx.cz/uploads/2017-03-19_11.06.54.png
http://www.img.tpx.cz/uploads/2017-03-19_11.07.00.png
http://www.img.tpx.cz/uploads/2017-03-19_11.07.07.png
http://www.img.tpx.cz/uploads/2017-03-19_11.07.14.png
http://www.img.tpx.cz/uploads/2017-03-19_11.07.24.png
http://www.img.tpx.cz/uploads/2017-03-19_11.18.27.png

**Comment by andris155** [comment]
https://github.com/andris155/TheOld-Crafters/issues/185

**Comment by andris155** [comment]
A sóder annyira nem értékes, de köszönjük a bejelentést.

**Comment by DrDynamit** [comment]
Hát figyeld , szinte ingyen rengeteg sifted ore , ami a SF alapanyaga ,
nekek mondjuk mind1.

2017-03-20 18:03 GMT+01:00 Marczinkó András <notifications@github.com>:
