### ISSUE TITLE
SkyBlock fejlesztés

### ISSUE THREAD

**Issue by Vargyaska** [andris155/TheOld-Crafters#556]
Pluginok: https://docs.google.com/document/d/1sRt36niBOk49XCEDDp6a_5yEh_Th8_5ZEwOXSYNe1Fc/edit
               https://www.spigotmc.org/resources/greenhouses.910/

Teendők:

1. pluginok magyarosítása (Ebben segítőnk mi is, csak írj rám.)
2. konfig
3. külön inv a mob világba (skyblockon ez a letrehozott vilag neve)
4. A többit mi csináljuk meg :)

**Comment by andris155** [comment]
a caseopen nem jó 1.11.2-őn

**Comment by andris155** [comment]
kész minden világban ugyan az az inv kivéve a mobs-ban
