### ISSUE TITLE
Pár infó/kérés

### ISSUE THREAD

**Issue by Vargyaska** [andris155/TheOld-Crafters#558]
Szia andris.

Lenne még pár dolog. Én elkezdtem a magyarosítást. Igyekszem ma befejezni, de max holnapra meg lesz.
Az lenne a kérésem, hogy majd ha vissza küldtem a konfigot, akkor a killermonye-ben ki kellene venni, hogy a sima állatokért pénzt kapj. Kivétel a polip. (squid)
Emellett, ha van időd ma rakd nekem át kérlek építészről azt a mapot amin van a mobs. Mert vmi végett, hiába schemaznam jól be, a levelek eltűnnek és nem tudom miért. Egyenlőre ennyi. :)
Ha van valami írok. :)

**Comment by andris155** [comment]
kész

**Comment by andris155** [comment]
No decay oak : 18:4
no decay spruce: 18:5
no decay birch : 18:6
no decay jungle 18:7
no decay acida: 161:4
no decay dark oak: 161:5
