### ISSUE TITLE
További fejlesztések SKyBlock

### ISSUE THREAD

**Issue by Vargyaska** [andris155/TheOld-Crafters#560]
Szia andris.

Kellene akkor jopar konfig. Először is be kellene tenni azt a két schemat amit ma csinaltam (arena1 arena2) ezek apiteszen vannak. Tovabba hozza kellene adni a a friends plugin parancsait a rangokhoz. Mindegyikhez. A greenhouse el van vetve nem lesz egyenlore. A skywars pluginnal ugy vagyok, hogy sztem nem olyan, mint amilyenre szamitotam. Itt nem adnak az ercek cuccost, ahogy neztem a konfig filet. Ha tudsz olyan plugint, akkor kuldd el kerlek fb-n a kofig filet, amit majd le kell magyarositani. Az arenak keszen lesznek a heten. A mobs is kesz van, oda csak a boltot kell berendezni es a vilagot beallitani stb.. de azt en is el tudom intezni. 
Hat tömören ennyi. :)

**Comment by andris155** [comment]
itt vannak a jogok hozzá: https://github.com/HyChrod/Friends2.0/tree/master#commands--permissions
Ami kell /pex group Tag add jog
pl.: /pex group Tag add Friends.Use

**Comment by andris155** [comment]
A greenhouse-t, és skywars-t szedjem ki?

**Comment by andris155** [comment]
kiszedve
