### ISSUE TITLE
SkyWars plugin update!!!

### ISSUE THREAD

**Issue by Vargyaska** [andris155/TheOld-Crafters#561]
Na andris. ezt talaltam a masik skyblock helyett
https://www.spigotmc.org/resources/%E2%9C%AF-biteskywars-multiarena-kits-cages-titles-stats-1-8-1-9-1-10-1-11-%E2%9C%AF.9245/

Ezt kellene bekonfigolni
en lemagyarositom ha gy van csak kuldj kofig filet

**Comment by andris155** [comment]
berakva
