### ISSUE TITLE
Skywars plugin

### ISSUE THREAD

**Issue by Vargyaska** [andris155/TheOld-Crafters#562]
Szia andris.

Lenne egy kis problema.
Skyblockon létrehoztam egy világot skywars neven, de nem teszi be a pluginhoz szükesges itemeket az invedbe. Ezután létrehoztam egy másik világot mobs neven, oda meg betette es hiába csináltam meg akárhogyan a világot, csak a "mobs" világba tette be :D. Erre ha tudsz megoldást akkor kérlek csináld meg :)

**Comment by andris155** [comment]
nem értek ahhoz a pluginhoz
