### ISSUE TITLE
Buggok

### ISSUE THREAD

**Issue by Vargyaska** [andris155/TheOld-Crafters#566]
1. Tab nem mutatja a külön világban lévő embereket egymásnak. 2. Az inv minden alkalommal egy másik világban az adott világban szerzett cuccokat adja (ha előszor kerülünk oda akkor üres), 3. Nem mutatja a chat hogy [+] &7{PLAYER},

Nos az h mas cuccokat mutat az invedben az a kulon inv vegett van gondolom, de csak aban a vilagban kellen kulon inv amelyiken a mobs van

**Comment by pacica12342** [comment]
Szia, szeretném jelenteni ahogy a PE tulélő szerveren, Fire Chargeval, lehet gyújtogatni levédett területeken.
