### ISSUE TITLE
Mypet gondok #2

### ISSUE THREAD

**Issue by Kronox12** [andris155/TheOld-Crafters#57]
A /pr pay,/petr pay,/petrespawn pay parancsokkal duplikálni lehet a mypetet,és ez a másolat csak a chunkok ki/be töltésekor tűnik el.Javasolt megoldások:Frissíteni a legújjabb mypetre és tiltani az említett parancsokat 2 ok miatt:1.Fent az indok. 2.Halhatatlanok tőle a petek, soha nincs vége a párbajnak, nem igazi a harc.

**Comment by andris155** [comment]
Várunk az új verzióra.

**Comment by andris155** [comment]
Az új verzió berakva.
