### ISSUE TITLE
Kreatív addolás

### ISSUE THREAD

**Issue by S3nS3IW00** [andris155/TheOld-Crafters#573]
#### Hiba leírása

Kreatívban meglehet nyitni a sütőt, tölcsért, pakolni bele cuccot, majd survivalban kilehet venni.

#### Minecraft verzió.

* Operációs rendszer: 4.4.2
* Minecraft verzió: 1.0.4.11
* Minecraft launcher (nem kötelező): Alap app

**Comment by andris155** [comment]
direkt kipróbáltam, és nem megy
