### ISSUE TITLE
PVP

### ISSUE THREAD

**Issue by Vargyaska** [andris155/TheOld-Crafters#574]
Nos andris

Annyit kellene, hogy azt az ures szervert beizziteni meg ma ha raersz vagy a hetvegen.
Nekem elkuldeni egy multicraftot, es ha arra is lenne idod meg akkor a volt skypvpv/kitpvp mentest pluginostul mapostul feltenni
 
Lenyegebe ennyi :)

**Comment by andris155** [comment]
nincs hely új szerverre
