### ISSUE TITLE
SkyPvP&KitPvP kit csere

### ISSUE THREAD

**Issue by PEszem** [andris155/TheOld-Crafters#575]
Szia.Az lenne a keresem hogy a pe Skypvp és kitpvp szerveren a kezdő és felderítő kitbe a bőrszett helyett legyen lánc vagy vas .Nagyon egyenlőtlenek az esélyek a rangosokkal szemben és sokan inkább fel sem jönnek mindig meghalni így csökken a játékosszám.
Üdv Szem~

**Comment by DragleX** [comment]
Támogatom a feltevésed.

**Comment by RGeri** [comment]
Tök jó ötlet Támogatom 👍  Vagyány lenne!!!!

**Comment by TOCFrelly** [comment]
Jó ötlet, de én inkább, azt szeretném hogy a kezdő kitben lehetne enchantolt szerelések is,  így meglenne a rangosok, és a tagoknál az egyensúly.

**Comment by Mousking** [comment]
Támogatom, kiegyenlítettebbek lennének a küzdelmek.

**Comment by NoelD10** [comment]
Nagyon jó ötlet! Mert így nincs nagyon esélyük a rangosok ellen! Én támogatom az ötletet!

**Comment by andris155** [comment]
kész, holnap tölt be,
