### ISSUE TITLE
PE KitPvP jogok

### ISSUE THREAD

**Issue by Mousking** [andris155/TheOld-Crafters#577]
A PE KitPvP szerverre szeretném ha az Építészek kaphatnának sethome, back, sphere és hsphere jogot. Az utolsó kettő az építésben, a sethome az építményeik helyének elmentéséhez kellene. Nick jog kellene Mindhárom PE szerverre az Építészeknek a színes neveik megmaradásához, és jó lenne ha láthatnák hogy ki kit bannolt és hogy kire tpzett.
Üdv,
~RoarSRoad

**Comment by Mousking** [comment]
A PE KitPvP szerverre szeretném ha az Építészek kaphatnának sethome, sphere és hsphere jogot. Az utolsó kettő az építésben, a sethome pedig az építményeik helyének elmentéséhez kellene.
Üdv,
~RoarSRoad

**Comment by DragleX** [comment]
Támogatnám ezt az ötletet.

**Comment by TOCFrelly** [comment]
Támogatom. ☺

**Comment by TOCFrelly** [comment]
Támogatom.

**Comment by andris155** [comment]
- essentials.home.bed
  - essentials.home.use
  - essentials.sethome
  - essentials.tpa
  - essentials.tpahere
  - essentials.back

**Comment by andris155** [comment]
A nick jog továbbra is felesleges szerintem, mivel nem lehet feltörni a jelszókat, egyszerűen csak normális jelszót kell megadni.
