### ISSUE TITLE
A pe szerverre a jail javítása.

### ISSUE THREAD

**Issue by TocPe-szem** [andris155/TheOld-Crafters#578]
Szia. Szeretném kérni hogy a pe szervereken a jail plugin-t javítsd ki, mert nagyon sok az apró szabálysértés és szükség lenne rá.

**Comment by DragleX** [comment]
Tényleg jó lenne ha javítva lenne.

**Comment by TOCFrelly** [comment]
Igen, nagyon jó lenne a jail. :)

**Comment by Mousking** [comment]
Támogatom az ötletet, jó lenne visszavezetni.

**Comment by andris155** [comment]
Nincs elég erős gépünk jelenleg hozzá. A timer sokat eszik. (A PE VPS-sen fut, mivel a dedikált gép dos védelme tiltja a PE-t is.).
