### ISSUE TITLE
Near parancs javítása fire charge hiba.

### ISSUE THREAD

**Issue by DragleX** [andris155/TheOld-Crafters#579]
A pe szervereken a near az old rangnál nem működik a parancs beírása után nem történik semmi (ennek a rangnak kellene joga legyen hozza), a fire charge-val levédett területekre tüzet lehet rakni (area védésnél csak).

**Comment by DragleX** [comment]
Úgy gondolom ban item alá kellene helyezni a fire charget az id-je 385.

**Comment by andris155** [comment]
javítva

**Comment by andris155** [comment]
320 OCD -> DragleX

**Comment by DragleX** [comment]
Köszönöm szépen :D
