### ISSUE TITLE
Plugin ötletek.

### ISSUE THREAD

**Issue by warsajt** [andris155/TheOld-Crafters#581]
Sziasztok, lenne egy pár plugin ötletem a PC Survival szerverre.

-Bloodmoonier
* Ez lényegében megadott időnként ,,Vérholdat" varázsol a szerverre.
 - A csontvázak gyorsabban lőnek, már tüzes nyilat is.
 - A zombik fegyverzettel spawnolnak.
 - Minden ellenséges mob amit megölünk, esély van rá hogy zombiként újjáéled.
 - Ellenséges mobok spawnolhatnak amikor megpróbálsz elaludni.
 - Az ellenséges mobok több XP-t, ill tárgyat dobnak.
 - Az ellenséges mobok gyorsabbak lesznek.
 - Amikor bekövetkezik az Event, egy  egyedi Textúra-csomagot is bisztos't az élvezhetőbb, hitelesebb játék végett.

* Be lehet azt is álli'tani hogy teliholdkor, esetleg minden 3. éjszaka következzen be ez az esemény.

-SkullTurret ( Egy kicsit összefüggésbe lehet hozni a Bloodmonier-el ) 
* A plugin lényege hogy tudsz épi'teni, lényegében egy automata ny'lpuskát ami, beálli'tás szerint lövi a Barátságos/Ellenséges mobokat.

- Automata célzás, és lövés.
- Úgy nevezett ,,Töltény Láda". Ebbe kell elhelyezni a nyilakat.
- Egyedi Skinek használata. Akár a te fejed is lehet az egésznek a ,,Turret" része.
- Ki/Be kapcsolási lehetőség Redstone-al.
- Tüzes nyilakat is ki tud lőni.
- 6 craftolható ,,skull" ti'pus. ( Minél jobb, nagyobb a skullod szintje, annál erősebb nyilakat lő ki, ill annál gyorsabban, pontosabban lövi ki azokat.

Üdvözlettel: warsajt

**Comment by andris155** [comment]
A SkullTurret-t már nem fejlesztik tudtommal, csak fizetőst találtam. A blood-os egyelőre nem kerül be.
