### ISSUE TITLE
SkyBlock

### ISSUE THREAD

**Issue by TamasB14** [andris155/TheOld-Crafters#582]
A skyblock-on ha átmész a /warp arénába akkor hogy ha egy kardot [Vagy Mást] felteszel /ah-ra és utána visszamész a szigetre kitudod venni azt a cuccot amit a /ah-ra raktál a szigetedet!

**Comment by andris155** [comment]
Javítva!
Köszönjük a hibajelentést!

**Comment by andris155** [comment]
320 OCD -> TamasB14
