### ISSUE TITLE
OldGold ötlet

### ISSUE THREAD

**Issue by Lordi88** [andris155/TheOld-Crafters#583]
Mivel bejött a Slimefun, egyre többen árulnak Lucky Cuccokat, amik jóval jobbak mint pl. a Pokol cuccok, ezért arra gondoltam kezdeni kéne valamit az OldGold-al.
Ötletem:
Be lehessen váltani az oldgoldot, egy bizonyos darabszám után a legkisebb rangra, ami tudomásom szerint a Tag+, vagy esetleg valami más színnel a "Tag" rang, olyan + dolgokkal mint pl. 2 telek, 3 pet, 7 levédés, esetleg fly... 
De ha nem, a Tag+ is szerintem egy olyan rang amit oda lehetne adni a játékosoknak teszem azt kb. 450-500 OldGoldért cserébe. 
Talán ez motiválná egy kicsit a játékosokat hogy keressék, adják vegyék az OldGoldot, mert jelenleg szinte semmi érdeklődés nincs iránta. 

Lordi voltam.

**Comment by TamasB14** [comment]
Tényleg jó ötlet!

**Comment by andris155** [comment]
508 OCD
