### ISSUE TITLE
SlimeFun/Pláza szépséghiba

### ISSUE THREAD

**Issue by Icecroft** [andris155/TheOld-Crafters#589]
#### Hiba leírása
A survival szerveren ha slimefun-os tárgyat viselek (pl Glowstone helmet) a pláza területén, akkor a rendszer spammel:  "Az a tárgy tiltva van ebben a világban". Lásd screenshot.
Elég lenne, ha ezt max egyszer jelezné

#### A hiba reprodukálás lépései pontokba szedve
1.) vegyél fel egy Glowstone sisakot
2.) menj a /warp pláza -ra

#### Minecraft verzió.
* Operációs rendszer:  Win7
* Minecraft verzió: 1.11.2
* Minecraft launcher (nem kötelező): 

#### Videók, képek, mód lista és egyéb fájlok
![2017-04-21_21 45 51](https://cloud.githubusercontent.com/assets/19332825/25293821/b88dd4f8-26dc-11e7-9269-488be54a5842.png)

**Comment by andris155** [comment]
Ha jól tudom ez minden felvehető tárgynál így van itt. Hát igazából ez így van megírva. Lehetne szebben és jobban is, de a fejlesztő ennél komolyabb hibákat is elég lassan javít.
