### ISSUE TITLE
MCMMO Herblore bug

### ISSUE THREAD

**Issue by Icecroft** [andris155/TheOld-Crafters#590]
#### Hiba leírása
MCMMO Herblore skillem meghaladja az 1500-as szintet, miszerint automatikusan újravet minden betakarított növényt. Az újravetés viszont nem mindig indul azonnal, a növénytáblák elején sokszor újravetetlen terület keletkezik. Lásd screenshot.
Ha egyszer sikerült újravetnie, utána már kifogástalanul működik.

#### A hiba reprodukálás lépései pontokba szedve
1.) érd el az 1500-as Herblore szintet
2.) kezd el aratni a beért termést

#### Minecraft verzió.
* Operációs rendszer:  Win7
* Minecraft verzió: 1.11.2
* Minecraft launcher (nem kötelező): 

#### Videók, képek, mód lista és egyéb fájlok
![2017-04-17_15 16 08](https://cloud.githubusercontent.com/assets/19332825/25294135/1edf91fa-26de-11e7-8e40-bbda6e7edaad.png)

**Comment by andris155** [comment]
Ide kellene írni ezzel kapcsolatban: https://github.com/mcMMO-Dev/mcMMO/issues

**Comment by andris155** [comment]
204 OCD
