### ISSUE TITLE
Íj hiba.

### ISSUE THREAD

**Issue by DragleX** [andris155/TheOld-Crafters#591]
A Pocket Edition SkyPvP szerveren az íj nem lövi ki a nyílat.

**Comment by DragleX** [comment]
Még egy hibát találtam az ender pearl se használható.

**Comment by andris155** [comment]
Jaj ezek a javított hibák... Rosszul leszek mindjárt. 2x javítani ugyan azt. xd

**Comment by andris155** [comment]
Javítva!
Köszönjük a hibajelentést!

**Comment by andris155** [comment]
320 OCD

**Comment by DragleX** [comment]
Köszönöm. :D
