### ISSUE TITLE
Üdv

### ISSUE THREAD

**Issue by JustGame10** [andris155/TheOld-Crafters#592]
#### Minecraft verzió.

* Operációs rendszer: 
* Minecraft verzió: 
* Minecraft launcher (nem kötelező):

**Comment by JustGame10** [comment]
Üdv 
A skypvp szerveren a kezdö kitbe benne van egy lánc kalap lánc melvért meg egy lánc nadrág,de a lánc cipö helyet is lánc nadrág van és igy nincs meg a szett!
By:JustGame

**Comment by andris155** [comment]
Na ügyes voltam. xd Tanulás után​ javítom. Meg adom az OCD-t.

**Comment by andris155** [comment]
javítva, holnap tölt be

**Comment by andris155** [comment]
320 OCD

**Comment by andris155** [comment]
Majd írd le milyen névre adhatom.
