### ISSUE TITLE
Job plugin hiba, pénz farmolás lehetősége.

### ISSUE THREAD

**Issue by DragleX** [andris155/TheOld-Crafters#598]
A telefonos túlélő szerveren a fatelepen ki lehet ütni kreatív játék módban a fát, ha be van aktiválva a favágó munka a pénzt meglehet vele kapni. Ezáltal pénzt lehet vele farmolni.
-kreatív játékmód
-favágó munka aktiválása
-fa kiütése

**Comment by andris155** [comment]
Kreatívban talán még lassabb ez mint egy fejlesztett baltával, tehát ennek sok értelme nincs.
