### ISSUE TITLE
limitedCreative probléma, Survival (PE)

### ISSUE THREAD

**Issue by Fr3lly** [andris155/TheOld-Crafters#599]
Szia! Survival (PE) szerveren, az a probléma, hogy az Elit, és az Old rangosok letudják rakni creatívban az érceket. És fent ál a veszély, hogy ezt kihasználják, mivel kiütik /gm s-ben, és eladják a piacon! 
Azt szeretném kérni hogy az alábbi ID-k tiltva legyenek az Elit, és az Old rangosoknak.
ID-k:
- 14
- 15
- 16
- 21
- 56
- 73
- 129:0

**Comment by andris155** [comment]
A 129-t tiltottam. A többi eddig is volt. Kivéve a redstone ore, de az amúgy sem jó semmire, szóval azt nem tiltottam.

**Comment by andris155** [comment]
204 OCD

**Comment by Fr3lly** [comment]
Rendben. Köszi
