### ISSUE TITLE
Auction House Bug

### ISSUE THREAD

**Issue by Kyren562** [andris155/TheOld-Crafters#6]
Aukciós házban a vissza számlálónál mikor 1et számol és bidelünk automata megnyerjük az adott cuccot
![2015-12-11_16 32 18](https://cloud.githubusercontent.com/assets/12587428/11755111/55e223cc-a050-11e5-9fed-57b3bb170b27.png)

**Comment by andris155** [comment]
Ha más nem bidel, akkor meg, vagy itt mi a hiba?
