### ISSUE TITLE
Plugin ötletek a PE szerverekre.

### ISSUE THREAD

**Issue by Fr3lly** [andris155/TheOld-Crafters#601]
Szia. Szeretnék pár plugint ajánlani, ami megdobná a szerver hírességét, és többen járnának fel.
1. VoteReward: A szervernek több szavazása, illetve több játékos lenne fent, és aki 1 hónapba több szavazatot ad le, annak járna, esetleg játékpénz, és tárgyak.
2. Mentőrúd: Lehetne venni a MineMarketben, SkyPvP szerverre, illetve több támogató, és sokkal többen járnának fel! :)

**Comment by andris155** [comment]
VoteReward - nincs rá magyar oldal

**Comment by andris155** [comment]
Mentőrúd - egy másik témában már benne van.

**Comment by andris155** [comment]
https://github.com/andris155/TheOld-Crafters/issues/584
