### ISSUE TITLE
Munka hiba (PE Survival)

### ISSUE THREAD

**Issue by Fr3lly** [andris155/TheOld-Crafters#603]
Szia. (PE Survival) szerveren, ha leteszek bármilyen fát, (szabadban, telken) és joinolva vagyok a "favágó" munkába, és kiütöm kreatívban a fát, ugyan úgy megkapom a pénzt. És így bármilyen Elit, és Old rangos, kihasználhatja a problémát. A tagokkal szemben, mivel nekik nincs kreatívjuk. És ugyan ez a hiba a "Bányász" munkában.

**Comment by DragleX** [comment]
Már volt jelentve a hiba.
