### ISSUE TITLE
broadcaster hiba. (PE Survival)

### ISSUE THREAD

**Issue by Fr3lly** [andris155/TheOld-Crafters#604]
Szia. PE Survival szerveren. Az "[Információ]: Ha az épülő házadnál vagy, ill. menteni szeretnéd a jelenlegi pozíciód akkor a /sethome <otthon név> parancsot használva mentheted a pozíciódat!" 
- Az "ill."az nem kellene oda, az el lett írva.

**Comment by DragleX** [comment]
Az ill=illetve vagyis nem lett elírva csak rövidítve van.

**Comment by andris155** [comment]
De úgy elég hülyén hangzik. Szóval átírtam.
204 OCD

**Comment by andris155** [comment]
(holnap tölt be)
