### ISSUE TITLE
PE (Survival) láda megosztása hiba.

### ISSUE THREAD

**Issue by Fr3lly** [andris155/TheOld-Crafters#608]
Szia. PE (Survival) szerveren, a láda megosztása nem jó, hiába beírom hogy /pg share <<név>> és rá kattintok a ládára akkor sem jó.

**Comment by andris155** [comment]
Valaki esetleg tud rá jobb plugin-t? Láda kemence stb. levédésre?

**Comment by Fr3lly** [comment]
Jelenleg milyen van bent?

**Comment by andris155** [comment]
PocketGuard
