### ISSUE TITLE
Eltünő karaktermodellek // Survival PC.

### ISSUE THREAD

**Issue by Sanyigyerek** [andris155/TheOld-Crafters#611]
#### Hiba leírása
Időnként,de főleg teleportálások után nem megfelelően betöltött karaktermodellek.Konkrétan láthatatlanná válnak a szemem előtt más játékosok,ismerősnek is sűrűn előforduló hiba,tehát nemhiszem,hogy a számítógépemben kellene a problémát keresni.

#### A hiba reprodukálás lépései pontokba szedve
Sajnos random a hiba előfordulása,tehát nem tudom lépésekbe szedni. :/

#### Minecraft verzió.
* Operációs rendszer:   Win 7 Professional
* Minecraft verzió: 1.11.2
* Minecraft launcher (nem kötelező): Shiginima

#### Videók, képek, mód lista és egyéb fájlok
-

**Comment by andris155** [comment]
Ha jól tudom a skin váltás is bugoltatja valamilyen szinten. Mindenképp frissítsd az optifine modot, ha használsz. Illetve ha előfordul a hiba elvileg az F3+T megnyomása megoldja a hibát.
