### ISSUE TITLE
Épitész+ PE szerverekre.

### ISSUE THREAD

**Issue by Fr3lly** [andris155/TheOld-Crafters#612]
Szia. Azt szeretném kérni, hogy a PE szerverekre legyen Építész+. 
- Mivel nagyon jól építő, és aktív Építészek vannak. Akik megérdemlik a + t.
Pár joggal több kellene. 
• no.advertising.pe.bypass
• essentials.mute.exempt
• essentials.mute.use

**Comment by Mousking** [comment]
Támogatom az ötletet

**Comment by RGeri** [comment]
Támogatom az ötletet!! 👍

**Comment by NoelD10** [comment]
Támogatom

**Comment by RystenN00** [comment]
Támogatom az ötletet!

**Comment by andris155** [comment]
Építész építsen. Staff építhet, de staffkodjon is közbe,
