### ISSUE TITLE
ClearChat plugin(PE)

### ISSUE THREAD

**Issue by NoelD10** [andris155/TheOld-Crafters#613]
Szia. Javasolnám a Clear Chat plugin a pe szerverekre mivel sokan hirdetnek, és azzal könnyedén lehetne elhárítani. Ha esetleg küldjek, megteszem.

**Comment by RGeri** [comment]
Támogatom!!

**Comment by Fr3lly** [comment]
Támogatom az ötletet, könnyebbíteni a Staffok munkáját, illetve a chat nem lenne tele értelmetlen karakterekkel. És tele szerver hírdetéssel.

**Comment by andris155** [comment]
Holnap tölt be. /cc a parancs
Segítőtől elérhető

**Comment by andris155** [comment]
1016 OCD
