### ISSUE TITLE
PC Survival Információ hiba

### ISSUE THREAD

**Issue by Mousking** [andris155/TheOld-Crafters#614]
Üdv, észrevettem az automatikus hirdetésben egy kisebb hibát.
[Információ] A területet ahol, építesz MINDIG VÉDD LE! Mert különben szétrombolhatják!

Itt a vessző rossz helyen van, valamint 1 vessző hiányzik
Helyesen

[Információ] A területet, ahol építesz, MINDIG VÉDD LE! Mert különben szétrombolhatják!

~RoarSRoad

**Comment by andris155** [comment]
'§r§7A területet, ahol építesz §cMINDIG VÉDD LE§7! Mert különben szétrombolhatják!'

Így van jelenleg írva. Szerintem ez így helyes.
