### ISSUE TITLE
Block plugin, nálam elérhető

### ISSUE THREAD

**Issue by NoelD10** [andris155/TheOld-Crafters#616]
Szia, van egy pluginom ami nagyon megkönnyiteni az Épitészek dolgát, a parancsa: /block <méret> <id> ha esetleg nem találnál akkor én szívesen tudok küldeni. ˙(Facebookon elérsz.)
ezzel a pluginnal lehet köröket létrehozni, egy stick(bot) itemmel

**Comment by andris155** [comment]
Hát küld el. :D

**Comment by NoelD10** [comment]
elküldtem messengeren :D

**Comment by NoelD10** [comment]
SNoel Horváth

**Comment by NoelD10** [comment]
https://www.mediafire.com/file/iyeni4lb3wvheyx/block_MCPE14.phar

**Comment by andris155** [comment]
A neten meg sem találtam szinte. Jó lenne valami leírás vagy videó hozzá.

**Comment by andris155** [comment]
Csak a Survivalra kellene?

**Comment by andris155** [comment]
Berakva, akinek van WorldEdit van ilyen is.

**Comment by andris155** [comment]
320 OCD
