### ISSUE TITLE
SimpleMessages Hiba, (PE KitPvP.)

### ISSUE THREAD

**Issue by Fr3lly** [andris155/TheOld-Crafters#618]
Szia! PE KitPvP-n, az Infórmáció, hibásan van írva.
[Információ]: A szerverszabályzatot itt elolvashatod www.oldcrafters.net/szabalyok
Így lenne helyesen: [Információ]: A szerver szabályzatját, itt elolvashatod: www.oldcrafters.net/szabalyok

**Comment by Mousking** [comment]
Szerintem
[Információ] A szerver szabályzatját itt olvashatod el: www.oldcrafters.net/szabalyok

De a kettőspont a lényeg, ha nincs még benne

**Comment by andris155** [comment]
Van benne kettőspont, és szerintem ez így jó.
