### ISSUE TITLE
PC Survival kiírási hiba

### ISSUE THREAD

**Issue by Mousking** [andris155/TheOld-Crafters#619]
Üdv, találtam egy hibát a spawnon a rangok kiírásánál, a Tag+ jogaiban, a 2. sor 1. tábláján.
A telkeke elírás, telkek lenne helyesen.
![20170513_232556](https://cloud.githubusercontent.com/assets/25939300/26042336/c0ed51b8-3934-11e7-97cc-263a75c3224c.jpg)

**Comment by andris155** [comment]
Javítva!
Köszönjük a hibajelentést!

**Comment by andris155** [comment]
204 OCD
