### ISSUE TITLE
1vs1 plugin, (KitPvP)

### ISSUE THREAD

**Issue by Fr3lly** [andris155/TheOld-Crafters#620]
Szia. Javasolnám az 1vs1 plugint Pe KitPvP-re, feldobná a szerver hírességét, illetve többen járnának fel. Az aréna már elkészült. Ha szeretnéd akkor átküldöm a plugint.

**Comment by Crypt97** [comment]
Nem támogatom! xd

**Comment by SilterX** [comment]
Támogatom!

**Comment by DragleX** [comment]
Ötleted régebben bedobtam én is és támogatom.

**Comment by andris155** [comment]
Ez KitPvP szerver, és nem Minigame
