### ISSUE TITLE
Javaslat a játékos létszám növelésére! [PocketEdition]

### ISSUE THREAD

**Issue by Crypt97** [andris155/TheOld-Crafters#622]
# **A javaslatom a következő arra, hogy a játékosok vissza jöjjenek mivel mostanában a játékos szám óriásit csökkent.**

## Az összes kitiltás:

```
- **IP** kitiltás
- **Kliens** kitiltás
- **Név** kitiltás
```
 
### **Feloldása!**

Írta **Crypthu** Pozició: _Építész_

**Comment by andris155** [comment]
A kliens és IP tiltások feloldásra kerültek.

**Comment by andris155** [comment]
204 OCD

**Comment by Crypt97** [comment]
Köszönöm A MineMarket nevem: Crypt
