### ISSUE TITLE
Fire Charge Item, (PE)

### ISSUE THREAD

**Issue by Fr3lly** [andris155/TheOld-Crafters#623]
Szia. PE survival szerveren, észre vettem hogy a Fire Charge itemet lehet használni kreatívban, az old és az elit rangosoknak, amivel tudnak gyújtogatni. Jobb lenne ha az is LimitedCreative-ba lenne.
ID: 385

**Comment by andris155** [comment]
letiltva - holnap tölt be

**Comment by andris155** [comment]
1016 OCD
