### ISSUE TITLE
Ötlet, a weboldara.

### ISSUE THREAD

**Issue by Fr3lly** [andris155/TheOld-Crafters#624]
Szia. A weboldalon jó lenne, ha ki írná ki van fent a szervereken, illetve milyen rangúak.

**Comment by andris155** [comment]
Nem vagyok sajnos php programozó, de egyébként itt kiírja: http://www.gametracker.com/server_info/s1.oldcrafters.net:25565/

**Comment by andris155** [comment]
http://www.gametracker.com/server_info/37.17.172.57:19132/
http://www.gametracker.com/server_info/37.17.172.57:19133/
http://www.gametracker.com/server_info/37.17.172.57:19134/
