### ISSUE TITLE
OLD Sapka

### ISSUE THREAD

**Issue by Wyvorn** [andris155/TheOld-Crafters#625]
#### Hiba leírása

Az oldszettes Sapka vízaffinitás X enchant túl nagy, nem látni a víz alatt semmit benne

#### A hiba reprodukálás lépései pontokba szedve

Az enchant szint stabilizálás aminél a player még lát rendesen a víz alatt

#### Minecraft verzió.

* Operációs rendszer: win7
* Minecraft verzió: 1.11.2
* Minecraft launcher (nem kötelező): eredeti

#### Videók, képek, mód lista és egyéb fájlok

http://prntscr.com/f9dwsn

**Comment by andris155** [comment]
javítva, de a Respiration fejlesztés az okozója nem a víz affinitás, így azt levettem III-ra.

**Comment by andris155** [comment]
320 OCD
