### ISSUE TITLE
Lucky Cuccok

### ISSUE THREAD

**Issue by Lordi88** [andris155/TheOld-Crafters#626]
Üdv. Egy újabb ötletem lenne, mégpedig azért hogy a Lucky Cuccoknak kicsit fentebb tornázódjon az ára.
Hogy ez miért lenne jó?
Ritkábbak lennének a lucky cuccok, mert a mostani áruk körülbelül 20.000$-nál kezdődnek, ami valljuk be nem egy nagy összeg ahhoz képest hogy milyen enchantok vannak az adott tárgyon. (Persze, azért ha a nincs Auto disenchantere/enchantere az illetőnek és nem rakja át gyémánt felszerelésre akkor sokáig úgyse bírja a tárgy..). Ezzel nagyobb lenne az értéke, többen kezdenének esetleg maguknak gyártani Lucky Blockot.

Mit javasolok, mi az ötletem?
Ha lehetséges, nem tudom mennyire lehet konfigurálni ezt, de a Lucky Blockon belül a Lucky Itemek droppját csökkenteni. Mind a sima, mind a +80-as Lucky block esetében, 10-20%-al, vagy akár a felére csökkenteni, ezt már nem az én tisztem eldönteni (bár én olyan 20%-al csökkenteném a droppját).

-Lordi

**Comment by andris155** [comment]
Nem találtam leírást a beállításához.

**Comment by andris155** [comment]
`chance: 2`
Jelenleg erre van, de fogalmam sincs, hogy kellene ezt állítani,

**Comment by andris155** [comment]
Szerinted?

**Comment by Lordi88** [comment]
Na majd megprobalom valahogy tesztelni..Csak kellene hozza a mod.
de talan ha 1-re lenne allitva?:D

**Comment by andris155** [comment]
A bukkit plugins oldalon fent van minden, megtudod nézni te is. A szerverfájl Paper, de spigottal is működik. (1.12-vel még nem)

**Comment by andris155** [comment]
1-re állítottam. Holnap betölt.
