### ISSUE TITLE
Régi Aukció!

### ISSUE THREAD

**Issue by Lordi88** [andris155/TheOld-Crafters#627]
Üdv!
Azzal az ötlettel, felvetéssel állnék elő hogy ha van rá mód, akkor legyen visszarakva a régi licitálós Aukció (is!). 
A mostanival sincs semmi probléma, mivel ha egy játékos éppen nem tartózkodik a szerveren, akkor is tudja árulni a dolgait. Ám, nem tudom, talán saját tapasztalat, hogy ha több ember van fent, teszem azt 20-30, talán több, és a régi fajta aukciót használjuk akkor nagyobb esély van arra hogy licitálni fognak a játékosok. 
Ezzel +1-el nőne azoknak a helyeknek a listája ahol áruba lehetne bocsájtani értékeinket/tárgyainkat/bármit...
Szerintem nem volt ezzel az aukcióval semmi probléma, nekem személy szerint nagyon tetszett hogy néha konkrét licitháborúk alakultak ki, én szabhattam meg azt hogy mennyivel növekedjen a licit, mennyiért vihessék el azonnal...

/Ha esetleg nem fejlesztették  tovább a plugint vagy valami probléma volt vele akkor tárgytalan,bocsi. /

-Lordi

**Comment by andris155** [comment]
Nagyon spam-el a régebbi aukció, de egyébként működik meg magyar tárgylista is van hozzá, bár még nem frissítettem 1.12-re.
