### ISSUE TITLE
Tárgy duplikálás

### ISSUE THREAD

**Issue by TamasB14** [andris155/TheOld-Crafters#628]
Ha van enderportál és egy szamár és a szamárra teszünk ládát abba bele cuccokat és ha az enderportál alá pontosan alá pontosan 1 blokkal alá teszünk lávát(minden hova de úgy hogy ne fojjon nagyon] a szamarat pedig lesebezzük hogy fél élete legyen akkor ezután belelökjük az endbe úgy hogy sebződjön egyet és meghal akkor  belement meghalt és kidobott olyan cuccokat amiket beleraktál és ha bemész az endbe ott lesz ugyan az a szamár méghozzá él és a cuccok még egyszer benne vannak a ládájában. 

példa: https://www.youtube.com/watch?v=TpEcyXN_l_A#t=497.4575

**Comment by andris155** [comment]
Ez szerveren volt tesztelve?

**Comment by andris155** [comment]
Az End portált szélét már nem lehet kiütni.

**Comment by andris155** [comment]
2032 OCD
