### ISSUE TITLE
Építész chat üzenet színe zavaró [PocketEdition]

### ISSUE THREAD

**Issue by Crypt97** [andris155/TheOld-Crafters#629]
#### Hiba leírása
A probléma az lenne hogy Számítógépen az Építész chat üzenete ugye lila és nagyon nehezen lehet látni, hogy mit írtak a chatbe szeretném ha a rang színe maradna §9 de a chat üzenete §f lenne.

#### A hiba reprodukálás lépései pontokba szedve
Lépj be Windows 10 editionból és nézd meg egy építész üzenetét.

#### Minecraft verzió.
* Operációs rendszer: Windows 10 Home
* Minecraft verzió: Minecraft Windows 10 Edition **1.0.9**
* Minecraft launcher (nem kötelező): Eredeti

**Írta:** Crypt **Pozició:** PE Építész

**Comment by andris155** [comment]
Egyáltalán nem zavaró
