### ISSUE TITLE
Slimefun Wind staff + god mode

### ISSUE THREAD

**Issue by Linux1230** [andris155/TheOld-Crafters#631]
#### Hiba leírása:
God módban ha használjuk a wind staff-ot, akkor a kajánk ugyan úgy lemegy, de ez még nem akkora probléma. Ha ezután eszünk a kaja csík azonnal maxra töltődik akkor is ha 0n volt, teljessen mindegy mit ettünk.
(Jelenleg nem tudom tesztelni, mert nincs rangom, de amíg volt akkor még működött ez a dolog)

#### A hiba reprodukálás lépései pontokba szedve:
- /god
- repkedés wind staffal
- étel fogyasztás

#### Minecraft verzió.

* Operációs rendszer: Win10 Pro 64bit 1703
* Minecraft verzió: 1.11.2

**Comment by andris155** [comment]
Hát nem túl kompatibilis sajnos ez az Essentials-sal, de szerintem nem okoz nagyobb gondot.
