### ISSUE TITLE
IP címet jelez WorldEdit használatkor. 

### ISSUE THREAD

**Issue by teddmaci** [andris155/TheOld-Crafters#633]
WorldEdit brush probléma.

Nem tudom használni a vesszővel elválasztott ID-ket, mint pl a //br s 1:5,48,1,4 5 parancsot,mert IP-nek jelzi. 

#### Minecraft verzió.
1.11.2
A játékod, és operációs rendszered pontos verziója. A legújabb nem megfelelő válasz.
-->
* Operációs rendszer: 
* Minecraft verzió: 
* Minecraft launcher (nem kötelező):

**Comment by andris155** [comment]
javítva

**Comment by andris155** [comment]
320 OCD
