### ISSUE TITLE
Top-Kills plugin

### ISSUE THREAD

**Issue by SilterX** [andris155/TheOld-Crafters#636]
Találtam egy plugint, ami a [PE] PvP szerverekre jó lenne->
http://www.mediafire.com/file/mi5qniavwcdlvln/TopKills.zip

Úgy gondoltam, hogy a Top-Kills plugin feldobná a PE szervereken a játék élményt, ez arra való, hogy a játékosok megtudják nézni hogy, kb mennyi playert öltek meg.

**Comment by PEszem** [comment]
Remek lenne én úgy gondolom.Mindenképp kell valami újítás.

**Comment by Fr3lly** [comment]
Támogatom

**Comment by Crypt97** [comment]
Remek ötlet :D

**Comment by andris155** [comment]
Rakjátok le, ahova akarjátok.
/atp kills 
A többi részt nem fordítottam le, mivel nem nagyon látom értelmét. A halálból hülyeség szerint a top lista mivel az inkább szégyen ha valaki sokat hal meg. :D
![kepkivagas](https://cloud.githubusercontent.com/assets/8324198/26578519/75d8d32a-4530-11e7-81dc-2bc150ad37a3.PNG)

**Comment by andris155** [comment]
1016 OCD

**Comment by andris155** [comment]
Majd írd le kinek adjam.

**Comment by SilterX** [comment]
Ha lehet, akkor SKHigazi-ra

**Comment by SilterX** [comment]
Az a régi minemarket nevem

**Comment by andris155** [comment]
Sajnos a kilépés után eltűnik a felirat így az OCD visszavonva.
