### ISSUE TITLE
Slimefun Cheat

### ISSUE THREAD

**Issue by Lordi88** [andris155/TheOld-Crafters#637]
Udv. Szeretnem kervenyezni a /sf cheat nevu parancsot Adminoknak, a kozeljovoben elkeszulo slimefun warp miatt. Hogy tudjuk tesztelni a dolgokat, kiprobalni mire is jo egy egy dolog.
-Lordi

**Comment by andris155** [comment]
megadva

**Comment by andris155** [comment]
320 OCD
