### ISSUE TITLE
Pluginok

### ISSUE THREAD

**Issue by Paxelcfg** [andris155/TheOld-Crafters#638]
Helló. Javasolnál a következő pluginokat:
PE-SkyPvP-re:
- https://github.com/NightmareCybers/ClansProV6.9
- https://github.com/Muirfield/KillRate
PE-Survival
- https://github.com/Darunia18/mcpeMMO
- https://github.com/Corsad/Aution
- https://github.com/mathCodingClub/lotto
- https://github.com/Phoenix616/RandomTeleport

**Comment by andris155** [comment]
A clans nem SkyPvP szerverre való.
A Killrate-t már kérte más.
Az mcpeMMO nincs kész még.
Az Aucion nem php plugin.
A lotto plugin nincs kész, és nagyon régi.
A Randomteleport PC-re van. Nem php plugin.
