### ISSUE TITLE
McMMO hiba

### ISSUE THREAD

**Issue by asdlol911** [andris155/TheOld-Crafters#639]
#### Hiba leírása
Az MCMMO skill használata után láthatatlan lesz a játékos amíg el nem hagyja a telket, valamint a eszközkeretek is láthatatlanná válnak, amíg nem lép újra a játékos.

#### A hiba reprodukálás lépései pontokba szedve
1. Eszközkeret letéve a falra, bele egy Lucky Block.
2. Használtam a Tombolás (McMMO) képességet.
3. Láthatatlan lettem, valamint az eszközkeretek is.
4. Újraléptem és minden láthatóvá vált.

#### Minecraft verzió.

* Operációs rendszer: - Windows 7 (32bit)
* Minecraft verzió: 1.11.2
* Minecraft launcher (nem kötelező): Shiginima Launcher SE v3.100, TLauncher

#### Videók, képek, mód lista és egyéb fájlok
Amelyiken látható az eszközkeret, az újralépés utáni, amelyiken nem, az az mcmmo képesség használata utáni kép.
![2017-05-26_15 16 34](https://cloud.githubusercontent.com/assets/17855326/26496382/963a31a6-4227-11e7-829c-87b245826771.png)
![2017-05-26_15 17 17](https://cloud.githubusercontent.com/assets/17855326/26496383/9643fd44-4227-11e7-8f3c-708b7baa0851.png)

**Comment by andris155** [comment]
Ide kellene írni ezzel kapcsolatban: https://github.com/mcMMO-Dev/mcMMO/issues
Ha írtál, akkor tudjuk megadni az OCD-t.
Szerver verzió: Paper build 1104 (MC: 1.11.2)
