### ISSUE TITLE
HealthBar plugin

### ISSUE THREAD

**Issue by Fr3lly** [andris155/TheOld-Crafters#640]
Üdv! Javasolnám az alábbi plugint SkyPvP-re!
Hogy miért is jó ez? A játékos skine felett mutatná hogy mennyi élete van még.
Letöltő link: http://forums.pocketmine.net/plugins/healthbar.742/
~ Frelly

**Comment by andris155** [comment]
Nem túl valóságos, és kicsit csalás is szerintem. Rontja a játékélményt.
