### ISSUE TITLE
S3-S4-S5 Alias

### ISSUE THREAD

**Issue by NoelD10** [andris155/TheOld-Crafters#642]
Szia kellene egy Alias plugin. Könnyebben meg lehetne találni a multiaccos embereket:
http://forums.pocketmine.net/plugins/alias.260/
Előre is köszönöm

**Comment by andris155** [comment]
1016 OCD
holnap tölt be.
https://github.com/ZacHack/Alias/blob/master/plugin.yml
segítőtől elérhető
