### ISSUE TITLE
Birka le nyirás csalás.

### ISSUE THREAD

**Issue by TamasB14** [andris155/TheOld-Crafters#643]
Ha egy birkát megölünk akkor holtan még le lehet nyirni. az az hogy ha megöljük kapunk gyapjút és ha még amikor meghalt de még nem tünt ell még le tudjuk nyirni!

**Comment by andris155** [comment]
Nem tudom minek a hibája, de a gyapjú nem sokat ér. Vannak fontosabb hibák is most, amikre az időmet szánom.

**Comment by andris155** [comment]
204 OCD
