### ISSUE TITLE
topmoney

### ISSUE THREAD

**Issue by NoelD10** [andris155/TheOld-Crafters#648]
Szia, meg lehetne oldani a topmoney parancsot, a piacot úgy is újítjuk PE-n és újra rakjuk az összes táblát, kérhetném hogy javítsd? Előre is köszönöm

**Comment by andris155** [comment]
javítva, nem kell táblázni

**Comment by andris155** [comment]
508 OCD

**Comment by NoelD10** [comment]
Köszi :3
