### ISSUE TITLE
Plugin

### ISSUE THREAD

**Issue by NoelD10** [andris155/TheOld-Crafters#649]
Szia, lenne egy plugin ajánlatom s3-ra s4-re
Neve: LVL (sokan pvp-znek és jó lenne)
Plugin: https://www.mediafire.com/file/w5952v4q8n64hxt/PVPlevelRPG_6.8.phar
(Nincs magyarosítva)
Előre is köszönöm :)

**Comment by andris155** [comment]
Már volt tesztelve, és sokaknak nem tetszett, és bugos volt vele a prefix is.
