### ISSUE TITLE
Caps limit plugin

### ISSUE THREAD

**Issue by NoelD10** [andris155/TheOld-Crafters#652]
Szia, ez egy hasznos plugin lenne minden szerverre, mert nagyon sokan Caps-el írnak:
https://www.mediafire.com/file/3h271pcxyqrhm77/CapsLimit_v1.0.0.phar
(Nincs magyarosítva)

**Comment by andris155** [comment]
PE-re szerintem ez nem fontos, nem mindenki tudja bekapcsolni sem Androidon a ,,Caps Lock-ot".

**Comment by andris155** [comment]
330 OCD
