### ISSUE TITLE
Plugin ajánló

### ISSUE THREAD

**Issue by NoelD10** [andris155/TheOld-Crafters#654]
Szia, ajánlanék egy plugint!
Neve: Cosmetic Menu ha kell küldöm messengeren :D 

#### Minecraft verzió.

* Operációs rendszer: 
* Minecraft verzió: 
* Minecraft launcher (nem kötelező):

**Comment by andris155** [comment]
nincs lobby, így ez felesleges

**Comment by NoelD10** [comment]
Oksa, és ha építünk? :)

**Comment by andris155** [comment]
Hát nem nagyon látom értelmét ennyi szerverre jelenleg.
