### ISSUE TITLE
SG arénák beállítása

### ISSUE THREAD

**Issue by andris155** [andris155/TheOld-Crafters#66]
- [x] 10854 75 27201 - Lethezo arénája 
- [ ] 11092 80 26457 - Helder arénája
- [ ] -5591 76 5230
- [ ] 23372 70 16460

**Comment by andris155** [comment]
https://github.com/andris155/TheOld-Crafters/issues/119

**Comment by Treuce** [comment]
Helder arénája azóta sincs bent?

**Comment by andris155** [comment]
nincs

**Comment by toasttom** [comment]
Markp aréna - 23417 73 16448

**Comment by andris155** [comment]
köszi

**Comment by andris155** [comment]
Nem nyitja meg az mcedit a világot, olyan nagy...

**Comment by andris155** [comment]
beállítottam a megfelelőket.
