### ISSUE TITLE
Óriási hiba

### ISSUE THREAD

**Issue by NoelD10** [andris155/TheOld-Crafters#663]
Ha valakin enchantolt szett van és magasról  leesik akkor particle bugg lesz és a közelében lévő emberek inventorija eltűnik.

**Comment by andris155** [comment]
Azt hiszem ezek a fejlesztők nem tudnak nagyon fejleszteni. xD

**Comment by andris155** [comment]
javítva

**Comment by NoelD10** [comment]
Köszönöm
