### ISSUE TITLE
Üllő + eszkozkeret addolas

### ISSUE THREAD

**Issue by Lordi88** [andris155/TheOld-Crafters#664]
Udv. 
Ket bugot hoztam ma, nem tudom voltak e mar feltuntetve. Az egyik, hogy ha leesik az ullo valahonnan ami kreaban volt lerakva,akkor az survivalban felveheto lesz.
Nagyon sok penzt lehet belole osszeszedni.

Megoldas:  Ullo eladas tiltasa a boltban.

Masik: Ha lerakunk egy eszkozkeretet es egy kőkeritest(ami csatlakozik teszem azt egy 1x2-es oszlophoz) akkor az eszkozkeret kiesik,survivalban felveheto lesz.

-Lordi

**Comment by andris155** [comment]
Az elsőt megtudod oldani szerintem. :D
A második nem lehetséges, mivel kreatívban nem lehet eszközkeretet lerakni.

**Comment by Lordi88** [comment]
Ezt egy jatekos jelentette amugy, Levytheking csak nem tudott ide irni :/
