### ISSUE TITLE
PE SkyPvP Építész

### ISSUE THREAD

**Issue by Mousking** [andris155/TheOld-Crafters#665]
Üdv.
A PE SkyPvP szerveren az Építészeknek nincs LimitedCreative, tudnak másokat ölni illetve felvenni eladobott itemeket kreatívban, valamint Építészeknek BanItem be kellene (ha van rangra leosztható lehetőség) a láva és a tábla.
~RoarSRoad / ~MousX

**Comment by Crypt97** [comment]
Hát ha nekem Limited Kreám lesz felmondok XD én úgy tuti nem építek kinem állomxd

**Comment by Fr3lly** [comment]
Nem támogatom, a LimitedCreative-t az építészeknek.

**Comment by andris155** [comment]
javítva
1016 OCD
