### ISSUE TITLE
Tiltott szavak/nevek (PE)

### ISSUE THREAD

**Issue by Fr3lly** [andris155/TheOld-Crafters#666]
Üdv.
A PE szervereken, tiltva van a, Viol, Anett, Emerald, Fly, szavak/nevek.
Törölni kellene, a tiltott szók istájából. Köszönöm.

**Comment by Fr3lly** [comment]
Ja, és még a Lion.

**Comment by Mousking** [comment]
![screenshot_20170603-163312](https://cloud.githubusercontent.com/assets/25939300/26754405/60c00056-487a-11e7-9b70-94e6ff061843.png)

**Comment by Mousking** [comment]
Beírtam mindet, egyiket sem engedi.

**Comment by Crypt97** [comment]
Én is igazolom hogy tényleg ezt írja a fent megadott nevekre.

**Comment by Fr3lly** [comment]
![screenshot_2017-06-04-12-45-23](https://cloud.githubusercontent.com/assets/26357505/26760909/0a0056c6-4924-11e7-8837-b16bf162d24f.jpeg)

**Comment by Fr3lly** [comment]
Megoldva.

**Comment by Fr3lly** [comment]
![screenshot_2017-06-04-12-52-00](https://cloud.githubusercontent.com/assets/26357505/26760934/dfbd836a-4924-11e7-92d9-db778943744e.jpeg)

**Comment by Fr3lly** [comment]
![screenshot_2017-06-04-12-52-00](https://cloud.githubusercontent.com/assets/26357505/26760938/06a38344-4925-11e7-8cb5-eec1825e3abf.jpeg)

**Comment by Fr3lly** [comment]
Megoldva.
