### ISSUE TITLE
PE Figyelmeztés elírás

### ISSUE THREAD

**Issue by Mousking** [andris155/TheOld-Crafters#667]
![screenshot_20170603-163312](https://cloud.githubusercontent.com/assets/25939300/26754446/4b80d64c-487b-11e7-9cfa-34c458e4c962.png)
Üdv. A PE szerveren a Gyors chat figyelmeztetés el van írva, Figyelmeztetés lenne helyesen a mondatban

**Comment by andris155** [comment]
Javítva. Holnap tölt be.

**Comment by andris155** [comment]
204 OCD
