### ISSUE TITLE
StaffChat plugin (kérelem) [PocketEdition]

### ISSUE THREAD

**Issue by Crypt97** [andris155/TheOld-Crafters#668]
Üdv szerintünk jó lenne ha lenne a szerveren saját staffchat amit csak a staffok látnak persze ezt egyszerűen belehet állítani a pluginban mivel van permje hozzá!

Ha érdekel téged is itt a Link: https://github.com/ThunderDoesPlugins/StaffChat

Nem elhanyagolt plugin :D 4 napja volt frissítve!

**Comment by NoelD10** [comment]
Támogatom! :)

**Comment by andris155** [comment]
Beraktam, holnap tölt be. Majd teszteljétek nekem most nincs 1.0.9-es verzióm.

**Comment by andris155** [comment]
508 OCD

**Comment by Crypt97** [comment]
Crypt97  a nevem már minemarket és koszi
