### ISSUE TITLE
SkyPvP&KitPvP Enchantolt kezdő kit!

### ISSUE THREAD

**Issue by Fr3lly** [andris155/TheOld-Crafters#669]
Üdv. 
Azt szeretném kérni, hogy a kezdő kit enchantolt legyen, persze ha megoldható.
Nem kérek, olyan nagy enchantot rá. Ezzel azt szeretném elérni, hogy a rangosok, és a tagok közt,
meglegyen az egyensúly, kiegyenlőtebbek legyenek a harcok. 
Talán, megjönne a játékosoknak, a kedvük, egy kis harchoz, és KitPvP-re is járnának fel.
Enchantment:
Szett: Bane Of Arthropods III, protection I
Kard: Smite 3
- Fr3lly

**Comment by Crypt97** [comment]
Támogatom! 🗡

**Comment by ChorsyumX** [comment]
Támogatom!

**Comment by andris155** [comment]
elvetve
1.1-ben elvileg lehet már enchantolni majd.

**Comment by SilterX** [comment]
Támogatom!
