### ISSUE TITLE
Pe Hiba

### ISSUE THREAD

**Issue by Fr3lly** [andris155/TheOld-Crafters#671]
Üdv!
Pe survival szerveren, a Moderátor rang-nak, nincs limitedcreativba, a Tojás, le lehet rakni, bármilyen mobot.

**Comment by Crypt97** [comment]
bezeg az építész -.-" xd

**Comment by andris155** [comment]
Ez lehetetlen. Akkor az a Moderátor lehet op jogokkal rendelkezik.
