### ISSUE TITLE
PE Próbahetes ÉP és ÉP+ rangok

### ISSUE THREAD

**Issue by Mousking** [andris155/TheOld-Crafters#673]
Üdv.
Javasolnék 2 rangot a PE szerverekre, az egyik a Próbahetes Építész, a másik pedig az Építész+ rang lenne.
Javaslatok a Próbahetes Építész rang jogosultságaira: 
-A sima Építészen alapuló rang
-WorldEdit nélküli rang
-LimitedCreative
Előnye:
Itt főleg a WE nélküliségnek lenne szerepe, mivel nagy hatalmat kapna vele egy próbahetes Építész.

Javaslatok az Építész+ rang jogosultságaira:
-A sima Építészre épülő rang
-LimitedCreative nélküli rang
-(Hogyha van a sima Építész rangban) BanItem nélküli rang
Előnye:
Végre az Építészek is kaphatnának előléptetést,  és valamivel fejlettebb rangot.

Bárki szeretne, javasolhat még a 2 rangötlettel kapcsolatban jogokat.

~RoarSRoad / ~MousX

**Comment by ChorsyumX** [comment]
Támogatom!

**Comment by Crypt97** [comment]
Imádolom <3

**Comment by Mousking** [comment]
Esetleg ha még lehetne, akkor tp láthatósági jogot a sima Építésznek és az Építesz+ nak.

**Comment by andris155** [comment]
megvalósítva - holnap betölt

**Comment by andris155** [comment]
2032 OCD
