### ISSUE TITLE
Rang ajánló

### ISSUE THREAD

**Issue by NoelD10** [andris155/TheOld-Crafters#674]
Szia, szeretnénk ha lenne Tag+ rang survivalon.
Ezekkel a plusz jogokkal:
-1 telek
-50.000$
Remélem elfogadod, sokan szeretnénk.
(320OCD-be kerülhetne :D)

**Comment by Crypt97** [comment]
Támogatom eme becslésre méltó ötletett!!!

**Comment by andris155** [comment]
Jelenleg a fly van ott a Tag+ helyett.
