### ISSUE TITLE
PE Elittől színes nick lehetőség

### ISSUE THREAD

**Issue by Mousking** [andris155/TheOld-Crafters#676]
Üdv.
Szerintem egy jó ötlet lenne, ha a PE szerverekre Elit rangtól elérhető lenne a színes nick változtatása/választása.
~ RoarSRoad

**Comment by Proverload** [comment]
Támogatom.

**Comment by hunbest** [comment]
Támogatom

**Comment by Crypt97** [comment]
Tomogatom  +5000$-al!!!!!

**Comment by andris155** [comment]
PE-n át lehet változtatni a nevet is. Nincs olyan beállítás, hogy csak színezés.
