### ISSUE TITLE
textúra hiba kihasználható x-ray formájában

### ISSUE THREAD

**Issue by JustS4U** [andris155/TheOld-Crafters#677]
Szia!

Az alábbi technikát osztanám meg, ami elég csúnyán kihasználható előnyszerzéshez.
A módszer célja, hogy textúrabetöltési hibát kihasználva átlátunk a földön, megnézve rajta keresztül az érceket, járatokat, erődöket.
hozzávalók: 1 sín, 1 csille, 1 lomb /sövénynyíró és csákány/

Módszer:
Le kell ásni a föld alá /de sokszor a felszínen ásás nélkül is működik/ egy 2x1-es mezőt kialakítva. Következik sín lerakása majd rá a csille, fölé a lomb és bele kell ülni a csillébe. Ekkor át lehet látni a falakon és minden láthatóvá válik /ércek, mobok, ládák, ketrecek, járatok és erődök/. Ha nem minden irányban lehet körbenézni vagy épp adott helyen nem működik, meg lehet ismételni kicsit arrébb és már megy is a "cheat". Videón láttam ezt a glitch-et, kipróbáltam és nagyon hatékony, így nagyon jól kihasználható.

Köszönöm a figyelmet!
JustS4U

**Comment by andris155** [comment]
videó kellene erről

**Comment by JustS4U** [comment]
Szia Andris!

Készítettem egy videót a jelenségről. Nem a legjobb, mert még nem csináltam, de minden látszik rajta.

https://www.youtube.com/watch?v=Cq4mxgWEIZQ

**Comment by andris155** [comment]
Engedélyezett csalás
