### ISSUE TITLE
Survivalos cuccok eltűnése

### ISSUE THREAD

**Issue by Kelvin172** [andris155/TheOld-Crafters#679]
Rejtélyes módon eltűntek a survivalos dolgaim, úgy hogy ,,néző" játékos módból csatlakozni lehet survival games-re és a mobarénákba, utána kiléptem és játékos mód váltás után eltűnnek.

**Comment by andris155** [comment]
A staffok csak tudnak figyelni milyen módban hova lépnek be. :D
