### ISSUE TITLE
Rang ajánló PE szerverekre!

### ISSUE THREAD

**Issue by Fr3lly** [andris155/TheOld-Crafters#681]
Üdv!
Szeretném, ha a PE szervereken a FőAdmin színe, nem §4-es hanem §c-s lenne.
Mint PC-n. Mivel, egy színű az Olddal, ezáltal zavaró a chatbe való írás.
~ Fr3lly

**Comment by andris155** [comment]
PC -> PE
Holnap betölt.

**Comment by andris155** [comment]
320 OCD
