### ISSUE TITLE
World hiba (EssentialsPE) [PocketMine]

### ISSUE THREAD

**Issue by Crypt97** [andris155/TheOld-Crafters#682]
Az lenne a probléma hogy az event worldnek a mappa és a level.dat neve nem egyezik így az EssentialsPE nem tudja elmenteni a homeokat se a warpokat!

- Tipp: A _level.dat_-ban az **NBTExplorer** a megfelelő hogy lehesen javítani a world nevét! :D

**Comment by Fr3lly** [comment]
Igaz.

**Comment by andris155** [comment]
javítva

**Comment by andris155** [comment]
204 OCD
