### ISSUE TITLE
Chunk betöltési hiba.

### ISSUE THREAD

**Issue by TaroTOC** [andris155/TheOld-Crafters#684]
Ha nem a levédett zóna területén belül tartózkodsz,és odamész a sethomeod segítségével esetenként átbuggolsz dolgokon,mert a chunk nics betöltve és setenként a nemkívnt személek használatba tudják venni mások zárt xp farmjait stb.(Ez a chunk betöltési bugg akkor is érvényes ha akkor lépsz be és kilépéskor a területén tartózkodtál,csak akkor a földbe buggolsz bele,és kickel fly miatt.

**Comment by andris155** [comment]
Már jelentett hiba.
