### ISSUE TITLE
Petes átbuggolás blockokon

### ISSUE THREAD

**Issue by TaroTOC** [andris155/TheOld-Crafters#685]
Ha a pet pcstjét lovaglásra állítod,és megidézed  úgy hogy az adott blockokon kivulre tegye (könnyen kiüthető blockok) és a kitütés után rá kattolsz a petre lasszóval átbuggolhatsz mások elzárt területére,stb.

**Comment by andris155** [comment]
Ezt én sajnos nem tudom javítani.
