### ISSUE TITLE
Teljes invertory mozgatása

### ISSUE THREAD

**Issue by JustS4U** [andris155/TheOld-Crafters#686]
Szia!

Eddig ha hasonló dolgokat akartam áttenni mondjuk egy ládából a saját invertorymba vagy vissza akkor elég volt 1 darabot abból a kezemben tartanom, majd a következő hasonló dologra duplán klikkelni miközben lenyomva tartom a shift-et és akkor az összes ugyanolyan tárgy átkerült az egyik helyről a másikra. Már nem működik. Ha próbálkozok vele akkor átrak 6 stacket, de 5-öt vissza is tesz az eredeti helyére.

Kösz a figyelmet

**Comment by Wexthory** [comment]
Ez azert van, mert a szerver meg 1.11-be fut, de te 1.12-be vagy fent. En is tapasztaltam es nemi probalkozas utan jutottam erre a megoldasra.
