### ISSUE TITLE
Skinváltás hiba.

### ISSUE THREAD

**Issue by TaroTOC** [andris155/TheOld-Crafters#689]
Mielőtt a ./skin használatval a tetszőleges skint betöltené a szerverröl kidob a proxy,és nemvált skint sem egyből,hanem csak sokadik probálkozás után.
Minden játékosnál problémát okoz!!

**Comment by andris155** [comment]
Világ váltás után egyből betölt a váltott skin. A kidobás hiba lehet az 1.12-es verzió támogatás hibája. Használd a régebbi 1.11.2-t egyelőre.
