### ISSUE TITLE
Kihasználható bugok

### ISSUE THREAD

**Issue by Levytheking** [andris155/TheOld-Crafters#693]
A rangosokra vonatkozik inkább akiknek van creájuk. lerakunk egy fél blockok és 4 magaságra felépítünk mellete egy oszlopot. amit felépitettünk oszlop oldalára a fél block felé a magas oszlop oldaláról ejtsünk le bármi homokot, bármifélét ami leesik. (pl.: homok, üllő...). ugye ha ezt megépitjuk kreában akkor ki dropolja úgy hogy az már nem creás block.

**Comment by andris155** [comment]
már jelentett hiba
