### ISSUE TITLE
AZ 1.11-es PE szerveren hibákat találtam

### ISSUE THREAD

**Issue by FinickyLace2785** [andris155/TheOld-Crafters#699]
1.Először is nem lehet szines ágyat krfatolni vagy szinezni.
2.Létrán nem lehet mászni.
3.A fatelepen nem lehet fát ki ütni az arra kijelölt helyen .
4.Az ágyak egy idő után buggolnak láthatatlanok lesznek.

A játékos és Minemarket nevem: FinickyLace2785

**Comment by Fr3lly** [comment]
Üdv!
1. A színes ágy még nincs teljesen benne a szerver fájlba.
2. Már lehet létrán mászni.
3. A fatelep már meg lett oldva. /warp fatelep
4. Azért buggolnak el. Mert levédett helyre tetted.

**Comment by FinickyLace2785** [comment]
saját telkemre tettem a színes ágyat

kocsisbenjamin@gmail

2017.06.16. 11:20 ezt írta ("Fr3lly" <notifications@github.com>):

**Comment by Fr3lly** [comment]
Kellene videó róla. Mert ez így igazolatlan hiba.

**Comment by Crypt97** [comment]
Fr3lly tényleg így van már tapasztaltam ez azért van mert nincsenek bent az ágyak színei :D

**Comment by FinickyLace2785** [comment]
Na valaki igazat adott!

2017-06-16 18:25 GMT+02:00 Crypt97 <notifications@github.com>:
