### ISSUE TITLE
Lockette Ajtó Bug

### ISSUE THREAD

**Issue by Kyren562** [andris155/TheOld-Crafters#7]
Ha valaki sokszor kattol az ajtóra egy ideig azt írja hogy le van véde utána szabad útja van átmenni , de vissza bugol... az ajtóba ha átmegyünk rajta akkor már bug nélkül át tudunk menni 
![2015-12-11_21 47 30](https://cloud.githubusercontent.com/assets/12587428/11755212/079cb69a-a051-11e5-9fa4-bb6b5872d4b6.png)
![2015-12-11_21 47 25](https://cloud.githubusercontent.com/assets/12587428/11755213/07aa2a14-a051-11e5-87cc-8da95aacc3c3.png)

**Comment by andris155** [comment]
Erről videó kellene.

**Comment by andris155** [comment]
Csinálsz róla videót?

**Comment by andris155** [comment]
Elvileg javítva:
- monkyslockette cserélve deadboltra.

**Comment by embervagyok2** [comment]
ciganykurvak anyatok roman szorostalpu fasszopo fereg patkany gecik tetves fasszopo @Shryxx anyadat basszam teherbe ukran vendegmunkas @andris155
