### ISSUE TITLE
Addolható a sóder (hasznos a slimefunban!)

### ISSUE THREAD

**Issue by Kayalafur** [andris155/TheOld-Crafters#702]
Teszteltem, mert volt egy gyanúm! (1 db on XD )

Kreatívban leteszek egy fáklyát fölé egy bármilyen blokkot, fölé teszel egy sóder sort, majd kiütöd a blokkot. Így lehullik a sóder, és a fáklya széttöri, ezt csak surviban tudod felvenni. Így végtelen mennyiségű sódert tudsz szerezni amiből rengeteg slimefun dust készíthető.

**Comment by Mousking** [comment]
#185

**Comment by andris155** [comment]
Már jelentett hiba.
