### ISSUE TITLE
S3 biome hiba

### ISSUE THREAD

**Issue by Proverload** [andris155/TheOld-Crafters#704]
Telekvilágban ha valaki Biomet állít át,restartol a szerver,minden egyes alkalommal.Imore jelezte a hibát

**Comment by Crypt97** [comment]
Javaslom a /biome parancs törlését a telek pluginban mivel amúgy se müködik!

**Comment by Crypt97** [comment]
Vagy csak permet kell tiltani azt cső xd

**Comment by andris155** [comment]
Javítva!
Köszönjük a hibajelentést!
