### ISSUE TITLE
Új szabad járművek. 

### ISSUE THREAD

**Issue by DragleX** [andris155/TheOld-Crafters#705]
Az új szabadban a járműveket (repülő-t néztem meg) nem engedi lerakni.
![2017-06-18_15 50 15](https://user-images.githubusercontent.com/25017718/27261034-31f66810-543b-11e7-88de-f7e5ab3e0f86.png)

**Comment by andris155** [comment]
javítva, holnap betölt

**Comment by andris155** [comment]
320 OCD
