### ISSUE TITLE
Pc, slime fun, elektromos spawner

### ISSUE THREAD

**Issue by Wexthory** [andris155/TheOld-Crafters#706]
Az elektromos wither skeleton spawner sima skeletonokat spawnol. A netherben levo dungeonban is ki lett probalva.

**Comment by Wexthory** [comment]
+ nem lenne rossz, ha mondjuk torott ocelot stb spawnert lehetne venni OCD-be vagy oldgoldba, ha mar elektromos is van.

**Comment by andris155** [comment]
És mennyi OCD-t ér mennyi spawner?

**Comment by Levytheking** [comment]
Kb 320 OCD 2 spawner mert szerintem ez így magyon megérné

**Comment by Wexthory** [comment]
320/spawner akkor, hiszen mégse lehet másképpen megszerezni és akinek kell az úgy is szerez rá OCD-t.

**Comment by andris155** [comment]
330 OCD
