### ISSUE TITLE
Munka plugin fejlesztése/javítások [PocketEdition]

### ISSUE THREAD

**Issue by Crypt97** [andris155/TheOld-Crafters#707]
![19397732_778641875630721_842468659_n](https://user-images.githubusercontent.com/28710769/27303705-f392ebe6-553b-11e7-87ea-ad6fba810028.png)

46:0 a TNT ID-je és nem értem mit keres a bányásznál! :D 25$/tnt kiütés?! xd

**Comment by andris155** [comment]
```
---
favágó:
  17:0:break: 15
  17:1:break: 15
  17:2:break: 15
  18:3:break: 15
  162:0:break: 15
  162:1:break: 15
bányász:
  1:0:break: 15
  4:0:break: 15
  46:0:break: 25
faültető:
  6:0:place: 5
  6:1:place: 5
  6:2:place: 5
kertész:
  391:0:place: 10
  392:0:place: 10
  369:0:place: 10
  295:0:place: 10
  361:0:place: 10
  458:0:place: 10
...
```
Nincs kedved segíteni fejleszteni? Ez így elég gagyi jelenleg.

**Comment by Crypt97** [comment]
de van :D

**Comment by Crypt97** [comment]
adok hozzá fa blockot meg érc blockot

**Comment by Crypt97** [comment]
---
favago:
  17:0:break: 15
  17:1:break: 15
  17:2:break: 15
  18:3:break: 15
  162:0:break: 15
  162:1:break: 15
banyasz:
  1:0:break: 10
  4:0:break: 10
  13:0:break: 10
  14:break: 25
  15:break: 20
  16:break: 15
  56:break: 35
faulteto:
  6:0:place: 5
  6:1:place: 5
  6:2:place: 5
  6:3:place: 5
  6:4:place: 5
  6:5:place: 5
kertesz:
  391:0:place: 10
  392:0:place: 10
  362:place: 15
  296:place: 10
  372:0:place: 15
  361:0:place: 10
  458:0:place: 10
  351:0:place: 15
...

Minden jó és finomság hozzá lett adva ami csak kell :D

**Comment by Crypt97** [comment]
+ ki töröltem a lángrudat a TNT-t és a kész búzát xddd

**Comment by Crypt97** [comment]
---
favago:
  17:0:break: 15
  17:1:break: 15
  17:2:break: 15
  17:3:break: 15
  162:0:break: 15
  162:1:break: 15
banyasz:
  1:0:break: 10
  4:0:break: 10
  13:0:break: 10
  14:break: 25
  15:break: 20
  16:break: 15
  56:break: 35
faulteto:
  6:0:place: 5
  6:1:place: 5
  6:2:place: 5
  6:3:place: 5
  6:4:place: 5
  6:5:place: 5
kertesz:
  391:0:place: 10
  392:0:place: 10
  362:place: 15
  296:place: 10
  372:0:place: 15
  361:0:place: 10
  458:0:place: 10
  351:0:place: 15
...

- **Törölve:** _lángrúd, TNT, kész Búza, 1db levél a favágónál mivel a favágó nem foglalkozik a levelekel!_
- **Hozzá adva:** _több ültethető fa, magok, fatörzs, ércek_

## + **ékezetek törölve mivel így könyebb beírni telefonról.**

**Comment by andris155** [comment]
javítva

**Comment by andris155** [comment]
1016 OCD
