### ISSUE TITLE
VoxelSniper, FastAwe teszt, és beüzemelés

### ISSUE THREAD

**Issue by teddmaci** [andris155/TheOld-Crafters#708]
Folyamatos világrombolás helyreállítása, gyors tájrendezés, és hatalmas segítség teddmelknek. Minőségi munka nélküle nem végezhető, így javaslom a mihamarabbi behelyezését a szerverre.

**Comment by andris155** [comment]
kész

**Comment by andris155** [comment]
5080 OCD

**Comment by Levytheking** [comment]
Lol
