### ISSUE TITLE
PC Slimefun kiegészítés

### ISSUE THREAD

**Issue by Mousking** [andris155/TheOld-Crafters#709]
Üdv. Ajánlani szeretném a PC Survival szerverre a Slimefun Barrels-t. Jelenleg ha valakinek van 20000 köve, hatalmas tárolókat kell építenie, hogy elraktározza. Egy slimefun Barrellel mindössze 1 blockban több ezer/több tízezer blockot lehet eltárolni, ugyanúgy automatikusan lehet bele tölteni a cuccokat, mint egy sima chestbe.

Link:

https://dev.bukkit.org/projects/slimefun-barrels

**Comment by andris155** [comment]
Berakva. Holnap betölt.

**Comment by andris155** [comment]
204 OCD
