### ISSUE TITLE
Slimefun italok

### ISSUE THREAD

**Issue by TamasB14** [andris155/TheOld-Crafters#710]
A slimefun italok nem töltenek étel csíkot!

**Comment by andris155** [comment]
Nem levédett, és nem telkek területen sem?

**Comment by Levytheking** [comment]
Megnéztem azon sem

**Comment by TamasB14** [comment]
Még levédetlen helyeken sem töltenek
2017.06.20. 23:10 ezt írta ("Marczinkó András" <notifications@github.com>):

**Comment by Tyloendis** [comment]
ha minihűtőbe berakod őket, akkor töltenek. Úgy is az a legjobb kaja, automatán megiszod őket :D

**Comment by TamasB14** [comment]
Milyen mini hűttő?¿?
2017.06.29. 17:22 ezt írta ("Tyloendis" <notifications@github.com>):

**Comment by Levytheking** [comment]
cooler

**Comment by andris155** [comment]
https://github.com/TheBusyBiscuit/Slimefun4/issues/87
