### ISSUE TITLE
Nem tudok felmenni a PE szerverekre 

### ISSUE THREAD

**Issue by FinickyLace2785** [andris155/TheOld-Crafters#711]
Nem tudok felmenni a PE szerverekre  jó IP  írtam a Survival ra akartam felmenni !
Ip:s3.oldcrafters.net.  PORT:alap

**Comment by Crypt97** [comment]
1.1.0.55 vagy 1.1.1.151-es verzóval probálkozz!

**Comment by andris155** [comment]
1.1.1.51 vagy .1.1.1.151-es verzió kell hozzá.
