### ISSUE TITLE
PE survival moderátor jog (give)

### ISSUE THREAD

**Issue by SilterX** [andris155/TheOld-Crafters#718]
Szia!
Lenne egy kérésem, azzal kapcsolatban, hogy a PE survival szerverre vissza tudnád-e a moderátor ranghoz rakni a give jogot?

Hogy miért is? Azért, mert régebben megvolt, csak ma giveoltam volna vizet, és nem engedte szerintem eltünt.

Szerintem az építész rang permjei össze lettek cserélve a segítő rang permjeivel, és a moderátor permjeivel, mert az Építész rang tud kickelni, giveolni, és némítani (muteolni) és az építész rangnak nincsen WE joga

**Comment by andris155** [comment]
Az építész-nek nincs WE jog csak az építész+-nak. A Moderátor kapott limitedcrative nélküli engedélyt
