### ISSUE TITLE
PE survival moderátor jog (nick)

### ISSUE THREAD

**Issue by SilterX** [andris155/TheOld-Crafters#720]
Szia!

Lenne egy kérésem, hogy vissza tudod-e rakni a moderátor rangnak a /nick jogot?

Hogy miért is? Azért, mert múltkor még megvolt, és szerintem jó, ha egy moderátor tud nickelni, pl ha egy segítő-t kell, és nicns fent nagyobb rangos, csak egy moderátor, és adnék neki, ha kérne.

**Comment by andris155** [comment]
kész

**Comment by andris155** [comment]
204 OCD
