### ISSUE TITLE
Pet és Levédett "helyi" Redstone

### ISSUE THREAD

**Issue by TamasB14** [andris155/TheOld-Crafters#721]
Ha a pet rálép valami redstone-os szerkezetre levédett "helyen" akkor ő be tudja aktiválni de a játékos nem.

**Comment by andris155** [comment]
Sajnos a mob-tól nem tudok jogokat lekérni, hogy neki most van-e jog vagy nincs. A pet tulajt lehetne lekérni, de a WorldGaurd nem támogatja a MyPet-et sajnos.
