### ISSUE TITLE
MisteryBoy plugin PE SkyPvP szerverre

### ISSUE THREAD

**Issue by SilterX** [andris155/TheOld-Crafters#723]
Szia!

Találtam egy jó plugint, ami a SkyPvP szerverre jó lenne szerintem.

Plugin:http://www.mediafire.com/file/6bp5umjz0egy5p5/MisteryBox.phar

Hogy miért is lenne, ez jó, és hogyan kell használni? Szerintem jobb lenne a játékélmény, azért, mert lehet cserélgetni? Hogy mivel is? Fogsz egy emerálot a kezedbe, és rá kattíntasz egy chestre (ládára) és lesznek benne enchis cuccok, op, kard, stb ezt a plugint azért gondoltam SkyPvP-re, mert ott mindig van emeráld kereső event, és úgy tudnának keresni emeráldot, és elcserélnék valamire, ha rányomnak a chestre.
Survival-ra azért nem ajánlom, mert ott napiszinten lehetne cserélgetni, mert sok mindenkinek van ott emeraldja.

**Comment by NoelD10** [comment]
Támogatom! Nagyon jó lenne

**Comment by andris155** [comment]
Ez most hogy működik?

**Comment by SilterX** [comment]
Szia! 
Ez úgy működik, hogy a kezedbe veszel egy emeráldot, és rá kattintasz egy ládára, és benne lesznek cuccok, amiket beválthatsz 1 emeráldra.

**Comment by andris155** [comment]
Videót nem tudsz róla készíteni?

**Comment by Fr3lly** [comment]
Megnéztem a plugint, nincs konfigja.
