### ISSUE TITLE
PE próbahetes építész rang (fejlesztése)

### ISSUE THREAD

**Issue by Fr3lly** [andris155/TheOld-Crafters#725]
Üdvözletem! Javasolnám, hogy a PE próbahetes építész rang ne tudjon rombolni levédett területen.
A Tulaj és a FőÉpítész engedélyével.
Pozíció: |FőAdmin|~Fr3lly
Köszönöm!

**Comment by andris155** [comment]
megvalósítva

**Comment by andris155** [comment]
204 OCD
