### ISSUE TITLE
PE Építész TGF Űrlap

### ISSUE THREAD

**Issue by Fr3lly** [andris155/TheOld-Crafters#726]
Szia. Elkészítettem, egy TheOld - Crafters PE Építész kérdőiv űrlapot.
Mivel már van próbahetes Építész rang, ezért gondoltam, jó lenne egy TGF-es űrlap.
A Tulaj, és a FöÉpítész jónak látta, (tetszik nekik az ötlet) illetve, engedélyt is adtak az oldal publikására, ha te is beleegyezel. Illetve, a FőÉpítész és a Tulaj, persze a FőTulajdonos is kapna jogosultságot a válaszok megtekintésére. Facebook-on linkeltem az oldal kitöltési linkjét.
Illetve javasolnám az Építész TGF-es kitöltési űrlapjának a linkjét, a http://oldcrafters.net/tgfvalasztas
hozzáadásához. Köszönöm!
Pozíció: |FőAdmin|~Fr3lly

**Comment by andris155** [comment]
kész

**Comment by andris155** [comment]
320 OCD
