### ISSUE TITLE
Auction plugin,Bansystem és Enchant shop Plugin

### ISSUE THREAD

**Issue by Paxelcfg** [andris155/TheOld-Crafters#729]
------------------------------------------------(Pluginok)--------------------------------------------------
https://github.com/JunkDaCoder/AuctionHouse
https://github.com/Derpasaurous596/Enchant-Shop
https://github.com/randy128gamer/BanSystem-PocketMine
--------------------------------------------------(Ajánlat)---------------------------------------------------
A Bansystem plugint azért ajánlom, mert amikor bannolva vagy és csatlakozni akarsz másodperc pontosan kiírja a hátralévő időt. A jelenleg ha ban kör csatlakozni akarsz annyit ír Bannolva vagy sem időt sem indokot.
Másképp ha hacker jön fel és banbol mindig vissza jön akkor /block és nem tud mozogni sem :D 
---------------------------------------------------(Vége)-----------------------------------------------------

**Comment by andris155** [comment]
A soppos szerintem még nincs kész. A Bansystem nem jobb mint a mostani egy indok miatt nem rakok be egy plugint.

**Comment by andris155** [comment]
Az Auction működik? Tudjátok tesztelni? A bidet eladást stb...?

**Comment by Paxelcfg** [comment]
Tudom tesztelni! Mindjárt küldök képet.

**Comment by andris155** [comment]
beraktam, holnap betölt.

**Comment by andris155** [comment]
508 OCD
