### ISSUE TITLE
Multi Tool Bug S.F.

### ISSUE THREAD

**Issue by Levytheking** [andris155/TheOld-Crafters#737]
Elmegyünk az endbe és át váltunk a Multi toolban a grapplin  hook ban és ledobjuk az endbe ezt a jobb klickbe (ez egy olyan mód amelyikbe eldob egy laszót és oda terepolátrsz ahova eldobta) és ha ledobod az endbe ezt jobb kilickel mintha oda akarsz telepotálni akkor a végtelenségbe esne de nem esik le hanem ’’elszakad’’ és kidonja lasszó formáljában. így lehet buggolttani

**Comment by andris155** [comment]
Ide kellene jelenteni a hibát: https://github.com/TheBusyBiscuit/Slimefun4/issues
Persze angolul.
