### ISSUE TITLE
Enchant bugg

### ISSUE THREAD

**Issue by RystenN00** [andris155/TheOld-Crafters#738]
Szia! A Survival PE szerveren gond van az enchantal! Amikor enchantolnak, akkor utána ki dobja a lapist és a másik itemet utána meg ha belépünk az inventoryba és ki lépünk akkor kapunk egy lapist. Ezt folyamatosan lehet csinálni, hogy ki-be lépegetünk és kapjuk a lapist. Érdemes lenne ki szedni az enchántoló asztalt.

**Comment by andris155** [comment]
Szia!
Az enchant hack miatt le van tiltva.
