### ISSUE TITLE
PE KitPvP map-->S3

### ISSUE THREAD

**Issue by Mousking** [andris155/TheOld-Crafters#739]
Üdv. Szeretném, ha a PE KitPvP map bekerülne S3-ra, rengeteg felhasználható építmény van rajta.

**Comment by andris155** [comment]
map nevet kérek.

**Comment by Crypt97** [comment]
kitpvp2

**Comment by Mousking** [comment]
kitpvp2 a map neve

**Comment by andris155** [comment]
berakva
