### ISSUE TITLE
Shulkerbox gondok

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#740]
Szia Andris!

Az utóbbi időben véltem felfedezni, illetve jelezték ezt. Szóval, több embernél is tapasztaltam, hogy ha a skulkerboxot kiüti, nem tudja felvenni mert rákerül a kreatív védelmes szöveg. Illetve ha én felveszem már üres a box tartalma. Tag által lerakott,kiütött shulkerbox.
Bug lehet?

**Comment by andris155** [comment]
Clearlore-s shulkerdobozzal tudod tesztelni.

**Comment by andris155** [comment]
Egyébként gondolom kértek kreástól. Aztán azt hitték milyen menők, hogy adoltak maguknak, aztán felszedték és rájöttek, hogy mégsem. xD

**Comment by Wexthory** [comment]
Ha olyan block helyére raksz Shulkert ahol már volt kreatívos item akkor elbuggol, de tudtommal van rá módszer, hogy visszakerüljön egy adott block oda ahol volt. UDP egy shulkeremet nekem is visszahozta valahogy.

**Comment by Wexthory** [comment]
Tényleg eltudnak buggolni survivalban lerakott shulkerek. Arra még nem jöttem rá, hogy mi okozza.

**Comment by Wexthory** [comment]
Az egyik telkemen van is egy hely, ahova ha rakok le shulkert és kiütöm kreás lesz, régebben próbálgattam ilyen helyeket hátha kitalálom a hiba okát oszt megéri jelenteni.

**Comment by andris155** [comment]
Új kreatív védelem lett. Ahol már nincs kreatívos blokk ott biztosan nem lesz már kreatívos.
