### ISSUE TITLE
Felesleges világok törlése. !!PE Staffok!!

### ISSUE THREAD

**Issue by andris155** [andris155/TheOld-Crafters#741]
SkyPvP
![kepkivagas](https://user-images.githubusercontent.com/8324198/27562095-2e11d4a0-5acb-11e7-8432-c554b27b7422.PNG)
Survival
![kepkivagas](https://user-images.githubusercontent.com/8324198/27562120-4c20523c-5acb-11e7-9fe4-b8a11ceb46b9.PNG)
Melyik világok nem kellenek?

**Comment by Crypt97** [comment]
# Törlések:
## Skypvp: **Spawn**
## Survival: **spawn2, end**

**Comment by andris155** [comment]
törölve
