### ISSUE TITLE
Segítő TGF (javaslatok)

### ISSUE THREAD

**Issue by Fr3lly** [andris155/TheOld-Crafters#744]
Üdvözletem! Javasolnák pár kérdést a PE Segítő tagfelvételhez. (Fejlesztés)
1. Mit tennél, ha egy játékos szídna?
2. Mit tennél, ha egy játékos spawnkillelne?
3. Hogyan figyelmeztetnél egy játékost? Milyen parancsot használnál?
4. Mit tennél ha egy rangos, visszaélne a rangjával? Pld: addol a játékos társainak.
5. Ha egy játékos, a némítás után is káromkodna, mit csinálnál? (ban jog nélkül)

**Comment by andris155** [comment]
Frissítve, válaszok resetelve. Mindenki újra töltheti.

**Comment by andris155** [comment]
508 OCD

**Comment by Fr3lly** [comment]
Köszönöm!
