### ISSUE TITLE
PC, Segítő felvételi

### ISSUE THREAD

**Issue by Wexthory** [andris155/TheOld-Crafters#746]
A segítő felvételhez kitöltendő űrlapon lehetnének, olyan kérdések amiket csak azok tudnak akik  játszanak a szerveren egy ideje, mert a legfrissebb segítők között vannak/voltak olyanok, akik magát az mc-t kiguglizták, de a szerverről fingjuk sem volt, aztán okosak, hogy de úgy van ahogy mondják, közbe pont nem és ezek a kialakult képet rontják. Gondolok itt olyanra, hogy hol enchantolhat bárki? Kaylandon, stb...

Persze az is elég lenne ha kapnának egy kiskönyvet ilyen apróbb infókkal és akkor nem lenne gond, de a tapasztalatok azt mutatják, hogy egyszerübb a tgf kérdéseket átírni.

**Comment by andris155** [comment]
Jelenleg is kapnak könyvet.
