### ISSUE TITLE
Survivalos itemek kreatívossá válásának oka(?)

### ISSUE THREAD

**Issue by Wexthory** [andris155/TheOld-Crafters#747]
UDP-t idézve: ,,Minden blokkot / tárgyat, ami kiesik ha a mellette / alatta lévő blokk eltűnik lehet addolni, nem lesz rajta a jelzés, fel lehet venni, használni is. Facsemeték, tábla, nyomólapok, redstone, homok, sóder, stb."

Az ilyen módon kiesett blockoknak a helyét valószínűleg továbbra is úgy érzékeli a plugin, hogy az ott van, így azt a blockot amit legközelebb odarak, majd kiüt valaki, azt kreatívossá teszi. A shulkerek így válnak kreássá, a fejekből így lesz kreás skeleton fej, vagy csak egyszerü kőből kreás kő stb...
Nem igaz a: keretre, armor standre és az ilyen jellegű itemekre.

**Comment by Wexthory** [comment]
Visszafelé nem működik, hogy survis homokot hagyok leesni és kreás itemet rakok a helyére majd kiütöm. (azaz kreás marad)
Lett 15 addolt black concrate powderem, pls ne banoly koxi.

**Comment by andris155** [comment]
Tudunk a hibáról.
