### ISSUE TITLE
Járművek

### ISSUE THREAD

**Issue by Levytheking** [andris155/TheOld-Crafters#748]
Ha beszálunk egy olyan járműbe szálunk be creatívban amivel lehet lőne tűzgolyoval akkor engedi. így creában is meg lehet azt csinálni lősz vele. nem addolás féle csak nem kell legalább csinálni.

**Comment by andris155** [comment]
Kárt nem csinál vele végül is. Aki vesz tankot meg kreatívot az tőlem már lövöldözhet kreatívban.

**Comment by andris155** [comment]
204 OCD
