### ISSUE TITLE
Slimefun minemarketre.

### ISSUE THREAD

**Issue by HELLCATGHOST** [andris155/TheOld-Crafters#749]
**1. Spawnerek.** (Guardian->1016 OCD|Ghast ->1016OCD|Mamga cube ->1016 OCD|slime ->1016)
**2. Plutonium .** --- 508 ocd/5db
**3. Blistering Ingot.** --- 508/6db
**4. Neptunium.** ---320 ocd/5db
**5. Boosted Uranium.** --- 508 ocd/4db
**6. Enriched Nether ice.** --- 508 ocd/10db  |   1016 ocd/22db 
**7. Nuclear Reactor.** --- 1016 ocd/1db
**8. Nether star reactor.** --- 1016 ocd/1db
**9. Empowered Programmable** Android. --- 1016/1db

-_**HELLCAT**_

**Comment by Levytheking** [comment]
én max 508 OCD-re gondoltam a spawnereket mert eg yicsit drágánnak találom, és ami 2k OCD az lehet 1k OCD, ami 500 OCD az lehetne 320, ami 1k OCD az lehetne 500 OCD. én így gondoltam az árakat mert egy slimefun itemért kicsit sok a 2k OCD mert s zerveren 400k körül mozog a nether star reactor

**Comment by HELLCATGHOST** [comment]
Spawnereket nem hinnem hogy olcsóbban kéne adni,hisz ilyen spawnereket nem találni.

**Comment by Levytheking** [comment]
abban igazad van de akkor pl 2-ért és szerintem csak sima spawnereket kéne árulni nem powereket és olyanokat amelyikekhez nem lehet hozzá férni. Mert akinek van OCD je de nincs hozzá valója pl plutoniuma azt is venni kell a minemaketből. a Powered spawnerhez nagyon sok energia is kell az egyenletes működéshez és sokan nem tudják hogy hoygan kell hozzá férni ilyen sok energiához. HA valaki Powered spawnert szeretne akkor az elő állítja ő maga.

**Comment by AwesomeFM** [comment]
Reinforced Alloy Ingot lehetne 508OCD/8db, amit HELLCAT írt, spawnerek azok lennének 1016OCD, a többi, spawner, ha bekerül a MineMarketbe, 508OCD/1db

**Comment by andris155** [comment]
Empowered Programmable Android-t nem találtam

**Comment by andris155** [comment]
http://theold.minemarket.hu/category/slimefunsurvival

**Comment by andris155** [comment]
1016 OCD

**Comment by andris155** [comment]
(minden résztvevőnek)
