### ISSUE TITLE
SimpleMessages javaslat

### ISSUE THREAD

**Issue by Fr3lly** [andris155/TheOld-Crafters#750]
Üdvözletem! Mivel már van Építész tagfelvételi űrlap a PE szervereken, akkor a jelenlegi Segítő tgf üzenetét, át lehetne írni arra hogy: §9Építész §7és §6Segítö tagfelvétel elérhető. §9http://www.oldcrafters.net/tgfvalasztas
Köszönöm!

**Comment by andris155** [comment]
kész, holnap tölt be
