### ISSUE TITLE
SlimeFun-Pickaxe Of The Seeker

### ISSUE THREAD

**Issue by Levytheking** [andris155/TheOld-Crafters#757]
Ezel a csákányal (Pickaxe of The Seeker) ha job klickelsz vale megmutatja hold van az ércek verges oda teleport téged vagy ha közel van akkor csak a fejedet ugráltatja oda. sok admin/segítő azt hiheti erre hogy oops ez folyamatosan gyémántokat talál és valahogy mindig megtallja. Pedig ez a csákny csak megmutatja hol vannak az ércek.

**Comment by andris155** [comment]
Beszéltem a staffokkal, hogy ilyen is van.
