### ISSUE TITLE
Plugin ötlet [Pocket Edition] •SkyPvP•

### ISSUE THREAD

**Issue by Fr3lly** [andris155/TheOld-Crafters#759]
Üdvözletem!
 Lenne egy plugin, ami jó lenne SkyPvP-re Emerald beváltására. 
Ha az Emeralddal rákattintok a ládára, akkor random itemet dob ki, persze az itemet bármire átlehet állítani a konfigba. (CrateKeys mappa) a plugin tesztelve volt, és működik. Magyarosítás kell csak.
•PLUGIN• [[KATT]](http://forums.pocketmine.net/plugins/cratekeys.1683/)

**Comment by Fr3lly** [comment]
[KATT](https://github.com/andris155/TheOld-Crafters/issues/759)

**Comment by Fr3lly** [comment]
# plugin

**Comment by Fr3lly** [comment]
**pont**

**Comment by andris155** [comment]
Be kellene állítani rendesen, és tesztelni.
https://poggit.pmmp.io/ci/infinity-pe/CrateKeys

**Comment by andris155** [comment]
Amit küldtem azt. Én nem tudom mit akartok, vagy hogyan.

**Comment by andris155** [comment]
Most akkor elkülditek a véglegest, vagy mi legyen?

**Comment by Fr3lly** [comment]
elküldtem a véglegest.

**Comment by andris155** [comment]
és az miket ad?

**Comment by andris155** [comment]
A kód alapján ennek semmi értelme. Nem fogok gyémánt cuccokat osztogatni.
