### ISSUE TITLE
1.9 WG gondok.

### ISSUE THREAD

**Issue by Kronox12** [andris155/TheOld-Crafters#76]
Brigikeee-nek le van védve egy Endcity WG-vel. A probléma az, hogy több helyen is hatalmas, majdnem chunk méretű helyeken tűntek el 1.9-es blokkok.

**Comment by andris155** [comment]
A processzor túl terhelés miatti leállás miatt volt. /co restore u:neve r:50 t:4h ezt, ha beírjátok ott, elvileg megoldja.

**Comment by Kronox12** [comment]
Akkor admin kell hozzá. Moderátornak nincs rá joga.

**Comment by andris155** [comment]
Vagy Tulaj.
