### ISSUE TITLE
Kreditért OCD PE javaslat

### ISSUE THREAD

**Issue by DragleX** [andris155/TheOld-Crafters#762]
Arra gondoltam hogy a PE szerveren a begyűjtőt kreditet lehessen be váltani OCD-re, egy kevés OCD-re gondoltam kb 100 OCD egy kicsit több kreditért.

**Comment by andris155** [comment]
milyen kredit?

**Comment by DragleX** [comment]
Ami van a pe szerveren, lehet kapni  segítségre.

**Comment by andris155** [comment]
Nincs rá automatikus beváltás én meg nem igazán érek rá ezt is jóváírogatni.
