### ISSUE TITLE
SlimeFun-Talismans Tiere I, II

### ISSUE THREAD

**Issue by Levytheking** [andris155/TheOld-Crafters#763]
Ezek a talismanonok adnak effectet nem mindegyik de pl gyorsaság 3 at ai eventen nagy előny lehet egyesek számára. nem kell közvetlen nála lenni ennek a talsimannak de ha berakja az ender chestjébe akkor itt is hat az effect. Így eventen könyebb nyerni. (Van olyan is amelyik egyáltalán nem segít az eventekben de pl regenerácio 3 as is van vagy ami megment a lávától)

**Comment by andris155** [comment]
Az event világban ez le van tiltva.
