### ISSUE TITLE
Share control hiba

### ISSUE THREAD

**Issue by TaroTOC** [andris155/TheOld-Crafters#766]
Amióta bejött a kreatív rangosoknak szóló sharecontrol újítás azóta amit régen tettünk le kreatívban és a ShareControl újítás után ütöttük ki megadja survivalban,és használható!
Akkor vettem észre amikor elkezdtem dolgozni egy régebbi építményemen telkeken,és egy két helyen kijavítottam!

**Comment by andris155** [comment]
Sajnos ez logikus, Hiszen más plugin.

**Comment by TaroTOC** [comment]
szóval akkor ha valaki diábol épített házat amiben van kb 123123 diablock az megtarthatja a diablockokat.?

**Comment by TaroTOC** [comment]
csakmert szerintem ez egyfajta önaddolásnak felel meg . 🗡
