### ISSUE TITLE
Slimefun alchemy bug

### ISSUE THREAD

**Issue by Icecroft** [andris155/TheOld-Crafters#768]
Alchemy level 250 után lehetne készíteni magasugrás potit, csak nyúlfarok helyett piros gomba hozzáadásával. Jelenleg 680-as szint felett vagyok, de ezt az egy receptet nem hajlandó elkészíteni.
(ha nyúlfarokkal készítem a receptet, akkor is kicsit másképp működik:
1.) a shift+jobb clickre bedobja az összes nyúlfarkat
2.) az MCMMO főzésgyorsítása nem érvényesül magasugrás potikra)

**Comment by andris155** [comment]
Kérlek ide jelentsd a hibát angolul: https://github.com/mcMMO-Dev/mcMMO/issues
