### ISSUE TITLE
1.9 Szabály javaslat.

### ISSUE THREAD

**Issue by Kronox12** [andris155/TheOld-Crafters#77]
Az EndCity-k és az EndHajók teljes elbontása legyen tilos.

**Comment by andris155** [comment]
Pontosan mi legyen a szabály szövege?

**Comment by Kronox12** [comment]
"A Végben levő városok és hajók elbontása szigorúan Tilos!"

**Comment by andris155** [comment]
5.20, A Végben levő városok és hajók teljes elbontása tilos!
5.21, A Végben levő városok és hajók kifosztása kisajátítása szabad!
