### ISSUE TITLE
bugos pear sapling

### ISSUE THREAD

**Issue by Laci501asLackos** [andris155/TheOld-Crafters#771]
Hello. Az lenne a bug, hogy sok pear saplinget leültettem ez mind kinőtt, és mikor a soulbound axe-val neki álltam szedni darálta a fát és ebből következett szerintem hogy a saplingek a levegőben maradtak, és igy arra a blokkra nem lehetett blokkot rakni, ezt már megpróbáltam ugy, hogy egy pistonnal oda tolok egy blokkot hát ha frissül de csak sokszori próbálkozásra sikerült de ez annyira sok helyen van hogy inkább feladtam. üdv Lackos

**Comment by andris155** [comment]
Üdv!
Keresd fel andris155-t a szerveren.
