### ISSUE TITLE
Addolás

### ISSUE THREAD

**Issue by Kelvin172** [andris155/TheOld-Crafters#772]
Minden slottal rendelkező Slimefun cuccal addolni lehet itemeket, mert kreatívban beléjük lehet nyúlni - Jelentette: ProfYgamer  <Kelvin172>

**Comment by andris155** [comment]
Javítva!
Köszönjük a hibajelentést!

**Comment by Levytheking** [comment]
Menyi OCD-t kapott?

**Comment by andris155** [comment]
5080
