### ISSUE TITLE
Caps plugin javaslat PE szerverekre.

### ISSUE THREAD

**Issue by DragleX** [andris155/TheOld-Crafters#773]
## Szeretném javasolni a **PE** szerverekre [ezt](http://forums.pocketmine.net/plugins/accidentcaps.1720/) a plugint mivel sok a folyamatosan nagy betűvel írt szöveg.

**Comment by andris155** [comment]
Már más javasolta.

**Comment by andris155** [comment]
https://github.com/andris155/TheOld-Crafters/issues/652
