### ISSUE TITLE
Pc-Szavazás

### ISSUE THREAD

**Issue by Levytheking** [andris155/TheOld-Crafters#775]
nem rég elértem a 30szavazást és nem kapok Oldgoldott hanem ugyanúgy og-t kaptam.

**Comment by Levytheking** [comment]
ugyanúgy NEM* Og-t kaptam hanem vasrudat

**Comment by andris155** [comment]
Javítva!
Köszönjük a hibajelentést!

**Comment by andris155** [comment]
Kárpótoljon az 330 OCD. :D

**Comment by Levytheking** [comment]
Köszönöm :D
