### ISSUE TITLE
Ancient Pedestallal

### ISSUE THREAD

**Issue by AwesomeFM** [andris155/TheOld-Crafters#778]
Ha kreatívban valamilyen cuccot ráteszünk az Ancient Pedestal-ra, azt le tudjuk venni survivalban, és így addolni.

Illetve, ha survivalban, esetleg, valami különleges/slimefunos cuccot rakunk rá, kreatívban le tudjuk venni róla, majd azt visszarakva, tudjuk sokszorozni.

**Comment by Levytheking** [comment]
Ez nagyon durva.

**Comment by andris155** [comment]
És most tiltsam le, vagy mit kezdjek ezzel?

**Comment by MrZero1** [comment]
Szerintem célszerű lenne tiltani.

**Comment by andris155** [comment]
Javítva.

**Comment by Levytheking** [comment]
Ha ez tíltva lesz akkor sok tárgyat is mellé tiltani kellene mivel sok tárgyat pl spawnert lehet kavítani. Megszűnik ezeknek a craftolása de áldozatot kell hozni hogy ne lehessen buggoltatni

**Comment by andris155** [comment]
Nincs tiltva. Mivel nyílt forráskódú a plugin beleírtam egy kreatív védelmet erre, ami szerencsére működik. :)

**Comment by andris155** [comment]
330 OCD emlékeztetésért, de már más jelentette egyébként.
