### ISSUE TITLE
1.9 bogárpáncél bug

### ISSUE THREAD

**Issue by Pixi91** [andris155/TheOld-Crafters#78]
Az lenne a gond, hogy a bogárpáncél repülésnél visszarángat, de még csak el sem kezdhetek repülni. Ennek az az eredménye, hogy vagy visszadob a kezdeti pozícióba, vagy pedig esek egy nagyot, attól függ. A speedhack-hoz és az illegális fly-hoz tudnám hasonlítani ezt a jelenséget. Nem tudom rangosoknál működik-e, de tagként nem.

**Comment by andris155** [comment]
https://github.com/andris155/TheOld-Crafters/issues/74

**Comment by andris155** [comment]
Javítva.
