### ISSUE TITLE
ShareControl bug

### ISSUE THREAD

**Issue by Theodis2dot0** [andris155/TheOld-Crafters#781]
https://www.youtube.com/watch?v=R_vaHZLnBxQ

Gyors bemutatás.

+++++++

Mint kiderült, ezzel az Ancient Altaros slimefunos buggal, ha megtömtél egy shulkert minden jóval, és azt átvetted kreába, és a videóban látott módszerrel nagyon szoksorosan meg lehetett sokszorosítani bármit.

**Comment by Levytheking** [comment]
Le kell tiltani creatában a shulker box ot és a redstone használatát és a probléma meg van oldódva

**Comment by Theodis2dot0** [comment]
kössz sherlock

**Comment by andris155** [comment]
Javítva!
Köszönjük a hibajelentést!

**Comment by andris155** [comment]
330 OCD
