### ISSUE TITLE
Pc-petek

### ISSUE THREAD

**Issue by Levytheking** [andris155/TheOld-Crafters#782]
vannak egyes petek amelyiknek lehet a kezébe adni bármi féle fegyvert,páncélt. Ha survivalba rárakjuk és felveszük creativban majd meg duplázzuk és vissza rakjuk survivalba felveszük. így 2 szer anyi értékes fegyverünk lehet mint volt.

**Comment by andris155** [comment]
Javítva!
Köszönjük a hibajelentést!

**Comment by andris155** [comment]
1016 OCD
