### ISSUE TITLE
Elveszett az elit rangom!

### ISSUE THREAD

**Issue by FinickyLace2785** [andris155/TheOld-Crafters#784]
![image-0-02-05-3b1a185430c2d54ddd89a3b60a67949dcb950abccfe6b1efe3dea6321c1bbf6b-v](https://user-images.githubusercontent.com/29478450/27988232-97a46e9a-641d-11e7-955f-3c94fa141b56.jpg)
Kedves Frelly elveszett az elit rangom amit pár napja vettem  szerintem azért mert a VIP rang lejárása előtt vettem meg kérlek segítsd visszaállítani vagy add vissza az OCDt kérlek!

Köszönettel FinickyLace2785!

**Comment by andris155** [comment]
,,Meglévő nem Tag rangra tilos rangot vásárolni! Mindig meg kell várni még az előző lejár!​"

**Comment by andris155** [comment]
Visszaadva!

**Comment by FinickyLace2785** [comment]
Köszönöm!Többet nem teszek ilyet

2017. júl. 8. 21:30 ezt írta ("Marczinkó András" <notifications@github.com
