### ISSUE TITLE
PC-Járművek

### ISSUE THREAD

**Issue by Levytheking** [andris155/TheOld-Crafters#785]
Vannak azok a járművek amikell lehet lőni mint pl a tank. Creában még mindig lehet velük buggoltatni és lőni tűzgolyóval.

**Comment by andris155** [comment]
Hogyan, ha ezeket nem tudod kivenni sem a kreatív táskából?

**Comment by Levytheking** [comment]
ehh pedig ment ): xd

**Comment by Levytheking** [comment]
TNT-t se lehet? Mert azt nem próbáltam

**Comment by andris155** [comment]
Elírtam a konfigot.
