### ISSUE TITLE
Plugin ötlet.

### ISSUE THREAD

**Issue by warsajt** [andris155/TheOld-Crafters#786]
Javaslom hogy egy fegyveres plugin kerüljön be a szerverre. pl: https://www.spigotmc.org/resources/guns-plugin.31569/ ezeket nem lehet craftolni, szóval a minemarket részlegbe. Pisztolyok, kis tűzerővel rendelkező fegyverek: 320OCD, SMG:508OCD, nagyobb kaliberű, pl: mesterlövész puska, rakétavető 1016OCD :)

**Comment by andris155** [comment]
Nem szeretnék kötelező forráscsomagot a szerverre.
