### ISSUE TITLE
1.9 invertory páncélzat bug

### ISSUE THREAD

**Issue by Pixi91** [andris155/TheOld-Crafters#79]
Ha egyik világból, pl. plotme-ból szabadba, vagy szabadból, end-be, és így az összessel, tehát ha nem a meglévő világban spawnolunk a meglévőbe valahová, akkor eltűnik a páncélzat kijelző lentről. Akkor jelenik meg újra, ha a felszereléseknél egyet leveszünk magunkról és/vagy hozzáadunk egyet újra. Ha meglévő világban spawnolgatunk, akkor viszont jó ahogy látom. Gondolom valami renderelési hiba lehet.

**Comment by andris155** [comment]
Erre nem tudok megoldást sajnos.

**Comment by andris155** [comment]
Javítva.
