### ISSUE TITLE
McMMO skill nem használható, FAWE hibát floodol.

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#790]
Ha a McMMO-s gyógynövénytan skill-t próbálom használni jobbklikkel, nem működik. A block-ot nem üti ki, helyette egy hibát floodol chat-en, hogy nincs jogom a FAWE pluginhoz.

![2017-07-10_18 11 10](https://user-images.githubusercontent.com/16057404/28028202-0d587364-659c-11e7-834f-b4b2bb96d620.png)

**Comment by andris155** [comment]
Lol, most ezt végképp nem is értem. Worledit-tel működik vagy wtf.

**Comment by UDPSendToFailed** [comment]
https://youtu.be/XmGaQ4OG5P0

**Comment by UDPSendToFailed** [comment]
Akkor is ez van, ha mást próbálok kiütni a kapával, nem csak McMMO dolgoknál.

**Comment by andris155** [comment]
nem sikerült reprodukálni
