### ISSUE TITLE
Rangok-Javaslat

### ISSUE THREAD

**Issue by Levytheking** [andris155/TheOld-Crafters#793]
Nem rég került be az a plugin hogy össze lehet vonni a rangokat. Arra gondoltam hogy ha minnél nagyobb rangod van annál több telket tudj össze vonni pl:
Tag+ --
VIP 3
Elit 4
Prémium 6
Old 10

**Comment by andris155** [comment]
https://github.com/andris155/TheOld-Crafters/issues/787
