### ISSUE TITLE
Item salvage.

### ISSUE THREAD

**Issue by TaroTOC** [andris155/TheOld-Crafters#794]
A spawnon kernem az aranyblockokat kicserelni mivel a mainap folyaman unalmamban lovoldoztem a spawnon es a aranyblockra kattintva a bowomat torolte az "Item Salvage" 
Szeretnem ha lcserelnetek,hogy mas jatekosokkal ne tortenhessen meg,mert eleg ertekes dolgokat tudnak vesziteni..

**Comment by andris155** [comment]
Figyelni kell.
