### ISSUE TITLE
BlockSniper plugin javaslat [Pocket Edition]

### ISSUE THREAD

**Issue by Fr3lly** [andris155/TheOld-Crafters#795]
Üdvözletem!
Javasolnák egy plugint, ami jól jönne az Építészeknek. 
Építész+tól legyen elérhető a használata. 
## •Plugin• --> [BlockSniper](https://poggit.pmmp.io/ci/BlockHorizons/BlockSniper/BlockSniper)

**Comment by andris155** [comment]
kész

**Comment by andris155** [comment]
330 OCD
