### ISSUE TITLE
Építész rangnak is tiltott minden blokk kreatívban.

### ISSUE THREAD

**Issue by andris155** [andris155/TheOld-Crafters#8]

**Comment by andris155** [comment]
Engedett blokkok egyeztetése a stafokkal...

**Comment by andris155** [comment]
Tesztelve, javítva.

**Comment by embervagyok2** [comment]
ciganykurvak anyatok roman szorostalpu fasszopo fereg patkany gecik tetves fasszopo @Shryxx anyadat basszam teherbe ukran vendegmunkas @andris155
