### ISSUE TITLE
/god hiba

### ISSUE THREAD

**Issue by Treuce** [andris155/TheOld-Crafters#80]
Ma vettem észre, hogy /god ha be van kapcsolva akkor is van ami sebzi a páncélt.

**Comment by andris155** [comment]
https://github.com/andris155/TheOld-Crafters/issues/74

**Comment by andris155** [comment]
Elvileg ezt is javították, de ez plugin hiba, amit mi nem tudunk javítani, ha mégsem lenne jó.
