### ISSUE TITLE
Minigames Pluginok

### ISSUE THREAD

**Issue by BodorB** [andris155/TheOld-Crafters#800]
DragonRun
DrawMyThing
BedwarsReloaded
VotePlugin
by.: BodorX

**Comment by andris155** [comment]
A DragonRun-t nem sikerült frissítenem sajnos.

**Comment by andris155** [comment]
A DrawMyThing nem nyílt forráskódú. De ez biztos működne: https://www.spigotmc.org/resources/drawmything-1-7-1-11-now-supports-1-11.8338/

**Comment by BodorB** [comment]
rendben, Vote?

2017. júl. 14. 6:33 du. ezt írta ("Marczinkó András" <
notifications@github.com>):

**Comment by andris155** [comment]
A BedwarsReloaded most mit ír?

**Comment by andris155** [comment]
A Vote-hoz teljes szerver újraindítás is kell mert a szerverkezelőben kell beüzemelni. Ez szerintem nem tudom mikor lesz.

**Comment by BodorB** [comment]
Hol mit ir?
Konzolban?
Ha ujrainditom a szervert, bent lesz a vote?

2017. júl. 14. 6:39 du. ezt írta ("Marczinkó András" <
notifications@github.com>):

**Comment by BodorB** [comment]
a bw ugyanugy nem indul

2017. júl. 14. 6:47 du. ezt írta ("Bodor B" <bodorb44@gmail.com>):

**Comment by BodorB** [comment]
logban is ugyan az.
Could Not Pass Player Event

2017. júl. 14. 6:48 du. ezt írta ("Bodor B" <bodorb44@gmail.com>):

**Comment by andris155** [comment]
Mint írtam a teljes szervercsoporton kell állítani dolgokat ahhoz, hogy a vote 2 szerveren működjön 1 IP-en belül.

**Comment by BodorB** [comment]
értem.

2017. júl. 14. 6:50 du. ezt írta ("Marczinkó András" <
notifications@github.com>):

**Comment by andris155** [comment]
Most megtudod nézni a Bedwars-t?

**Comment by BodorB** [comment]
Igen
Most megy.....
Mit csináltál? :O


<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Mentes
a vírusoktól. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2017-07-14 18:52 GMT+02:00 Marczinkó András <notifications@github.com>:

**Comment by andris155** [comment]
Látom működik. A shop.yml-ben írtatok el valamit. Visszaraktam az alapot. A régit shopold.yml néven találod meg.

**Comment by BodorB** [comment]
Viszont a DrawMyThing amit küldtél az 20 USD.

2017-07-14 18:54 GMT+02:00 Bodor B <bodorb44@gmail.com>:

**Comment by BodorB** [comment]
GhostTrigger csinálta a shop.yml-t :D

2017. július 14. 18:54 Bodor B írta, <bodorb44@gmail.com>:

**Comment by andris155** [comment]
A fordítás okés, de a " " jelek nem azért vannak ott, hogy töröld.

**Comment by BodorB** [comment]
Mondom, nem én fordítottam :D

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Mentes
a vírusoktól. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2017-07-14 18:57 GMT+02:00 Marczinkó András <notifications@github.com>:
