### ISSUE TITLE
Láda Bolt

### ISSUE THREAD

**Issue by Levytheking** [andris155/TheOld-Crafters#805]
Ha egy player által készített ládabolból veszünk valamit akkor nem írja ki hogy kitől vetted és menyiért vetted. De akitől vetted annak kírja hogy te ezt vetted enyiért. Így nem tudod mikor veszel és mikor nem. Igen működött a láda bolt mert pénzt von le csak chetbe nem jelzi

**Comment by andris155** [comment]
Ez miatt van tiltva ideiglenes direkt egyelőre.
https://github.com/ChestShop-authors/ChestShop-3/issues/63
