### ISSUE TITLE
Slimefun gyorstalpalo konyv

### ISSUE THREAD

**Issue by Lordi88** [andris155/TheOld-Crafters#809]
Otlet:
Azt a slimefunos kezdo osszefoglalast konyv formaban a szerverre atvinni es a kezdocuccokhoz(amit alapbol kapnak) + kitbe berakni.
A szoveget megtalalod Facebookon Andris,ott kuldtem el.

**Comment by andris155** [comment]
kész

**Comment by andris155** [comment]
330 OCD
