### ISSUE TITLE
Petrespawn bug

### ISSUE THREAD

**Issue by Treuce** [andris155/TheOld-Crafters#81]
Ha "auto"-ra van állítva a petrespawn, akkor sem spawnol rögtön újra miután meghal. Még átállás előtt mondtam 1x ezt a bugot, de még az új verzióban sincs javítva.

**Comment by andris155** [comment]
Köszönjük a bejelentést.

**Comment by Kronox12** [comment]
Hiba továbbítva a fejlesztőnek.

**Comment by andris155** [comment]
Köszönöm. :)
