### ISSUE TITLE
PE CapsLimit.

### ISSUE THREAD

**Issue by MerciGT** [andris155/TheOld-Crafters#810]
Szia. A CapsLimitben ahogy észrevettem 2 a maximum nagybetű, amit lehet írni. Ez néha zavaró lehet, ha egy mondatban több fordul elő, pld. a Nagybetűs névfelsorolásnál, és hogy lehetne ezt valahogyan orvosolni?

**Comment by andris155** [comment]
Szia!
A ban listán minden kisbetűvel van. Nem érdekli a rendszert milyen betűvel írod. Ugyan ez a rangadás is.
