### ISSUE TITLE
OldGold Helyettesítő

### ISSUE THREAD

**Issue by CptEdvin** [andris155/TheOld-Crafters#813]
Láttam facebookon a posztot,amiben megszűntettétek az OldGoldot,de mit szólnátok egy alternatívához?
Mi lenne,ha be lenne vezetve egy token rendszer,amit a staffok ugyanúgy küldhetnek eventek nyerteseinek,viszont ez egy külön paranccsal,másodlagos egyenlegként jelenne meg,így elkerülve a duplikációs bugok kihasználását,ugyanis ha valami nem itemként funkcionál,nem lehet duplikálni.
A spawnon ugyanúgy el lehetne rejteni táblákat amik jóváírnak 3-4 tokent mint a rejtett OldGoldos ládák.
Illetve továbbá ezekből a tokenekből lehetne Tag+ rangot szerezni,a játékosok kereskedhetnek vele mert ők is tudnának küldeni egymásnak,bár a részleteket döntsétek el ti,illetve magát a kérdést hogy ez be kerüljön-e.

**Comment by andris155** [comment]
Duplikáció mindig lesz, nem szerencsés ez az egész így, hogy van kreatív is a szerveren.

**Comment by andris155** [comment]
Inkább a pénz lesz előtérbe helyezve.
