### ISSUE TITLE
Slime fun hiba regulátorok kapcsolása

### ISSUE THREAD

**Issue by Kayalafur** [andris155/TheOld-Crafters#814]
Nem tudom, hogy tudtok-e valamit kezdeni a dologgal, de ha egy áram hálózaton 2 regulátor van, akkor egyik sem működik. Össze akartam kapcsolni a napelemes rendszert a bio reaktorokkal és letiltott, amikor szét választottam őket, akkor külön-külön működtek.

**Comment by andris155** [comment]
Kérlek ide írj a SlimeFun hibával kapcsolatban. Ha írsz oda akkor tudok adni OCD, ha szólsz.
https://github.com/TheBusyBiscuit/Slimefun4/issues

**Comment by andris155** [comment]
Paper v1_12_R1
CS-CoreLib v1.5.16
Slimefun v4.1.9
Installed Addons (4)
 ExtraGear v1.1.1
SlimefunLuckyBlocks v1.1
ExoticGarden v1.6.3
ElectricSpawners v1.0
