### ISSUE TITLE
Szerverre szavazás kiírás

### ISSUE THREAD

**Issue by Kayalafur** [andris155/TheOld-Crafters#815]
Nagyon idegesítőnek találom, hogy ha nem szavazok a szerverre, akkor időnként a képembe tolja, hogy szavazzak. Ezt a részét szeretném magam eldönteni, hogy akarok-e szavazni, vagy nem, főleg, hogy mivel támogató játékos vagyok. 

Emiatt egy javaslat: támogással le lehessen tiltani ezt az üzenetet, mert 6 sort tol a chatre, és ha valakivel beszélgetek, esetenként nem látom az üzenetet.

**Comment by TaroTOC** [comment]
Adom (Y)

**Comment by andris155** [comment]
kikapcsoltam
