### ISSUE TITLE
Addolási bug

### ISSUE THREAD

**Issue by poprundelHD** [andris155/TheOld-Crafters#818]
Egy kihasználható bugról van szó, amit könnyen elérhet a player Kreatív módban. A lényege, hogy egy felfelé néző sticky pistont leteszel redstone jellel, amire ráteszel egy Slime Blockot, és aköré a kreatívos blockot amit leszeretnél addolni. Ezután a pistonról leveszed a jelet, így a Slime Block és a körülötte lévő blockok fent maradnak. Utána ha megint jelet adsz a pistonnak, az ismét feltolódik, így a piston, a slime block, és az addolni kívánt blockok nem a Kreatívba módba lesznek "elérhetőek" hanem a Survival módban.

Remélem tudtam segíteni, és minél hamarabb kijavítjátok a hibát! ;)

**Comment by andris155** [comment]
A nyálkablokkot nem tolja el a dugattyú.
