### ISSUE TITLE
Elytra nem javítható /fix paranccsal.

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#82]
![kepernyofoto 2016-03-14 - 11 28 39](https://cloud.githubusercontent.com/assets/16057404/13741710/fceceb9a-e9d7-11e5-9bbc-00764de87209.png)

**Comment by andris155** [comment]
Az EssentialsX már tud hibáról.

**Comment by andris155** [comment]
https://github.com/andris155/TheOld-Crafters/issues/74

**Comment by andris155** [comment]
Javítva.
