### ISSUE TITLE
Kreatívban spawnoltatás

### ISSUE THREAD

**Issue by Kelvin172** [andris155/TheOld-Crafters#820]
Ha egy Withert idézünk, elég legalább 1 fejnek survivalosnak lennie, hogy lespawnoljon a Wither. Jelentette: Treucev2.

**Comment by andris155** [comment]
Mindenre nem tudok védelmet találni.

**Comment by andris155** [comment]
Sikeresen adtál 330 OCD-t a következő játékosnak: Treucev2.
