### ISSUE TITLE
MineMarket rang leírás

### ISSUE THREAD

**Issue by Linux1230** [andris155/TheOld-Crafters#821]
Észrevettem, hogy a Minemarketen még mindig fel van tüntetve a rangoknál a /fix parancs. A facebook csoportban viszont olvastam, hogy ingyenes lett. Gondoltam szólok, azoknak akik nincsenek a csoportban vagy nem nézik az oldalt megtévesztő lehet.

**Comment by andris155** [comment]
A rangosoknak eddig játékpénzbe került. Most már ingyenes, de továbbra is csak a rangokban van benne.
