### ISSUE TITLE
Economy Ötletek !

### ISSUE THREAD

**Issue by HELLCATGHOST** [andris155/TheOld-Crafters#826]
# Sziasztok! Ide írhattok pénzszerzési ötleteket/pluginokat.
##  **JOBS NEM LEHET!**

**//PC s1///
-HELLCAT**

**Comment by Kayalafur** [comment]
Nincs gond a piac rendszerrel, de az árai lehetnének jobbak! 
(mivel a jobs ki van lőve)
Ami még lehetőségként látok, csak pokoli sok munka, a quest plugin különböző feladatok végre hajtásáért kapsz pénzt/itemet, de nagyon sok idő leprogramozni ha nagy küldetést akarunk.
Viszont többször felvhető küldiként mehet bele ilyen:
-Hozz 64 gyapjút és 128 követ kapsz 1000$ <- csak egy sarkos példa a gyengébbek kedvéért.

**Comment by daemonic01** [comment]
## Hali!

**Személy szerint első körben egy jól átgondolt boltot javasolnék, amelyben elfogadható árakon lehetne kereskedni, tehát vásárolni és eladni egyaránt.**

A jelenlegi piac sajnos minden tekintetben rosszabb, mint az előző bolt volt, ezen nincs mit tagadni. Nem beszélve arról, hogy venni szinte semmit nem lehet már, az eladási árak között egy sincs, amelyre támaszkodni lehetne pénzszerzés céljából. Mindemellett a piac szerkezete teljes mértékben átláthatatlan, mivel az egyes táblasorok rendszertelenül, elszórtan találhatóak meg a területen.
Az általam elképzelt bolt letisztult és átlátható építészet terméke lenne, melyben szinte minden a játékban fellelhető item megtalálható. A vásárlási és eladási árak egyaránt alapos megfontolást igényelnek, hiszen alkalmazkodniuk kell a jelenlegi játékosok boltjaihoz a véletlen üzleti rések elkerülése végett, gondolok itt arra, mikor a játékosnál vásárolt dolgokat esetleg drágábban adják el a boltban.

**A másik ötletem már a szerver MMO szálához fűződik, amely - ahogy előttem Kayalafur is írta - a küldetésrendszer.** Ezt úgy képzelem el, hogy a szerver bizonyos pontjain, például a spawn területén elhelyezett NPC-k küldetéseket adhatnának a játékosoknak, amelyek teljesítéséért pénzt, vagy más értékes jutalmakat szerezhetnek. A küldetések száma igazából végtelen, hiszen lehetnek gyűjtögetés, vadászat, halászat, de akár kereskedelem alapúak is. További pozitívum ezzel kapcsolatban, hogy még mindig nagy divatban vannak a hasonló MMO játékok, melyekben a játékos küldetések sorát végrehajtva érhet el jutalmakat, helyezéseket.

Véleményem szerint a fent említett két lehetőség csak egy része annak, amely megoldást jelenthet, de úgy gondolom, ezek valamelyike, sőt, akár ötvözése nagyot lendítene a szerver belső gazdaságán.

**daemonic01**

**Comment by balazzrthd** [comment]
Hello!

Az lenne az én ötletem, hogy a pénzszerzést megkönnyítve, az egyes szintlépések után (ásás,bányászász és társai), egy bizonyos összeget kaphatnánk szintenként!

**Comment by Nightfury12** [comment]
Sziasztok!
Elsonek stabilizalnam a piaci arakat ertekeket. ez alatt ertem azt hogy kicsit tobbet ernenek a dolgok, nem sokkal csak hogy ha az ember esetleg szerez valami nagyon ertekes targyat vagy esetleg valamibol sokat azt eltudja adni penzert hogy azert legyen neki profit. 2. otletem az a mar emlitett MMO rendszer az npc-kel szerintem nagyon jo otlet, igaz nehezen megvalosithato is de megerne. De mivel ez nem eggy MMORP szerver kicsit talan (furcsa is lenne) 3. A 3-ik otletem az nem mas mint hogy frissiteni kellene a penz osszegeket. Tudom hogy valoszinuleg aki olvassa ezt hulyenek nez de nem vagyok az. Ez az otletem arra alapszik hogy a szereveren nem forog a penz. Ezert kellene egy penz reset esetleg hogy mindenki egyenlorol kezdje es ne legyen az akinek van 50 100 200 millio-ja az nem vesz semmit csak orzi a penzt. 4-ik otletem pedig az hogy az eventen is lehetne tobb penzt keresni, Tegyuk fel hogy egy olyan 60 70k korul. Persze ez csak egy pelda lehet ez akar tobb vagy kevesebb, maximum ritkabban lenne event. 5-ik otletem az a  frakciok hogyha esetleg talalnatok ra plugint az nagyon jo penz szerzesi lehetoseg lenne.

**Comment by daemonic01** [comment]
### Újra én...

Az előzőekhez hozzátenném, hogy a pénz-reset sajnos az érintett gazdagok 80%-át elvinné a szerverről. Az eventeken szerezhető pénz mennyisége pedig jelen helyzetben nem kevés, de lehetne esetleg több fordulós eventeket rendezni (pl.: Spleef), amelyben a nyertes ténylegesen többet kapna, vagy akár dobogós helyezések is lehetnének.

A frakciók pedig egy olyan dolog, amit sokan elleneznek már most is, ráadásul ha frakcióvédések lennének, az azt is jelentené hogy sokaknak össze kéne bútorozniuk egymással, ami egyrészt rengeteg meló ha nem új vagy még, illetve azoknak, akik az esztétikus építés hívei, mint például én is, nem fog tetszeni, hogy ő felhúz 3 nap alatt valami komolyat, körülötte meg sok fadoboz rontja a képet. Persze amennyiben megoldható a frakciórendszer enélkül, támogatom. Javasolnám, hogy esetlegesen a frakcióknak kelljen egy közös bázist kialakítaniuk, amelyet a frakció építésze tervez meg, és a közös vagyon itt lenne felhalmozva, ami legalábbis a tárgyi értékeket illeti.

**daemonic01**

**Comment by Nightfury12** [comment]
## A jobs masfele keppen

Az otletem csak annyi hogy a jatekosoknak nem kellen egy adott munkat elvegezni hanem lenne egy atlag napi heti vagy akar havi fizetese, ami nem is lenne hulyeseg szerintem. Az arakat persze meg kene szabni de nem tartom hulyesegnek. Ez is egy fajta munka inkabb fizetes. Lehetne adni akar jatek idore stb.... Igy azok akik nem jatsszanak sokat nem is kapnak annyi penzt. nem lenne az hogy 1 ev utan foljon es milliomos pedig nem is csinalt semmit/fol sem jott a szerverre egy eve. Azoknak az embereknek akik meg kapnak a fizetest valoszinu el is koltenek ha mondjuk hetente kapnak vagy havonta. A munkad csak annyi lenne hogy font kellene lenned a szereveren ameddig csak kedved van es arra kapsz penzt. Igy ezzel a modszerrel a penz problemakat is meg lehetne oldani.... (Csak is kizarolag sajat velemeny)
De nem hulyeseg szerintem.

**Comment by Kayalafur** [comment]
Van egy sima quest plugin ami csak annyit tud, hogy a táblára kattolva felveszed a feladatot, majd a megfelelő táblára lerakod, ezzel pl lehet olyat is, hogy a felvevő tábla a 1.1-en van, a leadó tábla a 5000.200-on így mászkálás a küldi. Tehát menj el  x-y koordinátára, vagy szállítanod kell számára valami itemet, vagy több itemet. A frakció pont a fent leírt dolgok miatt teljesen megvalósíthatatlan, illetve több embernek rg-s levédése van a területére, mert az 50x50-es levédés kicsi a számára. A pénz resetet senki se támogatja semmilyen körülmények között ez szerintem egyértelmű.

**Comment by Nightfury12** [comment]
## Achievmentek!!

Szerintem ez is egy nagyon jo otlet lenne. Bizonyos elert achievmentekert kapnal egy bizonyos osszeget 
Es meg top lista is kene hozza. Ezaltal a top helyezettek kapnanak valamit penz osszeget, vagy esetleg valami ertekes dolgot amint kihuznak egy achievment tree-t Peldanak oka-ert tegyuk fol hogy az egyik Achievment-fan van az xp.. Elerheto celok 20 40 60 80 100 120 140 xp szint stb. ezekert lehetne kapni penzt meg sok ertekes jutalmat amivel meg lehet gazdagodni.

**Comment by Sherox** [comment]
Nekem Egyszerű Mégis hatásos Ötletem lenne.
Ocd-ből pénz.
Ocd-t Eventeken Lehetne Szerezni az event nehézségétől függően.
Vagy
Régi Bolt Visszatétele az eredeti állapotába.
És
A Piac Megszüntetése.
Vagy
Piacon 1 tárgy kijelölése a pénzszerzés céljára. (Prizmarin,Szivacs,RefrénGyümölcs).
