### ISSUE TITLE
Pénz szavazáskor.

### ISSUE THREAD

**Issue by HELLCATGHOST** [andris155/TheOld-Crafters#827]
Szia Andris! Olyan kérdésem lenne,hogy szavazásnál lehet-e pénzt adni?
Válaszod előre is köszi!:D

**Comment by andris155** [comment]
de mennyi a vas helyett?

**Comment by GhostTriggerGT** [comment]
10 szavazatonként 2,5-5k?

**Comment by andris155** [comment]
és minden szavazatnál mennyit adjon?

**Comment by HELLCATGHOST** [comment]
1k/szavazat.
Minden 5. Szavazat 2,5k.
Minden 20. Szavazat 5k.

2017. júl. 29. 14:59 ezt írta ("Marczinkó András" <notifications@github.com

**Comment by andris155** [comment]
kész

**Comment by andris155** [comment]
204 OCD
