### ISSUE TITLE
PE survival (fatelep) javítás

### ISSUE THREAD

**Issue by SilterX** [andris155/TheOld-Crafters#828]
Szia! 

Annyit szeretnék mondani, a survival szerveren a fatelepen tagok bármilyen blockot letudnak rakni, de ha jól emlékszem régebben nem lehetett.
Nos annyi, hogy megtudnád-e oldani? Azért, mert trollkodnak a tagok, és nem tudjuk, hogy ki volt.

Előre is köszönöm, ha tudod javítani! :)

**Comment by SentinelPE** [comment]
Sziasztok.
Igen,ezzel a problémával érdemes lenne valamit kezdeni. Most,hogy ez van,így a játékosok bármilyen blokkot elhelyezhetnek a fatelep tároló területein. Ezzel persze elég sok fejfájást okozva a többi tagnak és a Staffoknak is egyaránt,akiknek a tisztogatással megy el az ideje. Meg persze igencsak csúfítja a területét is a warpnak és páran ezt még cifrázzák a nem odaillő szimbólumokkal amiket lehet 'alkotni' a különféle blokkokból.

_Sent from my Samsung SM-G950F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by andris155** [comment]
Szerintem a jelenlegi védés pluginnal ez javíthatatlan.
