### ISSUE TITLE
Törölve.

### ISSUE THREAD

**Issue by HELLCATGHOST** [andris155/TheOld-Crafters#831]

**Comment by daemonic01** [comment]
### Hali!

Alapvetően nem értek egyet azzal, hogyha egy játékban ily módon lehet előnyre szert tenni, de az ötlet több szempontból is érthető.

A gond az, hogy tegyük fel, veszek 330 OCD-t. Abból vehetek mondjuk 20 Falusi Spawn tojást, vagy  100.000$-t.
Namost, a jelenlegi ismereteim alapján a falusi tojás jó áron megy a szerveren, mivel értékes és ritka. A 100.000$ viszont nem lehet egyenlő 20 db falusi tojással, mert az azt eredményezi, hogy 1 tojás 5000$-t ér, ami egyértelműen nem igaz.
Mindemellett: Aki kitartó, és türelmes, legrosszabb esetben is 10-15 percenként képes összeszedni 25.000$-t, 1 óra befektetett munka tehát megér mondjuk 100.000$-t. Kérdés az, hogy vajon alig 1 óra meló megúszása megér az embereknek 330 OCD-t?

Véleményem szerint, akinek nincs rangja, nem fogja megvenni az OCD-t, hogy pénzhez jusson. Az, akinek van rangja, legfeljebb a nagyobb tételeket fogja igénybe venni, hiszen számukra a 100-200.000$ 1-2 óra alatt lazán összeszedhető.

Ezzel persze nem azt mondom, hogy a feltétlenül ki kell venni a kis címleteket, de úgy gondolom, nem sokan veszik majd igénybe.

**daemonic01**

**Comment by Sherox** [comment]
# Szia!
330OCD - 100.000$ = 303$/DB
508OCD - 150.000$ = 295$/DB
1016OCD - $320.000$ ≈ 315$/DB
2032OCD - $640.000$ ≈ 315$/DB
5080OCD - $1.280.000$  ≈ 252$/DB

"Sherox Miért írod Ki a Nyilvánvalót",
Csak azért csináltam ezt az alap számítást hogy lehessen észrevenni az OCD értékét.

A Playerek között 1.5-2k/1dbOCD.
Ezért sokat fog esni az OCD értéke.

Ilyen Módon Szerezni Pénzt Sajnos Már Kezd Átmenni A Szerver "PayToWin" Szintre.

-./Sherox/.-
