### ISSUE TITLE
X-ray lépcsóvel és falevéllel

### ISSUE THREAD

**Issue by TamasB14** [andris155/TheOld-Crafters#834]
Rájöttem valamire miközben épitettem a házamat és a házam sarkára raktam lépcsót és rá falevelet és amikor véletlen beleültem láttam minden alagutat és (dungeont) és ez szerintem egy bug és hát sajnos ez kihasználható mert dungeonokat és más földalatti dolgokat lehet vele találni. [Az egyik home-m mellé csináltam egy tesztet és müködik(home neve:roncstelep)]

**Comment by andris155** [comment]
Nyugodtan lehet használni. Ez az alap játék funkciója.
