### ISSUE TITLE
Kreativból átvinni az üllőt túlélőbe!

### ISSUE THREAD

**Issue by TamasB14** [andris155/TheOld-Crafters#835]
Ha épitek egy 1x1 kb10 blokk magas "épitményt" és a leg fent a szélére lehejezek egy üllőt akkor gyors átváltok survivalba és amikor le esett az üllő akkor kiütöm csákánnyal és survivalban megkapom

**Comment by andris155** [comment]
Erről a hibáról már tudunk. De köszönjük.
