### ISSUE TITLE
/warp rangok hiba

### ISSUE THREAD

**Issue by asdlol911** [andris155/TheOld-Crafters#837]
Üdv!

A rangok warpon, a Tag jogai résznél beírva maradt a recept parancs, ami már le van tiltva, de ki van írva a táblára.
![2017-08-01_08 06 31](https://user-images.githubusercontent.com/17855326/28811641-d982b1f2-7690-11e7-8fe1-96113e902c70.png)

**Comment by andris155** [comment]
Joga van rá, de az Essentials tiltotta egyelőre 1.12-ben.
