### ISSUE TITLE
Nem tudok felmenni

### ISSUE THREAD

**Issue by FinickyLace2785** [andris155/TheOld-Crafters#838]
Segitség kell 1.11.4el  meg 1.11.3al nem tudok felmenni a szerora meg a rangomért kérem vissza az OCDt Skyon mert most nem tudom használni s felujitás alatt!

**Comment by Sherox** [comment]
Pc-n 1.12.
Pe-n NEMtudom
Ocd-t Meg nem fogod szerintem vissza kapni mert már aktíváltad a rangodat.

**Comment by andris155** [comment]
A PE egy instabil dolog sajnos néha egy-egy frissítésben elrontanak benne dolgokat.
