### ISSUE TITLE
Lopás telkekről

### ISSUE THREAD

**Issue by Kelvin172** [andris155/TheOld-Crafters#839]
Egy olyan telken, ahol van Slimefun gép, játékosok bele tudnak nyúlni és ki tud venni itemeket a gépből, ha hozzá van adva, ha nincs.  Jelentette: baumannkitti

**Comment by Sherox** [comment]
Tört Mc miatt.

**Comment by andris155** [comment]
Sajnos a Slimefun-t nem igazán támogatják más plugin-ok. A hibáról egyébként már tudunk.
