### ISSUE TITLE
MyPet kis bug

### ISSUE THREAD

**Issue by Treuce** [andris155/TheOld-Crafters#84]
RG védéseken nem lehet íjjal lőni néhány irányba mert a Pet hitboxját érzékeli és letiltja a hozzáférést. Szóval mondjuk egy repülő petről nem lehet magunk alá lőni és valamelyiknél előre sem mert nem engedéyezett RG miatt

**Comment by andris155** [comment]
Erről esetleg nem tudnál videót készíteni? Mert így kicsit nehezen érthető.

**Comment by Treuce** [comment]
Nagyon sokáig tartana feltöltenem, de szerveren megtudom mutatni.

**Comment by andris155** [comment]
Okés

**Comment by andris155** [comment]
Erre jelenleg nincs megoldás.
