### ISSUE TITLE
/condense dinnye block

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#841]
A /condense parancs nem ismeri fel a dinnyeszeletet, pedig lehet belőle blockot craftolni.

![2017-08-02_16 36 08](https://user-images.githubusercontent.com/16057404/28879019-3ef927b2-77a1-11e7-88c4-b2d4d7cf5813.png)
![2017-08-02_16 36 19](https://user-images.githubusercontent.com/16057404/28879018-3ef76ba2-77a1-11e7-9732-34d4c6720afa.png)

**Comment by andris155** [comment]
Jelentettem az Essentials-nak.

**Comment by andris155** [comment]
204 OCD

**Comment by andris155** [comment]
> I think this is on purpose. /condense will only process items that can be converted back into their original state later without any losses. A diamond block can be turned back into nine diamonds with 100% reliability, but a melon won't always yield you nine lemon slices, so you're potentially losing items. This might also be the reason why it doesn't work on quartz (and some other blocks previously requested), since you can't turn a quartz block back into quartz shards.
