### ISSUE TITLE
Telek eladása

### ISSUE THREAD

**Issue by AwesomeFM** [andris155/TheOld-Crafters#842]
Ha telket szeretnék eladni, nem fogadja el a parancsot. (/p sell) Pedig a telkek warpon ez a parancs van kiírva. Illetve, a /p help-ben sem találtam. Viszont van egy olyan parancs, hogy /p buy, aminek így semmi értelme.

![2017-08-02_17 13 09](https://user-images.githubusercontent.com/18013708/28880683-1af4e27a-77a6-11e7-9564-bb30a8ef10a8.png)
![2017-08-02_17 13 40](https://user-images.githubusercontent.com/18013708/28880684-1af80658-77a6-11e7-8aab-eb58c4d02131.png)

**Comment by UDPSendToFailed** [comment]
Hasonló hiba: A /plot save és /plot backup ugyanazt csinálja, elmenti a telket, de a warpon nem így van. /plot restore lenne a visszaállítás, nincs rá jog. Nem is kell, mert azzal lehetne duplázni, csak így rosszul van kirakva a tábla, és a /plot save se jó semmire.

![2017-08-02_20 17 19](https://user-images.githubusercontent.com/16057404/28888112-b5e41648-77bf-11e7-9910-80bfb48f7ef2.png)
![2017-08-02_20 17 44](https://user-images.githubusercontent.com/16057404/28888115-b9cf4a34-77bf-11e7-8f6c-32a77a02eb93.png)

**Comment by andris155** [comment]
javítva

**Comment by andris155** [comment]
204 OCD
