### ISSUE TITLE
Spawnház, plázabolt - lucky block hiba

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#843]
Spawnon házakat, plázában boltokat lehet rongálni slimefun-os lucky block-al, persze csak sajátot, ahol le tudom tenni a blockot. Szerintem plot világban az úton is megy, nem volt annyi lucky block-om, hogy teszteljem.

![2017-08-02_17 30 40](https://user-images.githubusercontent.com/16057404/28881489-8e36c1ac-77a8-11e7-811e-e39803857740.png)
![2017-08-02_17 00 34](https://user-images.githubusercontent.com/16057404/28881490-8e38f0a8-77a8-11e7-843d-879ddd9fe55f.png)
![2017-08-02_17 21 46](https://user-images.githubusercontent.com/16057404/28881491-8e3afa6a-77a8-11e7-82b3-15354f559997.png)

**Comment by andris155** [comment]
Holnap betölt és nem lehet. Majd kérj meg egy Admin-t, hogy a rongálást állítsa helyre.

**Comment by andris155** [comment]
508 OCD
