### ISSUE TITLE
Ládabolt nem használható plot-on

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#844]
![2017-08-02_21 27 50](https://user-images.githubusercontent.com/16057404/28891061-808dac7a-77c9-11e7-89d8-699bb5678843.png)
![2017-08-02_21 26 23](https://user-images.githubusercontent.com/16057404/28891007-51c75224-77c9-11e7-9a3f-7b1c3e93c6fc.png)

**Comment by andris155** [comment]
Javítva!
Köszönjük a hibajelentést!

**Comment by andris155** [comment]
204 OCD
