### ISSUE TITLE
Újszabad világ - ércek

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#845]
Az újszabad világban túl sok érc generálódik, szerencse X-es csákánnyal és magas mcmmo bányászás szinttel pár óra alatt 3-4 stack gyémántblock simán megvan.

**Comment by Sherox** [comment]
Lenne 1 kérdésem.
Te Miért nem csinálod ezt?
Szerintem ez most Senkit se fog érdekelni.

-./Sherox/.-

**Comment by andris155** [comment]
Hát ez egy speciális generátor előnyökkel. :D
