### ISSUE TITLE
Pet fejlődési hiba

### ISSUE THREAD

**Issue by Kayalafur** [andris155/TheOld-Crafters#847]
Netherben NEM spawneres wither skeletonokat öltem, mert sokan voltak endben, hogy fejlesszem a petem, viszont valamiért nem kap xp-t.

**Comment by andris155** [comment]
Kellene erről egy videó.

**Comment by Kayalafur** [comment]
Mondj valami normális programot, amivel fel tudom venni, és felveszem

**Comment by andris155** [comment]
Windows 10 Xbox alkalmazás.

**Comment by Kayalafur** [comment]
https://youtu.be/1y5t6c9Siqw

bocs a minőségért, de jól látható

**Comment by andris155** [comment]
Jelentettem a fejlesztőnek. Köszönjük a hibajelentést.

**Comment by andris155** [comment]
330 OCD
