### ISSUE TITLE
Redstone átbuggolás hiba

### ISSUE THREAD

**Issue by poma123** [andris155/TheOld-Crafters#854]
Üdv.
Hogyha valaki letesz kreatívban egy pistont, és arra egy redstone-t, és aktiválja, akkor a redstone ledobódik a pistonról, amit fel lehet venni túlélőben.
![2017-08-09_21 01 41](https://user-images.githubusercontent.com/25465545/29139299-b97c06a8-7d46-11e7-84a2-cb161cd8c46a.png)
![2017-08-09_21 01 43](https://user-images.githubusercontent.com/25465545/29139327-ca819af8-7d46-11e7-9e30-8fee8a69c068.png)

**Comment by Sherox** [comment]
Bugról Videó:https://youtu.be/sHNj-OvOQFQ

-./Sherox/.-

**Comment by andris155** [comment]
igen meg ha kiütöd alóla a blokkot is ad redstone-t, ezekről tudtunk, de köszönjük.
