### ISSUE TITLE
Slimefun Bugg

### ISSUE THREAD

**Issue by Atr0n0X** [andris155/TheOld-Crafters#859]
Good night, no cargo work like they should work, for example, gold dust I want to go to 1smeltery and set that 1 is the dust time, but then it goes to the other box, which is set to 10 Release it

**Comment by Atr0n0X** [comment]
sorry, google translator...

**Comment by Atr0n0X** [comment]
I found a 1cargo buggot, the cargo magnets can not be turned off, how many times i click it always says it is on and never turn it off

**Comment by Sherox** [comment]
Belekezdtem 1 Reinforced gyárba És most nem jó 1 heti munka kukába.
Itt magyarul is írhatsz
Atri :)

-./Sherox/.-

**Comment by Icecroft** [comment]
Tegnap visszatértem szabiról, sajnos a cargo dolgok nem mennek, ugrott a dust gyár és minden más.
Kézzel nem fogok dustokat csinálni mint a kezdetekben, így számomra a slimefun most halott.

**Comment by andris155** [comment]
508 OCD-t kaptatok. Köszönöm a hibajelentést.
