### ISSUE TITLE
Kemence bug

### ISSUE THREAD

**Issue by Shader158** [andris155/TheOld-Crafters#86]
Néha nem ég az agyag és a kaktusz a kemencében, csak ha felveszem és leteszem újra.

**Comment by andris155** [comment]
Szerverfájl bug

**Comment by andris155** [comment]
Holnap már elvileg jónak kell majd lennie.

**Comment by andris155** [comment]
Most jó?

**Comment by andris155** [comment]
Elvileg javítva.
