### ISSUE TITLE
Hibás a plotme rendszer

### ISSUE THREAD

**Issue by szaffo** [andris155/TheOld-Crafters#864]
Másik játékkos által claim-elt telken nem tudok építenni ha nincs ott. Hozzá vagyok adva, ha ott van akk minden jó. 

Üdv: Programfej :)

**Comment by HELLCATGHOST** [comment]
Szia! 2 féle telekhez adás van, a /plotme add ,és a /plotme trust
A /plotme add-dal akkor tudsz építeni/akkor tud valaki építeni ha hozzá vagy adva/hozzá van adva.
A /plotme trust pedig a 'megbízás' azaz bármikor építhet/rombolhat.

**Comment by szaffo** [comment]
Működik, köszi. 
A baj csak az hogy emiatt töröltették velünk a telkünket mert egy admin se tudta megmondani ezt. Tudom, le van írva. Őszintén, te mindent elolvastál eddig ahova regisztráltál? Tudod, hogy a facebook kinek adja-e ki az adataid, vagy éppen a github? 

Köszönöm a megoldást, nem fogjuk használni. Keresünk más szervert.
