### ISSUE TITLE
Smeltery hiba

### ISSUE THREAD

**Issue by Hory20** [andris155/TheOld-Crafters#865]
https://www.youtube.com/watch?v=QMzj0jv01Go

**# Ha a smelteryben jobb alsó sarokba rakod a porokat/kiégetni való dolgot,azt nem égeti ki.**

**Comment by andris155** [comment]
Jelentettem a fejlesztőnek. Itt tudod követni a hibát: https://github.com/TheBusyBiscuit/Slimefun4/issues/392
