### ISSUE TITLE
Savsziget Jegesrafting event várakozó átbuggolás hiba 

### ISSUE THREAD

**Issue by poma123** [andris155/TheOld-Crafters#866]
Üdv.
Ha valaki letesz egy csónakot a középső kőre 5 blokk távolságból, és beleül, át tud menni a jéghez.
[Videó a bugról](https://www.youtube.com/watch?v=qE-KFMJLxos&feature=youtu.be)

_poma123_

**Comment by andris155** [comment]
Javítva!
Köszönjük a hibajelentést!
