### ISSUE TITLE
PocketEdition Permission hiba

### ISSUE THREAD

**Issue by Crypt97** [andris155/TheOld-Crafters#867]
A PE szerveren az Elit rang csak 7 telket tud vásárolni a minemarketben leírt 10 telek helyett!

**Comment by andris155** [comment]
A Permission megvan adva jól. Majd hamarosan elemzem bővebben a hibát.

**Comment by andris155** [comment]
Javítva!
Köszönjük a hibajelentést!

**Comment by andris155** [comment]
508 OCD

**Comment by Crypt97** [comment]
Köszönöm és nincsmit
