### ISSUE TITLE
Survival CombatLogger [Pocket Editon]

### ISSUE THREAD

**Issue by Fr3lly** [andris155/TheOld-Crafters#869]
Üdvözletem! Egy hiba jelentéssel, illetve egy ötlettel jöttem a csalás elkerülése érdekében.
A PE Survival szerveren, javasolnám hogy pár parancsot kellene beleírni a CombatLogger plugin konfigjába a blockolt parancsok közé. 
/fly, /heal, /god, /gamemode 
A PE Survival arénában a leírt parancsokat TILOS használni, de a joggal rendelkezők kihasználják ezt a hibát, mivel be lehet írni őket.

**Comment by andris155** [comment]
Javítva!
Köszönjük a hibajelentést!

**Comment by andris155** [comment]
330 OCD
