### ISSUE TITLE
Faszén

### ISSUE THREAD

**Issue by Treuce** [andris155/TheOld-Crafters#87]
Ha valaki faszenet használ a kemencében akkor az egy stack égetésére elég, singleplayerben csak 8 dolgot lehet vele kiégetni. Ezt a bugot "Castiel_" fedezte fel.

EDIT: Teszteltem, rendes szénnel is ugyanez a helyzet

**Comment by andris155** [comment]
https://github.com/andris155/TheOld-Crafters/issues/86
