### ISSUE TITLE
Digital Miner Bug

### ISSUE THREAD

**Issue by Sherox** [andris155/TheOld-Crafters#870]
Csak 1db Tölcsér Kell Meg 1 Olyan Rang Amelyiknek Van Creatívja.
Videó:https://youtu.be/jbKbVLd3VaI

**Comment by andris155** [comment]
Sajnos egy plugin sem támogatja a Slimefun-t, és a vas blokkot nem akarom tiltani. De az OCD jár érte. 330 OCD.
