### ISSUE TITLE
Vote plugin hiba

### ISSUE THREAD

**Issue by AwesomeFM** [andris155/TheOld-Crafters#871]
A /vote parancsnál, csak az első link működik, a másik kettőnél, nem írja ki a rendes linket, csak annyit "VoteURL"

![2017-08-14_16 54 05](https://user-images.githubusercontent.com/18013708/29277179-33c204d0-8111-11e7-8d1d-92f53e2e321a.png)

**Comment by andris155** [comment]
Javítva!
Köszönjük a hibajelentést!
