### ISSUE TITLE
Információ hiba [Pocket Edition]

### ISSUE THREAD

**Issue by Fr3lly** [andris155/TheOld-Crafters#872]
Üdvözletem!
Mivel már a Fly rang helyett, Tag+ van, akkor célszerű lenne átírni a rang vétel SimpleMessaget.
![img_20170814_225434](https://user-images.githubusercontent.com/26357505/29291447-e686e32e-8143-11e7-807c-fcfe2686ab82.jpg)

**Comment by andris155** [comment]
Javítva!
Köszönjük a hibajelentést!
