### ISSUE TITLE
Tag+ prefix hiba [Pocket Edition]

### ISSUE THREAD

**Issue by Fr3lly** [andris155/TheOld-Crafters#873]
Üdvözletem!
A Pocket Edition Survival szerveren, a Tag+ prefixe el lett rontva.
A nametag után nincs szóköz, de a chaten van. 
![img_20170814_225941](https://user-images.githubusercontent.com/26357505/29291755-db54e6bc-8144-11e7-9b00-8156788e8641.jpg)
![img_20170814_230004](https://user-images.githubusercontent.com/26357505/29291759-e2150c98-8144-11e7-87c7-9d9cbf2b0f8f.jpg)

**Comment by Fr3lly** [comment]
Illetve, a chatelési színét sem ártana átírni &3 színre.

**Comment by andris155** [comment]
Már javítva lett. Holnap betölt. Mivel magam előbb vettem észre sajnos OCD-t nem tudok adni,
