### ISSUE TITLE
Plugin ajánlat [Pocket Edition]

### ISSUE THREAD

**Issue by Fr3lly** [andris155/TheOld-Crafters#874]
PE Survival: [Seat Block](https://imgcl.co/plugins/seat-block.185/)
(le lehet ülni a tölgyfa lépcsőre)
PE SkyPvP: [PvP Level RPG](https://imgcl.co/plugins/pvp-level-rpg.634/)
(Ölésekért Level-t lehet szerezni. 1 ölés = 1 Level) (tesztelve)
PE SkyPvP & Survival: [SkinStealer](https://imgcl.co/plugins/skinstealer.597)
(Egy paranccsal változtatni lehet a saját skined, az adott játékoséra)

**Comment by Fr3lly** [comment]
Pluginok tesztelve, Seat Block nem működik. 
Egyébként arra gondoltam, hogy a SkinStealer egy bizonyos rangtól legyen elérhető.
Permission: skin.stealer

**Comment by Fr3lly** [comment]
SkinStealer command:
/skin név

**Comment by Fr3lly** [comment]
SkinStelar command:
/skin <játékos név>

**Comment by andris155** [comment]
Totál felesleges oda bármilyen skin plugin is, hiszen mindenki olyan skint tud feltölteni amilyet akar, még a tört verzióval is.

**Comment by andris155** [comment]
Az RPG-s volt tesztelve, nem igazán működött jól és a játékosoknak sem tetszett.

**Comment by andris155** [comment]
De köszönjük az ajánlatokat.

**Comment by Fr3lly** [comment]
Az RPG Level 0.16.0 verzióban volt tesztelve ha jól emlékszek, javíts ki ha tévedek. De szerintem ma már tetszene a játékosoknak, hisz lenne miért versenyezni 🙆
