### ISSUE TITLE
Kitiltás plugin [Pocket Edition]

### ISSUE THREAD

**Issue by Fr3lly** [andris155/TheOld-Crafters#875]
Üdvözletem!
Találtam egy plugint, amit lehetetlen feloldani, ha csak nem oldja a bizonyos joggal rendelkező Staff.
Plugin: [MegaBan](https://imgcl.co/plugins/megaban.750/)

**Comment by Fr3lly** [comment]
/megaban {player} - kitiltja az adott játékost.
/megaunban {player} - Feloldja az adott játékost.
/megaban clear - törölje az összes megaban kitiltást.

**Comment by andris155** [comment]
A skin tiltás nem jó megoldás. Mert ha valakinek ugyan olyan skine van azt is tiltja. A többi része pedig benne van a szerverfájlban.
