### ISSUE TITLE
Rotater plugin [Pocket Edition]

### ISSUE THREAD

**Issue by Fr3lly** [andris155/TheOld-Crafters#876]
Üdvözletem!
Egy pluginnal jöttem, ami eléggé jól jöhet az Építészeknek a PE SkyPvP & Survival szerveren.
A Plugin képes megfordítani az Építményt az adott fokba. (90°, 180°, 270°)
Commandok: 
• /rotate 90
• /rotate 180
• /rotate 270
• /rundo

**Comment by Fr3lly** [comment]
•/rpos1 
•/rpos2
## Plugin : [Rotater](https://imgcl.co/plugins/rotater.593/)

**Comment by andris155** [comment]
és kell is nekik ilyen?

**Comment by Fr3lly** [comment]
Nem
