### ISSUE TITLE
Pipes bug

### ISSUE THREAD

**Issue by Treuce** [andris155/TheOld-Crafters#877]
Csak elnyeli az itemeket, még a frissen készített rendszer is.

**Comment by andris155** [comment]
Cargo, vagy Craftbook?

**Comment by Treuce** [comment]
Craftbook

**Comment by andris155** [comment]
Más nem panaszkodott ilyen hibára. Kérlek nyiss új hibajelentést videóval, ha még mindig él a hiba.
