### ISSUE TITLE
CheckID plugin [Pocket Edition]

### ISSUE THREAD

**Issue by Fr3lly** [andris155/TheOld-Crafters#878]
Üdvözletem!
Egy plugin ötlettel jöttem. A plugin /id parancsot tartalmaz, amit ha be ír az a bizonyos személy, és ha a tárgy a kezében van, akkor ki írja a tárgy ID-t, ami jól jöhet az Építészeknek és a Staffoknak.
[[CheckID]](https://www.mediafire.com/file/752b94i6diq9df9/CheckID.phar)

**Comment by andris155** [comment]
Megtudják nézni a neten. Ezenkívül angolul is működnek nem muszáj számot megadni. De köszönjük.
