### ISSUE TITLE
Hiba.

### ISSUE THREAD

**Issue by Sherox** [andris155/TheOld-Crafters#879]
Plotmen Ha Olyan Fát Növeszt az ember aminek Nagy Lombja Van. Akkor az Ránőhet az útra.
![asssssaaasas](https://user-images.githubusercontent.com/30244296/29327193-a5bd5e62-81ee-11e7-901f-543928fd578a.png)

Ha Valaki Muteolva Van Akkor Nem Tudja Használni az alábbi parancsokat:
/helpop,/party.

Üllő Bug:
https://youtu.be/ndt81N6UFpA

Lobbyzó Bug:
https://youtu.be/niJ-SD4uLX8

-./Sherox/.-

**Comment by andris155** [comment]
Nyilván tudunk a hibáról. Rengeteg telken van ilyen. Sajnos nem támogatja a slimefun-t a plot-os plugin.
De köszönjük a bejelentést!
