### ISSUE TITLE
Bugoló mob nevek.

### ISSUE THREAD

**Issue by HELLCATGHOST** [andris155/TheOld-Crafters#880]
Szia Andris, valamiért ha megütünk egy mobot,a nevét átírja.
![2017-08-16_14 20 33](https://user-images.githubusercontent.com/20195055/29362969-565bba8a-828e-11e7-9c7f-a158bb00bf96.png)

![2017-08-16_14 19 17](https://user-images.githubusercontent.com/20195055/29362990-670441f4-828e-11e7-98d3-517b7d69febd.png)

**Comment by andris155** [comment]
Átraktam UTF8-ra. Reméljük jó lesz.

**Comment by andris155** [comment]
204 OCD
