### ISSUE TITLE
SF növény kiütés

### ISSUE THREAD

**Issue by Balint2** [andris155/TheOld-Crafters#881]
A telekvilágban, ha más telkén vagyok (és nem vagyok hozzáadva). Akkor meg lehet semmesíteni az SF növényeket, úgy hogy a termés (felső része) mellé lerakok egy blockot.

**Comment by Balint2** [comment]
A blockot törli amit leteszek, de a növény megsemmesül.

**Comment by andris155** [comment]
Szegény plugin még akkor sem fogja támogatni a Slimefun-t ha minden hibajelentés erről szól :DD

**Comment by andris155** [comment]
Egyébként nem tudok vele mit tenni. Sajnálom.

**Comment by andris155** [comment]
De köszönjük a hibajelentést.
