### ISSUE TITLE
Plotme-ásás bug(??)

### ISSUE THREAD

**Issue by Hory20** [andris155/TheOld-Crafters#882]
Nem egy kihasználható bug(?),de felettév érdekes. :D 

https://www.youtube.com/watch?v=sW9CVGsRnDk&feature=youtu.be

**Comment by andris155** [comment]
Ebben mi a bug? Az mcmmo ad ilyen extra dolgokat nagy szintnél.

**Comment by Hory20** [comment]
A telek alján ások,és feldobja a telek tetejére.

**Comment by andris155** [comment]
Néha úgy dobja tárgyat, hogy felfele és akkor fentre a blokk felé rakja le.
