### ISSUE TITLE
BanItem [Pocket Edition]

### ISSUE THREAD

**Issue by Fr3lly** [andris155/TheOld-Crafters#884]
Üdvözletem!
A PE Survival szerveren, az arénában TILOS EnderPearlt használni, de egyes játékosok ezt kihasználják.
Mivel másra úgy sem jó az EnderPearl, és nincs is szükség rá, akkor érdemes lenne BanItembe helyezni a csalás elkerülés, és játékélmény érdekében.
Item ID: 381

**Comment by andris155** [comment]
Elég gagyi megoldás lenne ez így.

**Comment by Fr3lly** [comment]
Lenne rá megoldás, mint pedig ha lenne olyan plugin ami azt tartalmazná hogy mennyi EnderPearlt lehet használni, de én még sajnos nem halottam olyan pluginól. De azért még utána nézek.

**Comment by Fr3lly** [comment]
https://imgcl.co/plugins/enderpearls.536/
Talán ez jó lehet.

**Comment by andris155** [comment]
Nézzétek át, hogy van-e náluk. Egyelőre erre nincs jobb ötletem.
