### ISSUE TITLE
ItemSend plugin SkyPvP & Survival [Pocket Edition]

### ISSUE THREAD

**Issue by Fr3lly** [andris155/TheOld-Crafters#885]
Üdvözletem!
Találtam egy plugint, aminek a segítségével lehet küldeni játékosnak tárgyat. Ezzel el lehetne kerülni a lopást esetleges csalást.
Plugin: [[ItemSend]](https://imgcl.co/plugins/itemsend.738/)
Plugin tutorial: [[Videó]](https://vk.com/video227150488_456239120)

**Comment by andris155** [comment]
Nem támogatja az enchantokat sajnos.
