### ISSUE TITLE
/pvp [Pocket Edition]

### ISSUE THREAD

**Issue by Fr3lly** [andris155/TheOld-Crafters#886]
Üdvözletem!
Találtam egy plugint ami jól jöhet a PE Survival szerverre, a plugin segítségével egy parancs beütése és már is ott vagy az arénában. 😋 
A Plugin úgy működik hogy ha beírja az adott játékos hogy /pvp - akkor oda teleportálja a config.yml nevű fájlban megadott kordinátára.(XYZ) Illetve ha bekerülne a plugin akkor érdemes lesz hozzá adni a SimpleMessages-hez. Illetve, törölni a(z) /warp arena Messaget.
" &bKedved &7támadt &charcolni? &6Írd be hogy /pvp &b - &7és már is a PvP arénában vagy!"
Plugin: [[PvPTP]](https://imgcl.co/plugins/pvptp.51/)

**Comment by Fr3lly** [comment]
Kordináta:
![img_20170817_155625](https://user-images.githubusercontent.com/26357505/29415865-b49f3c30-8364-11e7-9b7c-a3c917d2119c.jpg)

**Comment by andris155** [comment]
Nem szeretnék minden teleport helyre parancsot írni. Bocsi. A warpot mindenki ismeri szerintem. Viszont ha parancsokat írok max az fogja ismerni aki a szerveren játszik.
