### ISSUE TITLE
Kayland bug

### ISSUE THREAD

**Issue by alex00mc** [andris155/TheOld-Crafters#89]
Szia.

A /warp kayland-on találtam egy bugot. Amikor odaérkeztünk a warpra akkor ha hátrafordulunk akkor ott van a kilátó, és ott lent van egy adagoló. Abba belehet nézni meg a tölcsérbe is, mert nincsen levédve jól táblával.

Üdv Alex00mc.

**Comment by andris155** [comment]
Szia!
Ezt kérlek a régió tulajdonosának jelentsd majd. Köszönjük.
