### ISSUE TITLE
Savszigetre ötlet

### ISSUE THREAD

**Issue by TamasB14** [andris155/TheOld-Crafters#896]
Savszigetre szerintem nem lenne rossz ha esik az eső és ha van sapka a fejeden ugy nem fogsz sebződni de a sapka élete megy le lassacskán. + Anti acid szett ami ocd ért lehet megvenni és azzal lehet uszni a vizben,

**Comment by andris155** [comment]
```
   # Protect players from acid rain if they have a helmet on
   helmetprotection: true
```

**Comment by andris155** [comment]
Sajnos Acid szettet nem tudom megoldani. De a god megvéd a vízben.
