### ISSUE TITLE
Savsziget: nem működik a falusiak falva, nem szaporodnak

### ISSUE THREAD

**Issue by Icecroft** [andris155/TheOld-Crafters#898]
Nem sikerült működőképes falut létrehoznom a savszigeten, pedig egy jól bevált formát követtem, ami eddig mindig ment.

**Comment by andris155** [comment]
`villagerlimit: 10`

**Comment by andris155** [comment]
Átírtam 20-ra

**Comment by Icecroft** [comment]
Andris, nem a limittel van a bajom, mert kevesebb  falusim van,
A probléma, hogy nem szaporodnak, mintha nem működne a falujuk. (A SkyBlockon is volt ilyen probléma a kezdetekben)
Azt szeretném, hogy teszteljétek le egy szigeten, fenn áll-e valóban ez a probléma.
