### ISSUE TITLE
Mobokra nem hat a sav eső

### ISSUE THREAD

**Issue by TamasB14** [andris155/TheOld-Crafters#901]
a mobokra a sav eső nem hat + a csirke tud uszni a vizben!

**Comment by Sherox** [comment]
Ezt edddig is tudtuk.

Savsziget "Hibák"
https://github.com/Furasct/TheOld-Crafters-SavSziget/issues


-./Sherox/.-

**Comment by andris155** [comment]
Javítva!
Köszönjük a hibajelentést!

**Comment by andris155** [comment]
204 OCD
