### ISSUE TITLE
SlimeFun - McMMO jobbklikkes skill hiba

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#906]
SlimeFun-os cuccok közelében ha használom a McMMO skillt jobbklikkel, a skill idejének lejárata után bebugolnak a mobok / playerek, nem lehet őket ütni, és a sf dolgokat se lehet megnyitni. Elwarpolás és /back után jó lesz, amíg nem használom újra a McMMO-t. 

https://www.youtube.com/watch?v=YSJ2bS5cK0Y
https://www.youtube.com/watch?v=LzcLSncPZls

**Comment by Sherox** [comment]
Csak 1 baj van ezzel kedves Kernel Barátom hogy Most ebben a pillanatban nincs mcmmo.


-./Sherox/.-

**Comment by andris155** [comment]
Nem sikerült reprodukálni a hibát.

**Comment by andris155** [comment]
![2017-08-30_23 10 52](https://user-images.githubusercontent.com/8324198/29895209-86d62fa6-8dd8-11e7-9cd7-e89e4564fd8d.png)
Az az páncélállvány amúgy nagyon idegesítő tud lenni, ha nem vagy hozzáadva a régióhoz.

**Comment by andris155** [comment]
(A Slimefun szerkezeté)
