### ISSUE TITLE
Plugin ötlet

### ISSUE THREAD

**Issue by Paxelcfg** [andris155/TheOld-Crafters#907]
https://dev.bukkit.org/projects/marriage-master 
https://dev.bukkit.org/projects/custom-join-items 
https://dev.bukkit.org/projects/framepicture
https://dev.bukkit.org/projects/global-market
https://dev.bukkit.org/projects/fr-playerreport-by-loulouz?gameCategorySlug=bukkit-plugins&projectID=272745

**Comment by HELLCATGHOST** [comment]
A Player report nem hiszem hogy előnyös, mert ugye főként képi/videós bizonyíték kell. 
És persze jópár játékos 'fun'-olna vele.

**Comment by andris155** [comment]
Esküvő? Szerintem teljesen felesleges nagyrészt csak fiúk játszanak a szerveren. Meleg házasságot pedig magyar szerverre nem biztos, hogy jó ötlet lenne. Mivel gondolom ez előnyökkel is jár, ha valaki házas szerintem jó páran el is játszanák ezt...

**Comment by andris155** [comment]
A customjoinitems helyett a kitek vannak. Illetve a lobby-n és login-on használjuk ezt.

**Comment by andris155** [comment]
A képes eszközkeret jó dolog, de anélkül is tudunk berakni képeket sokkal okosabb megoldással. De ezt a lehetőséget a staffok és építészek nem igazán veszik igénybe.

**Comment by andris155** [comment]
A market-esről tudok talán jobb is lenne, mivel a sok eszközkeret azzal nincs így nem laggos. De azért szerintem a piac igen szép egy építmény sokkal szebb mint egy ládás menü. Szóval inkább nem cserélném le. :)

**Comment by andris155** [comment]
A report túl egyszerű lenne sokan trollkodnának vele. Aki annyira jelenteni akar valakit inkább írjon e-mailt vagy írjon a Facebook oldalra.
