### ISSUE TITLE
Ötletek

### ISSUE THREAD

**Issue by Sherox** [andris155/TheOld-Crafters#908]
Kéne egy Külön Warp Ahol XY elbugolt fejet El tudod cserélni XY Nem elbugolt Formájába.

Este/Reggel Tábla Csinálása $ért(Pl:10.000$ ért tudsz estét állítani).

GyorsÍrás Jog vétele (Pl:35.000$ és nem fog bannolni 10 percre ha gyorsan írsz "spammolsz").

-./Sherox/.-

**Comment by andris155** [comment]
A Slimefun készítőjének kellene már végre javítania ezt nem nekünk cserélgetni.
