### ISSUE TITLE
Bugok.

### ISSUE THREAD

**Issue by Sherox** [andris155/TheOld-Crafters#909]
Minden Slimefun Gépet pl:Grind Stone,Enchanted CraftingTable.

Elbugolt Carbonado Endeg Furnacebe Beletettem 64 iron oret meg 1 szenet és kb 10 ládányi iron oret adott.

MobArénában Old6 Pályán a ládába Belepakolsz és máskor ki tudod venni.

Altar Bug:
https://youtu.be/qnOoY7fAI6w

Kreatívban Leteszünk 1 kemencét és Égetünk benne akkor Ki lehet szedni surivalba.(kemencét)

Fatelepen Nem Tudjuk Használni a Balta Szuper Képességét (Shift+Jobbklikk)

Advanced Digital Miner Bug:
https://youtu.be/cw4tzLqlV1Q

/mcmmo nemjó és Ásás/favágás skill sem jó.

Izzókő-Porból nem lehet /condense-el Izzókövet csinálni.

-./Sherox/.-

**Comment by Kelvin172** [comment]
A Carbonado edged furnance az alapból többszörözi is az alapmennyiséget, kb megy 10x-i, vagy mennyi, viszont az a 20 láda szerintem is sok, lehet megnézem a sajátommal is xd.

Szerintem az korrekt ha kreatívos sütőben lehet survivalos cuccokat kisütni, ez nem olyan nagy probléma, a Crafting Table is ilyen, lehet benne craftolni, hiába kreában lett letéve.

Eventvilágabn ne is számíts mcmmo képességekre, a fatelep is abban a világban van xd


-Kelvin172-

**Comment by Treuce** [comment]
Fatelepet szerintem át lehetne rakni másik világba mert ha más nem is akkor a double drop nagyon is elfogadható lenne ott, az viszont hogy fejlődni lehessen fatelepen vagy képességet használni nem lenne jó.

**Comment by andris155** [comment]
@Treuce erre nyiss külön jelentést.

**Comment by andris155** [comment]
Az Altar bug jelentve. Itt tudod követni: https://github.com/TheBusyBiscuit/Slimefun4/issues/403

**Comment by andris155** [comment]
Old6 javítva

**Comment by andris155** [comment]
A condense.
,,I think this is on purpose. /condense will only process items that can be converted back into their original state later without any losses. A diamond block can be turned back into nine diamonds with 100% reliability, but a melon won't always yield you nine lemon slices, so you're potentially losing items. This might also be the reason why it doesn't work on quartz (and some other blocks previously requested), since you can't turn a quartz block back into quartz shards."

**Comment by andris155** [comment]
Az Advanced Digital Miner Bug sajnos nem javítható. A Slimefun nem támogatja a kreatív játékmódot, de kérés már van rá.

**Comment by andris155** [comment]
A Carbonado Endeg Furnance jelenleg olyan mint a sima kemence, de erről a hibáról tudok, és már más jelentette.

**Comment by andris155** [comment]
A mcmmo-val nincs gond tudtommal.

**Comment by andris155** [comment]
Át lett helyezve a fatelep.

**Comment by andris155** [comment]
508 OCD
