### ISSUE TITLE
Rs Plugin probléma.

### ISSUE THREAD

**Issue by Kayalafur** [andris155/TheOld-Crafters#91]
Mivel egy új RS plugin került be sajnos elég sok gond van vele, sokkal többet vél rezgésnek mint a korábbi plugin. A farmjaimon az adminok, és Andris által ellenorzott időzítőket használok. Az új plugin miatt mind egytől egyig használhatatlanná vált, a az egyszer kiadott jelet valamiért rezgésnek érzékeli. Sajnos vagy sokkal érzékenyebb, vagy sokkal hamarabb jelez, ezt nem tudom. Viszont sajnos így használhatatlanná vált az a farmom ami eddig működött, és más megoldást nem igazán találtunk ami szerver barát is volt, és a játékosok is használni tudtak, remélem találunk rá megoldást, hogy újra a játékosok is tudjanak egyes szerkezeteket használni, illetve a szervernek is meglegyen a védelme. 

Köszönöm : Kayalafur

**Comment by andris155** [comment]
Ma délután sem működött rendesen?

**Comment by Kayalafur** [comment]
Este jöttem fel, de nem, állnak az időzítőim inkább.

**Comment by andris155** [comment]
Teszteld le újra, ha nem jó akkor rá nézek amint tudok. Köszönöm.

**Comment by Kayalafur** [comment]
Rendben újra indítom a farmokat hogy menjen a teszt köszönöm.

**Comment by andris155** [comment]
Visszakerült a régi plugin, mert az új sok erőforrást használt.

**Comment by Kayalafur** [comment]
Köszi, akkor azért állt vissza normálisra az rs müködés, mert most megint csak a hosszú jeleket csapta le.
