### ISSUE TITLE
Vasgólem spawn

### ISSUE THREAD

**Issue by Treuce** [andris155/TheOld-Crafters#913]
Építettem egy vasgólem farmot, pontosan úgy ahogy egy tutorial videóban illetve letöltött világban láttam majd kipróbáltam hogy valóban működik-e de nagyon úgy néz ki hogy szerveren nem igazán akar menni. 1-2 gólem spawnolt tesztelés közben a szerveren hiába voltam fent este hogy úgy teszteljem. Kérdés hogy ez javítható-e esetleg könnyen vagy sem?

**Comment by andris155** [comment]
Nincs limitálva a mobok száma működnie kellene.
