### ISSUE TITLE
Plugin Ötletek. (Ide írhattok még)

### ISSUE THREAD

**Issue by HELLCATGHOST** [andris155/TheOld-Crafters#916]
**Ide tudtok írni plugin ötleteket a játékosok/staffok számára,de akár a szerver 'customizálására', szépítésére is.**

## **Innen lehet pluginokat keresni:** 
https://mods.curse.com/bukkit-plugins/minecraft
https://www.spigotmc.org/resources/?order=download_count
http://www.mc-market.org/resources/?order=download_count
https://aquifermc.org/resources/?order=download_count

## **PLAYEREKNEK:** 

RecipesGUI
[https://www.spigotmc.org/resources/recipesgui.3013/](url)

Friends3.0
[https://www.spigotmc.org/resources/friends3-0-mc1-8-x-1-12-x.12063/](url)

## **STAFFOKNAK:**

PunishmentGUI
[https://www.spigotmc.org/resources/punishmentgui.29356/](url)

ProReports
[https://www.spigotmc.org/resources/proreports.11443/](url)

uGlow
[https://www.spigotmc.org/resources/uglow-1-10.19520/](url)

Staff+
[https://www.spigotmc.org/resources/staff-the-ultimate-moderation-plugin-1-7-1-11.15151/](url)

AdminPlayerMenu GUI
[https://www.spigotmc.org/resources/adminplayermenu-gui.36358/](url)

## **Egyéb ötlet:**

-StaffReportSystem
   A Staffoknak lehetne egy saját report systemjük,ahova írhatják ki,miért mit kapott.Így naplózhatjuk a büntetéseket.

-Staff  "időmérés" 
  A Staffoknak lehetne mérni a szerveren fent töltött idejüket napi/heti/havi/fél-évi/évi egységekkel, így látni mennyit van fent a bizonyos staff. Ez jól jöhet akár próbahetesek nézésére is.
(Erre plugint még nem találtam, csak 1 stopper órát. De a stopperből lehet baj,hogy az illető elfelejti bekapcsolni stb...)

## **Customizálás:**

AdvancedBan
[https://www.spigotmc.org/resources/advancedban.8695/](url)

uGlow
[https://www.spigotmc.org/resources/uglow-1-10.19520/](url)

AdvancementGUI
[https://www.spigotmc.org/resources/advancementgui.42737/](url)

Ban Animations
[https://www.spigotmc.org/resources/ban-animations.36483/](url)

**Comment by Treuce** [comment]
Villagemarker plugin ami lehetővé tenné a villagemarker mod használatát is a szerveren. 
https://dev.bukkit.org/projects/villagemarker
Sajnos még se a plugin se a mod nincs 1.12.1-re de ha kijön a frissítés szerintem hasznos lehetne pár embernek, magam is tapasztaltam a napokban hogy tudnám használni.
Persze az egész csak akkor ha kompatibilis és nem eszik túl sok erőforrást.

**Comment by Furasct** [comment]
- Staff "Időmérés"
https://dev.bukkit.org/projects/ontime

**Comment by MrDinamit88** [comment]
Mc Troll Plugin

**Comment by UDPSendToFailed** [comment]
https://www.spigotmc.org/resources/lasers-completely-customizable.5957/
https://www.spigotmc.org/resources/rainbow-armor.46198/
https://www.spigotmc.org/resources/gamebox.37273/
https://www.spigotmc.org/resources/oreopaint.46067/
https://www.spigotmc.org/resources/particlehats.1007/

**Comment by MrDinamit88** [comment]
https://dev.bukkit.org/projects/troll-extreme

2017-08-30 16:12 GMT+02:00 UDPSendToFailed <notifications@github.com>:

**Comment by andris155** [comment]
RecipesGUI - Az 1.12.1-es könyvnél szerintem nincs jobb. Sőt azt nem is támogatják szerintem az ilyenek.
Friends3.0 - Extra dolog lehet jól jönne néhány esetben, de én nem látom olyan jónak, hogy ezt most berakjam szerverre. Így is rengeteg plugin van.
STAFFOKNAK - A staff is fontos persze, de most feleslegesen oda nem kell mindenféle extra menü. Csak betudja írni az eredeti parancsokat is menü nélkül is. :DD
Uglow - Sajnos a nametagedit-el nem igazán kompatibilis. Illetve szerintem néha idegesítő is lenne, hogy a falon át látsz valakit ha a közelben van.
AdvancedBan - A warnon kívül nem igazán van benne semmi új extra. Szerintem enélkül is megvoltunk eddig is és meg is leszünk.
AdvancementGUI - Ez igazából az új RPG szerverekre nagyon menő lenne. De nekünk nincs RPG-nk. A túlélő és savsziget szerverre pedig nem igazán látok benne nagy lehetőségeket.

**Comment by andris155** [comment]
A Villagemarker-ből egyáltalán van 1.12.1-es?

**Comment by andris155** [comment]
Az ontime nem működik, és nem is publikus kódú.

**Comment by Treuce** [comment]
Villagermarkerből még nincs 1.12.1es ahogy írtam is.

**Comment by Furasct** [comment]
https://www.spigotmc.org/resources/betterontime.18679/

Talán ez, bár nem ismerem.

**Comment by Treuce** [comment]
Ki jött a villagemarker mod 1.12.1re.

**Comment by Paxelcfg** [comment]
https://dev.bukkit.org/projects/auctionsplus?gameCategorySlug=bukkit-plugins&projectID=99097

**Comment by rikmind** [comment]
https://www.spigotmc.org/resources/coins.33382/ -->Mobok öléséért pénzt lehet szerezni.
https://mods.curse.com/bukkit-plugins/minecraft/anti-x-ray#t1:description

**Comment by poma123** [comment]
Mob ölésért pénzszerzésre inkább ezt ajánlom:C https://www.spigotmc.org/resources/mobcash.25057/

**Comment by poma123** [comment]
http://www.mc-market.org/resources/4527/

**Comment by HELLCATGHOST** [comment]
Az AdvancedBan-nak a "Ban Screen"-je még hasznos és jó szerintem, illetve a 'warn' rendszerét lehetne használni.

**Comment by andris155** [comment]
Lezárva. Aki szeretne plugin-t ajánlani nyisson majd új témát rá,

**Comment by andris155** [comment]
Köszönöm mindenkinek a segítséget.
