### ISSUE TITLE
/skin Parancs 

### ISSUE THREAD

**Issue by MrDinamit88** [andris155/TheOld-Crafters#917]
A /skin Parancs senkinek sem müködik!# HIBA Ehez Nincs Jogod! /MrDinamit88/

**Comment by HELLCATGHOST** [comment]
Érdemes elolvasni a facebook csoportot.

**Comment by andris155** [comment]
Jelenleg a tulajnak sincs ilyen joga. Holnap betölt hozzá a külön jogrendszer aztán el lesz döntve, hogy lesz.
