### ISSUE TITLE
Smilefun

### ISSUE THREAD

**Issue by MrDinamit88** [andris155/TheOld-Crafters#919]

**Comment by MrDinamit88** [comment]
a smilefun ban nem müködik a mindent feloldó könyv! /MrDinamit88/

**Comment by andris155** [comment]
Miért mi baja?

**Comment by MrDinamit88** [comment]
Megvan a 30 xp szint 80000 $t ráőltem de semmi elveszi es azt nem oldja fel az a konyv Figyelem ez nem az sf es könyv hanem a mindent feloldó de nem mukodik

**Comment by HELLCATGHOST** [comment]
A feloldó könyvet először magához kell csatolnia valakinek, akinek maxos az SF. 
2x lehet jobbkattolni vele, az 1. A hozzácsatolás.

**Comment by MrDinamit88** [comment]
Megvolt de semmi .

**Comment by andris155** [comment]
Másnak nem volt ilyen hiba egyelőre, ha lesz akkor utána nézek bővebben.

**Comment by Kelvin172** [comment]
Annyi a lényeg, hogy ha kész a könyv, akkor először a kimaxolt (vagy legalábbis magasabb ,,tudású") játékosnak kell jobb klikkelnie a könyvvel, aztán akinek még nincs kimaxolva(kevesebb ,,tudással" rendelkezik), annak kell jobb klikkelnie ezután. Ezzel a nem maxos, ki lesz maxolva.
