### ISSUE TITLE
Kreás itemek törlése

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#920]
Régebben el lehetett tüntetni a kreás cuccokat az inv-ből Q-val, most csak úgy lehet, ha ráklikkelek és megnyomom az ESC-et. A régi megoldás szerintem egyszerűbb volt, ha be lehet állítani ebben a plugin-ban. 

https://www.youtube.com/watch?v=P9Ou2ZFRu5I

**Comment by UDPSendToFailed** [comment]
Nem arra gondoltam, hogy így ki lehessen dobni az item-et, hanem törölni az inv-ből.

**Comment by andris155** [comment]
Értettem a kérést, de az + event a szerver részléről, hogy levegőre cseréle aminek nem látom értelmét, mivel enélkül is lehet törölni a tárgyakat.
