### ISSUE TITLE
Addolási bug

### ISSUE THREAD

**Issue by MrZsemle** [andris155/TheOld-Crafters#923]
Kedves Old Crafters Team!
Barátommal, Almaevo1-el észrevettünk egy item addolási bug-ot.
A bug lényege, hogy ha creative-ban lerakunk egy tököt/dinnyeblockot/tavirózsát/kaktuszt és azt egy dugattyúval eltoljuk, akkor megkapjuk az itemet ami a blockból származik.
Reméljük, hogy tudtunk segíteni!
pine54,Almaevo1
--
pine54 & Almaevo1 találta ezt, én csak bejelentettem, mert szóltak hogy csináljam én.

**Comment by andris155** [comment]
A hibáról tudunk, de köszönjük!
