### ISSUE TITLE
CombatLogger [Pocket Edition]

### ISSUE THREAD

**Issue by Fr3lly** [andris155/TheOld-Crafters#924]
Üdvözletem!
A PE Survival CombatLogger config.yml nevű fájlba javaslom a /tpyes /tpaccept parancsot beírni, mivel pár játékos PvP közben el /tpaherez-ik. (PvP közbeni elmenekülés/kilépés)

**Comment by andris155** [comment]
Javítva!
Köszönjük a hibajelentést!

**Comment by andris155** [comment]
204 OCD
