### ISSUE TITLE
SlimeFun addolás

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#925]
A csontlisztes megoldás minden sf plant-nál működik. Amúgy itt is látható az item bugolás, csak F3 + A után mutatta a cuccokat. 

https://www.youtube.com/watch?v=6D6nR6p9GVc

**Comment by andris155** [comment]
A sharecontrol-ba hogy írjam bele a csontliszt ID-t?

**Comment by andris155** [comment]
A füves szerintem nem gond igazából találni se sokkal nehezebb füvet hozzá

**Comment by andris155** [comment]
A másik elvileg javítva.

**Comment by andris155** [comment]
330 OCD
