### ISSUE TITLE
Telek világ kibuggolás

### ISSUE THREAD

**Issue by Balint2** [andris155/TheOld-Crafters#926]
Ha valaki a világhatárnál le foglal egy telket, aminek az egyik része a világhatáron kívül van, és beírja, hogy /p h, akkor a világhatáron kívülre tud menni.

**Comment by andris155** [comment]
Hát igen a Mojang nem god meg kreatívra tervezte azt a világhatárt. xd

**Comment by andris155** [comment]
508 OCD

**Comment by Balint2** [comment]
Plotme-re meg pláne nem xd

**Comment by andris155** [comment]
Az nem is baj mert túlélőben megölne ha kívülre kerülsz.
