### ISSUE TITLE
SavSziget Szabályzat

### ISSUE THREAD

**Issue by Furasct** [andris155/TheOld-Crafters#927]
Ha lesz időd, akkor ezt kitehetnéd majd a weboldalra.
https://goo.gl/m8TRCS

**Comment by andris155** [comment]
A jövőben át akarom alakítani a webet majd, nem tudom, hogy azok maradnak-e rajta.

**Comment by andris155** [comment]
https://github.com/andris155/TheOld-Crafters/issues/928
