### ISSUE TITLE
Új Weboldal

### ISSUE THREAD

**Issue by andris155** [andris155/TheOld-Crafters#928]

**Comment by HELLCATGHOST** [comment]
Amiben tudok, segítek!  :)

**Comment by Sherox** [comment]
Én is :dagger: 


-./Sherox/.-

**Comment by HELLCATGHOST** [comment]
Vektoros,minimalista design iconok:
https://glyphicons.com/

**Comment by AnnaMastersong** [comment]
Ha kell rajzolni, én szívesen segítek :) Ezt is én csináltam:
![kep](https://user-images.githubusercontent.com/32579927/32444099-a596834c-c301-11e7-962b-599aeca55eab.png)

**Comment by andris155** [comment]
Részben kész.
