### ISSUE TITLE
SimpleMessages elírási hiba [Pocket Edition]

### ISSUE THREAD

**Issue by Fr3lly** [andris155/TheOld-Crafters#931]
Üdvözletem!
A játékpénzes üzenetbe, el lett írva a(z) 320 OCD-be kerül 75.000$ játékpénz, 330 ocd a helyes.
![img_20170829_231011](https://user-images.githubusercontent.com/26357505/29844456-9ce4540e-8d0f-11e7-9782-8df7a32cdc28.jpg)

**Comment by andris155** [comment]
Javítva!
Köszönjük a hibajelentést!

**Comment by andris155** [comment]
204 OCD
