### ISSUE TITLE
PLugin lol

### ISSUE THREAD

**Issue by warsajt** [andris155/TheOld-Crafters#934]
Javaslom az üvegházas plugin bevezetését a survival szerverre! :)

**Comment by andris155** [comment]
Miért lenne jó a Survival szerverre is?

**Comment by warsajt** [comment]
Könnyebb lenne ezt-azt farmolni.

**Comment by andris155** [comment]
A savsziget szerverre jó, de túlélőre nem igazán való ez a plugin.
