### ISSUE TITLE
BanItem [Pocket Edition]

### ISSUE THREAD

**Issue by Fr3lly** [andris155/TheOld-Crafters#937]
Üdvözletem!
Javasolnám a kidobható mérgező potit banitem-be helyezni. Pár játékos használja az arénában, úgy hogy tilos használni, ezálltal ők még is használják, és jókat szórakoznak, úgy tudom a beiható már tiltva van, de nem biztos, viszont a kidobható az biztos nincs.
•Item ID-k:
 - 438:23
 - 438:24
 - 441:23
 - 441:24

**Comment by andris155** [comment]
Új levédés plugin kellene inkább nem ezeket tiltani.
