### ISSUE TITLE
SG szavazás - üres a láda

### ISSUE THREAD

**Issue by UDPSendToFailed** [andris155/TheOld-Crafters#938]
![2017-08-31_11 04 53](https://user-images.githubusercontent.com/16057404/29916951-a44f7c82-8e40-11e7-97cc-b3b33ac42731.png)

**Comment by andris155** [comment]
Most jó?

**Comment by andris155** [comment]
Javítva!
Köszönjük a hibajelentést!

**Comment by andris155** [comment]
204 OCD
