### ISSUE TITLE
Pipes permission

### ISSUE THREAD

**Issue by Treuce** [andris155/TheOld-Crafters#94]
[14:56:31] [Client thread/INFO]: [CHAT] area.use-permission
Amikor a sticky pistonra akartam táblát rakni a Pipes pluginnal hogy mit ne vigyen el a ládából ezt dobta ki.
EDIT: Ez csak akkor van ha valami olyan itemet szeretnénk ráírni mint "X:Y" mondjuk 397:3(guardian fej)

**Comment by andris155** [comment]
Erre Kronox12 tudja a megoldást.

**Comment by andris155** [comment]
Ha jól tudom a táblát kell a másik oldalra rakni, vagy máshova rakni, és jó lesz, megoldani sajnos nem tudjuk.

**Comment by embervagyok2** [comment]
ciganykurvak anyatok roman szorostalpu fasszopo fereg patkany gecik tetves fasszopo @Shryxx anyadat basszam teherbe ukran vendegmunkas @andris155
