### ISSUE TITLE
Duplikációs rés

### ISSUE THREAD

**Issue by Hory20** [andris155/TheOld-Crafters#941]
Magas szintű bányászatnál már 100%-os az érc duplázást.
Ezért hogy ha 1 ércet többször kiütünk,akár a végtelenségig lehet duplázni azt.
Videót is csináltam róla.

/Nasi
https://www.youtube.com/watch?v=qTVihl5X7Hw

**Comment by andris155** [comment]
Sajnos ezzel nem tudok mit tenni.
