### ISSUE TITLE
Ötlet a lucky blockal

### ISSUE THREAD

**Issue by TamasB14** [andris155/TheOld-Crafters#946]
Szerintem jó dolog lenne ha lehetne ujszabadban Lucky blockokat találni természetesen luck 0 val

**Comment by andris155** [comment]
Sajnos a plugin nem támogatja ezt. Max speciális megoldással lehetne
megoldani. De a generálás így is sokat eszik. Nem akarom feleslegesen
tovább lassítani.

2017. szept. 5. 13:59 ezt írta ("TamasB14" <notifications@github.com>):
