### ISSUE TITLE
Farm pet 28-as szint

### ISSUE THREAD

**Issue by TamasB14** [andris155/TheOld-Crafters#948]
ha a farm petet fejlesztjük 28-as szintre akkor ki irja "mostantól tudja használni ezeket a buffokat: (hatotávolság 0.00 - időkorlát: 0 másodperc

**Comment by andris155** [comment]
Igazából ez inkább olyan dolog amit nem kellene kiírnia. De nem hiba hiszen a 0 is azt jelenti, hogy nem tudod használni. De köszönjük.
