### ISSUE TITLE
Rainbow szet bug

### ISSUE THREAD

**Issue by crazygamer75** [andris155/TheOld-Crafters#949]
Tiszteletem
 Az old rangos rainbow szet bugoltatja a ládákat, sf gépeket, ha bekapcsolom, akkor a ládákban a jobbfelsö 4 slotba se betenni, se kivenni nem tudok semmit. SF gépeknél is hasonlo a helyzet, csak más slot-ok nem müködnek.

Köszönettel:crazygamer

**Comment by andris155** [comment]
Ha le van tiltva akkor se engedi?

**Comment by crazygamer75** [comment]
Ahogy kikapcsolom, minden újra jó, csak bekapcsolt állapotban bugol tőle a
láda és gépek slot-ja.

2017-09-10 10:59 GMT+02:00 Marczinkó András <notifications@github.com>:

**Comment by andris155** [comment]
Videót tudsz róla csinálni?

**Comment by crazygamer75** [comment]
Hát max ha fiam segít, sose csináltam videót a futó játékról.

2017-09-10 14:59 GMT+02:00 Marczinkó András <notifications@github.com>:

**Comment by andris155** [comment]
Jelentve a fejlesztőnek: https://www.spigotmc.org/threads/rainbow-armor.268101/

**Comment by andris155** [comment]
Javítva!
Köszönjük a hibajelentést!

**Comment by andris155** [comment]
204 OCD

**Comment by crazygamer75** [comment]
Nagyon szépen köszönöm

2017-09-21 22:27 GMT+02:00 Marczinkó András <notifications@github.com>:
