### ISSUE TITLE
Hoper és kemence probléma

### ISSUE THREAD

**Issue by Kayalafur** [andris155/TheOld-Crafters#95]
Sajnos a hoper és a kemence időnként teljesen megáll, bebugol, ki kell ütni, és újra letenni, hogy működjön.

**Comment by andris155** [comment]
Akkor áll meg ha nincs ott senki, vagy akkor is ha van ott valaki?

**Comment by Kayalafur** [comment]
Változó, betöltött chunknál is állt már meg sajnos. Bár úgy ritkább.

**Comment by andris155** [comment]
Egyenlőre ezzel nem tudunk sajnos mit tenni.
