### ISSUE TITLE
Bugok(Sherox Visszatér)

### ISSUE THREAD

**Issue by Sherox** [andris155/TheOld-Crafters#956]
Pláza Világban ha jobb klikkelünk egy cserépre neked kiveszi de ha kiütöd akkor újra megjelenik.

Chat Probléma:Ha csúnya szót Írunk Nagy Betűvel Akkor Ki Tudod írni.

**Comment by andris155** [comment]
Az első megjelenítési hiba. Szerintem ez nem okoz gondot. A 2. tesztelve és nem működik.
