### ISSUE TITLE
[Ötlet] Globális (Bungee) Staff Chat

### ISSUE THREAD

**Issue by poma123** [andris155/TheOld-Crafters#957]
Nem lenne rossz, egy külön staff chat, lehetne csapat chat a neve, amivel a két szerver között lehetne szót váltani az összes elérhető staff taggal. A chatcontrollal múltkor ki lett próbálva, de egy különszedett "staff channel" jobb lenne a szerverek között.

[Savsziget-MOD.]poma123

**Comment by andris155** [comment]
Azt hiszem van benne valami ilyesmi. Majd megnézem.

**Comment by andris155** [comment]
(chc pro)

**Comment by andris155** [comment]
nem nagyon találtam rá megoldás max globálisan lehet írni üzenetet.
