### ISSUE TITLE
CombatLogger [Pocket Edition]

### ISSUE THREAD

**Issue by Fr3lly** [andris155/TheOld-Crafters#960]
Üdvözletem! Javasolnám a PE SkyPvP & Survival szerveren a CombatLogger config.yml tiltott parancsok közé beírni a /logout parancsot. Mivel ki lehet jelentkezni harc közben.

**Comment by andris155** [comment]
Javítva!
Köszönjük a hibajelentést!

**Comment by andris155** [comment]
204 OCD
