### ISSUE TITLE
Frissítések

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#964]
Szia Andris!

Napi szinten kapom a visszajelzéseket, néha már eléggé fájóan megfogalmazva, hogy a privát üzenetküldés és a ki-belépés újítás nem igazán nyerte el a tetszést a játékosoknak. 
De talán csak a privát üzenetküldés ami igazán nagy gondot okoz nekik. 
Ha a közösséget nézzük, nekik nem tetszik. 
Személy szerint hamar hozzá lehet szokni, nekem tetszik, főleg a szerverek közötti üzenetküldés. Most még furcsa, de idővel biztosan kiforrja magát. Vagy nem.

Üdv, MrZero

**Comment by andris155** [comment]
Szia!
Kikapcsoltam az egyik szerverváltási üzenetet így valamivel kevesebb lesz. A privát üzenet modern. Nekem személy szerint jobban tetszik, mert kicsit jobban átláthatóbb így a chat. Persze van aki úgy is mindig az ősrégi dolgokhoz ragaszkodik, de ha értelmes és hasznos egy újítás szerintem érdemes berakni. Ezenkívül a szerver közötti beszélgetés is szerintem elég hasznos újítás.
