### ISSUE TITLE
Építész szerveri jogok.

### ISSUE THREAD

**Issue by HELLCATGHOST** [andris155/TheOld-Crafters#965]
Szia Andris,azt vettem ma észre,hogy építészen nincs jogom a setlight-ra. :(
Nem tudom miért lett elvéve,de én szeretném vissza!
Elég sok mindent meg tudok oldani vele,hasznos,és nem csúnya mint az izzókő,nem mindenhova illik a játékban lévő lámpa dizájnok.

(worldedit.light.set)

**Comment by andris155** [comment]
Nem módosítottam a dolgokon már lassan 1 hónapja ezzel kapcsolatban. Ha szükséges van + jogokra kérlek írjatok össze egy listát.
