### ISSUE TITLE
Medve fej bug Survival-on

### ISSUE THREAD

**Issue by Haythamvagyokaszerveren** [andris155/TheOld-Crafters#973]
Ha jegesmedvefejet kapok, és lerakom, egy játékos, pontosabban _DmacK_ fejévé változik át a medvefej, és már nem medve kinézete van, hanem konkrétan a játékos fejének a kinézete látszik, és a fej neve is átváltozik.

**Comment by Sherox** [comment]
Ez már Régi Hiba és Már Én is Kb 3x jelentettem.


-./Sherox/.-

**Comment by andris155** [comment]
hiába jelented ha nem ide írtad.  :D

**Comment by andris155** [comment]
Javítva 330 OCD

**Comment by andris155** [comment]
Haytham még nem regisztrált a http://theold.minemarket.hu/ oldalon.
