### ISSUE TITLE
ChC permissionok + bungee channel "adminchat"

### ISSUE THREAD

**Issue by poma123** [andris155/TheOld-Crafters#976]
Tehát, a chatcontrolhoz kellene pár permission admin ranghoz (savsziget):
chatcontrol.commands.togglepm
chatcontrol.commands.clear

Nos a másik, hogy a chatcontrolban lehet csinálni plusz bungee channelek -et a /channel paranccsal. Elég jó lenne egy bungee adminchat, külön channelen.

[admin]poma123 (savsziget)

**Comment by andris155** [comment]
segítőtől bekerül a clear.

**Comment by andris155** [comment]
A togglepm szerintem felesleges. A channel nem teljesen arra van.
