### ISSUE TITLE
Moderátor plotjogok

### ISSUE THREAD

**Issue by rikmind** [andris155/TheOld-Crafters#977]
Arra gondoltam, hogy sok esetben rángatják az adminokat telkekhez, hogy üssék ki a kilógó lombokat. A moderátorok le tudnák venni a terhet az adminok válláról, csak nincs ugye joguk a telkekhez. 
Egy fél plot admint nem lehetne megoldani? Hogy ki tudják ütni a lombokat, viszont ládahozzáférés nem lenne szükséges. 
[Moderátor]rikmind

**Comment by andris155** [comment]
kérlek keress fel Facebook-on és írd le mikor tudsz feljönni tesztelni!!!

**Comment by andris155** [comment]
Kész
