### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Sherox** [andris155/TheOld-Crafters#979]
Round-Robin Mode Bug:https://youtu.be/zt44JGts_dU

Amit Kéne Csinálni:
Items Will be equally distributed on the Channel-Itemek Egyenlő elosztása Channelek között.

Amit Csinál:
6.-7.re Csinálja azt amit minden 2.ra kéne.
Vagy egyáltalán nem is rakja be.

-./Sherox/.-

**Comment by andris155** [comment]
Nem tudok ezzel mit tenni.
