### ISSUE TITLE
MineMarket elírás

### ISSUE THREAD

**Issue by Mousking** [andris155/TheOld-Crafters#980]
A PC Survival szerverre való Old rang rangvásárlás kiírásában elírás van.

/ptime day, night - Saját időjárás változtatása. (day = nappal, night = este)

Helyesen nem "időjárás változtatása", hanem "idő változtatása".

![screenshot_20170930-205525](https://user-images.githubusercontent.com/25939300/31048677-80af1158-a622-11e7-9ea6-150432c0a5d0.png)

Ugyanez a hiba megtalálható a Savsziget Old rang leírásában is.

![screenshot_20170930-215419](https://user-images.githubusercontent.com/25939300/31048975-08106262-a62a-11e7-8907-8a2bdeb95e98.png)

**Comment by Mousking** [comment]
Mégegyszer jobban megnéztem, ugyanez a hiba megtalálható a Pocket Edition Old rang leírásánál is.

/ptime - Saját időjárás változtatása. (jelenleg nem működik)

Itt is ugyanaz, időjárás helyett idő.

**Comment by Mousking** [comment]
A PC Survival szerverre vásárolható Tag+ rangnál is van elírás.

A plusz befogott petek a rang lejárata után is megmarad, és a váltás jog is.

Helyesen: A plusz befogott petek a rang lejárata után is megmaradnak, és a váltás jog is.

![screenshot_20170930-210912](https://user-images.githubusercontent.com/25939300/31048737-f91f028c-a623-11e7-8b23-49b1ea8c5bf6.png)

**Comment by Mousking** [comment]
A PC V.I.P. rang leírásában is elírás van:

/pweather - Eső ki/be kapcsolása saját magadnak.

Ha jól tudom a pweather nemcsak az esőt állítja el, hanem minden időjárást.
Helyesen: /pweather - Időjárás ki/be kapcsolása saját magadnak.

/petstore - aktív pet elmentése.
/pswitch - váltás a petek között.

Itt csak annyi lenne, hogy minden leírásnál a " - " után nagybetűvel van kezdve a mondat, kivéve ennél a kettőnél.

Színes írás táblára pl.:&2

A többi rangnál a kettőspont után ki van hagyva egy szóköz, itt nincs.
Helyesen: Színes írás táblára pl.: &2

![screenshot_20170930-211304](https://user-images.githubusercontent.com/25939300/31048888-11f69d7a-a628-11e7-9719-00ba7368325c.png)

**Comment by Mousking** [comment]
A PC Survival szerverre vehető 20 db. Nyálka idéző tojásnál másolás utáni hiba van.

Ezzel 20 db. Nyálka idéző tojást veszel a Survival szerverre.
Több információ a papagájokról: https://minecraft-hu.gamepedia.com/Ny%C3%A1lka


Nyálka vételnél a papagájokról tudhatunk meg több információt (a leírás szerint), viszont a link a jó helyre visz, ahol a Nyálkákról olvashatunk.
Helyesen:
Ezzel 20 db. Nyálka idéző tojást veszel a Survival szerverre.
Több információ a nyálkákról: https://minecraft-hu.gamepedia.com/Ny%C3%A1lka

![screenshot_20170930-215701](https://user-images.githubusercontent.com/25939300/31049033-1fa76cbc-a62b-11e7-8ca1-a16425b9f9a6.png)

A papagájok leírásánál is van egy hiba (talán nem hiba, viszont több lenne vele a tartalma a leírásnak, ha ott lenne).

Ezzel 20 db. Papagáj idéző tojást veszel a Survival szerverre.
Több információ a papagájokról: https://minecraft.gamepedia.com/Parrot

A többi szelidíthető állat leírásánál megtalálható az is, hogy mivel lehet szelidíteni, viszont a papagájnál ez nincs ott.

Valahogy így lehetne:

Ezzel 20 db. Papagáj idéző tojást veszel a Survival szerverre.
A papagájok magokkal szelidíthetőek meg.
Több információ a papagájokról: https://minecraft.gamepedia.com/Parrot

![screenshot_20170930-215750](https://user-images.githubusercontent.com/25939300/31049064-adbce284-a62b-11e7-8993-8cc7bac536b3.png)

**Comment by Mousking** [comment]
A PC Survival szerverre vehető járműveknél is van egy elírás.

Ezzel 1 db. Rószaszín Autót veszel a Survival szerverre.

Rózsaszín helyett Rószaszín van írva.
Helyesen:
Ezzel 1 db. Rózsaszín Autót veszel a Survival szerverre.

![screenshot_20170930-221405](https://user-images.githubusercontent.com/25939300/31049133-e768062a-a62c-11e7-8ffc-d528f2b6c769.png)

**Comment by Mousking** [comment]
A Savszigetre vásárolható Old Itemeknél is van elírás.

Ezzel 1 db. Old Csákányt (Gyengéd Érintés) veszel a Savsziget szerverre.

Ez egy Old-Ásóhoz van írva.
Helyesen:
Ezzel 1 db. Old-Ásót (Gyengéd Érintés) veszel a Savsziget szerverre.

![screenshot_20170930-223516](https://user-images.githubusercontent.com/25939300/31049270-2a528caa-a630-11e7-8aec-9d973fd294db.png)

Az Old-Csákánynál is van egy elírás.

Ezzel 1 db. Old Csákányt (Gyengéd Érintés) veszel a Savsziget szerverre.

Mindegyik Old Item leírásnál az Old és maga az Item között van egy kötőjel, csak itt nincs.
Helyesen:
Ezzel 1 db. Old-Csákányt (Gyengéd Érintés) veszel a Savsziget szerverre.

![screenshot_20170930-223801](https://user-images.githubusercontent.com/25939300/31049279-69d5c23e-a630-11e7-9c26-659a90bab321.png)

Az Old-Lábszárvédőnél is van egy elírás, Savsziget szerver helyett Szavsziget szerver van írva

Ezzel 1 db. Old-Lábszárvédőt veszel a Szavsziget szerverre.

Szavsziget --> Savsziget

![screenshot_20170930-223405](https://user-images.githubusercontent.com/25939300/31049286-a78bb3ae-a630-11e7-8143-bd70c5ae0020.png)

**Comment by Mousking** [comment]
A Savsziget szerverre vásárolható játékpénznél is van elírás.

Ezen menüpont alatt vásárolhatod meg a Savsziget szerverre szóló játékpénzt. (A termék jóváírása eltarthat pár percig)

Ez a szöveg a 75 000$-t 330 OCD-ért eladó itemre kattintva jön fel, míg a másik vásárolható pénznél a rendes szöveg ugrik fel.

![screenshot_20170930-224455](https://user-images.githubusercontent.com/25939300/31049333-5067e736-a631-11e7-9774-f4568f6ce49b.png)

![screenshot_20170930-224501](https://user-images.githubusercontent.com/25939300/31049335-5a93147e-a631-11e7-8cf9-e1684a494107.png)

**Comment by Mousking** [comment]
A Pocket Edition SkyPvP szerverre vásárolható rangok elírásai:

A Prémium rang le tudja hívni az orzo kitet, amihez nincs odaírva az Íj enchantja, csak annyi, hogy Erő.

Az íjon egyébként Erő III található.

![screenshot_20170930-225605](https://user-images.githubusercontent.com/25939300/31049436-6513d666-a633-11e7-9d69-50490daecf67.png)

Itt is megtalálható az Old rang jogok elírása.

/ptime day, night - Saját időjárás változtatása. (jelenleg nem működik)

Itt is az időjárás helyett idő kellene.

![screenshot_20170930-225644](https://user-images.githubusercontent.com/25939300/31049465-ec4474b0-a633-11e7-90d6-262b8e2b864e.png)

**Comment by Mousking** [comment]
A Pocket Edition SkyPvP Tárgy vételnél másolás utáni hiba van, Survival van odaírva

![screenshot_20170930-230704](https://user-images.githubusercontent.com/25939300/31049479-3a9811b2-a634-11e7-887a-1200e3aab886.png)

**Comment by Mousking** [comment]
A Pocket Edition SkyPvP szerverre való játékpénz vásárlás menüpontban a régi KitPvP szerver neve van írva, másolás utáni hibaként.

![screenshot_20170930-231037](https://user-images.githubusercontent.com/25939300/31049509-d08a7b92-a634-11e7-9a82-84964ce26813.png)

**Comment by Mousking** [comment]
Az OCD Feltöltés utalással menüpont elírásai:

Utalás esetén is dupla OCD jár az SMS-hez képest. Az utaláshoz nem szükséges bankszámla bármelyik bankban be lehet fizetni erre a számlaszámra készpénzt is.

Hiányzik egy vessző a bankszámla és a bármelyik szó közt.

Helyesen:
Utalás esetén is dupla OCD jár az SMS-hez képest. Az utaláshoz nem szükséges bankszámla, bármelyik bankban be lehet fizetni erre a számlaszámra készpénzt is.

A számlázási adatokat kitöltése kötelező még az utalás előtt!

adatokat --> adatok
Helyesen:
A számlázási adatok kitöltése kötelező még az utalás előtt!

![screenshot_20170930-231609](https://user-images.githubusercontent.com/25939300/31049554-c482e784-a635-11e7-9b4d-59d81145deac.png)

Ez nem biztos, hogy hiba, de lehet érthetőbb lenne:

Ha valaki szó szerint MineMarket Neved szöveget adja meg, akkor mi nem fogunk nyomozni az után ki küldte a támogatást.

Ha valaki szó szerint MineMarket Neved szöveget adja meg, akkor mi nem fogunk nyomozni az után, hogy ki küldte a támogatást.

![screenshot_20170930-231956](https://user-images.githubusercontent.com/25939300/31049581-53e78236-a636-11e7-9d0d-53770663a573.png)

**Comment by andris155** [comment]
A legtöbb javítva. 5080 OCD
