### ISSUE TITLE
PE LimitedCreative hiba

### ISSUE THREAD

**Issue by Mousking** [andris155/TheOld-Crafters#983]
A PE Survival szerveren Creative játékmódban le lehet tenni a Lapis és a Redstone érceket, illetve a Szén, a Lapis és a Redstone tömböket.

![screenshot_20171001-165129](https://user-images.githubusercontent.com/25939300/31055896-3918db46-a6ca-11e7-8de0-9a0908d0bd3c.png)

**Comment by andris155** [comment]
Mindent nem tilthatunk le. Ezek nem nagyon érnek sokat.
