### ISSUE TITLE
Moderátor plusz jog

### ISSUE THREAD

**Issue by rikmind** [andris155/TheOld-Crafters#985]
Survival szerverre moderátor rangtól jól jönne még egy jog. Ez pedig a /spawn játékosnév parancs lenne.
Ha valaki bent marad eventen, amikor nem kéne, akkor ezzel egyszerűbben ki lehetne vinni őket onnan, nem kéne személyesen elmenni a spawnra majd /tphere-el szórakozni. 
[Moderátor]rikmind

**Comment by andris155** [comment]
204 OCD
