### ISSUE TITLE
Járművek

### ISSUE THREAD

**Issue by poprundelHD** [andris155/TheOld-Crafters#987]
A járművekkel csak előre lehet menni, másmerre képtelenek mozdulni.

**Comment by andris155** [comment]
Szerintem tud a fejlesztő a hibáról.
![kepkivagas](https://user-images.githubusercontent.com/8324198/31317012-66b3a8b4-ac39-11e7-9fe0-ed60a0f2fcea.PNG)

**Comment by andris155** [comment]
Remélem hamarosan javítja.

**Comment by andris155** [comment]
Pedig azt hittem az 1.12.2-ben nincs semmi ilyen újítás. Fura.

**Comment by poprundelHD** [comment]
A hiba pontosan ma javítva lett.

**Comment by andris155** [comment]
Érdekes, hogy megoldódott az új szerverfájlal. Ritkán találkozni ilyennel. Általában mindig a plugin szokott hibás lenni.
