### ISSUE TITLE
Pokol, Vég

### ISSUE THREAD

**Issue by MrZero1** [andris155/TheOld-Crafters#988]
Szia Andris!

Több visszajelzés is érkezett, illetve én is úgy gondolom, hogy a pokolra és a végre egy resi ráférne. :D
Eléggé levan harcolva már mindkét világ, ha megoldható, egy előre bejelentett resi, némi időt hagyva míg az értékeiket elviszik onnan, mehetne.
Jó lenne ezt megbeszélni akár közösen is! 
Üdv

**Comment by andris155** [comment]
Sokaknak van ott építményük nem akarom azokat törölni. Át kellene helyezni inkább a teleport helyet a pokolban. A vég-ben nem tudom mit lehetne. :/ Illetve ha kell tudom nagyítani a világhatárt.
