### ISSUE TITLE
Fordítások OCD jutalomért.

### ISSUE THREAD

**Issue by andris155** [andris155/TheOld-Crafters#992]
Sziasztok!
Segítség kellene a fordításokban, hogy még több dolog lehessen magyar nyelvű a szerveren. Ezekért cserébe OCD-t tudok adni. Felraktam a meglévő fordításokat is. Ezeket használjátok az adott plugin-ál ha elérhető, hogy nagyjából azonos szavakat használjon a plugin. Ne pedig többet, hiszen a magyarban rengeteg olyan szó is van amire több szavunk is van. Plugin-onként pedig jobb ha ez egységes. A fordításokat, aki akarja fel is használhatja igazából csak örülök, ha ezzel tudtam segíteni még szervereknek is. De azért ha kérdezik ki fordította az eredeti fordító nevét említsétek meg. Minden segítséget nagyon szépen köszönünk.

Fordítás segítség:
Fájlok: https://github.com/andris155/TheOld-Crafters/tree/master/Ford%C3%ADt%C3%A1sok%20OCD%20jutalom%C3%A9rt
Ajánlott fordító program: Notepad++

Színkódok
A színkódokat általában & jellel és utána egy színkóddal jelölik. Ezeket a fordítás szerint lehet módosítani ha szükséges, de át színezni nem kell.

Változók
Ezeket általában két %% jel közé szokták rakni. A sorrendjét lehet módosítani átírni nem szabad. Kivenni pedig csak kivételes esetben lehet, ha úgy nem lehet megoldani normálisan a magyar fordítást.
Példa:
`wonMoney: " &2You won &1%reward%&2!"" ->     wonMoney: " &2Nyertél &1%reward%&2-t!"`

Tesztelés:
A Word-be átmásolással meg lehet találni a legtöbb hibát benne. Ezenkívül egy kis saját szervert is csak pár perc összedobni és azon lehet tesztelni az egészet.

2048:
- [x] lang fájl (Kronox12)
- [x] config fájl

Battleship:
- [x] lang fájl (Kronox12)
- [x] config fájl

ConnectFour:
- [x] lang fájl (Kronox12)
- [x] config fájl

CookieClicker
- [x] lang fájl (poma123)
- [x] config fájl (Paxel)

GameBox:
- [x] lang fájl (Kronox12)
- [x] config fájl (Paxel)

GameCrush:
- [x] lang fájl (Kronox12)
- [x] config fájl (Paxel)

Minesweeper:
- [x] lang fájl (Kronox12)
- [x] config fájl (Paxel)

Murder:
- [x] data fájl (gyzsombor6X)

Sudoku:
- [x] lang fájl (Kronox12)
- [x] config fájl (Paxel)

WhacAMole:
- [x] lang fájl (Kronox12)
- [x] config fájl (poma123)

**Comment by poma123** [comment]
CookieClicker
 lang fájl-t scinálom
