### ISSUE TITLE
Pc Surv. SF

### ISSUE THREAD

**Issue by Viktor1969TOC** [andris155/TheOld-Crafters#997]
SF-ben a Wither Assembler 30sec-enként spawnolja a withert (bele kell addagolni a cuclit) És az embernek
Nincs elég ideje megölni ezért egyfojtában 2-5 Wither él ami TILOS!

**Comment by andris155** [comment]
Igazából az i7 4790K-nak tök mind1 mennyi van. Majd eltörlöm a szabályt.

**Comment by andris155** [comment]
eltörölve

**Comment by andris155** [comment]
204 OCD
